### ISSUE TITLE
Jest does not work out of the box with @nrwl:workspace library

### ISSUE THREAD

**Issue by gregveres** [nrwl/nx#10042]
## Current Behavior
Follow the steps below and you will see that 

```
nx test lib
```

fails with the following error:
```
04-28 08:49:51 74> nx test common-store
Unexpected error:
TypeError: Cannot read properties of undefined (reading 'pluginsConfig')
    at C:\Users\Greg\source\plain-nx\skycourt\node_modules\@nrwl\jest\src\executors\jest\hasher.js:6:58
    at Generator.next (<anonymous>)
    at C:\Users\Greg\source\plain-nx\skycourt\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Greg\source\plain-nx\skycourt\node_modules\tslib\tslib.js:114:16)
    at run (C:\Users\Greg\source\plain-nx\skycourt\node_modules\@nrwl\jest\src\executors\jest\hasher.js:5:20)
    at TaskOrchestrator.<anonymous> (C:\Users\Greg\source\plain-nx\skycourt\node_modules\@nrwl\workspace\src\tasks-runner\task-orchestrator.js:309:19)
    at Generator.next (<anonymous>)
    at C:\Users\Greg\source\plain-nx\skycourt\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
```

This is crashing on line 6 of hasher.js. The line is:

```
const jestPluginConfig = context.workspaceConfig.pluginsConfig
            ? context.workspaceConfig.pluginsConfig['@nrwl/jest']
            : undefined;
```
what I am seeing is that context.workspaceConfig is undefined.

## Expected Behavior
I expected to be able to create a workspace and library and have jest work out of the box without any changes. 
I also have no idea how to get to a working state because I can't figure out how to get context.workspaceConfig defined.

## Steps to Reproduce
here are the commands I executed to reproduce this:
```
mkdir nx-problem
cd .\nx-problem\
npx create-nx-workspace@^13.0.0 --packageManager yarn
cd .\myorg\
yarn add @nrwl/cypress@^13.0.0 @nrwl/jest@^13.0.0 @nrwl/linter@^13.0.0 --dev
yarn nx g @nrwl/workspace:lib library
nx test library
```

during the nx create, I answered with myorg as the workspace name and then I selected empty as the preset.
When nx test library is run, the above error happens.
I am forced to stay on version 13 because of the nx-plus/vue plugin. I don't have the nx-plus plugin installed in this example. It fails without it so I didn't include it.

### Environment
```
04-28 09:22:35 12> nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   yarn : 1.22.17

   nx : 13.10.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.0.0
   @nrwl/eslint-plugin-nx : 13.0.0
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.3
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.0.0
   typescript : 4.3.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Hey @gregveres , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate 13.10.3`.  Alternatively, updating to latest with `nx migrate latest` would also work.
