### ISSUE TITLE
npx add-nx-to-monorepo fails with errno: -4058

### ISSUE THREAD

**Issue by rallz-dev** [nrwl/nx#10115]
## Current Behavior
Running `npx add-nx-to-monorepo` fails with code number -4058 claiming it cannot open packages.json
`Error: ENOENT: no such file or directory`

## Expected Behavior
Add Nx to your package.json.
Create nx.json, containing all the necessary configuration for Nx.

## Steps to Reproduce
Run `npx add-nx-to-monorepo` to a mono repo structure that does not contain a pre-existing packages.json
 
### Failure Logs
```
Error: ENOENT: no such file or directory, open 'C:\repos\bosch-ui\st-mono-bosch-ui\package.json'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at readJsonFile (C:\Users\mer2jvl\AppData\Roaming\npm-cache\_npx\5768\node_modules\add-nx-to-monorepo\src\add-nx-to-monorepo.js:154:44)
    at detectWorkspaceScope (C:\Users\mer2jvl\AppData\Roaming\npm-cache\_npx\5768\node_modules\add-nx-to-monorepo\src\add-nx-to-monorepo.js:157:17)
    at createNxJsonFile (C:\Users\mer2jvl\AppData\Roaming\npm-cache\_npx\5768\node_modules\add-nx-to-monorepo\src\add-nx-to-monorepo.js:166:19)
    at C:\Users\mer2jvl\AppData\Roaming\npm-cache\_npx\5768\node_modules\add-nx-to-monorepo\src\add-nx-to-monorepo.js:41:9
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\mer2jvl\AppData\Roaming\npm-cache\_npx\5768\node_modules\add-nx-to-monorepo\node_modules\tslib\tslib.js:115:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\repos\\bosch-ui\\st-mono-bosch-ui\\package.json'
}
```

### Environment
Node:
`$ node --version
v14.17.6`

NPM:
```
    $ npm version
    {
        npm: '6.14.15',
        ares: '1.17.2',
        brotli: '1.0.9',
        cldr: '39.0',
        icu: '69.1',
        llhttp: '2.1.3',
        modules: '83',
        napi: '8',
        nghttp2: '1.42.0',
        node: '14.17.6',
        openssl: '1.1.1l',
        tz: '2021a',
        unicode: '13.0',
        uv: '1.41.0',
        v8: '8.4.371.23-node.76',
        zlib: '1.2.11'
    }
```

Nx Report:
`$ nx report

 >  NX   The current directory isn't part of an Nx workspace.

   To create a workspace run:
   npx create-nx-workspace@latest <workspace name>

 >  NX   For more information please visit https://nx.dev/`

**Comment by FrozenPandaz** [comment]
Could you please provide a repo as an example?

Is this not a `js/ts` repo?
