### ISSUE TITLE
Skip Import broken

### ISSUE THREAD

**Issue by bopm** [nrwl/nx#10133]
## Current Behavior

```
nx g component menu --project=chat
Error: More than one module matches. Use the '--skip-import' option to skip importing the component into the closest module or use the module option to specify a module.
    at findModule (...node_modules/@schematics/angular/utility/find-module.js:67:19)
    at findModuleFromOptions (...node_modules/@schematics/angular/utility/find-module.js:26:38)
    at ...node_modules/@schematics/angular/component/index.js:109:66
More than one module matches. Use the '--skip-import' option to skip importing the component into the closest module or use the module option to specify a module.
nx g component menu --project=chat --skip-import
'skipImport' is not found in schema
```
## Expected Behavior
It was working before. Around version 13.

## Steps to Reproduce
It's self-describing.

### Environment
```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   yarn : 1.22.18

   nx : 14.1.1
   @nrwl/angular : 14.1.1
   @nrwl/cypress : 14.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.1
   @nrwl/eslint-plugin-nx : 14.1.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.1
   @nrwl/js : 14.1.1
   @nrwl/linter : 14.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.1
   @nrwl/web : 14.1.1
   @nrwl/workspace : 14.1.1
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
   	 @ionic/angular: 5.9.3
   	 @ngrx/component-store: 13.0.2
   	 @ngrx/effects: 13.0.2
   	 @ngrx/entity: 13.0.2
   	 @ngrx/router-store: 13.0.2
   	 @ngrx/store: 13.0.2
   	 @ngrx/schematics: 13.0.2
   	 @ngrx/store-devtools: 13.0.2
   	 @nxtend/capacitor: 13.0.0
   	 @nxtend/ionic-angular: 13.0.0
   	 ngx-tailwind: 3.0.0

(node:10810) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/sergeymoiseev/Toptal/tripleagent/askari/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by Benja1512** [comment]
ng generate @schematics/angular:component --name=banner --project=ui --style=scss --export --prefix=ui --selector=banner --skip-import
