### ISSUE TITLE
"Error: Cannot find module" for monorepo package during development restart (NestJS/Node executor)

### ISSUE THREAD

**Issue by Nick-Lucas** [nrwl/nx#10210]
## Current Behavior

I have a NestJS API with several other monorepo packages being imported. During development the build is fine, and making changes to files causes a code rebuild/restart as expected, but only around 3 times. After a few rebuilds I get the following error:

```
chunk (runtime: main) main.js (main) 42.9 KiB [entry]
webpack compiled successfully (0dd51bf7be1c6432)
Debugger listening on ws://localhost:9229/92490c46-aeeb-462f-b936-4d7a89294eb7
For help, see: https://nodejs.org/en/docs/inspector

/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/packages/api/src/app/admin/users/users.service.ts:5
import {
^
Error: Cannot find module '@inventory/okta-management-types'
    at webpackMissingModule (/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/packages/api/src/app/admin/users/users.service.ts:5:1)
    at Object../packages/api/src/app/admin/users/users.service.ts (/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/packages/api/src/app/admin/users/users.service.ts:5:1)
    at __webpack_require__ (/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/webpack/bootstrap:19:1)
    at Object../packages/api/src/app/admin/users/users.module.ts (/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/packages/api/src/app/admin/users/users.module.ts:3:1)
    at __webpack_require__ (/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/webpack/bootstrap:19:1)
    at Object../packages/api/src/app/admin/admin.module.ts (/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/packages/api/src/app/admin/admin.module.ts:3:1)
    at __webpack_require__ (/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/webpack/bootstrap:19:1)
    at Object../packages/api/src/app/app.module.ts (/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/packages/api/src/app/app.module.ts:3:1)
    at __webpack_require__ (/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/webpack/bootstrap:19:1)
    at Object../packages/api/src/createApi.ts (/home/n_lucas/dev/inventory/dist/packages/api/webpack:/inventory/packages/api/src/createApi.ts:6:1)
```

The only way to resolve this is to exit the process and start it again.

The project graph looks like this:

![image](https://user-images.githubusercontent.com/8896153/167399653-1acb79a9-a470-4ed7-b3b5-d28b53cb0936.png)

The projects are:

api: @nrwl/nestjs:app
api-types: @nrwl/web:lib
okta-management: @nrwl/node:lib
okta-management-types: @nrwl/web:lib

It's unclear to me how I can debug or reproduce this. It seems to be some bad state which webpack gets itself into, perhaps a race condition, but beyond that I haven't been able to find anything matching this problem in past issues or google.

### Environment

```
   Node : 14.19.0
   OS   : linux x64
   yarn : 1.22.17
   
   nx : 13.9.7
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.7
   @nrwl/eslint-plugin-nx : 13.9.7
   @nrwl/express : Not Found
   @nrwl/jest : 13.9.7
   @nrwl/js : 13.9.7
   @nrwl/linter : 13.9.7
   @nrwl/nest : 13.9.7
   @nrwl/next : Not Found
   @nrwl/node : 13.9.7
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.7
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.7
   @nrwl/web : 13.9.7
   @nrwl/workspace : 13.9.7
   typescript : 4.5.5
   rxjs : 7.5.5
```

**Comment by vyarmak** [comment]
Bumped on somewhat similar situation after updating NX. adding 

```
"noResolve": false
```

to compiler options helped. Maybe there was some change in defaults. IDK. Was not digging deep on it.

**Comment by Nick-Lucas** [comment]
Thanks for this! 

We just moved to new machines at work and weirdly the issue is now gone. Probably something in my old environment was hanging around even after resetting the Nx cache and removing dist. 

Hopefully between your suggestion and this experience, anyone coming in from Google can figure out a solution
