### ISSUE TITLE
PNPM package manager support

### ISSUE THREAD

**Issue by bohushvitali** [nrwl/nx#1022]
## Expected Behavior

Code linting should work with PNPM package manager

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Ranning nx lint or ng lint commands with "node_modules/@nrwl/schematics/src/tslint" in tslint.json rulesDirectory cause failure

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. generate Angular application in NX Workspace
1. remove node_modules
2. install dependencies using PNPM package manager with flag --shamefully-flatten
2. ensure latest version installed npm-check-updates --upgrade
3. run nx lint or ng lint

### Context

Please provide any relevant information about your setup:

tslint.json
```
"rulesDirectory": [
    "node_modules/codelyzer",
    "node_modules/@nrwl/schematics/src/tslint"
],
```

ng lint -> failed 
nx lint -> failed 
```
"rulesDirectory": [
    "node_modules/codelyzer"
],
```
ng lint -> pass with nx-enforce-module-boundaries absence complain
nx lint -> failed 

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

nx lint
```
E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\yargs\11.1.0\node_modules\yargs\yargs.js:1133
      else throw err
           ^

Error: ENOENT: no such file or directory, open 'E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@nrwl\schematics\7.4.1\node_modules\@nrwl\schematics\src\command-line/angular.json'
    at Object.openSync (fs.js:449:3)
    at Object.readFileSync (fs.js:349:35)
    at Object.readJsonFile (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@nrwl\schematics\7.4.1\node_modules\@nrwl\schematics\src\utils\fileutils.js:59:26)
    at Object.readAngularJson (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@nrwl\schematics\7.4.1\node_modules\@nrwl\schematics\src\command-line\shared.js:218:24)
    at Object.lint (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@nrwl\schematics\7.4.1\node_modules\@nrwl\schematics\src\command-line\lint.js:9:51)
    at Object.handler (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@nrwl\schematics\7.4.1\node_modules\@nrwl\schematics\src\command-line\nx.js:54:19)
    at Object.runCommand (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\yargs\11.1.0\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\yargs\11.1.0\node_modules\yargs\yargs.js:1046:30)
    at Object.get [as argv] (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\yargs\11.1.0\node_modules\yargs\yargs.js:989:21)
    at Object.<anonymous> (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@nrwl\schematics\7.4.1\node_modules\@nrwl\schematics\src\command-line\nx.js:71:21)
```

ng lint
```
Linting "libs"...
ENOENT: no such file or directory, open 'E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@angular\cli\7.2.2\node_modules\@angular\cli\bin/angular.json'
Error: ENOENT: no such file or directory, open 'E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@angular\cli\7.2.2\node_modules\@angular\cli\bin/angular.json'
    at Object.openSync (fs.js:449:3)
    at Object.readFileSync (fs.js:349:35)
    at Object.readJsonFile (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@nrwl\schematics\7.4.1\node_modules\@nrwl\schematics\src\utils\fileutils.js:59:26)
    at Object.readAngularJson (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@nrwl\schematics\7.4.1\node_modules\@nrwl\schematics\src\command-line\shared.js:218:24)
    at new Rule (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@nrwl\schematics\7.4.1\node_modules\@nrwl\schematics\src\tslint\nxEnforceModuleBoundariesRule.js:44:44)
    at Object.loadRules (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\tslint\5.12.1\node_modules\tslint\lib\ruleLoader.js:46:24)
    at Linter.getEnabledRules (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\tslint\5.12.1\node_modules\tslint\lib\linter.js:226:29)
    at Linter.lint (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\tslint\5.12.1\node_modules\tslint\lib\linter.js:104:33)
    at lint (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@angular-devkit\build-angular\0.12.2\node_modules\@angular-devkit\build-angular\src\tslint\index.js:132:20)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (E:\workspace\projects\sandbox\sources\frontend\node_modules\.registry.npmjs.org\@angular-devkit\build-angular\0.12.2\node_modules\@angular-devkit\build-angular\src\tslint\index.js:61:37)
```
## Other

Relevant issue https://github.com/angular/angular-cli/issues/13304

**Comment by bogushvitaly** [comment]
nx dep-graph produce the same error

**Comment by bogushvitaly** [comment]
Direct call working

"dep-graph": "node node_modules/.registry.npmjs.org/@nrwl/schematics/7.4.1/node_modules/@nrwl/schematics/src/command-line/nx.js dep-graph --all --file=index.html",
