### ISSUE TITLE
nx generate component can not --skip-import

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#10242]
## Current Behavior
```
  nx g c form-mutually-exclusive-attrs                                     
```
error:
```
Error: Could not find an NgModule. Use the '--skip-import' option to skip importing in NgModule.
    at findModule (.../node_modules/@schematics/angular/utility/find-module.js:76:11)
    at findModuleFromOptions (.../node_modules/@schematics/angular/utility/find-module.js:25:38)
    at .../node_modules/@schematics/angular/component/index.js:104:66
Could not find an NgModule. Use the '--skip-import' option to skip importing in NgModule.
```
okay, let's use the '--skip-import':
```
 nx g c form-mutually-exclusive-attrs --skip-import
```
but:
```
'skipImport' is not found in schema
```
😐
## Expected Behavior
Component should be generated without importing it to the module (I have no NgModules in this library).

## Steps to Reproduce
Your app or library should not have modules (library is much easier to create without modules).

### Environment

<details>
<summary>NX  Report</summary>

```bash

   Node : 18.1.0
   OS   : darwin arm64
   npm  : 8.9.0
   nx : 14.1.4
   @nrwl/angular : 14.1.4
   @nrwl/cypress : 14.1.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.1.3
   @nrwl/eslint-plugin-nx : 14.1.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.4
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.4
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.4
   typescript : 4.7.0-dev.20220506
   rxjs : 8.0.0-alpha.3
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 13.2.0
         @ngrx/effects: 13.2.0
         @jefiozie/ngx-aws-deploy: 4.1.0

```
</details>

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This issue has been fixed in https://github.com/nrwl/nx/pull/10167 and it should be released soon. Please keep an eye on the releases to get the fix.
