### ISSUE TITLE
App fails to build when another app has stylePreprocessorOptions includesPath

### ISSUE THREAD

**Issue by Plysepter** [nrwl/nx#103]
I am migrating our applications over from CLI projects and one of our apps leverages
 ` "stylePreprocessorOptions": {
                "includePaths": [
                    "../../user-dashboard/src/styles"
                ]
            },`
as part of its app config in .angular-cli.json. This works when we build the app (app 0), however when we go to build app 1, we see this in our console:

```
> ERROR in Error: Child compilation failed:
Module build failed: 
@import "theme";
^
      File to import not found or unreadable: theme.
Parent style sheet: stdin
      in /Users/user/Projects/workspace/apps/app0/src/app/+login/login.component.scss (line 1, column 1):
Error: 
@import "theme";
^
      File to import not found or unreadable: theme.
Parent style sheet: stdin
      in /Users/user/Projects/workspace/apps/app0/src/app/+login/login.component.scss (line 1, column 1)
    at childCompiler.runAsChild (/Users/user/Projects/workspace/apps/node_modules/@ngtools/webpack/src/resource_loader.js:53:28)
    at compile (/Users/user/Projects/workspace/apps/node_modules/webpack/lib/Compiler.js:304:11)
    at applyPluginsAsync.err (/Users/user/Projects/workspace/apps/node_modules/webpack/lib/Compiler.js:514:14)
    at next (/Users/user/Projects/workspace/apps/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/Users/user/Projects/workspace/apps/node_modules/webpack/lib/CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (/Users/user/Projects/workspace/apps/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/Users/user/Projects/workspace/apps/node_modules/webpack/lib/Compiler.js:511:11)
    at Compilation.applyPluginsAsyncSeries (/Users/user/Projects/workspace/apps/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/Users/user/Projects/workspace/apps/node_modules/webpack/lib/Compilation.js:680:19)
    at Compilation.applyPluginsAsyncSeries (/Users/user/Projects/workspace/apps/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/Users/user/Projects/workspace/apps/node_modules/webpack/lib/Compilation.js:671:11)
    at Compilation.applyPluginsAsyncSeries (/Users/user/Projects/workspace/apps/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/Users/user/Projects/workspace/apps/node_modules/webpack/lib/Compilation.js:666:10)
    at Compilation.applyPluginsAsyncSeries (/Users/user/Projects/workspace/apps/node_modules/tapable/lib/Tapable.js:195:46)
    at sealPart2 (/Users/user/Projects/workspace/apps/node_modules/webpack/lib/Compilation.js:662:9)
    at Compilation.applyPluginsAsyncSeries (/Users/user/Projects/workspace/apps/node_modules/tapable/lib/Tapable.js:195:46)
```

The trouble is that app 1 has no dependancies for app 0's style sheets, however when building app 1 it fails to build due to this. If there are any alternatives in the meantime I would greatly appreciate the help!

OS: macOS (High Sierra)
Node: 8.7.0
Angular CLI: 1.5.0
NX: 0.1.1

**Comment by vsavkin** [comment]
Could you provide a repro?

**Comment by Plysepter** [comment]
Sorry for the late response. I ended up being able to solve this by migrating our apps to a new nx workspace based on v0.3.0. I have yet to be able to recreate the issue on the latest version so I believe that this issue is resolved.

**Comment by panay** [comment]
I have the same problem. What need doing?
