### ISSUE TITLE
npx add-nx-to-monorepo Request failed with status code 500

### ISSUE THREAD

**Issue by StevenMatchett** [nrwl/nx#10323]
## Current Behavior
Can not run npx add-nx-to-monorepo without throwing an error

## Steps to Reproduce
````
git clone git@github.com:StevenMatchett/sample-monorepo.git
cd sample-monorepo
npm i
npx add-nx-to-monorepo

````

### Failure Logs
````
❯  npx add-nx-to-monorepo

 >  NX   🐳 Nx initialization

✔ Use Nx Cloud? (It's free and doesn't require registration.) · Yes

 >  NX   🧑‍🔧 Analyzing the source code and creating configuration file


 >  NX   📦 Installing dependencies

yarn install v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.28s.
yarn run v1.22.4
$ /Users/stevenmatchett/rdc/sample-monorepo/node_modules/.bin/nx g @nrwl/nx-cloud:init
Request failed with status code 500
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn nx g @nrwl/nx-cloud:init
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:902:15)
    at initCloud (/Users/stevenmatchett/.npm/_npx/dcff4b037c44fe4f/node_modules/add-nx-to-monorepo/src/add-nx-to-monorepo.js:264:34)
    at /Users/stevenmatchett/.npm/_npx/dcff4b037c44fe4f/node_modules/add-nx-to-monorepo/src/add-nx-to-monorepo.js:46:13
    at Generator.next (<anonymous>)
    at fulfilled (/Users/stevenmatchett/.npm/_npx/dcff4b037c44fe4f/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 97414,
  stdout: null,
  stderr: null
}
````

### Environment
node version 16

**Comment by StalkAltan** [comment]
Hi @StevenMatchett, thanks for reporting this! The issue should be resolved now, apologies for any inconvenience. I tested against your sample repository, but let me know if you have any further issues.

**Comment by StevenMatchett** [comment]
Worked thank you!

**Comment by kaleprakash** [comment]
I am facing the same issue. Can we get the resolution?
