### ISSUE TITLE
v14 Migration error

### ISSUE THREAD

**Issue by plusplushq** [nrwl/nx#10424]
## Current Behavior
When migrating to nx v14 latest, experiencing error with the following output shown down in Failure Logs

## Expected Behavior
Migration completes without errors

## Steps to Reproduce
`npx nx migrate latest`
`yarn`
`npx nx migrate --run-migrations --verbose`

 (also tried `yarn nx ...` instead for those with same result)

### Failure Logs
```
❯ npx nx migrate --run-migrations --verbose

>  NX  Running 'yarn' to make sure necessary packages are installed

yarn install v1.22.17
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.07s.

>  NX  Running migrations from 'migrations.json'

Running migration 14-0-6-remove-root
The "path" argument must be of type string or an instance of Buffer or URL. Received null
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at Object.openSync (node:fs:577:10)
    at readFileSync (node:fs:453:35)
    at readJsonFile (/dirname/node_modules/nx/src/utils/fileutils.js:16:43)
    at /dirname/node_modules/nx/src/commands/migrate.js:538:57
    at Generator.next (<anonymous>)
    at /dirname/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/dirname/node_modules/tslib/tslib.js:113:16)
    at runNxMigration (/dirname/node_modules/nx/src/commands/migrate.js:536:34)
    at /dirname/node_modules/nx/src/commands/migrate.js:518:27
```

### Environment

MacOS BigSur / Node 16

❯ yarn nx report
yarn run v1.22.17
$ /Users/happyfamily/code/digital-garden/node_modules/.bin/nx report
Cannot find module '@nrwl/workspace/src/utilities/perf-logging'
Require stack:
- /Users/happyfamily/code/digital-garden/node_modules/nx/src/cli/init-local.js
- /Users/happyfamily/code/digital-garden/node_modules/nx/bin/nx.js
- /Users/happyfamily/code/digital-garden/node_modules/@nrwl/cli/node_modules/nx/bin/nx.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by plusplushq** [comment]
The issue resolved when after running `yarn nx migrate latest` and before running `yarn`, I deleted my node_modules. 
So the issue seemed to be that running `yarn` on top of the existing node_modules didn't install properly. 
I'll close the issue then :)
