### ISSUE TITLE
Can't install create-nx-workspace@4.1.8

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#10462]
> npm i -g create-nx-workspace@4.1.8

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for create-nx-workspace@4.1.8.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

<details>
<summary>Log</summary>

```
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@8.10.0
2 info using node@v18.2.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/oz/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 4ms
18 timing npm:load:configload Completed in 4ms
19 timing npm:load:mkdirpcache Completed in 2ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm i create-nx-workspace@4.1.8
22 verbose argv "i" "--global" "create-nx-workspace@4.1.8"
23 timing npm:load:setTitle Completed in 5ms
24 timing config:load:flatten Completed in 1ms
25 timing npm:load:display Completed in 2ms
26 verbose logfile logs-max:10 dir:/Users/oz/.npm/_logs
27 verbose logfile /Users/oz/.npm/_logs/2022-05-24T21_18_20_022Z-debug-0.log
28 timing npm:load:logFile Completed in 3ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 16ms
32 timing arborist:ctor Completed in 0ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 2ms
36 timing idealTree:userRequests Completed in 2ms
37 silly idealTree buildDeps
38 silly fetch manifest create-nx-workspace@4.1.8
39 http fetch GET 200 https://registry.npmjs.org/create-nx-workspace 8ms (cache hit)
40 silly placeDep ROOT create-nx-workspace@ OK for:  want: 4.1.8
41 timing idealTree:#root Completed in 14ms
42 timing idealTree:node_modules/create-nx-workspace Completed in 0ms
43 timing idealTree:buildDeps Completed in 15ms
44 timing idealTree:fixDepFlags Completed in 0ms
45 timing idealTree Completed in 19ms
46 timing command:i Completed in 22ms
47 verbose type version
48 verbose stack create-nx-workspace: No matching version found for create-nx-workspace@4.1.8.
48 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
48 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:126:26
48 verbose stack     at async [nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1108:19)
48 verbose stack     at async [buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:976:11)
48 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
48 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
48 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:156:5)
48 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
49 verbose cwd /Users/oz
50 verbose Darwin 21.5.0
51 verbose node v18.2.0
52 verbose npm  v8.10.0
53 error code ETARGET
54 error notarget No matching version found for create-nx-workspace@4.1.8.
55 error notarget In most cases you or one of your dependencies are requesting
55 error notarget a package version that doesn't exist.
56 verbose exit 1
57 timing npm Completed in 76ms
58 verbose unfinished npm timer reify 1653427100074
59 verbose unfinished npm timer reify:loadTrees 1653427100076
60 verbose code 1
```

</details>

But NPM says that latest version is 4.1.8:
https://www.npmjs.com/package/create-nx-workspace

**Comment by nartc** [comment]
The latest version is 14.1.18 on npm for me. Can you double check?
