### ISSUE TITLE
Add additional webpack configuration to withModuleFederation plugin

### ISSUE THREAD

**Issue by sscotth** [nrwl/nx#10485]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@nrwl/react@14.1.9` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@nrwl/react/src/module-federation/models.d.ts b/node_modules/@nrwl/react/src/module-federation/models.d.ts
index d42a01a..a91e14e 100644
--- a/node_modules/@nrwl/react/src/module-federation/models.d.ts
+++ b/node_modules/@nrwl/react/src/module-federation/models.d.ts
@@ -21,4 +21,5 @@ export interface ModuleFederationConfig {
     exposes?: Record<string, string>;
     shared?: SharedFunction;
     additionalShared?: AdditionalSharedConfig;
+    webpackConfig?: any;
 }
diff --git a/node_modules/@nrwl/react/src/module-federation/with-module-federation.js b/node_modules/@nrwl/react/src/module-federation/with-module-federation.js
index c0d371c..4961b43 100644
--- a/node_modules/@nrwl/react/src/module-federation/with-module-federation.js
+++ b/node_modules/@nrwl/react/src/module-federation/with-module-federation.js
@@ -9,6 +9,7 @@ const file_utils_1 = require("nx/src/project-graph/file-utils");
 const package_json_1 = require("./package-json");
 const path_1 = require("path");
 const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
+const webpackMerge = require('webpack-merge');
 function collectDependencies(projectGraph, name, dependencies = {
     workspaceLibraries: new Set(),
     npmPackages: new Set(),
@@ -187,7 +188,7 @@ function withModuleFederation(options) {
                 remotes: mappedRemotes,
                 shared: Object.assign({}, sharedDependencies),
             }), sharedLibraries.getReplacementPlugin());
-            return config;
+            return options.webpackConfig ? webpackMerge.merge(config, options.webpackConfig) : config;
         };
     });
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by AgentEnder** [comment]
withModuleFederation returns a webpack config, so you should be able to use webpack-merge in your webpackage.config.js file to extend it already, without the need for us adding custom handling. 

Is this not working currently?

**Comment by akhilsreenivasan** [comment]
webpack-merge won't handle promise and tried to implement  `module.exports = async (webpackConfig) => {
    return (await withModuleFederation(config))({
        ...webpackConfig,
        output: {
            ...webpackConfig.output,
            scriptType: 'text/javascript'
        }
    });
};`
but no luck async exports are not working and host server is not getting started

**Comment by sscotth** [comment]
@AgentEnder  No, it doesn't work

https://github.com/sscotth/nxdemo/blob/main/apps/shop/webpack.config.js

```
originalOnListen is not a function
TypeError: originalOnListen is not a function
    at devServerConfig.onListening (.../node_modules/@nrwl/web/src/utils/run-webpack.js:48:13)
    at Server.start (.../webpack-dev-server/lib/Server.js:3245:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jrfornes** [comment]
This is working for me. Using NX 14.3.0.

```
const { withModuleFederation } = require('@nrwl/angular/module-federation');
const config = require('./module-federation.config');

module.exports = withModuleFederation(config).then((fn) =>
  fn({
    module: {
      rules: [
        {
          test: /\.html$/,
          exclude: /node_modules/,
          include: [
            require('path').resolve(__dirname, 'src/app/legacy/ractive/templates'),
          ],
          loader: 'ractive-component-loader',
        },
      ],
    },
  })
);
```

**Comment by codrin-iftimie** [comment]
Docs here a bit wrong. https://nx.dev/guides/customize-webpack
While checking the `withModuleFederation` source code I noticed that a promise is needed to be set as the export...
```js
const withModuleFederation = require('@nrwl/react/module-federation');
const moduleFederationConfig = require('./module-federation.config');

const federatedWebpack = withModuleFederation({
  ...moduleFederationConfig,
})

module.exports = new Promise((resolve) => {
  federatedWebpack.then(fn => {
    resolve((config) => {
      config.module.rules.push({
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'dts-loader',
              options: {
                ...moduleFederationConfig,
              },
            },
          ],
      });
      return fn(config);
    })
  })
})
```
Initially I was trying to get this working:
```js
module.exports = async(config) => {
  (await federatedWebpack)(config)
}
```

**Comment by LongLiveCHIEF** [comment]
I remember having the same issue with the normal federated modules webpack plugin, until the author made a patch in the plugin to support async. (this happened just before that plugin was merged to core webpack)  Guessing it is the exact same thing here. Just can't find the issue and subsequent PR that fixed this.

**Comment by LongLiveCHIEF** [comment]
This will be the simplest way to merge config in the meantime:

```js
const withModuleFederation = require('@nrwl/react/module-federation');
const moduleFederationConfig = require('./module-federation.config');
const { merge } = require('webpack-merge');

const federatedModules = async () => withModuleFederation({ ...moduleFederationConfig })

module.exports = async (config, context) => {
  const federatedModuleConfig = await federatedModules();
  return merge(federatedModuleConfig(config), {
    module: {
      //...module configs
    },
    resolve: {
      //... resolve configs
    }
  })
}
```

**Comment by sscotth** [comment]
@LongLiveCHIEF I'm confused, is your solution supposed to work as is?

https://github.com/sscotth/nxdemo/commit/c64033231aabc5efe4da9ea9ed734778b34246e4

```
❯ npx nx serve shop --verbose

> nx run shop:serve:development --verbose=true

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
...

 >  NX   originalOnListen is not a function


TypeError: originalOnListen is not a function
    at devServerConfig.onListening (/.../nxdemo/node_modules/@nrwl/web/src/utils/run-webpack.js:48:13)
    at Server.start (/.../nxdemo/node_modules/webpack-dev-server/lib/Server.js:3242:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "shop:serve" failed

   Failed tasks:

   - shop:serve:development

   Hint: run the command with --verbose for more details.

```

**Comment by LongLiveCHIEF** [comment]
@sscotth you have to actually add the webpack configs you want to merge where i have `//...` comments

**Comment by sscotth** [comment]
@LongLiveCHIEF Empty objects are valid for `webpack-merge`

Like this?

```js
const withModuleFederation = require('@nrwl/react/module-federation');
const moduleFederationConfig = require('./module-federation.config');
const { merge } = require('webpack-merge');
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin');

const federatedModules = async () =>
  withModuleFederation({ ...moduleFederationConfig });

module.exports = async (config, context) => {
  const federatedModuleConfig = await federatedModules();
  return merge(federatedModuleConfig(config), {
    plugins: [new NodePolyfillPlugin()],
  });
};
```

**Comment by cjones26** [comment]
> @LongLiveCHIEF I'm confused, is your solution supposed to work as is?
> 
> [sscotth/nxdemo@c640332](https://github.com/sscotth/nxdemo/commit/c64033231aabc5efe4da9ea9ed734778b34246e4)
> 
> ```
> ❯ npx nx serve shop --verbose
> 
> > nx run shop:serve:development --verbose=true
> 
> <i> [webpack-dev-server] Project is running at:
> <i> [webpack-dev-server] Loopback: http://localhost:8080/
> ...
> 
>  >  NX   originalOnListen is not a function
> 
> 
> TypeError: originalOnListen is not a function
>     at devServerConfig.onListening (/.../nxdemo/node_modules/@nrwl/web/src/utils/run-webpack.js:48:13)
>     at Server.start (/.../nxdemo/node_modules/webpack-dev-server/lib/Server.js:3242:20)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
>  —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
> 
>  >  NX   Running target "shop:serve" failed
> 
>    Failed tasks:
> 
>    - shop:serve:development
> 
>    Hint: run the command with --verbose for more details.
> ```

I'm also seeing this EXACT same thing:

```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://172.31.5.213:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/charlesjones/Work/web/public' directory

 >  NX   originalOnListen is not a function


TypeError: originalOnListen is not a function
    at Object.devServerConfig.onListening (/Users/charlesjones/Work/web/node_modules/@nrwl/web/src/utils/run-webpack.js:48:13)
    at Server.start (/Users/charlesjones/Work/web/node_modules/@nrwl/web/node_modules/webpack-dev-server/lib/Server.js:3242:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "web:serve" failed

   Failed tasks:

   -web:serve:development

   Hint: run the command with --verbose for more details.
```

**Comment by cjones26** [comment]
This actually appears to be a problem with `webpack-merge`, as it appears to be breaking the `onListening` function.  Here's a test custom webpack config:

```
const { merge } = require('webpack-merge');

module.exports = async (config, context) => {
  console.log('onListening: ', config.devServer.onListening.toString());
  
  console.log(
    'onListening post merge: ',
    merge(config, {
      devServer: config.devServer,
    }).devServer.onListening.toString()
  );

  return merge(config, {
    devServer: config.devServer,
  });
};
```

And the output:

```
~/Work/nx-test (main ✗) npx nx run web:serve:development

> nx run web:serve:development

onListening:  onListening(server) {
            devkit_1.logger.info(`NX Web Development Server is listening at ${server.options.https ? 'https' : 'http'}://${server.options.host}:${server.options.port}${(0, serve_path_1.buildServePath)(buildOptions)}`);
        }
onListening post merge:  function () {
                var args = [];
                for (var _i = 0; _i < arguments.length; _i++) {
                    args[_i] = arguments[_i];
                }
                return _joinArrays(a.apply(void 0, __spreadArray([], __read(args))), b.apply(void 0, __spreadArray([], __read(args))), k);
            }
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://172.31.5.213:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/charlesjones/Work/nx-test/public' directory

 >  NX   originalOnListen is not a function

   Pass --verbose to see the stacktrace.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "web:serve" failed

   Failed tasks:

   - web:serve:development

   Hint: run the command with --verbose for more details.
```

**Comment by sscotth** [comment]
@cjones26 

It's not just `webpack-merge`. The below example, based on [LongLiveCHIEF](https://github.com/LongLiveCHIEF)'s solution also fails with the same error:

```js
const withModuleFederation = require('@nrwl/react/module-federation');
const moduleFederationConfig = require('./module-federation.config');

const federatedModules = async () =>
  withModuleFederation({ ...moduleFederationConfig });

module.exports = async (config, context) => {
  const federatedModuleConfig = await federatedModules();
  return federatedModuleConfig;
};

```

**Comment by cjones26** [comment]
@sscotth good point.  This is kind of a blocker for us to even evaluate migrating to Nx which is a huge bummer :(.

**Comment by sscotth** [comment]
> @sscotth good point. This is kind of a blocker for us to even evaluate migrating to Nx which is a huge bummer :(.

@cjones26 [@codrin-iftimie's Solution](https://github.com/nrwl/nx/issues/10485#issuecomment-1190375885) is working for me right now in the mean time.

```js
const withModuleFederation = require('@nrwl/react/module-federation');
const moduleFederationConfig = require('./module-federation.config');
const { merge } = require('webpack-merge');
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin');

const federatedWebpack = withModuleFederation({
  ...moduleFederationConfig,
});

const polyfillConfig = {
  plugins: [new NodePolyfillPlugin()],
};

module.exports = new Promise((resolve) =>
  federatedWebpack.then((fn) => {
    resolve((config) => fn(merge(config, polyfillConfig)));
  })
);
```

**Comment by jaysoo** [comment]
There is a bug where you cannot actually export an async function.

```js
module.exports = async (config) => config;
```

You can, however export a promise of the `config -> config` function.

```js
module.exports = Promise.resolve((config, context) => {
  return config;
});
```

That is why the solution [here](https://github.com/nrwl/nx/issues/10485#issuecomment-1190375885) from @codrin-iftimie works.

You can simply it a bit as:

```js
const withModuleFederation = require('@nrwl/react/module-federation');
const moduleFederationConfig = require('./module-federation.config');

module.exports = withModuleFederation({
  ...moduleFederationConfig,
}).then((fromModuleFederation) => {
  return (config, context) => {
    config = fromModuleFederation(config, context);

    // update config here...

    return config;
  }
});
```

Once we land the fix in the next patch release, you can properly use the async function like:

```js
const withModuleFederation = require('@nrwl/react/module-federation');
const moduleFederationConfig = require('./module-federation.config');

module.exports = async (config, context) => {
  const fromModuleFederation = await withModuleFederation({
    ...moduleFederationConfig,
  });

  config = fromModuleFederation(config, context);

  // update config here...

  return config;
};
```

**Comment by quicksilverr** [comment]
Hey guys, were any of you facing this error? 

```
ERROR in external "//localhost:4201/remoteEntry.js"
The target environment doesn't support EcmaScriptModule syntax so it's not possible to use external type 'module'

```

**Comment by LongLiveCHIEF** [comment]
> Hey guys, were any of you facing this error?
> 
> ```
> ERROR in external "//localhost:4201/remoteEntry.js"
> The target environment doesn't support EcmaScriptModule syntax so it's not possible to use external type 'module'
> ```

Somewhere you have defined the `"type": "module"` in a `package.json`, and this is not supported with nx at this time.
