### ISSUE TITLE
Cannot find module 'jest-resolve/build/default_resolver'

### ISSUE THREAD

**Issue by Merott** [nrwl/nx#1054]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Tests written in Jest to run.

## Current Behavior

Getting the following error after running `nx test`:

```
Cannot find module 'jest-resolve/build/default_resolver'
```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Update Jest to the latest version. As of this report, it's `24.0.0`.
2. Run `nx test`

### Context

Please provide any relevant information about your setup:

- version of Nx used: 7.5.1
- version of Angular CLI used: 7.3.0
- version of Jest used: 24.0.0

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

```
Cannot find module 'jest-resolve/build/default_resolver'
Error: Cannot find module 'jest-resolve/build/default_resolver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/merott/Workspace/nFusz/frontend-apps/node_modules/@nrwl/builders/plugins/jest/resolver.js:5:26)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Function.findNodeModule (/Users/merott/Workspace/nFusz/frontend-apps/node_modules/jest-resolve/build/index.js:88:9)
    at resolve (/Users/merott/Workspace/nFusz/frontend-apps/node_modules/jest-config/build/utils.js:78:41)
    at Object.keys.map.regex (/Users/merott/Workspace/nFusz/frontend-apps/node_modules/jest-config/build/normalize.js:723:32)
    at Array.map (<anonymous>)
```

## Other

The file `default_resolver` has been renamed to `defaultResolver` in `jest-resolve@24.0.0`. Updating the following accordingly appears to fix the issue.

https://github.com/nrwl/nx/blob/0788a81322481b3687ba4c15fb11fbcd28f4ad80/packages/builders/plugins/jest/resolver.ts#L3

I can contribute a PR, but need some guidance on how you'd like to maintain backwards compatibility. The best solution I can think of is a `try/catch` approach for the import.

**Comment by FrozenPandaz** [comment]
Thanks for opening this issue.

This will be something we will need to change when updating to Jest 24.

As of now, we are waiting for `jest-preset-angular` to update before updating.

Going to close as it's in scope of this issue: https://github.com/nrwl/nx/issues/1029

**Comment by HackPoint** [comment]
Cannot find module 'jest-resolve/build/default_resolver'
Error: Cannot find module 'jest-resolve/build/default_resolver'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/genadyshmunik/projects/ge-phoenix/node_modules/@nrwl/builders/plugins/jest/resolver.js:5:26)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Function.findNodeModule (/Users/genadyshmunik/projects/ge-phoenix/node_modules/jest-resolve/build/index.js:88:9)
    at resolve (/Users/genadyshmunik/projects/ge-phoenix/node_modules/jest-config/build/utils.js:78:41)
    at Object.keys.map.regex (/Users/genadyshmunik/projects/ge-phoenix/node_modules/jest-config/build/normalize.js:718:32)
    at Array.map (<anonymous>)

**Comment by skorunka** [comment]
Same issue. Jest 23.6.0 works.

**Comment by jbjhjm** [comment]
I'm still experiencing this issue with nx@7.8.5. Tried jest 24.8, 24.1 and 24.0 and all failed.
I ended up with downgrading jest to 23.6.0 and jest-preset-angular to 6.0.2, and it seems to work now.

**Comment by danieldanielecki** [comment]
> 
> 
> I'm still experiencing this issue with nx@7.8.5. Tried jest 24.8, 24.1 and 24.0 and all failed.
> I ended up with downgrading jest to 23.6.0 and jest-preset-angular to 6.0.2, and it seems to work now.

Same here, tried it just 1 week ago, and still the same result and "solution" as you.

**Comment by jvpepino** [comment]
@FrozenPandaz so this should work when using nx v7.8.1?

**Comment by maxime1992** [comment]
Still happening with 8.3.0

Not sure why this issue's closed :thinking:

**Comment by Mallfurion** [comment]
this still happens when running ng test, with the new upgrade to @nrwl v9.1.3

`An unhandled exception occurred: Cannot find module 'jest-resolve/build/defaultResolver'
Require stack:
- /mnt/c/projects/talent-matching-frontend/node_modules/@nrwl/jest/plugins/resolver.js
- /mnt/c/projects/talent-matching-frontend/node_modules/jest/node_modules/jest-resolve/build/index.js
- /mnt/c/projects/talent-matching-frontend/node_modules/jest/node_modules/@jest/core/node_modules/jest-config/build/normalize.js
- /mnt/c/projects/talent-matching-frontend/node_modules/jest/node_modules/@jest/core/node_modules/jest-config/build/index.js
- /mnt/c/projects/talent-matching-frontend/node_modules/jest/node_modules/@jest/core/build/cli/index.js
- /mnt/c/projects/talent-matching-frontend/node_modules/jest/node_modules/@jest/core/build/jest.js
- /mnt/c/projects/talent-matching-frontend/node_modules/jest/build/jest.js
- /mnt/c/projects/talent-matching-frontend/node_modules/@nrwl/jest/src/builders/jest/jest.impl.js
- /mnt/c/projects/talent-matching-frontend/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /mnt/c/projects/talent-matching-frontend/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /mnt/c/projects/talent-matching-frontend/node_modules/@angular/cli/models/architect-command.js
- /mnt/c/projects/talent-matching-frontend/node_modules/@angular/cli/commands/test-impl.js
- /mnt/c/projects/talent-matching-frontend/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /mnt/c/projects/talent-matching-frontend/node_modules/@angular-devkit/schematics/tools/index.js
- /mnt/c/projects/talent-matching-frontend/node_modules/@angular/cli/utilities/json-schema.js
- /mnt/c/projects/talent-matching-frontend/node_modules/@angular/cli/models/command-runner.js
- /mnt/c/projects/talent-matching-frontend/node_modules/@angular/cli/lib/cli/index.js
- /usr/lib/node_modules/@angular/cli/lib/init.js
- /usr/lib/node_modules/@angular/cli/bin/ng`

**Comment by ankitr-nalkv** [comment]
It's a bit weird but what worked for me was placing these packages at the very end of package.json's devDependencies

_"@nrwl/workspace": "8.4.8",
"@nrwl/jest": "8.4.8",
"@nrwl/cypress": "8.4.8"_
