### ISSUE TITLE
Unable to convert CRA to Nx

### ISSUE THREAD

**Issue by ghost** [nrwl/nx#10562]
I am getting an error when trying to convert to Nx.
I do see however the project being converted to an Nx workspace.

Error when converting to Nx
```
 wmonecke@MacBook-Pro-de-Walter  ~/Documents/Code/monorepo   main  npx cra-to-nx

 >  NX   🐳 Nx initialization

✔ Use Nx Cloud? (It's free and doesn't require registration.) · Yes

 >  NX   Nx is creating your v14.1.9 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace.
✔ NxCloud has been set up successfully

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   First time using Nx? Check out this interactive Nx tutorial.

   https://nx.dev/react-tutorial/01-create-application
   
   Prefer watching videos? Check out this free Nx course on Egghead.io.
   https://egghead.io/playlists/scale-react-development-with-nx-4038


 >  NX   Nx Cloud has been enabled

   Your workspace is currently unclaimed. Run details from unclaimed workspaces can be viewed on nx.app by anyone
   with the link. Claim your workspace at the following link to restrict access.
   
   https://nx.app/orgs/workspace-setup?accessToken=Zjc0YmJlYjEtNTY2Yi00MmFjLWFmOTYtYzAyZmFhMmI4NmRmfHJlYWQtd3JpdGU=


 >  NX   👋 Welcome to Nx!


 >  NX   🧹 Clearing unused files


 >  NX   🚚 Moving your React app in your new Nx workspace


 >  NX   🤹 Add CRA craco scripts to package.json


 >  NX   🧑‍🔧 Customize webpack 5.0.0


 >  NX   🛬 Skip CRA preflight check since Nx manages the monorepo


 >  NX   🧶 Add all node_modules to .gitignore


 >  NX   🚚 Folder restructuring.


 >  NX   🧹 Cleaning up.


 >  NX   📃 Extend the app's tsconfig.json from the base

SyntaxError: Unexpected token ] in JSON at position 887
    at JSON.parse (<anonymous>)
    at setupTsConfig (/Users/wmonecke/.npm/_npx/4b7b36b90dc25906/node_modules/cra-to-nx/src/lib/tsconfig-setup.js:60:27)
    at /Users/wmonecke/.npm/_npx/4b7b36b90dc25906/node_modules/cra-to-nx/src/lib/cra-to-nx.js:102:44
    at Generator.next (<anonymous>)
    at /Users/wmonecke/.npm/_npx/4b7b36b90dc25906/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/wmonecke/.npm/_npx/4b7b36b90dc25906/node_modules/tslib/tslib.js:114:16)
    at createNxWorkspaceForReact (/Users/wmonecke/.npm/_npx/4b7b36b90dc25906/node_modules/cra-to-nx/src/lib/cra-to-nx.js:40:20)
    at Object.<anonymous> (/Users/wmonecke/.npm/_npx/4b7b36b90dc25906/node_modules/cra-to-nx/src/index.js:9:43)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

However, when I try to run the app with `npx nx serve aware` (aware being the name of the CRA app) I get the following:

```
✘ wmonecke@MacBook-Pro-de-Walter  ~/Documents/Code/monorepo   main ±  npx nx serve aware

> nx run aware:serve


> aware@0.1.0 serve
> npm start


> aware@0.1.0 start
> craco start

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'react-dev-utils/ModuleScopePlugin'
Require stack:
- /Users/wmonecke/Documents/Code/monorepo/apps/aware/craco.config.js
- /Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/node_modules/cosmiconfig/dist/loaders.js
- /Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/node_modules/cosmiconfig/dist/ExplorerBase.js
- /Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/node_modules/cosmiconfig/dist/Explorer.js
- /Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/node_modules/cosmiconfig/dist/index.js
- /Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/lib/config.js
- /Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/scripts/start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/wmonecke/Documents/Code/monorepo/apps/aware/craco.config.js:4:29)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/wmonecke/Documents/Code/monorepo/apps/aware/craco.config.js',
    '/Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/node_modules/cosmiconfig/dist/loaders.js',
    '/Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/node_modules/cosmiconfig/dist/ExplorerBase.js',
    '/Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/node_modules/cosmiconfig/dist/Explorer.js',
    '/Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/node_modules/cosmiconfig/dist/index.js',
    '/Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/lib/config.js',
    '/Users/wmonecke/.nvm/versions/node/v16.8.0/lib/node_modules/@craco/craco/scripts/start.js'
  ]
}

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "aware:serve" failed
```

After having run `npx nx run serve` this is the file structure I got:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/104456448/171621247-4b4cab94-44bc-4afb-a56e-33402266d8a1.png">

**Comment by AgentEnder** [comment]
@waltermonecke I've transferred this to the main Nx repo, since cra-to-nx lives here now.
