### ISSUE TITLE
nx 14.2.1 fails to resolve local executors

### ISSUE THREAD

**Issue by lwhiteley** [nrwl/nx#10629]
## Current Behavior
With migration to 14.2.1, custom/local executors are not able to run due to not resolving the module

## Expected Behavior
nx should still resolve local executor modules

## Steps to Reproduce
- upgrade to nx 14.2.1
- run a custom executor

The target is defined as follows in a project.json
```
    "bump-service": {
      "executor": "./dist/tools/executors/bump-service:bump",
      "options": {}
    },
```

below is a screenshot of the dist folder

![Screenshot-20220608T101758](https://user-images.githubusercontent.com/6108793/172568171-3e3b47e0-4e2b-49fc-9567-a68a0e314da5.png)

not sure if its similar to #10610

### Failure Logs
```
Error: Unable to resolve ./dist/tools/executors/bump-service:bump.
Found module undefined while trying to locate ./dist/tools/executors/bump-service/package.json
    at Workspaces.readExecutor (/home/dev/nx-workspace/node_modules/.pnpm/nx@14.2.1/node_modules/nx/src/config/workspaces.js:95:19)

...

Unexpected error:
Error: Unable to load hasher for task "services-api:bump-service"
    at getCustomHasher (/home/dev/nx-workspace/node_modules/.pnpm/nx@14.2.1/node_modules/nx/src/tasks-runner/utils.js:173:15)
    at TasksSchedule.<anonymous> (/home/dev/nx-workspace/node_modules/.pnpm/nx@14.2.1/node_modules/nx/src/tasks-runner/tasks-schedule.js:111:62)
    at Generator.next (<anonymous>)
    at /home
```

### Environment

```
> nx "report"


 >  NX   Report complete - copy this into the issue template

   Node : 14.19.1
   OS   : linux x64
   pnpm : 7.1.9
   
   nx : 14.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.2.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.1
   @nrwl/eslint-plugin-nx : 14.2.1
   @nrwl/express : 14.2.1
   @nrwl/jest : 14.2.1
   @nrwl/js : 14.2.1
   @nrwl/linter : 14.2.1
   @nrwl/nest : 14.2.1
   @nrwl/next : 14.2.1
   @nrwl/node : 14.2.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.2.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.1
   @nrwl/web : 14.2.1
   @nrwl/workspace : 14.2.1
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @compodoc/compodoc: 1.1.19
         @nx-tools/nx-docker: 2.3.0
         @twittwer/compodoc: 1.8.0
```

**Comment by AgentEnder** [comment]
The fix for this is already merged and will be released in 14.2.2. you can track #10624.

I'm going to close this out since it's been addressed.
