### ISSUE TITLE
Both project and target have to be specified

### ISSUE THREAD

**Issue by andyjessop** [nrwl/nx#10637]
## Current Behavior
I'm trying to serve a project, but am getting the following error:

I’m building a plugin, and am testing it out by installing it on a fresh repo and running the generator to create an app. However, when I come to serve that app, I get the following error:

Test repo: https://github.com/andyjessop/nx-plugin-test
Uses plugin to generate app: https://www.npmjs.com/package/@andyjessop/cloudflare
Command: `npx nx serve worker`

```
Error: Both project and target to have to be specified
    at parseRunOneOptions (/Users/andy/dev/cloudflare-test/node_modules/nx/src/command-line/run-one.js:76:15)
    at Object.<anonymous> (/Users/andy/dev/cloudflare-test/node_modules/nx/src/command-line/run-one.js:19:22)
    at Generator.next (<anonymous>)
    at /Users/andy/dev/cloudflare-test/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/andy/dev/cloudflare-test/node_modules/tslib/tslib.js:114:16)
    at Object.runOne (/Users/andy/dev/cloudflare-test/node_modules/nx/src/command-line/run-one.js:15:20)
    at /Users/andy/dev/cloudflare-test/node_modules/nx/src/command-line/nx-commands.js:50:147
    at Generator.next (<anonymous>)
    at fulfilled (/Users/andy/dev/cloudflare-test/node_modules/tslib/tslib.js:115:62)

✘ [ERROR] Command failed with exit code 1: npm install && npm run build
```

## Expected Behavior
The command should execute without errors. When I run the same command in the repo where I'm building the plugin, everything works fine. 

### Environment
`nx report:`

```
Node : 18.3.0
   OS   : darwin x64
   npm  : 8.11.0

   nx : 14.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.1
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.1
   @nrwl/js : 14.2.1
   @nrwl/linter : 14.2.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.2.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.1
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
   	 @andyjessop/cloudflare: 0.0.2
```

**Comment by AgentEnder** [comment]
What's the version of Nx in the repo you are building the plugin?

**Comment by andyjessop** [comment]
It's 4.1.9.

```
nx : 14.1.9
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.9
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.1.9
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.1.9
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
```

**Comment by ldco2016** [comment]
I am running into this problem after I upgraded to Angular 14 and Nx version 14.6.4 and then run `ng serve --open --watch`.
