### ISSUE TITLE
Error while generating Angular component after upgrading from Angular 13 to 14 using `nx migrate`

### ISSUE THREAD

**Issue by ElecTreeFrying** [nrwl/nx#10676]
Need help...

Not sure why I'm starting get these kind of errors after upgrading angular 13 to 14 using `nx migrate`

I can't generate angular component.

## Current Behavior
Terminal errors while generating angular component.

## Expected Behavior
Generate angular component without errors

## Steps to Reproduce

1. nx migrate from angular 13 to 14
2. generate angular component using nx cli

### Failure Logs

Same error appears even if I try using `ng generate component`

Using `nx g c component-name`
```
InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"style":"scss","skipTests":true,"skipImport":true,"path":"libs/fisendo-web/staycation/ui/staycation-components/src/lib/components/property-content","project":"fisendo-web-staycation-ui-staycation-components","name":"component-name","displayBlock":false,"inlineStyle":false,"inlineTemplate":false,"changeDetection":"Default","flat":false,"skipSelector":false,"type":"component","export":false}

Errors:

  Data path "" must NOT have additional properties(standalone).
    at MapSubscriber.project (***\***\node_modules\@angular-devkit\schematics\tools\schema-option-transform.js:30:27)
    at MapSubscriber._next (***\***\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (***\***\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (***\***\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (***\***\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (***\***\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (***\***\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (***\***\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (***\***\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:143:22)
    at ThrowIfEmptySubscriber._next (***\***\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26) {
  errors: [
    {
      instancePath: '',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: [Object],
      message: 'must NOT have additional properties'
    }
  ]
}
```

### Environment

```
   Node : 14.18.1
   OS   : win32 x64
   npm  : 6.14.15

   nx : 14.2.2
   @nrwl/angular : 14.2.2
   @nrwl/cypress : 14.2.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.2
   @nrwl/eslint-plugin-nx : 14.2.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.2
   @nrwl/js : 14.2.2
   @nrwl/linter : 14.2.2
   @nrwl/nest : 14.2.2
   @nrwl/next : Not Found
   @nrwl/node : 14.2.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.2
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.2
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @nguniversal/express-engine: 13.0.2
         @nguniversal/builders: 13.0.2
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you share the output of running `npm ls @schematics/angular`?

**Comment by ElecTreeFrying** [comment]
> Thanks for reporting this!
> 
> Could you share the output of running `npm ls @schematics/angular`?

Hi, thanks for the reply. Here's the result

```
npm ls @schematics/angular
october@ ***\***
+-- @angular/cli@14.0.1
| `-- @schematics/angular@14.0.1 
+-- @angular/fire@7.2.1
| `-- @schematics/angular@13.3.0 
`-- @nrwl/angular@14.2.2
  `-- @schematics/angular@14.0.1 
```

**Comment by ElecTreeFrying** [comment]
This is so weird, after I upgraded from `@angular/cli@7.2.1` to latest (v7.4.1) it seems that I can create components now.

**Comment by drakedeatonuk** [comment]
Getting this error too currently

**Comment by skog-newglue** [comment]
This is still happening in 15.0.3..
