### ISSUE TITLE
no such file or directory, open 'libs/interfaces/package.json'

### ISSUE THREAD

**Issue by andyjessop** [nrwl/nx#10698]
I'm getting this error on all of my dependency packages when running my `api` app with `npx nx serve api`.

## Current Behavior

Here's the output of one of the packages (there is a similar output for each of my three dependent packages).

```
Running custom build: nx build api

 >  NX   Running target build for project api and 4 task(s) it depends on


node:fs:591
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'libs/interfaces/package.json'
    at Object.openSync (node:fs:591:3)
    at readFileSync (node:fs:459:35)
    at readJsonFile (/Users/andy/dev/runestone/node_modules/nx/src/utils/fileutils.js:21:43)
    at updatePackageJson (/Users/andy/dev/runestone/node_modules/@nrwl/js/src/utils/update-package-json.js:14:51)
    at /Users/andy/dev/runestone/node_modules/@nrwl/js/src/executors/tsc/tsc.impl.js:57:57
    at Generator.next (<anonymous>)
    at fulfilled (/Users/andy/dev/runestone/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'libs/interfaces/package.json'
}

Node.js v18.3.0

> nx run interfaces:build

Compiling TypeScript files for project "interfaces"...
error TS6059: File '/Users/andy/dev/runestone/libs/interfaces/src/index.ts' is not under 'rootDir' 'libs/interfaces'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
../../libs/interfaces/src/index.ts:1:15 - error TS6059: File '/Users/andy/dev/runestone/libs/interfaces/src/lib/api.ts' is not under 'rootDir' 'libs/interfaces'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via './lib/api' from file '/Users/andy/dev/runestone/libs/interfaces/src/index.ts'
    Root file specified for compilation

1 export * from './lib/api';
                ~~~~~~~~~~~
```
FTR, `libs/interfaces/package.json` _does_ exist.

Each of the libs was created with `npx nx g @nrwl/js:lib [name]`, and they each have a buildable step that works:

```
npx nx build interfaces

> nx run interfaces:build

Compiling TypeScript files for project "interfaces"...
Done compiling TypeScript files for project "interfaces".

 >  NX   Successfully ran target build for project interfaces (578ms)
```

## Steps to Reproduce
This is the current state of this WIP repo: https://github.com/andyjessop/runestone so you can pull it down and run the command yourself.

```
npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.3.0
   OS   : darwin x64
   npm  : 8.11.0

   nx : 14.1.9
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.9
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.1.9
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.1.9
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:
   	 nx-plugin-vite: 2.0.2
```

**Comment by andyjessop** [comment]
More info here, it looks like a `dist` folder is being created inside my app, so I guess it's looking there for the package.json (not finding it) and also this `dist` folder is not in the package root. It might explain both error messages. Still don't know why it's happening though
![Uploading Screenshot 2022-06-10 at 23.24.02.png…]()
.

**Comment by andyjessop** [comment]
Solved now (thanks rubber 🦆 ). In my executor I was changing the working directory: https://github.com/andyjessop/runestone/blob/main/apps/api/project.json#L26

I've now changed this to provide the path in-line, and it works. Cheers!
