### ISSUE TITLE
nx g c – InvalidInputOptions [Error]: Schematic input does not validate against the Schema

### ISSUE THREAD

**Issue by chriscurnow** [nrwl/nx#10729]
## Current Behavior
Run `nx g c ...` 
with `@nrwl/angular:component`

returns error message 

`InvalidInputOptions [Error]: Schematic input does not validate against the Schema: ``{"style":"scss","project":"admin","name":"libs/shared/feature-head-contractor/src/lib/company-list-container","displayBlock":false,"inlineStyle":false,"inlineTemplate":false,"standalone":false,"changeDetection":"Default","skipTests":false,"flat":false,"skipImport":false,"skipSelector":false,"type":"component","export":false}`
`Errors:`

  `Data path "" must NOT have additional properties(standalone).`
    `at MapSubscriber.project (/Users/chriscurnow/Projects/4cast/workspace/node_modules/@angular-devkit/schematics/tools/schema-option-transform.js:30:27)
    at MapSubscriber._next (/Users/chriscurnow/Projects/4cast/workspace/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/chriscurnow/Projects/4cast/workspace/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (/Users/chriscurnow/Projects/4cast/workspace/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (/Users/chriscurnow/Projects/4cast/workspace/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/Users/chriscurnow/Projects/4cast/workspace/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/Users/chriscurnow/Projects/4cast/workspace/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/chriscurnow/Projects/4cast/workspace/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/Users/chriscurnow/Projects/4cast/workspace/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/Users/chriscurnow/Projects/4cast/workspace/node_modules/rxjs/internal/Subscriber.js:66:18) {
  errors: [
    {
      instancePath: '',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: [Object],
      message: 'must NOT have additional properties'
    }
  ]
}`
## Expected Behavior
Component is created

## Steps to Reproduce
Run `nx g c` with component path

I updated to Nx 14.2.2 yesterday.
Other generators have been working today eg:

`nx g lib`
`nx g ngrx`

When I run `nx g c` now, it says 
`? Which generator would you like to use? … `
`@schematics/angular:component`
`@nrwl/angular:component`
`None of the above`

The problem occurs when I chose `@nrwl/angular:component` which is what I have used previously when using the contextual menu option `nx generate`.

### Environment

Node : 16.15.1
   OS   : darwin arm64
   npm  : 8.12.1
   
   nx : 14.2.4
   @nrwl/angular : 14.2.4
   @nrwl/cypress : 14.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.4
   @nrwl/eslint-plugin-nx : 14.2.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.4
   @nrwl/js : Not Found
   @nrwl/linter : 14.2.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.4
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.4
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 13.2.0
         @ngrx/effects: 13.2.0
         @ngrx/entity: 13.2.0
         @ngrx/router-store: 13.2.0
         @ngrx/store: 13.2.0
         rxjs: 6.6.7
         @ngrx/schematics: 13.2.0
         @ngrx/store-devtools: 13.2.0

**Comment by gilian-rockstars** [comment]
It seems like the error I'm getting when migrating from 14.1.9 to 14.3.1:

```
Schema validation failed with the following errors:
  Data path "/scripts/2" must be object.
  Data path "/scripts/2" must match pattern "\.[cm]?jsx?$".
  Data path "/scripts/2" must match exactly one schema in oneOf.
Error: Schema validation failed with the following errors:
  Data path "/scripts/2" must be object.
  Data path "/scripts/2" must match pattern "\.[cm]?jsx?$".
  Data path "/scripts/2" must match exactly one schema in oneOf.
    at SwitchMapSubscriber.project (/Dir/node_modules/@angular-devkit/architect/src/architect.js:226:19)
    at SwitchMapSubscriber._next (/Dir/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/switchMap.js:47:27)
    at SwitchMapSubscriber.Subscriber.next (/Dir/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (/Dir/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Dir/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/Dir/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Dir/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (/Dir/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Dir/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:143:22)
    at MergeMapSubscriber.notifyNext (/Dir/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/Dir/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/Dir/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (/Dir/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Dir/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/Dir/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Dir/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)

```

Could this be related?

**Comment by leosvelperez** [comment]
Thanks for reporting this!

@chriscurnow it would seem there might be some hoisting issues with the installed npm packages or some wrong versions installed. Could you share the output of `npm ls @schematics/angular` and `npm ls @angular-devkit/core`? Or better yet, could you provide a repo we can use to troubleshoot the issue?

@gilian-rockstars your issue happens because you have some script values that are no longer valid since Angular v14. This is expected and the correct behavior. The message `Data path "/scripts/2" must match pattern "\.[cm]?jsx?$".` indicates you have a value in the `scripts` which doesn't comply with that regular expression (it's missing one of the allowed extensions).

**Comment by florent1933** [comment]
On my side
```
npx nx generate @nrwl/angular:component dsqdsq --no-interactive --dry-run

Schematic input does not validate against the Schema: {"style":"scss","changeDetection":"OnPush","project":"front","name":"dsqdsq","displayBlock":false,"inlineStyle":false,"inlineTemplate":false,"standalone":false,"skipTests":false,"flat":false,"skipImport":false,"skipSelector":false,"type":"component","export":false}
Errors:

  Data path "" must NOT have additional properties(standalone).
```

```
npm ls @schematics/angular
├─┬ @angular/cli@14.0.1
│ └── @schematics/angular@14.0.1
├─┬ @angular/fire@7.4.1
│ └── @schematics/angular@13.3.7
└─┬ @nrwl/angular@14.2.2
  └── @schematics/angular@14.0.1
``` 


``` 
npm ls @angular-devkit/core
├─┬ @angular-devkit/build-angular@14.0.1
│ ├─┬ @angular-devkit/architect@0.1400.1
│ │ └── @angular-devkit/core@14.0.1
│ └── @angular-devkit/core@14.0.1
├─┬ @angular/cli@14.0.1
│ ├── @angular-devkit/core@14.0.1
│ ├─┬ @angular-devkit/schematics@14.0.1
│ │ └── @angular-devkit/core@14.0.1 deduped
│ └─┬ @schematics/angular@14.0.1
│   └── @angular-devkit/core@14.0.1 deduped
├─┬ @angular/fire@7.4.1
│ ├─┬ @angular-devkit/schematics@13.3.7
│ │ └── @angular-devkit/core@13.3.7 deduped
│ └─┬ @schematics/angular@13.3.7
│   └── @angular-devkit/core@13.3.7 deduped
├─┬ @nestjs/schematics@8.0.11
│ ├── @angular-devkit/core@13.3.5
│ └─┬ @angular-devkit/schematics@13.3.5
│   └── @angular-devkit/core@13.3.5 deduped
├─┬ @nrwl/angular@14.2.2
│ ├─┬ @angular-devkit/schematics@14.0.1
│ │ └── @angular-devkit/core@14.0.1
│ └─┬ @schematics/angular@14.0.1
│   └── @angular-devkit/core@14.0.1 deduped
└─┬ @storybook/angular@6.5.8
  └── @angular-devkit/core@13.3.7
```

**Comment by leosvelperez** [comment]
@florent1933 could you check the version of the installed `@schematics/angular` in the top-level `node_modules`?

If you or someone else on this thread can provide a reproduction would allow me to better troubleshoot the issue.

**Comment by florent1933** [comment]
The installed version of "@schematics/angular" is "version": "13.3.7".

Thanks for your time. Not sure to have the time to provide a reproduction. I will do my best.

**Comment by leosvelperez** [comment]
That right there is the issue though. You should have `@schematics/angular` on version v14.x.x. That's why the `standalone` flag is not allowed, because it was introduced for v14. You could try deleting your lock file and `node_modules` and reinstall the packages to see if the hoisting changes. If that doesn't work, you could make sure to add the `@schematics/angular` to your `devDependencies` with the same version the rest of the `@angular/*` packages have.

**Comment by gilian-rockstars** [comment]
> @gilian-rockstars your issue happens because you have some script values that are no longer valid since Angular v14. This is expected and the correct behavior. The message `Data path "/scripts/2" must match pattern "\.[cm]?jsx?$".` indicates you have a value in the `scripts` which doesn't comply with that regular expression (it's missing one of the allowed extensions).

Thanks :)

**Comment by chriscurnow** [comment]
@leosvelperez I have just invited you to have read access to our repo. I think the issue occurs in the main branch. If not, it certainly does in the feature/NX-116 branch.

**Comment by leosvelperez** [comment]
@chriscurnow thanks for providing a reproduction! The issue is that the `@schematics/angular` in your package.json is set to version `^13.2.6` and it should actually be aligned with the rest of the versions of the angular packages (e.g. `@angular-devkit/build-angular`, 14.0.1 in your workspace).

I can see the migration didn't update that package version automatically. I'll push a fix for that so anyone that migrates in the future doesn't face the same issue.

For anyone having this issue as of now, please check if you have the `@schematics/angular` package in your package.json and make sure it's updated to the same version the `@angular-devkit/build-angular` package has.

If you don't have the package listed in the package.json but you're having the same issue, you might have other packages that depend on an older version of the same and it's causing it to be hoisted with that older version. In those cases, you could add the package to your `devDependencies` with a version that matches the mentioned `@angular-devkit/build-angular` package.

**Comment by chriscurnow** [comment]
@leosvelperez thanks so much for this. Yes it works!! I really appreciate how quickly you responded to the issue and found a fix for me..
