### ISSUE TITLE
Error: Cannot find module 'nx/src/config/configuration'

### ISSUE THREAD

**Issue by joewIST** [nrwl/nx#10815]
I am unable to run any schematics or build commands due to incorrect exports in @nrwl/devkit

## Current Behavior
Schematics and build comments all fail.

## Expected Behavior
Schematics to run as usual and for me to be able to build my library.

### Failure Logs
Cannot find module 'nx/src/config/configuration'
Require stack:
- C:\...\@nrwl\devkit\index.js
- C:\...\@nrwl\workspace\src\utilities\buildable-libs-utils.js
- C:\...\@nrwl\angular\src\executors\ng-packagr-lite\ng-packagr-lite.impl.js
- C:\...\nx\src\config\workspaces.js
- C:\...\nx\src\command-line\run.js
- C:\...\nx\bin\run-executor.js
-
Error: Cannot find module 'nx/src/config/configuration'
Require stack:
- C:\...\@nrwl\devkit\index.js
- C:\...\@nrwl\workspace\src\utilities\buildable-libs-utils.js
- C:\...\@nrwl\angular\src\executors\ng-packagr-lite\ng-packagr-lite.impl.js
- C:\...nx\src\config\workspaces.js
- C:\...\nx\src\command-line\run.js
- C:\...\nx\bin\run-executor.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\...\@nrwl\devkit\index.js:20:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)

### Environment

   Node : 14.17.3
   OS   : win32 x64
   yarn : 1.22.10

   nx : 14.1.9
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.1.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @ngneat/spectator: 8.3.1
         @ngrx/component-store: 13.2.0
         @ngrx/effects: 13.2.0
         @ngrx/entity: 13.2.0
         @ngrx/router-store: 13.2.0
         @ngrx/store: 13.2.0
         apollo-angular: 2.6.0
         @compodoc/compodoc: 1.1.18
         @ngneat/spectator: 8.3.1
         @ngrx/schematics: 13.2.0
         @ngrx/store-devtools: 13.2.0
         @storybook/angular: 6.5.9
         nx-stylelint: 12.2.0

**Comment by joewIST** [comment]
hi @leosvelperez  i have already run that command and it did not update my nx package. Possibly a bug in the migrate script? I will upgrade it manually. Thanks

**Comment by mrcreatist** [comment]
> 

This worked for me, Thanks!
