### ISSUE TITLE
After migration to nrwl 14.3 nx serves errors out

### ISSUE THREAD

**Issue by MirkoDaumann** [nrwl/nx#10829]
## Current Behavior

After updating to nrwl 14.3 i get following errors:

```
./apps/web/src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i6.PortalModule to symbol
    at C:\Users\U24617\Documents\Projekte\E-Antrag\node_modules\@ngtools\webpack\src\ivy\loader.js:81:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

./apps/web/src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity i6.PortalModule to symbol
    at C:\Users\U24617\Documents\Projekte\E-Antrag\node_modules\@ngtools\webpack\src\ivy\loader.js:81:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
## Expected Behavior

Should be able to run the app as it worked before.

## Steps to Reproduce

1. npx nx migrate @nrwl/workspace --to="@nrwl/angular@13.10.5"
2. swapping Typescript version back to 4.6.2
3. npm i
4. npx nx migrate --run-migrations
5. npx nx serve --> errors

### Environment

```
Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0

   nx : 14.3.6
   @nrwl/angular : 13.10.5
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.5
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : Not Found
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.5
   @nrwl/web : Not Found
   @nrwl/workspace : 14.3.6
   typescript : 4.6.2
```

**Comment by Coly010** [comment]
Hey! :)

Can you give a little bit more detail around this?

Have you migrated to Angular 14 with Nx 14.3.6, but manually downgraded TS?

If that is the case, then this could be why it will be erroring.

Can you move TS to 4.7 and try again?

**Comment by MirkoDaumann** [comment]
Hey, thanks for the quick answer.

Upgrading to Typescript 4.7 doesnt work. Angular v13. has a depency for typescript <4.7
The actual problem was that nx v13 has a problem with Husky. So i wanted to Upade to v14 without updating the angular Version above 13.

Thats why i ran those steps:
```
npx nx migrate @nrwl/workspace --to="@nrwl/angular@13.10.5"
swapping Typescript version back to 4.6.2
npm i
npx nx migrate --run-migrations
npx nx serve --> errors
```

Anyway, now i tried updating to Nx v.14 and Angular v.14 
with the following steps:

```
npx nx migrate latest
npm i

```

and im already running depency issue again.
Should i open another ticket for that?

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: e-antrag@0.0.0
npm ERR! Found: jest@27.5.1
npm ERR! node_modules/jest
npm ERR!   dev jest@"27.5.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jest@"^28.0.0" from jest-preset-angular@12.1.0
npm ERR! node_modules/jest-preset-angular
npm ERR!   dev jest-preset-angular@"12.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by MirkoDaumann** [comment]
Problem was been solved. Was an issue on my side. Can be closed. Thanks.

**Comment by giantape** [comment]
Hi @MirkoDaumann sorry to reopen this, could you please reposting how do you resolve this problem?
thank you very much.

**Comment by binarybro** [comment]
@MirkoDaumann I am running in a similar issue, and I would also like to understand how you resolved this.
