### ISSUE TITLE
Cannot generate Angular application

### ISSUE THREAD

**Issue by chioarub** [nrwl/nx#10865]
After installing "@nrwl/angular": "^14.3.6" I am not able to use the Nx Console or the CLI to generate Angular applications

## Current Behavior
TypeError when generating Angular applications using Cli/NxConsole plugin

## Expected Behavior
Generate Angular applications using Cli/NxConsole plugin

## Steps to Reproduce
Run the following commands to reproduce the issue.
```
npm i -g create-nx-workspace

npx create-nx-workspace nx-test --preset="apps" --nxCloud=false

cd nx-test

npm install -D @nrwl/nest

npx nx generate @nrwl/nest:application srv-test --no-interactive

npm install -D @nrwl/angular

npx nx generate @nrwl/angular:application web-ui --style=scss --no-interactive --dry-run

Tried removing node_modules/package-lock.json and reinstalling, but the issue is till there.
One thing I observed is that if I install angular first, without installing/generating nest application, I am able to generate the angular application. Sadely, when I install/generate nest application after the previous steps that worked and remove node_modules/package-lock.json and reinstall, I get the issue once more. :(
```

### Failure Logs
```
>  NX  Generating @nrwl/angular:application

TypeError: this.tree.readText is not a function
    at TreeWorkspaceHost.readFile (D:\Projects\Ts\test\nx-issues\nx-test\node_modules\@schematics\angular\utility\workspace.js:23:26)
    at readJsonWorkspace (D:\Projects\Ts\test\nx-issues\nx-test\node_modules\@schematics\angular\node_modules\@angular-devkit\core\src\workspace\json\reader.js:17:28)
    at Object.readWorkspace (D:\Projects\Ts\test\nx-issues\nx-test\node_modules\@schematics\angular\node_modules\@angular-devkit\core\src\workspace\core.js:91:62)
    at async getWorkspace (D:\Projects\Ts\test\nx-issues\nx-test\node_modules\@schematics\angular\utility\workspace.js:73:27)
    at async D:\Projects\Ts\test\nx-issues\nx-test\node_modules\@schematics\angular\application\index.js:224:27
this.tree.readText is not a function
```

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 14.19.3
   OS   : win32 x64
   npm  : 6.14.17

   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : 14.3.6
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

Also tried it on linux with the same issue.
 >  NX   Report complete - copy this into the issue template

   Node : 14.19.2
   OS   : linux x64
   npm  : 6.14.17

   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : 14.3.6
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by rhutchison** [comment]
@chioarub try `npm i -D @angular-devkit/schematics`

**Comment by chioarub** [comment]
installing @angular-devkit/schematics solved it.
