### ISSUE TITLE
OSX pathing is incorrect on init install?

### ISSUE THREAD

**Issue by matthewharwood** [nrwl/nx#109]
Works just fine on my windows machine. 
Unfortunately, tested on 2 Macs  with the same bad results.

**[Repo](https://github.com/morningharwood/platform)**

```
mharwood@mharwood-macbookpro: ~/Documents/GitHub/morningharwood/platform on master
$ tsc -v
Version 2.6.1


mharwood@mharwood-macbookpro: ~/Documents/GitHub/morningharwood/platform on master
$ yarn
✨  Done in 94.63s.

m@m: platform on master
$ npm start --app=portfolio

Cannot find module 'typescript' from '/Users/mharwood/Documents/GitHub'
Error: Cannot find module 'typescript' from '/Users/mharwood/Documents/GitHub'
    at Function.module.exports [as sync] (/Users/mharwood/Documents/GitHub/morningharwood/platform/node_modules/resolve/lib/sync.js:40:15)
    at Object.requireProjectModule (/Users/mharwood/Documents/GitHub/morningharwood/platform/node_modules/@angular/cli/utilities/require-project-module.js:6:28)
    at Object.readTsconfig (/Users/mharwood/Documents/GitHub/morningharwood/platform/node_modules/@angular/cli/utilities/read-tsconfig.js:6:48)
    at new NgCliWebpackConfig (/Users/mharwood/Documents/GitHub/morningharwood/platform/node_modules/@angular/cli/models/webpack-config.js:19:42)
    at Class.run (/Users/mharwood/Documents/GitHub/morningharwood/platform/node_modules/@angular/cli/tasks/serve.js:71:29)
    at check_port_1.checkPort.then.port (/Users/mharwood/Documents/GitHub/morningharwood/platform/node_modules/@angular/cli/commands/serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! morningharwood@0.0.0 start: `ng serve --app=portfolio`
```

weird directory to look for typescript.  For the lulz I adde it
```
mharwood@mharwood-macbookpro: ~/Documents/GitHub/morningharwood/platform
$ cd ../../
mharwood@mharwood-macbookpro: ~/Documents/GitHub
$ npm init -y

mharwood@mharwood-macbookpro: ~/Documents/GitHub
$ npm install --save typescript
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN github@1.0.0 No description
npm WARN github@1.0.0 No repository field.

+ typescript@2.6.1
added 1 package in 1.15s
```

Now we get a new error:
```
mharwood@mharwood-macbookpro: ~/Documents/GitHub/morningharwood/platform on master
$ npm start --app=portfolio

> morningharwood@0.0.0 start /Users/mharwood/Documents/GitHub/morningharwood/platform
> ng serve --app=portfolio

ENOENT: no such file or directory, stat '/Users/mharwood/Documents/GitHub/tsconfig.app.json'
Error: ENOENT: no such file or directory, stat '/Users/mharwood/Documents/GitHub/tsconfig.app.json'
```

**Why is the pathing so weird?**

**Comment by vsavkin** [comment]
The issue is because the root property in .angular-cli.json is set to `"root": "apps\\portfolio\\src"`, if you change it to `apps/portfolio/src`, it will work. I'll fix it.

**Comment by luchillo17** [comment]
@vsavkin I was having the same issue in Ubuntu, Why are the root paths the only ones weird? when i generate libs and stuff i see normal Linux-like paths except for the **root** one.
