### ISSUE TITLE
NX spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by Telokis** [nrwl/nx#10929]
## Current Behavior

Unable to run nx on my project.

## Expected Behavior

It was working properly but then I generated around 10k files I want to add to my git repository.  
I need to run one of my projects before I can commit/push them properly.

## Steps to Reproduce
I have around 10k files I want to add to my git repository. Some were already there but changed and some are totally new.

### Failure Logs
When running `nx run project:build`:

```
nx.js run [project][:target][:configuration] [_..]

Run a target for a project
(e.g., nx run myapp:serve:production).

You can also use the infix notation to run a target:
(e.g., nx serve myapp --configuration=production)

You can skip the use of Nx cache by using the --skip-nx-cache option.

Options:
      --version        Show version number                                                                                                                                                              [boolean]
      --prod           Use the production configuration                                                                                                                                [boolean] [default: false]
  -c, --configuration  Target configuration                                                                                                                                                              [string]
      --project        Target project                                                                                                                                                                    [string]
      --output-style   Defines how Nx emits outputs tasks logs                                                                                       [string] [choices: "dynamic", "static", "stream", "compact"]

Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at spawn (node:child_process:698:9)
    at C:\work\node_modules\nx\src\hasher\git-hasher.js:67:54
    at Generator.next (<anonymous>)
    at C:\work\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\work\node_modules\tslib\tslib.js:114:16)
    at spawnProcess (C:\work\node_modules\nx\src\hasher\git-hasher.js:63:20)
    at C:\work\node_modules\nx\src\hasher\git-hasher.js:35:66
    at Generator.next (<anonymous>) {
  errno: -4064,
  code: 'ENAMETOOLONG',
  syscall: 'spawn'
}
```

### Environment
```
> nx report

 >  NX   Report complete - copy this into the issue template

   Node : 17.2.0
   OS   : win32 x64
   npm  : 8.9.0

   nx : 14.1.9
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.9
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.1.9
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.9
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9
   @nrwl/web : 14.1.9
   @nrwl/workspace : 14.1.9
   typescript : 4.5.5
   ---------------------------------------
   Community plugins:
         nx-electron: 13.1.2
```

I noticed https://github.com/nrwl/nx/issues/9295 but I'm at a newer version when compared to that solution.

**Comment by aikrez** [comment]
I had the same issue with Nx 15.3.3 after Migrating Angular Material 15 which changed 440 files when running an application.
After adding the files to a commit the run command worked.
