### ISSUE TITLE
v14 migrate: The "path" argument must be of type string

### ISSUE THREAD

**Issue by wmarques** [nrwl/nx#10978]
## Current Behavior

I'm on a project with Nx V13 with Angular, trying to update to 14.
Command: 
npm i --legacy-peer-deps
npx nx migrate latest
npx nx migrate --run-migrations --verbose

After that, any nx command doesn't produce anything...

Specific thing about my setup: My NX Monorepo is not located in the root of the Git project. It's in a subfolder. I don't know if this can cause some issues...

I tried to debug myself for a few hours and I couldn't find anything to fix this...

## Steps to Reproduce

I couldn't reproduce it on a fresh Nx install, maybe it some of my dependencies ?

### Failure Logs

Output migrate latest: 
```
 nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching nx@14.3.6
Fetching @nrwl/jest@14.3.6
Fetching @nrwl/workspace@14.3.6
Fetching @nrwl/linter@14.3.6
Fetching @nrwl/angular@14.3.6
Fetching @angular/cdk@14.0.4
Fetching @angular/material@14.0.4
Fetching @angular/core@14.0.4
Fetching @angular/cli@13.3.8
Fetching @angular/cli@~13.3.0
```

Output run-migration:
```
>  NX  Running migrations from 'migrations.json'

Running migration 14-0-6-remove-root
The "path" argument must be of type string or an instance of Buffer or URL. Received null
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at Object.openSync (node:fs:577:10)
    at readFileSync (node:fs:453:35)
    at readJsonFile (/private/var/folders/9b/4pqky60d3z37wbsq0mh08gn40000gn/T/tmp-87683-tJh61wLOxege/node_modules/nx/src/utils/fileutils.js:18:43)
    at /private/var/folders/9b/4pqky60d3z37wbsq0mh08gn40000gn/T/tmp-87683-tJh61wLOxege/node_modules/nx/src/command-line/migrate.js:704:57
    at Generator.next (<anonymous>)
    at /private/var/folders/9b/4pqky60d3z37wbsq0mh08gn40000gn/T/tmp-87683-tJh61wLOxege/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/private/var/folders/9b/4pqky60d3z37wbsq0mh08gn40000gn/T/tmp-87683-tJh61wLOxege/node_modules/tslib/tslib.js:114:16)
    at runNxMigration (/private/var/folders/9b/4pqky60d3z37wbsq0mh08gn40000gn/T/tmp-87683-tJh61wLOxege/node_modules/nx/src/command-line/migrate.js:702:20)
    at /private/var/folders/9b/4pqky60d3z37wbsq0mh08gn40000gn/T/tmp-87683-tJh61wLOxege/node_modules/nx/src/command-line/migrate.js:617:23
Command failed: /var/folders/9b/4pqky60d3z37wbsq0mh08gn40000gn/T/tmp-87683-tJh61wLOxege/node_modules/.bin/tao migrate --run-migrations --verbose
```

### Environment

Node : 16.15.1
   OS   : darwin x64
   npm  : 8.11.0

   nx : 13.1.3
   @nrwl/angular : 13.8.3
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.8.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.1.3
   @nrwl/eslint-plugin-nx : 13.8.3
   @nrwl/express : undefined
   @nrwl/jest : 13.8.3
   @nrwl/js : undefined
   @nrwl/linter : 13.8.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.1.3
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.3
   typescript : 4.5.5
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
   	 @angular/animations: 13.2.4
   	 @angular/cdk: 13.2.4
   	 @angular/common: 13.2.4
   	 @angular/compiler: 13.2.4
   	 @angular/core: 13.2.4
   	 @angular/forms: 13.2.4
   	 @angular/localize: 13.2.4
   	 @angular/material: 13.2.4
   	 @angular/material-moment-adapter: 13.2.4
   	 @angular/platform-browser: 13.2.4
   	 @angular/platform-browser-dynamic: 13.2.4
   	 @angular/router: 13.2.4
   	 @angular/upgrade: 13.2.4
   	 @ng-bootstrap/ng-bootstrap: 11.0.0
   	 ngx-bootstrap: 7.1.2
   	 ngx-spinner: 13.1.1
   	 @angular-builders/custom-webpack: 13.1.0
   	 @angular-devkit/build-angular: 13.2.5
   	 @angular-eslint/builder: 13.0.1
   	 @angular-eslint/schematics: 13.0.1
   	 @angular/cli: 13.2.5
   	 @angular/compiler-cli: 13.2.4
   	 @angular/language-service: 13.2.4
   	 @testing-library/angular: 11.0.2

**Comment by wmarques** [comment]
Ok it's solved, I didn't have the nx nor the @nrwl/workspace dependencies... Sorry !
