### ISSUE TITLE
New project: generatePackageJson doesn't include tslib as a dependency

### ISSUE THREAD

**Issue by jksaunders** [nrwl/nx#11012]
## Current Behavior
When a new workspace is created with a node app (eg. express) and the `generatePackageJson` option is set to true, `package.json` is missing `tslib` which is required since the `tsconfig.base.json` that comes with a new `nx` workspace uses `importHelpers: true`. This means that when pulled into a Docker container for deployment or similar, and `npm install` is run, `tslib` is excluded, and the build will fail.

## Expected Behavior
`tslib` should be included in the `package.json` file produced by the `generatePackageJson` option if `importHelpers: true`.

## Steps to Reproduce
Repo that demonstrates this behaviour: `https://github.com/jksaunders/nx-generate-package-json-tslib`
To use the example, run `npm install` then `nx build`, and observe that the generated `package.json` in the `dist/api` folder is missing `tslib`.

To reproduce from scratch:
- `npx create-nx-workspace --preset=express`
- `nx g @nrwl/express:app api`
- `nx build`
- observe that the generated `package.json` in the `dist/api` folder is missing `tslib`.

### Failure Logs
When `npm ci/install` is run in the container:
```
2022-06-29 11:16:12.392 MDT
Error: Cannot find module 'tslib'

2022-06-29 11:16:12.392 MDT
Require stack:
2022-06-29 11:16:12.392 MDT
- /usr/src/app/main.js
2022-06-29 11:16:12.392 MDT
 at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
2022-06-29 11:16:12.392 MDT
 at Module._load (node:internal/modules/cjs/loader:787:27)
2022-06-29 11:16:12.392 MDT
 at Module.require (node:internal/modules/cjs/loader:1012:19)
2022-06-29 11:16:12.392 MDT
 at require (node:internal/modules/cjs/helpers:102:18)
2022-06-29 11:16:12.392 MDT
 at Object.tslib (/usr/src/app/main.js:22:18)

2022-06-29 11:16:12.392 MDT
 at __webpack_require__ (/usr/src/app/main.js:46:41)
2022-06-29 11:16:12.392 MDT
 at /usr/src/app/main.js:59:17
2022-06-29 11:16:12.392 MDT
 at /usr/src/app/main.js:98:3
2022-06-29 11:16:12.392 MDT
 at Object.<anonymous> (/usr/src/app/main.js:103:12)
2022-06-29 11:16:12.392 MDT
 at Module._compile (node:internal/modules/cjs/loader:1112:14) {
2022-06-29 11:16:12.392 MDT
 code: 'MODULE_NOT_FOUND',
2022-06-29 11:16:12.392 MDT
 requireStack: [ '/usr/src/app/main.js' ]
2022-06-29 11:16:12.392 MDT
}
```

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 18.3.0
   OS   : darwin x64
   npm  : 8.11.0
   
   nx : 14.3.6
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : 14.3.6
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by DesertFoxNV** [comment]
I am seeing this as well.

**Comment by nartc** [comment]
Hi @jksaunders, thank you for reporting. I can't seem to reproduce the issue here. `tslib` isn't generated because it's not needed in the case of the reproduce steps.

I followed the reproduce steps and didn't run into any `tslib` error. Could you have missed any step in between?
<img width="805" alt="image" src="https://user-images.githubusercontent.com/25516557/182285023-973f57ae-0075-464c-aa59-0f96c1a50abc.png">

**Comment by jksaunders** [comment]
@nartc Thanks for trying it out! I don't have trouble locally if tslib is installed in the parent level `node_modules`. However, when installing it in a container with the generated `package.json`, it reports it missing on run since it's not included. 

To simulate this scenario locally, can you try deleting `tslib` from your parent level `node_modules` and seeing if you can still run without any issues?

**Comment by nartc** [comment]
@jksaunders thanks for the extra info. Unfortunately, still can't reproduce it with `tslib` gone from the workspace (all transitive deps are cleaned of tslib as well)

<img width="890" alt="image" src="https://user-images.githubusercontent.com/25516557/182286651-93ca9219-97f6-4315-9a79-e5276689ff91.png">

I also `cd dist/apps/api && npm install` then run `node main.js`, still works 
![Uploading image.png…]()

**Comment by nartc** [comment]
I just tested with a minimal dockerfile as well.

```dockerfile
FROM node:14.17-slim

WORKDIR /app

COPY ./dist/apps/api .

RUN npm install --production

EXPOSE 3333

CMD ["node", "./main.js"]
```

Then run:
```
docker build -f ./apps/api/dockerfile . -t api
docker run -p 3333:3333 api
```

<img width="553" alt="image" src="https://user-images.githubusercontent.com/25516557/182289432-4e6aacdc-6baf-4b68-87e0-08f082bc17bc.png">

**Comment by jksaunders** [comment]
@nartc My mistake! I thought for sure this was on a clean base project, but I didn't realize I had already installed two packages: `fastify` and `mercurius`. So this is not an issue for the base project, but still an issue not picking up on the `tslib` dependency. Sorry for the wasted time trying to reproduce it on the base project!

I've updated the sample repo: https://github.com/jksaunders/nx-generate-package-json-tslib. I've just confirmed that it does need `tslib`, is not being added to the generated `package.json`, and will fail building if `tslib` is deleted from the parent `node_modules`. Let me know if you see what I'm seeing with these two packages (I _think_ `mercurius` is the offending one).

**Comment by nartc** [comment]
@jksaunders Gotcha. I'm afraid in this case, transitive deps of deps aren't inferrable by Nx (especially when both `fastify` and `mecurius` do not specify `tslib` anywhere in their `package.json`). 

What you can do to workaround this is to install `tslib` separately in the container. Eg in a Dockerfile

```dockerfile
FROM node:14.17-slim

WORKDIR /app

COPY ./dist/apps/api .

RUN npm install --production
# install transitive deps
RUN npm install tslib

EXPOSE 3333

CMD ["node", "./main.js"]
```

Would this be sufficient enough?

**Comment by jksaunders** [comment]
@nartc I should clarify, it's not actually the fault of those packages - it's from the `importHelpers: true` value in the top level `tsconfig.base.json`, which is the default value in a newly generated Nx Express workspace. The `package.json` in the base generated Nx workspace comes with `tslib` listed as a dependency to account for this (I'm assuming) but is not included in the generated `package.json` generated by `generatePackageJson`, which I believe is not intended behaviour.

Setting `importHelpers: false` builds `.js` files that don't require `tslib`, but I'm thinking there must be a way to include `tslib` as a dependency in the generated `package.json` if the loaded `tsconfig` at build time has `includeHelpers: true`, which is the current default for Nx Express workspaces. Does that make sense?

Also yes, I'm currently installing `tslib` separately in app's Docker container, that is definitely a usable workaround!

**Comment by ankuragrwl** [comment]
I did the following and it worked for me:

In the nestjs App's project.json file, configure **generatePackageJson** : **true**  inside the build configuration section.

Then add  `RUN npm --prefix api-gateway --omit=dev -f install` to the Dockerfile
