### ISSUE TITLE
CLI error when dependency is missing

### ISSUE THREAD

**Issue by richtera** [nrwl/nx#11077]
## Current Behavior
When a npm dependency is physically missing but still referenced this error will show

```sh
> nx run server:serve:development --host=0.0.0.0

Debugger attached.
Debugger attached.

 >  NX   Cannot read property 'type' of undefined
```

## Expected Behavior
It should say something like unable to find dependency "name".
using --verbose you can see the actual stack trace
```javascript
TypeError: Cannot read property 'type' of undefined
    at /home/andy/Development/nx-workspace/node_modules/@nrwl/workspace/src/utilities/buildable-libs-utils.js:25:21
    at Array.map (<anonymous>)
    at calculateProjectDependencies (/home/andy/Development/nx-workspace/node_modules/@nrwl/workspace/src/utilities/buildable-libs-utils.js:22:10)
    at calculateResolveMappings (/home/andy/Development/nx-workspace/node_modules/@nrwl/node/src/executors/node/node.impl.js:62:86)
    at nodeExecutor_1 (/home/andy/Development/nx-workspace/node_modules/@nrwl/node/src/executors/node/node.impl.js:37:26)
    at nodeExecutor_1.next (<anonymous>)
    at resume (/home/andy/Development/nx-workspace/node_modules/@nrwl/node/node_modules/tslib/tslib.js:225:48)
    at /home/andy/Development/nx-workspace/node_modules/@nrwl/node/node_modules/tslib/tslib.js:224:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (/home/andy/Development/nx-workspace/node_modules/@nrwl/node/node_modules/tslib/tslib.js:224:67)
```
Within the buildable-libs-utils.js file:
The error happens on this line
```javascript
if (depNode.type === 'lib') {
```
adding a new
```javascript
if (!depNode) {
   console.error('Unable to find dependency', dep);
}
```
in front of this line results in:
Unable to find dependency npm:jsonwebtoken
in my particular case.

## Steps to Reproduce
Take a working nx project and artificially yarn remove or npm uninstall a required dependency.

### Environment
```sh
$ yarn nx report

 >  NX   Report complete - copy this into the issue template

   Node : 14.17.5
   OS   : linux x64
   yarn : 3.2.0
   
   nx : 14.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : 14.4.2
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.4.2
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : 14.4.2
   @nrwl/react : 14.4.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
An improvement on the error message would definitely help out, do you want to open a PR with the changes you suggested?

**Comment by richtera** [comment]
https://github.com/nrwl/nx/pull/11080
