### ISSUE TITLE
Error: Cannot find module '@nrwl/workspace/src/utilities/perf-logging'

### ISSUE THREAD

**Issue by amirsaran3** [nrwl/nx#11108]
I tried doing `nx migrate latest` and then `nx migrate --run-migrations`, but it returns an error: `Cannot find module '@nrwl/workspace/src/utilities/perf-logging'`.

This is the project I am trying to upgrade: https://github.com/near/wallet-selector

OS: Windows 10
Node version: v14.18.1
NPM version: 8.8.0

**Comment by AgentEnder** [comment]
Can you provide more of the error message? If that is all that is provided can you check with NX_VERBOSE_LOGGING set to true?

Are you using any non first party plugins? Can you run `nx report`?

**Comment by smallstepstoday** [comment]
Experiencing the same issue. Here is the error output from my build: 

```
> npx nx build [project] --configuration production                 
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@nrwl/workspace/src/utilities/perf-logging'
Require stack:
- /Users/david/Projects/.../node_modules/@nrwl/cli/lib/init-local.js
- /Users/david/Projects/.../node_modules/@nrwl/cli/bin/nx.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/Users/david/Projects/.../node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.initLocal (/Users/david/Projects/.../node_modules/@nrwl/cli/lib/init-local.js:17:5)
    at Object.<anonymous> (/Users/david/Projects/.../node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/david/Projects/.../node_modules/@nrwl/cli/lib/init-local.js',
    '/Users/david/Projects/.../node_modules/@nrwl/cli/bin/nx.js'
  ]
}
```
With the following:
```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.5.5
   
   nx : 14.4.2
   @nrwl/angular : 14.4.2
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : 14.4.2
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.4.2
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

(node:36155) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/david/Projects/.../node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by AgentEnder** [comment]
This still looks like out of sync versions to me, but it doesn't show up in Nx report since the package that is out of sync appears to be @nrwl/cli

You can remove that package, since it's functionality has been moved to the main Nx package.
