### ISSUE TITLE
Storybook angular don't work if follow tutorial steps

### ISSUE THREAD

**Issue by ddtch** [nrwl/nx#11118]
## Current Behavior
Storybooks don't run. Crashes with error 

## Expected Behavior
Storybook runs properly

## Steps to Reproduce
So I have usual monorepo with NX. I have 3 apps in it and a UI library. I installed storybook [following docs](https://nx.dev/storybook/overview-angular). Everything is ok but once use command `nx run ui:storybook`, I have an error

### Failure Logs
```
> nx run ui:storybook
info => Loading presets
(node:12731) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /monorepo/path/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
info Addon-docs: using MDX1
info => Using implicit CSS loaders
info => Loading angular-cli config for angular 12.2.x
info => Using angular browser target options from "ui:build-storybook"
info => Using angular project with "tsConfig:/monorepo/path/libs/ui/.storybook/tsconfig.json"
ERR! TypeError: getTypeScriptConfig is not a function
ERR!     at /monorepo/path/node_modules/.pnpm/@storybook+angular@6.5.9_t7vatw5yz57kcw3cq4ba5bl5l4/node_modules/@storybook/angular/dist/ts3.9/server/angular-cli-webpack-12.2.x.js:32:175
ERR!     at generateWebpackConfig (/monorepo/path/node_modules/.pnpm/@angular-devkit+build-angular@0.1102.18_5dmnvfwmrb4eo4i7mxcir5syjq/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:45:49)
ERR!     at async generateBrowserWebpackConfigFromContext (/monorepo/path/node_modules/.pnpm/@angular-devkit+build-angular@0.1102.18_5dmnvfwmrb4eo4i7mxcir5syjq/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:136:20)
ERR!     at async generateI18nBrowserWebpackConfigFromContext (/monorepo/path/node_modules/.pnpm/@angular-devkit+build-angular@0.1102.18_5dmnvfwmrb4eo4i7mxcir5syjq/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:77:20)
ERR!  TypeError: getTypeScriptConfig is not a function
ERR!     at /monorepo/path/node_modules/.pnpm/@storybook+angular@6.5.9_t7vatw5yz57kcw3cq4ba5bl5l4/node_modules/@storybook/angular/dist/ts3.9/server/angular-cli-webpack-12.2.x.js:32:175
ERR!     at generateWebpackConfig (/monorepo/path/node_modules/.pnpm/@angular-devkit+build-angular@0.1102.18_5dmnvfwmrb4eo4i7mxcir5syjq/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:45:49)
ERR!     at async generateBrowserWebpackConfigFromContext (/monorepo/path/node_modules/.pnpm/@angular-devkit+build-angular@0.1102.18_5dmnvfwmrb4eo4i7mxcir5syjq/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:136:20)
ERR!     at async generateI18nBrowserWebpackConfigFromContext (/monorepo/path/node_modules/.pnpm/@angular-devkit+build-angular@0.1102.18_5dmnvfwmrb4eo4i7mxcir5syjq/node_modules/@angular-devkit/build-angular/src/utils/webpack-browser-config.js:77:20)
```

### Environment
```
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin arm64
   pnpm : 7.5.1
   
   nx : 14.4.2
   @nrwl/angular : 11.6.3
   @nrwl/cypress : 11.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 11.6.3
   @nrwl/eslint-plugin-nx : 11.6.3
   @nrwl/express : Not Found
   @nrwl/jest : 11.6.3
   @nrwl/js : Not Found
   @nrwl/linter : 11.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : Not Found
   @nrwl/workspace : 11.6.3
   typescript : 4.1.6
   ---------------------------------------
   Community plugins:
   	 @ionic/angular: 5.0.7
   	 @ngrx/effects: 11.1.1
   	 @ngrx/entity: 11.1.1
   	 @ngrx/schematics: 10.1.2
   	 @ngrx/store: 11.1.1
   	 @ngrx/store-devtools: 11.1.1
   	 rxjs: 6.6.7
   	 @nxtend/capacitor: 11.1.1
   	 @nxtend/ionic-angular: 11.1.1

(node:16392) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /PATH/monorepo/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

```

My clues is maybe because storybook and NX uses different webpack versions. Any ideas or suggestions?

**Comment by mandarini** [comment]
Hmmmm @ddtch, here's the thing. For me it works. Can you please share your repository with me, to try to figure this out?

Here is my Nx report:
```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   npm  : 8.3.1

   nx : 14.4.2
   @nrwl/angular : 14.4.2
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 999.9.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @storybook/angular: 6.5.9

```

**Comment by ddtch** [comment]
@mandarini, you mean the repo of my project? ) of course I can not share it )

**Comment by mandarini** [comment]
Hi there @ddtch ! Haha, no I did not mean that you should share the repo of your private project! :) I am sorry if I did not convey what I meant correctly, I am not a native speaker and sometimes it's a struggle! :) I actually meant if you can share a repository reproducing the issue (sort of a minimum reproduction), which will make this easier for me to test and debug, so that I can help you!

**Comment by ddtch** [comment]
@mandarini  ok I got you ) so the problem is, in fresh new created repo https://github.com/ddtch/nx-demo it seems like everything is works like a charm. But I don't understand why in my I have problems? May it be BCS of pnpm? or again different webpack versions? any suggestions any clues?

**Comment by mandarini** [comment]
Ohhhhhhhhh sorry I am so silly!!!! I just checked your Nx report more closely!!!!!

So, you see your `@nrwl/storybook` package version does not match the version of the rest of the `@nrwl/*` packages. The versions should match, or else things don't work!! So, please match the versions, and everything will work! :)

**Comment by ddtch** [comment]
@mandarini ok, I got you. Will try to align all versions and try again. Thank you a lot for helping... and... offtopic

I just mention your nickname 'mandarini' - in Georgian 🇬🇪 language means oranges )))
And I just looked at your profiles on tw ln, you are so beautiful )
