### ISSUE TITLE
Default Storybook doesn't work with an initial NX application

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [nrwl/nx#11124]
Hello guys, 
I've tried to add the storybook to my existing project but it didn't work, so I decided to create totally new workspace with storybook but it didn't work aswell.

## Current Behavior
Following default storybook configuration crashes with errors.
`https://nx.dev/storybook/overview-angular`

## Expected Behavior
Storybook runs properly under `apps` and `libs`.

## Steps to Reproduce

Create angular workspace
`npx create-nx-workspace@latest --preset=angular`

Create library (from nx plugin):
`node node_modules/@nrwl/cli/bin/nx.js generate @nrwl/angular:library --name=xxx --unitTestRunner=jest --strict --linter=eslint --compilationMode=full --no-interactive`

Create component in library and put it into apps main html - just to display the initial component.

Install storybook:
`npm install --dev @nrwl/storybook`

Create storybook configuration (lql is my workspace name):
`nx g @nrwl/angular:storybook-configuration lql`

Run storybook:
`nx run lql:storybook`

### Failure Logs
```
WARNING in DefinePlugin
Conflicting values for 'process.env.NODE_ENV'

1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

manager (webpack 5.73.0) compiled with 2 warnings in 5961 ms
99% done plugins webpack-hot-middlewarewebpack built preview ac3c105dbbf303fc096b in 6732ms
WARN Force closed manager build
ModuleBuildError: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /Users/michalgrzegorczyk/Desktop/programowanie/test-stroy/lql/apps/lql/src/polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at /Users/michalgrzegorczyk/Desktop/programowanie/test-stroy/lql/node_modules/@ngtools/webpack/src/ivy/loader.js:64:26
    at processResult (/Users/michalgrzegorczyk/Desktop/programowanie/test-stroy/lql/node_modules/webpack/lib/NormalModule.js:758:19)
    at /Users/michalgrzegorczyk/Desktop/programowanie/test-stroy/lql/node_modules/webpack/lib/NormalModule.js:860:5
    at /Users/michalgrzegorczyk/Desktop/programowanie/test-stroy/lql/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /Users/michalgrzegorczyk/Desktop/programowanie/test-stroy/lql/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/Users/michalgrzegorczyk/Desktop/programowanie/test-stroy/lql/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/michalgrzegorczyk/Desktop/programowanie/test-stroy/lql/node_modules/@ngtools/webpack/src/ivy/loader.js:64:17


 >  NX   Broken build, fix the error above.

   You may need to refresh the browser.
```

### Environment
```
Node : 16.14.0
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 14.4.2
   @nrwl/angular : 14.4.2
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @storybook/angular: 6.5.9
```

**Comment by mandarini** [comment]
Oh noo!!

**Comment by mandarini** [comment]
Hmmm @michalgrzegorczyk-dev here's the thing. For me it works. Can you share your repository, please?

Here's my Nx report:

```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   npm  : 8.3.1

   nx : 14.4.2
   @nrwl/angular : 14.4.2
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 999.9.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @storybook/angular: 6.5.9

```

**Comment by mandarini** [comment]
Ohhhhhhh!!!!! I saw the error, sorry!!!! 

Can you add 

```
"files": ["../src/polyfills.ts"],
```

inside your project's `.storybook/tsconfig.json`? For you that would be `apps/lql/.storybook/tsconfig.json` or something!

And you are correct, I must add this in the template!! :D We recently modified that template.
