### ISSUE TITLE
nx/packages/cypress/: Unable to resolve @nrwl/cypress:migrate-to-cypress-10.

### ISSUE THREAD

**Issue by Shooshte** [nrwl/nx#11207]
### Documentation issue

- [ ] Reporting a typo
- [ X ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Enter the URL or documentation section here.](https://nx.dev/packages/cypress/generators/migrate-to-cypress-10)

### Additional context or description

The documentation mentions that it's possible to migrate a Cypress e2e project from v8/v9 to Cypress v10. The current published version of @nrwl/cypress (14.4.3) has a peer dependency of cypress@>= 3 < 10.

When I try running `nx g @nrwl/cypress:migrate-to-cypress-10` (the command from the documentation page) I get the following error:

> NX   Unable to resolve @nrwl/cypress:migrate-to-cypress-10.
> 
>    Cannot find generator 'migrate-to-cypress-10' in /Users/shooshte/Work/PersonalProjects/mavrica/node_modules/@nrwl/cypress/generators.json.
> 
> Error: Unable to resolve @nrwl/cypress:migrate-to-cypress-10.
> Cannot find generator 'migrate-to-cypress-10' in /Users/shooshte/Work/PersonalProjects/mavrica/node_modules/@nrwl/cypress/generators.json.
>     at Workspaces.readGenerator (/Users/shooshte/Work/PersonalProjects/mavrica/node_modules/nx/src/config/workspaces.js:144:19)
>     at Object.<anonymous> (/Users/shooshte/Work/PersonalProjects/mavrica/node_modules/nx/src/command-line/generate.js:216:92)
>     at Generator.next (<anonymous>)
>     at fulfilled (/Users/shooshte/Work/PersonalProjects/mavrica/node_modules/tslib/tslib.js:115:62)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

This is my package.json file:
```
{
  "name": "mavrica",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test"
  },
  "private": true,
  "dependencies": {
    "@next-auth/neo4j-adapter": "^1.0.3",
    "@sentry/nextjs": "^7.6.0",
    "@uppy/aws-s3": "^2.2.1",
    "@uppy/aws-s3-multipart": "^2.4.1",
    "@uppy/core": "^2.3.1",
    "@uppy/react": "^2.2.2",
    "aws-sdk": "^2.1162.0",
    "axios": "^0.27.2",
    "neo4j-driver": "^4.4.6",
    "next": "12.1.6",
    "next-auth": "^4.9.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-virtuoso": "^2.16.1",
    "uppy": "^2.12.3",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@nrwl/cli": "14.4.3",
    "@nrwl/cypress": "^14.4.3",
    "@nrwl/eslint-plugin-nx": "14.4.3",
    "@nrwl/express": "14.4.3",
    "@nrwl/jest": "14.4.3",
    "@nrwl/linter": "14.4.3",
    "@nrwl/next": "14.4.3",
    "@nrwl/node": "14.4.3",
    "@nrwl/nx-cloud": "14.2.0",
    "@nrwl/react": "14.4.3",
    "@nrwl/web": "14.4.3",
    "@nrwl/workspace": "14.4.3",
    "@types/cors": "^2.8.12",
    "@types/express": "4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "18.0.0",
    "@types/react": "18.0.14",
    "@types/react-dom": "18.0.5",
    "@types/supertest": "^2.0.12",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "5.30.7",
    "@typescript-eslint/parser": "5.30.7",
    "babel-jest": "27.5.1",
    "cypress": "^9.7.0",
    "eslint": "~8.15.0",
    "eslint-config-next": "12.1.6",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jsx-a11y": "6.6.0",
    "eslint-plugin-react": "7.30.1",
    "eslint-plugin-react-hooks": "4.6.0",
    "jest": "27.5.1",
    "nx": "14.4.3",
    "prettier": "^2.6.2",
    "react-test-renderer": "18.2.0",
    "sass": "1.52.3",
    "supertest": "^6.2.4",
    "ts-jest": "27.1.4",
    "ts-node": "~10.8.0",
    "tslib": "^2.4.0",
    "typescript": "~4.7.2"
  }
}
```

**Comment by nsmith7989** [comment]
Looks to be unreleased generator. It [exists on master](https://github.com/nrwl/nx/blob/master/packages/cypress/generators.json)

but the latest @nrwl/cypress@14.4.3 contains no such generator.

**Comment by andy-ta** [comment]
Related: #11215

**Comment by Shooshte** [comment]
No related to this issue, so no need to reopen, but is there a release date planned? Excited to migrate to cypress 10 :)

**Comment by JustusNBB** [comment]
@Shooshte Upgrade to nx v.14.5 https://github.com/nrwl/nx/releases/tag/14.5.0 then you can run this migration

**Comment by fyodorio** [comment]
Anyone did that already? How it works with big/huge repos?
