### ISSUE TITLE
Nx init fails for Yarn 2+

### ISSUE THREAD

**Issue by PowerOfM** [nrwl/nx#11246]
## Current Behavior
`yarn nx init` fails when it attempts to run `yarn list` in a workspace with Yarn v3.

## Expected Behavior
The init script should check for Yarn v3 and use the proper command (ex: `yarn info --name-only`)

## Steps to Reproduce
- `git clone https://github.com/nrwl/nx-examples`
- `yarn set version berry`
- `yarn install`
- `yarn nx init`

### Failure Logs
```
❯ yarn nx init
nx.js init

Adds nx.json file and installs nx if not installed already

Options:
  --help     Show help                                                                                                                                                                                                 [boolean]
  --version  Show version number                                                                                                                                                                                       [boolean]

Error: Command failed: yarn list
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.initHandler (/home/powerofm/MMoser/unify/.yarn/unplugged/nx-virtual-874d868c53/node_modules/nx/src/command-line/init.js:10:58)
    at /home/powerofm/MMoser/unify/.yarn/unplugged/nx-virtual-874d868c53/node_modules/nx/src/command-line/nx-commands.js:187:140
    at Generator.next (<anonymous>)
    at fulfilled (/home/powerofm/MMoser/unify/.yarn/cache/tslib-npm-2.4.0-9cb6dc5030-8c4aa6a3c5.zip/node_modules/tslib/tslib.js:115:62) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 1b 5b 33 31 6d 1b 5b 31 6d 55 73 61 67 65 20 45 72 72 6f 72 1b 5b 32 32 6d 1b 5b 33 39 6d 3a 20 43 6f 75 6c 64 6e 27 74 20 66 69 6e 64 20 61 20 73 63 ... 123 more bytes>,
    <Buffer >
  ],
  pid: 68052,
  stdout: <Buffer 1b 5b 33 31 6d 1b 5b 31 6d 55 73 61 67 65 20 45 72 72 6f 72 1b 5b 32 32 6d 1b 5b 33 39 6d 3a 20 43 6f 75 6c 64 6e 27 74 20 66 69 6e 64 20 61 20 73 63 ... 123 more bytes>,
  stderr: <Buffer >
}
```

### Environment
_Unable to run `nx report` because nx can't be set up._
Node: 16.16.0
OS: Linux x64
yarn: 3.2.1
nx: 14.4.3

**Comment by AgentEnder** [comment]
Yarn 2+ support is tracked in https://github.com/nrwl/nx/issues/2386
