### ISSUE TITLE
Migration `update-14-4-3/add-dev-output-path` fails

### ISSUE THREAD

**Issue by Tirke** [nrwl/nx#11277]
## Current Behavior

I can't apply this migration file

```
{
  "migrations": [
    {
      "cli": "nx",
      "version": "14.4.3-beta.0",
      "description": "Add a development outputPath to avoid conflict with the production build.",
      "factory": "./src/migrations/update-14-4-3/add-dev-output-path",
      "package": "@nrwl/next",
      "name": "add-dev-output-path"
    }
  ]
}
```
```
>  NX  Running migrations from 'migrations.json'

Running migration add-dev-output-path

 >  NX   Unable to determine implementation path for "/Users/tirke/code/monorepo/node_modules/.pnpm/@nrwl+next@14.4.2_tccwfqyryppdo3pzoeoi3zgxxi/node_modules/@nrwl/next/migrations.json:add-dev-output-path" using collection.schematics

   Pass --verbose to see the stacktrace.

Command failed: /var/folders/dn/zfmw02m54f125nx0sbdpmc6w0000gn/T/tmp-6331-2PBF20l050QH/node_modules/.bin/nx _migrate --run-migrations
```

## Expected Behavior

The migration can be applied.

## Steps to Reproduce

`project.json` of one front app using next
```
{
  "$schema": "../../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/front/front-legacy",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nrwl/next:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "root": "apps/front/front-legacy",
        "outputPath": "dist/apps/front/front-legacy",
        "assets": [
          {
            "input": "apps/front/front-legacy/public",
            "glob": "**/*",
            "output": "."
          },
          {
            "input": "libs/front/translations/assets",
            "glob": "**/*",
            "output": "."
          },
          {
            "input": "apps/front/front-legacy/config",
            "glob": "**/*",
            "output": "./../config"
          },
          {
            "input": "apps/front/front-legacy",
            "glob": "**/next-i18next.config.js",
            "output": "./.."
          }
        ]
      },
      "configurations": {
        "development": {},
        "production": {}
      }
    },
    "serve": {
      "executor": "@nrwl/next:server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "front-legacy:build",
        "dev": true,
        "port": 3000
      },
      "configurations": {
        "development": {
          "buildTarget": "front-legacy:build:development",
          "dev": true
        },
        "production": {
          "buildTarget": "front-legacy:build:production",
          "dev": false
        }
      }
    },
    "export": {
      "executor": "@nrwl/next:export",
      "options": {
        "buildTarget": "front-legacy:build:production"
      }
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["coverage/apps/front/front-legacy"],
      "options": {
        "jestConfig": "apps/front/front-legacy/jest.config.ts",
        "passWithNoTests": true
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/front/front-legacy/**/*.{ts,tsx,js,jsx}"]
      }
    },
    "typecheck": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "command": "pnpm exec tsc -b ./apps/front/front-legacy --pretty"
      }
    },
    "sonar": {
      "executor": "@nrwl/workspace:run-commands",
      "outputs": [],
      "options": {
        "command": "sonar-scanner",
        "cwd": "apps/front/front-legacy"
      }
    },
    "build-storybook": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "command": "pnpm storybook:build"
      }
    },
    "copy-translations": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "command": "echo front-legacy: copying locales from translations lib... && cp -R ./libs/front/translations/assets/locales ./apps/front/front-legacy/public/"
      }
    }
  },
  "tags": []
}
```
### Failure Logs

```
 >  NX   Unable to determine implementation path for "/Users/tirke/code/monorepo/node_modules/.pnpm/@nrwl+next@14.4.2_tccwfqyryppdo3pzoeoi3zgxxi/node_modules/@nrwl/next/migrations.json:add-dev-output-path" using collection.schematics
```

### Environment

```
❯ pnx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin arm64
   pnpm : 7.5.2

   nx : 14.4.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : 14.4.3
   @nrwl/next : 14.4.2
   @nrwl/node : 14.4.3
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   ```

**Comment by Khumozin** [comment]
I'm also having the same issue with `nx migrate latest` and `nx migrate --run-migrations`

**Comment by ntgussoni** [comment]
Having the same issue.
Error
```
Running migration add-default-development-configurations-14.0.0

 >  NX   Unable to determine implementation path for "/Users/nicolast/Documents/projects/developer-hub/node_modules/.pnpm/@nrwl+next@13.9.6_ad509d3f3696b6c3e441fd5e6257e201/node_modules/@nrwl/next/migrations.json:add-default-development-configurations-14.0.0" using collection.schematics


Error: Unable to determine implementation path for "/Users/nicolast/Documents/projects/developer-hub/node_modules/.pnpm/@nrwl+next@13.9.6_ad509d3f3696b6c3e441fd5e6257e201/node_modules/@nrwl/next/migrations.json:add-default-development-configurations-14.0.0" using collection.schematics
    at /private/var/folders/dh/fycwz5550xv8khjxyjdzrhdm0000gp/T/tmp-74874-67rbTqrh4zBl/node_modules/.pnpm/nx@14.4.3/node_modules/nx/src/command-line/migrate.js:708:19
    at Generator.next (<anonymous>)
    at /private/var/folders/dh/fycwz5550xv8khjxyjdzrhdm0000gp/T/tmp-74874-67rbTqrh4zBl/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/private/var/folders/dh/fycwz5550xv8khjxyjdzrhdm0000gp/T/tmp-74874-67rbTqrh4zBl/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:114:16)
    at runNxMigration (/private/var/folders/dh/fycwz5550xv8khjxyjdzrhdm0000gp/T/tmp-74874-67rbTqrh4zBl/node_modules/.pnpm/nx@14.4.3/node_modules/nx/src/command-line/migrate.js:702:20)
    at /private/var/folders/dh/fycwz5550xv8khjxyjdzrhdm0000gp/T/tmp-74874-67rbTqrh4zBl/node_modules/.pnpm/nx@14.4.3/node_modules/nx/src/command-line/migrate.js:617:23
    at Generator.next (<anonymous>)
    at fulfilled (/private/var/folders/dh/fycwz5550xv8khjxyjdzrhdm0000gp/T/tmp-74874-67rbTqrh4zBl/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:115:62)
Command failed: /var/folders/dh/fycwz5550xv8khjxyjdzrhdm0000gp/T/tmp-74874-67rbTqrh4zBl/node_modules/.bin/nx _migrate --run-migrations --verbose
```
Here's my report 
```
  Node : 14.17.6
   OS   : darwin x64
   pnpm : 6.11.0
   
   nx : 14.4.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/express : 14.4.3
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : Not Found
   @nrwl/next : 13.9.6
   @nrwl/node : 14.4.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
         @nx-tools/nx-prisma: 2.0.0-alpha.4
```

**Comment by Binimow** [comment]
I had a similar issue trying to update to version 14 where a migration was unable to be found for @nrwl/angular. My problem was that @nrwl/angular didn't update automatically when preparing the migration. I had to modify the package.json to explicitly set the version to 14.4.3 and then run yarn install. I see your version for @nrwl/next is 13.9.6. The migration may not be present in that version and it may not be updating automatically.

Tell me if it works, best regards.

**Comment by Tirke** [comment]
Thanks to @Binimow, I've pinpointed the issue to a duplicate entry of `@nrwl/next` in `package.json`, which may have been the culprit. Removing `@nrwl/next` and adding it back to only devDeps did the trick and fixed the error.
Closing :)
