### ISSUE TITLE
couldn't migrate to nx v14, tried backing down to v13 get different error

### ISSUE THREAD

**Issue by EMCP** [nrwl/nx#11367]
I have a project which utilizes `nx` .. and followed these migration commands

```
nx migrate latest
nx migrate --run-migrations
```

```
nx migrate 13.10.5
nx migrate --run-migrations
```

I found these notes https://github.com/nrwl/nx/issues/7613 but still unclear how best to proceed if I get an error while running the 2nd command `--run-migrations`

here's my output from `nx report`

```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 14.20.0
   OS   : linux x64
   npm  : 6.14.17
   
   nx : 14.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : Not Found
   typescript : Not Found
   ---------------------------------------
   Community plugins:
         ngx-build-plus: 12.0.1
         rxjs: 6.6.7
```

Im unsure which error to start with first.. the one migrating to v14 or v13.. here's the v13 error trace

```

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2022-07-29T23_38_07_973Z-debug.log

 >  NX   Command failed: npm install

   Pass --verbose to see the stacktrace.

/home/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /tmp/tmp-37931-dayMaVhmvuvq/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at Object.handler (/home/emcp/Dev/git/JRGEMCP_MAHRIO/mahrio-two-one/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:90:25)
    at Object.runCommand (/home/emcp/Dev/git/JRGEMCP_MAHRIO/mahrio-two-one/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/emcp/Dev/git/JRGEMCP_MAHRIO/mahrio-two-one/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/home/emcp/Dev/git/JRGEMCP_MAHRIO/mahrio-two-one/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/home/emcp/Dev/git/JRGEMCP_MAHRIO/mahrio-two-one/node_modules/@nrwl/cli/lib/init-local.js:26:79)
    at Object.<anonymous> (/home/emcp/Dev/git/JRGEMCP_MAHRIO/mahrio-two-one/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 38026,
  stdout: null,
  stderr: null
}
$ nx format
Cannot find module '@nrwl/workspace/src/utilities/perf-logging'
Require stack:
- /home/Dev/git/node_modules/nx/src/cli/init-local.js
- /home/Dev/git/node_modules/nx/bin/nx.js
- /home/.nvm/versions/node/v14.20.0/lib/node_modules/nx/bin/nx.js

```

**Comment by EMCP** [comment]
if I do a `npm i --production=false` and try again, I get the same error upgrading to v13.. as I did when trying to go straight to v14

```
Please run npm install to ensure the correct version of Nx is installed.
Ran 13-9-0-replace-tao-with-nx from @nrwl/workspace
  Replace @nrwl/tao with nx

  UPDATE package.json
---------------------------------------------------------
Ran 13-10-0-update-tasks-runner from @nrwl/workspace
  Update the tasks runner property to import it from the nx package instead of @nrwl/worksapce

  UPDATE nx.json
---------------------------------------------------------

 ERROR  Failed to run update-testing-imports from @nrwl/angular. This workspace is NOT up to date!


 >  NX   Cannot read property 'replace' of undefined

   Pass --verbose to see the stacktrace.

Command failed: /tmp/tmp-44541-E3XCskaG9HPU/node_modules/.bin/nx _migrate --run-migrations

```

**Comment by AgentEnder** [comment]
Can you try to remove the global install of Nx? Sometimes the version of it can conflict with your workspace's version of Nx and it seems like that may be happening here. Instead, invoke Nx from the workspace itself using `npx nx...`

**Comment by EMCP** [comment]
okay I have done fresh clone of the project..

```
npm i --production=false
npx nx migrate latest
npm nx migration --run-migrations
```

Once I can confirm the build is good I can come back and report

Thanks for the tip !  Had no idea about NRWL .. just inheriting this from a colleague

**Comment by EMCP** [comment]
okay my error related to the last message above was fixed, via https://github.com/nrwl/nx/issues/9168#issuecomment-1057897421

I need to do some more testing.. and then if it looks okay bump even further to 14.. but let's close this for now.. big thank you again for the tip on npx!
