### ISSUE TITLE
Cypress component testing - Component spec generator fails for libs

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#11373]
## Current Behavior

`nx g @nrwl/react:component-cypress-spec` fails for libs

## Expected Behavior
Should generate spec as documented

## Steps to Reproduce
* Create nx workspace @ 14.5.1
* Create a React lib (e.g. name `ui`)
* Add Cypress component configuration
* Run `nx g @nrwl/react:component-cypress-spec --project=ui`

Result:
```sh
>  NX   Cannot read properties of undefined (reading 'root')


TypeError: Cannot read properties of undefined (reading 'root')
    at createComponentSpecFile (/Users/dan/work/cypress-ct-nx/node_modules/@nrwl/react/src/generators/component-cypress-spec/component-cypress-spec.js:36:66)
    at componentCypressGenerator (/Users/dan/work/cypress-ct-nx/node_modules/@nrwl/react/src/generators/component-cypress-spec/component-cypress-spec.js:9:5)
    at Object.<anonymous> (/Users/dan/work/cypress-ct-nx/node_modules/nx/src/command-line/generate.js:227:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dan/work/cypress-ct-nx/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```sh
>  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 14.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.1
   @nrwl/eslint-plugin-nx : 14.5.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.1
   @nrwl/js : 14.5.1
   @nrwl/linter : 14.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.1
   @nrwl/web : 14.5.1
   @nrwl/workspace : 14.5.1
   typescript : 4.7.4

```

**Comment by barbados-clemens** [comment]
thanks for the report @danr-za but that generator is for Cypress testing with storybook not Cypress component testing, (confusing I know) 
the generators for cypress component testing are 
`@nrwl/react:cypress-component-configuration` and `@nrwl/react:component-test`

the error you're seeing is `@nrwl/react:cypress-component-spec` unable to find the e2e test to generate the cypress e2e specs for storybook

**Comment by danr-za** [comment]
oh, was confusing indeed.
thanks
