### ISSUE TITLE
React Nx Tutorial does not work with 14.5.x

### ISSUE THREAD

**Issue by aautem** [nrwl/nx#11431]
## Current Behavior

When using `npx create-nx-workspace@latest` to create a React workspace as documented in the [React Nx Tutorial](https://nx.dev/react-tutorial/01-create-application), I am not able to `serve` my application due to a Webpack error:

```
My-MBP my-project % nx serve my-app

> nx run my-app:serve:development

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:4200/, http://127.0.0.1:4200/
<i> [webpack-dev-server] 404s will fallback to '/index.html'

>  NX  Web Development Server is listening at http://localhost:4200/

<e> [webpack-dev-middleware] HookWebpackError: Only file and data URLs are supported by the default ESM loader
<e>     at makeWebpackError (/Documents/my-project/node_modules/webpack/lib/HookWebpackError.js:48:9)
<e>     at /Documents/my-project/node_modules/webpack/lib/Compilation.js:3060:12
<e>     at eval (eval at create (/Documents/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:46:1)
<e>     at /Documents/my-project/node_modules/webpack/lib/Compilation.js:510:26
<e>     at /Documents/my-project/node_modules/copy-webpack-plugin/dist/index.js:708:13
<e> -- inner error --
<e> Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
<e>     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:720:11)
<e>     at Loader.resolve (internal/modules/esm/loader.js:97:40)
<e>     at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
<e>     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
<e>     at link (internal/modules/esm/module_job.js:41:36)
<e> caused by plugins in Compilation.hooks.processAssets
<e> Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
<e>     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:720:11)
<e>     at Loader.resolve (internal/modules/esm/loader.js:97:40)
<e>     at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
<e>     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
<e>     at link (internal/modules/esm/module_job.js:41:36)
```

## Expected Behavior

Apps should compile successfully. Here's the output when using `npx create-nx-workspace@14.4.3` instead of `@latest`:

```
My-MBP my-project % nx serve my-app

> nx run my-app:serve:development

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:4200/, http://127.0.0.1:4200/
<i> [webpack-dev-server] 404s will fallback to '/index.html'

>  NX  Web Development Server is listening at http://localhost:4200/

Entrypoint main [big] 1.6 MiB (1.88 MiB) = runtime.js 50.8 KiB vendor.js 1.49 MiB main.js 57.6 KiB 3 auxiliary assets
Entrypoint polyfills [big] 764 KiB (927 KiB) = runtime.js 50.8 KiB polyfills.js 713 KiB 2 auxiliary assets
Entrypoint styles [big] 431 KiB (534 KiB) = runtime.js 50.8 KiB styles.css 398 bytes styles.js 380 KiB 2 auxiliary assets
chunk (runtime: runtime) main.js (main) 49.3 KiB [initial] [rendered]
chunk (runtime: runtime) polyfills.js (polyfills) 665 KiB [initial] [rendered]
chunk (runtime: runtime) runtime.js (runtime) 34.1 KiB [entry] [rendered]
chunk (runtime: runtime) styles.css, styles.js (styles) 363 KiB (javascript) 397 bytes (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) vendor.js (vendor) (id hint: vendor) 1.48 MiB [initial] [rendered] split chunk (cache group: vendor) (name: vendor)
webpack compiled successfully (4d79a4b2d88dea8b)
No issues found.
```

## Steps to Reproduce

Just follow along with the [React Nx Tutorial](https://nx.dev/react-tutorial/01-create-application):

> Start by creating a new workspace.
> ```
> npx create-nx-workspace@latest
> ```
>
> You then receive the following prompts in your command line:
> ```
> Workspace name (e.g., org name)     myorg
> What to create in the new workspace react
> Application name                    todos
> Default stylesheet format           CSS
> ```
> Enter the indicated answers.
>
> Now that the application is set up, run it locally via:
> ```
> npx nx serve todos
> ```

### Failure Logs

Results of running the `npx nx serve` command:

```
<e> [webpack-dev-middleware] HookWebpackError: Only file and data URLs are supported by the default ESM loader
<e>     at makeWebpackError (/Documents/my-project/node_modules/webpack/lib/HookWebpackError.js:48:9)
<e>     at /Documents/my-project/node_modules/webpack/lib/Compilation.js:3060:12
<e>     at eval (eval at create (/Documents/my-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:46:1)
<e>     at /Documents/my-project/node_modules/webpack/lib/Compilation.js:510:26
<e>     at /Documents/my-project/node_modules/copy-webpack-plugin/dist/index.js:708:13
<e> -- inner error --
<e> Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
<e>     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:720:11)
<e>     at Loader.resolve (internal/modules/esm/loader.js:97:40)
<e>     at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
<e>     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
<e>     at link (internal/modules/esm/module_job.js:41:36)
<e> caused by plugins in Compilation.hooks.processAssets
<e> Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
<e>     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:720:11)
<e>     at Loader.resolve (internal/modules/esm/loader.js:97:40)
<e>     at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
<e>     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
<e>     at link (internal/modules/esm/module_job.js:41:36)
```

### Environment

```
   Node : 14.2.0
   OS   : darwin x64
   npm  : 6.14.4
   
   nx : 14.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.2
   @nrwl/eslint-plugin-nx : 14.5.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.2
   @nrwl/js : 14.5.2
   @nrwl/linter : 14.5.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.2
   @nrwl/web : 14.5.2
   @nrwl/workspace : 14.5.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment]
Thank you for reporting this issue.

You can fix the issue by upgrading your Node version to `>= 14.15.0` and it should work.

@jaysoo This was caused by [upgrading our dependency on `copy-webpack-plugin`](https://github.com/nrwl/nx/commit/d657f912d987c5c79a79bfeb6005ba24f0a667ea#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R127). Can we revert it for now?
