### ISSUE TITLE
build error in nx version 14.5.4

### ISSUE THREAD

**Issue by Krasnov8953** [nrwl/nx#11543]
I migrated my angular-cli project to nx workspace, my steps:
- ```npx add-nx-to-monorepo```
- ```nx format```
- ```nx add @nrwl/workspace```
- ```npm i -g @nrwl/workspace```
- ```nx generate @nrwl/workspace:convert-to-nx-project --all=true```
## Current Behavior
run ```nx affected:build```
failed with: ``` NX   Unable to resolve @angular-devkit/build-ng-packagr:build.```

## Expected Behavior
Building affected app

### Failure Logs
```
    >  NX   Affected criteria defaulted to --base=feature/nx --head=HEAD

 >  NX   Ran target build for 9 projects (25ms)
 
         With additional flags:
           --verbose=true

    √    0/0 succeeded [0 read from cache]

    ×    0/0 targets failed, including the following:



 >  NX   Unable to resolve @angular-devkit/build-ng-packagr:build.

   Cannot find module '@angular-devkit/build-ng-packagr'
   Require stack:
   - \node_modules\nx\src\utils\package-json.js
   - \node_modules\nx\src\utils\package-manager.js
   - \node_modules\nx\bin\init-local.js
   - \node_modules\nx\bin\nx.js

Error: Unable to resolve @angular-devkit/build-ng-packagr:build.
Cannot find module '@angular-devkit/build-ng-packagr'
Require stack:
- \node_modules\nx\src\utils\package-json.js
- \node_modules\nx\src\utils\package-manager.js
- \node_modules\nx\bin\init-local.js
- \node_modules\nx\bin\nx.js
    at Workspaces.readExecutor (\node_modules\nx\src\config\workspaces.js:117:19)
    at getExecutorForTask (\node_modules\nx\src\tasks-runner\utils.js:133:22)
    at getCustomHasher (\node_modules\nx\src\tasks-runner\utils.js:137:21)
    at TasksSchedule.<anonymous> (\node_modules\nx\src\tasks-runner\tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at \node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (\node_modules\tslib\tslib.js:113:16)
    at TasksSchedule.hashTask (\node_modules\nx\src\tasks-runner\tasks-schedule.js:113:24)
    at TasksSchedule.<anonymous> (\node_modules\nx\src\tasks-runner\tasks-schedule.js:61:24)
```

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : win32 x64
   npm  : 8.11.0

   nx : 14.5.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : Not Found
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.5.4
   typescript : 4.6.3
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 14.1.0
         @ngrx/store: 14.1.0
         @ngrx/store-devtools: 14.1.0
         rxjs: 6.6.7
```

**Comment by AgentEnder** [comment]
Migrating from angular cli should use `ng add @nrwl/angular`, can you try that and see if you get any errors?

Here are the docs: https://nx.dev/migration/migration-angular

**Comment by spicemix** [comment]
To avoid opening a new issue when I'm not going to put the time into finding a repro path, I will just tack this report onto this similar issue.

## NX 14.5.5: Cannot read properties of undefined (reading 'hashTask')

Migrated to 14.5.5, 14.5.5 is installed globally, ran migrations to turn jest-config.js into .ts, everything looks good, I've done many many NX migrations successfully. Angular 14 project, all deps are latest stable version.

However, I got this with 14.5.5:

```red
% nx serve --verbose

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target serve for project MYPROJ


 >  NX   Cannot read properties of undefined (reading 'hashTask')


TypeError: Cannot read properties of undefined (reading 'hashTask')
    at /MYDIR/node_modules/@nrwl/workspace/node_modules/nx/src/hasher/hash-task.js:24:22
    at Generator.next (<anonymous>)
    at /MYDIR/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/MYDIR/node_modules/tslib/tslib.js:114:16)
    at hashTask (/MYDIR/node_modules/@nrwl/workspace/node_modules/nx/src/hasher/hash-task.js:15:20)
    at TasksSchedule.<anonymous> (/MYDIR/node_modules/@nrwl/workspace/node_modules/nx/src/tasks-runner/tasks-schedule.js:62:48)
    at Generator.next (<anonymous>)
    at /MYDIR/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
```

I'm guessing this is a general Nx broken build, but it could be specific to my project. Rolling everything back to 14.5.4 works fine. If it is specific to my project, accept my apologies for reporting.

`nx report` output _after rolling back_ (I only filed the bug once I knew rolling back worked again):

```red
% nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 14.4.3
   @nrwl/angular : 14.5.4
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.4
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @ionic/angular: 6.2.2
   	 @ionic/angular-toolkit: 7.0.0
   	 @nxtend/capacitor: 13.0.0
   	 @nxtend/ionic-angular: 13.1.0
   	 ngx-build-plus: 14.0.0
```

Yes I know I can update nxtend to nxext and I even tried that in 14.5.5 but it didn't help so I rolled everything back to the 14.5.4 configuration that I pasted above.

Thanks for all your work on Nx.

**Comment by Krasnov8953** [comment]
Yeah, that was a point, ng add @nrwl/angular was failed with unsupported build executors, thanks.
