### ISSUE TITLE
Bugs Next middleware redirect url `[ERR_INVALID_URL]: Invalid URL`

### ISSUE THREAD

**Issue by RioChndr** [nrwl/nx#11582]
## Current Behavior
I just installed nx js with preset nextjs. everything normal but redirect middleware nextjs show error  `[ERR_INVALID_URL]: Invalid URL`. Without nxjs, nextjs works perfectly

```
return NextResponse.redirect(new URL('/login', req.url))
```

```
error - TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Object.relativizeURL (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/shared/lib/router/utils/relativize-url.js:7:48)
    at Object.fn (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/server/next-server.js:922:53)
    at async Router.execute (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/server/router.js:213:36)
    at async DevServer.run (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/server/base-server.js:619:29)
    at async DevServer.run (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/server/dev/next-dev-server.js:536:20)
    at async DevServer.handleRequest (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/server/base-server.js:320:20) {
  input: '/_next/static/chunks/react-refresh.js?ts=1660469080724',
  code: 'ERR_INVALID_URL'
}
```

## Expected Behavior
Middleware should redirect to new url based input.

## Steps to Reproduce

- Clone this repo : https://github.com/RioChndr/reproduce-next-nxjs
- `yarn install` && `nx serve next`
- Open page `localhost:4200/`
- It should redirect to `/login`

### Failure Logs
```
error - TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Object.relativizeURL (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/shared/lib/router/utils/relativize-url.js:7:48)
    at Object.fn (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/server/next-server.js:922:53)
    at async Router.execute (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/server/router.js:213:36)
    at async DevServer.run (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/server/base-server.js:619:29)
    at async DevServer.run (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/server/dev/next-dev-server.js:536:20)
    at async DevServer.handleRequest (/home/riochndr/project/react-learn/reproduce-next-2/node_modules/next/dist/server/base-server.js:320:20) {
  input: '/_next/static/chunks/react-refresh.js?ts=1660469080724',
  code: 'ERR_INVALID_URL'
}
```

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.10.0
   OS   : linux x64
   npm  : 7.24.0
   
   nx : 14.5.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.6
   @nrwl/eslint-plugin-nx : 14.5.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.6
   @nrwl/js : 14.5.6
   @nrwl/linter : 14.5.6
   @nrwl/nest : Not Found
   @nrwl/next : 14.5.6
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.6
   @nrwl/web : 14.5.6
   @nrwl/workspace : 14.5.6
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by RioChndr** [comment]
Closed, i just found the solution. open file `projects.json`, add new property at `targets.serve.options.hostname` and fill it with `localhost`

**Comment by yufengwang** [comment]
Oh, gosh, it wasted me three hours...

**Comment by yufengwang** [comment]
Why hostname is undefined by default?

**Comment by RioChndr** [comment]
maybe default generator next are not filled property hostname by localhost

**Comment by yufengwang** [comment]
Let me dig deeper in it, it seems weird
