### ISSUE TITLE
Can't import a local TS library from a TS web app

### ISSUE THREAD

**Issue by jmeyers91** [nrwl/nx#11673]
## Current Behavior
Importing a TS library from a TS web app after following the steps in the "NX and Typescript" doc results in webpack errors.

## Expected Behavior
You should be able to import a TS library from a TS web app without error.

## Steps to Reproduce

Repo: https://github.com/jmeyers91/nx-hello-world

I ran these commands

```
npx create-nx-workspace happynrwl --preset=ts
cd happynrwl
npm install @nrwl/web
nx generate @nrwl/js:library --name=hello-tsc --buildable
nx generate @nrwl/web:app demoapp
```

### Failure Logs
```
> nx run demoapp:serve

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:4200/, http://127.0.0.1:4200/
<i> [webpack-dev-server] 404s will fallback to '/index.html'

>  NX  Web Development Server is listening at http://localhost:4200/

Entrypoint main 167 KiB = runtime.2ef8300016da4fd7.esm.js 1.25 KiB main.9cc340baffc2f722.esm.js 165 KiB
Entrypoint polyfills 213 KiB = runtime.2ef8300016da4fd7.esm.js 1.25 KiB polyfills.2c39e135f1df3412.esm.js 212 KiB
Entrypoint styles 122 KiB = runtime.2ef8300016da4fd7.esm.js 1.25 KiB styles.ef46db3751d8e999.css 0 bytes styles.e927227daf5bda06.esm.js 120 KiB
chunk (runtime: runtime) main.9cc340baffc2f722.esm.js (main) 208 KiB [initial] [rendered]
chunk (runtime: runtime) polyfills.2c39e135f1df3412.esm.js (polyfills) 457 KiB [initial] [rendered]
chunk (runtime: runtime) styles.ef46db3751d8e999.css, styles.e927227daf5bda06.esm.js (styles) 159 KiB (javascript) 80 bytes (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) runtime.2ef8300016da4fd7.esm.js (runtime) 3.37 KiB [entry] [rendered]
webpack compiled successfully (17aa0310f8da178d)
Entrypoint main = runtime.fd0da2248de56607.esm.js main.e647f2523c18660c.esm.js
Entrypoint polyfills = runtime.fd0da2248de56607.esm.js polyfills.2c39e135f1df3412.esm.js
Entrypoint styles = runtime.fd0da2248de56607.esm.js styles.ef46db3751d8e999.css styles.e927227daf5bda06.esm.js
chunk (runtime: runtime) main.e647f2523c18660c.esm.js (main) 208 KiB [initial] [rendered]
chunk (runtime: runtime) polyfills.2c39e135f1df3412.esm.js (polyfills) 457 KiB [initial] [rendered]
chunk (runtime: runtime) styles.ef46db3751d8e999.css, styles.e927227daf5bda06.esm.js (styles) 159 KiB (javascript) 80 bytes (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) runtime.fd0da2248de56607.esm.js (runtime) 3.37 KiB [entry] [rendered]

ERROR in ../hello-tsc/src/lib/hello-tsc.ts
Module build failed (from ../../node_modules/@nrwl/web/src/utils/web-babel-loader.js):
SyntaxError: /Users/james/projects/happynrwl/packages/hello-tsc/src/lib/hello-tsc.ts: Unexpected token, expected "{" (1:26)

> 1 | export function helloTsc(): string {
    |                           ^
  2 |   return 'hello-tsc';
  3 | }
  4 |
    at instantiate (/Users/james/projects/happynrwl/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/Users/james/projects/happynrwl/node_modules/@babel/parser/lib/index.js:366:12)
    at Parser.raise (/Users/james/projects/happynrwl/node_modules/@babel/parser/lib/index.js:3453:19)
    at Parser.unexpected (/Users/james/projects/happynrwl/node_modules/@babel/parser/lib/index.js:3491:16)
    at Parser.expect (/Users/james/projects/happynrwl/node_modules/@babel/parser/lib/index.js:4128:28)
    at Parser.parseBlock (/Users/james/projects/happynrwl/node_modules/@babel/parser/lib/index.js:15389:10)
    at Parser.parseFunctionBody (/Users/james/projects/happynrwl/node_modules/@babel/parser/lib/index.js:14085:24)
    at Parser.parseFunctionBodyAndFinish (/Users/james/projects/happynrwl/node_modules/@babel/parser/lib/index.js:14069:10)
    at /Users/james/projects/happynrwl/node_modules/@babel/parser/lib/index.js:15570:12
    at Parser.withSmartMixTopicForbiddingContext (/Users/james/projects/happynrwl/node_modules/@babel/parser/lib/index.js:14457:14)

webpack compiled with 1 error (b022fd9df31b7e7f)
```

### Environment

Macbook M1 Mac OS 12.3.1

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin arm64
   npm  : 8.11.0
   
   nx : 14.5.8
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.8
   @nrwl/eslint-plugin-nx : 14.5.8
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.8
   @nrwl/js : 14.5.8
   @nrwl/linter : 14.5.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 14.5.8
   @nrwl/workspace : 14.5.8
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   ```

**Comment by jmeyers91** [comment]
The fix that ended up working for me was to add `"presets": ["@nrwl/web/babel"]` to the root `babel.config.json`.

See: https://github.com/nrwl/nx/issues/10819#issuecomment-1178404861
