### ISSUE TITLE
--verbose arg positioning can cause Nx to just quietly complete without action

### ISSUE THREAD

**Issue by paul-cupola** [nrwl/nx#11720]
v14.4.2.

```
npm nx --verbose blah
```
... has no output.  But omitting the `--verbose` arg yields tons of output ...

```
$ npx nx blah

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target blah for project dashboard (176ms)
 
    ✖    0/0 failed
    ✔    0/0 succeeded [0 read from cache]
 
   See Nx Cloud run details at https://nx.app/runs/REDACTED


 >  NX   Cannot find configuration for task dashboard:blah

   Pass --verbose to see the stacktrace.

npm ERR! code 1
npm ERR! path /home/paul/path/to/repo
npm ERR! command failed
npm ERR! command sh -c nx "blah"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2022-08-25T10_11_15_048Z-debug.log
```

**Comment by meshde** [comment]
@paul-cupola The `--verbose` flag is to be added towards the end of the command like so:

```bash
$ npx nx blah --verbose
```


```
$ npx nx@14.4.2 blah  --verbose

 >  NX   Cannot find configuration for task ang-testing:blah


Error: Cannot find configuration for task ang-testing:blah
    at getExecutorNameForTask (/path/to/repo/node_modules/nx/src/tasks-runner/utils.js:125:15)
    at getExecutorForTask (/path/to/repo/node_modules/nx/src/tasks-runner/utils.js:131:22)
    at getCustomHasher (/path/to/repo/node_modules/nx/src/tasks-runner/utils.js:137:21)
    at hashDependsOnOtherTasks (/path/to/repo/node_modules/nx/src/hasher/hash-task.js:8:54)
    at /path/to/repo/node_modules/nx/src/tasks-runner/run-command.js:68:58
    at Generator.next (<anonymous>)
    at /path/to/repo/node_modules/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/path/to/repo/node_modules/tslib/tslib.js:114:16)
    at hashTasksThatDontDependOnOtherTasks (/path/to/repo/node_modules/nx/src/tasks-runner/run-command.js:65:20)
```
