### ISSUE TITLE
@nrwl/jest: nx migrate --run-migrations > Failed to run exclude-jest-config-from-ts-config from @nrwl/jest

### ISSUE THREAD

**Issue by rizaldirnm** [nrwl/nx#11748]
## Current Behavior
After run `nx migrate latest` and then run `nx migrate --run-migrations` I get error log like bellow

## Expected Behavior
It should run migration smoothly.

## Steps to Reproduce
run `nx migrate latest` migration file looks like

```
{
  "migrations": [
    {
      "cli": "nx",
      "version": "14.5.3-beta.0",
      "description": "Add .next folder to gitignore.",
      "factory": "./src/migrations/update-14-5-3/add-gitignore-entry",
      "package": "@nrwl/next",
      "name": "add-gitignore-entry"
    },
    {
      "cli": "nx",
      "version": "14.5.3-beta.0",
      "description": "Update development outputPath to the project root.",
      "factory": "./src/migrations/update-14-5-3/update-dev-output-path",
      "package": "@nrwl/next",
      "name": "update-dev-output-path"
    },
    {
      "version": "14.5.5-beta.0",
      "cli": "nx",
      "description": "Exclude jest.config.ts from tsconfig where missing.",
      "factory": "./src/migrations/update-14-0-0/update-jest-config-ext",
      "package": "@nrwl/jest",
      "name": "exclude-jest-config-from-ts-config"
    }
  ]
}
```

Then run `nx migrate --run-migration` I get error logs bellow. 

### Failure Logs
```

 >  NX   Running migrations from 'migrations.json'


 >  NX   Failed to run exclude-jest-config-from-ts-config from @nrwl/jest. This workspace is NOT up to date!


 >  NX   Cannot parse apps/app-auth/tsconfig.json: PropertyNameExpected in JSON at position 535


Error: Cannot parse apps/app-auth/tsconfig.json: PropertyNameExpected in JSON at position 535
    at readJson (/Users/rizaldi/Documents/wwworklet/gemini/node_modules/.pnpm/nx@14.5.10/node_modules/nx/src/generators/utils/json.js:20:15)
    at /Users/rizaldi/Documents/wwworklet/gemini/node_modules/.pnpm/@nrwl+jest@14.5.10_v2xbxgm3jkglxif3chrdtjxgvu/node_modules/@nrwl/jest/src/migrations/update-14-0-0/update-jest-config-ext.js:78:60
    at forEachExecutorOptions (/Users/rizaldi/Documents/wwworklet/gemini/node_modules/.pnpm/@nrwl+workspace@14.5.10_leign22aco7s6wclfvszobinta/node_modules/@nrwl/workspace/src/utilities/executor-options-utils.js:23:17)
    at /Users/rizaldi/Documents/wwworklet/gemini/node_modules/.pnpm/@nrwl+jest@14.5.10_v2xbxgm3jkglxif3chrdtjxgvu/node_modules/@nrwl/jest/src/migrations/update-14-0-0/update-jest-config-ext.js:66:61
    at Generator.next (<anonymous>)
    at /Users/rizaldi/Documents/wwworklet/gemini/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/rizaldi/Documents/wwworklet/gemini/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:114:16)
    at updateJestConfigExt (/Users/rizaldi/Documents/wwworklet/gemini/node_modules/.pnpm/@nrwl+jest@14.5.10_v2xbxgm3jkglxif3chrdtjxgvu/node_modules/@nrwl/jest/src/migrations/update-14-0-0/update-jest-config-ext.js:62:20)
    at /private/var/folders/q1/glgkn_nd2xl313jr6_r5_nsc0000gp/T/tmp-40608-GdnII5iGGEhr/node_modules/.pnpm/nx@14.5.10/node_modules/nx/src/command-line/migrate.js:749:15
Command failed: /var/folders/q1/glgkn_nd2xl313jr6_r5_nsc0000gp/T/tmp-40608-GdnII5iGGEhr/node_modules/.bin/nx _migrate --run-migrations --verbose
```

my `tsconfig.json` in `app-auth` look like this:

```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2018",
    "lib": ["es2018", "esnext.asynciterable", "dom"],
    "jsx": "preserve",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "incremental": true,
    "types": ["jest", "node"],
  },
  "include": ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "next-env.d.ts"],
  "exclude": ["node_modules", "jest.config.ts"],
 
}

```

### Environment

```
   Node : 16.13.2
   OS   : darwin arm64
   pnpm : 7.9.5
   
   nx : 14.5.10
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : 14.5.10
   @nrwl/jest : 14.5.10
   @nrwl/js : Not Found
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : 14.5.10
   @nrwl/node : 14.5.10
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.10
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nrwl/remix: 14.1.7
         @nx-go/nx-go: 2.5.0
         @nxrs/cargo: 0.3.3
```

**Comment by ndrsg** [comment]
Had the same problem some days ago.

After debugging I found that the problem is the "," after the last compilerOptions property

```json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2018",
    "lib": ["es2018", "esnext.asynciterable", "dom"],
    "jsx": "preserve",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "incremental": true,
    "types": ["jest", "node"], <------- remove this ','
  },
  "include": ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "next-env.d.ts"],
  "exclude": ["node_modules", "jest.config.ts"],
 
}
```

**Comment by barbados-clemens** [comment]
As @ndrsg you have a hanging comma in your tsconfig. Removing that should fix it for you.
