### ISSUE TITLE
nx 13 to 14 Migration. Failed to run 14-2-0-add-json-schema from nx. This workspace is NOT up to date!

### ISSUE THREAD

**Issue by thecoleorton** [nrwl/nx#11812]
I'm trying to upgrade nx 13.5.3 to 14.5.8 by running: 

1. yarn nx migrate 14.5.8
2. yarn
3. yarn nx migrate --run-migrations

## Current Behavior

Getting the below error: 

```
 >  NX   Running migrations from 'migrations.json'


 >  NX   Failed to run 14-2-0-add-json-schema from nx. This workspace is NOT up to date!


 >  NX   Unable to determine implementation path for "/Users/coleorton/Development/idp-app-seed-ui-template/node_modules/nx/migrations.json:14-2-0-add-json-schema" using collection.generators


Error: Unable to determine implementation path for "/Users/coleorton/Development/idp-app-seed-ui-template/node_modules/nx/migrations.json:14-2-0-add-json-schema" using collection.generators
    at /private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/nx/src/command-line/migrate.js:734:19
    at Generator.next (<anonymous>)
    at /private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/tslib/tslib.js:114:16)
    at runNxMigration (/private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/nx/src/command-line/migrate.js:728:20)
    at /private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/nx/src/command-line/migrate.js:622:43
    at Generator.next (<anonymous>)
    at /private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
Command failed: /var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/.bin/nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected Behavior

`yarn nx migrate --run-migrations` is successful. 

## Steps to Reproduce

1. Begin with a nx 13.5.3 project
1. yarn nx migrate 14.5.8
2. yarn
3. yarn nx migrate --run-migrations

### Failure Logs

```
 >  NX   Running migrations from 'migrations.json'


 >  NX   Failed to run 14-2-0-add-json-schema from nx. This workspace is NOT up to date!


 >  NX   Unable to determine implementation path for "/Users/coleorton/Development/idp-app-seed-ui-template/node_modules/nx/migrations.json:14-2-0-add-json-schema" using collection.generators


Error: Unable to determine implementation path for "/Users/coleorton/Development/idp-app-seed-ui-template/node_modules/nx/migrations.json:14-2-0-add-json-schema" using collection.generators
    at /private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/nx/src/command-line/migrate.js:734:19
    at Generator.next (<anonymous>)
    at /private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/tslib/tslib.js:114:16)
    at runNxMigration (/private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/nx/src/command-line/migrate.js:728:20)
    at /private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/nx/src/command-line/migrate.js:622:43
    at Generator.next (<anonymous>)
    at /private/var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
Command failed: /var/folders/_c/nmb08p0s6s5cblqtxxy5kmkr0000gq/T/tmp-23210-VIL7SunTZ1Lo/node_modules/.bin/nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

coleorton@M-H7XYV4D5QC idp-app-seed-ui-template % yarn nx report                            
yarn run v1.22.19
$ nx report

 >  NX   Report complete - copy this into the issue template

```
   Node : 16.15.1
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 14.1.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.8
   @nrwl/eslint-plugin-nx : 14.5.8
   @nrwl/express : 14.5.8
   @nrwl/jest : 14.5.8
   @nrwl/js : 14.5.8
   @nrwl/linter : 14.5.8
   @nrwl/nest : 14.5.8
   @nrwl/next : 14.5.8
   @nrwl/node : 14.5.8
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.8
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.8
   @nrwl/web : 14.5.8
   @nrwl/workspace : 14.5.8
   typescript : 4.7.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

✨  Done in 3.46s.
```

**Comment by FrozenPandaz** [comment]
> nx : 14.1.1
> @nrwl/workspace : 14.5.8

Your version of `nx` doesn't line up with your other packages. Do you perhaps have `nx` in both your `dependencies` and `devDependencies`? You should only set in one or other. Preferably, `devDependencies` unless you have a reason to have it in `dependencies`.

**Comment by thecoleorton** [comment]
> > nx : 14.1.1
> > @nrwl/workspace : 14.5.8
> 
> Your version of `nx` doesn't line up with your other packages. Do you perhaps have `nx` in both your `dependencies` and `devDependencies`? You should only set in one or other. Preferably, `devDependencies` unless you have a reason to have it in `dependencies`.

Great catch! I’ll try that out next week. Thanks!
