### ISSUE TITLE
Error: Command failed: git merge-base --fork-point "main" "HEAD"

### ISSUE THREAD

**Issue by mrlubos** [nrwl/nx#11840]
## Current Behavior

Over the last few days, I've started noticing this error when building Nx apps in Vercel. From what I can tell, it happens only on pull requests, subsequent builds on merge work fine. I am using the standard `nx-ignore` approach in the ignore step.

## Expected Behavior

Continue working as before. This didn't use to happen, and it's not clear why it happens.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
Cloning github.com/org/repo (Branch: fix/nx, Commit: aaaaaaa)
--
04:37:19.985 | Cloning completed: 860.267ms
04:37:19.986 | Running "npx nx-ignore app --verbose"
04:37:28.433 | ≫ Using Nx to determine if this project (app) is affected by the commit...
04:37:28.575 |  
04:37:28.576 | ≫ Comparing ...HEAD
04:37:28.576 |  
04:37:30.294 | fatal: Not a valid object name main
04:37:30.298 | fatal: No such ref: 'main'
04:37:30.301 | Error: Command failed: git merge-base --fork-point "main" "HEAD"
04:37:30.301 | fatal: No such ref: 'main'
04:37:30.301 |  
04:37:30.301 | at checkExecSyncError (child_process.js:790:11)
04:37:30.301 | at execSync (child_process.js:863:15)
04:37:30.302 | at getFilesUsingBaseAndHead (/vercel/.npm/_npx/255/lib/node_modules/nx-ignore/node_modules/nx/src/utils/command-line-utils.js:283:50)
04:37:30.302 | at parseFiles (/vercel/.npm/_npx/255/lib/node_modules/nx-ignore/node_modules/nx/src/utils/command-line-utils.js:252:20)
04:37:30.302 | at projectsToRun (/vercel/.npm/_npx/255/lib/node_modules/nx-ignore/node_modules/nx/src/command-line/affected.js:100:145)
04:37:30.302 | at /vercel/.npm/_npx/255/lib/node_modules/nx-ignore/node_modules/nx/src/command-line/affected.js:29:26
04:37:30.302 | at Generator.next (<anonymous>)
04:37:30.302 | at fulfilled (/vercel/.npm/_npx/255/lib/node_modules/nx-ignore/node_modules/tslib/tslib.js:115:62)
04:37:30.302 | at processTicksAndRejections (internal/process/task_queues.js:95:5) {
```

**Comment by mrlubos** [comment]
@jaysoo very nice, and thank you for the additional context!
