### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] when upgrading to the latest version

### ISSUE THREAD

**Issue by MauriceNino** [nrwl/nx#11847]
## Current Behavior
When upgrading from `14.5.6` to `14.6.3`, I get an error when running any nx command:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at join (node:path:1172:7)
    at CloudEnabledLifeCycle.getTerminalOutput (/drone/src/node_modules/@nrwl/nx-cloud/lib/core/runners/cloud-enabled/cloud-enabled-life-cycle.js:1:4382)
    at CloudEnabledLifeCycle.updateStartedTask (/drone/src/node_modules/@nrwl/nx-cloud/lib/core/runners/cloud-enabled/cloud-enabled-life-cycle.js:1:4005)
    at CloudEnabledLifeCycle.endTasks (/drone/src/node_modules/@nrwl/nx-cloud/lib/core/runners/cloud-enabled/cloud-enabled-life-cycle.js:1:3363)
    at CompositeLifeCycle.endTasks (/drone/src/node_modules/nx/src/tasks-runner/life-cycle.js:56:19)
    at TaskOrchestrator.<anonymous> (/drone/src/node_modules/nx/src/tasks-runner/task-orchestrator.js:236:36)
    at Generator.next (<anonymous>)
    at fulfilled (/drone/src/node_modules/tslib/tslib.js:115:62) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Full log can be found here: https://drone.mauz.io/MauriceNino/dashdot/1559/1/3

## Expected Behavior
I expect the command to run like it did before.

## Steps to Reproduce
1. `git clone -b renovate/nrwl-monorepo https://github.com/MauriceNino/dashdot`
2. `yarn`
3. `yarn build`

### Environment
```

 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : linux x64
   yarn : 3.2.3
   
   nx : 14.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.6.3
   @nrwl/eslint-plugin-nx : 14.6.3
   @nrwl/express : 14.6.3
   @nrwl/jest : 14.6.3
   @nrwl/js : 14.6.3
   @nrwl/linter : 14.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.6.3
   @nrwl/nx-cloud : 14.0.5
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.6.3
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.6.3
   @nrwl/web : 14.6.3
   @nrwl/workspace : 14.6.3
   typescript : 4.8.2
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nx-plus/docusaurus: 14.1.0
```

**Comment by FrozenPandaz** [comment]
> @nrwl/nx-cloud : 14.0.5

Upgrading `@nrwl/nx-cloud` to `14.6.0` will fix the issue.

Can you please retry with that version please?

**Comment by MauriceNino** [comment]
Thanks for making me aware of this! It seems like the version for `@nrwl/nx-cloud` automatically got set to the version `latest`, which in turn made renovate bot skip the update.
After setting it to an exact version, everything works fine again.
