### ISSUE TITLE
Upgrading to 14.6.3+ causes build to fail due to SVGR plugin

### ISSUE THREAD

**Issue by terrymun** [nrwl/nx#11873]
## Current Behavior
After upgrading from 14.6.2 to 14.6.3+, I get an error when attempting to build my solution"

```
>  NX   Cannot read properties of undefined (reading 'svgr')
```

I have encountered this error when upgrading from 14.5.10 to 14.6.4. I have tested several other patch versions to find out at which version the build step involving SVGR was broken:

| Version         | Build works? |
|-----------------|--------------|
| 14.5.10         | ✔️ |
| 14.6.0.         | ✔️ |
| 14.6.1.         | ✔️ |
| 14.6.2          | ✔️ |
| 14.6.3          | ❌ |
| 14.6.4 (latest) | ❌ |

## Expected Behavior
The build should work without any issue: when downgrading back to 14.6.2, the build passes without any issue.

## Steps to Reproduce
Upgrading from 14.6.2 to 14.6.3+ will trigger the build failure.

### Failure Logs
When running the build with `--verbose`, it seems like the error is coming from the next plugin:

```
TypeError: Cannot read properties of undefined (reading 'svgr')
    at Object.webpack (/Users/[REDACTED]/Documents/GitHub/Campaigns/node_modules/@nrwl/next/plugins/with-nx.js:97:20)
    at webpack (/Users/[REDACTED]/Documents/GitHub/Campaigns/node_modules/next-transpile-modules/src/next-transpile-modules.js:255:29)
    at Object.config.webpack (/Users/[REDACTED]/Documents/GitHub/Campaigns/node_modules/@nrwl/next/src/utils/config.js:61:163)
    at Object.getBaseWebpackConfig [as default] (/Users/[REDACTED]/Documents/GitHub/Campaigns/node_modules/next/dist/build/webpack-config.js:1310:32)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (/Users/[REDACTED]/Documents/GitHub/Campaigns/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/[REDACTED]/Documents/GitHub/Campaigns/node_modules/next/dist/build/index.js:409:33
    at async /Users/[REDACTED]/Documents/GitHub/Campaigns/node_modules/next/dist/build/index.js:393:13
    at async Span.traceAsyncFn (/Users/[REDACTED]/Documents/GitHub/Campaigns/node_modules/next/dist/trace/trace.js:79:20)
    at async build (/Users/[REDACTED]/Documents/GitHub/Campaigns/node_modules/next/dist/build/index.js:65:29)
```

### Environment

```
Node : 16.16.0
OS   : darwin x64
yarn : 3.1.1

nx : 14.6.3
@nrwl/angular : Not Found
@nrwl/cypress : 14.6.3
@nrwl/detox : Not Found
@nrwl/devkit : 14.6.3
@nrwl/eslint-plugin-nx : 14.6.3
@nrwl/express : Not Found
@nrwl/jest : 14.6.3
@nrwl/js : 14.6.3
@nrwl/linter : 14.6.3
@nrwl/nest : Not Found
@nrwl/next : 14.6.3
@nrwl/node : 14.6.3
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : 14.6.3
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.6.3
@nrwl/web : 14.6.3
@nrwl/workspace : 14.6.3
typescript : 4.8.2
---------------------------------------
Local workspace plugins:
---------------------------------------
Community plugins:
```

**Comment by terrymun** [comment]
It turns out that it is necessary to add `nx: { svgr: true }` to `next.config.js`: it seems that we have assumed `svgr: true` behaviour to be the default all the whole, which was a mistake :) 

https://github.com/nrwl/nx/releases/tag/14.6.3
