### ISSUE TITLE
14.6.4 can't generate an Angular component inside the library

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#11883]
## Current Behavior

Error message when I'm trying to generate a component

## Expected Behavior

It is a regression definitely, in 14.6.1 it was working fine.

## Steps to Reproduce
<details>
<summary>Full log of reproduction, including error message and nx report</summary>

```
oz@Avalon tmp % npx create-nx-workspace
Need to install the following packages:
  create-nx-workspace@14.6.4
Ok to proceed? (y) y
✔ Workspace name (e.g., org name)     · test
✔ What to create in the new workspace · angular
✔ Application name                    · testApp
✔ Default stylesheet format           · scss
✔ Enable distributed caching to make your CI faster · Yes

 >  NX   Nx is creating your v14.6.4 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace: test.
✔ NxCloud has been set up successfully

 >  NX   Successfully initialized git.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   First time using Nx? Check out this interactive Nx tutorial.

   https://nx.dev/angular-tutorial/01-create-application
   
   Prefer watching videos? Check out this free Nx course on YouTube.
   https://www.youtube.com/watch?v=2mYLe9Kp9VM&list=PLakNactNC1dH38AfqmwabvOszDmKriGco


 >  NX   Distributed caching via Nx Cloud has been enabled

   In addition to the caching, Nx Cloud provides config-free distributed execution,
   UI for viewing complex runs and GitHub integration. Learn more at https://nx.app
   
   Your workspace is currently unclaimed. Run details from unclaimed workspaces can be viewed on cloud.nx.app by anyone
   with the link. Claim your workspace at the following link to restrict access.
   
   https://cloud.nx.app/orgs/workspace-setup?accessToken=ZTBhNzliYTctMzgyZi00YWFlLTg5NzMtZDBiOWUzZTM2MzQwfHJlYWQtd3JpdGU=

oz@Avalon tmp % cd test
oz@Avalon test % nx g @nrwl/angular:lib my-lib                               

>  NX  Generating @nrwl/angular:library

[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in angular.json
[NX] Double check angular.json before proceeding
UPDATE angular.json
CREATE libs/my-lib/README.md
CREATE libs/my-lib/tsconfig.lib.json
CREATE libs/my-lib/tsconfig.spec.json
CREATE libs/my-lib/src/index.ts
CREATE libs/my-lib/src/lib/my-lib.module.ts
CREATE libs/my-lib/tsconfig.json
UPDATE tsconfig.base.json
CREATE libs/my-lib/jest.config.ts
CREATE libs/my-lib/src/test-setup.ts
CREATE libs/my-lib/.eslintrc.json
CREATE libs/my-lib/project.json
oz@Avalon test % cd libs/my-lib/src/lib
oz@Avalon lib % ls
my-lib.module.ts
oz@Avalon lib % nx g c test-component --standalone=true

>  NX  Generating @nrwl/angular:component


 >  NX   The path provided for the component (libs/my-lib/src/lib) does not exist under the project root (apps/test-app). Please make sure to provide a path that exists under the project root.

   Pass --verbose to see the stacktrace.

oz@Avalon lib % nx g c test-component --standalone=true --verbose

>  NX  Generating @nrwl/angular:component


 >  NX   The path provided for the component (libs/my-lib/src/lib) does not exist under the project root (apps/test-app). Please make sure to provide a path that exists under the project root.


Error: The path provided for the component (libs/my-lib/src/lib) does not exist under the project root (apps/test-app). Please make sure to provide a path that exists under the project root.
    at checkPathUnderProjectRoot (/Users/oz/repos/tmp/test/node_modules/@nrwl/angular/src/generators/component/component.js:34:15)
    at /Users/oz/repos/tmp/test/node_modules/@nrwl/angular/src/generators/component/component.js:14:9
    at Generator.next (<anonymous>)
    at /Users/oz/repos/tmp/test/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/oz/repos/tmp/test/node_modules/tslib/tslib.js:114:16)
    at componentGenerator (/Users/oz/repos/tmp/test/node_modules/@nrwl/angular/src/generators/component/component.js:11:20)
    at Object.<anonymous> (/Users/oz/repos/tmp/test/node_modules/nx/src/command-line/generate.js:250:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/oz/repos/tmp/test/node_modules/tslib/tslib.js:115:62)
oz@Avalon lib % nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.7.0
   OS   : darwin arm64
   npm  : 8.17.0
   
   nx : 14.6.4
   @nrwl/angular : 14.6.4
   @nrwl/cypress : 14.6.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.6.4
   @nrwl/eslint-plugin-nx : 14.6.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.6.4
   @nrwl/js : 14.6.4
   @nrwl/linter : 14.6.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.6.4
   @nrwl/web : 14.6.4
   @nrwl/workspace : 14.6.4
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

oz@Avalon lib % 
```
<details>

**Comment by e-oz** [comment]
As a workaround: add ` --project=libraryOrAppName` to `nx g c...`
