### ISSUE TITLE
Angular migration to 14 fails with safe navigation operator unknown token

### ISSUE THREAD

**Issue by akoreh** [nrwl/nx#11906]
## Current Behavior
I have an angular 13 workspace created from scratch and am trying to upgrade to v14 using nx migrate.

## Steps to Reproduce

- have a fresh NX 13.8.8 angular workspace.
- run nx migrate latest
- npm install --legacy-peer-deps (this fails with conflicting peer dependencies because of storybook and react versions)
- npx nx migrate --run-migrations

### Failure Logs
```
 >  NX   Failed to run migration-v14 from @angular/cdk. This workspace is NOT up to date!


 >  NX   Unexpected token '.'


/home/rooter/Desktop/AngularWorkspace/node_modules/@angular/cdk/schematics/update-tool/component-resource-collector.js:36
        const decorators = ts.getDecorators?.(node) || node.decorators;
                                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/rooter/Desktop/AngularWorkspace/node_modules/@angular/cdk/schematics/update-tool/index.js:12:40)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by akoreh** [comment]
my node version was too old
