### ISSUE TITLE
Error: CloseBraceExpected in /home/circleci/project/node_modules/.cache/nx/nxdeps.json

### ISSUE THREAD

**Issue by dmaretskyi** [nrwl/nx#11938]
## Current Behavior

Nx CLI crashes during CI run.

## Expected Behavior

Nx CLI doesn't crash.

## Steps to Reproduce

Happened during CI run:

https://cloud.nx.app/runs/wrsuVMhD0of

### Failure Logs

```
Error reading '/home/circleci/project/node_modules/.cache/nx/nxdeps.json'. Continue the process without the cache.
Error: CloseBraceExpected in /home/circleci/project/node_modules/.cache/nx/nxdeps.json at position 385024
    at parseJson (/home/circleci/project/node_modules/.pnpm/nx@14.5.7_@swc-node+register@1.5.1/node_modules/nx/src/utils/json.js:23:15)
    at readJsonFile (/home/circleci/project/node_modules/.pnpm/nx@14.5.7_@swc-node+register@1.5.1/node_modules/nx/src/utils/fileutils.js:23:37)
    at readCache (/home/circleci/project/node_modules/.pnpm/nx@14.5.7_@swc-node+register@1.5.1/node_modules/nx/src/project-graph/nx-deps-cache.js:41:49)
    at readCachedProjectGraph (/home/circleci/project/node_modules/.pnpm/nx@14.5.7_@swc-node+register@1.5.1/node_modules/nx/src/project-graph/project-graph.js:20:61)
    at checkDependencies (/home/circleci/project/node_modules/.pnpm/@nrwl+js@14.5.7_osi77fjxs57mwennraun4e6pmi_7tybhtwyz6spdrinxewf6jf4oy/node_modules/@nrwl/js/src/utils/check-dependencies.js:7:62)
    at tscExecutor_1 (/home/circleci/project/node_modules/.pnpm/@nrwl+js@14.5.7_osi77fjxs57mwennraun4e6pmi_7tybhtwyz6spdrinxewf6jf4oy/node_modules/@nrwl/js/src/executors/tsc/tsc.impl.js:29:111)
    at tscExecutor_1.next (<anonymous>)
    at resume (/home/circleci/project/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:230:48)
    at /home/circleci/project/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:229:125
    at new Promise (<anonymous>)

 >  NX   [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

   
   If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
   the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.
   
   If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
   Pass --verbose to see the stacktrace.
```

**Comment by AgentEnder** [comment]
What's the output of `nx report`?

**Comment by wimme** [comment]
Are you running nx commands in simultaneous parallel? Might be the same issue as #9146.
