### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'nodes')

### ISSUE THREAD

**Issue by Vishionary** [nrwl/nx#11995]
## Current Behavior

`nx build` is failing for all applications with the below error. It started happening after I rebased master to rewrite the commit history, I don't know if that's related.

```
nx run hello-world-app:build --verbose

Cannot read properties of undefined (reading 'nodes')
HookWebpackError: Cannot read properties of undefined (reading 'nodes')
    at makeWebpackError (/Users/vishionary/Work/Git/hw-repo/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/vishionary/Work/Git/hw-repo/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/vishionary/Work/Git/hw-repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at fn (/Users/vishionary/Work/Git/hw-repo/node_modules/webpack/lib/Compilation.js:480:17)
    at Hook.eval [as callAsync] (eval at create (/Users/vishionary/Work/Git/hw-repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/vishionary/Work/Git/hw-repo/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/Users/vishionary/Work/Git/hw-repo/node_modules/webpack/lib/Compilation.js:3057:34)
    at /Users/vishionary/Work/Git/hw-repo/node_modules/webpack/lib/Compilation.js:3105:10
    at symbolIterator (/Users/vishionary/Work/Git/hw-repo/node_modules/neo-async/async.js:3485:9)
    at done (/Users/vishionary/Work/Git/hw-repo/node_modules/neo-async/async.js:3527:9)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'nodes')
    at getHelperDependenciesFromProjectGraph (/Users/vishionary/Work/Git/hw-repo/node_modules/@nrwl/js/src/utils/compiler-helper-dependency.js:67:23)
    at /Users/vishionary/Work/Git/hw-repo/node_modules/@nrwl/node/src/utils/generate-package-json-webpack-plugin.js:23:115
    at fn (/Users/vishionary/Work/Git/hw-repo/node_modules/webpack/lib/Compilation.js:478:10)
    at Hook.eval [as callAsync] (eval at create (/Users/vishionary/Work/Git/hw-repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/vishionary/Work/Git/hw-repo/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/Users/vishionary/Work/Git/hw-repo/node_modules/webpack/lib/Compilation.js:3057:34)
    at /Users/vishionary/Work/Git/hw-repo/node_modules/webpack/lib/Compilation.js:3105:10
    at symbolIterator (/Users/vishionary/Work/Git/hw-repo/node_modules/neo-async/async.js:3485:9)
    at done (/Users/vishionary/Work/Git/hw-repo/node_modules/neo-async/async.js:3527:9)
    at /Users/vishionary/Work/Git/hw-repo/node_modules/neo-async/async.js:2830:7
```

## Expected Behavior

`nx build` should run correctly

## Steps to Reproduce

 This is what I did for the rebase on master:

- Commits on master were A,B,C,D
- Reset master to A
- Merged a new PR with commit X that included all changes from B,C,D with altered commit messages

### Environment

```

  Node : 16.14.2
   OS   : darwin x64
   npm  : 8.5.0

   nx : 14.1.7
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7
   @nrwl/eslint-plugin-nx : 14.1.7
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.7
   @nrwl/js : 14.6.4
   @nrwl/linter : 14.1.7
   @nrwl/nest : 14.6.4
   @nrwl/next : Not Found
   @nrwl/node : 14.6.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.7
   typescript : 4.6.4
   rxjs : 7.5.6
   ---------------------------------------
   Community plugins:

```

**Comment by jcyovera-halo** [comment]
I have the same problem!

**Comment by Vishionary** [comment]
So it doesn't seem to be related to the rebase at all.. I copied the entire code as-is over to a new empty git repo, same build errors there as well.

**Comment by Vishionary** [comment]
Issue seems to be resolved after migrating to the latest version of nx with `nx migrate @nrwl/workspace@latest`
```

   Node : 16.14.2
   OS   : darwin x64
   npm  : 8.5.0

   nx : 14.7.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : 14.7.5
   @nrwl/next : Not Found
   @nrwl/node : 14.7.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.5
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```
