### ISSUE TITLE
NX, nextjs generate package error (reading 'externalNodes')

### ISSUE THREAD

**Issue by VinayKempa** [nrwl/nx#12050]
Hi Team, 
Please help me to get this resolved.

I'm running a build command to generate nextjs project build. I guess Project is getting build, but getting an error while creating package.json.

I did try to debug and found that in `context.projectGraph` in `@nrwl/next/src/executors/build/lib/create-package-json.js:9:73` is undefined.

Below is the verbose for the same:
```sh
 >  NX   Cannot read properties of undefined (reading 'externalNodes')


TypeError: Cannot read properties of undefined (reading 'externalNodes')
    at findAllNpmDeps (/my-workspace/node_modules/@nrwl/next/node_modules/@nrwl/workspace/src/utilities/create-package-json.js:51:24)
    at createPackageJson (/my-workspace/node_modules/@nrwl/next/node_modules/@nrwl/workspace/src/utilities/create-package-json.js:12:21)
    at /my-workspace/node_modules/@nrwl/next/src/executors/build/lib/create-package-json.js:9:73
    at Generator.next (<anonymous>)
    at /my-workspace/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/my-workspace/node_modules/tslib/tslib.js:114:16)
    at createPackageJson (/my-workspace/node_modules/@nrwl/next/src/executors/build/lib/create-package-json.js:8:20)
    at /my-workspace/node_modules/@nrwl/next/src/executors/build/build.impl.js:35:59
    at Generator.next (<anonymous>)
```

**Comment by FrozenPandaz** [comment]
Could you please provide a repo we can clone to reproduce the issue?

**Comment by Tchakoumi** [comment]
> Could you please provide a repo we can clone to reproduce the issue?

https://gitlab.com//glomsarl/skeleton.git

**Comment by Tchakoumi** [comment]
@FrozenPandaz please we're still waiting

**Comment by FrozenPandaz** [comment]
Thank you for the reproduction. I was able to reproduce the issue.

I migrated the repo to the latest Nx (14.8.3) and the issue is no longer reproducible so this may have already been fixed.

Please try again with the latest version.

**Comment by jjaybrown** [comment]
Hi @FrozenPandaz this has returned in next 13 release
