### ISSUE TITLE
Cypress component test runner not working in Angular

### ISSUE THREAD

**Issue by rainerhahnekamp** [nrwl/nx#12061]
## Current Behavior
Running Cypress component tests in Angular fails.

## Expected Behavior
A fresh nx workspace should be able to run Cypress component tests in Angular.

## Steps to Reproduce
Generate a new nx workspace with Angular template, configure the component tester with pre-generated tests, and run:
```bash
npx create-nx-workspace nx-angular-cypress-component --preset angular --appName foobar --style scss --nxCloud
cd nx-angular-cypress-component
npx nx g @nrwl/angular:cypress-component-configuration --project=foobar --create-tests
npx nx component-test foobar
```

### Failure Logs
```bash
Your configFile is invalid: C:\Users\raine\Programming\softarc\nx-angular-cypress-component\apps\foobar\cypress.config.ts

It threw an error when required, check the stack trace below:

Error: Unable to find the project configuration that includes apps\foobar\cypress.config.
Found project name? undefined.
Graph has data? false
    at getProjectConfigByPath (C:\Users\raine\Programming\softarc\nx-angular-cypress-component\packages\cypress\plugins\cypress-preset.ts:97:11)
    at nxComponentTestingPreset (C:\Users\raine\Programming\softarc\nx-angular-cypress-component\packages\angular\plugins\component-testing.ts:64:49)
    at Object.<anonymous> (C:\Users\raine\Programming\softarc\nx-angular-cypress-component\apps\foobar\cypress.config.ts:5:38)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (C:\Users\raine\AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\raine\AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadFile (C:\Users\raine\AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (C:\Users\raine\AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at process.<anonymous> (C:\Users\raine\AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (node:events:527:28)
    at process.emit (node:domain:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (C:\Users\raine\AppData\Local\Cypress\Cache\10.8.0\Cypress\resources\app\node_modules\@cspotcode\source-map-support\source-map-support.js:745:40)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

### Environment
nx 10.7.5
OS: Windows 11

**Comment by barbados-clemens** [comment]
Fixed in https://github.com/nrwl/nx/pull/11963
