### ISSUE TITLE
"Cypress configuration error" when running Cypress Angular Component test configuration on Windows

### ISSUE THREAD

**Issue by rujorgensen** [nrwl/nx#12082]
## Current Behavior
I'm attempting to setup Angular component tests by using the NRWL generator `nx g @nrwl/angular:cypress-component-configuration`, but I'm getting this error when trying to run `nx component-test angular-app --watch` **the issue appears to only be on my Windows 10/11 machines, it works as expected on Linux (and reportedly on [Mac](https://github.com/cypress-io/cypress/issues/23841#issuecomment-1251221507))**:

![190854107-a6e4376b-c4b1-4e1b-a857-4d5016ecf21f](https://user-images.githubusercontent.com/6797319/191065409-d230b4ab-bc60-47a6-8b5f-57b1205ad030.png)

(I originally reported the issue to Cypress https://github.com/cypress-io/cypress/issues/23841) 

## Expected Behavior
I'd like the tool to generate working configuration(s) enabling me to test Angular components (/not getting "Cypress configuration error").

## Steps to Reproduce
I'm using a clean nx-workspace (Angular/NestJS/Cypress), which can be found on this branch: [github](https://github.com/rujorgensen/nx-workspace/tree/testing/cy-component-tests/initial-configuration-setup), then using `nx component-test angular-app --watch` on Windows 10 or 11.

### Failure Logs

**Complete output**
```Error: Unable to find the project configuration that includes apps\angular-app\cypress.config.
Found project name? undefined.
Graph has data? false
    at getProjectConfigByPath (C:\Users\rj\Desktop\nx-workspace\packages\cypress\plugins\cypress-preset.ts:97:11)
    at nxComponentTestingPreset (C:\Users\rj\Desktop\nx-workspace\packages\angular\plugins\component-testing.ts:64:49)
    at Object. (C:\Users\rj\Desktop\nx-workspace\apps\angular-app\cypress.config.ts:5:40)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\ts-node\src\index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions. [as .ts] (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadFile (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:89:14)
    at EventEmitter. (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at process. (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (node:events:527:28)
    at process.emit (node:domain:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (C:\Users\rj\AppData\Local\Cypress\Cache\10.7.0\Cypress\resources\app\node_modules\@cspotcode\source-map-support\source-map-support.js:613:40)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

### Environment
NX Version
14.7.5

Cypress Version
10.7.0

Node version
16.16.0

Operating System
Windows 10 and 11

**Comment by rujorgensen** [comment]
Issue resolved after running the current NX migration 👍.

My current environment:

```JSON
{
     ...
    "dependencies": {
        "@angular/animations": "14.2.3",
        "@angular/common": "14.2.3",
        "@angular/compiler": "14.2.3",
        "@angular/core": "14.2.3",
        "@angular/forms": "14.2.3",
        "@angular/platform-browser": "14.2.3",
        "@angular/platform-browser-dynamic": "14.2.3",
        "@angular/router": "14.2.3",
        "@nestjs/common": "9.1.2",
        "@nestjs/core": "9.1.2",
        "@nestjs/platform-express": "9.1.2",
        "@nrwl/angular": "14.7.11",
        "reflect-metadata": "^0.1.13",
        "rxjs": "7.5.6",
        "tslib": "^2.4.0",
        "zone.js": "0.11.8"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "14.2.3",
        "@angular-eslint/eslint-plugin": "14.1.2",
        "@angular-eslint/eslint-plugin-template": "14.1.2",
        "@angular-eslint/template-parser": "14.1.2",
        "@angular/cli": "14.2.3",
        "@angular/compiler-cli": "14.2.3",
        "@angular/language-service": "14.2.3",
        "@cypress/webpack-dev-server": "2.3.0",
        "@nestjs/schematics": "9.0.3",
        "@nestjs/testing": "9.1.2",
        "@nrwl/cli": "14.7.11",
        "@nrwl/cypress": "14.7.11",
        "@nrwl/eslint-plugin-nx": "14.7.11",
        "@nrwl/jest": "14.7.11",
        "@nrwl/linter": "14.7.11",
        "@nrwl/nest": "14.7.11",
        "@nrwl/node": "14.7.11",
        "@nrwl/workspace": "14.7.11",
        "@types/jest": "28.1.8",
        "@types/node": "18.7.18",
        "@types/supertest": "^2.0.12",
        "@typescript-eslint/eslint-plugin": "5.38.0",
        "@typescript-eslint/parser": "5.38.0",
        "cypress": "10.8.0",
        "dotenv": "16.0.2",
        "eslint": "8.23.1",
        "eslint-config-prettier": "8.5.0",
        "eslint-plugin-cypress": "2.12.1",
        "html-webpack-plugin": "5.5.0",
        "jest": "28.1.3",
        "jest-environment-jsdom": "28.1.1",
        "jest-extended": "^3.1.0",
        "jest-preset-angular": "12.2.2",
        "nx": "14.7.11",
        "prettier": "2.7.1",
        "supertest": "^6.2.4",
        "ts-jest": "28.0.8",
        "ts-node": "10.9.1",
        "typescript": "4.7.4"
    },
    "engines": {
        "node": "16.17.0",
        "npm": "8.15.0"
    }
}
```
