### ISSUE TITLE
Publishable libs should have the production target generated

### ISSUE THREAD

**Issue by schackito** [nrwl/nx#1210]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
`yarn run affected:build --base=HEAD --prod` should also work with publishable libs. `--prod` should be ignored for libs since it's not necessary due to https://github.com/angular/angular-cli/issues/12226#issuecomment-420011342.

## Current Behavior
Production builds for apps work but for libs they will fail.

### Steps to Reproduce
Following the tutorial i did...
1. `npx create-nx-workspace myorg`
2. `ng g app todos`
3. `ng g lib mylib --publishable`
4. `yarn run affected:build --base=HEAD --prod`

### Context
- version of Nx used: 7.7.2
- version of Angular CLI used: tested with 7.3.1 and 7.3.7
- version of Angular DevKit used: 7.3.7 / 0.13.7
- `angular.json` configuration:
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "",
  "projects": {
    "todos": {
      "root": "apps/todos/",
      "sourceRoot": "apps/todos/src",
      "projectType": "application",
      "prefix": "myorg",
      "schematics": {
        "@nrwl/schematics:component": {
          "style": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/apps/todos",
            "index": "apps/todos/src/index.html",
            "main": "apps/todos/src/main.ts",
            "polyfills": "apps/todos/src/polyfills.ts",
            "tsConfig": "apps/todos/tsconfig.app.json",
            "assets": ["apps/todos/src/favicon.ico", "apps/todos/src/assets"],
            "styles": ["apps/todos/src/styles.scss"],
            "scripts": [],
            "es5BrowserSupport": true
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "apps/todos/src/environments/environment.ts",
                  "with": "apps/todos/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "todos:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "todos:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "todos:build"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "apps/todos/tsconfig.app.json",
              "apps/todos/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**"]
          }
        },
        "test": {
          "builder": "@nrwl/builders:jest",
          "options": {
            "jestConfig": "apps/todos/jest.config.js",
            "tsConfig": "apps/todos/tsconfig.spec.json",
            "setupFile": "apps/todos/src/test-setup.ts"
          }
        }
      }
    },
    "todos-e2e": {
      "root": "apps/todos-e2e",
      "projectType": "application",
      "prefix": "",
      "architect": {
        "e2e": {
          "builder": "@nrwl/builders:cypress",
          "options": {
            "cypressConfig": "apps/todos-e2e/cypress.json",
            "tsConfig": "apps/todos-e2e/tsconfig.e2e.json",
            "devServerTarget": "todos:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "todos:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "apps/todos-e2e/tsconfig.e2e.json",
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    },
    "mylib": {
      "root": "libs/mylib",
      "sourceRoot": "libs/mylib/src",
      "projectType": "library",
      "prefix": "myorg",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "libs/mylib/tsconfig.lib.json",
            "project": "libs/mylib/ng-package.json"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "libs/mylib/tsconfig.lib.json",
              "libs/mylib/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**"]
          }
        },
        "test": {
          "builder": "@nrwl/builders:jest",
          "options": {
            "jestConfig": "libs/mylib/jest.config.js",
            "tsConfig": "libs/mylib/tsconfig.spec.json",
            "setupFile": "libs/mylib/src/test-setup.ts"
          }
        }
      },
      "schematics": {
        "@nrwl/schematics:component": {
          "styleext": "scss"
        }
      }
    }
  },
  "cli": {
    "warnings": {
      "typescriptMismatch": false,
      "versionMismatch": false
    },
    "defaultCollection": "@nrwl/schematics"
  },
  "schematics": {
    "@nrwl/schematics:application": {
      "style": "scss"
    },
    "@nrwl/schematics:library": {
      "style": "scss"
    }
  },
  "defaultProject": "todos"
}
```
### Failure Logs
```
Running build for mylib
Configuration 'production' could not be found in project 'mylib'.
Error: Configuration 'production' could not be found in project 'mylib'.
    at Architect.getBuilderConfiguration (/.../myorg/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js:127:23)
    at BuildCommand.runSingleTarget (/.../myorg/node_modules/@angular/cli/models/architect-command.js:160:45)
    at BuildCommand.runArchitectTarget (/.../myorg/node_modules/@angular/cli/models/architect-command.js:201:35)
    at BuildCommand.run (/.../myorg/node_modules/@angular/cli/commands/build-impl.js:21:21)
    at BuildCommand.validateAndRun (/.../myorg/node_modules/@angular/cli/models/command.js:124:31)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:865:11)
    at internal/main/run_main_module.js:21:11
Running build for affected projects failed.
Failed projects: mylib
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Other
I hope it's correct to report this issue here. 
Thank you for looking into this!

**Comment by schackito** [comment]
For now i'm adding:
```
"configurations": {
    "production": {}
}
```
under `lib --> architect --> build` in `angular.json`. That's how `yarn run affected:build --base=HEAD --prod` works with publishable libs.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
