### ISSUE TITLE
Updated @nrwl/node from 14.7.5 to 14.7.8 causes "NX Cannot read properties of undefined (reading 'map')"

### ISSUE THREAD

**Issue by rujorgensen** [nrwl/nx#12172]
## Current Behavior
When I update `@nrwl/node` from v 14.7.5 to 14.7.8, then I can't serve my backend server(s) using `nx serve ...`.

### Failure Logs
Running `nx serve backend-server --verbose` (replaced sensitive info.):

```
 >  NX   Cannot read properties of undefined (reading 'map')


TypeError: Cannot read properties of undefined (reading 'map')
    at normalizeExtraEntryPoints (C:\Users\rj\Documents\Workspace\company-name\my-project-name\node_modules\@nrwl\webpack\src\utils\webpack\normalize-entry.js:8:29)
    at getCommonConfig (C:\Users\rj\Documents\Workspace\company-name\my-project-name\node_modules\@nrwl\webpack\src\utils\webpack\partials\common.js:73:87)
    at getCommonPartial (C:\Users\rj\Documents\Workspace\company-name\my-project-name\node_modules\@nrwl\webpack\src\executors\webpack\lib\get-webpack-config.js:74:55)
    at getWebpackConfig (C:\Users\rj\Documents\Workspace\company-name\my-project-name\node_modules\@nrwl\webpack\src\executors\webpack\lib\get-webpack-config.js:57:9)
    at C:\Users\rj\Documents\Workspace\company-name\my-project-name\node_modules\@nrwl\webpack\src\executors\webpack\webpack.impl.js:44:55
    at Generator.next (<anonymous>)
    at C:\Users\rj\Documents\Workspace\company-name\my-project-name\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\rj\Documents\Workspace\company-name\my-project-name\node_modules\tslib\tslib.js:114:16)
    at getWebpackConfigs (C:\Users\rj\Documents\Workspace\company-name\my-project-name\node_modules\@nrwl\webpack\src\executors\webpack\webpack.impl.js:22:20)
```

### Environment
OS: 
Windows 10

`nx --version`:
14.7.8

`npm --version`:
8.15.0

`node -v`:
v16.17.0

**Comment by rujorgensen** [comment]
For the record: I attempted to run the current NX migrations, replacing `@nrwl/node:webpack` with `@nrwl/webpack:webpack` in my workspace.json yesterday, but I get some issues with my .env file not being loaded, just wanted to mention it, as it seems to be related.

**Comment by Jedliu** [comment]
Update to version 14.7.11 fixed my problem. You could have a try.

**Comment by rujorgensen** [comment]
@Jedliu  Running the NX migration updating to 14.7.11 fixed the issue, thanks 🙂!
