### ISSUE TITLE
[Jest] Unable to test React application or library that uses react-intl

### ISSUE THREAD

**Issue by smallstepstoday** [nrwl/nx#12223]
## Current Behavior

Any application or library that utilizes the `react-intl` library for internationalization fails to run Jest tests. This is despite implementing the instructions [here](https://formatjs.io/docs/tooling/babel-plugin) to enable integration via `babel` plugin.

The error received is:
```
           [@formatjs/intl] An `id` must be provided to format a message. You can either:
           1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
           or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
           2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
           to autofix this issue
```

It is not clear what additional steps are required to ensure successful test runs.

## Expected Behavior

The tests should succeed. The messages are displayed when the application is `serve`'d.

## Steps to Reproduce

- Create new Nx Repository
- Create React library: `npx nx g @nrwl/react:application test-app`
- Create React application: `npx nx g @nrwl/react:application test-app --buildable`
- Run lint/build/test cycle: `NODE_ENV=test npx nx run-many --target=lint --all --parallel && npx nx run-many --target=build --all --parallel && npx nx run-many --target=test --all --parallel` -- These all succeed
- Install react-intl: `npm install react-intl`
- Install babel plugin: `npm i -D babel-plugin-formatjs`
- Add plugin to root `babel.config.json`:

```json
// babel.config.json
{
  "babelrcRoots": ["*"],
  "plugins": [
    [
      "formatjs",
      {
        "idInterpolationPattern": "[sha512:contenthash:base64:6]",
        "ast": true
      }
    ]
  ]
}
```

- Add a message to the application and library code:

```typescript
// apps/test-app/src/app/nx-welcome.tsx
import { useIntl } from "react-intl";
...
  const intl = useIntl();
...
<p>{intl.formatMessage({
  defaultMessage: 'This is an app-level message',
  description: 'An app-level message',
})}</p>
...
```

```typescript
// libs/test-library/src/lib/test-library.tsx
import { useIntl } from "react-intl";
/* eslint-disable-next-line */
export interface TestLibraryProps {}

export function TestLibrary(props: TestLibraryProps) {
  const intl = useIntl();
  return (
    <div>
      <h1>{intl.formatMessage(
  {
    description: 'A message', // Description should be a string literal
    defaultMessage: 'This is a test', // Message should be a string literal
  })}</h1>
    </div>
  );
}

export default TestLibrary;
```

- Run lint/build/test cycle: `NODE_ENV=test npx nx run-many --target=lint --all --parallel && npx nx run-many --target=build --all --parallel && npx nx run-many --target=test --all --parallel` -- These all fail
- Add plugins to application and library babel configurations:

```
// apps/test-app/.babelrc
{
  "presets": [
    [
      "@nrwl/react/babel",
      {
        "runtime": "automatic"
      }
    ]
  ],
  "plugins": [
    [
      "formatjs",
      {
        "idInterpolationPattern": "[sha512:contenthash:base64:6]",
        "ast": true
      }
    ]
  ]
}
```

```
// libs/test-library/.babelrc
{
  "presets": [
    [
      "@nrwl/react/babel",
      {
        "runtime": "automatic",
        "useBuiltIns": "usage"
      }
    ]
  ],
  "plugins": [
    [
      "formatjs",
      {
        "idInterpolationPattern": "[sha512:contenthash:base64:6]",
        "ast": true
      }
    ]
  ]
}
```

- Run lint/build/test cycle: `NODE_ENV=test npx nx run-many --target=lint --all --parallel && npx nx run-many --target=build --all --parallel && npx nx run-many --target=test --all --parallel` -- These all fail

See repository [here](https://github.com/smallstepstoday/react-intl-issue).

### Failure Logs

The error received is:
```
           [@formatjs/intl] An `id` must be provided to format a message. You can either:
           1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
           or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
           2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
           to autofix this issue
```
Additional console logging shows the following (multiple instances):
```
    ✖  nx run test-app:test
  console.error
           Error: Uncaught [Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
           1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
           or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
           2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
           to autofix this issue]
               at reportException (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
               at innerInvokeEventListeners (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:343:9)
               at invokeEventListeners (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
               at HTMLUnknownElementImpl._dispatch (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
               at HTMLUnknownElementImpl.dispatchEvent (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
               at HTMLUnknownElement.dispatchEvent (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
               at Object.invokeGuardedCallbackDev (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
               at invokeGuardedCallback (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
               at beginWork$1 (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:27451:7)
               at performUnitOfWork (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:26560:12)
               at workLoopSync (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:26466:5)
               at renderRootSync (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:26434:7)
               at performConcurrentWorkOnRoot (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:25738:74)
               at flushActQueue (/Users/david/Projects/test/node_modules/react/cjs/react.development.js:2667:24)
               at act (/Users/david/Projects/test/node_modules/react/cjs/react.development.js:2582:11)
               at /Users/david/Projects/test/node_modules/@testing-library/react/dist/act-compat.js:63:25
               at renderRoot (/Users/david/Projects/test/node_modules/@testing-library/react/dist/pure.js:159:26)
               at render (/Users/david/Projects/test/node_modules/@testing-library/react/dist/pure.js:246:10)
               at Object.<anonymous> (/Users/david/Projects/test/apps/test-app/src/app/app.spec.tsx:9:29)
               at Promise.then.completed (/Users/david/Projects/test/node_modules/jest-circus/build/utils.js:333:28)
               at new Promise (<anonymous>)
               at callAsyncCircusFn (/Users/david/Projects/test/node_modules/jest-circus/build/utils.js:259:10)
               at _callCircusTest (/Users/david/Projects/test/node_modules/jest-circus/build/run.js:277:40)
               at async _runTest (/Users/david/Projects/test/node_modules/jest-circus/build/run.js:209:3)
               at async _runTestsForDescribeBlock (/Users/david/Projects/test/node_modules/jest-circus/build/run.js:97:9)
               at async _runTestsForDescribeBlock (/Users/david/Projects/test/node_modules/jest-circus/build/run.js:91:9)
               at async run (/Users/david/Projects/test/node_modules/jest-circus/build/run.js:31:3)
               at async runAndTransformResultsToJestFormat (/Users/david/Projects/test/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
               at async jestAdapter (/Users/david/Projects/test/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:92:19)
               at async runTestInternal (/Users/david/Projects/test/node_modules/jest-runner/build/runTest.js:411:16)
               at async runTest (/Users/david/Projects/test/node_modules/jest-runner/build/runTest.js:499:34) {
             detail: Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
             1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
             or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
             2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
             to autofix this issue
                 at invariant (/Users/david/Projects/test/node_modules/@formatjs/ecma402-abstract/utils.js:87:15)
                 at formatMessage (/Users/david/Projects/test/node_modules/@formatjs/intl/src/message.js:34:38)
                 at formatMessage (/Users/david/Projects/test/node_modules/react-intl/src/components/provider.js:49:39)
                 at TestLibrary (/Users/david/Projects/test/libs/test-library/src/lib/test-library.tsx:9:17)
                 at renderWithHooks (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:16305:18)
                 at mountIndeterminateComponent (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:20074:13)
                 at beginWork (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:21587:16)
                 at HTMLUnknownElement.callCallback (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:4164:14)
                 at HTMLUnknownElement.callTheUserObjectsOperation (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
                 at innerInvokeEventListeners (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:340:25)
                 at invokeEventListeners (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
                 at HTMLUnknownElementImpl._dispatch (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
                 at HTMLUnknownElementImpl.dispatchEvent (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
                 at HTMLUnknownElement.dispatchEvent (/Users/david/Projects/test/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
                 at Object.invokeGuardedCallbackDev (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
                 at invokeGuardedCallback (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
                 at beginWork$1 (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:27451:7)
                 at performUnitOfWork (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:26560:12)
                 at workLoopSync (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:26466:5)
                 at renderRootSync (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:26434:7)
                 at performConcurrentWorkOnRoot (/Users/david/Projects/test/node_modules/react-dom/cjs/react-dom.development.js:25738:74)
                 at flushActQueue (/Users/david/Projects/test/node_modules/react/cjs/react.development.js:2667:24)
                 at act (/Users/david/Projects/test/node_modules/react/cjs/react.development.js:2582:11)
                 at /Users/david/Projects/test/node_modules/@testing-library/react/dist/act-compat.js:63:25
                 at renderRoot (/Users/david/Projects/test/node_modules/@testing-library/react/dist/pure.js:159:26)
                 at render (/Users/david/Projects/test/node_modules/@testing-library/react/dist/pure.js:246:10)
                 at Object.<anonymous> (/Users/david/Projects/test/apps/test-app/src/app/app.spec.tsx:9:29)
                 at Promise.then.completed (/Users/david/Projects/test/node_modules/jest-circus/build/utils.js:333:28)
                 at new Promise (<anonymous>)
                 at callAsyncCircusFn (/Users/david/Projects/test/node_modules/jest-circus/build/utils.js:259:10)
                 at _callCircusTest (/Users/david/Projects/test/node_modules/jest-circus/build/run.js:277:40)
                 at async _runTest (/Users/david/Projects/test/node_modules/jest-circus/build/run.js:209:3)
                 at async _runTestsForDescribeBlock (/Users/david/Projects/test/node_modules/jest-circus/build/run.js:97:9)
                 at async _runTestsForDescribeBlock (/Users/david/Projects/test/node_modules/jest-circus/build/run.js:91:9)
                 at async run (/Users/david/Projects/test/node_modules/jest-circus/build/run.js:31:3)
                 at async runAndTransformResultsToJestFormat (/Users/david/Projects/test/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
                 at async jestAdapter (/Users/david/Projects/test/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:92:19)
                 at async runTestInternal (/Users/david/Projects/test/node_modules/jest-runner/build/runTest.js:411:16)
                 at async runTest (/Users/david/Projects/test/node_modules/jest-runner/build/runTest.js:499:34),
             type: 'unhandled exception'
           }
       
              7 | describe('App', () => {
              8 |   it('should render successfully', () => {
           >  9 |     const { baseElement } = render(
                |                             ^
             10 |       <BrowserRouter>
             11 |         <App />
             12 |       </BrowserRouter>
       
             at VirtualConsole.<anonymous> (../../node_modules/jest-environment-jsdom/build/index.js:70:23)
             at reportException (../../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
             at innerInvokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:343:9)
             at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
             at HTMLUnknownElementImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
             at HTMLUnknownElementImpl.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
             at HTMLUnknownElement.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
             at Object.invokeGuardedCallbackDev (../../node_modules/react-dom/cjs/react-dom.development.js:4213:16)
             at invokeGuardedCallback (../../node_modules/react-dom/cjs/react-dom.development.js:4277:31)
             at beginWork$1 (../../node_modules/react-dom/cjs/react-dom.development.js:27451:7)
             at performUnitOfWork (../../node_modules/react-dom/cjs/react-dom.development.js:26560:12)
             at workLoopSync (../../node_modules/react-dom/cjs/react-dom.development.js:26466:5)
             at renderRootSync (../../node_modules/react-dom/cjs/react-dom.development.js:26434:7)
             at performConcurrentWorkOnRoot (../../node_modules/react-dom/cjs/react-dom.development.js:25738:74)
             at flushActQueue (../../node_modules/react/cjs/react.development.js:2667:24)
             at act (../../node_modules/react/cjs/react.development.js:2582:11)
             at ../../node_modules/@testing-library/react/dist/act-compat.js:63:25
             at renderRoot (../../node_modules/@testing-library/react/dist/pure.js:159:26)
             at render (../../node_modules/@testing-library/react/dist/pure.js:246:10)
             at Object.<anonymous> (src/app/app.spec.tsx:9:29)
```

### Environment

```
   Node : 18.9.0
   OS   : darwin arm64
   npm  : 8.19.1
   
   nx : 14.7.13
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.7.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.13
   @nrwl/eslint-plugin-nx : 14.7.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.13
   @nrwl/js : 14.7.13
   @nrwl/linter : 14.7.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.7.13
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.13
   @nrwl/web : 14.7.13
   @nrwl/workspace : 14.7.13
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by barbados-clemens** [comment]
have you tried adding to the `.babelrc` and then including that as the config file for the babel-jest transformer?

this will force the babelrc to be applied vs being inferred which I've seen have some issues with file not getting the preset applied

```ts
    '^.+\\.[tj]sx?$': ['babel-jest', { configFile: path.join(__dirname, '.babelrc') }],
```

**Comment by smallstepstoday** [comment]
Genius! That works. Thank you.
