### ISSUE TITLE
Jest error when testing components with SVG react

### ISSUE THREAD

**Issue by LouisLecouturier** [nrwl/nx#12333]
## Current Behavior

When I try to run my tests via nx console I get this error :

```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){<svg height="100%" stroke-miterlimit="10"
                                                                                      ^

    SyntaxError: Unexpected token '<'

      3 | import { NavLink } from 'react-router-dom';
      4 |
    > 5 | import { ReactComponent as Logo } from '../../../../../../assets/svg/brand/logo.svg';
        | ^
      6 | import { ReactComponent as Home } from '../../../../../../assets/svg/icons/sellers/home.svg';
      7 | import { ReactComponent as Wallet } from '../../../../../../assets/svg/icons/common/wallet.svg';
      8 | import { ReactComponent as Orders } from '../../../../../../assets/svg/icons/common/orders.svg';

      at Runtime.createScriptFromCode (../../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/lib/Panel/Layout/Navigation/index.tsx:5:1)
      at Object.<anonymous> (src/lib/Panel/Layout/Navigation/index.spec.tsx:3:1)
      at async TestScheduler.scheduleTests (../../../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at async runJest (../../../node_modules/@jest/core/build/runJest.js:404:19)
      at async _run10000 (../../../node_modules/@jest/core/build/cli/index.js:320:7)
      at async runCLI (../../../node_modules/@jest/core/build/cli/index.js:173:3)
```

After some researches online, it seems that Jest is not happy with components using `svgr` components...
I recently had some issues with my nx versions so I had to change my config/versions...

## Expected Behavior
Tests should run with no worries.

### Environment

Nx config :
```
Node : 16.15.1
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 14.8.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : 14.8.1
   @nrwl/next : 14.5.4
   @nrwl/node : 14.5.4
   @nrwl/nx-cloud : 14.3.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.4
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment]
Hey @LouisLecouturier, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by LouisLecouturier** [comment]
Hey I found a solution to my problem reproducing some things from a repo I found :
https://github.com/Lonli-Lokli/nx-reacticon

I think that's a shame that nx doesn't come with this out of the box... May save a lot of time for many users...


Anyway thanks ! I'll update my packages ^^
