### ISSUE TITLE
Creating a new workspace failed with error

### ISSUE THREAD

**Issue by vinoth-berkmons** [nrwl/nx#1234]
Creating a new workspace failed with error

When I run
create-nx-workspace angular-core

ng new "app-name" --collection=@nrwl/schematics
Could not find module "@nrwl/schematics" from "/Users/vinoth/Documents/vinoth/Angular/angular-core".
Error: Could not find module "@nrwl/schematics" from "/Users/vinoth/Documents/vinoth/Angular/angular-core".
    at Object.resolve (/Users/vinoth/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at NodeModulesEngineHost._resolvePackageJson (/Users/vinoth/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:28:21)
    at NodeModulesEngineHost._resolveCollectionPath (/Users/vinoth/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:69:40)
    at NodeModulesEngineHost.createCollectionDescription (/Users/vinoth/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:111:27)
    at SchematicEngine._createCollectionDescription (/Users/vinoth/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/Users/vinoth/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at NewCommand.getCollection (/Users/vinoth/node_modules/@angular/cli/models/schematic-command.js:123:35)
    at NewCommand.runSchematic (/Users/vinoth/node_modules/@angular/cli/models/schematic-command.js:262:50)
    at NewCommand.run (/Users/vinoth/node_modules/@angular/cli/commands/new-impl.js:29:21)
    at NewCommand.validateAndRun (/Users/vinoth/node_modules/@angular/cli/models/command.js:124:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
child_process.js:656
    throw err;
    ^

Error: Command failed: /var/folders/5w/nykk9gh126ndg310qrqtr1p40000gn/T/tmp-72901e24SYJpJK2zw/node_modules/.bin/ng new "app-name" --collection=@nrwl/schematics
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at Object.<anonymous> (/Users/vinoth/.npm-global/lib/node_modules/@nrwl/schematics/bin/create-nx-workspace.js:61:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by SebasG22** [comment]
Seems like `@nrwl/schematics` are not installed on your machine. Use the `npm list -g @nrwl/schematics` to check the version. If not, try to install globally `npm i - g @nrwl/schematics`.

**Comment by vinoth-berkmons** [comment]
@SebasG22 @nrwl/schematics installed in my machine. and the version is @nrwl/schematics@7.8.0

**Comment by SebasG22** [comment]
Try to generate an app or lib using `ng new app myApp`
![Nx-Generate-App2](https://user-images.githubusercontent.com/17608169/55675350-c6761480-5886-11e9-8e3f-e88483eb99a7.gif)
![Nx-Routing-Prompt](https://user-images.githubusercontent.com/17608169/55675351-caa23200-5886-11e9-93e6-cb63d3402bcf.gif)

**Comment by vinoth-berkmons** [comment]
@SebasG22 I can able to do **ng new angular-core**. But not able to do **create-nx-workspace angular-core**.

**Comment by vsavkin** [comment]
@vinoth-berkmons could you try `npx create-nx-workspace myworkspace`?

**Comment by vinoth-berkmons** [comment]
@vsavkin 

When I run
npx create-nx-workspace myworkspace, this is what i'm getting.

npx: installed 53 in 6.432s
Creating a sandbox with Nx...
[fsevents] Success: "/private/var/folders/5w/nykk9gh126ndg310qrqtr1p40000gn/T/tmp-13327YbKzDP1ekFcn/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
added 454 packages from 239 contributors and audited 17577 packages in 12.218s
found 0 vulnerabilities

ng new "myworkspace" --collection=@nrwl/schematics
Could not find module "@nrwl/schematics" from "/Users/vinoth/Documents/vinoth/Angular/npx-test".
Error: Could not find module "@nrwl/schematics" from "/Users/vinoth/Documents/vinoth/Angular/npx-test".
    at Object.resolve (/Users/vinoth/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at NodeModulesEngineHost._resolvePackageJson (/Users/vinoth/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:28:21)
    at NodeModulesEngineHost._resolveCollectionPath (/Users/vinoth/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:69:40)
    at NodeModulesEngineHost.createCollectionDescription (/Users/vinoth/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:111:27)
    at SchematicEngine._createCollectionDescription (/Users/vinoth/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/Users/vinoth/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at NewCommand.getCollection (/Users/vinoth/node_modules/@angular/cli/models/schematic-command.js:123:35)
    at NewCommand.runSchematic (/Users/vinoth/node_modules/@angular/cli/models/schematic-command.js:262:50)
    at NewCommand.run (/Users/vinoth/node_modules/@angular/cli/commands/new-impl.js:29:21)
    at NewCommand.validateAndRun (/Users/vinoth/node_modules/@angular/cli/models/command.js:124:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by sidsakhadeo** [comment]
@vinoth-berkmons Check if you already have a directory called `angular-core` in the location that you're running the command

**Comment by vsavkin** [comment]
@vinoth-berkmons it looks like you have node modules in the home dir which affects the angular cli.  If you delete them, the command should work.

**Comment by vsavkin** [comment]
Closing this issue. The issue is like to be the problem with the local environment.

**Comment by HackPoint** [comment]
> @vinoth-berkmons could you try `npx create-nx-workspace myworkspace`?

~/projects:🚀 (genadyshmunik)$ npx create-nx-workspace fastry
npx: installed 162 in 7.576s
? What to create in the new workspace angular-nest      [a workspace with a full
 stack application (Angular + Nest)]
? Application name                    fastry
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
Creating a sandbox with Nx...
(node:10328) UnhandledPromiseRejectionWarning: Error: Command failed: npm install --silent
    at checkExecSyncError (child_process.js:600:11)
    at Object.execSync (child_process.js:637:13)
    at createSandbox (/Users/gena/.npm/_npx/10328/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:288:21)
    at /Users/gena/.npm/_npx/10328/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:59:34
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
