### ISSUE TITLE
Jest config cannot be resolved on Windows

### ISSUE THREAD

**Issue by tamas-nemeth** [nrwl/nx#1244]
## Expected Behavior

Tests run

## Current Behavior

`ng test` throws the following error 
```
Can't find a root directory while resolving a config file path.
Provided path to resolve: C:\C\DEV\myworkspace\apps\myapp\jest.config.js
```

### Steps to Reproduce

1. npm install -g @angular/cli
2. npx create-nx-workspace myworkspace
3. npm t

### Context

Please provide any relevant information about your setup:

- version of Nx used: 7.8.0 (still works with 7.7.2)
- version of Angular CLI used: 7.3.1
- node version: v10.15.3
- npm version: 6.4.1
- OS: Windows 10 (1809)

### Failure Logs

```
Can't find a root directory while resolving a config file path.
Provided path to resolve: C:\C\DEV\myworkspace\apps\myapp\jest.config.js
cwd: C:\DEV\myworkspace
Error: Can't find a root directory while resolving a config file path.
Provided path to resolve: C:\C\DEV\myworkspace\apps\myapp\jest.config.js
cwd: C:\DEV\myworkspace
    at _default (C:\DEV\myworkspace\node_modules\jest-config\build\resolveConfigPath.js:69:11)
    at readConfig (C:\DEV\myworkspace\node_modules\jest-config\build\index.js:156:49)
    at readConfigs (C:\DEV\myworkspace\node_modules\jest-config\build\index.js:368:26)
    at C:\DEV\myworkspace\node_modules\@jest\core\build\cli\index.js:155:58
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\DEV\myworkspace\node_modules\@jest\core\build\cli\index.js:108:24)
    at _next (C:\DEV\myworkspace\node_modules\@jest\core\build\cli\index.js:128:9)
    at C:\DEV\myworkspace\node_modules\@jest\core\build\cli\index.js:133:7
    at new Promise (<anonymous>)
    at C:\DEV\myworkspace\node_modules\@jest\core\build\cli\index.js:125:12
    at runCLI (C:\DEV\myworkspace\node_modules\@jest\core\build\cli\index.js:226:19)
    at JestBuilder.run (C:\DEV\myworkspace\node_modules\@nrwl\builders\src\jest\jest.builder.js:65:28)
    at MergeMapSubscriber.getBuilderDescription.pipe.operators_1.concatMap.builder [as project] (C:\DEV\myworkspace\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect-legacy.js:142:415)
    at MergeMapSubscriber._tryNext (C:\DEV\myworkspace\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (C:\DEV\myworkspace\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\DEV\myworkspace\node_modules\rxjs\internal\Subscriber.js:67:18)
```

**Comment by tamas-nemeth** [comment]
sorry, dupe of https://github.com/nrwl/nx/issues/1242

**Comment by tamas-nemeth** [comment]
sorry, dupe of https://github.com/nrwl/nx/issues/1242
