### ISSUE TITLE
Bug: Lint fails on exports with no module specifier

### ISSUE THREAD

**Issue by mwhitis** [nrwl/nx#1251]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

nx lint runs without errors

## Current Behavior

nx lint fails with an exception

## Failure Information (for bugs)

Cannot read property 'getText' of undefined
TypeError: Cannot read property 'getText' of undefined
    at DepsCalculator.getStringLiteralValue (/foo/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:252:21)
    at DepsCalculator.processNode (/foo/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:202:28)
    at /foo/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:220:63
    at visitNodes (/foo/node_modules/typescript/lib/typescript.js:16144:30)
    at Object.forEachChild (/foo/node_modules/typescript/lib/typescript.js:16372:24)
    at DepsCalculator.processNode (/foo/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:220:12)
    at DepsCalculator.processFile (/foo/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:152:18)
    at /foo/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:68:24
    at Array.forEach (<anonymous>)
    at /foo/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:67:14
    at Array.forEach (<anonymous>)
    at dependencies (/foo/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:60:10)
    at Object.readDependencies (/foo/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:35:16)
    at new Rule (/foo/node_modules/@nrwl/schematics/src/tslint/nxEnforceModuleBoundariesRule.js:48:49)
    at Object.loadRules (/foo/node_modules/tslint/lib/ruleLoader.js:47:24)
    at Linter.getEnabledRules (/foo/node_modules/tslint/lib/linter.js:195:29)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. export a property from a class with no module specifier 

ex:

import * as fooActions from './foo.actions';
export { fooActions };

### Context

Please provide any relevant information about your setup:

- version of Nx used: 7.8.0
- version of Angular CLI used: 7.3.8

## Other

The getLiteralValue function in deps-calculator.js is not checking for undefined before attempting to expand properties:

    DepsCalculator.prototype.getStringLiteralValue = function (node) {
        return node.getText().substr(1, node.getText().length - 2);
    };

Where the failure is occurring, the text being passed in is the node.moduleSpecifier value.  This is not required for exports, and is being set to undefined in the use case above.

**Comment by kamilchlebek** [comment]
In my case I've "fixed" the issue by changing order of `export` in `.ts` files.

Failing version: 
```
import { foo } from './foo'
export { foo }
export const obj = {}
```

Passing version:
```
import { foo } from './foo'
export const obj = {}
export { foo }
```

Or by merging multiple exports into one:
```
import { foo } from './foo'
const obj = {}
export { foo, obj }
```

**Comment by abierbaum** [comment]
Causing problems for us to while moving an existing project over to Nx.  Haven't been able to track it down completely yet, but the error stack looks the same.

**Comment by FrozenPandaz** [comment]
@kamilchlebek
I checked the failing version of the code and it does not seem to be erroring anymore. Can you please check that this issue is reproducible with the current version of Nx?

**Comment by kamilchlebek** [comment]
To be honest after I fixed it in my way I forgot about this issue. Currently I can't find the place in the code that was affected by this problem. Maybe @mwhitis can see if it's okay on his side.

**Comment by vsavkin** [comment]
any update? if you could provide a repro, we will take a look.

**Comment by FrozenPandaz** [comment]
This issue should be resolved.

If you continue to experience this issue, please open a new issue with a repro.
