### ISSUE TITLE
nx/cli - angular - Generate pages - Specified module 'page/page.module.ts' does not exist.

### ISSUE THREAD

**Issue by PieterjanDeClippel** [nrwl/nx#12517]
I did experience [this bug earlier](https://github.com/nrwl/nx/issues/10009).
- I checked the [pull-request](https://github.com/nrwl/nx/pull/10113/files#diff-4574d87905e021ec469f8dbb9303705cc116b0bb67d45d0524b57e08459aad69) and verified that the code changes still apply to the [current HEAD of master](https://github.com/nrwl/nx/blob/master/packages/nx/src/adapter/ngcli-adapter.ts#L744)

### Environment

```
PS C:\repos\aaa\bundletest\apps\demo\src\app> nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : win32 x64
   OS description: Windows 11
   npm  : 8.1.2
   
   nx : 13.10.6
   @nrwl/angular : 13.10.6
   @nrwl/cypress : 13.10.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.6
   @nrwl/eslint-plugin-nx : 13.10.6
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.6
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.6
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.6
   typescript : 4.6.4
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
```
There are no spaces in the CWD

## Current Behavior

I'm unable to generate pages in my angular app.

## Expected Behavior

    nx g module page --module app --route page --project demo

should generate a page (module + component) in my app

## Steps to Reproduce

    npx --yes create-nx-workspace --name pagetest --preset angular --appName demo --style scss --nxCloud false

Import the `RouterModule.forRoot([])` in the `AppModule`

    cd pagetest\apps\demo\src\app
    nx g module home --module app --route home

Result

```
PS C:\repos\bb\pagetest\apps\demo\src\app> nx g module home --module app --route home
Error: Specified module 'home/home.module.ts' does not exist.
Looked in the following directories:
    /apps/demo/src/app/home/home.module.ts
    /apps/demo/src/app/home
    /apps/demo/src/app
    /apps/demo/src
    /apps/demo
    /apps
    at findModuleFromOptions (C:\repos\bb\pagetest\node_modules\@schematics\angular\utility\find-module.js:48:15)
    at C:\repos\bb\pagetest\node_modules\@schematics\angular\component\index.js:109:66
Error: Specified module 'home/home.module.ts' does not exist.
Looked in the following directories:
    /apps/demo/src/app/home/home.module.ts
    /apps/demo/src/app/home
    /apps/demo/src/app
    /apps/demo/src
    /apps/demo
    /apps
    at findModuleFromOptions (C:\repos\bb\pagetest\node_modules\@schematics\angular\utility\find-module.js:48:15)
    at C:\repos\bb\pagetest\node_modules\@schematics\angular\component\index.js:109:66
Specified module 'home/home.module.ts' does not exist.
Looked in the following directories:
    /apps/demo/src/app/home/home.module.ts
    /apps/demo/src/app/home
    /apps/demo/src/app
    /apps/demo/src
    /apps/demo
    /apps
```

Same with the `--project` flag

    nx g module home --module app --route home --project demo

[Repository](https://github.com/PieterjanDeClippel/pagetest)

**Comment by PieterjanDeClippel** [comment]
I'm sorry. This bug seems to be fixed in an intermediate version.

    nx migrate latest
    npm update
    npx nx migrate --run-migrations

Fixed this.
