### ISSUE TITLE
TypeError: Class constructor E cannot be invoked without 'new' after nx migration

### ISSUE THREAD

**Issue by liitfr** [nrwl/nx#12592]
Hello, 
I have executed `npx nx migrate next` command, coming from `14.7.5` version.
(same problem when trying to migrate to `14.8.4` version).

My backend app is a `nestjs` one. I'm using `"@nestjs/mongoose": "^9.1.1",` & `"mongoose": "^6.6.5",`

When starting my backend server, i'm now experiencing following issue : 

## Current Behavior

```
Debugger listening on ws://localhost:9229/a40cd1be-3f68-498e-8801-a5957805d47a
For help, see: https://nodejs.org/en/docs/inspector

/home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/definitions.factory.js:43
            optionsOrType = isClass ? optionsOrType : optionsOrType();
                                                      ^
TypeError: Class constructor E cannot be invoked without 'new'
    at Function.inspectTypeDefinition (/home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/definitions.factory.js:43:55)
    at Function.inspectTypeDefinition (/home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/definitions.factory.js:52:39)
    at /home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/definitions.factory.js:26:38
    at Array.forEach (<anonymous>)
    at Function.createForClass (/home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/definitions.factory.js:25:86)
    at Function.createForClass (/home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/schema.factory.js:9:75)
    at Object.moduleId [as 9511] (/home/foo/code/bar/dist/apps/back/webpack:/bar/apps/back/src/master-datas/entities/cost-margin.entity.ts:83:54)
    at a (/home/foo/code/bar/dist/apps/back/webpack:/bar/webpack/bootstrap:19:22)
    at Object.moduleId [as 7242] (/home/foo/code/bar/dist/apps/back/webpack:/bar/apps/back/src/master-datas/entities/index.ts:9:1)
    at a (/home/foo/code/bar/dist/apps/back/webpack:/bar/webpack/bootstrap:19:22)
```

## Expected Behavior

Regression : this error wasn't experienced before.

## Steps to Reproduce

`npx nx migrate next`

package.json initial dependencies : 

```json
 "devDependencies": {
    "@emotion/babel-plugin": "11.10.2",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.1.4",
    "@nrwl/cli": "^14.7.5",
    "@nrwl/cypress": "^14.7.5",
    "@nrwl/eslint-plugin-nx": "^14.7.5",
    "@nrwl/jest": "^14.7.5",
    "@nrwl/linter": "^14.7.5",
    "@nrwl/nest": "^14.7.5",
    "@nrwl/node": "^14.7.5",
    "@nrwl/react": "^14.7.5",
    "@nrwl/web": "^14.7.5",
    "@nrwl/workspace": "^14.7.5",
    "@testing-library/react": "13.4.0",
    "@types/bcrypt": "^5.0.0",
    "@types/cookie-parser": "^1.4.3",
    "@types/geojson": "^7946.0.10",
    "@types/jest": "^29.1.2",
    "@types/lodash": "^4.14.186",
    "@types/node": "^18.8.5",
    "@types/passport-jwt": "^3.0.7",
    "@types/passport-local": "^1.0.34",
    "@types/react": "^18.0.21",
    "@types/react-dom": "^18.0.6",
    "@types/react-router-dom": "5.3.3",
    "@types/sanitize-html": "^2.6.2",
    "@typescript-eslint/eslint-plugin": "^5.40.0",
    "@typescript-eslint/parser": "^5.40.0",
    "babel-jest": "^29.1.2",
    "cypress": "^10.10.0",
    "eslint": "^8.25.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-react": "^7.31.10",
    "eslint-plugin-react-hooks": "4.6.0",
    "jest": "^29.1.2",
    "jest-environment-jsdom": "^29.1.2",
    "nx": "^14.7.5",
    "prettier": "^2.6.2",
    "react-test-renderer": "18.2.0",
    "ts-jest": "^29.0.3",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4"
  },
  "dependencies": {
    "@apollo/client": "^3.7.0",
    "@apollo/gateway": "^2.1.3",
    "@babel/runtime": "^7.19.4",
    "@casl/ability": "^6.3.1",
    "@emotion/react": "^11.9.3",
    "@emotion/styled": "^11.9.3",
    "@faker-js/faker": "^7.6.0",
    "@graphql-codegen/cli": "^2.13.6",
    "@graphql-codegen/typescript": "^2.7.4",
    "@graphql-codegen/typescript-operations": "^2.5.4",
    "@graphql-codegen/typescript-react-query": "^4.0.2",
    "@mui/icons-material": "^5.10.9",
    "@mui/lab": "^5.0.0-alpha.103",
    "@mui/material": "^5.10.9",
    "@mui/x-data-grid": "^5.17.6",
    "@mui/x-date-pickers": "^5.0.4",
    "@nestjs/apollo": "^10.1.3",
    "@nestjs/common": "^9.1.4",
    "@nestjs/config": "^2.1.0",
    "@nestjs/core": "^9.1.4",
    "@nestjs/event-emitter": "^1.3.1",
    "@nestjs/graphql": "^10.1.3",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/mongoose": "^9.1.1",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.1.4",
    "@nestjs/serve-static": "^3.0.0",
    "@nrwl/nx-cloud": "^14.1.2",
    "@react-google-maps/api": "^2.13.1",
    "@tanstack/react-query": "^4.10.3",
    "@tanstack/react-query-devtools": "^4.11.0",
    "@tinymce/tinymce-react": "^4.2.0",
    "@toast-ui/react-image-editor": "^3.15.2",
    "apollo-server-express": "^3.10.3",
    "argon2": "^0.30.1",
    "bson-objectid": "^2.0.3",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "cookie-parser": "^1.4.6",
    "core-js": "^3.25.5",
    "csv2json": "^2.0.2",
    "date-fns": "^2.29.1",
    "formik": "^2.2.9",
    "geojson": "^0.5.0",
    "graphql": "^16.5.0",
    "graphql-request": "^4.3.0",
    "graphql-tools": "^8.3.6",
    "graphql-upload": "^15.0.2",
    "joi": "^17.6.3",
    "lodash": "^4.17.21",
    "mongoose": "^6.6.5",
    "mongoose-autopopulate": "^0.16.1",
    "notistack": "^2.0.5",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-helmet-async": "^1.3.0",
    "react-json-pretty": "^2.2.0",
    "react-router-dom": "^6.4.2",
    "reflect-metadata": "^0.1.13",
    "regenerator-runtime": "^0.13.10",
    "rxjs": "^7.5.7",
    "sanitize-html": "^2.7.2",
    "sharp": "^0.31.1",
    "ts-morph": "^16.0.0",
    "tslib": "^2.3.0",
    "typesense": "^1.4.1",
    "web-vitals": "^3.0.3"
  }
```

new back project.json : 

```
{
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/back/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nrwl/node:webpack",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/back",
        "main": "apps/back/src/main.ts",
        "tsConfig": "apps/back/tsconfig.app.json",
        "assets": [],
        "generatePackageJson": true
      },
      "configurations": {
        "development": {
          "optimization": true,
          "extractLicenses": true,
          "inspect": false
        },
        "local-docker": {
          "optimization": true,
          "extractLicenses": true,
          "inspect": false,
          "fileReplacements": [
            {
              "replace": "apps/back/src/environments/environment.ts",
              "with": "apps/back/src/environments/environment.local-docker.ts"
            }
          ]
        },
        "staging": {
          "optimization": true,
          "extractLicenses": true,
          "inspect": false,
          "fileReplacements": [
            {
              "replace": "apps/back/src/environments/environment.ts",
              "with": "apps/back/src/environments/environment.staging.ts"
            }
          ]
        },
        "production": {
          "optimization": true,
          "extractLicenses": true,
          "inspect": false,
          "fileReplacements": [
            {
              "replace": "apps/back/src/environments/environment.ts",
              "with": "apps/back/src/environments/environment.prod.ts"
            }
          ]
        }
      }
    },
    "serve": {
      "executor": "@nrwl/node:node",
      "configurations": {
        "development": {
          "buildTarget": "back:build:development"
        },
        "local-docker": {
          "buildTarget": "back:build:local-docker"
        },
        "staging": {
          "buildTarget": "back:build:staging"
        },
        "production": {
          "buildTarget": "back:build:production"
        }
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/back/**/*.ts"]
      }
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/apps/back"],
      "options": {
        "jestConfig": "apps/back/jest.config.ts",
        "passWithNoTests": true
      }
    },
    "build-docker": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "parallel": false
      },
      "configurations": {
        "local-docker": {
          "commands": [
            "nx build back --configuration=local-docker",
            "docker build -f ./apps/back/Dockerfile . -t foo"
          ]
        }
      }
    }
  },
  "tags": []
}

```

### Failure Logs

```
Debugger listening on ws://localhost:9229/a40cd1be-3f68-498e-8801-a5957805d47a
For help, see: https://nodejs.org/en/docs/inspector

/home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/definitions.factory.js:43
            optionsOrType = isClass ? optionsOrType : optionsOrType();
                                                      ^
TypeError: Class constructor E cannot be invoked without 'new'
    at Function.inspectTypeDefinition (/home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/definitions.factory.js:43:55)
    at Function.inspectTypeDefinition (/home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/definitions.factory.js:52:39)
    at /home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/definitions.factory.js:26:38
    at Array.forEach (<anonymous>)
    at Function.createForClass (/home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/definitions.factory.js:25:86)
    at Function.createForClass (/home/foo/code/bar/node_modules/@nestjs/mongoose/dist/factories/schema.factory.js:9:75)
    at Object.moduleId [as 9511] (/home/foo/code/bar/dist/apps/back/webpack:/bar/apps/back/src/master-datas/entities/cost-margin.entity.ts:83:54)
    at a (/home/foo/code/bar/dist/apps/back/webpack:/bar/webpack/bootstrap:19:22)
    at Object.moduleId [as 7242] (/home/foo/code/bar/dist/apps/back/webpack:/bar/apps/back/src/master-datas/entities/index.ts:9:1)
    at a (/home/foo/code/bar/dist/apps/back/webpack:/bar/webpack/bootstrap:19:22)
```

migrations.json : 

```
{
  "migrations": [
    {
      "cli": "nx",
      "version": "15.0.0-beta.1",
      "description": "Replace implicitDependencies with namedInputs + target inputs",
      "implementation": "./src/migrations/update-15-0-0/migrate-to-inputs",
      "package": "nx",
      "name": "15.0.0-migrate-to-inputs"
    },
    {
      "cli": "nx",
      "version": "15.0.0-beta.1",
      "description": "Prefix outputs with {workspaceRoot}/{projectRoot} if needed",
      "implementation": "./src/migrations/update-15-0-0/prefix-outputs",
      "package": "nx",
      "name": "15.0.0-prefix-outputs"
    },
    {
      "cli": "nx",
      "version": "15.0.0-beta.0",
      "description": "Stop hashing cypress spec files and config files for build targets and dependent tasks",
      "factory": "./src/migrations/update-15-0-0/add-cypress-inputs",
      "package": "@nrwl/cypress",
      "name": "add-cypress-inputs"
    },
    {
      "cli": "nx",
      "version": "15.0.0-beta.4",
      "description": "Update to using cy.mount in the commands.ts file instead of importing mount for each component test file",
      "factory": "./src/migrations/update-15-0-0/update-cy-mount-usage",
      "package": "@nrwl/cypress",
      "name": "update-cy-mount-usage"
    },
    {
      "version": "15.0.0-beta.0",
      "cli": "nx",
      "description": "Stop hashing jest spec files and config files for build targets and dependent tasks",
      "factory": "./src/migrations/update-15-0-0/add-jest-inputs",
      "package": "@nrwl/jest",
      "name": "add-jest-inputs"
    },
    {
      "cli": "nx",
      "version": "15.0.0-beta.0",
      "description": "Stop hashing eslint config files for build targets and dependent tasks",
      "factory": "./src/migrations/update-15-0-0/add-eslint-inputs",
      "package": "@nrwl/linter",
      "name": "add-eslint-inputs"
    },
    {
      "cli": "nx",
      "version": "15.0.0-beta.0",
      "description": "Adds babel.config.json to the hash of all tasks",
      "factory": "./src/migrations/update-15-0-0/add-babel-inputs",
      "package": "@nrwl/web",
      "name": "add-babel-inputs"
    },
    {
      "cli": "nx",
      "version": "15.0.0-beta.1",
      "description": "Update usages of rollup executors to @nrwl/rollup",
      "factory": "./src/migrations/update-15-0-0/update-rollup-executor",
      "package": "@nrwl/web",
      "name": "update-rollup-executor"
    }
  ]
}

```
### Environment

   Node : 16.17.0
   OS   : linux x64
   npm  : 8.15.0
   
   nx : 15.0.0-rc1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.0-rc1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0-rc1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0-rc1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0-rc1
   @nrwl/js : 15.0.0-rc1
   @nrwl/linter : 15.0.0-rc1
   @nrwl/nest : 15.0.0-rc1
   @nrwl/next : Not Found
   @nrwl/node : 15.0.0-rc1
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.0-rc1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.0-rc1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0-rc1
   @nrwl/web : 15.0.0-rc1
   @nrwl/webpack : 15.0.0-rc1
   @nrwl/workspace : 15.0.0-rc1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by FrozenPandaz** [comment]
Thank you so much for trying the beta and letting us know issues you found!

We just published the stable version. Could you see if updating to `15.0.0` fixes your issue? :pray:
