### ISSUE TITLE
Cannot launch Angular cypress component-test

### ISSUE THREAD

**Issue by GaetanRdn** [nrwl/nx#12637]
## Current Behavior
After having migrating to nx 15.0.0 and installing cypress component-test config for one of my angular library (buildable), I cannot launch the component-test command for this library.

## Expected Behavior

I expect to play with the new feature "cypress angular component-test"

## Steps to Reproduce
- migrate to nx 15.0.0
- add configuration to an angular library for cypress component testing
- run: nx run my-angular-buildable-library:component-test

### Failure Logs

`Your configFile is invalid: /myproject/libs/angular/ui/atoms/cypress.config.ts

It threw an error when required, check the stack trace below:

Error: Missing executor options "main"
    at withSchemaDefaults (/myproject/packages/angular/plugins/component-testing.ts:231:11)
    at normalizeBuildTargetOptions (/myproject/packages/angular/plugins/component-testing.ts:167:24)
    at nxComponentTestingPreset (/myproject/packages/angular/plugins/component-testing.ts:95:34)
    at Object.<anonymous> (/myproject/libs/angular/ui/atoms/cypress.config.ts:5:38)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/Users/gaetanredin/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/gaetanredin/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadFile (/Users/gaetanredin/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (/Users/gaetanredin/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:526:28)
    at EventEmitter.emit (node:domain:475:12)
    at process.<anonymous> (/Users/gaetanredin/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:526:28)
    at process.emit (node:domain:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/gaetanredin/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)``

content of the incriminated cypress config file:
`import { defineConfig } from 'cypress';
import { nxComponentTestingPreset } from '@nrwl/angular/plugins/component-testing';

export default defineConfig({
  component: nxComponentTestingPreset(__filename),
});`

component-test config in project.json of the library:
`"component-test": {
      "executor": "@nrwl/cypress:cypress",
      "options": {
        "cypressConfig": "libs/angular/ui/atoms/cypress.config.ts",
        "testingType": "component",
        "skipServe": true,
        "devServerTarget": "angular-ui-atoms:build"
      }
    }`

### Environment

 NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.0
   
   nx : 15.0.0
   @nrwl/angular : 15.0.0
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : 15.0.0
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @storybook/angular: 6.5.12

**Comment by barbados-clemens** [comment]
What is the project configuration for angular-ui-atoms:build ? Looks like it's missing the "main" field in that configuration.

**Comment by GaetanRdn** [comment]
Hi, this is the project.json of the library:

{
  "name": "angular-ui-atoms",
  "$schema": "../../../../node_modules/nx/schemas/project-schema.json",
  "projectType": "library",
  "sourceRoot": "libs/angular/ui/atoms/src",
  "prefix": "rc",
  "targets": {
    "build": {
      "executor": "@nrwl/angular:ng-packagr-lite",
      "outputs": [
        "{workspaceRoot}/dist/libs/angular/ui/atoms"
      ],
      "options": {
        "project": "libs/angular/ui/atoms/ng-package.json"
      },
      "configurations": {
        "production": {
          "tsConfig": "libs/angular/ui/atoms/tsconfig.lib.prod.json"
        },
        "development": {
          "tsConfig": "libs/angular/ui/atoms/tsconfig.lib.json"
        }
      },
      "defaultConfiguration": "production"
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": [
        "{workspaceRoot}/coverage/libs/angular/ui/atoms"
      ],
      "options": {
        "jestConfig": "libs/angular/ui/atoms/jest.config.ts",
        "passWithNoTests": true
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "options": {
        "lintFilePatterns": [
          "libs/angular/ui/atoms/**/*.ts",
          "libs/angular/ui/atoms/**/*.html"
        ]
      }
    },
    "storybook": {
      "executor": "@storybook/angular:start-storybook",
      "options": {
        "port": 4400,
        "configDir": "libs/angular/ui/atoms/.storybook",
        "browserTarget": "angular-ui-atoms:build-storybook",
        "compodoc": false
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
    "build-storybook": {
      "executor": "@storybook/angular:build-storybook",
      "outputs": [
        "{options.outputDir}"
      ],
      "options": {
        "outputDir": "dist/storybook/angular-ui-atoms",
        "configDir": "libs/angular/ui/atoms/.storybook",
        "browserTarget": "angular-ui-atoms:build-storybook",
        "compodoc": false
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
    "component-test": {
      "executor": "@nrwl/cypress:cypress",
      "options": {
        "cypressConfig": "libs/angular/ui/atoms/cypress.config.ts",
        "testingType": "component",
        "skipServe": true,
        "devServerTarget": "angular-ui-atoms:build"
      }
    }
  },
  "tags": [
    "ui"
  ]
}

**Comment by GaetanRdn** [comment]
After some tries, I found the problem.

I misunderstood the buildTarget param of the nx generators. Even if you have no Angular application in your workspace you have to generate one and use it.

I dit it and then I change this in the project.json of my lib:
`"component-test": {
      "executor": "@nrwl/cypress:cypress",
      "options": {
        "cypressConfig": "libs/angular/ui/atoms/cypress.config.ts",
        "testingType": "component",
        "skipServe": true,
        "devServerTarget": "angular-ui-atoms:build"
      }
    }`

to

`"component-test": {
      "executor": "@nrwl/cypress:cypress",
      "options": {
        "cypressConfig": "libs/angular/ui/atoms/cypress.config.ts",
        "testingType": "component",
        "skipServe": true,
        "devServerTarget": "angular-sandbox:build" // here the point
      }
    }`

I closed my issue.

**Comment by barbados-clemens** [comment]
good to know @GaetanRdn I'm updating the docs with more examples in #12629 I'll make sure to mention that for others. 👍

**Comment by GaetanRdn** [comment]
> good to know @GaetanRdn I'm updating the docs with more examples in #12629 I'll make sure to mention that for others. 👍

Thanks @barbados-clemens :-)
