### ISSUE TITLE
nx lint is broken: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

### ISSUE THREAD

**Issue by goldylucks** [nrwl/nx#12649]
## Current Behavior

trying to lint any project yields the above error locally, however the linting works on the CI (circle).

What I tried:

1. deleting yarn.lock and node_modules and yarn install
2. cloning the repo, yarn install, and linting

## Expected Behavior

should just work

## Steps to Reproduce

I don't know how to reproduce this.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
$ npx nx lint --verbose

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target lint for project main-site


   See Nx Cloud run details at https://nx.app/runs/YfTebvyV7A


 >  NX   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined


TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at HashingImpl.hashArray (/Users/Goldy/breathe/code/node_modules/nx/src/hasher/hashing-impl.js:10:20)
    at Hasher.hashArray (/Users/Goldy/breathe/code/node_modules/nx/src/hasher/hasher.js:113:29)
    at /Users/Goldy/breathe/code/node_modules/@nrwl/linter/src/executors/eslint/hasher.js:23:35
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Goldy/breathe/code/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
### Environment

```
Node : 17.6.0
   OS   : darwin arm64
   yarn : 1.22.18

   nx : 14.4.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.4.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.4.3
   @nrwl/expo : Not Found
   @nrwl/express : 14.4.3
   @nrwl/jest : 14.4.3
   @nrwl/js : 14.4.3
   @nrwl/linter : 14.4.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.4.3
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.4.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.3
   @nrwl/web : 14.4.3
   @nrwl/webpack : Not Found
   @nrwl/workspace : 14.4.3
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by goldylucks** [comment]
so I have no idea why, but running this solved it:

```
$ yarn add --dev @typescript-eslint/parser @typescript-eslint/eslint-plugin
```
