### ISSUE TITLE
Failed to resolve module when importing a library from another library

### ISSUE THREAD

**Issue by SonMooSans** [nrwl/nx#12652]
## Current Behavior

Gets `error TS2307: Cannot find module '@my-workspace/utils' or its corresponding type declarations.` when run or build the app
However, it has no errors caused in vs code

## Expected Behavior

Run and Build the app successfully

## Steps to Reproduce
Create a new NX Project with vite app `web`
Generate library: `api` and `utils` with `nx generate`
`api` Import functions from `utils` library
Build the app using  `npm run build`
It's not a minimal repo, I need some time to tidy up things: [Original Github Repo](https://github.com/SonMooSans/omagize/tree/debug)

### Failure Logs
```
Failed to resolve import "@omagize/utils" from "..\..\libs\api\src\query\group.ts". Does the file exist?
[vite] Internal server error: Failed to resolve import "@omagize/utils" from "..\..\libs\api\src\query\group.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/Deve/2022/omagize/libs/api/src/query/group.ts
  1  |  import { replaceMatch } from "@omagize/utils";
     |                                ^
  2  |  import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
  3  |  import {
      at formatError (file:///D:/Deve/2022/omagize/node_modules/.pnpm/vite@3.1.7/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:40862:46)
      at TransformContext.error (file:///D:/Deve/2022/omagize/node_modules/.pnpm/vite@3.1.7/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:40858:19)
      at normalizeUrl (file:///D:/Deve/2022/omagize/node_modules/.pnpm/vite@3.1.7/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:37595:33)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (file:///D:/Deve/2022/omagize/node_modules/.pnpm/vite@3.1.7/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:37728:47)
      at async Object.transform (file:///D:/Deve/2022/omagize/node_modules/.pnpm/vite@3.1.7/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:41111:30)
      at async loadAndTransform (file:///D:/Deve/2022/omagize/node_modules/.pnpm/vite@3.1.7/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:37373:29)
```

### Environment
```
Node : 16.6.2
OS   : win32 x64
pnpm : 7.13.4

nx : 14.8.3
@nrwl/angular : Not Found
@nrwl/cypress : 14.8.3
@nrwl/detox : Not Found
@nrwl/devkit : 14.8.3
@nrwl/esbuild : Not Found
@nrwl/eslint-plugin-nx : 14.8.3
@nrwl/expo : Not Found
@nrwl/express : Not Found
@nrwl/jest : 14.8.3
@nrwl/js : 14.8.3
@nrwl/linter : 14.8.3
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : 14.7.0
@nrwl/nx-plugin : Not Found
@nrwl/react : 14.8.3
@nrwl/react-native : Not Found
@nrwl/rollup : 14.8.3
@nrwl/schematics : Not Found
@nrwl/storybook : 14.8.3
@nrwl/web : 14.8.3
@nrwl/webpack : 14.8.3
@nrwl/workspace : 14.8.3
typescript : 4.8.4
---------------------------------------
Local workspace plugins:
---------------------------------------
Community plugins:
```

**Comment by AgentEnder** [comment]
It looks like this issue probably needs to be opened on the repo for vite-tsconfig-paths, I'm going to close it out since its not on Nx's side of things. There may be a misconfiguration, but they would be better suited to help find it.
