### ISSUE TITLE
'nx generate @nrwl/angular:component' failed after update to nx@15.0.0

### ISSUE THREAD

**Issue by vorant** [nrwl/nx#12712]
## Current Behavior
command like 
`nx generate @nrwl/angular:component --path=libs/users/api/src/lib --project=users-api --name=test --type=component --skip-import --no-interactive --dry-run` works fine for nx@13.9.7 but failed for nx@15.0.0

## Expected Behavior
The command creates a component

## Steps to Reproduce
just run the command

### Failure Logs

```
InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"path":"libs/users/api/src/lib","project":"users-api","name":"test","viewEncapsulation":"Emulated","changeDetection":"Default","style":"css","type":"component","displayBlock":false,"inlineStyle":false,"inlineTemplate":false,"standalone":false,"skipTests":false,"flat":false,"skipImport":false,"skipSelector":false,"export":false}
Errors:

  Data path "" must NOT have additional properties(standalone).
    at MapSubscriber.project (./node_modules/@angular-devkit/schematics/tools/schema-option-transform.js:30:27)
    at MapSubscriber._next (./node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (./node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (./node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (./node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (./node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (./node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (./node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (./node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:143:22)
    at ThrowIfEmptySubscriber._next (./node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26) {
  errors: [
    {
      instancePath: '',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: [Object],
      message: 'must NOT have additional properties'
    }
  ]
}

 >  NX   Schematic input does not validate against the Schema: {"path":"libs/users/api/src/lib","project":"users-api","name":"test","viewEncapsulation":"Emulated","changeDetection":"Default","style":"css","type":"component","displayBlock":false,"inlineStyle":false,"inlineTemplate":false,"standalone":false,"skipTests":false,"flat":false,"skipImport":false,"skipSelector":false,"export":false}

   Errors:
   
     Data path "" must NOT have additional properties(standalone).
   Pass --verbose to see the stacktrace.


```
### Environment
<details>
  <summary>`nx report`</summary>

  ```
  Node : 14.20.1
   OS   : linux x64
   npm  : 6.14.17
   
   nx : 15.0.0
   @nrwl/angular : 15.0.0
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ng-bootstrap/ng-bootstrap: 10.0.0
         @ngneat/transloco: 2.23.5
         @ngrx/component: 14.3.2
         @ngrx/component-store: 14.3.2
         @ngrx/effects: 14.3.2
         @ngrx/entity: 14.3.2
         @ngrx/router-store: 14.3.2
         @ngrx/store: 14.3.2
         rxjs: 6.5.5
         @ngrx/schematics: 14.3.2
         @ngrx/store-devtools: 14.3.2
         @storybook/angular: 6.5.12
         ngx-build-plus: 13.0.1

  ```
</details>

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you provide a repo where this issue can be reproduced? With the information provided, I could not reproduce it, and without a reproduction, we won't be able to troubleshoot it.

Without seeing the reproduction what I could guess you can check is to ensure the `@schematics/angular` package version that's resolved in the `node_modules` root. You should have it with the same major version as your Angular packages `14.x.x.`.

**Comment by vorant** [comment]
not relevant
