### ISSUE TITLE
Can't generaet a new expo app using nx generate 

### ISSUE THREAD

**Issue by bogris** [nrwl/nx#12722]
## Current Behavior
When i try to create a new app I get the error below:

nx g @nrwl/expo:app expo-mvp --verbose

>  NX  Generating @nrwl/expo:application

 >  NX   Invalid Version: null

TypeError: Invalid Version: null
    at new SemVer (/Users/sorin/code/foodfix/foodFixMega/node_modules/@nrwl/devkit/node_modules/semver/classes/semver.js:19:13)
    at compare (/Users/sorin/code/foodfix/foodFixMega/node_modules/@nrwl/devkit/node_modules/semver/functions/compare.js:3:3)
    at gt (/Users/sorin/code/foodfix/foodFixMega/node_modules/@nrwl/devkit/node_modules/semver/functions/gt.js:2:29)
    at /Users/sorin/code/foodfix/foodFixMega/node_modules/@nrwl/devkit/src/utils/package-json.js:37:32
    at Array.filter (<anonymous>)
    at updateExistingDependenciesVersion (/Users/sorin/code/foodfix/foodFixMega/node_modules/@nrwl/devkit/src/utils/package-json.js:23:10)
    at addDependenciesToPackageJson (/Users/sorin/code/foodfix/foodFixMega/node_modules/@nrwl/devkit/src/utils/package-json.js:60:83)
    at updateDependencies (/Users/sorin/code/foodfix/foodFixMega/node_modules/@nrwl/expo/src/generators/init/init.js:34:54)
    at /Users/sorin/code/foodfix/foodFixMega/node_modules/@nrwl/expo/src/generators/init/init.js:17:46
    at Generator.next (<anonymous>)

## Expected Behavior
Expected: greate the new app

It works on previous versions: yarn add @nrwl/expo@14.8.6 

## Steps to Reproduce

yarn add @nrwl/expo
nx g @nrwl/expo:app expo-mvp --verbose

I will mention that prior to this I had nx 14.6 in the repo and a single next app. 
I also upgraded all an packages to 15.0.0 and I get the same behaiviour. 

### Environment
I am running this on macos 12.5 with M1 pro chip. 
==========
node -v                               
v16.17.0
yarn -v
1.22.15
==========
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin arm64
   yarn : 1.22.15
   
   nx : 15.0.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.0
   @nrwl/detox : 15.0.0
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : 15.0.0
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : 15.0.0
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.0
   @nrwl/react-native : 15.0.0
   @nrwl/rollup : 15.0.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : 15.0.0
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by xiongemi** [comment]
do you have a repo that i could replicate this issue?

**Comment by xiongemi** [comment]
did you run `nx migrate latest` after you upgrade the @nrwl/expo version?

**Comment by xiongemi** [comment]
closing this issue since i could not replicate it locally
