### ISSUE TITLE
nx test - ReferenceError: fetch is not defined - from running the trainings

### ISSUE THREAD

**Issue by freuthli-qc** [nrwl/nx#12726]
Hey, 
we are having a first look into NX using the online training materials from https://nxplaybook.com/ - we btw found that the course seems a bit outdated, the latest NX versions sometimes start to behave differently than described in the course, maybe a slight update on the course would also help, just cannot put that comment in there, since the nxplaybook website doesn't provide feedback and collab tools.

The issue we encountered is when running commands as presented in the 4th video "Add a server API".

## Current Behavior
Running "nx test", like presented in the video for running the test after doing a code change to the API URL, does yield a test error. All code and changes were done using NX like presented in the video lectures.

## Expected Behavior
"nx test" should be running even without the change to the API_URL variable, but it doesn't. Seems to us that there might be an issue in the NX tooling that we used for the setup, as described in the videos.

## Steps to Reproduce
Follow the lecture videos and run commands, make code changes just as suggested in the lectures.

### Failure Logs
felix.reuthlinger@DE01-OF-LV8947:~/datatypemob$ nx test

> nx run data-hive:test

  console.error
    Error: Uncaught [ReferenceError: fetch is not defined]
        at reportException (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at innerInvokeEventListeners (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:343:9)
        at invokeEventListeners (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
        at HTMLUnknownElementImpl._dispatch (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
        at Object.invokeGuardedCallbackDev (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
        at invokeGuardedCallback (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
        at reportUncaughtErrorInDEV (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:22838:5)
        at captureCommitPhaseError (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:27126:5) {
      detail: ReferenceError: fetch is not defined
          at /home/local/CORP/felix.reuthlinger/datatypemob/apps/data-hive/src/app/app.tsx:16:5
          at commitHookEffectListMount (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:23150:26)
          at commitPassiveMountOnFiber (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:24931:11)
          at commitPassiveMountEffects_complete (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:24891:9)
          at commitPassiveMountEffects_begin (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:24878:7)
          at commitPassiveMountEffects (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:24866:3)
          at flushPassiveEffectsImpl (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:27039:3)
          at flushPassiveEffects (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:26984:14)
          at /home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:26769:9
          at flushActQueue (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react/cjs/react.development.js:2667:24)
          at act (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react/cjs/react.development.js:2582:11)
          at /home/local/CORP/felix.reuthlinger/datatypemob/node_modules/@testing-library/react/dist/act-compat.js:63:25
          at renderRoot (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/@testing-library/react/dist/pure.js:159:26)
          at render (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/@testing-library/react/dist/pure.js:246:10)
          at Object.<anonymous> (/home/local/CORP/felix.reuthlinger/datatypemob/apps/data-hive/src/app/app.spec.tsx:9:35)
          at Promise.then.completed (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/utils.js:333:28)
          at new Promise (<anonymous>)
          at callAsyncCircusFn (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/utils.js:259:10)
          at _callCircusTest (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/run.js:277:40)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async _runTest (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/run.js:209:3)
          at async _runTestsForDescribeBlock (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/run.js:97:9)
          at async _runTestsForDescribeBlock (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/run.js:91:9)
          at async run (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/run.js:31:3)
          at async runAndTransformResultsToJestFormat (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
          at async jestAdapter (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:92:19)
          at async runTestInternal (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-runner/build/runTest.js:411:16)
          at async runTest (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-runner/build/runTest.js:499:34),
      type: 'unhandled exception'
    }

      at VirtualConsole.<anonymous> (../../node_modules/jest-environment-jsdom/build/index.js:70:23)
      at reportException (../../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:343:9)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
      at HTMLUnknownElementImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)

  console.error
    The above error occurred in the <App> component:
    
        at App (/home/local/CORP/felix.reuthlinger/datatypemob/apps/data-hive/src/app/app.tsx:14:49)
        at Router (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-router/lib/components.tsx:292:13)
        at BrowserRouter (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-router-dom/index.tsx:240:3)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (../../node_modules/react-dom/cjs/react-dom.development.js:18687:23)
      at update.callback (../../node_modules/react-dom/cjs/react-dom.development.js:18720:5)
      at callCallback (../../node_modules/react-dom/cjs/react-dom.development.js:13923:12)
      at commitUpdateQueue (../../node_modules/react-dom/cjs/react-dom.development.js:13944:9)
      at commitLayoutEffectOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:23391:13)
      at commitLayoutMountEffects_complete (../../node_modules/react-dom/cjs/react-dom.development.js:24688:9)
      at commitLayoutEffects_begin (../../node_modules/react-dom/cjs/react-dom.development.js:24674:7)

  console.error
    Error: Uncaught [ReferenceError: fetch is not defined]
        at reportException (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at innerInvokeEventListeners (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:343:9)
        at invokeEventListeners (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
        at HTMLUnknownElementImpl._dispatch (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
        at Object.invokeGuardedCallbackDev (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
        at invokeGuardedCallback (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
        at reportUncaughtErrorInDEV (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:22838:5)
        at captureCommitPhaseError (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:27126:5) {
      detail: ReferenceError: fetch is not defined
          at /home/local/CORP/felix.reuthlinger/datatypemob/apps/data-hive/src/app/app.tsx:16:5
          at commitHookEffectListMount (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:23150:26)
          at commitPassiveMountOnFiber (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:24931:11)
          at commitPassiveMountEffects_complete (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:24891:9)
          at commitPassiveMountEffects_begin (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:24878:7)
          at commitPassiveMountEffects (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:24866:3)
          at flushPassiveEffectsImpl (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:27039:3)
          at flushPassiveEffects (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:26984:14)
          at /home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-dom/cjs/react-dom.development.js:26769:9
          at flushActQueue (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react/cjs/react.development.js:2667:24)
          at act (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react/cjs/react.development.js:2582:11)
          at /home/local/CORP/felix.reuthlinger/datatypemob/node_modules/@testing-library/react/dist/act-compat.js:63:25
          at renderRoot (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/@testing-library/react/dist/pure.js:159:26)
          at render (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/@testing-library/react/dist/pure.js:246:10)
          at Object.<anonymous> (/home/local/CORP/felix.reuthlinger/datatypemob/apps/data-hive/src/app/app.spec.tsx:19:33)
          at Promise.then.completed (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/utils.js:333:28)
          at new Promise (<anonymous>)
          at callAsyncCircusFn (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/utils.js:259:10)
          at _callCircusTest (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/run.js:277:40)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async _runTest (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/run.js:209:3)
          at async _runTestsForDescribeBlock (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/run.js:97:9)
          at async _runTestsForDescribeBlock (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/run.js:91:9)
          at async run (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/run.js:31:3)
          at async runAndTransformResultsToJestFormat (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)
          at async jestAdapter (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:92:19)
          at async runTestInternal (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-runner/build/runTest.js:411:16)
          at async runTest (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/jest-runner/build/runTest.js:499:34),
      type: 'unhandled exception'
    }

      at VirtualConsole.<anonymous> (../../node_modules/jest-environment-jsdom/build/index.js:70:23)
      at reportException (../../node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:343:9)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:276:3)
      at HTMLUnknownElementImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:223:9)

  console.error
    The above error occurred in the <App> component:
    
        at App (/home/local/CORP/felix.reuthlinger/datatypemob/apps/data-hive/src/app/app.tsx:14:49)
        at Router (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-router/lib/components.tsx:292:13)
        at BrowserRouter (/home/local/CORP/felix.reuthlinger/datatypemob/node_modules/react-router-dom/index.tsx:240:3)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (../../node_modules/react-dom/cjs/react-dom.development.js:18687:23)
      at update.callback (../../node_modules/react-dom/cjs/react-dom.development.js:18720:5)
      at callCallback (../../node_modules/react-dom/cjs/react-dom.development.js:13923:12)
      at commitUpdateQueue (../../node_modules/react-dom/cjs/react-dom.development.js:13944:9)
      at commitLayoutEffectOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:23391:13)
      at commitLayoutMountEffects_complete (../../node_modules/react-dom/cjs/react-dom.development.js:24688:9)
      at commitLayoutEffects_begin (../../node_modules/react-dom/cjs/react-dom.development.js:24674:7)

 FAIL   data-hive  apps/data-hive/src/app/app.spec.tsx
  App
    ✕ should render successfully (279 ms)
    ✕ should have a greeting as the title (51 ms)

  ● App › should render successfully

    ReferenceError: fetch is not defined

      14 |   const [apiResponse, setApiResponse] = useState<ApiResponse>({message: 'Loading...'});
      15 |   useEffect(() => {
    > 16 |     fetch(API_URL).then(r => r.json().then(setApiResponse));
         |     ^
      17 |   }, []);
      18 |
      19 |   return (

      at src/app/app.tsx:16:5
      at commitHookEffectListMount (../../node_modules/react-dom/cjs/react-dom.development.js:23150:26)
      at commitPassiveMountOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24931:11)
      at commitPassiveMountEffects_complete (../../node_modules/react-dom/cjs/react-dom.development.js:24891:9)
      at commitPassiveMountEffects_begin (../../node_modules/react-dom/cjs/react-dom.development.js:24878:7)
      at commitPassiveMountEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24866:3)
      at flushPassiveEffectsImpl (../../node_modules/react-dom/cjs/react-dom.development.js:27039:3)
      at flushPassiveEffects (../../node_modules/react-dom/cjs/react-dom.development.js:26984:14)
      at ../../node_modules/react-dom/cjs/react-dom.development.js:26769:9
      at flushActQueue (../../node_modules/react/cjs/react.development.js:2667:24)
      at act (../../node_modules/react/cjs/react.development.js:2582:11)
      at ../../node_modules/@testing-library/react/dist/act-compat.js:63:25
      at renderRoot (../../node_modules/@testing-library/react/dist/pure.js:159:26)
      at render (../../node_modules/@testing-library/react/dist/pure.js:246:10)
      at Object.<anonymous> (src/app/app.spec.tsx:9:35)

  ● App › should have a greeting as the title

    ReferenceError: fetch is not defined

      14 |   const [apiResponse, setApiResponse] = useState<ApiResponse>({message: 'Loading...'});
      15 |   useEffect(() => {
    > 16 |     fetch(API_URL).then(r => r.json().then(setApiResponse));
         |     ^
      17 |   }, []);
      18 |
      19 |   return (

      at src/app/app.tsx:16:5
      at commitHookEffectListMount (../../node_modules/react-dom/cjs/react-dom.development.js:23150:26)
      at commitPassiveMountOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:24931:11)
      at commitPassiveMountEffects_complete (../../node_modules/react-dom/cjs/react-dom.development.js:24891:9)
      at commitPassiveMountEffects_begin (../../node_modules/react-dom/cjs/react-dom.development.js:24878:7)
      at commitPassiveMountEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24866:3)
      at flushPassiveEffectsImpl (../../node_modules/react-dom/cjs/react-dom.development.js:27039:3)
      at flushPassiveEffects (../../node_modules/react-dom/cjs/react-dom.development.js:26984:14)
      at ../../node_modules/react-dom/cjs/react-dom.development.js:26769:9
      at flushActQueue (../../node_modules/react/cjs/react.development.js:2667:24)
      at act (../../node_modules/react/cjs/react.development.js:2582:11)
      at ../../node_modules/@testing-library/react/dist/act-compat.js:63:25
      at renderRoot (../../node_modules/@testing-library/react/dist/pure.js:159:26)
      at render (../../node_modules/@testing-library/react/dist/pure.js:246:10)
      at Object.<anonymous> (src/app/app.spec.tsx:19:33)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        2.879 s
Ran all test suites.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project data-hive (6s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
felix.reuthlinger@DE01-OF-LV8947:~/datatypemob$ 

### Environment
 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : linux x64
   npm  : 8.19.2
   
   nx : 14.8.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.4
   @nrwl/expo : Not Found
   @nrwl/express : 14.8.4
   @nrwl/jest : 14.8.4
   @nrwl/js : 14.8.4
   @nrwl/linter : 14.8.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.8.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.4
   @nrwl/web : 14.8.4
   @nrwl/webpack : 14.8.4
   @nrwl/workspace : 14.8.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by barbados-clemens** [comment]
An easy way out is to try using node v18 where fetch is implementing node js.
another way is just to fake fetch for your tests by patching `global.fetch` or using node-fetch if you can't upgrade to nodejs v18 and need a fetch implemetation

make a test-setup.ts file in your project root
that looks something like 
```ts
// this is the test-setup.ts file
import fetch from 'node-fetch';

if (!global?.fetch) {
  // @ts-ignore
  global.fetch = jest.fn();
// or if you need the fetch implementation use node-fetch or something
  global.fetch = fetch;
}
```

then you can tell jest to run this file as apart of the setup with `setupFilesAfterEnv: ['<rootDir>/test-setup.ts'],` property in the jest.config.ts

Let me know if you run into any issues. happy to help :)

**Comment by barbados-clemens** [comment]
Also would you mind sharing the repo you were using so I can take a look? might just be a setting in the jest config/preset that got changed/wasn't accounted for.

**Comment by freuthli-qc** [comment]
> Also would you mind sharing the repo you were using so I can take a look? might just be a setting in the jest config/preset that got changed/wasn't accounted for.

I cannot share the repo, sorry. But anyways the steps that were used to set up the repo were the exact same as used in the video lectures of the NX training course hosted by NX. The point about this is that following the training materials wouldn't yield a working code setup.

**Comment by barbados-clemens** [comment]
I'll need a cloneable repo to test this out as i can't reproduce it on the latest version of Nx.

**Comment by jordanbertasso** [comment]
I'm also experiencing this issue

**Comment by jordanbertasso** [comment]
This issue is still valid

**Comment by jordanbertasso** [comment]
This issue is still valid

**Comment by barbados-clemens** [comment]
Hi there, finally was able to look into this and this is because when using the 'jsdom' testing environment (default for Nx workspaces) fetch is not avaiable even if using node v18+

See this comment. 
https://github.com/facebook/jest/issues/13834#issuecomment-1407375787

You can extend the testing environment with your own to implement fetch if you so wish.
[Example](https://github.com/jsdom/jsdom/issues/1724#issuecomment-1446858041)

You can also mock fetch with a jest mock or node-fetch.

I would caution using real fetch within unit testing as it can slow down testing or be flaky as you're tests are waiting on network connections at that point.

**Comment by jordanbertasso** [comment]
Thanks for looking into it!
