### ISSUE TITLE
nx migrations fail while parsing tsconfig with trailing commas

### ISSUE THREAD

**Issue by 31piy** [nrwl/nx#12736]
## Current Behavior
Whenever any migration tries to read a tsconfig*.json file which contains a trailing comma after property value (example below), the migration fails to read that file and the error message is also not super clear.

**.tsconfig.json**
```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "experimentalDecorators": true,  <-- trailing comma
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}

```

## Expected Behavior
Ideally, the parsing shouldn't fail because TypeScript itself allows trailing commas, comments etc. in these files. But the best we can do is to actually prompt the user that such a file is not accepted by nx.

### Failure Logs
```
Error: Cannot parse any-app/tsconfig.json: PropertyNameExpected in JSON at position 104
    at readJson (my-app/node_modules/nx/src/generators/utils/json.js:20:15)
    at my-app/node_modules/@nrwl/jest/src/migrations/update-14-0-0/update-jest-config-ext.js:80:60
    at forEachExecutorOptions (my-app/node_modules/@nrwl/workspace/src/utilities/executor-options-utils.js:23:17)
    at my-app/node_modules/@nrwl/jest/src/migrations/update-14-0-0/update-jest-config-ext.js:67:61
    at Generator.next (<anonymous>)
    at my-app/node_modules/@nrwl/jest/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (my-app/node_modules/@nrwl/jest/node_modules/tslib/tslib.js:114:16)
    at updateJestConfigExt (my-app/node_modules/@nrwl/jest/src/migrations/update-14-0-0/update-jest-config-ext.js:62:20)
    at /private/var/folders/01/5d34fqpj4f9c52snlv0qyfcm0000gp/T/tmp-53635-GHGS15MyJS8H/node_modules/nx/src/command-line/migrate.js:758:15
Command failed: /var/folders/01/5d34fqpj4f9c52snlv0qyfcm0000gp/T/tmp-53635-GHGS15MyJS8H/node_modules/.bin/nx _migrate --run-migrations --verbose
```

### Environment

```
   Node : 18.10.0
   OS   : darwin x64
   npm  : 8.19.2

   nx : 14.8.6
   @nrwl/angular : 14.8.6
   @nrwl/cypress : 14.8.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.6
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.6
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.6
   @nrwl/js : 14.8.6
   @nrwl/linter : 14.8.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.6
   @nrwl/web : Not Found
   @nrwl/webpack : 14.8.6
   @nrwl/workspace : 14.8.6
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 rxjs: 6.6.7
   	 single-spa-angular: 6.3.1
   	 @ngneat/spectator: 10.0.1
   	 @storybook/angular: 6.5.11
   	 ngx-build-plus: 13.0.1
   	 nx-stylelint: 12.2.0
```

**Comment by 31piy** [comment]
I found a discussion around this case here - https://github.com/nrwl/nx/discussions/6711. Please feel free to close in case this is already on the list.

**Comment by JoA-MoS** [comment]
@31piy generally trailing commas are not supported in JSON

> As JSON is based on a very restricted subset of JavaScript syntax, trailing commas are not allowed in JSON.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#trailing_commas_in_json

**Comment by 31piy** [comment]
@JoA-MoS I understand, but TypeScript parsed it perfectly. My concern here is more about reporting the error correctly rather than failing the migration abruptly with a cryptic message.

We could perhaps be better by saying "The migration blah failed to run because the file path/to/file.tsconfig.json is not a valid JSON".
