### ISSUE TITLE
Unable to generate a react application using `@nrwl/react` generator

### ISSUE THREAD

**Issue by usamazansari** [nrwl/nx#12841]
## `@nrwl/react` generator is unable to generate a new react application in the monorepo
After upgrade to `nx@15.0.3`, the `@nrwl/react` generator fails to generate the react application in the workspace

## The react app should be generated

It is a regression - this phenomenon worked in `<15.0.0.`

## Steps to Reproduce

```
yarn nx generate @nrwl/react:application admin --style=scss --directory=frontend --routing --standaloneConfig --no-interactive --verbose
yarn run v1.22.19
$ ~/home/nx-workspace/node_modules/.bin/nx generate @nrwl/react:application admin --style=scss --directory=frontend --routing --standaloneConfig --no-interactive --verbose

>  NX  Generating @nrwl/react:application

 >  NX   Keyword [object Object] is not a valid identifier

Error: Keyword [object Object] is not a valid identifier
    at Ajv.addKeyword (~/home/nx-workspace/node_modules/schema-utils/node_modules/ajv/lib/keyword.js:30:11)
    at instanceofPlugin (~/home/nx-workspace/node_modules/schema-utils/node_modules/ajv-keywords/dist/keywords/instanceof.js:7:39)
    at ajvKeywords (~/home/nx-workspace/node_modules/schema-utils/node_modules/ajv-keywords/dist/index.js:10:19)
    at Object.<anonymous> (~/home/nx-workspace/node_modules/schema-utils/dist/validate.js:65:1)
    at Module._compile (~/home/nx-workspace/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (~/home/nx-workspace/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
error Command failed with exit code 1.
```

### Failure Logs

_Included in Steps to Reproduce_

### Environment

```
yarn nx report
yarn run v1.22.19
$ ~/home/nx-workspace/node_modules/.bin/nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.12.0
   OS   : win32 x64
   npm  : 8.19.2

   nx : 15.0.3
   @nrwl/angular : 15.0.3
   @nrwl/cypress : 15.0.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.3
   @nrwl/js : 15.0.3
   @nrwl/linter : 15.0.3
   @nrwl/nest : 15.0.3
   @nrwl/next : Not Found
   @nrwl/node : 15.0.3
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.3
   @nrwl/web : 15.0.3
   @nrwl/webpack : 15.0.3
   @nrwl/workspace : 15.0.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

Done in 2.02s.
```

**Comment by FrozenPandaz** [comment]
I'm not able to reproduce this issue. The command runs and generates an application for me.

Can you please provide a repo where we can reproduce the issue?
