### ISSUE TITLE
@nrwl/next v15.0.4 withNx cannot add libs path into webpack loaders

### ISSUE THREAD

**Issue by abel1105** [nrwl/nx#12912]
## Current Behavior
When install `@nrwl/next` v15.0.4 with next `v13.0.1`, running the serve command will crash with the following error

I think the root cause is next v13.0.1 removed the `issuer` from the `webpack` config. ([Next.js PR](https://github.com/vercel/next.js/pull/42106/files))

## Expected Behavior
It should not throw errors when running serve.

## Steps to Reproduce
```bash
npx create-nx-workspace@latest next-13-demo --preset=next
cd next-13-demo
pnpm install next@latest
pnpm start --verbose
```

### Failure Logs
```
➜  next-13-demo git:(main) ✗ pnpm start --verbose

> next-13-demo@0.0.0 start /Users/abel/www/next-13-demo
> nx serve "--verbose"


> nx run web-app:serve:development


 >  NX   Cannot read properties of undefined (reading 'and')


TypeError: Cannot read properties of undefined (reading 'and')
    at webpack (/Users/abel/www/next-13-demo/node_modules/.pnpm/@nrwl+next@15.0.4_zrbe3cr7yxpdlpk67wjm3wnrme/node_modules/@nrwl/next/plugins/with-nx.js:53:64)
    at config.webpack (/Users/abel/www/next-13-demo/node_modules/.pnpm/@nrwl+next@15.0.4_zrbe3cr7yxpdlpk67wjm3wnrme/node_modules/@nrwl/next/src/utils/config.js:60:163)
    at Object.getBaseWebpackConfig [as default] (/Users/abel/www/next-13-demo/node_modules/.pnpm/next@13.0.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/webpack-config.js:1402:32)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (/Users/abel/www/next-13-demo/node_modules/.pnpm/next@13.0.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async Span.traceAsyncFn (/Users/abel/www/next-13-demo/node_modules/.pnpm/next@13.0.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async HotReloader.start (/Users/abel/www/next-13-demo/node_modules/.pnpm/next@13.0.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/dev/hot-reloader.js:329:30)
    at async DevServer.prepare (/Users/abel/www/next-13-demo/node_modules/.pnpm/next@13.0.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/dev/next-dev-server.js:514:9)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "web-app:serve" failed

   Failed tasks:

   - web-app:serve:development

   Hint: run the command with --verbose for more details.

 ELIFECYCLE  Command failed with exit code 1.
```

### Environment
```

   Node : 18.8.0
   OS   : darwin arm64
   pnpm : 7.11.0
   
   nx : 15.0.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.4
   @nrwl/expo : Not Found
   @nrwl/express : 15.0.4
   @nrwl/jest : 15.0.4
   @nrwl/js : 15.0.4
   @nrwl/linter : 15.0.4
   @nrwl/nest : Not Found
   @nrwl/next : 15.0.4
   @nrwl/node : 15.0.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.4
   @nrwl/web : 15.0.4
   @nrwl/webpack : 15.0.4
   @nrwl/workspace : 15.0.4
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nx-aws-plugin/nx-aws-cache: 1.1.0

```

**Comment by mrlonis** [comment]
Also experiencing this same issue.  `v15.0.6` is affected and is the most recent version as of this comment going live

**Comment by jaysoo** [comment]
Merged this PR https://github.com/nrwl/nx/pull/12973 which will fix this issue.
