### ISSUE TITLE
Just upgraded from @nrwl/angular 13.7.1 to 15.0.4 and now I cannot run any of my projects

### ISSUE THREAD

**Issue by shadow1349** [nrwl/nx#12910]
## Current Behavior
When I try to run my project with `npx nx serve myproject --configuration=development` I get the following error

```
Unexpected error:
Error: Cannot find module '@nrwl/cli/lib/run-cli.js'
Require stack:
- /path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/utils.js
- /path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/forked-process-task-runner.js
- /path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js
- /path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/default-tasks-runner.js
- /path/to/my/project/node_modules/@nrwl/workspace/tasks-runners/default.js
- /path/to/my/project/node_modules/nx/src/tasks-runner/run-command.js
- /path/to/my/project/node_modules/nx/src/command-line/run-one.js
- /path/to/my/project/node_modules/nx/src/command-line/nx-commands.js
- /path/to/my/project/node_modules/nx/bin/init-local.js
- /path/to/my/project/node_modules/nx/bin/nx.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (/path/to/my/project/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
    at getCliPath (/path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:180:25)
    at new ForkedProcessTaskRunner (/path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/forked-process-task-runner.js:18:47)
    at new TaskOrchestrator (/path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:22:40)
    at /path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/default-tasks-runner.js:45:30
    at Generator.next (<anonymous>)
    at /path/to/my/project/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/path/to/my/project/node_modules/tslib/tslib.js:114:16) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/utils.js',
    '/path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/forked-process-task-runner.js',
    '/path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js',
    '/path/to/my/project/node_modules/@nrwl/workspace/src/tasks-runner/default-tasks-runner.js',
    '/path/to/my/project/node_modules/@nrwl/workspace/tasks-runners/default.js',
    '/path/to/my/project/node_modules/nx/src/tasks-runner/run-command.js',
    '/path/to/my/project/node_modules/nx/src/command-line/run-one.js',
    '/path/to/my/project/node_modules/nx/src/command-line/nx-commands.js',
    '/path/to/my/project/node_modules/nx/bin/init-local.js',
    '/path/to/my/project/node_modules/nx/bin/nx.js'
  ]
}
```

## Expected Behavior
I expect to be able to run my project

### Environment

```
   Node : 16.14.2
   OS   : darwin x64
   npm  : 8.6.0
   
   nx : 15.0.4
   @nrwl/angular : 15.0.4
   @nrwl/cypress : 13.7.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.7.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 13.7.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.4
   @nrwl/js : 15.0.4
   @nrwl/linter : 13.7.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.7.1
   @nrwl/nx-cloud : 13.1.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.4
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.4
   @nrwl/workspace : 13.7.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

Here is my current package.json

```json
{
  "name": "my-workspace",
  "version": "0.0.0",
  "license": "UNLICENSED",
  "engines": {
    "node": "16.14.x",
    "npm": "8.6.x"
  },
  "scripts": {
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "postinstall": "ngcc --properties es2020 browser module main"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "14.2.8",
    "@angular/cdk": "14.2.6",
    "@angular/common": "14.2.8",
    "@angular/compiler": "14.2.8",
    "@angular/core": "14.2.8",
    "@angular/elements": "14.2.8",
    "@angular/flex-layout": "^14.0.0-beta.41",
    "@angular/forms": "14.2.8",
    "@angular/material": "14.2.6",
    "@angular/platform-browser": "14.2.8",
    "@angular/platform-browser-dynamic": "14.2.8",
    "@angular/router": "14.2.8",
    "@datadog/browser-core": "^4.15.0",
    "@datadog/browser-logs": "^4.15.0",
    "@datadog/browser-rum": "^4.15.0",
    "@ngxs/devtools-plugin": "^3.7.5",
    "@ngxs/hmr-plugin": "^3.7.5",
    "@ngxs/storage-plugin": "^3.7.5",
    "@ngxs/store": "^3.7.5",
    "@optimizely/optimizely-sdk": "^4.9.2",
    "body-parser": "^1.20.1",
    "cors": "^2.8.5",
    "dayjs": "^1.10.7",
    "express": "^4.18.2",
    "ngx-google-analytics": "^14.0.1",
    "ngx-mask": "^14.2.4",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "14.2.7",
    "@angular-eslint/eslint-plugin": "14.0.4",
    "@angular-eslint/eslint-plugin-template": "14.0.4",
    "@angular-eslint/template-parser": "14.0.4",
    "@angular/cli": "~14.2.0",
    "@angular/compiler-cli": "14.2.8",
    "@angular/language-service": "14.2.8",
    "@faker-js/faker": "^6.0.0-alpha.5",
    "@nrwl/angular": "15.0.4",
    "@nrwl/cli": "15.0.4",
    "@nrwl/cypress": "13.7.1",
    "@nrwl/eslint-plugin-nx": "13.7.1",
    "@nrwl/jest": "15.0.4",
    "@nrwl/linter": "13.7.1",
    "@nrwl/node": "^13.7.1",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/tao": "13.7.1",
    "@nrwl/workspace": "13.7.1",
    "@types/body-parser": "^1.19.2",
    "@types/cors": "^2.8.12",
    "@types/express": "^4.17.14",
    "@types/jest": "28.1.1",
    "@types/node": "18.7.1",
    "@typescript-eslint/eslint-plugin": "~5.10.0",
    "@typescript-eslint/parser": "~5.10.0",
    "concat": "^1.0.3",
    "cypress": "^9.1.0",
    "eslint": "~8.7.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "fs-extra": "^10.0.0",
    "jest": "28.1.1",
    "jest-environment-jsdom": "28.1.1",
    "jest-preset-angular": "12.2.2",
    "prettier": "^2.5.1",
    "ts-jest": "28.0.5",
    "ts-node": "10.9.1",
    "typescript": "4.8.4",
    "webpack": "^5.70.0"
  }
}
```

**Comment by AgentEnder** [comment]
Hey @shadow1349 , it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by shadow1349** [comment]
@AgentEnder huh that seems to have fixed the issue. As a side note, I had run `nx migrate latest` which didn't actually make any changes. I had to ran `nx migrate @nrwl/{package}` individually until I got to @nrwl/workspace which upgraded all of the @nrwl/* dependencies for me. I'm not sure if that's expected behavior or not but figured I'd bring it up. Thanks for that!

**Comment by FrozenPandaz** [comment]
Glad this is resolved now. :+1:
