### ISSUE TITLE
React Jest tests fail to run due to Babel error

### ISSUE THREAD

**Issue by ngoc199** [nrwl/nx#12936]
## Current Behavior
The React Jest tests fail to run with the default config because there is an error with Babel.
```
You gave us a visitor for the node type TSSatisfiesExpression but it's not a valid type
```

## Expected Behavior
The tests should be run successfully with the default config.

## Steps to Reproduce
1. Create a new React app or React library using `@nrwl/react` by running the command `nx g @nrwl/react:app example`
2. Run the test by running the command `nx test example`

You can see the tests fails due to the Babel error.

I am using `@nrwl/react 15.0.5`.

### Failure Logs

    [BABEL] /....../web/src/app/app.spec.tsx: You gave us a visitor for the node type TSSatisfiesExpression but it's not a valid type

      at verify (../../../node_modules/jest-config/node_modules/@babel/traverse/src/visitors.ts:154:13)
      at evaluateSync (../../../node_modules/gensync/index.js:251:28)
      at Function.sync (../../../node_modules/gensync/index.js:89:14)
      at sync (../../../node_modules/gensync/index.js:182:19)
      at onFirstPause (../../../node_modules/gensync/index.js:210:24)
          at cachedFunction.next (<anonymous>)
          at loadPluginDescriptor.next (<anonymous>)
          at loadPluginDescriptors.next (<anonymous>)
          at loadFullConfig.next (<anonymous>)
          at transform.next (<anonymous>)
      at evaluateSync (../../../node_modules/gensync/index.js:251:28)
      at fn (../../../node_modules/gensync/index.js:89:14)
      at ScriptTransformer.transformSource (../../../node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (../../../node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (../../../node_modules/@jest/transform/build/ScriptTransformer.js:822:19)

### Environment

   Node : 16.15.0
   OS   : linux x64
   yarn : 1.22.19
   
   nx : 14.8.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.5
   @nrwl/expo : Not Found
   @nrwl/express : 15.0.0
   @nrwl/jest : 15.0.5
   @nrwl/js : 15.0.5
   @nrwl/linter : 15.0.5
   @nrwl/nest : 15.0.0
   @nrwl/next : Not Found
   @nrwl/node : 15.0.0
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.5
   @nrwl/web : 15.0.5
   @nrwl/webpack : 15.0.5
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by ngoc199** [comment]
I have tried to create a new workspace and it works just fine. So somehow the error is caused by me, which I don't know yet.

Since this is not the Nx issue, I closed this.
