### ISSUE TITLE
`ng serve api` fail with @nrwl/nest 8.0.0-alpha.4

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#1294]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
`ng serve api` should work 

## Current Behavior

 getting following error. 
may be  `@nrwl/node` is missing   dependency on `@nrwl/web` ?
https://github.com/nrwl/nx/blob/master/packages/node/src/builders/build/build.builder.ts#L17

## Failure Information (for bugs)

```
Cannot find module '../../../../web/src/utils/normalize'
Error: Cannot find module '../../../../web/src/utils/normalize'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Developer/Work/SPA/xxx/ngx-starter-kit/node_modules/@nrwl/node/src/builders/build/build.builder.js:21:19)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Architect.getBuilder (/Developer/Work/SPA/xxx/ngx-starter-kit/node_modules/@angular-devkit/architect/src/architect-legacy.js:210:35)
    at MapSubscriber.getBuilderDescription.pipe.operators_1.map [as project] (/Developer/Work/SPA/xxx/ngx-starter-kit/node_modules/@angular-devkit/architect/src/architect-legacy.js:142:332)
    at MapSubscriber._next (/Developer/Work/SPA/xxx/ngx-starter-kit/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Developer/Work/SPA/xxx/ngx-starter-kit/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:67:18)
    at TapSubscriber._next (/Developer/Work/SPA/xxx/ngx-starter-kit/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/tap.js:65:26)
```
Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. ...

### Context

Please provide any relevant information about your setup:

- version of Nx used
```
    "@nrwl/angular": "^8.0.0-alpha.4",
    "@nrwl/cypress": "8.0.0-alpha.4",
    "@nrwl/jest": "8.0.0-alpha.4",
    "@nrwl/nest": "^8.0.0-alpha.4",
    "@nrwl/node": "^8.0.0-alpha.4",
```
- version of Angular CLI used
```
Angular CLI: 7.3.8
Node: 11.14.0
OS: darwin x64
Angular: 8.0.0-beta.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/json-schema              1.1.0
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
ng-packagr                        5.1.0
rxjs                              6.5.1
typescript                        3.4.5
webpack                           4.29.0
```
- `angular.json` configuration
- version of Angular DevKit used
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by xmlking** [comment]
after `yarn add @nrwl/web -D` , this works. 
would be nice we can decouple dependency on    `@nrwl/web` for `@nrwl/node`

**Comment by FrozenPandaz** [comment]
Fixed with https://github.com/nrwl/nx/commit/a3be21ca78b67a0fb8e462dc41b2c166446bbdba

`@nrwl/node` will not depend on `@nrwl/web` :)
