### ISSUE TITLE
symlink issue during next js build (@nrwl/next@15.0.12)

### ISSUE THREAD

**Issue by perscrew** [nrwl/nx#13065]
Hello, I have an issue regarding my Next JS 13 build. 
I have a specific symlink in my public folder, for some fonts coming from my library.

When I run `nx build <my_app>`, I have the following issue : 

```
>  NX   Cannot copy '../../../libs/proweb-design-system/src/lib/themes/fonts' to a subdirectory of itself, '../../../libs/proweb-design-system/src/lib/themes/fonts'.


Error: Cannot copy '../../../libs/proweb-design-system/src/lib/themes/fonts' to a subdirectory of itself, '../../../libs/proweb-design-system/src/lib/themes/fonts'.
    at onLink (/Users/tibtib/Dev/front-core-nx/node_modules/fs-extra/lib/copy/copy-sync.js:151:13)
    at getStats (/Users/tibtib/Dev/front-core-nx/node_modules/fs-extra/lib/copy/copy-sync.js:52:45)
    at startCopy (/Users/tibtib/Dev/front-core-nx/node_modules/fs-extra/lib/copy/copy-sync.js:41:10)
    at copyDirItem (/Users/tibtib/Dev/front-core-nx/node_modules/fs-extra/lib/copy/copy-sync.js:125:10)
    at /Users/tibtib/Dev/front-core-nx/node_modules/fs-extra/lib/copy/copy-sync.js:118:39
    at Array.forEach (<anonymous>)
    at copyDir (/Users/tibtib/Dev/front-core-nx/node_modules/fs-extra/lib/copy/copy-sync.js:118:23)
    at onDir (/Users/tibtib/Dev/front-core-nx/node_modules/fs-extra/lib/copy/copy-sync.js:108:10)
    at getStats (/Users/tibtib/Dev/front-core-nx/node_modules/fs-extra/lib/copy/copy-sync.js:48:37)
    at handleFilterAndCopy (/Users/tibtib/Dev/front-core-nx/node_modules/fs-extra/lib/copy/copy-sync.js:36:10)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "phoenix:build" failed
```

The same build was working fine with the nx next executor  14.8.5

## Current Behavior

Build is broken due to a symlink in the public folder

## Expected Behavior

Build should pass

## Steps to Reproduce

Create a symlink in the public folder.

Run `nx build <my-app>`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
 NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin x64
   npm  : 8.19.2
   
   nx : 15.0.12
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.12
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.6
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.12
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.12
   @nrwl/js : 15.0.12
   @nrwl/linter : 15.0.12
   @nrwl/nest : 15.0.12
   @nrwl/next : 15.0.12
   @nrwl/node : 15.0.12
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.12
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.12
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.12
   @nrwl/web : 15.0.12
   @nrwl/webpack : 15.0.12
   @nrwl/workspace : 15.0.12
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.27.1
```

**Comment by quicksilverr** [comment]
@perscrew I think this is an issue, with circular dependencies. I strongly suggest, the nx should make a blog on project boundaries and circular dependencies.
