### ISSUE TITLE
Nx commands are failing in 15.0.12

### ISSUE THREAD

**Issue by dpsthree** [nrwl/nx#13117]
## Current Behavior
Attempting to run any nx command from the global CLI, in a new Nx project, results in the following error:
`TypeError: Cannot read properties of null (reading 'type')`

## Expected Behavior
It should run without error

## Steps to Reproduce
```
npx create-nx-workspace
nx g lib
```

### Failure Logs
```
C:\Users\dpsth\AppData\Roaming\npm\node_modules\nx\node_modules\@nrwl\cli\bin\nx.js:6
if (workspace.type === 'nx') {
              ^

TypeError: Cannot read properties of null (reading 'type')
    at Object.<anonymous> (C:\Users\dpsth\AppData\Roaming\npm\node_modules\nx\node_modules\@nrwl\cli\bin\nx.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\dpsth\AppData\Roaming\npm\node_modules\nx\bin\nx.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

### Environment
nx report fails with the same above error

**Comment by dpsthree** [comment]
Invoking Nx from a package script works fine.

**Comment by AgentEnder** [comment]
You probably need to update your global cli version, can you try uninstalling Nx globally and reinstalling? Alternatively, I recommend leaving it uninstalled and invoking via `npx`. If you wish to keep just `nx` as the command, you can set up an alias such that `nx` = `npx nx`.

Since you are on windows, this post may help: https://stackoverflow.com/questions/20530996/aliases-in-windows-command-prompt
