### ISSUE TITLE
`readTargetOptions` not working on angular workspace with `@nrwl/devkit@v15.1.1`

### ISSUE THREAD

**Issue by dianjuar** [nrwl/nx#13215]
## Current Behavior

On an Angular Workspace, `@nrwl/devkit`'s function, `readTargetOption`, is not working as expected. When it executes launches an error on `@nrwl/devkit@15.1.1`

This video may help to understand the problem.

https://user-images.githubusercontent.com/7026066/202386926-b53aae59-0462-4f98-b41d-565961743f8f.mov

```
TypeError: Cannot read properties of undefined (reading 'data')
    at readTargetOptions (/Users/dianjuar/Documents/programing/ngx-deploy-npm/repo/node_modules/@nrwl/devkit/src/executors/read-target-options.js:13:70)
    at /Users/dianjuar/Documents/programing/ngx-deploy-npm/repo/dist/packages/ngx-deploy-npm/src/executors/deploy/actions.js:17:61
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dianjuar/Documents/programing/ngx-deploy-npm/repo/node_modules/tslib/tslib.js:115:62)
```

## Expected Behavior

To return the target options without errors. It was working without problems on previous `@nrwl/devkit` versions.

## Steps to Reproduce

An angular workspace e2e test failed on a plugin I maintain. It happened when renovate [tried to update to `@nrwl/devkit@15.1.1`](https://github.com/bikecoders/ngx-deploy-npm/pull/419)
https://github.com/bikecoders/ngx-deploy-npm/actions/runs/3481523208/jobs/5823675756

You can create the environment when this problem is by using a plugin's [script](https://github.com/bikecoders/ngx-deploy-npm/blob/main/tools/create-angular-workspace.sh) to create an angular workspace.

1. Clone the [repo](https://github.com/bikecoders/ngx-deploy-npm)
2. Move to the branch `renovate/nrwl-monorepo` where V15.1.1 is
3. Install dependencies
4. Execute `./tools/create-angular-workspace.sh` to create the angular workspace
   - It will create an Angular Workspace under `tmp/angular-workspace`
   - It will create an Angular Library called `angular-lib`
   - Will `yarn link` the plugin into the workspace
   - Will install the plugin
   - Will execute the plugin (here it fails)
5. Watch it fail

Providing a repository with the problem is challenging since I don't want to update the plugin to the affected version.

### Failure Logs

```
TypeError: Cannot read properties of undefined (reading 'data')
    at readTargetOptions (/Users/dianjuar/Documents/programing/ngx-deploy-npm/repo/node_modules/@nrwl/devkit/src/executors/read-target-options.js:13:70)
    at /Users/dianjuar/Documents/programing/ngx-deploy-npm/repo/dist/packages/ngx-deploy-npm/src/executors/deploy/actions.js:17:61
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dianjuar/Documents/programing/ngx-deploy-npm/repo/node_modules/tslib/tslib.js:115:62)
```

This is the CI job failing -> https://github.com/bikecoders/ngx-deploy-npm/actions/runs/3481523208/jobs/5823675756

On my plugin, the problem is on this line -> https://github.com/bikecoders/ngx-deploy-npm/blob/renovate/nrwl-monorepo/packages/ngx-deploy-npm/src/executors/deploy/actions.ts#L29

### Environment

Angular Workspace where it's failing

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.9
Node: 18.4.0 (Unsupported)
Package Manager: yarn 1.22.15 
OS: darwin x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1402.9
@angular-devkit/core         14.2.9
@angular-devkit/schematics   14.2.9
@angular/cli                 14.2.9
@schematics/angular          14.2.9
typescript                   4.8.4
```

---

Puglin's Environment

```
   Node : 18.4.0
   OS   : darwin x64
   yarn : 1.22.15
   
   nx : 15.1.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.1
   @nrwl/js : 15.1.1
   @nrwl/linter : 15.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.1.1
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.1.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         ngx-deploy-npm
   ---------------------------------------
   Community plugins:
         @jscutlery/semver: 2.27.2
```

**Comment by dianjuar** [comment]
`@nrwl/devkit` is good.

I could locate my problem.
Since I'm creating the angular workspace inside my nx workspace, the nx workspace root path was set to the plugin's workspace path instead of the angular workspace path causing the error described.

Navigating through the source code, I noticed is possible to indicate the workspace root path using the environment variable `NX_WORKSPACE_ROOT_PATH`.

I added this to the script that generated the angular workspace:

```bash
export NX_WORKSPACE_ROOT_PATH=`pwd`
```

And it solved the problem
