### ISSUE TITLE
pnpx create-nx-workspace failed

### ISSUE THREAD

**Issue by TicTak21** [nrwl/nx#13260]
### Current Behavior

I can't create new nx workspace using pnpm.

I tried to do the same using `npx` and it works fine.

### Expected Behavior

New workspace with installed packages and without errors.

### Steps to Reproduce

1. `pnpx create-nx-workspace@latest` or `pnpm dlx create-nx-workspace@latest`

### Nx Report

```shell
-
```

### Failure Logs

```shell
pnpx create-nx-workspace@latest
../../Library/pnpm/store/v3/tmp/dlx-878  | Progress: resolved 1, reused 0, downloaded 0, a../../Library/pnpm/store/v3/tmp/dlx-878  | Progress: resolved 6, reused 3, downloaded 0, a../../Library/pnpm/store/v3/tmp/dlx-878  | Progress: resolved 10, reused 9, downloaded 0, ../../Library/pnpm/store/v3/tmp/dlx-878  | Progress: resolved 38, reused 32, downloaded 0,../../Library/pnpm/store/v3/tmp/dlx-878  | Progress: resolved 66, reused 66, downloaded 0,../../Library/pnpm/store/v3/tmp/dlx-878  |  +67 +++++++
../../Library/pnpm/store/v3/tmp/dlx-878  | Progress: resolved 66, reused 66, downloaded 0,../../Library/pnpm/store/v3/tmp/dlx-878  | Progress: resolved 67, reused 67, downloaded 0,../../Library/pnpm/store/v3/tmp/dlx-878  | Progress: resolved 67, reused 67, downloaded 0, added 67, done

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Choose your style                     · integrated
✔ What to create in the new workspace   · angular
✔ Repository name                       · test
✔ Application name                      · test
✔ Default stylesheet format             · scss
✔ Enable distributed caching to make your CI faster · No

 >  NX   Nx is creating your v15.2.0 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✖ Creating your workspace in test

 >  NX   Nx failed to create a workspace.

   Exit code: 1
   Log file: /var/folders/wy/slmqdxgs7h91gw7m4d1f52w00000gn/T/tmp-884-Hfg08l1wbaCf/error.log

 ERROR  Command failed with exit code 1: /Users/Library/pnpm/store/v3/tmp/dlx-878/node_modules/.bin/create-nx-workspace

pnpm: Command failed with exit code 1: /Users/Library/pnpm/store/v3/tmp/dlx-878/node_modules/.bin/create-nx-workspace
    at makeError (/Users/Library/pnpm/global/5/.pnpm/pnpm@7.15.0/node_modules/pnpm/dist/pnpm.cjs:22415:17)
    at handlePromise (/Users/Library/pnpm/global/5/.pnpm/pnpm@7.15.0/node_modules/pnpm/dist/pnpm.cjs:22986:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/Users/Library/pnpm/global/5/.pnpm/pnpm@7.15.0/node_modules/pnpm/dist/pnpm.cjs:193613:7)
    at async /Users/Library/pnpm/global/5/.pnpm/pnpm@7.15.0/node_modules/pnpm/dist/pnpm.cjs:200906:21
    at async main (/Users/Library/pnpm/global/5/.pnpm/pnpm@7.15.0/node_modules/pnpm/dist/pnpm.cjs:200877:34)
    at async runPnpm (/Users/Library/pnpm/global/5/.pnpm/pnpm@7.15.0/node_modules/pnpm/dist/pnpm.cjs:201101:5)
    at async /Users/Library/pnpm/global/5/.pnpm/pnpm@7.15.0/node_modules/pnpm/dist/pnpm.cjs:201093:7
```

### Additional Information

pnpm version: 7.15.0

pnpm log

`/var/folders/wy/slmqdxgs7h91gw7m4d1f52w00000gn/T/tmp-884-Hfg08l1wbaCf/error.log`

```Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 5, reused 5, downloaded 0, added 0
Progress: resolved 84, reused 77, downloaded 0, added 0
Progress: resolved 157, reused 153, downloaded 0, added 0
Progress: resolved 243, reused 242, downloaded 0, added 0
Progress: resolved 381, reused 381, downloaded 0, added 0
Progress: resolved 504, reused 482, downloaded 0, added 0
 WARN  deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
Progress: resolved 636, reused 634, downloaded 0, added 0
Progress: resolved 748, reused 748, downloaded 0, added 0
Progress: resolved 832, reused 832, downloaded 0, added 0
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
Progress: resolved 841, reused 841, downloaded 0, added 0
Packages: +848
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 842, reused 842, downloaded 0, added 18
Progress: resolved 842, reused 842, downloaded 0, added 255
 ENOENT  ENOENT: no such file or directory, copyfile '/Users/Library/pnpm/store/v3/files/da/af5f6b3e8bb6d2fad1d9997db4a8c611169b0291e6286ad6c459ca5d6258610999205a668353449a44e6316ac6fc117163d2ee7f75faccc316a28417eb5fa6-exec' -> '/Users/.../test/node_modules/.pnpm/@parcel+watcher@2.0.4/node_modules/@parcel/_tmp_2082_1412c7a5b726bf3964005b0098f2e3d8/node_modules/.bin/node-gyp-build-optional'

pnpm: ENOENT: no such file or directory, copyfile '/Users/Library/pnpm/store/v3/files/da/af5f6b3e8bb6d2fad1d9997db4a8c611169b0291e6286ad6c459ca5d6258610999205a668353449a44e6316ac6fc117163d2ee7f75faccc316a28417eb5fa6-exec' -> '/Users/.../test/node_modules/.pnpm/@parcel+watcher@2.0.4/node_modules/@parcel/_tmp_2082_1412c7a5b726bf3964005b0098f2e3d8/node_modules/.bin/node-gyp-build-optional'

 >  NX   Command failed: pnpm install --no-frozen-lockfile

   Pass --verbose to see the stacktrace.```

**Comment by FrozenPandaz** [comment]
Sorry, I'm not able to reproduce this. Is there any more information you can provide to help us reproduce this? Which OS are you on?

**Comment by TicTak21** [comment]
MacOS Catalina.

It might be local issue, but I'm not sure.
I'll try to create a repro.

**Comment by TicTak21** [comment]
Ok. Seems like its pnpm-related [issue](https://github.com/pnpm/pnpm/issues/4711).
