### ISSUE TITLE
running eas-cli not working in @nwrl/expo apps

### ISSUE THREAD

**Issue by lyhourchhen** [nrwl/nx#13278]
### Current Behavior

nx expo not working with eas-cli 

### Expected Behavior

build apps with eas-cli 

### Steps to Reproduce

1.`cd apps/mobile`
2. run `eas build --platform android --profile development --local`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 15.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.1
   @nrwl/detox : 15.2.1
   @nrwl/devkit : 15.2.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.1
   @nrwl/expo : 15.2.1
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.1
   @nrwl/js : 15.2.1
   @nrwl/linter : 15.2.1
   @nrwl/nest : 15.2.1
   @nrwl/next : Not Found
   @nrwl/node : 15.2.1
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.1
   @nrwl/react-native : 15.2.1
   @nrwl/rollup : 15.2.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.1
   @nrwl/web : 15.2.1
   @nrwl/webpack : 15.2.1
   @nrwl/workspace : 15.2.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
`[SETUP_WORKINGDIR] Preparing workingdir /var/folders/1r/mlgkn_x5633dg0hqby5tsmdr0000gn/T/eas-build-local-nodejs/ad51d943-6116-4a85-96f4-add568f15f39
[START_BUILD] Starting build
  "job": {
    "type": "generic",
    "platform": "android",
    "projectRootDirectory": "apps/mobile",
    "projectArchive": {
      "type": "PATH",
      "path": "/var/folders/1r/mlgkn_x5633dg0hqby5tsmdr0000gn/T/eas-cli-nodejs/1f18513e-29fa-4e68-9da7-83558877178a.tar.gz"
    },
    "builderEnvironment": {},
    "cache": {
      "disabled": false,
      "customPaths": [],
      "cacheDefaultPaths": true,
      "clear": false
    },
    "updates": {},
    "developmentClient": true,
    "buildType": "apk",
    "username": "lyhourchhen",
    "experimental": {}
  }
[PREPARE_PROJECT] We detected that you set the NPM_TOKEN environment variable
[PREPARE_PROJECT] .npmrc already exists in your project directory, skipping generation
[PRE_INSTALL_HOOK] Script 'eas-build-pre-install' is present in package.json, running it...
[PRE_INSTALL_HOOK] Usage Error: The nearest package directory (/private/var/folders/1r/mlgkn_x5633dg0hqby5tsmdr0000gn/T/eas-build-local-nodejs/ad51d943-6116-4a85-96f4-add568f15f39/build/apps/mobile) doesn't seem to be part of the project declared in /private/var/folders/1r/mlgkn_x5633dg0hqby5tsmdr0000gn/T/eas-build-local-nodejs/ad51d943-6116-4a85-96f4-add568f15f39/build.
[PRE_INSTALL_HOOK] 
[PRE_INSTALL_HOOK] - If /private/var/folders/1r/mlgkn_x5633dg0hqby5tsmdr0000gn/T/eas-build-local-nodejs/ad51d943-6116-4a85-96f4-add568f15f39/build isn't intended to be a project, remove any yarn.lock and/or package.json file there.
[PRE_INSTALL_HOOK] - If /private/var/folders/1r/mlgkn_x5633dg0hqby5tsmdr0000gn/T/eas-build-local-nodejs/ad51d943-6116-4a85-96f4-add568f15f39/build is intended to be a project, it might be that you forgot to list apps/mobile in its workspace configuration.
[PRE_INSTALL_HOOK] - Finally, if /private/var/folders/1r/mlgkn_x5633dg0hqby5tsmdr0000gn/T/eas-build-local-nodejs/ad51d943-6116-4a85-96f4-add568f15f39/build is fine and you intend apps/mobile to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.
[PRE_INSTALL_HOOK] 
[PRE_INSTALL_HOOK] $ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
[PRE_INSTALL_HOOK] 
Error: yarn exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/@expo/spawn-async/build/spawnAsync.js:41:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
    ...
    at spawnAsync (/Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/@expo/turtle-spawn/dist/index.js:17:47)
    at runHookIfPresent (/Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/@expo/build-tools/dist/utils/hooks.js:33:42)
    at async /Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/@expo/build-tools/dist/utils/project.js:32:9
    at async BuildContext.runBuildPhase (/Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/@expo/build-tools/dist/context.js:69:28)
    at async setup (/Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/@expo/build-tools/dist/utils/project.js:31:5)
    at async buildAsync (/Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/@expo/build-tools/dist/builders/android.js:19:5)
    at async runBuilderWithHooksAsync (/Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/@expo/build-tools/dist/builders/common.js:13:13)
    at async Object.androidBuilder (/Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/@expo/build-tools/dist/builders/android.js:15:12)
    at async buildAndroidAsync (/Users/lyhourchhen/.npm/_npx/4b14fe6d5b97e8bd/node_modules/eas-cli-local-build-plugin/dist/android.js:62:12)

Build failed
Unknown error. See logs for more information.
    Error: npx exited with non-zero code: 1
`
```

**Comment by FrozenPandaz** [comment]
Is there a github repo? I see in the reproduction steps it says to cd into a directory. 

If you can provide a repo that we can clone to reproduce the issue, it will greatly help us identify and fix the issue sooner. :pray:

**Comment by lyhourchhen** [comment]
Yes the problem occurred with Yarn berry, since most of my projects using yarn berry instead of yarn1, npm, pnpm. so i can't run script inside monorepo app. do you have solution with this ? 
This is reproduce repo https://github.com/lyhourchhen/nx-expo-bug-reproduce

**Comment by xiongemi** [comment]
@lyhourchhen the quick way to solve is go to apps/mobile/package.json and delete the line "eas-build-pre-install".
