### ISSUE TITLE
Angular - nx g web-worker fails when tsconfig.worker.json exist

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#13397]
### Current Behavior

First call was fine:

```
oz@Avalon npp-ui % nx g web-worker --project=npp --path=apps/npp/src/app/features/export-jobs                                                            

>  NX  Generating @nrwl/angular:web-worker

✔ What name would you like to use for the worker? · export-jobs-events-checker
[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in angular.json
[NX] Double check angular.json before proceeding
CREATE apps/npp/src/app/features/export-jobs/export-jobs-events-checker.worker.ts
CREATE apps/npp/tsconfig.worker.json
UPDATE apps/npp/project.json
```

Second call has failed:
```
oz@Avalon npp-ui % nx g web-worker --project=npp --path=apps/npp/src/app/components/animated-background 

>  NX  Generating @nrwl/angular:web-worker

✔ What name would you like to use for the worker? · bg-animate
[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in angular.json
[NX] Double check angular.json before proceeding
MergeConflictException [Error]: A merge conflicted on path "/apps/npp/tsconfig.worker.json".
    at /Users/oz/repos/scs/npp-ui/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:143:35
    at Array.forEach (<anonymous>)
    at HostTree.merge (/Users/oz/repos/scs/npp-ui/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:132:23)
    at /Users/oz/repos/scs/npp-ui/node_modules/@schematics/angular/node_modules/@angular-devkit/schematics/src/rules/base.js:58:103
    at /Users/oz/repos/scs/npp-ui/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
    at OperatorSubscriber._this._next (/Users/oz/repos/scs/npp-ui/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/oz/repos/scs/npp-ui/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /Users/oz/repos/scs/npp-ui/node_modules/rxjs/dist/cjs/internal/observable/innerFrom.js:120:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 >  NX   A merge conflicted on path "/apps/npp/tsconfig.worker.json".

Error: A merge conflicted on path "/apps/npp/tsconfig.worker.json".
    at /Users/oz/repos/scs/npp-ui/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:143:35
    at Array.forEach (<anonymous>)
    at HostTree.merge (/Users/oz/repos/scs/npp-ui/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:132:23)
    at /Users/oz/repos/scs/npp-ui/node_modules/@schematics/angular/node_modules/@angular-devkit/schematics/src/rules/base.js:58:103
    at /Users/oz/repos/scs/npp-ui/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
    at OperatorSubscriber._this._next (/Users/oz/repos/scs/npp-ui/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/oz/repos/scs/npp-ui/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /Users/oz/repos/scs/npp-ui/node_modules/rxjs/dist/cjs/internal/observable/innerFrom.js:120:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected Behavior

It should proceed when tsconfig.worker.json exist.

### Steps to Reproduce

1. Generate a webworker
2. Generate another one

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.0.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.2.1
   @nrwl/angular : 15.2.1
   @nrwl/cypress : 15.2.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.1
   @nrwl/js : 15.2.1
   @nrwl/linter : 15.2.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.1
   @nrwl/web : Not Found
   @nrwl/webpack : 15.2.1
   @nrwl/workspace : 15.2.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 15.0.0-rc.0
         @ngrx/effects: 15.0.0-rc.0
         @ngrx/store: 15.0.0-rc.0
         @jefiozie/ngx-aws-deploy: 5.0.0
         @ngrx/eslint-plugin: 15.0.0-rc.0
         @storybook/angular: 6.5.13
```

**Comment by FrozenPandaz** [comment]
This might be an issue in `angular-cli`? Have you filed an issue on https://github.com/angular/angular-cli?

**Comment by e-oz** [comment]
No. I can live with it.
