### ISSUE TITLE
Feat: Be able to organize `./tools/schematics` directory

### ISSUE THREAD

**Issue by hadrien-toma** [nrwl/nx#1340]
## Expected Behavior
I would like to be able to run a schematic from the workspace directory, even if it is nested inside a subdirectory of `./tools/schematics` directory.

## Current Behavior
An error is thrown when attempting to run the schematic.

## Failure Information (for bugs)
```
> myworkspace@0.0.0 workspace-schematic ~/nxtests/myworkspace
> nx workspace-schematic "foo/bar"

Error: Schematic "foo/bar" not found in collection "~/nxtests/myworkspace/dist/out-tsc/tools/schematics/workspace-schematics.json".
    at SchematicEngine.createSchematic (~/nxtests/myworkspace/node_modules/@angular-devkit/schematics/src/engine/engine.js:232:23)
    at CollectionImpl.createSchematic (~/nxtests/myworkspace/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at NodeWorkflow.execute (~/nxtests/myworkspace/node_modules/@angular-devkit/schematics/src/workflow/base.js:99:38)
    at ~/nxtests/myworkspace/node_modules/@nrwl/schematics/src/command-line/workspace-schematic.js:235:30
    at step (~/nxtests/myworkspace/node_modules/@nrwl/schematics/src/command-line/workspace-schematic.js:43:23)
    at Object.next (~/nxtests/myworkspace/node_modules/@nrwl/schematics/src/command-line/workspace-schematic.js:24:53)
    at ~/nxtests/myworkspace/node_modules/@nrwl/schematics/src/command-line/workspace-schematic.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (~/nxtests/myworkspace/node_modules/@nrwl/schematics/src/command-line/workspace-schematic.js:14:12)
    at executeSchematic (~/nxtests/myworkspace/node_modules/@nrwl/schematics/src/command-line/workspace-schematic.js:182:12)
```

### Steps to Reproduce
```
ng generate workspace-schematic foo/bar
npm run workspace-schematic foo/bar # Throw the above-mentioned error
```

### Context
```
> cat package.json 
{
  "name": "myworkspace",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "./node_modules/.bin/nx lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "./node_modules/.bin/nx affected:apps",
    "affected:libs": "./node_modules/.bin/nx affected:libs",
    "affected:build": "./node_modules/.bin/nx affected:build",
    "affected:e2e": "./node_modules/.bin/nx affected:e2e",
    "affected:test": "./node_modules/.bin/nx affected:test",
    "affected:lint": "./node_modules/.bin/nx affected:lint",
    "affected:dep-graph": "./node_modules/.bin/nx affected:dep-graph",
    "affected": "./node_modules/.bin/nx affected",
    "format": "./node_modules/.bin/nx format:write",
    "format:write": "./node_modules/.bin/nx format:write",
    "format:check": "./node_modules/.bin/nx format:check",
    "update": "ng update @nrwl/schematics",
    "update:check": "ng update",
    "workspace-schematic": "./node_modules/.bin/nx workspace-schematic",
    "dep-graph": "./node_modules/.bin/nx dep-graph",
    "help": "./node_modules/.bin/nx help"
  },
  "private": true,
  "dependencies": {
    "@nestjs/common": "5.5.0",
    "@nestjs/core": "5.5.0",
    "@angular/animations": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "core-js": "^2.5.4",
    "rxjs": "6.3.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "jest-preset-angular": "7.0.0",
    "ts-jest": "24.0.0",
    "@nestjs/schematics": "5.11.2",
    "@nestjs/testing": "5.5.0",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "^7.0.0",
    "@angular-devkit/build-angular": "~0.13.0",
    "codelyzer": "~4.5.0",
    "@nrwl/builders": "7.8.0",
    "jest": "24.1.0",
    "@types/jest": "24.0.9",
    "cypress": "3.1.0",
    "@types/jquery": "3.3.6",
    "@angular/cli": "7.3.1",
    "@nrwl/schematics": "7.8.0",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "3.2.2",
    "prettier": "1.15.2"
  }
}
```
```
> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.1
Node: 11.15.0
OS: linux x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.29.0
```

**Comment by hadrien-toma** [comment]
I still would like to be able to deeply organize the schematics directory like I described 😇

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.
