### ISSUE TITLE
Connect to cloud command non-functional.

### ISSUE THREAD

**Issue by cefn** [nrwl/nx#13425]
### Current Behavior

I removed the accessToken from my nx.json with the aim of re-setting and re-running the process of connecting NX Cloud. 

I attempted to run the command described in the [main nx documentation](https://nx.dev/core-features/share-your-cache#share-your-cache) like...

```sh
npx nx connect-to-nx-cloud
```

However, it responds as if there is no such command...

```sh
$ npx nx connect-to-nx-cloud
nx run [project][:target][:configuration] [_..]

Run a target for a project
(e.g., nx run myapp:serve:production).

You can also use the infix notation to run a target:
(e.g., nx serve myapp --configuration=production)

You can skip the use of Nx cache by using the --skip-nx-cache option.

Options:
      --version           Show version number                                                                                                                               [boolean]
      --target            Task to run for affected projects                                                                                                                  [string]
      --output-style      Defines how Nx emits outputs tasks logs                             [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes", "compact"]
      --exclude           Exclude certain projects from being processed                                                                                         [array] [default: []]
      --parallel          Max number of parallel processes [default is 3]                                                                                                    [string]
      --runner            This is the name of the tasks runner configured in nx.json                                                                                         [string]
  -c, --configuration     This is the configuration to use when performing tasks on projects                                                                                 [string]
      --verbose           Prints additional information about the commands (e.g., stack traces)                                                            [boolean] [default: false]
      --nx-bail           Stop command execution after the first failed task                                                                               [boolean] [default: false]
      --nx-ignore-cycles  Ignore cycles in the task graph                                                                                                  [boolean] [default: false]
      --skip-nx-cache     Rerun the tasks even when the results are available in the cache                                                                 [boolean] [default: false]
      --project           Target project                                                                                                                                     [string]

Error: Both project and target have to be specified
    at parseRunOneOptions (/home/cefn/Documents/github/watchable/node_modules/nx/src/command-line/run-one.js:79:15)
    at Object.<anonymous> (/home/cefn/Documents/github/watchable/node_modules/nx/src/command-line/run-one.js:20:22)
    at Generator.next (<anonymous>)
    at fulfilled (/home/cefn/Documents/github/watchable/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected Behavior

I imagined it would reconfigure the cloud connection.

### Github Repo

I was attempting to run this in https://github.com/cefn/watchable/tree/c83e81ba4274f0253c6fddbbf2c1a9868e4759a8

### Steps to Reproduce

Configure nx following tutorial documentation, then try to run `npx nx connect-to-nx-cloud`

### Nx Report

```shell
$ npm exec nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : linux x64
   npm  : 9.1.1
   
   nx : 15.1.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.1.0
   @nrwl/js : 15.1.0
   @nrwl/linter : 15.1.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.1.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
$ npx nx connect-to-nx-cloud
nx run [project][:target][:configuration] [_..]

Run a target for a project
(e.g., nx run myapp:serve:production).

You can also use the infix notation to run a target:
(e.g., nx serve myapp --configuration=production)

You can skip the use of Nx cache by using the --skip-nx-cache option.

Options:
      --version           Show version number                                                                                                                               [boolean]
      --target            Task to run for affected projects                                                                                                                  [string]
      --output-style      Defines how Nx emits outputs tasks logs                             [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes", "compact"]
      --exclude           Exclude certain projects from being processed                                                                                         [array] [default: []]
      --parallel          Max number of parallel processes [default is 3]                                                                                                    [string]
      --runner            This is the name of the tasks runner configured in nx.json                                                                                         [string]
  -c, --configuration     This is the configuration to use when performing tasks on projects                                                                                 [string]
      --verbose           Prints additional information about the commands (e.g., stack traces)                                                            [boolean] [default: false]
      --nx-bail           Stop command execution after the first failed task                                                                               [boolean] [default: false]
      --nx-ignore-cycles  Ignore cycles in the task graph                                                                                                  [boolean] [default: false]
      --skip-nx-cache     Rerun the tasks even when the results are available in the cache                                                                 [boolean] [default: false]
      --project           Target project                                                                                                                                     [string]

Error: Both project and target have to be specified
    at parseRunOneOptions (/home/cefn/Documents/github/watchable/node_modules/nx/src/command-line/run-one.js:79:15)
    at Object.<anonymous> (/home/cefn/Documents/github/watchable/node_modules/nx/src/command-line/run-one.js:20:22)
    at Generator.next (<anonymous>)
    at fulfilled (/home/cefn/Documents/github/watchable/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by FrozenPandaz** [comment]
This has been fixed in https://github.com/nrwl/nx/commit/3653e5944da44dd9df50488f33ff818c2832d161#diff-69134004442deffb32f7694747edfaf068d3277ea008cb9552e4a924625d0119R71. We will release a patch version soon.
