### ISSUE TITLE
couldn't Render React native components in React

### ISSUE THREAD

**Issue by MJ-One** [nrwl/nx#13472]
### Current Behavior

Hey there recently I've been working on your workspaces using a react native and react apps which shares the react native components across both the apps. But at last, there has been an error and i couldn't find out what the problem is. Please Help me Out.

### Expected Behavior

I am expecting to use react native components in react app.

### Steps to Reproduce

1.

### Nx Report

```shell
there has been no nx report for this issue
```

### Failure Logs

```shell
ERROR in ../../libs/react-native/src/lib/hello-world/hello-world.tsx
Module build failed (from ../../node_modules/@nrwl/webpack/src/utils/web-babel-loader.js):
SyntaxError: D:\Programs\Github\HOA_Master_New\master\libs\react-native\src\lib\hello-world\hello-world.tsx: Support for the experimental syntax 'flow' isn't currently enabled (7:8):

   5 |
   6 | /* eslint-disable-next-line */
>  7 | export interface HelloWorldProps {
     |        ^
   8 | }
   9 |
  10 |

Add @babel/preset-flow (https://github.com/babel/babel/tree/main/packages/babel-preset-flow) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-flow) to the 'plugins' section to enable parsing.
    at instantiate (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:67:32)
    at constructor (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:364:12)
    at Parser.raise (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:3365:19)
    at Parser.expectOnePlugin (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:3414:18)
    at Parser.isExportDefaultSpecifier (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:14261:16)
    at Parser.maybeParseExportDefaultSpecifier (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:14158:14)
    at Parser.parseExport (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:14088:29)
    at Parser.parseStatementContent (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:13073:27)
    at Parser.parseStatementLike (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:12952:17)
    at Parser.parseModuleItem (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:12933:17)
    at Parser.parseBlockOrModuleBlockBody (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:13558:36)
    at Parser.parseBlockBody (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:13550:10)
    at Parser.parseProgram (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:12842:10)
    at Parser.parseTopLevel (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:12832:25)
    at Parser.parse (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:14740:10)
    at parse (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\parser\lib\index.js:14782:38)
    at parser (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\core\lib\parser\index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\core\lib\transformation\normalize-file.js:66:38)
    at normalizeFile.next (<anonymous>)
    at run (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\core\lib\transformation\index.js:21:50)
    at run.next (<anonymous>)
    at transform (D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\core\lib\transform.js:22:41)
    at transform.next (<anonymous>)
    at step (D:\Programs\Github\HOA_Master_New\master\node_modules\gensync\index.js:261:32)
    at D:\Programs\Github\HOA_Master_New\master\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (D:\Programs\Github\HOA_Master_New\master\node_modules\gensync\index.js:223:11)
    at D:\Programs\Github\HOA_Master_New\master\node_modules\gensync\index.js:189:28
    at D:\Programs\Github\HOA_Master_New\master\node_modules\@babel\core\lib\gensync-utils\async.js:72:7
    at D:\Programs\Github\HOA_Master_New\master\node_modules\gensync\index.js:113:33
    at step (D:\Programs\Github\HOA_Master_New\master\node_modules\gensync\index.js:287:14)
    at D:\Programs\Github\HOA_Master_New\master\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (D:\Programs\Github\HOA_Master_New\master\node_modules\gensync\index.js:223:11)
```

### Additional Information

I've tried adding the babel/preset/flow in babel.config.js of the root of the package. But no change so far.

**Comment by xiongemi** [comment]
@MJ-One if your library is a react native one? To use react-native code in react web app, you need to:
1. install package `react-native-web`
2. in .babelrc of your react web app, add 'react-native-web' to plugins. So the babelrc should look like:
```
{
  "presets": [
    [
      "@nrwl/react/babel",
      {
        "runtime": "automatic"
      }
    ]
  ],
  "plugins": [
    [
      "module-resolver",
      {
        "alias": {
          "^react-native$": "react-native-web"
        }
      }
    ]
  ]
}


```

**Comment by minuz** [comment]
@xiongemi Thanks for your detailed answer. I'm having exactly the same issue, but the changes you proposed didn't make any difference. I still have the same error message. I was following the how-to from this article: https://blog.nrwl.io/introducing-react-native-support-for-nx-48d335e90c89

I made the changes on the app. Do I need to do something on the library as well?
I created a library using the `@nrwl/react-native:library` generator and my `babel.config.json` looks like this: 
``` json
{
  "presets": [
    "@babel/preset-flow",
    [
      "@nrwl/react/babel",
      {
        "runtime": "automatic",
        "useBuiltIns": "usage"
      }
    ]
  ],
  "plugins": [["react-native-web", { "commonjs": true }]],
  "env": {
    "test": {
      "presets": ["module:metro-react-native-babel-preset"]
    }
  }
}
``` 

I also tried the suggested from the error log but that didn't work either.

**Comment by Timur2915** [comment]
I'm also experiencing the same issue after setup by @minuz mentioned guide.

**Comment by minuz** [comment]
> I'm also experiencing the same issue after setup following @minuz mentioned guide.
> 
> UPD: Looks like for some reason the .babelrc config is not created on react-native library generation. The problem was solved after I added it with content:
> 
> ```
> {
>   "presets": ["@nrwl/react/babel"],
>   "plugins": [["react-native-web", { "commonjs": true }]]
> }
> ```

That did not work with my current setup. I managed to get it working by switching app and libs to build with vite+swc. But using webpack+babel is not working.
