### ISSUE TITLE
@nrwl/expo using pnpm gives this error Cannot resolve @babel/runtime/helpers/interopRequireDefault

### ISSUE THREAD

**Issue by violabg** [nrwl/nx#13533]
### Current Behavior

@nrwl/expo using pnpm gives this error Cannot resolve @babel/runtime/helpers/interopRequireDefault when you start a project, even with a blank project started with pnpx create-nx-workspace.

it work if you use yarn

### Expected Behavior

to be able to launch the project pnpm nx run mobile:start

### Steps to Reproduce

1. creata a new project with  pnpx create-nx-workspace and choose expo
2. start the project pnpm nx run mobile:start on iOS simulator

### Nx Report

```shell
Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on iOS...
› Opening exp://192.168.1.188:8081 on iPhone 14 Pro
› Press ? │ show all commands
iOS Bundling failed 53ms
error: Error: Cannot resolve @babel/runtime/helpers/interopRequireDefault
    at /Users/paolo/Sites/aaa/node_modules/.pnpm/@nrwl+expo@15.2.4_cxao4er3rdp3a3nmnsd2uqgmcm/node_modules/@nrwl/expo/plugins/metro-resolver.js:30:15
    at Object.resolve (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro-resolver@0.70.3/node_modules/metro-resolver/src/resolve.js:31:12)
    at ModuleResolver.resolveDependency (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:115:31)
    at DependencyGraph.resolveDependency (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async traverseDependenciesForSingleFile (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/DeltaBundler/traverseDependencies.js:114:3)
    at async DeltaCalculator._getChangedDependencies (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:164:25)
    at async DeltaCalculator.getDelta (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:94:16)
    at async DeltaBundler.buildGraph (/Users/paolo/Sites/aaa/node_modules/.pnpm/metro@0.70.3/node_modules/metro/src/DeltaBundler.js:50:5)
```

### Additional Information

nx 15.2.4

iOS 16.1

**Comment by jasondavis87** [comment]
also having this issue

**Comment by DanNeish** [comment]
I’m also having this issue

**Comment by AdhamMoussa** [comment]
I have the same issue

**Comment by anthlasserre** [comment]
Same issue

**Comment by MohammadKurjieh** [comment]
Any updates on this issue?

**Comment by TNAJanssen** [comment]
For me this only happens with nx build, i already installed @babel/runtime. Does somebody have any ideas?
