### ISSUE TITLE
Sporadic Issue with 502 Bad Gateway error on NX cloud 

### ISSUE THREAD

**Issue by Indronil** [nrwl/nx#13545]
### Current Behavior

We have a CI which runs certain tasks Using multiple agents. We are seeing the agents getting 502 NX cloud error sporidically. Attached the Logs zip here.
[logs_23878.zip](https://github.com/nrwl/nx/files/10133685/logs_23878.zip)

NX-cloud is running fin but not sure why we the CI shows a 502 error.

### Expected Behavior

CI should always run without fail and should never see 502 Badgateway error.

### Steps to Reproduce

1. Create a PR and CI runs and it fails sporadically while running " npx nx-cloud start-ci-run" in Github actions CI.

### Nx Report

```shell
Node : 14.17.4
  OS   : darwin x64
  yarn : 1.16.0
  
  nx : 12.10.0
  @nrwl/angular : 12.10.0
  @nrwl/cli : 12.10.0
  @nrwl/cypress : 12.10.0
  @nrwl/devkit : 12.10.0
  @nrwl/eslint-plugin-nx : 12.10.0
  @nrwl/express : 12.10.0
  @nrwl/jest : 12.10.0
  @nrwl/linter : 12.10.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.10.0
  @nrwl/nx-cloud : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.0
  @nrwl/storybook : 12.10.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.3
```

### Failure Logs

```shell
- Request failed with status code 503. <HTML><HEAD>
<TITLE>Service Unavailable</TITLE>
</HEAD><BODY>
<H1>Service Unavailable - Zero size object</H1>
The server is temporarily unable to service your request.  Please try again
later.<P>
Reference&#32;&#35;15&#46;1d97df17&#46;1669908094&#46;1012e9f9
</BODY></HTML>



>  NX   ERROR  Agent wasn't able to store artifacts

Error: Command failed: npx nx run-many --target=test  --projects=web-angular-shared-util-error-handling,live-feed-monitor,web-angular-order-management-console-shared,onboarding,web-angular-playout-global-overview-shared-utils,web-angular-pitchnew-ui-shared-ui-components,web-angular-shared-util-auth,reusable-ui-json-editor,reusable-ui-video-player,web-angular-administration-shared-data-access-ms-graph-api,web-angular-shared-ui-notifications,web-angular-shared-tcp-charts,vms-api,reusable-ui-acceptance-dialog,web-angular-shared-data-access-feature-flag-api,reusable-ui-loading-spinner,reusable-ui-charts,web-angular-shared-ui-breadcrumbs,reusable-ui-card,web-angular-playout-global-overview-top-of-show-view,central-repository,reusable-ui-button-bar,web-angular-central-repository-shared,reusable-ui-custom-material-components,web-angular-shared-video-players,reusable-ui-directives,var-directive,common-helpers,web-angular-shared-util-configuration --passWithNoTests --parallel --max-parallel=2
    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at invokeTasksUsingRunMany (/home/runner/work/vcap-platform-applications/vcap-platform-applications/node_modules/@nrwl/nx-cloud/lib/core/runners/distributed-agent/distributed-agent.runner.js:1:6011)
    at /home/runner/work/vcap-platform-applications/vcap-platform-applications/node_modules/@nrwl/nx-cloud/lib/core/runners/distributed-agent/distributed-agent.runner.js:1:4944
    at Generator.next (<anonymous>)
    at _0x2b32d6 (/home/runner/work/vcap-platform-applications/vcap-platform-applications/node_modules/@nrwl/nx-cloud/lib/core/runners/distributed-agent/distributed-agent.runner.js:1:2467)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  status: 166,
  signal: null,
  output: [ null, null, null ],
  pid: 2648,
  stdout: null,
  stderr: null
}
```

**Comment by FrozenPandaz** [comment]
Sorry for the inconvenience. Are you still encountering issues? It could have been intermittent.

**Comment by Indronil** [comment]
it is very sporadic. Have seen it on multiple occasions.
One of the agents die off with a 502 but the cloud is available.

**Comment by FrozenPandaz** [comment]
I'm going to close this as it was probably sporadic. If you continue to have issues, please create a new issue or contact [Nx Cloud Support ](https://nx.app/)
