### ISSUE TITLE
When targets[string].executor is not provided: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [nrwl/nx#13556]
### Current Behavior

Suppose you set up a `project.json` that includes `targets`, and one is missing the `executor` key:

```json
{
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "type": "library",
  "implicitDependencies": [],
  "targets": {
    "build": {
      "outputs": ["packages/ast-spec/dist/*.ts"]
    },
  }
}
```

### Expected Behavior

Nx should give me a friendly complaint. Vaguely:

```plaintext
> nx run my-package/build

Invalid project data at packages/my-package/project.json: target 'build' is missing an 'executor'.
```

### Github Repo

https://github.com/JoshuaKGoldberg/typescript-eslint/blob/1023cbcfa56480e1b5b963fc65f3ee28fc506a56/packages/ast-spec/project.json

### Steps to Reproduce

1. Get an existing working Nx `project.json`
2. Remove the `executor` from a target

### Nx Report

```shell
Node : 18.7.0
   OS   : darwin arm64
   npm  : 8.15.0
   
   nx : 14.8.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.4
   @nrwl/js : Not Found
   @nrwl/linter : 14.8.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.7.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 14.8.4
   typescript : 4.9.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         lerna: 6.0.3
```

### Additional Information

Can I suggest a tool such as [zod](https://github.com/colinhacks/zod) for validating these schemas?

I'd be happy to send a PR for either or both of fixing this one issue ad-hoc, and doing more schema validation.

**Comment by mklueh** [comment]
I'm running into this issue as well after using the workspace.json migration command. Is the fix already rolled out?


```

 >  NX   Cannot read properties of undefined (reading 'split')


TypeError: Cannot read properties of undefined (reading 'split')
    at getExecutorForTask (/home/user/workspace/my-app/node_modules/nx/src/tasks-runner/utils.js:176:49)
    at getCustomHasher (/home/user/workspace/my-app/node_modules/nx/src/tasks-runner/utils.js:181:21)
    at /home/user/workspace/my-app/node_modules/nx/src/hasher/hash-task.js:21:58
    at Generator.next (<anonymous>)
    at /home/user/workspace/my-app/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/user/workspace/my-app/node_modules/tslib/tslib.js:114:16)
    at hashTask (/home/user/workspace/my-app/node_modules/nx/src/hasher/hash-task.js:20:20)
    at TasksSchedule.<anonymous> (/home/user/workspace/my-app/node_modules/nx/src/tasks-runner/tasks-schedule.js:65:48)
    at Generator.next (<anonymous>)

```



Only those targets specified in the project.json are affected, while normal package.json scripts work

```
{
  "projectType": "application",
  "root": "apps/my-app",
  "targets": {
    "deploy": {
      "dependsOn": [
        {
          "projects": "dependencies",
          "target": "prepack"
        }
      ]
    },
    "dev": {
      "dependsOn": [
        {
          "projects": "dependencies",
          "target": "prepack:stub"
        }
      ]
    }
  }
}
```
