### ISSUE TITLE
cypress-component-configuration unable to find configs

### ISSUE THREAD

**Issue by tytremblay** [nrwl/nx#13562]
### Current Behavior

I'm unable to add component testing to my React app.  It seems that the generator is unable to find a config for the app?

### Expected Behavior

The generator finds the config and updates it.

### Steps to Reproduce

1. nx g @nrwl/react:cypress-component-configuration --project=control-panel --generate-tests --verbose

### Nx Report

```shell
Node : 16.13.1
   OS   : linux x64
   npm  : 8.12.1
   
   nx : 14.8.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.6
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.6
   @nrwl/expo : Not Found
   @nrwl/express : 14.8.6
   @nrwl/jest : 14.8.6
   @nrwl/js : 14.8.6
   @nrwl/linter : 14.8.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.8.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.6
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.6
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.6
   @nrwl/web : 14.8.6
   @nrwl/webpack : 14.8.6
   @nrwl/workspace : 14.8.6
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
$ nx g @nrwl/react:cypress-component-configuration --project=control-panel --generate-tests --verbose

>  NX  Generating @nrwl/react:cypress-component-configuration
>  NX   Cannot read properties of undefined (reading 'config')

TypeError: Cannot read properties of undefined (reading 'config')
    at node_modules/@nrwl/react/src/generators/cypress-component-configuration/lib/update-configs.js:14:32
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/tslib/tslib.js:115:62)
```

### Additional Information

Here is my `project.json` if relevant:
```
{
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/control-panel/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nrwl/web:webpack",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "compiler": "babel",
        "outputPath": "dist/apps/control-panel",
        "index": "apps/control-panel/src/index.html",
        "baseHref": "/",
        "main": "apps/control-panel/src/main.tsx",
        "polyfills": "apps/control-panel/src/polyfills.ts",
        "tsConfig": "apps/control-panel/tsconfig.app.json",
        "assets": [
          "apps/control-panel/src/favicon.ico",
          "apps/control-panel/src/assets"
        ],
        "styles": ["apps/control-panel/src/styles.css"],
        "scripts": [],
        "webpackConfig": "@nrwl/react/plugins/webpack"
      },
      "configurations": {
        "development": {
          "extractLicenses": false,
          "optimization": false,
          "sourceMap": true,
          "vendorChunk": true
        },
        "production": {
          "fileReplacements": [
            {
              "replace": "apps/control-panel/src/environments/environment.ts",
              "with": "apps/control-panel/src/environments/environment.prod.ts"
            }
          ],
          "optimization": true,
          "outputHashing": "all",
          "sourceMap": false,
          "namedChunks": false,
          "extractLicenses": true,
          "vendorChunk": false
        }
      }
    },
    "serve": {
      "executor": "@nrwl/web:dev-server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "control-panel:build",
        "hmr": true,
        "proxyConfig": "apps/control-panel/proxy.conf.json",
        "port": 3001,
        "open": true
      },
      "configurations": {
        "development": {
          "buildTarget": "control-panel:build:development"
        },
        "production": {
          "buildTarget": "control-panel:build:production",
          "hmr": false
        }
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/control-panel/**/*.{ts,tsx,js,jsx}"]
      }
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["coverage/apps/control-panel"],
      "options": {
        "jestConfig": "apps/control-panel/jest.config.ts",
        "passWithNoTests": true
      }
    }
  },
  "tags": []
}
```

**Comment by tytremblay** [comment]
https://github.com/nrwl/nx/issues/12844
