### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name') when running nx affected

### ISSUE THREAD

**Issue by jericopingul** [nrwl/nx#13668]
### Current Behavior

Running into an error when running `nx affected` because the resulting `undefined` returned by an `[].find()` isn't handled.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/11609982/205988599-75af086d-2cd3-4a45-b183-55c848fead75.png">

### Expected Behavior

No error, undefined is handled.

### Github Repo

https://github.com/jericopingul/nx-affected-issue

### Steps to Reproduce

1. Clone the project linked
2. Checkout [this PR branch](https://github.com/jericopingul/nx-affected-issue/pull/1) with `git checkout test`
3. Run `pnpm i` and then `pnpm nx affected --target=lint`

### Nx Report

```shell
pnpm nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   pnpm : 7.14.0
   
   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
TypeError: Cannot read properties of undefined (reading 'name')
    at getTouchedNpmPackages (/Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/nx@15.3.0/node_modules/nx/src/project-graph/affected/locators/npm-packages.js:24:41)
    at /Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/nx@15.3.0/node_modules/nx/src/project-graph/affected/affected-project-graph.js:31:27
    at Array.reduce (<anonymous>)
    at filterAffected (/Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/nx@15.3.0/node_modules/nx/src/project-graph/affected/affected-project-graph.js:30:52)
    at projectsToRun (/Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/nx@15.3.0/node_modules/nx/src/command-line/affected.js:100:55)
    at Object.<anonymous> (/Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/nx@15.3.0/node_modules/nx/src/command-line/affected.js:29:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jericopingul/projects/nx-affected-issue/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {stack: 'TypeError: Cannot read properties of undefine…ions (node:internal/process/task_queues:96:5)', message: 'Cannot read properties of undefined (reading 'name')'}
```

**Comment by DoomAndLove** [comment]
I've got the same error myself when looking to add a new lib with a package.json for publishing the lib
```
yarn nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : win32 x64
   yarn : 3.3.0

   nx : 15.0.13
   @nrwl/angular : 15.0.13
   @nrwl/cypress : 15.0.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.13
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.13
   @nrwl/js : 15.0.13
   @nrwl/linter : 15.0.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.0.13
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.0.13
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.13
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.13
   @nrwl/workspace : 15.0.13
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         ng-zorro-antd: 14.2.1
         ngx-daterangepicker-material: 6.0.0
         @compodoc/compodoc: 1.1.19
         @jscutlery/semver: 2.27.1
         ngx-deploy-npm: 4.3.0
         nx-stylelint: 14.0.2
```

**Comment by jericopingul** [comment]
@FrozenPandaz is it possible to be able to push a fix for this issue to this repo please? I'm getting a permissions error at the moment

```bash
ERROR: Permission to nrwl/nx.git denied to jericopingul.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by newmankyle** [comment]
I have a similar issue to @DoomAndLove. If I log inside npm-packages.js and inspect what's failing I get this:
* it's consistently failing when path is  `['devDepencies', 'html-webpack-plugin']` (this was added via cypress' component-test generator)
* when I log the names in external nodes, html-webpack-plugin looks like this
```
npmPackages.[x].name === 'npm:html-webpack-plugin-4@npm:html-webpack-plugin'
npmPackages.[x].data.packageName === 'html-webpack-plugin-4@npm:html-webpack-plugin'
// I also get an entry for 'html-webpack-plugin-5' which has the same issue
```
for all other packages, [x].data.packageName is simply the regular npm module name.

**Comment by jericopingul** [comment]
Thank you both @meeroslav and @FrozenPandaz for helping resolve this 🎉
