### ISSUE TITLE
nx g c doesn't work

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#13673]
### Current Behavior

```
oz@Avalon npp-ui % nx g c err-localized --project=components --verbose        

>  NX  Generating @nrwl/angular:component


 >  NX   Invalid Version: null


TypeError: Invalid Version: null
    at new SemVer (/Users/oz/repos/scs/npp-ui/node_modules/@nrwl/angular/node_modules/semver/classes/semver.js:19:13)
    at major (/Users/oz/repos/scs/npp-ui/node_modules/@nrwl/angular/node_modules/semver/functions/major.js:2:29)
    at getGeneratorDirectoryForInstalledAngularVersion (/Users/oz/repos/scs/npp-ui/node_modules/@nrwl/angular/src/utils/get-generator-directory-for-ng-version.js:13:52)
    at /Users/oz/repos/scs/npp-ui/node_modules/@nrwl/angular/src/generators/component/component.js:14:129
    at Generator.next (<anonymous>)
    at /Users/oz/repos/scs/npp-ui/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/oz/repos/scs/npp-ui/node_modules/tslib/tslib.js:114:16)
    at componentGenerator (/Users/oz/repos/scs/npp-ui/node_modules/@nrwl/angular/src/generators/component/component.js:13:20)
    at Object.<anonymous> (/Users/oz/repos/scs/npp-ui/node_modules/nx/src/command-line/generate.js:222:36)

```

### Expected Behavior

generated component

### Steps to Reproduce

I can not reporduce it with the newly created workspace, although it doesn't make things better for my existing workspace.
Please read the error and let me know if you know what could be the reason and if I can fix it.
Last migration was from 15.2 to 15.3

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.2.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 15.0.0
         @ngrx/effects: 15.0.0
         @ngrx/store: 15.0.0
         @jefiozie/ngx-aws-deploy: 5.0.0
         @ngrx/eslint-plugin: 15.0.0
         @storybook/angular: 6.5.14
```

**Comment by FrozenPandaz** [comment]
What is the `@angular/core` version in your `package.json`? Is it under `dependencies` or `devDependencies`?

**Comment by e-oz** [comment]
> "@angular/core": "next",

in `dependencies`.

When I put `^15.1.0-next.1` here it works.
