### ISSUE TITLE
Wildcard not working in --projects for run-many

### ISSUE THREAD

**Issue by ajmal-bash** [nrwl/nx#13715]
### Current Behavior

`nx run-many --target=test --projects=myapp-*`

```
Error: Invalid projects: myapp-*
    at checkForInvalidProjects (/home/monorepo/node_modules/nx/src/command-line/run-many.js:45:15)
    at projectsToRun (/home/monorepo/node_modules/nx/src/command-line/run-many.js:38:5)
    at Object.<anonymous> (/home/monorepo/node_modules/nx/src/command-line/run-many.js:23:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/monorepo/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Behavior

Nx to run target `test` on all projects starting with `myapp`

### Github Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

`1. nx run-many --target=lint --projects=cart*`
zsh: no matches found: --projects=cart*

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   npm  : 8.11.0
   
   nx : 14.8.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : 15.2.4
   @nrwl/linter : 14.8.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.2.4
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @theunderscorer/nx-semantic-release: 1.14.0
```

### Failure Logs

```shell
`nx run-many --target=test --projects=myapp-*`


nx run-many

Run target for multiple listed projects

Options:
  --help              Show help                                                                                                                                      [boolean]
  --version           Show version number                                                                                                                            [boolean]
  --target            Task to run for affected projects                                                                                                    [string] [required]
  --parallel          Max number of parallel processes [default is 3]                                                                                                 [string]
  --output-style      Defines how Nx emits outputs tasks logs                                     [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes"]
  --projects          Projects to run (comma delimited)                                                                                                               [string]
  --all               [deprecated] Run the target on all projects in the workspace                                                                   [boolean] [default: true]
  --runner            Override the tasks runner in `nx.json`                                                                                                          [string]
  --skip-nx-cache     Rerun the tasks even when the results are available in the cache                                                              [boolean] [default: false]
  --configuration     This is the configuration to use when performing tasks on projects                                                                              [string]
  --only-failed       Only run the target on projects which previously failed
                 [deprecated: The command to rerun failed projects will appear if projects fail. This now does nothing and will be removed in v15.] [boolean] [default: false]
  --exclude           Exclude certain projects from being processed                                                                                      [array] [default: []]
  --verbose           Prints additional information about the commands (e.g., stack traces)                                                         [boolean] [default: false]
  --nx-bail           Stop command execution after the first failed task                                                                            [boolean] [default: false]
  --nx-ignore-cycles  Ignore cycles in the task graph                                                                                               [boolean] [default: false]

Examples:
  run-many --target=test                                      Test all projects
  run-many --target=test --projects=proj1,proj2               Test proj1 and proj2
  run-many --target=test --projects=proj1,proj2 --parallel=2  Test proj1 and proj2 in parallel

Find more information and examples at https://nx.dev/cli/run-many

Error: Invalid projects: myapp-*
    at checkForInvalidProjects (/home/monorepo/node_modules/nx/src/command-line/run-many.js:45:15)
    at projectsToRun (/home/monorepo/node_modules/nx/src/command-line/run-many.js:38:5)
    at Object.<anonymous> (/home/monorepo/node_modules/nx/src/command-line/run-many.js:23:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/monorepo/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```


### Additional Information

```
nx --version
14.8.2
```

**Comment by FrozenPandaz** [comment]
1. Running `nx run-many --target projects=cart*` will not work in most shells as they will try to expand `cart*` and will expand it into whatever is on the filesystem. For the `nx-examples`, that is nothing which is what `zsh` is telling you.
2. The real error you're seeing is because this feature was recently introduced to Nx.
  a. This should be properly documented. Would you like to make the change?

**Comment by rubiagatra** [comment]
should we add a wildcard to this documentation @FrozenPandaz? https://nx.dev/nx/run-many#run-many

**Comment by ajmal-bash** [comment]
@FrozenPandaz @rubiagatra I ran this command in a bash shell
wildcard works in the example nx repo but not in our monorepo - https://mobius-gitlab.bt.com/assets-public/demo-monorepo

Can you pls let me know what I am missing here ?

**Comment by brskiy** [comment]
@ajmal-bash Fixed by install node v16. https://nx.dev/packages/workspace/documents/nx-nodejs-typescript-version-matrix

**Comment by ajmal-bash** [comment]
> @ajmal-bash Fixed by install node v16. https://nx.dev/packages/workspace/documents/nx-nodejs-typescript-version-matrix 

@brskiy Did the command work in the sample repo I have shared using node v16 ?
Can you please confirm exact node version? I am already using node version 16.15.1
