### ISSUE TITLE
Custom cache location not working

### ISSUE THREAD

**Issue by FlorianBurgevin** [nrwl/nx#13760]
### Current Behavior

Hello.

I'm trying to change the NX cache location following the documentation
https://nx.dev/concepts/how-caching-works#customizing-the-cache-location

```json
    "tasksRunnerOptions": {
        "default": {
            "runner": "nx/tasks-runners/default",
            "options": {
                "cacheableOperations": ["build", "lint", "test", "e2e"],
                "cacheDirectory": "/nxcache"
            }
        }
    },
```

But when I launch my nx commands (build or tests), i got errors.

```
Error: ENOENT: no such file or directory, open '/nxcache/d/daemon-error.log'
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2157:35)
    at writeDaemonLogs (/sources/node_modules/nx/src/daemon/tmp-dir.js:19:28)
    at /sources/node_modules/nx/src/project-graph/project-graph.js:118:72
    at Generator.throw (<anonymous>)
    at rejected (/sources/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/nxcache/d/daemon-error.log'
}
```

Then I tried to disable `NX_DAEMON` but still i have errors.

```
Error: Failed to create directory: /nxcache
    at ensureCacheDirectory (/sources/node_modules/nx/src/project-graph/nx-deps-cache.js:30:19)
    at readCache (/sources/node_modules/nx/src/project-graph/nx-deps-cache.js:37:5)
    at /sources/node_modules/nx/src/project-graph/build-project-graph.js:28:66
    at Generator.next (<anonymous>)
    at /sources/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/sources/node_modules/tslib/tslib.js:113:16)
    at buildProjectGraph (/sources/node_modules/nx/src/project-graph/build-project-graph.js:24:20)
    at /sources/node_modules/nx/src/project-graph/project-graph.js:52:66
    at Generator.next (<anonymous>)
```

### Expected Behavior

I want the cache stored in my custom location and not in node_modules ".cache"

Thanks

### Steps to Reproduce

1. Change location of cache
2. Launch build command

### Nx Report

```shell
Node : 16.14.2
   OS   : linux x64
   npm  : 8.11.0
   
   nx : 14.3.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.3.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.4.4
   ---------------------------------------
   Community plugins:

(node:19771) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /sources/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by jonhamm** [comment]
Are you sure you have permission to create a directory in the root - i.e. can you try `mkdir /nxcache` and then some `nx` command?

**Comment by FlorianBurgevin** [comment]
Hello @jonhamm 
That's the same if the directory is already created.

**Comment by FlorianBurgevin** [comment]
Ok.
It was effectively a problem with rights.

If changed the cache location to point to my project instead of /nxcache and it's OK !

Thanks.
