### ISSUE TITLE
Using Github branch as dependency in package.json cause build (--generatedPackageJson) to fail

### ISSUE THREAD

**Issue by boompikachu** [nrwl/nx#13868]
### Current Behavior

if in package.json has a GitHub branch/commit as a dependency, such as 
```
"omise": "github:omise/omise-node#515461b84a775f29899021d412be1f178c6c0d26",
```
building with `pnpm build <project> --generatePackageJson` caused the build to fail.

### Expected Behavior

Should not cause error

### Steps to Reproduce

1. add `"omise": "github:omise/omise-node#515461b84a775f29899021d412be1f178c6c0d26",` to package.json
2. import the package inside app.
3. build the app with `pnpm build <project name> --generatePackageJson`

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin arm64
   pnpm : 7.18.2
   
   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : 15.3.3
   @nrwl/next : 15.3.3
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.3.3
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.3
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
         @project/platform-frontend
         @project/platform-backend
   ---------------------------------------
   Community plugins:
         @nx-plus/docusaurus: 12.2.0
```

### Failure Logs

```shell
HookWebpackError: Cannot read properties of undefined (reading 'key')
    at makeWebpackError (PATH/node_modules/.pnpm/webpack@5.75.0_@swc+core@1.2.203/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at PATH/node_modules/.pnpm/webpack@5.75.0_@swc+core@1.2.203/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (PATH/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:71:1)
    at fn (PATH/node_modules/.pnpm/webpack@5.75.0_@swc+core@1.2.203/node_modules/webpack/lib/Compilation.js:480:17)
    at _next0 (eval at create (PATH/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:69:1)
    at eval (eval at create (PATH/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:82:1)
    at eval (eval at create (PATH/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'key')
    at PATH/node_modules/.pnpm/nx@15.3.3_5zubonobd4pskrhk2vdirnv6gy/node_modules/nx/src/lock-file/pnpm.js:239:35
    at Array.forEach (<anonymous>)
    at pruneDependencies (PATH/node_modules/.pnpm/nx@15.3.3_5zubonobd4pskrhk2vdirnv6gy/node_modules/nx/src/lock-file/pnpm.js:225:181)
    at prunePnpmLockFile (PATH/node_modules/.pnpm/nx@15.3.3_5zubonobd4pskrhk2vdirnv6gy/node_modules/nx/src/lock-file/pnpm.js:213:26)
    at createLockFile (PATH/node_modules/.pnpm/nx@15.3.3_5zubonobd4pskrhk2vdirnv6gy/node_modules/nx/src/lock-file/lock-file.js:152:57)
    at PATH/node_modules/.pnpm/@nrwl+webpack@15.3.3_ww7ajodpujsuwhvnuzllhch7dy/node_modules/@nrwl/webpack/src/utils/generate-package-json-webpack-plugin.js:42:135
    at fn (PATH/node_modules/.pnpm/webpack@5.75.0_@swc+core@1.2.203/node_modules/webpack/lib/Compilation.js:478:10)
    at _next0 (eval at create (PATH/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:69:1)
    at eval (eval at create (PATH/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:82:1)
    at eval (eval at create (PATH/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
```

### Additional Information

In `packages/nx/src/lock-file/pnpm.ts`

```ts
function pruneDependencies(
  dependencies: LockFileData['dependencies'],
  normalizedPackageJson: PackageJsonDeps
): LockFileData['dependencies'] {
  const result: LockFileData['dependencies'] = {};

  Object.keys({
    ...normalizedPackageJson.dependencies,
    ...normalizedPackageJson.devDependencies,
    ...normalizedPackageJson.peerDependencies,
  }).forEach((packageName) => {
    if (dependencies[packageName]) {
      const [key, { packageMeta, ...value }] = Object.entries(
        dependencies[packageName]
      ).find(([_, v]) => v.rootVersion);
      result[packageName] = result[packageName] || {};
      const metaKey = `/${packageName}/${value.version}`;
      const meta = packageMeta.find((m) => m.key.startsWith(metaKey));        ///// problem here

      result[packageName][key] = Object.assign(value, {
        packageMeta: [
          {
            isDependency:
              !!normalizedPackageJson.dependencies?.[packageName] ||
              !!normalizedPackageJson.peerDependencies?.[packageName],
            isDevDependency:
              !!normalizedPackageJson.devDependencies?.[packageName],
            key: meta.key,     // error here
            specifier: value.version,
            dependencyDetails: meta.dependencyDetails,    //error here
          },
        ],
      });

      pruneTransitiveDependencies(
        [packageName],
        dependencies,
        result,
        result[packageName][key]
      );
    } else {
      console.warn(
        `Could not find ${packageName} in the lock file. Skipping...`
      );
    }
  });

  return result;
}
```
packageMeta.find((m) => m.key.startsWith(metaKey)) may return undefined if it cannot match startsWith

the `packageMeta` is 

```
[
  {
    key: 'github.com/omise/omise-node/515461b84a775f29899021d412be1f178c6c0d26',
    isDependency: true,
    isDevDependency: false,
    specifier: 'omise/omise-node#515461b84a775f29899021d412be1f178c6c0d26',
    dependencyDetails: { dependencies: [Object], transitivePeerDependencies: [Array] }
  }
]
``` 
while the `metakey` value is `/omise/github.com/omise/omise-node/515461b84a775f29899021d412be1f178c6c0d26`

can fix by checking undefined
{
....
key: meta?.key,     // fix here
specifier: value.version,
dependencyDetails: meta?.dependencyDetails,    // fix here
...
}

or maybe check if version is not a number, don't append (in this case), '/omise'

**Comment by meeroslav** [comment]
What version of Nx are you using? This should have been fixed in the latest version with https://github.com/nrwl/nx/pull/13585
