### ISSUE TITLE
Can't set up Cypress Component Testing for publishable Angular library (using @nrwl/angular:package executor)

### ISSUE THREAD

**Issue by Waterstraal** [nrwl/nx#13873]
### Current Behavior

An error is thrown when I run: `nx g @nrwl/angular:cypress-component-configuration --project=my-cool-lib --verbose`:

```
>  NX  Generating @nrwl/angular:cypress-component-configuration

√ Automatically generate tests for components declared in this project? (y/N) · false

 >  NX   Unable to find a valid build configuration. Try passing in a target for an Angular app. --build-target=<project>:<target>[:<configuration>]


Error: Unable to find a valid build configuration. Try passing in a target for an Angular app. --build-target=<project>:<target>[:<configuration>]
    at assertValidConfig (C:\Sandboxes\Experiments\my-cool-org\node_modules\@nrwl\angular\src\generators\cypress-component-configuration\cypress-component-configuration.js:83:15)
    at C:\Sandboxes\Experiments\my-cool-org\node_modules\@nrwl\angular\src\generators\cypress-component-configuration\cypress-component-configuration.js:75:9
    at Generator.next (<anonymous>)
    at fulfilled (C:\Sandboxes\Experiments\my-cool-org\node_modules\tslib\tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
```

### Expected Behavior

Cypress Component Testing should work in a Nx monorepo with publishable Angular libs. 

### Steps to Reproduce

1. `npx create-nx-workspace --preset angular-monorepo --name my-cool-org --appName=nx-cct --nxCloud=false`
2. select scss
3. `cd my-cool-org`
4. `nx g @nrwl/angular:lib myCoolLib --publishable --importPath=@my-cool-org/my-cool-lib`
5. `nx g @nrwl/angular:cypress-component-configuration --project=my-cool-lib`
6. An error is thrown. 
 
When I dive in the `assertValidConfig` method that throws the error it seems it only accept two executors: `@nrwl/angular:webpack-browser` and `@angular-devkit/build-angular:browser`. Because I am using a publishable Angular library, this has a `@nrwl/angular:package` executor.

Note. Referencing the Angular app does work: `nx g @nrwl/angular:cypress-component-configuration --project=nx-cct --verbose`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : win32 x64
   npm  : 8.19.3

   nx : 15.3.3
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
The error:

>  NX  Generating @nrwl/angular:cypress-component-configuration

√ Automatically generate tests for components declared in this project? (y/N) · false

 >  NX   Unable to find a valid build configuration. Try passing in a target for an Angular app. --build-target=<project>:<target>[:<configuration>]


Error: Unable to find a valid build configuration. Try passing in a target for an Angular app. --build-target=<project>:<target>[:<configuration>]
    at assertValidConfig (C:\Sandboxes\Experiments\my-cool-org\node_modules\@nrwl\angular\src\generators\cypress-component-configuration\cypress-component-configuration.js:83:15)
    at C:\Sandboxes\Experiments\my-cool-org\node_modules\@nrwl\angular\src\generators\cypress-component-configuration\cypress-component-configuration.js:75:9
    at Generator.next (<anonymous>)
    at fulfilled (C:\Sandboxes\Experiments\my-cool-org\node_modules\tslib\tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5



cypress-component-configuration.js:

function updateProjectConfig(tree, options) {
    return tslib_1.__awaiter(this, void 0, void 0, function* () {
        const found = yield (0, find_target_options_1.findBuildConfig)(tree, {
            project: options.project,
            buildTarget: options.buildTarget,
            validExecutorNames: new Set([
                '@nrwl/angular:webpack-browser',
                '@angular-devkit/build-angular:browser',
            ]),
        });
        assertValidConfig(found === null || found === void 0 ? void 0 : found.config);
        const projectConfig = (0, devkit_1.readProjectConfiguration)(tree, options.project);
        projectConfig.targets['component-test'].options = Object.assign(Object.assign({}, projectConfig.targets['component-test'].options), { skipServe: true, devServerTarget: found.target });
        (0, devkit_1.updateProjectConfiguration)(tree, options.project, projectConfig);
    });
}
function assertValidConfig(config) {
    if (!config) {
        throw new Error('Unable to find a valid build configuration. Try passing in a target for an Angular app. --build-target=<project>:<target>[:<configuration>]');
    }
}
```

**Comment by barbados-clemens** [comment]
the build target currently has to be an Angular app. the build target for a publishable library does not contain the the information that cypress needs to run the component testing framework.

**Comment by Waterstraal** [comment]
@barbados-clemens It's a shame that it's restricted to Angular apps. It would be super useful to be able to configure Cypress Component Testing for libs. Is there any way to make it work?

**Comment by barbados-clemens** [comment]
You can use it for libraries, you just need to pass it a build target for an app when generating (or set the devServerTarget on the component-test target to the apps build target)

i.e. 
`nx g cypress-component-configuration --project=my-ng-library --build-target=my-ng-app:build`

**Comment by Waterstraal** [comment]
@barbados-clemens I guess that works if you happen to have an Angular app in your Nx workspace. In my case, I do not. I would have to create a dummy app in order to get this to work. Would be great if that would not be needed and Nx would solve this under the hood :).

**Comment by Waterstraal** [comment]
@barbados-clemens The above setup with an app as build target can run component tests, but it has issues:
- It does not load in the global styles.scss as defined in the build target app
- It cannot find zone.js

To fix this, I had to modify cypress.config.ts: 

```ts
import { defineConfig } from 'cypress';
import { nxComponentTestingPreset } from '@nrwl/angular/plugins/component-testing';

const preset: Cypress.ConfigOptions = {
  component: {
    ...nxComponentTestingPreset(__filename),
    specPattern: [`**/*.cy.ts`],
    devServer: {
      framework: 'angular',
      bundler: 'webpack',
      options: {
        projectConfig: {
          root: '',
          sourceRoot: '../../apps/my-ng-app',
          buildOptions: {
            tsConfig: '../../apps/my-ng-app/tsconfig.app.json',
            inlineStyleLanguage: 'scss',
            styles: ['../../apps/my-ng-app/src/styles.scss'],
          },
        },
      },
    },
  },
};

export default defineConfig(preset);
```

It still complains about not being able to find the favicon, but all styles load now and there are no warning about zone.js anymore. 

Above solution is definitely not ideal. IMHO, this should be abstracted away in the `nxComponentTestingPreset` so nx users can just use component testing in an Angular library. 

@barbados-clemens Could this issue be reopened to address this?

**Comment by barbados-clemens** [comment]
@Waterstraal please open a new issue since the issue you're seeing and the original issue are unrelated.
