### ISSUE TITLE
@nrwl/angular:application fails in Angular CLI workspace (only angular.json exists)

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx#13918]
### Current Behavior

>⚠ Sorry if such usage is totally out of scope ⚠ 

I see a TypeError when trying to generate @nrwl/angular:application in Angular CLI project where only `angular.json` is present.

![image](https://user-images.githubusercontent.com/1770529/208549580-2c1fc3aa-3cf4-4bde-bd8f-b7ed34d8fd72.png)

### Expected Behavior

I am expecting that it should be possible

### Steps to Reproduce

```bash
npx @angular/cli new ng15-minimal --create-application=false --minimal --defaults
cd ng15-minimal
npm i @nrwl/angular -D
ng generate @nrwl/angular:application my-nx-app --defaults --directory=apps --e2e-test-runner=none --unit-test-runner=none
```

### Nx Report

```shell
Node : 14.20.0
   OS   : win32 x64
   npm  : 6.14.17

   nx : 15.3.3
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
> ng generate @nrwl/angular:application my-nx-app --defaults --directory=apps --e2e-test-runner=none --unit-test-runner=none
[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in angular.json
[NX] Double check angular.json before proceeding
Cannot find configuration for 'my-nx-app' in /angular.json.
C:\ng15-minimal\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\util\hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: Cannot read property 'toString' of null
    at saveWorkspaceConfigurationInWrappedSchematic (C:\ng15-minimal\node_modules\nx\src\adapter\ngcli-adapter.js:866:62)
    at SafeSubscriber.recorder [as _next] (C:\ng15-minimal\node_modules\nx\src\adapter\ngcli-adapter.js:772:21)
    at SafeSubscriber.__tryOrUnsub (C:\ng15-minimal\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\ng15-minimal\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\ng15-minimal\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (C:\ng15-minimal\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Subject.next (C:\ng15-minimal\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subject.js:60:25)
    at SafeSubscriber._next (C:\ng15-minimal\node_modules\@angular-devkit\schematics\src\workflow\base.js:75:28)
    at SafeSubscriber.__tryOrUnsub (C:\ng15-minimal\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\ng15-minimal\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:143:22)
```

### Additional Information

It fails here https://github.com/nrwl/nx/blob/37dc336a0a618ba8decdbbfe95285f477de45f7d/packages/nx/src/adapter/ngcli-adapter.ts#L1220-L1222

**Comment by Coly010** [comment]
The expected flow would be to do the following:

1. `npx nx init`
2. `nx g @nrwl/angular:app`

I'll close this issue but if you have any further problems, tag me!
