### ISSUE TITLE
15 Migration: TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by gitout0fhere** [nrwl/nx#13930]
### Current Behavior

Running `nx build` after migrating from 14.2.0 to 15.3.3 produces an error. 

TypeError: Cannot read properties of undefined (reading 'data')
    at C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\utils\\hashing.js:43:37
    at Array.forEach (<anonymous>)
    at traverseExternalNodesDependencies (C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\utils\\hashing.js:41:37)
    at hashExternalNode (C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\utils\\hashing.js:36:9)
    at C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\utils\\hashing.js:23:13
    at Array.forEach (<anonymous>)
    at hashExternalNodes (C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\utils\\hashing.js:20:45)
    at mapLockFileDataToPartialGraph (C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\lock-file\\lock-file.js:95:41)
    at C:\\Sources\\tp-frontend-framework\\node_modules\\nx\\src\\project-graph\\build-project-graph.js:61:78
    at Generator.next (<anonymous>)
  message: "Cannot read properties of undefined (reading 'data')

Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
If the error persists, please run "nx reset".

### Expected Behavior

The project builds without errors.

### Steps to Reproduce

I don't exactly know what causes this behavior. I got this after migrating from 14.2.0 to 15.3.3 using `nx migrate latest`.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : win32 x64
   npm  : 8.11.0

   nx : 15.3.3
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.3
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nebular/theme: 9.0.3
         angular-auth-oidc-client: 14.1.4
         @storybook/angular: 6.5.12
```

### Additional Information

Reverting to 15.2.4 resolves the issue. Deleting `node_modules` and reinstalling the packages did not.

As per #7606 more people experience this behavior lately.

**Comment by mkieblesz** [comment]
For the record, this error disappeard for me after ugprading to `15.4.4`.

**Comment by JumBay** [comment]
Same error with version `15.7.0`, reverting to `15.6.3` fixed the issue.
Here are the logs:
```sh
 nx run hasura-handlers:build --verbose

> nx run hasura-handlers:build


 >  NX   Cannot read properties of undefined (reading 'data')


HookWebpackError: Cannot read properties of undefined (reading 'data')
    at makeWebpackError (/Users/jb/myproject/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/jb/myproject/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/jb/myproject/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at fn (/Users/jb/myproject/node_modules/webpack/lib/Compilation.js:480:17)
    at Hook.eval [as callAsync] (eval at create (/Users/jb/myproject/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/jb/myproject/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/Users/jb/myproject/node_modules/webpack/lib/Compilation.js:3057:34)
    at /Users/jb/myproject/node_modules/webpack/lib/Compilation.js:3105:10
    at symbolIterator (/Users/jb/myproject/node_modules/neo-async/async.js:3485:9)
    at done (/Users/jb/myproject/node_modules/neo-async/async.js:3527:9)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'data')
    at pathLengthToIncoming (/Users/jb/myproject/node_modules/nx/src/lock-file/project-graph-pruning.js:128:37)
    at /Users/jb/myproject/node_modules/nx/src/lock-file/project-graph-pruning.js:97:34
    at Array.forEach (<anonymous>)
    at /Users/jb/myproject/node_modules/nx/src/lock-file/project-graph-pruning.js:96:25
    at Map.forEach (<anonymous>)
    at rehoistNodes (/Users/jb/myproject/node_modules/nx/src/lock-file/project-graph-pruning.js:87:23)
    at pruneProjectGraph (/Users/jb/myproject/node_modules/nx/src/lock-file/project-graph-pruning.js:17:5)
    at createLockFile (/Users/jb/myproject/node_modules/nx/src/lock-file/lock-file.js:122:75)
    at /Users/jb/myproject/node_modules/@nrwl/webpack/src/plugins/generate-package-json-plugin.js:43:131
    at fn (/Users/jb/myproject/node_modules/webpack/lib/Compilation.js:478:10)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target build for project hasura-handlers failed

   Failed tasks:

   - hasura-handlers:build

   Hint: run the command with --verbose for more details.
```

**Comment by JumBay** [comment]
Same as https://github.com/nrwl/nx/issues/15109. This happens because `generatePackageJson` is turned on in project.json

**Comment by John-vd-Berg** [comment]
Running into the same issue. This is kind of a big deal as it's the only way to sanely deploy a NestJS application since it does not include a package.json by default. Could we get any feedback on when we can expect a fix for this?

**Comment by jcassee** [comment]
I think PR #15052 contains a fix.
