### ISSUE TITLE
[Generators][Node Lib] Unable to build a buildable node library with swc compiler

### ISSUE THREAD

**Issue by atanaskanchev** [nrwl/nx#13948]
### Current Behavior

Unable to build a buildable node library with swc compiler - missing `.lib.swcrc`

### Expected Behavior

Able to build the library 

### Steps to Reproduce

1. Generate a new workspace
2. Generate a node library `nx generate @nrwl/node:library node-lib --buildable --compiler=swc --strict --testEnvironment=node`
3. Try building the library `nx run node-lib:build`

### Nx Report

```shell
Node : 16.18.1
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.4.0-beta.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.0-beta.3
   @nrwl/detox : 15.4.0-beta.3
   @nrwl/devkit : 15.4.0-beta.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.0-beta.3
   @nrwl/expo : 15.3.3
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.0-beta.3
   @nrwl/js : 15.4.0-beta.3
   @nrwl/linter : 15.4.0-beta.3
   @nrwl/nest : Not Found
   @nrwl/next : 15.4.0-beta.3
   @nrwl/node : 15.4.0-beta.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.0-beta.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.0-beta.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.0-beta.3
   @nrwl/webpack : 15.4.0-beta.3
   @nrwl/workspace : 15.4.0-beta.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nrwl/vite: 15.4.0-beta.3
```

### Failure Logs

```shell
> nx run node-lib:build


 >  NX   ENOENT: no such file or directory, open '/REPO_ROOT/libs/node-lib/.lib.swcrc'


Error: ENOENT: no such file or directory, open '/REPO_ROOT/libs/node-lib/.lib.swcrc'
    at Object.openSync (node:fs:590:3)
    at readFileSync (node:fs:458:35)
    at readJsonFile (/REPO_ROOT/node_modules/nx/src/utils/fileutils.js:18:43)
    at getHelperDependency (/REPO_ROOT/node_modules/@nrwl/js/src/utils/compiler-helper-dependency.js:48:58)
    at swcExecutor_1 (/REPO_ROOT/node_modules/@nrwl/js/src/executors/swc/swc.impl.js:63:90)
    at swcExecutor_1.next (<anonymous>)
    at resume (/REPO_ROOT/node_modules/tslib/tslib.js:230:48)
    at /REPO_ROOT/node_modules/tslib/tslib.js:229:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (/REPO_ROOT/node_modules/tslib/tslib.js:229:67)
`
```

**Comment by atanaskanchev** [comment]
Still an issue with `15.4.2`

**Comment by nartc** [comment]
Hi @atanaskanchev, is this still an issue on latest?
