### ISSUE TITLE
Cannot compile with nrwl/js:swc

### ISSUE THREAD

**Issue by dustyhorizon** [nrwl/nx#13959]
### Current Behavior

Compiling with @nrwl/js:swc throws errors

### Expected Behavior

Compiling with @nrwl/js:swc does not throw errors

### Steps to Reproduce
1. Configure target to use @nrwl/js swc executor
2. Get error `spawnSync /bin/sh ENOENT`

### Nx Report

```shell
❯ pnpm nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.1
   OS   : linux x64
   npm  : 8.15.0

   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nx-go/nx-go: 2.7.0
```

### Failure Logs

```shell
❯ pnpm nx swc node/genproto --verbose

> nx run node/genproto:swc

Compiling with SWC for node/genproto...

 >  NX   spawnSync /bin/sh ENOENT


Error: spawnSync /bin/sh ENOENT
    at Object.spawnSync (node:internal/child_process:1112:20)
    at spawnSync (node:child_process:827:24)
    at execSync (node:child_process:907:15)
    at /home/kennethtan/Documents/GitHub/opus/node_modules/.pnpm/@nrwl+js@15.3.3_wucvqhwgds7qvgzle7ri3inxiq/node_modules/@nrwl/js/src/utils/swc/compile-swc.js:36:56
    at Generator.next (<anonymous>)
    at /home/kennethtan/Documents/GitHub/opus/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/kennethtan/Documents/GitHub/opus/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:114:16)
    at compileSwc (/home/kennethtan/Documents/GitHub/opus/node_modules/.pnpm/@nrwl+js@15.3.3_wucvqhwgds7qvgzle7ri3inxiq/node_modules/@nrwl/js/src/utils/swc/compile-swc.js:31:20)
    at swcExecutor_1 (/home/kennethtan/Documents/GitHub/opus/node_modules/.pnpm/@nrwl+js@15.3.3_wucvqhwgds7qvgzle7ri3inxiq/node_modules/@nrwl/js/src/executors/swc/swc.impl.js:97:99)
```

### Additional Information

`@swc/cli` and `@swc/core` installed, `swc` binary available in `node_modules/.bin`

**Comment by atanaskanchev** [comment]
+1 Same on `15.4.0-rc.0`

**Comment by mandarini** [comment]
Hi there @dustyhorizon @atanaskanchev ! I tried with the latest version of Nx and I could not reproduce your issue. Can you please retry with latest and let me know if issue persists?
