### ISSUE TITLE
Webpack stats build result is required

### ISSUE THREAD

**Issue by urugator** [nrwl/nx#13980]
### Current Behavior

After upgrading to `@angular-devkit/build-angular": "15.0.2"` from `14.2.7.` (using `nx migrate 15.3.3` from `15.1.0`) 

`yarn nx serve` fails with
```
Error: Webpack stats build result is required.
    at MergeMapSubscriber.project (C:\Projects\redacted\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js:213:23)
    at MergeMapSubscriber._tryNext (C:\Projects\redacted\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:67:27)
    at MergeMapSubscriber._next (C:\Projects\redacted\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\mergeMap.js:57:18)
    at Subscriber.next (C:\Projects\redacted\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (C:\Projects\redacted\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\switchMap.js:85:26)
    at SimpleInnerSubscriber._next (C:\Projects\redacted\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\innerSubscribe.js:27:21)
    at Subscriber.next (C:\Projects\redacted\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:66:18)
    at C:\Projects\redacted\node_modules\@angular-devkit\build-angular\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js:51:17
    at Hook.eval [as callAsync] (eval at create (C:\Projects\redacted\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:26:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Projects\redacted\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (C:\Projects\redacted\node_modules\webpack\lib\Watching.js:287:28)
    at C:\Projects\redacted\node_modules\webpack\lib\Watching.js:209:21
    at Compiler.emitRecords (C:\Projects\redacted\node_modules\webpack\lib\Compiler.js:919:5)
    at C:\Projects\redacted\node_modules\webpack\lib\Watching.js:187:22
    at C:\Projects\redacted\node_modules\webpack\lib\Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (C:\Projects\redacted\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
```
https://github.com/angular/angular-cli/blob/5ba64014718be0193933f3850af327b6252e62ad/packages/angular_devkit/build_angular/src/builders/browser/index.ts#L202

### Expected Behavior

`yarn nx serve` not throwing

### Steps to Reproduce

1. `yarn nx migrate 15.3.3` (from 15.1.0)
2. `yarn`
3. `yarn nx migrate --run-migrations`
4. `yarn`
5. `yarn nx serve`

### Nx Report

```shell
Node : 19.2.0
   OS   : win32 x64
   yarn : 1.22.18

   nx : 15.3.3
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : 15.3.3
   @nrwl/next : Not Found
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngneat/transloco: 4.1.1
```

**Comment by Coly010** [comment]
Hey :)

I can't reproduce this.

Can you provide a repo that reproduces this issue so that we can investigate more thoroughly?

**Comment by daelmaak** [comment]
I had the same issue and simple `rm -rf node_modules` and then `yarn install` solved it.

**Comment by urugator** [comment]
Sorry for being unresponsive. I has some spare time, which I decided to spend on v15 upgrade, but this issue had blocked me and at the moment I don't have a budget to continue in the efford.

@daelmaak  Thank you for the suggestion. I did try to reinstall modules, delete caches etc without success, but perhaps something changed since then... I will try again once the opportunity appears.
