### ISSUE TITLE
address already in use error. when I save some files and reload the app.

### ISSUE THREAD

**Issue by muhammaduxair** [nrwl/nx#14027]
### Current Behavior

**Now I have migrated my Workspace to the latest version**
_but I'm facing that issue._

Starting inspector on localhost:9229 failed: address already in use
[Nest] 19084  - 12/27/2022, 3:48:48 PM     LOG [NestFactory] Starting Nest application...
[Nest] 19084  - 12/27/2022, 3:48:48 PM     LOG [InstanceLoader] AppModule dependencies initialized +33ms
[Nest] 19084  - 12/27/2022, 3:48:48 PM     LOG [RoutesResolver] AppController {/}: +6ms
[Nest] 19084  - 12/27/2022, 3:48:48 PM     LOG [RouterExplorer] Mapped {/, GET} route +5ms
[Nest] 19084  - 12/27/2022, 3:48:48 PM     LOG [NestApplication] Nest application successfully started +5ms
[Nest] 19084  - 12/27/2022, 3:48:48 PM   ERROR [NestApplication] Error: listen EADDRINUSE: address already in use :::5000 +5ms
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at ExpressAdapter.listen (C:\uzair-dir\Development\Projects\cbrand-prv\node_modules\@nestjs\platform-express\adapters\express-adapter.js:78:32)
    at C:\uzair-dir\Development\Projects\cbrand-prv\node_modules\@nestjs\core\nest-application.js:167:30
    at new Promise (<anonymous>)
    at NestApplication.listen (C:\uzair-dir\Development\Projects\cbrand-prv\node_modules\@nestjs\core\nest-application.js:156:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Expected Behavior

I want to rid of this error. when i reload or save some files.

### Steps to Reproduce

1. nx serve api

### Nx Report

```
 Node : 16.15.1
   OS   : win32 x64
   yarn : 1.22.19
   
   nx : 15.4.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.1
   @nrwl/js : 15.4.1
   @nrwl/linter : 15.4.1
   @nrwl/nest : 15.4.1
   @nrwl/next : Not Found
   @nrwl/node : 15.4.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.1
   @nrwl/webpack : 15.4.1
   @nrwl/workspace : 15.4.1
   @nrwl/vite : 15.4.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by muhammaduxair** [comment]
**Ohh! I have found a solution right now.** 

```
yarn add -D @nrwl/js@15.3.3
```

it's working fine.
