### ISSUE TITLE
Storybook (Vite) fails to run on clean monorepo setup

### ISSUE THREAD

**Issue by andrejilderda** [nrwl/nx#14055]
### Current Behavior

On a clean Nx monorepo setup Storybook fails to run (see error below).

### Expected Behavior

I expect Storybook to run properly.

### Github Repo

https://github.com/andrejilderda/nx-storybook-issue

### Steps to Reproduce

The commands I ran are:

1. `npx create-nx-workspace@latest`
    - settings: integrated, ts
2. `cd nx-storybook-issue` 
3. `yarn add -D @nrwl/react`
4. `nx g @nrwl/react:app test-app`
    - SASS
    - React Router - false
    - Vite (!)
5. `yarn add --dev @nrwl/storybook`
6. `nx g @nrwl/storybook:configuration test-app`
    - @storybook/react
    - e2e - false
    - Vite (!)
7. `nx run test-app:storybook`

### Nx Report

```shell
Node : 16.15.0
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.2
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.4.2
   @nrwl/vite : 15.4.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
> nx run test-app:storybook

info @storybook/react v6.5.15
info 
info => Loading presets

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/Andre/Development/nx-storybook-issue/node_modules/react-docgen/dist/main.js from /Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js not supported.
ERR! Instead change the require of main.js in /Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js to a dynamic import() which is available in all CommonJS modules.
ERR!     at Object.<anonymous> (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js:8:24)
ERR!     at /Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/vite-config.js:236:85
ERR!     at async pluginConfig (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/vite-config.js:236:37)
ERR!     at async commonConfig (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/vite-config.js:66:18)
ERR!     at async createViteServer (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/vite-server.js:10:24)
ERR!     at async Object.start (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/index.js:64:14)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/core-server/dist/cjs/dev-server.js:203:28)
ERR!     at async buildDevStandalone (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
ERR!  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/Andre/Development/nx-storybook-issue/node_modules/react-docgen/dist/main.js from /Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js not supported.
ERR! Instead change the require of main.js in /Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js to a dynamic import() which is available in all CommonJS modules.
ERR!     at Object.<anonymous> (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/plugins/react-docgen.js:8:24)
ERR!     at /Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/vite-config.js:236:85
ERR!     at async pluginConfig (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/vite-config.js:236:37)
ERR!     at async commonConfig (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/vite-config.js:66:18)
ERR!     at async createViteServer (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/vite-server.js:10:24)
ERR!     at async Object.start (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/builder-vite/dist/index.js:64:14)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/core-server/dist/cjs/dev-server.js:203:28)
ERR!     at async buildDevStandalone (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/Users/Andre/Development/nx-storybook-issue/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5) {
ERR!   code: 'ERR_REQUIRE_ESM'
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
✔ Would you like to send crash reports to Storybook? … no
```

**Comment by andrejilderda** [comment]
@mandarini , yes that fixes it, thanks a lot!

**Comment by omrihecht** [comment]
@mandarini , thanks for the response, migrated to latest, still not luck :(
now on v `15.4.8`
```
   Node : 18.1.0
   OS   : darwin x64
   npm  : 8.8.0

   nx : 15.4.8
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.8
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.8
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.8
   @nrwl/js : 15.4.8
   @nrwl/linter : 15.4.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.8
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.8
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.8
   @nrwl/web : 15.4.8
   @nrwl/webpack : 15.4.8
   @nrwl/workspace : 15.4.8
   @nrwl/vite : 15.4.8
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by mandarini** [comment]
Hi there @omrihecht ! 

I just tried to reproduce the issue but I couldn't.

If you migrated from an older version using `nx migrate` you should have all the correct package versions.
If you're using `vite`, you may be missing the following from your `.storybook/main.js`:

```
const rootMain = require('../../../.storybook/main');
const { mergeConfig } = require('vite');
const viteTsConfigPaths = require('vite-tsconfig-paths').default;

module.exports = {
  ...rootMain,
  core: { ...rootMain.core, builder: '@storybook/builder-vite' },
  stories: [
    ...rootMain.stories,
    '../src/app/**/*.stories.@(js|jsx|ts|tsx|mdx)',
  ],
  addons: [...rootMain.addons],
  async viteFinal(config, { configType }) {
    return mergeConfig(config, {
      plugins: [
        viteTsConfigPaths({
          root: '../../../',
        }),
      ],
    });
  },
};
```

The `const viteTsConfigPaths = require('vite-tsconfig-paths').default;` import and the `viteFinal` vite config, which are needed for Storybook. I really must update the docs there.

Can you create a reproduction of your error and send me the repository?

Versions you should have are:
* All `@nrwl/*` packages should be anything larger than `15.4.5`
* Storybook packages should be `"^6.5.15"`
But if you used `nx migrate`, that should take care of it!

**Comment by JosepBergay** [comment]
We've been hitting this issue for a while now. It's related to webpack4 and node. Workarounds are:
* Use node 16
* Run node with flag ``--openssl-legacy-provider``

Issues [webpack/#14532](https://github.com/webpack/webpack/issues/14532), [node/#40455](https://github.com/nodejs/node/issues/40455)
