### ISSUE TITLE
Module Federation with SSR for React recipe issues | Host app loading additional micro frontends in some routes. 

### ISSUE THREAD

**Issue by giri-jeedigunta** [nrwl/nx#14092]
### Current Behavior

I'm new to NX and trying out the Module federation recipe(ssr + react) available here - https://nx.dev/recipes/module-federation/module-federation-with-ssr. I created a host app called **store** and 2 remote apps - **pdp** and **search** using ```npx nx g @nrwl/react:host store --ssr --remotes=pdp,search```.

**Issue - 1:**
When I run the production build and serve(```pnpm nx serve store --configuration production```) and access http://localhost:4200/search... I'm seeing the pdp view loads first then search view. I've added throttling on the browser to capture this in screenshot.  
<img width="1728" alt="pdp-view loads first" src="https://user-images.githubusercontent.com/2689410/210257429-564e7f22-47a6-4a7d-889d-e2f91852d4fb.png">

<img width="1728" alt="search-view" src="https://user-images.githubusercontent.com/2689410/210257454-4e0f6ee8-0a02-45be-bf9d-050917ea6239.png">

but the same do not happen with http://localhost:4200/pdp

**Issue - 2:**
Hot-reload / Watch mode do not work. When I do ```pnpm nx serve store --devRemotes=search,pdp``` any changes I do in the remote apps nothing reflects. I have to stop and re-run to see the changes. What is a better way to run the host and remote apps locally for development. 

### Expected Behavior

I'm expecting **not** to see the other micro frontend code which appears in the source as shown in the screenshot above. 

### Github Repo

https://github.com/giri-jeedigunta/nx-react-module-fedration

### Steps to Reproduce

1. ```pnpm nx serve store --configuration production```
2. http://localhost:4200/search

### Nx Report

```shell
   Node : 16.18.1
   OS   : darwin arm64
   pnpm : 7.18.1

   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.2
   @nrwl/webpack : 15.4.1
   @nrwl/workspace : 15.4.2
   @nrwl/vite : 15.4.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by giri-jeedigunta** [comment]
Another issue: when I try to add additional app using ```npx nx g @nrwl/react:remote header --host=store``` The complete setup is broken with these errors: 

```

/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/@nrwl+react@15.4.2_5lsoxqohtf6xr5mptm3eh42av4/node_modules/@nrwl/react/src/executors/module-federation-ssr-dev-server/module-federation-ssr-dev-server.impl.js:44
                    const remoteServerOutput = (0, path_1.join)(devkit_1.workspaceRoot, remoteProject.targets.server.options.outputPath, 'main.js');
                                                                                                                     ^

TypeError: Cannot read properties of undefined (reading 'options')
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/@nrwl+react@15.4.2_5lsoxqohtf6xr5mptm3eh42av4/node_modules/@nrwl/react/src/executors/module-federation-ssr-dev-server/module-federation-ssr-dev-server.impl.js:44:118
    at Generator.next (<anonymous>)
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:114:16)
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/@nrwl+react@15.4.2_5lsoxqohtf6xr5mptm3eh42av4/node_modules/@nrwl/react/src/executors/module-federation-ssr-dev-server/module-federation-ssr-dev-server.impl.js:42:128
    at Object.[Symbol.asyncIterator] (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/@nrwl+devkit@15.4.2_nx@15.4.2+typescript@4.8.4/node_modules/@nrwl/devkit/src/utils/async-iterable/create-async-iterable.js:11:13)
    at f_1 (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/@nrwl+devkit@15.4.2_nx@15.4.2+typescript@4.8.4/node_modules/@nrwl/devkit/src/utils/async-iterable/map-async-iteratable.js:10:44)
    at f_1.next (<anonymous>)
    at resume (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:230:48)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project store failed

   Failed tasks:

   - store:serve:development

   Hint: run the command with --verbose for more details.


╭─  ╱  ~/Dev-Zone/Git-Repos/nx-react-module-fedration ╱ on   main !3 ?2                                                                                                 1 ✘ ╱ took 4s  ╱ at 03:36:38 pm  ─╮
╰─ Error: write EPIPE                                                                                                                                                                                              ─╯
    at process.target._send (node:internal/child_process:874:20)
    at process.target.send (node:internal/child_process:747:19)
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at process.target._send (node:internal/child_process:874:20)
    at process.target.send (node:internal/child_process:747:19)
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at process.target._send (node:internal/child_process:874:20)
    at process.target.send (node:internal/child_process:747:19)
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at process.target._send (node:internal/child_process:874:20)
    at process.target.send (node:internal/child_process:747:19)
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/venjeedi/Dev-Zone/Git-Repos/nx-react-module-fedration/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.13_qw7fmzhoapcndkteb5rsc33stq/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',

```

**Comment by giri-jeedigunta** [comment]
Issues still exist

**Comment by stevebrowndotco** [comment]
@giri-jeedigunta were you able to fix this or find a workaround?
