### ISSUE TITLE
@nrwl/nx-plugin:plugin generator fail if NOT using eslintrc JSON file

### ISSUE THREAD

**Issue by ild0tt0re** [nrwl/nx#14160]
### Current Behavior

I run `nx g @nrwl/nx-plugin:plugin my-plugin` command but it throw an error
>  NX   Cannot find .eslintrc.json

We have switched from .eslintrc.json to .eslint.js file type for flexibility, so I tried to put an initial Nx .eslintrc.json configuration file and it work.

### Expected Behavior

The `nx g @nrwl/nx-plugin:plugin my-plugin` command should generate a new `libs/my-plugin` folder also if the .eslint file type is `.js` instead of `.json`

### Steps to Reproduce

1. rename `.eslint.json` file in `.eslint.js` and adapt it to `.js` syntax
2. run `nx g @nrwl/nx-plugin:plugin my-plugin` command
3. error will be shown `>  NX   Cannot find .eslintrc.json`

### Nx Report

```shell
Node : 16.13.1
   OS   : darwin arm64
   pnpm : 7.18.2

   nx : 15.4.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.4
   @nrwl/js : 15.4.4
   @nrwl/linter : 15.4.4
   @nrwl/nest : Not Found
   @nrwl/next : 15.4.4
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.4.4
   @nrwl/react : 15.4.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.4
   @nrwl/web : 15.4.4
   @nrwl/webpack : 15.4.4
   @nrwl/workspace : 15.4.4
   @nrwl/vite : 15.4.4
   typescript : 4.9.4
   ---------------------------------------
   Community plugins:
   	 @jscutlery/semver: 2.29.3
   	 ngx-deploy-npm: 4.3.10
```

### Failure Logs

```shell
nx g @nrwl/nx-plugin:plugin my-plugin --verbose

>  NX  Generating @nrwl/nx-plugin:plugin


 >  NX   Cannot find .eslintrc.json


Error: Cannot find .eslintrc.json
    at readJson (/path/to/my/project/node_modules/.pnpm/nx@15.4.4_jo2v6bqm25ind3jfpv3cqehd6u/node_modules/nx/src/generators/utils/json.js:14:15)
    at updateRootEslintConfig (/path/to/my/project/node_modules/.pnpm/@nrwl+nx-plugin@15.4.4_m6vpjk5izdg6x75zxtvtkxpcri/node_modules/@nrwl/nx-plugin/src/generators/lint-checks/generator.js:126:46)
    at /path/to/my/project/node_modules/.pnpm/@nrwl+nx-plugin@15.4.4_m6vpjk5izdg6x75zxtvtkxpcri/node_modules/@nrwl/nx-plugin/src/generators/lint-checks/generator.js:15:13
    at Generator.next (<anonymous>)
    at /path/to/my/project/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/path/to/my/project/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:114:16)
    at pluginLintCheckGenerator (/path/to/my/project/node_modules/.pnpm/@nrwl+nx-plugin@15.4.4_m6vpjk5izdg6x75zxtvtkxpcri/node_modules/@nrwl/nx-plugin/src/generators/lint-checks/generator.js:10:20)
    at /path/to/my/project/node_modules/.pnpm/@nrwl+nx-plugin@15.4.4_m6vpjk5izdg6x75zxtvtkxpcri/node_modules/@nrwl/nx-plugin/src/generators/plugin/plugin.js:97:43
    at Generator.next (<anonymous>)
```

### Additional Information

Avoid assumptions type of file used for eslint.

**Comment by Pigrabbit** [comment]
same here

**Comment by Pigrabbit** [comment]
For me, I copied existing `.eslintrc.js` and created new one in json format(`.eslintrc.json`).

After running the script(`nx g @nrwl/nx-plugin:plugin my-plugin`), I just removed `.eslintrc.json` as it was never been there before.

**Comment by artembelik** [comment]
this property should help: https://nx.dev/packages/nx-plugin/generators/plugin#skiplintchecks
