### ISSUE TITLE
`run-many` exits with error on not existing targets

### ISSUE THREAD

**Issue by Michsior14** [nrwl/nx#14234]
### Current Behavior

When executing `nx run-many` with not existing target the command fails like bellow:

```sh
$ nx run-many --target=not-existing --projects=cart

 >  NX   the following do not have configuration for "undefined"

   - cart

nx run-many

Run target for multiple listed projects

Options:
      --help               Show help                                                                                                                                                                [boolean]
      --version            Show version number                                                                                                                                                      [boolean]
  -c, --configuration      This is the configuration to use when performing tasks on projects                                                                                                        [string]
  -t, --targets, --target  Tasks to run for affected projects                                                                                                                             [string] [required]
      --output-style       Defines how Nx emits outputs tasks logs                                                               [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes"]
      --exclude            Exclude certain projects from being processed                                                                                                               [string] [default: ""]
      --parallel           Max number of parallel processes [default is 3]                                                                                                                           [string]
      --runner             This is the name of the tasks runner configured in nx.json                                                                                                                [string]
      --verbose            Prints additional information about the commands (e.g., stack traces)                                                                                   [boolean] [default: false]
      --nx-bail            Stop command execution after the first failed task                                                                                                      [boolean] [default: false]
      --nx-ignore-cycles   Ignore cycles in the task graph                                                                                                                         [boolean] [default: false]
      --skip-nx-cache      Rerun the tasks even when the results are available in the cache                                                                                        [boolean] [default: false]
  -p, --projects           Projects to run. (comma/space delimited project names and/or patterns)                                                                                                    [string]
      --all                [deprecated] Run the target on all projects in the workspace                                                                                             [boolean] [default: true]

Examples:
  run-many --target=test                                          Test all projects
  run-many --target=test --projects=proj1,proj2                   Test proj1 and proj2
  run-many --target=test --projects=proj1,proj2 --parallel=2      Test proj1 and proj2 in parallel
  run-many --target=test --projects=*-app --exclude excluded-app  Test all projects ending with `*-app` except `excluded-app`

Find more information and examples at https://nx.dev/nx/run-many

Error: No projects found for project patterns
    at projectsToRun (/home/michal/Documents/projects/nx-examples/node_modules/nx/src/command-line/run-many.js:59:15)
    at Object.<anonymous> (/home/michal/Documents/projects/nx-examples/node_modules/nx/src/command-line/run-many.js:24:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/michal/Documents/projects/nx-examples/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

### Expected Behavior

The command should exit successfully as in `nx` <= 15.4.2:

```sh
$ nx run-many --target=not-existing --projects=cart

 >  NX   the following do not have configuration for "undefined"

   - cart

 >  NX   Successfully ran target not-existing for 0 projects (4ms)
 
   View logs and run details at https://nx.app/runs/Wj7M1X3QI9
```

### Github Repo

https://github.com/Michsior14/nx-examples/tree/bug/run-many-targets

### Steps to Reproduce

1. Use the `nx` in version above 15.4.2 (done in the provided repo)
2. Run `nx run-many` with non existing target, e.g:
```sh
yarn nx run-many --target=not-existing  --projects=cart
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : linux x64
   yarn : 1.22.18
   
   nx : 15.4.5
   @nrwl/angular : 15.4.5
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 15.0.0
         @ngrx/effects: 15.0.0
         @ngrx/entity: 15.0.0
         @ngrx/router-store: 15.0.0
         @ngrx/store: 15.0.0
         @ngrx/store-devtools: 15.0.0
```

### Additional Information

The issue was introduced in version 15.4.3.

**Comment by FrozenPandaz** [comment]
Resolved in https://github.com/nrwl/nx/pull/14238
