### ISSUE TITLE
Error running 'npx nx g @nrwl/angular:host host'

### ISSUE THREAD

**Issue by boeschenstein** [nrwl/nx#14273]
## Current Behavior

Learning nx federation and trying to reproduce the demo app according this docs: <https://nx.dev/recipes/module-federation/faster-builds>

Running

```cmd
npx nx g @nrwl/angular:host host
```

shows this error:

`>  NX   Cannot read properties of null (reading 'generators')`

## Expected Behavior

no error, continue according docs

## Steps to Reproduce

```cmd
npx create-nx-workspace acme --preset=empty --nxCloud=false --skipGit
cd acme
npm install --save-dev @nrwl/angular
npx nx g @nrwl/angular:host host --style css --verbose
```

What I tried

- other styles (css, scss, sass, less): same error
- other name (instead of host): same error

### Failure Logs / Images / Videos

`c:\work\Angular\Nx\acme>npx nx g @nrwl/angular:host host --style css --verbose

>  NX  Generating @nrwl/angular:host

 >  NX   (0 , devkit_1.updateNxJson) is not a function

TypeError: (0 , devkit_1.updateNxJson) is not a function
    at addTestInputs (c:\work\Angular\Nx\acme\node_modules\@nrwl\jest\src\generators\init\init.js:100:31)
    at createJestConfig (c:\work\Angular\Nx\acme\node_modules\@nrwl\jest\src\generators\init\init.js:36:9)
    at jestInitGenerator (c:\work\Angular\Nx\acme\node_modules\@nrwl\jest\src\generators\init\init.js:145:5)
    at c:\work\Angular\Nx\acme\node_modules\@nrwl\angular\src\generators\init\init.js:91:53
    at Generator.next (<anonymous>)
    at c:\work\Angular\Nx\acme\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (c:\work\Angular\Nx\acme\node_modules\tslib\tslib.js:114:16)
    at addUnitTestRunner (c:\work\Angular\Nx\acme\node_modules\@nrwl\angular\src\generators\init\init.js:79:20)
    at c:\work\Angular\Nx\acme\node_modules\@nrwl\angular\src\generators\init\init.js:28:36`

### Environment

- Nx Console version: not relevant, running from Windows prompt (cmd)
- VSCode version: not relevant, running from Windows prompt (cmd)

c:\work\Angular\Nx\acme>npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : win32 x64
   npm  : 8.19.3

   nx : 15.3.2
   @nrwl/angular : 15.4.5
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.3.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.3.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

## How to avoid this error

There is no error using an older version of nx workspace

npx create-nx-workspace@15.2.4

**Comment by FrozenPandaz** [comment]
Your package versions are misaligned. Can you please align them and see if the issue still exists?

**Comment by diaraujo13** [comment]
In my current project, this error has appeared while trying to generate a React app. I have no clue about what happened and caused this.

```npx nx g @nrwl/react:app webapp --bundler=vite --verbose


>  NX  Generating @nrwl/react:application

✔ Which stylesheet format would you like to use? · css
✔ Would you like to add React Router to this application? (y/N) · true

 >  NX   (0 , devkit_1.updateNxJson) is not a function


TypeError: (0 , devkit_1.updateNxJson) is not a function
    at setDefault (/home/izaias/Área de Trabalho/Projetos/Sandbox/dating-app/node_modules/@nrwl/react/src/generators/init/init.js:13:31)
    at /home/izaias/Área de Trabalho/Projetos/Sandbox/dating-app/node_modules/@nrwl/react/src/generators/init/init.js:52:9
    at Generator.next (<anonymous>)
    at /home/izaias/Área de Trabalho/Projetos/Sandbox/dating-app/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/izaias/Área de Trabalho/Projetos/Sandbox/dating-app/node_modules/tslib/tslib.js:114:16)
    at reactInitGenerator (/home/izaias/Área de Trabalho/Projetos/Sandbox/dating-app/node_modules/@nrwl/react/src/generators/init/init.js:50:20)
    at /home/izaias/Área de Trabalho/Projetos/Sandbox/dating-app/node_modules/@nrwl/react/src/generators/application/application.js:54:51
    at Generator.next (<anonymous>)
    at /home/izaias/Área de Trabalho/Projetos/Sandbox/dating-app/node_modules/tslib/tslib.js:118:75```

**Comment by diaraujo13** [comment]
I had this error while using Nx@15.4.4, so updated it to nx@15.5.0 and it works now

**Comment by boeschenstein** [comment]
Finally I figured out how to update packages installed by npx: use @lastest 

```cmd
npx create-nx-workspace@latest acme --preset=empty --nxCloud=false --skipGit
cd acme
npm install --save-dev @nrwl/angular
npx nx g @nrwl/angular:host host --style css --verbose
````

Now I think it run successfully, but I saw another error:

```
c:\work\Angular\Nx\acme>npx nx g @nrwl/angular:host host --style css --verbose

>  NX  Generating @nrwl/angular:host

[NX] Angular devkit called `writeWorkspace`, this may have created 'workspace.json' or 'angular.json
[NX] Double check workspace configuration before proceeding
Error: ENOENT: no such file or directory, open 'c:\work\Angular\Nx\acme\workspace.json'
    at Object.openSync (node:fs:600:3)
    at readFileSync (node:fs:468:35)
    at FsTree.fsReadFile (c:\work\Angular\Nx\acme\node_modules\nx\src\generators\tree.js:192:44)
    at FsTree.read (c:\work\Angular\Nx\acme\node_modules\nx\src\generators\tree.js:22:32)
    at convertEventTypeToHandleMultipleConfigNames (c:\work\Angular\Nx\acme\node_modules\nx\src\adapter\ngcli-adapter.js:666:44)
    at SafeSubscriber.recorder [as _next] (c:\work\Angular\Nx\acme\node_modules\nx\src\adapter\ngcli-adapter.js:766:23)
    at SafeSubscriber.__tryOrUnsub (c:\work\Angular\Nx\acme\node_modules\rxjs\internal\Subscriber.js:205:16)                                                                                               at SafeSubscriber.next (c:\work\Angular\Nx\acme\node_modules\rxjs\internal\Subscriber.js:143:22)                                                                                                       at Subscriber._next (c:\work\Angular\Nx\acme\node_modules\rxjs\internal\Subscriber.js:89:26)                                                                                                           at Subscriber.next (c:\work\Angular\Nx\acme\node_modules\rxjs\internal\Subscriber.js:66:18)                                                                                                        Skipping host since apps\host\project.json already exists.
UPDATE nx.json
UPDATE package.json
CREATE jest.preset.js
...
```

Report:

```
c:\work\Angular\Nx\acme>npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : win32 x64
   npm  : 8.19.3

   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

```

**Comment by Coly010** [comment]
@boeschenstein That error is printed in the console because of `--verbose`, but everything should still have been generated correctly.

There is a try-catch surrounding that area of code :)

You should be able to see your host was generated correctly, and you can run commands such as `nx serve host` and `nx build host`
