### ISSUE TITLE
NX Affected not working in pipeline

### ISSUE THREAD

**Issue by 72gm** [nrwl/nx#14274]
### Current Behavior

I'm trying to use nx affected in my azure pipeline and azure repo and I'm getting the following issue

```
npx nx affected  --target=build
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/a73faf7b-0df8-4b7b-9996-077d993e02d1.sh

 >  NX   Affected criteria defaulted to --base=main --head=HEAD

fatal: Not a valid object name main
fatal: No such ref: 'main'
nx affected
```

```
Error: Command failed: git merge-base --fork-point "main" "HEAD"
fatal: No such ref: 'main'

    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at getFilesUsingBaseAndHead (/home/vsts/work/1/s/node_modules/nx/src/utils/command-line-utils.js:173:50)
    at parseFiles (/home/vsts/work/1/s/node_modules/nx/src/utils/command-line-utils.js:148:20)
    at projectsToRun (/home/vsts/work/1/s/node_modules/nx/src/command-line/affected.js:100:145)
    at Object.<anonymous> (/home/vsts/work/1/s/node_modules/nx/src/command-line/affected.js:29:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/1/s/node_modules/tslib/tslib.js:115:62) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 4e 6f 20 73 75 63 68 20 72 65 66 3a 20 27 6d 61 69 6e 27 0a>
  ],
  pid: 1879,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 4e 6f 20 73 75 63 68 20 72 65 66 3a 20 27 6d 61 69 6e 27 0a>
```

If I just do a standard build then that works fine, but I'd prefer to use nx affected

```
> nx run social-security:build:production

Entrypoint main [big] 2.35 MiB (280 KiB) = runtime.12da5b6d6af22930.js 2.03 KiB main.f1a36380d6358064.js 2.35 MiB 4 auxiliary assets
Entrypoint polyfills 98.5 KiB = runtime.12da5b6d6af22930.js 2.03 KiB polyfills.1a00f00808ced2c0.js 96.5 KiB
Entrypoint styles 9.09 KiB = runtime.12da5b6d6af22930.js 2.03 KiB styles.355976c4a20c2945.css 7.07 KiB
....
webpack compiled successfully (60f2289138818a02)

  >  NX   Successfully ran target build for project social-security
```

### Expected Behavior

I expect nx affected not to throw an error when run in my pipeline

### Steps to Reproduce

Not relevant

### Nx Report

```shell
PS C:\Dev\NX\monorepo> nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : win32 x64
   yarn : 1.22.19

   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.5
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
As above
```

**Comment by 72gm** [comment]
Hi @StalkAltan 

Thanks for your quick response. Sounded like a good fix to me but doesn't seem to have made any difference!

I turned it off via the classic editor but didn't seem to work... 

So I then also hardcoded it in my yaml: 
- checkout: self
   fetchDepth: 0

but again, same error

anything else I can try?

**Comment by StalkAltan** [comment]
You might also have luck going to your `nx.json`, and changing (or adding, if it doesn't exist):

```
{
  ...rest of nx.json
  "affected": {
    "defaultBase": "origin/main"
  }
}
```

If this doesn't work, can you attach your pipeline yaml and I can play with it sometime this week.

**Comment by StalkAltan** [comment]
The behavior is inconsistent across different CI platforms, so I'm not sure. Github handles `main` just fine, but Azure and Gitlab (among others) require `origin/main`.

Glad that it's working for you now. Going to close the issue!
