### ISSUE TITLE
 NX   Cannot find module 'node:fs'

### ISSUE THREAD

**Issue by boopathi-ramasamy-db** [nrwl/nx#14302]
### Current Behavior

Currently the Nx workspace is on version 10.4.15 (contains only angular projects)
Ran the below commands to upgrade to version 11.6.3,
> nx migrate 11.6.3
> npm install
> npx nx migrate --run-migrations=migrations.json
and this last command produces the error 

 >  NX   Running migrations from 'migrations.json'

 >  NX   Cannot find module 'node:fs'

   Require stack:
   - C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\@angular-devkit\core\node\host.js
   - C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\@angular-devkit\core\node\index.js

### Expected Behavior

npx nx migrate --run-migrations=migrations.json runs all migrations successfully.

### Steps to Reproduce

same as given in Current Behaviour section.

### Nx Report

```shell
>  NX  Report complete - copy this into the issue template

  Node : 12.16.1
  OS   : win32 x64
  npm  : 6.13.4

  nx : Not Found
  @nrwl/angular : 11.6.3
  @nrwl/cli : 11.6.3
  @nrwl/cypress : 11.6.3
  @nrwl/devkit : 11.6.3
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.3
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.3
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.8
```

### Failure Logs

```shell
>  NX   Running migrations from 'migrations.json'


 >  NX   Cannot find module 'node:fs'

   Require stack:
   - C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\@angular-devkit\core\node\host.js
   - C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\@angular-devkit\core\node\index.js
   - C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\nx\src\adapter\ngcli-adapter.js
   - C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\nx\src\command-line\migrate.js
   - C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\nx\src\command-line\nx-commands.js
   - C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\nx\bin\init-local.js
   - C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\nx\bin\nx.js
   - C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\@nrwl\tao\index.js
   Pass --verbose to see the stacktrace.

C:\Users\local_user\Dev\ui\proj-ui\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\LOCAL_~1\Temp\tmp-20140qm5bTf9ylEwN\node_modules\.bin\tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.handler (C:\Users\local_user\Dev\ui\proj-ui\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:80:25)
    at Object.runCommand (C:\Users\local_user\Dev\ui\proj-ui\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Users\local_user\Dev\ui\proj-ui\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\Users\local_user\Dev\ui\proj-ui\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\Users\local_user\Dev\ui\proj-ui\node_modules\@nrwl\cli\lib\init-local.js:23:13)
    at Object.<anonymous> (C:\Users\local_user\Dev\ui\proj-ui\node_modules\@nrwl\cli\bin\nx.js:42:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19356,
  stdout: null,
  stderr: null
}
```

**Comment by FrozenPandaz** [comment]
Can you try updating your version of Node to 14+ and give it another try?

**Comment by boopathi-ramasamy-db** [comment]
I tried with node v14.16.1, received same error. I tried with v16.14.0 and it worked. Thank you for the help.

**Comment by dmares01** [comment]
Can confirm I had the same issue on Node v14.15.0, change to Node v16.19.0 and the migration was successful
