### ISSUE TITLE
After a new Angular workspace has been created, nx test on this app is failing

### ISSUE THREAD

**Issue by hellraisercenobit** [nrwl/nx#14388]
### Current Behavior

`nx run xxx:test` trigger an error

### Expected Behavior

test should run has expected

### Steps to Reproduce

1. run `npx create-nx-workspace@latest --name xxx --appName xxx --preset angular-monorepo --style scss --nxCloud`
2. run `cd xxx`
3. run `nx run xxx:test`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin x64
   npm  : 8.19.3

   nx : 15.5.1
   @nrwl/angular : 15.5.1
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
nx run xxx:test --verbose

> nx run xxx:test


 >  NX   Jest: Failed to parse the TypeScript config file /Users/myuser/Projects/xxx/apps/xxx/jest.config.ts

     TSError: ⨯ Unable to compile TypeScript:
   error TS5083: Cannot read file '/tsconfig.json'.


Error: Jest: Failed to parse the TypeScript config file /Users/myuser/Projects/xxx/apps/xxx/jest.config.ts
  TSError: ⨯ Unable to compile TypeScript:
error TS5083: Cannot read file '/tsconfig.json'.

    at readConfigFileAndSetRootDir (/Users/myuser/Projects/xxx/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:136:13)
    at async readConfig (/Users/myuser/Projects/xxx/node_modules/jest-config/build/index.js:216:18)
```

### Additional Information

seems to work in another desktop.
seems to work too, when i copy tsconfig.base.json to tsconfig.json, like has  'cwd' was wrong and targeted rootDir instead of xxx app.

**Comment by barbados-clemens** [comment]
@hellraisercenobit can you provide a clone-able repo I can take a look at. I just tried the reproducible steps provided and the tests work as expected.
