### ISSUE TITLE
lerna version 6.4.1 fails due to @nrwl/devkit

### ISSUE THREAD

**Issue by ozee** [nrwl/nx#14440]
### Current Behavior

@lerna/version is throwing an error that points to @nrwl/devkit.

### Expected Behavior

That @lerna/version will properly version and release.

### Steps to Reproduce

1. Using Lerna 6.4.1, use @lerna/version to version a package.
2. It'll make call, checking the package.json and lock file
3. It'll fail because lock-file exists in the utils folder and not at src.

### Nx Report

```shell
Node : 16.17.0
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 14.8.6
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.6
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.5.5
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         lerna: 6.4.1
```

### Failure Logs

```shell
Error: Cannot find module 'nx/src/lock-file/lock-file'
Require stack:
- /home/runner/work/aileron/aileron/node_modules/@lerna/version/node_modules/@nrwl/devkit/index.js
- /home/runner/work/aileron/aileron/node_modules/@lerna/version/lib/git-add.js
- /home/runner/work/aileron/aileron/node_modules/@lerna/version/index.js
- /home/runner/work/aileron/aileron/node_modules/@lerna/publish/index.js
- /home/runner/work/aileron/aileron/node_modules/@lerna/publish/command.js
- /home/runner/work/aileron/aileron/node_modules/lerna/index.js
- /home/runner/work/aileron/aileron/node_modules/lerna/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/runner/work/aileron/aileron/node_modules/@lerna/version/node_modules/@nrwl/devkit/index.js:240:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/runner/work/aileron/aileron/node_modules/@lerna/version/lib/git-add.js:7:41)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/aileron/aileron/node_modules/@lerna/version/node_modules/@nrwl/devkit/index.js',
    '/home/runner/work/aileron/aileron/node_modules/@lerna/version/lib/git-add.js',
    '/home/runner/work/aileron/aileron/node_modules/@lerna/version/index.js',
    '/home/runner/work/aileron/aileron/node_modules/@lerna/publish/index.js',
    '/home/runner/work/aileron/aileron/node_modules/@lerna/publish/command.js',
    '/home/runner/work/aileron/aileron/node_modules/lerna/index.js',
    '/home/runner/work/aileron/aileron/node_modules/lerna/cli.js'
  ]
}
Error: Process completed with exit code 1.
```

### Additional Information

This is happening within our Github Action, I have also tried this with the latest version of nx, 15, for both nx and @nrwl/devkit.

**Comment by ozee** [comment]
I think that this is the offending line, https://github.com/nrwl/nx/blob/master/packages/devkit/index.ts#L367

**Comment by FrozenPandaz** [comment]
@meeroslav can you please take a look at this?

**Comment by jcarasick-geog8r** [comment]
Hi all, I am running into this. Is there any workaround to get this to work?

**Comment by ozee** [comment]
hey @jcarasick-geog8r I was able to get around this by updating my package.json with:

```json
{
...
  "overrides": {
    "@lerna/version": {
      "@nrwl/devkit": "14.8.6"
    }
  },
...
}
```

**Comment by meeroslav** [comment]
This has been fixed from what I can tell.

Please let me know if the error persists.
