### ISSUE TITLE
@nrwl/esbuild:esbuild throws error when additionalEntryPoints option is specified

### ISSUE THREAD

**Issue by NKNaaS** [nrwl/nx#14486]
### Current Behavior

@nrwl/esbuild:esbuild throws error when additionalEntryPoints option is specified.

### Expected Behavior

build successfully with `additionalEntryPoints` option.

### Steps to Reproduce

Build with the following options.

```
{
    "build": {
      "executor": "@nrwl/esbuild:esbuild",
      "outputs": ["{options.outputPath}"],
      "options": {
        "bundle": true,
        "thirdParty": false,
        "format": ["cjs"],
        "platform": "node",
        "target": "node16",
        "skipTypeCheck": false,
        "outputPath": "apps/main/dist",
        "additionalEntryPoints": [
          "apps/main/tgt1/index.ts",
          "apps/main/tgt2/index.ts",
          ...
        ],
        "main": "apps/main/src/main.ts",
        "tsConfig": "apps/main/tsconfig.app.json",
        "assets": ["apps/main/src/assets"]
      },
      "configurations": {
        "production": {
          "minify": true,
          "sourcemap": false
        }
      }
    }
}
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : darwin arm64
   pnpm : 7.18.1
   
   nx : 15.5.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.2
   @nrwl/esbuild : 15.5.2
   @nrwl/eslint-plugin-nx : 15.5.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.2
   @nrwl/js : 15.5.2
   @nrwl/linter : 15.5.2
   @nrwl/nest : 15.5.2
   @nrwl/next : 15.5.2
   @nrwl/node : 15.5.2
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.5.2
   @nrwl/web : 15.5.2
   @nrwl/webpack : 15.5.2
   @nrwl/workspace : 15.5.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
> nx run main:build


 >  NX   The "path" argument must be of type string. Received undefined


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)
    at joinPathFragments (/Users/path/to/this/repo/node_modules/.pnpm/nx@15.5.2_@swc+core@1.2.249/node_modules/nx/src/utils/path.js:19:31)
    at getOutfile (/Users/path/to/this/repo/node_modules/.pnpm/@nrwl+esbuild@15.5.2_xqmqlbwh2synftzx6vgjoidvma/node_modules/@nrwl/esbuild/src/executors/esbuild/lib/build-esbuild-options.js:61:52)
    at esbuildExecutor_1 (/Users/path/to/this/repo/node_modules/.pnpm/@nrwl+esbuild@15.5.2_xqmqlbwh2synftzx6vgjoidvma/node_modules/@nrwl/esbuild/src/executors/esbuild/esbuild.impl.js:143:100)
    at esbuildExecutor_1.next (<anonymous>)
    at resume (/Users/path/to/this/repo/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:230:48)
    at fulfill (/Users/path/to/this/repo/node_modules/.pnpm/tslib@2.4.1/node_modules/tslib/tslib.js:232:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ndcunningham** [comment]
Can you retry this with the latest?
I tried to reproduce your issue here: https://github.com/ndcunningham/issue-14486
