### ISSUE TITLE
SplitTargets -- Cannot read properties of undefined (reading 'nodes')

### ISSUE THREAD

**Issue by ZackTherrien** [nrwl/nx#14555]
### Current Behavior

After upgrading to Nx 15.5.3, getting the following error in the console when running a build.

```
TypeError: Cannot read properties of undefined (reading 'nodes')
    at splitTarget (/Repo/node_modules/@nrwl/webpack/node_modules/@nrwl/devkit/node_modules/nx/src/utils/split-target.js:7:51)
    at parseTargetString (/Repo/node_modules/@nrwl/webpack/node_modules/@nrwl/devkit/src/executors/parse-target-string.js:17:77)
    at getBuildOptions (/Repo/node_modules/@nrwl/webpack/src/executors/dev-server/dev-server.impl.js:52:51)
    at devServerExecutor_1 (/Repo/node_modules/@nrwl/webpack/src/executors/dev-server/dev-server.impl.js:19:72)
    at devServerExecutor_1.next (<anonymous>)
    at resume (/Repo/node_modules/tslib/tslib.js:230:48)
    at /Repo/node_modules/tslib/tslib.js:229:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (/Repo/node_modules/tslib/tslib.js:229:67)
    at /Repo/node_modules/nx/src/command-line/run.js:53:35
```

Seems to be thrown at this function:
```
function splitTarget(s, projectGraph) {
    var _a, _b;
    let [project, ...segments] = splitByColons(s);
    const validTargets = (_b = (_a = **projectGraph.nodes[project])**
```

How can the Nx project graph be undefined? Although running `nx graph` works fine. 🤔 

### Expected Behavior

Allows me to build the app.

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 16.18.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 15.5.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.3
   @nrwl/js : 15.5.3
   @nrwl/linter : 15.5.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.5.3
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.5.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.5.3
   @nrwl/vite : Not Found
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nx-extend/gcp-functions: 6.3.5
```

**Comment by jaysoo** [comment]
I wonder if there's some version mismatch issue here. Seems weird that `node_modules/@nrwl/webpack/node_modules/@nrwl/devkit` and `node_modules/@nrwl/webpack/node_modules/@nrwl/devkit/node_modules/nx` are present, rather than being in the root `node_modules` folder.

Does removing `node_modules` and re-install help? What happens if you run `yarn why nx`?
