### ISSUE TITLE
Error: no such file or directory .... project.json

### ISSUE THREAD

**Issue by amivag** [nrwl/nx#14587]
### Current Behavior

Hello,
I am trying to migrate a React CRA project into NX.
I run the command "npx nx@latest init"

But I get this error... (excerpt)

  >  NX   � Clearing unused files
```

Error: ENOENT: no such file or directory, lstat 'temp-workspace/apps/fyot_booking_page/project.json'
    at Object.lstatSync (node:fs:1574:3)
    at Object.lstatSync (C:\Users\evan\AppData\Local\npm-cache\_npx\8331ccaaf37e1499\node_modules\graceful-fs\polyfills.js:318:34)
    at statFunc (C:\Users\evan\AppData\Local\npm-cache\_npx\8331ccaaf37e1499\node_modules\fs-extra\lib\util\stat.js:24:20)
    at getStatsSync (C:\Users\evan\AppData\Local\npm-cache\_npx\8331ccaaf37e1499\node_modules\fs-extra\lib\util\stat.js:25:19)

How do I troubleshoot this?

```

### Expected Behavior

Successful migration to NX?

### Steps to Reproduce

npx nx@latest init

### Nx Report

```shell
No NX workspace created
```

**Comment by amivag** [comment]
I'm afraid this issue has not been resolved. Tried it again, nx version 15.6.2 was used, the error is still the same.
Let me know what kind of extra info I can provide for troubleshooting. Or anything else I should try.
Thanks!
