### ISSUE TITLE
pruneDependencies fails for pnpm after upgrading Nx

### ISSUE THREAD

**Issue by anogr** [nrwl/nx#14599]
### Current Behavior

After upgrading Nx from 15.2.1 to any version above 15.4, some builds fail with this error message:

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at x\node_modules\.pnpm\nx@15.6.1\node_modules\nx\src\lock-file\pnpm.js:228:31
    at Array.forEach (<anonymous>)
    at pruneDependencies (x\node_modules\.pnpm\nx@15.6.1\node_modules\nx\src\lock-file\pnpm.js:225:184)
    at prunePnpmLockFile (x\node_modules\.pnpm\nx@15.6.1\node_modules\nx\src\lock-file\pnpm.js:213:26)
    at createLockFile (x\node_modules\.pnpm\nx@15.6.1\node_modules\nx\src\lock-file\lock-file.js:152:57)

```

### Expected Behavior

We expect builds to complete without errors.

### Steps to Reproduce

1.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.17.1
   OS   : win32 x64
   pnpm : 7.16.1

   nx : 15.6.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.1
   @nrwl/expo : Not Found
   @nrwl/express : 15.6.1
   @nrwl/jest : 15.6.1
   @nrwl/js : 15.6.1
   @nrwl/linter : 15.6.1
   @nrwl/nest : Not Found
   @nrwl/next : 15.6.1
   @nrwl/node : 15.6.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.6.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.1
   @nrwl/web : 15.6.1
   @nrwl/webpack : 15.6.1
   @nrwl/workspace : 15.6.1
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by jbarmash** [comment]
May be related to https://github.com/nrwl/nx/issues/14096

**Comment by meeroslav** [comment]
This is fixed by https://github.com/nrwl/nx/pull/13864
