### ISSUE TITLE
Cypress E2E "Cannot read property 'baseUrl' of undefined" after upgrade to 15.6.1

### ISSUE THREAD

**Issue by Nick-Lucas** [nrwl/nx#14601]
### Current Behavior

When starting Cypress E2E tests for a React frontend, the process fails with:

```
TypeError: Cannot read property 'baseUrl' of undefined
    at startDevServer_1 (/home/nick/dev/application-monorepo/node_modules/@nrwl/cypress/src/executors/cypress/cypress.impl.js:131:34)
    at startDevServer_1.next (<anonymous>)
    at resume (/home/nick/dev/application-monorepo/node_modules/tslib/tslib.js:230:48)
    at fulfill (/home/nick/dev/application-monorepo/node_modules/tslib/tslib.js:232:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This appears to be an error in the Cypress Executor accessing `output.info`

Cypress config is:

```ts
import { defineConfig } from 'cypress'
import { nxE2EPreset } from '@nrwl/cypress/plugins/cypress-preset'

const cypressJsonConfig: Parameters<typeof defineConfig>[number]['e2e'] = {
  baseUrl: 'http://localhost:4202',
  viewportHeight: 1080,
  viewportWidth: 1920,
  fileServerFolder: '.',
  fixturesFolder: './src/fixtures',
  video: true,
  videosFolder: '../../../dist/cypress/apps/gss-toolkit/frontend-e2e/videos',
  screenshotsFolder:
    '../../../dist/cypress/apps/gss-toolkit/frontend-e2e/screenshots',
  chromeWebSecurity: false,
  defaultCommandTimeout: 60000,
  requestTimeout: 60000,
  retries: {
    runMode: 2,
    openMode: 0,
  },
  specPattern: 'src/e2e/**/*.cy.{js,jsx,ts,tsx}',
  supportFile: 'src/support/e2e.ts',
}
export default defineConfig({
  e2e: {
    ...nxE2EPreset(__dirname),
    ...cypressJsonConfig,
  },
})
  
```

### Expected Behavior

Cypress starts

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 14.21.2
   OS   : linux x64
   yarn : 1.22.19
   
   nx : 15.6.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.1
   @nrwl/js : 15.6.1
   @nrwl/linter : 15.6.1
   @nrwl/nest : 15.6.1
   @nrwl/next : Not Found
   @nrwl/node : 15.6.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.6.1
   @nrwl/react : 15.6.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.6.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.6.1
   @nrwl/webpack : 15.6.1
   @nrwl/workspace : 15.6.1
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
yarn run v1.22.19
$ yarn run nx e2e gss-toolkit-frontend-e2e --watch --browser=electron --verbose
$ nx e2e gss-toolkit-frontend-e2e --watch --browser=electron --verbose

> nx run gss-toolkit-frontend-e2e:e2e --watch --browser=electron

> nx run gss-toolkit-frontend:serve:development
> nx run gss-toolkit-api:serve
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:4202/, http://127.0.0.1:4202/
<i> [webpack-dev-server] 404s will fallback to '/index.html'
>  NX  Web Development Server is listening at http://localhost:4202/
asset main.js 1.11 MiB [emitted] [big] (name: main) 1 related asset
asset assets/.gitkeep 0 bytes [emitted] [from: apps/gss-toolkit/api/src/assets/.gitkeep] [copied]
cacheable modules 1.08 MiB
  modules by path ./libs/common/ 134 KiB
    modules by path ./libs/common/gss/src/ 110 KiB 47 modules
    modules by path ./libs/common/gss-zod/src/ 24.5 KiB
      ./libs/common/gss-zod/src/index.ts 866 bytes [built] [code generated]
      + 13 modules
  modules by path ./apps/gss-toolkit/api/src/ 972 KiB 44 modules
modules by path external "@aws-sdk/ 126 bytes
  external "@aws-sdk/client-secrets-manager" 42 bytes [built] [code generated]
  external "@aws-sdk/client-s3" 42 bytes [built] [code generated]
  external "@aws-sdk/s3-request-presigner" 42 bytes [built] [code generated]
modules by path external "@trpc/ 84 bytes
  external "@trpc/server/adapters/standalone" 42 bytes [built] [code generated]
  external "@trpc/server" 42 bytes [built] [code generated]
+ 11 modules
webpack 5.75.0 compiled successfully in 3991 ms
Debugger listening on ws://localhost:9229/38dc5155-38e2-4598-8050-ceedc0cd9de4
For help, see: https://nodejs.org/en/docs/inspector
Type-checking in progress...
Listening on 3334
Playground serving on http://localhost:33342/
No errors found.
 >  NX   Cannot read property 'baseUrl' of undefined
TypeError: Cannot read property 'baseUrl' of undefined
    at startDevServer_1 (/home/nick/dev/application-monorepo/node_modules/@nrwl/cypress/src/executors/cypress/cypress.impl.js:131:34)
    at startDevServer_1.next (<anonymous>)
    at resume (/home/nick/dev/application-monorepo/node_modules/tslib/tslib.js:230:48)
    at fulfill (/home/nick/dev/application-monorepo/node_modules/tslib/tslib.js:232:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target e2e for project gss-toolkit-frontend-e2e failed

   Failed tasks:
   
   - gss-toolkit-frontend-e2e:e2e
   
   Hint: run the command with --verbose for more details.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mandarini** [comment]
PR #14598 fixes this issue
