### ISSUE TITLE
ng serve --aot - causes "cannot find node_modules/@nrwl/builders/src/builders.json'"

### ISSUE THREAD

**Issue by appsolutegeek** [nrwl/nx#1470]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Current Behavior

Running ng serve with the --aot option gives the following error

```
➜  test git:(setting_up_project) ✗ ng serve --aot          
Cannot find module '/Users/ian/Development/Personal/typescript/test/node_modules/@nrwl/builders/src/builders.json'
Error: Cannot find module '/Users/ian/Development/Personal/typescript/test/node_modules/@nrwl/builders/src/builders.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (/Users/ian/Development/Personal/typescript/test/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:42:29)
    at ServeCommand.initialize (/Users/ian/Development/Personal/typescript/test/node_modules/@angular/cli/models/architect-command.js:72:63)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

```

```
    "@nrwl/builders": "8.0.2",
    "@nrwl/schematics": "^8.1.0",

```
## Expected Behavior

Being able to call ng serve passing --aot

### Context

Please provide any relevant information about your setup:

- version of Nx 8
- version of Angular CLI8

## Other

Any other relevant information that will help us help you.

**Comment by appsolutegeek** [comment]
Here is some more info, this is from a project that uses ```    "@nrwl/builders": "7.8.6", ```, you will notice the builder.json

![image](https://user-images.githubusercontent.com/2370364/59101493-6e609a80-8929-11e9-89fd-3db62724012a.png)

and this is from my project that uses ```    "@nrwl/builders": "8.0.2", ```, there is no builders.json 

![image](https://user-images.githubusercontent.com/2370364/59101558-a10a9300-8929-11e9-9d97-e388246c6385.png)

Help :-)

**Comment by appsolutegeek** [comment]
Ok, noticed there is a migration guide.

**Comment by bostondevin** [comment]
I have the same issue - where did you find the guide?

> Ok, noticed there is a migration guide.

I have the same issue - where did you find the guide?
