### ISSUE TITLE
Expo: Tests fail after upgrade to NX 15

### ISSUE THREAD

**Issue by ukch** [nrwl/nx#14704]
### Current Behavior

The removal of the `jest-expo` preset in the latest upgrade is causing tests to fail when an expo module such as 'expo-notifications' is used. The following errors are shown:

```
> nx run jest-expo-reproduce:test

  console.warn
    The "EXNativeModulesProxy" native module is not exported through NativeModules; verify that expo-modules-core's native code is linked properly

      at Object.<anonymous> (../../node_modules/expo-modules-core/src/NativeModulesProxy.native.ts:71:11)

  console.warn
    No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?

      at Object.<anonymous> (../../node_modules/expo-constants/src/Constants.ts:33:11)

 FAIL   jest-expo-reproduce  apps/jest-expo-reproduce/src/app/App.spec.tsx
  ● Test suite failed to run

    TypeError: Cannot read property '__expo_module_name__' of undefined

      at new EventEmitter (../../node_modules/expo-modules-core/src/EventEmitter.ts:32:22)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.586 s
Ran all test suites.

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project jest-expo-reproduce (2s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

```

### Expected Behavior

It should be possible to import expo modules from test code without errors occurring

### GitHub Repo

https://github.com/ukch/jest-expo-reproduce

### Steps to Reproduce

1. (on `master` branch) run tests: all tests pass
2. Switch to branch `upgrade/nx-15.6.3` and do `npm install`. Alternatively perform the migration manually:
   * `nx migrate latest`
   * `npm install`
   * `nx migrate --run-migrations --create-commits`
   * `expo-cli doctor --fix-dependencies`
3. Run tests again (`nx test jest-expo-reproduce`)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 14.19.1
   OS   : linux x64
   npm  : 8.16.0
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.3
   @nrwl/detox : 15.6.3
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : 15.6.3
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.6.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.6.3
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
> nx run jest-expo-reproduce:test

  console.warn
    The "EXNativeModulesProxy" native module is not exported through NativeModules; verify that expo-modules-core's native code is linked properly

      at Object.<anonymous> (../../node_modules/expo-modules-core/src/NativeModulesProxy.native.ts:71:11)

  console.warn
    No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?

      at Object.<anonymous> (../../node_modules/expo-constants/src/Constants.ts:33:11)

 FAIL   jest-expo-reproduce  apps/jest-expo-reproduce/src/app/App.spec.tsx
  ● Test suite failed to run

    TypeError: Cannot read property '__expo_module_name__' of undefined

      at new EventEmitter (../../node_modules/expo-modules-core/src/EventEmitter.ts:32:22)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.586 s
Ran all test suites.

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project jest-expo-reproduce (2s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

```
```


### Additional Information

_No response_

**Comment by xiongemi** [comment]
this possibly could be fixed in https://github.com/nrwl/nx/pull/16504. i added preset:jest-expo back in for jest.config.

**Comment by xiongemi** [comment]
closing this issue for now.
