### ISSUE TITLE
Angular Standalone install with wrong typescript version

### ISSUE THREAD

**Issue by d3473r** [nrwl/nx#14748]
### Current Behavior

After creating a angular standalone workspace and trying to add angular material the following error is thrown:

```
 >  NX   Cannot read properties of undefined (reading 'kind')
```

Upgrading typescript from `4.8.4` to `4.9.5` fixes the issue

### Expected Behavior

Nx should install the correct typescript version on workspace initialization.

### Steps to Reproduce

1. `npx create-nx-workspace@latest`
2. `npm install @angular/material && npx nx g @angular/material:ng-add`

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin arm64
   npm  : 8.19.2

   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
➜  test git:(main) npm install @angular/material && npx nx g @angular/material:ng-add

added 55 packages, and audited 1523 packages in 11s

175 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

>  NX  Generating @angular/material:ng-add

✔ Choose a prebuilt theme name, or "custom" for a custom theme: · indigo-pink
✔ Set up global Angular Material typography styles? (y/N) · false
✔ Include the Angular animations module? · enabled
✔ Packages installed successfully.
TypeError: Cannot read properties of undefined (reading 'kind')
    at _angularImportsFromNode (xxx/test/node_modules/@schematics/angular/utility/ast-utils.js:196:16)
    at xxx/test/node_modules/@schematics/angular/utility/ast-utils.js:239:24
    at Array.map (<anonymous>)
    at getDecoratorMetadata (xxx/test/node_modules/@schematics/angular/utility/ast-utils.js:239:10)
    at addSymbolToNgModuleMetadata (xxx/test/node_modules/@schematics/angular/utility/ast-utils.js:285:19)
    at addImportToModule (xxx/test/node_modules/@schematics/angular/utility/ast-utils.js:384:12)
    at addModuleImportToModule (xxx/test/node_modules/@angular/cdk/schematics/utils/ast.js:46:55)
    at addModuleImportToRootModule (xxx/test/node_modules/@angular/cdk/schematics/utils/ast.js:31:5)
    at addAnimationsModuleToNonStandaloneApp (xxx/test/node_modules/@angular/material/schematics/ng-add/setup-project.js:111:58)
    at xxx/test/node_modules/@angular/material/schematics/ng-add/setup-project.js:58:13

 >  NX   Cannot read properties of undefined (reading 'kind')

   Pass --verbose to see the stacktrace.
```

### Additional Information

Upgrading typescript from `4.8.4` to `4.9.5` fixes the issue

**Comment by danielmhair** [comment]
Thank you @d3473r! Upgrading typescript to 4.9.5 did it for me too!

**Comment by Coly010** [comment]
Hi @d3473r and @danielmhair !

We are aware of this, however, it results from an issue in Angular Material itself.

Angular 15 is supposed to support 4.8.2 <= TS <= 4.9.5

However, there is an issue in the AST Utils for Angular Material where they only support TS 4.9.5.

I created an issue on the Angular Material repo: https://github.com/angular/components/issues/26540

**Comment by Coly010** [comment]
As this issue stems from the Angular Material package, I'm going to close this issue. We should follow along with the issue I have linked above.
