### ISSUE TITLE
npx nx init fails at make-angular-cli-faster@latest init

### ISSUE THREAD

**Issue by boaz-yaari-arad** [nrwl/nx#14804]
### Current Behavior

When run the command:  `npx nx init` in a angular  cli project I get the following error:

```
Error: Command failed: npx --yes make-angular-cli-faster@latest init
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at Object.<anonymous> (C:\Code\harmony-encore-fe\node_modules\@nrwl\cli\node_modules\nx\src\command-line\init.js:22:46)
    at Generator.next (<anonymous>)
    at C:\Code\harmony-encore-fe\node_modules\tslib\tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Code\harmony-encore-fe\node_modules\tslib\tslib.js:163:16)
    at Object.initHandler (C:\Code\harmony-encore-fe\node_modules\@nrwl\cli\node_modules\nx\src\command-line\init.js:12:20)
    at C:\Code\harmony-encore-fe\node_modules\@nrwl\cli\node_modules\nx\src\command-line\nx-commands.js:207:71
    at Generator.next (<anonymous>) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10148,
  stdout: null,
```

### Expected Behavior

Command will run without any errors

### Steps to Reproduce

1. Run:  npx nx init

### Nx Report

```shell
PS C:\Code\harmony-encore-fe> npx nx init
nx.js init

Adds nx.json file and installs nx if not installed already

Options:
  --help     Show help                                                                                         [boolean]  --version  Show version number                                                                               [boolean]
Error: Command failed: npx --yes make-angular-cli-faster@latest init
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at Object.<anonymous> (C:\Code\harmony-encore-fe\node_modules\@nrwl\cli\node_modules\nx\src\command-line\init.js:22:46)
    at Generator.next (<anonymous>)
    at C:\Code\harmony-encore-fe\node_modules\tslib\tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Code\harmony-encore-fe\node_modules\tslib\tslib.js:163:16)
    at Object.initHandler (C:\Code\harmony-encore-fe\node_modules\@nrwl\cli\node_modules\nx\src\command-line\init.js:12:20)
    at C:\Code\harmony-encore-fe\node_modules\@nrwl\cli\node_modules\nx\src\command-line\nx-commands.js:207:71
    at Generator.next (<anonymous>) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10148,
  stdout: null,
  stderr: null
}
```

### Failure Logs

```shell
PS C:\Code\harmony-encore-fe> npx nx init
nx.js init

Adds nx.json file and installs nx if not installed already

Options:
  --help     Show help                                                                                         [boolean]  --version  Show version number                                                                               [boolean]
Error: Command failed: npx --yes make-angular-cli-faster@latest init
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at Object.<anonymous> (C:\Code\harmony-encore-fe\node_modules\@nrwl\cli\node_modules\nx\src\command-line\init.js:22:46)
    at Generator.next (<anonymous>)
    at C:\Code\harmony-encore-fe\node_modules\tslib\tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Code\harmony-encore-fe\node_modules\tslib\tslib.js:163:16)
    at Object.initHandler (C:\Code\harmony-encore-fe\node_modules\@nrwl\cli\node_modules\nx\src\command-line\init.js:12:20)
    at C:\Code\harmony-encore-fe\node_modules\@nrwl\cli\node_modules\nx\src\command-line\nx-commands.js:207:71
    at Generator.next (<anonymous>) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10148,
  stdout: null,
  stderr: null
}
```

**Comment by Coly010** [comment]
I couldn't reproduce this.

Can you

- Delete your npx cache (`rm -rf ~/.npm/_npx`) and try again
- Provide a repo containing the angular cli workspace you want to init nx in
