### ISSUE TITLE
standalone nxcloud get socket hang up when trigger jobs run

### ISSUE THREAD

**Issue by loo2k** [nrwl/nx#14939]
### Current Behavior

I'm running a local [standalone nxcloud server](https://nx.dev/nx-cloud/private-cloud/standalone) and configure accessToken.

But it can not correct send request to my standalone nxcloud server when i try to test Distributed Caching.

> logs below

### Expected Behavior

NO `ECONNABORTED` ERRORS.

### Steps to Reproduce

1. RUN standalone nxcloud

```
docker run -d --name nxcloud \
        -e NX_CLOUD_APP_URL=http://example.com
	-e ADMIN_PASSWORD=admin \
        -e NX_VERBOSE_LOGGING=true
        -e NX_API_LOG_LEVEL=DEBUG
	-v ./:data \
        -p 8081:8081
        nxprivatecloud/nxcloud:latest
```

2. RUN nx-cloud init command

```
NX_CLOUD_API=http://example.com npx nx g @nrwl/nx-cloud:init
```

3. configure accessToken in standalone nxcloud

4. run build task test

```
NX_BRANCH=testing npx nx run jssdk:build --verbose
```

5. clear local cache

```
npx nx clear-cache
```

6. rebuild task

```
npx nx run jssdk:build --verbose
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin arm64
   pnpm : 7.19.0
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : 15.6.3
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```
```


### Failure Logs

```shell
## Logs from docker container


nxcloud    | 2023-02-12T11:49:37.887Z cloud-proxy: Delegating to nx-api (POST /nx-cloud/runs/start)
nxcloud    | 2023-02-12T11:49:37.910Z cloud-proxy: Delegating to nx-api (POST /nx-cloud/runs/end)
nxcloud    | error Error: socket hang up
nxcloud    |     at connResetException (internal/errors.js:639:14)
nxcloud    |     at Socket.socketCloseListener (_http_client.js:449:25)
nxcloud    |     at Socket.emit (events.js:412:35)
nxcloud    |     at TCP.<anonymous> (net.js:686:12) {
nxcloud    |   code: 'ECONNRESET'
nxcloud    | }
nxcloud    | error Error: socket hang up
nxcloud    |     at connResetException (internal/errors.js:639:14)
nxcloud    |     at Socket.socketCloseListener (_http_client.js:449:25)
nxcloud    |     at Socket.emit (events.js:412:35)
nxcloud    |     at TCP.<anonymous> (net.js:686:12) {
nxcloud    |   code: 'ECONNRESET'
nxcloud    | }
nxcloud    | 2023-02-12T11:49:54.426Z cloud-proxy: Delegating to nx-api (POST /nx-cloud/runs/end)
nxcloud    | 2023-02-12T11:49:58.613Z cloud-proxy: Delegating to nx-api (POST /nx-cloud/runs/start)
nxcloud    | error Error: socket hang up
nxcloud    |     at connResetException (internal/errors.js:639:14)
nxcloud    |     at Socket.socketCloseListener (_http_client.js:449:25)
nxcloud    |     at Socket.emit (events.js:412:35)
nxcloud    |     at TCP.<anonymous> (net.js:686:12) {
nxcloud    |   code: 'ECONNRESET'
nxcloud    | }
nxcloud    | error Error: socket hang up
nxcloud    |     at connResetException (internal/errors.js:639:14)
nxcloud    |     at Socket.socketCloseListener (_http_client.js:449:25)
nxcloud    |     at Socket.emit (events.js:412:35)
nxcloud    |     at TCP.<anonymous> (net.js:686:12) {
nxcloud    |   code: 'ECONNRESET'
nxcloud    | }
```

## Logs by running `nx build jssdk --verbose`

```

 >  NX   RunStart

   
{
  "meta": {},
  "branch": null,
  "runGroup": "bff372b411e457a7773c806f35d915815eadb0c8",
  "hashes": [
    "2f4beddf2d45fbe061c0d4546fe679b21e45f5e57af65ed2043be306d096a525"
  ]
}


> nx run jssdk:build  [existing outputs match the cache, left as is]
 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project jssdk

   Nx read the output from the cache instead of running the command for 1 out of 1 tasks.


 >  NX   RunEnd. Completed tasks

   
[
  {
    "taskId": "jssdk:build",
    "startTime": "2023-02-12T11:49:37.792Z",
    "target": "build",
    "projectName": "jssdk",
    "hash": "2f4beddf2d45fbe061c0d4546fe679b21e45f5e57af65ed2043be306d096a525",
    "hashDetails": {
      "nodes": {
        "jssdk:{projectRoot}/**/*": "ce58888e395653732a7f395a514eb3af448fcd6878dbbf761b55ba121f3d4da7",
        "{workspaceRoot}/nx.json": "3dd754b488456260605c13b4e7695d5e94ca49eb6a54c6006e7c1ae4aa91fbf7",
        "{workspaceRoot}/.gitignore": "703d2a29f88cd20de31d6312e6f37905e4155117c6ac2c7a6ce4027618a3021c",
        "{workspaceRoot}/.nxignore": "89a7dc80e347925879352a7962ae62bb9eb294e16b86c99f5df19ab12f2f4e07",
        "jssdk": "nx:run-script"
      },
      "runtime": {},
      "implicitDeps": {}
    },
    "params": "",
    "endTime": "2023-02-12T11:49:37.836Z",
    "status": 0,
    "cacheStatus": "local-cache-hit",
    "terminalOutput": "\n> jssdk@1.0.10 buil..."
  }
]


 >  NX   Received ECONNABORTED. Retrying in 10718.084201428725ms.


 >  NX   Received ECONNABORTED. Retrying in 6509.318713418065ms.


 >  NX   Nx Cloud Problems

   - Cannot connect to Nx Cloud (scope: api, code: ECONNABORTED). Try invoking the command with the NX_CLOUD_NO_TIMEOUTS env variable set to 'true'.
```

## Logs by running `NX_CLOUD_NO_TIMEOUTS=true npx nx build jssdk --verbose`

pending in here without more info
```
 >  NX   RunStart

   
{
  "meta": {},
  "branch": null,
  "runGroup": "bff372b411e457a7773c806f35d915815eadb0c8",
  "hashes": [
    "dd2564f869cacbb3642abd735dd4636e975de4959b0ae9f033e927696ea893ce"
  ]
}
```
```


### Additional Information

_No response_

**Comment by StalkAltan** [comment]
Hi @loo2k !

Unfortunately, at this time we only support private installations through our Nx Enterprise program. You can find additional info about that here ( https://nx.app/enterprise/ ) if you or your org are interested!
