### ISSUE TITLE
Migrate @nrwl/storybook

### ISSUE THREAD

**Issue by Khaldor48** [nrwl/nx#15005]
### Current Behavior

When trying to migrate to v15.7.0 after running `nx migrate --run-migrations` I got error when trying to update `@angular/cdk` like was said in issue [Issue 14990](https://github.com/nrwl/nx/issues/14990). After I try to run this command again I got stuck on error 

`>  NX   Failed to run update-15-7-0 from @nrwl/storybook. This workspace is NOT up to date!
 >  NX   Cannot read properties of undefined (reading 'parent')`

Stacktrace:

`
TypeError: Cannot read properties of undefined (reading 'parent')
    at traverse (C:\www\verzuz-fe\node_modules\@phenomnomnominal\tsquery\dist\src\traverse.js:44:38)
    at Object.traverseChildren (C:\www\verzuz-fe\node_modules\@phenomnomnominal\tsquery\dist\src\traverse.js:29:5)
    at Object.match (C:\www\verzuz-fe\node_modules\@phenomnomnominal\tsquery\dist\src\match.js:11:16)
    at Function.query (C:\www\verzuz-fe\node_modules\@phenomnomnominal\tsquery\dist\src\query.js:11:20)
    at removeStoriesArrayFromRootIfEmpty (C:\www\verzuz-fe\node_modules\@nrwl\storybook\src\migrations\update-15-7-0\add-addon-essentials-to-all.js:225:50)   
    at C:\www\verzuz-fe\node_modules\@nrwl\storybook\src\migrations\update-15-7-0\add-addon-essentials-to-all.js:47:41
    at Generator.next (<anonymous>)
    at C:\www\verzuz-fe\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\www\verzuz-fe\node_modules\tslib\tslib.js:114:16)
`

This problem is related to root directory `./storybook/main.js` as it tries to remove empty `stories` array from config

`module.exports = {
  addons: ['storybook-addon-mock', 'storybook-addon-angular-router'],
  ...,
  stories: [],
  ...
`

Empty array was removed during first `nx migrate --run-migrations` and when you want to perform this action for second time, it cannot find that empty array, so it throws this error.

Temporary solution is adding manually `stories: []` to main config before run `nx migrate --run-migrations`

### Expected Behavior

Adding conditional logic to skip this unnecessary action, when it was already done or the array is missing.

### Steps to Reproduce

1. remove line `stories: []` from `.storybook/main.js` 
2. run `nx migrate latest` you want to target v.15.7.0
3. run `nx migrate --run-migrations`  

### Nx Report

```shell
Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   npm  : 8.19.2

   nx                      : 15.7.0
   @nrwl/jest              : 15.7.0
   @nrwl/linter            : 15.7.0
   @nrwl/workspace         : 15.7.0
   @nrwl/angular           : 15.7.0
   @nrwl/cli               : 15.7.0
   @nrwl/cypress           : 15.7.0
   @nrwl/devkit            : 15.7.0
   @nrwl/eslint-plugin-nx  : 15.7.0
   @nrwl/js                : 15.7.0
   @nrwl/rollup            : 15.7.0
   @nrwl/storybook         : 15.7.0
   @nrwl/tao               : 15.7.0
   @nrwl/web               : 15.7.0
   @nrwl/webpack           : 15.7.0
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   ngx-spec           : 2.1.5
   @storybook/angular : 6.5.15
   ng-mocks           : 14.4.0
```

**Comment by vire** [comment]
I'm having this issue even with `15.7.1`

```
Ran update-15.4.6 from @nrwl/storybook
  Refactor the Storybook target options

  UPDATE libs/ui-components/project.json
---------------------------------------------------------

 >  NX   Failed to run update-15-7-0 from @nrwl/storybook. This workspace is NOT up to date!


 >  NX   Cannot read properties of undefined (reading 'parent')


TypeError: Cannot read properties of undefined (reading 'parent')
    at traverse (/path/to/repo/.yarn/__virtual__/@phenomnomnominal-tsquery-virtual-405127bc67/0/cache/@phenomnomnominal-tsquery-npm-4.1.1-59375c0c5f-64eb6d90aa.zip/node_modules/@phenomnomnominal/tsquery/dist/src/traverse.js:44:38)
    at Object.traverseChildren (/path/to/repo/.yarn/__virtual__/@phenomnomnominal-tsquery-virtual-405127bc67/0/cache/@phenomnomnominal-tsquery-npm-4.1.1-59375c0c5f-64eb6d90aa.zip/node_modules/@phenomnomnominal/tsquery/dist/src/traverse.js:29:5)
    at Object.match (/path/to/repo/.yarn/__virtual__/@phenomnomnominal-tsquery-virtual-405127bc67/0/cache/@phenomnomnominal-tsquery-npm-4.1.1-59375c0c5f-64eb6d90aa.zip/node_modules/@phenomnomnominal/tsquery/dist/src/match.js:11:16)
    at Function.query (/path/to/repo/.yarn/__virtual__/@phenomnomnominal-tsquery-virtual-405127bc67/0/cache/@phenomnomnominal-tsquery-npm-4.1.1-59375c0c5f-64eb6d90aa.zip/node_modules/@phenomnomnominal/tsquery/dist/src/query.js:11:20)
    at removeStoriesArrayFromRootIfEmpty (/path/to/repo/.yarn/cache/@nrwl-storybook-npm-15.7.1-8a4ae30b74-0e961c08b7.zip/node_modules/@nrwl/storybook/src/migrations/update-15-7-0/add-addon-essentials-to-all.js:225:50)
    at /path/to/repo/.yarn/cache/@nrwl-storybook-npm-15.7.1-8a4ae30b74-0e961c08b7.zip/node_modules/@nrwl/storybook/src/migrations/update-15-7-0/add-addon-essentials-to-all.js:47:41
    at Generator.next (<anonymous>)
    at /path/to/repo/.yarn/cache/tslib-npm-2.4.1-36f0ed04db-19480d6e03.zip/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/path/to/repo/.yarn/cache/tslib-npm-2.4.1-36f0ed04db-19480d6e03.zip/node_modules/tslib/tslib.js:114:16)
Command failed: yarn exec nx _migrate --run-migrations --verbose
```
