### ISSUE TITLE
Unable to migrate from NX 10.1.0 to 10.4.15 (First step in migrating to latest)

### ISSUE THREAD

**Issue by frobean** [nrwl/nx#15022]
### Current Behavior

NX migration fails with these error messages when trying to migrate from 10.1.0 to 10.4.15
Unable to read angular.json
Error: Cannot find module 'typescript'

### Expected Behavior

Migration completes without errors

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. npx create-nx-workspace@10.1.0 --preset=react
2. name workspace testws
3. name app testapp
4. default stylesheet format (doesn't matter, I chose CSS)
5. don't use cloud
6. cd into new testws workspace
7. run npx nx migrate 10.4.15
8. run npm install (may need to add --force depending on your npm version)
9. run npx nx migrate --run-migrations=migrations.json
10. watch the migration explode

### Nx Report

```shell
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.4.15
  @nrwl/cypress : 10.4.15
  @nrwl/eslint-plugin-nx : 10.4.15
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.15
  @nrwl/linter : 10.4.15
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.4.15
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.15
  @nrwl/web : 10.4.15
  @nrwl/workspace : 10.4.15
  typescript : 4.0.8
```

### Failure Logs

```shell
>  NX   Running migrations from 'migrations.json'

Ran add-cli-dependency from @nrwl/workspace
  Add @nrwl/cli as dependency

  UPDATE package.json
---------------------------------------------------------
Ran update-10-3-0 from @nrwl/workspace
  Update typescript to v4

  UPDATE package.json
---------------------------------------------------------
Unable to read angular.json
Error: Cannot find module 'typescript'
Require stack:
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-dependencies/index.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-project-graph.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/project-graph.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/file-utils.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/generators/utils/nx-json.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/generators/utils/project-configuration.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/adapter/ngcli-adapter.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/command-line/migrate.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/command-line/nx-commands.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/bin/init-local.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/bin/nx.js
- /private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/@nrwl/tao/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at Module.require (/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/adapter/compat.js:35:40)
    at require (node:internal/modules/cjs/helpers:103:18)
    at new TypeScriptImportLocator (/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js:11:20)
    at buildExplicitTypeScriptDependencies (/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js:11:27)
    at buildExplicitTypescriptAndPackageJsonDependencies (/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-dependencies/build-explicit-typescript-and-package-json-dependencies.js:10:98)
    at buildExplicitDependenciesWithoutWorkers (/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-project-graph.js:190:117)
    at buildExplicitDependencies (/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-project-graph.js:147:16) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-dependencies/typescript-import-locator.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-dependencies/explicit-project-dependencies.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-dependencies/index.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/build-project-graph.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/project-graph.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/project-graph/file-utils.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/generators/utils/nx-json.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/generators/utils/project-configuration.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/adapter/ngcli-adapter.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/command-line/migrate.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/src/command-line/nx-commands.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/bin/init-local.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/nx/bin/nx.js',
    '/private/var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/@nrwl/tao/index.js'
  ]
}
/Users/howard/workspace/nxpoo/testws/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/n8/ctrhv2n15hz30v2pzp7vpym0n1lb23/T/tmp-93253SPswTc2uAuO1/node_modules/.bin/tao migrate --run-migrations=migrations.json
    at checkExecSyncError (node:child_process:861:11)
    at Object.execSync (node:child_process:932:15)
    at Object.handler (/Users/howard/workspace/nxpoo/testws/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:78:25)
    at Object.runCommand (/Users/howard/workspace/nxpoo/testws/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/howard/workspace/nxpoo/testws/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/howard/workspace/nxpoo/testws/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/howard/workspace/nxpoo/testws/node_modules/@nrwl/cli/lib/init-local.js:24:13)
    at Object.<anonymous> (/Users/howard/workspace/nxpoo/testws/node_modules/@nrwl/cli/bin/nx.js:40:18)
    at Module._compile (node:internal/modules/cjs/loader:1165:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 93266,
  stdout: null,
  stderr: null
}
```

### Additional Information

I've been working on a project to update a rather large code repo from 10.1.0 to 13.latest.  I have the upgrade scripted and have been doing test runs to prepare for running this during the maintenance window set aside for it this week.  This was working up until yesterday (Feb 14) when it started failing with errors about being unable to find typescript (can be worked around by installing typescript into the root of the temp folder so that node can find it when running the migration) and another error about being unable to read angular.json

**Comment by frobean** [comment]
Update: Using latest resolves the "Unable to read angular.json" error, but the "Error: Cannot find module 'typescript'" error persists.  As a workaround, I can install typescript into the temp folder and get the migration to finish.
