### ISSUE TITLE
Local plugin "Unable to compile TypeScript" error with ts-node (without swc)

### ISSUE THREAD

**Issue by forivall** [nrwl/nx#15038]
### Current Behavior

While https://github.com/nrwl/nx/issues/9823 is solved (by https://github.com/nrwl/nx/pull/14995), in my workspace without swc and relying on ts-node instead, I'm getting a new error (see below _Failure Logs_)

### Expected Behavior

The executor should successfully run, as it does when swc is installed:

```
» nx run demo:build

> nx run demo:build

Executor ran for Build {}

 —————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project demo (378ms)
```

### GitHub Repo

https://github.com/forivall/nx-repro-local-plugin-issue-without-swc

### Steps to Reproduce

1. `npm install`
2. `npx nx run demo:build --verbose`

### Nx Report

```shell
Node : 16.17.0
OS   : darwin arm64
npm  : 8.15.0

nx                      : 15.7.1
@nrwl/jest              : 15.7.1
@nrwl/linter            : 15.7.1
@nrwl/workspace         : 15.7.1
@nrwl/cli               : 15.7.1
@nrwl/devkit            : 15.7.1
@nrwl/eslint-plugin-nx  : 15.7.1
@nrwl/js                : 15.7.1
@nrwl/nx-plugin         : 15.7.1
@nrwl/tao               : 15.7.1
typescript              : 4.8.4
---------------------------------------
Local workspace plugins:
 @repro-local-plugin-issue/repro
```

### Failure Logs

```shell
» nx run demo:build --verbose

> nx run demo:build

 >  NX   ⨯ Unable to compile TypeScript:
   error TS5024: Compiler option 'module' requires a value of type string.
   error TS5024: Compiler option 'target' requires a value of type string.

TSError: ⨯ Unable to compile TypeScript:
error TS5024: Compiler option 'module' requires a value of type string.
error TS5024: Compiler option 'target' requires a value of type string.
    at createTSError (/Users/emily.klassen/code/sandbox/repro-local-plugin-issue/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/emily.klassen/code/sandbox/repro-local-plugin-issue/node_modules/ts-node/src/index.ts:863:19)
    at createFromPreloadedConfig (/Users/emily.klassen/code/sandbox/repro-local-plugin-issue/node_modules/ts-node/src/index.ts:874:36)
    at create (/Users/emily.klassen/code/sandbox/repro-local-plugin-issue/node_modules/ts-node/src/index.ts:624:10)
    at register (/Users/emily.klassen/code/sandbox/repro-local-plugin-issue/node_modules/ts-node/src/index.ts:591:15)
    at registerTranspiler (/Users/emily.klassen/code/sandbox/packages/nx/src/utils/register.ts:64:25)
    at registerTranspiler (/Users/emily.klassen/code/sandbox/packages/nx/src/utils/register.ts:78:12)
    at registerPluginTSTranspiler (/Users/emily.klassen/code/sandbox/packages/nx/src/utils/nx-plugin.ts:194:23)
    at /Users/emily.klassen/code/sandbox/packages/nx/src/config/workspaces.ts:326:35
    at /Users/emily.klassen/code/sandbox/packages/nx/src/command-line/run.ts:189:28

 ————————————————————————————————————————————————————————————————————————————

 >  NX   Running target build for project demo failed

   Failed tasks:

   - demo:build

   Hint: run the command with --verbose for more details.
```

**Comment by yharaskrik** [comment]
Also seeing this across all our custom executors

**Comment by yharaskrik** [comment]
`nx-plugin.ts` lines 196,197 are using enum values from TS but those are numbers not strings which are not valid values for the `module` and `target` options when registering a TS project.

**Comment by AgentEnder** [comment]
Yeah, that does seem to be the case. Thanks for the investigation!
