### ISSUE TITLE
Regression: Local Plugins do not work after 15.7.0

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#15081]
### Current Behavior

Running local executor like: 

https://github.com/Bielik20/nx-plugins/blob/341010873a9408e92d14789b5668a7ed76441ce9/packages/nx-npm/project.json#L61-L63

```json
    "publish": {
      "executor": "@ns3/nx-npm:publish"
    }
```

Does not work, getting:

```
 >  NX   Unable to resolve @ns3/nx-npm:publish.

   ⨯ Unable to compile TypeScript:
   error TS5024: Compiler option 'module' requires a value of type string.
   error TS5024: Compiler option 'target' requires a value of type string.
```

But running build on `@ns3/nx-npm` works.

### Expected Behavior

Should work as expected, it worked in previous versions.

### GitHub Repo

https://github.com/Bielik20/nx-plugins

### Steps to Reproduce

1. migrate Nx to latest version
2. run `NPM_TOKEN=abc yarn nx run nx-core:publish`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : darwin arm64
   yarn : 1.22.19

   nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/node              : 15.7.1
   @nrwl/nx-plugin         : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/webpack           : 15.7.1
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   	 @ns3/nx-jest-playwright
   	 @ns3/nx-serverless
   	 @ns3/nx-core
   	 @ns3/nx-npm
```

### Failure Logs

```shell
>  NX   Unable to resolve @ns3/nx-npm:publish.

   ⨯ Unable to compile TypeScript:
   error TS5024: Compiler option 'module' requires a value of type string.
   error TS5024: Compiler option 'target' requires a value of type string.


Error: Unable to resolve @ns3/nx-npm:publish.
⨯ Unable to compile TypeScript:
error TS5024: Compiler option 'module' requires a value of type string.
error TS5024: Compiler option 'target' requires a value of type string.

    at Workspaces.readExecutor (/Users/bielecd/Projects/_private/packages/nx/src/config/workspaces.ts:187:13)
    at getExecutorForTask (/Users/bielecd/Projects/_private/packages/nx/src/tasks-runner/utils.ts:244:20)
    at getCustomHasher (/Users/bielecd/Projects/_private/packages/nx/src/tasks-runner/utils.ts:253:19)
    at /Users/bielecd/Projects/_private/packages/nx/src/hasher/hash-task.ts:36:39
    at Generator.next (<anonymous>)
    at /Users/bielecd/Projects/_private/nx-plugins/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/bielecd/Projects/_private/nx-plugins/node_modules/tslib/tslib.js:114:16)
    at hashTask (/Users/bielecd/Projects/_private/nx-plugins/node_modules/nx/src/hasher/hash-task.js:20:20)
    at TasksSchedule.<anonymous> (/Users/bielecd/Projects/_private/packages/nx/src/tasks-runner/tasks-schedule.ts:90:21)
error Command failed with exit code 1.
```

**Comment by AgentEnder** [comment]
Duplicate of #15038, Fixed by #15066
