### ISSUE TITLE
Unable to resolve lazy loaded module within a library module

### ISSUE THREAD

**Issue by thekhoi** [nrwl/nx#151]
I want to lazy load a library module which also contains sub routes.  Those sub routes should also lazy load internal modules.

The 'host' application defines a default route that lazy loads my library.

```
    RouterModule.forRoot([
      {
        path: 'foo-bar',
        loadChildren: '@foobar-nx/foo-bar#FooBarModule'
      }],
      { initialNavigation: 'enabled' })],
```

The library in turn lazy loads an internal module:

```
      {
        path: 'baz',
        pathMatch: 'full',
        loadChildren: './foo-baz/foo-baz-component#FooBazModule'
      }

```
Compiler Error:
```
ERROR in Error: Could not resolve module ./foo-baz/foo-baz-component relative to C:/Workspace/GitHub/foobar-nx/libs/foo-bar/src/foo-bar.module.ts
    at StaticSymbolResolver.getSymbolByModule (C:\Workspace\GitHub\foobar-nx\node_modules\@angular\compiler\bundles\compiler.umd.js:31826:30)
    at StaticReflector.resolveExternalReference (C:\Workspace\GitHub\foobar-nx\node_modules\@angular\compiler\bundles\compiler.umd.js:30292:62)
    at parseLazyRoute (C:\Workspace\GitHub\foobar-nx\node_modules\@angular\compiler\bundles\compiler.umd.js:28577:55)
    at listLazyRoutes (C:\Workspace\GitHub\foobar-nx\node_modules\@angular\compiler\bundles\compiler.umd.js:28539:36)
    at visitLazyRoute (C:\Workspace\GitHub\foobar-nx\node_modules\@angular\compiler\bundles\compiler.umd.js:29937:47)
    at visitLazyRoute (C:\Workspace\GitHub\foobar-nx\node_modules\@angular\compiler\bundles\compiler.umd.js:29941:17)
    at AotCompiler.listLazyRoutes (C:\Workspace\GitHub\foobar-nx\node_modules\@angular\compiler\bundles\compiler.umd.js:29905:20)
    at AngularCompilerProgram.listLazyRoutes (C:\Workspace\GitHub\foobar-nx\node_modules\@angular\compiler-cli\src\transformers\program.js:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Workspace\GitHub\foobar-nx\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (C:\Workspace\GitHub\foobar-nx\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:246:66)
    at Promise.resolve.then.then (C:\Workspace\GitHub\foobar-nx\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:542:50)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Repo: https://github.com/thekhoi/foobar-nx

**Comment by BenevidesLecontes** [comment]
@thekhoi this what i'm doing `loadChildren: '@wiseit-admin/login-wrapper/src/login-wrapper.module#LoginWrapperModule',`

**Comment by thekhoi** [comment]
oops false alarm. I had a typo in my code. The foo-bar.module should have defined the module as:

      {
        path: 'baz',
        pathMatch: 'full',
        loadChildren: './foo-baz/foo-baz.module#FooBazModule'
      }

**Comment by blomm** [comment]
I'm trying to do this also, but having no luck. In the main root project I use the lazy-wrapper method to lazy load my library which tries itself lazy loads modules, but the lib can't the modules its trying to lazy load.  Did you get a solution?
