### ISSUE TITLE
HookWebpackError: Loop detected while pruning

### ISSUE THREAD

**Issue by jaqua** [nrwl/nx#15109]
### Current Behavior

Can't build nestJS application with `--generatePackageJson` parameter if project is using `gm` import (`gm/apps/gm/src/main.ts`)

Verbose output is:

```
HookWebpackError: Loop detected while pruning. Please report this issue.
    at makeWebpackError (/Users/tmp/gm/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/tmp/gm/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:71:1)
    at fn (/Users/tmp/gm/node_modules/webpack/lib/Compilation.js:480:17)
    at _next0 (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:69:1)
    at eval (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:82:1)
    at eval (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
-- inner error --
Error: Loop detected while pruning. Please report this issue.
    at nestMappedPackages (/Users/tmp/gm/node_modules/nx/src/lock-file/npm-parser.js:307:15)
    at nestMappedPackages (/Users/tmp/gm/node_modules/nx/src/lock-file/npm-parser.js:310:9)
    at mapSnapshots (/Users/tmp/gm/node_modules/nx/src/lock-file/npm-parser.js:256:9)
    at stringifyNpmLockfile (/Users/tmp/gm/node_modules/nx/src/lock-file/npm-parser.js:187:28)
    at createLockFile (/Users/tmp/gm/node_modules/nx/src/lock-file/lock-file.js:123:54)
    at /Users/tmp/gm/node_modules/@nrwl/webpack/src/plugins/generate-package-json-plugin.js:43:131
    at fn (/Users/tmp/gm/node_modules/webpack/lib/Compilation.js:478:10)
    at _next0 (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:69:1)
    at eval (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:82:1)
    at eval (eval at create (/Users/tmp/gm/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
```

### Expected Behavior

Successful build of application

### GitHub Repo

https://github.com/jaqua/gm

### Steps to Reproduce

1. Clone repo
2. npm install
3. nx run gm:build:production --generatePackageJson

Build fails

### Nx Report

```shell
Node : 16.6.1
   OS   : darwin x64
   npm  : 7.20.3
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/nest              : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.8.4
```

**Comment by mandarini** [comment]
Linking this here: https://github.com/nrwl/nx/issues/15093
