### ISSUE TITLE
Migrating @nwrl/nx to 15.7.1 breaks linting when enforce-module-boundaries is enabled

### ISSUE THREAD

**Issue by MichaelBagnasco** [nrwl/nx#15102]
### Current Behavior

On 15.6.3, linting worked as normal. However, after running `nx migrate latest` and `nx migrate --run-migrations` and getting 15.7.1, all linting has broken.

Removing `@nrwl/nx/enforce-module-boundaries` from .eslintrc.json resolves the issue.

<img width="1512" alt="Screenshot 2023-02-17 at 3 40 35 PM" src="https://user-images.githubusercontent.com/22750836/219799328-31514dd5-231b-42dc-9c7a-997588021bc1.png">

### Expected Behavior

Listing should work as normal after migrations

### Steps to Reproduce

1. Run linting on 15.7.1

### Nx Report

```shell
Node : 19.6.0
   OS   : darwin arm64
   npm  : 9.4.2

   nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/angular           : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/cypress           : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/rollup            : 15.7.1
   @nrwl/storybook         : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/web               : 15.7.1
   @nrwl/webpack           : 15.7.1
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component      : 15.3.0
   @ngrx/effects        : 15.3.0
   @ngrx/entity         : 15.3.0
   @ngrx/router-store   : 15.3.0
   @ngrx/store          : 15.3.0
   @ngrx/store-devtools : 15.3.0
   @compodoc/compodoc   : 1.1.19
   @ngrx/schematics     : 15.3.0
   @storybook/angular   : 7.0.0-beta.50
```

### Failure Logs

```shell
nx run explorer:lint
       Linting "explorer"...

        >  NX   Cannot read properties of undefined (reading 'startsWith')

          Occurred while linting /Users/michaelbagnasco/Developer/apps/explorer/jest.config.ts:3
          Rule: "@nrwl/nx/enforce-module-boundaries"
          Pass --verbose to see the stacktrace.


    ✖  nx run authoring-e2e:lint
       Linting "authoring-e2e"...

        >  NX   Cannot read properties of undefined (reading 'startsWith')

          Occurred while linting /Users/michaelbagnasco/playground/apps/authoring-e2e/cypress.config.ts:1
          Rule: "@nrwl/nx/enforce-module-boundaries"
          Pass --verbose to see the stacktrace.
```

**Comment by meeroslav** [comment]
Thank you @MichaelBagnasco for reporting this issue.

Can you please run the same command with `--verbose` to tell us where this problem comes from?

**Comment by meeroslav** [comment]
The only thing I see new with `startsWith` is this line of code:

https://github.com/nrwl/nx/blob/master/packages/eslint-plugin-nx/src/utils/runtime-lint-utils.ts#L94

Which would imply that your tag is somehow `undefined`?

**Comment by MichaelBagnasco** [comment]
Here is a screenshot of the logs with `--verbose`

```
Linting "explorer"...

 >  NX   Cannot read properties of undefined (reading 'startsWith')

   Occurred while linting /Users/michaelbagnasco/Developer/playground/apps/explorer/jest.config.ts:3
   Rule: "@nrwl/nx/enforce-module-boundaries"

TypeError: Cannot read properties of undefined (reading 'startsWith')
Occurred while linting /Users/michaelbagnasco/Developer/playground/apps/explorer/jest.config.ts:3
Rule: "@nrwl/nx/enforce-module-boundaries"
    at hasTag (/Users/michaelbagnasco/Developer/playground/node_modules/@nrwl/eslint-plugin-nx/src/utils/runtime-lint-utils.js:45:13)
    at /Users/michaelbagnasco/Developer/playground/node_modules/@nrwl/eslint-plugin-nx/src/utils/runtime-lint-utils.js:167:34
    at Array.every (<anonymous>)
    at /Users/michaelbagnasco/Developer/playground/node_modules/@nrwl/eslint-plugin-nx/src/utils/runtime-lint-utils.js:167:21
    at Array.filter (<anonymous>)
    at hasBannedImport (/Users/michaelbagnasco/Developer/playground/node_modules/@nrwl/eslint-plugin-nx/src/utils/runtime-lint-utils.js:159:37)
    at run (/Users/michaelbagnasco/Developer/playground/node_modules/@nrwl/eslint-plugin-nx/src/rules/enforce-module-boundaries.js:240:77)
    at ImportDeclaration (/Users/michaelbagnasco/Developer/playground/node_modules/@nrwl/eslint-plugin-nx/src/rules/enforce-module-boundaries.js:410:17)
    at ruleErrorHandler (/Users/michaelbagnasco/Developer/playground/node_modules/eslint/lib/linter/linter.js:1118:28)
    at /Users/michaelbagnasco/Developer/playground/node_modules/eslint/lib/linter/safe-emitter.js:45:58
```


<img width="1184" alt="Screenshot 2023-02-21 at 4 01 34 PM" src="https://user-images.githubusercontent.com/22750836/220468910-a001fd65-da42-4552-937b-fb4f345830f4.png">

**Comment by MichaelBagnasco** [comment]
To your point about tag possibly being undefined, here is the tags array in my project.json


`"tags": ["scope:explorer", "type:app"]`

**Comment by MichaelBagnasco** [comment]
And if it's helpful at all. Here is my .eslintrc.json. 

```
{
  "root": true,
  "ignorePatterns": [
    "**/*"
  ],
  "plugins": [
    "@nrwl/nx",
    "sonarjs"
  ],
  "extends": [
    "eslint-config-prettier",
    "plugin:sonarjs/recommended",
    "plugin:storybook/recommended"
  ],
  "overrides": [
    {
      "files": [
        "*.ts",
        "*.tsx",
        "*.js",
        "*.jsx"
      ],
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "enforceBuildableLibDependency": true,
            "allow": [],
            "depConstraints": [
              {
                "sourceTag": "scope:shared",
                "onlyDependOnLibsWithTags": [
                  "scope:shared"
                ]
              },
              {
                "sourceTag": "scope:admin",
                "onlyDependOnLibsWithTags": [
                  "scope:shared",
                  "scope:admin"
                ]
              },
              {
                "sourceTag": "scope:authoring",
                "onlyDependOnLibsWithTags": [
                  "scope:shared",
                  "scope:authoring"
                ]
              },
              {
                "sourceTag": "scope:embedded",
                "onlyDependOnLibsWithTags": [
                  "scope:shared",
                  "scope:embedded"
                ]
              },
              {
                "sourceTag": "scope:inspector",
                "onlyDependOnLibsWithTags": [
                  "scope:shared",
                  "scope:inspector"
                ]
              },
              {
                "sourceTag": "scope:explorer",
                "onlyDependOnLibsWithTags": [
                  "scope:shared",
                  "scope:explorer"
                ]
              },
              {
                "sourceTag": "type:ui",
                "onlyDependOnLibsWithTags": [
                  "type:ui",
                  "type:util"
                ]
              },
              {
                "sourceTag": "type:data",
                "onlyDependOnLibsWithTags": [
                  "type:data",
                  "type:util"
                ]
              },
              {
                "sourceTag": "type:util",
                "onlyDependOnLibsWithTags": [
                  "type:util"
                ]
              },
              {
                "sourceTah": "type:toolkit",
                "onlyDependOnLibsWithTags": [
                  "type:toolkit"
                ]
              }
            ]
          }
        ]
      }
    },
    {
      "files": [
        "*.ts",
        "*.tsx"
      ],
      "extends": [
        "plugin:@nrwl/nx/typescript"
      ],
      "rules": {}
    },
    {
      "files": [
        "*.js",
        "*.jsx"
      ],
      "extends": [
        "plugin:@nrwl/nx/javascript"
      ],
      "rules": {}
    },
    {
      "files": [
        "*.spec.ts",
        "*.spec.tsx",
        "*.spec.js",
        "*.spec.jsx"
      ],
      "env": {
        "jest": true
      },
      "rules": {}
    },
    {
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:sonarjs/recommended"
      ],
      "rules": {
        "sonarjs/no-element-overwrite": "off",
        "sonarjs/no-same-line-conditional": "off",
        "sonarjs/prefer-object-literal": "off"
      }
    },
    {
      "files": [
        "*.cy.ts"
      ],
      "extends": [
        "plugin:sonarjs/recommended"
      ],
      "rules": {
        "sonarjs/no-duplicate-string": "off"
      }
    }
  ]
}
```

**Comment by meeroslav** [comment]
You have a typo in your configuration:

```jsonc
  {
    "sourceTah": "type:toolkit", // <- this should be "sourceTag"
    "onlyDependOnLibsWithTags": [
      "type:toolkit"
    ]
  }
```
