### ISSUE TITLE
insertAfterLastOccurrence (/Users/san/project/Sample/testing/node_modules/@nrwl/workspace/src/utilities/ast-utils.js:103:15)

### ISSUE THREAD

**Issue by anandjaisy** [nrwl/nx#15107]
### Current Behavior

```
Error
    at insertAfterLastOccurrence (/Users/san/project/Sample/testing/node_modules/@nrwl/workspace/src/utilities/ast-utils.js:103:15)
    at insertImport (/Users/san/project/Sample/testing/node_modules/@nrwl/workspace/src/utilities/ast-utils.js:96:12)
    at addImport (/Users/san/project/Sample/testing/node_modules/@nrwl/angular/src/generators/ngrx/lib/add-imports-to-module.js:76:45)
    at addImportsToModule (/Users/san/project/Sample/testing/node_modules/@nrwl/angular/src/generators/ngrx/lib/add-imports-to-module.js:107:22)
    at /Users/san/project/Sample/testing/node_modules/@nrwl/angular/src/generators/ngrx/ngrx.js:15:42
    at Generator.next (<anonymous>)
    at /Users/san/project/Sample/testing/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/san/project/Sample/testing/node_modules/tslib/tslib.js:163:16)
    at ngrxGenerator (/Users/san/project/Sample/testing/node_modules/@nrwl/angular/src/generators/ngrx/ngrx.js:8:20)
```

### Expected Behavior

Should add the ngrx store to the root of the application

### GitHub Repo

https://github.com/anandjaisy/nx-ngrx-issue

### Steps to Reproduce

Using latest version of NX and angular CLI latest

Create a micro-frontends application using below commands

Create the workspace
`npx create-nx-workspace@latest testing`

CD to the directory

Install angular
`npm i @nrwl/angular`

Create micro-frontends apps
`nx g @nrwl/angular:host shell --remotes=shop,cart --standalone`

Try to add the ngrx store to the main app
`nx g @nrwl/angular:ngrx --root --parent=apps/shell/src/main.ts`

### Nx Report

```shell
Error
    at insertAfterLastOccurrence (/Users/san/project/Sample/testing/node_modules/@nrwl/workspace/src/utilities/ast-utils.js:103:15)
    at insertImport (/Users/san/project/Sample/testing/node_modules/@nrwl/workspace/src/utilities/ast-utils.js:96:12)
    at addImport (/Users/san/project/Sample/testing/node_modules/@nrwl/angular/src/generators/ngrx/lib/add-imports-to-module.js:76:45)
    at addImportsToModule (/Users/san/project/Sample/testing/node_modules/@nrwl/angular/src/generators/ngrx/lib/add-imports-to-module.js:107:22)
    at /Users/san/project/Sample/testing/node_modules/@nrwl/angular/src/generators/ngrx/ngrx.js:15:42
    at Generator.next (<anonymous>)
    at /Users/san/project/Sample/testing/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/san/project/Sample/testing/node_modules/tslib/tslib.js:163:16)
    at ngrxGenerator (/Users/san/project/Sample/testing/node_modules/@nrwl/angular/src/generators/ngrx/ngrx.js:8:20)
```

**Comment by Coly010** [comment]
I can see you're using Module Federation, therefore you need to specify `--parent=apps/shell/src/bootstrap.ts` rather than the main.ts file.

With Module Federation, the functions to bootstrap your app are placed in `bootstrap.ts` as that file needs to be dynamically imported to allow the share scopes of Module Federation to be initialised correctly.


As this issue has a workaround, I'm going to close the issue. If you have any problems implementing the workaround, tag me in a new comment on this issue.
