### ISSUE TITLE
ng-packagr-lite shows useless error when invalid styleUrls path

### ISSUE THREAD

**Issue by jonhamm** [nrwl/nx#15185]
### Current Behavior

If in a buildable library build with `ng-packagr-lite` you specify a `styleUrls` path that does not match any file:
```
@Component({
  selector: 'xxx',
  templateUrl: './zzz.component.html',
  styleUrls: ['../../bad/path/xxx.scss'], // no such file ../../bad/path/xxx.scss
  encapsulation: ViewEncapsulation.None,
})
```
then `nx build <<library>>` will give a useless result like this : 
```
> nx run some-lib:build

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@xxx/libs/some-lib'
------------------------------------------------------------------------------

 >  NX   Cannot read properties of undefined (reading 'includes')

   Pass --verbose to see the stacktrace.

```
and here when run with verbose:

```
 >  NX   Cannot read properties of undefined (reading 'includes')


TypeError: Cannot read properties of undefined (reading 'includes')
    at StylesheetProcessor.<anonymous> (/Users/jha/work/git/wt/release/3.20/node_modules/@nrwl/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/styles/stylesheet-processor.js:82:26)
    at Generator.next (<anonymous>)
    at /Users/jha/work/git/wt/release/3.20/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/jha/work/git/wt/release/3.20/node_modules/tslib/tslib.js:163:16)
    at StylesheetProcessor.process (/Users/jha/work/git/wt/release/3.20/node_modules/@nrwl/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/styles/stylesheet-processor.js:76:24)
    at /Users/jha/work/git/wt/release/3.20/node_modules/@nrwl/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/ts/cache-compiler-host.js:109:63
    at Generator.next (<anonymous>)
    at /Users/jha/work/git/wt/release/3.20/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/jha/work/git/wt/release/3.20/node_modules/tslib/tslib.js:163:16)
    at Object.readResource (/Users/jha/work/git/wt/release/3.20/node_modules/@nrwl/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/ts/cache-compiler-host.js:99:48)
    at AdapterResourceLoader.preload (file:///Users/jha/work/git/wt/release/3.20/node_modules/@angular/compiler-cli/bundles/chunk-DEOVYZ6W.js:1794:31)
    at resolveStyleUrl (file:///Users/jha/work/git/wt/release/3.20/node_modules/@angular/compiler-cli/bundles/chunk-P6RV7WPP.js:6001:36)
    at file:///Users/jha/work/git/wt/release/3.20/node_modules/@angular/compiler-cli/bundles/chunk-P6RV7WPP.js:6029:47
    at Array.map (<anonymous>)

```

### Expected Behavior

The error message should provide some information that could direct the developer to fix the problem

### Steps to Reproduce

1. create buildable library
2. add component to library
3. specify invalid `styleUrls` path in component
4. build the library

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.5.5
   
   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : 15.6.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.3
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   	 @cue/dx
   ---------------------------------------
   Community plugins:
   	 @ngrx/component-store: 15.3.0
   	 @ngrx/store: 15.3.0
   	 @ngrx/store-devtools: 15.3.0
   	 @ngx-matomo/tracker: 4.0.1
   	 apollo-angular: 4.2.1
   	 @compodoc/compodoc: 1.1.19
   	 @storybook/angular: 6.5.16
   	 @testing-library/angular: 13.1.0
   	 ng-mocks: 14.6.0
   	 nx-stylelint: 14.0.2
```

**Comment by jonhamm** [comment]
I will provide a PR for this
