### ISSUE TITLE
Unable to run NestJS app with Nx 15.7

### ISSUE THREAD

**Issue by maphe** [nrwl/nx#15246]
### Current Behavior

I upgraded our Nx environment from 15.5 to 15.7 and NestJS apps can't run anymore from the `serve` command.

### Expected Behavior

NestJS apps should run normally after upgrading Nx to 15.7

### Steps to Reproduce

1. on a repo using Nx 15.5 and having at least one NextJS app: 
  - `nx migrate @nrwl/workspace@15.7.2`
  - `yarn`
  - `nx migrate --run-migrations`

### Nx Report

```shell
Node : 18.14.2
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/nest              : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   @nrwl/nx-cloud          : 15.1.0
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @auth0/auth0-angular    : 1.10.1
   ng2-charts              : 3.0.9
   @sharethrough/nx-deploy : 2.3.1
```

### Failure Logs

```shell
>  NX   Cannot read properties of undefined (reading 'data')


HookWebpackError: Cannot read properties of undefined (reading 'data')
    at makeWebpackError (/Users/maphe/Workspace/publisher-platform/node_modules/@nrwl/webpack/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/maphe/Workspace/publisher-platform/node_modules/@nrwl/webpack/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/maphe/Workspace/publisher-platform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at fn (/Users/maphe/Workspace/publisher-platform/node_modules/@nrwl/webpack/node_modules/webpack/lib/Compilation.js:480:17)
    at _next0 (eval at create (/Users/maphe/Workspace/publisher-platform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at eval (eval at create (/Users/maphe/Workspace/publisher-platform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at eval (eval at create (/Users/maphe/Workspace/publisher-platform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/maphe/Workspace/publisher-platform/node_modules/@nrwl/webpack/node_modules/webpack/lib/Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (/Users/maphe/Workspace/publisher-platform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/maphe/Workspace/publisher-platform/node_modules/tapable/lib/Hook.js:18:14)
```

### Additional Information

When going from `15.5.3` to `15.6.3` and then to `15.7.2`, it worked fine on `15.6.3`

**Comment by jojoa** [comment]
i had the same error, it was fixed in #15052 for me

**Comment by maphe** [comment]
Good to know, thanks @jojoa. Looks like I'll have to wait for 18.0 to get out of beta then I'll give it a try...

**Comment by maphe** [comment]
Ok I did try 15.8.0-beta-6 and can confirm it fixes the issue. I'll just wait for an official release I guess.

**Comment by ndcunningham** [comment]
Since `15.8.0` has already been released closing this.

**Comment by kdawgwilk** [comment]
Still seeing this on `15.9.2`
