### ISSUE TITLE
15.7.2 Loop detected while pruning. Please report this issue.

### ISSUE THREAD

**Issue by vicb** [nrwl/nx#15243]
### Current Behavior

$ nx build proxy --skip-nx-cache

> nx run proxy:build

 >  NX   Loop detected while pruning. Please report this issue.

   Pass --verbose to see the stacktrace.

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project proxy (4s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]

### Expected Behavior

no crash

### Steps to Reproduce

1. repo is https://github.com/vicb/flyxc
2. branch fail
3. nx run proxy:build

### Nx Report

```shell
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.10.0
   OS   : linux x64
   npm  : 8.19.2
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/express           : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/rollup            : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/vite              : 15.7.2
   @nrwl/web               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 4.0.3
```

### Failure Logs

```shell
>  NX   Loop detected while pruning. Please report this issue.


HookWebpackError: Loop detected while pruning. Please report this issue.
    at makeWebpackError (/usr/local/google/home/berchet/code/flyxc/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /usr/local/google/home/berchet/code/flyxc/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/usr/local/google/home/berchet/code/flyxc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at fn (/usr/local/google/home/berchet/code/flyxc/node_modules/webpack/lib/Compilation.js:480:17)
    at Hook.eval [as callAsync] (eval at create (/usr/local/google/home/berchet/code/flyxc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/local/google/home/berchet/code/flyxc/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/usr/local/google/home/berchet/code/flyxc/node_modules/webpack/lib/Compilation.js:3057:34)
    at /usr/local/google/home/berchet/code/flyxc/node_modules/webpack/lib/Compilation.js:3105:10
    at symbolIterator (/usr/local/google/home/berchet/code/flyxc/node_modules/neo-async/async.js:3485:9)
    at done (/usr/local/google/home/berchet/code/flyxc/node_modules/neo-async/async.js:3527:9)
-- inner error --
Error: Loop detected while pruning. Please report this issue.
    at nestMappedPackages (/usr/local/google/home/berchet/code/flyxc/node_modules/nx/src/lock-file/npm-parser.js:307:15)
    at nestMappedPackages (/usr/local/google/home/berchet/code/flyxc/node_modules/nx/src/lock-file/npm-parser.js:310:9)
    at mapSnapshots (/usr/local/google/home/berchet/code/flyxc/node_modules/nx/src/lock-file/npm-parser.js:256:9)
    at stringifyNpmLockfile (/usr/local/google/home/berchet/code/flyxc/node_modules/nx/src/lock-file/npm-parser.js:187:28)
    at createLockFile (/usr/local/google/home/berchet/code/flyxc/node_modules/nx/src/lock-file/lock-file.js:123:54)
    at /usr/local/google/home/berchet/code/flyxc/node_modules/@nrwl/webpack/src/plugins/generate-package-json-plugin.js:43:131
    at fn (/usr/local/google/home/berchet/code/flyxc/node_modules/webpack/lib/Compilation.js:478:10)
    at Hook.eval [as callAsync] (eval at create (/usr/local/google/home/berchet/code/flyxc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/local/google/home/berchet/code/flyxc/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/usr/local/google/home/berchet/code/flyxc/node_modules/webpack/lib/Compilation.js:3057:34)
```

**Comment by AgentEnder** [comment]
This should be fixed in beta, see: #15093
