### ISSUE TITLE
e2e fails for plugin generated by @nrwl/nx-plugin:plugin when using yarn2

### ISSUE THREAD

**Issue by lislon** [nrwl/nx#15263]
### Current Behavior

The e2e tests fails for freshly generated nx-plugin on yarn2 (berry) project

### Expected Behavior

e2e test should pass

### GitHub Repo

https://github.com/lislon/nx-plugin-e2e-yarn-issue

### Steps to Reproduce

1. Make sure yarn `yarn --version` is `3.x` (If not, run `yarn set version berry`)
1. Run `yarn install`
2. Run `yarn exec nx e2e my-plugin-e2e`

### Nx Report

```shell
   Node : 18.12.1
   OS   : win32 x64
   yarn : 3.3.1

   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/nx-plugin         : 15.7.2
   @nrwl/react             : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/vite              : 15.7.2
   typescript              : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         @nx-plugin-e2e-fail/my-plugin
```

### Failure Logs

```shell
> nx run my-plugin-e2e:e2e

Compiling TypeScript files for project "my-plugin"...
Done compiling TypeScript files for project "my-plugin".
  FAIL   my-plugin-e2e  apps/my-plugin-e2e/tests/my-plugin.spec.ts (14.007 s)
my-plugin e2e
    × should create my-plugin
--directory
      × should create src in the specified directory
--tags
      × should add tags to the project

  ● my-plugin e2e › should create my-plugin

Command failed: yarn

at runPackageManagerInstall (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:54:27)
at newNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:74:3)
at ensureNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:86:3)
at Object.<anonymous> (tests/my-plugin.spec.ts:17:20)
```

### Additional Information

I debugged the `yarn` command in `./tmp` and got following error:

```
> yarn
Usage Error: The nearest package directory (C:\Users\ele\src\nx-plugin-e2e-fail\tmp\nx-e2e\proj) doesn't seem to be part of the project declared in C:\Users\ele\src\nx-plugin-e2e-fail.

- If C:\Users\ele\src\nx-plugin-e2e-fail isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If C:\Users\ele\src\nx-plugin-e2e-fail is intended to be a project, it might be that you forgot to list tmp/nx-e2e/proj in its workspace configuration.
- Finally, if C:\Users\ele\src\nx-plugin-e2e-fail is fine and you intend tmp/nx-e2e/proj to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.
```

When I add empty `yarn.lock` in `./tmp/nx-e2e/proj`  the `yarn` command and e2e pass

**Comment by mta-trackunit** [comment]
I have the same issue - is there a workaround? ... seems like 

`runPackageManagerInstall` should check if yarn.lock is in the tmp location and just create an empty one before it runs `yarn`

That solves it if I hack it directly in node_modules ... but I dont have a workaround for it - and would love to see it... or a fix :) Let me know if there is anything I can do to help out!

**Comment by AgentEnder** [comment]
This sounds a bit different, but the way we are approaching #10992 should solve this too, so I'm going to go ahead and close this as a duplicate. We are working on this area soon, stay tuned. 📺
