### ISSUE TITLE
setup-ssr doesn't with with standalone components

### ISSUE THREAD

**Issue by ciriousjoker** [nrwl/nx#15273]
### Current Behavior

Cannot run setup-ssr in Angular standalone project without an app.module.ts file.
`npx nx generate setup-ssr --verbose --dry-run`

### Expected Behavior

Generator should run without error.

### GitHub Repo

https://github.com/ciriousjoker/repro-nx-angular-ssr

### Steps to Reproduce

1. `npx create-nx-workspace --name repro-nx-angular-ssr --preset empty --skipGit --nxCloud false`
2. `cd repro-nx-angular-ssr`
3. `npm install @nrwl/angular`
4. `npx nx g @nrwl/angular:application test --routing --standalone --minimal --setParserOptionsProject --skipTests --strict --style css`

**This fails:**
6. `npx nx generate setup-ssr --project test --verbose`

### Nx Report

```shell
Node : 16.19.0
   OS   : darwin arm64
   npm  : 9.4.0
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.8.4
```

### Failure Logs

```shell
Error: ENOENT: no such file or directory, open '/Users/.../project/apps/website/src/app/app.module.ts'
    at Object.openSync (node:fs:590:3)
    at readFileSync (node:fs:458:35)
    at FsTree.fsReadFile (/Users/.../project/node_modules/nx/src/generators/tree.js:202:44)
    at FsTree.read (/Users/.../project/node_modules/nx/src/generators/tree.js:22:32)
    at updateAppModule (/Users/.../project/node_modules/@nrwl/angular/src/generators/setup-ssr/lib/update-app-module.js:10:31)
    at /Users/.../project/node_modules/@nrwl/angular/src/generators/setup-ssr/setup-ssr.js:13:35
    at Generator.next (<anonymous>)
    at /Users/.../project/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/.../project/node_modules/tslib/tslib.js:163:16)

 >  NX   Cannot read properties of null (reading 'length')
```

### Additional Information

Is this a bug or is it just impossible to run SSR without an `app.module.ts` file?

#### Related:
- https://github.com/angular/angular-cli/issues/24784

**Comment by ciriousjoker** [comment]
Current workaround, similar to how it can be done for the pwa generator:
https://stackoverflow.com/a/75430579/5854364

1. Create `app/app.module.ts` with this content:
```ts
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";

@NgModule({
  declarations: [],
  imports: [BrowserModule],
  providers: [],
  bootstrap: [],
})
export class AppModule {}
```

2. Replace `main.ts` with this:
```ts
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { AppModule } from "./app/app.module";

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch((err) => console.error(err));
```

3. `npx nx generate setup-ssr`
4. Migrate changes manually
