### ISSUE TITLE
Failed to create a React mf remote using an Angular Host

### ISSUE THREAD

**Issue by RicardoJBarrios** [nrwl/nx#15281]
### Current Behavior

When I try to create a React remote with module federation using an Angular host I receive this error:

```sh
npx nx g @nrwl/react:remote users --host=shell --style css --verbose

>  NX  Generating @nrwl/react:remote

>  NX   The "path" argument must be of type string. Received undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at join (node:path:1172:7)
    at FsTree.normalize (/root/dev/testapp/node_modules/nx/src/generators/tree.js:187:64)
    at FsTree.exists (/root/dev/testapp/node_modules/nx/src/generators/tree.js:73:25)
    at updateHostWithRemote (/root/dev/testapp/node_modules/@nrwl/react/src/generators/remote/lib/update-host-with-remote.js:31:14)
    at /root/dev/testapp/node_modules/@nrwl/react/src/generators/remote/remote.js:28:64
    at Generator.next (<anonymous>)
    at fulfilled (/root/dev/testapp/node_modules/tslib/tslib.js:164:62)
```

### Expected Behavior

To create the react app and link the remote to the Angular Router.

### Steps to Reproduce

1. Execute the following commands:

```
npx create-nx-workspace@latest --preset apps --name testapp --nxCloud false
cd testapp
npm i -D @nrwl/angular
npm i -D @nrwl/react
npx nx g @nrwl/angular:host shell --remotes=posts,comments --style css
npx nx g @nrwl/react:remote users --host=shell --style css
```

### Nx Report

```shell
Node : 18.14.2
   OS   : linux x64
   npm  : 9.5.1

   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/react             : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.8.4
```

### Failure Logs

```shell
npx nx g @nrwl/react:remote users --host=shell --style css --verbose

>  NX  Generating @nrwl/react:remote

>  NX   The "path" argument must be of type string. Received undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at join (node:path:1172:7)
    at FsTree.normalize (/root/dev/testapp/node_modules/nx/src/generators/tree.js:187:64)
    at FsTree.exists (/root/dev/testapp/node_modules/nx/src/generators/tree.js:73:25)
    at updateHostWithRemote (/root/dev/testapp/node_modules/@nrwl/react/src/generators/remote/lib/update-host-with-remote.js:31:14)
    at /root/dev/testapp/node_modules/@nrwl/react/src/generators/remote/remote.js:28:64
    at Generator.next (<anonymous>)
    at fulfilled (/root/dev/testapp/node_modules/tslib/tslib.js:164:62)
```

**Comment by jaysoo** [comment]
Hi @RicardoJBarrios serving remotes in different frameworks (Angular vs React) is not a use-case we support at the moment. Can you start a [discussion](https://github.com/nrwl/nx/discussions) and we can look into in the future if people are interested in the feature? Thanks.
