### ISSUE TITLE
host generator with dynamic option - Error: Call setRemoteDefinitions or setRemoteUrlResolver

### ISSUE THREAD

**Issue by neilsoult** [nrwl/nx#15283]
### Current Behavior

serving a host (with remote) made by using the host generator with dynamic flag fails to route/load remote route. 

Error in console: 

```
ERROR Error: Uncaught (in promise): Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly.
Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly.
```

### Expected Behavior

no error, remote route should load

### GitHub Repo

https://github.com/neilsoult/nx-workspace-mfe-test

### Steps to Reproduce

1. follow steps in https://nx.dev/recipes/module-federation/module-federation-with-ssr - up until Generating a host and multiple remotes with SSR
2. generate host and remote with the following command: `npx nx g @nrwl/angular:host shell --remotes=product --ssr --dynamic --skipTests --style=scss` 
3. serve app (`npx nx serve shell`)
4. load shell - no errors
5. try to navigate to remote
6. check web console

### Nx Report

```shell
Node : 16.5.0
   OS   : linux x64
   npm  : 8.10.0
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   @nrwl/nx-cloud          : 15.1.1
   typescript              : 4.8.4
   ---------------------------------------
   Community plugins:
   @nguniversal/express-engine : 15.1.0
   @nguniversal/builders       : 15.1.0
```

### Failure Logs

```shell
​ ERROR Error: Uncaught (in promise): Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly.
Error: Call setRemoteDefinitions or setRemoteUrlResolver to allow Dynamic Federation to find the remote apps correctly.
    at apps_shell_src_bootstrap_ts.js:449:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (apps_shell_src_bootstrap_ts.js:483:24)
    at _next (apps_shell_src_bootstrap_ts.js:502:9)
    at apps_shell_src_bootstrap_ts.js:507:7
    at new ZoneAwarePromise (polyfills.js:8582:21)
    at apps_shell_src_bootstrap_ts.js:499:12
    at _loadRemoteContainer (apps_shell_src_bootstrap_ts.js:465:31)
    at loadRemoteContainer (apps_shell_src_bootstrap_ts.js:441:31)
    at apps_shell_src_bootstrap_ts.js:428:103
    at resolvePromise (polyfills.js:8370:19)
    at resolvePromise (polyfills.js:8323:9)
    at polyfills.js:8431:9
    at _ZoneDelegate.invokeTask (polyfills.js:7581:171)
    at node_modules_angular…ore_mjs.js:23873:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (node_modules_angular…ore_mjs.js:23873:30)
    at _ZoneDelegate.invokeTask (polyfills.js:7581:54)
    at Object.onInvokeTask (node_modules_angular…ore_mjs.js:24175:25)
    at _ZoneDelegate.invokeTask (polyfills.js:7581:54)
    at Zone.runTask (polyfills.js:7386:37)
```

**Comment by Coly010** [comment]
We currently don't support dynamic federation with SSR. We need to do more investigation into this and determine the appropriate method of solving this issue. I'm going to close this issue and I can update here if we add support.
