### ISSUE TITLE
15.8.1 : The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

### ISSUE THREAD

**Issue by BenLune** [nrwl/nx#15367]
### Current Behavior

After upgrading from 15.7.2 to 15.8.1 , I have these errors :
>  NX   Failed to run update-configs-jest-29 from @nrwl/jest. This workspace is NOT up to date!
>  NX   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

I can't serve my app anymore

I also have this error when I nx serve my app :  
>  NX   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

I have to revert, and try later

### Expected Behavior

Going on working on my projects

### Steps to Reproduce

1. Migrate from 15.7.2 to 15.8.1

### Nx Report

```shell
I have this error with nx report command:  >  NX   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```

**Comment by mlc-mlapis** [comment]
The same problem on our side in the precisely the same case.

**Comment by thtliife** [comment]
If you run any nx command with the --verbose flag, you get the full stack trace:

```bash
nx run-many --target=serve --verbose
yarn run v1.22.15
$ /Users/vito/repos/personal/test-repo/node_modules/.bin/nx run-many --target=serve --verbose

 >  NX   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

{
  stack: 'TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined\n' +
    '    at new NodeError (node:internal/errors:371:5)\n' +
    '    at Hash.update (node:internal/crypto/hash:105:11)\n' +
    '    at HashingImpl.hashArray (/Users/vito/repos/personal/test-repo/node_modules/nx/src/hasher/hashing-impl.js:10:20)\n' +
    '    at /Users/vito/repos/personal/test-repo/node_modules/nx/src/lock-file/yarn-parser.js:49:55\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at /Users/vito/repos/personal/test-repo/node_modules/nx/src/lock-file/yarn-parser.js:33:26\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at addNodes (/Users/vito/repos/personal/test-repo/node_modules/nx/src/lock-file/yarn-parser.js:26:34)\n' +
    '    at parseYarnLockfile (/Users/vito/repos/personal/test-repo/node_modules/nx/src/lock-file/yarn-parser.js:17:5)\n' +
    '    at parseLockFile (/Users/vito/repos/personal/test-repo/node_modules/nx/src/lock-file/lock-file.js:68:52)',
  message: 'The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined\n' +
    '\n' +
    'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    'If the error persists, please run "nx reset".',
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by yardenxr** [comment]
same issue here after updating to 15.8.1.

**Comment by mlc-mlapis** [comment]
@FrozenPandaz The  https://github.com/nrwl/nx/pull/15364 fix doesn't solve the problem for NPM. After updating to Nx 15.8.2 the problem with the error of `The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined` remains.

**Comment by mlc-mlapis** [comment]
The same issue after updating to 15.8.3 remains.

**Comment by mlc-mlapis** [comment]
The same issue after updating to 15.8.5 remains.

**Comment by mlc-mlapis** [comment]
@FrozenPandaz Just a polite question, are you aware that this issue has not been solved by [#15364 ](https://github.com/nrwl/nx/pull/15364)?

**Comment by mlc-mlapis** [comment]
@BenLune @thtliife @yardenxr What is your experience? I mean whether the problem has been solved or not on your side.

**Comment by thtliife** [comment]
@mlc-mlapis I haven't seen the problem again  Since 15.8.2
I did remove my node_modules folder and tarn.lock file and rerun yarn install. 
and obviously I use yarn, not npm.

**Comment by mlc-mlapis** [comment]
@thtliife Thanks for your answer. On our side, nothing mentioned didn't help. We use NPM.

**Comment by thtliife** [comment]
@mlc-mlapis I also see you are on windows, whereas I’m on Linux. 
have you tried using WSL, rather than cmd?
Just on the off chance it is OS or path related?

**Comment by mlc-mlapis** [comment]
@thtliife Yep, good point. I'll try to make the test to know if it's related.

**Comment by mlc-mlapis** [comment]
@thtliife @FrozenPandaz I tried to compile the same project under Linux instead of Windows, and it looks the `nx` commands work as expected. So it seems that the problem is related only to the Windows environment.

**Comment by thtliife** [comment]
@mlc-mlapis that explains why I don’t get the issue since that pr then

**Comment by mlc-mlapis** [comment]
@thtliife I double-checked the versions. Both (local & global) are the same. In this case, it's v15.8.5. The problem remains.

PS: Using the project with the local Nx version 15.7.2 and the global 15.8.5 also works without any problem.

Environment:
* Node.js v16.14.0
* NPM v8.3.1
* Windows 10
