### ISSUE TITLE
Unable to generate app 

### ISSUE THREAD

**Issue by tommyc38** [nrwl/nx#154]
I followed the directions but get the following error when trying to build an app:

`$ ng generate app home --routing
input.mergeMap is not a function
TypeError: input.mergeMap is not a function
    at Object.callRule (/Users/tommyc38/WebstormProjects/u-hoa-workspace/node_modules/@angular-devkit/schematics/src/rules/call.js:70:18)
    at SchematicImpl.call (/Users/tommyc38/WebstormProjects/u-hoa-workspace/node_modules/@angular-devkit/schematics/src/engine/schematic.js:35:23)
    at Promise (/Users/tommyc38/WebstormProjects/u-hoa-workspace/node_modules/@angular/cli/tasks/schematic-run.js:73:23)
    at new Promise (<anonymous>)
    at Class.run (/Users/tommyc38/WebstormProjects/u-hoa-workspace/node_modules/@angular/cli/tasks/schematic-run.js:72:16)
    at Class.run (/Users/tommyc38/WebstormProjects/u-hoa-workspace/node_modules/@angular/cli/commands/generate.js:156:33)
    at resolve (/Users/tommyc38/WebstormProjects/u-hoa-workspace/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (/Users/tommyc38/WebstormProjects/u-hoa-workspace/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/Users/tommyc38/WebstormProjects/u-hoa-workspace/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)
`

I am also getting this error in yarn when I added angular/cli globally via yarn - https://github.com/angular/devkit/issues/332

It looks to be related.

**Comment by jschwarty** [comment]
I believe this is due to the pinned version of rxjs at 5.5.2. If you bump that to 5.5.5 it fixes it. Doing some replication to confirm...

**Comment by jschwarty** [comment]
The same thing is happening with Angular CLI projects:
https://github.com/angular/angular-cli/issues/8782

**Comment by tommyc38** [comment]
@jschwarty thanks for looking into it for me.  On a side note, I'm a huge fan of what you guys are doing with this project and look forward to helping and seeing it successful anyway I can.

**Comment by tommyc38** [comment]
@jschwarty I upgraded rxjs and the problem went away.  Thanks!
