### ISSUE TITLE
npx nx run-android removing app dependencies from node_modules

### ISSUE THREAD

**Issue by tiagobnobrega** [nrwl/nx#15405]
### Current Behavior

On a react-native project, after instaling some dependencies on the app package.json, when I run `npx nx run-android my-app` the app dependencies are removed from the node_modules. I think this is done by the https://github.com/nrwl/nx/blob/76fcf7a319f447d4c940a175b0351d920f5800e8/packages/react-native/src/utils/ensure-node-modules-symlink.ts#L13.

The metro bundler complains about not finding some dependencies. 
If I run `react-native start` and `react-native run-android` it works.

### Expected Behavior

When runing `npx nx run-android my-app` app dependencies should be present on node_modules before the mtero bundler starts

### GitHub Repo

reproducible in a newly created workspace

### Steps to Reproduce

1. `npx create-nx-workspace --preset=apps`
2. cd into project folder
3. `npm i --save-dev @nrwl/react-native`
4. `nx g @nrwl/react-native:app my-app`
5. `cd apps/my-app`
6. `npm i react-native-screens`
7. Edit App.tsx adding a import to react-native-screens and calling a function
```js
import { enableScreens } from 'react-native-screens';
enableScreens();
```
8. run `npx nx run-android my-app`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.19.1
   OS   : linux x64
   npm  : 8.19.3
   
   nx                      : 15.8.2
   @nrwl/js                : 15.8.2
   @nrwl/jest              : 15.8.2
   @nrwl/linter            : 15.8.2
   @nrwl/workspace         : 15.8.2
   @nrwl/cli               : 15.8.2
   @nrwl/detox             : 15.8.2
   @nrwl/devkit            : 15.8.2
   @nrwl/eslint-plugin-nx  : 15.8.2
   @nrwl/react             : 15.8.2
   @nrwl/react-native      : 15.8.2
   @nrwl/tao               : 15.8.2
   typescript              : 4.9.5
```

### Failure Logs

```shell
BUILD SUCCESSFUL in 5s
89 actionable tasks: 2 executed, 87 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.myapp/.MainActivity }
 BUNDLE  src/main.tsx 

error: Error: Cannot resolve react-native-screens
    at /home/tnobrega/ws/other/example/node_modules/@nrwl/react-native/plugins/metro-resolver.js:31:15
    at Object.resolve (/home/tnobrega/ws/other/example/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro-resolver/src/resolve.js:27:12)
    at ModuleResolver.resolveDependency (/home/tnobrega/ws/other/example/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:111:31)
    at DependencyGraph.resolveDependency (/home/tnobrega/ws/other/example/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/home/tnobrega/ws/other/example/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/home/tnobrega/ws/other/example/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/home/tnobrega/ws/other/example/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Graph._addDependency (/home/tnobrega/ws/other/example/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 2)
```

### Additional Information

If I check app node-modules, the `ract-native-screens` is NOT there.

If I run `npm i` again and then `react-native start` and `react-native run-android` it does not complain about the missing dependency.

**Comment by xiongemi** [comment]
i think this is intentional. nx support the single-version policy. the node_modules in app folder is just a proxy to the root's node_modules. I think you can still install react-native-screens at root.

**Comment by tiagobnobrega** [comment]
@xiongemi Thanks for clarifying that.

> i think this is intentional. nx support the single-version policy. the node_modules in app folder is just a proxy to the root's node_modules. I think you can still install react-native-screens at root.

Yes, this works and is what I'm leaning towards. But this could lead to some troubles if you need to develop different apps for different clients/devices. Let's say You want to develop one app for android/ios, but a different one for TVs. You might be forced to remain in some old RN (or any lib) version.

Is there any specific reason for this? 

I've managed to work around this by calling the react-native cli directly in the project. But that means losing a bunch of goodies nx brings to the table. Is there a way to opt out of this single-version policy?
