### ISSUE TITLE
NX   Cannot read properties of undefined (reading 'defaultProject')

### ISSUE THREAD

**Issue by yehonadav** [nrwl/nx#15435]
### Current Behavior

`nx serve my-next-app`  
breaks with this error:
```
 >  NX   Cannot read properties of undefined (reading 'defaultProject')


TypeError: Cannot read properties of undefined (reading 'defaultProject')
    at Workspaces.calculateDefaultProjectName (C:\git\Feel\node_modules\@nrwl\next\node_modules\nx\src\config\workspaces.js:41:23)
    at readTargetOptions (C:\git\Feel\node_modules\@nrwl\next\node_modules\@nrwl\devkit\src\executors\read-target-options.js:20:31)
    at serveExecutor_1 (C:\git\Feel\node_modules\@nrwl\next\src\executors\server\server.impl.js:25:61)
    at serveExecutor_1.next (<anonymous>)
    at resume (C:\git\Feel\node_modules\tslib\tslib.js:230:48)
    at C:\git\Feel\node_modules\tslib\tslib.js:229:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (C:\git\Feel\node_modules\tslib\tslib.js:229:67)
    at C:\git\Feel\node_modules\nx\src\command-line\run.js:52:35
    at Generator.next (<anonymous>)

```

### Expected Behavior

```
> nx serve my-next-app

info  - automatically enabled Fast Refresh for 1 custom loader
event - compiled client and server successfully in 3.5s (169 modules)
[ ready ] on http://localhost:4200
wait  - compiling / (client and server)...
event - compiled client and server successfully in 371 ms (185 modules)
```

### Steps to Reproduce

1. run `nx serve my-next-app`

### Nx Report

```shell
>  NX   Cannot read properties of undefined (reading 'defaultProject')


TypeError: Cannot read properties of undefined (reading 'defaultProject')
    at Workspaces.calculateDefaultProjectName (C:\git\Feel\node_modules\@nrwl\next\node_modules\nx\src\config\workspaces.js:41:23)
    at readTargetOptions (C:\git\Feel\node_modules\@nrwl\next\node_modules\@nrwl\devkit\src\executors\read-target-options.js:20:31)
    at serveExecutor_1 (C:\git\Feel\node_modules\@nrwl\next\src\executors\server\server.impl.js:25:61)
    at serveExecutor_1.next (<anonymous>)
    at resume (C:\git\Feel\node_modules\tslib\tslib.js:230:48)
    at C:\git\Feel\node_modules\tslib\tslib.js:229:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (C:\git\Feel\node_modules\tslib\tslib.js:229:67)
    at C:\git\Feel\node_modules\nx\src\command-line\run.js:52:35
    at Generator.next (<anonymous>)
```

### Additional Information

hi, this error happened to me in a private repo so i can't really share it.
i already troubleshooted the issue...
if somebody can do a pull request real quick that would be awesome:

at Workspaces.calculateDefaultProjectName 
\node_modules\@nrwl\next\node_modules\nx\src\config\workspaces.js:38:23

```
        return nxJson.defaultProject;
```
just replace this line with
```
        return nxJson?.defaultProject;
```
![image](https://user-images.githubusercontent.com/35917238/222831411-efe9211c-b056-4c5c-aae2-cb9d64e5a4f0.png)

**Comment by yehonadav** [comment]
please someone submit a fix like the provided solution 
its 1 char of code

**Comment by FrozenPandaz** [comment]
What a conicidence:

Closed here: https://github.com/nrwl/nx/pull/15432
