### ISSUE TITLE
federatedModules: shared lib dependency (@apollo/client) causes "eager consumption" error

### ISSUE THREAD

**Issue by LironHazan** [nrwl/nx#15475]
### Current Behavior

Hey 👋 
I'm trying to setup a tiny module as federated one. 
The shell and the remote module are both in React:
 `"react": "18.2.0"`
`"@nrwl/react": "15.7.2" `

My repo is structured as follows:
- apps:
  - shell/host app (contains only app routes)
  - hosted app (contains only app routes)
- libs:
  -  shell features broken into libs (maximizing import boundries + tags/scope :P AWESOME feature)
  - app module features broken into libs
  - shared/common libs e.g. data-access related 

The host configuration

```javascript
module.exports = composePlugins(
  withNx(),
  withReact(),
  async (config, { options, context }) => {
  const federatedModules = await withModuleFederation({
    name: 'shell-app',
    remotes: [
      ['react-test-app', '//localhost:3001/'],
    ],
    // Tod avoid: Uncaught Error: Shared module is not available for eager consumption
    shared: (dep, sconfig) => {
      if (dep.startsWith('@apollo/client')) {
        //return false;
        return {
          eager: true,
          requiredVersion: dependencies['@apollo/client'],
          strictVersion: true,
        };
      }
      return {
        ...sconfig,
        eager: true,
        strictVersion: false,
      };
    },
    additionalShared: [
      '@apollo/client',
      'graphql',
    ]
  });

});
````

The remote configuration 

```javascript
  const federatedModules = await withModuleFederation({
    name: 'react-test-app',
    exposes: {
      './Module': './src/remote-entry.ts',
    },
    shared: (dep, sconfig) => {
      if (dep.startsWith('@apollo/client')) {
        return false;
      }
      return {
        ...sconfig,
        eager: true,
        strictVersion: false,
      };
    }
  });
``` 

The error I'm getting seem to come from the shared lib ( /libs/shared/data/data-access/) which also consumes ```'@apollo/client'```.

```
consumes:184 Uncaught Error: Shared module is not available for eager consumption: webpack/sharing/consume/default/@apollo/client/@apollo/client
    at __webpack_require__.m.<computed> (consumes:184:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ../../libs/shared/data/data-access/src/lib/Utils/clientSetup.ts (index.ts:28:50)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ../../libs/shared/data/data-access/src/index.ts (topics.ts:82:23)
    at options.factory (react refresh:6:1)
```

I started getting it after adding the **additionalShared** list in the host config, before that I was getting errors related to the apolo client version etc..
According to the docs, "withModuleFederation" should take care of my shared libs config.
I maybe missing something,

Will appreciate your help,
I really LOVE the NX tools :))

### Expected Behavior

Should load third parties and other shared dependencies properly.

### Steps to Reproduce

I may create a side repo soon

### Nx Report

```shell
Node : 16.10.0
   OS   : darwin x64
   npm  : 7.24.2
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/react             : 15.7.2
   @nrwl/rollup            : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/vite              : 15.7.2
   @nrwl/web               : 15.7.2
   @nrwl/webpack           : 15.7.2
   @nrwl/nx-cloud          : 15.0.3
   typescript              : 4.8.4
```

**Comment by LironHazan** [comment]
After isolating the issue, I saw it's not related directly to the apollo client, if using the client instance in scope of the app it will work so it's not an NX bug on any manner.
