### ISSUE TITLE
`jest` fails with error when running as a standalone

### ISSUE THREAD

**Issue by Lonli-Lokli** [nrwl/nx#15657]
### Current Behavior

`"test:ci": "node --max_old_space_size=4096 node_modules/jest/bin/jest.js --collectCoverage=true --coverageProvider=v8",`

Ends with error
`Error: Can't find a root directory while resolving a config file path.`

### Expected Behavior

Jest can work independently from Nx

### Steps to Reproduce

Unfortunately I cannot create them with Nx13

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 14.18.1
   OS   : win32 x64
   npm  : 8.19.3

   nx : 13.10.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.6
   @nrwl/eslint-plugin-nx : 13.10.6
   @nrwl/express : 13.10.6
   @nrwl/jest : 13.10.6
   @nrwl/js : 13.10.6
   @nrwl/linter : 13.10.6
   @nrwl/nest : 13.10.6
   @nrwl/next : Not Found
   @nrwl/node : 13.10.6
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.6
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.6
   @nrwl/web : 13.10.6
   @nrwl/workspace : 13.10.6
   typescript : 4.9.5
   rxjs : 7.5.6
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
> dashboards@0.0.0 test:ci
> node --max_old_space_size=4096 node_modules/jest/bin/jest.js

Error: Can't find a root directory while resolving a config file path.
Provided path to resolve: D:\sources\rmboa\libs\core\notification
cwd: D:\sources\rmboa
    at _default (D:\sources\rmboa\node_modules\@jest\core\node_modules\jest-config\build\resolveConfigPath.js:130:11)
    at readConfig (D:\sources\rmboa\node_modules\@jest\core\node_modules\jest-config\build\index.js:228:49)
    at D:\sources\rmboa\node_modules\@jest\core\node_modules\jest-config\build\index.js:462:18
    at Array.map (<anonymous>)
    at readConfigs (D:\sources\rmboa\node_modules\@jest\core\node_modules\jest-config\build\index.js:456:10)
    at async runCLI (D:\sources\rmboa\node_modules\@jest\core\build\cli\index.js:132:59)
    at async Object.run (D:\sources\rmboa\node_modules\jest\node_modules\jest-cli\build\cli\index.js:155:37)
```

**Comment by Lonli-Lokli** [comment]
It happens even after upgrade to the latest version
```
 >  NX   Report complete - copy this into the issue template

   Node : 14.18.1
   OS   : win32 x64
   npm  : 8.19.3

   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/express           : 15.8.6
   @nrwl/nest              : 15.8.6
   @nrwl/node              : 15.8.6
   @nrwl/react             : 15.8.6
   @nrwl/rollup            : 15.8.6
   @nrwl/storybook         : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/web               : 15.8.6
   @nrwl/webpack           : 15.8.6
   typescript              : 4.9.5
```

**Comment by barbados-clemens** [comment]
@Lonli-Lokli do you have a cloneable repo I can take a look at I just tried this and could not reproduce the issue.

**Comment by Lonli-Lokli** [comment]
@barbados-clemens I found an issue in jest repo where they fixed a regression so upgrade fixed my issue
