### ISSUE TITLE
nrwl/js:tsc does not take into account a custom rootDir when returning mainOutputPath

### ISSUE THREAD

**Issue by wadamek65** [nrwl/nx#15719]
### Current Behavior

When you specify the "rootDir" option in @nrwl/js:tsc executor, the calculated path may be invalid depending on the compiled files.

### Expected Behavior

The path returned is correct or is customizable.

### Steps to Reproduce

1. Setup a basic repo.
2. Change the rootDir option to for example `../`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   npm  : 8.19.3

   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/next              : 15.8.6
   @nrwl/node              : 15.8.6
   @nrwl/react             : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/webpack           : 15.8.6
   typescript              : 4.9.5
```

### Failure Logs

```shell
Error: Cannot find module 'C:\code\work\X\dist\packages\app\server\main.js'                                      
Require stack:                                                                                                           
- C:\code\work\X\node_modules\@nrwl\js\src\executors\node\node-with-require-overrides.js                         
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)                                        
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)                                                   
    at Function.Module._load (C:\code\work\X\packages\js\src\executors\node\node-with-require-overrides.ts:16:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)                                                         
    at require (node:internal/modules/cjs/helpers:102:18)                                                                
    at Object.<anonymous> (C:\code\work\X\packages\js\src\executors\node\node-with-require-overrides.ts:20:1)    
    at Module._compile (node:internal/modules/cjs/loader:1101:14)                                                        
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)                                          
    at Module.load (node:internal/modules/cjs/loader:981:32)                                                             
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

### Additional Information

This is probably caused by the following logic:

https://github.com/nrwl/nx/blob/5e88d1d7d15c8f54f445e4cc58b4dade28e30622/packages/js/src/executors/tsc/tsc.impl.ts#L74-L78

Background: I was trying to set up a `nrwl/next` application with a custom server. I wanted to move the API files to a separate library that I created using `nrwl/node` generators and set up path aliases. Unfortunately after setting it up, the app would no longer compile because it threw TS compilation errors about files not being under the `rootDir` of the project. The only fix that I managed to find was to overwrite this in executor options, but then the `nrwl/js:node` executor stops working because it's trying to run a file that does not exist because the path is incorrect.

**Comment by xiejay97** [comment]
`rootDir` should be absolute paths.
