### ISSUE TITLE
Cannot find module '/path-to-mydir/dist/libs/my-lib'

### ISSUE THREAD

**Issue by tigredonorte** [nrwl/nx#15751]
### Current Behavior

If I run nx serve api and import something from a lib, I have to build the lib.

### Expected Behavior

I expect to not have to run nx build model everytime that I make some changes into this module (while I'm developing at least)

### Steps to Reproduce

I created a new app using the nx tools. I used the following commands:

1. pnpm create nx-workspace wefit --preset=react --appName=web
2. pnpm add -D @nrwl/express
3. nx g @nrwl/express:app api --frontendProject=web
4. nx g @nrwl/web:lib models

on libs/model/src/lib/model.ts:
```
export type MyType = {
  title: string;
  id: number;
};
```

then I imported it on apps/api/src/main.ts
```
import express from 'express';
import { MyType } from '@wefit/model';

const data: MyType = [
     {
         title: 'mytitle',
         id: 1
     }
]
const app = express();

app.get('/api/data', (req, res) => {
  res.send(tickets);
});

const port = process.env.port || 3000;
const server = app.listen(port, () => {
  console.log(`Listening at http://localhost:${port}/api`);
});
server.on('error', console.error);
```

when I run nx serve api, I get the following error:
```
nx run api:serve:development

[ watch ] build succeeded, watching for changes...
Debugger listening on ws://localhost:9229/55876d37-7128-4d7d-be62-071db5fd3bc1
For help, see: https://nodejs.org/en/docs/inspector
Error: Cannot find module '/wefit/dist/libs/model'
Require stack:
- /wefit/dist/apps/api/apps/api/src/main.js
- /wefit/dist/apps/api/main.js
- /wefit/node_modules/.pnpm/@nrwl+js@15.8.7_ezoeqglmlu35vldo4ojpubhjcm/node_modules/@nrwl/js/src/executors/node/node-with-require-overrides.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._resolveFilename (/wefit/tmp/api/main-with-require-overrides.js:41:36)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.Module._load (/wefit/node_modules/.pnpm/@nrwl+js@15.8.7_ezoeqglmlu35vldo4ojpubhjcm/packages/js/src/executors/node/node-with-require-overrides.ts:14:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/wefit/apps/api/src/main.ts:2:25)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
```

my tsconfig.base.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@wefit/model": ["libs/model/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}

```

taking a look on dist folder, it seems the files are generated on wrong folder:
![image](https://user-images.githubusercontent.com/648890/226151143-789107e6-ca45-4ccc-aeab-e9609f46dea8.png)

### Nx Report

```shell
nx                      : 15.8.7
   @nrwl/js                : 15.8.7
   @nrwl/jest              : 15.8.7
   @nrwl/linter            : 15.8.7
   @nrwl/workspace         : 15.8.7
   @nrwl/cli               : 15.8.7
   @nrwl/cypress           : 15.8.7
   @nrwl/esbuild           : 15.8.7
   @nrwl/eslint-plugin-nx  : 15.8.7
   @nrwl/express           : 15.8.7
   @nrwl/nest              : 15.8.7
   @nrwl/node              : 15.8.7
   @nrwl/react             : 15.8.7
   @nrwl/tao               : 15.8.7
   @nrwl/webpack           : 15.8.7
   typescript              : 4.9.5
```

### Failure Logs

```shell
Error: Cannot find module '/wefit/dist/libs/model'
Require stack:
- /wefit/dist/apps/api/apps/api/src/main.js
- /wefit/dist/apps/api/main.js
- /wefit/node_modules/.pnpm/@nrwl+js@15.8.7_ezoeqglmlu35vldo4ojpubhjcm/node_modules/@nrwl/js/src/executors/node/node-with-require-overrides.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._resolveFilename (/wefit/tmp/api/main-with-require-overrides.js:41:36)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.Module._load (/wefit/node_modules/.pnpm/@nrwl+js@15.8.7_ezoeqglmlu35vldo4ojpubhjcm/packages/js/src/executors/node/node-with-require-overrides.ts:14:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/wefit/apps/api/src/main.ts:2:25)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
```

**Comment by tigredonorte** [comment]
It's not fixed
