### ISSUE TITLE
bug(run-commands): Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by AdditionAddict** [nrwl/nx#15771]
### Current Behavior

I keep getting this error after my command succeeds  when including configuration

e.g. `yarn nx deploy procurment --configuration=production`

### Expected Behavior

No error

### Steps to Reproduce

1. Create an angular project
2. Add configurations
3. Run a command that uses the configuration

### Nx Report

```shell
Node : 16.17.1
   OS   : win32 x64
   yarn : 3.4.1
   
   nx : 15.2.4
   @nrwl/angular : 15.2.4
   @nrwl/cypress : 15.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.4
   @nrwl/js : 15.2.4
   @nrwl/linter : 15.2.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.2.4
   @nrwl/nx-cloud : 15.1.1
   @nrwl/nx-plugin : 15.2.4
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.4
   @nrwl/web : 15.2.4
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 15.2.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         @extruda/plugin
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 15.2.1
         @ngrx/data: 15.2.1
         @ngrx/effects: 15.2.1
         @ngrx/entity: 15.2.1
         @ngrx/router-store: 15.2.1
         @ngrx/store: 15.2.1
         @ngrx/schematics: 15.0.0
         @ngrx/store-devtools: 15.0.0
         @storybook/angular: 6.5.13
```

### Failure Logs

```shell
>  NX   Successfully ran target deploy for project procurement



 >  NX   RunEnd. Completed tasks

   
[]

RunEnd duration: 116
   View logs and run details at https://cloud.nx.app/runs/PjSinG6ENz


 >  NX   Cannot read properties of undefined (reading 'split')
```
```


### Additional Information

As a slight aside the way commands are run means I cannot name any target with a colon "test:ci" because this gets interpreted as a configuration on the "test" target.

**Comment by AgentEnder** [comment]
That target doesn't have any configurations, so I'd expect it to fail although the logged output is a bit weird. Can you rerun with --verbose so that we can see the stack trace?

**Comment by AdditionAddict** [comment]
@AgentEnder apologies, put this from memory but I did have configuration

```
    "deploy": {
      "command": "firebase deploy --only hosting:procurement",
      "configurations": {
        "production": {}
      }
    }
  },
```

The verbose trace isn't that much more helpful. Nothing on the nx cloud logs either.

```
>nx deploy procurement --configuration=production --verbose

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Successfully ran target deploy for project procurement



 >  NX   RunEnd. Completed tasks


[]

RunEnd duration: 264
   View logs and run details at https://cloud.nx.app/runs/----------------------


 >  NX   Cannot read properties of undefined (reading 'split')


TypeError: Cannot read properties of undefined (reading 'split')
    at getExecutorForTask (C:\myOrg\node_modules\nx\src\tasks-runner\utils.js:176:49)  
    at getCustomHasher (C:\myOrg\node_modules\nx\src\tasks-runner\utils.js:181:21)     
    at C:\myOrg\node_modules\nx\src\hasher\hash-task.js:21:58
    at Generator.next (<anonymous>)
    at C:\myOrg\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\myOrg\node_modules\tslib\tslib.js:114:16)
    at hashTask (C:\myOrg\node_modules\nx\src\hasher\hash-task.js:20:20)
    at TasksSchedule.<anonymous> (C:\myOrg\node_modules\nx\src\tasks-runner\tasks-schedule.js:62:48)
    at Generator.next (<anonymous>)
```

**Comment by AgentEnder** [comment]
The stack trace is meant to be helpful for us - it points us to the lines of code that are throwing, not necessarily end users. I'll look into this.

**Comment by AgentEnder** [comment]
The `command` syntax support was added in 15.3.0, I can confirm this works on latest: https://github.com/nrwl/nx/pull/13139
![image](https://user-images.githubusercontent.com/6933928/226412145-3dab509c-f28d-4936-a1f1-3ec86d033fe6.png)
