### ISSUE TITLE
Cannot find module 'typescript

### ISSUE THREAD

**Issue by tomani77** [nrwl/nx#1581]
while trying to create new workspace using command "npx create-nx-workspace myworkspace" i am getting error -

ng new "myworkspace" --collection=@nrwl/workspace
Cannot find module 'typescript'
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/manish/node_modules/@nrwl/workspace/src/utils/ast-utils.js:14:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/manish/node_modules/@nrwl/workspace/src/schematics/ng-new/ng-new.js:16:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
Command failed: "/var/folders/2d/5l6zm8nd3330lvlzx0hs53tm0000gn/T/tmp-1880PP8fyPVRMlpX/node_modules/.bin/ng" new "myworkspace" --collection=@nrwl/workspace

Global version installed - 
Typescript  - Version 3.1.6
@nrwl/schematics@8.2.0

**Comment by nortain** [comment]
I seem to be getting a similar error whenever I try to invoke any nx command.  Such as  "nx affected:libs"

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:15:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by ramir000** [comment]
try this npx create-nx-workspace@8.3.0 myworkspace

**Comment by bcabanes** [comment]
Hi @tomani77!
Can you try again with the latest version please! It should work now.

I'm closing the issue, don't hesitate to create a new one if it reappears.

**Comment by demisx** [comment]
I was checking out NX today following the [Getting Started Guide](https://nx.dev/angular/getting-started/getting-started) and got this error. This is what I ran:

```sh
$ npm install @nrwl/schematics @angular/cli
$ npx create-nx-workspace@latest dl
--------
npx: installed 166 in 6.481s
? What to create in the new workspace empty             [an empty workspace]
? CLI to power the Nx workspace       Angular CLI  [Extensible CLI for Angular applications. Recommended for Angular projects.]
Creating a sandbox with Nx...
added 328 packages from 215 contributors and audited 3130 packages in 5.433s
found 0 vulnerabilities

new dl --preset="empty" --collection=@nrwl/workspace
An unhandled exception occurred: Cannot find module 'typescript'
Require stack:
- /Users/dmoore/projects/bm/dl/mono/node_modules/@nrwl/workspace/src/utils/ast-utils.js
- /Users/dmoore/projects/bm/dl/mono/node_modules/@nrwl/workspace/src/schematics/shared-new/shared-new.js
- /Users/dmoore/projects/bm/dl/mono/node_modules/@nrwl/workspace/src/schematics/ng-new/ng-new.js
- /Users/dmoore/projects/bm/dl/mono/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/dmoore/projects/bm/dl/mono/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/dmoore/projects/bm/dl/mono/node_modules/@angular/cli/utilities/json-schema.js
- /Users/dmoore/projects/bm/dl/mono/node_modules/@angular/cli/models/command-runner.js
- /Users/dmoore/projects/bm/dl/mono/node_modules/@angular/cli/lib/cli/index.js
- /private/var/folders/yn/tfydvv613h95b9364681z6k00000gn/T/tmp-67270xg5I4dzsqrFK/node_modules/@angular/cli/lib/init.js
- /private/var/folders/yn/tfydvv613h95b9364681z6k00000gn/T/tmp-67270xg5I4dzsqrFK/node_modules/@angular/cli/bin/ng
See "/private/var/folders/yn/tfydvv613h95b9364681z6k00000gn/T/ng-DpIb5u/angular-errors.log" for further details.
(node:67270) UnhandledPromiseRejectionWarning: Error: Command failed: "/var/folders/yn/tfydvv613h95b9364681z6k00000gn/T/tmp-67270xg5I4dzsqrFK/node_modules/.bin/ng" new dl --preset="empty" --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at createApp (/Users/dmoore/.npm/_npx/67270/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:356:21)
    at /Users/dmoore/.npm/_npx/67270/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:74:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:67270) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:67270) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This happened because I didn't have typescript installed neither locally, nor globally. After `npm install typescript` the error went away. Maybe the getting started guide should mention this step?

**Comment by OP-Klaus** [comment]
I got this during the getting started guide just now as well, on the latest version

**Comment by capJavert** [comment]
@bcabanes this is happening again in latest version `13.1.3`, workspace creation is unusable.

**Comment by humkins** [comment]
for me it was reproduced when I switched back to `yarn` with `useWorkspaces: false` and `nx` version `14.2`. After upgrading `nx` to version `14.4` (also tried with `14.7`) the problem have been fixed. But with version `14.3` it was still reproduced.
