### ISSUE TITLE
NX cannot create the package-lock.json file

### ISSUE THREAD

**Issue by janosroska** [nrwl/nx#15856]
### Current Behavior

When using aws-sdk, the build process cannot create the package-lock.json file. 

### Expected Behavior

The expected operation would be as follows:
1. please make the package-lock.json file creation configurable (CR)
**2. package-lock.json should be created without errors (bugfix)**

### GitHub Repo

https://github.com/janosroska/package_lock_bug

### Steps to Reproduce

When using the package aws-sdk during development, the build process throws an error, see the error message below.

### Nx Report

```shell
Node : 16.19.1
   OS   : win32 x64
   npm  : 8.19.3

   nx                      : 15.8.7
   @nrwl/js                : 15.8.7
   @nrwl/jest              : 15.8.7
   @nrwl/linter            : 15.8.7
   @nrwl/workspace         : 15.8.7
   @nrwl/cli               : 15.8.7
   @nrwl/devkit            : 15.8.7
   @nrwl/eslint-plugin-nx  : 15.8.7
   @nrwl/nest              : 15.8.7
   @nrwl/node              : 15.8.7
   @nrwl/tao               : 15.8.7
   @nrwl/webpack           : 15.8.7
   typescript              : 4.9.5
```

### Failure Logs

```shell
d:\NX_BUG_REPROD\package_lock_bug\myorg>npx nx run myapp:build:development

> nx run myapp:build:development


 >  NX   An error occured while creating pruned lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.
   If you run `npm install --package-lock-only` in your output folder it will regenerate the correct pruned lockfile.

Original error: Cannot read properties of undefined (reading 'dependencies')


   TypeError: Cannot read properties of undefined (reading 'dependencies')
    at getPackageParent (d:\NX_BUG_REPROD\package_lock_bug\myorg\node_modules\nx\src\lock-file\npm-parser.js:238:21)
    at d:\NX_BUG_REPROD\package_lock_bug\myorg\node_modules\nx\src\lock-file\npm-parser.js:223:9
    at Array.forEach (<anonymous>)
    at mapV1Snapshots (d:\NX_BUG_REPROD\package_lock_bug\myorg\node_modules\nx\src\lock-file\npm-parser.js:222:20)
    at stringifyNpmLockfile (d:\NX_BUG_REPROD\package_lock_bug\myorg\node_modules\nx\src\lock-file\npm-parser.js:207:31)
    at createLockFile (d:\NX_BUG_REPROD\package_lock_bug\myorg\node_modules\nx\src\lock-file\lock-file.js:136:58)
    at d:\NX_BUG_REPROD\package_lock_bug\myorg\node_modules\@nrwl\webpack\src\plugins\generate-package-json-plugin.js:42:131
    at fn (d:\NX_BUG_REPROD\package_lock_bug\myorg\node_modules\webpack\lib\Compilation.js:478:10)
    at _next0 (eval at create (d:\NX_BUG_REPROD\package_lock_bug\myorg\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (d:\NX_BUG_REPROD\package_lock_bug\myorg\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)

chunk (runtime: main) main.js (main) 2.86 KiB [entry] [rendered]
webpack compiled successfully (7a103691a86da527)

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project myapp (7s)
```

### Additional Information

Same issue here: https://github.com/nrwl/nx/issues/15835

**Comment by natrixofficial** [comment]
+1
