### ISSUE TITLE
After NX update from 15.5.0 to 15.8.8, unable to nx generate @nrwl/angular:lib

### ISSUE THREAD

**Issue by Majky1423** [nrwl/nx#15876]
### Current Behavior

After executing 'nx generate @nrwl/angular:lib [name]', it fails with error listed in Failure logs.

### Expected Behavior

Expected > successful Nx library generating.

### Steps to Reproduce

Unable to provide an example repo or further steps at this time.

### Nx Report

```shell
Node : 16.10.0
   OS   : win32 x64
   npm  : 7.24.0

   nx                      : 15.8.8
   @nrwl/js                : 15.8.8
   @nrwl/jest              : 15.8.8
   @nrwl/linter            : 15.8.8
   @nrwl/workspace         : 15.8.8
   @nrwl/angular           : 15.8.8
   @nrwl/cli               : 15.8.8
   @nrwl/cypress           : 15.8.8
   @nrwl/devkit            : 15.8.8
   @nrwl/eslint-plugin-nx  : 15.8.8
   @nrwl/storybook         : 15.8.8
   @nrwl/tao               : 15.8.8
   @nrwl/webpack           : 15.8.8
   typescript              : 4.7.4
   ---------------------------------------
   Community plugins:
   ngx-daterangepicker-material   : 5.0.2
   rxjs                           : 6.6.7
   @migalons/angular-wdio-builder : 1.0.2
   @storybook/angular             : 7.0.0-rc.7
```

### Failure Logs

```shell
Skipping invalid project value; expected an object.
..\node_modules\rxjs\internal\util\hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

Error: 'project.json' files are incompatible with version 1 workspace schemas.
    at ..\node_modules\nx\src\adapter\angular-json.js:76:19
    at Array.forEach (<anonymous>)
    at toOldFormat (..\node_modules\nx\src\adapter\angular-json.js:74:37)
    at saveProjectsConfigurationsInWrappedSchematic (..\node_modules\nx\src\adapter\ngcli-adapter.js:650:82)
    at SafeSubscriber.recorder [as _next] (..\node_modules\nx\src\adapter\ngcli-adapter.js:551:21)
    at SafeSubscriber.__tryOrUnsub (..\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (..\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (..\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (..\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Subject.next (..\node_modules\rxjs\internal\Subject.js:60:25)
```

### Additional Information

I got same error after updating from 15.5.0 to 15.7.2, I just tried bump version to the latest but same error appears on 15.8.8

**Comment by leosvelperez** [comment]
Thanks for reporting this!

The error seems to indicate that you might have an `angular.json` with `"version": 1` and with at least one project with a string value instead of an object. Configuration using v1 should always have the projects inlined in the `angular.json` and not set as a path to a `project.json` file. This is just a guess from the error shared. You can check if that's the case.

Unfortunately, I can't reproduce this issue in a fresh new workspace or in a workspace migrated from 15.5.0 to latest. The issue seems to be specific to your setup. Please provide a repro so we can troubleshoot it properly.

**Comment by Majky1423** [comment]
I am sorry but repo is private :/ ... Version in angular.json was the first thing I checked but it is set to 2: 
```
"$schema": "./node_modules/nx/schemas/workspace-schema.json",
 "version": 2,
```

Are there any wild guesses I can try at least? :(

**Comment by barrymichaeldoyle** [comment]
We got a different error with the recent version bumps as well with our module federation react repo. One of our devRemotes is failing with a type error when running it in the shell app (it runs fine standalone).

This happened when we upgrade from `15.8.5`, it looks like `15.8.7` must have introduced the problem, because every version (tried up to ``15.8.9` since then fails. `15.8.6` is the last working version.

**Comment by leosvelperez** [comment]
@Majky1423 you shouldn't have a version 2 `angular.json`. There is a migration (`15-7-0-split-configuration-into-project-json-files`) that you should have run when migrating from a version lower than 15.7.0 to it or later that would have split any v2 workspace config file into individual `project.json`. We no longer support v2 global workspace config files (`workspace.json` or `angular.json`).

I'm not sure how the project was migrated, but it seems you might have skipped that migration somehow. If I take a project pre-v15.7.0 with an `angular.json` v2 file and migrate to latest, the file is split correctly into individual `project.json` files.

To fix your workspace config now, you can run:

```shell
nx migrate latest --from=nx@15.6.0
nx migrate --run-migrations
```

Optionally, before running the migrations, you can clean up the `migrations.json` file generated by the first command above and only leave the `15-7-0-split-configuration-into-project-json-files` migration.
