### ISSUE TITLE
Webstorm NX console plugin - Missing header Content-Length

### ISSUE THREAD

**Issue by pvds** [nrwl/nx#15873]
### Current Behavior

I regularly receive this "Internal IDE error" in webstorm caused by the NX console plugin:

```
java.lang.IllegalStateException: Missing header Content-Length in input "
"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected Behavior

No "Internal IDE error" when using the "NX console" plugin in webstorm.

### Steps to Reproduce

I can not really pinpoint the root cause the error seems to show up sometimes when:
- opening my project
- running `nx migrate latest`
- switching branch

### Nx Report

```shell
Webstorm: 2022.3.4 (Build #WS-223.8836.50)
NX console plugin: 1.2.0

---

   Node : 16.19.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx                      : 15.8.8
   @nrwl/js                : 15.8.8
   @nrwl/jest              : 15.8.8
   @nrwl/linter            : 15.8.8
   @nrwl/workspace         : 15.8.8
   @nrwl/angular           : 15.8.8
   @nrwl/cli               : 15.8.8
   @nrwl/cypress           : 15.8.8
   @nrwl/devkit            : 15.8.8
   @nrwl/eslint-plugin-nx  : 15.8.8
   @nrwl/node              : 15.8.8
   @nrwl/storybook         : 15.8.8
   @nrwl/tao               : 15.8.8
   @nrwl/webpack           : 15.8.8
   @nrwl/nx-cloud          : 15.3.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/effects        : 15.3.0
   @ngrx/router-store   : 15.3.0
   @ngrx/store          : 15.3.0
   @ngrx/store-devtools : 15.3.0
   @compodoc/compodoc   : 1.1.19
   @storybook/angular   : 6.5.16
   @twittwer/compodoc   : 1.9.0
   ng-mocks             : 14.7.1
   nx-stylelint         : 14.0.2
```

### Additional Information

The [NX console IDEA plugin](https://plugins.jetbrains.com/plugin/15101-nx-console-idea) also regularly triggered internal IDE errors in the past but had gotten much more stable.

Maybe consult with him on his experiences.

**Comment by pvds** [comment]
The label "scope: console" can be added to this issue.

**Comment by pvds** [comment]
Thanks @MaxKless I missed the fact that nx-console is in a separate repo
