### ISSUE TITLE
Can not create workspace with react-monorepo preset

### ISSUE THREAD

**Issue by ianzone** [nrwl/nx#15895]
### Current Behavior

```
❯ pnpx create-nx-workspace@latest MyRepo --preset=react-monorepo --appName=demoapp --bundler=vite --style=scss --nxCloud=false
.local/share/pnpm/store/v3/tmp/dlx-12339 |  +67 +++++++
.local/share/pnpm/store/v3/tmp/dlx-12339 | Progress: resolved 67, reused 67, downloaded 0, added 67, done

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]


 >  NX   Nx is creating your v15.8.9 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✖ Creating your workspace in my-repo

 >  NX   Nx failed to create a workspace.

   Error:

 ERROR  Command failed with exit code 1: create-nx-workspace MyRepo --preset=react-monorepo --appName=demoapp --bundler=vite --style=scss --nxCloud=false

pnpm: Command failed with exit code 1: create-nx-workspace MyRepo --preset=react-monorepo --appName=demoapp --bundler=vite --style=scss --nxCloud=false
    at makeError (/home/ian/.local/share/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:24230:17)
    at handlePromise (/home/ian/.local/share/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:24801:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/ian/.local/share/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:215154:7)
    at async /home/ian/.local/share/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:222970:21
    at async main (/home/ian/.local/share/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:222937:34)
    at async runPnpm (/home/ian/.local/share/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:223192:5)
    at async /home/ian/.local/share/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:223184:7
```

### Expected Behavior

throw no error

### Steps to Reproduce

run `pnpx create-nx-workspace@latest MyRepo --preset=react-monorepo --appName=demoapp --bundler=vite --style=scss --nxCloud=false`

### Nx Report

```shell
❯ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.12.0
   OS   : linux x64
   pnpm : 7.30.3

   nx            : 15.8.9
   @nrwl/cli     : 15.8.9
   @nrwl/devkit  : 15.8.9
   @nrwl/tao     : 15.8.9
```
```


### Failure Logs

_No response_

### Additional Information

_No response_

**Comment by mandarini** [comment]
Hi there @ianzone ! Unfortunately I could not reproduce your issue. Here are my logs:

```
pnpx create-nx-workspace@latest MyRepo --preset=react-monorepo --appName=demoapp --bundler=vite --style=scss --nxCloud=false
Library/pnpm/store/v3/tmp/dlx-1778       | Progress: resolved 1, reused 0, downloaded 0, Library/pnpm/store/v3/tmp/dlx-1778       | Progress: resolved 16, reused 8, downloaded 0,Library/pnpm/store/v3/tmp/dlx-1778       | Progress: resolved 60, reused 42, downloaded 1Library/pnpm/store/v3/tmp/dlx-1778       |  +67 +++++++
Library/pnpm/store/v3/tmp/dlx-1778       | Progress: resolved 60, reused 42, downloaded 1Library/pnpm/store/v3/tmp/dlx-1778       | Progress: resolved 67, reused 66, downloaded 1Library/pnpm/store/v3/tmp/dlx-1778       | Progress: resolved 67, reused 66, downloaded 1, added 67, done

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]


 >  NX   Nx is creating your v15.8.9 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✔ Nx has successfully created the workspace: my-repo.

 >  NX   Successfully initialized git.


 —————————————————————————————————————————————————————————————————————————————————————————


 >  NX   Nx CLI is not installed globally.

   This means that you might have to use "yarn nx" or "npx nx" to execute commands in the workspace.
   Run "yarn global add nx" or "npm install -g nx" to be able to execute command directly.


 —————————————————————————————————————————————————————————————————————————————————————————


 >  NX   First time using Nx? Check out this interactive Nx tutorial.

   https://nx.dev/react-tutorial/1-code-generation

```

and my Nx report:

```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin x64
   pnpm : 7.29.1

   nx                      : 15.8.9
   @nrwl/js                : 15.8.9
   @nrwl/linter            : 15.8.9
   @nrwl/workspace         : 15.8.9
   @nrwl/cli               : 15.8.9
   @nrwl/cypress           : 15.8.9
   @nrwl/devkit            : 15.8.9
   @nrwl/eslint-plugin-nx  : 15.8.9
   @nrwl/react             : 15.8.9
   @nrwl/tao               : 15.8.9
   @nrwl/vite              : 15.8.9
   typescript              : 4.9.5
```

**Comment by ianzone** [comment]
Hi @mandarini , I'm using WSL2, and this is my neofetch output. 
```
OS: Ubuntu 22.04.2 LTS on Windows 10 x86_64
Kernel: 5.15.90.1-microsoft-standard-WSL2
Uptime: 27 mins
Packages: 743 (dpkg)
Shell: zsh 5.8.1
Terminal: Windows Terminal
CPU: Intel i5-8250U (8) @ 1.799GHz
GPU: 1627:00:00.0 Microsoft Corporation Device 008e
Memory: 320MiB / 7871MiB
Disk (/): 26G / 251G (11%)
```
