### ISSUE TITLE
create-nx-workspace empty Error when failed to create a workspace

### ISSUE THREAD

**Issue by tomassatka** [nrwl/nx#15926]
### Current Behavior

Basic command from [tutorial](https://nx.dev/getting-started/package-based-repo-tutorial) is not working and no message is provided to know what went wrong.

```
lenovo@DESKTOP-917P3KV:/mnt/c/Users/Lenovo/Develop$ npx create-nx-workspace --version
15.8.9
lenovo@DESKTOP-917P3KV:/mnt/c/Users/Lenovo/Develop$ npx create-nx-workspace@latest package-based --preset=npm

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Enable distributed caching to make your CI faster · No

 >  NX   Nx is creating your v15.8.9 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✖ Creating your workspace in package-based

 >  NX   Nx failed to create a workspace.

   Error:
```

After quick check i updated nodejs from 12 to 19. And that fixed the issue. Since ubuntu 22.04 comes with nodejs 12 pre-installed i naturally just run the command and guessed what could be the problem. I would still appreciate to print the error that nodejs is outdated and has to be set to required minimum version. 

```
lenovo@DESKTOP-917P3KV:/mnt/c/Users/Lenovo/Develop$ rtx install nodejs@latest
[WARN] newer rtx version 1.27.8 available, currently on 1.25.6
Downloading node-v19.8.1-linux-x64.tar.gz...
-> https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.gz
Installing node-v19.8.1-linux-x64...
Installed node-v19.8.1-linux-x64 to /home/lenovo/.local/share/rtx/installs/nodejs/19.8.1
rtx nodejs@19.8.1 Trying to update node-build... ok                                                                                                                ✓ 7s lenovo@DESKTOP-917P3KV:/mnt/c/Users/Lenovo/Develop$ rtx global nodejs@19
[WARN] newer rtx version 1.27.8 available, currently on 1.25.6
nodejs 19
lenovo@DESKTOP-917P3KV:/mnt/c/Users/Lenovo/Develop$ npx create-nx-workspace@latest package-based --preset=npm

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Enable distributed caching to make your CI faster · No

 >  NX   Nx is creating your v15.8.9 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace: package-based.

 >  NX   Successfully initialized git.


 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   Nx CLI is not installed globally.

   This means that you might have to use "yarn nx" or "npx nx" to execute commands in the workspace.
   Run "yarn global add nx" or "npm install -g nx" to be able to execute command directly.


 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   First time using Nx? Check out this interactive Nx tutorial.

   https://nx.dev/core-tutorial/01-create-blog
```

### Expected Behavior

When a command fails Error is populated to understand why it failed. Or at least provide --verbose mode to know what was happening in the background.

### Steps to Reproduce

1. use nodejs 12 and run command
`npx create-nx-workspace@latest package-based --preset=npm`

### Nx Report

```shell
lenovo@DESKTOP-917P3KV:/mnt/c/Users/Lenovo/Develop/package-based$ npx nx report
nx report

Reports useful version numbers to copy into the Nx issue template

Options:
  --help     Show help                                                                                                                                         [boolean]
  --version  Show version number                                                                                                                               [boolean]

Error: Cannot find module 'fs/promises'
Require stack:
- /mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/src/daemon/client/client.js
- /mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/src/project-graph/project-graph.js
- /mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/src/command-line/report.js
- /mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/src/command-line/nx-commands.js
- /mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/bin/init-local.js
- /mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/bin/nx.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/mnt/c/Users/Lenovo/Develop/package-based/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/src/daemon/client/client.js:8:20)
    at Module._compile (/mnt/c/Users/Lenovo/Develop/package-based/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/src/daemon/client/client.js',
    '/mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/src/project-graph/project-graph.js',
    '/mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/src/command-line/report.js',
    '/mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/src/command-line/nx-commands.js',
    '/mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/bin/init-local.js',
    '/mnt/c/Users/Lenovo/Develop/package-based/node_modules/nx/bin/nx.js'
  ]
}
```

**Comment by AgentEnder** [comment]
Node 12 is under out minimum support version, which is currently the latest v14 release. Can you update and try again?

**Comment by tomassatka** [comment]
Yes. After update to node19 it worked as expected. My point here was if there would be a way how to check node version as a check and if not meeting required minimum print it out in error message. Now its bit confusing since error message is empty. I understand if not doable... was just a proposal
