### ISSUE TITLE
GitLab CI example: affected example might break if NX_BASE is 0000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by jase88** [nrwl/nx#15927]
### Documentation issue

[The current Gitlab documentation](https://nx.dev/recipes/ci/monorepo-ci-gitlab) describes that you assign two variables `NX_BASE` and `NX_HEAD` and then use them in combination with nx affected.

Using this configuration, I ran into the case where `NX_BASE` had the value `0000000000000000000000000000` and caused errors / failed in the CI.

This is of course solvable by applying a default value, for example
```bash
if [ "$NX_BASE" = "0000000000000000000000000000000000000000" ]; then NX_BASE="origin/${CI_DEFAULT_BRANCH}"; fi;
```

But I'm not sure if this is the right default.  Would be great to have a great default configuration documented. If this is too difficult because the CI requirements are too diverse and different, it would be good to list the most useful values for NX_HEAD and NX_BASE. Thus the possible paths would be transparent for the users.

// edit: that `CI_COMMIT_BEFORE_SHA` is filled with zeros happens on a new pushed branch (`CI_PIPELINE_SOURCE ` = `push`). This is also documented here: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

> CI_COMMIT_BEFORE_SHA The previous latest commit present on a branch or tag. Is always 0000000000000000000000000000000000000000 in merge request pipelines and for the first commit in pipelines for branches or tags.

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [x] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/ci/monorepo-ci-gitlab

### Additional context or description

Related tickets about Gitlab / CI documentation:
https://github.com/nrwl/nx/issues/633
https://github.com/nrwl/nx/issues/8008

**Comment by jase88** [comment]
The mentioned workaround doesn't seem to work properly on all targets
```
 NX_HEAD=$CI_COMMIT_SHA
$ echo "${NX_HEAD}"
000da1e1286a908171a63d1961214bfa0e9d1f6b
$ NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
$ if [ "$NX_BASE" = "0000000000000000000000000000000000000000" ]; then NX_BASE="$CI_DEFAULT_BRANCH"; fi;
$ echo "${NX_BASE}"
main
$ npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --configuration=ci
fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
nx affected
Run target for affected projects
Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
      --base  Base of the current branch (usually main)  [string]
or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
      --base  Base of the current branch (usually main)  [string]
      --head  Latest commit of the current branch (usually HEAD)  [string]
or using:
      --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas or spaces  [string]
      --uncommitted  Uncommitted changes  [boolean]
      --untracked    Untracked changes  [boolean]
Options:
      --help               Show help  [boolean]
      --version            Show version number  [boolean]
  -c, --configuration      This is the configuration to use when performing tasks on projects  [string]
  -t, --targets, --target  Tasks to run for affected projects  [string] [required]
      --output-style       Defines how Nx emits outputs tasks logs  [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes"]
      --exclude            Exclude certain projects from being processed  [string] [default: ""]
      --parallel           Max number of parallel processes [default is 3]  [string]
      --runner             This is the name of the tasks runner configured in nx.json  [string]
      --verbose            Prints additional information about the commands (e.g., stack traces)  [boolean] [default: false]
      --nx-bail            Stop command execution after the first failed task  [boolean] [default: false]
      --nx-ignore-cycles   Ignore cycles in the task graph  [boolean] [default: false]
      --skip-nx-cache      Rerun the tasks even when the results are available in the cache  [boolean] [default: false]
      --all                All projects  [boolean]
Examples:
  affected --target=custom-target                               Run custom target for all affected projects
  affected --target=test --parallel=5                           Run tests in parallel
  affected --target=test --all                                  Run the test target for all projects
  affected --targets=lint,test,build                            Run lint, test, and build targets for affected projects. Requires Nx v15.4+
  affected --target=test --files=libs/mylib/src/index.ts        Run tests for all the projects affected by changing the index.ts file
  affected --target=test --base=main --head=HEAD                Run tests for all the projects affected by the changes between main and HEAD (e.g., PR)
  affected --target=test --base=main~1 --head=main              Run tests for all the projects affected by the last commit on main
  affected --target=build --tag=$NX_TARGET_TASK_PROJECT:latest  Use the currently executing project name in your command.
Find more information and examples at https://nx.dev/nx/affected
Error: Command failed: git diff --name-only --no-renames --relative "main" "000da1e1286a908171a63d1961214bfa0e9d1f6b"
fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at parseGitOutput (/builds/project/node_modules/nx/src/utils/command-line-utils.js:196:41)
    at getFilesUsingBaseAndHead (/builds/project/node_modules/nx/src/utils/command-line-utils.js:193:12)
    at parseFiles (/builds/project/node_modules/nx/src/utils/command-line-utils.js:146:20)
    at projectsToRun (/builds/project/node_modules/nx/src/command-line/affected.js:102:145)
    at Object.<anonymous> (/builds/project/node_modules/nx/src/command-line/affected.js:31:26)
    at Generator.next (<anonymous>)
    at fulfilled (/builds/project/node_modules/tslib/tslib.js:164:62) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 61 6d 62 69 67 75 6f 75 73 20 61 72 67 75 6d 65 6e 74 20 27 6d 61 69 6e 27 3a 20 75 6e 6b 6e 6f 77 6e 20 72 65 76 69 73 69 6f 6e ... 135 more bytes>
  ],
  pid: 170,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 61 6d 62 69 67 75 6f 75 73 20 61 72 67 75 6d 65 6e 74 20 27 6d 61 69 6e 27 3a 20 75 6e 6b 6e 6f 77 6e 20 72 65 76 69 73 69 6f 6e ... 135 more bytes>
}
Uploading artifacts for failed job
```

**Comment by dauth-dev** [comment]
even if the variables are resolved correctly there is an error:

![image](https://user-images.githubusercontent.com/61625920/228901208-cf6f0665-99be-47f6-98aa-aa802117f3cd.png)

**Comment by jase88** [comment]
@dauth-dev your error seems to be related to a missing git installation. Make sure the docker image you're using includes it.

I deleted my previous comment about an error that occurs if setting `NX_BASE` to `main`. Using `origin/main` fixed it.

**Comment by dauth-dev** [comment]
wow, thanks for your help. Sorry, i was using the alpine image for node and missed the point that there is no git installed there.
