### ISSUE TITLE
nx init broken in v 15.9.0

### ISSUE THREAD

**Issue by daiscog** [nrwl/nx#15989]
### Current Behavior

In an existing Angular 14 project, running `npx nx@latest init` results in an error

### Expected Behavior

`npx nx@latest init` works in an Angular 14 project

### Steps to Reproduce

Run these commands in an empty dir:

```shell
npx @angular/cli@14 new example
# accept default options in prompts

cd example

npx nx@latest init

```

### Nx Report

```shell
Nothing, as not yet an nx workspace
```

### Failure Logs

```shell
nx init

Adds nx.json file and installs nx if not installed already

Options:
  --help     Show help                                                                                                                              [boolean]
  --version  Show version number                                                                                                                    [boolean]

TypeError: Invalid Version: undefined
    at new SemVer (~/.npm/_npx/f948e921c5898768/node_modules/semver/classes/semver.js:19:13)
    at compare (~/.npm/_npx/f948e921c5898768/node_modules/semver/functions/compare.js:3:3)
    at gte (~/.npm/_npx/f948e921c5898768/node_modules/semver/functions/gte.js:2:30)
    at ~/.npm/_npx/f948e921c5898768/node_modules/nx/src/nx-init/angular/legacy-angular-versions.js:77:30
    at Generator.next (<anonymous>)
    at ~/.npm/_npx/f948e921c5898768/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (~/.npm/_npx/f948e921c5898768/node_modules/tslib/tslib.js:163:16)
    at installDependencies (~/.npm/_npx/f948e921c5898768/node_modules/nx/src/nx-init/angular/legacy-angular-versions.js:73:20)
    at ~/.npm/_npx/f948e921c5898768/node_modules/nx/src/nx-init/angular/legacy-angular-versions.js:53:19
```

### Additional Information

This worked before 15.9.0 was published

**Comment by waitingsong** [comment]
I got issue too with latest version,

but if `npm i -g nx@15.8.9` then got:
```sh
 Error: ENOENT: no such file or directory, open '/__w/foo/foo/package-lock.json'
    at Object.openSync (node:fs:601:3)
    at readFileSync (node:fs:469:35)
    at lockFileHash (/__w/foo/foo/node_modules/nx/src/plugins/js/lock-file/lock-file.js:54:41)
    at /__w/foo/foo/node_modules/nx/src/plugins/js/index.js:20:57
    at Generator.next (<anonymous>)
    at /__w/foo/foo/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/__w/foo/foo/node_modules/tslib/tslib.js:163:16)
    at Object.processProjectGraph (/__w/foo/foo/node_modules/nx/src/plugins/js/index.js:17:57)
    at /__w/foo/foo/node_modules/nx/src/project-graph/build-project-graph.js:125:38 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/__w/kmore/kmore/package-lock.json'
}
Failed to process the project graph with "index". This will error in the future!
```
