### ISSUE TITLE
Cannot build web apps after updating to Nx >= 15.5.3

### ISSUE THREAD

**Issue by jaytavares** [nrwl/nx#15985]
### Current Behavior

`nx build [application]` fails with webpack/babel error.

### Expected Behavior

App should build successfully

### GitHub Repo

https://github.com/CurioVision/nx-15985-repro

### Steps to Reproduce

1. Clone repro repo
2. `npm install`
3. `nx build demo-application`

### Nx Report

```shell
Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.19.4
   
   nx                      : 15.8.9
   @nrwl/js                : 15.8.9
   @nrwl/jest              : 15.8.9
   @nrwl/linter            : 15.8.9
   @nrwl/workspace         : 15.8.9
   @nrwl/cli               : 15.8.9
   @nrwl/cypress           : 15.8.9
   @nrwl/devkit            : 15.8.9
   @nrwl/eslint-plugin-nx  : 15.8.9
   @nrwl/node              : 15.8.9
   @nrwl/react             : 15.8.9
   @nrwl/rollup            : 15.8.9
   @nrwl/storybook         : 15.8.9
   @nrwl/tao               : 15.8.9
   @nrwl/web               : 15.8.9
   @nrwl/webpack           : 15.8.9
   @nrwl/nx-cloud          : 15.3.2
   typescript              : 4.9.5
```

### Failure Logs

```shell
> nx run cloud-sql:build:staging

assets by status 17.1 KiB [cached] 9 assets
Entrypoint main = runtime.8146301c839f438b.js main.39162c643192dde7.js
Entrypoint polyfills = runtime.8146301c839f438b.js polyfills.21c7eefd71f718cc.js
Entrypoint styles = runtime.8146301c839f438b.js styles.ef46db3751d8e999.css styles.b79f02fd2e89a8dd.js


ERROR in ./src/main.tsx
Module build failed (from ../../node_modules/@nrwl/webpack/src/utils/web-babel-loader.js):
TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.loader (/Users/jay/dev/curiovision/cvbi/node_modules/@nrwl/webpack/node_modules/babel-loader/lib/index.js:153:18)

ERROR in ./src/polyfills.ts
Module build failed (from ../../node_modules/@nrwl/webpack/src/utils/web-babel-loader.js):
TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.loader (/Users/jay/dev/curiovision/cvbi/node_modules/@nrwl/webpack/node_modules/babel-loader/lib/index.js:153:18)

webpack 5.76.0 compiled with 2 errors (d05b2f523803f73e)
```

### Additional Information

I noticed this behavior after updating from 15.3 to 15.8.9 (latest). I rolled back and tested `nx migrate` with different versions between the two in order to identify that the issue I'm seeing was introduced in v15.5.3.

This does not happen in a fresh 15.8.9 Nx Workspace. So, I guess it's something with our particular workspace. 🤷‍♂️

**Comment by jaytavares** [comment]
Hey @vsavkin, here's that issue I mentioned this morning. I was able to create a small repro to aid in troubleshooting.

**Comment by jaysoo** [comment]
The `babel-loader` is resolving `@babel/core` at version 7.9, but it requires 7.15.

If you update `package.json` with these entries then it will work:

```
    "@babel/core": "7.15.0",
    "@babel/preset-env": "7.15.0",
    "@babel/preset-react": "7.14.5",
    "@babel/preset-typescript": "7.15.0",
```

We will need to pin these dependencies properly or provide migrations in the future if workspaces have them installed.
