### ISSUE TITLE
pnpx/npx create workspace errors while creating next js app

### ISSUE THREAD

**Issue by Venipa** [nrwl/nx#15992]
### Current Behavior

running create-workspace results in "empty" error, workspace has been created but not the next app

### Expected Behavior

expected a workspace with a generated app

### GitHub Repo

there is no repo since it doesnt create one.

### Steps to Reproduce

1. run command: 
```
pnpx create-nx-workspace maki-services --pm pnpm --preset next --name maki-services --appName maki-web --style styled-jsx --nxCloud false
```
2. wait for generator
3. error appears

### Nx Report

```shell
Node : 18.15.0
   OS   : win32 x64
   pnpm : 8.1.0

   nx (global)      : 15.9.0
   nx               : 15.9.0
   @nrwl/workspace  : 15.9.0
   @nrwl/cli        : 15.9.0
   @nrwl/next       : 15.9.0
   @nrwl/tao        : 15.9.0
```

### Failure Logs

```shell
>  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]


 >  NX   Nx is creating your v15.9.0 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✖ Creating your workspace in maki-services

 >  NX   Nx failed to create a workspace.

   Error:

 ERROR  Command failed with exit code 1: create-nx-workspace maki-services --pm pnpm --preset next --name maki-services --appName web --style styled-jsx --nxCloud false
```

**Comment by ndcunningham** [comment]
Can you add a `--verbose` or show what error you got?
We have test cases that cover installing with npm/yarn/pnpm

**Comment by Venipa** [comment]
> Can you add a `--verbose` or show what error you got? We have test cases that cover installing with npm/yarn/pnpm

```
# pnpx create-nx-workspace maki-services --pm pnpm --preset next --name maki-services --appName web --style scss --nxCloud false --verbose
../.pnpm-store/v3/tmp/dlx-33832          |  +67 +++++++
../.pnpm-store/v3/tmp/dlx-33832          | Progress: resolved 67, reused 66, downloaded 1, added 67, done

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]


 >  NX   Nx is creating your v15.9.2 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✖ Creating your workspace in maki-services

 >  NX   Nx failed to create a workspace.

   Error:

 ERROR  Command failed with exit code 1: create-nx-workspace maki-services --pm pnpm --preset next --name maki-services --appName web --style scss --nxCloud false --verbose

pnpm: Command failed with exit code 1: create-nx-workspace maki-services --pm pnpm --preset next --name maki-services --appName web --style scss --nxCloud false --verbose
    at makeError (C:\ProgramData\nvm\v18.15.0\node_modules\pnpm\dist\pnpm.cjs:24235:17)
    at handlePromise (C:\ProgramData\nvm\v18.15.0\node_modules\pnpm\dist\pnpm.cjs:24806:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (C:\ProgramData\nvm\v18.15.0\node_modules\pnpm\dist\pnpm.cjs:212270:7)
    at async C:\ProgramData\nvm\v18.15.0\node_modules\pnpm\dist\pnpm.cjs:221602:21
    at async main (C:\ProgramData\nvm\v18.15.0\node_modules\pnpm\dist\pnpm.cjs:221569:34)
    at async runPnpm (C:\ProgramData\nvm\v18.15.0\node_modules\pnpm\dist\pnpm.cjs:221824:5)
    at async C:\ProgramData\nvm\v18.15.0\node_modules\pnpm\dist\pnpm.cjs:221816:7
```

**Comment by CinnamonRage** [comment]
I'm having the same issues. Any help would be appreciated.

**Comment by ChristophWolfPCG** [comment]
same issue with just react. not using nx then when even the install fails. byebye

**Comment by me82852578** [comment]
I'm having the same issues, too.

**Comment by ndcunningham** [comment]
I tried this running `app/` or `pages/` router and both are working as expected.

Can you try again with the latest version of Nx?
