### ISSUE TITLE
Impossible to install storybook 7 for the first time

### ISSUE THREAD

**Issue by corentingosselin** [nrwl/nx#16012]
### Current Behavior

I followed this documentation:
https://nx.dev/packages/storybook/documents/storybook-7-setup    

but when I run:
npx nx build-storybook front-desktop   

I get this error:   
```
info => Using angular project with "tsConfig:/home/project/front-ng/apps/front-desktop/.storybook/tsconfig.json"
WARN No story files found for the specified pattern: apps/front-desktop/src/app/**/*.stories.@(js|jsx|ts|tsx|mdx)
    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
info => Using default Webpack5 setup
9% setup compilation SourceMapDevToolPlugin/home/project/front-ng/node_modules/.pnpm/webpack@5.76.1_esbuild@0.17.8/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:143
                        throw new TypeError(
                              ^


TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/home/project/front-ng/node_modules/.pnpm/webpack@5.76.1_esbuild@0.17.8/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:143:10)
    at SourceMapDevToolModuleOptionsPlugin.apply (/home/project/front-ng/node_modules/.pnpm/webpack@5.76.1_esbuild@0.17.8/node_modules/webpack/lib/SourceMapDevToolModuleOptionsPlugin.js:50:27)
    at <anonymous> (/home/project/front-ng/node_modules/.pnpm/webpack@5.76.1_esbuild@0.17.8/node_modules/webpack/lib/SourceMapDevToolPlugin.js:163:53)
    at _next0 (eval at create (/home/project/front-ng/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:207:1)
    at Hook.eval [as call] (eval at create (/home/project/front-ng/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:286:1)
    at Hook.CALL_DELEGATE (/home/project/front-ng/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/project/front-ng/node_modules/.pnpm/webpack@5.77.0/node_modules/webpack/lib/Compiler.js:1122:26)
    at <anonymous> (/home/project/front-ng/node_modules/.pnpm/webpack@5.77.0/node_modules/webpack/lib/Compiler.js:1166:29)
    at _next0 (eval at create (/home/project/front-ng/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:23:1)
    at eval (eval at create (/home/project/front-ng/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:35:1)

Node.js v18.15.0
```

### Expected Behavior

Storybook build

### Steps to Reproduce

1. npm install -D @nrwl/storybook
2. nx g @nrwl/storybook:configuration front-desktop --storybook7Configuration --storybook7UiFramework=@storybook/angular
3. npx storybook@next upgrade --prerelease --config-dir apps/front-desktop/.storybook
4. npx nx build-storybook front-desktop

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 18.15.0
   OS   : linux x64
   pnpm : 8.1.0

   nx                      : 15.9.1
   @nrwl/js                : 15.9.1
   @nrwl/jest              : 15.9.1
   @nrwl/linter            : 15.9.1
   @nrwl/workspace         : 15.9.1
   @nrwl/angular           : 15.9.1
   @nrwl/cli               : 15.9.1
   @nrwl/cypress           : 15.9.1
   @nrwl/eslint-plugin-nx  : 15.9.1
   @nrwl/storybook         : 15.9.1
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 15.3.0
   @ngrx/effects         : 15.3.0
   @ngrx/entity          : 15.3.0
   @ngrx/router-store    : 15.3.0
   @ngrx/store           : 15.3.0
   apollo-angular        : 4.0.1
   @ngrx/schematics      : 15.3.0
   @ngrx/store-devtools  : 15.3.0
   @storybook/angular    : 7.0.0
```
```


### Failure Logs

_No response_

### Additional Information

_No response_

**Comment by mandarini** [comment]
Hi there @corentingosselin ! Thanks for filing an issue, I'm looking into it now.
Just a question, though. I see you generated Storybook configuration for your project using Storybook v7 (`nx g @nrwl/storybook:configuration front-desktop --storybook7Configuration --storybook7UiFramework=@storybook/angular`). 

The question is: why did you run the `npx storybook@next upgrade --prerelease` command afterwards? Your configuration and packages are already in v7. Or was there an issue when you generated?

**Comment by mandarini** [comment]
@corentingosselin  thank you for filing this issue. Unfortunately I could not reproduce and here is my repository: https://github.com/mandarini/storybook-7-nx-angular

Can you see if there are any major differences between our repos?

However, THANK you because your issue highlighted two problems on our side:
1. Storybook 7 generation documentation does not make clear that you would benefit from using the framework-specific generator. I will make sure to stress that more.
2. Our storybook generator does not install react and react-dom, which are needed in SB7, and you had to manually run the `sb@next upgrade`. So I'll make sure to fix that as well.

**Comment by corentingosselin** [comment]
> Can you delete node_modules and try re-installing everything?

Using pnpm install is causing the webpack issue.
Using npm install --legacy-per-deeps causing another issue:
```
info => Using default Webpack5 setup
ERR! => Failed to build the preview
ERR! Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
ERR! Error: /home/project/front-ng/apps/front-desktop/src/polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
ERR!     at /home/project/front-ng/node_modules/@ngtools/webpack/src/ivy/loader.js:67:18
ERR! Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ERR! Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ERR! /home/project/front-ng/node_modules/@storybook/addon-actions/dist/chunk-KKE3V3AL.mjs depends on 'uuid-browser/v4'. CommonJS or AMD dependencies can cause optimization bailouts.
ERR! For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
ERR! /home/project/front-ng/node_modules/@storybook/blocks/dist/index.mjs depends on 'lodash/cloneDeep.js'. CommonJS or AMD dependencies can cause optimization bailouts.
ERR! For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
ERR! /home/project/front-ng/node_modules/@storybook/blocks/dist/index.mjs depends on 'lodash/pickBy.js'. CommonJS or AMD dependencies can cause optimization bailouts.
ERR! For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
ERR! /home/project/front-ng/node_modules/@storybook/blocks/dist/index.mjs depends on 'lodash/uniq.js'. CommonJS or AMD dependencies can cause optimization bailouts.
ERR! For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
ERR! /home/project/front-ng/node_modules/@storybook/react-dom-shim/dist/react-18.mjs depends on 'react-dom/client'. CommonJS or AMD dependencies can cause optimization bailouts.
ERR! For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
ERR! Error: => Webpack failed, learn more with --debug-webpack
ERR!     at /home/project/front-ng/node_modules/@storybook/builder-webpack5/dist/index.js:113:210
ERR!     at /home/project/front-ng/node_modules/webpack/lib/HookWebpackError.js:40:5
ERR!     at Hook.eval [as callAsync] (eval at create (/home/project/front-ng/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:11:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/project/front-ng/node_modules/tapable/lib/Hook.js:15:15)
ERR!     at Cache.shutdown (/home/project/front-ng/node_modules/webpack/lib/Cache.js:116:25)
ERR!     at /home/project/front-ng/node_modules/webpack/lib/Compiler.js:974:18
ERR!     at Hook.eval [as callAsync] (eval at create (/home/project/front-ng/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:15:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/project/front-ng/node_modules/tapable/lib/Hook.js:15:15)
ERR!     at Compiler.close (/home/project/front-ng/node_modules/webpack/lib/Compiler.js:969:25)
ERR!     at /home/project/front-ng/node_modules/@storybook/builder-webpack5/dist/index.js:113:156
ERR!     at finalCallback (/home/project/front-ng/node_modules/webpack/lib/Compiler.js:318:9)
ERR!     at /home/project/front-ng/node_modules/webpack/lib/Compiler.js:333:18
ERR!     at Hook.eval [as callAsync] (eval at create (/home/project/front-ng/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:23:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/project/front-ng/node_modules/tapable/lib/Hook.js:15:15)
ERR!     at onCompiled (/home/project/front-ng/node_modules/webpack/lib/Compiler.js:330:25)
ERR!     at /home/project/front-ng/node_modules/webpack/lib/Compiler.js:949:26
ERR!     at eval (eval at create (/home/project/front-ng/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:13:1)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!  Error: => Webpack failed, learn more with --debug-webpack
ERR!     at /home/project/front-ng/node_modules/@storybook/builder-webpack5/dist/index.js:113:210
ERR!     at /home/project/front-ng/node_modules/webpack/lib/HookWebpackError.js:40:5
ERR!     at Hook.eval [as callAsync] (eval at create (/home/project/front-ng/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:11:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/project/front-ng/node_modules/tapable/lib/Hook.js:15:15)
ERR!     at Cache.shutdown (/home/project/front-ng/node_modules/webpack/lib/Cache.js:116:25)
ERR!     at /home/project/front-ng/node_modules/webpack/lib/Compiler.js:974:18
ERR!     at Hook.eval [as callAsync] (eval at create (/home/project/front-ng/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:15:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/project/front-ng/node_modules/tapable/lib/Hook.js:15:15)
ERR!     at Compiler.close (/home/project/front-ng/node_modules/webpack/lib/Compiler.js:969:25)
ERR!     at /home/project/front-ng/node_modules/@storybook/builder-webpack5/dist/index.js:113:156
ERR!     at finalCallback (/home/project/front-ng/node_modules/webpack/lib/Compiler.js:318:9)
ERR!     at /home/project/front-ng/node_modules/webpack/lib/Compiler.js:333:18
ERR!     at Hook.eval [as callAsync] (eval at create (/home/project/front-ng/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:23:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/project/front-ng/node_modules/tapable/lib/Hook.js:15:15)
ERR!     at onCompiled (/home/project/front-ng/node_modules/webpack/lib/Compiler.js:330:25)
ERR!     at /home/project/front-ng/node_modules/webpack/lib/Compiler.js:949:26
ERR!     at eval (eval at create (/home/project/front-ng/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:13:1)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by mandarini** [comment]
@corentingosselin can you please verify that this is an issue with Nx? We are directly calling the `@storybook/angular:*` executors, so I think the problem may be on the Storybook side.

Can you try and see if the same issue exists on a pure angular app. For example `ng new` to create a new app, then use pnpm if possible to init storybook (`sb@next init`) and see if the issue persists?

**Comment by corentingosselin** [comment]
> @corentingosselin can you please verify that this is an issue with Nx? We are directly calling the `@storybook/angular:*` executors, so I think the problem may be on the Storybook side.
> 
> Can you try and see if the same issue exists on a pure angular app. For example `ng new` to create a new app, then use pnpm if possible to init storybook (`sb@next init`) and see if the issue persists?

To fix this issue I had to add:
`"files": ["../src/polyfills.ts"]` 
inside .storybook/tsconfig.json
