### ISSUE TITLE
Incorrect package.json generation with @nrwl/node and ESbuild leads to issues in Docker image

### ISSUE THREAD

**Issue by tanint** [nrwl/nx#16126]
### Current Behavior

I encountered an issue while trying to generate a Node.js application using `@nrwl/node` in conjunction with `ESbuild`. 
The "Intelligent package.json" feature seems to be malfunctioning, as it generates an empty package in package.json file. 
Consequently, when running `npm --prefix fastify-app --omit=dev -f install` in the Dockerfile, 
the necessary packages are not included in the resulting Docker image. 
This causes the Docker image to encounter errors, as the required packages cannot be found.

### Expected Behavior

The "Intelligent package.json" feature should function correctly by generating the necessary packages used in the generated application within the package.json file located in the dist folder. so the steps in the Docker image can successfully install the required packages.

### GitHub Repo

https://github.com/tanint/nx-node-fastify-example

### Steps to Reproduce

1. Generate new NodeJS app
`npx nx generate @nrwl/node:application fastify-app --docker --no-interactive`
2. build app
`nx run fastify-app:build:production`
3. build docker
`nx run fastify-app:docker-build`

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin arm64
   npm  : 8.19.2

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/esbuild           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```
```


### Failure Logs

```shell
2023-04-05 22:10:32 node:internal/modules/cjs/loader:1078
2023-04-05 22:10:32   throw err;
2023-04-05 22:10:32   ^
2023-04-05 22:10:32 
2023-04-05 22:10:32 Error: Cannot find module 'fastify'
2023-04-05 22:10:32 Require stack:
2023-04-05 22:10:32 - /app/node-app/apps/node-app/src/main.js
2023-04-05 22:10:32 - /app/node-app/main.js
2023-04-05 22:10:32     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
2023-04-05 22:10:32     at Module._resolveFilename (/app/node-app/main.js:32:36)
2023-04-05 22:10:32     at Module._load (node:internal/modules/cjs/loader:920:27)
2023-04-05 22:10:32     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-04-05 22:10:32     at require (node:internal/modules/cjs/helpers:110:18)
2023-04-05 22:10:32     at Object.<anonymous> (/app/node-app/apps/node-app/src/main.js:23:30)
2023-04-05 22:10:32     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-04-05 22:10:32     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-04-05 22:10:32     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-04-05 22:10:32     at Module._load (node:internal/modules/cjs/loader:958:12) {
2023-04-05 22:10:32   code: 'MODULE_NOT_FOUND',
2023-04-05 22:10:32   requireStack: [
2023-04-05 22:10:32     '/app/node-app/apps/node-app/src/main.js',
2023-04-05 22:10:32     '/app/node-app/main.js'
2023-04-05 22:10:32   ]
2023-04-05 22:10:32 }
2023-04-05 22:10:32 
2023-04-05 22:10:32 Node.js v18.15.0
```

### Additional Information

Some necessary packages were generated during the build process with Webpack, but not all of the required.

**Comment by ashar340** [comment]
+1 on this, facing the same issue

**Comment by CarlosVilasAlvarez** [comment]
Having same problem, only solution to this seems to bundle the code which could be problematic (for example packages importing things using glob).

**Comment by marc-wittwer** [comment]
Any updates on this? Thanks in advance.

**Comment by jjaybrown** [comment]
Run `yarn nx migrate next` as this resolves the issue for me, worth noting you stated webpack, but your commands creates an esbuild config.
