### ISSUE TITLE
Storybook v.7 build fail

### ISSUE THREAD

**Issue by Majky1423** [nrwl/nx#16222]
### Current Behavior

I am not able to run build-storybook after NX update to 15.8.9 (I was not using SB for a longer time but I think, the last time I built SB, I had Nx ~14.4). I am able to run just storybook ("@storybook/angular:start-storybook") command without any problems, so I think there could be problem with config after migrations but that just my humble opinion. I am providing project.json under the failure logs. Thanks for any tip.

### Expected Behavior

Successful Storybook build.

### Steps to Reproduce

Unable to provide an example repo or further steps at this time.

### Nx Report

```shell
Node : 16.10.0
   OS   : win32 x64
   npm  : 7.24.0

   nx                      : 15.8.9
   @nrwl/js                : 15.8.9
   @nrwl/jest              : 15.8.9
   @nrwl/linter            : 15.8.9
   @nrwl/workspace         : 15.8.9
   @nrwl/angular           : 15.8.9
   @nrwl/cli               : 15.8.9
   @nrwl/cypress           : 15.8.9
   @nrwl/devkit            : 15.8.9
   @nrwl/eslint-plugin-nx  : 15.8.9
   @nrwl/storybook         : 15.8.9
   @nrwl/tao               : 15.8.9
   @nrwl/webpack           : 15.8.9
   typescript              : 4.7.4
   ---------------------------------------
   Community plugins:
   ngx-daterangepicker-material   : 5.0.2
   rxjs                           : 6.6.7
   @migalons/angular-wdio-builder : 1.0.2
   @storybook/angular             : 7.0.0-rc.8
```

### Failure Logs

```shell
A lot of: 
ERR! => Failed to build the preview
ERR!8192.a49061ef.iframe.bundle.js from Terser plugin
ERR! __spreadProps is not defined
ERR! ReferenceError: __spreadProps is not defined
ERR!     at buildTerserOptions (eval at transform (\node_modules\terser-webpack-plugin\dist\minify.js:43:3), <anonymous>:71:5)
ERR!     at terserMinify (eval at transform (\node_modules\terser-webpack-plugin\dist\minify.js:43:3), <anonymous>:90:25)
ERR!     at minify (\node_modules\terser-webpack-plugin\dist\minify.js:23:10)
ERR!     at Object.transform (\node_modules\terser-webpack-plugin\dist\minify.js:44:10)
ERR!     at execFunction (\node_modules\jest-worker\build\workers\threadChild.js:148:17)
ERR!     at execHelper (\node_modules\jest-worker\build\workers\threadChild.js:127:5)
ERR!     at execMethod (\node_modules\jest-worker\build\workers\threadChild.js:131:5)
ERR!     at MessagePort.messageListener (\node_modules\jest-worker\build\workers\threadChild.js:49:7)
ERR!     at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:559:20)
ERR!     at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

And at the end:
ERR!
ERR! Error: => Webpack failed, learn more with --debug-webpack
ERR!     at null.<anonymous> (\node_modules\@storybook\builder-webpack5\dist\index.js:1:7620)
ERR!     at null.<anonymous> (\node_modules\webpack\lib\HookWebpackError.js:68:3)
ERR!     at Hook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:25:14), <anonymous>:11:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE (\node_modules\tapable\lib\Hook.js:18:14)
ERR!     at Cache.shutdown (\node_modules\webpack\lib\Cache.js:150:23)
ERR!     at null.<anonymous> (\node_modules\webpack\lib\Compiler.js:1225:15)
ERR!     at Hook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:25:14), <anonymous>:15:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE (\node_modules\tapable\lib\Hook.js:18:14)
ERR!     at Compiler.close (\node_modules\webpack\lib\Compiler.js:1218:23)
ERR!     at null.<anonymous> (\node_modules\@storybook\builder-webpack5\dist\index.js:1:7572)
ERR!
```

### Additional Information

```
{
  "name": "shared-storybook",
  "$schema": "../../../node_modules/nx/schemas/project-schema.json",
  "projectType": "library",
  "sourceRoot": "libs/shared/storybook/src",
  "targets": {
    "storybook": {
      "executor": "@storybook/angular:start-storybook",
      "options": {
        "port": 4400,
        "configDir": "libs/shared/storybook/.storybook",
        "browserTarget": "shared-storybook:build-storybook",
        "compodoc": true,
        "compodocArgs": ["-e", "json", "-d", "libs/shared/storybook"]
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
    "build-storybook": {
      "executor": "@storybook/angular:build-storybook",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputDir": "dist/storybook/shared-storybook",
        "configDir": "libs/shared/storybook/.storybook",
        "browserTarget": "shared-storybook:build-storybook",
        "compodoc": true,
        "compodocArgs": ["-e", "json", "-d", "libs/shared/storybook"],
        "styles": [
          "./libs/shared/storybook/storybook.scss"
        ]
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    }
  },
  "tags": []
}
```

**Comment by mandarini** [comment]
Hi there @Majky1423 ! Thanks for filing an issue. Unfortunately I cannot reproduce. Would it be possible to provide a minimum reproduction repository?

The way you can create a minimum reproduction repository is the following:

1. Create a new Nx workspace
2. Create an angular app or lib (or try to mimic your repo's setup)
3. Configure it to use Storybook
4. Copy your settings to the new repository
5. Make sure the issue is reproducible

This will help me get to your issue very quickly!

Thank you very much in advance!

**Comment by mandarini** [comment]
@Majky1423 I would delete `node_modules` and install all dependencies again. Then I would look in the Storybook repository, on GitHub, for similar errors, since on Nx we're just calling `@storybook/angular` directly. Then I would rerun the command with `--debug-webpack` or `--verbose` to see if any more hints are there.

Let me know if you have any updates. To me it looks like some dependency version mismatch, or some bad cache? I would also update all `@storybook/*` packages to their latest version, which is `7.0.4`.

**Comment by Majky1423** [comment]
Well, I manage to fix it by deleting both node_modules with package-lock.json and install again. Thanks anyway :)
