### ISSUE TITLE
Cannot use multiple configuration on custom config file option @nrwl/webpack:webpack

### ISSUE THREAD

**Issue by geofmigliacci** [nrwl/nx#16254]
### Current Behavior

Linked to https://github.com/nrwl/nx/issues/9453 (but not done)

When using a custom webpack config with multiples webpack configurations in it (an array) an error is thrown :

`customWebpack is not a function`

Example :

```json
// project.json
"build": {
  "executor": "@nrwl/webpack:webpack",
  "options": {
    ...
    "webpackConfig": "packages/core/webpack.config.js"
  }
},
```

```ts
// webpack.config.js
const { composePlugins, withNx, withWeb } = require('@nrwl/webpack');
const { merge } = require('webpack-merge');

module.exports = [ // The important thing is the array here
  composePlugins(withNx(), withWeb(), (config, { options, context }) => {
    return merge(config, {
      optimization: {
        minimize: true,
      },
    });
  }),
];
```

### Expected Behavior

When using an array as a webpack configuration, all the webpack configuration should be executed without any error.

### Steps to Reproduce

1. Create a js lib with webpack as executor for the build
2. Add a custom webpack with multiple config
3. Run the builder

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : win32 x64
   npm  : 8.19.3

   nx                      : 15.8.6
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/nx-plugin         : 15.9.2
   @nrwl/tao               : 15.8.6
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@15.9.2
     - @nrwl/jest@15.9.2
     - @nrwl/cli@15.9.2
     - @nrwl/devkit@15.9.2
     - @nrwl/nx-plugin@15.9.2
     - @nrwl/webpack@15.9.2

   To fix this, run `nx migrate nx@15.9.2`
```

### Failure Logs

```shell
nx run core:build


 >  NX   customWebpack is not a function


TypeError: customWebpack is not a function
    at C:\Users\geoff\sources\the-last-day\node_modules\@nrwl\webpack\src\executors\webpack\webpack.impl.js:33:26
    at Generator.next (<anonymous>)
    at C:\Users\geoff\sources\the-last-day\node_modules\tslib\tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\geoff\sources\the-last-day\node_modules\tslib\tslib.js:163:16)
    at getWebpackConfigs (C:\Users\geoff\sources\the-last-day\node_modules\@nrwl\webpack\src\executors\webpack\webpack.impl.js:18:20)   
    at webpackExecutor_1 (C:\Users\geoff\sources\the-last-day\node_modules\@nrwl\webpack\src\executors\webpack\webpack.impl.js:81:47)   
    at webpackExecutor_1.next (<anonymous>)
    at resume (C:\Users\geoff\sources\the-last-day\node_modules\tslib\tslib.js:279:48)
    at C:\Users\geoff\sources\the-last-day\node_modules\tslib\tslib.js:278:125

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Running target build for project core failed

   Failed tasks:

   - core:build
```

### Additional Information

A simple patch release could fix this behavior without breaking changes.

**Comment by AgentEnder** [comment]
We don't support using an array for this - but we provide the composePlugins function to help merge configs. To support multiple configuration entries here, just add a new function into the composePlugins call, similar to the one that you already have.

**Comment by geofmigliacci** [comment]
> We don't support using an array for this - but we provide the composePlugins function to help merge configs. To support multiple configuration entries here, just add a new function into the composePlugins call, similar to the one that you already have.

By doing so:

```
module.exports = composePlugins(
  withNx(),
  withWeb(),
  (config, { options, context }) => {
    return merge(config, {
      entry: {
        main: path.resolve(__dirname, 'src/client/main.ts'),
      },
      output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'client'),
      },
      optimization: {
        minimize: true,
      },
    });
  },
  (config, { options, context }) => {
    return merge(config, {
      entry: {
        main: path.resolve(__dirname, 'src/server/main.ts'),
      },
      output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'server'),
      },
      optimization: {
        minimize: true,
      },
    });
  }
);```

Just the last configuration is taken into account. So it generate only a bundle "main.js" into a "server" directory (it was for testing). What I'd like is to have (at the end) is a bundle for my client & server like so:

- my-package/client/main.js
- my-package/server/main.js
- my-package/myasset.png

With only one package. Any way to achieve that?

Thank you for your answer.

**Comment by geofmigliacci** [comment]
> We don't support using an array for this - but we provide the composePlugins function to help merge configs. To support multiple configuration entries here, just add a new function into the composePlugins call, similar to the one that you already have.

Thank you for your answer. It helped alot.

**Comment by geofmigliacci** [comment]
I've done this:

```ts
module.exports = composePlugins(
  withNx(),
  withWeb(),
  (config, { options, context }) => {
    return [
      merge(config, {
        entry: {
          main: path.resolve(__dirname, 'src/client/main.ts'),
        },
        output: {
          filename: '[name].js',
          path: path.resolve(config.output.path, 'client'),
        },
        plugins: [
          new CopyPlugin({
            patterns: [
              {
                from: path.resolve(__dirname, 'src/fxmanifest.lua'),
                to: path.resolve(config.output.path),
              },
            ],
          }),
        ],
        optimization: {
          minimize: true,
        },
      }),
      merge(config, {
        entry: {
          main: path.resolve(__dirname, 'src/server/main.ts'),
        },
        output: {
          filename: '[name].js',
          path: path.resolve(config.output.path, 'server'),
        },
        plugins: [
          new CopyPlugin({
            patterns: [
              {
                from: path.resolve(__dirname, 'src/fxmanifest.lua'),
                to: path.resolve(config.output.path),
              },
            ],
          }),
        ],
        optimization: {
          minimize: true,
        },
      }),
    ];
  }
);
```

But now when using watch it just compile the first bundle (client) not both, is this normal?
