### ISSUE TITLE
Unable to create project in similar destination as another project due to projectName being affected by directory

### ISSUE THREAD

**Issue by PowerSupply** [nrwl/nx#16308]
### Current Behavior

Running the following generator...
```
import { Tree } from "@nrwl/devkit";
import { libraryGenerator, remote } from "@nrwl/angular/generators";

export default async function (tree: Tree) {
    const name = 'test'

    await libraryGenerator(tree, {
        name,
        directory: 'libs/xxx',
    });

    await remote(tree, {
        name,
        directory: 'apps/xxx'
    });
}
```
...gives errors...:
```
Skipping project found at apps/xxx/test since project xxx-test already exists at libs/xxx/test! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at apps/xxx/test since project xxx-test already exists at libs/xxx/test! Specify a unique name for the project to allow Nx to differentiate between the two projects.

 >  NX   Cannot find apps/xxx/test/.eslintrc.json
 ...
 ```
This is caused by the libraryGenerator and the remote generator (and many others like the workspace move generator) changes the projectName in part based on the directory.
 
I know this is intended behaviour but it causes problems and I think it is inexplicit that the name is not the name you supply to the generator. After you generate/move a project, you have to guess the project name. 

I propose that this behaviour is changed. To avoid a breaking change you could add an option to keep the legacy behaviour or introduce a migration to change the code.

### Expected Behavior

The above generator works. Or introduce the changed behaviour I mentioned earlier.

### Steps to Reproduce

1. Run a generator with the following code:
```
import { Tree } from "@nrwl/devkit";
import { libraryGenerator, remote } from "@nrwl/angular/generators";

export default async function (tree: Tree) {
    const name = 'test'

    await libraryGenerator(tree, {
        name,
        directory: 'libs/xxx',
    });

    await remote(tree, {
        name,
        directory: 'apps/xxx'
    });
}
```

### Nx Report

```shell
Node : 18.13.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx                      : 16.0.0-beta.0
   @nrwl/js                : 16.0.0-beta.0
   @nrwl/jest              : 16.0.0-beta.0
   @nrwl/linter            : 16.0.0-beta.0
@nrwl/workspace         : 16.0.0-beta.0
   @nrwl/angular           : 16.0.0-beta.0
   @nrwl/cypress           : 16.0.0-beta.0
   @nrwl/devkit            : 16.0.0-beta.0
   @nrwl/eslint-plugin-nx  : 16.0.0-beta.0
   @nrwl/nx-plugin         : 16.0.0-beta.0
   @nrwl/tao               : 16.0.0-beta.0
   @nrwl/vite              : 16.0.0-beta.0
   @nrwl/web               : 16.0.0-beta.0
   @nrwl/webpack           : 16.0.0-beta.0
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @xxx/yyy : 8.0.1
   @twittwer/compodoc          : 1.5.3
```

### Failure Logs

```shell
Skipping project found at apps/xxx/test since project xxx-test already exists at libs/xxx/test! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at apps/xxx/test since project xxx-test already exists at libs/xxx/test! Specify a unique name for the project to allow Nx to differentiate between the two projects.

 >  NX   Cannot find apps/xxx/test/.eslintrc.json
```

**Comment by PowerSupply** [comment]
This is also a problem using Nx 15.8.7:
```
   Node : 18.13.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx                      : 15.8.7
   @nrwl/js                : 15.8.7
   @nrwl/jest              : 15.8.7
   @nrwl/linter            : 15.8.7
   @nrwl/workspace         : 15.8.7
   @nrwl/angular           : 15.8.7
   @nrwl/cli               : 15.8.7
   @nrwl/cypress           : 15.8.7
   @nrwl/devkit            : 15.8.7
   @nrwl/eslint-plugin-nx  : 15.8.7
   @nrwl/nx-plugin         : 15.8.7
   @nrwl/tao               : 15.8.7
   @nrwl/vite              : 15.8.7
   @nrwl/webpack           : 15.8.7
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @xxx/yyy: 8.0.1
   @twittwer/compodoc          : 1.5.3

```

```
Error: Project name already exists.
    at ProjectDefinitionCollection.add (/Users/paustr/Documents/Dev/gaia/packages/angular_devkit/core/src/workspace/definitions.ts:147:13)
    at /Users/paustr/packages/schematics/angular/application/index.ts:219:24
    at /Users/paustr/packages/schematics/angular/utility/workspace.ts:66:26
    at callRuleAsync (/Users/paustr/packages/angular_devkit/schematics/src/rules/call.ts:79:16)

 >  NX   Project name already exists.


Error: Project name already exists.
    at ProjectDefinitionCollection.add (/Users/paustr/Documents/Dev/gaia/packages/angular_devkit/core/src/workspace/definitions.ts:147:13)
    at /Users/paustr/packages/schematics/angular/application/index.ts:219:24
    at /Users/paustr/packages/schematics/angular/utility/workspace.ts:66:26
    at callRuleAsync (/Users/paustr/packages/angular_devkit/schematics/src/rules/call.ts:79:16)
MacBook-Pro:gaia paustr$ 
```
I don't know why the error is output twice.

**Comment by PowerSupply** [comment]
Any progress on this?

**Comment by antonyftp** [comment]
Hi ! I have pretty much the same error on my side but in .netcore. My issue is when I try to create another .net core app with the plugin @nx-dotnet/core, it gives me this error :

`Skipping project found at apps/reportbackendapp since project reportbackendapp already exists at apps/reportbackendapp! Specify a unique name for the project to allow Nx to differentiate between the two projects.`

The thing is this app doesn't exist before and my other app doesn't have the same name.

**Comment by PowerSupply** [comment]
Any progress on this? My proposed solution would avoid the problem in #17430 as well.
