### ISSUE TITLE
cannot find module 'tslib' in nestjs production build

### ISSUE THREAD

**Issue by satheshsat** [nrwl/nx#16320]
### Current Behavior

Got below error, when I place it in server. It works fine in localhost.

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.tslib (/root/main.js:424:18)
    at __webpack_require__ (/root/main.js:448:41)
    at /root/main.js:465:17
    at /root/main.js:482:3
    at Object.<anonymous> (/root/main.js:487:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

### Expected Behavior

Code should run without any error

### Steps to Reproduce

1. Create new workspace with nestjs app
2. Build the app
3. place it in ubuntu server
4. Code throws an error

### Nx Report

```shell
Node : 18.15.0
   OS   : darwin x64
   npm  : 9.5.0
   
   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/nest              : 15.8.6
   @nrwl/node              : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/webpack           : 15.8.6
   @nrwl/nx-cloud          : 15.2.3
   typescript              : 4.9.5
```

### Additional Information

server node version is v10.19.0

**Comment by ndcunningham** [comment]
Can you retry this with the latest version of Nx?
