### ISSUE TITLE
Lerna (powered by Nx)   Cannot find module '@nrwl/nx-cloud'

### ISSUE THREAD

**Issue by delfws** [nrwl/nx#16333]
### Current Behavior

[] ~/lerna-workspace <prelerna> ✗ pnpm dlx lerna run build --scope=header
.../share/pnpm/store/v3/tmp/dlx-6812     |  WARN  deprecated @npmcli/move-file@2.0.1
.../share/pnpm/store/v3/tmp/dlx-6812     | +589 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.../share/pnpm/store/v3/tmp/dlx-6812     | Progress: resolved 597, reused 589, downloaded 0, added 589, done
lerna notice cli v6.6.1
lerna notice filter including "header"
lerna info filter [ 'header' ]

 >  Lerna (powered by Nx)   Cannot find module '@nrwl/nx-cloud'

   Require stack:
   - /home/heisenberg/.local/share/pnpm/store/v3/tmp/dlx-6812/node_modules/.pnpm/registry.npmmirror.com+nx@15.9.2/node_modules/nx/src/tasks-runner/run-command.js
   - /home/heisenberg/.local/share/pnpm/store/v3/tmp/dlx-6812/node_modules/.pnpm/registry.npmmirror.com+nx@15.9.2/node_modules/nx/src/command-line/run-one.js
   - /home/heisenberg/.local/share/pnpm/store/v3/tmp/dlx-6812/node_modules/.pnpm/registry.npmmirror.com+lerna@6.6.1/node_modules/lerna/dist/cli.js
   Pass --verbose to see the stacktrace.

 ERROR  Command failed with exit code 1: lerna run build --scope=header

pnpm: Command failed with exit code 1: lerna run build --scope=header
    at makeError (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:24230:17)
    at handlePromise (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:24801:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:206486:7)
    at async /home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:215818:21
    at async main (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:215785:34)
    at async runPnpm (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:216040:5)
    at async /home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:216032:7

### Expected Behavior

run success

### Steps to Reproduce

1. follow the [docs](https://lerna.js.org/docs/features/share-your-cache)，and run `pnpm dlx nx connect-to-nx-cloud` command, looks like good.

.../share/pnpm/store/v3/tmp/dlx-5440     | +124 ++++++++++++
.../share/pnpm/store/v3/tmp/dlx-5440     | Progress: resolved 132, reused 124, downloaded 0, added 124, done
✔ Enable distributed caching to make your CI faster · Yes

>  NX  Generating @nrwl/nx-cloud:init

UPDATE nx.json

 >  NX   Distributed caching via Nx Cloud has been enabled

   In addition to the caching, Nx Cloud provides config-free distributed execution,
   UI for viewing complex runs and GitHub integration. Learn more at https://nx.app
   
   Your workspace is currently unclaimed. Run details from unclaimed workspaces can be viewed on cloud.nx.app by anyone
   with the link. Claim your workspace at the following link to restrict access.
   
   https://cloud.nx.app/orgs/workspace-setup?accessToken=???

2. run `pnpm dlx lerna run build --scope=header && pnpm dlx nx reset && pnpm dlx lerna run build --scope=header` command, and i got this,

.../share/pnpm/store/v3/tmp/dlx-5988     |  WARN  deprecated @npmcli/move-file@2.0.1
.../share/pnpm/store/v3/tmp/dlx-5988     | +589 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.../share/pnpm/store/v3/tmp/dlx-5988     | Progress: resolved 597, reused 589, downloaded 0, added 589, done
lerna notice cli v6.6.1
lerna notice filter including "header"
lerna info filter [ 'header' ]

 >  Lerna (powered by Nx)   Daemon process terminated and closed the connection

   Please rerun the command, which will restart the daemon.

 ERROR  Command failed with exit code 1: lerna run build --scope=header

pnpm: Command failed with exit code 1: lerna run build --scope=header
    at makeError (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:24230:17)
    at handlePromise (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:24801:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:206486:7)
    at async /home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:215818:21
    at async main (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:215785:34)
    at async runPnpm (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:216040:5)
    at async /home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:216032:7

3. i think maybe i forget install, then i run `pnpm install -r`,and rerun 3. command, it still failed 

.../share/pnpm/store/v3/tmp/dlx-6465     |  WARN  deprecated @npmcli/move-file@2.0.1
.../share/pnpm/store/v3/tmp/dlx-6465     | +589 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.../share/pnpm/store/v3/tmp/dlx-6465     | Progress: resolved 597, reused 589, downloaded 0, added 589, done
lerna notice cli v6.6.1
lerna notice filter including "header"
lerna info filter [ 'header' ]

 >  Lerna (powered by Nx)   Cannot find module '@nrwl/nx-cloud'

   Require stack:
   - /home/heisenberg/.local/share/pnpm/store/v3/tmp/dlx-6465/node_modules/.pnpm/registry.npmmirror.com+nx@15.9.2/node_modules/nx/src/tasks-runner/run-command.js
   - /home/heisenberg/.local/share/pnpm/store/v3/tmp/dlx-6465/node_modules/.pnpm/registry.npmmirror.com+nx@15.9.2/node_modules/nx/src/command-line/run-one.js
   - /home/heisenberg/.local/share/pnpm/store/v3/tmp/dlx-6465/node_modules/.pnpm/registry.npmmirror.com+lerna@6.6.1/node_modules/lerna/dist/cli.js
   Pass --verbose to see the stacktrace.

 ERROR  Command failed with exit code 1: lerna run build --scope=header

pnpm: Command failed with exit code 1: lerna run build --scope=header
    at makeError (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:24230:17)
    at handlePromise (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:24801:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:206486:7)
    at async /home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:215818:21
    at async main (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:215785:34)
    at async runPnpm (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:216040:5)
    at async /home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:216032:7

i can make sure i install it, on my local node_modules,

![image](https://user-images.githubusercontent.com/24715927/232445908-b5c81673-2ce0-4aec-a6a2-a21fab8f2622.png)

![image](https://user-images.githubusercontent.com/24715927/232445997-f5cd0c95-de8f-49a1-8bf8-33193a48edb9.png)

### Nx Report

```shell
.../share/pnpm/store/v3/tmp/dlx-7064     | +124 ++++++++++++
.../share/pnpm/store/v3/tmp/dlx-7064     | Progress: resolved 132, reused 124, downloaded 0, added 124, done

 >  NX   Report complete - copy this into the issue template

   Node : 18.15.0
   OS   : linux x64
   pnpm : 8.2.0
   
   nx              : 15.9.2
   lerna           : 6.6.1
   @nrwl/cli       : 15.9.2
   @nrwl/tao       : 15.9.2
   @nrwl/nx-cloud  : 15.3.5
```

### Additional Information

when i start use lerna, sometimes has problem,maybe this can help 

.../share/pnpm/store/v3/tmp/dlx-6978     | +124 ++++++++++++
.../share/pnpm/store/v3/tmp/dlx-6978     | Progress: resolved 132, reused 124, downloaded 0, added 124, done

 >  NX   Daemon process terminated and closed the connection

   Please rerun the command, which will restart the daemon.

 ERROR  Command failed with exit code 1: nx report

pnpm: Command failed with exit code 1: nx report
    at makeError (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:24230:17)
    at handlePromise (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:24801:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:206486:7)
    at async /home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:215818:21
    at async main (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:215785:34)
    at async runPnpm (/home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:216040:5)
    at async /home/heisenberg/.cache/node/corepack/pnpm/8.2.0/dist/pnpm.cjs:216032:7

**Comment by delfws** [comment]
i think i find the problem , change `pnpm dlx lerna run build --scope=header && pnpm dlx nx reset && pnpm dlx lerna run build --scope=header` to `pnpm exec -- lerna run build --scope=header && pnpm dlx nx reset && pnpm exec -- lerna run build --scope=header`

`pnpm dlx` isn't equals `npx`
