### ISSUE TITLE
Upgrading @nrwl/next 15.8.5 to anything higher results in production build errors 

### ISSUE THREAD

**Issue by ryandegruyter** [nrwl/nx#16361]
### Current Behavior

When running 
`nx export website`

Receiving numerous errors of this type:
 
```Attempted import error: 'ReactComponent' is not exported from '../../public/img/logos/alpha.svg' (imported as 'AlphaSvg').```

import code:

`import { ReactComponent as AlphaSvg } from '../../public/img/logos/alpha.svg';`

And

```info  - Generating static pages (0/45)
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zc (/Users/.../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:493)
```

### Expected Behavior

Build succeeds without any errors like v15.8.5 or please clarify any breaking changes.

### GitHub Repo

private

### Steps to Reproduce

Upgrade 
    "@nrwl/next": "15.8.5",

To
    "@nrwl/next": "15.9.2",

### Nx Report

```shell
Node : 16.17.1
   OS   : darwin arm64
   npm  : 9.2.0
   
   nx                      : 15.9.2
   lerna                   : 5.6.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ng-bootstrap/ng-bootstrap : 14.1.0
   @storybook/angular         : 6.5.16
```

### Failure Logs
```

info  - Generating static pages (0/48)
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zc (/Users/.../node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:493)

```
### Additional Information

Initially thought upgrading nextjs was the issue, but updating to 13.3.0 works fine.
https://github.com/vercel/next.js/issues/47340

Failing build step is when generating static pages.
Succesfull build logs:

```
info  - Skipping linting
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[    ] info  - Generating static pages (0/48)Warning: data for page "/blog" is 130 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
See more info here: https://nextjs.org/docs/messages/large-page-data
info  - Generating static pages (48/48)
info  - Finalizing page optimization  

Route (pages)                                                                                     Size     First Load JS
....

○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

info  - using build directory: /Users/.../.next
info  - Copying "static build" directory
info  - Launching 9 workers
info  - Copying "public" directory
info  - Exporting (18/18)

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target export for project website (37s)
```

**Comment by barrymichaeldoyle** [comment]
Out of curiosity, if you upgrade to the latest beta version does it work?

[16.0.0-beta.6](https://github.com/nrwl/nx/releases/tag/16.0.0-beta.6)

I had issues with module federation and then they fixed it but it hasn't reached mainstream release yet. But it is nicely fixed if I use the latest beta release!

I see in the release docs there is some stuff about fixing migrations to next v13.3.0. Give that a shot and see what happens :)

**Comment by jaysoo** [comment]
@ryandegruyter Do you mind sharing your `next.config.js` file and `tsconfig.json` files? It looks like the SVG file is not processed through SVGR.

**Comment by ryandegruyter** [comment]
@barrymichaeldoyle upgrading to the latest beta gives other errors, also not sure what the correct migration path is for that.


@jaysoo Yes sure, thanks.

next.config.js
```
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withNx = require('@nrwl/next/plugins/with-nx');

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  compiler: {
    styledComponents: true,
  },
  images: {
    // TODO: check how we can remove this unoptimized setting
    // While being able to run `npx nx export website`
    unoptimized: true,
    domains: ['images.{removed}.net'],
  },
};

module.exports = withBundleAnalyzer(withNx(nextConfig));
```

tsconfig.json
```
{
  "extends": "../../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "preserve",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "incremental": true,
    "types": ["jest", "node"]
  },
  "include": ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "next-env.d.ts"],
  "exclude": ["node_modules", "jest.config.ts"]
}
```

tsconfig.base.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2021", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {....}
  },
  "exclude": ["node_modules", "tmp"]
}

```

**Comment by ryandegruyter** [comment]
We resolved the issue by setting
```
nx: {
    svgr: true,
},
```
in the next.config.js
