### ISSUE TITLE
Error: The module could not be resolved in React native project created with preset npm

### ISSUE THREAD

**Issue by adithep** [nrwl/nx#16391]
### Current Behavior

Once app is being compiled there is the following error:

```
error: Error: The module could not be resolved because none of these files exist:
* /Users/---/repo/happynrwl/packages/shared-ui-layout/src/index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
* /Users/---/repo/happynrwl/packages/shared-ui-layout/src/index.ts/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  at resolveModulePath (/Users/---/repo/happynrwl/node_modules/metro-resolver/src/resolve.js:134:9)
  at Object.resolve (/Users/---/repo/happynrwl/node_modules/metro-resolver/src/resolve.js:37:12)
  at tsconfigPathsResolver (/Users/---/repo/happynrwl/node_modules/@nrwl/react-native/plugins/metro-resolver.js:84:30)
  at /Users/---/repo/happynrwl/node_modules/@nrwl/react-native/plugins/metro-resolver.js:26:13
  at Object.resolve (/Users/---/repo/happynrwl/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro-resolver/src/resolve.js:27:12)
  at ModuleResolver.resolveDependency (/Users/---/repo/happynrwl/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:111:31)
  at DependencyGraph.resolveDependency (/Users/---/repo/happynrwl/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
  at Object.resolve (/Users/---/repo/happynrwl/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/lib/transformHelpers.js:177:21)
  at Graph._resolveDependencies (/Users/---/repo/happynrwl/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
  at Graph._processModule (/Users/---/repo/happynrwl/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
```

### Expected Behavior

App Built successfully

### GitHub Repo

https://github.com/adithep/nx-react-native-module-not-found

### Steps to Reproduce

1. npx create-nx-workspace happynrwl --preset=npm
2. npm install @nrwl/react-native --save-dev
3. npx nx g @nrwl/react-native:app
4. npx nx g @nrwl/react-native:lib shared-ui-layout
5. npx nx g @nrwl/react-native:component layout --project=shared-ui-layout --export
6. Modify App.tsx to
```typescript
import React from 'react';
import { SafeAreaView } from 'react-native';

import { Layout } from 'shared-ui-layout';

const App = () => {
  return (
    <SafeAreaView>
      <Layout />
    </SafeAreaView>
  );
};

export default App;
```
7. npx nx run-android mobile

Note that it is `shared-ui-layout` instead of `@happynrwl/shared-ui-layout` when the preset is `npm`

Also note that changing it to `@happynrwl/shared-ui-layout` in `tsconfig.base.json` and `App.tsx` makes no difference.

The same issue happens on both android and ios

### Nx Report

```shell
Node : 18.15.0
   OS   : darwin arm64
   npm  : 9.5.0

   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/detox             : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/react-native      : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.5
```

### Additional Information

This works perfectly if the preset in `react-native`. I have not tried any other preset.

**Comment by xiongemi** [comment]
fixed in pr https://github.com/nrwl/nx/pull/16624. it should be in nx release > 16
