### ISSUE TITLE
Upgrade to 16.0.0-beta.6: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by brandoncollins7** [nrwl/nx#16513]
### Current Behavior

Project will not build with newest version:

HookWebpackError: Cannot read properties of undefined (reading 'data')
    at makeWebpackError (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\Compilation.js:3060:12
    at eval (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1)
    at fn (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\Compilation.js:480:17)
    at _next0 (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\Hook.js:18:14)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'data')
    at C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\nx@16.0.0-beta.6_@swc+core@1.3.52\node_modules\nx\src\plugins\js\package-json\create-package-json.js:31:55
    at Array.forEach (<anonymous>)
    at createPackageJson (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\nx@16.0.0-beta.6_@swc+core@1.3.52\node_modules\nx\src\plugins\js\package-json\create-package-json.js:29:79)
    at C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\@nx+webpack@16.0.0-beta.6_@swc+core@1.3.52_@types+node@18.7.23_esbuild@0.17.17_nx@
16.0.0-beta_x347wfc4s65ekwhbl6iylpyrsq\node_modules\@nx\webpack\src\plugins\generate-package-json-plugin.js:34:64
    at fn (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\Compilation.js:478:10)
    at _next0 (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    
    
    
![image](https://user-images.githubusercontent.com/36413482/234073513-83c8f69d-73de-44ad-93e7-7ef43036a167.png)

### Expected Behavior

should build

### Steps to Reproduce

1. not sure

### Nx Report

```shell
Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : win32 x64
   pnpm   : 8.3.1
   Hasher : Native

   nx (global)             : 15.9.2
   nx                      : 16.0.0-beta.6
   @nrwl/js                : 16.0.0-beta.6
   @nrwl/jest              : 16.0.0-beta.6
   @nrwl/linter            : 16.0.0-beta.6
   @nrwl/workspace         : 16.0.0-beta.6
   @nrwl/devkit            : 16.0.0-beta.6
   @nrwl/esbuild           : 16.0.0-beta.6
   @nx/eslint-plugin       : 16.0.0-beta.6
   @nrwl/eslint-plugin-nx  : 16.0.0-beta.6
   @nrwl/nest              : 16.0.0-beta.6
   @nrwl/node              : 16.0.0-beta.6
   @nrwl/webpack           : 16.0.0-beta.6
   @nrwl/nx-cloud          : 16.0.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 4.0.3
```

### Failure Logs

```shell
Project will not build with newest version:

HookWebpackError: Cannot read properties of undefined (reading 'data')
    at makeWebpackError (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\Compilation.js:3060:12
    at eval (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1)
    at fn (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\Compilation.js:480:17)
    at _next0 (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\Hook.js:18:14)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'data')
    at C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\nx@16.0.0-beta.6_@swc+core@1.3.52\node_modules\nx\src\plugins\js\package-json\create-package-json.js:31:55
    at Array.forEach (<anonymous>)
    at createPackageJson (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\nx@16.0.0-beta.6_@swc+core@1.3.52\node_modules\nx\src\plugins\js\package-json\create-package-json.js:29:79)
    at C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\@nx+webpack@16.0.0-beta.6_@swc+core@1.3.52_@types+node@18.7.23_esbuild@0.17.17_nx@
16.0.0-beta_x347wfc4s65ekwhbl6iylpyrsq\node_modules\@nx\webpack\src\plugins\generate-package-json-plugin.js:34:64
    at fn (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\Compilation.js:478:10)
    at _next0 (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\webpack@5.80.0_@swc+core@1.3.52_esbuild@0.17.17_webpack-cli@3.3.12\node_modules\webpack\lib\Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (C:\Users\brand\OneDrive\Documents\Projects\FRNT\temp\atlantic-dawn-backend-monorepo\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    
    
    
![image](https://user-images.githubusercontent.com/36413482/234073513-83c8f69d-73de-44ad-93e7-7ef43036a167.png)
```

**Comment by brandoncollins7** [comment]
![image](https://user-images.githubusercontent.com/36413482/234076036-b24d5f48-2c5d-40ee-bdd9-f943e1bbb0e6.png)

**Comment by brandoncollins7** [comment]
I just tried this with a new nestjs project using the generator. Once you add generatePackageJson: true it fails

**Comment by FrozenPandaz** [comment]
I've been trying to track down this issue.

Do you have `tslib` in your `package.json`? Could you provide a repo where the issue occurs? What were your exact reproduction steps?

**Comment by brandoncollins7** [comment]
@FrozenPandaz 
Here is a very simple sample project.
just run pnpm i && nx build my-nest-app

https://github.com/brandoncollins7/nx-broken

**Comment by danyhiol** [comment]
I am also having this issue after migrating to the latest version: `16.0.1`.

```ts
HookWebpackError: Cannot read properties of undefined (reading 'data')
    at makeWebpackError (/path/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /path/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:57:1)
    at fn (/path/node_modules/webpack/lib/Compilation.js:480:17)
    at _next0 (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:55:1)
    at eval (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:68:1)
    at eval (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'data')
    at /path/node_modules/nx/src/plugins/js/package-json/create-package-json.js:31:55
    at Array.forEach (<anonymous>)
    at createPackageJson (/path/node_modules/nx/src/plugins/js/package-json/create-package-json.js:29:79)
    at /path/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:34:64
    at fn (/path/node_modules/webpack/lib/Compilation.js:478:10)
    at _next0 (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:55:1)
    at eval (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:68:1)
    at eval (eval at create (/path/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
```
removing/disabling `generatePackageJson` does fix it, but of course, remove the `package.json`.

**Comment by brandoncollins7** [comment]
Any update on this? Completely blocking my ability to upgrade to latest version. The strange things is if I create a brand new workspace and add a brand new nestjs from from the generator, this issue does not happen. I have tried endlessly to see what is the difference between my sample project above and a new project and I for the life of me can't find one that would be causing this issue:(

**Comment by Phault** [comment]
This regression also made it into the [15.9.3](https://github.com/nrwl/nx/releases/tag/15.9.3) release.

**Comment by brandoncollins7** [comment]
This also exists in the now official 16 release

**Comment by FrozenPandaz** [comment]
Thank you for the reproduction! It was very helpful :+1: 

@brandoncollins7

```json
  "pluginsConfig": {
    "@nrwl/js": {
      "analyzeSourceFiles": true
    }
  }
```

This config is missing "analyzePackageJson". I will update the logic to default to true when it's not specified.

@jaysoo The above is not the surface level issue why this error occurs though. I believe this has to do with how the `tslib`/`@swc/helpers` are added into the `package.json`. I think users may still run into this cryptic error if they don't have either `tslib` or `@swc/helpers` installed.
