### ISSUE TITLE
nx plugin incorrectly parses tsconfig

### ISSUE THREAD

**Issue by g-cheishvili** [nrwl/nx#16583]
### Current Behavior

This PR #15438 caused the issue.
If you have a custom plugin and running nx@^15.8.8 AND you have "jsx" configured in your tsconfig, using custom executor will cause break. It will state that `jsx` should be a string. What happens is that instead of taking config from tsconfig directly, without modification, it takes probably some enum value and the [code](https://github.com/nrwl/nx/blob/2dd59c3b57c22ebb80f1e4f5ec651abdd13b41fe/packages/nx/src/utils/nx-plugin.ts#L276) just takes that output and shoves into the transpilation without any alteration

### Expected Behavior

It should work and it does not

### GitHub Repo

https://github.com/SAP/fundamental-styles/tree/nx_issue_showcase

### Steps to Reproduce

Just try [this branch ](https://github.com/SAP/fundamental-styles/tree/nx_issue_showcase), install deps, then run any target and you'll see. I was playing with the `nx run styles:build-visual`

### Nx Report

```shell
Node : 16.19.1
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/nx-plugin         : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/nx-cloud          : 16.0.4
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   nx-stylelint : 14.0.2
```

### Failure Logs

```shell
>  NX   Unable to resolve workspace-plugins:visual-stories.

   ⨯ Unable to compile TypeScript:
   error TS5024: Compiler option 'jsx' requires a value of type string.
   

Error: Unable to resolve workspace-plugins:visual-stories.
⨯ Unable to compile TypeScript:
error TS5024: Compiler option 'jsx' requires a value of type string.

    at Workspaces.readExecutor (/Users/giorgicheishvili/Projects/SAP/packages/nx/src/config/workspaces.ts:216:13)
    at /Users/giorgicheishvili/Projects/SAP/packages/nx/src/tasks-runner/utils.ts:244:20
    at Generator.next (<anonymous>)
    at fulfilled (/Users/giorgicheishvili/Projects/SAP/fundamental-styles/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by g-cheishvili** [comment]
@AgentEnder are there any plans for this?
