### ISSUE TITLE
Cannot read properties of null (reading 'replace') when genering component for app/lib created with standalone option for components

### ISSUE THREAD

**Issue by semla** [nrwl/nx#16689]
### Current Behavior

`nx generate component wrapper --project ang-app --verbose --dry-run`
✔ Which generator would you like to use? · @nrwl/angular:component

>  NX  Generating @nrwl/angular:component

 >  NX   Cannot read properties of null (reading 'replace')

```
TypeError: Cannot read properties of null (reading 'replace')
    at removeWindowsDriveLetter (/home/user/code/nx-examples/node_modules/nx/src/utils/path.js:6:27)
    at normalizePath (/home/user/code/nx-examples/node_modules/nx/src/utils/path.js:12:12)
    at findModuleFromOptions (/home/user/code/nx-examples/node_modules/@nrwl/angular/src/generators/component/lib/module.js:14:43)
    at /home/user/code/nx-examples/node_modules/@nrwl/angular/src/generators/component/component.js:59:67
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/code/nx-examples/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

### Expected Behavior

`nx generate component wrapper --project ang-app2 --verbose --dry-run`
✔ Which generator would you like to use? · @nrwl/angular:component

>  NX  Generating @nrwl/angular:component

```
CREATE apps/ang-app2/src/app/wrapper/wrapper.component.css
CREATE apps/ang-app2/src/app/wrapper/wrapper.component.html
CREATE apps/ang-app2/src/app/wrapper/wrapper.component.spec.ts
CREATE apps/ang-app2/src/app/wrapper/wrapper.component.ts
UPDATE apps/ang-app2/src/app/app.module.ts

NOTE: The "dryRun" flag means no changes were made.

```

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. `nx generate app ang-app-with-standalone`
2. `? Would you like to use Standalone Components?`: Yes
3. `nx generate component wrapper --project ang-app-with-standalone --verbose --dry-run`

### Nx Report

```shell
nx report
/bin/sh: 1: yarn: not found
nx report

Reports useful version numbers to copy into the Nx issue template

Options:
  --help     Show help                                                                               [boolean]
  --version  Show version number                                                                     [boolean]

Error: Command failed: yarn --version
/bin/sh: 1: yarn: not found
```

### Failure Logs

```shell
>  NX   Cannot read properties of null (reading 'replace')


TypeError: Cannot read properties of null (reading 'replace')
    at removeWindowsDriveLetter (/home/user/code/nx-examples/node_modules/nx/src/utils/path.js:6:27)
    at normalizePath (/home/user/code/nx-examples/node_modules/nx/src/utils/path.js:12:12)
    at findModuleFromOptions (/home/user/code/nx-examples/node_modules/@nrwl/angular/src/generators/component/lib/module.js:14:43)
    at /home/user/code/nx-examples/node_modules/@nrwl/angular/src/generators/component/component.js:59:67
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/code/nx-examples/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional Information

https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/utility/find-module.ts#L29
iiuc you don't have to look for the module when creating standalone components

_No response_

**Comment by Coly010** [comment]
It should be noted that it doesn't appear that you have selected standalone option for the component:

```
nx generate component wrapper --project ang-app --verbose --dry-run
```

If the application generated has been generated to use standalone components, when calling the generator to generate a component, you still need to pass `--standalone` to it. 

This is because of the interop between NgModule and Standalone Components, where both can exist and work in the one application.

That said, we should throw better error.
