### ISSUE TITLE
eslint-plugin tries to read a directory when there's a self-import

### ISSUE THREAD

**Issue by alumni** [nrwl/nx#16716]
### Current Behavior

In `@nx/eslint-plugin/src/utils/ast-utils`, `getRelativeImportPath` is trying to read a directory using `readFileSync`, which causes `EISDIR: illegal operation on a directory, read`

### Expected Behavior

There should be no error. ESLint should highlight a library self-import as a lint error.

### Steps to Reproduce

*tsconfig.base.json*:
```json
{
    "compilerOptions": {
        "paths": {
            "@libs/my-lib": ["libs/my-lib/src"],
        },
    },
}
```

*libs/my-lib/src/lib/types.ts*:
```ts
export type SomeType = ...
```

*libs/my-lib/src/lib/some-file.ts*:
```ts
import type { SomeType } from '@libs/my-lib';
```

### Nx Report

```shell
Node   : 18.13.0
OS     : linux x64
yarn   : 1.22.19
Hasher : Native

nx                 : 16.0.3
@nx/js             : 16.0.3
@nx/jest           : 16.0.3
@nx/linter         : 16.0.3
@nx/workspace      : 16.0.3
@nx/devkit         : 16.0.3
@nx/eslint-plugin  : 16.0.3
@nx/nest           : 16.0.3
@nx/node           : 16.0.3
@nrwl/tao          : 16.0.3
@nx/webpack        : 16.0.3
typescript         : 5.0.4
```

### Failure Logs

```shell
Error: EISDIR: illegal operation on a directory, read
Occurred while linting /repo/libs/my-lib/src/lib/some-file.ts:5 <- line with self-import
Rule: "@nx/enforce-module-boundaries"
    at Object.readSync (node:fs:748:3)
    at tryReadSync (node:fs:448:20)
    at readFileSync (node:fs:494:19)
    at getRelativeImportPath (/repo/node_modules/@nx/eslint-plugin/src/utils/ast-utils.js:60:47)
    at Object.fix (/repo/node_modules/@nx/eslint-plugin/src/rules/enforce-module-boundaries.js:203:98)
    at normalizeFixes (/repo/node_modules/eslint/lib/linter/report-translator.js:193:28)
    at /repo/node_modules/eslint/lib/linter/report-translator.js:364:49
    at Object.report (/repo/node_modules/eslint/lib/linter/linter.js:1016:41)
    at run (/repo/node_modules/@nx/eslint-plugin/src/rules/enforce-module-boundaries.js:181:29)
    at ImportDeclaration (/repo/node_modules/@nx/eslint-plugin/src/rules/enforce-module-boundaries.js:408:17)
```

**Comment by alumni** [comment]
@AgentEnder I opened the issue since the tsconfig is correct without `index.ts`, and maybe `getBarrelEntryPointByImportScope` should append `/index.ts` if necessary :) But I agree, manually appending `index.ts` to the tsconfig paths would be a valid workaround.

**Comment by AgentEnder** [comment]
Yeah, just providing a workaround for the time being. It should likely check the index if necessary as pointed out.
