### ISSUE TITLE
 NX   this._schemaRegistry.compile(...).pipe is not a function

### ISSUE THREAD

**Issue by phihochzwei** [nrwl/nx#16736]
### Current Behavior

After running nx migrate next, none of our Angular projects is working. Searching for this error message lead to no results

### Expected Behavior

Either I would expect the migrations to make the necessary changes or if that is not possible, at least give me a better information on how to fix this problem 

### Steps to Reproduce

1. Take a NX 16.0.3 project with Angular 
2. Try to serve or build

### Nx Report

```shell
Node   : 18.10.0
   OS     : darwin arm64
   npm    : 8.19.2
   Hasher : Native
   
   nx                 : 16.1.0-beta.0
   @nx/js             : 16.1.0-beta.0
   @nx/jest           : 16.1.0-beta.0
   @nx/linter         : 16.1.0-beta.0
   @nx/workspace      : 16.1.0-beta.0
   @nx/angular        : 16.1.0-beta.0
   @nx/cypress        : 16.1.0-beta.0
   @nx/devkit         : 16.1.0-beta.0
   @nx/eslint-plugin  : 16.1.0-beta.0
   @nx/nest           : 16.1.0-beta.0
   @nx/node           : 16.1.0-beta.0
   @nx/storybook      : 16.1.0-beta.0
   @nrwl/tao          : 16.1.0-beta.0
   @nx/webpack        : 16.1.0-beta.0
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngrx/component             : 15.3.0
   @ngrx/effects               : 15.3.0
   @ngrx/entity                : 15.3.0
   @ngrx/router-store          : 15.3.0
   @ngrx/schematics            : 15.3.0
   @ngrx/store                 : 15.3.0
   @ngrx/store-devtools        : 15.3.0
   @nguniversal/express-engine : 16.0.0-rc.2
   @nguniversal/builders       : 16.0.0-rc.2
   @storybook/angular          : 7.0.8
```

**Comment by AgentEnder** [comment]
Can you run with --verbose and provide a stack trace?

**Comment by phihochzwei** [comment]
With pleasure

`TypeError: this._schemaRegistry.compile(...).pipe is not a function
    at SwitchMapSubscriber.project (/GIT/storefront/node_modules/@angular-devkit/architect/src/jobs/simple-scheduler.js:108:79)
    at SwitchMapSubscriber._next (/GIT/storefront/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/switchMap.js:47:27)
    at Subscriber.next (/GIT/storefront/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at DefaultIfEmptySubscriber._next (/GIT/storefront/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/defaultIfEmpty.js:41:26)
    at Subscriber.next (/GIT/storefront/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/GIT/storefront/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/take.js:54:30)
    at Subscriber.next (/GIT/storefront/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at FilterSubscriber._next (/GIT/storefront/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/filter.js:52:30)
    at Subscriber.next (/GIT/storefront/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/GIT/storefront/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
`

**Comment by phihochzwei** [comment]
Jepp. Just added a brand new app to it. Same error. Here is the project.json


[project.txt](https://github.com/nrwl/nx/files/11389952/project.txt)

**Comment by phihochzwei** [comment]
Okay, this is REALLY weird. I just created a blank new workspace, all working fine. Then I opened the file, which threw the error in my project, but in the new workspace (@angular-devkit/architect/src/jobs/simple-scheduler.js) and the files are completely different. In "my" project, the SchemaRegistry seems to expect an Observable where in the "new" project it seems to be based on Promises.

**Comment by phihochzwei** [comment]
It seems, that my old project is not able to install the latest version of @angular-devkit. Any idea, why?

**Comment by phihochzwei** [comment]
@AgentEnder  Found the problem: 

We use @angular-builders/custom-webpack to integrate Sentry. And this has a hard dependency on angular-devkit 15.2.4
Once removed everything works as expected. Thanks for your time
