### ISSUE TITLE
nx migrate latest failed

### ISSUE THREAD

**Issue by MarkKla** [nrwl/nx#16753]
### Current Behavior

I want to migrate from v15.9.2 tot the latest version. Using the command nx migrate latest.

Getting these results:

Fetching @nrwl/workspace@latest
Fetching nx@16.0.3
Fetching @nrwl/cli@16.0.3
Fetching @nrwl/eslint-plugin-nx@16.0.3
Fetching @nrwl/express@16.0.3
Fetching @nrwl/jest@16.0.3
Fetching @nrwl/linter@16.0.3
Fetching @nrwl/node@16.0.3
Fetching ts-jest@~29.1.0
Fetching @typescript-eslint/parser@^5.58.0
Fetching @typescript-eslint/eslint-plugin@^5.58.0

 ERROR  The migrate command failed.

Command failed: npm install @nrwl/cli@16.0.3
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/cli@16.0.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Expected Behavior

I excpected it to migrate to the latest version without any problems as it always does.

### Steps to Reproduce

1. 
nx migrate latest

### Nx Report

```shell
Node : 18.13.0
   OS   : win32 x64
   npm  : 9.2.0

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/express           : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 5.0.4
```

### Failure Logs

```shell
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching nx@16.0.3
Fetching @nrwl/cli@16.0.3
Fetching @nrwl/eslint-plugin-nx@16.0.3
Fetching @nrwl/express@16.0.3
Fetching @nrwl/jest@16.0.3
Fetching @nrwl/linter@16.0.3
Fetching @nrwl/node@16.0.3
Fetching ts-jest@~29.1.0
Fetching @typescript-eslint/parser@^5.58.0
Fetching @typescript-eslint/eslint-plugin@^5.58.0

 ERROR  The migrate command failed.

Command failed: npm install @nrwl/cli@16.0.3
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/cli@16.0.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I haven't been able to reproduce it. I've tried following these steps:

- Created a new 15.9.2 workspace with an Express app (based on your report)
- Added `@nrwl/cli` to the `package.json` (it's no longer present in new workspaces, you probably have it coming from older versions)
- Migrated it running `nx migrate latest`

Those steps worked successfully and the migration doesn't attempt to fetch `@nrwl/cli`. Could you provide a repo where the issue can be reproduced so we can troubleshoot it?

**Comment by fuufen** [comment]
Had the same issue. Removed `@nrwl/cli` from `package.json` and after that `nx migrate latest` runs without issues.

**Comment by jaysoo** [comment]
I just tried this with the same packages, Windows, Node 18.13.0, and npm 9.2.0. Could not reproduce the problem. Like @fuufen said, the workaround is to remove `@nrwl/cli` before migrating.

If anyone has a public repo we can check that would be super helpful.

**Comment by MarkKla** [comment]
Removing @nrwl/cli also fixed the migrate command for me too, but now when running nx run api:serve I get :  

Cannot find module '@nrwl/webpack/package.json'

**Comment by MarkKla** [comment]
I did run it and it says:
    {
      "cli": "nx",
      "version": "16.0.0-beta.5",
      "description": "Replace @nx/node:webpack with @nx/node:webpack",
      "implementation": "./src/migrations/update-16-0-0/update-webpack-executor",
      "package": "@nx/node",
      "name": "update-16-0-0-update-executor"
    }

**Comment by jaysoo** [comment]
Hmm, that one was for `@nrwl/node:webpack` to `@nx/webpack:webpack` in case a migration from Nx 13 was skipped. There should be another for the rescope that looks like this:

``` 
    {
      "cli": "nx",
      "version": "16.0.0-beta.1",
      "description": "Replace @nrwl/webpack with @nx/webpack",
      "implementation": "./src/migrations/update-16-0-0-add-nx-packages/update-16-0-0-add-nx-packages",
      "package": "@nrwl/webpack",
      "name": "update-16-0-0-add-nx-packages"
    }
```

**Comment by MarkKla** [comment]
No, that rescope is not in the migrations.json

**Comment by jaysoo** [comment]
Do you happen to have an outdated `nx` installed globally? It's possible the global CLI logic is out of date -- we've started to warn against it recently.

**Comment by MarkKla** [comment]
nx --version gives 

Nx Version:
- Local: v16.1.0
- Global: vNot found

after running npm i -g nx@latest it says

Nx Version:
- Local: v16.1.0
- Global: v16.1.0

I always use nx migrate latest to upgrade to the latest version. Tried npx nx migrate latest now also. Still the same result. Is there a way to manually fix this?

 >  NX   Unable to resolve @nrwl/webpack:webpack.

   Cannot find module '@nrwl/webpack/package.json'
   Require stack:
   - E:\repositories\backend\node_modules\nx\src\utils\package-json.js
   - E:\repositories\backend\node_modules\nx\src\utils\print-help.js
   - E:\repositories\backend\node_modules\nx\src\command-line\run.js
   - E:\repositories\backend\node_modules\nx\bin\run-executor.js

Error: Unable to resolve @nrwl/webpack:webpack.
Cannot find module '@nrwl/webpack/package.json'
Require stack:
- E:\repositories\backend\node_modules\nx\src\utils\package-json.js
- E:\repositories\backend\node_modules\nx\src\utils\print-help.js
- E:\repositories\backend\node_modules\nx\src\command-line\run.js
- E:\repositories\backend\node_modules\nx\bin\run-executor.js
    at Workspaces.readExecutor (E:\repositories\backend\node_modules\nx\src\config\workspaces.js:120:19)
    at E:\repositories\backend\node_modules\nx\src\command-line\run.js:92:54
    at Generator.next (<anonymous>)
    at E:\repositories\backend\node_modules\tslib\tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (E:\repositories\backend\node_modules\tslib\tslib.js:163:16)
    at runExecutorInternal (E:\repositories\backend\node_modules\nx\src\command-line\run.js:80:20)
    at E:\repositories\backend\node_modules\nx\src\command-line\run.js:166:22
    at Generator.next (<anonymous>)
    at E:\repositories\backend\node_modules\tslib\tslib.js:167:75

**Comment by MarkKla** [comment]
Running npm install --save-dev @nrwl/webpack seems to fix the issuenpmnx migrate latest
