### ISSUE TITLE
`yarn nx graph --view tasks` fails when no `targetDefaults` are configured

### ISSUE THREAD

**Issue by jovdb** [nrwl/nx#16843]
### Current Behavior

`yarn nx graph --view tasks`

The command crashes with: 
```
node_modules\nx\src\command-line\dep-graph.js:450
    Object.keys(defaults).forEach((k) => {
           ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at mapTargetDefaultsToDependencies (C:\repos\express-development\Source\creator\node_modules\nx\src\command-line\dep-graph.js:450:12)
    at getAllTaskGraphsForWorkspace (C:\repos\express-development\Source\creator\node_modules\nx\src\command-line\dep-graph.js:407:38)
    at C:\repos\express-development\Source\creator\node_modules\nx\src\command-line\dep-graph.js:399:28
    at Generator.next (<anonymous>)
    at fulfilled (C:\repos\express-development\Source\creator\node_modules\tslib\tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)      

Node.js v18.4.0
```

### Expected Behavior

No crash

### Steps to Reproduce

1. Configure `nx.json` without `targetDefaults`
2. `yarn nx graph --view tasks`

### Nx Report

```shell
Node   : 18.4.0
OS     : win32 x64
yarn   : 3.2.2
Hasher : Native

nx          : 16.1.0
@nrwl/tao   : 16.1.0
typescript  : 4.9.5
```

### Failure Logs

```shell
node_modules\nx\src\command-line\dep-graph.js:450
    Object.keys(defaults).forEach((k) => {
           ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at mapTargetDefaultsToDependencies (C:\repos\express-development\Source\creator\node_modules\nx\src\command-line\dep-graph.js:450:12)
    at getAllTaskGraphsForWorkspace (C:\repos\express-development\Source\creator\node_modules\nx\src\command-line\dep-graph.js:407:38)
    at C:\repos\express-development\Source\creator\node_modules\nx\src\command-line\dep-graph.js:399:28
    at Generator.next (<anonymous>)
    at fulfilled (C:\repos\express-development\Source\creator\node_modules\tslib\tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Confirmed as fixed
