### ISSUE TITLE
"nx affected:apps" failed after upgrade NX from version 14 to version 16

### ISSUE THREAD

**Issue by tam-nguyen-yum** [nrwl/nx#16881]
### Current Behavior

`nx affected:apps` returns error "Cannot find configuration for <app_name>:affected:apps"

### Expected Behavior

`nx affected:apps` should return affected apps

### Steps to Reproduce

Following this doc (https://nx.dev/core-features/automate-updating-dependencies), here is what I did

1. Run `nx migrate latest`
2. Run `nx migrate --run-migrations`
3. Run `nx affected:apps`

### Nx Report

```shell
$ nx report                                  

 >  NX   Report complete - copy this into the issue template

   Node   : 14.21.3
   OS     : darwin x64
   yarn   : 1.22.18
   Hasher : Native
   
   nx (global)        : 16.0.3
   nx                 : 16.1.3
   @nx/js             : 16.1.3
   @nx/jest           : 16.1.3
   @nx/linter         : 16.1.3
   @nx/workspace      : 16.1.3
   @nx/devkit         : 16.1.3
   @nx/eslint-plugin  : 16.1.3
   @nx/nest           : 16.1.3
   @nx/node           : 16.1.3
   @nrwl/tao          : 16.1.3
   @nx/webpack        : 16.1.3
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-docker : 2.3.0
```

### Failure Logs

```shell
Error: Cannot find configuration for task app_lambda_api:affected:apps
    at ProcessTasks.createTask (/Users/user_name/project_name/node_modules/nx/src/tasks-runner/create-task-graph.js:156:19)
    at ProcessTasks.processTasks (/Users/user_name/project_name/node_modules/nx/src/tasks-runner/create-task-graph.js:23:39)
    at createTaskGraph (/Users/user_name/project_name/node_modules/nx/src/tasks-runner/create-task-graph.js:192:21)
    at createTaskGraphAndValidateCycles (/Users/user_name/project_name/node_modules/nx/src/tasks-runner/run-command.js:79:63)
    at /Users/user_name/project_name/node_modules/nx/src/tasks-runner/run-command.js:104:31
    at Generator.next (<anonymous>)
    at /Users/user_name/project_name/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/user_name/project_name/node_modules/tslib/tslib.js:163:16)
    at /Users/user_name/project_name/node_modules/nx/src/tasks-runner/run-command.js:101:114
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by tam-nguyen-yum** [comment]
Thanks a lot @leosvelperez
