### ISSUE TITLE
NX this._schemaRegistry.compile(...).pipe is not a function

### ISSUE THREAD

**Issue by raphael22** [nrwl/nx#16889]
### Current Behavior

Hi
I migrate from 13 to 16 and app:build throw this error.

### Expected Behavior

Application should build.

### Steps to Reproduce

1. Could not reproduce with workspace@16 :/

But I see that after migration I have **@nx/angular:webpack-browser** as build executor, but in fresh workspace@16 it is set to **@angular-devkit/build-angular:browser** 
Can't switch to it since I have a custom-webpack for module-federation.

### Nx Report

```shell
Node   : 18.16.0
   OS     : linux x64
   npm    : 9.5.1
   Hasher : Native

   nx (global)        : 16.0.3
   nx                 : 16.1.3
   @nx/js             : 16.1.3
   @nx/jest           : 16.1.3
   @nx/linter         : 16.1.3
   @nx/workspace      : 16.1.3
   @nx/angular        : 16.1.3
   @nx/cypress        : 16.1.3
   @nx/devkit         : 16.1.3
   @nx/eslint-plugin  : 16.1.3
   @nx/storybook      : 16.1.3
   @nrwl/tao          : 16.1.3
   @nx/web            : 16.1.3
   @nx/webpack        : 16.1.3
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @jscutlery/semver       : 3.0.0
   @ngrx/data              : 15.4.0
   @ngrx/effects           : 15.4.0
   @ngrx/entity            : 15.4.0
   @ngrx/router-store      : 15.4.0
   @ngrx/store             : 15.4.0
   @ngrx/store-devtools    : 15.4.0
   ngx-extended-pdf-viewer : 16.2.16
   rxjs                    : 6.6.7
```

### Failure Logs

```shell
> nx run shell:build-app:prod
 >  NX   this._schemaRegistry.compile(...).pipe is not a function
TypeError: this._schemaRegistry.compile(...).pipe is not a function
    at SwitchMapSubscriber.project (/home/nikopol/www/runtime_angular/node_modules/@angular-devkit/architect/src/jobs/simple-scheduler.js:108:79)
    at SwitchMapSubscriber._next (/home/nikopol/www/runtime_angular/node_modules/rxjs/internal/operators/switchMap.js:47:27)
    at Subscriber.next (/home/nikopol/www/runtime_angular/node_modules/rxjs/internal/Subscriber.js:66:18)
    at DefaultIfEmptySubscriber._next (/home/nikopol/www/runtime_angular/node_modules/rxjs/internal/operators/defaultIfEmpty.js:41:26)
    at Subscriber.next (/home/nikopol/www/runtime_angular/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/home/nikopol/www/runtime_angular/node_modules/rxjs/internal/operators/take.js:54:30)
    at Subscriber.next (/home/nikopol/www/runtime_angular/node_modules/rxjs/internal/Subscriber.js:66:18)
    at FilterSubscriber._next (/home/nikopol/www/runtime_angular/node_modules/rxjs/internal/operators/filter.js:52:30)
    at Subscriber.next (/home/nikopol/www/runtime_angular/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/home/nikopol/www/runtime_angular/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

OS: Win11 - WSL Ubuntu
node 18
npm 9

I have "some" dependencies so it's may related to a nasty peerDeps as mentioned in #16736

  "dependencies": {
    "@angular/animations": "16.0.0",
    "@angular/cdk": "16.0.0",
    "@angular/cdk-experimental": "16.0.0",
    "@angular/common": "16.0.0",
    "@angular/compiler": "16.0.0",
    "@angular/core": "16.0.0",
    "@angular/flex-layout": "14.0.0-beta.41",
    "@angular/forms": "16.0.0",
    "@angular/material": "16.0.0",
    "@angular/platform-browser": "16.0.0",
    "@angular/platform-browser-dynamic": "16.0.0",
    "@angular/router": "16.0.0",
    "@ngneat/content-loader": "7.0.0",
    "@ngneat/until-destroy": "9.2.3",
    "@ngrx/data": "15.4.0",
    "@ngrx/effects": "15.4.0",
    "@ngrx/entity": "15.4.0",
    "@ngrx/router-store": "15.4.0",
    "@ngrx/store": "15.4.0",
    "@ngrx/store-devtools": "15.4.0",
    "@ngx-translate/core": "14.0.0",
    "@ngx-translate/http-loader": "7.0.0",
    "@runtime/api-notification": "^2.1.3",
    "@runtime/api-proxyback": "^3.0.1",
    "@runtime/api-shell": "^3.0.0",
    "bowser": "2.11.0",
    "hammerjs": "2.0.8",
    "marked": "5.0.1",
    "messageformat": "2.3.0",
    "ngx-auto-unsubscribe": "3.0.1",
    "ngx-ellipsis": "4.1.1",
    "ngx-extended-pdf-viewer": "16.2.16",
    "ngx-markdown": "16.0.0",
    "ngx-socket-io": "4.4.0",
    "ngx-translate-messageformat-compiler": "6.3.0",
    "rxjs": "6.6.7"
  },
  "devDependencies": {
    "@angular-architects/module-federation": "~16.0.3",
    "@angular-architects/module-federation-tools": "~16.0.3",
    "@angular-builders/jest": "~15.0.0",
    "@angular-devkit/build-angular": "16.0.0",
    "@angular-devkit/core": "16.0.0",
    "@angular-devkit/schematics": "16.0.0",
    "@angular-eslint/eslint-plugin": "16.0.1",
    "@angular-eslint/eslint-plugin-template": "16.0.1",
    "@angular-eslint/template-parser": "16.0.1",
    "@angular/cli": "~16.0.0",
    "@angular/compiler-cli": "16.0.0",
    "@angular/language-service": "16.0.0",
    "@commitlint/cli": "17.6.3",
    "@commitlint/config-conventional": "17.6.3",
    "@commitlint/cz-commitlint": "17.5.0",
    "@jscutlery/semver": "3.0.0",
    "@nx/angular": "16.1.3",
    "@nx/eslint-plugin": "16.1.3",
    "@nx/jest": "16.1.3",
    "@nx/js": "16.1.3",
    "@nx/linter": "16.1.3",
    "@nx/web": "16.1.3",
    "@nx/workspace": "16.1.3",
    "@schematics/angular": "16.0.0",
    "@types/hammerjs": "~2.0.41",
    "@types/jest": "29.5.1",
    "@types/marked": "^4.3.0",
    "@types/node": "20.1.1",
    "@types/socket.io-client": "~1.4.36",
    "@typescript-eslint/eslint-plugin": "5.59.5",
    "@typescript-eslint/parser": "5.59.5",
    "autoprefixer": "^10.4.14",
    "commitizen": "~4.3.0",
    "css-loader": "^6.7.3",
    "dotenv": "~16.0.3",
    "eslint": "8.40.0",
    "eslint-config-prettier": "~8.8.0",
    "eslint-plugin-prettier": "~4.2.1",
    "eslint-plugin-unused-imports": "~2.0.0",
    "husky": "~8.0.3",
    "jest": "29.5.0",
    "jest-environment-jsdom": "29.5.0",
    "jest-junit": "16.0.0",
    "jest-preset-angular": "13.1.0",
    "jest-transform-stub": "~2.0.0",
    "jsonc-eslint-parser": "^2.3.0",
    "lint-staged": "~13.2.2",
    "mini-css-extract-plugin": "^2.7.5",
    "ng-packagr": "~16.0.0",
    "nx": "16.1.3",
    "nx-cloud": "16.0.5",
    "postcss": "8.4.23",
    "postcss-import": "15.1.0",
    "postcss-loader": "^7.3.0",
    "postcss-preset-env": "8.3.2",
    "postcss-url": "10.1.3",
    "prettier": "2.8.8",
    "sass": "^1.62.1",
    "sass-loader": "^13.2.2",
    "storybook-addon-themes": "^6.1.0",
    "stylelint": "~15.6.1",
    "stylelint-config-prettier-scss": "^0.0.1",
    "stylelint-config-standard-scss": "~9.0.0",
    "stylelint-declaration-strict-value": "~1.9.2",
    "stylelint-declaration-use-variable": "~1.7.3",
    "stylelint-scss": "~5.0.0",
    "ts-jest": "29.1.0",
    "ts-loader": "9.4.2",
    "ts-node": "10.9.1",
    "tslib": "2.5.0",
    "typescript": "5.0.4",
    "watch-cli": "0.2.3",
    "webpack-remove-empty-scripts": "1.0.3",
    "zone.js": "0.13.0"
  },
  "optionalDependencies": {
    "@nx/storybook": "16.1.3",
    "@storybook/addon-essentials": "7.0.9",
    "@storybook/addon-storyshots": "7.0.9",
    "@storybook/addon-storyshots-puppeteer": "7.0.9",
    "@storybook/addons": "7.0.9",
    "@storybook/angular": "7.0.9",
    "@storybook/builder-webpack5": "7.0.9",
    "@storybook/jest": "0.1.0",
    "@storybook/manager-webpack5": "6.5.16",
    "@storybook/testing-library": "0.1.0",
    "jest-image-snapshot": "6.1.0",
    "puppeteer": "20.1.2",
    "svg-sprite": "2.0.2",
    "webpack-cli": "5.1.1"
  },

### project.json:build

    "build-app": {
      "executor": "@nx/angular:webpack-browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/shell",
        "index": "apps/shell/src/index.html",
        "main": "apps/shell/src/main.ts",
        "polyfills": "apps/shell/src/polyfills.ts",
        "tsConfig": "apps/shell/tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "preserveSymlinks": true,
        "buildLibsFromSource": false,
        "assets": [],
        "scripts": [
          {
            "bundleName": "runtime-loader",
            "inject": false,
            "input": "dist/libs/loader/index.js"
          }
        ],
        "customWebpackConfig": {
          "path": "apps/shell/webpack.config.js"
        },
        "statsJson": true
      },

**Comment by AgentEnder** [comment]
https://unpkg.com/@angular-builders/jest@15.0.0/package.json

Its most likely coming from @angular-builders/jest, which doesn't support Ng 16 yet.  You could try running `npm ls @angular-devkit/core` to confirm this.

In any case, I'm going to close this out since the issue is just that a dependency doesn't have a v16 compatible version just yet.
