### ISSUE TITLE
GitLab CI/CD failing with basic NX config if there are more than 400+ changes

### ISSUE THREAD

**Issue by kostetskyroma** [nrwl/nx#16975]
### Current Behavior

Middle project for 2 apps and 45 libraries. The initial project's version of nx was 13.x.x then it was migrated to nx@16.x.x. It was around 400+ changes on git. 

GitLab CI/CD couldn't execute it, all the time I was receiving "fatal: bad object ...". 

It seems it's not enough [maxBuffer=TEN_MEGABYTES](https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/command-line-utils.ts#LL327C10-L327C24
) to process 400+ changes.

Notes:
1) I'm sure that a branch with this sha exists (locally works well)
2) I’ve created another branch with small changes from my migration branch and tried to run CI/CD and it works

### Expected Behavior

Increase or make configurable maxBuffer for parseGitOutput and other functions

### Steps to Reproduce

1. Create a project with 2 apps and 45 libraries(each library has around 20 components) with version 13.x.x
2. Migrate it incrementally (version by version) to nx@16.0.0
3. Try to run it with [basic nx config](https://nx.dev/recipes/ci/monorepo-ci-gitlab) on GitLab CI/CD

### Nx Report

```shell
Node   : 16.15.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx (global)        : 16.1.4
   nx                 : 16.1.0
   @nx/js             : 16.1.0
   @nx/jest           : 16.1.0
   @nx/linter         : 16.1.0
   @nx/workspace      : 16.1.0
   @nx/angular        : 16.1.0
   @nx/cypress        : 16.1.0
   @nx/devkit         : 16.1.0
   @nx/eslint-plugin  : 16.1.0
   @nrwl/tao          : 16.1.0
   @nx/webpack        : 16.1.0
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @auth0/auth0-angular  : 2.1.0
   @ngneat/spectator     : 10.0.1
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/schematics      : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
```

### Failure Logs

```
$ NX_HEAD=$CI_COMMIT_SHA
$ NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
$ yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3
yarn run v1.22.19
$ /builds/***/ui/***/node_modules/.bin/nx affected --base=836eac67a5f431854ddb4b52b633c438a55003a4 --head=5daf7be041570182f5e8068a1a5f41bad17e502e --target=lint --parallel=3
fatal: bad object 836eac67a5f431854ddb4b52b633c438a55003a4
nx affected
Run target for affected projects
Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
      --base  Base of the current branch (usually main)  [string]
or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
      --base  Base of the current branch (usually main)  [string]
      --head  Latest commit of the current branch (usually HEAD)  [string]
or using:
      --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas or spaces  [string]
      --uncommitted  Uncommitted changes  [boolean]
      --untracked    Untracked changes  [boolean]
Options:
      --help               Show help  [boolean]
      --version            Show version number  [boolean]
  -c, --configuration      This is the configuration to use when performing tasks on projects  [string]
  -t, --targets, --target  Tasks to run for affected projects  [string] [required]
      --output-style       Defines how Nx emits outputs tasks logs  [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes"]
      --exclude            Exclude certain projects from being processed  [string]
      --parallel           Max number of parallel processes [default is 3]  [string]
      --runner             This is the name of the tasks runner configured in nx.json  [string]
      --graph              Show the task graph of the command  [boolean] [default: false]
      --verbose            Prints additional information about the commands (e.g., stack traces)  [boolean]
      --nx-bail            Stop command execution after the first failed task  [boolean] [default: false]
      --nx-ignore-cycles   Ignore cycles in the task graph  [boolean] [default: false]
      --skip-nx-cache      Rerun the tasks even when the results are available in the cache  [boolean] [default: false]
      --all                All projects  [boolean]
Examples:
  affected -t custom-target                               Run custom target for all affected projects
  affected -t test --parallel=5                           Run tests in parallel
  affected -t test --all                                  Run the test target for all projects
  affected -t lint test build                             Run lint, test, and build targets for affected projects. Requires Nx v15.4+
  affected -t test --files=libs/mylib/src/index.ts        Run tests for all the projects affected by changing the index.ts file
  affected -t test --base=main --head=HEAD                Run tests for all the projects affected by the changes between main and HEAD (e.g., PR)
  affected -t test --base=main~1 --head=main              Run tests for all the projects affected by the last commit on main
  affected -t build --tag=$NX_TASK_TARGET_PROJECT:latest  Use the currently executing project name in your command.
Find more information and examples at https://nx.dev/nx/affected
Error: Command failed: git diff --name-only --no-renames --relative "836eac67a5f431854ddb4b52b633c438a5[50](https://gitlab.com/***/ui/***/-/jobs/4273693811#L50)03a4" "5daf7be041570182f5e8068a1a5f41bad17e502e"
fatal: bad object 836eac67a5f431854ddb4b[52](https://gitlab.com/***/ui/***-/jobs/4273693811#L52)b633c438a[55](https://gitlab.com/***/ui/***/-/jobs/4273693811#L55)003a4
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at parseGitOutput (/builds/***/ui/***/node_modules/nx/src/utils/command-line-utils.js:242:41)
    at getFilesUsingBaseAndHead (/builds/***/ui/***/node_modules/nx/src/utils/command-line-utils.js:239:12)
    at parseFiles (/builds/***/ui/***/node_modules/nx/src/utils/command-line-utils.js:192:20)
    at /builds/***/ui/***/node_modules/nx/src/command-line/affected.js:78:155
    at Generator.next (<anonymous>)
    at /builds/***/ui/***/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 62 61 64 20 6f 62 6a 65 63 74 20 38 33 36 65 61 63 36 37 61 35 66 34 33 31 38 35 34 64 64 62 34 62 35 32 62 36 33 33 63 34 33 38 ... 9 more bytes>
  ],
  pid: 1[56](https://gitlab.com/***/ui/***/-/jobs/4273693811#L56),
  stdout: <Buffer >,
  stderr: <Buffer 66 [61](https://gitlab.com/***/ui/***/-/jobs/4273693811#L61) 74 61 6c 3a 20 [62](https://gitlab.com/***/ui/***/-/jobs/4273693811#L62) 61 64 20 6f 62 6a 65 [63](https://gitlab.com/***/ui/***/-/jobs/4273693811#L63) 74 20 38 33 36 65 61 63 36 37 61 35 66 34 33 31 38 35 34 [64](https://gitlab.com/***/ui/***/-/jobs/4273693811#L64) 64 62 34 62 35 32 62 36 33 33 63 34 33 38 ... 9 more bytes>
}
error Command failed with exit code 1.


```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by darkmavis1980** [comment]
I have the same exact issue on our CI/CD pipeline (Jenkins), just upgraded from 15.9.4 to 16.2.2, and we get the same error as you do

**Comment by volago** [comment]
Hi, I have similar error, but different origin. 

There is the same crashing method:
```
 checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
```

But I got following error by running migrations (in fact cannot migrate from `15.6.3` to `15.9.3`)

```
$ yarn nx migrate --run-migrations --verbose
yarn run v1.22.19
$ nx migrate --run-migrations --verbose

 >  NX   Running 'yarn' to make sure necessary packages are installed

[1/4] Resolving packages...
success Already up-to-date.
$ ngcc --properties es2020 browser module main && node ./decorate-angular-cli.js

 >  NX   Decoration of the Angular CLI is deprecated and will be removed in a future version

   Please replace usage of "ng <command>" in any scripts, particularly for CI, with "nx <command>"


 >  NX   Angular CLI has been decorated to enable computation caching.

$ nx migrate --run-migrations --verbose
$ nx _migrate --run-migrations --verbose
$ nx migrate --run-migrations --verbose
$ nx _migrate --run-migrations --verbose
$ nx migrate --run-migrations --verbose
$ nx _migrate --run-migrations --verbose
$ nx migrate --run-migrations --verbose
$ nx _migrate --run-migrations --verbose
$ nx migrate --run-migrations --verbose
$ nx _migrate --run-migrations --verbose
$ nx migrate --run-migrations --verbose
$ nx _migrate --run-migrations --verbose
$ nx migrate --run-migrations --verbose
$ nx _migrate --run-migrations --verbose
$ nx migrate --run-migrations --verbose
$ nx _migrate --run-migrations --verbose
$ nx migrate --run-migrations --verbose
$ nx _migrate --run-migrations --verbose
$ nx migrate --run-migrations --verbose
$ nx _migrate --run-migrations --verbose
$ nx migrate --run-migrations --verbose
'nx' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\git\Volago8\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:937:43
    at Generator.next (<anonymous>)
    at C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:113:16)
    at runMigrations (C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:930:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\git\Volago8\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:937:43
    at Generator.next (<anonymous>)
    at C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:113:16)
    at runMigrations (C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:930:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\git\Volago8\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:937:43
    at Generator.next (<anonymous>)
    at C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:113:16)
    at runMigrations (C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:930:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\git\Volago8\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:937:43
    at Generator.next (<anonymous>)
    at C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:113:16)
    at runMigrations (C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:930:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\git\Volago8\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:937:43
    at Generator.next (<anonymous>)
    at C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:113:16)
    at runMigrations (C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:930:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\git\Volago8\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:937:43
    at Generator.next (<anonymous>)
    at C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:113:16)
    at runMigrations (C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:930:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\git\Volago8\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:937:43
    at Generator.next (<anonymous>)
    at C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:113:16)
    at runMigrations (C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:930:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\git\Volago8\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:937:43
    at Generator.next (<anonymous>)
    at C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:113:16)
    at runMigrations (C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:930:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\git\Volago8\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:937:43
    at Generator.next (<anonymous>)
    at C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:113:16)
    at runMigrations (C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:930:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\git\Volago8\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:937:43
    at Generator.next (<anonymous>)
    at C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\git\Volago8\node_modules\nx\node_modules\tslib\tslib.js:113:16)
    at runMigrations (C:\git\Volago8\node_modules\nx\src\command-line\migrate.js:930:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Command failed: yarn nx migrate --run-migrations --verbose


Error: Command failed: yarn nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (C:\Users\walte\AppData\Local\Temp\tmp-15632-pItqHwKpjh1h\node_modules\nx\src\utils\child-process.js:26:34)
    at C:\Users\walte\AppData\Local\Temp\tmp-15632-pItqHwKpjh1h\node_modules\nx\src\command-line\migrate\migrate.js:972:43
    at Generator.next (<anonymous>)
    at C:\Users\walte\AppData\Local\Temp\tmp-15632-pItqHwKpjh1h\node_modules\tslib\tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\walte\AppData\Local\Temp\tmp-15632-pItqHwKpjh1h\node_modules\tslib\tslib.js:163:16)
    at runMigrations (C:\Users\walte\AppData\Local\Temp\tmp-15632-pItqHwKpjh1h\node_modules\nx\src\command-line\migrate\migrate.js:965:20)
Command failed: C:\Users\walte\AppData\Local\Temp\tmp-15632-pItqHwKpjh1h\node_modules\.bin\nx _migrate --run-migrations --verbose
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Of course `nx` is installed and accessible in shell

**Comment by carlflor** [comment]
> For me, it fails with the same issue if I force-push branch. Commit history is changed and `CI_COMMIT_SHA` has value of sha of the commit before force-pushing. However, when I create new dummy commit and run the same pipeline it works well.

@kubmir did you have a fix for this?

**Comment by m3Lith** [comment]
Had the issue with a big list of changes too (900+). Changing git clone depth (temporarily) to zero worked for us: https://docs.gitlab.com/ee/ci/pipelines/settings.html#limit-the-number-of-changes-fetched-during-clone
