### ISSUE TITLE
Error using create-nx-workspace with react preset

### ISSUE THREAD

**Issue by gitLinda** [nrwl/nx#16980]
### Current Behavior

When using ```npx create-nx-workspace@latest``` with ```--preset=react-standalone``` or ```--preset=react-monorepo``` it fails when the workspace name is camel case or pascal case.

This works:
npx create-nx-workspace@latest kebab-case --preset=react-standalone
npx create-nx-workspace@latest lowercase --preset=react-standalone

This doesn't work:
npx create-nx-workspace@latest camelCase --preset=react-standalone
npx create-nx-workspace@latest PascalCase --preset=react-standalone

Console output:
```
linda@DESKTOP-BJCBISQ:~/projects$ npx create-nx-workspace@latest camelCase --preset=react-standalone

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Bundler to be used to build the application · vite
✔ Default stylesheet format             · css
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.1.4 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Successfully created the workspace: camel-case.
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/sh ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs: [ '-c', 'git rev-parse --is-inside-work-tree' ]
}

Node.js v18.16.0
```

### Expected Behavior

It creates the new workspace successfully independent of the name.

### Steps to Reproduce

Run one of the following commands:
npx create-nx-workspace@latest camelCase --preset=react-standalone
npx create-nx-workspace@latest PascalCase --preset=react-standalone
npx create-nx-workspace@latest camelCase --preset=react-monorepo
npx create-nx-workspace@latest PascalCase --preset=react-monorepo

### Nx Report

```shell
linda@DESKTOP-BJCBISQ:~/projects/camelCase$ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : linux x64
   npm    : 9.5.1
   Hasher : Native

   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/react          : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/vite           : 16.1.4
   @nx/web            : 16.1.4
   typescript         : 5.0.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by tukusejssirs** [comment]
I get the same error when using `pnpx create-nx-workspace@latest "$workspace" --preset=nest --appName "$app" --nxCloud false --packageManager pnpm --skipGit false` on Arch Linux with `node@19.9.0`, `npm@8.19.2` and `pnpm@8.19.2`.

<details>
  <summary>log</summary>

```bash
.../share/pnpm/store/v3/tmp/dlx-425787   |  +67 +++++++
.../share/pnpm/store/v3/tmp/dlx-425787   | Progress: resolved 67, reused 64, downloaded 3, added 67, done

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]


 >  NX   Creating your v16.1.4 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✔ Successfully created the workspace: $workspace.
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/sh ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs: [ '-c', 'git rev-parse --is-inside-work-tree' ]
}

Node.js v19.9.0
 ERROR  Command failed with exit code 1: create-nx-workspace $workspace --preset=nest --appName $app --nxCloud false --packageManager pnpm --skipGit false

pnpm: Command failed with exit code 1: create-nx-workspace $workspace --preset=nest --appName $app --nxCloud false --packageManager pnpm --skipGit false
    at makeError ($HOME/.cache/node/corepack/pnpm/8.3.1/dist/pnpm.cjs:24230:17)
    at handlePromise ($HOME/.cache/node/corepack/pnpm/8.3.1/dist/pnpm.cjs:24801:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] ($HOME/.cache/node/corepack/pnpm/8.3.1/dist/pnpm.cjs:206754:7)
    at async $HOME/.cache/node/corepack/pnpm/8.3.1/dist/pnpm.cjs:216086:21
    at async main ($HOME/.cache/node/corepack/pnpm/8.3.1/dist/pnpm.cjs:216053:34)
    at async runPnpm ($HOME/.cache/node/corepack/pnpm/8.3.1/dist/pnpm.cjs:216308:5)
    at async $HOME/.cache/node/corepack/pnpm/8.3.1/dist/pnpm.cjs:216300:7
```

</details>
