### ISSUE TITLE
Error running `ng lint` in lerna monorepo for Angular package

### ISSUE THREAD

**Issue by nstuyvesant** [nrwl/nx#16998]
### Current Behavior

Have a monorepo of component library packages for Angular, React, Svelte, and Vue using `lerna`.

Trying to setup the Angular 16 package in packages/angular to use eslint and prettier.

When I run `ng lint` from packages/angular, I get this error that suggests it's looking in the monorepo root for the angular.json rather than the current working directory (angular.json is there)...
```
[error] Error: ENOENT: no such file or directory, open '/Users/foo/dev/carbon-charts/angular.json'
    at Object.openSync (node:fs:601:3)
    at readFileSync (node:fs:469:35)
    at readJsonFile (/Users/foo/dev/carbon-charts/packages/angular/node_modules/nx/src/utils/fileutils.js:18:43)
    at readAngularJson (/Users/foo/dev/carbon-charts/packages/angular/node_modules/nx/src/adapter/angular-json.js:40:53)
    at mergeAngularJsonAndGlobProjects (/Users/foo/dev/carbon-charts/packages/angular/node_modules/nx/src/adapter/angular-json.js:44:17)
    at Workspaces.readProjectsConfigurations (/Users/foo/dev/carbon-charts/packages/angular/node_modules/nx/src/config/workspaces.js:66:98)
    at builderFunction (/Users/foo/dev/carbon-charts/packages/angular/node_modules/@nx/devkit/src/utils/convert-nx-executor.js:17:51)
    at onInput (/Users/foo/dev/carbon-charts/packages/angular/node_modules/@angular-devkit/architect/src/create-builder.js:139:30)
    at Object.next (/Users/foo/dev/carbon-charts/packages/angular/node_modules/@angular-devkit/architect/src/create-builder.js:57:25)
    at ConsumerObserver.next (/Users/foo/dev/carbon-charts/packages/angular/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33)
```

So it's looking in the monorepo root for angular.json rather than the packages/angular/ directory.

This only affects Angular package. I have eslint and prettier setup for all the other packages.

### Expected Behavior

That I could add eslint and prettier to the Angular package in the usual Angular way...
```bash
cd packages/angular
ng add @angular-eslint/schematics
yarn add -D prettier prettier-eslint eslint-config-prettier eslint-plugin-prettier
```

### GitHub Repo

https://github.com/nstuyvesant/carbon-charts.git

### Steps to Reproduce

```bash
git clone https://github.com/nstuyvesant/carbon-charts.git
cd carbon-charts
git checkout pr-1544
git pull
yarn install
yarn build
cd packages/angular
yarn lint
```

### Nx Report

```shell
Skipping project found at packages/core/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/react/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/svelte/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/vue/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/core/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/react/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/svelte/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/vue/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/core/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/react/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/svelte/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/vue/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/core/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/react/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/svelte/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/vue/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/core/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/react/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/svelte/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.
Skipping project found at packages/vue/demo/bundle since project bundle already exists at packages/angular/demo/bundle! Specify a unique name for the project to allow Nx to differentiate between the two projects.

 >  NX   Report complete - copy this into the issue template

   Node : 18.16.0
   OS   : darwin arm64
   yarn : 3.5.1
   
   nx            : 15.9.4
   lerna         : 6.6.2
   @nrwl/cli     : 15.9.4
   @nrwl/devkit  : 15.9.4
   @nrwl/tao     : 15.9.4
   typescript    : 5.0.4
```

### Failure Logs

```shell
See above
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Blunderchips** [comment]
Hi @nstuyvesant, this seems to be an issue with Angular v16. For a short-term fix you can downgrade to Angular v15 until it is resolved. I can confirm v15 it works on with a yarn berry monorepo where the `angular.json` is not in the root directory. 

I don't know if the issue stems from nx or with angular-eslint.

**Comment by nstuyvesant** [comment]
BTW... I just switched to invoking eslint directly and that seemed to do the trick.
