### ISSUE TITLE
Issues using NestJS GraphQL plugin as a transformer

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#17013]
### Current Behavior

As per [this example](https://github.com/nrwl/nx/issues/12966#issuecomment-1443873311), I'm adding the [NestJS GraphQL cli plugin](https://docs.nestjs.com/graphql/cli-plugin) to my project, but it doesn't seem to work. When I manually add the `@Field` decorator the server starts again.

### Expected Behavior

The plugin gets invoked and I don't need to annotate the fields with the `@Field` decorator.

### GitHub Repo

https://github.com/beeman/nx-graphql-plugin

### Steps to Reproduce

1. Create a NestJS app in an Nx Workspace
2. Set up a 'code-first' setup GraphQL using [this guide](https://docs.nestjs.com/graphql/quick-start).
3. Configure the GraphQL CLI plugin using the `transformers` property as shown [here](https://github.com/nrwl/nx/issues/12966#issuecomment-1443873311).
4. Be sad it doesn't work and build a repro 😅  

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native

   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/nest           : 16.1.4
   @nx/node           : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/webpack        : 16.1.4
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Failure Logs

```shell
[
  GraphQLError: Type HelloEntity must define one or more fields.
      at SchemaValidationContext.reportError (./nx-graphql-plugin/node_modules/graphql/type/validate.js:73:7)
      at validateFields (./nx-graphql-plugin/node_modules/graphql/type/validate.js:271:13)
      at validateTypes (./nx-graphql-plugin/node_modules/graphql/type/validate.js:244:7)
      at validateSchema (./nx-graphql-plugin/node_modules/graphql/type/validate.js:43:3)
      at graphqlImpl (./nx-graphql-plugin/node_modules/graphql/graphql.js:60:63)
      at ./nx-graphql-plugin/node_modules/graphql/graphql.js:23:43
      at new Promise (<anonymous>)
      at graphql (./nx-graphql-plugin/node_modules/graphql/graphql.js:23:10)
      at GraphQLSchemaFactory.create (./nx-graphql-plugin/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:51:65)
      at GraphQLSchemaBuilder.generateSchema (./nx-graphql-plugin/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:35:52) {
    path: undefined,
    locations: undefined,
    extensions: [Object: null prototype] {}
  },
  GraphQLError: Input Object type HelloWorldInput must define one or more fields.
      at SchemaValidationContext.reportError (./nx-graphql-plugin/node_modules/graphql/type/validate.js:73:7)
      at validateInputFields (./nx-graphql-plugin/node_modules/graphql/type/validate.js:532:13)
      at validateTypes (./nx-graphql-plugin/node_modules/graphql/type/validate.js:260:7)
      at validateSchema (./nx-graphql-plugin/node_modules/graphql/type/validate.js:43:3)
      at graphqlImpl (./nx-graphql-plugin/node_modules/graphql/graphql.js:60:63)
      at ./nx-graphql-plugin/node_modules/graphql/graphql.js:23:43
      at new Promise (<anonymous>)
      at graphql (./nx-graphql-plugin/node_modules/graphql/graphql.js:23:10)
      at GraphQLSchemaFactory.create (./nx-graphql-plugin/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:51:65)
      at GraphQLSchemaBuilder.generateSchema (./nx-graphql-plugin/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:35:52) {
    path: undefined,
    locations: undefined,
    extensions: [Object: null prototype] {}
  }
]

./nx-graphql-plugin/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:57
                throw new schema_generation_error_1.SchemaGenerationError(errors);
                      ^
Error: Schema generation error (code-first approach)
    at GraphQLSchemaFactory.create (./nx-graphql-plugin/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:57:23)
    at GraphQLSchemaBuilder.generateSchema (./nx-graphql-plugin/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:35:24)
    at GraphQLSchemaBuilder.build (./nx-graphql-plugin/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:22:20)
    at GraphQLFactory.generateSchema (./nx-graphql-plugin/node_modules/@nestjs/graphql/dist/graphql.factory.js:27:41)
    at GraphQLModule.onModuleInit (./nx-graphql-plugin/node_modules/@nestjs/graphql/dist/graphql.module.js:103:27)
    at callModuleInitHook (./nx-graphql-plugin/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at NestApplication.callInitHook (./nx-graphql-plugin/node_modules/@nestjs/core/nest-application-context.js:224:13)
    at NestApplication.init (./nx-graphql-plugin/node_modules/@nestjs/core/nest-application.js:98:9)
    at NestApplication.listen (./nx-graphql-plugin/node_modules/@nestjs/core/nest-application.js:168:33)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Related issue #12966

**Comment by TechnoPvP** [comment]
Would love to get this solved, facing same issue

**Comment by beeman** [comment]
> This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs. If we missed this issue please reply to keep it active. Thanks for being a part of the Nx community! 🙏

Please leave this open.

**Comment by ndcunningham** [comment]
Hey sorry for the late reply. I cloned the repo and ran `build` following your reproduction steps but I got no such issue.
From your repository is there something else that is needed other than just running `build`?

**Comment by beeman** [comment]
> Hey sorry for the late reply. @beeman I cloned the repo and ran `build` following your reproduction steps but I got no such issue. From your repository is there something else that is needed other than just running `build`?

Hi there @ndcunningham - it's been 13 months since I created this issue and the repro so not sure from the top of my head. 😁

I'll see if I can find some time to create a repro with the current versions and will post back if it still happens.
