### ISSUE TITLE
babelrc react-intl and vite not working properly in libraries

### ISSUE THREAD

**Issue by mrpotato3** [nrwl/nx#17020]
### Current Behavior

Using the "react-intl" library and babelrc, I want to substitute messages in both apps and libraries without using the "id" of the "formatMessage" function. In the case of apps, it works correctly by following the instructions on the "react-intl" and "vite" websites, but it does not work correctly for libraries.

Error:

```
Uncaught Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at invariant (utils.js:76:15)
    at formatMessage (message.js:31:5)
    at formatMessage2 (provider.js:46:36)
    at TestI18n (test-i18n.tsx:7:17)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
```

### Expected Behavior

All strings should be translated even if they don't have an "id".

### Steps to Reproduce

1. npx create-nx-workspace@latest
2. Select Integrated Monorepo
3. Select React
4. <name>
5. <name>
6. Vite
7. CSS
8. No
9. npx nx g @nx/react:lib common-ui
10. vitest
11. vite
12.  npx nx g @nrwl/react:component test-i18n --project=common-ui --export
13. None
16. npm install react-intl
17. Add IntlProvider
18. Create transalted strings in "app" component and "TestI18N" component without "id".
19. Import "TestI18N" Component in "app".
20. nx run testapp:serve:development
21. Error: "ils.js:76 Uncaught Error: [@formatjs/intl] An `id` must be provided to format a message."
22. Configure babelrc: https://formatjs.io/docs/tooling/babel-plugin/#via-babelconfigjson-recommended
23. Install "babel-plugin-formatjs"
24. Add .babelrc at root folder "./" or in every "app/lib" root folder.
25. Add into vite.config.ts of app and lib: 
```
react({
      babel: {
        babelrc: true,
      },
    })
```
26. Rerun app again.
27. Only "defaultMessage" without "id" in app works, library translations without "id" crashes with same message as point 21.

### Nx Report

```shell
Node   : 19.4.0
   OS     : darwin arm64
   npm    : 9.2.0
   Hasher : Native
   
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/react          : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/vite           : 16.1.4
   @nx/web            : 16.1.4
   typescript         : 5.0.4
```

### Failure Logs

```shell
Uncaught Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
    at invariant (utils.js:76:15)
    at formatMessage (message.js:31:5)
    at formatMessage2 (provider.js:46:36)
    at TestI18n (test-i18n.tsx:7:17)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by almike** [comment]
same here, even tried with ts transformer... 

```
import typescript from '@rollup/plugin-typescript'
import {transform} from '@formatjs/ts-transformer'

...


  build: {
    rollupOptions: {
      plugins: [
        typescript({
          transformers: {
            before: [
              transform({
                 overrideIdFn: '[sha512:contenthash:base64:6]',
                 additionalFunctionNames: ['$t'],
                 ast: true
              })
            ]
          }
        })
      ]
    }
  },

```

**Comment by almike** [comment]
same here, it does add the IDs to my app but not to the libs, still looking for a way to configure this

**Comment by almike** [comment]
this the cause: https://github.com/vitejs/vite-plugin-react/issues/113

**Comment by mandarini** [comment]
Thank you @almike ! I'll take a look later today and see if there's anything we should do on our end!
