### ISSUE TITLE
withReact (potentially withWeb) - pluginOptions not working

### ISSUE THREAD

**Issue by vadimka123** [nrwl/nx#17021]
### Current Behavior

withWeb has cache of config processing 
they executed twice - one time with empty pluginOptions and second time with pluginOptions passed to withReact, but used cache of config and pluginOptions simply didn’t using
I added this code to withWeb plugin to debug 
```
console.log(pluginOptions);
console.trace("Here I am!")
```
And get this result
```
{}
Trace: Here I am!
    at configure (/Users/vadimgoy/workspace/operations-os-ui/node_modules/@nx/webpack/src/utils/with-web.js:28:15)
    at combined (/Users/vadimgoy/workspace/operations-os-ui/node_modules/@nx/webpack/src/utils/config.js:29:22)
    at getWebpackConfig (/Users/vadimgoy/workspace/operations-os-ui/node_modules/@nx/webpack/src/executors/webpack/lib/get-webpack-config.js:14:12)
    at /Users/vadimgoy/workspace/operations-os-ui/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:31:57
    at Generator.next (<anonymous>)
    at /Users/vadimgoy/workspace/operations-os-ui/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/vadimgoy/workspace/operations-os-ui/node_modules/tslib/tslib.js:163:16)
    at getWebpackConfigs (/Users/vadimgoy/workspace/operations-os-ui/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:18:20)
    at webpackExecutor_1 (/Users/vadimgoy/workspace/operations-os-ui/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:81:47)
    
{ scripts: [ 'bla bla bla' ] }
Trace: Here I am!
    at configure (/Users/vadimgoy/workspace/operations-os-ui/node_modules/@nx/webpack/src/utils/with-web.js:28:15)
    at configure (/Users/vadimgoy/workspace/operations-os-ui/node_modules/@nx/react/plugins/with-react.js:47:40)
    at /Users/vadimgoy/workspace/operations-os-ui/node_modules/@nx/webpack/src/utils/config.js:19:32
    at Generator.next (<anonymous>)
    at fulfilled (/Users/vadimgoy/workspace/operations-os-ui/node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

### Expected Behavior

working pluginOptions

### Steps to Reproduce

1. withReact (most likely withWeb also) - specify any pluginOptions

### Nx Report

```shell
Node   : 18.12.1
   OS     : darwin x64
   npm    : 8.19.2
   Hasher : Native
   
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/react          : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/web            : 16.1.4
   @nx/webpack        : 16.1.4
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Can you share your `webpack.config.js` file?

**Comment by vadimka123** [comment]
Webpack Config 
```
const { composePlugins, withNx } = require('@nrwl/webpack');
const { withReact } = require('@nrwl/react');
const { withModuleFederation } = require('@nrwl/react/module-federation');

const baseConfig = require('./module-federation.config');

const config = {
  ...baseConfig,
};

// Nx plugins for webpack to build config object from Nx options and context.
module.exports = composePlugins(
  withNx(),
  withReact(),
  withModuleFederation(config),
  (config) => {
    config.module.rules.push({
      test: /\.(woff|woff2|eot|ttf|otf)$/i,
      type: 'asset/resource',
    });

    return config;
  },
  (config) => {
    // https://github.com/nrwl/nx/issues/10017
    config.output.publicPath = '...';
    return config;
  }
);
```

project.json
```
{
  "name": "host",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/host/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nrwl/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "compiler": "babel",
        "outputPath": "dist/apps/host",
        "index": "apps/host/src/index.html",
        "baseHref": "/",
        "main": "apps/host/src/main.ts",
        "tsConfig": "apps/host/tsconfig.app.json",
        "assets": ["apps/host/src/favicon.ico", "apps/host/src/assets"],
        "styles": [],
        "scripts": [],
        "webpackConfig": "apps/host/webpack.config.js"
      },
      "configurations": {
        "development": {
          "extractLicenses": false,
          "optimization": false,
          "sourceMap": true,
          "vendorChunk": true
        },
        "staging": {
          "fileReplacements": [
            {
              "replace": "apps/host/src/environments/environment.ts",
              "with": "apps/host/src/environments/environment.stg.ts"
            }
          ],
          "optimization": true,
          "outputHashing": "all",
          "deployUrl": "/apps/host/",
          "sourceMap": true,
          "namedChunks": false,
          "extractLicenses": false,
          "vendorChunk": false,
          "webpackConfig": "apps/host/webpack.config.stg.js"
        },
        "production": {
          "fileReplacements": [
            {
              "replace": "apps/host/src/environments/environment.ts",
              "with": "apps/host/src/environments/environment.prod.ts"
            }
          ],
          "optimization": true,
          "outputHashing": "all",
          "deployUrl": "/apps/host/",
          "sourceMap": true,
          "namedChunks": false,
          "extractLicenses": false,
          "vendorChunk": false,
          "webpackConfig": "apps/host/webpack.config.prod.js"
        }
      }
    },
    "serve": {
      "executor": "@nrwl/react:module-federation-dev-server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "host:build",
        "hmr": true,
        "port": 4200
      },
      "configurations": {
        "development": {
          "buildTarget": "host:build:development"
        },
        "production": {
          "buildTarget": "host:build:production",
          "hmr": false
        }
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/host/**/*.{ts,tsx,js,jsx}"]
      }
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/{projectRoot}"],
      "options": {
        "jestConfig": "apps/host/jest.config.ts",
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    },
    "serve-static": {
      "executor": "@nrwl/web:file-server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "host:build",
        "port": 4200
      },
      "configurations": {
        "development": {
          "buildTarget": "host:build:development"
        },
        "production": {
          "buildTarget": "host:build:production"
        }
      }
    }
  },
  "tags": []
}
```

Project generated with NX 15x version and latter just updated npm packages
Need something run to migrate configs or update manually ?

**Comment by jaysoo** [comment]
Can you update `project.json` with `isolatedConfig: true`?

e.g.

```
    "build": {
      "executor": "@nrwl/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
         ...
        "isolatedConfig": true,
        "webpackConfig": "apps/host/webpack.config.js"
      },
```

There was a migration that turned it on for projects, but maybe it was missed. That option, when true, will make sure we don't apply any legacy config prior to calling your webpack config file. It will be defaulted to true in Nx 17.

See: https://nx.dev/packages/webpack/documents/webpack-config-setup#using-webpack-with-

Let me know if that helps or not.

**Comment by vadimka123** [comment]
Yes, working
Thanks for help
