### ISSUE TITLE
Can't create an interface or a service in an angular project (library or app)

### ISSUE THREAD

**Issue by GlaucoGodoi** [nrwl/nx#17096]
### Current Behavior

I am using nx 16 in an Angular project and, when running the command:

npx nx generate @schematics/angular:interface oph --project=p18language --path=libs/p18language/src/lib --no-interactive --dry-run

to create an interface I am receiving the error message:

 NX   Cannot find module '../adapter/compat'
 
 Similar error message is displayed when trying to create a service. 
 When I try to create a library or a componente everything works fine.

### Expected Behavior

Interface or service created normally. 

### Steps to Reproduce

1. Create a new workspace (nx 16.2.1)
2. Create an interface using the command 
npx nx generate @schematics/angular:interface oph --project=p18language --path=libs/p18language/src/lib --no-interactive --dry-run --verbose

### Nx Report

```shell
Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin arm64
   npm    : 9.6.5
   Hasher : Native
   
   nx (global)        : 16.2.1
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/angular        : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/web            : 16.2.1
   @nx/webpack        : 16.2.1
   typescript         : 5.0.4
```

### Failure Logs

```shell
npx nx generate @schematics/angular:interface oph --project=p18language --path=libs/p18language/src/lib --no-interactive --dry-run --verbose

>  NX  Generating @schematics/angular:interface


 >  NX   Cannot find module '../adapter/compat'

   Require stack:
   - /Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/src/command-line/generate/generate.js
   - /Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/src/command-line/generate/command-object.js
   - /Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/src/command-line/nx-commands.js
   - /Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/bin/init-local.js
   - /Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/bin/nx.js

Error: Cannot find module '../adapter/compat'
Require stack:
- /Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/src/command-line/generate/generate.js
- /Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/src/command-line/generate/command-object.js
- /Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/src/command-line/nx-commands.js
- /Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/bin/init-local.js
- /Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/bin/nx.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at Mod.require (/Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/bin/init-local.js:204:36)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/glaucogodoi/Work/lib/p18lib/node_modules/nx/src/command-line/generate/generate.js:267:17)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/glaucogodoi/Work/lib/p18lib/node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
This has been fixed by: https://github.com/nrwl/nx/pull/17090
