### ISSUE TITLE
Nx generator throw an error

### ISSUE THREAD

**Issue by mreouven** [nrwl/nx#17102]
### Current Behavior

create a new nestjs module the cli throw an error (also with vscode ui)

### Expected Behavior

create files

### Steps to Reproduce

1. nx generate @nestjs/schematics:module notifcation --no-interactive --dry-run --verbose

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx (global)        : 16.2.1
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/nest           : 16.2.1
   @nx/node           : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/webpack        : 16.2.1
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Failure Logs

```shell
nx generate @nestjs/schematics:module notifcation --no-interactive --dry-run --verbose                                base at  08:05:36

>  NX  Generating @nestjs/schematics:module


 >  NX   Cannot find module '../adapter/compat'

   Require stack:
   - /Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/src/command-line/generate/generate.js
   - /Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/src/command-line/generate/command-object.js
   - /Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/src/command-line/nx-commands.js
   - /Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/bin/init-local.js
   - /Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/bin/nx.js
   - /Users/user/.nvm/versions/node/v18.14.0/lib/node_modules/nx/bin/nx.js

Error: Cannot find module '../adapter/compat'
Require stack:
- /Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/src/command-line/generate/generate.js
- /Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/src/command-line/generate/command-object.js
- /Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/src/command-line/nx-commands.js
- /Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/bin/init-local.js
- /Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/bin/nx.js
- /Users/user/.nvm/versions/node/v18.14.0/lib/node_modules/nx/bin/nx.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at Mod.require (/Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/bin/init-local.js:204:36)
    at require (/Users/user/Desktop/cymcop/cymulate-websocket/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/user/Desktop/cymcop/cymulate-websocket/node_modules/nx/src/command-line/generate/generate.js:267:17)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/Desktop/cymcop/cymulate-websocket/node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
This has been fixed by: https://github.com/nrwl/nx/pull/17090
