### ISSUE TITLE
nx affected:test --base=remotes/origin/master fails after Angular and nx upgrade

### ISSUE THREAD

**Issue by aserdarevic** [nrwl/nx#17132]
### Current Behavior

After upgrading the Angular from the version **14.x** to the **16.14.0** and NX from version **12.8.0** to the **15.8.5**, when applying same settings on Azure pipeline and running the command:

`npx nx affected:test --base=remotes/origin/master`  this command fails with next error message:

```

No tests found, exiting with code 0
node:internal/event_target:916
  process.nextTick(() => { throw err; });
                           ^

Error: Unknown worker mes***ge type mes***ge
This is caused by either a bug in Node.js or incorrect u***ge of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at new NodeError (node:internal/errors:371:5)
    at Function.fail (node:internal/assert:20:9)
    at Worker.[kOnMes***ge] (node:internal/worker:317:12)
    at Mes***gePort.<anonymous> (node:internal/worker:201:57)
    at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invokeTask (/home/vsts/work/1/s/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:446:35)
    at Zone.Object.<anonymous>.Zone.runTask (/home/vsts/work/1/s/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:214:51)
    at ZoneTask.Object.<anonymous>.ZoneTask.invokeTask [as invoke] (/home/vsts/work/1/s/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:528:38)
    at invokeTask (/home/vsts/work/1/s/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1730:22)
    at globalCallback (/home/vsts/work/1/s/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1761:31)
    at Mes***gePort.globalZoneAwareCallback (/home/vsts/work/1/s/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1797:20)
    at Mes***gePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at Mes***gePort.exports.emitMes***ge (node:internal/per_context/mes***geport:23:28) {
  code: 'ERR_INTERNAL_ASSERTION'
}

```

When running this command locally all tests pass. Beside this issue, considering that it is an NX monorepo containing multiple applications, each with its own pipeline that is either triggered only by changes related to that application, or in the case of shared libraries, all pipelines are triggered concurrently, other pipelines fail on the **_nx build_** task with following error:
`NX   Maximum call stack size exceeded`

### Expected Behavior

Tests shouldn't fail on Azure pipeline, when they're passing locally.

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 16.14.0
   OS   : linux x64
   npm  : 8.3.1
   
   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/angular           : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/cypress           : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/storybook         : 15.8.5
   @nrwl/webpack           : 15.8.5
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngneat/transloco        : 3.2.0
   @ngrx/effects            : 15.3.0
   @ngrx/store              : 15.3.0
   angular-auth-oidc-client : 11.6.11
   apollo-angular           : 2.6.0
   rxjs                     : 6.6.3
   @compodoc/compodoc       : 1.1.19
   @ngrx/schematics         : 15.3.0
   @ngrx/store-devtools     : 15.3.0
   @storybook/angular       : 7.0.2
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

There is an issue https://github.com/nrwl/nx/issues/15708 where @JelleBruisten had somewhat similar issue but changing to nx version 15.6.x didn't work.

**Comment by barbados-clemens** [comment]
Hi @aserdarevic I am unable to reproduce this.
Have you tried with latest nx?
if it's still happening after updating can you provide a reproducible repo I can clone and test? Since it's only happening in Azure CI it's almost likely some kind of setting unexpected setup that is causing an issue which will be specific to your repo/settings vs a clean/new workspace.
