### ISSUE TITLE
Cannot find module '../adapter/compat' when using ng-add

### ISSUE THREAD

**Issue by kumibrr** [nrwl/nx#17138]
### Current Behavior

After installing @angular/material with my package manager, when I try the command  npx nx g @angular/material:ng-add --project=project --verbose, I get the following error:
`
 >  NX   Cannot find module '../adapter/compat'

   Require stack:
   - node_modules/.pnpm/nx@16.2.1/node_modules/nx/src/command-line/generate/generate.js
`

### Expected Behavior

I expect the command to run

### Steps to Reproduce

1. Install @angular/material with npm i @angular/material
2. Run npx nx g @angular/material:ng-add --project=project

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : linux x64
   pnpm   : 8.5.1
   Hasher : Native

   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/angular        : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/web            : 16.2.1
   @nx/webpack        : 16.2.1
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Failure Logs

```shell
Error: Cannot find module '../adapter/compat'
Require stack:
- /home/israel/git/bitbucket/ce-legacy-to-angular-latest/node_modules/.pnpm/nx@16.2.1/node_modules/nx/src/command-line/generate/generate.js
- /home/israel/git/bitbucket/ce-legacy-to-angular-latest/node_modules/.pnpm/nx@16.2.1/node_modules/nx/src/command-line/generate/command-object.js
- /home/israel/git/bitbucket/ce-legacy-to-angular-latest/node_modules/.pnpm/nx@16.2.1/node_modules/nx/src/command-line/nx-commands.js
- /home/israel/git/bitbucket/ce-legacy-to-angular-latest/node_modules/.pnpm/nx@16.2.1/node_modules/nx/bin/init-local.js
- /home/israel/git/bitbucket/ce-legacy-to-angular-latest/node_modules/.pnpm/nx@16.2.1/node_modules/nx/bin/nx.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at Mod.require (/home/israel/git/bitbucket/ce-legacy-to-angular-latest/node_modules/.pnpm/nx@16.2.1/node_modules/nx/bin/init-local.js:204:36)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/israel/git/bitbucket/ce-legacy-to-angular-latest/node_modules/.pnpm/nx@16.2.1/node_modules/nx/src/command-line/generate/generate.js:267:17)
    at Generator.next (<anonymous>)
    at fulfilled (/home/israel/git/bitbucket/ce-legacy-to-angular-latest/node_modules/.pnpm/tslib@2.5.2/node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

As I've seen, in the 'generate.js' the path to the adapter/compat is incorrect, the adapter directory is two folders behind.
'../adapter/compat' should be '../../adapter/compat'.

**Comment by kumibrr** [comment]
I'll close the issue as I've now seen that's  been fixed and will be released in the next version.
