### ISSUE TITLE
TypeError: this._schemaRegistry.compile(...).pipe is not a function After upgrading to NX 16

### ISSUE THREAD

**Issue by shadow1349** [nrwl/nx#17215]
### Current Behavior

I created an nx workspace using NX 15 and tried upgrading to v16 using `npx nx migrate latest`, when I created a new Angular app and tried to run it, I got the following error

```
TypeError: this._schemaRegistry.compile(...).pipe is not a function
    at SwitchMapSubscriber.project (/Users/sam/node_modules/@angular-devkit/architect/src/jobs/simple-scheduler.js:108:79)
    at SwitchMapSubscriber._next (/Users/sam/node_modules/rxjs/internal/operators/switchMap.js:47:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/sam/node_modules/rxjs/internal/Subscriber.js:66:18)
    at DefaultIfEmptySubscriber._next (/Users/sam/node_modules/rxjs/internal/operators/defaultIfEmpty.js:41:26)
    at DefaultIfEmptySubscriber.Subscriber.next (/Users/sam/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/Users/sam/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/Users/sam/node_modules/rxjs/internal/Subscriber.js:66:18)
    at FilterSubscriber._next (/Users/sam/node_modules/rxjs/internal/operators/filter.js:52:30)
    at FilterSubscriber.Subscriber.next (/Users/sam/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/sam/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
```

### Expected Behavior

I should be able to run my angular app 

### Steps to Reproduce

1. Create an NX Workspace using version 15
2. Upgrade to version 16 with `npx nx migrate latest`
3. Add a new angular app
4. Try to run the angular app

### Nx Report

```shell
Node   : 16.16.0
OS     : darwin arm64
npm    : 9.6.1
Hasher : Native
   
nx                 : 16.2.1
@nx/js             : 16.2.1
@nx/jest           : 16.2.1
@nx/linter         : 16.2.1
@nx/workspace      : 16.2.1
@nx/angular        : 16.2.1
@nx/cypress        : 16.2.1
@nx/devkit         : 16.2.1
@nx/eslint-plugin  : 16.2.1
@nx/node           : 16.2.1
@nrwl/tao          : 16.2.1
@nx/webpack        : 16.2.1
nx-cloud           : 16.0.5
typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

package.json

```json
{
  "name": "techu-solutions",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "private": true,
  "devDependencies": {
    "@angular-devkit/build-angular": "16.0.2",
    "@angular-devkit/core": "^16.0.2",
    "@angular-devkit/schematics": "16.0.2",
    "@angular-eslint/eslint-plugin": "16.0.2",
    "@angular-eslint/eslint-plugin-template": "16.0.2",
    "@angular-eslint/template-parser": "16.0.2",
    "@angular/cli": "~16.0.2",
    "@angular/compiler-cli": "16.0.2",
    "@angular/language-service": "16.0.2",
    "@nx/angular": "16.2.1",
    "@nx/eslint-plugin": "16.2.1",
    "@nx/jest": "16.2.1",
    "@nx/js": "16.2.1",
    "@nx/linter": "16.2.1",
    "@nx/node": "16.2.1",
    "@nx/workspace": "16.2.1",
    "@schematics/angular": "16.0.2",
    "@types/jest": "^29.4.0",
    "@types/node": "~18.7.1",
    "@typescript-eslint/eslint-plugin": "5.59.6",
    "@typescript-eslint/parser": "5.59.6",
    "autoprefixer": "^10.4.0",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "jest": "^29.4.1",
    "jest-environment-jsdom": "^29.4.1",
    "jest-environment-node": "^29.4.1",
    "jest-preset-angular": "13.1.1",
    "nx": "16.2.1",
    "nx-cloud": "16.0.5",
    "postcss": "^8.4.5",
    "prettier": "^2.6.2",
    "tailwindcss": "^3.0.2",
    "ts-jest": "29.1.0",
    "ts-node": "10.9.1",
    "typescript": "5.0.4"
  },
  "dependencies": {
    "@angular/animations": "16.0.2",
    "@angular/cdk": "16.0.1",
    "@angular/common": "16.0.2",
    "@angular/compiler": "16.0.2",
    "@angular/core": "16.0.2",
    "@angular/fire": "^7.5.0",
    "@angular/forms": "16.0.2",
    "@angular/material": "16.0.1",
    "@angular/platform-browser": "16.0.2",
    "@angular/platform-browser-dynamic": "16.0.2",
    "@angular/router": "16.0.2",
    "@ngxs/devtools-plugin": "^3.8.0",
    "@ngxs/logger-plugin": "^3.8.0",
    "@ngxs/router-plugin": "^3.8.0",
    "@ngxs/storage-plugin": "^3.8.0",
    "@ngxs/store": "^3.8.0",
    "@sendgrid/client": "^7.7.0",
    "@sendgrid/mail": "^7.7.0",
    "firebase": "^9.20.0",
    "firebase-admin": "^11.7.0",
    "firebase-functions": "^4.3.1",
    "immer": "^10.0.1",
    "rxjs": "~7.8.0",
    "stripe": "^12.2.0",
    "sweetalert2": "^11.7.3",
    "tslib": "^2.3.0",
    "zone.js": "0.13.0"
  },
  "overrides": {
    "@angular/fire": {
      "@angular/common": "^16.0.1",
      "@angular/core": "^16.0.1",
      "@angular/platform-browser": "^16.0.1",
      "@angular/platform-browser-dynamic": "^16.0.1"
    }
  }
}
```

project.json:build
```json
    "build": {
      "executor": "@angular-devkit/build-angular:browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/main",
        "index": "apps/main/src/index.html",
        "main": "apps/main/src/main.ts",
        "polyfills": ["zone.js"],
        "tsConfig": "apps/main/tsconfig.app.json",
        "assets": ["apps/main/src/favicon.ico", "apps/main/src/assets"],
        "styles": ["apps/main/src/styles.scss"],
        "scripts": []
      },
      "configurations": {
        "production": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "500kb",
              "maximumError": "1mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "2kb",
              "maximumError": "4kb"
            }
          ],
          "outputHashing": "all"
        },
        "development": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true
        }
      },
      "defaultConfiguration": "production"
    }
```

**Comment by shadow1349** [comment]
Just a quick update I created a brand new nx 16 workspace, and everything seemed to work so I copied and pasted the dependencies and dev dependencies into my broken project, and everything seems to be working. I reinstalled all of my other dependencies, and everything still seems to be happy, so I have absolutely no clue why this migration failed in the first place but seems like something

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I'm glad you were able to address the issue. It happens because the resolved `@angular-devkit/architect` version was not aligned with the `@angular-devkit/core` version. Some breaking changes in Angular 16 would cause the error you're reporting when those packages' versions are not aligned.

Unfortunately, the `@angular-devkit/architect` package is considered an internal package by the Angular CLI. That's why it has a funny version lower than 1.0.0 (e.g. 0.1600.2) and it's not added to the workspace `package.json` (the Angular CLI doesn't add it either). It's installed as a transitive dependency of other Angular CLI packages. This can cause the wrong version to be resolved sometimes when third-party packages also have it as a dependency on an older version.

There's little we can do in this case other than advise to:

- delete your `node_modules` and the package manager lock file and reinstall the packages (sometimes this is enough and easy to try), or
- ensure third-party packages with a dependency on Angular CLI packages are updated to a version that supports the Angular version you're using, or
- add the `@angular-devkit/architect` to the `package.json` with the desired version.

I'm closing this. If anyone else ends up here, please make sure to follow the bullet points above.
