### ISSUE TITLE
NextJS 13.4 can throw Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by dprothero** [nrwl/nx#17247]
### Current Behavior

When using a component that needs useState (like MDXRemote), we are getting:

```
Cannot read properties of null (reading 'useState')
```

It seams `react` is not getting imported, or perhaps imported twice?

The problem does not occur when you do **not** use Nx. Using create-next-app, the problem doesn't occur.

### Expected Behavior

React should be found so useState, useEffect, etc. can be used normally.

### GitHub Repo

https://github.com/dprothero/mdx-remote-error

### Steps to Reproduce

1. [Here is a reproduction of the issue on codesandbox](https://codesandbox.io/p/github/dprothero/mdx-remote-error/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cli2xef9p000a3t6kvei2ql01%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cli2xef9p000a3t6kvei2ql01%2522%253A%257B%2522id%2522%253A%2522cli2xef9p000a3t6kvei2ql01%2522%252C%2522activeTabId%2522%253A%2522cli2xn2t5000a3t6kze7ukk93%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cli2xef9p00093t6k2iplb59y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cli2xg7pz00qm3t6kt0sxip5d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cli4pag0q0020fwkoboo164k3%2522%257D%252C%257B%2522id%2522%253A%2522cli2xn2t5000a3t6kze7ukk93%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npx%2520nx%2520serve%2520twilio-cli%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npx%2520nx%2520serve%2520twilio-cli%2522%252C%2522port%2522%253A4200%252C%2522id%2522%253A%2522cli2xntl200mf3t6k92vd4ogk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fdocs%252Ftwilio-cli%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522cli4pbdtw017v3t6lq2wlegfg%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%252C%257B%2522type%2522%253A%2522EMPTY_DEVTOOL%2522%252C%2522id%2522%253A%2522cli4pbjyv01913t6laq5qfpbe%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).
2. Define the starting process: `npx nx serve twilio-cli`
3. Try to load the `/docs/twilio-cli` route.

### Nx Report

```shell
Node   : 16.17.0
   OS     : darwin x64
   npm    : 9.2.0
   Hasher : Native
   
   nx (global)        : 16.2.2
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/next           : 16.2.2
   @nx/react          : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   typescript         : 5.0.4
```

### Failure Logs

```shell
- error TypeError: Cannot read properties of null (reading 'useState')
    at useState (/Users/dprothero/Projects/docs2/node_modules/react/cjs/react.development.js:1622:21)
    at MDXRemote (file:///Users/dprothero/Projects/docs2/node_modules/next-mdx-remote/dist/index.js:40:51)
    at renderWithHooks (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8674:16)
    at renderIndeterminateComponent (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8748:15)
    at renderElement (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8983:7)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9149:11)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderIndeterminateComponent (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8802:7)
    at renderElement (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8983:7)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9149:11)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderNode (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9328:12)
    at renderHostElement (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8658:3)
    at renderElement (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8989:5)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9149:11)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderNode (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9328:12)
    at renderChildrenArray (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9277:7)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:7)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderElement (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9009:9)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9149:11)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderIndeterminateComponent (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8802:7)
    at renderElement (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8983:7)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9149:11)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderIndeterminateComponent (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8802:7)
    at renderElement (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8983:7)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9149:11)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderNode (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9328:12)
    at renderChildrenArray (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9277:7)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:7)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderElement (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9009:9)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9149:11)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderNode (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9328:12)
    at renderChildrenArray (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9277:7)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9185:7)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderElement (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9009:9)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9149:11)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderContextProvider (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8947:3)
    at renderElement (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9060:11)
    at renderNodeDestructiveImpl (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9149:11)
    at renderNodeDestructive (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:9121:14)
    at renderContextProvider (/Users/dprothero/Projects/docs2/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:8947:3) {
  page: '/docs/twilio-cli'
}
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The problem does not occur when you do **not** use Nx. Using create-next-app, the problem doesn't occur.

The workaround is to downgrade Next to v13.2.4

**Comment by drkstr101** [comment]
This happens to me whenever I attempt to use `@headlessui/react` or `@vercel/analytics` (or any library using hooks I would assume) in a freshly generated nextjs app using `@nx/next@16.2.2`. 

I also get a react version mismatch error, although all projects are on `react@18.2.0`.

> Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

Just a wild guess, but I am noticing that nextjs now seems to be using its own internally built react, and this could explain the above results. I am still looking for a fix or workaround.

**Comment by brunos3d** [comment]
Up :up:

**Comment by ndcunningham** [comment]
Hi, there we don't fully support Next.js 13.4.0 as yet due to the fact that they are mixing renderers when you are using the _pages layout_: 
https://github.com/vercel/next.js/issues/49169

Initially, we did a migration but undone this change due to issues we found. https://github.com/nrwl/nx/pull/17049

Once Nx 16.3.0 is out it should support it since we will be using the Next.js CLI

**Comment by drkstr101** [comment]
Thanks for the update! I can just downgrade the nextjs version until then. Cheers!
