### ISSUE TITLE
Can't use withNx plugin with not @nx/next executors

### ISSUE THREAD

**Issue by gudvinga** [nrwl/nx#17241]
### Current Behavior

I wan't to serve and build my next.js application with nx:run-commands and nx:run-script

my current project.json looks like this
```
{
  "name": "app",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/app",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "nx:run-script",
      "options": {
        "script": "build",
        "outputs": [
          "apps/account/.next"
        ]
      }
    },
    "serve": {
      "executor": "nx:run-commands",
      "options": {
        "command": "ts-node --project apps/account/tsconfig.server.json apps/account/server/index.ts",
        "fix": true
      }
    },
```

When I try to build or serve an application I get an error
```
Error: Could not determine the config for this Next application.
```

Before updating to 16 version it worked

### Expected Behavior

Custom build and serve commands should work with withNx plugin without error

### Steps to Reproduce

1. Create next js application
2. Try to serve application with ts-node
```
    "serve": {
      "executor": "nx:run-commands",
      "options": {
        "command": "ts-node --project apps/account/tsconfig.server.json apps/account/server/index.ts"
      }
    },
```
3. Error

### Nx Report

```shell
Node   : 16.18.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native

   nx                 : 16.2.2
   lerna              : 5.6.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nrwl/devkit       : 15.4.1
   @nx/eslint-plugin  : 16.2.2
   @nx/next           : 16.2.2
   @nx/plugin         : 16.2.2
   @nx/react          : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   typescript         : 5.0.4
```

### Failure Logs

```shell
Error: Could not determine the config for this Next application.
    at getNxContext (/Users/user/Documents/projects/frontend/packages/next/plugins/with-nx.ts:120:9)
    at /Users/user/Documents/projects/frontend/packages/next/plugins/with-nx.ts:220:80
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/Documents/projects/frontend/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Warning: run-commands command "ts-node --project apps/app/tsconfig.server.json apps/account/server/index.ts" exited with non-zero status code
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

https://github.com/nrwl/nx/blob/master/packages/next/plugins/with-nx.ts#LL61C10-L61C22
getNxContext function work only with @nx/next executors.
Due to the more subtle configuration of the project, we cannot use them, perhaps we should not rely heavily on the names of the executors there and come up with another case for others

**Comment by ndcunningham** [comment]
Yes, we changed how the next plugin `withNx` works for a few reasons, one of which is so that we could using the Next CLI for our `build` and `server` executors.
