### ISSUE TITLE
Storybook stories imported from lib A cannot use lib B

### ISSUE THREAD

**Issue by JalilArfaoui** [nrwl/nx#17257]
### Current Behavior

In main application, importing `import { getSomethingFromDomain } from '@repro-app/domain-something';` (which is a lib)
In `libs/ui/components/src/lib/IconRSSI/IconRSSI.stories.tsx`

and running `npm run storybook`

breaks the story :

```shell
23:27:15 [vite] Internal server error: Failed to resolve import "@repro-app/domain-something" from "libs/ui/components/src/lib/IconRSSI/IconRSSI.stories.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/jalil/code/repro/libs/ui/components/src/lib/IconRSSI/IconRSSI.stories.tsx:16:41
  14 |    window.$RefreshSig$ = RefreshRuntime.createSignatureFunctionForTransform;
  15 |  }
  16 |  import { getSomethingFromDomain } from "@repro-app/domain-something";
     |                                          ^
  17 |  import { IconRSSI } from "./";
  18 |  export default {
      at formatError (file:///home/jalil/code/repro/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:42597:46)
      at TransformContext.error (file:///home/jalil/code/repro/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:42593:19)
      at normalizeUrl (file:///home/jalil/code/repro/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:40509:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///home/jalil/code/repro/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:40652:47
      at async Promise.all (index 3)
      at async TransformContext.transform (file:///home/jalil/code/repro/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:40578:13)
      at async Object.transform (file:///home/jalil/code/repro/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:42871:30)
      at async loadAndTransform (file:///home/jalil/code/repro/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:53335:29)
```

But if I remove this import, the story works well.

Strange thing is that if I do the same import/usage in `apps/operating-app/src/DarkModeToggle.stories.tsx` from the same domain lib, it works well

### Expected Behavior

I expect all my libs to be importable in my stories.

### GitHub Repo

https://github.com/JalilArfaoui/nx-vite-storybook-issue-repro

### Steps to Reproduce

1. `npm install`
2. `npm run storybook`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.13.0
   OS     : linux x64
   npm    : 8.19.3
   Hasher : Native
   
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/react          : 16.2.1
   @nx/storybook      : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/vite           : 16.2.1
   @nx/web            : 16.2.1
   typescript         : 4.9.5
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Repo was using Webpack and was migrated to Vite.

I stripped as much code as I could to demonstrate the issue.

**Comment by JalilArfaoui** [comment]
Just tried to update to Nx 16.2.2 but same issue …

Also, sometimes the issue is show as soon as Storybook is started, with a sligthly different message:

```shell
Error: The following dependencies are imported but could not be resolved:

  @repro-app/domain-something (imported by /home/jalil/code/repro/libs/ui/components/src/lib/IconRSSI/index.tsx)
```

**Comment by JalilArfaoui** [comment]
It looks like https://github.com/nrwl/nx/issues/2320 but I don’t think it’s the same since I can import a library if directly in app’s stories … issue only happen if I import lib X in a story in lib Y and then import stories from Y in app/A Storybook’s …

**Comment by JalilArfaoui** [comment]
@mandarini this is the issue

**Comment by danr-za** [comment]
Happens with Cypress CT + Vite as well

**Comment by mandarini** [comment]
See this: https://github.com/nrwl/nx/issues/17156#issuecomment-1603958601

**Comment by mandarini** [comment]
Valid workaround for now, to make it work:

Remove the `.stories.*` paths from your project's `tsconfig.app|lib.json`

**Comment by mandarini** [comment]
Once #17749 is merged and makes into our next minor release, you can nx migrate and a better solution will take effect!

**Comment by danr-za** [comment]
@mandarini does that also solve Cypress same error?

**Comment by mandarini** [comment]
I think it should but I am not sure. Do we have a reproduction repository where we can test? It should be easy to test I think.
