### ISSUE TITLE
Next app fails to start in production mode

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#17260]
### Current Behavior

Building a next app to use inside a container fails with:

```
node:internal/modules/cjs/loader:1070
  const err = new Error(message);
              ^

Error: Cannot find module 'semver'
Require stack:
- /usr/src/app/.nx-helpers/with-nx.js
- /usr/src/app/.nx-helpers/compiled.js
- /usr/src/app/next.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
    at /usr/src/app/node_modules/next/dist/server/require-hook.js:180:36
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at forNextVersion (/usr/src/app/.nx-helpers/with-nx.js:332:20)
    at withNx (/usr/src/app/.nx-helpers/with-nx.js:103:5)
    at /usr/src/app/.nx-helpers/compose-plugins.js:12:40
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/tslib/tslib.js:164:62) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/.nx-helpers/with-nx.js',
    '/usr/src/app/.nx-helpers/compiled.js',
    '/usr/src/app/next.config.js'
  ]
}
```

The problem is that with-nx plugins needs `semver` which is not included in the generated package.json after next app build...

### Expected Behavior

The package.json generated inside dist folder should include semver so the app can start without errors

### Steps to Reproduce

1. Create a new next app using nx 16.2.2
2. Build the app
3. Copy the builded source from `dist/apps/next-app` and paste it to another location
4. Enter to the new location and run `npm install`
5. Run `npm run start`

> Steps 3 and 4 are required, otherwise if you try to run the app from the list folder, will start without errors

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node   : 20.2.0
   OS     : darwin x64
   npm    : 9.6.7
   Hasher : Native
   
   nx (global)        : 16.2.2
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/nest           : 16.2.2
   @nx/next           : 16.2.2
   @nx/node           : 16.2.2
   @nx/react          : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.0.0-beta.1
```

### Failure Logs

```shell
node:internal/modules/cjs/loader:1070
  const err = new Error(message);
              ^

Error: Cannot find module 'semver'
Require stack:
- /usr/src/app/.nx-helpers/with-nx.js
- /usr/src/app/.nx-helpers/compiled.js
- /usr/src/app/next.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
    at /usr/src/app/node_modules/next/dist/server/require-hook.js:180:36
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at forNextVersion (/usr/src/app/.nx-helpers/with-nx.js:332:20)
    at withNx (/usr/src/app/.nx-helpers/with-nx.js:103:5)
    at /usr/src/app/.nx-helpers/compose-plugins.js:12:40
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/tslib/tslib.js:164:62) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/.nx-helpers/with-nx.js',
    '/usr/src/app/.nx-helpers/compiled.js',
    '/usr/src/app/next.config.js'
  ]
}
```
```


### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by Adherentman** [comment]
i install semver in production

**Comment by ndcunningham** [comment]
For your build inside `dist` you should run `npx next start`

We will update the `package.json` scripts in an upcoming patch to reflect this.

Let me know if this helps though.
