### ISSUE TITLE
Error during yarn pruned lock file generation - Cannot read properties of undefined

### ISSUE THREAD

**Issue by cwoebker** [nrwl/nx#17329]
### Current Behavior

Initially reported here https://github.com/nrwl/nx/pull/16886#issuecomment-1548353780 and here https://github.com/nrwl/nx/issues/17026#issuecomment-1559835992. With certain yarn.lock files the generation has been broken since v16 of NX monorepo has been released:

Unfortunately, we now encounter a different issue with the same yarn.lock file changes that I mentioned in my previous comment here: https://github.com/nrwl/nx/issues/17026#issuecomment-1548179924

We now get an error message during pruned lockfile generation: `Original error: Cannot read properties of undefined (reading 'has')`

FYI @cuddlecake @dalenguyen

### Expected Behavior

I would expect pruned yarn lock files to be generated correctly without throwing any errors.

### Steps to Reproduce

I can provide a failing yarn.lock file via direct message if needed.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native

   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/angular        : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/express        : 16.2.2
   @nx/nest           : 16.2.2
   @nx/node           : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @ionic/angular         : 7.0.9
   @ionic/angular-toolkit : 9.0.0
   @ngneat/spectator      : 14.0.0
   @ngrx/effects          : 15.4.0
   @ngrx/entity           : 15.4.0
   @ngrx/router-store     : 15.4.0
   @ngrx/store            : 15.4.0
   @ngrx/store-devtools   : 15.4.0
   ngx-toastr             : 16.2.0
   ngx-ui-loader          : 13.0.0
   ---------------------------------------
   Local workspace plugins:
   	 @remberg/remberg-nx-plugin
```

### Failure Logs

```shell
> nx run PROJECT:build:production
 >  NX   An error occured while creating pruned lockfile
   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.
   
Original error: Cannot read properties of undefined (reading 'has')
   TypeError: Cannot read properties of undefined (reading 'has')
    at /builds/PROJECT/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:230:47
    at Map.forEach (<anonymous>)
    at mapSnapshots (/builds/PROJECT/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:221:17)
    at stringifyYarnLockfile (/builds/PROJECT/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:131:23)
    at createLockFile (/builds/PROJECT/node_modules/nx/src/plugins/js/lock-file/lock-file.js:132:60)
    at /builds/PROJECT/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:42:124
    at fn (/builds/PROJECT/node_modules/@nx/webpack/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/builds/PROJECT/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:65:1)
    at eval (eval at create (/builds/PROJECT/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:78:1)
    at eval (eval at create (/builds/PROJECT/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
chunk (runtime: main) main.js (main) 374 KiB [entry] [rendered]
webpack compiled successfully (830ea7ca5a366d2f)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by cwoebker** [comment]
More details and a concrete yarn.lock file have been provided by @veimox in https://github.com/nrwl/nx/issues/17440

**Comment by joshuaja** [comment]
I'm experiencing this as well on `16.2.2`. Seems to be fixed with `16.3.2` but I'm getting a different error on that version that's preventing me from upgrading.

**Comment by cwoebker** [comment]
@joshuaja I would assume that this most likely comes from a change in the yarn.lock file. The error I reported here still persists on version 16.3.2, I just rechecked it.

**Comment by Lp-Francois** [comment]
Hello, just to confirm I experience the same issue on 16.3.2
