### ISSUE TITLE
cypress configuration produces wrong path for component-index.html in Angular component testing

### ISSUE THREAD

**Issue by electrofLy** [nrwl/nx#17383]
### Current Behavior

Cypress component tests running in watch mode there is an error where the only way of resolving it is to restart Cypress. This happens on code change and/or on tests rerun.

### Expected Behavior

No errors on code changes and tests rerun

### Steps to Reproduce

1. In cypress.config.ts include:
```
import { nxComponentTestingPreset } from '@nx/angular/plugins/component-testing';

const preset: Cypress.ConfigOptions = {
  component: {
    ...nxComponentTestingPreset(__filename),
  }
}
```
2. Open a component test
3. Make a code change (might need a few tries)
4. You should get the following error (check Failure Logs) (mind that `codePath` is included twice thus the wrong path):

PS: commenting out `...nxComponentTestingPreset(__filename)` in the configuration makes cypress work correctly again but I assume some important configuration is gone.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template
                                                            
   Node   : 18.10.0                                         
   OS     : win32 x64                                       
   npm    : 8.19.2                                          
   Hasher : Native                                          
                                                            
   nx                 : 16.3.0                              
   @nx/js             : 16.3.0                              
   @nx/jest           : 16.3.0                              
   @nx/linter         : 16.3.0                              
   @nx/workspace      : 16.3.0                              
   @nx/angular        : 16.3.0                              
   @nx/cypress        : 16.3.0                              
   @nx/devkit         : 16.3.0
   @nx/eslint-plugin  : 16.3.0
   @nrwl/tao          : 16.3.0
   @nx/webpack        : 16.3.0
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.13.0
   @jscutlery/semver                : 3.0.0
   @ngneat/transloco                : 4.2.7
   ngx-deploy-npm                   : 6.0.0
```

### Failure Logs

```shell
Error: ENOENT: no such file or directory, utime 'C:\codePath\codePath\cypress\support\component-index.html'
    at utimesSync (node:fs:2028:3)
    at EventEmitter.CypressCTWebpackPlugin.onSpecsChange (C:\Users\dummy\AppData\Local\Cypress\Cache\12.13.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-dev-server\dist\CypressCTWebpackPlugin.js:70:13)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at EventEmitter. (C:\Users\dummy\AppData\Local\Cypress\Cache\12.13.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\dev-server.js:9:21)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at process. (C:\Users\dummy\AppData\Local\Cypress\Cache\12.13.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (C:\Users\dummy\AppData\Local\Cypress\Cache\12.13.0\Cypress\resources\app\node_modules\@cspotcode\source-map-support\source-map-support.js:745:40)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by electrofLy** [comment]
@barbados-clemens you nailed it :) indeed I had the project root path defined with an empty string for some reason. After removing it it started working correctly. Epic!
