### ISSUE TITLE
No native build found for @parcel/watcher due to NPM_CONFIG_PLATFORM being set to production

### ISSUE THREAD

**Issue by rraziel** [nrwl/nx#17402]
### Current Behavior

When attempting to start the Nx daemon through an Nx task, it errors saying it can't compute the dependency graph but the daemon log points to a different issue (cf. failure logs block).

After some digging, this is what I found (with a completely cleared `node_modules/.cache/nx`):

**🟢 Daemon started before the task**

If I start the daemon before running the task, there is no issue, e.g.:

```sh
pnpm nx daemon --start
pnpm lint:all # package.json script for nx run-many --all --target=lint
```

Looking at the Nx daemon logs, it starts correctly:

```
[NX Daemon Server] - 2023-06-03T09:21:08.441Z - Started listening on: \\.\pipe\nx\C:\Users\micha\AppData\Local\Temp\9693a78a6e5f92bb7a16\d.sock
[NX Daemon Server] - 2023-06-03T09:21:08.447Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-03T09:21:08.448Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2023-06-03T09:21:08.448Z - [WATCHER]: Subscribed to changes within: snip-snip
```

Although there is an error while building the dependency graph when the task starts, but maybe that's "normal":

```
[NX Daemon Server] - 2023-06-03T09:21:39.787Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-03T09:21:39.788Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2023-06-03T09:21:39.788Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-03T09:21:39.791Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-03T09:21:40.128Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-03T09:21:41.381Z - Time taken for 'hash changed files from watcher' 42.54799997806549ms
[NX Daemon Server] - 2023-06-03T09:21:43.036Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-06-03T09:21:43.045Z - Time taken for 'total for creating and serializing project graph' 3245.0033000707626ms
[NX Daemon Server] - 2023-06-03T09:21:43.045Z - Done responding to the client project-graph
```

**🔴 Daemon started by the task**

When the daemon is not running (and again, a cleared Nx cache):

```sh
pnpm lint:all # package.json script for nx run-many --all --target=lint
```

The following is displayed in the console:

```sh
 >  NX   Nx Daemon was not able to compute the project graph.

   Log file with the error: snip-snip\node_modules\.cache\nx\d\daemon-error.log
   Please file an issue at https://github.com/nrwl/nx
   Nx Daemon is going to be disabled until you run "nx reset".
```

And the error log is the one above, specifically with this error:

```
Error: No native build was found for platform=production arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.14.2
```

Digging a bit into it, node-gyp-build detects the platform - which I assume should be `win32` in this scenario - using the following code:

```js
var platform = process.env.npm_config_platform || os.platform()
```

If I comment out the process.env part, then the daemon can start properly (as it picks the right platform).

I also tested with other tasks (test, etc.) so this does not seem to be specific to eslint or jest (or their plugins).

**Root cause?**

Before starting the daemon, the environment variable (`NPM_CONFIG_PLATFORM`) is not set, so I assumed either pnpm or Nx itself sets the variable (because "production" sounds like an environment thing in the project configuration, development vs production). However I didn't see any reference to that variable in the Nx repository... or in the pnpm repository.

In the end, I found out that while this does not work:

```sh
pnpm lint:all # package.json script for nx run-many --all --target=lint
```

This does:

```sh
pnpm nx run-many --all --target=lint
```

And now I'm not sure whether that is an issue with the way Nx starts processes or the way pnpm works, or even node-gyp 😅

### Expected Behavior

No error when starting Nx daemon

### Steps to Reproduce

Anything that starts the Nx daemon causes the error, but it's a rather large project that can't really be shared 😅

### Nx Report

```shell
Node   : 18.14.2
   OS     : win32 x64
   pnpm   : 8.5.1
   Hasher : Native

   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/angular        : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/node           : 16.2.2
   @nx/rollup         : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
```

### Failure Logs

```shell
Error: No native build was found for platform=production arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.14.2
    loaded from: snip-snip\node_modules\.pnpm\@parcel+watcher@2.0.4\node_modules\@parcel\watcher

    at load.resolve.load.path (snip-snip\node_modules\.pnpm\node-gyp-build@4.6.0\node_modules\node-gyp-build\node-gyp-build.js:60:9)
    at load (snip-snip\node_modules\.pnpm\node-gyp-build@4.6.0\node_modules\node-gyp-build\node-gyp-build.js:22:30)
    at Object.<anonymous> (snip-snip\node_modules\.pnpm\@parcel+watcher@2.0.4\node_modules\@parcel\watcher\index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at snip-snip\node_modules\.pnpm\nx@16.2.2_@swc+core@1.3.57\node_modules\nx\src\daemon\server\watcher.js:90:60
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by rraziel** [comment]
Well eventually found out something had somehow set `platform=production` on my pnpm config environment (since I couldn't reproduce it on another machine), so... ignore everything 😅
