### ISSUE TITLE
Migrate CRA app to integrated monorepo

### ISSUE THREAD

**Issue by zanatoshi** [nrwl/nx#17421]
### Current Behavior

On a CRA react app repository, migrating to an integrated NX repo with Vite is failing.
![image](https://github.com/nrwl/nx/assets/3593258/c61fb7b5-5c26-4f59-b6a7-156659dd86e9)

### Expected Behavior

Expect to migrate the app to vite in a NX monorepo

### Steps to Reproduce

1. `NX_VERBOSE_LOGGING=true npx nx@latest init --integrated --force --nxCloud`

### Nx Report

```shell
N/A
```

### Failure Logs

```shell
>  NX   🐳 Nx initialization


 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]


 >  NX   Creating your v16.3.2 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "yarn install" several times. Please wait.

✔ Installing dependencies with yarn
✖ Creating your workspace in temp-workspace

 >  NX   Failed to create a workspace.

   Error: error Command failed with exit code 1.

   Stack: CreateNxWorkspaceError: error Command failed with exit code 1.

    at /home/florian/.npm/_npx/505743838affa773/node_modules/create-nx-workspace/src/utils/child-process-utils.js:38:21
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

nx init

Adds Nx to any type of workspace. It installs nx, creates an nx.json configuration file and optionally sets up distributed caching. For
more info, check https://nx.dev/recipes/adopting-nx.

Options:
  --help         Show help                                                                                                      [boolean]
  --version      Show version number                                                                                            [boolean]
  --nxCloud      Set up distributed caching with Nx Cloud.                                                                      [boolean]
  --interactive  When false disables interactive input prompts for options.                                     [boolean] [default: true]
  --integrated   Migrate to an Nx integrated layout workspace. Only for Angular CLI workspaces and CRA projects.
                                                                                                               [boolean] [default: false]
  --addE2e       Set up Cypress E2E tests in integrated workspaces. Only for CRA projects.                     [boolean] [default: false]
  --force        Force the migration to continue and ignore custom webpack setup or uncommitted changes. Only for CRA projects.
                                                                                                               [boolean] [default: false]
  --vite         Use Vite as the bundler. Only for CRA projects.                                                [boolean] [default: true]

Error: Command failed: npx -y create-nx-workspace@latest temp-workspace --appName=identity-frontend --preset=react-monorepo --style=css --bundler=vite --packageManager=yarn --nxCloud
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at createTempWorkspace (/home/florian/.npm/_npx/f948e921c5898768/node_modules/nx/src/command-line/init/implementation/react/index.js:132:34)
    at /home/florian/.npm/_npx/f948e921c5898768/node_modules/nx/src/command-line/init/implementation/react/index.js:87:9
    at Generator.next (<anonymous>)
    at /home/florian/.npm/_npx/f948e921c5898768/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/florian/.npm/_npx/f948e921c5898768/node_modules/tslib/tslib.js:163:16)
    at reorgnizeWorkspaceStructure (/home/florian/.npm/_npx/f948e921c5898768/node_modules/nx/src/command-line/init/implementation/react/index.js:86:20) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 99574,
  stdout: null,
  stderr: null
}
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This is a private project, can't give a repository link.
Could not reproduce in a public repository.
Anyway I can debug this somehow ?

Also tried on macOS

**Comment by xiongemi** [comment]
These steps failed to create a temp-workspace in your repo. I don't see why it would. it does the same thing where you run `npx -y create-nx-workspace@latest temp-workspace --appName=identity-frontend --preset=react-monorepo --style=css --bundler=vite --packageManager=yarn --nxCloud` at workspace root. it should be same behaviour for private vs public repo.

**Comment by zanatoshi** [comment]
If I run this command `NX_VERBOSE_LOGGING=true npx -y create-nx-workspace@latest temp-workspace --appName=identity-frontend --preset=react-monorepo --style=css --bundler=vite --packageManager=yarn` , I have this result:
```
 >  NX   Failed to create a workspace.

   Error: error Command failed with exit code 1.

   Stack: CreateNxWorkspaceError: error Command failed with exit code 1.

    at /home/florian/.npm/_npx/505743838affa773/node_modules/create-nx-workspace/src/utils/child-process-utils.js:38:21
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

Let me know if you need any other info.

**Comment by xiongemi** [comment]
@zanatoshi is there already a temp-workspace folder in your workspace? if so could you delete the folder and run the command again `NX_VERBOSE_LOGGING=true npx -y create-nx-workspace@latest temp-workspace --appName=identity-frontend --preset=react-monorepo --style=css --bundler=vite --packageManager=yarn`?
if this does not work, could you paste the `yarn-error.log` under temp-workspace?

**Comment by TNAJanssen** [comment]
I have the same issue here

**Comment by TNAJanssen** [comment]
https://github.com/yarnpkg/berry/issues/625 <- is the issue

**Comment by xiongemi** [comment]
is it an issue yarn? when there is yarn.lock already in the workspace, there is some issue doing `yarn install` for create-nx-workspace?

**Comment by zanatoshi** [comment]
So if I delete yarn.lock, then it use npm instead which go further than yarn but still failed because of missing npm lock file.
