### ISSUE TITLE
Cannot build after migrating to nx 16.3.2

### ISSUE THREAD

**Issue by omerfaran** [nrwl/nx#17546]
### Current Behavior

After migrating NX from version 15.3.0 to version 16.3.2, by running `nx migrate latest`, when trying to build the app, I'm receiving the following error:

```
TypeError: Cannot destructure property 'options' of 'undefined' as it is undefined.
    at configure (E:\***\***\***\node_modules\.pnpm\@nx+webpack@16.3.2_@types+node@18.14.2_esbuild@0.17.19_nx@16.3.2_typescript@5.0.4\node_modules\@nx\webpack\src\utils\with-web.js:26:50)
    at configure (E:\\***\***\***\node_modules\.pnpm\@nx+react@16.3.2_eslint@8.15.0_nx@16.3.2_typescript@5.0.4_webpack@5.75.0\node_modules\@nx\react\plugins\with-react.js:47:40)
    at module.exports (E:\***\***\***\packages\***\custom-webpack.config.js:7:3)
```
    
My package.json devDependencies:

```
  "devDependencies": {
    "@babel/core": "7.12.13",
    "@babel/preset-react": "^7.14.5",
    "@babel/preset-typescript": "7.12.13",
    "@emotion/babel-plugin": "11.10.6",
    "@nrwl/js": "16.3.2",
    "@nrwl/rollup": "16.3.2",
    "@nrwl/webpack": "16.3.2",
    "@nx/cypress": "16.3.2",
    "@nx/eslint-plugin": "16.3.2",
    "@nx/jest": "16.3.2",
    "@nx/js": "16.3.2",
    "@nx/linter": "16.3.2",
    "@nx/react": "16.3.2",
    "@nx/storybook": "16.3.2",
    "@nx/vite": "16.3.2",
    "@nx/web": "16.3.2",
    "@nx/workspace": "16.3.2",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.7",
    "@storybook/addon-essentials": "7.0.20",
    "@storybook/addon-viewport": "^7.0.20",
    "@storybook/core-server": "7.0.20",
    "@storybook/react": "7.0.20",
    "@storybook/react-webpack5": "7.0.20",
    "@svgr/webpack": "^6.1.2",
    "@testing-library/react": "14.0.0",
    "@types/chrome": "^0.0.203",
    "@types/jest": "29.4.4",
    "@types/node": "18.14.2",
    "@types/papaparse": "^5.3.5",
    "@types/react": "18.0.28",
    "@types/react-date-range": "^1.4.4",
    "@types/react-dom": "18.0.11",
    "@types/react-helmet": "^6.1.6",
    "@typescript-eslint/eslint-plugin": "5.59.9",
    "@typescript-eslint/parser": "5.59.9",
    "babel-loader": "8.1.0",
    "css-loader": "^6.4.0",
    "cypress": "^12.2.0",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "eslint-plugin-import": "2.27.5",
    "eslint-plugin-jsx-a11y": "6.7.1",
    "eslint-plugin-react": "7.32.2",
    "eslint-plugin-react-hooks": "4.6.0",
    "eslint-plugin-storybook": "^0.6.12",
    "jest": "29.4.3",
    "jest-environment-jsdom": "29.4.3",
    "nx": "16.3.2",
    "nx-cloud": "16.0.5",
    "prettier": "^2.6.2",
    "react-refresh": "^0.10.0",
    "storybook": "7.0.20",
    "style-loader": "^3.3.0",
    "stylus": "^0.55.0",
    "stylus-loader": "^7.1.0",
    "ts-jest": "29.1.0",
    "ts-node": "10.9.1",
    "type-fest": "^3.8.0",
    "typescript": "5.0.4",
    "url-loader": "^4.1.1",
    "vite-plugin-eslint": "1.8.1",
    "webpack": "^5.75.0",
    "webpack-merge": "^5.8.0"
  },
```

Thank you very much in advance

### Expected Behavior

Should build successfully 

### Steps to Reproduce

Migrate from version 15.3.0 to version 16.3.2

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   pnpm   : 7.27.1
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/react          : 16.3.2
   @nrwl/rollup       : 16.3.2
   @nx/storybook      : 16.3.2
   @nx/vite           : 16.3.2
   @nx/web            : 16.3.2
   @nrwl/webpack      : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by omerfaran** [comment]
Found it

For anyone using custom webpack config:

`const nrwlConfig = require('@nx/react/plugins/webpack.js');`

Make sure to pass a second options argument:
`nrwlConfig(config, {});`

So options won't be undefined
