### ISSUE TITLE
NestJS fails to compile

### ISSUE THREAD

**Issue by rassawyer** [nrwl/nx#17557]
### Current Behavior

When I try to run the NestJS backend, it fails with errors related to the create-package-json file.

### Expected Behavior

When I run pnpm api, it should compile and run the backend in dev mode, listening for changes, and serving on localhost:8000

### GitHub Repo

https://github.com/rassawyer/ClickUp

### Steps to Reproduce

1. Pull down repo
2. run `pnpm i`
3. run `pnpm api`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.20.0
   OS     : linux x64
   pnpm   : 8.6.1
   Hasher : Native

   nx (global)        : 16.2.2
   nx                 : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/nest           : 16.3.2
   @nx/node           : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/webpack        : 16.3.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   ng-mocks : 13.0.3
```

### Failure Logs

```shell
pnpm api --verbose

> integro@0.0.3 api /home/rassawyer/Code/Integro/ClickUp/integro
> nx run api:serve "--verbose"


 >  NX   Using `implicitDependencies` for global implicit dependencies configuration is no longer supported.

   Use "namedInputs" instead. You can run "nx repair" to automatically migrate your configuration.
   For more information about the usage of "namedInputs" see https://nx.dev/deprecated/global-implicit-dependencies#global-implicit-dependencies


> nx run api:serve


 >  NX   RunStart


{
  "meta": {
    "nxCloudVersion": "16.0.5"
  },
  "branch": null,
  "runGroup": "b161ea680ab4ddd27b7adc61719d63ba6f798e4b",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "4764711903537708902"
  ]
}


 >  NX   Received ERR_BAD_REQUEST. Retrying in 3519.9329341417906ms.


 >  NX   Using `implicitDependencies` for global implicit dependencies configuration is no longer supported.

   Use "namedInputs" instead. You can run "nx repair" to automatically migrate your configuration.
   For more information about the usage of "namedInputs" see https://nx.dev/deprecated/global-implicit-dependencies#global-implicit-dependencies


 >  NX   RunStart


{
  "meta": {
    "nxCloudVersion": "16.0.5"
  },
  "branch": null,
  "runGroup": "b161ea680ab4ddd27b7adc61719d63ba6f798e4b",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "14382644044564379690"
  ]
}


 >  NX   Received ERR_BAD_REQUEST. Retrying in 2054.876774980886ms.


 >  NX   Nx Cloud: Cache miss 14382644044564379690.


> nx run api:build

 >  NX   Cannot read properties of undefined (reading 'data')
HookWebpackError: Cannot read properties of undefined (reading 'data')
    at makeWebpackError (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/webpack@5.85.1/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/webpack@5.85.1/node_modules/webpack/lib/Compilation.js:3068:12
    at eval (eval at create (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at fn (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/webpack@5.85.1/node_modules/webpack/lib/Compilation.js:481:17)
    at _next0 (eval at create (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/webpack@5.85.1/node_modules/webpack/lib/Compilation.js:503:10
    at Hook.eval [as callAsync] (eval at create (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:18:14)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'data')
    at /home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/nx@16.3.2/node_modules/nx/src/plugins/js/package-json/create-package-json.js:36:55
    at Array.forEach (<anonymous>)
    at createPackageJson (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/nx@16.3.2/node_modules/nx/src/plugins/js/package-json/create-package-json.js:34:79)
    at /home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/@nx+webpack@16.3.2_@types+node@18.7.1_nx@16.3.2_typescript@5.0.4/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:34:64
    at fn (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/webpack@5.85.1/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/webpack@5.85.1/node_modules/webpack/lib/Compilation.js:503:10
    at Hook.eval [as callAsync] (eval at create (/home/rassawyer/Code/Integro/ClickUp/integro/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)



 >  NX   Running target build for project api failed

   Failed tasks:

   - api:build

   Hint: run the command with --verbose for more details.


 >  NX   Nx Cloud Problems

   - Error when connecting to Nx Cloud. Code: ERR_BAD_REQUEST. Error: Invalid Nx Cloud access token. Token: tbd=.


Build failed, waiting for changes to restart...
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I recently took over maintaining/developing this project, after it had been stagnant for about 8 months. I used `nx migrate` to bring the packages and dependencies up to date, then switched from npm to pnpm

**Comment by rassawyer** [comment]
This is only my second time ever opening a Github issue. If I made any mistakes, I apologize. If there is any additional information that would be helpful, I will gladly provide it, as long as I am able.

**Comment by Tirke** [comment]
Same as #17450 we can close this one :)

**Comment by ibockowsky** [comment]
Use 16.1.4, latest version where nestjs seems to be working ;)

**Comment by mandarini** [comment]
I will be closing as duplicate. Or maybe as fixed @ibockowsky . I will check this out later today
