### ISSUE TITLE
Cannot find module 'typescript' with npx create-nx-workspace@latest myworkspace

### ISSUE THREAD

**Issue by mrambow** [nrwl/nx#1755]
Using **npx create-nx-workspace@latest myworkspace** results in an error:

```
C:\Code\GIT>npx create-nx-workspace@latest myworkspace
npx: Installierte 162 in 21.846s
? What to create in the new workspace angular           [a workspace with a single Angular application]
new myworkspace --preset="angular" --appName="test" --style="scss" --collection=@nrwl/workspace
An unhandled exception occurred: Cannot find module 'typescript'
See "C:\Users\mra\AppData\Local\Temp\ng-WAGtrx\angular-errors.log" for further details.
(node:28184) UnhandledPromiseRejectionWarning: Error: Command failed: "C:\Users\mra\AppData\Local\Temp\tmp-28184IY72CPEkEALY\node_modules\.bin\ng" new myworkspace --preset="angular" --appName="test" --style="scss" --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:600:11)
    at Object.execSync (child_process.js:637:13)
    at createApp (C:\Users\mra\AppData\Roaming\npm-cache\_npx\28184\node_modules\create-nx-workspace\bin\create-nx-workspace.js:309:21)
    at C:\Users\mra\AppData\Roaming\npm-cache\_npx\28184\node_modules\create-nx-workspace\bin\create-nx-workspace.js:60:21
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:28184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Expected behavior would be that it installs an work space with an angular project.
npm Version: 6.11.2
typescript 3.5.3

Related to https://github.com/nrwl/nx/issues/1581

**Comment by mrambow** [comment]
Same error

**Comment by vsavkin** [comment]
@mrambow could you go to the temporary folder created by `create-nx-workspace` to check if typescript is installed in the node_modules folder. 

Could you pasted the list of packages installed in node_modules?

**Comment by mrambow** [comment]
@vsavkin Typescript is installed with version 3.4.5 (as requested in the package.json).

folders/packages in the node_modules folder:
https://gist.github.com/mrambow/9b722296d8d31ebc8d4ddd11383647b2

**Comment by mrambow** [comment]
> @mrambow could you try `npx --ignore-existing create-nx-workspace@latest myworkspace`?

This is working now :)
Thanks a lot!
