### ISSUE TITLE
$ nx run cart:serve:development --verbose <- ignores verbose flag

### ISSUE THREAD

**Issue by kevinbeal** [nrwl/nx#17636]
### Current Behavior

Verbose flag changes nothing about the output in my console. I get this whether --verbose is used or not:

```
>  NX   Running target serve for project cart failed

   Failed tasks:
   
   - cart:serve:development
   
   Hint: run the command with --verbose for more details.

   View structured, searchable error logs at https://nx.app/runs/GxUuXa5HPn

kevinbeal@Kev nx-examples % Error: write EPIPE
    at process.target._send (node:internal/child_process:849:20)
    at process.target.send (node:internal/child_process:722:19)
    at /Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at process.target._send (node:internal/child_process:849:20)
    at process.target.send (node:internal/child_process:722:19)
    at /Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

### Expected Behavior

I would expect there to be more output about what is happening when you run the command, or at least not show this bit:
>  Hint: run the command with --verbose for more details.

### GitHub Repo

https://github.com/kevinbeal/nx-examples

### Steps to Reproduce

1. Open up the latest nx-examples repo
2. Run some process on port 4200 (to make an error show up)
3. run $ nx run cart:serve:development --verbose 
4. observe the hint message

### Nx Report

```shell
Node   : 16.5.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 16.4.0-beta.3
   @nx/js             : 16.4.0-beta.3
   @nx/jest           : 16.4.0-beta.3
   @nx/linter         : 16.4.0-beta.3
   @nx/workspace      : 16.4.0-beta.3
   @nx/angular        : 16.4.0-beta.3
   @nx/cypress        : 16.4.0-beta.3
   @nx/devkit         : 16.4.0-beta.3
   @nx/eslint-plugin  : 16.4.0-beta.3
   @nx/react          : 16.4.0-beta.3
   @nrwl/tao          : 16.4.0-beta.3
   @nx/web            : 16.4.0-beta.3
   @nx/webpack        : 16.4.0-beta.3
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
```

### Failure Logs

```shell
>  NX   Running target serve for project cart failed

   Failed tasks:
   
   - cart:serve:development
   
   Hint: run the command with --verbose for more details.

   View structured, searchable error logs at https://nx.app/runs/GxUuXa5HPn

kevinbeal@Kev nx-examples % Error: write EPIPE
    at process.target._send (node:internal/child_process:849:20)
    at process.target.send (node:internal/child_process:722:19)
    at /Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at process.target._send (node:internal/child_process:849:20)
    at process.target.send (node:internal/child_process:722:19)
    at /Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:27:31
    at new Promise (<anonymous>)
    at sendMessage (/Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:19:38)
    at /Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:60:27
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kevinbeal/www/nx-examples/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/expose-rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I understand why I'm getting the error in the first place.

**Comment by jeremiah-snee-openx** [comment]
Also Having this issue, while having failing build and no helpful console output.

Running
```sh
 nx "build" "app-ui" "--maxWorkers=3" "--memoryLimit=768" "--prod" "--outputPath=dist-for-tests/apps/app-ui" "--verbose"

nx run app-ui:build:production  
```

Tried adding `--`
```sh
nx "build" "publisher-ui" "--maxWorkers=3" "--memoryLimit=768" "--prod" "--outputPath=dist-for-tests/apps/publisher-ui" "--" "--verbose"

nx run publisher-ui:build:production --verbose #added verbose
```

But the result is the same

```sh
...
<s> [webpack.Progress] 92% sealing asset processing copy-webpack-plugin
<i> [webpack.Progress]  |  | 90 ms asset processing > copy-webpack-plugin
<s> [webpack.Progress] 92% sealing asset processing TerserPlugin

 

 >  NX   Running target build for project app-ui failed

   Failed tasks:
   
   - app-ui:build:production
   
   Hint: run the command with --verbose for more details.
   ```

**Comment by t-mish** [comment]
Any updates?

**Comment by t-mish** [comment]
Seems the same for Nx 16.2.1

```
    "@nx/angular": "^16.6.0",
    "@nx/eslint-plugin": "16.2.1",
    "@nx/jest": "16.2.1",
    "@nx/js": "16.2.1",
    "@nx/linter": "16.2.1",
    "@nx/workspace": "16.2.1",
```

**Comment by jeremiah-snee-openx** [comment]
Seems to be related to memory available, and possible trying to allocate memory that has been claimed by another process

**Comment by carmenleira** [comment]
Hi, I am completely new to code. I am just using it for a specific task at work as a designing. I didn't have a problem with npm start until now, and this shows: 

PS C:\Users\Intern1\Desktop\dev\calypso-ui> npm start

> calypso-ui@1.3.0 start
> nx serve x-lng


> nx run x-lng:serve:development

⠴ Generating browser application bundles (phase: sealing)...
<--- Last few GCs --->

[11340:000001DE8AB10240]    48112 ms: Mark-Compact 1915.5 (2084.5) -> 1901.8 (2067.0) MB, 535.17 / 0.00 ms  (average mu = 0.257, current mu = 0.163) allocation failure; scavenge might not succeed
[11340:000001DE8AB10240]    48766 ms: Mark-Compact 1910.0 (2075.1) -> 1907.5 (2066.4) MB, 631.62 / 0.00 ms  (average mu = 0.152, current mu = 0.035) allocation failure; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF67EF371AB node::SetCppgcReference+16075
 2: 00007FF67EEADCC6 v8::base::CPU::num_virtual_address_bits+79190
 3: 00007FF67EEAFED5 v8::base::CPU::num_virtual_address_bits+87909
 4: 00007FF67F91F061 v8::Isolate::ReportExternalAllocationLimitReached+65
 5: 00007FF67F9087F8 v8::Function::Experimental_IsNopFunction+1336
 6: 00007FF67F76A120 v8::Platform::SystemClockTimeMillis+659328
 7: 00007FF67F7763A3 v8::Platform::SystemClockTimeMillis+709123
 8: 00007FF67F773D04 v8::Platform::SystemClockTimeMillis+699236
 9: 00007FF67F766E40 v8::Platform::SystemClockTimeMillis+646304
10: 00007FF67F77C4BA v8::Platform::SystemClockTimeMillis+733978
11: 00007FF67F77CD37 v8::Platform::SystemClockTimeMillis+736151
12: 00007FF67F78596E v8::Platform::SystemClockTimeMillis+772046
13: 00007FF67F7962B6 v8::Platform::SystemClockTimeMillis+839958
14: 00007FF67F79AE88 v8::Platform::SystemClockTimeMillis+859368
15: 00007FF67F51261A v8::base::Thread::StartSynchronously+372186
16: 00007FF67F92971D v8::String::Utf8Length+141
17: 00007FF67EEDC03E node::Buffer::New+3454
18: 00007FF67F8D558E v8::SharedValueConveyor::SharedValueConveyor+416270
19: 00007FF67F8D518A v8::SharedValueConveyor::SharedValueConveyor+415242
20: 00007FF67F8D544F v8::SharedValueConveyor::SharedValueConveyor+415951
21: 00007FF67F8D52C0 v8::SharedValueConveyor::SharedValueConveyor+415552
22: 00007FF67F9D052E v8::PropertyDescriptor::writable+676878
23: 00007FF601862A5D

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Running target serve for project x-lng failed

   Failed tasks:

   - x-lng:serve:development

   Hint: run the command with --verbose for more details.

**Comment by baptisteclaussttd** [comment]
Hi, 
We have the same error `EPIPE` in our CI/CD with the command `nx affected` when 2 react projects need be build. 

NX version: 16.8.0

`nx affected --target=build --base=xxx --head=xxx --parallel=true --maxParallel=3 --progress --maxWorkers=4 --memoryLimit=4096 --ipartone=xxx --xxx`

To solve the issue we reduce `maxParallel` to `1`. It's not really a solution. 

Perhaps this can give a hint for the real solution.

**Comment by baptisteclaussttd** [comment]
Error came from typeChecking, you need to disable async in ForkTsChecker config object 
`new ForkTsCheckerWebpackPlugin({
            async : false 
        })`
