### ISSUE TITLE
Having issues installing Nx@11.5.1 globally

### ISSUE THREAD

**Issue by shashankvivek** [nrwl/nx#17666]
### Current Behavior

Currently, my project is on Angular 11 and I am trying to upgrade it to 16. But to begin with that, I will have to install 

`npm install --global nx@11.5.1`

I have node version `v12.13.0` installed. When I try to install Nx globally, there are 2 things that I am observing:

1.  The global installation for Nx is failing with the below error. I can install other npm packages globally (like @angular/cli)

```
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\svi\AppData\Roaming\npm-cache\_logs\2023-06-18T06_57_14_780Z-debug.log
```

Here is how the last few lines of log file looks like:

```
3931 warn optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-darwin-x64@15.9.3 (node_modules\nx\node_modules\nx\node_modules\@nrwl\nx-darwin-x64):
3932 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-darwin-x64@15.9.3: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
3933 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
3933 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  x64
3933 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
3933 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
3934 warn optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-linux-x64-gnu@15.9.3 (node_modules\nx\node_modules\nx\node_modules\@nrwl\nx-linux-x64-gnu):
3935 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-linux-x64-gnu@15.9.3: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
3936 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    linux
3936 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  x64
3936 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
3936 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
3937 warn nx@15.9.3 requires a peer of @swc-node/register@^1.4.2 but none is installed. You must install peer dependencies yourself.
3938 warn nx@15.9.3 requires a peer of @swc/core@^1.2.173 but none is installed. You must install peer dependencies yourself.
3939 warn nx@15.9.3 requires a peer of @swc-node/register@^1.4.2 but none is installed. You must install peer dependencies yourself.
3940 warn nx@15.9.3 requires a peer of @swc/core@^1.2.173 but none is installed. You must install peer dependencies yourself.
3941 verbose stack RangeError: Maximum call stack size exceeded
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3942 verbose cwd C:\Users\svi
3943 verbose Windows_NT 10.0.22621
3944 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "nx@11.5.1"
3945 verbose node v12.13.0
3946 verbose npm  v6.12.0
3947 error Maximum call stack size exceeded
3948 verbose exit [ 1, true ]
```

I tried  `npm cache clean --force` and `npm rebuild` , but nothing seems to work.

2. I think that even though I am trying to install nx version `11.5.1` , it is trying to install `15.9.3`

What is the solution to this problem? 

### Expected Behavior

The Nx@11.5.1 should get installed globally.

### Steps to Reproduce

`npm install --global nx@11.5.1`

### Nx Report

```shell
NA
```

### Failure Logs

```shell
3932 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-darwin-x64@15.9.3: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
3933 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
3933 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  x64
3933 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
3933 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
3934 warn optional SKIPPING OPTIONAL DEPENDENCY: @nrwl/nx-linux-x64-gnu@15.9.3 (node_modules\nx\node_modules\nx\node_modules\@nrwl\nx-linux-x64-gnu):
3935 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nrwl/nx-linux-x64-gnu@15.9.3: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
3936 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    linux
3936 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  x64
3936 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
3936 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
3937 warn nx@15.9.3 requires a peer of @swc-node/register@^1.4.2 but none is installed. You must install peer dependencies yourself.
3938 warn nx@15.9.3 requires a peer of @swc/core@^1.2.173 but none is installed. You must install peer dependencies yourself.
3939 warn nx@15.9.3 requires a peer of @swc-node/register@^1.4.2 but none is installed. You must install peer dependencies yourself.
3940 warn nx@15.9.3 requires a peer of @swc/core@^1.2.173 but none is installed. You must install peer dependencies yourself.
3941 verbose stack RangeError: Maximum call stack size exceeded
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3941 verbose stack     at failedDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:448:9)
3942 verbose cwd C:\Users\svi
3943 verbose Windows_NT 10.0.22621
3944 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "nx@11.5.1"
3945 verbose node v12.13.0
3946 verbose npm  v6.12.0
3947 error Maximum call stack size exceeded
3948 verbose exit [ 1, true ]
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

x64 . 

Node -> v12.13.0

**Comment by shashankvivek** [comment]
Alright, I tried `v14.15.0` of nodeJS and it has been installed. Although, I am still now sure if this ok. Because theoretically Nx `11.5.1` should work with the same node version that Angular 11 needed (i.e. 12.13.0).

**Comment by shashankvivek** [comment]
@AgentEnder  I am lost on how to upgrade our company project with how nx migrating is just not working. 

As you suggested, I removed nx globally, Then, tried

npx nx migrate 12.10.1

and I am presented with 

```
D:\q_repo\qontrol-ui>npx nx migrate 12.10.1
@nrwl/tao has been deprecated and will not be published in Nx 17. Please update your global install of nx: https://nx.dev/more-concepts/global-nx
√ Enable distributed caching to make your CI faster? · No
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@12.10.1
Fetching @nrwl/workspace@12.10.1

 >  NX   The migrate command failed.


 >  NX   Command failed: npm install @nrwl/workspace@12.10.1

   npm ERR! Unexpected end of JSON input while parsing near ''

   npm ERR! A complete log of this run can be found in:
   npm ERR!     C:\Users\svi\AppData\Roaming\npm-cache\_logs\2023-06-25T10_27_09_110Z-debug.log

   Pass --verbose to see the stacktrace.

D:\q_repo\qontrol-ui\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\svi\AppData\Local\Temp\tmp-24404-jFQOSw03SFKL\node_modules\.bin\tao migrate 12.10.1
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (D:\q_repo\qontrol-ui\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:101:25)
    at Object.runCommand (D:\q_repo\qontrol-ui\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (D:\q_repo\qontrol-ui\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (D:\q_repo\qontrol-ui\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (D:\q_repo\qontrol-ui\node_modules\@nrwl\cli\lib\init-local.js:23:13)
    at Object.<anonymous> (D:\q_repo\qontrol-ui\node_modules\@nrwl\cli\bin\nx.js:42:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13760,
  stdout: null,
  stderr: null
}

D:\q_repo\qontrol-ui>nx version
'nx' is not recognized as an internal or external command,
operable program or batch file.
```

What should be my approach ? 

Based on this error, I tried `npm install @nrwl/workspace@12.10.1` separately, and I am able to install it.

Here is `npx nx report`:

````
D:\q_repo\qontrol-ui>npx nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.15.0
  OS   : win32 x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : 11.5.1
  @nrwl/cli : 11.5.1
  @nrwl/cypress : 11.5.1
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.10.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
  ```
