### ISSUE TITLE
NX-Daemon does not restart correctly after file reload

### ISSUE THREAD

**Issue by thomas-p3** [nrwl/nx#17672]
### Current Behavior

When working in a nx-workspace, the nx-daemon seems not to be able to perform a reload of the changed files. After changing a file, it tries to load the changes and restart the server, but fails to do so. It also shows the error message "Address already in use". After that, the server seems to still run in the background, but with the "old" files.

### Expected Behavior

It should correctly load the changes and restart the servers.

### Steps to Reproduce

1. start server with nx serve ...
2. change files in repo, save files

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : linux x64
   npm    : 9.5.1
   Hasher : Native
   
   nx (global)        : 16.3.2
   nx                 : 16.3.1
   @nx/js             : 16.3.1
   @nx/jest           : 16.3.1
   @nx/linter         : 16.3.1
   @nx/workspace      : 16.3.1
   @nx/angular        : 16.3.1
   @nx/cypress        : 16.3.1
   @nx/devkit         : 16.3.1
   @nx/esbuild        : 16.3.1
   @nx/eslint-plugin  : 16.3.1
   @nx/nest           : 16.3.1
   @nx/node           : 16.3.1
   @nx/plugin         : 16.3.1
   @nrwl/tao          : 16.3.1
   @nx/webpack        : 16.3.1
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @datorama/akita       : 2.2.4
   @ngrx/component-store : 16.0.1
   @ngrx/effects         : 16.0.1
   @ngrx/entity          : 16.0.1
   @ngrx/router-store    : 16.0.1
   @ngrx/schematics      : 16.0.1
   @ngrx/store           : 16.0.1
   @ngrx/store-devtools  : 16.0.1
   @rx-angular/cdk       : 1.0.0
   @rx-angular/template  : 1.0.0
   ng-mocks              : 14.10.0
```

### Failure Logs

```shell
[NX Daemon Server] - 2023-06-19T11:17:14.205Z - Error detected when recomputing project file map: Cannot read properties of null (reading 'hash')

.../node_modules/nx/src/daemon/server/file-watching/file-watcher-sockets.js:37

const watchedProjects = new Set((0, find_matching_projects_1.findMatchingProjects)(config.watchProjects, project_graph_incremental_recomputation_1.currentProjectGraph.nodes));

TypeError: Cannot read properties of undefined (reading 'nodes')
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The error messages are similar to those in this issue: [12200](https://github.com/nrwl/nx/issues/12200)

EDIT: the issue may also be related to this one: [16718](https://github.com/nrwl/nx/issues/16718#issuecomment-1594368212)

**Comment by naseemshah** [comment]
I have the same issue. 

`ERROR [NestApplication] Error: listen EADDRINUSE: address already in use :::3333`

Happens every save of the file.

**Comment by limordryer** [comment]
I also have the same issue

**Comment by JuniorTour** [comment]
Same error, relate to nx@16?

```
Starting inspector on localhost:9229 failed: address already in use

Error: listen EADDRINUSE: address already in use :::3332
    at Server.setupListenHandle [as _listen2] (node:net:1463:16)
    at listenInCluster (node:net:1511:12)
    at Server.listen (node:net:1599:7)
    at Function.listen (project/node_modules/express/lib/application.js:635:24)
    at project/dist/apps/server-record/webpack:/src/main.ts:31:20
    at project/dist/apps/server-record/main.js:315:3
    at Object.<anonymous> (project/dist/apps/server-record/main.js:320:12)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
```

```
