### ISSUE TITLE
Error while migrating from Angular 11 to Angular 12 

### ISSUE THREAD

**Issue by tapt93** [nrwl/nx#17719]
### Current Behavior

I encountered an error during the migration process from Angular 11 to Angular 12, I have executed the following commands:

- nx migrate 13.1.4

 After that, I am getting the below error:

 ```
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@13.1.4
Fetching @nrwl/workspace@13.1.4

 >  NX   The migrate command failed.


 >  NX   Command failed: npm install @nrwl/workspace@13.1.4

   npm ERR! Unexpected end of JSON input while parsing near ''

   npm ERR! A complete log of this run can be found in:
    at Object.parseArgs [as _parseArgs] (D:\qoncept-clone\qontrol-ui\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (D:\qoncept-clone\qontrol-ui\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (D:\qoncept-clone\qontrol-ui\node_modules\@nrwl\cli\lib\init-local.js:23:13)
    at Object.<anonymous> (D:\qoncept-clone\qontrol-ui\node_modules\@nrwl\cli\bin\nx.js:42:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 26780,
  stdout: null,
  stderr: null
}

```

### Expected Behavior

The migration to Angular 12 should be completed successfully.

### Steps to Reproduce

1. nx migrate **13.1.4**

    node - **v14.15.0**

    npm - **v6.14.8**

### Nx Report

```shell
>  NX   Its time to update Nx 🎉                                  
                                                                   
   For more information, see https://nx.dev/more-concepts/global-nx


>  NX  Report complete - copy this into the issue template
                                                          
  Node : 14.15.0                                          
  OS   : win32 x64                                        
  npm  : 6.14.8                                           
                                                          
  nx : Not Found                                          
  @nrwl/angular : 11.5.1
  @nrwl/cli : 11.5.1
  @nrwl/cypress : 11.5.1
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.5.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by shashankvivek** [comment]
@leosvelperez  Can you please check this ? As suggested by you in https://github.com/nrwl/nx/issues/17667 ,  we tried to migrate to 12.3.0 and also 13.1.4. We are facing the same issue !

**Comment by tapt93** [comment]
My package.json after running
```
"dependencies": {
    "@angular-eslint/eslint-plugin": "^2.1.1",
    "@angular-eslint/eslint-plugin-template": "^2.1.1",
    "@angular-eslint/template-parser": "^2.1.1",
    "@angular/animations": "^11.2.14",
    "@angular/cdk": "^11.2.13",
    "@angular/common": "^11.2.14",
    "@angular/compiler": "^11.2.14",
    "@angular/core": "^11.2.14",
    "@angular/forms": "^11.2.14",
    "@angular/material": "^11.2.13",
    "@angular/platform-browser": "^11.2.14",
    "@angular/platform-browser-dynamic": "^11.2.14",
    "@angular/router": "^11.2.14",
    "@microsoft/signalr": "^3.1.16",
    "@ngrx/component-store": "11.0.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^5.0.0",
    "@nrwl/eslint-plugin-nx": "^11.6.3",
    "@nrwl/linter": "^11.6.3",
    "@qoncept/jsonapi-serializer": "0.0.1",
    "@syncfusion/ej2-angular-buttons": "^19.2.46",
    "@syncfusion/ej2-angular-calendars": "^19.2.46",
    "@syncfusion/ej2-angular-charts": "^19.2.46",
    "@syncfusion/ej2-angular-dropdowns": "^19.2.46",
    "@syncfusion/ej2-angular-grids": "^19.2.46",
    "@syncfusion/ej2-angular-inputs": "^19.2.46",
    "@syncfusion/ej2-angular-navigations": "^19.2.46",
    "@syncfusion/ej2-angular-notifications": "^19.2.44",
    "@syncfusion/ej2-angular-popups": "^19.2.46",
    "@syncfusion/ej2-angular-richtexteditor": "^19.2.46",
    "@syncfusion/ej2-angular-schedule": "^19.2.46",
    "@syncfusion/ej2-angular-splitbuttons": "^19.2.44",
    "@syncfusion/ej2-charts": "^19.2.46",
    "@syncfusion/ej2-layouts": "^19.2.44",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "angular-oauth2-oidc": "^10.0.3",
    "cldr-data": "^36.0.0",
    "core-js": "^2.5.4",
    "date-fns": "^2.22.1",
    "guid-typescript": "^1.0.9",
    "lodash-es": "^4.17.21",
    "ng-click-outside": "^7.0.1",
    "qs": "^6.10.1",
    "rxjs": "^6.6.7",
    "shed-css": "^1.4.0",
    "tslib": "^2.2.0",
    "uuid": "^8.3.2",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1102.4",
    "@angular/cli": "^11.2.14",
    "@angular/compiler-cli": "^11.2.14",
    "@angular/language-service": "^11.2.14",
    "@nrwl/angular": "11.5.1",
    "@nrwl/cli": "11.5.1",
    "@nrwl/cypress": "11.5.1",
    "@nrwl/devkit": "11.5.1",
    "@nrwl/jest": "11.5.1",
    "@nrwl/tao": "11.5.1",
    "@nrwl/workspace": "11.5.1",
    "@types/jasmine": "3.6.6",
    "@types/jasminewd2": "^2.0.10",
    "@types/jest": "26.0.8",
    "@types/lodash-es": "^4.17.6",
    "@types/node": "^12.20.16",
    "@types/qs": "^6.9.7",
    "codelyzer": "6.0.1",
    "cypress": "^4.1.0",
    "dotenv": "6.2.0",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-cypress": "^2.11.3",
    "eslint-plugin-prettier": "^3.4.0",
    "husky": "^4.2.5",
    "jasmine-core": "3.6.0",
    "jasmine-spec-reporter": "5.0.2",
    "jest": "26.2.2",
    "jest-preset-angular": "8.3.2",
    "karma": "5.0.9",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage": "2.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "ng-packagr": "^11.0.0",
    "nx-cloud": "^16.0.5",
    "postcss-import": "^12.0.1",
    "postcss-loader": "^3.0.0",
    "postcss-scss": "^2.0.0",
    "prettier": "2.2.1",
    "prettier-eslint": "^9.0.1",
    "protractor": "7.0.0",
    "ts-jest": "26.4.0",
    "ts-node": "9.1.1",
    "tslint": "6.1.3",
    "tslint-no-focused-test": "^0.5.0",
    "typescript": "4.1.5"
  },
```

**Comment by leosvelperez** [comment]
I wasn't able to reproduce the issue with the information provided. For a sanity check, these are the steps (based on the info provided) I performed to try to reproduce it:

- Set up Node and npm to the same versions shown in the `nx report`
- Created workspace running `npx create-nx-workspace@11.5.1` and choosing Angular
- Overwrote the `package.json` deps with the ones pasted in the comment above
- Tried the following migrations:
	- `npx nx migrate 12.3.0` (min version supporting Angular 12)
	- `npx nx migrate 12.10.1` (latest Nx v12 version)
	- `npx nx migrate 13.1.4` (latest Nx version supporting Angular 12)

In all cases, the `migrate` command ran successfully.

That error message performing an `npm install` is normally due to a corrupt npm cache or an unstable internet connection. You can try doing:

- `npm cache clean --force`
- `npm install`
- `npx nx migrate 12.10.1`

Make sure your internet connection is stable.

If the problem still persists, we're going to need a reproduction so we can further troubleshoot the issue.

**Comment by shashankvivek** [comment]
Ok, let us get back to you in next few days
