### ISSUE TITLE
Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by jdnichollsc** [nrwl/nx#17762]
### Current Behavior

Getting the below error `Error: Cannot find module 'typescript'` while creating a new remix project

### Expected Behavior

Be able to create a new project flawlessly <3

### Steps to Reproduce

- Running the below command to create a new project:
```sh
npx create-nx-workspace@latest acme \
--preset=@nx/remix \
--project=demo
```

- Then I'm getting this error:
```sh
>  NX   Cannot find module 'typescript'

   Require stack:
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@phenomnomnominal/tsquery/dist/src/ast.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@phenomnomnominal/tsquery/dist/src/index.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@nx/remix/src/utils/testing-config-utils.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@nx/remix/src/generators/application/lib/update-unit-test-config.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@nx/remix/src/generators/application/lib/index.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@nx/remix/src/generators/application/application.impl.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@nx/remix/src/generators/preset/preset.impl.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/src/config/workspaces.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/src/config/configuration.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/src/utils/package-manager.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/bin/init-local.js
   - /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/bin/nx.js

Error: Cannot find module 'typescript'
Require stack:
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@phenomnomnominal/tsquery/dist/src/ast.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@phenomnomnominal/tsquery/dist/src/index.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@nx/remix/src/utils/testing-config-utils.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@nx/remix/src/generators/application/lib/update-unit-test-config.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@nx/remix/src/generators/application/lib/index.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@nx/remix/src/generators/application/application.impl.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@nx/remix/src/generators/preset/preset.impl.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/src/config/workspaces.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/src/config/configuration.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/src/utils/package-manager.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/bin/init-local.js
- /Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/bin/nx.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at Mod.require (/Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/nx/bin/init-local.js:204:36)
    at require (/Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/@phenomnomnominal/tsquery/dist/src/ast.js:5:20)
    at Module._compile (/Users/jdnichollsc/dev/remix/nx-remo/webapp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)

 >  NX   Failed to apply preset: @nx/remix

   See above

```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin arm64
   npm    : 9.5.1
   Hasher : Native
   
   nx             : 16.3.2
   @nx/js         : 16.3.2
   @nx/linter     : 16.3.2
   @nx/workspace  : 16.3.2
   @nx/devkit     : 16.3.2
   @nx/react      : 16.3.2
   @nrwl/tao      : 16.3.2
   @nx/web        : 16.3.2
   nx-cloud       : 16.0.5
   ---------------------------------------
   Community plugins:
   @nx/remix : 16.3.1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Is typescript installed?

**Comment by jdnichollsc** [comment]
@AgentEnder sorry Sir, what do you mean? Do I need to install TypeScript globally? 🤔

**Comment by jdnichollsc** [comment]
I already tried installing typescript globally using `npm i typescript -g` and `brew install typescript` from Mac but I'm still getting this error. Also, I tried from another Mac and I'm getting the same error

**Comment by jaysoo** [comment]
We released  a fix for this, so you should be able to create the workspace now.

**Comment by jdnichollsc** [comment]
@jaysoo I confirm, thanks folks for your support! <3

**Comment by jdnichollsc** [comment]
BTW, I don't see the apps folder at the root of the project... is that Ok? 🤔

**Comment by jdnichollsc** [comment]
@jaysoo I tried adding a new lib but I'm getting a different structure folder compared with an older project:

<img width="348" alt="image" src="https://github.com/nrwl/nx/assets/2154886/804585f7-d877-44ca-bebe-f5f094441ac6">

Older project: 
<img width="391" alt="image" src="https://github.com/nrwl/nx/assets/2154886/f89ede38-d7db-411c-ab80-3946701674b5">

Is that expected? 🤔 

Thanks for your support folks!
