### ISSUE TITLE
Invalid Cypress config file when using Vite with `"type": "module"`

### ISSUE THREAD

**Issue by joshdales** [nrwl/nx#17794]
### Current Behavior

When a project has set `"type": "module"` in the `package.json` cypress fails to find its own config. I'm using vite as the bundler, might also happen with webpack but I haven't checked.

Running the e2e command you get the following error:
```
Your configFile is invalid: /path/to/project-e2e/cypress.config.ts

It threw an error when required, check the stack trace below:

Error: Cannot find module 'file:///path/to/project-e2e/cypress.config.ts'
```

The application it's self runs fine, the cypress config is in a valid format, it's just Cypress that fails to start. I've tried this in another project without Nx that uses Vite and Cypress and it works fine 😢 

### Expected Behavior

Cypress starts and runs the tests.

### GitHub Repo

https://github.com/joshdales/nx-invalid-cypress-config

### Steps to Reproduce

After you have pulled the code and installed the dependancies you just need to run the e2e command `npm run e2e` (which is just `nx run test-e2e:e2e`)

### Nx Report

```shell
Node   : 20.3.1
OS     : darwin-arm64
npm    : 9.6.7

nx                 : 16.4.0
@nx/js             : 16.4.0
@nx/linter         : 16.4.0
@nx/workspace      : 16.4.0
@nx/cypress        : 16.4.0
@nx/devkit         : 16.4.0
@nx/eslint-plugin  : 16.4.0
@nx/react          : 16.4.0
@nrwl/tao          : 16.4.0
@nx/vite           : 16.4.0
@nx/web            : 16.4.0
typescript         : 5.1.3
```

### Failure Logs

```shell
> nx run test-e2e:e2e

  ➜  Local:   http://localhost:4200/
DevTools listening on ws://127.0.0.1:55590/devtools/browser/d3b4d4c3-6cbb-4b50-b9cc-3273a2119a25
Your configFile is invalid: /Users/joshdales/dev/nx-invalid-cypress-config/test-e2e/cypress.config.ts

It threw an error when required, check the stack trace below:

Error: Cannot find module 'file:///Users/joshdales/dev/nx-invalid-cypress-config/test-e2e/cypress.config.ts'
Require stack:
- /Users/joshdales/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js
- /Users/joshdales/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1072:15)
    at Function.Module._resolveFilename (/Users/joshdales/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/joshdales/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at /Users/joshdales/Library/Caches/Cypress/12.15.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:106:34
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by barbados-clemens** [comment]
@joshdales do you have a cloneable repo I can take a look at for the non nx version you mentioned? curious why cypress is trying to `require` the package which is an issue since type:module declaring everything is esm so require() would probably be an issue.

**Comment by joshdales** [comment]
@barbados-clemens Yep sure, I just made one here: https://github.com/joshdales/cypress-with-module

**Comment by joshdales** [comment]
Just updated the example repo and it seems like it's still an issue 😞

**Comment by leosvelperez** [comment]
Forgot to mention that you also need to adjust your `cypress.config.ts` for ESM. The configuration uses `__dirname`, which is not defined in ESM. The updated working config for the project you shared would be:

```ts
import { defineConfig } from 'cypress';
import { nxE2EPreset } from '@nx/cypress/plugins/cypress-preset';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  e2e: nxE2EPreset(__dirname, {
    bundler: 'vite',
  }),
});
```
