### ISSUE TITLE
Serve command does not take into account build configuration outputPath.

### ISSUE THREAD

**Issue by alextrep96** [nrwl/nx#17800]
### Current Behavior

For debugging purposes and to reduce the risks of deploying a build with the wrong configuration, we have separate `outputPath` values for our NestJs build configurations:
```json
"build": {
  "executor": "@nx/webpack:webpack",
  "outputs": ["{options.outputPath}"],
  "defaultConfiguration": "production",
  "options": {
    "target": "node",
    "compiler": "tsc",
    "outputPath": "dist/packages/api",
    "main": "packages/api/src/main.ts",
    "tsConfig": "packages/api/tsconfig.app.json",
    "assets": ["packages/api/src/assets"],
    "isolatedConfig": true,
    "webpackConfig": "packages/api/webpack.config.js"
  },
  "configurations": {
    "development": {
      "outputPath": "dist/packages/api-dev"
    },
    "production": {
      "outputPath": "dist/packages/api-prod"
    }
  }
},
"serve": {
  "executor": "@nx/js:node",
  "defaultConfiguration": "development",
  "options": {
    "buildTarget": "api:build"
  },
  "configurations": {
    "development": {
      "buildTarget": "api:build:development"
    },
    "production": {
      "buildTarget": "api:build:production"
    }
  }
},
```

The issue is that running the serve command doesn't consider the outputPath for each configuration. Inspecting the `/dist` folder after running the serve command, we see that the build step did output to `/dist/packages/api-dev` as expected from the build configuration, but the serve command seems to be searching for the default `dist/packages/api`.

### Expected Behavior

The serve command should consider the build step ouputPath values and serve without any error.

### GitHub Repo

https://github.com/alextrep96/nx-outputPath-issue

### Steps to Reproduce

1. Clone the repo
2. Run `pnpm i`
3. Make sure the `/dist` folder is empty.
4. Run the command `npx nx serve api`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   pnpm   : 8.6.0
   
   nx (global)        : 16.4.0
   nx                 : 16.4.0
   @nx/js             : 16.4.0
   @nx/jest           : 16.4.0
   @nx/linter         : 16.4.0
   @nx/workspace      : 16.4.0
   @nx/eslint-plugin  : 16.4.0
   @nx/nest           : 16.4.0
   @nx/node           : 16.4.0
   @nrwl/tao          : 16.4.0
   @nx/webpack        : 16.4.0
   typescript         : 5.0.2
```

### Failure Logs

```shell
> nx run api:serve:development

/Users/alexistrepanier/dev/nx-outputPath-issue/node_modules/.pnpm/@nx+js@16.4.0_nx@16.4.0_typescript@5.0.2/node_modules/@nx/js/src/executors/node/node.impl.js:235
                throw new Error(`Could not find ${fileToRun}. Make sure your build succeeded.`);
                      ^

Error: Could not find /Users/alexistrepanier/dev/nx-outputPath-issue/dist/packages/api/main.js. Make sure your build succeeded.
    at fileToRunCorrectPath (/Users/alexistrepanier/dev/nx-outputPath-issue/node_modules/.pnpm/@nx+js@16.4.0_nx@16.4.0_typescript@5.0.2/node_modules/@nx/js/src/executors/node/node.impl.js:235:23)
    at /Users/alexistrepanier/dev/nx-outputPath-issue/node_modules/.pnpm/@nx+js@16.4.0_nx@16.4.0_typescript@5.0.2/node_modules/@nx/js/src/executors/node/node.impl.js:108:102
    at new Promise (<anonymous>)
    at /Users/alexistrepanier/dev/nx-outputPath-issue/node_modules/.pnpm/@nx+js@16.4.0_nx@16.4.0_typescript@5.0.2/node_modules/@nx/js/src/executors/node/node.impl.js:103:40
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alexistrepanier/dev/nx-outputPath-issue/node_modules/.pnpm/tslib@2.3.0/node_modules/tslib/tslib.js:114:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This has been working perfectly fine for us for a while but since version 16.2, this is an issue preventing us from working efficiently.

**Comment by vicb** [comment]
I have the same issue after upgrading to 16.4.0 (from 16.3.2).

My config is:

```
    "serve": {
      "executor": "@nx/js:node",
      "options": {
        "buildTarget": "fetcher:build"
      },
      "configurations": {
        "production": {
          "buildTarget": "fetcher:build:production"
        }
      }
    },
 ```

**Comment by cwoebker** [comment]
I am encountering the same issue on 16.4.1 (upgrading from 16.3.2).

**Comment by mandarini** [comment]
Duplicate: https://github.com/nrwl/nx/issues/17946
