### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read when upgrading workspace with mix of projects

### ISSUE THREAD

**Issue by phillipCouto** [nrwl/nx#17828]
### Current Behavior

When upgrading from 16.0.3 to 16.1.4 we are experiencing an error:

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:749:3)
    at tryReadSync (node:fs:449:20)
    at readFileSync (node:fs:495:19)
    at FsTree.fsReadFile (/Users/pcouto/workspace/eckler-fs/life-2/ingenius/ingenius/node_modules/.pnpm/nx@16.1.3/node_modules/nx/src/generators/tree.js:247:44)
    at FsTree.read (/Users/pcouto/workspace/eckler-fs/life-2/ingenius/ingenius/node_modules/.pnpm/nx@16.1.3/node_modules/nx/src/generators/tree.js:31:32)
    at getBootstrapCallFileInfo (/Users/pcouto/workspace/eckler-fs/life-2/ingenius/ingenius/node_modules/.pnpm/@nx+angular@16.1.3_@angular-devkit+build-angular@16.0.6_@angular-devkit+core@16.0.6_@angular-_cbel7jtnj4xi4zw3c6lfpwkfum/node_modules/@nx/angular/src/migrations/update-16-1-0/extract-standalone-config-from-bootstrap.js:12:42)
    at /Users/pcouto/workspace/eckler-fs/life-2/ingenius/ingenius/node_modules/.pnpm/@nx+angular@16.1.3_@angular-devkit+build-angular@16.0.6_@angular-devkit+core@16.0.6_@angular-_cbel7jtnj4xi4zw3c6lfpwkfum/node_modules/@nx/angular/src/migrations/update-16-1-0/extract-standalone-config-from-bootstrap.js:84:74
    at Generator.next (<anonymous>)
    at /Users/pcouto/workspace/eckler-fs/life-2/ingenius/ingenius/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
```

This is generated when executing the migration `extract-app-config-for-standalone`.

### Expected Behavior

We expect the migration to complete successfully.

### GitHub Repo

https://github.com/phillipCouto/nx-upgrade-16.0_16.1

### Steps to Reproduce

1. Create repo with Angular application based on Nx 16.0.x
2. Add nx-go application with `--useGoWork` flag set
3. Update main in go application config to point to the folder instead of the path to the file
4. Migrate to Nx 16.1
5. Observe the migration errors

See repo for instructions and preconfigured repo.

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin arm64
   pnpm   : 8.6.5
   Hasher : Native
   
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/angular        : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/web            : 16.1.4
   @nx/webpack        : 16.1.4
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx-go/nx-go : 2.7.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by phillipCouto** [comment]
Thank you @leosvelperez 😄
