### ISSUE TITLE
Daemon process terminated 

### ISSUE THREAD

**Issue by GIT-MDW** [nrwl/nx#17830]
### Current Behavior

after running project with nx start it throws 
![image](https://github.com/nrwl/nx/assets/94377644/f68f9fac-15c3-485b-bbf8-643fa8ad00b0)

### Expected Behavior

Should run project without throwing errors

### Steps to Reproduce

start project

### Nx Report

```shell
>  NX   Daemon process terminated and closed the connection

   Please rerun the command, which will restart the daemon.
```

nx plugin in vs code also doesn't work

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by GIT-MDW** [comment]
Here is the Daemon log 

[NX Daemon Server] - 2023-06-28T06:23:41.842Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-28T06:23:41.851Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:23:41.851Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-28T06:23:41.853Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-28T06:23:41.889Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-28T06:23:41.889Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:23:41.889Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:23:42.171Z - Time taken for 'hash changed files from watcher' 4.03758000023663ms
[NX Daemon Server] - 2023-06-28T06:23:42.172Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:23:42.172Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-28T06:24:13.244Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-28T06:24:13.250Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:24:13.251Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-28T06:24:13.258Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-28T06:24:13.411Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-28T06:24:13.411Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:24:13.411Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:24:13.602Z - Time taken for 'hash changed files from watcher' 114.08435699995607ms
[NX Daemon Server] - 2023-06-28T06:24:13.603Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:24:13.603Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:969
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-28T06:26:38.963Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-28T06:26:38.970Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:26:38.971Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-28T06:26:38.973Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-28T06:26:39.008Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-28T06:26:39.009Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:26:39.009Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:26:39.200Z - Time taken for 'hash changed files from watcher' 3.0819840002804995ms
[NX Daemon Server] - 2023-06-28T06:26:39.200Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:26:39.201Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-28T06:32:19.112Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-28T06:32:19.117Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:32:19.118Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-28T06:32:19.120Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-28T06:32:19.153Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-28T06:32:19.153Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:32:19.153Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:32:19.300Z - Time taken for 'hash changed files from watcher' 3.108153998851776ms
[NX Daemon Server] - 2023-06-28T06:32:19.301Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:32:19.301Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-28T06:33:25.761Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-28T06:33:25.772Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:33:25.773Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-28T06:33:25.775Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-28T06:33:25.811Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-28T06:33:25.811Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:33:25.811Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:33:25.956Z - Time taken for 'hash changed files from watcher' 3.559418000280857ms
[NX Daemon Server] - 2023-06-28T06:33:25.957Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:33:25.957Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-28T06:33:54.462Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-28T06:33:54.472Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:33:54.472Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-28T06:33:54.474Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-28T06:33:54.510Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-28T06:33:54.510Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:33:54.510Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:33:54.653Z - Time taken for 'hash changed files from watcher' 3.7445340007543564ms
[NX Daemon Server] - 2023-06-28T06:33:54.653Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:33:54.654Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-28T06:34:03.781Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-28T06:34:03.786Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:34:03.787Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-28T06:34:03.789Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-28T06:34:03.825Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-28T06:34:03.825Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:34:03.825Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:34:03.975Z - Time taken for 'hash changed files from watcher' 3.079508999362588ms
[NX Daemon Server] - 2023-06-28T06:34:03.975Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:34:03.975Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-28T06:34:37.344Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-28T06:34:37.351Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:34:37.352Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-28T06:34:37.354Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-28T06:34:37.389Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-28T06:34:37.389Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:34:37.389Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:34:37.537Z - Time taken for 'hash changed files from watcher' 2.905164999887347ms
[NX Daemon Server] - 2023-06-28T06:34:37.537Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:34:37.537Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-28T06:40:57.975Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-28T06:40:57.980Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:40:57.981Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-28T06:40:57.983Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-28T06:40:58.109Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-28T06:40:58.109Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:40:58.109Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:40:58.330Z - Time taken for 'hash changed files from watcher' 93.6024379990995ms
[NX Daemon Server] - 2023-06-28T06:40:58.331Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:40:58.332Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:969
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-28T06:41:37.240Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-28T06:41:37.245Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:41:37.246Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-28T06:41:37.248Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-28T06:41:37.328Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-28T06:41:37.329Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:41:37.329Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-28T06:41:37.492Z - Time taken for 'hash changed files from watcher' 47.031935999169946ms
[NX Daemon Server] - 2023-06-28T06:41:37.493Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-28T06:41:37.494Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:969
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-29T06:22:02.128Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-29T06:22:02.135Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-29T06:22:02.136Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-29T06:22:02.138Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-29T06:22:02.192Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-29T06:22:02.192Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-29T06:22:02.193Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-29T06:22:02.360Z - Time taken for 'hash changed files from watcher' 2.7775970000075176ms
[NX Daemon Server] - 2023-06-29T06:22:02.361Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-29T06:22:02.361Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-29T06:33:23.045Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-29T06:33:23.050Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-29T06:33:23.051Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-29T06:33:23.053Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-29T06:33:23.105Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-29T06:33:23.105Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-29T06:33:23.105Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-29T06:33:23.345Z - Time taken for 'hash changed files from watcher' 4.161304000066593ms
[NX Daemon Server] - 2023-06-29T06:33:23.347Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-29T06:33:23.347Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:969
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[NX Daemon Server] - 2023-06-29T06:37:39.946Z - Started listening on: /tmp/dc8a12a83f3a86624e1a/d.sock
[NX Daemon Server] - 2023-06-29T06:37:39.954Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-29T06:37:39.955Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-06-29T06:37:39.957Z - [REQUEST]: Client Request for Project Graph Received
fatal: no path specified
[NX Daemon Server] - 2023-06-29T06:37:40.006Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-06-29T06:37:40.006Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-29T06:37:40.006Z - [REQUEST]: 
[NX Daemon Server] - 2023-06-29T06:37:40.190Z - Time taken for 'hash changed files from watcher' 4.046740000136197ms
[NX Daemon Server] - 2023-06-29T06:37:40.191Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-06-29T06:37:40.191Z - [WATCHER]: Subscribed to changes within: /home/usr/www/react-acton-ui-2
node:internal/event_target:1011
  process.nextTick(() => { throw err; });
                           ^

Error: Source project does not exist: mock-service
    at ProjectGraphBuilder.addDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:175:19)
    at ProjectGraphBuilder.addStaticDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at ProjectGraphBuilder.addExplicitDependency (/home/usr/www/react-acton-ui-2/node_modules/nx/src/project-graph/project-graph-builder.js:131:14)
    at /home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:81:29
    at Array.forEach (<anonymous>)
    at Worker.<anonymous> (/home/usr/www/react-acton-ui-2/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:80:38)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)

**Comment by AgentEnder** [comment]
Do you have a project called "mock-service", or are there references to it still hanging around elsewhere?

**Comment by AgentEnder** [comment]
Do you have a project called "mock-service", or are there references to it still hanging around elsewhere?

**Comment by GIT-MDW** [comment]
Project has  mockService and package,json with this content, but how can it be the reason for crush? its weird 
{
  "name": "mock-service",
  "dependencies": {
    "apollo-server": "^2.15.1",
    "apollo-server-express": "^1.4.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "graphql": "^16.6.0"
  }
}

**Comment by AgentEnder** [comment]
Is that package.json referenced in your npm workspaces setup, or is there a sibling project.json?

**Comment by GIT-MDW** [comment]
Since the project is monorepo, npm i installs all dependencies across the board. This type of issues prevents us from running the project, and I'm not sure if they have anything to do with the nx plugin.

**Comment by GIT-MDW** [comment]
I noticed that after updating React to 18 and changing some packages, this issue occurred.

**Comment by GIT-MDW** [comment]
There is no answer
