### ISSUE TITLE
nx 16.5.0-beta0 with-nx.js , RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rodrigc** [nrwl/nx#17842]
### Current Behavior

I was testing out `nx 16.5.0-beta0` and ran into this problem:

```
> Build error occurred
RangeError: Maximum call stack size exceeded
    at Module._resolveFilename (node:internal/modules/cjs/loader:988:35)
    at mod._resolveFilename (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at getNxContext (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/@nx/next/plugins/with-nx.js:25:35)
    at getNxContext (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/@nx/next/plugins/with-nx.js:38:16)
    at getNxContext (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/@nx/next/plugins/with-nx.js:38:16)
    at getNxContext (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/@nx/next/plugins/with-nx.js:38:16)
    at getNxContext (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/@nx/next/plugins/with-nx.js:38:16)
Error occurred while trying to run the npx next build
Error: Command failed: npx next build
    at checkExecSyncError (node:child_process:885:11)
    ```

### Expected Behavior

This error should not happen

### Steps to Reproduce

`npx nx run mytarget:build`

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 20.3.1
   OS     : darwin-x64
   yarn   : 1.22.19

   nx                 : 16.5.0-beta.0
   @nx/js             : 16.5.0-beta.0
   @nx/jest           : 16.5.0-beta.0
   @nx/linter         : 16.5.0-beta.0
   @nx/workspace      : 16.5.0-beta.0
   @nx/cypress        : 16.5.0-beta.0
   @nx/devkit         : 16.5.0-beta.0
   @nx/eslint-plugin  : 16.5.0-beta.0
   @nx/express        : 16.5.0-beta.0
   @nx/next           : 16.5.0-beta.0
   @nx/node           : 16.5.0-beta.0
   @nx/react          : 16.5.0-beta.0
   @nx/rollup         : 16.5.0-beta.0
   @nx/storybook      : 16.5.0-beta.0
   @nrwl/tao          : 16.5.0-beta.0
   @nx/web            : 16.4.0
   @nx/webpack        : 16.5.0-beta.0
   typescript         : 4.7.4
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-docker : 3.0.8
   ---------------------------------------
```

### Failure Logs

```shell
> Build error occurred
RangeError: Maximum call stack size exceeded
    at Module._resolveFilename (node:internal/modules/cjs/loader:988:35)
    at mod._resolveFilename (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at getNxContext (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/@nx/next/plugins/with-nx.js:25:35)
    at getNxContext (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/@nx/next/plugins/with-nx.js:38:16)
    at getNxContext (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/@nx/next/plugins/with-nx.js:38:16)
    at getNxContext (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/@nx/next/plugins/with-nx.js:38:16)
    at getNxContext (/Users/crodrigues/go/src/github.com/quiknode-labs/ts-mono/node_modules/@nx/next/plugins/with-nx.js:38:16)
Error occurred while trying to run the npx next build
Error: Command failed: npx next build
    at checkExecSyncError (node:child_process:885:11)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by rodrigc** [comment]
@jaysoo I ran into this problem while trying to test out https://github.com/nrwl/nx/pull/17819
in my monorepo.

**Comment by AgentEnder** [comment]
Can you check with the latest stable release on this?

**Comment by rodrigc** [comment]
In my tree running NX 15.8.6, I ran:

```
npx nx migrate latest
yarn
npx nx migrate --run-migrations
```

and it ran successfully, without failing.  So I think this can be closed.
