### ISSUE TITLE
Empty outputPath deletes entire working directory

### ISSUE THREAD

**Issue by aadito123** [nrwl/nx#17872]
### Current Behavior

In a project.json, if the `outputPath` under `targets.<target>.options` is empty. i.e. `""`, it errors and deletes the entire repository. I literally lost 4 days worth of commits cause of this (going to cry).

### Expected Behavior

Ideally, it would throw an error or more selectively delete items.

### GitHub Repo

https://github.com/aadito123/nx-delete-all-example

### Steps to Reproduce

1. Clone repo
2. `npm i`
3. `npx nx build test`

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : linux-x64
   npm    : 9.7.1
   
   nx                 : 16.4.0
   @nx/js             : 16.4.0
   @nx/jest           : 16.4.0
   @nx/linter         : 16.4.0
   @nx/workspace      : 16.4.0
   @nx/devkit         : 16.4.0
   @nx/esbuild        : 16.4.0
   @nx/eslint-plugin  : 16.4.0
   @nx/node           : 16.4.0
   @nrwl/tao          : 16.4.0
   @nx/vite           : 16.4.0
   typescript         : 5.1.3
   ---------------------------------------
   Local workspace plugins:
         @bleepbloop/solid-utils
         @bleepbloop/types
```

### Failure Logs

```shell
> nx run utils:build

Compiling TypeScript files for project "utils"...
error TS6053: File '/home/aadit/Documents/bleepbloop/libs/utils/src/index.ts' not found.
  The file is in the program because:
    Root file specified for compilation
error TS6053: File '/home/aadit/Documents/bleepbloop/libs/utils/src/schemas.ts' not found.
  The file is in the program because:
    Root file specified for compilation
error TS6053: File '/home/aadit/Documents/bleepbloop/libs/utils/src/solid.tsx' not found.
  The file is in the program because:
    Root file specified for compilation
error TS6053: File '/home/aadit/Documents/bleepbloop/node_modules/typescript/lib/lib.dom.d.ts' not found.
  The file is in the program because:
    Library 'lib.dom.d.ts' specified in compilerOptions
error TS6053: File '/home/aadit/Documents/bleepbloop/node_modules/typescript/lib/lib.es2017.d.ts' not found.
  The file is in the program because:
    Library 'lib.es2017.d.ts' specified in compilerOptions
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'CallableFunction'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'NewableFunction'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.

/home/aadit/Documents/bleepbloop/node_modules/nx/src/hasher/task-hasher.js:607
        throw new Error(`Input '${input}' is not defined`);
              ^

Error: Input 'production' is not defined
    at expandNamedInput (/home/aadit/Documents/bleepbloop/node_modules/nx/src/hasher/task-hasher.js:607:15)
    at /home/aadit/Documents/bleepbloop/node_modules/nx/src/hasher/task-hasher.js:502:87
    at Array.map (<anonymous>)
    at getTargetInputs (/home/aadit/Documents/bleepbloop/node_modules/nx/src/hasher/task-hasher.js:502:76)
    at findProjectsNpmDependencies (/home/aadit/Documents/bleepbloop/node_modules/nx/src/plugins/js/package-json/create-package-json.js:115:45)
    at createPackageJson (/home/aadit/Documents/bleepbloop/node_modules/nx/src/plugins/js/package-json/create-package-json.js:22:21)
    at updatePackageJson (/home/aadit/Documents/bleepbloop/node_modules/@nx/js/src/utils/package-json/update-package-json.js:27:67)
    at /home/aadit/Documents/bleepbloop/node_modules/@nx/js/src/executors/tsc/tsc.impl.js:51:57
    at Generator.next (<anonymous>)
    at fulfilled (/home/aadit/Documents/bleepbloop/node_modules/tslib/tslib.js:164:62)

Node.js v18.16.0
Unable to print terminal output for Task "utils:build".
Task failed with Exit Code 1 and Signal "null".

Received error message:
ENOENT: no such file or directory, open '/home/aadit/Documents/bleepbloop/node_modules/.cache/nx/terminalOutputs/4585833929355084103'

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project utils (1m)
 
    ✖    0/0 failed
    ✔    0/0 succeeded [0 read from cache]
 

 >  NX   Failed to start or connect to the Nx Daemon process.

   
   Messages from the log:
   node:internal/modules/cjs/loader:1078
     throw err;
     ^
   
   Error: Cannot find module '/home/aadit/Documents/bleepbloop/node_modules/nx/src/daemon/server/start.js'
       at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
       at Module._load (node:internal/modules/cjs/loader:920:27)
       at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
       at node:internal/main/run_main_module:23:47 {
     code: 'MODULE_NOT_FOUND',
     requireStack: []
   }
   
   Node.js v18.16.0
   
   
   
   More information: /home/aadit/Documents/bleepbloop/node_modules/.cache/nx/d/daemon.log
   Pass --verbose to see the stacktrace.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The nx report was run on a version of the repo that is a little old.

**Comment by FrozenPandaz** [comment]
So sorry you lost all your commits. I hope your brain kept most of the knowledge.

This is actually part of the `@nx/js:tsc` executor. @jaysoo can we change it to error if `options.clean && options.outputDir === ''`?
