### ISSUE TITLE
`npx nx connect-to-nx-cloud ` failed

### ISSUE THREAD

**Issue by zqinmiao** [nrwl/nx#17908]
### Current Behavior

Execute `npx nx connect-to-nx-cloud`, Report the following error，`pnpm add -Dw @nrwl/nx-cloud@latest` is the same:

```bash
✔ Enable distributed caching to make your CI faster · Yes
nx.js connect

Connect workspace to Nx Cloud

Options:
  --help     Show help                                                                                                                                                                      [boolean]
  --version  Show version number                                                                                                                                                            [boolean]

Find more information and examples at https://nx.dev/nx/connect-to-nx-cloud

Error: Command failed: pnpm add -Dw @nrwl/nx-cloud@latest
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Object.<anonymous> (/Users/xxx/node_modules/.pnpm/nx@15.8.6/node_modules/nx/src/command-line/connect.js:55:42)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxx/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer e2 80 89 45 52 52 5f 50 4e 50 4d 5f 50 55 42 4c 49 43 5f 48 4f 49 53 54 5f 50 41 54 54 45 52 4e 5f 44 49 46 46 e2 80 89 20 54 68 69 73 20 6d 6f 64 75 ... 126 more bytes>,
    <Buffer >
  ],
  pid: 52692,
  stdout: <Buffer e2 80 89 45 52 52 5f 50 4e 50 4d 5f 50 55 42 4c 49 43 5f 48 4f 49 53 54 5f 50 41 54 54 45 52 4e 5f 44 49 46 46 e2 80 89 20 54 68 69 73 20 6d 6f 64 75 ... 126 more bytes>,
  stderr: <Buffer >
}
```

### Expected Behavior

Executed successfully.

### Steps to Reproduce

`npx nx connect-to-nx-cloud`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.18.1
   OS   : darwin arm64
   pnpm : 7.18.1
   
   nx              : 15.8.6
   lerna           : 6.5.1
   @nrwl/cli       : 15.8.6
   @nrwl/devkit    : 15.8.6
   @nrwl/tao       : 15.8.6
   @nrwl/nx-cloud  : 16.0.5
   typescript      : 4.9.5
```

### Failure Logs

```shell
✔ Enable distributed caching to make your CI faster · Yes
nx.js connect

Connect workspace to Nx Cloud

Options:
  --help     Show help                                                                                                                                                                      [boolean]
  --version  Show version number                                                                                                                                                            [boolean]

Find more information and examples at https://nx.dev/nx/connect-to-nx-cloud

Error: Command failed: pnpm add -Dw @nrwl/nx-cloud@latest
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at Object.<anonymous> (/Users/xxx/node_modules/.pnpm/nx@15.8.6/node_modules/nx/src/command-line/connect.js:55:42)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxx/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:164:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer e2 80 89 45 52 52 5f 50 4e 50 4d 5f 50 55 42 4c 49 43 5f 48 4f 49 53 54 5f 50 41 54 54 45 52 4e 5f 44 49 46 46 e2 80 89 20 54 68 69 73 20 6d 6f 64 75 ... 126 more bytes>,
    <Buffer >
  ],
  pid: 52692,
  stdout: <Buffer e2 80 89 45 52 52 5f 50 4e 50 4d 5f 50 55 42 4c 49 43 5f 48 4f 49 53 54 5f 50 41 54 54 45 52 4e 5f 44 49 46 46 e2 80 89 20 54 68 69 73 20 6d 6f 64 75 ... 126 more bytes>,
  stderr: <Buffer >
}
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
What error do you see if you run the command manually?

```
pnpm add -Dw @nrwl/nx-cloud@latest
```

**Comment by zqinmiao** [comment]
> 

Successfully installed `@nrwl/nx-cloud` in the project root directory.

Then proceed to `npx nx connect-to-nx-cloud` and report the same error as above.

**Comment by zqinmiao** [comment]
> What error do you see if you run the command manually?
> 
> ```
> pnpm add -Dw @nrwl/nx-cloud@latest
> ```

Successfully installed `@nrwl/nx-cloud` in the project root directory.

Then proceed to `npx nx connect-to-nx-cloud` and report the same error as above.

**Comment by zqinmiao** [comment]
> What error do you see if you run the command manually?
> 
> ```
> pnpm add -Dw @nrwl/nx-cloud@latest
> ```

@AgentEnder 

Successfully installed `@nrwl/nx-cloud` in the project root directory.

Then proceed to `npx nx connect-to-nx-cloud` and report the same error as above.
