### ISSUE TITLE
Cypress: Setting env breaks cypress hosting

### ISSUE THREAD

**Issue by dflor003** [nrwl/nx#17912]
### Current Behavior

I have a project with cypress for e2e and component testing. We just had a need to add an environment variable to the cypress config that we want to access via `Cypress.env('...')` so we can set a different value in our CI. We tried just about every possible way that cypress supports setting environment variables based off their [docs](https://docs.cypress.io/guides/guides/environment-variables) and experimentation:

- Creating a `cypress.env.json` file with the variables
- Setting a `CYPRESS_MY_ENV_VAR=value` env var
- Passing `--env.MY_ENV_VAR=value` via the CLI
- Passing `env: { MY_ENV_VAR: 'value' }` in the `cypress.config.ts` at the top-level
- Passing `env: { MY_ENV_VAR: 'value' }` in the `cypress.config.ts` under the e2e block

In all cases, the behavior makes it so that cypress cannot respond to any requests to the app's URL. All requests are met with an `ECONNREFUSED` error. See the failure log for details.

### Expected Behavior

Setting env vars on cypress works as per their docs and env vars are accessible using `Cypress.env('MY_ENV_VAR')`.

### Steps to Reproduce

1. Create an NX angular app project with cypress for e2e testing
2. In the `cypress.config.json` add an `env` section with an environment variable (or any of the other methods listed above).
3. Add an e2e test that retrieves the environment variable and navigates via `cy.visit('/')`
4. Observe that if you pass an `env` section, the navigation results in an `ECONNREFUSED` error.
5. Remove the `env` section and observe that navigation works now.

### Nx Report

```shell
$ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.7.2
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/storybook      : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.1
   @ngrx/effects         : 16.0.1
   @ngrx/entity          : 16.0.1
   @ngrx/eslint-plugin   : 16.0.1
   @ngrx/router-store    : 16.0.1
   @ngrx/store           : 16.0.1
   @ngrx/store-devtools  : 16.0.1
   @storybook/angular    : 7.0.18
```

### Failure Logs

```shell
CypressError: `cy.visit()` failed trying to load:
http://localhost:4201/
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:
  > Error: connect ECONNREFUSED 127.0.0.1:4201
Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Sign Up`
      at <unknown> (http://localhost:4201/__cypress/runner/cypress_runner.js:147682:82)
      at visitFailedByErr (http://localhost:4201/__cypress/runner/cypress_runner.js:147074:12)
      at <unknown> (http://localhost:4201/__cypress/runner/cypress_runner.js:147681:11)
      at tryCatcher (http://localhost:4201/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:4201/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:4201/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:4201/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:4201/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:4201/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:4201/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4201/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:4201/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (webpack:///./src/e2e/sign-up.cy.ts:6:0)

  From Node.js Internals:
    Error: connect ECONNREFUSED 127.0.0.1:4201
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

We run our app on port `4200` for local dev but run it on `4201` for e2e to avoid it conflicting if we run `npm run e2e` while local dev server is running. This is our serve config in our main app:

```json
"serve": {
      "executor": "@angular-devkit/build-angular:dev-server",
      "configurations": {
        "production": {
          "browserTarget": "<the-app>:build:production"
        },
        "development": {
          "browserTarget": "<the-app>:build:development"
        },
        "e2e": {
          "browserTarget": "<the-app>:build:development",
          "port": 4201
        }
      },
      "defaultConfiguration": "development"
    },
```

And then our e2e app's target:

```json
"e2e": {
      "executor": "@nx/cypress:cypress",
      "options": {
        "cypressConfig": "apps/<the-app>-e2e/cypress.config.ts",
        "devServerTarget": "<the-app>:serve:e2e",
        "testingType": "e2e"
      },
      "configurations": {
        "production": {
          "devServerTarget": "<the-app>::serve:production"
        }
      }
    },
```

**Comment by dflor003** [comment]
Did some more troubleshooting on this and looks like it's a cypress bug. I created an issue on their board for this: https://github.com/cypress-io/cypress/issues/27186
