### ISSUE TITLE
16.5.0 does not work on Node.js 14 anymore

### ISSUE THREAD

**Issue by danez** [nrwl/nx#17986]
### Current Behavior

gitpod /workspace/react-docgen (renovate/nrwl-monorepo) $ ./node_modules/.bin/nx run-many --target=build --exclude='@react-docgen-internal/*' --verbose

 >  NX   Running target build for 2 projects:

    - @react-docgen/cli
    - react-docgen

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for 2 projects

 >  NX   performance is not defined

ReferenceError: performance is not defined
    at Cache.<anonymous> (/workspace/react-docgen/node_modules/.pnpm/nx@16.5.0/node_modules/nx/src/tasks-runner/cache.js:124:13)
    at Generator.next (<anonymous>)
    at /workspace/react-docgen/node_modules/.pnpm/tslib@2.6.0/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/workspace/react-docgen/node_modules/.pnpm/tslib@2.6.0/node_modules/tslib/tslib.js:165:16)
    at Cache._expandOutputs (/workspace/react-docgen/node_modules/.pnpm/nx@16.5.0/node_modules/nx/src/tasks-runner/cache.js:122:24)
    at Cache.<anonymous> (/workspace/react-docgen/node_modules/.pnpm/nx@16.5.0/node_modules/nx/src/tasks-runner/cache.js:118:25)
    at Generator.next (<anonymous>)
    at /workspace/react-docgen/node_modules/.pnpm/tslib@2.6.0/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)

### Expected Behavior

To work normally as in 16.4.x

### GitHub Repo

https://github.com/reactjs/react-docgen/pull/817

### Steps to Reproduce

1. clone
2. nvm install 14
3. pnpm run build

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 14.21.3
   OS     : linux-x64
   pnpm   : 8.6.6
   
   nx          : 16.5.0
   @nrwl/tao   : 16.5.0
   typescript  : 5.1.6
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by tido64** [comment]
We are also hitting the same issue. We maintain a bunch of tools that still support v14, so we still run v14 on CI.

**Comment by chigia001** [comment]
This is introduce by https://github.com/nrwl/nx/pull/17638
Node@14 don't support the performance global object.
CC: @Cammisuli
