### ISSUE TITLE
ERR_REQUIRE_ESM causing all nx commands to fail on macOS using Node 18 and 20

### ISSUE THREAD

**Issue by jlengstorf** [nrwl/nx#18031]
### Current Behavior

On my macOS environment, Nx is failing with `ERR_REQUIRE_ESM` for all commands.

I tried upgrading Nx as well as using `npx` to pull the latest with no luck. Also tried Node 18 and 20 to see if it was a Node version thing. See below for the full error output.

### Expected Behavior

Nx should execute commands as expected without error.

### Steps to Reproduce

1. Run `npx nx --help` on macOS

### Nx Report

```shell
❯ npx nx report
/Users/blitz/github/learnwithjason/learnwithjason.dev/node_modules/nx/node_modules/yargs/node_modules/cliui/build/index.cjs:291
const stringWidth = require('string-width');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/blitz/github/learnwithjason/learnwithjason.dev/node_modules/string-width/index.js from /Users/blitz/github/learnwithjason/learnwithjason.dev/node_modules/nx/node_modules/yargs/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /Users/blitz/github/learnwithjason/learnwithjason.dev/node_modules/nx/node_modules/yargs/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/blitz/github/learnwithjason/learnwithjason.dev/node_modules/nx/node_modules/yargs/node_modules/cliui/build/index.cjs:291:21)
    at Object.<anonymous> (/Users/blitz/github/learnwithjason/learnwithjason.dev/node_modules/nx/node_modules/yargs/build/index.cjs:1:60039)
    at Object.<anonymous> (/Users/blitz/github/learnwithjason/learnwithjason.dev/node_modules/nx/node_modules/yargs/index.cjs:5:30)
    at Object.<anonymous> (/Users/blitz/github/learnwithjason/learnwithjason.dev/node_modules/nx/src/command-line/nx-commands.js:8:15)
    at Object.<anonymous> (/Users/blitz/github/learnwithjason/learnwithjason.dev/node_modules/nx/bin/init-local.js:7:23)
    at Object.<anonymous> (/Users/blitz/github/learnwithjason/learnwithjason.dev/node_modules/nx/bin/nx.js:6:22) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.4.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jlengstorf** [comment]
did a little more digging and realized that my nx versions were out of sync — I had a local on 15.x, but my global was on latest. when I uninstalled it only got the global, so my local was still the outdated version

false alarm on the bug. kind of a weird debugging experience but I'm not sure how to make it easier since I do need the local install in the project to deploy
