### ISSUE TITLE
In Angular 16, after upgrading to storybook 7.0.26, getting the glob is not a function issue 

### ISSUE THREAD

**Issue by surenlancer7** [nrwl/nx#18083]
### Current Behavior

Below is the terminal response if I run "npm run storybook"
> external-app@7.4.2 storybook
> storybook dev

@storybook/cli v7.0.26

ERR! TypeError: glob is not a function

### Expected Behavior

It should run the storybook in browser

### Steps to Reproduce

1. Use the Angular 16 base application
2. npm run storybook

### Nx Report

```shell
> external-app@7.4.2 storybook
> storybook dev

@storybook/cli v7.0.26

ERR! TypeError: glob is not a function
ERR!     at /Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:5:5
ERR!     at new Promise (<anonymous>)
ERR!     at promise (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:4:10)
ERR!     at validateConfigurationFiles (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:6:1024)
ERR!     at loadMainConfig (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:19:6701)
ERR!     at buildDevStandalone (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:59:1340)
ERR!     at async withTelemetry (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:46:3620)
ERR!     at async dev (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/cli/dist/generate.js:440:401)
ERR!     at async Command.<anonymous> (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/cli/dist/generate.js:442:225)
ERR!  TypeError: glob is not a function
ERR!     at /Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:5:5
ERR!     at new Promise (<anonymous>)
ERR!     at promise (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:4:10)
ERR!     at validateConfigurationFiles (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:6:1024)
ERR!     at loadMainConfig (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:19:6701)
ERR!     at buildDevStandalone (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:59:1340)
ERR!     at async withTelemetry (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:46:3620)
ERR!     at async dev (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/cli/dist/generate.js:440:401)
ERR!     at async Command.<anonymous> (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/cli/dist/generate.js:442:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info Found existing addon "@storybook/addon-controls", skipping.
info Found existing addon "@storybook/addon-actions", skipping.
TypeError: glob is not a function
    at /Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:5:5
    at new Promise (<anonymous>)
    at promise (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:4:10)
    at validateConfigurationFiles (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:6:1024)
    at loadCustomPresets (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:12:48)
    at loadAllPresets (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:15:1681)
    at getErrorLevel (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:46:2072)
    at sendTelemetryError (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:46:2793)
    at withTelemetry (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:46:3802)
    at async dev (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/cli/dist/generate.js:440:401)
```

### Failure Logs

```shell
> external-app@7.4.2 storybook
> storybook dev

@storybook/cli v7.0.26

ERR! TypeError: glob is not a function
ERR!     at /Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:5:5
ERR!     at new Promise (<anonymous>)
ERR!     at promise (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:4:10)
ERR!     at validateConfigurationFiles (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:6:1024)
ERR!     at loadMainConfig (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:19:6701)
ERR!     at buildDevStandalone (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:59:1340)
ERR!     at async withTelemetry (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:46:3620)
ERR!     at async dev (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/cli/dist/generate.js:440:401)
ERR!     at async Command.<anonymous> (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/cli/dist/generate.js:442:225)
ERR!  TypeError: glob is not a function
ERR!     at /Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:5:5
ERR!     at new Promise (<anonymous>)
ERR!     at promise (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:4:10)
ERR!     at validateConfigurationFiles (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:6:1024)
ERR!     at loadMainConfig (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:19:6701)
ERR!     at buildDevStandalone (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:59:1340)
ERR!     at async withTelemetry (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:46:3620)
ERR!     at async dev (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/cli/dist/generate.js:440:401)
ERR!     at async Command.<anonymous> (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/cli/dist/generate.js:442:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info Found existing addon "@storybook/addon-controls", skipping.
info Found existing addon "@storybook/addon-actions", skipping.
TypeError: glob is not a function
    at /Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:5:5
    at new Promise (<anonymous>)
    at promise (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/glob-promise/lib/index.js:4:10)
    at validateConfigurationFiles (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:6:1024)
    at loadCustomPresets (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:12:48)
    at loadAllPresets (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-common/dist/index.js:15:1681)
    at getErrorLevel (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:46:2072)
    at sendTelemetryError (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:46:2793)
    at withTelemetry (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/core-server/dist/index.js:46:3802)
    at async dev (/Users/user/Desktop/company/Code_base/Responsive Web/mrw-library/mrw-app/node_modules/@storybook/cli/dist/generate.js:440:401)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @surenlancer7 ! Thanks for filing an issue! Can you please provide a minimum reproduction repository, so that I can debug this more easily and be able to help you more quickly? Thank you! :D
