### ISSUE TITLE
dependentTasksOutputFiles not working

### ISSUE THREAD

**Issue by coder89** [nrwl/nx#18080]
### Current Behavior

dependentTasksOutputFiles not working on Windows

### Expected Behavior

.

### Steps to Reproduce

1. Create simple monorepo with tsc as a compiler (without nx generators).
2. Link two dependencies together
3. Specity target outputs as per documentation i.e. `"deps": [{ "dependentTasksOutputFiles": "**/*.d.ts", "transitive": true }]`
4. run build script and observe an error showing in the logs

### Nx Report

```shell
.
```

### Failure Logs

```shell
C:\repos\sn.monorepo\node_modules\nx\src\hasher\file-hasher.js:81
    return hashArray(content);
           ^

Error: Failed to convert JavaScript value `Null` into rust type `String`
    at hashArray (C:\repos\sn.monorepo\node_modules\nx\src\hasher\file-hasher.js:81:12)
    at TaskHasherImpl.hashDepOuputs (C:\repos\sn.monorepo\node_modules\nx\src\hasher\task-hasher.js:233:52)
    at TaskHasherImpl.hashDepsOutputs (C:\repos\sn.monorepo\node_modules\nx\src\hasher\task-hasher.js:212:33)
    at TaskHasherImpl.<anonymous> (C:\repos\sn.monorepo\node_modules\nx\src\hasher\task-hasher.js:154:34)
    at Generator.next (<anonymous>)
    at fulfilled (C:\repos\sn.monorepo\node_modules\tslib\tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'StringExpected'
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
We've made lots of fixes here recently. Can you lease retry with the latest version?

If you still have issues, can you please provide a repo that we can use to reproduce an issue?
