### ISSUE TITLE
Io error. Look inside err_kind for more details

### ISSUE THREAD

**Issue by kf6kjg** [nrwl/nx#18111]
### Current Behavior

Executing 

```sh
rm -rf node_modules/.cache/nx
npx nx run-many --output-style=stream --target=build --parallel=8
```
works fine. A second execution of

```sh
npx nx run-many --output-style=stream --target=build --parallel=8
```

Results in

```
>  NX   Running target build for 18 projects:
...REDACTED...

 >  NX   Successfully ran target build for 18 projects

 >  NX   Io error. Look inside err_kind for more details.

   Pass --verbose to see the stacktrace.
```

The verbose flag only shows the following additional data:

```
Error: Io error. Look inside err_kind for more details.
    at /app/node_modules/nx/src/tasks-runner/cache.js:155:21
    at new Promise (<anonymous>)
    at Cache.<anonymous> (/app/node_modules/nx/src/tasks-runner/cache.js:153:20)
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:163:16)
    at Cache.remove (/app/node_modules/nx/src/tasks-runner/cache.js:151:24)
    at Cache.<anonymous> (/app/node_modules/nx/src/tasks-runner/cache.js:102:36)
    at Generator.next (<anonymous>)
```

I'm executing from inside of a customized Docker Dev Container based off of `mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18-bullseye` using VSCode.

### Expected Behavior

That NX should recognize that all entries are cached and not report any errors.

If there are indeed IO errors, then it should report the real error, not just the wrapper error [posted by rust fs_extra](https://github.com/webdesus/fs_extra/blob/1754296075e7cc4a25feaa876a3f4b9daccc0b98/src/error.rs#L153). This would help me diagnose the underlying problem.

### Steps to Reproduce

I'm not sure I have a generic way to reproduce this at this time. The root cause may be unique to me - this request is more to see if we can get the error message handling provide better information. It looks like the change to using this library was recent? https://github.com/nrwl/nx/pull/17638

### Nx Report

```shell
Node   : 18.16.0
   OS     : linux-arm64
   npm    : 8.19.4
   
   nx             : 16.5.2
   @nx/workspace  : 16.5.2
   @nx/devkit     : 16.5.2
   @nrwl/tao      : 16.5.2
   typescript     : 5.1.3
   ---------------------------------------
   Local workspace plugins:
         @REDACTED/config-demo
         @REDACTED/nx-config
         @REDACTED/types
```

### Failure Logs

```shell
Error: Io error. Look inside err_kind for more details.
    at /app/node_modules/nx/src/tasks-runner/cache.js:155:21
    at new Promise (<anonymous>)
    at Cache.<anonymous> (/app/node_modules/nx/src/tasks-runner/cache.js:153:20)
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:163:16)
    at Cache.remove (/app/node_modules/nx/src/tasks-runner/cache.js:151:24)
    at Cache.<anonymous> (/app/node_modules/nx/src/tasks-runner/cache.js:102:36)
    at Generator.next (<anonymous>)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by kf6kjg** [comment]
So I found out more symptoms.
1. This happens on Intel Macs as well.
2. A co-worker discovered that if he downgraded to NX 16.4 he got the following much more useful error:
   ```
   >  NX   EBUSY: resource busy or locked, rmdir '/app/packages/tsconfig-generator/dist'
   ```
3. This is because NX has some form of default behavior for the `build` target that is conflicting with the fact that my devcontainer set up is mounting a `tmpfs` disk on the `dist` folder.

Workaround: change the target name to something that NX doesn't have default behaviors for. If there's a way to turn thse off I'd prefer that.

**Comment by Cammisuli** [comment]
This isn't a fix, but it'll help us solve this issue. I've done what you suggested, and exposed the IoError that gets swallowed up by fs_extra. Hopefully this will give us some more answers on what we can do for you
#18656

**Comment by kf6kjg** [comment]
Thank you. We'd diagnosed the underlying cause by using an earlier version of nx: we got an error that the dist folder could not be deleted. We had mounted the dist folder with tmpfs. This makes the folder unable to be deleted, causing an error when nx tries to remove and recreate it.

**Comment by kf6kjg** [comment]
Do you need further input? With the new diagnostics it should be easy to reproduce.

**Comment by Cammisuli** [comment]
No, its something we still need to fix, as we're getting the same kind of errors in our e2es -  randomly of course.

**Comment by kf6kjg** [comment]
Hopefully I'll be back to working on the monorepos in a couple months. Was working on converting a lot of repos, but other priorities took over.

**Comment by stefanlivens** [comment]
We have a similar but different issue:
Error:
 NX   Io error. Look inside err_kind for more details.

But that is all we get.

Context: this is a mono-repo with NX20.3.1, running in a linux-based docker container. The fun thing is: if i add useLegacyCache:true to my nx.json, everything works without an issue! It works with and without that setting in MacOS and Windows.

**Comment by grxy** [comment]
I also encountered this error. Here's what I did to resolve it, in case it is helpful for anyone:

## Initial setup

**Target: `build`**
  - `build` creates a `{projectRoot}/build` directory containing built assets

**Execution environment: docker container**
  - `{projectRoot}/build` is mounted as a delegated volume
  - `.nx` directory is mounted as a delegated volume

**Nx config**
  - No `outputs` config defined for `build` target

## ❌  Fix attempt 1
**Change:**  Define `build.outputs` config as `["{projectRoot}/build"]`

**Thoughts:** I think this is failing because Nx is replacing the mounted directory with the cache contents, and that directory is considered busy and cannot be replaced.

## ✅ Fix attempt 2
**Change:** Define `build.outputs` config as `["{projectRoot}/build/**"]`

**Thoughts:** I think this works because Nx is now replacing the contents of the mounted `build` directory, and is not replacing the directory itself.

**Comment by patrickmichalina** [comment]
This is hitting me all the time now..

**Comment by AgentEnder** [comment]
> This is hitting me all the time now..

The steps that can lead to it are pretty well documented above, though the root cause isnt fixed. Have you recently updated nx or changed how a project is configured or docker volume is mounted? Can you share a reproduction of dedicated steps to cause it?

At the very least, a stack trace showing how your error is presented to validate that it is indeed the same error would go a long way.

**Comment by patrickmichalina** [comment]
> > This is hitting me all the time now..
> 
> The steps that can lead to it are pretty well documented above, though the root cause isnt fixed. Have you recently updated nx or changed how a project is configured or docker volume is mounted? Can you share a reproduction of dedicated steps to cause it?
> 
> At the very least, a stack trace showing how your error is presented to validate that it is indeed the same error would go a long way.

```
 NX   Io error. Look inside err_kind for more details.

Error: Io error. Look inside err_kind for more details.
    at DbCache.applyRemoteCacheResults (/Users/patrick/code/node_modules/.pnpm/nx@22.6.3_@swc-node+register@1.11.1_@swc+core@1.15.21_@swc+helpers@0.5.20__@swc+types@0_48904fb87aa811df9a831fe23b8a8224/node_modules/nx/src/tasks-runner/cache.js:103:27)
    at DbCache.get (/Users/patrick/code/node_modules/.pnpm/nx@22.6.3_@swc-node+register@1.11.1_@swc+core@1.15.21_@swc+helpers@0.5.20__@swc+types@0_48904fb87aa811df9a831fe23b8a8224/node_modules/nx/src/tasks-runner/cache.js:84:22)
    at processTicksAndRejections (node:internal/process/task_queues:104:5)
    at TaskOrchestrator.applyCachedResult (/Users/patrick/code/node_modules/.pnpm/nx@22.6.3_@swc-node+register@1.11.1_@swc+core@1.15.21_@swc+helpers@0.5.20__@swc+types@0_48904fb87aa811df9a831fe23b8a8224/node_modules/nx/src/tasks-runner/task-orchestrator.js:218:30)
    at async Promise.all (index 0)
    at TaskOrchestrator.applyCachedResults (/Users/patrick/code/node_modules/.pnpm/nx@22.6.3_@swc-node+register@1.11.1_@swc+core@1.15.21_@swc+helpers@0.5.20__@swc+types@0_48904fb87aa811df9a831fe23b8a8224/node_modules/nx/src/tasks-runner/task-orchestrator.js:214:21)
    at TaskOrchestrator.applyFromCacheOrRunTask (/Users/patrick/code/node_modules/.pnpm/nx@22.6.3_@swc-node+register@1.11.1_@swc+core@1.15.21_@swc+helpers@0.5.20__@swc+types@0_48904fb87aa811df9a831fe23b8a8224/node_modules/nx/src/tasks-runner/task-orchestrator.js:437:40)
    at TaskOrchestrator.executeDiscreteTaskLoop (/Users/patrick/code/node_modules/.pnpm/nx@22.6.3_@swc-node+register@1.11.1_@swc+core@1.15.21_@swc+helpers@0.5.20__@swc+types@0_48904fb87aa811df9a831fe23b8a8224/node_modules/nx/src/tasks-runner/task-orchestrator.js:150:17)
    at async Promise.all (index 1)
    at TaskOrchestrator.run (/Users/patrick/code/node_modules/.pnpm/nx@22.6.3_@swc-node+register@1.11.1_@swc+core@1.15.21_@swc+helpers@0.5.20__@swc+types@0_48904fb87aa811df9a831fe23b8a8224/node_modules/nx/src/tasks-runner/task-orchestrator.js:102:9)
```

**Comment by patrickmichalina** [comment]
Claude's investigation may help: 

```
Root Cause                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                               
  431 of ~460 cache directories in .nx/cache/ are completely empty, but the SQLite DB (.nx/workspace-data/*.db) thinks they contain files. When Nx tries to restore cached outputs on a subsequent run, the Rust native code walks these empty directories,    
  hits a filesystem mismatch, and fs_extra wraps the real IO error in the useless "Io error. Look inside err_kind for more details." message.                                                                                                                  
                                                                                                                                                                                                                                                               
  The chain:                                                                                                                                                                                                                                                   
  1. GCS remote cache downloads and extracts a tarball → creates directory under .nx/cache/<hash>/                                                                                                                                                             
  2. If download fails silently or the task has no file outputs (e.g., lint), the directory is left empty                                                                                                                                                      
  3. applyRemoteCacheResults records success in SQLite anyway                                                                                                                                                                                                  
  4. Next run: SQLite says "hash X has cached outputs of size Y" → Rust tries to copy from an empty dir → boom                                                                                                                                                 
                                                                                                                                                                                                                                                               
  Why this is an Nx bug (not your fault)                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
  - applyRemoteCacheResults has no retry logic (unlike put() and copyFilesFromCache() which both use tryAndRetry with 6 attempts)                                                                                                                              
  - The Rust fs_extra crate's Display impl only prints the wrapper message — the actual OS error (ENOENT, EACCES, etc.) is trapped in a struct field inaccessible from JS                                                                                      
  - The GCS plugin doesn't clean up empty directories on failed downloads                                                                                                                                                                                      
                                                                  
  Immediate Fix                                                                                                                                                                                                                                                
                                                                  
  pnpm nx reset

  This clears .nx/cache/ and the SQLite DB, resolving the DB-vs-filesystem mismatch. You'll take a one-time cache miss hit as everything rebuilds/re-fetches from GCS.                                                                                         
  
  Longer-term Mitigations                                                                                                                                                                                                                                      
                                                                  
  1. Periodic cache reset — if this keeps recurring, add pnpm nx reset to your pre-push hook or run it weekly                                                                                                                                                  
  2. Report upstream — you already commented on nrwl/nx#18111. The key new info to add:
    - 431/460 empty cache dirs with non-empty DB entries                                                                                                                                                                                                       
    - applyRemoteCacheResults lacks tryAndRetry wrapping (lines 102-104 in cache.js)                                                                                                                                                                           
    - GCS cache plugin doesn't validate extraction success before recording in DB                                                                                                                                                                              
  3. useLegacyCache: true in nx.json works as a workaround (as noted in the issue by @stefanlivens) because the legacy cache doesn't use the Rust/SQLite path — but you'd lose the perf benefits of the DB cache 
```
