### ISSUE TITLE
Cannot read properties of undefined (reading 'styled-components') when installing 

### ISSUE THREAD

**Issue by cbroomemktw** [nrwl/nx#18168]
### Current Behavior

When running `nx generate @nx/react:app gatsby` to generate a new gatsby react app in an existing repo there's a failure soon after selecting 'sass' for styling.

### Expected Behavior

You should be able to create a gatsby app using the generator

### Steps to Reproduce

1. install gatsby generator: npm i -D @nx/gatsby
1. run nx generate @nx/react:app gatsby
2. observe error

### Nx Report

```shell
Node   : 19.9.0
   OS     : darwin-x64
   npm    : 9.6.3

   nx (global)        : 16.3.2
   nx                 : 16.5.3
   @nx/js             : 16.5.3
   @nx/jest           : 16.5.3
   @nx/linter         : 16.5.3
   @nx/workspace      : 16.5.3
   @nx/cypress        : 16.5.3
   @nx/devkit         : 16.5.3
   @nx/esbuild        : 16.5.3
   @nx/eslint-plugin  : 16.5.3
   @nx/express        : 16.5.3
   @nx/node           : 16.5.3
   @nx/plugin         : 16.5.3
   @nx/react          : 16.5.3
   @nrwl/tao          : 16.5.3
   @nx/web            : 16.5.3
   @nx/webpack        : 16.5.3
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx/gatsby : 16.1.1
```

### Failure Logs

```shell
TypeError: Cannot read properties of undefined (reading 'styled-components')
    at Object.<anonymous> (.../@nx/gatsby/src/utils/styles.js:9:53)
    at Module._compile (.../node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at Mod.require (.../node_modules/nx/bin/init-local.js:204:36)
    at require (.../node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (.../node_modules/@nx/gatsby/src/generators/application/application.js:7:18)
    at Module._compile (.../node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by rwpino** [comment]
I m having the same issue

**Comment by rathodkaran07** [comment]
Hi , 
I was able to resolve the issue. This is due to version compatibility, try using the same @nx/react version as @nx/gatsby.
E.g: npm install -D @nx/gatsby@16.1 @nx/react@16.1
after this try , generating the gatsby app using "npx nx g @nx/gatsby:application"

**Comment by cbroomemktw** [comment]
Hmm, my react version is at v18. It doesn't look like there's a @nx/gatsby that matches it yet.

**Comment by rathodkaran07** [comment]
@cbroomemktw , I am talking about @nx/react version and not just react. Plus @nx/gatsby@16.1 will refer to the latest available version that is 16.1.1.
Try this out once

**Comment by cbroomemktw** [comment]
@rathodkaran07 Verified! This gets past the styled-components error.

**Comment by cbroomemktw** [comment]
Looks like there's a few more steps to get this working. The default `project.json` has references to `builder` fields that need to be replaced with `executor`:

```
{
  "name": "ui",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/ui/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nx/gatsby:build",
      "options": {
        "outputPath": "apps/ui/public",
        "uglify": true,
        "color": true,
        "profile": false
      },
      "configurations": {
        "production": {}
      }
    },
    "serve": {
      "executor": "@nx/gatsby:server",
      "options": {
        "buildTarget": "ui:build"
      },
      "configurations": {
        "production": {
          "buildTarget": "ui:build:production"
        }
      }
    },
    "lint": {
      "executor": "@nx/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/ui/**/*.{ts,tsx,js,jsx}"]
      }
    },
    "test": {
      "executor": "@nx/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/{projectRoot}"],
      "options": {
        "jestConfig": "apps/ui/jest.config.ts",
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    }
  },
  "tags": []
}
```

Then both `nx build ui` and `nx serve ui` will work. However after running serve I got this message: 

> The Gatsby plugin will be deprecated in Nx 15 and removed in Nx 16. We are committed to providing high-quality tooling to community, and we no longer have the capacity to keep this plugin updated.

So 🤷 ... I guess can a Gatsby site run in NX without this plugin? Should it be run as a Node or react site instead?

**Comment by mandarini** [comment]
Hi all! It's great that you found a solution to this issue, but yes, as mentioned we are no longer maintaining that plugin. So I will be closing this issue!
