### ISSUE TITLE
Cannot find module '@nx/node/src/executors/node/schema.json'

### ISSUE THREAD

**Issue by anthony-b-dev** [nrwl/nx#18205]
### Current Behavior

I use `nx serve <nestjs app>` in the command line and it fails to build my app. I recently moved files from an angular app into libraries and upgraded to Nx 16.5.3 when I started running into this issue. 
Troubleshooting:
- I rolled my version back to 16.5.0 where I knew I wasn't having any problems.
- I rolled by global version back to 16.5.0 as well. 
- I deleted my entire node_modules folder and package-lock.json before running npm install again
- I restarted vs code
- I restarted my computer

### Expected Behavior

`nx serve` builds and runs the nestjs app without any errors.

### Steps to Reproduce

1. run `nx serve <nestjs app> `

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32-x64
   npm    : 9.6.6

   nx (global)        : 16.5.0
   nx                 : 16.5.0
   @nx/js             : 16.5.0
   @nx/jest           : 16.5.0
   @nx/linter         : 16.5.0
   @nx/workspace      : 16.5.0
   @nx/angular        : 16.5.0
   @nx/cypress        : 16.5.0
   @nx/devkit         : 16.5.0
   @nx/esbuild        : 16.5.0
   @nx/eslint-plugin  : 16.5.0
   @nx/express        : 16.5.0
   @nx/nest           : 16.5.0
   @nx/node           : 16.5.0
   @nrwl/tao          : 16.5.0
   @nx/webpack        : 16.5.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/eslint-plugin   : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/schematics      : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
   ---------------------------------------
   Local workspace plugins:
         @afb/dates
```

### Failure Logs

```shell
>  NX   Unable to resolve @nrwl/node:node.

   Cannot find module '@nx/node/src/executors/node/schema.json'
   Require stack:
   - <workspace>\node_modules\nx\src\config\workspaces.js
   - <workspace>\node_modules\nx\src\config\configuration.js
   - <workspace>\node_modules\nx\src\utils\package-manager.js
   - <workspace>\node_modules\nx\bin\init-local.js
   - <workspace>\node_modules\nx\bin\nx.js
   - C:\Users\user\AppData\Roaming\npm\node_modules\nx\bin\nx.js

Error: Unable to resolve @nrwl/node:node.
Cannot find module '@nx/node/src/executors/node/schema.json'
Require stack:
- <workspace>\node_modules\nx\src\config\workspaces.js
- <workspace>\node_modules\nx\src\config\configuration.js
- <workspace>\node_modules\nx\src\utils\package-manager.js
- <workspace>\node_modules\nx\bin\init-local.js
- <workspace>\node_modules\nx\bin\nx.js
- C:\Users\user\AppData\Roaming\npm\node_modules\nx\bin\nx.js
    at Workspaces.readExecutor (<workspace>\node_modules\nx\src\config\workspaces.js:119:19)
    at <workspace>\node_modules\nx\src\tasks-runner\utils.js:191:26
    at Generator.next (<anonymous>)
    at fulfilled (<workspace>\node_modules\tslib\tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by anthony-b-dev** [comment]
Not a bug. Goes back to the removal of the node executor in favor of nx/js:node executor. 
[https://stackoverflow.com/questions/76745424/how-do-i-resolve-the-following-error-cannot-find-module-nx-node-src-executors/76745449#76745449]

Would be good to include a migration for this if it doesn't exist...
