### ISSUE TITLE
NX   Failed to parse yarn lockfile

### ISSUE THREAD

**Issue by withYJ** [nrwl/nx#18247]
### Current Behavior

Failed to install

### Expected Behavior

Install

### Steps to Reproduce

1. Mac Studio Apple M1 Max OS 13.2.1(22D68)
2. node v18.12.0
3. npx create-nx-workspace@latest --pm yarn --preset=next --skip-git=true
✔ Where would you like to create your workspace? · quizpang
✔ Application name · web
✔ Would you like to use the App Router (recommended)? · Yes
✔ Default stylesheet format · scss
✔ Enable distributed caching to make your CI faster · Yes

### Nx Report

```shell
>  NX   Creating your v16.5.4 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "yarn install" several times. Please wait.

✔ Installing dependencies with yarn
✖ Creating your workspace in quizpang

 >  NX   Failed to create a workspace.

   Exit code: 1
   Log file: /var/folders/0x/vnfcrx493wb5hdpkp1b_41mm0000gn/T/tmp-8981-CFuVbi5OjGGJ/error.log
```

### Failure Logs

```shell
yarn run v1.22.19
$ /private/var/folders/0x/vnfcrx493wb5hdpkp1b_41mm0000gn/T/tmp-8981-CFuVbi5OjGGJ/node_modules/.bin/nx new --pm=yarn --packageManager=yarn --preset=next --skipGit --g --interactive '--commit.message=Initial commit' --no-allPrompts --no-a --/bin/sh=/Users/yj/.npm/_npx/505743838affa773/node_modules/.bin/create-nx-workspace --name=quizpang --stack=react --style=scss --appName=web --nextAppDir --nxCloud --defaultBase=main --ci= --nxWorkspaceRoot=/Users/yj/dev
Resolving classic to a url...
Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn-1.22.19.js...
Saving it into /Users/yj/dev/quizpang/.yarn/releases/yarn-1.22.19.cjs...
Updating /Users/yj/dev/quizpang/.yarnrc...
Done!
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ /Users/yj/dev/quizpang/node_modules/.bin/nx g @nx/workspace:preset --name=web --style=scss --linter=eslint --preset=next --nextAppDir=true --packageManager=yarn --standaloneApi=false --interactive=true --routing=true

 >  NX   Failed to parse yarn lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   
Original error: Target project does not exist: npm:nx-cloud@16.1.1


   Error: Target project does not exist: npm:nx-cloud@16.1.1
    at ProjectGraphBuilder.addDependency (/Users/yj/dev/quizpang/node_modules/nx/src/project-graph/project-graph-builder.js:180:19)
    at ProjectGraphBuilder.addStaticDependency (/Users/yj/dev/quizpang/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at /Users/yj/dev/quizpang/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:164:41
    at Array.forEach (<anonymous>)
    at /Users/yj/dev/quizpang/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:160:49
    at Array.forEach (<anonymous>)
    at /Users/yj/dev/quizpang/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:158:72
    at Array.forEach (<anonymous>)
    at /Users/yj/dev/quizpang/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:155:26
    at Array.forEach (<anonymous>)


 >  NX   Failed to process the project graph with "nx-js-graph-plugin".

   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 >  NX   Workspace creation failed, see above.

   Pass --verbose to see the stacktrace.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

warning " > @nx/next@16.5.4" has unmet peer dependency "next@>=13.0.0".
warning "@nx/next > copy-webpack-plugin@10.2.4" has unmet peer dependency "webpack@^5.1.0".
warning "@nx/next > @babel/plugin-proposal-decorators@7.22.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@nx/next > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "@nx/next > ts-node@10.9.1" has unmet peer dependency "typescript@>=2.7".
warning "@nx/next > url-loader@4.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "@nx/next > @babel/plugin-proposal-decorators > @babel/helper-replace-supers@7.22.9" has unmet peer dependency "@babel/core@^7.0.0".
warning "@nx/next > @babel/plugin-proposal-decorators > @babel/helper-create-class-features-plugin@7.22.9" has unmet peer dependency "@babel/core@^7.0.0".
warning "@nx/next > @babel/plugin-proposal-decorators > @babel/plugin-syntax-decorators@7.22.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@nx/next > @nx/linter > @phenomnomnominal/tsquery@5.0.1" has unmet peer dependency "typescript@^3 || ^4 || ^5".
warning "@nx/next > @nx/react > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
error Command failed with exit code 1.
error Command failed with exit code 1.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by hlmnd** [comment]
I have the same issue, apparently only happens with "--pm yarn"  and "✔ Enable distributed caching to make your IQ faster Yes". With "npm" works well.

**Comment by hellwolf** [comment]
Hitting the same issue.

**Comment by hellwolf** [comment]
Perhaps related to "git+https:" links:

```
$ npm ls ethereumjs-abi@0.6.8
npm ERR! code ELSPROBLEMS
npm ERR! invalid: ethereumjs-abi@0.6.8 /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/downgrade-lerna/node_modules/eth-sig-util/node_modules/ethereumjs-abi
@superfluid-finance/protocol-monorepo@0.0.0 /home/hellwolf/Projects/superfluid/protocol-monorepo.worktree/downgrade-lerna
├─┬ @truffle/hdwallet-provider@2.1.13
│ ├─┬ @metamask/eth-sig-util@4.0.1
│ │ └── ethereumjs-abi@0.6.8 deduped
│ └─┬ web3-provider-engine@16.0.3
│   └─┬ eth-sig-util@1.4.2
│     └── ethereumjs-abi@0.6.8 invalid: "git+https://github.com/ethereumjs/ethereumjs-abi.git" from node_modules/eth-sig-util
└─┬ hardhat@2.17.1
  └── ethereumjs-abi@0.6.8
```

**Comment by meeroslav** [comment]
This is fixed in https://github.com/nrwl/nx/pull/18335. Please update to latest version
