### ISSUE TITLE
🐛 fix: upgrading from 16.5.3 to 16.5.4 causes: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

### ISSUE THREAD

**Issue by bjornharvold** [nrwl/nx#18248]
### Current Behavior

1. I upgraded to 16.5.4
2. I ran `yarn`
3. I ran `yarn nx migrate --run-migrations` but there were no tasks to run
4. I tried to start my app with `npx nx serve my-app` and it errors out with error
5. Downgrading to 16.5.3 solves the issue

There are no extra messages with `--verbose` enabled### 

### Expected Behavior

Applications should run

### Steps to Reproduce

1. Upgrade from 16.5.3 to 16.5.4

### Nx Report

```shell
I can't run nx report as it gives me the same error.

When i downgrade to 16.5.3 and run the report, I get:
 Node   : 18.16.1
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 16.5.3
   @nx/js             : 16.5.3
   @nx/jest           : 16.5.3
   @nx/linter         : 16.5.3
   @nx/workspace      : 16.5.3
   @nx/angular        : 16.5.3
   @nx/cypress        : 16.5.3
   @nx/devkit         : 16.5.3
   @nx/eslint-plugin  : 16.5.3
   @nx/storybook      : 16.5.3
   @nrwl/tao          : 16.5.3
   @nx/web            : 16.5.3
   @nx/webpack        : 16.5.3
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc               : 1.1.21
   @fortawesome/angular-fontawesome : 0.13.0
   @jscutlery/semver                : 3.0.0
   @ng-bootstrap/ng-bootstrap       : 15.1.0
   @ngneat/transloco                : 4.3.0
   @ngrx/component                  : 16.1.0
   @ngrx/component-store            : 16.1.0
   @ngrx/data                       : 16.1.0
   @ngrx/effects                    : 16.1.0
   @ngrx/entity                     : 16.1.0
   @ngrx/router-store               : 16.1.0
   @ngrx/schematics                 : 16.1.0
   @ngrx/store                      : 16.1.0
   @ngrx/store-devtools             : 16.1.0
   @storybook/angular               : 7.1.0
   angular-calendar                 : 0.31.0
```

### Failure Logs

```shell
>  NX   Failed to process the project graph with "nx-js-graph-plugin".

   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```
```


### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

package.json dependencies:

```
"dependencies": {
    "@angular/animations": "16.1.6",
    "@angular/cdk": "16.1.5",
    "@angular/common": "16.1.6",
    "@angular/compiler": "16.1.6",
    "@angular/core": "16.1.6",
    "@angular/elements": "16.1.6",
    "@angular/forms": "16.1.6",
    "@angular/localize": "16.1.6",
    "@angular/platform-browser": "16.1.6",
    "@angular/platform-browser-dynamic": "16.1.6",
    "@angular/router": "16.1.6",
    "@angular/service-worker": "16.1.6",
    "@angular/youtube-player": "16.1.5",
    "@auth0/angular-jwt": "5.1.2",
    "@cloudinary/ng": "2.0.0",
    "@cloudinary/url-gen": "1.10.2",
    "@fortawesome/angular-fontawesome": "0.13.0",
    "@fortawesome/fontawesome-pro": "6.4.0",
    "@fortawesome/fontawesome-svg-core": "6.4.0",
    "@fortawesome/free-brands-svg-icons": "6.4.0",
    "@fortawesome/pro-light-svg-icons": "6.4.0",
    "@fortawesome/pro-regular-svg-icons": "6.4.0",
    "@fortawesome/pro-solid-svg-icons": "6.4.0",
    "@ng-bootstrap/ng-bootstrap": "15.1.0",
    "@ng-select/ng-option-highlight": "0.0.7",
    "@ng-select/ng-select": "11.0.0",
    "@ngneat/content-loader": "7.0.0",
    "@ngneat/transloco": "4.3.0",
    "@ngrx/component": "16.1.0",
    "@ngrx/component-store": "16.1.0",
    "@ngrx/data": "16.1.0",
    "@ngrx/effects": "16.1.0",
    "@ngrx/entity": "16.1.0",
    "@ngrx/router-store": "16.1.0",
    "@ngrx/store": "16.1.0",
    "@ngrx/store-devtools": "16.1.0",
    "@nx/angular": "16.5.3",
    "@paypal/checkout-components": "5.0.208",
    "@popperjs/core": "2.11.8",
    "@sentry/angular-ivy": "7.59.3",
    "@sentry/browser": "7.59.3",
    "@sentry/tracing": "7.59.3",
    "@swimlane/ngx-charts": "20.4.1",
    "@webcomponents/custom-elements": "1.6.0",
    "angular-calendar": "0.31.0",
    "angular-calendar-scheduler": "15.1.0",
    "angular-oauth2-oidc": "15.0.1",
    "bootstrap": "5.3.0",
    "bs-stepper": "1.7.0",
    "cloudinary-build-url": "0.2.4",
    "compass-mixins": "0.12.12",
    "cryptocurrency-icons": "0.18.1",
    "date-fns": "2.30.0",
    "document-register-element": "1.14.10",
    "hammerjs": "2.0.8",
    "immutable": "4.3.1",
    "ionicons": "7.1.2",
    "lodash-es": "4.17.21",
    "ng-qrcode": "16.0.0",
    "ng-sortgrid": "16.0.0",
    "ng2-file-upload": "5.0.0",
    "ngx-captcha": "13.0.0",
    "ngx-color-picker": "14.0.0",
    "ngx-cookie-service": "16.0.0",
    "ngx-date-fns": "10.0.1",
    "ngx-duration-picker": "3.3.1",
    "ngx-sharebuttons": "13.0.0",
    "ngx2-pipes": "13.0.0",
    "npm-font-open-sans": "1.1.0",
    "recaptcha-v3": "1.10.0",
    "rxjs": "^7.8.1",
    "tslib": "^2.6.0",
    "typeface-poppins": "1.1.13",
    "typeface-raleway": "1.1.13",
    "typeface-roboto": "1.1.13",
    "zone.js": "0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "16.1.5",
    "@angular-devkit/core": "16.1.5",
    "@angular-devkit/schematics": "16.1.5",
    "@angular-eslint/eslint-plugin": "16.1.0",
    "@angular-eslint/eslint-plugin-template": "16.1.0",
    "@angular-eslint/template-parser": "16.1.0",
    "@angular/cli": "~16.1.5",
    "@angular/compiler-cli": "16.1.6",
    "@angular/language-service": "16.1.6",
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
    "@cld-apis/types": "0.1.6",
    "@cld-apis/utils": "0.2.0",
    "@commitlint/cli": "17.6.7",
    "@commitlint/config-conventional": "17.6.7",
    "@compodoc/compodoc": "1.1.21",
    "@etchteam/storybook-addon-css-variables-theme": "1.5.1",
    "@jscutlery/semver": "3.0.0",
    "@ngrx/schematics": "16.1.0",
    "@nrwl/tao": "16.5.3",
    "@nx/cypress": "16.5.3",
    "@nx/eslint-plugin": "16.5.3",
    "@nx/jest": "16.5.3",
    "@nx/js": "16.5.3",
    "@nx/linter": "16.5.3",
    "@nx/storybook": "16.5.3",
    "@nx/web": "16.5.3",
    "@nx/workspace": "16.5.3",
    "@schematics/angular": "16.1.5",
    "@sentry/cli": "2.19.4",
    "@storybook/addon-essentials": "7.1.0",
    "@storybook/addon-links": "7.1.0",
    "@storybook/angular": "7.1.0",
    "@storybook/core-server": "7.1.0",
    "@storybook/preset-scss": "1.0.3",
    "@swc-node/core": "^1.10.4",
    "@swc-node/register": "^1.6.6",
    "@tailwindcss/aspect-ratio": "0.4.2",
    "@tailwindcss/forms": "0.5.4",
    "@tailwindcss/line-clamp": "0.4.4",
    "@types/google.maps": "3.53.4",
    "@types/jest": "29.5.3",
    "@types/lodash-es": "4.17.8",
    "@types/node": "18.16.3",
    "@types/stripe-v3": "3.1.29",
    "@types/webpack": "5.28.1",
    "@typescript-eslint/eslint-plugin": "6.1.0",
    "@typescript-eslint/parser": "6.1.0",
    "ajv-formats": "2.1.1",
    "angular-http-server": "1.11.3",
    "autoprefixer": "10.4.14",
    "bamboo-jest-reporter": "1.0.3",
    "cypress": "^12.17.1",
    "dotenv": "16.3.1",
    "eslint": "8.45.0",
    "eslint-config-prettier": "8.8.0",
    "eslint-plugin-cypress": "2.13.3",
    "eslint-plugin-storybook": "^0.6.12",
    "fast-sourcemap-concat": "^2.1.1",
    "firebase-tools": "12.4.5",
    "git-describe": "4.1.1",
    "html-webpack-plugin": "^5.5.3",
    "husky": "8.0.3",
    "jest": "29.6.1",
    "jest-environment-jsdom": "29.6.1",
    "jest-preset-angular": "13.1.1",
    "ng-packagr": "~16.1.0",
    "postcss": "^8.4.26",
    "postcss-import": "~15.1.0",
    "postcss-preset-env": "^9.0.0",
    "postcss-url": "~10.1.3",
    "prettier": "2.8.8",
    "source-map-explorer": "2.5.3",
    "storybook": "7.1.0",
    "tailwindcss": "3.3.3",
    "ts-jest": "29.1.1",
    "ts-node": "10.9.1",
    "typescript": "5.1.6",
    "webpack-bundle-analyzer": "4.9.0"
  }
```

Running npx nx report also listed out a ton of my modules under `Local workspace plugins`. Took a long time to generate as we have a 2000 module Angular repo. I have not seen this before. All these modules are regular Angular modules and not Nx workspace plugins.

Here are the first 4 lines as a sample:
```
Local workspace plugins:
   	 @wink/google-tag-manager/util-priced-supplier-contract-with-acquirer-to-ga4-add-payment-info-pipe
   	 @wink/google-tag-manager/util-ranked-inventory-grid-item-list-to-ga4-view-item-list-pipe
   	 @wink/google-tag-manager/util-room-type-with-price-configurations-to-ga4-item-list-pipe
```

**Comment by bjornharvold** [comment]
Make sure to try to remove node_modules and yarn.lock and run "yarn" or "npm install" again. I can verify that 16.5.3 works fine and we have our apps running in production with that version.

**Comment by aparij** [comment]
Can confirm that downgrading @nrwl/workspace from 16.5.5 to 16.5.3 fixed the issue

**Comment by AndKiel** [comment]
The same error when using `npx lerna` to publish prerelease. Started happening a few days ago.

```
[Container] 2023/07/26 02:09:41 Running command npx lerna publish --no-commit-hooks --conventional-prerelease --include-merged-tags --yes
npm WARN exec The following package was not found and will be installed: lerna@7.1.4
lerna notice cli v7.1.4

 >  NX   Failed to parse yarn lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.

Original error: Target project does not exist: npm:typescript@5.1.6


   Error: Target project does not exist: npm:typescript@5.1.6
    at ProjectGraphBuilder.addDependency (/root/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/project-graph/project-graph-builder.js:180:19)
    at ProjectGraphBuilder.addStaticDependency (/root/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at /root/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:164:41
    at Array.forEach (<anonymous>)
    at /root/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:160:49
    at Array.forEach (<anonymous>)
    at /root/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:158:72
    at Array.forEach (<anonymous>)
    at /root/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:155:26
    at Array.forEach (<anonymous>)

lerna ERR! TypeError [ERR_INVALID_ARG_TYPE]: Failed to process the project graph with "nx-js-graph-plugin".
lerna ERR! The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
lerna ERR!     at writeFileSync (node:fs:2211:5)
lerna ERR!     at writeLastProcessedLockfileHash (/root/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/plugins/js/index.js:49:28)
lerna ERR!     at /root/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/plugins/js/index.js:25:17
lerna ERR!     at Generator.next (<anonymous>)
lerna ERR!     at /root/.npm/_npx/d5cad42883f80c04/node_modules/tslib/tslib.js:169:75
lerna ERR!     at new Promise (<anonymous>)
lerna ERR!     at Object.__awaiter (/root/.npm/_npx/d5cad42883f80c04/node_modules/tslib/tslib.js:165:16)
lerna ERR!     at Object.processProjectGraph (/root/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/plugins/js/index.js:15:57)
lerna ERR!     at /root/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/project-graph/build-project-graph.js:121:38
lerna ERR! lerna Failed to process the project graph with "nx-js-graph-plugin".
lerna ERR! lerna The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```

**Comment by aikrez** [comment]
Same issue after migration to 16.5.5

**Comment by kgadek** [comment]
We had the same problem, but only on CI. We've been able to fix that by ensuring lockfile is used:

- <details><summary>replace <code>yarn install</code> -> <code>yarn install --frozen-lockfile</code></summary>
  > If you need reproducible dependencies, which is usually the case with the continuous integration systems, you should pass `--frozen-lockfile` flag.
  — https://classic.yarnpkg.com/lang/en/docs/cli/install/
  </details>
- <details><summary>replace <code>lerna run …</code> -> <code>npx lerna run …</code></summary>
  Not sure if this was needed. This ensures that (effectively) `node_modules/.bin` is first in `$PATH`, and so a proper `lerna` is taken
  </details>

Maybe this will help somebody in making their workaround.

**Comment by bjornharvold** [comment]
Hi @kgadek 

Thank you for the suggestion.

However, I can confirm that upgrading to 16.5.5 and deleting node_modules and the yarn.lock file and then re-installing does not solve this issue.

**Comment by Choupa-web** [comment]
Hello @kgadek ,

Same here for me

**Comment by pf1gura** [comment]
I am trying to configure new nx repo with nest.js app and I am getting the same error. Downgrading nx libs to 16.5.3 works as expected.
