### ISSUE TITLE
The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by rniederer** [nrwl/nx#18293]
### Current Behavior

I want to add a new library with:

`nx generate library iot` 

to an existing nx monorepo (nx version is 16.5.5).

But all I get is this error:

```
 >  NX   The "path" argument must be of type string. Received null


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1172:7)
    at joinPathFragments (/Users/rniederer/subsidia/subsidia-web-applications/node_modules/nx/src/utils/path.js:19:31)
    at /Users/rniederer/subsidia/subsidia-web-applications/node_modules/@nx/linter/src/generators/init/init-migration.js:14:70
    at Array.forEach (<anonymous>)
    at migrateConfigToMonorepoStyle (/Users/rniederer/subsidia/subsidia-web-applications/node_modules/@nx/linter/src/generators/init/init-migration.js:11:14)
    at /Users/rniederer/subsidia/subsidia-web-applications/node_modules/@nx/linter/src/generators/lint-project/lint-project.js:92:67
    at Generator.next (<anonymous>)
    at /Users/rniederer/subsidia/subsidia-web-applications/node_modules/tslib/tslib.js:169:75
```

### Expected Behavior

A new library in the /libs folder.

### Steps to Reproduce

`nx generate library iot` 

### Nx Report

```shell
Node   : 18.15.0
   OS     : darwin-x64
   npm    : 9.5.0

   nx                 : 16.5.5
   @nx/js             : 16.5.5
   @nx/jest           : 16.5.5
   @nx/linter         : 16.5.5
   @nx/workspace      : 16.5.5
   @nx/cypress        : 16.5.5
   @nx/devkit         : 16.5.5
   @nx/eslint-plugin  : 16.5.5
   @nx/node           : 16.5.5
   @nx/react          : 16.5.5
   @nx/storybook      : 16.5.5
   @nrwl/tao          : 16.5.5
   @nx/web            : 16.5.5
   @nx/webpack        : 16.5.5
   nx-cloud           : 16.1.1
   typescript         : 4.7.4
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 3.0.0
   ---------------------------------------
```
```


### Failure Logs

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by AgentEnder** [comment]
@meeroslav I'm sending this to linter since it looks like the stack trace involves the lint change for monorepo
