### ISSUE TITLE
/typings/image.d.ts && cssmodule.d.ts not found in Vite build

### ISSUE THREAD

**Issue by seemX17** [nrwl/nx#18364]
### Current Behavior

I have migrated from create-react-app to Vite.
Running the app & build locally works fine but when I try to deploy the changes via bitbucket pipeline I get this error.

Nx version: 16.5.3

 **tsconfig.json**
```
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "allowJs": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "types": ["vite/client", "vitest"]
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ],
  "extends": "../../tsconfig.base.json"
}


```
**tsconfig.app.json**
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": ["node", "vite/client"]
  },
  "files": ["../../node_modules/@nx/react/typings/cssmodule.d.ts", "../../node_modules/@nx/react/typings/image.d.ts"],
  "exclude": [
    "src/**/*.spec.ts",
    "src/**/*.test.ts",
    "src/**/*.spec.tsx",
    "src/**/*.test.tsx",
    "src/**/*.spec.js",
    "src/**/*.test.js",
    "src/**/*.spec.jsx",
    "src/**/*.test.jsx"
  ],
  "include": ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
}

```
**tsconfig.spec.ts**

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": ["vitest/globals", "vitest/importMeta", "vite/client", "node"]
  },
  "include": [
    "vite.config.ts",
    "src/**/*.test.ts",
    "src/**/*.spec.ts",
    "src/**/*.test.tsx",
    "src/**/*.spec.tsx",
    "src/**/*.test.js",
    "src/**/*.spec.js",
    "src/**/*.test.jsx",
    "src/**/*.spec.jsx",
    "src/**/*.d.ts"
  ],
  "files": ["../../node_modules/@nx/react/typings/cssmodule.d.ts", "../../node_modules/@nx/react/typings/image.d.ts"]
}

```

**tsconfig.base.json**
```
{
  "compileOnSave": false,
  "compilerOptions": {
     "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "Node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "ESNext",
    "module": "ESNext",
    "lib": ["ES2017", "DOM", "ES2018.Promise", "ESNext"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "resolveJsonModule": true,
    "jsx": "react-jsx",
    "allowSyntheticDefaultImports": true,
    "strictNullChecks": true,
  },
  "exclude": ["node_modules", "tmp"]
}
```

### Expected Behavior

The tsconfig should be able to detect the path for typings on nodemodules 

### Steps to Reproduce

1. Create a nx  react with vite bundler application
2. Deploy using bitbucket pipeline

### Nx Report

```shell
Node   : 20.4.0
   OS     : darwin-arm64
   yarn   : 1.22.19

   nx (global)        : 16.5.3
   nx                 : 16.5.3
   @nx/js             : 16.5.3
   @nx/jest           : 16.5.3
   @nx/linter         : 16.5.3
   @nx/workspace      : 16.5.3
   @nx/cypress        : 16.5.3
   @nx/devkit         : 16.5.3
   @nx/eslint-plugin  : 16.5.3
   @nx/react          : 16.5.3
   @nrwl/tao          : 16.5.3
   @nx/vite           : 16.5.3
   @nx/web            : 16.5.3
   @nx/webpack        : 16.5.3
   nx-cloud           : 16.1.0
   typescript         : 5.1.6
```

### Failure Logs
```
error TS6053: File '/nx-wspace/node_modules/@nx/react/typings/cssmodule.d.ts' not found.
  The file is in the program because:
    Root file specified for compilation
error TS6053: File '/nx-wspace/node_modules/@nx/react/typings/image.d.ts' not found.
  The file is in the program because:
    Root file specified for compilation
Found 2 errors.
 >  NX   Found type errors. See above.
Error: Found type errors. See above.
    at validateTypes (/node_modules/@nx/vite/src/utils/executor-utils.js:28:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async viteBuildExecutor (/node_modules/@nx/vite/src/executors/build/build.impl.js:34:9)
```

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by seemX17** [comment]
The work around is to move the `.dts` entries from the `files array` to the` include array` in the `tsconfig.app.json`.
This is required only for my vite app but this config works fine with other CRA apps present in the repo.
Also the react -Vite  generators woulld include `.dts` file inside `files`

**Comment by meeroslav** [comment]
You should include types via `types` field in the form of `@nx/react/typings/...`, not using the relative path in files section.

We had to abandon the relative paths since Yarn PnP and Pnpm with PnP do not install dependencies to node_modules
