### ISSUE TITLE
Failed to parse yarn lockfile

### ISSUE THREAD

**Issue by Zamiell** [nrwl/nx#18409]
### Current Behavior

I get an error when running `npx nx run-many --target=build --all`:

```
+ npx nx run-many --target=build --all

 >  NX   Failed to parse yarn lockfile

   Please open an issue at `***://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   
Original error: Target project does not exist: npm:react-loadable@ct-loadable@npm:5.5.2


   Error: Target project does not exist: npm:react-loadable@ct-loadable@npm:5.5.2
    at ProjectGraphBuilder.addDependency (/home/runner/work/isaacscript/isaacscript/node_modules/nx/src/project-graph/project-graph-builder.js:180:19)
    at ProjectGraphBuilder.addStaticDependency (/home/runner/work/isaacscript/isaacscript/node_modules/nx/src/project-graph/project-graph-builder.js:80:[14](https://github.com/IsaacScript/isaacscript/actions/runs/5720666555/job/15500970759#step:6:15))
    at /home/runner/work/isaacscript/isaacscript/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:174:41
    at Array.forEach (<anonymous>)
    at /home/runner/work/isaacscript/isaacscript/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:170:49
    at Array.forEach (<anonymous>)
    at /home/runner/work/isaacscript/isaacscript/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:[16](https://github.com/IsaacScript/isaacscript/actions/runs/5720666555/job/15500970759#step:6:17)8:72
    at Array.forEach (<anonymous>)
    at /home/runner/work/isaacscript/isaacscript/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:165:[26](https://github.com/IsaacScript/isaacscript/actions/runs/5720666555/job/15500970759#step:6:27)
    at Array.forEach (<anonymous>)


 >  NX   Failed to process the project graph with "nx-js-graph-plugin".

   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

Error: Process completed with exit code 1.
```

### Expected Behavior

I expect nx to succeed.

I experienced this error when upgrading from nx version 15.5.3 to version 16.6.0.

### Steps to Reproduce

1. `git clone git@github.com:IsaacScript/isaacscript.git`
2. `cd isaacscript`
3. `git checkout 3e104605f562d1b1afcdaf1479fe5c3e92f4fb44`
4. `npx nx run-many --target=build --all`

### Nx Report

The `nx report` fails with the exact same error.

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by josokinas** [comment]
Same issue - with all `nx` commands, on macOS and Linux (GitLab CI).

**Comment by majies** [comment]
> Same issue. I looked around for source of this issue and in our case it seems to be related to one of docusaurus [dependencies](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus/package.json#L88C5-L88C62).
> 
> > ```
> > "react-loadable": "npm:@docusaurus/react-loadable@5.5.2",
> > ```
> 
> Apparently yarn lock parser plugin doesn't support such case and resolve version incorrectly as `ct-loadable@5.5.2`. What leads to error while building dependency tree

Thats the ticket! do we know what a possible work around for this could be?

**Comment by jakeboone02** [comment]
I'm using `lerna` to manage versions and publish packages in a monorepo. One of the workspaces is a Docusaurus site, which seems to be the cause of this issue. I know there are manual, non-lerna ways to publish the packages but it seems like I'm out of luck w/r/t lerna until this gets fixed.

Anyone know of any workarounds? I'm not opposed to using `yarn patch` for the time being.

**Comment by Zamiell** [comment]
@jakeboone02 I'm staying on nx version 15.5.3, which does not have this issue.

**Comment by jakeboone02** [comment]
> @jakeboone02 I'm staying on nx version 15.5.3, which does not have this issue.

Thanks @Zamiell, that seems to have worked (but I think you meant **_16_**.5.3 not 15).

**Comment by Zamiell** [comment]
no i did not, i meant 15.5.3

**Comment by jakeboone02** [comment]
> no i did not, i meant 15.5.3

Oh that's weird because I got errors when I used `nx@15.5.3` with `lerna@latest` but `nx@16.5.3` worked fine.

**Comment by meeroslav** [comment]
Thank you for reporting this. I will look into it as soon as possible.

**Comment by josokinas** [comment]
Looks like 16.7 has a problem still:

```
$ yarn run nx affected --target=build $NX_ARGS --parallel=2
 >  NX   Failed to parse yarn lockfile
   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   
Original error: Target project does not exist: npm:react-loadable@ct-loadable@npm:5.5.2
   Error: Target project does not exist: npm:react-loadable@ct-loadable@npm:5.5.2
    at validateCommonDependencyRules (/builds/kevineu/engineering/kevin-frontend/node_modules/nx/src/project-graph/project-graph-builder.js:285:15)
    at validateDependency (/builds/kevineu/engineering/kevin-frontend/node_modules/nx/src/project-graph/project-graph-builder.js:275:5)
    at ProjectGraphBuilder.addDependency (/builds/kevineu/engineering/kevin-frontend/node_modules/nx/src/project-graph/project-graph-builder.js:162:9)
    at ProjectGraphBuilder.addStaticDependency (/builds/kevineu/engineering/kevin-frontend/node_modules/nx/src/project-graph/project-graph-builder.js:79:14)
    at /builds/kevineu/engineering/kevin-frontend/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:174:41
    at Array.forEach (<anonymous>)
    at /builds/kevineu/engineering/kevin-frontend/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:170:49
    at Array.forEach (<anonymous>)
    at /builds/kevineu/engineering/kevin-frontend/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:168:72
    at Array.forEach (<anonymous>)
 >  NX   Failed to process the project graph with "nx-js-graph-plugin".
   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```

**Comment by TriPSs** [comment]
@meeroslav see #18435, it has a repo linked.

**Comment by meeroslav** [comment]
Thank you @TriPSs
