### ISSUE TITLE
npx create-nx-workspace --pm pnpm results in Nx failed to create a workspace.

### ISSUE THREAD

**Issue by ZeroPie** [nrwl/nx#18401]
### Current Behavior

npx create-nx-workspace --pm pnpm fails at creating a workspace

### Expected Behavior

Workspace is created

### Steps to Reproduce

1.`npx create-nx-workspace --pm pnpm`

### Nx Report

```shell
npx create-nx-workspace --pm pnpm
✔ Workspace name (e.g., org name)     · pnpm
✔ What to create in the new workspace · apps
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

 >  NX   Nx is creating your v13.10.6 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✖ Creating your workspace

 >  NX   Nx failed to create a workspace.

   Exit code: 1
   Log file: /var/folders/yw/c0jpl6r10mq8_s8gjmlbp_rc0000gn/T/tmp-21557-pjo7EsTDzRIB/error.log
```

### Failure Logs

```shell
>  NX   Unable to resolve @nx/workspace/generators.json:new.

   Cannot find module '@nx/workspace/generators.json'
   Require stack:
   - /Users/alej/Library/pnpm/store/v3/tmp/dlx-21611/node_modules/.pnpm/nx@16.6.0/node_modules/nx/src/command-line/generate/generator-utils.js
   - /Users/alej/Library/pnpm/store/v3/tmp/dlx-21611/node_modules/.pnpm/nx@16.6.0/node_modules/nx/src/command-line/new/new.js
   - /Users/alej/Library/pnpm/store/v3/tmp/dlx-21611/node_modules/.pnpm/nx@16.6.0/node_modules/nx/src/command-line/new/command-object.js
   - /Users/alej/Library/pnpm/store/v3/tmp/dlx-21611/node_modules/.pnpm/nx@16.6.0/node_modules/nx/src/command-line/nx-commands.js
   - /Users/alej/Library/pnpm/store/v3/tmp/dlx-21611/node_modules/.pnpm/nx@16.6.0/node_modules/nx/bin/init-local.js
   - /Users/alej/Library/pnpm/store/v3/tmp/dlx-21611/node_modules/.pnpm/nx@16.6.0/node_modules/nx/bin/nx.js
   Pass --verbose to see the stacktrace.


.../Library/pnpm/store/v3/tmp/dlx-21611  | Progress: resolved 1, reused 0, downloaded 0, added 0
.../Library/pnpm/store/v3/tmp/dlx-21611  | Progress: resolved 31, reused 22, downloaded 0, added 0
.../Library/pnpm/store/v3/tmp/dlx-21611  | Progress: resolved 46, reused 37, downloaded 0, added 0
.../Library/pnpm/store/v3/tmp/dlx-21611  | Progress: resolved 96, reused 86, downloaded 0, added 0
.../Library/pnpm/store/v3/tmp/dlx-21611  | Progress: resolved 132, reused 123, downloaded 0, added 0
.../Library/pnpm/store/v3/tmp/dlx-21611  | +124 ++++++++++++
.../Library/pnpm/store/v3/tmp/dlx-21611  | Progress: resolved 133, reused 124, downloaded 0, added 124, done
 ERROR  Command failed with exit code 1: nx new pnpm --pm=pnpm --packageManager=pnpm --no-allPrompts --no-a --/bin/sh=/Users/alej/.npm/_npx/d2207cf76adb22dc/node_modules/.bin/create-nx-workspace --name=pnpm --preset=apps --appName= --no-nxCloud --defaultBase=main --collection=@nrwl/workspace/generators.json --cli=nx --nxWorkspaceRoot=/Users/alej/Workspace

pnpm: Command failed with exit code 1: nx new pnpm --pm=pnpm --packageManager=pnpm --no-allPrompts --no-a --/bin/sh=/Users/alej/.npm/_npx/d2207cf76adb22dc/node_modules/.bin/create-nx-workspace --name=pnpm --preset=apps --appName= --no-nxCloud --defaultBase=main --collection=@nrwl/workspace/generators.json --cli=nx --nxWorkspaceRoot=/Users/alej/Workspace
    at makeError (/Users/alej/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:24890:17)
    at handlePromise (/Users/alej/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:25461:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/Users/alej/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:210334:7)
    at async /Users/alej/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:219737:21
    at async main (/Users/alej/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:219704:34)
    at async runPnpm (/Users/alej/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:219960:5)
    at async /Users/alej/.volta/tools/image/packages/pnpm/lib/node_modules/pnpm/dist/pnpm.cjs:219952:7
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ZeroPie** [comment]
The cache was causing problems:
The following fixed it :)
```rm -rf ~/.npm/_npx```

The following did also work:
npx create-nx-workspace@latest --pm pnpm
pnpm dlx create-nx-workspace --pm pnpm
