### ISSUE TITLE
Cannot create bazel workspace

### ISSUE THREAD

**Issue by alyalin** [nrwl/nx#1845]
## Expected Behavior

Workspace with Angular and Bazel

## Current Behavior

Errors about unknown options: Angular & Bazel

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npm i -g  create-nx-workspace@latest`
2. `npx create-nx-workspace@latest myproject --preset angular --bazel`

### Context

Please provide any relevant information about your setup:

- node 12.9.0
- os x 10.14.6

### Failure Logs

```
➜  web npx create-nx-workspace --preset angular --bazel
? Workspace name (e.g., org name)     myworkspace
? Application name                    cars
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
Creating a sandbox with Nx...
added 333 packages from 217 contributors and audited 3114 packages in 11.552s
found 0 vulnerabilities

new myworkspace "angular" "--bazel" --preset="angular" --appName="cars" --style="scss" --collection=@nrwl/workspace
Unknown option: 'angular'
Unknown option: '--bazel'
(node:9377) UnhandledPromiseRejectionWarning: Error: Command failed: "/var/folders/dv/tnvx48h50sb31kc3j1qf6tm00000gp/T/tmp-9377beolswOhK8RE/node_modules/.bin/ng" new myworkspace "angular" "--bazel" --preset="angular" --appName="cars" --style="scss" --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at createApp (/usr/local/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:345:21)
    at /usr/local/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:64:21
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:9377) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9377) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Other

Read the guide about creating bazel workspace in your blog (https://blog.nrwl.io/introduction-to-nrwl-bazel-schematics-c391911a5e9f)

**Comment by hql287** [comment]
Can confirm this as well.

**Comment by vsavkin** [comment]
The bazel support was very experimental and ended up not being practical.

We are trying to add it in a different way (we are a lot more optimistic this time). Read more here:
https://blog.nrwl.io/nx-%EF%B8%8F-bazel-release-plans-eaed5bbaa3ba
