### ISSUE TITLE
Expo app build fail with after upgrading to expo sdk 49 and react native 0.72.3

### ISSUE THREAD

**Issue by rranjan14** [nrwl/nx#18517]
### Current Behavior

running command `eas build --platform android --profile preview --local` to locally build the app, failing on `Cannot resolve http` on expo version `49.0.6` with react native `0.72.3`.

Build fails after logging `[Nx] Unable to resolve with default PNPM resolver: http. Expo app build fail.`

`eas.json`
```
{
  "build": {
    "production": {
      "android": {
        "buildType": "app-bundle"
      }
    },
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      }
    },
    "preview": {
      "distribution": "internal",
      "ios": {
        "simulator": true
      },
      "android": {
        "buildType": "apk"
      }
    }
  },
  "submit": {
    "production": {}
  },
  "cli": {
    "version": ">=3.15.1"
  }
}
```

### Expected Behavior

The apk file or aab file should build to without fail.

### Steps to Reproduce

1. Create a new nx workspace
2. Create an expo app.
3. Setup eas
4. Run `eas build --platform android --profile preview --local`
5. Build fails

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : darwin-arm64
   yarn   : 3.6.1
   
   nx (global)        : 16.6.0
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/detox          : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/expo           : 16.6.0
   @nx/react          : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/vite           : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
   	 @xyz/interfaces
   	 xyz-web
   	 api-server
   	 @xyz/logger
   	 @xyz/store
   	 @xyz/api
   	 @xyz/sdk
   	 mobile
   	 @xyz/ui
   	 xyz-webapp
```

### Failure Logs

```shell
[RUN_GRADLEW] [Nx] Unable to resolve with default PNPM resolver: http
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets FAILED
[RUN_GRADLEW] Error: Cannot resolve http
[RUN_GRADLEW] Error: Cannot resolve http
[RUN_GRADLEW]     at /private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/@nx/expo/plugins/metro-resolver.js:31:15
[RUN_GRADLEW]     at resolveRequest (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/@expo/cli/build/src/start/server/metro/withMetroResolvers.js:50:24)
[RUN_GRADLEW]     at Object.resolve (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro-resolver/src/resolve.js:47:12)
[RUN_GRADLEW]     at ModuleResolver.resolveDependency (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:79:31)
[RUN_GRADLEW]     at DependencyGraph.resolveDependency (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
[RUN_GRADLEW]     at Object.resolve (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro/src/lib/transformHelpers.js:169:21)
[RUN_GRADLEW]     at Graph._resolveDependencies (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
[RUN_GRADLEW]     at Graph._processModule (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
[RUN_GRADLEW]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[RUN_GRADLEW]     at async Graph._addDependency (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
[RUN_GRADLEW]     at async Promise.all (index 5)
[RUN_GRADLEW]     at async Graph._processModule (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
[RUN_GRADLEW]     at async Graph._addDependency (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
[RUN_GRADLEW]     at async Promise.all (index 5)
[RUN_GRADLEW]     at async Graph._processModule (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
[RUN_GRADLEW]     at async Graph._addDependency (/private/var/folders/dx/4kgfgdss33xc70xbk7cn19mr0000gn/T/eas-build-local-nodejs/2a063021-982e-4643-9453-2e92b9e1dda4/build/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
[RUN_GRADLEW] w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
[RUN_GRADLEW] 868 actionable tasks: 868 executed
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets'.
[RUN_GRADLEW] > Process 'command 'node'' finished with non-zero exit value 1
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 2m 33s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by rranjan14** [comment]
Update:
Removing `unstable_enableSymlinks: true` and `unstable_enablePackageExports:true` leads to successful build.

**Comment by ethras** [comment]
facing the same issue when trying to import a workspace js library

```[Nx] Unable to resolve with default PNPM resolver: http.```

tried removing the unstable field but no luck
