### ISSUE TITLE
findOriginalKeys is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by janantala** [nrwl/nx#18567]
### Current Behavior

I get this error when building

```
NX_VERBOSE_LOGGING=true nx build coupons-tf-migrate --runner=local --skip-nx-cache

> nx run coupons-tf-migrate:build


 >  NX   An error occured while creating pruned lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.
   
Original error: findOriginalKeys is not a function or its return value is not iterable


   TypeError: findOriginalKeys is not a function or its return value is not iterable
    at /Users/janantala/github/simplicity/sim-draco-dwarf/sim-nx-monorepo/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:190:41
    at Array.forEach (<anonymous>)
    at mapSnapshots (/Users/janantala/github/simplicity/sim-draco-dwarf/sim-nx-monorepo/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:189:26)
    at stringifyYarnLockfile (/Users/janantala/github/simplicity/sim-draco-dwarf/sim-nx-monorepo/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:131:23)
    at createLockFile (/Users/janantala/github/simplicity/sim-draco-dwarf/sim-nx-monorepo/node_modules/nx/src/plugins/js/lock-file/lock-file.js:132:60)
    at /Users/janantala/github/simplicity/sim-draco-dwarf/sim-nx-monorepo/node_modules/@nrwl/webpack/src/plugins/generate-package-json-plugin.js:43:131
    at fn (/Users/janantala/github/simplicity/sim-draco-dwarf/sim-nx-monorepo/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/Users/janantala/github/simplicity/sim-draco-dwarf/sim-nx-monorepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/Users/janantala/github/simplicity/sim-draco-dwarf/sim-nx-monorepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/Users/janantala/github/simplicity/sim-draco-dwarf/sim-nx-monorepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)

asset yarn.lock 700 KiB [emitted] [big]
asset main.js 35.6 KiB [emitted] (name: main) 1 related asset
asset package.json 710 bytes [emitted]
asset assets/.gitkeep 0 bytes [emitted] [from: src/assets/.gitkeep] [copied]
  
webpack 5.88.2 compiled successfully (08b2d07eb3d3021d)

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project coupons-tf-migrate
```

devDependencies
```
"nx": "15.9.4",
"@nrwl/cli": "15.9.4",
"@nrwl/devkit": "15.9.4",
"@nrwl/eslint-plugin-nx": "15.9.4",
"@nrwl/jest": "15.9.4",
"@nrwl/linter": "15.9.4",
"@nrwl/node": "15.9.4",
"@nrwl/webpack": "15.9.4",
"@nrwl/workspace": "15.9.4",
```

### Expected Behavior

Build without error

### Steps to Reproduce

1. ```NX_VERBOSE_LOGGING=true nx build coupons-tf-migrate --runner=local --skip-nx-cache```

### Nx Report

```shell
nx report
(node:18257) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/janantala/github/simplicity/sim-draco-dwarf/sim-nx-monorepo/node_modules/@opensearch-project/opensearch/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

 >  NX   Report complete - copy this into the issue template

   Node : 16.20.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx (global)             : 16.6.0
   nx                      : 15.9.4
   @nrwl/js                : 15.9.4
   @nrwl/jest              : 15.9.4
   @nrwl/linter            : 15.9.4
   @nrwl/workspace         : 15.9.4
   @nrwl/cli               : 15.9.4
   @nrwl/devkit            : 15.9.4
   @nrwl/eslint-plugin-nx  : 15.9.4
   @nrwl/node              : 15.9.4
   @nrwl/tao               : 15.9.4
   @nrwl/webpack           : 15.9.4
   @nrwl/nx-cloud          : 16.0.5
   typescript              : 4.9.5
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Can you please try with the latest version, since there were some fixes lately for yarn lock file parsing that might have fixed your issue.

If that doesn't help please provide a minimal repo. In order to debug this we need to know which package is causing the `findOriginalKeys` to break and what does your lock file look like.

**Comment by meeroslav** [comment]
Looking at your command again, I can see that your local version is `15.9.4` but you run the command as `nx ...` which would trigger the global one (`16.6.0`).

In order to match nx command to your local version prepend the `nx` command with package manager-specific command:
```bash
npx nx
# or
yarn nx 
# or
pnpm nx
```
