### ISSUE TITLE
failure to create angular-nest workspace

### ISSUE THREAD

**Issue by beckend** [nrwl/nx#1857]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

angular-nest applications is created without errors.

## Current Behavior

angular-nest with certain choices is not created correctly.

## Failure Information (for bugs)

```shell
Schematic input does not validate against the Schema: {"name":"js-backend","inlineStyle":false,"inlineTemplate":false,"prefix":"javascript-universal","skipTests":false,"style":"@emotion/styled","enableIvy":false,"routing":false,"skipInstall":true,"skipPackageJson":false}
Errors:

  Data path ".style" should be equal to one of the allowed values.
Workspace creation failed, see above.
(node:6190) UnhandledPromiseRejectionWarning: Error: Command failed: "/tmp/tmp-6190GeNqZTaNowpf/node_modules/.bin/ng" new javascript-universal --preset="angular-nest" --appName="js-backend" --style="@emotion/styled" --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at createApp (/home/linken/.npm/_npx/6190/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:345:21)
    at /home/linken/.npm/_npx/6190/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:64:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

```shell
npx create-nx-workspace javascript-universal
```

* Type/pick -> angular-nest -> js-backend

### Context

- nx 8.5.0
- arch linux
- node 12.10.0
- npm 6.11.3

### Failure Logs

```shell
$ npx create-nx-workspace javascript-universal
npx: installed 164 in 7.34s
? What to create in the new workspace angular-nest      [a workspace with a full stack application (Angular + Nest)]
? Application name                    js-backend
? Default stylesheet format           emotion           [ https://emotion.sh]
Creating a sandbox with Nx...
new javascript-universal --preset="angular-nest" --appName="js-backend" --style="@emotion/styled" --collection=@nrwl/workspace
CREATE javascript-universal/nx.json (211 bytes)
CREATE javascript-universal/tsconfig.json (509 bytes)
CREATE javascript-universal/README.md (2715 bytes)
CREATE javascript-universal/.editorconfig (245 bytes)
CREATE javascript-universal/.gitignore (503 bytes)
CREATE javascript-universal/.prettierignore (74 bytes)
CREATE javascript-universal/.prettierrc (26 bytes)
CREATE javascript-universal/angular.json (96 bytes)
CREATE javascript-universal/package.json (1259 bytes)
CREATE javascript-universal/apps/.gitkeep (1 bytes)
CREATE javascript-universal/libs/.gitkeep (0 bytes)
CREATE javascript-universal/tools/tsconfig.tools.json (218 bytes)
CREATE javascript-universal/tools/schematics/.gitkeep (0 bytes)
CREATE javascript-universal/.vscode/extensions.json (164 bytes)

> core-js@2.6.9 postinstall /home/linken/tmp/Coding/github/javascript-universal/node_modules/babel-runtime/node_modules/core-js
> node scripts/postinstall || echo "ignore"


> core-js@3.2.1 postinstall /home/linken/tmp/Coding/github/javascript-universal/node_modules/core-js
> node scripts/postinstall || echo "ignore"


> @angular/cli@8.3.3 postinstall /home/linken/tmp/Coding/github/javascript-universal/node_modules/@angular/cli
> node ./bin/postinstall/script.js


> @nrwl/angular@8.5.0 postinstall /home/linken/tmp/Coding/github/javascript-universal/node_modules/@nrwl/angular
> node ./scripts/nx-cli-warning.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fork-ts-checker-webpack-plugin/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@angular/compiler-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@angular-devkit/build-angular/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1181 packages from 560 contributors and audited 31011 packages in 16.004s
found 0 vulnerabilities

Schematic input does not validate against the Schema: {"name":"js-backend","inlineStyle":false,"inlineTemplate":false,"prefix":"javascript-universal","skipTests":false,"style":"@emotion/styled","enableIvy":false,"routing":false,"skipInstall":true,"skipPackageJson":false}
Errors:

  Data path ".style" should be equal to one of the allowed values.
Workspace creation failed, see above.
(node:6190) UnhandledPromiseRejectionWarning: Error: Command failed: "/tmp/tmp-6190GeNqZTaNowpf/node_modules/.bin/ng" new javascript-universal --preset="angular-nest" --appName="js-backend" --style="@emotion/styled" --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at createApp (/home/linken/.npm/_npx/6190/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:345:21)
    at /home/linken/.npm/_npx/6190/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:64:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:6190) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6190) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by beckend** [comment]
I am bit unsure if this belongs here since it is indeed angular related, you may close if it is, I do however think that users should be able to find this if they are having the same problem.

**Comment by jdpearce** [comment]
Thanks for raising this issue, @beckend! It looks to me like the our `@nrwl/angular:applicaiton` schematic doesn't have support for `emotion`, so this is actually our problem. 😞

**Comment by mehrad-rafigh** [comment]
Hi @beckend @jdpearce 
I filed an issue. You can follow it [here](https://github.com/nrwl/nx/issues/1773). This would be quite easy to fix and @vsavkin added the community flag to it. I thought someone might grab it, because its a perfect fit for first time contribution towards NX.

**Comment by beckend** [comment]
@mehrad-rafigh thanks, should I leave this open or close this? This title is much easier than the other to find.

**Comment by jdpearce** [comment]
I'll mark this as duplicate and close. Thanks @mehrad-rafigh, I hadn't seen the other issue.

**Comment by mehrad-rafigh** [comment]
You guys are very welcome :)
