### ISSUE TITLE
nx host using serve cannot running : Error : Invalid buildTarget

### ISSUE THREAD

**Issue by AndiKusnadi** [nrwl/nx#18697]
### Current Behavior

i used
"@nx/angular": "16.7.1",
"@angular/cli": "~16.2.0",with the following 2 project, host => enterprise, remote => login,
for Login : npx nx run login:serve --configuration=development
running well in port 4201
for Host : >npx nx run enterprise:serve --configuration=development  --verbosebut i got this error,
D:\temp\testaja4\fxdx\node_modules\@nx\angular\src\builders\module-federation-dev-server\module-federation-dev-server.impl.js:68
                throw new Error(`Remote '${remote}' failed to serve correctly due to the following: \r\n${err.toString()}`);
                      ^Error: Remote 'login' failed to serve correctly due to the following:
Error: Invalid buildTarget: login:build:development
    at D:\temp\testaja4\fxdx\node_modules\@nx\angular\src\builders\module-federation-dev-server\module-federation-dev-server.impl.js:68:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)Node.js v18.17.1

### Expected Behavior

The host should be running well. but it show error and not running. 
![image](https://github.com/nrwl/nx/assets/53073262/5908eb48-caea-434c-a801-1ffa44e49337)
[fxdx.zip](https://github.com/nrwl/nx/files/12375375/fxdx.zip)

### Steps to Reproduce

1. first install angular mono repo from nx
2. delete the first project
3. make new project host with the name enterprise
4. make new project remote with the name login
5. running host and remote (login).

### Nx Report

```shell
D:\temp\testaja6\fxdx\node_modules\@nx\angular\src\builders\module-federation-dev-server\module-federation-dev-server.impl.js:68
                throw new Error(`Remote '${remote}' failed to serve correctly due to the following: \r\n${err.toString()}`);
                      ^

Error: Remote 'login' failed to serve correctly due to the following:
Error: Invalid buildTarget: login:build:development
    at D:\temp\testaja6\fxdx\node_modules\@nx\angular\src\builders\module-federation-dev-server\module-federation-dev-server.impl.js:68:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.1
```

### Failure Logs

```shell
D:\temp\testaja4\fxdx\node_modules\@nx\angular\src\builders\module-federation-dev-server\module-federation-dev-server.impl.js:68
                throw new Error(`Remote '${remote}' failed to serve correctly due to the following: \r\n${err.toString()}`);
                      ^Error: Remote 'login' failed to serve correctly due to the following:
Error: Invalid buildTarget: login:build:development
    at D:\temp\testaja4\fxdx\node_modules\@nx\angular\src\builders\module-federation-dev-server\module-federation-dev-server.impl.js:68:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)Node.js v18.17.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by LayZeeDK** [comment]
Confirmed that this bug is present in Nx 16.7.1 but not in Nx 16.6.0.

The build targets are neither invalid nor failing.

**Comment by LayZeeDK** [comment]
Assign @Coly010

**Comment by Coly010** [comment]
I can't reproduce this on windows with nx version `16.7.3`.

Can you try again with the latest version of nx?

`nx migrate latest && nx migrate --run-migrations`

**Comment by rbirkgit** [comment]
My colleague says 16.7.3 works for him now. It didn't with 16.7.1

**Comment by Coly010** [comment]
Awesome :) In that case all you need to do is migrate to that version!
