### ISSUE TITLE
Nx failed to create a workspace when use option `--pm pnpm`

### ISSUE THREAD

**Issue by zhangfisher** [nrwl/nx#18696]
### Current Behavior

Nx failed to create a workspace.

### Expected Behavior

Successfully created workspace

### Steps to Reproduce

1.  npm config set registry https://registry.npm.taobao.org
2. run `npx create-nx-workspace@latest package-based --preset=npm --pm pnpm`

### Nx Report

```shell
>  NX   Unable to resolve @nx/workspace/generators.json:new.

   Cannot find module '@nx/workspace/generators.json'
   Require stack:
   - C:\Users\Administrator\AppData\Local\pnpm\store\v3\tmp\dlx-50184\node_modules\.pnpm\nx@16.7.1\node_modules\nx\src\command-line\generate\generator-utils.js
   - C:\Users\Administrator\AppData\Local\pnpm\store\v3\tmp\dlx-50184\node_modules\.pnpm\nx@16.7.1\node_modules\nx\src\command-line\new\new.js
   - C:\Users\Administrator\AppData\Local\pnpm\store\v3\tmp\dlx-50184\node_modules\.pnpm\nx@16.7.1\node_modules\nx\src\command-line\new\command-object.js
   - C:\Users\Administrator\AppData\Local\pnpm\store\v3\tmp\dlx-50184\node_modules\.pnpm\nx@16.7.1\node_modules\nx\src\command-line\nx-commands.js
   - C:\Users\Administrator\AppData\Local\pnpm\store\v3\tmp\dlx-50184\node_modules\.pnpm\nx@16.7.1\node_modules\nx\bin\init-local.js
   - C:\Users\Administrator\AppData\Local\pnpm\store\v3\tmp\dlx-50184\node_modules\.pnpm\nx@16.7.1\node_modules\nx\bin\nx.js
   Pass --verbose to see the stacktrace.


.../Local/pnpm/store/v3/tmp/dlx-50184    | Progress: resolved 1, reused 0, downloaded 0, added 0
.../Local/pnpm/store/v3/tmp/dlx-50184    | Progress: resolved 133, reused 123, downloaded 0, added 0
.../Local/pnpm/store/v3/tmp/dlx-50184    | +124 ++++++++++++
.../Local/pnpm/store/v3/tmp/dlx-50184    | Progress: resolved 133, reused 124, downloaded 0, added 2
.../Local/pnpm/store/v3/tmp/dlx-50184    | Progress: resolved 133, reused 124, downloaded 0, added 43
.../Local/pnpm/store/v3/tmp/dlx-50184    | Progress: resolved 133, reused 124, downloaded 0, added 88
.../Local/pnpm/store/v3/tmp/dlx-50184    | Progress: resolved 133, reused 124, downloaded 0, added 124, done
 ERROR  Command failed with exit code 1: nx new voerkacloud --pm=pnpm --packageManager=pnpm --preset=npm --no-allPrompts --no-a --$0=C:\Users\Administrator\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\index.js --name=voerkacloud --appName= --no-nxCloud --defaultBase=master --collection=@nrwl/workspace/generators.json --cli=nx --nxWorkspaceRoot=E:/Work/Code/sources

pnpm: Command failed with exit code 1: nx new voerkacloud --pm=pnpm --packageManager=pnpm --preset=npm --no-allPrompts --no-a --$0=C:\Users\Administrator\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\index.js --name=voerkacloud --appName= --no-nxCloud --defaultBase=master --collection=@nrwl/workspace/generators.json --cli=nx --nxWorkspaceRoot=E:/Work/Code/sources
    at makeError (C:\Users\Administrator\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.6.11\node_modules\pnpm\dist\pnpm.cjs:24890:17)
    at handlePromise (C:\Users\Administrator\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.6.11\node_modules\pnpm\dist\pnpm.cjs:25461:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (C:\Users\Administrator\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.6.11\node_modules\pnpm\dist\pnpm.cjs:210334:7)
    at async C:\Users\Administrator\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.6.11\node_modules\pnpm\dist\pnpm.cjs:219737:21
    at async main (C:\Users\Administrator\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.6.11\node_modules\pnpm\dist\pnpm.cjs:219704:34)
    at async runPnpm (C:\Users\Administrator\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.6.11\node_modules\pnpm\dist\pnpm.cjs:219960:5)
    at async C:\Users\Administrator\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.6.11\node_modules\pnpm\dist\pnpm.cjs:219952:7
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

but run `pnpx create-nx-workspace@latest package-based --preset=npm --pm pnpm` is successfully created workspace!

**Comment by FrozenPandaz** [comment]
I think that registry doesn't get all of the package versions at the same time sometimes. Can you try with an older version when you run into this issue?

I tried with `16.7.4` and it worked.
