### ISSUE TITLE
Setting up for Storybook not working

### ISSUE THREAD

**Issue by hornta** [nrwl/nx#18725]
### Current Behavior

I'm following the instructions at https://nx.dev/packages/storybook but when I run this command `npx nx g @nx/storybook:configuration project-name` it fails with this error message `NX   Cannot convert undefined or null to object`

```
PS C:\git\todoapp> npx nx g @nx/storybook:configuration frontend --verbose

>  NX  Generating @nx/storybook:configuration

√ Do you want to set up Storybook interaction tests? (Y/n) · false
√ Choose the Storybook framework that you need to use. · @storybook/react-vite

 >  NX   Cannot convert undefined or null to object


TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at updateLintConfig (C:\git\todoapp\node_modules\@nx\storybook\src\generators\configuration\lib\util-functions.js:260:34)
    at C:\git\todoapp\node_modules\@nx\storybook\src\generators\configuration\configuration.js:55:47
    at Generator.next (<anonymous>)
    at fulfilled (C:\git\todoapp\node_modules\tslib\tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected Behavior

-

### Steps to Reproduce

1.

### Nx Report

```shell
PS C:\git\todoapp> npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.1
   OS     : win32-x64
   npm    : 9.5.1

   nx          : 16.7.1
   @nrwl/tao   : 16.7.1
   typescript  : 5.1.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
@hornta hey, thanks for filing an issue! It seems that you do not have a `targets` object in your project's `project.json`. If you add a `targets` object, then it will work. I will make sure we catch that in the code!
