### ISSUE TITLE
Issue migrating Angular project v14->v15

### ISSUE THREAD

**Issue by gs-scooter** [nrwl/nx#18772]
### Current Behavior

Nx migration is failing at `update-tsconfig-target`.

### Expected Behavior

Migration completes successfully.

### Steps to Reproduce

1. Run `nx migrate --run-migrations`

### Nx Report

```shell
$ npx nx report

 >  NX   Cannot convert undefined or null to object


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

### Failure Logs

```shell
>  NX   Running migrations from 'migrations.json'


 >  NX   Failed to run update-tsconfig-target from @nrwl/angular. This workspace is NOT up to date!


 >  NX   Cannot convert undefined or null to object


TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at mapPackages (C:\Users\jrosenbaum\dev\rapter\node_modules\nx\src\utils\lock-file\npm.js:24:12)
    at parseNpmLockFile (C:\Users\jrosenbaum\dev\rapter\node_modules\nx\src\utils\lock-file\npm.js:15:23)
    at parseLockFile (C:\Users\jrosenbaum\dev\rapter\node_modules\nx\src\utils\lock-file\lock-file.js:68:43)
    at C:\Users\jrosenbaum\dev\rapter\node_modules\nx\src\project-graph\build-project-graph.js:61:109
    at Generator.next (<anonymous>)
    at C:\Users\jrosenbaum\dev\rapter\node_modules\tslib\tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\jrosenbaum\dev\rapter\node_modules\tslib\tslib.js:165:16)
    at buildProjectGraphUsingProjectFileMap (C:\Users\jrosenbaum\dev\rapter\node_modules\nx\src\project-graph\build-project-graph.js:34:20)
Command failed: npx nx _migrate --run-migrations --verbose
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please provide more specific reproduction steps so we can troubleshoot this (or provide a repo if possible):

- How to get to the state before migrating (create workspace flow, install extra deps, add/update files that are needed to reproduce the issue, etc).
- Command run to generate migrations (nx migrate xxx)
- `nx migrate --run-migrations` <= this was the only step provided
