### ISSUE TITLE
Running NX workflow in github failed

### ISSUE THREAD

**Issue by normanaranez** [nrwl/nx#18818]
name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Environment Variables
        run: |
          echo "NX_BASE=${{ github.event.before }}" >> $GITHUB_ENV
          echo "NX_HEAD=${{ github.sha }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master
      - run: npm install
      - run: npm ci

      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 --configuration=ci
      - run: npx nx affected -t build --parallel=3
      - run: npx nx run prisma:migrate
      - run: npx nx run prisma:generate

Run npx nx affected -t lint --parallel=3
  

 >  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: 6451d4318921d6ea2cfdd29db0bc685d1d[7](https://github.com/normanaranez/nx-todos/actions/runs/5964467146/job/16179725156#step:7:7)cde62

 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: [8](https://github.com/normanaranez/nx-todos/actions/runs/5964467146/job/16179725156#step:7:9)da42aaec44638aaf3fccf2d3f317f0b3[9](https://github.com/normanaranez/nx-todos/actions/runs/5964467146/job/16179725156#step:7:10)ccbf51

 >  NX   Failed to parse pnpm lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   
Original error: Could not find ".modules.yaml" at "/home/runner/work/nx-todos/nx-todos/node_modules/.modules.yaml"

   Error: Could not find ".modules.yaml" at "/home/runner/work/nx-todos/nx-todos/node_modules/.modules.yaml"
    at loadPnpmHoistedDepsDefinition (/home/runner/work/nx-todos/nx-todos/node_modules/nx/src/plugins/js/lock-file/utils/pnpm-normalizer.js:25:[15](https://github.com/normanaranez/nx-todos/actions/runs/5964467146/job/16179725156#step:7:16))
    at addNodes (/home/runner/work/nx-todos/nx-todos/node_modules/nx/src/plugins/js/lock-file/pnpm-parser.js:51:77)
    at parsePnpmLockfile (/home/runner/work/nx-todos/nx-todos/node_modules/nx/src/plugins/js/lock-file/pnpm-parser.js:13:5)
    at parseLockFile (/home/runner/work/nx-todos/nx-todos/node_modules/nx/src/plugins/js/lock-file/lock-file.js:79:49)
    at /home/runner/work/nx-todos/nx-todos/node_modules/nx/src/plugins/js/index.js:25:64
    at Generator.next (<anonymous>)
    at /home/runner/work/nx-todos/nx-todos/node_modules/tslib/tslib.js:[16](https://github.com/normanaranez/nx-todos/actions/runs/5964467146/job/16179725156#step:7:17)9:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/runner/work/nx-todos/nx-todos/node_modules/tslib/tslib.js:165:16)
    at Object.processProjectGraph (/home/runner/work/nx-todos/nx-todos/node_modules/nx/src/plugins/js/index.js:16:57)

 >  NX   Failed to process the project graph with "nx-js-graph-plugin".

   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

**Comment by FrozenPandaz** [comment]
Is there a `pnpm-lock.yml` in your workspace? If so, you should use `pnpm` to install on CI.

If not, you should remove that file.
