### ISSUE TITLE
Migration failure: `'.' is not recognized as an internal or external command` or `The "path" argument must be of type string. Received type object`

### ISSUE THREAD

**Issue by wKovacs64** [nrwl/nx#1882]
## Expected Behavior

I would expect `nx migrate @nrwl/workspace` to succeed.

## Current Behavior

`nx migrate @nrwl/workspace` errors (failure logs below).

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a new Nx workspace (select `empty` and `Nx`)
2. Change to the new workspace directory
3. Run `nx migrate @nrwl/workspace`

### Context

- Starting with `8.5.0` or `8.5.1` Nx workspace
- `@nrwl/cli@8.5.1`

#### Windows

```sh
$ nx migrate @nrwl/workspace
'.' is not recognized as an internal or external command,
operable program or batch file.
C:\dev\test\nx-scoped-imports\node_modules\yargs\yargs.js:1133
      else throw err
           ^

Error: Command failed: ./node_modules/.bin/tao migrate @nrwl/workspace
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.exports.commandsObject.yargs.usage.command.command.command.command.command.command.command.command.command.command.command.command.command.alias.command.command.command [as handler] (C:\dev\test\nx-scoped-imports\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:83:21)
    at Object.runCommand (C:\dev\test\nx-scoped-imports\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\dev\test\nx-scoped-imports\node_modules\yargs\yargs.js:1046:30)
    at Object.get [as argv] (C:\dev\test\nx-scoped-imports\node_modules\yargs\yargs.js:989:21)
    at Object.<anonymous> (C:\dev\test\nx-scoped-imports\node_modules\@nrwl\cli\bin\nx.js:40:26)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

#### Linux

```sh
$ nx migrate @nrwl/workspace
The "path" argument must be of type string. Received type object
/home/dev/nx-migrate-test/node_modules/yargs/yargs.js:1133
      else throw err
           ^

Error: Command failed: ./node_modules/.bin/tao migrate @nrwl/workspace
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.exports.commandsObject.yargs.usage.command.command.command.command.command.command.command.command.command.command.command.command.command.alias.command.command.command [as handler] (/home/dev/nx-migrate-test/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:83:21)
    at Object.runCommand (/home/dev/nx-migrate-test/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/dev/nx-migrate-test/node_modules/yargs/yargs.js:1046:30)
    at Object.get [as argv] (/home/dev/nx-migrate-test/node_modules/yargs/yargs.js:989:21)
    at Object.<anonymous> (/home/dev/nx-migrate-test/node_modules/@nrwl/cli/bin/nx.js:40:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

**Comment by jdpearce** [comment]
Thanks for raising this issue, @wKovacs64, looks like this is down to a typo - `.migration` should be `.migrations` : 

https://github.com/nrwl/nx/blob/dca7934aec2f40bee5f0a58a9bb042c0fb4f09ce/packages/tao/src/commands/migrate.ts#L293-L296

This could be a quick PR, although I haven't yet looked at the tests to see if adding one to cover this case would be trivial or not.

**Comment by vsavkin** [comment]
Fixed it in here: https://github.com/nrwl/nx/commit/5bb12dc4afa98c2a0da3497e7b661254efe0ab29.

The 8.5.2 release has the fix.

**Comment by wKovacs64** [comment]
Thanks!

**Comment by AsimNet** [comment]
@nrwl/cli@9.2.2
`nx -- migrate @nrwl/workspace` produces this error:

```
> nx "migrate" "@nrwl/workspace"

'.\node_modules\.bin\tao' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Asim\Documents\Asim\node_modules\@nrwl\workspace\node_modules\yargs\yargs.js:1109
      else throw err
           ^

Error: Command failed: .\node_modules\.bin\tao migrate @nrwl/workspace
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:658:15)
    at Object.handler (C:\Users\Asim\Documents\Asim\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:76:21)
    at Object.runCommand (C:\Users\Asim\Documents\Asim\node_modules\@nrwl\workspace\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\Asim\Documents\Asim\node_modules\@nrwl\workspace\node_modules\yargs\yargs.js:1022:30)
    at Object.get [as argv] (C:\Users\Asim\Documents\Asim\node_modules\@nrwl\workspace\node_modules\yargs\yargs.js:965:21)
    at Object.initLocal (C:\Users\Asim\Documents\Asim\node_modules\@nrwl\cli\lib\init-local.js:20:79)
    at Object.<anonymous> (C:\Users\Asim\Documents\Asim\node_modules\@nrwl\cli\bin\nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 414388,
  stdout: null,
  stderr: null
}
```

Win10

**Comment by jdpearce** [comment]
@AsimNet If this is a continuing problem, can you raise this as a separate issue, please?

If you're getting problems with 9.0.0 you can always upgrade to the latest version and then use this to generate the migrations:

`nx migrate 9.2.2 --from="@nrwl/workspace@9.0.0"`
