### ISSUE TITLE
No such file or directory (os error 2) if a project has a file with a broken symlink

### ISSUE THREAD

**Issue by Tom910** [nrwl/nx#18830]
### Current Behavior

If a project has [bad symlinks](https://github.com/Tom910/nx-cache-symlink-problem/blob/main/apps/test-app/internal-staff/COMMIT) without correct path to file. NX will have an error `No such file or directory (os error 2)`
It happenes because Rust code throw an error https://github.com/nrwl/nx/blob/master/packages/nx/src/native/cache/file_ops.rs#L15-L33

### Expected Behavior

Files with bad symlinks will be skipped or copy without exceptions

### GitHub Repo

https://github.com/Tom910/nx-cache-symlink-problem

### Steps to Reproduce

1. Clone https://github.com/Tom910/nx-cache-symlink-problem
2. npm i
3. Run `nx build test-app --verbose`
4 Optional: if you don't have an error, remove a file /tmp/COMMIT

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-arm64
   npm    : 9.5.1

   nx (global)        : 16.6.0
   nx                 : 16.7.2
   @nx/js             : 16.7.2
   @nx/jest           : 16.7.2
   @nx/linter         : 16.7.2
   @nx/workspace      : 16.7.2
   @nx/devkit         : 16.7.2
   @nx/esbuild        : 16.7.2
   @nx/eslint-plugin  : 16.7.2
   @nx/node           : 16.7.2
   @nrwl/tao          : 16.7.2
   typescript         : 5.1.6
```

### Failure Logs

```shell
nx build test-app --verbose

 >  NX   Running target build for project test-app and 1 task it depends on:

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run test-app:assets


> nx run test-app:build:production


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project test-app and 1 task it depends on



 >  NX   No such file or directory (os error 2)


Error: No such file or directory (os error 2)
    at /Users/amarchenko/Downloads/broken-alias-in-file/node_modules/nx/src/tasks-runner/cache.js:160:21
    at new Promise (<anonymous>)
    at Cache.<anonymous> (/Users/amarchenko/Downloads/broken-alias-in-file/node_modules/nx/src/tasks-runner/cache.js:158:20)
    at Generator.next (<anonymous>)
    at /Users/amarchenko/Downloads/broken-alias-in-file/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/amarchenko/Downloads/broken-alias-in-file/node_modules/tslib/tslib.js:165:16)
    at Cache.copy (/Users/amarchenko/Downloads/broken-alias-in-file/node_modules/nx/src/tasks-runner/cache.js:152:24)
    at Cache.<anonymous> (/Users/amarchenko/Downloads/broken-alias-in-file/node_modules/nx/src/tasks-runner/cache.js:93:36)
    at Generator.next (<anonymous>)
```

### Package Manager Version

9.5.1

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Thevyn** [comment]
I'm getting this error now when building my app, only way to fix it was to use `--skip-nx-cache`

NX version: 17.1.3

**Comment by FrozenPandaz** [comment]
Thank you for the reproduction. It was very helpful for reproducing the issue.
