### ISSUE TITLE
Problems testing an Angular library with Jest and HTTP

### ISSUE THREAD

**Issue by RicardoJBarriosEviden** [nrwl/nx#18876]
### Current Behavior

After update the nx dependencies some Angular tests started to fail. In previous version they worked as expected. 

I've modifies some config files, but mostly to add documentation and support some libraries. I even tried to reproduce it in a new install with the same results. I've also tried with another simple HTTP tests with the same result.

In the IDE there is a message when I try to run them using `Orta.vscode-jest`:

```
Error: Need to call TestBed.initTestEnvironment() first Jest
```

You can check it in the following tests:

- https://github.com/AMS-AFT/ams-aft-angular/blob/feature/config/packages/ams-aft-core-angular/src/lib/rest/retry/retry-http-request.operator.spec.ts
- https://github.com/AMS-AFT/ams-aft-angular/blob/feature/config/packages/ams-aft-core-angular/src/lib/rest/retry/retry-interceptor.function.spec.ts
- https://github.com/AMS-AFT/ams-aft-angular/blob/feature/config/packages/ams-aft-core-angular/src/lib/rest/retry/retry.interceptor.spec.ts

### Expected Behavior

Before the library update the tests worked as expected. They should continue working.

### GitHub Repo

https://github.com/AMS-AFT/ams-aft-angular/

### Steps to Reproduce

1. `git clone https://github.com/AMS-AFT/ams-aft-angular.git`
2. `git checkout feature/config`
3. `pnpm install`
4. `nx run ams-aft-core-angular:test`

### Nx Report

```shell
Node   : 18.17.1
   OS     : linux-x64
   pnpm   : 8.7.0
   
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/angular        : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/vite           : 16.7.4
   @nx/webpack        : 16.7.4
   nx-cloud           : 16.3.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @ngneat/spectator : 15.0.1
```

### Failure Logs

```shell
FAIL   ams-aft-core-angular  packages/ams-aft-core-angular/src/lib/rest/retry/retry-http-request.operator.spec.ts
  ● Test suite failed to run

    RangeError: Maximum call stack size exceeded

      at Math.<anonymous> (../../node_modules/.pnpm/jest-mock@29.6.3/node_modules/jest-mock/build/index.js:336:51)
      at randomIntInRange (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:43:33)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:75:22)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
      at doQuickSort (../../node_modules/.pnpm/source-map@0.6.1/node_modules/source-map/lib/quick-sort.js:100:5)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by RicardoJBarriosEviden** [comment]
A new log

```bash
 retryHttpRequest › retries the HTTP request on retryable HTTP error with default values

    Need to call TestBed.initTestEnvironment() first

      32 |
      33 |   beforeEach(() => {
    > 34 |     TestBed.configureTestingModule({
         |             ^
      35 |       imports: [HttpClientTestingModule]
      36 |     });
      37 |     httpClient = TestBed.inject(HttpClient);

      at _TestBedImpl.get compiler [as compiler] (../../node_modules/.pnpm/@angular+core@16.2.1_rxjs@7.8.0_zone.js@0.13.1/node_modules/@angular/core/fesm2022/testing.mjs:26918:19)
      at _TestBedImpl.configureTestingModule (../../node_modules/.pnpm/@angular+core@16.2.1_rxjs@7.8.0_zone.js@0.13.1/node_modules/@angular/core/fesm2022/testing.mjs:26830:14)
      at Function.configureTestingModule (../../node_modules/.pnpm/@angular+core@16.2.1_rxjs@7.8.0_zone.js@0.13.1/node_modules/@angular/core/fesm2022/testing.mjs:26662:37)
      at src/lib/rest/retry/retry-http-request.operator.spec.ts:34:13
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (../../node_modules/.pnpm/zone.js@0.13.0/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:416:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/.pnpm/zone.js@0.13.0/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3728:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (../../node_modules/.pnpm/zone.js@0.13.0/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:415:56)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/.pnpm/zone.js@0.13.0/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:173:47)
      at Object.wrappedFunc (../../node_modules/.pnpm/zone.js@0.13.0/node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4208:34)
```
