### ISSUE TITLE
@nx/next:custom-server `serve-custom-server` target is using wrong production build path

### ISSUE THREAD

**Issue by stomvi** [nrwl/nx#18901]
### Current Behavior

Running

```
nx run liff:serve:production
```

is not looking for the Next production build at the right place.

### Expected Behavior

To use the production build in `dist/app/<appName>/.next`.

### Steps to Reproduce

1. npx create-nx-workspace@latest --preset=next test
2. cd test
3. npx nx g @nx/next:custom-server test
4. npx nx run test:serve:production

### Nx Report

```shell
Node   : 16.20.1
OS     : darwin-arm64
npm    : 9.8.0

nx                 : 16.7.4
@nx/js             : 16.7.4
@nx/jest           : 16.7.4
@nx/linter         : 16.7.4
@nx/workspace      : 16.7.4
@nx/cypress        : 16.7.4
@nx/devkit         : 16.7.4
@nx/eslint-plugin  : 16.7.4
@nx/next           : 16.7.4
@nx/react          : 16.7.4
@nrwl/tao          : 16.7.4
@nx/web            : 16.7.4
typescript         : 5.1.6
```

### Failure Logs

```shell
Error: Could not find a production build in the '<projectPath>/apps/<appName>/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (<projectPath>/node_modules/next/src/server/next-server.ts:455:15)
    at new Server (<projectPath>/node_modules/next/src/server/base-server.ts:403:25)
    at new NextNodeServer (<projectPath>/node_modules/next/src/server/next-server.ts:216:5)
    at NextServer.createServer (<projectPath>/node_modules/next/src/server/next.ts:149:20)
    at <projectPath>/node_modules/next/src/server/next.ts:195:23
    at NextServer.prepare (<projectPath>/node_modules/next/src/server/next.ts:128:20)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I found this line might have to do with this issue.

https://github.com/nrwl/nx/blob/7e5027498d84687f52ab13114cf29e6047ff4879/packages/next/src/executors/server/custom-server.impl.ts#L20

**Comment by stomvi** [comment]
I found I should use `nx run app:serve-custom-server:production` instead. Close this issue.
