### ISSUE TITLE
Running `nx report` requires and runs library code

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#18920]
### Current Behavior

I've noticed that when running `nx report` (as part of reporting another bug), I've gotten log prints from our system, which means that when running `nx report`, something ends up `require`ing a system module which has nothing to do with NX itself.

We also have an NX plugin (that's listed in the plugins section in `nx.json`), however I've made sure that it does not reference any system module.

I've added a `console.trace()` in the module to try to see where this happens, but the trace is clearly cut somewhere in the middle by whatever triggers this.

It also specifies that it fails to find plugins that are listed in `nx.json['plugins']`, when in practice there's just one, and it loads properly.

### Expected Behavior

`nx report` (and any other NX commands that do not directly run executors that run code) should not be accessing and running code of the repo.

### Steps to Reproduce

1. `nx report`

### Nx Report

```shell
p nx report
2023-08-30T17:52:52.605Z info safe-shutdown.js: Registered shutdown listeners
metadata: { signals: [ 'SIGINT', 'SIGTERM' ] }
Trace: 
    at Object.<anonymous> (/Users/gioraguttsait/development/loox/packages/safe-shutdown/src/lib/safe-shutdown.js:192:9)
    at Module._compile (/Users/gioraguttsait/development/loox/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._compile (/Users/gioraguttsait/development/loox/node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object.newLoader [as .js] (/Users/gioraguttsait/development/loox/node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (/Users/gioraguttsait/development/loox/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/gioraguttsait/development/loox/packages/safe-shutdown/src/index.js:30:36)
    at Module._compile (/Users/gioraguttsait/development/loox/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._compile (/Users/gioraguttsait/development/loox/node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object.newLoader [as .js] (/Users/gioraguttsait/development/loox/node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (/Users/gioraguttsait/development/loox/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/gioraguttsait/development/loox/packages/rabbitmq-infra/src/lib/rabbitmq-infra.ts:13:21)
    at Module._compile (/Users/gioraguttsait/development/loox/node_modules/.pnpm/v8-compile-cache@2.3.0/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._compile (/Users/gioraguttsait/development/loox/node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
Plugin listed in `nx.json` not found: @loox/shopper-ui
Plugin listed in `nx.json` not found: @loox-root/controllers
Plugin listed in `nx.json` not found: frontend
Plugin listed in `nx.json` not found: @loox-root/clients
Plugin listed in `nx.json` not found: @loox-root/events
Plugin listed in `nx.json` not found: @loox-root/orders
Plugin listed in `nx.json` not found: @loox-root/utils
(node:15272) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

 >  NX   Report complete - copy this into the issue template

   Node : 14.21.3
   OS   : darwin x64
   pnpm : 7.29.0
   
   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/esbuild           : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/node              : 15.8.6
   @nrwl/nx-plugin         : 15.8.6
   @nrwl/react             : 15.8.6
   @nrwl/storybook         : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/vite              : 15.8.6
   @nrwl/webpack           : 15.8.6
   typescript              : 4.9.5
   ---------------------------------------
   Local workspace plugins:
         @loox/nx-plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
This should be fixed, after the changes in https://github.com/nrwl/nx/pull/18306
