### ISSUE TITLE
using pnpm 8.7.0 and "generatePackageJson": true doesn't generate certain packages

### ISSUE THREAD

**Issue by leon** [nrwl/nx#18932]
### Current Behavior

using `@nrwl/webpack:webpack` with `"generatePackageJson": true,` to output a package.json with dependencies for a dockerized cloud run instance.

it does not contain firebase-admin dep.

### Expected Behavior

that the package.json should contain firebase-admin.

### Steps to Reproduce

have a @nrwl/webpack:webpack with generatePageJson: true
have a dependency on firebase-admin

in pnpm 8.5.1 it outputs the correct package.json
in pnpm 8.7.0 it does not output the correct package.json

### Nx Report

```shell
Node   : 18.15.0
   OS     : darwin-arm64
   pnpm   : 8.5.1
   
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/angular        : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/esbuild        : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/nest           : 16.7.4
   @nx/node           : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/webpack        : 16.7.4
   nx-cloud           : 16.3.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @testing-library/angular : 14.3.0
   ng2-charts               : 5.0.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I compared the pnpm-lock.yaml and they are almost identical.

There is a new section at the top in 8.7.0 which is

```
settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

```

but they both have the same lockfileVersion: '6.0'

other small difference is some deps have a 
requiresBuild: true

**Comment by sebastiandg7** [comment]
Are you 100% sure the `firebase-admin` dependency is present in the root's package.json `dependencies` and **NOT** in the `devDependencies`?

**Comment by leon** [comment]
@sebastiandg7 Yes it's in dependencies.

As I wrote, it works great with pnpm 8.5.1

What I did to confirm.

compile with 8.5.1 = it works

1. remove node_modules + pnpm-lock
2. update package.json `"packageManager": "pnpm@8.7.0"` since i'm using corepack.
3. verify correct version with `pnpm --version`
4. `pnpm install`
5. Build again
6. no firebase-admin

**Comment by ahmadbakhshi** [comment]
Same here in 16.8.0

getting this error
```shell
TypeError: Cannot read properties of undefined (reading 'data')
    at D:\Projects\cardon\momentum\node_modules\.pnpm\nx@16.8.0_@swc+core@1.3.82\node_modules\nx\src\plugins\js\package-json\create-package-json.js:124:55
    at Array.forEach (<anonymous>)
    at findProjectsNpmDependencies (D:\Projects\cardon\momentum\node_modules\.pnpm\nx@16.8.0_@swc+core@1.3.82\node_modules\nx\src\plugins\js\package-json\create-package-json.js:122:33)
    at createPackageJson (D:\Projects\cardon\momentum\node_modules\.pnpm\nx@16.8.0_@swc+core@1.3.82\node_modules\nx\src\plugins\js\package-json\create-package-json.js:23:21)
    at D:\Projects\cardon\momentum\node_modules\.pnpm\@nx+webpack@16.8.0_@swc+core@1.3.82_@types+node@18.14.2_esbuild@0.19.2_html-webpack-plugin@5._frfzgsnz7xbsd5fvk3ibcxmcrm\node_modules\@nx\webpack\src\plugins\generate-package-json-plugin.js:33:64
    at fn (D:\Projects\cardon\momentum\node_modules\.pnpm\webpack@5.88.2_@swc+core@1.3.82_esbuild@0.19.2\node_modules\webpack\lib\Compilation.js:479:10)
    at Hook.eval [as callAsync] (eval at create (D:\Projects\cardon\momentum\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\Projects\cardon\momentum\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\Hook.js:18:14)
    at cont (D:\Projects\cardon\momentum\node_modules\.pnpm\webpack@5.88.2_@swc+core@1.3.82_esbuild@0.19.2\node_modules\webpack\lib\Compilation.js:3065:34)
    at D:\Projects\cardon\momentum\node_modules\.pnpm\webpack@5.88.2_@swc+core@1.3.82_esbuild@0.19.2\node_modules\webpack\lib\Compilation.js:3113:10
```

project.json
```javascript
{
  "name": "d365",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/d365/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nx/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "target": "node",
        "compiler": "tsc",
        "outputPath": "dist/apps/d365",
        "main": "apps/d365/src/main.ts",
        "tsConfig": "apps/d365/tsconfig.app.json",
        "isolatedConfig": true,
        "webpackConfig": "apps/d365/webpack.config.js",
        "outputFileName": "server.js",
        "generatePackageJson": true
      },
      "configurations": {
        "development": {},
        "production": {}
      }
    },
    "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "d365:build"
      },
      "configurations": {
        "development": {
          "buildTarget": "d365:build:development",
          "watch": true
        },
        "production": {
          "buildTarget": "d365:build:production"
        }
      }
    },
    "lint": {
      "executor": "@nx/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/d365/**/*.ts"]
      }
    },
    "test": {
      "executor": "@nx/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/{projectRoot}"],
      "options": {
        "jestConfig": "apps/d365/jest.config.ts",
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    }
  },
  "tags": []
}
```

If I remove "generatePackageJson": true, it will work but I lose my package.json

Nx report:
```shell
   Node   : 18.16.0
   OS     : win32-x64
   pnpm   : 8.7.4
   
   nx (global)        : 16.8.0
   nx                 : 16.8.0
   @nx/js             : 16.8.0
   @nx/jest           : 16.8.0
   @nx/linter         : 16.8.0
   @nx/workspace      : 16.8.0
   @nx/esbuild        : 16.8.0
   @nx/eslint-plugin  : 16.8.0
   @nx/nest           : 16.8.0
   @nx/next           : 16.8.0
   @nx/node           : 16.8.0
   @nx/react          : 16.8.0
   @nx/webpack        : 16.8.0
   typescript         : 5.1.3
```

I am on windows machine.

**Comment by elena-dev-thought** [comment]
I am having the same issue, but in my case is a dependency from a shared lib created in the nx space, my built app bundle does not contain the lib dependency.

**Comment by elena-dev-thought** [comment]
As a hack for now, I "duplicated" the dependency package import in the app itself again.

**Comment by hiepxanh** [comment]
I have same issue, change install package from devDependencies to dependencies make it work. Maybe you should try

**Comment by exsesx** [comment]
+1

**Comment by MaxKless** [comment]
Hey @leon thanks for the report!
Sorry it took so long, there are so many issue to work through and so little time. 
I'm wondering, does this still happen to you on the latest version of nx? And if yes, could you provide a minimal reproduction repo with the dependencies you've mentioned? Package managers can be fiddly and if I poke around, trying to repro the issue I will probably spend a lot of time failing.
