### ISSUE TITLE
React App Webpack issue with HtmlWebpackPlugin and generateIndexHtml: false

### ISSUE THREAD

**Issue by mwarger** [nrwl/nx#18978]
### Current Behavior

When using a custom webpack config with the HtmlWebpackPlugin and `generateIndexHtml` set to false, a react app built with webpack will fail to run correctly when served.

```
Uncaught SyntaxError: Cannot use 'import.meta' outside a module (at runtime.js:615:30)
```

<img width="1370" alt="image" src="https://github.com/nrwl/nx/assets/686823/2463e3ec-cc09-4659-9a52-3c8ad732c6ff">

### Expected Behavior

I would expect this to output and work correctly - showing the intended template and output.

### GitHub Repo

https://github.com/mwarger/html-webpack-plugin-repro

### Steps to Reproduce

Setup default NX react application within a workspace

Update the project.json to set the `generateIndexHtml` build option to `false`.

Update the webpack.config to output a custom `HtmlWebpackPlugin` 

Run the app

See error

```
Uncaught SyntaxError: Cannot use 'import.meta' outside a module (at runtime.js:615:30)
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.19.1
   OS     : darwin-arm64
   npm    : 8.19.3
   
   nx                 : 16.8.0-beta.3
   @nx/js             : 16.8.0-beta.3
   @nx/jest           : 16.8.0-beta.3
   @nx/linter         : 16.8.0-beta.3
   @nx/workspace      : 16.8.0-beta.3
   @nx/cypress        : 16.8.0-beta.3
   @nx/devkit         : 16.8.0-beta.3
   @nx/eslint-plugin  : 16.8.0-beta.3
   @nx/react          : 16.8.0-beta.3
   @nrwl/tao          : 16.8.0-beta.3
   @nx/web            : 16.8.0-beta.3
   @nx/webpack        : 16.8.0-beta.3
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mwarger** [comment]
Thank you, it looks like that worked.
