### ISSUE TITLE
@nx/enforce-module-boundaries doesn't work on current Node LTS version (18.7.1)

### ISSUE THREAD

**Issue by kirkobyte** [nrwl/nx#18988]
### Current Behavior

When trying to use `@nx/enforce-module-boundaries` in my project, very few violations will be found, including in cases where I know circular dependencies exist.

This error is found while running on Node 18.17.1, which is the current Node LTS version.

### Expected Behavior

The plugin should be able to resolve the file and not throw errors

### Steps to Reproduce

1. Add NX to project running Node <20
2. Add `@nx/enforce-module-boundaries`

### Nx Report

```shell
Not applicable, still adopting
```

### Failure Logs

```shell
[Error - 10:18:06] Error: ENOENT: no such file or directory, lstat '/<actual path to imported file is here>/__generated__/gql'
Occurred while linting /<actual path to file being linted here>.tsx:31
Rule: "@nx/enforce-module-boundaries"
    at lstatSync (node:fs:1568:3)
    at t.lstatSync (node:electron/js2c/asar_bundle:2:3729)
    at getRelativeImportPath (/Users/kirkh/dev/pacman/node_modules/@nx/eslint-plugin/src/utils/ast-utils.js:85:28)
    at Object.fix (/Users/kirkh/dev/pacman/node_modules/@nx/eslint-plugin/src/rules/enforce-module-boundaries.js:205:98)
    at normalizeFixes (/Users/kirkh/dev/pacman/node_modules/eslint/lib/linter/report-translator.js:193:28)
    at /Users/kirkh/dev/pacman/node_modules/eslint/lib/linter/report-translator.js:364:49
    at Object.report (/Users/kirkh/dev/pacman/node_modules/eslint/lib/linter/linter.js:1085:41)
    at run (/Users/kirkh/dev/pacman/node_modules/@nx/eslint-plugin/src/rules/enforce-module-boundaries.js:183:29)
    at ImportDeclaration (/Users/kirkh/dev/pacman/node_modules/@nx/eslint-plugin/src/rules/enforce-module-boundaries.js:423:17)
    at ruleErrorHandler (/Users/kirkh/dev/pacman/node_modules/eslint/lib/linter/linter.js:1114:28)
```

### Package Manager Version

yarn 1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This particular `lstatSync` seems to be the cause:
https://github.com/nrwl/nx/blob/20528790bb1793ee09518446b35651ffaed3b15c/packages/eslint-plugin/src/utils/ast-utils.ts#L113

All other calls to `lstatSync` include the `{ throwIfNoEntry: false }` flag which prevents the error from being thrown

**Comment by kirkobyte** [comment]
Actually, this doesn't seem to be Node version specific like I thought. Trying running this again on Node 20.5.1, I still get the error on the same line. I'm unsure if there's minimum TypeScript versions etc for this package?

**Comment by kirkobyte** [comment]
It looks like this was a version mismatch on some ESLint peer dependencies. Sorry for the false issue!
