### ISSUE TITLE
Unable to resolve @nx/cypress:configuration.

### ISSUE THREAD

**Issue by OscarGodson** [nrwl/nx#19015]
### Current Behavior

I have an existing app called `embed-frontend` under `/apps`.

I'm trying to add Cypress:

```
nx g @nx/cypress:configuration embed-frontend-e2e --project=embed-frontend --verbose
```

However, running it I get the following error

```
$ nx g @nx/cypress:configuration embed-frontend-e2e --project=embed-frontend --verbose

 >  NX   Unable to resolve @nx/cypress:configuration.

   Cannot find generator 'configuration' in /Users/oscargodson/Projects/goro/node_modules/@nx/cypress/generators.json.

Error: Unable to resolve @nx/cypress:configuration.
Cannot find generator 'configuration' in /Users/oscargodson/Projects/goro/node_modules/@nx/cypress/generators.json.
    at Workspaces.readGenerator (/Users/oscargodson/Projects/goro/node_modules/nx/src/config/workspaces.js:150:19)
    at Object.<anonymous> (/Users/oscargodson/Projects/goro/node_modules/nx/src/command-line/generate/generate.js:227:209)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/oscargodson/Projects/goro/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

### Expected Behavior

I should be able to run `nx g @nx/cypress:configuration embed-frontend-e2e --project=embed-frontend` based on the docs and itll add an e2e project/Cypress support. 

### Steps to Reproduce

I did not setup the original app called `embed-frontend` but all I'm running is `nx g @nx/cypress:configuration embed-frontend-e2e --project=embed-frontend`. The package is installed already and `"@nx/cypress": "16.4.0",` is in my package.json. I've even tried deleting `node_modules` and `package-lock.json` and reinstalling it all. All I did was take a fresh pull of our existing repo and run that command.

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-x64
   npm    : 9.5.1
   
   nx                 : 16.4.0
   @nx/js             : 16.4.1
   @nx/jest           : 16.4.1
   @nx/linter         : 16.4.0
   @nx/workspace      : 16.4.0
   @nx/cypress        : 16.4.0
   @nx/devkit         : 16.4.0
   @nx/esbuild        : 16.4.1
   @nx/eslint-plugin  : 16.4.0
   @nx/node           : 16.4.1
   @nx/react          : 16.4.0
   @nrwl/react        : 16.7.4
   @nrwl/tao          : 16.4.0
   @nx/web            : 16.4.0
   @nx/webpack        : 16.4.0
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @goro/[REDACTED]-client
         @goro/[REDACTED]-client
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@16.4.1
     - @nrwl/js@16.4.1
     - @nx/jest@16.4.1
     - @nrwl/jest@16.4.1
     - @nx/esbuild@16.4.1
     - @nrwl/esbuild@16.4.1
     - @nx/node@16.4.1
     - @nrwl/node@16.4.1
     - @nrwl/react@16.7.4
   
   To fix this, run `nx migrate nx@16.7.4`
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Can you please update to the latest version of Nx and try again?

**Comment by OscarGodson** [comment]
While that fixes it, does that mean even minor version updates mean Nx stops supporting past versions or even provides work arounds? 

Thanks! But yeah knowing if minor versions mean Nx stops supporting it would be good to know as that would impact how we do certain parts of development.
