### ISSUE TITLE
Impossible to build expo app

### ISSUE THREAD

**Issue by a1092** [nrwl/nx#19073]
### Current Behavior

I want to build my nx expo app, but i still have an exception.

The error throwed appears that these script commands into package.json apps file cannot be run. 

"scripts": {
    "eas-build-pre-install": "pwd && ls && cd ../../ && ls && node tools/scripts/eas-build-pre-install.mjs . apps/laura && cp package-lock.json apps/laura",
    "eas-build-post-install": "pwd && ls && cd ../../ && node tools/scripts/eas-build-post-install.mjs . apps/laura"
  }

In fact, it appears that these scripts are runned after the project packaged in an other temp directory to be built. 

Note that i run it locally to understand the problem. Same behavior on expo platform.

### Expected Behavior

I just want to build my app !!

### Steps to Reproduce

1. npx nx build laura --platform ios --non-interactive --local

### Nx Report

```shell
Node   : 20.6.0
OS     : darwin-x64
npm    : 10.0.0

nx                 : 16.8.1
@nx/js             : 16.8.1
@nx/jest           : 16.8.1
@nx/linter         : 16.8.1
@nx/workspace      : 16.8.1
@nx/detox          : 16.8.1
@nx/devkit         : 16.8.1
@nx/eslint-plugin  : 16.8.1
@nx/expo           : 16.8.1
@nx/react          : 16.8.1
@nrwl/tao          : 16.8.1
@nx/web            : 16.8.1
@nx/webpack        : 16.8.1
nx-cloud           : 16.4.0
typescript         : 5.1.6
```

### Failure Logs

```shell
[SETUP_WORKINGDIR] Preparing workingdir (note that the path is /var/folders/p0/4wt5vfld4q98v8l8_1s4_fl80000gn/T/eas-build-local-nodejs/d938f2b3-1e72-4fd2-a7d3-ef0f89aff9b1)
[START_BUILD] Starting build
[PREPARE_PROJECT] .npmrc found at .npmrc
[PRE_INSTALL_HOOK] Script 'eas-build-pre-install' is present in package.json, running it ...
[PRE_INSTALL_HOOK] > laura@0.0.1 eas-build-pre-install
[PRE_INSTALL_HOOK] node:internal/modules/cjs/loader:1051
[PRE_INSTALL_HOOK]   throw err;
[PRE_INSTALL_HOOK]   ^
[PRE_INSTALL_HOOK] 
[PRE_INSTALL_HOOK] Error: Cannot find module '/private/var/folders/p0/4wt5vfld4q98v8l8_1s4_fl80000gn/T/eas-build-local-nodejs/tools/scripts/eas-build-pre-install.mjs'
[PRE_INSTALL_HOOK]     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
[PRE_INSTALL_HOOK]     at Module._load (node:internal/modules/cjs/loader:901:27)
[PRE_INSTALL_HOOK]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
[PRE_INSTALL_HOOK]     at node:internal/main/run_main_module:23:47 {
[PRE_INSTALL_HOOK]   code: 'MODULE_NOT_FOUND',
[PRE_INSTALL_HOOK]   requireStack: []
[PRE_INSTALL_HOOK] }
[PRE_INSTALL_HOOK] 
[PRE_INSTALL_HOOK] Node.js v20.6.0
[PRE_INSTALL_HOOK] 
Error: npm run eas-build-pre-install exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/xxxx/node_modules/@expo/turtle-spawn/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)
    ...
    at spawnAsync (/Users/xxxx/node_modules/@expo/turtle-spawn/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/xxxx/node_modules/@expo/turtle-spawn/dist/index.js:16:47)
    at runHookIfPresent (/Users/xxxx/node_modules/@expo/build-tools/dist/utils/hooks.js:36:42)
    at async /Users/xxxx/node_modules/@expo/build-tools/dist/common/setup.js:43:9
    at async BuildContext.runBuildPhase (/Users/xxxx/node_modules/@expo/build-tools/dist/context.js:101:28)
    at async setupAsync (/Users/xxxx/node_modules/@expo/build-tools/dist/common/setup.js:42:5)
    at async buildAsync (/Users/xxxx/node_modules/@expo/build-tools/dist/builders/ios.js:43:5)
    at async runBuilderWithHooksAsync (/Users/xxxx/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.iosBuilder (/Users/xxxx/node_modules/@expo/build-tools/dist/builders/ios.js:29:16)
    at async buildIosAsync (/Users/xxxx/node_modules/eas-cli-local-build-plugin/dist/ios.js:66:12)

Build failed
Unknown error. See logs of the Pre-install hook build phase for more information.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i could not replicate this log you are seeing. I just created an expo app using the latest nx and the build works for me out of box for local build. do you have a link to your repo?
also, just want to double-check:
- in your repo, do you have files tools/scripts/eas-build-post-install.mjs and tools/scripts/eas-build-pre-install.mjs?
- do you have all the all the required packages to run your build locally, like yarn, fastlane, cocoapods?

**Comment by xiongemi** [comment]
does it work without the `--local` flag?

**Comment by xiongemi** [comment]
closing this issue for now

**Comment by quicksilverr** [comment]
@xiongemi Please reopen this, facing the same issue. It's impossible to build. 

I have a bare react native project, I have done all the neccessary setups as mentioned in the expo docs. I'm trying to setup eas build and eas update. Just the package.json is being a hiccup. Please can you guide?

**Comment by xiongemi** [comment]
in your repo, do you have file tools/scripts/eas-build-pre-install.mjs?
