### ISSUE TITLE
Build error on AWS Amplify: TypeError: Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by cupid-dev** [nrwl/nx#19091]
### Current Behavior

My Nx project builds successfully locally with `pnpm exec nx run frontend:build --no-cloud`, but building on AWS Amplify with the same command fails while prerendering the /404 and /500 error routes with `TypeError: Cannot read properties of null (reading 'useRef') at exports.useRef`. I don't use `useRef` anywhere in my code.

### Expected Behavior

The same build command that succeeds locally should succeed on Amplify.

### Steps to Reproduce

1. Try to build Next.js app using Nx in Amplify

### Nx Report

```shell
Locally:
   Node   : 18.12.1
   OS     : darwin-x64
   pnpm   : 8.6.12

   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/next           : 16.6.0
   @nx/react          : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/web            : 16.6.0
   nx-cloud           : 16.4.0
   @nrwl/nx-cloud     : 16.2.0
   typescript         : 5.1.6

On Amplify:
Node   : 16.19.0
                                 OS     : linux-x64
                                 pnpm   : 8.7.4
                                 
                                 nx                 : 16.6.0
                                 @nx/js             : 16.6.0
                                 @nx/jest           : 16.6.0
                                 @nx/linter         : 16.6.0
                                 @nx/workspace      : 16.6.0
                                 @nx/cypress        : 16.6.0
                                 @nx/devkit         : 16.6.0
                                 @nx/eslint-plugin  : 16.6.0
                                 @nx/next           : 16.6.0
                                 @nx/react          : 16.6.0
                                 @nrwl/tao          : 16.6.0
                                 @nx/web            : 16.6.0
                                 nx-cloud           : 16.4.0
                                 typescript         : 5.1.6
```

### Failure Logs

```shell
2023-09-09T04:47:36.135Z [INFO]: # Starting phase: preBuild
                                 # Executing command: corepack enable
2023-09-09T04:47:36.404Z [INFO]: # Executing command: corepack prepare pnpm@latest --activate
2023-09-09T04:47:36.859Z [INFO]: Preparing pnpm@latest for immediate activation...
2023-09-09T04:47:37.333Z [INFO]: # Executing command: pnpm install
2023-09-09T04:47:38.172Z [INFO]: Lockfile is up to date, resolution step is skipped
2023-09-09T04:47:38.597Z [INFO]: Progress: resolved 1, reused 0, downloaded 0, added 0
2023-09-09T04:47:38.738Z [INFO]: Packages: +7 -7
                                 +++++++-------
2023-09-09T04:47:39.599Z [INFO]: Progress: resolved 7, reused 0, downloaded 3, added 2
2023-09-09T04:47:40.566Z [INFO]: Progress: resolved 7, reused 0, downloaded 7, added 7, done
2023-09-09T04:47:43.595Z [INFO]: dependencies:
                                 + @auth0/auth0-react 2.2.0
                                 + @aws-sdk/client-dynamodb 3.391.0
                                 + @aws-sdk/client-mturk 3.391.0
                                 + @aws-sdk/client-s3 3.391.0
                                 + @aws-sdk/client-secrets-manager 3.408.0
                                 + @aws-sdk/lib-dynamodb 3.391.0
                                 + @aws-sdk/s3-request-presigner 3.391.0
                                 + @chakra-ui/icons 2.1.0
                                 + @chakra-ui/react 2.8.0
                                 + @dnd-kit/core 6.0.8
                                 + @dnd-kit/sortable 7.0.2
                                 + @dnd-kit/utilities 3.2.1
                                 + @emotion/react 11.11.1
                                 + @emotion/styled 11.11.0
                                 + @swc/helpers 0.5.1
                                 + @types/auth0 3.3.4
                                 + auth0 3.7.0
                                 + aws-lambda 1.0.7
                                 + aws-sdk 2.1440.0
                                 + browser-image-compression 2.0.2
                                 + constructs 10.2.50
                                 + dotenv 16.3.1
                                 + framer-motion 10.15.1
                                 + jsonwebtoken 9.0.0
                                 + jwks-rsa 3.0.1
                                 - next 13.4.13
                                 + react 18.2.0
                                 + react-dom 18.2.0
                                 + react-icons 4.10.1
                                 + react-image-crop 10.1.5
                                 + stripe 12.9.0
                                 + superagent-proxy 3.0.0
                                 + tslib 2.6.1
                                 + uuid 9.0.0
                                 + xml-js 1.6.11
                                 + zod 3.22.1
                                 + zod-validation-error 1.3.1
                                 devDependencies:
                                 + @aws-cdk/aws-amplify-alpha 2.90.0-alpha.0
                                 + @aws-cdk/aws-apigatewayv2-authorizers-alpha 2.90.0-alpha.0
                                 + @aws-cdk/aws-apigatewayv2-integrations-alpha 2.90.0-alpha.0
                                 + @babel/preset-react 7.22.5
                                 + @nx/cypress 16.6.0
                                 + @nx/eslint-plugin 16.6.0
                                 + @nx/jest 16.6.0
                                 + @nx/js 16.6.0
                                 + @nx/linter 16.6.0
                                 + @nx/react 16.6.0
                                 + @nx/workspace 16.6.0
                                 + @swc/cli 0.1.62
                                 + @swc/core 1.3.51
                                 + @testing-library/react 14.0.0
                                 + @types/aws-lambda 8.10.119
                                 + @types/jest 29.5.3
                                 + @types/jsonwebtoken 9.0.2
                                 + @types/node 18.14.2
                                 + @types/react 18.2.14
                                 + @types/react-dom 18.2.6
                                 + @types/uuid 9.0.2
                                 + @typescript-eslint/eslint-plugin 5.62.0
                                 + @typescript-eslint/parser 5.62.0
                                 + aws-cdk-lib 2.90.0
                                 + babel-jest 29.6.2
                                 + cypress 12.17.3
                                 + eslint 8.15.0
                                 + eslint-config-next 13.4.1
                                 + eslint-config-prettier 8.1.0
                                 + eslint-plugin-cypress 2.13.4
                                 + eslint-plugin-import 2.27.5
                                 + eslint-plugin-jsx-a11y 6.7.1
                                 + eslint-plugin-react 7.32.2
                                 + eslint-plugin-react-hooks 4.6.0
                                 + jest 29.6.2
                                 + jest-environment-jsdom 29.6.2
                                 + next 13.4.19
                                 + nx 16.6.0
                                 + nx-cloud 16.4.0
                                 + prettier 2.8.8
                                 + ts-jest 29.1.1
                                 + ts-node 10.9.1
                                 + typescript 5.1.6
2023-09-09T04:47:43.859Z [INFO]: Done in 6.4s
2023-09-09T04:47:43.905Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2023-09-09T04:47:43.906Z [INFO]: # Executing command: pnpm exec nx run frontend:build --no-cloud
2023-09-09T04:47:47.685Z [INFO]: 
2023-09-09T04:47:47.690Z [INFO]: >  NX   Nx Cloud Will Not Be Used
                                 Nx will continue running, but nothing will be written or read from the remote cache.
                                 Run details will also not be available in the Nx Cloud UI.
                                 
                                 If this wasn't intentional, check for the NX_NO_CLOUD environment variable, the --no-cloud flag
2023-09-09T04:47:47.693Z [INFO]: 
2023-09-09T04:47:47.693Z [INFO]: > nx run frontend:build:production
2023-09-09T04:47:52.122Z [INFO]: - [33mwarn[39m No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2023-09-09T04:47:52.127Z [INFO]: [35m[1mAttention[22m[39m: Next.js now collects completely anonymous telemetry regarding usage.
2023-09-09T04:47:52.127Z [INFO]: This information is used to shape Next.js' roadmap and prioritize features.
                                 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
                                 [36mhttps://nextjs.org/telemetry[39m
2023-09-09T04:47:52.206Z [INFO]: - [36minfo[39m Creating an optimized production build...
2023-09-09T04:48:19.776Z [INFO]: - [36minfo[39m Compiled successfully
2023-09-09T04:48:19.778Z [INFO]: - [36minfo[39m Skipping linting
                                 - [36minfo[39m Checking validity of types...
2023-09-09T04:48:28.814Z [INFO]: - [36minfo[39m Collecting page data...
2023-09-09T04:48:41.047Z [INFO]: - [36minfo[39m Generating static pages (0/5)
2023-09-09T04:48:41.101Z [WARNING]: TypeError: Cannot read properties of null (reading 'useRef')
                                    at exports.useRef (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.production.min.js:25:337)
                                    at PathnameContextProviderAdapter (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/router/adapters.js:85:35)
                                    at Wc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
                                    Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
                                    TypeError: Cannot read properties of null (reading 'useRef')
                                    at exports.useRef (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.production.min.js:25:337)
                                    at PathnameContextProviderAdapter (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/router/adapters.js:85:35)
                                    at Wc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
2023-09-09T04:48:41.101Z [INFO]: - [36minfo[39m Generating static pages (1/5)
2023-09-09T04:48:41.114Z [INFO]: - [36minfo[39m Generating static pages (2/5)
2023-09-09T04:48:41.320Z [WARNING]: TypeError: Cannot read properties of null (reading 'useRef')
                                    at exports.useRef (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.production.min.js:25:337)
2023-09-09T04:48:41.321Z [WARNING]: at PathnameContextProviderAdapter (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/router/adapters.js:85:35)
                                    at Wc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
2023-09-09T04:48:41.321Z [WARNING]: Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
                                    TypeError: Cannot read properties of null (reading 'useRef')
                                    at exports.useRef (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.production.min.js:25:337)
                                    at PathnameContextProviderAdapter (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/router/adapters.js:85:35)
                                    at Wc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
                                    at Z (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at Zc (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
2023-09-09T04:48:41.321Z [INFO]: - [36minfo[39m Generating static pages (3/5)
2023-09-09T04:48:41.699Z [INFO]: external isAuthenticated: false
2023-09-09T04:48:41.701Z [INFO]: external isAuthenticated: false
2023-09-09T04:48:41.759Z [INFO]: home page isAuthenticated: false
2023-09-09T04:48:41.814Z [INFO]: - [36minfo[39m Generating static pages (5/5)
2023-09-09T04:48:41.816Z [WARNING]: > Export encountered errors on following paths:
                                    /_error: /404
                                    /_error: /500
2023-09-09T04:48:41.864Z [WARNING]: [1m[31mError occurred while trying to run the npx next build [39m[22m
2023-09-09T04:48:41.864Z [WARNING]: [1m[31mError: Command failed: npx next build [39m[22m
2023-09-09T04:48:41.865Z [WARNING]: [1m[31m    at checkExecSyncError (node:child_process:861:11)[39m[22m
                                    [1m[31m    at execSync (node:child_process:932:15)[39m[22m
                                    [1m[31m    at /codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/@nx+next@16.6.0_@babel+core@7.22.10_@swc+core@1.3.51_@types+node@18.14.2_eslint@8.15.0_next@1_3zyt67gsgqavcro3u3avhmtkki/node_modules/@nx/next/src/executors/build/build.impl.js:49:42[39m[22m
                                    [1m[31m    at Generator.next (<anonymous>)[39m[22m
                                    [1m[31m    at /codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/tslib@2.6.1/node_modules/tslib/tslib.js:169:75[39m[22m
                                    [1m[31m    at new Promise (<anonymous>)[39m[22m
                                    [1m[31m    at Object.__awaiter (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/tslib@2.6.1/node_modules/tslib/tslib.js:165:16)[39m[22m
                                    [1m[31m    at buildExecutor (/codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/@nx+next@16.6.0_@babel+core@7.22.10_@swc+core@1.3.51_@types+node@18.14.2_eslint@8.15.0_next@1_3zyt67gsgqavcro3u3avhmtkki/node_modules/@nx/next/src/executors/build/build.impl.js:20:20)[39m[22m
                                    [1m[31m    at /codebuild/output/src2156940249/src/cupid/node_modules/.pnpm/nx@16.6.0_@swc+core@1.3.51/node_modules/nx/src/command-line/run/run.js:102:23[39m[22m
2023-09-09T04:48:41.873Z [INFO]: 
2023-09-09T04:48:41.873Z [INFO]: 
                                 >  NX   Running target build for project frontend failed
                                 Failed tasks:
                                 
                                 - frontend:build:production
                                 
                                 Hint: run the command with --verbose for more details.
2023-09-09T04:48:41.887Z [ERROR]: !!! Build failed
2023-09-09T04:48:41.887Z [ERROR]: !!! Non-Zero Exit Code detected
2023-09-09T04:48:41.888Z [INFO]: # Starting environment caching...
2023-09-09T04:48:41.888Z [INFO]: # Uploading environment cache artifact...
2023-09-09T04:48:41.970Z [INFO]: # Uploaded environment cache artifact
2023-09-09T04:48:41.970Z [INFO]: # Environment caching completed
Terminating logging...
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by DabinLim** [comment]
Can you tell me how you solved this problem?
I'm having the exact same problem

**Comment by cupid-dev** [comment]
> Can you tell me how you solved this problem? I'm having the exact same problem

I don't know if I ever did. I ended up deciding not to use Nx because of its complexity and due to this issue. I just use Turbo with Next.js now.

**Comment by ndcunningham** [comment]
This was probably a `react` dependency which would be related to your environment.

Can you update to the latest and retry?
