### ISSUE TITLE
NestJS failed to compile with generatePackageJson:true

### ISSUE THREAD

**Issue by fabienvauchelles** [nrwl/nx#19092]
### Current Behavior

When trying to build with `generatePackageJson` option at `true`, nx failed to compile.

Here is the stacktrace:

```
$ nx build backend-app --verbose

 >  NX   Running target build for project backend-app and 47 tasks it depends on:

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run backend-app:build


 >  NX   Cannot read properties of undefined (reading 'data')


HookWebpackError: Cannot read properties of undefined (reading 'data')
    at makeWebpackError (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/webpack/lib/Compilation.js:3068:12
    at eval (eval at create (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at fn (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/webpack/lib/Compilation.js:481:17)
    at _next0 (eval at create (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/webpack/lib/Compilation.js:503:10
    at Hook.eval [as callAsync] (eval at create (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/tapable/lib/Hook.js:18:14)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'data')
    at /home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/nx/src/plugins/js/package-json/create-package-json.js:124:55
    at Array.forEach (<anonymous>)
    at findProjectsNpmDependencies (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/nx/src/plugins/js/package-json/create-package-json.js:122:33)
    at createPackageJson (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/nx/src/plugins/js/package-json/create-package-json.js:23:21)
    at /home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:33:64
    at fn (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/fabien/gitrepos/scrapoxy/scrapoxy4-nx/node_modules/webpack/lib/Compilation.js:503:10

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target build for project backend-app and 47 tasks it depends on failed

   Failed tasks:
   
   - backend-app:build
   
   Hint: run the command with --verbose for more details.
```

Issue happens in `create-package-json.js`:

```
const seen = new Set();
    (_b = options.helperDependencies) === null || _b === void 0 ? void 0 : _b.forEach((dep) => {
        seen.add(dep);
        npmDeps.dependencies[graph.externalNodes[dep].data.packageName] =
            graph.externalNodes[dep].data.version;
        recursivelyCollectPeerDependencies(dep, graph, npmDeps, seen);
    });
```

it is regardings `tslib`.

`graph.externalNodes` is `{}`

### Expected Behavior

We need to generate the package.json.

### Steps to Reproduce

1. Use version 16.8.1
2. Build and generate package.json

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : linux-x64
   npm    : 10.1.0
   
   nx (global)        : 16.8.1
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/angular        : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/nest           : 16.8.1
   @nx/node           : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/webpack        : 16.8.1
   typescript         : 5.1.6
```

### Package Manager Version

10.1.0

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

It works with version **16.7.4** (package.json is generated)

**Comment by nosaku** [comment]
I am also having the same issue and it is a showstopper for upgrading to 16.8.1

**Comment by nosaku** [comment]
Is there a workaround? I can't upgrade without this being working.

**Comment by fabienvauchelles** [comment]
I downgrade to 16.7.4 and it is working.

**Comment by jaqua** [comment]
It's really weird. I setup a new nx workspace with a nestjs application. Everything is working, as the `graph.externalNodes` has content.

In my production workspace I upgraded to 16.8.1. `graph.externalNodes` is always `{}`. I reset the cache, removed .cache/nx and so on. The new build project-graph.json has always an empty object for *externalNodes*.

**Comment by nosaku** [comment]
Even with the latest 16.9.1 this issue is not resolved.

**Comment by michan85** [comment]
for me the problem was having `importHelpers` set to true in tsconfig.json, disabling it resolved the issue might be related to https://github.com/nrwl/nx/issues/11012.

my guess is that importHelpers indirectly requires tslib and when generating the package json its not in the nx graph dependancies

**Comment by fabienvauchelles** [comment]
Interesting, I will test the configuration

**Comment by nosaku** [comment]
Tried with importHelpers as false in tsconfig.base.json. Build is successfuly but the generated package.json is missing dependencies.

**Comment by michan85** [comment]
i had that issue too but was related to @nx/js plugin config in nx.json, setting analyzeSourceFiles: true made the dependancies appear in package.json

here is the snippet from nx.json
<img width="257" alt="image" src="https://github.com/nrwl/nx/assets/207225/62905b0b-ee9d-4b2a-9410-a27cccc30511">

**Comment by nosaku** [comment]
Tried all options but nothing is working in the "old upgraded workspace". I created a new workspace with a sample NestJS app and it correctly generates the package.json with dependencies. I compared all config files in new and old workspace and do not see any difference except that old one has many apps and libs.

**Comment by jaqua** [comment]
Exactly the same thing as @nosaku described. I created a new workspace with sample apps and it is working. I compared all files and do not find the difference. So the only chance I see is to create new workspace and create all apps and libs again. But this is a very, very hard thing as I have hundreds of libs. And because of this behaviour it is not possible to create a repo, which recreates the problem. But it seems with my repo it is not possible to upgrade.

**Comment by nosaku** [comment]
It seems something strange with package-lock.json. I created a sample app in my old repo, but still failed. Then I copied the package.json and package-lock.json from new workspace to old repo and the build of new app worked fine.

**Comment by jaqua** [comment]
@nosaku What about copying the old package.json dependencies to the new one, run `npm install` to create the package-lock.json? First: does the new repo still work (now with all productive dependencies)? And second: Copy those files to the old repo. Would it then work?

**Comment by nosaku** [comment]
@jaqua yes trying the same now... takes long for npm install in my corporate environment.

**Comment by jaqua** [comment]
@nosaku Yes, that should work. But for me the other way round doesn't work: Copy the new lock-file to the old repo.

**Comment by nosaku** [comment]
@jaqua I copied the package-lock.json from new workspace to old one and it started working again. Very strange. I tried moving all my apps and libs to a folder named "old" and started testing with new app. Once it worked moved all back and even the old one was working. In the new workspace there are few changes to the versions of Angular etc. like ~16.2.0 may be this is issue? Not sure.

**Comment by nosaku** [comment]
@jaqua I think I finally found the problem. I had package-lock.json in my .gitignore file as I don't checkin this to git and generate it in Azure pipeline. I removed this line and it works fine. When I add it to .gitignore I get the error back. so I think .gitignore is used internally by Nx. Very strange but that's what I was able to find after wasting all day.

**Comment by jaqua** [comment]
@nosaku This is mentioned here: https://github.com/nrwl/nx/issues/19029#issuecomment-1726388916 But this is not the issue in my case. I'm running the tasks locally, and it is the same problem. lock file ist not in .gitignore.

**Comment by israellev** [comment]
I created a new nx project and moved the old project to it, only that way it worked

**Comment by pateroski** [comment]
we're still stuck at `nx@16.7.4` due to this closed issue => https://github.com/nrwl/nx/issues/19029

**Comment by jaysoo** [comment]
Are people seeing the error from the same line as the OP?

> npmDeps.dependencies[graph.externalNodes[dep].data.packageName]

Can you try `nx reset` to rebuild the graph? It looks like either the `analyzeSourceFiles` option is not turned on for `@nx/js` plugin, or the graph isn't populated correctly.

**Comment by karocksjoelee** [comment]
I am getting the exact same error

**Comment by wickstargazer** [comment]
Hi i am getting the same error, in version `18.0.4`

This is the stackTrace, this only happens if i turn on the `generatePackageJson:true` option for `@nx/webpack`

Also i am using `yarn` as my package manager. Any suggestions?

```bash
HookWebpackError: Cannot read properties of null (reading 'nodes')
    at makeWebpackError (D:\projects\nx-plugins\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at D:\projects\nx-plugins\node_modules\webpack\lib\Compilation.js:3075:12
    at eval (eval at create (D:\projects\nx-plugins\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at fn (D:\projects\nx-plugins\node_modules\webpack\lib\Compilation.js:481:17)
    at Hook.eval [as callAsync] (eval at create (D:\projects\nx-plugins\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\projects\nx-plugins\node_modules\tapable\lib\Hook.js:18:14)
    at cont (D:\projects\nx-plugins\node_modules\webpack\lib\Compilation.js:3072:34)
    at D:\projects\nx-plugins\node_modules\webpack\lib\Compilation.js:3120:10
    at symbolIterator (D:\projects\nx-plugins\node_modules\neo-async\async.js:3485:9)
    at done (D:\projects\nx-plugins\node_modules\neo-async\async.js:3527:9)
-- inner error --
TypeError: Cannot read properties of null (reading 'nodes')
    at getHelperDependenciesFromProjectGraph (D:\projects\nx-plugins\node_modules\@nx\js\src\utils\compiler-helper-dependency.js:78:23)
```

**Comment by gary-menzel** [comment]
I have updated an older app to use the current configuration files (NX 18.0.2) and get this error when I want to `generatePackageJson`.  As many other commenters have said, I need `package.json` generated for a production build and I can't seem to find a workaround.  Everything works perfectly fine when I am just running the local `serve`.  It is only the production build - and only the `generatePackageJson` flag (all my other config items came across and worked OK - I added them one by one to check).  I get the following errror:

`HookWebpackError: Cannot read properties of undefined (reading 'data')`

**Comment by gary-menzel** [comment]
> NOTE: I am happy to delete the `yarn.lock` file and try again if anyone thinks that might help.

OK - I don't know which part fixed this but it is now working.

- upgraded to NX 18.0.7
- deleted the yarn.lock file
- ran `yarn` again to install
- ran the production build that was previously failing - including the `generatePackageJson: true`
- tested a 2nd production build with the `generatePackageJson: true` flag
- both builds completed and the `package.json` and `yarn.lock` files are present in the output directories

I will have to wait until I deploy and test to see if the `package.json` is correct - but it it certainly appears to be.

I looked through the release notes from 18.0.2 to 18.0.7 and could not see any specific mention of `generatePackageJson` but there have been some type of updates to how webpack is used.  It may be because of that...

Or it may be because I deleted the `yarn.lock` file.  I note other similar issues seem to say it is related to `*.lock` files - although `yarn.lock` was never specifically mentioned.

For me, my issue is resolved.  Maybe the above may help others.

**Comment by SirPhemmiey** [comment]
hey @wickstargazer do you mind telling how you did that?

**Comment by SirPhemmiey** [comment]
I've fixed this issue [here](https://github.com/nrwl/nx/issues/22481#issuecomment-2017998626)
