### ISSUE TITLE
Angular/Cypress component testing broken with Cypress v.13

### ISSUE THREAD

**Issue by joewIST** [nrwl/nx#19119]
### Current Behavior

Since upgrading to Cypress v.13 (wanted to experiment with their new Test replay functionality), all component tests run using Nx fail with an error relating to isCtProjectUsingBuildProject function, which seems to be called multiple times for every library in our project, until the maximum call stack size is exceeded. LK in the failure logs below.

This means we are unable to run any tests.

### Expected Behavior

These tests should execute as they did before.

### Steps to Reproduce

1. Run yarn nx run _____:component-test on any library using Cypress as a component test runner.

### Nx Report

```shell
Node   : 20.6.1
   OS     : win32-x64
   yarn   : 1.22.19
   
   nx (global)        : 16.0.3
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/angular        : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/devkit         : 16.8.1
   @nrwl/devkit       : 13.1.3
   @nx/esbuild        : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/plugin         : 16.8.1
   @nx/storybook      : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/webpack        : 16.8.1
   nx-cloud           : 16.4.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc       : 1.1.21
   @ngneat/spectator        : 15.0.1
   @ngrx/component-store    : 16.2.0
   @ngrx/effects            : 16.2.0
   @ngrx/entity             : 16.2.0
   @ngrx/router-store       : 16.2.0
   @ngrx/schematics         : 16.2.0
   @ngrx/store              : 16.2.0
   @ngrx/store-devtools     : 16.2.0
   @storybook/angular       : 7.2.1
   angular-auth-oidc-client : 16.0.1
   apollo-angular           : 5.0.1
   nx-stylelint             : 14.0.2
   ---------------------------------------
```

### Failure Logs

```shell
RangeError: Maximum call stack size exceeded
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:33:38)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
    at isCtProjectUsingBuildProject (C:\Users\joe.williams\Projects\Chromium\src\node_modules\@nx\cypress\src\utils\ct-helpers.js:40:13)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by APOSWE** [comment]
Hello!
I've the same problem...
Is there already a bug fix available? Or how can i fix that with a workaround?

**Comment by martinsik** [comment]
I had the same problem but the issue was that my project had a circular dependency between Nx libraries.

I found what libraries cause the problem by adding `console.log()` directly into my `node_modules\@nx\cypress\src\utils\ct-helpers.js`.

```
39    for (const maybeIntermediateProject of maybeIntermediateProjects) {
40        console.log(maybeIntermediateProject.target);
41        if (isCtProjectUsingBuildProject(graph, maybeIntermediateProject.target, childProjectName)) {
42            return true;
43        }
44    }
```
