### ISSUE TITLE
Unable to locate React shared Library in React native with Nx workspaces

### ISSUE THREAD

**Issue by masinavinod410** [nrwl/nx#19120]
### Current Behavior

Tying to create React shared library Using Nx- workspaces which can be used in both react and React-native. React web able to locate and use the shared library but react-native unable to locate. Tried many ways but still issue exists.

![image](https://github.com/nrwl/nx/assets/36719382/6e61ca50-86f7-470b-90fe-0861e0752e14)

### Expected Behavior

Able to use Shared library logic in both react web and react-native 

### GitHub Repo

https://github.com/masinavinod410/Shared-Library-ReactWeb-ReactNative-with-Nx-workspaces

### Steps to Reproduce

1.npx create-nx-workspace app-name
2.npx nx g @nrwl/react:app reactjs-web
3. npx nx g @nrwl/react:lib shared with importPath = '@nx/shared'
4. import {shared} from '@nx/shared' in react-native and react web and run applications

### Nx Report

```shell
Node   : 18.17.1
   OS     : win32-x64
   npm    : 10.0.0
   
   nx (global)        : 16.8.1
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/detox          : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/react          : 16.8.1
   @nx/react-native   : 16.8.1
   @nx/rollup         : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/web            : 16.8.1
   @nx/webpack        : 16.8.1
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
```

### Failure Logs

```shell
LOG  Running "TalicMobile" with {"rootTag":11}
error: Error: Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);
    at ModuleResolver.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._traverseDependenciesForSingleFile (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:249:5)
    at async Graph.traverseDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:157:9)
    at async DeltaCalculator._getChangedDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:281:42)
    at async DeltaCalculator.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:112:16)
 ERROR  [Error: undefined Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);]
error: Error: Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);
    at ModuleResolver.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at async Graph._traverseDependenciesForSingleFile (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:249:5)
    at async Graph.traverseDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:157:9)
    at async DeltaCalculator._getChangedDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:281:42)
    at async DeltaCalculator.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:112:16)
    at async DeltaBundler.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler.js:67:12)
 ERROR  [Error: undefined Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);]
error: Error: Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx: 

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);
    at ModuleResolver.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at async Graph._traverseDependenciesForSingleFile (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:249:5)
    at async Graph.traverseDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:157:9)
    at async DeltaCalculator._getChangedDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:281:42)
    at async DeltaCalculator.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:112:16)
    at async DeltaBundler.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler.js:67:12)
 ERROR  [Error: undefined Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);]
error: Error: Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);
    at ModuleResolver.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at async Graph._traverseDependenciesForSingleFile (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:249:5)
    at async Graph.traverseDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:157:9)
    at async DeltaCalculator._getChangedDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:281:42)
    at async DeltaCalculator.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:112:16)
    at async DeltaBundler.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler.js:67:12)
 ERROR  [Error: undefined Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);]
error: Error: Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);
    at ModuleResolver.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at async Graph._traverseDependenciesForSingleFile (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:249:5)
    at async Graph.traverseDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:157:9)
    at async DeltaCalculator._getChangedDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:281:42)
    at async DeltaCalculator.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:112:16)
    at async DeltaBundler.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler.js:67:12)
 ERROR  [Error: undefined Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);]
error: Error: Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);
    at ModuleResolver.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at async Graph._traverseDependenciesForSingleFile (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:249:5)
    at async Graph.traverseDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:157:9)
    at async DeltaCalculator._getChangedDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:281:42)
    at async DeltaCalculator.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:112:16)
    at async DeltaBundler.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler.js:67:12)
 ERROR  [Error: undefined Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);]
error: Error: Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);
    at ModuleResolver.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at async Graph._traverseDependenciesForSingleFile (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:249:5)
    at async Graph.traverseDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\Graph.js:157:9)
    at async DeltaCalculator._getChangedDependencies (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:281:42)
    at async DeltaCalculator.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:112:16)
    at async DeltaBundler.getDelta (C:\Users\WX662MZ\talic-monorepo-app\node_modules\metro\src\DeltaBundler.js:67:12)
 ERROR  [Error: undefined Unable to resolve module @nx/shared from C:\Users\WX662MZ\talic-monorepo-app\apps\talic-mobile\src\app\App.tsx:

None of these files exist:
  * ..\shared\src\index.ts(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * ..\shared\src\index.ts\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  12 | } from 'react-native';
  13 | import Svg, { Path } from 'react-native-svg';
> 14 | import { Shared } from '@nx/shared';
     |                         ^
  15 |
  16 | export const App = () => {
  17 |   // const [whatsNextYCoord, setWhatsNextYCoord] = useState<number>(0);]
```

### Package Manager Version

10.0.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

![image](https://github.com/nrwl/nx/assets/36719382/6e7d354c-4132-427b-b16b-8bc1b52d2f46)

**Comment by kasun-ascentic** [comment]
Facing this issue when I try to use share lib to react-native app. Any alternative solution to resolve this issue?

**Comment by xiongemi** [comment]
i investigated your repo, and found out the issue where just need to add the apps folder in your watchFolders. In your app's metro.config.js, add:

```
const { workspaceRoot } = require('@nx/devkit');
const { join } = require('path');

...
module.exports = withNxMetro(mergeConfig(defaultConfig, customConfig), {
  // Change this to true to see debugging info.
  // Useful if you have issues resolving modules
  debug: false,
  // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx', 'json'
  extensions: [],
  // Specify folders to watch, in addition to Nx defaults (workspace libraries and node_modules)
  watchFolders: [join(workspaceRoot, 'apps')],
});
```

the pr looks like: https://github.com/masinavinod410/Shared-Library-ReactWeb-ReactNative-with-Nx-workspaces/pull/2/files

currently, it only watches the libs folder. i will submit a proper fix to watch the entire workspace.
