### ISSUE TITLE
Running `npm i` on fresh repo created with `npx create-nx-workspace@latest`

### ISSUE THREAD

**Issue by memee** [nrwl/nx#19270]
### Current Behavior

After i run:
```
❯ npx create-nx-workspace@latest

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · org
✔ Which stack do you want to use? · node
✔ What framework should be used? · fastify
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · api
✔ Would you like to generate a Dockerfile? [https://docs.docker.com/] · Yes
fatal: to nie jest repozytorium gita: /Users/macio/./.bare
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.8.1 workspace.
```

Then

```
❯ cd org/
❯ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @nx/esbuild@16.8.1
npm ERR! Found: esbuild@0.17.19
npm ERR! node_modules/esbuild
npm ERR!   dev esbuild@"^0.17.17" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional esbuild@"~0.19.2" from @nx/esbuild@16.8.1
npm ERR! node_modules/@nx/esbuild
npm ERR!   dev @nx/esbuild@"16.8.1" from the root project
npm ERR!   @nx/esbuild@"16.8.1" from @nrwl/esbuild@16.8.1
npm ERR!   node_modules/@nrwl/esbuild
npm ERR!     @nrwl/esbuild@"16.8.1" from @nx/esbuild@16.8.1
npm ERR!
npm ERR! Conflicting peer dependency: esbuild@0.19.3
npm ERR! node_modules/esbuild
npm ERR!   peerOptional esbuild@"~0.19.2" from @nx/esbuild@16.8.1
npm ERR!   node_modules/@nx/esbuild
npm ERR!     dev @nx/esbuild@"16.8.1" from the root project
npm ERR!     @nx/esbuild@"16.8.1" from @nrwl/esbuild@16.8.1
npm ERR!     node_modules/@nrwl/esbuild
npm ERR!       @nrwl/esbuild@"16.8.1" from @nx/esbuild@16.8.1
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/macio/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macio/.npm/_logs/2023-09-21T08_53_21_034Z-debug-0.log
```

### Expected Behavior

I can run `npm i` on a fresh project without errors.

### Steps to Reproduce

1. `npx create-nx-workspace@latest`
2. type "org" or just hit return
3. choose "node"
4. choose "fastify"
5. choose "integrated"
6. type "api"
7. for Docker choose "yes"
8. for distributed caching choose "no"

### Nx Report

```shell
Node   : 18.12.0
   OS     : darwin-arm64
   npm    : 8.19.2

   nx (global)        : 16.8.1
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/esbuild        : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/node           : 16.8.1
   @nrwl/tao          : 16.8.1
   typescript         : 5.1.6
```
```


### Failure Logs

```shell
0 verbose cli /Users/macio/.nvm/versions/node/v18.12.0/bin/node /Users/macio/.nvm/versions/node/v18.12.0/bin/npm
1 info using npm@8.19.2
2 info using node@v18.12.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/macio/.nvm/versions/node/v18.12.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/macio/Projects/My/org/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/macio/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/macio/.nvm/versions/node/v18.12.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:mkdirpcache Completed in 0ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm i
23 verbose argv "i"
24 timing npm:load:setTitle Completed in 5ms
25 timing config:load:flatten Completed in 1ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:/Users/macio/.npm/_logs
28 verbose logfile /Users/macio/.npm/_logs/2023-09-21T08_53_21_034Z-debug-0.log
29 timing npm:load:logFile Completed in 3ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 17ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 169ms
37 timing idealTree:userRequests Completed in 1ms
38 silly idealTree buildDeps
39 timing idealTree:#root Completed in 0ms
40 silly fetch manifest esbuild@~0.19.2
41 timing arborist:ctor Completed in 0ms
42 http fetch GET 200 https://registry.npmjs.org/esbuild 132ms (cache hit)
43 timing idealTree Completed in 307ms
44 timing command:i Completed in 311ms
45 verbose stack Error: could not resolve
45 verbose stack     at PlaceDep.failPeerConflict (/Users/macio/.nvm/versions/node/v18.12.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:549:25)
45 verbose stack     at PlaceDep.place (/Users/macio/.nvm/versions/node/v18.12.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:199:21)
45 verbose stack     at new PlaceDep (/Users/macio/.nvm/versions/node/v18.12.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:73:10)
45 verbose stack     at /Users/macio/.nvm/versions/node/v18.12.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:944:31
45 verbose stack     at Array.map (<anonymous>)
45 verbose stack     at [buildDepStep] (/Users/macio/.nvm/versions/node/v18.12.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:944:8)
45 verbose stack     at async Arborist.buildIdealTree (/Users/macio/.nvm/versions/node/v18.12.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
45 verbose stack     at async Promise.all (index 1)
45 verbose stack     at async Arborist.reify (/Users/macio/.nvm/versions/node/v18.12.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
45 verbose stack     at async Install.exec (/Users/macio/.nvm/versions/node/v18.12.0/lib/node_modules/npm/lib/commands/install.js:145:5)
46 verbose cwd /Users/macio/Projects/My/org
47 verbose Darwin 22.6.0
48 verbose node v18.12.0
49 verbose npm  v8.19.2
50 error code ERESOLVE
51 error ERESOLVE could not resolve
52 error
53 error While resolving: [1m@nx/esbuild[22m@[1m16.8.1[22m
53 error Found: [1mesbuild[22m@[1m0.17.19[22m[2m[22m
53 error [2mnode_modules/esbuild[22m
53 error   [33mdev[39m [1mesbuild[22m@"[1m^0.17.17[22m" from the root project
53 error
53 error Could not resolve dependency:
53 error peerOptional [1mesbuild[22m@"[1m~0.19.2[22m" from [1m@nx/esbuild[22m@[1m16.8.1[22m[2m[22m
53 error [2mnode_modules/@nx/esbuild[22m
53 error   [33mdev[39m [1m@nx/esbuild[22m@"[1m16.8.1[22m" from the root project
53 error   [1m@nx/esbuild[22m@"[1m16.8.1[22m" from [1m@nrwl/esbuild[22m@[1m16.8.1[22m[2m[22m
53 error   [2mnode_modules/@nrwl/esbuild[22m
53 error     [1m@nrwl/esbuild[22m@"[1m16.8.1[22m" from [1m@nx/esbuild[22m@[1m16.8.1[22m
53 error
53 error Conflicting peer dependency: [1mesbuild[22m@[1m0.19.3[22m[2m[22m
53 error [2mnode_modules/esbuild[22m
53 error   peerOptional [1mesbuild[22m@"[1m~0.19.2[22m" from [1m@nx/esbuild[22m@[1m16.8.1[22m[2m[22m
53 error   [2mnode_modules/@nx/esbuild[22m
53 error     [33mdev[39m [1m@nx/esbuild[22m@"[1m16.8.1[22m" from the root project
53 error     [1m@nx/esbuild[22m@"[1m16.8.1[22m" from [1m@nrwl/esbuild[22m@[1m16.8.1[22m[2m[22m
53 error     [2mnode_modules/@nrwl/esbuild[22m
53 error       [1m@nrwl/esbuild[22m@"[1m16.8.1[22m" from [1m@nx/esbuild[22m@[1m16.8.1[22m
53 error
53 error Fix the upstream dependency conflict, or retry
53 error this command with --force, or --legacy-peer-deps
53 error to accept an incorrect (and potentially broken) dependency resolution.
53 error
53 error See /Users/macio/.npm/eresolve-report.txt for a full report.
54 verbose exit 1
55 timing npm Completed in 362ms
56 verbose unfinished npm timer reify 1695286401082
57 verbose unfinished npm timer reify:loadTrees 1695286401083
58 verbose unfinished npm timer idealTree:buildDeps 1695286401254
59 verbose unfinished npm timer idealTree:node_modules/@nx/esbuild 1695286401254
60 verbose code 1
61 error A complete log of this run can be found in:
61 error     /Users/macio/.npm/_logs/2023-09-21T08_53_21_034Z-debug-0.log
```
```


### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by mhabsaoui** [comment]
FYI I used `npx npm-check -u` to try all available minor/major updates (included API breaking packages).

`npm install eslint@8.49.0 typescript@5.2.2 @types/node@20.6.3 @typescript-eslint/eslint-plugin@6.7.2 @typescript-eslint/parser@6.7.2 eslint-config-prettier@9.0.0 prettier@3.0.3 esbuild@0.19.3 --save-dev --color=always --force`

Of course still unresolved dependencies...

![image](https://github.com/nrwl/nx/assets/18755135/3efa1e6e-790d-4e00-aa07-52ec6aa481b5)

**Comment by mhabsaoui** [comment]
FYI when genrating project with Yarn as package manager (I used the --allPrompts flag to be able to choose Yarn !), it seems there is no problem when adding new packages... 

![image](https://github.com/nrwl/nx/assets/18755135/ebb8f8c8-d9df-4f78-83d2-81ff5105acb9)

**Comment by w-ap-admin** [comment]
Which version of node are you using ? Because I had the same problem with Node 16.XX, but everything works fine with Node 18.XX

**Comment by mhabsaoui** [comment]
> Which version of node are you using ? Because I had the same problem with Node 16.XX, but everything works fine with Node 18.XX

I am using NVM

nvm -v    0.39.1
node -v   v18.9.0
npm -v    8.19.1

**Comment by medv** [comment]
Upgrading to `esbuild@latest` should resolve to `^0.19.3`, at which point the install process succeeds. Still unfamiliar with nx to know what the desired solution here is, reverting to nx packages seems to be the recommendation. Don't see the problem with bumping esbuild ourselves while we wait for this to be resolved in `@nx/esbuild`.

**Comment by erichardson30** [comment]
Any update here? Running into the same issue trying where everything scaffolds correctly and then running `npm i` or adding a package fails

**Comment by mjbates7** [comment]
I get the same issue (I'm running 16.10.0) where I couldn't install any package after creating the repo
