### ISSUE TITLE
Native file watcher ignores packages in an npm workspace

### ISSUE THREAD

**Issue by Gelio** [nrwl/nx#19312]
### Current Behavior

Changes to files in `packages/app/*` and `packages/lib/*` are ignored. No logs are printed to the console.

Creating a new directory (e.g. `packages/new/package.json`) DOES print watch events from that directory until the current `npm run watcher` process is running. Filling in `packages/new/package.json` with a basic configuration, doing an `npm install` (so the `new` package is installed in `node_modules`), and then restarting `npm run watcher` triggers the bug again - changes to `packages/new/*` are not picked up again.

The lack of watch events is problematic because Nx does not pick up changes to the targets configuration in individual packages' `package.json`, and it also does not invalidate the cache when a source file has been modified.

### Expected Behavior

Changes to `packages/**/*` are picked up by the native watcher.

### GitHub Repo

https://github.com/Gelio/nx-watcher-repro

### Steps to Reproduce

1. `npm install`
2. `NX_NATIVE_LOGGING=nx NX_LOGGING_NX=nx,watch npm run watcher`
3. Make a change to `package.json` (the one in the root of the repository) and save -> this will correctly show the update events in the watcher logs
4. Make any change in `packages/{app,lib}` (e.g. create a new file in either of those packages, or modify an existing file there) -> there will be no logs in the watcher process

Extra steps to show that new packages are watched until restart:
1. Create a new package `packages/new/package.json` with the following content:
    ```json
    {
      "name": "new",
      "version": "0.0.1",
      "private": true,
      "type": "module"
    }
    ```
2. Notice that the change is shown in the watcher's logs
3. `npm install` (this will make sure `packages/new` is symlinked as `node_modules/new`)
3. Restart the watcher `NX_NATIVE_LOGGING=nx NX_LOGGING_NX=nx,watch npm run watcher`
4. Make any change to `packages/new/package.json` (or the `packages/new` directory contents) -> this will NOT show any updates in the watcher's logs

### Nx Report

```shell
nx report

Reports useful version numbers to copy into the Nx issue template

Options:
  --help     Show help                                                                                                            [boolean]
  --version  Show version number                                                                                                  [boolean]

Error: ENOENT: no such file or directory, open '/home/voreny/projects/nx-watcher-repro/nx.json'
    at Object.openSync (node:fs:603:3)
    at readFileSync (node:fs:471:35)
    at readJsonFile (/home/voreny/projects/nx-watcher-repro/node_modules/nx/src/utils/fileutils.js:17:43)
    at getDependenciesFromNxJson (/home/voreny/projects/nx-watcher-repro/node_modules/nx/src/utils/plugins/installed-plugins.js:55:59)
    at findInstalledPlugins (/home/voreny/projects/nx-watcher-repro/node_modules/nx/src/utils/plugins/installed-plugins.js:15:24)
    at findInstalledCommunityPlugins (/home/voreny/projects/nx-watcher-repro/node_modules/nx/src/command-line/report/report.js:174:75)
    at getReportData (/home/voreny/projects/nx-watcher-repro/node_modules/nx/src/command-line/report/report.js:90:30)
    at async Object.reportHandler (/home/voreny/projects/nx-watcher-repro/node_modules/nx/src/command-line/report/report.js:39:134)
    at async Object.handler (/home/voreny/projects/nx-watcher-repro/node_modules/nx/src/command-line/report/command-object.js:8:9) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/voreny/projects/nx-watcher-repro/nx.json'
}
```

### Package Manager Version

npm v10.1.0

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

* Node v18.17.1
* Ubuntu 20.04.3 LTS

This issue is very similar to https://github.com/nrwl/nx/issues/18218, but that one is regarding Debian and pnpm.

When using pnpm and nx 16.9.0 (https://github.com/Gelio/nx-watcher-repro/commit/8d8068b7157b386785e6ec93babe94d0f45d387e), the problem still exists for me, but only changes to the `lib` package are ignored. Changes to the `app` package are shown in the watcher.

To me, this suggests that Nx ignores events from packages that are in `node_modules`. New packages (not yet present in `node_modules`) are watched until they are added to `node_modules` and the watcher is restarted.

**Comment by Cammisuli** [comment]
Hmm.. I tried reproducing this and I get updates when changing files:
![image](https://github.com/nrwl/nx/assets/4332460/72f55342-47b7-4bf8-b84d-8dbbae3a26c9)


This is my system info:
![image](https://github.com/nrwl/nx/assets/4332460/019d7cc4-ee01-4017-b0e0-0ca20da61b17)

I can try with Ubuntu 20 to see if that causes an issue.

**Comment by Gelio** [comment]
I ended up using Ubuntu 22.04.3 LTS

![image](https://github.com/nrwl/nx/assets/889383/80b6a012-9c3d-41d0-9097-7710451211bd)

and the problem still occurs for me:


https://github.com/nrwl/nx/assets/889383/edeac6a9-b307-4c2d-bef8-94ff1edfcc3f

I suspect it may not be reproducible for you since you're using an ARM-based CPU, and I have an x86_64 one. Not sure. Still, I can reproduce the problem on my machine

**Comment by Cammisuli** [comment]
Let me try on a x86 version of ubuntu.

**Comment by Cammisuli** [comment]
I had some help with someone running non-arm Linux and they were getting file updates. 

@Gelio can you run this command instead so that we can see all the logs that come from the underlying watch library too? `NX_NATIVE_LOGGING=trace npm run watcher`

**Comment by Gelio** [comment]
Sure!

<details>

<summary>Logs after modifying and saving `packages/lib/src/lib.ts` (update was not detected)</summary>

```log
2023-10-24T18:39:22.991065Z TRACE watchexec::fs: receiving possible event from watcher event=Ok(Event { kind: Modify(Data(Any)), paths: ["/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None })
2023-10-24T18:39:22.991094Z TRACE watchexec::fs: processed notify event into watchexec event event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Data(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts", file_type: Some(File) }], metadata: {} }
2023-10-24T18:39:22.991109Z TRACE watchexec::fs: receiving possible event from watcher event=Ok(Event { kind: Access(Close(Write)), paths: ["/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None })
2023-10-24T18:39:22.991121Z TRACE watchexec::fs: processed notify event into watchexec event event=Event { tags: [Source(Filesystem), FileEventKind(Access(Close(Write))), Path { path: "/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts", file_type: Some(File) }], metadata: {} }
2023-10-24T18:39:22.991130Z TRACE watchexec::fs: receiving possible event from watcher event=Ok(Event { kind: Modify(Metadata(Any)), paths: ["/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None })
2023-10-24T18:39:22.991130Z TRACE watchexec::action::worker: got event event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Data(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts", file_type: Some(File) }], metadata: {} } priority=Normal
2023-10-24T18:39:22.991142Z TRACE watchexec::fs: processed notify event into watchexec event event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Metadata(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts", file_type: Some(File) }], metadata: {} }
2023-10-24T18:39:22.991158Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts" file_type=Some(File)}: ignore_files::filter: checking against path or parents
2023-10-24T18:39:22.991176Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts" file_type=Some(File)}: watchexec_filterer_ignore: positive match (fail) glob=Glob { from: Some("/home/voreny/projects/nx-watcher-repro"), original: "node_modules/", actual: "**/node_modules", is_whitelist: false, is_only_dir: true }
2023-10-24T18:39:22.991187Z TRACE filterer_check: watchexec_filterer_ignore: verdict pass=false
2023-10-24T18:39:22.991192Z TRACE watchexec::action::worker: filter rejected event
2023-10-24T18:39:22.991196Z TRACE watchexec::action::worker: nothing in set, waiting forever for next event
2023-10-24T18:39:22.991199Z TRACE watchexec::action::worker: waiting for event maxtime=18446744073709551615s
2023-10-24T18:39:22.991207Z TRACE watchexec::action::worker: got event event=Event { tags: [Source(Filesystem), FileEventKind(Access(Close(Write))), Path { path: "/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts", file_type: Some(File) }], metadata: {} } priority=Normal
2023-10-24T18:39:22.991216Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts" file_type=Some(File)}: ignore_files::filter: checking against path or parents
2023-10-24T18:39:22.991222Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts" file_type=Some(File)}: watchexec_filterer_ignore: positive match (fail) glob=Glob { from: Some("/home/voreny/projects/nx-watcher-repro"), original: "node_modules/", actual: "**/node_modules", is_whitelist: false, is_only_dir: true }
2023-10-24T18:39:22.991228Z TRACE filterer_check: watchexec_filterer_ignore: verdict pass=false
2023-10-24T18:39:22.991232Z TRACE watchexec::action::worker: filter rejected event
2023-10-24T18:39:22.991235Z TRACE watchexec::action::worker: nothing in set, waiting forever for next event
2023-10-24T18:39:22.991237Z TRACE watchexec::action::worker: waiting for event maxtime=18446744073709551615s
2023-10-24T18:39:22.991241Z TRACE watchexec::action::worker: got event event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Metadata(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts", file_type: Some(File) }], metadata: {} } priority=Normal
2023-10-24T18:39:22.991249Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts" file_type=Some(File)}: ignore_files::filter: checking against path or parents
2023-10-24T18:39:22.991255Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/node_modules/lib/src/lib.ts" file_type=Some(File)}: watchexec_filterer_ignore: positive match (fail) glob=Glob { from: Some("/home/voreny/projects/nx-watcher-repro"), original: "node_modules/", actual: "**/node_modules", is_whitelist: false, is_only_dir: true }
2023-10-24T18:39:22.991261Z TRACE filterer_check: watchexec_filterer_ignore: verdict pass=false
2023-10-24T18:39:22.991264Z TRACE watchexec::action::worker: filter rejected event
2023-10-24T18:39:22.991267Z TRACE watchexec::action::worker: nothing in set, waiting forever for next event
2023-10-24T18:39:22.991269Z TRACE watchexec::action::worker: waiting for event maxtime=18446744073709551615s
```

</details>

<details>

<summary>Logs after modifying the root `package.json` (update was detected)</summary>

```log
2023-10-24T18:40:43.687193Z TRACE watchexec::fs: receiving possible event from watcher event=Ok(Event { kind: Modify(Data(Any)), paths: ["/home/voreny/projects/nx-watcher-repro/package.json"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None })
2023-10-24T18:40:43.687230Z TRACE watchexec::fs: processed notify event into watchexec event event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Data(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} }
2023-10-24T18:40:43.687248Z TRACE watchexec::fs: receiving possible event from watcher event=Ok(Event { kind: Access(Close(Write)), paths: ["/home/voreny/projects/nx-watcher-repro/package.json"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None })
2023-10-24T18:40:43.687258Z TRACE watchexec::fs: processed notify event into watchexec event event=Event { tags: [Source(Filesystem), FileEventKind(Access(Close(Write))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} }
2023-10-24T18:40:43.687267Z TRACE watchexec::fs: receiving possible event from watcher event=Ok(Event { kind: Modify(Metadata(Any)), paths: ["/home/voreny/projects/nx-watcher-repro/package.json"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None })
2023-10-24T18:40:43.687277Z TRACE watchexec::fs: processed notify event into watchexec event event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Metadata(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} }
2023-10-24T18:40:43.687276Z TRACE watchexec::action::worker: got event event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Data(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} } priority=Normal
2023-10-24T18:40:43.687335Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/package.json" file_type=Some(File)}: ignore_files::filter: checking against path or parents
2023-10-24T18:40:43.687369Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/package.json" file_type=Some(File)}: watchexec_filterer_ignore: no match (pass)
2023-10-24T18:40:43.687377Z TRACE filterer_check: watchexec_filterer_ignore: verdict pass=true
2023-10-24T18:40:43.687381Z TRACE nx::native::watch::watch_filterer: checking if event is valid event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Data(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} }
2023-10-24T18:40:43.687387Z TRACE nx::native::watch::watch_filterer: event passed all checks event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Data(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} }
2023-10-24T18:40:43.687393Z TRACE watchexec::action::worker: filter passed event
2023-10-24T18:40:43.687396Z TRACE watchexec::action::worker: event is the first, resetting throttle window
2023-10-24T18:40:43.687402Z TRACE watchexec::action::worker: still within throttle window, cycling elapsed=1.397µs
2023-10-24T18:40:43.687409Z TRACE watchexec::action::worker: waiting for event maxtime=49.991968ms
2023-10-24T18:40:43.687414Z TRACE watchexec::action::worker: got event event=Event { tags: [Source(Filesystem), FileEventKind(Access(Close(Write))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} } priority=Normal
2023-10-24T18:40:43.687422Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/package.json" file_type=Some(File)}: ignore_files::filter: checking against path or parents
2023-10-24T18:40:43.687427Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/package.json" file_type=Some(File)}: watchexec_filterer_ignore: no match (pass)
2023-10-24T18:40:43.687431Z TRACE filterer_check: watchexec_filterer_ignore: verdict pass=true
2023-10-24T18:40:43.687434Z TRACE nx::native::watch::watch_filterer: checking if event is valid event=Event { tags: [Source(Filesystem), FileEventKind(Access(Close(Write))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} }
2023-10-24T18:40:43.687439Z TRACE watchexec::action::worker: filter rejected event
2023-10-24T18:40:43.687443Z TRACE watchexec::action::worker: waiting for event maxtime=49.958095ms
2023-10-24T18:40:43.687447Z TRACE watchexec::action::worker: got event event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Metadata(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} } priority=Normal
2023-10-24T18:40:43.687455Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/package.json" file_type=Some(File)}: ignore_files::filter: checking against path or parents
2023-10-24T18:40:43.687458Z TRACE filterer_check:checking_against_compiled{path="/home/voreny/projects/nx-watcher-repro/package.json" file_type=Some(File)}: watchexec_filterer_ignore: no match (pass)
2023-10-24T18:40:43.687462Z TRACE filterer_check: watchexec_filterer_ignore: verdict pass=true
2023-10-24T18:40:43.687466Z TRACE nx::native::watch::watch_filterer: checking if event is valid event=Event { tags: [Source(Filesystem), FileEventKind(Modify(Metadata(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} }
2023-10-24T18:40:43.687471Z TRACE watchexec::action::worker: filter rejected event
2023-10-24T18:40:43.687475Z TRACE watchexec::action::worker: waiting for event maxtime=49.926177ms
2023-10-24T18:40:43.737983Z TRACE watchexec::action::worker: timed out, cycling
2023-10-24T18:40:43.738039Z TRACE watchexec::action::worker: out of throttle on recycle
2023-10-24T18:40:43.738048Z TRACE watchexec::action::worker: out of throttle, starting action process
2023-10-24T18:40:43.738059Z  INFO watchexec::action::worker: action constructed action=Action { events: [Event { tags: [Source(Filesystem), FileEventKind(Modify(Data(Any))), Path { path: "/home/voreny/projects/nx-watcher-repro/package.json", file_type: Some(File) }], metadata: {} }], outcome: OnceCell(Uninit) }
2023-10-24T18:40:43.738080Z DEBUG watchexec::action::worker: running action handler
2023-10-24T18:40:43.738099Z TRACE nx::native::watch::watcher: origin_path="/home/voreny/projects/nx-watcher-repro/"
2023-10-24T18:40:43.738111Z TRACE nx::native::watch::types: event kind -> event type path=("/home/voreny/projects/nx-watcher-repro/package.json", Some(File)) event_kind=Modify(Data(Any)) event_type=update
2023-10-24T18:40:43.738150Z DEBUG watchexec::action::worker: action handler finished outcome=Start
2023-10-24T18:40:43.738161Z  INFO watchexec::action::worker: outcome resolved outcome=Start
2023-10-24T18:40:43.738167Z DEBUG watchexec::action::outcome_worker: spawning outcome worker outcome=Start gen=2
2023-10-24T18:40:43.738201Z DEBUG watchexec::action::worker: action process done
2023-10-24T18:40:43.738208Z TRACE watchexec::action::worker: nothing in set, waiting forever for next event
2023-10-24T18:40:43.738213Z TRACE watchexec::action::worker: waiting for event maxtime=18446744073709551615s
2023-10-24T18:40:43.738249Z  WARN watchexec::action::outcome_worker: tried to start commands without anything to run
2023-10-24T18:40:43.738261Z DEBUG watchexec::action::outcome_worker: outcome worker finished outcome=Start gen=2
2023-10-24T18:40:43.738253Z TRACE nx::native::watch::watcher: Base collection that will be sent ctx.value={"/home/voreny/projects/nx-watcher-repro/package.json": WatchEventInternal { path: "/home/voreny/projects/nx-watcher-repro/package.json", type: update, origin: Some("/home/voreny/projects/nx-watcher-repro/") }}
2023-10-24T18:40:43.738296Z TRACE nx::native::watch::watcher: sending to node watch_events=[WatchEvent { path: "package.json", type: update }]
[ { path: 'package.json', type: 'update' } ]
```

</details>

**Comment by Cammisuli** [comment]
yea, there's something up with the symlinks... The system is reporting that lib.ts file changes are coming from node_modules (`nx-watcher-repro/node_modules/lib/src/lib.ts`) and that gets caught by the node_modules gitignore...

What version of npm are you using? For reference mine is `9.6.6`. Maybe the way that npm set up the symlinks is weird?

**Comment by Gelio** [comment]
I am on npm 10.2.1

Not sure if there is anything special about the symlinks that npm creates. I just removed the `node_modules/lib` one and created it from the CLI:

```sh
rm node_modules/lib
ln -s ../packages/lib node_modules/lib
```

and the behavior is still the same - the watcher picks up the change from `node_modules/lib/src/lib.ts`, not `packages/lib/src/lib.ts`.

**Comment by Gelio** [comment]
From what I can tell, this problem is the same as https://github.com/watchexec/watchexec/issues/508 and may have a common cause.

**Comment by Gelio** [comment]
The problem seems to be at a much deeper level. The [notify](https://docs.rs/notify/latest/notify/) crate sets up the inotify watchers for both `packages/lib` **and** `node_modules/lib`. The latter is registered later. inotify provides events only for the latter.

My assumption is that inotify (the Linux API for watching the filesystem) notices that those 2 watchers are for the same target (`packages/lib`), and it replaces the first watcher (for `packages/lib` directly) with the second watcher (that goes through `node_modules/lib`). Then, when there are any events for that directory, the latest watcher that receives events is the one that starts with `node_modules/lib`.

I suggested using `fs::canonicalize` to resolve symlinks before filtering files in https://github.com/watchexec/watchexec/issues/508#issuecomment-1778913330.

**Comment by Cammisuli** [comment]
We do canonicalize in the Nx source for only debian and arch based repos. I may just modify the code so that we canonicalize the path for every linux distro instead. The relevant code is here:
[pub(super) fn transform_event(watch_event: &Event) -> Option<Event>](https://github.com/nrwl/nx/blob/8932b069f55261433c10dbf5c0c32456656cefed/packages/nx/src/native/watch/utils.rs#L61-L88)
