### ISSUE TITLE
Cypress fails complaining about headers-polyfill

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#19325]
### Current Behavior

I've updated my `msw` dependency from `1.2.3` to `1.3.1`, tried to serve my application - worked as expected, then I run my e2e tests and got an error message that made no sense.

I have noticed in my .yarn.lock file that headers-polyfill gets updated from 3.1.0 to 3.2.5 and that's when the error occurs. Has nothing to do with the MSW library, directly.

I've also experienced this when I've tried migrating NX.

### Expected Behavior

I expect that if the dependency brings forth an error and it works when serving the app, that it also works when running the cypress tests.

### Steps to Reproduce

1. Install the msw@1.3.1
2. Run the e2e test in the app that consumes the msw library

### Nx Report

```shell
Node   : 18.15.0
   OS     : linux-x64
   yarn   : 3.6.3
   
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/react          : 16.7.4
   @nx/vite           : 16.7.4
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   typescript         : 5.1.6
```

### Failure Logs

```shell
Running:  app.cy.ts                                                                       (1 of 1)
Oops...we found an error preparing this test file:

  > cypress/support/e2e.ts

The error was:

  Error: Webpack Compilation Error
/home/user/www/app/.yarn/cache/headers-polyfill-npm-3.2.5-5873ac13a0-a3c4bdd661.zip/node_modules/headers-polyfill/lib/index.mjs 285:53
Module parse failed: Unexpected token (285:53)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  |     this[_a] = {};
|     this[_b] = /* @__PURE__ */ new Map();
>     if (["Headers", "HeadersPolyfill"].includes(init?.constructor.name) || init instanceof HeadersPolyfill) {
|       const initialHeaders = init;
|       initialHeaders.forEach((value, name) => {
  @ /home/user/www/app/.yarn/unplugged/msw-virtual-e018ea81ad/node_modules/msw/lib/index.js 147:30-57 304:31-58 542:31-58 549:31-58 574:31-58 927:31-58 1002:31-58 1005:31-58 1610:31-58
  @ /home/user/www/app/libs/orchestrator-mocks/src/mocks/handlers/rest/post/error-logger.post.ts
  @ /home/user/www/app/libs/orchestrator-mocks/src/mocks/handlers.ts
  @ /home/user/www/app/libs/orchestrator-mocks/src/index.ts
  @ ./cypress/support/e2e.ts
    at handle (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at finalCallback (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
      at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:304:22
      at Compiler.emitRecords (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:499:39)
      at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:298:10
      at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:485:14
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
        at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:482:27
        at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/neo-async/async.js:2818:7
        at done (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/neo-async/async.js:3522:9)
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
          at AsyncSeriesHook.lazyCompileHook (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
          at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:464:33
          at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
          at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
          at /home/user/www/app/.pnp.cjs:31776:13
          at Object.createDeferred (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/lib/utils.js:10:19)
          at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:181:43
          at Object.handler (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-batteries-included-preprocessor/index.js:176:40)
          at invoke (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:183:18)
          at /home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:59:14
          at Object.wrapChildPromise (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:58:23)
          at Object.wrap (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/preprocessor.js:47:8)
          at RunPlugins.execute (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:157:29)
          at EventEmitter.<anonymous> (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:56:12)
            at EventEmitter.emit (node:events:513:28)
            at process.<anonymous> (/home/user/.cache/Cypress/12.17.2/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
              at process.emit (node:events:513:28)
              at process.emit (/home/user/www/app/.pnp.cjs:36463:25)
              at emit (node:internal/child_process:937:14)
              at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
              From previous event:
              at Object.getFile (<embedded>:4594:14887)
                at Object.handle (<embedded>:4594:15891)
                  at <embedded>:4633:67382
                    at a.handle_request (<embedded>:2640:1038)
                      at d (<embedded>:2655:1285)
                        at p.dispatch (<embedded>:2655:1307)
                          at a.handle_request (<embedded>:2640:1038)
                            at <embedded>:2663:3353
                              at y.process_params (<embedded>:2663:4284)
                                at h (<embedded>:2663:3296)
                                  at y.handle (<embedded>:2663:4188)
                                    at o (<embedded>:2663:1048)
                                      at a.handle_request (<embedded>:2640:1038)
                                        at <embedded>:2663:3774
                                          at <embedded>:2663:3796
                                            at y.process_params (<embedded>:2663:4284)
                                              at h (<embedded>:2663:3296)
                                                at a.handle_request (<embedded>:2640:1030)
                                                  at <embedded>:2663:3774
                                                    at <embedded>:2663:3796
                                                      at y.process_params (<embedded>:2663:4284)
                                                        at h (<embedded>:2663:3296)
                                                          at <embedded>:2463:2495
                                                            at a.handle_request (<embedded>:2640:1038)
                                                              at <embedded>:2663:3774
                                                                at <embedded>:2663:3796
                                                                  at y.process_params (<embedded>:2663:4284)
                                                                    at h (<embedded>:2663:3296)
                                                                      at <embedded>:2483:1024
                                                                        at a.handle_request (<embedded>:2640:1038)
                                                                          at <embedded>:2663:3774
                                                                            at <embedded>:2663:3796
                                                                              at y.process_params (<embedded>:2663:4284)
                                                                                at h (<embedded>:2663:3296)
                                                                                  at <embedded>:4633:80256
                                                                                    at a.handle_request (<embedded>:2640:1038)
                                                                                      at <embedded>:2663:3774
                                                                                        at <embedded>:2663:3796
                                                                                          at y.process_params (<embedded>:2663:4284)
                                                                                            at h (<embedded>:2663:3296)
                                                                                              at <embedded>:4633:79931
                                                                                                at a.handle_request (<embedded>:2640:1038)
                                                                                                  at <embedded>:2663:3774
                                                                                                    at <embedded>:2663:3796
                                                                                                      at y.process_params (<embedded>:2663:4284)
                                                                                                        at h (<embedded>:2663:3296)
                                                                                                          at <embedded>:2671:330
                                                                                                            at a.handle_request (<embedded>:2640:1038)
                                                                                                              at <embedded>:2663:3774
                                                                                                                at <embedded>:2663:3796
                                                                                                                  at y.process_params (<embedded>:2663:4284)
                                                                                                                    at h (<embedded>:2663:3296)
                                                                                                                      at <embedded>:2679:544
                                                                                                                        at a.handle_request (<embedded>:2640:1038)
                                                                                                                          at <embedded>:2663:3774
                                                                                                                            at <embedded>:2663:3796
                                                                                                                              at y.process_params (<embedded>:2663:4284)
                                                                                                                                at h (<embedded>:2663:3296)
                                                                                                                                  at y.handle (<embedded>:2663:4188)
                                                                                                                                    at T.handle (<embedded>:2735:3475)
                                                                                                                                      at Server.e (<embedded>:2766:742)
                                                                                                                                        at Server.<anonymous> (<embedded>:4357:71058)
                                                                                                                                          at <embedded>:4633:82963
                                                                                                                                            at Array.map (<anonymous>)
                                                                                                                                              at q._callRequestListeners (<embedded>:4633:82953)
                                                                                                                                                at Server.<anonymous> (<embedded>:4633:83103)
                                                                                                                                                  at Server.emit (node:events:527:28)
                                                                                                                                                  at parserOnIncoming (node:_http_server:956:12)
                                                                                                                                                  at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)

                                                                                                                                                  This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

                                                                                                                                                  - A missing file or dependency
                                                                                                                                                  - A syntax error in the file or one of its dependencies
```

### Package Manager Version

yarn: 3.6.3

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by nchery** [comment]
@nemonemi by any chance do you happen to have found a solution , i run into something similar
