### ISSUE TITLE
TypeError: WorkspaceContext is not a constructor 16.9.1

### ISSUE THREAD

**Issue by richlim** [nrwl/nx#19350]
### Current Behavior

Hello,
after upgrading to 16.9.1 nx won't compile.

/Users/rlima/Devel/GitHub/ntc/node_modules/.pnpm/nx@16.9.1/node_modules/nx/src/utils/workspace-context.js:9
    workspaceContext = new WorkspaceContext(workspaceRoot);

### Expected Behavior

nx module should compile

### Steps to Reproduce

nx migrate nx@16.9.1

### Nx Report

```shell
1.
 >  NX   Report complete - copy this into the issue template

   Node   : 20.4.0
   OS     : darwin-x64
   pnpm   : 8.6.7
   
   nx (global)        : 16.5.1
   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/angular        : 16.9.1
   @nx/cypress        : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nrwl/tao          : 16.5.1
   @nx/web            : 16.9.1
   nx-cloud           : 16.4.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @ngrx/component       : 16.1.0
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/schematics      : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/tao@16.5.1
   
   To fix this, run `nx migrate nx@16.9.1`

rlima@Richard-MBP ntc % nx migrate nx@16.9.1
/Users/rlima/Devel/GitHub/ntc/node_modules/.pnpm/nx@16.9.1/node_modules/nx/src/utils/workspace-context.js:9
    workspaceContext = new WorkspaceContext(workspaceRoot);
                       ^

TypeError: WorkspaceContext is not a constructor
    at setupWorkspaceContext (/Users/rlima/Devel/GitHub/ntc/node_modules/.pnpm/nx@16.9.1/node_modules/nx/src/utils/workspace-context.js:9:24)
    at main (/Users/rlima/Devel/GitHub/ntc/node_modules/.pnpm/nx@16.9.1/node_modules/nx/bin/nx.js:51:59)
    at Object.<anonymous> (/Users/rlima/Devel/GitHub/ntc/node_modules/.pnpm/nx@16.9.1/node_modules/nx/bin/nx.js:238:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at main (/opt/pnpm/global/5/.pnpm/nx@16.5.1/node_modules/nx/bin/nx.js:69:17)

Node.js v20.4.0
```

### Failure Logs

```shell
node_modules/.pnpm/nx@16.9.1/node_modules/nx: Running postinstall script, done in 2.1s

devDependencies:
- @nx/angular 16.8.1
+ @nx/angular 16.9.1
- @nx/cypress 16.8.1
+ @nx/cypress 16.9.1
- @nx/eslint-plugin 16.8.1
+ @nx/eslint-plugin 16.9.1
- @nx/jest 16.8.1
+ @nx/jest 16.9.1
- @nx/js 16.8.1
+ @nx/js 16.9.1
- @nx/linter 16.8.1
+ @nx/linter 16.9.1
- @nx/web 16.8.1
+ @nx/web 16.9.1
- @nx/workspace 16.8.1
+ @nx/workspace 16.9.1
- nx 16.8.1
+ nx 16.9.1

 WARN  Issues with peer dependencies found
.
└─┬ @angular-devkit/build-angular 16.2.0
  ├── ✕ unmet peer jest@^29.5.0: found 29.4.1
  └── ✕ unmet peer jest-environment-jsdom@^29.5.0: found 29.4.1

The integrity of 2315 files was checked. This might have caused installation to take longer.
Done in 16.1s
/Users/rlima/Devel/GitHub/ntc/node_modules/.pnpm/nx@16.9.1/node_modules/nx/src/utils/workspace-context.js:9
    workspaceContext = new WorkspaceContext(workspaceRoot);
                       ^

TypeError: WorkspaceContext is not a constructor
    at setupWorkspaceContext (/Users/rlima/Devel/GitHub/ntc/node_modules/.pnpm/nx@16.9.1/node_modules/nx/src/utils/workspace-context.js:9:24)
    at main (/Users/rlima/Devel/GitHub/ntc/node_modules/.pnpm/nx@16.9.1/node_modules/nx/bin/nx.js:51:59)
    at Object.<anonymous> (/Users/rlima/Devel/GitHub/ntc/node_modules/.pnpm/nx@16.9.1/node_modules/nx/bin/nx.js:238:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at main (/opt/pnpm/global/5/.pnpm/nx@16.5.1/node_modules/nx/bin/nx.js:69:17)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by richlim** [comment]
after going back to 16.8.1 and then to 16.9.1 the problem vanished
