### ISSUE TITLE
React Module Federation with SSR not working

### ISSUE THREAD

**Issue by merto20** [nrwl/nx#19394]
### Current Behavior

'npx nx serve store'  command throws an error.

### Expected Behavior

Application should run.

### Steps to Reproduce

1. Follow steps from this article: [](https://nx.dev/recipes/react/module-federation-with-ssr)

### Nx Report

```shell
npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : linux-x64
   npm    : 9.8.1
   
   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/cypress        : 16.9.1
   @nx/devkit         : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nx/next           : 16.9.1
   @nx/react          : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/web            : 16.9.1
   @nx/webpack        : 16.9.1
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
```

### Failure Logs

```shell
npx nx serve store --verbose

> nx run store:serve:development


 >  NX   RunStart

   
{
  "meta": {
    "nxCloudVersion": "latest"
  },
  "branch": null,
  "runGroup": "ba4d225cb8835633cc8d5a4f20d7d2ab10ee061e",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "15540246294565773718"
  ]
}


 >  NX   Could not load /org/apps/store/module-federation.config.js. Was this project generated with "@nx/react:host"?


Error: Could not load /org/apps/store/module-federation.config.js. Was this project generated with "@nx/react:host"?
    at moduleFederationSsrDevServer (/org/node_modules/@nx/react/src/executors/module-federation-ssr-dev-server/module-federation-ssr-dev-server.impl.js:19:15)
    at moduleFederationSsrDevServer.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/org/node_modules/nx/src/utils/async-iterator.js:13:27)
    at iteratorToProcessStatusCode (/org/node_modules/nx/src/command-line/run/run.js:41:94)
    at /org/node_modules/nx/src/command-line/run/run.js:154:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/org/node_modules/nx/src/utils/params.js:9:16)
    at async process.<anonymous> (/org/node_modules/nx/bin/run-executor.js:59:28)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project store failed

   Failed tasks:
   
   - store:serve:development
   
   Hint: run the command with --verbose for more details.

   View structured, searchable error logs at https://nx.app/runs/tXqAYCwc8Z
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by merto20** [comment]
[Missing article] https://nx.dev/recipes/react/module-federation-with-ssr

**Comment by KalanaPerera** [comment]
having the same problem: +1
