### ISSUE TITLE
Migration from nx11 up is broken by tao

### ISSUE THREAD

**Issue by cakeinpanic** [nrwl/nx#19418]
### Current Behavior

I have a project using nx 11, I'm running `nx migrate @nrwl/workspace@14`
and getting this stack trace
```
Error: Command failed: npm install --legacy-peer-deps
at checkExecSyncError (child_process.js:790:11)
at Object.execSync (child_process.js:863:15)
at taoPath (/Users/cakeinpanic/projects/project/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:303:21)
at Object.handler (/Users/cakeinpanic/projects/project/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:79:19)
at Object.runCommand (/Users/cakeinpanic/projects/project/node_modules/yargs/build/lib/command.js:196:48)
at Object.parseArgs [as _parseArgs] (/Users/cakeinpanic/projects/project/node_modules/yargs/build/lib/yargs.js:1043:55)
at Object.get [as argv] (/Users/cakeinpanic/projects/project/node_modules/yargs/build/lib/yargs.js:986:25)
at Object.initLocal (/Users/cakeinpanic/projects/project/node_modules/@nrwl/cli/lib/init-local.js:23:13)
at Object.<anonymous> (/Users/cakeinpanic/projects/project/node_modules/@nrwl/cli/bin/nx.js:42:18)
at Module._compile (internal/modules/cjs/loader.js:1085:14) {
```

after debugging I realized that issue is that process tries to install latest `tao` version and it throws incompatibility error

I found a solution for it – I'm going to the first file in the stacktrace – `/Users/cakeinpanic/projects/project/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:303:21`, add these changes and rerun migration command, all finishes successfully 
```diff
 fs_1.writeFileSync(path.join(tmpDir, 'package.json'), JSON.stringify({
        dependencies: {
-            '@nrwl/tao': 'latest',
+            '@nrwl/tao': '14',
            // these deps are required for migrations written using angular devkit
            '@angular-devkit/architect': 'latest',
            '@angular-devkit/schematics': 'latest',
            '@angular-devkit/core': 'latest',
        },
        license: 'MIT',
    }));
```

### Expected Behavior

Work smoothly (this behaviour appeared only about 1-2 weeks ago)

### Steps to Reproduce

1. create new project using nx11
2. run `nx migrate @nrwl/workspace@14`

### Nx Report

```shell
Node : 14.20.1
  OS   : darwin x64
  npm  : 6.14.17
  
  nx : Not Found
  @nrwl/angular : 11.6.2
  @nrwl/cli : 11.6.2
  @nrwl/cypress : 11.6.2
  @nrwl/devkit : 11.6.2
  @nrwl/eslint-plugin-nx : 11.6.2
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.2
  @nrwl/linter : 11.6.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.6.2
  @nrwl/react : 11.6.2
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 11.6.2
  @nrwl/web : 11.6.2
  @nrwl/workspace : 11.6.2
  @nrwl/storybook : 11.6.2
  @nrwl/gatsby : Not Found
  typescript : 4.0.5
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Can you try running with NX_MIGRATE_USE_LOCAL=true?

**Comment by cakeinpanic** [comment]
@AgentEnder it helped, thank you!

**Comment by cakeinpanic** [comment]
@AgentEnder however together with working smoothly command with this flag _did not update_ angular dependencies in package.json

Compare outputs

```
> NX_MIGRATE_USE_LOCAL=true nx migrate @nrwl/workspace@14

Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@14.0.0
Fetching prettier@^2.5.1
Fetching typescript@~4.3.5
Fetching dotenv@~10.0.0
Fetching @nrwl/angular@14.0.0
Fetching @nrwl/cli@14.0.0
Fetching @nrwl/cypress@14.0.0
Fetching @nrwl/devkit@14.0.0
Fetching @nrwl/eslint-plugin-nx@14.0.0
Fetching @nrwl/jest@14.0.0
Fetching @nrwl/linter@14.0.0
Fetching @nrwl/tao@14.0.0
Fetching jest-preset-angular@9.0.3
Fetching ts-jest@27.1.4
Fetching jest@27.5.1
Fetching @types/jest@27.4.1
Fetching babel-jest@27.5.1
Fetching @typescript-eslint/experimental-utils@~5.18.0
Fetching prettier@2.8.8
Fetching typescript@4.3.5
Fetching dotenv@10.0.0
Fetching @typescript-eslint/experimental-utils@5.18.0

>  NX  The migrate command has run successfully.
```

without flag
```
> nx migrate @nrwl/workspace@14 --verbose

Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@14.0.0
Fetching @nrwl/angular@14.0.0
Fetching @angular/cdk@13.3.9
Fetching @angular/core@13.3.11
Fetching @angular/cli@13.3.11
Fetching @angular/cli@~13.3.0

 >  NX   The migrate command has run successfully.

```
