### ISSUE TITLE
@nx/js:node fails when build target includes 'additionalEntryPoints'

### ISSUE THREAD

**Issue by pedropmedina** [nrwl/nx#19412]
### Current Behavior

When defining 'additionalEntryPoints' in the build target (in my case I'm building with @nx/esbuild:esbuild) the @nx/js:node server fails to find the main compiled file. Below it's my setup. Is there anything missing? I've read the docs several times and I can't find a solution. 

Also I was wondering if there was a way of defining the output path for the 'additionalEntryPoints'?

```json
  "targets": {
    "build": {
      "executor": "@nx/esbuild:esbuild",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "skipTypeCheck": false,
        "platform": "node",
        "outputPath": "dist/apps/auth/api",
        "format": ["esm"],
        "thirdParty": false,
        "bundle": true,
        "main": "apps/auth/api/src/main.ts",
        "tsConfig": "apps/auth/api/tsconfig.app.json",
        "assets": ["apps/auth/api/src/assets"],
        "additionalEntryPoints": ["libs/auth/db/src/lib/migrate.ts"],
        "generatePackageJson": true,
        "esbuildOptions": {
          "sourcemap": true,
          "outExtension": {
            ".js": ".js"
          }
        }
      },
      "configurations": {
        "development": {},
        "production": {
          "generateLockfile": true,
          "esbuildOptions": {
            "sourcemap": false,
            "outExtension": {
              ".js": ".js"
            }
          }
        }
      }
    },
    "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "auth-api:build"
      },
      "configurations": {
        "development": {
          "buildTarget": "auth-api:build:development"
        },
        "production": {
          "buildTarget": "auth-api:build:production"
        }
      }
    }
```

### Expected Behavior

Node server to find the correct entry file and start the server.

### Steps to Reproduce

Use my setup with 'additionalEntryPoints' and it should fail to run.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : darwin-arm64
   npm    : 9.6.7

   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/cypress        : 16.9.1
   @nx/devkit         : 16.9.1
   @nrwl/devkit       : 15.9.7
   @nx/esbuild        : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nx/express        : 16.9.1
   @nx/next           : 16.9.1
   @nx/node           : 16.9.1
   @nx/react          : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/web            : 16.9.1
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 4.0.4
   @nx-tools/nx-prisma    : 5.0.3
   ---------------------------------------
```

### Failure Logs

```shell
[ watch ] build succeeded, watching for changes...
/Users/pedropmedina/code/ricoma/ricoma/node_modules/@nx/js/src/executors/node/node.impl.js:286
    throw new Error(`Could not find ${fileToRun}. Make sure your build succeeded.`);
          ^

Error: Could not find /Users/pedropmedina/code/ricoma/ricoma/dist/apps/auth/api/main.js. Make sure your build succeeded.
    at fileToRunCorrectPath (/Users/pedropmedina/code/ricoma/ricoma/node_modules/@nx/js/src/executors/node/node.impl.js:286:11)
    at /Users/pedropmedina/code/ricoma/ricoma/node_modules/@nx/js/src/executors/node/node.impl.js:97:49
    at new Promise (<anonymous>)
    at Object.start (/Users/pedropmedina/code/ricoma/ricoma/node_modules/@nx/js/src/executors/node/node.impl.js:91:36)
    at async Timeout.processQueue [as _onTimeout] (/Users/pedropmedina/code/ricoma/ricoma/node_modules/@nx/js/src/executors/node/node.impl.js:62:13)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Todberg** [comment]
I'm facing the same issue with @nx/rollup:rollup where additionalEntryPoints is defined as a [string array](https://nx.dev/nx-api/rollup/executors/rollup#additionalentrypoints). but should to be an array of objects similar to how @nx/webpack:webpack defines it: https://nx.dev/nx-api/webpack/executors/webpack#additionalentrypoints.

Right now it just assumes that the file is in the root. I would like to define it as follows:

```ts
"additionalEntryPoints": [
  { "name": "./foo", "path": "./lib/foo/index.ts" }
]
```
