### ISSUE TITLE
expanded task env variables are immediately overwritten by not expanded vars

### ISSUE THREAD

**Issue by BorisTB** [nrwl/nx#19437]
### Current Behavior

Task env variables that are expanded are immediately overwritten by original values. So expand doesn't work for tasks.

1. env file is loaded with dotenv: https://github.com/nrwl/nx/blob/601b74d50e8b78fc46aae8e8c862667b8b51b0b2/packages/nx/src/tasks-runner/forked-process-task-runner.ts#L447-L452
2. dotenv populates processEnv (environmentVariables):  https://github.com/motdotla/dotenv/blob/cf4c56957974efb7238ecaba6f16e0afa895c194/lib/main.js#L205
3. env values are expanded: https://github.com/nrwl/nx/blob/601b74d50e8b78fc46aae8e8c862667b8b51b0b2/packages/nx/src/tasks-runner/forked-process-task-runner.ts#L453-L459
4. expanded values are overwritten by original values (populated by dotenv): https://github.com/nrwl/nx/blob/601b74d50e8b78fc46aae8e8c862667b8b51b0b2/packages/nx/src/tasks-runner/forked-process-task-runner.ts#L458

### Expected Behavior

task runner will expand env variables

### Steps to Reproduce

1. create app, e.g. apps/my-app (i used @nx/nest)
2. create dotenv for app, e.g. apps/my-app/.env
3. edit .env to look like this
```
NX_FOO=foo
NX_BAR=$NX_FOO
```
4. somewhere in app use process.env['NX_BAR']
5. run app, nx serve my-app
6. value of process.env.NX_BAR is "$NX_FOO"

### Nx Report

```shell
Node   : 20.1.0
   OS     : darwin-x64
   yarn   : 3.6.3
   
   nx (global)        : 16.9.1
   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/cypress        : 16.9.1
   @nx/devkit         : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nx/nest           : 16.9.1
   @nx/node           : 16.9.1
   @nx/plugin         : 16.9.1
   @nx/react          : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/vite           : 16.9.1
   @nx/web            : 16.9.1
   @nx/webpack        : 16.9.1
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.0.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by BorisTB** [comment]
Hey, tried it with v17.0.2 and issue's still there. It's here in the source code

https://github.com/nrwl/nx/blob/3e0f5c4993fda9be7a7ab5c4e60eecac8de7eaba/packages/nx/src/tasks-runner/task-env.ts#L175-L180

**Comment by nocnokneo** [comment]
This is affecting my usage of nested .env variables with vite. However I seem to be able to workaround the problem for the `serve` target if I don't run nx from the repo root. e.g.

```bash
cd apps/cloud-ui
nx serve cloud-ui # works: the value of NX_BAR is 'foo'
cd ../..
nx serve cloud-ui # broken: the value of NX_BAR is '$NX_FOO'
```

However this does not work with the `build` target:

```bash
cd apps/cloud-ui
nx build cloud-ui --verbose

> nx run cloud-ui:build:production


 >  NX   The "path" argument must be of type string. Received undefined


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at join (node:path:1172:7)
    at validateTypes (/home/tbj/git/cyto/node_modules/.pnpm/@nx+vite@17.0.2_@swc+core@1.3.91_@types+node@18.14.2_nx@17.0.2_typescript@5.1.6_vite@4.3.9_vitest@0.32.4/node_modules/@nx/vite/src/utils/executor-utils.js:22:38)
    at viteBuildExecutor (/home/tbj/git/cyto/node_modules/.pnpm/@nx+vite@17.0.2_@swc+core@1.3.91_@types+node@18.14.2_nx@17.0.2_typescript@5.1.6_vite@4.3.9_vitest@0.32.4/node_modules/@nx/vite/src/executors/build/build.impl.js:34:48)
    at async getLastValueFromAsyncIterableIterator (/home/tbj/git/cyto/node_modules/.pnpm/nx@17.0.2_@swc+core@1.3.91/node_modules/nx/src/utils/async-iterator.js:13:19)
    at async iteratorToProcessStatusCode (/home/tbj/git/cyto/node_modules/.pnpm/nx@17.0.2_@swc+core@1.3.91/node_modules/nx/src/command-line/run/run.js:41:29)
    at async handleErrors (/home/tbj/git/cyto/node_modules/.pnpm/nx@17.0.2_@swc+core@1.3.91/node_modules/nx/src/utils/params.js:9:16)
    at async process.<anonymous> (/home/tbj/git/cyto/node_modules/.pnpm/nx@17.0.2_@swc+core@1.3.91/node_modules/nx/bin/run-executor.js:59:28)
```

This is with Nx 17.0.2

**Comment by BorisTB** [comment]
The possible fix is `processenv: { …environmentVariables },` but idk how to write tests for it

**Comment by nocnokneo** [comment]
Still an issue.

nx serve foo # broken: ${vars} in vite .env files do not get expanded
cd apps/foo && vite serve # works

**Comment by PierreNicoletti** [comment]
I confirm this is still an issue. Expanded env variables can't be used.

**Comment by mattfysh** [comment]
yikes, there should probably be a test for this. is everything okay at nx, this is beyond low hanging fruit. this is fruit that's already dropped to the ground and slowly rotting away

**Comment by BioPaulK** [comment]
Are there any updates on this issue? We're running into the same thing right now, we can't use env var expansion in any of our tasks.

**Comment by nocnokneo** [comment]
still broken as of v20.3.2

**Comment by BorisTB** [comment]
I created this issue when I started at my new job. Now, almost two years later, I’m leaving that job and the problem is still caused by the exact same line of code I pointed out in the beginning 😃

I still have no idea how to write tests for it, but this time I’m coming armed with four different AIs, one of which even studied in China, so I might try again to fix it.

**Comment by manojdcoder** [comment]
I have `.env.local` at workspace root

```
NX_BAR=$NX_FOO
```

`.env.local` at project root

```
NX_FOO=foo
```

nx serve works, prints `foo`. But does not work with custom targets using nx:run-commands

Nx version: 22.3.3

**Comment by manojdcoder** [comment]
I think it was just the order of the env files. 

I was passing `envFile` from a `project.json` target, which appears to be loaded after all [default env files](https://nx.dev/docs/guides/tips-n-tricks/define-environment-variables#set-environment-variables). Using a default project specific env file works and variables are expanded as expected.
