### ISSUE TITLE
Custom Angular Executor no longer works in 16.9.0 -16.10.0

### ISSUE THREAD

**Issue by skrtheboss** [nrwl/nx#19475]
### Current Behavior

Custom angular build executor no longer works if used in combination with `useDaemonProcess: false`.

I found that the regression has been caused by https://github.com/nrwl/nx/pull/19187.

Since angular executors are resolved async, it can occur that the unregisterPluginTSTranspiler function is called before the plugin loading occurs.
https://github.com/nrwl/nx/blob/47fcce0dfbde758ea297e9a257006427bfa9ec7a/packages/nx/src/command-line/run/run.ts#L157-L198
https://github.com/nrwl/nx/blob/47fcce0dfbde758ea297e9a257006427bfa9ec7a/packages/nx/src/project-graph/project-graph.ts#L73-L94

### Expected Behavior

Custom angular builder should work even if `useDaemonProcess: false` is set to false.

### GitHub Repo

https://github.com/skrtheboss/custom-angular-builder-example

### Steps to Reproduce

1.Checkout https://github.com/skrtheboss/custom-angular-builder-example
2. Run `pnpm install`
3. Run `pnpm nx run main-app:custom-build --verbose`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.19.0
   OS     : linux-x64
   pnpm   : 8.8.0
   
   nx (global)        : 16.10.0
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/plugin         : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
   	 @devkit/custom-angular-build
```

### Failure Logs

```shell
nx run main-app:custom-build --verbose                                                                               

unregisterPluginTSTranspiler
registerPluginTSTranspiler

> nx run main-app:custom-build:production

registerPluginTSTranspiler
unregisterPluginTSTranspiler
 >  NX   Cannot use import statement outside a module
/home/denis/tmp/custom-angular-builder-example/devkit/custom-angular-build/src/executors/build/executor.ts:1
import { BuilderContext, createBuilder } from '@angular-devkit/architect';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1094:15)
    at Module._compile (node:internal/modules/cjs/loader:1129:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at Module.require (/home/denis/tmp/custom-angular-builder-example/node_modules/.pnpm/nx@16.10.0_@swc-node+register@1.6.8_@swc+core@1.3.92/node_modules/nx/src/adapter/compat.js:34:40)
    at require (node:internal/modules/cjs/helpers:103:18)
    at getBuilder (/home/denis/tmp/custom-angular-builder-example/packages/angular_devkit/architect/node/node-modules-architect-host.ts:246:16)

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target custom-build for project main-app failed

   Failed tasks:
   
   - main-app:custom-build:production
   
   Hint: run the command with --verbose for more details.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by TarasovMV** [comment]
Try to install these versions of swc packages, it helps for me

```
"@swc-node/register": "~1.4.2",
"@swc/cli": "~0.1.62",
"@swc/core": "~1.3.85",
```

**Comment by Lucas170799** [comment]
Hey, any info on this? Same problem happening with version 17.1.1.

**Comment by Sitzdev** [comment]
Hey @skrtheboss thank you for your fast reply. Sadly it didn't fix my error. Here my patchfile with npm patch-package
```
diff --git a/node_modules/nx/src/project-graph/project-graph.js b/node_modules/nx/src/project-graph/project-graph.js
index fb691c5..9c24c05 100644
--- a/node_modules/nx/src/project-graph/project-graph.js
+++ b/node_modules/nx/src/project-graph/project-graph.js
@@ -70,7 +70,7 @@ async function buildProjectGraphWithoutDaemon() {
     const { allWorkspaceFiles, fileMap, projectConfigurations, externalNodes } = await (0, retrieve_workspace_files_1.retrieveWorkspaceFiles)(workspace_root_1.workspaceRoot, nxJson);
     const cacheEnabled = process.env.NX_CACHE_PROJECT_GRAPH !== 'false';
     const projectGraph = (await (0, build_project_graph_1.buildProjectGraphUsingProjectFileMap)(projectConfigurations.projects, externalNodes, fileMap, allWorkspaceFiles, cacheEnabled ? (0, nx_deps_cache_1.readFileMapCache)() : null, cacheEnabled)).projectGraph;
-    (0, nx_plugin_1.unregisterPluginTSTranspiler)();
+    //(0, nx_plugin_1.unregisterPluginTSTranspiler)();
     return projectGraph;
 }
 exports.buildProjectGraphWithoutDaemon = buildProjectGraphWithoutDaemon;

```
Here the error message I'm getting while executing the executor:

```
>  NX   Cannot use import statement outside a module
 
C:\Users\...\node_modules\@angular\core\fesm2022\core.mjs:7
import { setActiveConsumer as setActiveConsumer$1, consumerDestroy as consumerDestroy$1, SIGNAL as SIGNAL$1, createComputed as createComputed$1, createSignal as createSignal$1, signalSetFn as signalSetFn$1, signalUpdateFn as signalUpdateFn$1, REACTIVE_NODE as REACTIVE_NODE$1, consumerBeforeComputation as consumerBeforeComputation$1, consumerAfterComputation as consumerAfterComputation$1, consumerPollProducersForChange as consumerPollProducersForChange$1, getActiveConsumer as getActiveConsumer$1, createWatch as createWatch$1, setThrowInvalidWriteToSignalError as setThrowInvalidWriteToSignalError$1 } from '@angular/core/primitives/signals';
```

**Comment by skrtheboss** [comment]
Then we will need to wait and see what @AgentEnder thinks about what the issue could be.
