### ISSUE TITLE
can't run nestjs project if it's using esm

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#19618]
### Current Behavior

it fails to build/serve

### Expected Behavior

it works just fine

### GitHub Repo

https://github.com/robertIsaac/nx-nest-esm

### Steps to Reproduce

1. clone the project and try to run it

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32-x64
   npm    : 9.6.7

   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/nest           : 16.10.0
   @nx/node           : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/webpack        : 16.10.0
   nx-cloud           : 16.5.2
   typescript         : 5.1.6
```

### Failure Logs

```shell
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\rober\test\nx-nest-esm\apps\nx-nest-esm\webpack.config.js from C:\Users\rober\test\nx-nest-esm\node_modules\@nx\webpack\src\utils\webpack\custom-webpack.js not supported.
Instead change the require of webpack.config.js in C:\Users\rober\test\nx-nest-esm\node_modules\@nx\webpack\src\utils\webpack\custom-webpack.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (C:\Users\rober\test\nx-nest-esm\node_modules\ts-node\dist\index.js:851:20)
    at resolveCustomWebpackConfig (C:\Users\rober\test\nx-nest-esm\node_modules\@nx\webpack\src\utils\webpack\custom-webpack.js:7:33)
    at getWebpackConfigs (C:\Users\rober\test\nx-nest-esm\node_modules\@nx\webpack\src\executors\webpack\webpack.impl.js:21:73)
    at webpackExecutor (C:\Users\rober\test\nx-nest-esm\node_modules\@nx\webpack\src\executors\webpack\webpack.impl.js:79:27)
    at webpackExecutor.next (<anonymous>)
    at C:\Users\rober\test\nx-nest-esm\node_modules\@nx\js\src\executors\node\node.impl.js:191:44 {
  code: 'ERR_REQUIRE_ESM'
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

running `npx tsc --project .\apps\nx-nest-esm\tsconfig.app.json` then `node .\dist\out-tsc\apps\nx-nest-esm\src\main.js` actually works, so the problem is solely in nx
doing the same for nest project produced by nest cli works without a problem, example here https://github.com/robertIsaac/nest-esm

**Comment by jmls** [comment]
ah bloody hell, I've just hit this :( Is there a workaround ?

**Comment by robertIsaac** [comment]
> ah bloody hell, I've just hit this :( Is there a workaround ?

if you don't use plugins, `npx tsc --project .\apps\nx-nest-esm\tsconfig.app.json` then `node .\dist\out-tsc\apps\nx-nest-esm\src\main.js` :)

**Comment by robertIsaac** [comment]
@AgentEnder any updates?

**Comment by jaysoo** [comment]
We'll need to patch this on our end because Nx compiles down to CommonJS, and we need to adapt around loading ESM modules.

In the meantime, if you use `webpack.config.ts`, Nx will automatically compile this to a commonjs file.

**Comment by jaysoo** [comment]
We'll need to patch `@nx/webpack` to adapt `webpack.config.js` files that use ESM. The only workaround in the meantime ifs to rename the file to `webpack.config.ts`, which Nx will transpile to CommonJS.

**Comment by robertIsaac** [comment]
@jaysoo I don't get what `webpack.config.js` I need to rename to `webpack.config.ts`
I don't have any `webpack.config.js` in my project

**Comment by robertIsaac** [comment]
oh in the reprod repo there is a webpack file

**Comment by robertIsaac** [comment]
it didn't work, added you to the repo, feel free to add a commit to fix it

**Comment by robertIsaac** [comment]
I need to write a comment to stop the bot from closing the issue

**Comment by ormarek** [comment]
Is there any workaround or working solution to that issue?
I'm encountering more and more packages that are ESM only

**Comment by jpsullivan** [comment]
Pinging this thread in case anyone has managed to figure out a fix. Node v22 added in the experimental flag to automatically patch in support for `require()` calls in ESM graphs. This flag is `--experimental-require-module`.

Does anyone know how to incorporate this into `nx` so that when I run, say, `nx serve api`, this flag is automatically set? Otherwise it's looking like I'll have to pivot away from nestjs and find something else which is very unfortunate.

**Comment by vsamofal** [comment]
same for me

**Comment by Clashsoft** [comment]
Same issue.

**Comment by Shuunen** [comment]
Same issue here :'(

**Comment by mklinke** [comment]
> Pinging this thread in case anyone has managed to figure out a fix. Node v22 added in the experimental flag to automatically patch in support for `require()` calls in ESM graphs. This flag is `--experimental-require-module`.
> 
> Does anyone know how to incorporate this into `nx` so that when I run, say, `nx serve api`, this flag is automatically set? Otherwise it's looking like I'll have to pivot away from nestjs and find something else which is very unfortunate.

Add the "runtimeArgs" property to the "serve" target's "options" in project.json, e.g.:

```
    ...
    "serve": {
      "executor": "@nx/js:node",
      "options": {
        "buildTarget": "api:build",
        "runtimeArgs": ["--experimental-require-module"]
      }
    }
    ...
```

**Comment by robertIsaac** [comment]
hi @mklinke 
it doesn't work, you have the reprod feel free to send PR if you could make it to work

the error before the flag
```
> nx run nx-nest-esm:serve:development

>  NX  Unable to load tsconfig-paths, workspace libraries may be inaccessible.
  - To fix this, install tsconfig-paths with npm/yarn/pnpm
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed
F:\nx-nest-esm\node_modules\ts-node\dist-raw\node-internal-errors.js:46
  const err = new Error(getErrRequireEsmMessage(filename, parentPath, packageJsonPath))
              ^
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: F:\nx-nest-esm\apps\nx-nest-esm\webpack.config.ts
require() of ES modules is not supported.
require() of F:\nx-nest-esm\apps\nx-nest-esm\webpack.config.ts from F:\nx-nest-esm\node_modules\@nx\webpack\src\utils\webpack\custom-webpack.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from F:\nx-nest-esm\package.json.

    at createErrRequireEsm (F:\nx-nest-esm\node_modules\ts-node\dist-raw\node-internal-errors.js:46:15)
    at assertScriptCanLoadAsCJSImpl (F:\nx-nest-esm\node_modules\ts-node\dist-raw\node-internal-modules-cjs-loader.js:584:11)
    at Object.require.extensions.<computed> [as .ts] (F:\nx-nest-esm\node_modules\ts-node\src\index.ts:1610:5)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at resolveCustomWebpackConfig (F:\nx-nest-esm\node_modules\@nx\webpack\src\utils\webpack\custom-webpack.js:7:33)
    at getWebpackConfigs (F:\nx-nest-esm\node_modules\@nx\webpack\src\executors\webpack\webpack.impl.js:21:73)
    at webpackExecutor (F:\nx-nest-esm\node_modules\@nx\webpack\src\executors\webpack\webpack.impl.js:79:27) {
  code: 'ERR_REQUIRE_ESM'
}
```

the error after
```
>  NX  Unable to load tsconfig-paths, workspace libraries may be inaccessible.
  - To fix this, install tsconfig-paths with npm/yarn/pnpm
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed
F:\nx-nest-esm\node_modules\ts-node\dist-raw\node-internal-errors.js:46
  const err = new Error(getErrRequireEsmMessage(filename, parentPath, packageJsonPath))
              ^
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: F:\nx-nest-esm\apps\nx-nest-esm\webpack.config.ts
require() of ES modules is not supported.
require() of F:\nx-nest-esm\apps\nx-nest-esm\webpack.config.ts from F:\nx-nest-esm\node_modules\@nx\webpack\src\utils\webpack\custom-webpack.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from F:\nx-nest-esm\package.json.

    at createErrRequireEsm (F:\nx-nest-esm\node_modules\ts-node\dist-raw\node-internal-errors.js:46:15)
    at assertScriptCanLoadAsCJSImpl (F:\nx-nest-esm\node_modules\ts-node\dist-raw\node-internal-modules-cjs-loader.js:584:11)
    at Object.require.extensions.<computed> [as .ts] (F:\nx-nest-esm\node_modules\ts-node\src\index.ts:1610:5)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1127:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at resolveCustomWebpackConfig (F:\nx-nest-esm\node_modules\@nx\webpack\src\utils\webpack\custom-webpack.js:7:33) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by Niewdanka** [comment]
Is there any workaround? This problem has been around for about 2 years now.

**Comment by kasir-barati** [comment]
JFI: When I decided to just go back to CommonJS since it was not a deal breaker for me I realized that hell yeah, there is a murder case here: `NX Daemon is not running. Node process will not restart automatically after file changes.`. So now I do not have hot reload in my NestJS app (do the manual restart yourself) 🚂.

**Comment by kasir-barati** [comment]
So I got it working with ESM but it is practically not usable in real life projects: https://github.com/kasir-barati/bugs/tree/esm-nestjs-nx

**Comment by Tow96** [comment]
Has something come up in these months?

**Comment by nhhockeyplayer** [comment]
we need to pray for Nx...

Im seeing alot for things surrounding this issue in my own issues
nestjs no project.json exists in my camp having shaken out all the 20.*.* releases to date
webpack still unpredictable
esbuild impositions when unexpected release to release now
infinite loops these are bad, recursions is fun wild and works but if it hits a land-mine OUCH
OS crash from heap out of memory

Nx is unstable right now from my camp I have yet to get out of build hell since november with my large codeebase

the task executor I think if it lands on a land-mine (and I would guess the Nx team can characterize these are amongst all the project.json flavors) runs off and starts doing rogue things with the search algorithms and such stopping builds.

I highly encourage the Nx team refrain from chronic introducing Promises and async/await into the codebase this is virtual multi-threaded concurrency and just oe leg of execution is all it takes to wipe things ouit

My gut feeling it its approaching critical mass if not already and this means major refactor taking huge steps back and out of the box and re-modeling everything that was attempted to be swallowed (the whole enchilada... react and the world)

I personally think the 1st cut should have stuck with angular with minimal webpack and segregated esbuild

But its doing everything now

and Im praying for the team so their true best can come out and get this elite awesome product running with precision

Im on 20.4.0 and more multiple issues are happening now I cannot file issues for this every three days

DAEMON DIED
```
nx build admin-api              

 NX   Daemon process terminated and closed the connection

Please rerun the command, which will restart the daemon.
If you get this error again, check for any errors in the daemon process logs found in: /Users/meanstack02/meanstacknh/.nx/workspace-data/d/daemon.log
```


LIBRARIES NOW BROKEN for esbuild
```
------------------------------------------------------------------------------
Building entry point '@nhhockeyplayer/shared-root-ui-assets'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy partial compilation mode.
✖ 

 NX   Could not resolve entry module "dist/libs/shared/root/ui-assets/esm2022/nhhockeyplayer-shared-root-ui-assets.mjs".

RollupError: Could not resolve entry module "dist/libs/shared/root/ui-assets/esm2022/nhhockeyplayer-shared-root-ui-assets.mjs".
    at getRollupError (/Users/meanstack02/meanstacknh/node_modules/rollup/dist/shared/parseAst.js:285:41)
    at Object.error (/Users/meanstack02/meanstacknh/node_modules/rollup/dist/shared/parseAst.js:281:42)
    at ModuleLoader.loadEntryModule (/Users/meanstack02/meanstacknh/node_modules/rollup/dist/shared/rollup.js:21324:32)
    at async Promise.all (index 0)

```

**Comment by EthanSK** [comment]
what a joke its 2025

**Comment by ndcunningham** [comment]
duplicate of #10296
We are looking into it.

**Comment by Coly010** [comment]
Closed by: https://github.com/nrwl/nx/pull/31965
