### ISSUE TITLE
process.on not a function: Nestjs app in Nx

### ISSUE THREAD

**Issue by SOG-web** [nrwl/nx#19621]
### Current Behavior

```/Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/webpack:/src/tracing.ts:42
process.on('beforeExit', () => {
        ^

TypeError: process.on is not a function
    at Array.<anonymous> (/Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/webpack:/src/tracing.ts:42:9)
    at __webpack_require__ (/Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/webpack:/webpack/bootstrap:19:1)
    at /Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/webpack:/src/main.ts:5:1
    at /Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/main.js:249:3
    at Object.<anonymous> (/Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/main.js:254:12)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.Module._load (/Users/rou/Documents/Github/rou-logistic/node_modules/@nx/js/src/executors/node/node-with-require-overrides.js:10:31)
```

### Expected Behavior

Just run normally

### GitHub Repo

https://github.com/SOG-web/nx-error.git

### Steps to Reproduce

1. new nx workspace
2. generate new nestjs app
3. use process.on

```ts
import {
  ConsoleSpanExporter,
  SimpleSpanProcessor,
} from '@opentelemetry/sdk-trace-base';
import { NodeSDK } from '@opentelemetry/sdk-node';
import * as process from 'process';
import { HttpInstrumentation } from '@opentelemetry/instrumentation-http';
import { ExpressInstrumentation } from '@opentelemetry/instrumentation-express';

const traceExporter = new ConsoleSpanExporter();

export const otelSDK = new NodeSDK({
  spanProcessor: new SimpleSpanProcessor(traceExporter),
  instrumentations: [new HttpInstrumentation(), new ExpressInstrumentation()],
});

async function shutdownSDK() {
  try {
    await otelSDK.shutdown();
    console.log('SDK shut down successfully');
  } catch (err) {
    console.log('Error shutting down SDK', err);
  }
}

// Call the shutdownSDK function when the process is about to exit
process.on('beforeExit', () => {
  shutdownSDK().finally(() => process.exit(0));
});
```

`main.js`
```ts
import { otelSDK } from './tracing';

import { Logger, LoggerErrorInterceptor } from 'nestjs-pino';
import { NestFactory } from '@nestjs/core';

import { AppModule } from './app/app.module';

async function bootstrap() {
  otelSDK.start();
  const app = await NestFactory.create(AppModule, { bufferLogs: true });
  app.useLogger(app.get(Logger));
  app.useGlobalInterceptors(new LoggerErrorInterceptor());
  const globalPrefix = 'api';
  app.setGlobalPrefix(globalPrefix);
  const port = process.env.PORT || 3000;
  await app.listen(port);
  console.log(
    `🚀 Application is running on: http://localhost:${port}/${globalPrefix}`
  );
}

bootstrap();
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : darwin-x64
   npm    : 9.6.7
   
   nx (global)        : 16.6.0
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/nest           : 16.10.0
   @nx/node           : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
```

### Failure Logs

```shell
/Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/webpack:/src/tracing.ts:42
process.on('beforeExit', () => {
        ^

TypeError: process.on is not a function
    at Array.<anonymous> (/Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/webpack:/src/tracing.ts:42:9)
    at __webpack_require__ (/Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/webpack:/webpack/bootstrap:19:1)
    at /Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/webpack:/src/main.ts:5:1
    at /Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/main.js:249:3
    at Object.<anonymous> (/Users/rou/Documents/Github/rou-logistic/dist/apps/auth-api/main.js:254:12)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.Module._load (/Users/rou/Documents/Github/rou-logistic/node_modules/@nx/js/src/executors/node/node-with-require-overrides.js:10:31)
```
```


### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by mandarini** [comment]
Please take a look at the PR I submitted here: https://github.com/SOG-web/nx-error/pull/1

In Node.js, `process` is a global object and does not need to be imported. When you do `import * as process from 'process';`, you are essentially overwriting the global `process` object with a module-scoped variable, which may not have all the properties and methods available on the global `process` object.

When you remove the import `import * as process from 'process';`, the code works because it uses the global `process` object, which does have the `on` method available for hooking into various process-level events.

In most Node.js programs, there's no need to import the `process` object because it's globally available to the application. Removing the import statement will solve the issue you're experiencing.

You just need to remove your import.
