### ISSUE TITLE
Unable to upgrade to latest version.

### ISSUE THREAD

**Issue by brandoncollins7** [nrwl/nx#19761]
### Current Behavior

After upgrading my nx workspace to latest I can no longer run my projects which are linked to a library. 

### Expected Behavior

Should work same as before upgrade.

### Steps to Reproduce

1. No idea. I have my project. I did nx migrate latest. I follow the steps. Now my apps won't run.

### Nx Report

```shell
POST UPGRAGE:
Node   : 18.15.0
   OS     : win32-x64
   pnpm   : 8.6.12
   
   nx (global)        : 16.6.0
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/esbuild        : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/nest           : 16.10.0
   @nx/next           : 16.10.0
   @nx/node           : 16.10.0
   @nx/react          : 16.10.0
   @nx/storybook      : 16.10.0
   @nx/vite           : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   nx-cloud           : 16.5.2
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.0.2
   @nx-tools/nx-prisma    : 5.0.2

PRE-UPGRADE:
Node   : 18.15.0
   OS     : win32-x64
   pnpm   : 8.6.12

   nx (global)        : 16.6.0
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/esbuild        : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/nest           : 16.6.0
   @nx/next           : 16.6.0
   @nx/node           : 16.6.0
   @nx/react          : 16.6.0
   @nx/storybook      : 16.6.0
   @nx/vite           : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   nx-cloud           : 16.2.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.0.2
   @nx-tools/nx-prisma    : 5.0.2
```

### Failure Logs

```shell
Debugger listening on ws:/
/localhost:7013/edeeadee-1add-4fa0-bfd4-9118c203c5d7
Debugger listening on ws://localhost:7013/edeeadee-1add-4fa0-bfd4-9118c203c5d7
For help, see: https://nodejs.org/en/docs/inspector

NODE_ENV: development
API_PORT8084
Error: Cannot find module '@frnt/shared/util/logging'
Require stack:
- C:\Users\brand\Projects\atlantic-dawn-monorepo\dist\apps\slack-api\apps\slack-api\src\index.js
- C:\Users\brand\Projects\atlantic-dawn-monorepo\dist\apps\slack-api\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._resolveFilename (C:\Users\brand\Projects\atlantic-dawn-monorepo\tmp\slack-api\main-with-require-overrides.js:41:36)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.Module._load (C:\Users\brand\Projects\atlantic-dawn-monorepo\node_modules\.pnpm\@nx+js@16.10.0_@swc-node+register@1.6.8_@swc+core@1.3.93_@types+node@18.14.2_nx@16.10.0_typescript@5.1.6\node_modules\@nx\js\src\executors\node\node-with-require-overrides.js:18:31)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\brand\Projects\atlantic-dawn-monorepo\apps\slack-api\src\index.js:2:20)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)


>  NX  Process exited with code 1, waiting for changes to restart...

```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @brandoncollins7 ! Thanks for filing an issue! Can you please provide a minimum reproduction repository?
