### ISSUE TITLE
Cannot externals antd when use nx

### ISSUE THREAD

**Issue by ngocxuan123** [nrwl/nx#19787]
### Current Behavior

I updated  webpack.config.js from app folder to using externals:

```
const { composePlugins, withNx } = require('@nx/webpack');
const { withReact } = require('@nx/react');

const externals = {
  "react": "React",
  "react-dom": "ReactDOM",
  "dayjs": "dayjs",
  "lodash": "_",
  "antd": "antd"
  // 'react-router-dom': 'ReactRouterDOM',
  // "antd": "https://cdnjs.cloudflare.com/ajax/libs/antd/5.9.0/antd.min.js"
};

const cdn = {
  scripts: [
    {
      input: "./node_modules/react/umd/react.production.min.js",
      bundleName: "react",
    },
    {
      input: "./node_modules/react-dom/umd/react-dom.production.min.js",
      bundleName: "react-dom",
    },
    {
      input: "./node_modules/dayjs/dayjs.min.js",
      bundleName: "dayjs",
    },
    {
      input: "./node_modules/lodash/lodash.min.js",
      bundleName: "lodash",
    },
    // {
    //   input: './apps/dop/src/assets/js/vendors/antd.min.js',
    //   bundleName: 'antd'
    // }
    {
      input: "./node_modules/antd/dist/antd.min.js",
      bundleName: "antd",
    },
  ],
}

// Nx plugins for webpack.
module.exports = composePlugins(withNx(), withReact({
  ...cdn
}), (config) => {
  // Update the webpack config as needed here.
  // e.g. `config.plugins.push(new MyPlugin())`

  config.externals = externals;
  config.optimization.splitChunks.chunks = 'all';

  return config;
});

```
![image](https://github.com/nrwl/nx/assets/26795245/c16b93fc-41f6-4a7e-8181-978478efe19c)

my config only work for React, ReactDOM but Ant Design doesn't work. can you help me please!

### Expected Behavior

I want to my config can work for antd

### Steps to Reproduce

1.
Setup project with nx
2.
Update webpack.config for externals antd

### Nx Report

```shell
nx build success but has error runtime
antd is not defined
ReferenceError: antd is not defined
    at 81821 (http://localhost:8000/main.js:50478:18)
    at options.factory (http://localhost:8000/runtime.js:645:31)
    at __webpack_require__ (http://localhost:8000/runtime.js:28:33)
    at fn (http://localhost:8000/runtime.js:296:21)
    at 13705 (http://localhost:8000/vendor.js:31116:22)
    at options.factory (http://localhost:8000/runtime.js:645:31)
    at __webpack_require__ (http://localhost:8000/runtime.js:28:33)
    at fn (http://localhost:8000/runtime.js:296:21)
    at 22091 (http://localhost:8000/main.js:69:74)
    at options.factory (http://localhost:8000/runtime.js:645:31)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
It looks like you are trying to load from CDN and read the value from a global var? It is recommended that you install packages using a package manager (e.g. `npm`), and import it in your source code.


e.g.

Shell:
```shell
npm i -D antd
```

Source:

```js
import { Button } from 'antd';
```
