### ISSUE TITLE
Migrating to nx@17.0.1 generates `Error: Unable to resolve @nrwl/linter:eslint.` when linting

### ISSUE THREAD

**Issue by KeithGillette** [nrwl/nx#19798]
### Current Behavior

Running `nx lint` on a project after migrating from `nx@16.10.0` to `nx@17.0.` generates `Error: Unable to resolve @nrwl/linter:eslint.`

### Expected Behavior

Linting should work as before.

### Steps to Reproduce

```
nx migrate latest
npm install
npx nx migrate --run-migrations 
nx lint project-name
```

### Nx Report

```shell
Under `nx@16.10.01`:


 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.1
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx             : 16.10.0
   @nx/js         : 16.10.0
   @nx/jest       : 16.10.0
   @nx/linter     : 16.10.0
   @nx/workspace  : 16.10.0
   @nx/angular    : 16.10.0
   @nx/cypress    : 16.10.0
   @nx/devkit     : 16.5.1
   @nx/node       : 16.10.0
   @nrwl/tao      : 16.10.0
   @nx/webpack    : 16.10.0
   nx-cloud       : 16.5.2
   typescript     : 5.1.6
   ---------------------------------------
   Community plugins:
   apollo-angular : 5.0.2
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/devkit@16.5.1
     - @nrwl/devkit@16.5.1
   
   To fix this, run `nx migrate nx@16.10.0`



After `nx migrate latest` `npx nx migrate --run-migrations`:



>  NX   Report complete - copy this into the issue template

   Node   : 18.16.1
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx             : 17.0.1
   @nx/js         : 17.0.1
   @nx/jest       : 17.0.1
   @nx/linter     : 17.0.1
   @nx/eslint     : 17.0.1
   @nx/workspace  : 17.0.1
   @nx/angular    : 17.0.1
   @nx/cypress    : 17.0.1
   @nx/devkit     : 16.5.1
   @nx/node       : 17.0.1
   @nrwl/tao      : 17.0.1
   @nx/web        : 17.0.1
   @nx/webpack    : 17.0.1
   typescript     : 5.1.6
   ---------------------------------------
   Community plugins:
   apollo-angular : 5.0.2
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/devkit@16.5.1
     - @nrwl/devkit@16.5.1
   
   To fix this, run `nx migrate nx@17.0.1`
```

### Failure Logs

```shell
>  NX   Unable to resolve @nrwl/linter:eslint.

   Cannot find module '@nrwl/linter/package.json'
   Require stack:
   - /path/to/node_modules/nx/src/utils/package-json.js
   - /path/to/node_modules/nx/src/utils/package-manager.js
   - /path/to/node_modules/nx/bin/init-local.js
   - /path/to/node_modules/nx/bin/nx.js

Error: Unable to resolve @nrwl/linter:eslint.
Cannot find module '@nrwl/linter/package.json'
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by KeithGillette** [comment]
Got linting to work again by manually changing `targets.lint.executor: @nx/linter:eslint` in all `project.json` files. Also added `@nx/linter` to `package.json` `devDependencies` for good measure, since it wasn't there, but it worked without explicitly including a linter as a dependency. I think the migration in [PR#19515](https://github.com/nrwl/nx/pull/19515) had failed to run.

**Comment by 4kochi** [comment]
Hey there,

i have the same problem. For me the command `nx lint my-lib` works, but not the affected command (`nx affected:lint`).
I guess I could also fix it manually like Keith but I think this is not the real solution here.

**Comment by seliceantitus** [comment]
I was running into the same issue after upgrading to nx 17.1.3 and had issues with 17.0.1 as well in the past. I think there might be something with the migration or node_modules cache or something similar. Either way, will post this since it might help others.

```
 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   npm    : 9.6.7
   
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/jest           : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/detox          : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/nest           : 17.1.3
   @nx/node           : 17.1.3
   @nx/react          : 17.1.3
   @nx/react-native   : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/vite           : 17.1.3
   @nx/web            : 17.1.3
   @nx/webpack        : 17.1.3
   typescript         : 5.2.2
``` 

After running `nx migrate latest`

```
Fetching meta data about packages.
It may take a few minutes.
Fetching nx@17.1.3
Fetching @nrwl/js@17.1.3
Fetching @nx/webpack@17.1.3
Fetching @nx/jest@17.1.3
Fetching @nx/workspace@17.1.3
Fetching @nrwl/js@17.1.3
Fetching @nx/cypress@17.1.3
Fetching @nx/linter@17.1.3
Fetching @nx/react@17.1.3
Fetching @nx/web@17.1.3
Fetching @nx/nest@17.1.3
Fetching @nx/node@17.1.3
Fetching @nx/react-native@17.1.3
Fetching @nx/detox@17.1.3
Fetching @nx/js@17.1.3
Fetching @nx/vite@17.1.3
Fetching @nx/eslint-plugin@17.1.3
Fetching @nx/linter@17.1.3

 >  NX   The migrate command has run successfully.

   - package.json has been updated.
   - migrations.json has been generated.


 >  NX   Next steps:

   - Make sure package.json changes make sense and then run 'npm install',
   - Run 'npx nx migrate --run-migrations'
   - To learn more go to https://nx.dev/core-features/automate-updating-dependencies
``` 

Error thrown when running `npx nx lint <project>`

```
Error: Unable to resolve @nx/eslint:lint.
Cannot find executor 'lint' in /path-to-node/node_modules/@nx/eslint/executors.json.
    at getExecutorInformation (/path-to-node/node_modules/nx/src/command-line/run/executor-utils.js:53:15)
    at getExecutorForTask (/path-to-node/node_modules/nx/src/tasks-runner/utils.js:187:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getCustomHasher (/path-to-node/node_modules/nx/src/tasks-runner/utils.js:191:22)
    at async /path-to-node/node_modules/nx/src/hasher/hash-task.js:11:30
    at async Promise.all (index 0)
    at async hashTasksThatDoNotDependOnOutputsOfOtherTasks (/path-to-node/node_modules/nx/src/hasher/hash-task.js:10:30)
    at async invokeTasksRunner (/path-to-node/node_modules/nx/src/tasks-runner/run-command.js:136:5)
    at async /path-to-node/node_modules/nx/src/tasks-runner/run-command.js:91:24
    at async handleErrors (/path-to-node/node_modules/nx/src/utils/params.js:9:16)
```

When inspecting @nx/eslint/executors.json it seems that it indeed does not contain any executor for lint. Below are the contents of the file

```
{
  "builders": {
    "eslint": {
      "implementation": "@nx/eslint/src/executors/lint/compat",
      "schema": "@nx/eslint/src/executors/lint/schema.json",
      "description": "Run ESLint on a project."
    }
  },
  "executors": {
    "eslint": {
      "implementation": "@nx/eslint/src/executors/lint/lint.impl",
      "schema": "@nx/eslint/src/executors/lint/schema.json",
      "hasher": "@nx/eslint/src/executors/lint/hasher",
      "description": "Run ESLint on a project."
    }
  }
}
``` 

I had to uninstall and manually reinstall `@nx/eslint@17.1.3` to get it working.
