### ISSUE TITLE
Affected --all fails with merge-base check after update from 8.6.0 to 8.7.0

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#1988]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

`nx affected:lint --all` should not trigger `git merge-base master HEAD`
Instead affected should just use all libs/apps from `nx.json` without checking affected files via `git merge-base`.

## Current Behavior

`nx affected:lint --all` fails with git error

## Failure Information (for bugs)

Running `nx affected:lint --all` fails with error bellow when there is no master branch.
```
Error: Command failed: git merge-base master HEAD
fatal: Not a valid object name master

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at getFilesUsingBaseAndHead (/ng-app/node_modules/@nrwl/workspace/src/command-line/shared.js:108:39)
    at Object.parseFiles (/ng-app/node_modules/@nrwl/workspace/src/command-line/shared.js:93:20)
    at Object.affected (/ng-app/node_modules/@nrwl/workspace/src/command-line/affected.js:16:35)
    at Object.handler (/ng-app/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:66:138)
    at Object.runCommand (/ng-app/node_modules/@nrwl/workspace/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/ng-app/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1022:30)
    at Object.get [as argv] (/ng-app/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:965:21)
    at Object.<anonymous> (/ng-app/node_modules/@nrwl/cli/bin/nx.js:38:26)
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Have a Nx workspace without `master` branch
2. Run `nx affected:lint --all` or any other affected CLI command with `--all`

### Context

The issue appeared after update from 8.6.0 to 8.7.0

**Comment by krawetko** [comment]
We experience the same issue after udpating "@nrwl/workspace" to 8.4.13+. 8.4.12 is the last version when it works.
