### ISSUE TITLE
TSC batch mode: Cannot read properties of null (reading 'tsConfig')

### ISSUE THREAD

**Issue by dmaretskyi** [nrwl/nx#19911]
### Current Behavior

Crashes with 

```
TypeError: Cannot read properties of null (reading 'tsConfig')
    at generateTaskProjectTsConfig (/Users/dmaretskyi/Projects/protocols/node_modules/.pnpm/@nx+js@17.0.2_@swc-node+register@1.5.4_@swc+core@1.3.70_@types+node@18.11.9_nx@17.0.2_typescript@5.2.2/node_modules/@nx/js/src/executors/tsc/lib/get-tsconfig.js:43:38)
    at generateTaskProjectTsConfig (/Users/dmaretskyi/Projects/protocols/node_modules/.pnpm/@nx+js@17.0.2_@swc-node+register@1.5.4_@swc+core@1.3.70_@types+node@18.11.9_nx@17.0.2_typescript@5.2.2/node_modules/@nx/js/src/executors/tsc/lib/get-tsconfig.js:36:34)
    at generateTaskProjectTsConfig (/Users/dmaretskyi/Projects/protocols/node_modules/.pnpm/@nx+js@17.0.2_@swc-node+register@1.5.4_@swc+core@1.3.70_@types+node@18.11.9_nx@17.0.2_typescript@5.2.2/node_modules/@nx/js/src/executors/tsc/lib/get-tsconfig.js:36:34)
    at generateTaskProjectTsConfig (/Users/dmaretskyi/Projects/protocols/node_modules/.pnpm/@nx+js@17.0.2_@swc-node+register@1.5.4_@swc+core@1.3.70_@types+node@18.11.9_nx@17.0.2_typescript@5.2.2/node_modules/@nx/js/src/executors/tsc/lib/get-tsconfig.js:36:34)
    at generateTaskProjectTsConfig (/Users/dmaretskyi/Projects/protocols/node_modules/.pnpm/@nx+js@17.0.2_@swc-node+register@1.5.4_@swc+core@1.3.70_@types+node@18.11.9_nx@17.0.2_typescript@5.2.2/node_modules/@nx/js/src/executors/tsc/lib/get-tsconfig.js:36:34)
    at generateTaskProjectTsConfig (/Users/dmaretskyi/Projects/protocols/node_modules/.pnpm/@nx+js@17.0.2_@swc-node+register@1.5.4_@swc+core@1.3.70_@types+node@18.11.9_nx@17.0.2_typescript@5.2.2/node_modules/@nx/js/src/executors/tsc/lib/get-tsconfig.js:36:34)
    at generateTaskProjectTsConfig (/Users/dmaretskyi/Projects/protocols/node_modules/.pnpm/@nx+js@17.0.2_@swc-node+register@1.5.4_@swc+core@1.3.70_@types+node@18.11.9_nx@17.0.2_typescript@5.2.2/node_modules/@nx/js/src/executors/tsc/lib/get-tsconfig.js:36:34)
    at generateTaskProjectTsConfig (/Users/dmaretskyi/Projects/protocols/node_modules/.pnpm/@nx+js@17.0.2_@swc-node+register@1.5.4_@swc+core@1.3.70_@types+node@18.11.9_nx@17.0.2_typescript@5.2.2/node_modules/@nx/js/src/executors/tsc/lib/get-tsconfig.js:36:34)
    at getProcessedTaskTsConfigs (/Users/dmaretskyi/Projects/protocols/node_modules/.pnpm/@nx+js@17.0.2_@swc-node+register@1.5.4_@swc+core@1.3.70_@types+node@18.11.9_nx@17.0.2_typescript@5.2.2/node_modules/@nx/js/src/executors/tsc/lib/get-tsconfig.js:10:9)
    at tscBatchExecutor (/Users/dmaretskyi/Projects/protocols/node_modules/.pnpm/@nx+js@17.0.2_@swc-node+register@1.5.4_@swc+core@1.3.70_@types+node@18.11.9_nx@17.0.2_typescript@5.2.2/node_modules/@nx/js/src/executors/tsc/tsc.batch-impl.js:25:73)
```

### Expected Behavior

Doesn't crash

### GitHub Repo

https://github.com/dxos/dxos/tree/dmaretskyi/bump-nx

### Steps to Reproduce

0. Install pnpm
1. `pnpm install`
2. `nx run-many --target=build --batch --verbose`

### Nx Report

```shell
Node   : 18.12.1
   OS     : darwin-arm64
   pnpm   : 8.9.2
   
   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/storybook      : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/vite           : 17.0.2
   @nx/web            : 17.0.2
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @dxos/esbuild              : 0.3.3
   @dxos/nx-protobuf-compiler : 0.3.3
   @dxos/serve-with-vault     : 0.3.3
   @dxos/test                 : 0.3.3
   @dxos/toolbox              : 0.3.3
   ---------------------------------------
   Local workspace plugins:
         @dxos/nx-protobuf-compiler
         @dxos/serve-with-vault
         @dxos/toolbox
         @dxos/esbuild
         @dxos/test
```

### Failure Logs

```shell
// console.logs of the variables just before the error is thrown 
{
  taskOptions: null,
  tasksOptions: {
    'random-access-storage:build': {
      main: 'packages/common/random-access-storage/src/index.ts',
      outputPath: '/Users/dmaretskyi/Projects/protocols/packages/common/random-access-storage/dist/types',
      tsConfig: '/Users/dmaretskyi/Projects/protocols/packages/common/random-access-storage/tsconfig.json',
      generateExportsField: false,
      assets: [],
      watch: false,
      clean: true,
      transformers: [],
      externalBuildTargets: [Array],
      generateLockfile: false,
      root: '/Users/dmaretskyi/Projects/protocols',
      sourceRoot: 'packages/common/random-access-storage/src',
      projectRoot: 'packages/common/random-access-storage',
      files: [],
      rootDir: '/Users/dmaretskyi/Projects/protocols/packages/common/random-access-storage',
      mainOutputPath: '/Users/dmaretskyi/Projects/protocols/packages/common/random-access-storage/dist/types/src/index.js'
    }
  },
  taskWithTscExecutor: 'log-hook:compile',
  context: {
    root: '/Users/dmaretskyi/Projects/protocols',
    cwd: '/Users/dmaretskyi/Projects/protocols',
    projectsConfigurations: { projects: [Object], version: 2 },
    nxJsonConfiguration: {
      pluginsConfig: [Object],
      extends: 'nx/presets/npm.json',
      affected: [Object],
      namedInputs: [Object],
      targetDefaults: [Object],
      nxCloudAccessToken: 'ZGVlNTQ0ODctNGI4ZS00MTc0LTljZDQtMzFlMzJkOTViMmQyfHJlYWQtd3JpdGU=',
      parallel: 6
    },
    workspace: {
      projects: [Object],
      version: 2,
      pluginsConfig: [Object],
      extends: 'nx/presets/npm.json',
      affected: [Object],
      namedInputs: [Object],
      targetDefaults: [Object],
      nxCloudAccessToken: 'ZGVlNTQ0ODctNGI4ZS00MTc0LTljZDQtMzFlMzJkOTViMmQyfHJlYWQtd3JpdGU=',
      parallel: 6
    },
    isVerbose: false,
    projectGraph: {
      nodes: [Object],
      externalNodes: [Object],
      dependencies: [Object],
      version: '6.0'
    },
    taskGraph: { roots: [Array], tasks: [Object], dependencies: [Object] }
  }
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by dmaretskyi** [comment]
After more digging it looks like the actual error happens in `assetGlobsToFiles`.
In my project.json the `assets` option is not set, which causes `TypeError: Cannot read properties of undefined (reading 'forEach')`

**Comment by AgentEnder** [comment]
@dmaretskyi It sounds like you've done enough research to open a PR, if you are interested that would speed up resolution of this.

**Comment by vneogi199** [comment]
Having same error.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I haven't been able to reproduce the issue. I tried creating an Nx 17.0.2 workspace (the version reported in the original issue) and using the latest version. I had two projects with a dependency between them, and both were without the `assets` option in their `build` target configuration. I was still able to build them using batch mode.

The link to the reproduction seems to be stale. It doesn't exist anymore. @dmaretskyi or @vneogi199, could you provide a reproduction so we can troubleshoot it?
