### ISSUE TITLE
vuejs misconfiguration when creating new "apps" integrated workspace with jest unitTestRunner

### ISSUE THREAD

**Issue by mathpaquette** [nrwl/nx#19921]
### Current Behavior

when creating a brand new "apps" workspace using create-nx-workspace@17.0.2
when adding a new vue app, unit tests are not properly configured (jest and vitest)
and those and failing as such

<img width="1334" alt="image" src="https://github.com/nrwl/nx/assets/4358455/46c6f962-2fc4-4cf2-9bbf-89109fb30d90">

### Expected Behavior

tests should run as new standalone app

### Steps to Reproduce

1.  `npx create-nx-workspace@latest --name vue-workspace --preset apps --pm yarn`
2. `yarn add @nx/vue -D`
3. `npx nx g @nx/vue:app --name vue-app --unitTestRunner jest --e2eTestRunner none --style css --routing`
4. `npx nx test vue-app`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : linux-x64
   yarn   : 1.22.19

   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/vite           : 17.0.2
   @nx/vue            : 17.0.2
   @nx/web            : 17.0.2
   typescript         : 5.1.6

> nx run vue-app:test
```

### Failure Logs

```shell
[vue-jest]: Not found tsconfig.json.

 FAIL   vue-app  vue-app/src/app/App.spec.ts
  ● Test suite failed to run

    SyntaxError: /home/freemind/src/vue-test/file.js: Unexpected token, expected "," (3:27)

      1 | import { createTextVNode as _createTextVNode, withCtx as _withCtx, createVNode as _createVNode, createElementVNode as _createElementVNode, Fragment as _Fragment, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"
      2 |
    > 3 | export function render(_ctx: any,_cache: any,$props: any,$setup: any,$data: any,$options: any) {
        |                            ^
      4 |   return (_openBlock(), _createElementBlock(_Fragment, null, [
      5 |     _createElementVNode("header", null, [
      6 |       _createElementVNode("nav", null, [

      1 | import { mount } from '@vue/test-utils';
    > 2 | import App from './App.vue';
        | ^
      3 |
      4 | describe('App', () => {
      5 |   it('renders properly', () => {

      at toParseError (../node_modules/@babel/parser/src/parse-error.ts:81:19)
      at Parser.raise (../node_modules/@babel/parser/src/tokenizer/index.ts:1487:19)
      at Parser.unexpected (../node_modules/@babel/parser/src/tokenizer/index.ts:1528:16)
      at Parser.expect (../node_modules/@babel/parser/src/parser/util.ts:149:28)
      at Parser.parseBindingList (../node_modules/@babel/parser/src/parser/lval.ts:402:14)
      at Parser.parseFunctionParams (../node_modules/@babel/parser/src/parser/statement.ts:1666:24)
      at Parser.parseFunction (../node_modules/@babel/parser/src/parser/statement.ts:1626:10)
      at Parser.parseFunctionStatement (../node_modules/@babel/parser/src/parser/statement.ts:1032:17)
      at Parser.parseStatementContent (../node_modules/@babel/parser/src/parser/statement.ts:460:21)
      at Parser.parseStatementLike (../node_modules/@babel/parser/src/parser/statement.ts:417:17)
      at Parser.parseStatementListItem (../node_modules/@babel/parser/src/parser/statement.ts:366:17)
      at Parser.parseExportDeclaration (../node_modules/@babel/parser/src/parser/statement.ts:2580:17)
      at Parser.maybeParseExportDeclaration (../node_modules/@babel/parser/src/parser/statement.ts:2502:31)
      at Parser.parseExport (../node_modules/@babel/parser/src/parser/statement.ts:2395:29)
      at Parser.parseStatementContent (../node_modules/@babel/parser/src/parser/statement.ts:597:25)
      at Parser.parseStatementLike (../node_modules/@babel/parser/src/parser/statement.ts:417:17)
      at Parser.parseModuleItem (../node_modules/@babel/parser/src/parser/statement.ts:354:17)
      at Parser.parseBlockOrModuleBlockBody (../node_modules/@babel/parser/src/parser/statement.ts:1394:16)
      at Parser.parseBlockBody (../node_modules/@babel/parser/src/parser/statement.ts:1368:10)
      at Parser.parseProgram (../node_modules/@babel/parser/src/parser/statement.ts:213:10)
      at Parser.parseTopLevel (../node_modules/@babel/parser/src/parser/statement.ts:195:25)
      at Parser.parse (../node_modules/@babel/parser/src/parser/index.ts:45:10)
      at parse (../node_modules/@babel/parser/src/index.ts:66:38)
      at parser (../node_modules/@babel/core/src/parser/index.ts:28:19)
          at parser.next (<anonymous>)
      at normalizeFile (../node_modules/@babel/core/src/transformation/normalize-file.ts:50:24)
          at normalizeFile.next (<anonymous>)
      at run (../node_modules/@babel/core/src/transformation/index.ts:39:36)
          at run.next (<anonymous>)
      at transform (../node_modules/@babel/core/src/transform.ts:29:20)
          at transform.next (<anonymous>)
      at evaluateSync (../node_modules/gensync/index.js:251:28)
      at fn (../node_modules/gensync/index.js:89:14)
      at stopHiding - secret - don't use this - v1 (../node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:99:14)
      at transform (../node_modules/@babel/core/src/transform.ts:56:56)
      at processTemplate (../node_modules/@vue/vue3-jest/lib/process.js:138:20)
      at Object.module.exports [as process] (../node_modules/@vue/vue3-jest/lib/process.js:166:26)
      at ScriptTransformer.transformSource (../node_modules/@jest/transform/build/ScriptTransformer.js:545:31)
      at ScriptTransformer._transformAndBuildScript (../node_modules/@jest/transform/build/ScriptTransformer.js:674:40)
      at ScriptTransformer.transform (../node_modules/@jest/transform/build/ScriptTransformer.js:726:19)
      at Object.<anonymous> (src/app/App.spec.ts:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.67 s
Ran all test suites.
```

### Package Manager Version

yarn 1.22.19

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ethaizone** [comment]
Hi. I never use Nx before but I come across this issue after I solved issue on my side.
Actually above errors is from `jest-config` can't resolve babel config so it doesn't transform any files then it will throw error on typescript or flow project.

I don't know where is `jest.config.js` in Nx as I never use it before but it need to add more line to point correct babel config location. https://github.com/jestjs/jest/issues/3845#issuecomment-582511237

I notice this issue happen on Jest 29. I hope this can help.

PS. Is it this file? Just guessing. https://github.com/nrwl/nx/blob/c15605879080d76180feb73a09202c8c960387d2/packages/vue/src/utils/setup-jest.ts#L81
