### ISSUE TITLE
[feature] nest hot reload

### ISSUE THREAD

**Issue by yassernasc** [nrwl/nx#1992]
## Expected Behavior

Out-of-box webpack hot reload on created nest apps.

## Current Behavior

Needed to add webpack manually following the tutorial: https://docs.nestjs.com/techniques/hot-reload.

**Comment by flogh** [comment]
This feature would be incredible

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by Nightbr** [comment]
Hey, would love to see a solution for this.
BTW I found this on Stackoverflow -> https://stackoverflow.com/questions/60476245/how-to-setup-webpacks-hmr-in-nestjs-project-in-nx-monorepo

**Comment by webberwang** [comment]
any updates on this?

**Comment by rubennaatje** [comment]
@yassernascimento Any way you could show how you did it manually?

**Comment by yassernascimento** [comment]
@rubennaatje didn't tried yet, sorry

**Comment by pacexy** [comment]
any news?

**Comment by jensbodal** [comment]
I’ve tried a few times to get this working and it’s just no go.  I’m not even sure how well the feature works outside of the nest cli, does anyone have any experience?

**Comment by mehrad-rafigh** [comment]
Unstale please

**Comment by MinJungHyun** [comment]
please.. help

**Comment by MinJungHyun** [comment]
https://github.com/typeorm/typeorm/issues/3017

**Comment by DeepaPrasanna** [comment]
Are there any updates regarding this? I am facing this same issue.

**Comment by antischematic** [comment]
Until this is added here's how to get HMR working with Nx 16.1.4.

Create a `webpack.hmr.config` file like this:

```js
const { composePlugins, withNx } = require('@nx/webpack');
const nodeExternals = require('webpack-node-externals');
const webpack = require('webpack')

// Set true if you don't want type checking
const skipTypeChecking = false

// Nx plugins for webpack.
module.exports = composePlugins(withNx({ skipTypeChecking }), (config) => {
  // Update the webpack config as needed here.
  // e.g. `config.plugins.push(new MyPlugin())`
  return {
    ...config,
    entry: ['webpack/hot/poll?100', ...config.entry.main],
    externals: [
      nodeExternals({
        allowlist: ['webpack/hot/poll?100'],
      }),
    ],
    plugins: [
      ...config.plugins,
      new webpack.HotModuleReplacementPlugin(),
      new webpack.WatchIgnorePlugin({
        paths: [/\.js$/, /\.d\.ts$/],
      }),
    ],
  };
});
```

Set your `project.json` like this

```json
{
  "targets": {
    "build": {
      "executor": "@nx/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "target": "node",
        "compiler": "swc",
        "outputPath": "dist/apps/myaccount-bff",
        "main": "apps/myaccount-bff/src/main.ts",
        "tsConfig": "apps/myaccount-bff/tsconfig.app.json",
        "assets": [
          "apps/myaccount-bff/src/assets",
          {
            "input": ".",
            "glob": "newrelic.js",
            "output": "."
          }
        ],
        "isolatedConfig": true
      },
      "configurations": {
        "development": {
          "webpackConfig": "apps/myaccount-bff/webpack.hmr.config.js"
        },
        "production": {
          "webpackConfig": "apps/myaccount-bff/webpack.config.js",
          "generatePackageJson": true
        }
      }
    },
    "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "watch": false,
      "options": {
        "buildTarget": "myaccount-bff:build"
      },
      "configurations": {
        "development": {
          "buildTarget": "myaccount-bff:build:development"
        },
        "production": {
          "buildTarget": "myaccount-bff:build:production"
        }
      }
    }
  }
}
```

Make sure `watch` is set to `false`. Then set up your `main.ts` like this

```ts
declare const module: any;

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);

  if (module.hot) {
    module.hot.accept();
    module.hot.dispose(() => app.close());
  }
}
bootstrap();
```

Now you can run `nx serve your-nest-app` and it will reload with HMR.

**Comment by dan-cooke** [comment]
@antischematic unfortunately this no longer works

```
nest: 10.3.2
nx: 18.0.6
```

And it appears those linked issues are fixed

I am currently getting this error

```
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at resolve (node:path:1101:7)
    at /home/dan/dev/templi/templi/node_modules/@nx/webpack/src/plugins/nx-webpack-plugin/lib/normalize-options.js:79:59
    at Array.map (<anonymous>)
    at normalizeAssets (/home/dan/dev/templi/templi/node_modules/@nx/webpack/src/plugins/nx-webpack-plugin/lib/normalize-options.js:75:19)
    at normalizeOptions (/home/dan/dev/templi/templi/node_modules/@nx/webpack/src/executors/webpack/lib/normalize-options.js:24:76)
    at webpackExecutor (/home/dan/dev/templi/templi/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:58:62)
    at webpackExecutor.next (<anonymous>)
    at /home/dan/dev/templi/templi/node_modules/@nx/js/src/executors/node/node.impl.js:191:44
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

Not sure if this belongs in a separate issue - i'm not 100% sure whats going on there

**Comment by paullryan** [comment]
@dan-cooke I got it to work with nest 10.3.7 and nx 18.2.1 with the following

webpack.hmr.config.js
```
const { composePlugins, withNx } = require('@nx/webpack');
const nodeExternals = require('webpack-node-externals');
const webpack = require('webpack')

// Set true if you don't want type checking
const skipTypeChecking = false

// Nx plugins for webpack.
module.exports = composePlugins(withNx({ skipTypeChecking }), (config) => {
  // Update the webpack config as needed here.
  // e.g. `config.plugins.push(new MyPlugin())`
  return {
    ...config,
    entry: ['webpack/hot/poll?100', ...config.entry.main],
    externals: [
      nodeExternals({
        main: './src/main.ts',
        tsConfig: './tsconfig.app.json',
        assets: ['./src/assets'],
        optimization: false,
        outputHashing: 'none',
        allowlist: ['webpack/hot/poll?100'],
      }),
    ],
    plugins: [
      ...config.plugins,
      new webpack.HotModuleReplacementPlugin(),
      new webpack.WatchIgnorePlugin({
        paths: [/\.js$/, /\.d\.ts$/],
      }),
    ],
  };
});
```

project.json
```
{
  "name": "your-nest-app",
  "$schema": "../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "your-nest-app/src",
  "projectType": "application",
  "tags": [],
  "targets": {
    "build": {
      "executor": "@nx/webpack:webpack",
      "outputs": [
        "{options.outputPath}"
      ],
      "defaultConfiguration": "production",
      "options": {
        "target": "node",
        "compiler": "tsc",
        "outputPath": "dist/your-nest-app",
        "main": "your-nest-app/src/main.ts",
        "tsConfig": "your-nest-app/tsconfig.app.json",
        "assets": [
          "your-nest-app/src/assets"
        ],
        "isolatedConfig": true
      },
      "configurations": {
        "development": {
          "webpackConfig": "your-nest-app/webpack.hmr.config.js"
        },
        "production": {
          "webpackConfig": "your-nest-app/webpack.config.js",
          "generatePackageJson": true
        }
      }
    },
    "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "your-nest-app:build"
      },
      "configurations": {
        "development": {
          "watch": true,
          "buildTarget": "your-nest-app:build:development"
        },
        "production": {
          "buildTarget": "your-nest-app:build:production"
        }
      }
    }
  }
}
```

main.ts
```
/**
 * This is not a production server yet!
 * This is only a minimal backend to get started.
 */

declare const module: any;

import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';

import { AppModule } from './app/app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const globalPrefix = 'api';
  app.setGlobalPrefix(globalPrefix);
  const port = process.env.PORT || 3000;
  await app.listen(port);
  Logger.log(
    `🚀 Application is running on: http://localhost:${port}/${globalPrefix}`
  );
  if (module.hot) {
    module.hot.accept();
    module.hot.dispose(() => app.close());
  }
}

bootstrap();
```

**Comment by svetlyr** [comment]
@paullryan your setup works, but the app seems to be restarting twice:
Once after the HMR updated the module, and a second time after it. Same config as yours. Do you have any suggestions?

**Comment by itspers** [comment]
For me API is not available in browser till this second reload happens (Maybe due to fact that im using proxy in angular app..). And this 2 reloads take more time than one without HMR - so disabled it at all.

It is quite obvious than whole this NX moved away from Angular to some 'cloud-things' and adding executors for Rust and they have no intention to support useful things like Nestjs. There will be no SWC and no HMR.

**Comment by fourgates** [comment]
I'm on nx 19 and nestjs 10. I am also seeing the double refresh. The first refresh is super fast though! Would be great if there were a fix for HMR!

**Comment by ardabeyazoglu** [comment]
I can confirm the trick from @paullryan works on latest nx 19 and nestjs, with double refresh problem. I tried playing with webpack config a bit with no luck. Debounce did not help either.

**Comment by paullryan** [comment]
@svetlyr sorry I'm not using this that heavily at the moment so am unsure about getting the double restart to stop, I did notice that as well. I'm guessing it needs to be addressed deeper in the hot implementation for this module as it's probably doing a small (manifest) change that is causing the second restart. @ndcunningham that's where I'd start in fixing that portion of the hot reload.

**Comment by dima11221122** [comment]
I think it's related https://github.com/nrwl/nx/issues/20963

**Comment by LazeKer** [comment]
I managed to make it work by combining this issue's feedback and NestJS documentation: https://docs.nestjs.com/recipes/hot-reload

The trick for HMR is to not "serve" it directly but build it in watch mode (the double refresh probably come from the serve).

`webpack.hmr.config.js`
```js
const { composePlugins, withNx } = require('@nx/webpack')
const { WebpackPnpExternals } = require('webpack-pnp-externals')
const { RunScriptWebpackPlugin } = require('run-script-webpack-plugin')
const webpack = require('webpack')

// Set true if you don't want type checking
const skipTypeChecking = false

// Nx plugins for webpack.
module.exports = composePlugins(withNx({ skipTypeChecking }), (config, { options, context }) => {
	config.entry = ['../../node_modules/webpack/hot/poll?100', ...config.entry.main]
	config.externals = [
		WebpackPnpExternals({
			exclude: ['../../node_modules/webpack/hot/poll?100'],
		}),
	]

	config.plugins = [
		...config.plugins,
		new webpack.HotModuleReplacementPlugin(),
		new webpack.WatchIgnorePlugin({
			paths: [/\.js$/, /\.d\.ts$/],
		}),
		new RunScriptWebpackPlugin({ name: options.outputFileName, autoRestart: false }),
	]

	return config
})
```
_I use yarn berry, so `webpack-pnp-externals` instead of `webpack-node-externals`, see NestJs documentation_

`project.json`
```json
{
	"name": "api",
	"$schema": "../../node_modules/nx/schemas/project-schema.json",
	"sourceRoot": "apps/api/src",
	"projectType": "application",
	"targets": {
		"build": {
			"executor": "@nx/webpack:webpack",
			"outputs": ["{options.outputPath}"],
			"defaultConfiguration": "production",
			"options": {
				...
			},
			"configurations": {
				"hmr": {
					"watch": true,
					"sourceMap": true,
					"webpackConfig": "apps/api/webpack.hmr.config.js"
				},
				"development": {
					"sourceMap": true,
					"webpackConfig": "apps/api/webpack.config.js"
				},
				"production": {
					"generatePackageJson": true,
					"optimization": true,
					"webpackConfig": "apps/api/webpack.config.js"
				}
			}
		},
		"serve": {
			"executor": "@nx/js:node",
			"defaultConfiguration": "development",
			"options": {
				"buildTarget": "api:build"
			},
			"configurations": {
				"development": {
					"buildTarget": "api:build:development"
				},
				"production": {
					"buildTarget": "api:build:production"
				}
			}
		},
	},
}
```

Notice that I created a separate build config with the `watch` option
To start it:
`nx build api --configuration=hmr`

**Comment by emilshr** [comment]
Facing the same issue. Any updates? Thanks

**Comment by emilshr** [comment]
@LazeKer 

Thanks for your work-around, it did work for me (well sort of). But something that I observed is that, after making a change and on the first save, I get the following logs

```
asset main.js 51.4 KiB [emitted] (name: main) 1 related asset
asset 0.a1762a017f437b9e.hot-update.js 1.28 KiB [emitted] [immutable] [hmr] (name: main) 1 related asset
asset main.a1762a017f437b9e.hot-update.json 23 bytes [emitted] [immutable] [hmr]
Entrypoint main 52.7 KiB (54.4 KiB) = main.js 51.4 KiB 0.a1762a017f437b9e.hot-update.js 1.28 KiB 2 auxiliary assets

webpack 5.98.0 compiled successfully (a276795c7b50b40d)
```

The changes aren't reflected on the resolvers or anything. However, when I make a second save on any file, the entire logs of the `main.ts` file gets spit out like its a refresh and now my changes are live. Have you encountered this? I'm struggling to understand why this is happening 🤔

**Comment by dguyonvarch** [comment]
I successfully got the build/serve working without the unwanted side effect of double reloading. For this, I forced watch to true in webpack.hmr.config.ts as it seems the [watch parameter from @nx/webpack:webpack](https://nx.dev/nx-api/webpack/executors/webpack#watch) isn't properly recognized by nx. I then set the [watch parameter of @nx/js:node](https://nx.dev/nx-api/js/executors/node#watch) to false.

```
nest: 11.0.10
nx: 20.4.4
```

To summarize, here's the configuration of the `webpack.hmr.config.js`
```typescript
const { composePlugins, withNx } = require('@nx/webpack');
const nodeExternals = require('webpack-node-externals');
const webpack = require('webpack')

// Nx plugins for webpack.
module.exports = composePlugins(withNx(}), (config) => {
  // Update the webpack config as needed here.
  // e.g. `config.plugins.push(new MyPlugin())`
  return {
    ...config,
    entry: ['../../node_modules/webpack/hot/poll?100', ...config.entry.main],
    externals: [
      nodeExternals({
        allowlist: ['../../node_modules/webpack/hot/poll?100'],
      }),
    ],
    plugins: [
      ...config.plugins,
      new webpack.HotModuleReplacementPlugin(),
      new webpack.WatchIgnorePlugin({
        paths: [/\.js$/, /\.d\.ts$/],
      }),
    ],
    watch: true
  };
});
```

and the `project.json`
```json
{
  "targets": {
    "build": {
      "executor": "@nx/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "target": "node",
        "compiler": "tsc",
        "outputPath": "dist/apps/your-nest-app",
        "main": "apps/your-nest-app/src/main.ts",
        "tsConfig": "apps/your-nest-app/tsconfig.app.json",
        "assets": [
          "apps/your-nest-app/src/assets"
        ],
       "watch": true // do not work
      },
      "configurations": {
        "development": {
          "webpackConfig": "apps/your-nest-app/webpack.hmr.config.js"
        },
        "production": {
          "webpackConfig": "apps/your-nest-app/webpack.config.js",
          "generatePackageJson": true
        }
      }
    },
    "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "your-nest-app:build"
        "watch": false
      },
      "configurations": {
        "development": {
          "buildTarget": "your-nest-app:build:development"
        },
        "production": {
          "buildTarget": "your-nest-app:build:production"
        }
      }
    }
  }
}
```

**Comment by dguyonvarch** [comment]
@finkpong No problem on my side with Cursor.
This might be a start of an answer [here](https://github.com/nrwl/nx/issues/21517#issuecomment-2244111594) 

I have this piece of code in my `webpack.config.ts`
```typescript
config.output.devtoolModuleFilenameTemplate = function (info) {
    const rel = path.relative(process.cwd(), info.absoluteResourcePath)
    return `webpack:///./${rel}`
  }
```

**Comment by finkpong** [comment]
@dguyonvarch apologies for late response, i only just tried `"sourceMap":  "eval-source-map"` and that indeed fixed breakpoints after a hot reload! thank you :)

**Comment by christian-forgacs** [comment]
When I use the setup from [this comment](https://github.com/nrwl/nx/issues/1992#issuecomment-2826664777), HMR works fine – but I still get double rebuilds.

I added the following watchOptions to the `webpack.hmr.config.js`:

```typescript
watchOptions: {
  ignored: /node_modules/,
  aggregateTimeout: 300,
  poll: 1000,
}
```

Since then, everything works smoothly. No more duplicate build logs.

**Comment by bamma** [comment]
for me I got it working on nestjs11 and nx21 following comments from [this](https://github.com/nrwl/nx/issues/1992#issuecomment-2826664777) and [this comment](https://github.com/nrwl/nx/issues/1992#issuecomment-2826664777) had to set the config, else it did not work at all

**Comment by finkpong** [comment]
did anything change wrt breakpoints/sourceMap in Nx 21? at the time it worked for me (20.6.4) but at some point after upgrading to Nx 21, breakpoints no longer work again after hot reload..

i have tried setting sourceMap: true and `devtool: 'eval-source-map',` in webpack.hmr.config.js, they don't work
