### ISSUE TITLE
serve:production of next.js production build with custom server fails

### ISSUE THREAD

**Issue by lifedraft** [nrwl/nx#19965]
### Current Behavior

Generated next.js app with custom server fails to start as serve:production.

### Expected Behavior

The generated next.js app starts with the custom server in production mode.

### GitHub Repo

https://github.com/lifedraft/nx-issue-next-custom-server

### Steps to Reproduce

1. generate next.js app with: `pnpm exec nx generate @nx/next:application --name=apps/next --directory=apps/next --appDir=false --customServer=true --e2eTestRunner=none --projectNameAndRootFormat=as-provided --no-interactive`
2. build the app `pnpm exec nx run apps/next:build:production`
3. serve as production `pnpm exec nx run apps/next:serve:production`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.1.0
   OS     : darwin-arm64
   pnpm   : 8.4.0
   
   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/next           : 17.0.2
   @nx/react          : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/web            : 17.0.2
   typescript         : 5.1.6
```

### Failure Logs

```shell
> nx run apps/next:build-custom-server:production

Compiling TypeScript files for project "apps/next"...
Done compiling TypeScript files for project "apps/next".

> nx run apps/next:build:production

- info Skipping linting
- info Checking validity of types...
- info Creating an optimized production build...
- info Compiled successfully
- info Collecting page data...
- info Generating static pages (0/3)
- info Generating static pages (3/3)
- info Finalizing page optimization...
Route (pages)                              Size     First Load JS
┌ ○ /                                      3.71 kB        79.8 kB
├   └ css/ef46db3751d8e999.css             20 B
├   /_app                                  0 B            76.1 kB
└ ○ /404                                   182 B          76.2 kB
+ First Load JS shared by all              77.8 kB
  ├ chunks/framework-2647c7e378e02044.js   45.2 kB
  ├ chunks/main-82a3bb120105d055.js        29.7 kB
  ├ chunks/pages/_app-7e99a5d1d9525fff.js  389 B
  ├ chunks/webpack-8fa1640cc84ba8fe.js     750 B
  └ css/1f9a8aa3beed2e68.css               1.7 kB
○  (Static)  automatically rendered as static HTML (uses no initial props)

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project apps/next and 1 task it depends on (5s)
 
-----

> nx run apps/next:serve:production

Compiling TypeScript files for project "apps/next"...
Done compiling TypeScript files for project "apps/next".
Debugger listening on ws://localhost:9229/38254e37-f136-4f3b-9fbc-a60c6e598f8a
Debugger listening on ws://localhost:9229/38254e37-f136-4f3b-9fbc-a60c6e598f8a
For help, see: https://nodejs.org/en/docs/inspector

Error: Could not find a production build in the '/Users/stanislav.muller/tmp/next-custom-server/apps/next/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/Users/stanislav.muller/tmp/next-custom-server/node_modules/.pnpm/next@13.4.1_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/next-server.ts:455:15)
    at new Server (/Users/stanislav.muller/tmp/next-custom-server/node_modules/.pnpm/next@13.4.1_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/base-server.ts:403:25)
    at new NextNodeServer (/Users/stanislav.muller/tmp/next-custom-server/node_modules/.pnpm/next@13.4.1_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/next-server.ts:216:5)
    at NextServer.createServer (/Users/stanislav.muller/tmp/next-custom-server/node_modules/.pnpm/next@13.4.1_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/next.ts:149:20)
    at /Users/stanislav.muller/tmp/next-custom-server/node_modules/.pnpm/next@13.4.1_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/next.ts:195:23
    at NextServer.prepare (/Users/stanislav.muller/tmp/next-custom-server/node_modules/.pnpm/next@13.4.1_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/src/server/next.ts:128:20)


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target serve for project apps/next
```

### Package Manager Version

8.4.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
Hey! Did you try and run `nx build` first like the error suggested?
`
Error: Could not find a production build in the '/Users/stanislav.muller/tmp/next-custom-server/apps/next/.next' directory. Try building your app with 'next build' before starting the production server.
`

I'll close this as I think that is the issue, but feel free to reopen it and if possible provide a small repo

**Comment by lifedraft** [comment]
@ndcunningham yes i did, please see the second point of the reproduction steps.
