### ISSUE TITLE
If the only packages entry in pnpm-workspace.yaml is an exclusion, all graph-based cli commands (nx build, nx graph, nx show projects, etc.) fail

### ISSUE THREAD

**Issue by gpremo-re** [nrwl/nx#19981]
### Current Behavior

If the only entry under `packages:` in pnpm-workspace.yaml is an exclusion, graph-based cli commands like `nx build`, `nx graph`, `nx show projects` fail immediately.

example `pnpm-workspace.yml`
```yaml
packages:
  - "!schematics"
```

### Expected Behavior

NX cli commands shouldn't break if the only entry in pnpm-workspace.yaml is an exclusion.

### GitHub Repo

https://github.com/gpremo-re/nx-cli-broken-pnpm-workspace-yaml

### Steps to Reproduce

1. Create new nx workspace with `pnpm` package manager

```
create-nx-workspace test-nx-new --allPrompts=true
```

These are the specific settings I used
![powershell_52vUB4V8WH](https://github.com/nrwl/nx/assets/84458236/2123667b-70e1-4d29-9422-18226ec29d0a)

2. Create a new file in root called `pnpm-workspace.yaml` with the following contents:
```yaml
packages:
  - "!schematics"
```

The file or folder excluded may or may not exist, it doesn't make a difference.

### Nx Report

```shell
pnpm exec nx report

 >  NX   InvalidSymbol in C:\Users\garret\Documents\Projects\test-nx-new\pnpm-lock.yaml at 1:1

   > 1 | lockfileVersion: '6.0'
       | ^^^^^^^^^^^^^^^
     2 |
     3 | settings:
     4 |   autoInstallPeers: true


   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

### Failure Logs

```shell
→ C:\Users\garret\Documents\Projects\test-nx-new [main ≡]› pnpm exec nx show projects
nx show projects

Show a list of projects in the workspace

Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
      --base  Base of the current branch (usually main)                                                                                                                         [string]

or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
      --base  Base of the current branch (usually main)                                                                                                                         [string]
      --head  Latest commit of the current branch (usually HEAD)                                                                                                                [string]

or using:
      --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas or spaces                     [string]
      --uncommitted  Uncommitted changes                                                                                                                                       [boolean]
      --untracked    Untracked changes                                                                                                                                         [boolean]

Options:
      --help        Show help                                                                                                                                                  [boolean]
      --version     Show version number                                                                                                                                        [boolean]
      --json        Output JSON                                                                                                                                                [boolean]
      --exclude     Exclude certain projects from being processed                                                                                                               [string]
      --affected    Show only affected projects                                                                                                                                [boolean]
  -p, --projects    Show only projects that match a given pattern.                                                                                                              [string]
  -t, --withTarget  Show only projects that have a specific target                                                                                                              [string]
      --type        Select only projects of the given type                                                                                       [string] [choices: "app", "lib", "e2e"]

Examples:
  nx show projects --projects "apps/*"         Show all projects in the apps directory
  nx show projects --projects "shared-*"       Show all projects that start with "shared-"
  nx show projects --affected                  Show affected projects in the workspace
  nx show projects --type app --affected       Show affected apps in the workspace
  nx show projects --affected --exclude=*-e2e  Show affected projects in the workspace, excluding end-to-end projects

{
  stack: 'Error: InvalidSymbol in C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\pnpm-lock.yaml at 1:1\n' +
    "> 1 | lockfileVersion: '6.0'\n" +
    '    | ^^^^^^^^^^^^^^^\n' +
    '  2 | \n' +
    '  3 | settings:\n' +
    '  4 |   autoInstallPeers: true\n' +
    '\n' +
    '    at parseJson (C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\node_modules\\.pnpm\\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\\node_modules\\nx\\src\\utils\\json.js:25:15)\n' +
    '    at readJsonFile (C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\node_modules\\.pnpm\\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\\node_modules\\nx\\src\\utils\\fileutils.js:22:37)\n' +
    '    at createNodeFromPackageJson (C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\node_modules\\.pnpm\\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\\node_modules\\nx\\plugins\\package-json-workspaces.js:26:47)\n' +
    '    at createNodes (C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\node_modules\\.pnpm\\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\\node_modules\\nx\\plugins\\package-json-workspaces.js:20:20)\n' +
    '    at buildProjectsConfigurationsFromProjectPathsAndPlugins (C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\node_modules\\.pnpm\\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\\node_modules\\nx\\src\\project-graph\\utils\\project-configuration-utils.js:57:88)\n' +
    '    at createProjectConfigurations (C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\node_modules\\.pnpm\\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\\node_modules\\nx\\src\\project-graph\\utils\\retrieve-workspace-files.js:131:129)\n' +
    '    at WorkspaceContext.<anonymous> (C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\node_modules\\.pnpm\\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\\node_modules\\nx\\src\\project-graph\\utils\\retrieve-workspace-files.js:82:39)\n' +
    '    at getProjectConfigurationsFromContext (C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\node_modules\\.pnpm\\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\\node_modules\\nx\\src\\utils\\workspace-context.js:26:29)\n' +
    '    at _retrieveProjectConfigurations (C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\node_modules\\.pnpm\\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\\node_modules\\nx\\src\\project-graph\\utils\\retrieve-workspace-files.js:81:72)\n' +
    '    at retrieveProjectConfigurations (C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\node_modules\\.pnpm\\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\\node_modules\\nx\\src\\project-graph\\utils\\retrieve-workspace-files.js:58:12)',
  message: 'InvalidSymbol in C:\\Users\\garret\\Documents\\Projects\\test-nx-new\\pnpm-lock.yaml at 1:1\n' +
    "> 1 | lockfileVersion: '6.0'\n" +
    '    | ^^^^^^^^^^^^^^^\n' +
    '  2 | \n' +
    '  3 | settings:\n' +
    '  4 |   autoInstallPeers: true\n' +
    '\n' +
    '\n' +
    'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    'If the error persists, please run "nx reset".'
}
```

### Package Manager Version

8.10.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

As far as I'm aware, this is an issue in nx versions `16.10.0`, `17.0.0`, `17.0.1`, `17.0.2`

Out of curiosity and more testing, I found that this only appears to be a problem if you have EXACTLY one entry under `packages` and that one entry is an exclusion.

## INVALID
```yaml
packages:
  - "!x"
```

## VALID
```yaml
packages:
  - "!x"
  - "!x"
```

```yaml
packages:
  - "!x"
  - "y"
```

```yaml
packages:
  - "!x"
  - "!y"
```

**Comment by gpremo-re** [comment]
This issue seems closely related to https://github.com/nrwl/nx/issues/19225

**Comment by gpremo-re** [comment]
@AgentEnder I ran into some more issues related to `pnpm-workspace.yaml` and wanted to log them here so you were aware. It seems as though the mere existence of an exclusion in `pnpm-workspace.yaml` can cause generators to fail as well.

FAILS:
```yaml
packages:
  - "x"
  - "!y"
```

SUCCEEDS:
```yaml
packages:
  - "x"
  - "y"
```

Console output
```powershell
> pnpm exec nx --version
Nx Version:
- Local: v17.0.2

> pnpm exec nx g @nx/angular:library test --directory=libs --buildable --verbose

>  NX  Generating @nx/angular:library

√ What should be the project name and where should it be generated? · test @ libs/test
In Nx 18, generating projects will no longer derive the name and root.
Please provide the exact project name and root in the future.
Example: nx g @nx/angular:library test --directory libs

 >  NX   Cannot parse libs/test/README.md: InvalidSymbol in JSON at 1:1

   > 1 | # test
       | ^
     2 |
     3 | This library was generated with [Nx](https://nx.dev).
     4 |

Error: Cannot parse libs/test/README.md: InvalidSymbol in JSON at 1:1
> 1 | # test
    | ^
  2 |
  3 | This library was generated with [Nx](https://nx.dev).
  4 |

    at readJson (C:\Users\garret\Documents\Projects\test-new-nx-workspace\node_modules\.pnpm\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\node_modules\nx\src\generators\utils\json.js:20:15)
    at readAndCombineAllProjectConfigurations (C:\Users\garret\Documents\Projects\test-new-nx-workspace\node_modules\.pnpm\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\node_modules\nx\src\generators\utils\project-configuration.js:147:53)
    at readProjectConfiguration (C:\Users\garret\Documents\Projects\test-new-nx-workspace\node_modules\.pnpm\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\node_modules\nx\src\generators\utils\project-configuration.js:90:25)
    at normalizeOptions (C:\Users\garret\Documents\Projects\test-new-nx-workspace\node_modules\.pnpm\@nx+jest@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95_@types+node@16.11.7_nx@17.0.2_ts-node@10.9.1_typescript@5.1.6\node_modules\@nx\jest\src\generators\configuration\configuration.js:35:59)
    at configurationGenerator (C:\Users\garret\Documents\Projects\test-new-nx-workspace\node_modules\.pnpm\@nx+jest@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95_@types+node@16.11.7_nx@17.0.2_ts-node@10.9.1_typescript@5.1.6\node_modules\@nx\jest\src\generators\configuration\configuration.js:43:21)
    at addUnitTestRunner (C:\Users\garret\Documents\Projects\test-new-nx-workspace\node_modules\.pnpm\@nx+angular@17.0.2_@angular-devkit+build-angular@16.2.8_@angular-devkit+core@16.2.8_@angular-_4ongqtxbolo3f6upz5lub3q5qa\node_modules\@nx\angular\src\generators\library\library.js:93:49)
    at libraryGeneratorInternal (C:\Users\garret\Documents\Projects\test-new-nx-workspace\node_modules\.pnpm\@nx+angular@17.0.2_@angular-devkit+build-angular@16.2.8_@angular-devkit+core@16.2.8_@angular-_4ongqtxbolo3f6upz5lub3q5qa\node_modules\@nx\angular\src\generators\library\library.js:58:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\garret\Documents\Projects\test-new-nx-workspace\node_modules\.pnpm\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\node_modules\nx\src\command-line\generate\generate.js:241:26
    at async handleErrors (C:\Users\garret\Documents\Projects\test-new-nx-workspace\node_modules\.pnpm\nx@17.0.2_@swc-node+register@1.6.8_@swc+core@1.3.95\node_modules\nx\src\utils\params.js:9:16)
```
