### ISSUE TITLE
Internal Nx error when building a package with an external

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#20016]
### Current Behavior

I get the following error when building one of my libs using `tsc`
```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at relative (node:path:1192:5)
    at /Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:182:60
    at String.replace (<anonymous>)
    at recursiveUpdateImport (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:177:48)
    at recursiveUpdateImport (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:188:13)
    at updateImports (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:167:5)
    at postProcessInlinedDependencies (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:54:5)
    at /Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/executors/tsc/tsc.impl.js:73:53 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

it seems to be caused by adding a specific package as an "external" in the project.json

Specifically, it happens when building `openfeature-nodejs-provider` while `shared-bucketing-test-data` is marked as an external. There are other externals listed as well, but if I remove that specific package from the list then the build succeeds (except the package is now bundled which I don't want)

### Expected Behavior

Should work with no error.

### GitHub Repo

https://github.com/DevCycleHQ/js-sdks/pull/593/commits/bc91771c0d51bbff278118063281c714bb6c9a36

### Steps to Reproduce

1. clone repo at that commit
2. yarn
3. yarn build openfeature-nodejs-provider

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   yarn   : 3.6.0

   nx                 : 16.10.0
   lerna              : 5.6.2
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/detox          : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/esbuild        : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/next           : 16.10.0
   @nx/node           : 16.10.0
   @nx/react          : 16.10.0
   @nx/react-native   : 16.10.0
   @nrwl/rollup       : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @altack/nx-bundlefy : 0.16.0
```

### Failure Logs

```shell
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at relative (node:path:1192:5)
    at /Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:182:60
    at String.replace (<anonymous>)
    at recursiveUpdateImport (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:177:48)
    at recursiveUpdateImport (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:188:13)
    at updateImports (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:167:5)
    at postProcessInlinedDependencies (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:54:5)
    at /Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/executors/tsc/tsc.impl.js:73:53 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.16.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ajwootto** [comment]
This actually seems to be related to the package that is being set as "external", and the fact that its build output is really weird. It seems to be including its own source files and the outer `lib` directory in the output for some reason. Switching from `esbuild` to `tsc` on that package fixes that issue, and also this issue.

**Comment by tafaust** [comment]
Related issue on the matter: https://github.com/nrwl/nx/issues/14071 which has gone stale multiple times before being closed. Contains MRE.
