### ISSUE TITLE
Can't build a package that depends on an external package that depends on an inlined package

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#20035]
### Current Behavior

Alright:
Using @nx/js:tsc

Package A is a buildable package which is using the "external" option to inline some packages, and externalize others.

Package B is one of the "external" dependencies of package A

Package B is also using the "external" option to externalize some packages and inline others.

Package C is a non-buildable lib that is an "inline" dependency of package B.

Package B builds correctly and includes package C in its build output

Package A fails to build with an internal Nx error.

### Expected Behavior

Package A should build successfully

The error happens here:

https://github.com/nrwl/nx/blob/master/packages/js/src/utils/inline.ts#L90

There seems to be a mismatch in expectations between the inlining processing code and the Typescript compilation code. The inlining expects the dist/ output of package A to contain a compiled set of files for package C, but there aren't any at that time.

### GitHub Repo

https://github.com/DevCycleHQ/js-sdks/pull/593/commits/7e8e88f726511bb20163b5430752b8107c5e5d25

### Steps to Reproduce

1. Clone repo at that commit
2. yarn
3. yarn build openfeature-nodejs-provider
4. see error

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   yarn   : 3.6.0

   nx                 : 16.10.0
   lerna              : 5.6.2
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/detox          : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/esbuild        : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/next           : 16.10.0
   @nx/node           : 16.10.0
   @nx/react          : 16.10.0
   @nx/react-native   : 16.10.0
   @nrwl/rollup       : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @altack/nx-bundlefy : 0.16.0
```

### Failure Logs

```shell
node:fs:1593
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, lstat '/Users/adamwootton/Code/taplytics/js-sdks/dist/sdk/openfeature-nodejs-provider/lib/shared/server-request'
    at Object.lstatSync (node:fs:1593:3)
    at Object.lstatSync (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/graceful-fs-npm-4.2.10-79c70989ca/node_modules/graceful-fs/polyfills.js:318:34)
    at statFunc (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/fs-extra-npm-11.1.1-ca44602180/node_modules/fs-extra/lib/util/stat.js:24:20)
    at getStatsSync (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/fs-extra-npm-11.1.1-ca44602180/node_modules/fs-extra/lib/util/stat.js:25:19)
    at Object.checkPathsSync (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/fs-extra-npm-11.1.1-ca44602180/node_modules/fs-extra/lib/util/stat.js:67:33)
    at copySync (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/fs-extra-npm-11.1.1-ca44602180/node_modules/fs-extra/lib/copy/copy-sync.js:27:38)
    at movePackage (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:162:29)
    at postProcessInlinedDependencies (/Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/utils/inline.js:46:17)
    at /Users/adamwootton/Code/taplytics/js-sdks/node_modules/.store/@nx-js-virtual-1cde1b2242/node_modules/@nx/js/src/executors/tsc/tsc.impl.js:73:53
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/Users/adamwootton/Code/taplytics/js-sdks/dist/sdk/openfeature-nodejs-provider/lib/shared/server-request'
}
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ajwootto** [comment]
not stale

**Comment by jorisw** [comment]
@ajwootto I'm trying to debug the same thing. By "external", do you mean the `ignoredDependencies` or the `peerDependencies`? I can't find the word external in your changes in the repro commit you added.
