### ISSUE TITLE
Unable to add plugin after transforming to flat config

### ISSUE THREAD

**Issue by yukimotochern** [nrwl/nx#20047]
### Current Behavior

Create a new workspace and run the followings will cause error
```bash
pnpm dlx create-nx-workspace@latest
pnpm nx g @nx/linter:convert-to-flat-config
pnpm add -D @nx/plugin
pnpm exec nx generate @nx/plugin:plugin --name=test-plugin --verbose
```

Logs
```
yukimoto@MacStudio: ~/playground
$ pnpm dlx create-nx-workspace@latest                                                               [9:39:13]
../Library/pnpm/store/v3/tmp/dlx-22444   |  +67 +++++++
../Library/pnpm/store/v3/tmp/dlx-22444   | Progress: resolved 67, reused 66, downloaded 1, added 67, done

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · org
✔ Which stack do you want to use? · node
✔ What framework should be used? · none
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · org
✔ Would you like to generate a Dockerfile? [https://docs.docker.com/] · No
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v17.0.3 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✔ Successfully created the workspace: org.

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   Nx CLI is not installed globally.

   This means that you might have to use "yarn nx" or "npx nx" to execute commands in the workspace.
   Run "yarn global add nx" or "npm install -g nx" to be able to execute command directly.


yukimoto@MacStudio: ~/playground
$ cd org                                                                                            [9:40:10]

yukimoto@MacStudio: ~/playground/org main
$ pnpm nx g @nx/linter:convert-to-flat-config                                                       [9:40:16]

>  NX  Generating @nx/linter:convert-to-flat-config

DELETE .eslintrc.json
DELETE .eslintignore
CREATE eslint.config.js
UPDATE package.json
DELETE apps/org/.eslintrc.json
CREATE apps/org/eslint.config.js
DELETE apps/org-e2e/.eslintrc.json
CREATE apps/org-e2e/eslint.config.js

yukimoto@MacStudio: ~/playground/org main ⚡
$ pnpm add -D @nx/plugin                                                                            [9:41:09]
Packages: +2
++
Progress: resolved 645, reused 606, downloaded 0, added 2, done

devDependencies:
+ @nx/plugin 17.0.3

Done in 2.6s

yukimoto@MacStudio: ~/playground/org main ⚡
$ pnpm exec nx generate @nx/plugin:plugin --name=test-plugin --verbose                              [9:41:32]

>  NX  Generating @nx/plugin:plugin


 >  NX   Unexpected token } in JSON at position 365


SyntaxError: Unexpected token } in JSON at position 365
    at JSON.parse (<anonymous>)
    at hasOverride (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+eslint@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85_@types+node@18.7.1_eslint@8.46.0_nx@17.0.3/node_modules/@nx/eslint/src/generators/utils/flat-config/ast-utils.js:66:31)
    at lintConfigHasOverride (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+eslint@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85_@types+node@18.7.1_eslint@8.46.0_nx@17.0.3/node_modules/@nx/eslint/src/generators/utils/eslint-file.js:168:44)
    at updateRootEslintConfig (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85_@types+node@18.7.1_eslint@8.46.0__xej7scmxrd646xttjrdqvo4jmm/node_modules/@nx/plugin/src/generators/lint-checks/generator.js:145:54)
    at pluginLintCheckGenerator (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85_@types+node@18.7.1_eslint@8.46.0__xej7scmxrd646xttjrdqvo4jmm/node_modules/@nx/plugin/src/generators/lint-checks/generator.js:14:9)
    at pluginGeneratorInternal (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85_@types+node@18.7.1_eslint@8.46.0__xej7scmxrd646xttjrdqvo4jmm/node_modules/@nx/plugin/src/generators/plugin/plugin.js:99:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/yukimoto/playground/org/node_modules/.pnpm/nx@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85/node_modules/nx/src/command-line/generate/generate.js:241:26
    at async handleErrors (/Users/yukimoto/playground/org/node_modules/.pnpm/nx@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85/node_modules/nx/src/utils/params.js:9:16)
    at async Object.handler (/Users/yukimoto/playground/org/node_modules/.pnpm/nx@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85/node_modules/nx/src/command-line/generate/command-object.js:13:22)
FAIL: 1
```

### Expected Behavior

No error

### GitHub Repo

https://github.com/yukimotochern/nx-plugin-error-demo

### Steps to Reproduce

1. `pnpm dlx create-nx-workspace@latest`
2. `pnpm nx g @nx/linter:convert-to-flat-config`
3. `pnpm add -D @nx/plugin`
4. `pnpm exec nx generate @nx/plugin:plugin --name=test-plugin --verbose`

### Nx Report

```shell
$ pnpm nx report                                                                                                      [9:44:43]

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   pnpm   : 8.6.11

   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/esbuild        : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/node           : 17.0.3
   @nx/plugin         : 17.0.3
   @nrwl/tao          : 17.0.3
   typescript         : 5.1.6
```

### Failure Logs

```shell
>  NX  Generating @nx/plugin:plugin


 >  NX   Unexpected token } in JSON at position 365


SyntaxError: Unexpected token } in JSON at position 365
    at JSON.parse (<anonymous>)
    at hasOverride (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+eslint@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85_@types+node@18.7.1_eslint@8.46.0_nx@17.0.3/node_modules/@nx/eslint/src/generators/utils/flat-config/ast-utils.js:66:31)
    at lintConfigHasOverride (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+eslint@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85_@types+node@18.7.1_eslint@8.46.0_nx@17.0.3/node_modules/@nx/eslint/src/generators/utils/eslint-file.js:168:44)
    at updateRootEslintConfig (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85_@types+node@18.7.1_eslint@8.46.0__xej7scmxrd646xttjrdqvo4jmm/node_modules/@nx/plugin/src/generators/lint-checks/generator.js:145:54)
    at pluginLintCheckGenerator (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85_@types+node@18.7.1_eslint@8.46.0__xej7scmxrd646xttjrdqvo4jmm/node_modules/@nx/plugin/src/generators/lint-checks/generator.js:14:9)
    at pluginGeneratorInternal (/Users/yukimoto/playground/org/node_modules/.pnpm/@nx+plugin@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85_@types+node@18.7.1_eslint@8.46.0__xej7scmxrd646xttjrdqvo4jmm/node_modules/@nx/plugin/src/generators/plugin/plugin.js:99:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/yukimoto/playground/org/node_modules/.pnpm/nx@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85/node_modules/nx/src/command-line/generate/generate.js:241:26
    at async handleErrors (/Users/yukimoto/playground/org/node_modules/.pnpm/nx@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85/node_modules/nx/src/utils/params.js:9:16)
    at async Object.handler (/Users/yukimoto/playground/org/node_modules/.pnpm/nx@17.0.3_@swc-node+register@1.6.7_@swc+core@1.3.85/node_mo
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by yukimotochern** [comment]
Still happening on 17.1.2

**Comment by meeroslav** [comment]
Thank you for reporting this. We will look into it as soon as possible.
