### ISSUE TITLE
npm upgrade does not upgrade @nrwl/eslint-plugin-nx

### ISSUE THREAD

**Issue by the-ult** [nrwl/nx#2006]
## Expected Behavior

Running `npm run update` should update @nrwl/* to 8.7.0

## Current Behavior
`"@nrwl/eslint-plugin-nx": "8.6.0",`
is not automatically updated and blocks the upgrade process:
```
> ng update @nrwl/workspace
Using package manager: 'npm'
Collecting installed dependencies...
Found 94 dependencies.
Fetching dependency metadata from registry...
                  Package "@nrwl/eslint-plugin-nx" has an incompatible peer dependency to "@nrwl/workspace" (requires "8.6.0", would install "8.7.0").
Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

### Context

```
"@nrwl/cypress": "8.6.0",
 "@nrwl/eslint-plugin-nx": "8.6.0",
 "@nrwl/express": "8.6.0",
 "@nrwl/jest": "8.6.0",
 "@nrwl/node": "8.6.0",
 "@nrwl/workspace": "8.6.0",
```

```
Angular CLI: 9.0.0-next.11
Node: 12.9.1
OS: linux x64
Angular: 9.0.0-next.11
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.3
@angular-devkit/build-angular     0.803.12
@angular-devkit/build-optimizer   0.803.12
@angular-devkit/build-webpack     0.803.12
@angular-devkit/core              9.0.0-next.11
@angular-devkit/schematics        8.3.3
@angular/cdk                      9.0.0-next.0
@angular/material                 9.0.0-next.0
@ngtools/webpack                  8.3.12
@schematics/angular               8.3.3
@schematics/update                0.900.0-next.11
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.39.2
```

**Comment by FrozenPandaz** [comment]
@jaysoo Can you please look into why `@nrwl/eslint-plugin-nx` was not updated?

**Comment by the-ult** [comment]
@jaysoo and @FrozenPandaz 
The issue is still occuring (8.11.1)

**Comment by jaysoo** [comment]
I wasn't able to reproduce. @the-ult Are you still having issues? Can you try upgrade again (to `9.2.2`)?

**Comment by the-ult** [comment]
@jaysoo 

Running on NX 8.1.2

```console

❯ npm run update

> ult-starter-workspace@0.0.0 update /Users/ultimate-solutions/dev/ultimate-nx-starter-workspace
> ng update @nrwl/workspace

The installed Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 107 dependencies.
Fetching dependency metadata from registry...
                  Package "@nrwl/eslint-plugin-nx" has an incompatible peer dependency to "@nrwl/workspace" (requires "8.12.1", would install "9.2.2").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/private/var/folders/6j/nbqyf2ld4wv320qvkdm71jl00000gn/T/ng-4Z1bHn/angular-errors.log" for further details.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ult-starter-workspace@0.0.0 update: `ng update @nrwl/workspace`
npm ERR! Exit status 1

``` 

NX Report
``` 
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 8.12.1
  @nrwl/cli : 8.12.1
  @nrwl/cypress : 8.12.1
  @nrwl/eslint-plugin-nx : 8.12.1
  @nrwl/express : 8.12.1
  @nrwl/jest : 8.12.1
  @nrwl/linter : 8.12.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 8.12.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.12.1
  @nrwl/web : Not Found
  @nrwl/workspace : 8.12.1
  typescript : 3.7.5
```

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.12
Node: 13.12.0
OS: darwin x64

Angular: 9.0.0-rc.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.900.0-rc.12
@angular-devkit/build-optimizer   0.900.0-rc.12
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cdk                      9.0.0-rc.9
@angular/cli                      9.0.0-rc.12
@angular/material                 9.0.0-rc.9
@ngtools/webpack                  9.0.0-rc.12
@schematics/angular               8.3.23
@schematics/update                0.900.0-rc.12
ng-packagr                        9.0.0-rc.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```


In my current projects we are not using `eslint / @nrwl/eslint-plugin-nx`, so I do not know what the status is with more updated projects.

You could close it for now.
If it occurs on future projects again, I'll create a new issue and link to this one.

**Comment by FrozenPandaz** [comment]
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by arjunyel** [comment]
Im getting this on NX 9.4.0 trying to upgrade to 9.4.1, and also got it when upgrading from 9.3.0 to 9.4.0, Im happy to post any logs that may help

```
> ng update @nrwl/workspace

Using package manager: 'npm'
Collecting installed dependencies...
Found 146 dependencies.
Fetching dependency metadata from registry...
                  Package "@nrwl/eslint-plugin-nx" has an incompatible peer dependency to "@nrwl/workspace" (requires "9.4.0", would install "9.4.1").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/private/var/folders/88/79l15vcd0xqcglhncwcnqb_80000gn/T/ng-hE82Cj/angular-errors.log" for further details.
```

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.4.0
  @nrwl/cli : 9.4.0
  @nrwl/cypress : 9.4.0
  @nrwl/eslint-plugin-nx : 9.4.0
  @nrwl/express : 9.4.0
  @nrwl/jest : 9.4.0
  @nrwl/linter : 9.4.0
  @nrwl/nest : 9.4.0
  @nrwl/next : Not Found
  @nrwl/node : 9.4.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 9.4.0
  typescript : 3.8.3
```

**Comment by jdpearce** [comment]
Managed to reproduce with 9.4.0 :

1. `npx create-nx-workspace@9.4.0 --preset angular-nest`
2. `ng add @nrwl/eslint-plugin-nx@9.4.0`
3. `ng update @nrwl/workspace`

> ./node_modules/.bin/ng update @nrwl/workspace
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 40 dependencies.
Fetching dependency metadata from registry...
                  Package "@nrwl/eslint-plugin-nx" has an incompatible peer dependency to "@nrwl/workspace" (requires "9.4.0", would install "9.5.1").
                  Package "@nrwl/angular" has a missing peer dependency of "tslib" @ "^1.10.0".
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/private/var/folders/wz/q0cp0td92jq7xw397rtyzv2h0000gn/T/ng-PebE8h/angular-errors.log" for further details.

The log file just has a stack trace deep in Angular:

> [error] Error: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
    at _validateUpdatePackages (/private/var/folders/wz/q0cp0td92jq7xw397rtyzv2h0000gn/T/angular-cli-packages-B7NWXS/node_modules/@schematics/update/update/index.js:154:15)
    at SwitchMapSubscriber.project (/private/var/folders/wz/q0cp0td92jq7xw397rtyzv2h0000gn/T/angular-cli-packages-B7NWXS/node_modules/@schematics/update/update/index.js:695:17)
    <snipped a ton of RxJS stuff...>

Personally, I'd suggest using `nx migrate` rather than `ng update` in these cases.

**Comment by jdpearce** [comment]
This is fixed for future releases, but if you still have this problem on an older version of workspace, you can monkey patch the `package.json` in `@nrwl/workspace` as in the linked PR.
