### ISSUE TITLE
 Failed to run migration-v16-remove-module-id from @angular/core. This workspace is NOT up to date!

### ISSUE THREAD

**Issue by phani17c** [nrwl/nx#20076]
### Current Behavior

>  NX   Failed to run migration-v16-remove-module-id from @angular/core. This workspace is NOT up to date!

 >  NX   (0 , rxjs_1.map) is not a function

I am having "@angular-devkit/schematics": "16.2.7"

### Expected Behavior

Smooth migration

### Steps to Reproduce

1. nx migrate 16.10.0

### Nx Report

```shell
Node   : 18.13.0
   OS     : darwin-arm64
   npm    : 8.19.3
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/nest           : 16.10.0
   @nx/node           : 16.10.0
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @datorama/akita       : 6.2.4
   @ng-toolkit/universal : 8.1.0
   @storybook/angular    : 7.5.2
```

### Failure Logs

```shell
>  NX   Failed to run migration-v16-remove-module-id from @angular/core. This workspace is NOT up to date!


 >  NX   (0 , rxjs_1.map) is not a function


TypeError: (0 , rxjs_1.map) is not a function
    at new IndentLogger (/Users/U0PX/Projects/uk.monorepo/node_modules/@angular-devkit/core/src/logger/indent.js:26:65)
    at createConsoleLogger (/Users/U0PX/Projects/uk.monorepo/node_modules/@angular-devkit/core/node/cli-logger.js:17:20)
    at getLogger (/Users/U0PX/Projects/uk.monorepo/node_modules/nx/src/adapter/ngcli-adapter.js:665:49)
    at Object.runMigration (/Users/U0PX/Projects/uk.monorepo/node_modules/nx/src/adapter/ngcli-adapter.js:476:42)
    at executeMigrations (/Users/U0PX/Projects/uk.monorepo/node_modules/nx/src/command-line/migrate/migrate.js:889:74)
    at async runMigrations (/Users/U0PX/Projects/uk.monorepo/node_modules/nx/src/command-line/migrate/migrate.js:962:37)
    at async /Users/U0PX/Projects/uk.monorepo/node_modules/nx/src/command-line/migrate/migrate.js:1031:13
    at async handleErrors (/Users/U0PX/Projects/uk.monorepo/node_modules/nx/src/utils/params.js:9:16)
    at async Object.handler (/Users/U0PX/Projects/uk.monorepo/node_modules/nx/src/command-line/migrate/command-object.js:26:43)
Command failed: npx nx _migrate --run-migrations --verbose
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by datatunning** [comment]
Same issue here on a migration from nx15.9.4 to nx16.10.0 where nx workspace is not on the git repo root.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I haven't been able to reproduce the issue. I tried creating a new Nx workspace using Nx 15.9.4, as mentioned in https://github.com/nrwl/nx/issues/20076#issuecomment-1896039559, but I was able to migrate successfully to Nx 16.10.0. Given the error, I also tried setting the RxJS version to `~6.6.7` but still got a successful migration.

Please provide a repository with the Nx v15.x.x version where migrating to 16.10.0 produces the error so we can troubleshoot it.
