### ISSUE TITLE
Having trouble running a default install

### ISSUE THREAD

**Issue by adyngom** [nrwl/nx#2007]
Fresh Install:
```
+ @angular/cli@8.3.15
+ @nrwl/schematics@8.7.0
added 10 packages from 6 contributors, removed 2 packages and updated 41 packages in 25.383s
Adys-MacBook-Pro:monorepos ng-om$ npx create-nx-workspace nrwl-airways
npx: installed 166 in 8.299s
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    nwairways
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
Creating a sandbox with Nx...
error Incorrect integrity when fetching from the cache
(node:16323) UnhandledPromiseRejectionWarning: Error: Command failed: yarn install --silent
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at createSandbox (/Users/ng-om/.npm/_npx/16323/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:335:21)
    at determineCli.then.cli (/Users/ng-om/.npm/_npx/16323/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:73:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16323) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16323) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Commands ran:

```
npm install -g @angular/cli @nrwl/schematics
```

and 

```
npx create-nx-workspace nrwl-airways
```

**Comment by adyngom** [comment]
Seems to be a yarn cache issue after all - Not so obvious when following steps from the book. This seems to fix it:

```
yarn clean cache
```
 Thanks Doug Richardson: https://stackoverflow.com/a/58172689
