### ISSUE TITLE
json.overrides in eslint-file.ts is not initialized when undefined

### ISSUE THREAD

**Issue by nolegendhere** [nrwl/nx#20116]
### Current Behavior
json.overrides ?? []; in line 199 of eslint-file.ts in eslint package generators
When undefined, it is not initiallized

### Expected Behavior
json.overrides ??= []; in line 199 of eslint-file.ts in eslint package generators
initialize it when undefined

### GitHub Repo

https://github.com/nrwl/nx/blob/master/packages/eslint/src/generators/utils/eslint-file.ts#L199

### Steps to Reproduce

“@nx/eslint-plugin”: “16.5.1",
nx g @nx/playwright:configuration --project=project_name

### Nx Report

```shell
TypeError: Cannot read properties of undefined (reading 'push')
    at /Users/martinpuertas/dist-clients/node_modules/@nx/eslint/src/generators/utils/eslint-file.js:128:32
    at updateJson (/Users/martinpuertas/dist-clients/node_modules/nx/src/generators/utils/json.js:45:26)
    at addOverrideToLintConfig (/Users/martinpuertas/dist-clients/node_modules/@nx/eslint/src/generators/utils/eslint-file.js:125:33)
    at addLinterToPlaywrightProject (/Users/martinpuertas/dist-clients/node_modules/@nx/playwright/src/utils/add-linter.js:42:51)
    at configurationGenerator (/Users/martinpuertas/dist-clients/node_modules/@nx/playwright/src/generators/configuration/configuration.js:24:68)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by meeroslav** [comment]
Good catch! Thank you!
