### ISSUE TITLE
17.1.1 breaking webpack compile

### ISSUE THREAD

**Issue by snigdha920** [nrwl/nx#20179]
### Current Behavior

When i run the command `pnpm nx run saas-api:serve`, which is configured as follows: 
```
"serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "watch": false,
      "options": {
        "buildTarget": "saas-api:build",
        "port": 9232
      },
      "configurations": {
        "production": {
          "buildTarget": "saas-api:build:production"
        },
        "development": {
          "buildTarget": "saas-api:build:development"
        }
      }
    },
``` 

I get the following error with the new version 17.1.1:

```
/Users/snigdhasingh/bpaas/apps/saas/api/webpack.hmr.config.js:28
    entry: ['webpack/hot/poll?100', ...config.entry.main],
                                                    ^

TypeError: config.entry.main is not iterable
    at /Users/snigdhasingh/bpaas/apps/saas/api/webpack.hmr.config.js:28:53
    at combined (/Users/snigdhasingh/bpaas/node_modules/.pnpm/@nx+webpack@17.1.1_@swc-node+register@1.6.8_@swc+core@1.3.96_@types+node@20.9.0_nx@17.1.1_typ_icnssm66it4icekjn2xiba4qom/node_modules/@nx/webpack/src/utils/config.js:17:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getWebpackConfigs (/Users/snigdhasingh/bpaas/node_modules/.pnpm/@nx+webpack@17.1.1_@swc-node+register@1.6.8_@swc+core@1.3.96_@types+node@20.9.0_nx@17.1.1_typ_icnssm66it4icekjn2xiba4qom/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:33:16)
    at async webpackExecutor (/Users/snigdhasingh/bpaas/node_modules/.pnpm/@nx+webpack@17.1.1_@swc-node+register@1.6.8_@swc+core@1.3.96_@types+node@20.9.0_nx@17.1.1_typ_icnssm66it4icekjn2xiba4qom/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:88:21)
    at async /Users/snigdhasingh/bpaas/node_modules/.pnpm/@nx+js@17.1.1_@swc-node+register@1.6.8_@swc+core@1.3.96_@types+node@20.9.0_nx@17.1.1_typescript@5.2.2_verdaccio@5.27.0/node_modules/@nx/js/src/executors/node/node.impl.js:191:31
```

### Expected Behavior

It worked perfectly with 17.0.3, we upgraded to 17.1.1 and that's when it started breaking. 

### Steps to Reproduce

Don't have a repo to reproduce yet, lmk if it is needed.

### Nx Report

```shell
pnpm nx report

> bpaas@6.171.2 nx /Users/snigdhasingh/bpaas
> nx "report"


 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   pnpm   : 8.5.1

   nx                 : 17.1.1
   @nx/js             : 17.1.1
   @nx/jest           : 17.1.1
   @nx/linter         : 17.1.1
   @nx/eslint         : 17.1.1
   @nx/workspace      : 17.1.1
   @nx/cypress        : 17.1.1
   @nx/devkit         : 17.1.1
   @nx/eslint-plugin  : 17.1.1
   @nx/nest           : 17.1.1
   @nx/next           : 17.1.1
   @nx/node           : 17.1.1
   @nx/playwright     : 17.1.1
   @nx/react          : 17.1.1
   @nx/rollup         : 17.1.1
   @nrwl/tao          : 17.1.1
   @nx/web            : 17.1.1
   @nx/webpack        : 17.1.1
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @nx-go/nx-go              : 2.8.0
   @nx-tools/nx-container    : 5.1.0
   @webpro/nx-tsc            : 0.0.1
   nest-commander-schematics : 3.0.0

```
```


### Failure Logs

_No response_

### Package Manager Version

pnpm v8.5.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by roderik** [comment]
Found it, the config format has changed messing with the hot module reload setup for nestjs, adding `.import` to the entry line makes it work.

```
const { composePlugins, withNx } = require('@nx/webpack');
const nodeExternals = require('webpack-node-externals');
const webpack = require('webpack');
const { relative } = require('path');
const { readFileSync } = require('fs');

// Set true if you don't want type checking
const skipTypeChecking = false;

// Nx plugins for webpack.
module.exports = composePlugins(withNx({ skipTypeChecking }), (config) => {
  // Update the webpack config as needed here.
  // e.g. `config.plugins.push(new MyPlugin())`

  config.output.devtoolModuleFilenameTemplate = function (info) {
    const rel = relative(process.cwd(), info.absoluteResourcePath);
    return `webpack:///./${rel}`;
  };

  const swcConfig = JSON.parse(readFileSync('apps/onprem/deploy-workers/.swcrc', 'utf-8'));
  const swcLoaderRule = config.module.rules.find((rule) => rule?.loader?.includes('swc-loader'));
  if (swcLoaderRule) {
    swcLoaderRule.options = swcConfig;
  }

  return {
    ...config,
    entry: ['webpack/hot/poll?100', ...config.entry.main.import],
    externals: [
      nodeExternals({
        allowlist: ['webpack/hot/poll?100'],
      }),
    ],
    plugins: [
      ...config.plugins,
      new webpack.HotModuleReplacementPlugin(),
      new webpack.WatchIgnorePlugin({
        paths: [/\.js$/, /\.d\.ts$/],
      }),
    ],
  };
});
```

**Comment by jaysoo** [comment]
We can change it back. There is a preparatory refactoring to allow Nx to be used in a standard webpack plugin, which doesn't work when entries are treated as iterable.

**Comment by jaysoo** [comment]
Incoming patch https://github.com/nrwl/nx/pull/20187

The workaround from @roderik is okay for now, but better to wait for the patch or do something like:

```
// TODO: Remove the config.entry.main.import check once 17.1.2 lands because config.entry.main will be iterable again
entry: ['webpack/hot/poll?100',  ...(config.entry.main.import ? config.entry.main.import : config.entry.main)],
```

So when 17.1.2 is released the config won't break again
