### ISSUE TITLE
 Build Fails when using Next 14.0.2 and Highcharts 11.2.0 in NX

### ISSUE THREAD

**Issue by gcko** [nrwl/nx#20231]
### Current Behavior

Production build fails with ```TypeError: Cannot read properties of undefined (reading 'document')``` (seems related to highcharts)

#### Product versions
```json
{
  "nx": "17.1.2",
  "highcharts": "11.2.0",
  "next": "14.0.2"
}
```

#### Affected browser(s)
N/A

### Expected Behavior

Production build will successfully generate in NX when using Next version `14.0.2` and Highcharts

### GitHub Repo

https://github.com/gcko/reproduction

#### Live demo with steps to reproduce
[![Edit gcko/reproduction/main](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/gcko/reproduction/main?import=true&embed=1&file=%2F.codesandbox%2Ftasks.json&showConsole=true)

1. run the following
```shell
nx run test:build
```

### Nx Report

```shell
node@20.9.0$ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : darwin-x64
   npm    : 10.1.0
   
   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nx/next           : 17.1.2
   @nx/react          : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/web            : 17.1.2
   typescript         : 5.2.2
```

### Failure Logs

```shell
node@20.9.0$ nx run test:build

> nx run test:build:production

   ▲ Next.js 14.0.2
   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping linting
   Checking validity of types ...
   Collecting page data ...
   Generating static pages (0/5) ...
   Generating static pages (1/5) 
   Generating static pages (2/5) 
   Generating static pages (3/5) 
TypeError: Cannot read properties of undefined (reading 'document')
    at /Users/jaredmscott/repos/projects/reproduction/dist/apps/test/.next/server/app/page.js:1:12408
    at 851 (/Users/jaredmscott/repos/projects/reproduction/dist/apps/test/.next/server/app/page.js:1:12493)
    at t (/Users/jaredmscott/repos/projects/reproduction/dist/apps/test/.next/server/webpack-runtime.js:1:142)
    at 6065 (/Users/jaredmscott/repos/projects/reproduction/dist/apps/test/.next/server/app/page.js:1:2136)
    at t (/Users/jaredmscott/repos/projects/reproduction/dist/apps/test/.next/server/webpack-runtime.js:1:142)
    at F (/Users/jaredmscott/repos/projects/reproduction/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91961)
    at /Users/jaredmscott/repos/projects/reproduction/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94376
    at W._fromJSON (/Users/jaredmscott/repos/projects/reproduction/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94814)
    at JSON.parse (<anonymous>)
    at N (/Users/jaredmscott/repos/projects/reproduction/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91682)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'document')
    at /Users/jaredmscott/repos/projects/reproduction/dist/apps/test/.next/server/app/page.js:1:12408
    at 851 (/Users/jaredmscott/repos/projects/reproduction/dist/apps/test/.next/server/app/page.js:1:12493)
    at t (/Users/jaredmscott/repos/projects/reproduction/dist/apps/test/.next/server/webpack-runtime.js:1:142)
    at 6065 (/Users/jaredmscott/repos/projects/reproduction/dist/apps/test/.next/server/app/page.js:1:2136)
    at t (/Users/jaredmscott/repos/projects/reproduction/dist/apps/test/.next/server/webpack-runtime.js:1:142)
    at F (/Users/jaredmscott/repos/projects/reproduction/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91961)
    at /Users/jaredmscott/repos/projects/reproduction/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94376
    at W._fromJSON (/Users/jaredmscott/repos/projects/reproduction/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:94814)
    at JSON.parse (<anonymous>)
    at N (/Users/jaredmscott/repos/projects/reproduction/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91682)
 ✓ Generating static pages (5/5) 
> Export encountered errors on following paths:
        /page: /
Error occurred while trying to run the build command
1

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project test (10s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

### Package Manager Version

npm 10.1.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This seems related to the latest version of next 14.0.2 and specifically when using Highcharts 11.2.0. This is not reproducible when using Next and Highcharts alone, only when NX is used.

**Comment by gcko** [comment]
@AgentEnder FYI this is being tracked here as well: https://github.com/highcharts/highcharts/issues/20129

**Comment by gcko** [comment]
From the work I have been doing debugging with the Highcharts team, this does not seem to be related to nx in any way. Closing this issue.
