### ISSUE TITLE
create-nx-workspace stuck in "Creating your workspace" step

### ISSUE THREAD

**Issue by Markus-Ende** [nrwl/nx#20270]
### Current Behavior

```
❯ npx create-nx-workspace@latest testwslatest
Need to install the following packages:
  create-nx-workspace@17.1.2
Ok to proceed? (y)

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Which stack do you want to use? · angular
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · testwslatest
✔ Which bundler would you like to use? · webpack
✔ Default stylesheet format · css
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · Yes
✔ Test runner to use for end to end (E2E) tests · cypress
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v17.1.2 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
⠸ Creating your workspace in testwslatest
```

Stuck in this state, no progress.

Is there some way to get more logs?

### Expected Behavior

Should finish creating the workspace.

### Steps to Reproduce

1. Run  npx create-nx-workspace@latest testwslatest
2. Tested with those options:
✔ Which stack do you want to use? · angular
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · testwslatest
✔ Which bundler would you like to use? · webpack
✔ Default stylesheet format · css
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · Yes
✔ Test runner to use for end to end (E2E) tests · cypress
✔ Enable distributed caching to make your CI faster · No

But also failed with 17.0.2 and 17.0.3 and with other options (e.g. NestJs app, even with type "None")

### Nx Report

```shell
Nx workspace not created, yet.
```

### Failure Logs

```shell
There are no logs.
```

### Package Manager Version

npm 9.5.1

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [X] Other (Please specify)

### Additional Information

Operating System: WSL2 under Windows

**Comment by Markus-Ende** [comment]
Maybe it just takes very long and I'm too impatient? Is there a way to get more logs?

**Comment by Ollitod** [comment]
Same here. I executed create-nx-workspace@17.1.3 on Windows 10 and after an hour it is still stuck in "Creating your workspace".

**Comment by Markus-Ende** [comment]
update: tried with v17.3.0, it still does not work

**Comment by schoggobaer** [comment]
It also wont work for me with the same command
```
ProductName:            macOS
ProductVersion:         14.2.1
BuildVersion:           23C71
```

**Comment by Markus-Ende** [comment]
Another update: it **did** work on an older non-M1 macbook.

**Comment by Markus-Ende** [comment]
Update: still not working with 18.2.4

**Comment by BaggersIO** [comment]
Same here. Still not working.

**Comment by Samaneh** [comment]
I'm using Windows 10, node v20, taking more than one hour to generate the workspace :/

**Comment by matthew-shirey** [comment]
Is there a workaround... _any_?  Suggested last version to use?  I'm stuck here too and this seems like a rather severe blocker.  I'm surprised that there's no helpful information here considering how long this one's been reported.  Any help would greatly be appreciated.  Thank you.

**Comment by ekawatani** [comment]
Getting the same result. I'm running it on WSL2 Ubuntu running nix dev shell, using NX v19.2.3.

<img width="575" alt="image" src="https://github.com/nrwl/nx/assets/61330990/f8f4526d-a1f4-4994-880c-fd54a83ad2d1">

**Comment by ekawatani** [comment]
Ok, maybe I was too early to post it. The command worked this time, but it took 27m57s. I know this since I use Starship to measure the length of a shell command. That's too slow, and something is definitely wrong.

**Comment by bhaugeea** [comment]
Currently running into this as well.

**Comment by mshirey** [comment]
I just hit this one again.  On Windows 11, this command worked fine.  On an update to date Manjaro Linux, it just hangs.  I left it for well over an hour with no progress.  Is there any logging that can be turned on to maybe get a bit of feedback regarding what it's _not_ doing?

**Comment by adyatlov** [comment]
I believe it's a bug. As far as I understand, the nx's post-install script is the main culprit. Here is the way I reproduce it.
Environment:
```
$ sw_vers
ProductName:            macOS
ProductVersion:         14.5
BuildVersion:           23F79

$ which node
/Users/adyatlov/.nvm/versions/node/v22.6.0/bin/node

$ node --version
v22.6.0

$ npx nx --version
Nx Version:
- Local: Not found
- Global: v19.5.7
```
Steps:
```
$ killall -9 node # to avoid possible interferences with previous runs

$ npx create-nx-workspace # chose all default options

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · org
✔ Which stack do you want to use? · none
✔ Package-based monorepo, integrated monorepo, or standalone project? · package-based
✔ Which CI provider would you like to use? · github

 NX   Creating your v19.5.7 workspace.

✔ Installing dependencies with npm
⠇ Creating your workspace in org # <-- it got stuck here
```
Troubleshooting steps:
```
# Press ^C
$ ps aux | grep "npm install"
...
adyatlov         14332   0.0  1.5 412357872 248832 s003  S     8:12PM   0:04.50 npm install # still running
$ killall -9 node # to clean up 
$ cd org
$ npm install # <-- it got stuck here again
# Press ^C
npm error code 130
npm error path /Users/adyatlov/tmp/org/node_modules/nx
npm error command failed
npm error command sh -c node ./bin/post-install
npm error A complete log of this run can be found in: /Users/adyatlov/.npm/_logs/2024-08-14T21_03_42_775Z-debug-0.log
```
Relevant logs:
```
2002 info run nx@19.5.7 postinstall node_modules/nx node ./bin/post-install
2003 info run nx@19.5.7 postinstall { code: 130, signal: null }
2004 verbose stack Error: command failed
2004 verbose stack     at promiseSpawn (/Users/adyatlov/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
2004 verbose stack     at spawnWithShell (/Users/adyatlov/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
2004 verbose stack     at promiseSpawn (/Users/adyatlov/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
2004 verbose stack     at runScriptPkg (/Users/adyatlov/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
2004 verbose stack     at runScript (/Users/adyatlov/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
2004 verbose stack     at /Users/adyatlov/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
2004 verbose stack     at run (/Users/adyatlov/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
2004 verbose stack     at /Users/adyatlov/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
2004 verbose stack     at new Promise (<anonymous>)
2004 verbose stack     at callLimit (/Users/adyatlov/.nvm/versions/node/v22.6.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
2005 verbose pkgid nx@19.5.7
2006 error code 130
2007 error path /Users/adyatlov/tmp/org/node_modules/nx
2008 error command failed
2009 error command sh -c node ./bin/post-install
2010 silly unfinished npm timer reify 1723669422889
2011 silly unfinished npm timer reify:build 1723669424765
2012 silly unfinished npm timer build 1723669424765
2013 silly unfinished npm timer build:deps 1723669424766
2014 silly unfinished npm timer build:run:postinstall 1723669424774
2015 silly unfinished npm timer build:run:postinstall:node_modules/nx 1723669424774
2016 verbose cwd /Users/adyatlov/tmp/org
2017 verbose os Darwin 23.5.0
2018 verbose node v22.6.0
2019 verbose npm  v10.8.2
2020 verbose exit 130
2021 verbose code 130
2022 error A complete log of this run can be found in: /Users/adyatlov/.npm/_logs/2024-08-14T21_03_42_775Z-debug-0.log
```
Full logfile: 
[2024-08-14T21_03_42_775Z-debug-0.log](https://github.com/user-attachments/files/16618884/2024-08-14T21_03_42_775Z-debug-0.log)

Note:
nx v19.4.0 works as expected.

Please contact me if you cannot reproduce the issue on your machine and you want to use my environment for debugging.

**Comment by Markus-Ende** [comment]
I just got the exact same error message, using `npm install` in a project without existing node_modules. 
`postinstall` is stuck and install never finishes.

```
npm verbose os Linux 5.15.153.1-microsoft-standard-WSL2
npm verbose node v22.3.0
npm verbose npm  v10.8.1
```

**Comment by Pedromigacz** [comment]
I've encountered this issue today as well.
```bash
npx create-nx-workspace
Need to install the following packages:
create-nx-workspace@20.0.0
Ok to proceed? (y) y


 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · org
✔ Which stack do you want to use? · react
✔ What framework would you like to use? · nextjs
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · diet-it
✔ Would you like to use the App Router (recommended)? · Yes
✔ Would you like to use the src/ directory? · Yes
✔ Test runner to use for end to end (E2E) tests · none
✔ Default stylesheet format · tailwind
✔ Which CI provider would you like to use? · github

 NX   Creating your v20.0.0 workspace.

✔ Installing dependencies with npm
⠋ Creating your workspace in org
```
It hanged for 10 minutes, then I gave up.
WSL2 Node v22.1.0

**Comment by tonivj5** [comment]
Same here! After a bunch of runs it has worked...

**Comment by crowmagnumb** [comment]
Yup, I let it run for hours, and hours .... stuck on creating ....

**Comment by hmidmrii** [comment]
Not sure if it's related, but happened to me on the second time, first time was fast and normal, the second one still pending,
not sure if it's because both workspaces has the same name

**Comment by crowmagnumb** [comment]
I finally just let it go over night figuring what the heck and it just finished after like 16 hours!  :)

**Comment by yhoungdev** [comment]
> I finally just let it go over night figuring what the heck and it just finished after like 16 hours! :)

This is not normal

**Comment by yhoungdev** [comment]
Got same issue today also, but it was my network. 

  Try checking your network

**Comment by FabianGosebrink** [comment]
I am also facing this issue currently. 

![Image](https://github.com/user-attachments/assets/4b27e41a-2e90-422d-9468-8d124ec1b7a3)

Stuck here since two days :(

**Comment by Tobertet** [comment]
For anyone still having this issue, the problem in my case is related to npm. It is getting stuck. Changing to yarn made it work.

**Comment by ekawatani** [comment]
It could be the npm issue indeed. I no longer have this problem after upgrading npm to 10.9.1.

See https://github.com/npm/cli/issues/7814

**Comment by gustavostz** [comment]
To make it work, I had to execute the create command skipping Prettier, CI, and remote caching.

**Comment by isaacplmann** [comment]
Reopening so that @getlarge can add a comment

**Comment by getlarge** [comment]
I was in a similar situation and it turns out it was related to the `.npmrc` containing some config to use verdaccio local registry🤦 
Since this issue comes in the first Google results when typing: `nx create workspace stuck`  this might help other poor souls...
