### ISSUE TITLE
Generate workspace cannot find modules

### ISSUE THREAD

**Issue by intellix** [nrwl/nx#203]
Was following this for converting a current project to NX: https://nrwl.io/nx/guide-nx-workspace

## Versions:
```
Angular CLI: 1.6.4
Node: 8.9.4
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router
... service-worker

@angular/cli: 1.6.4
@angular/language-service: 5.1.0
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0
```

## Error
```
$ ng generate workspace myapp --collection=@nrwl/schematics

Cannot find module '@angular-devkit/schematics'
Error: Cannot find module '@angular-devkit/schematics'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dominicwatson/.nvm/versions/node/v8.9.4/lib/node_modules/@nrwl/schematics/src/collection/workspace/index.js:11:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by intellix** [comment]
Ahah, it seems I was installing @nrwl/schematics globally and not locally to the project. Apologies :)
