### ISSUE TITLE
Failed to parse pnpm lockfile (on Github Actions)

### ISSUE THREAD

**Issue by Hypenate** [nrwl/nx#20337]
### Current Behavior

`nx run my-app:build:production` does work locally but not on Github Actions

### Expected Behavior

`nx run my-app:build:production` does work locally but and on Github Actions

### GitHub Repo

https://github.com/Hypenate/pogative_ui

### Steps to Reproduce

1. Run the [Action](https://github.com/Hypenate/pogative_ui/actions/workflows/firebase-hosting-merge.yml)

### Nx Report

```shell
Run nx run hike:build:production
  nx run hike:build:production
  shell: /usr/bin/bash -e ***0***
  

 >  NX   Failed to parse pnpm lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   
Original error: Could not find ".modules.yaml" at "/home/runner/work/pogative_ui/pogative_ui/node_modules/.modules.yaml"


   Error: Could not find ".modules.yaml" at "/home/runner/work/pogative_ui/pogative_ui/node_modules/.modules.yaml"
    at loadPnpmHoistedDepsDefinition (/home/runner/work/pogative_ui/pogative_ui/node_modules/nx/src/plugins/js/lock-file/utils/pnpm-normalizer.js:23:15)
    at getNodes (/home/runner/work/pogative_ui/pogative_ui/node_modules/nx/src/plugins/js/lock-file/pnpm-parser.js:69:77)
    at getPnpmLockfileNodes (/home/runner/work/pogative_ui/pogative_ui/node_modules/nx/src/plugins/js/lock-file/pnpm-parser.js:27:12)
    at getLockFileNodes (/home/runner/work/pogative_ui/pogative_ui/node_modules/nx/src/plugins/js/lock-file/lock-file.js:36:59)
    at exports.createNodes (/home/runner/work/pogative_ui/pogative_ui/node_modules/nx/src/plugins/js/index.js:42:64)
    at buildProjectsConfigurationsFromProjectPathsAndPlugins (/home/runner/work/pogative_ui/pogative_ui/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:77:88)
    at createProjectConfigurations (/home/runner/work/pogative_ui/pogative_ui/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:136:138)
    at WorkspaceContext.<anonymous> (/home/runner/work/pogative_ui/pogative_ui/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:29:39)
    at getNxWorkspaceFilesFromContext (/home/runner/work/pogative_ui/pogative_ui/node_modules/nx/src/utils/workspace-context.js:16:29)
    at retrieveWorkspaceFiles (/home/runner/work/pogative_ui/pogative_ui/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:28:100)


 >  NX   GenericFailure
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The repo is private, but I can add you guys to investigate the issue.

**Comment by Hypenate** [comment]
I switched from  npm to pnpm (same as what I have locally) and then it work.
It would maybe make more sense for a beter error message?
