### ISSUE TITLE
React Project is not loading internal libraries

### ISSUE THREAD

**Issue by abbasmashaddy72** [nrwl/nx#20333]
### Current Behavior

Error: The following dependencies are imported but could not be resolved

### Expected Behavior

To Run Smoothly

### GitHub Repo

If you Need Any I can Provide You

### Steps to Reproduce

1. I had a Project that was worked by someone else on NX 15 I tried to run it but had many issues
2. So I created a new NX 17 Project and migrated all the code to the new code base (NX 17).
3. But when I am running it, I'm getting Error: The following dependencies are imported but could not be resolved
4. I tried to check docs & git issues, but was not able to find the problem

Please Help Me: If you need any git Repo, I will provide you

Total Apps 3 based on React & Libraries 5

nx graph output.json
```
{
  "graph": {
    "nodes": {
      "service": {
        "name": "service",
        "type": "lib",
        "data": {
          "root": "libs/service",
          "name": "service",
          "sourceRoot": "libs/service/src",
          "projectType": "library",
          "tags": [
            "scope:service"
          ],
          "targets": {
            "lint": {
              "cache": true,
              "inputs": [
                "default",
                "{workspaceRoot}/.eslintrc.json",
                "{workspaceRoot}/.eslintignore",
                "{workspaceRoot}/eslint.config.js"
              ],
              "executor": "@nx/eslint:lint",
              "outputs": [
                "{options.outputFile}"
              ],
              "options": {
                "lintFilePatterns": [
                  "libs/service/**/*.{ts,tsx,js,jsx}"
                ]
              },
              "configurations": {}
            }
          },
          "implicitDependencies": []
        }
      },
      "common": {
        "name": "common",
        "type": "lib",
        "data": {
          "root": "libs/common",
          "name": "common",
          "sourceRoot": "libs/common/src",
          "projectType": "library",
          "tags": [
            "scope:common"
          ],
          "targets": {
            "lint": {
              "cache": true,
              "inputs": [
                "default",
                "{workspaceRoot}/.eslintrc.json",
                "{workspaceRoot}/.eslintignore",
                "{workspaceRoot}/eslint.config.js"
              ],
              "executor": "@nx/eslint:lint",
              "outputs": [
                "{options.outputFile}"
              ],
              "options": {
                "lintFilePatterns": [
                  "libs/common/**/*.{ts,tsx,js,jsx}"
                ]
              },
              "configurations": {}
            }
          },
          "implicitDependencies": []
        }
      },
      "admin": {
        "name": "admin",
        "type": "app",
        "data": {
          "root": "apps/admin",
          "name": "admin",
          "sourceRoot": "apps/admin/src",
          "projectType": "application",
          "targets": {
            "build": {
              "cache": true,
              "dependsOn": [
                "^build"
              ],
              "inputs": [
                "production",
                "^production"
              ],
              "executor": "@nx/vite:build",
              "outputs": [
                "{options.outputPath}"
              ],
              "defaultConfiguration": "production",
              "options": {
                "outputPath": "dist/apps/admin",
                "index": "apps/admin/src/public/index.html",
                "baseHref": "/",
                "main": "apps/admin/src/main.tsx",
                "polyfills": "apps/admin/src/polyfills.tsx",
                "buildLibsFromSource": true,
                "tsConfig": "apps/admin/tsconfig.app.json",
                "assets": [
                  {
                    "input": "libs/common/src/assets",
                    "glob": "**/*",
                    "output": "/assets"
                  }
                ],
                "styles": [],
                "scripts": []
              },
              "configurations": {
                "production": {
                  "fileReplacements": [
                    {
                      "replace": "apps/admin/src/environments/environment.js",
                      "with": "apps/admin/src/environments/environment.prod.js"
                    }
                  ],
                  "optimization": true,
                  "outputHashing": "all",
                  "sourceMap": false,
                  "namedChunks": false,
                  "extractLicenses": true,
                  "vendorChunk": false
                }
              }
            },
            "serve": {
              "executor": "@nx/vite:dev-server",
              "defaultConfiguration": "development",
              "options": {
                "buildTarget": "admin:build",
                "hmr": true
              },
              "configurations": {
                "development": {
                  "buildTarget": "admin:build:development",
                  "hmr": true
                },
                "production": {
                  "buildTarget": "admin:build:production",
                  "hmr": false
                }
              }
            },
            "preview": {
              "executor": "@nx/vite:preview-server",
              "defaultConfiguration": "development",
              "options": {
                "buildTarget": "admin:build"
              },
              "configurations": {
                "development": {
                  "buildTarget": "admin:build:development"
                },
                "production": {
                  "buildTarget": "admin:build:production"
                }
              }
            },
            "test": {
              "cache": true,
              "inputs": [
                "default",
                "^production"
              ],
              "executor": "@nx/vite:test",
              "outputs": [
                "{options.reportsDirectory}"
              ],
              "options": {
                "passWithNoTests": true,
                "reportsDirectory": "../../coverage/apps/admin"
              },
              "configurations": {}
            },
            "lint": {
              "cache": true,
              "inputs": [
                "default",
                "{workspaceRoot}/.eslintrc.json",
                "{workspaceRoot}/.eslintignore",
                "{workspaceRoot}/eslint.config.js"
              ],
              "executor": "@nx/eslint:lint",
              "outputs": [
                "{options.outputFile}"
              ],
              "options": {
                "lintFilePatterns": [
                  "apps/admin/**/*.{ts,tsx,js,jsx}"
                ]
              },
              "configurations": {}
            }
          },
          "tags": [
            "scope:app"
          ],
          "implicitDependencies": []
        }
      },
      "hooks": {
        "name": "hooks",
        "type": "lib",
        "data": {
          "root": "libs/hooks",
          "name": "hooks",
          "sourceRoot": "libs/hooks/src",
          "projectType": "library",
          "tags": [
            "scope:hooks"
          ],
          "targets": {
            "lint": {
              "cache": true,
              "inputs": [
                "default",
                "{workspaceRoot}/.eslintrc.json",
                "{workspaceRoot}/.eslintignore",
                "{workspaceRoot}/eslint.config.js"
              ],
              "executor": "@nx/eslint:lint",
              "outputs": [
                "{options.outputFile}"
              ],
              "options": {
                "lintFilePatterns": [
                  "libs/hooks/**/*.{ts,tsx,js,jsx}"
                ]
              },
              "configurations": {}
            }
          },
          "implicitDependencies": []
        }
      },
      "store": {
        "name": "store",
        "type": "lib",
        "data": {
          "root": "libs/store",
          "name": "store",
          "sourceRoot": "libs/store/src",
          "projectType": "library",
          "tags": [
            "scope:store"
          ],
          "targets": {
            "lint": {
              "cache": true,
              "inputs": [
                "default",
                "{workspaceRoot}/.eslintrc.json",
                "{workspaceRoot}/.eslintignore",
                "{workspaceRoot}/eslint.config.js"
              ],
              "executor": "@nx/eslint:lint",
              "outputs": [
                "{options.outputFile}"
              ],
              "options": {
                "lintFilePatterns": [
                  "libs/store/**/*.{ts,tsx,js,jsx}"
                ]
              },
              "configurations": {}
            }
          },
          "implicitDependencies": []
        }
      },
      "theme": {
        "name": "theme",
        "type": "lib",
        "data": {
          "root": "libs/theme",
          "name": "theme",
          "sourceRoot": "libs/theme/src",
          "projectType": "library",
          "tags": [
            "scope:theme"
          ],
          "targets": {
            "lint": {
              "cache": true,
              "inputs": [
                "default",
                "{workspaceRoot}/.eslintrc.json",
                "{workspaceRoot}/.eslintignore",
                "{workspaceRoot}/eslint.config.js"
              ],
              "executor": "@nx/eslint:lint",
              "outputs": [
                "{options.outputFile}"
              ],
              "options": {
                "lintFilePatterns": [
                  "libs/theme/**/*.{ts,tsx,js,jsx}"
                ]
              },
              "configurations": {}
            }
          },
          "implicitDependencies": []
        }
      },
      "alim": {
        "name": "alim",
        "type": "app",
        "data": {
          "root": "apps/alim",
          "name": "alim",
          "sourceRoot": "apps/alim/src",
          "projectType": "application",
          "targets": {
            "build": {
              "cache": true,
              "dependsOn": [
                "^build"
              ],
              "inputs": [
                "production",
                "^production"
              ],
              "executor": "@nx/vite:build",
              "outputs": [
                "{options.outputPath}"
              ],
              "defaultConfiguration": "production",
              "options": {
                "outputPath": "dist/apps/alim",
                "index": "apps/alim/src/public/index.html",
                "baseHref": "/",
                "main": "apps/alim/src/main.tsx",
                "polyfills": "apps/alim/src/polyfills.tsx",
                "buildLibsFromSource": true,
                "tsConfig": "apps/alim/tsconfig.app.json",
                "assets": [
                  {
                    "input": "libs/common/src/assets",
                    "glob": "**/*",
                    "output": "/assets"
                  }
                ],
                "styles": [],
                "scripts": []
              },
              "configurations": {
                "production": {
                  "fileReplacements": [
                    {
                      "replace": "apps/alim/src/environments/environment.js",
                      "with": "apps/alim/src/environments/environment.prod.js"
                    }
                  ],
                  "optimization": true,
                  "outputHashing": "all",
                  "sourceMap": false,
                  "namedChunks": false,
                  "extractLicenses": true,
                  "vendorChunk": false
                }
              }
            },
            "serve": {
              "executor": "@nx/vite:dev-server",
              "defaultConfiguration": "development",
              "options": {
                "buildTarget": "alim:build",
                "hmr": true
              },
              "configurations": {
                "development": {
                  "buildTarget": "alim:build:development",
                  "hmr": true
                },
                "production": {
                  "buildTarget": "alim:build:production",
                  "hmr": false
                }
              }
            },
            "preview": {
              "executor": "@nx/vite:preview-server",
              "defaultConfiguration": "development",
              "options": {
                "buildTarget": "alim:build"
              },
              "configurations": {
                "development": {
                  "buildTarget": "alim:build:development"
                },
                "production": {
                  "buildTarget": "alim:build:production"
                }
              }
            },
            "test": {
              "cache": true,
              "inputs": [
                "default",
                "^production"
              ],
              "executor": "@nx/vite:test",
              "outputs": [
                "{options.reportsDirectory}"
              ],
              "options": {
                "passWithNoTests": true,
                "reportsDirectory": "../../coverage/apps/alim"
              },
              "configurations": {}
            },
            "lint": {
              "cache": true,
              "inputs": [
                "default",
                "{workspaceRoot}/.eslintrc.json",
                "{workspaceRoot}/.eslintignore",
                "{workspaceRoot}/eslint.config.js"
              ],
              "executor": "@nx/eslint:lint",
              "outputs": [
                "{options.outputFile}"
              ],
              "options": {
                "lintFilePatterns": [
                  "apps/alim/**/*.{ts,tsx,js,jsx}"
                ]
              },
              "configurations": {}
            }
          },
          "tags": [
            "scope:app"
          ],
          "implicitDependencies": []
        }
      },
      "user": {
        "name": "user",
        "type": "app",
        "data": {
          "root": "apps/user",
          "name": "user",
          "sourceRoot": "apps/user/src",
          "projectType": "application",
          "targets": {
            "build": {
              "cache": true,
              "dependsOn": [
                "^build"
              ],
              "inputs": [
                "production",
                "^production"
              ],
              "executor": "@nx/vite:build",
              "outputs": [
                "{options.outputPath}"
              ],
              "defaultConfiguration": "production",
              "options": {
                "outputPath": "dist/apps/user",
                "index": "apps/user/src/public/index.html",
                "baseHref": "/",
                "main": "apps/user/src/main.tsx",
                "polyfills": "apps/user/src/polyfills.tsx",
                "buildLibsFromSource": true,
                "tsConfig": "apps/user/tsconfig.app.json",
                "assets": [
                  {
                    "input": "libs/common/src/assets",
                    "glob": "**/*",
                    "output": "/assets"
                  }
                ],
                "styles": [],
                "scripts": []
              },
              "configurations": {
                "production": {
                  "fileReplacements": [
                    {
                      "replace": "apps/user/src/environments/environment.js",
                      "with": "apps/user/src/environments/environment.prod.js"
                    }
                  ],
                  "optimization": true,
                  "outputHashing": "all",
                  "sourceMap": false,
                  "namedChunks": false,
                  "extractLicenses": true,
                  "vendorChunk": false
                }
              }
            },
            "serve": {
              "executor": "@nx/vite:dev-server",
              "defaultConfiguration": "development",
              "options": {
                "buildTarget": "user:build",
                "hmr": true
              },
              "configurations": {
                "development": {
                  "buildTarget": "user:build:development",
                  "hmr": true
                },
                "production": {
                  "buildTarget": "user:build:production",
                  "hmr": false
                }
              }
            },
            "preview": {
              "executor": "@nx/vite:preview-server",
              "defaultConfiguration": "development",
              "options": {
                "buildTarget": "user:build"
              },
              "configurations": {
                "development": {
                  "buildTarget": "user:build:development"
                },
                "production": {
                  "buildTarget": "user:build:production"
                }
              }
            },
            "test": {
              "cache": true,
              "inputs": [
                "default",
                "^production"
              ],
              "executor": "@nx/vite:test",
              "outputs": [
                "{options.reportsDirectory}"
              ],
              "options": {
                "passWithNoTests": true,
                "reportsDirectory": "../../coverage/apps/user"
              },
              "configurations": {}
            },
            "lint": {
              "cache": true,
              "inputs": [
                "default",
                "{workspaceRoot}/.eslintrc.json",
                "{workspaceRoot}/.eslintignore",
                "{workspaceRoot}/eslint.config.js"
              ],
              "executor": "@nx/eslint:lint",
              "outputs": [
                "{options.outputFile}"
              ],
              "options": {
                "lintFilePatterns": [
                  "apps/user/**/*.{ts,tsx,js,jsx}"
                ]
              },
              "configurations": {}
            }
          },
          "tags": [
            "scope:app"
          ],
          "implicitDependencies": []
        }
      },
      "ui": {
        "name": "ui",
        "type": "lib",
        "data": {
          "root": "libs/ui",
          "name": "ui",
          "sourceRoot": "libs/ui/src",
          "projectType": "library",
          "tags": [
            "scope:ui"
          ],
          "targets": {
            "lint": {
              "cache": true,
              "inputs": [
                "default",
                "{workspaceRoot}/.eslintrc.json",
                "{workspaceRoot}/.eslintignore",
                "{workspaceRoot}/eslint.config.js"
              ],
              "executor": "@nx/eslint:lint",
              "outputs": [
                "{options.outputFile}"
              ],
              "options": {
                "lintFilePatterns": [
                  "libs/ui/**/*.{ts,tsx,js,jsx}"
                ]
              },
              "configurations": {}
            }
          },
          "implicitDependencies": []
        }
      }
    },
    "dependencies": {
      "service": [],
      "common": [],
      "admin": [
        {
          "source": "admin",
          "target": "ui",
          "type": "static"
        },
        {
          "source": "admin",
          "target": "ui",
          "type": "dynamic"
        },
        {
          "source": "admin",
          "target": "store",
          "type": "static"
        },
        {
          "source": "admin",
          "target": "hooks",
          "type": "static"
        },
        {
          "source": "admin",
          "target": "common",
          "type": "static"
        },
        {
          "source": "admin",
          "target": "service",
          "type": "static"
        }
      ],
      "hooks": [
        {
          "source": "hooks",
          "target": "store",
          "type": "static"
        }
      ],
      "store": [
        {
          "source": "store",
          "target": "common",
          "type": "static"
        },
        {
          "source": "store",
          "target": "service",
          "type": "static"
        }
      ],
      "theme": [],
      "alim": [
        {
          "source": "alim",
          "target": "ui",
          "type": "static"
        },
        {
          "source": "alim",
          "target": "ui",
          "type": "dynamic"
        },
        {
          "source": "alim",
          "target": "store",
          "type": "static"
        },
        {
          "source": "alim",
          "target": "hooks",
          "type": "static"
        },
        {
          "source": "alim",
          "target": "common",
          "type": "static"
        },
        {
          "source": "alim",
          "target": "service",
          "type": "static"
        }
      ],
      "user": [
        {
          "source": "user",
          "target": "store",
          "type": "static"
        },
        {
          "source": "user",
          "target": "ui",
          "type": "static"
        },
        {
          "source": "user",
          "target": "ui",
          "type": "dynamic"
        },
        {
          "source": "user",
          "target": "hooks",
          "type": "static"
        },
        {
          "source": "user",
          "target": "common",
          "type": "static"
        },
        {
          "source": "user",
          "target": "service",
          "type": "static"
        }
      ],
      "ui": [
        {
          "source": "ui",
          "target": "common",
          "type": "static"
        },
        {
          "source": "ui",
          "target": "store",
          "type": "static"
        },
        {
          "source": "ui",
          "target": "service",
          "type": "static"
        },
        {
          "source": "ui",
          "target": "hooks",
          "type": "static"
        },
        {
          "source": "ui",
          "target": "theme",
          "type": "static"
        }
      ]
    }
  },
  "affectedProjects": [],
  "criticalPath": []
}
``` 

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : linux-x64
   npm    : 10.2.3
   
   nx (global)        : 17.1.2
   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nx/react          : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/vite           : 17.1.2
   @nx/web            : 17.1.2
   typescript         : 5.2.2
```

### Failure Logs

```shell
npx nx serve admin                                                                                                         ✔ 

> nx run admin:serve:development

  ➜  Local:   http://localhost:4200/
Error: The following dependencies are imported but could not be resolved:

  @istekhara/ui/layout (imported by /home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/apps/admin/src/helper/layout/index.tsx)
  @istekhara/ui/components (imported by /home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/apps/admin/src/helper/router/index.tsx)
  @admin/components/AdminMobileNavigation (imported by /home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/apps/admin/src/helper/layout/index.tsx)
  @admin/components/Header (imported by /home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/apps/admin/src/helper/layout/index.tsx)
  @admin/screens/login (imported by /home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/apps/admin/src/helper/router/index.tsx)
  @istekhara/ui/forgot-password-page (imported by /home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/apps/admin/src/helper/router/index.tsx)
  @istekhara/ui/reset-password-page (imported by /home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/apps/admin/src/helper/router/index.tsx)
  @admin/screens/dashboard (imported by /home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/apps/admin/src/helper/router/index.tsx)
  @istekhara/ui/not-found-page (imported by /home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/apps/admin/src/helper/router/index.tsx)

Are they installed?
    at file:///home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:44188:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/abbasmashaddy72/Documents/Sites/Frontend/istekhara/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43597:38
```

### Package Manager Version

10.2.3

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Could you please provide a repo to make reproducing the issue easier for us?
