### ISSUE TITLE
Upgrade 15 --> 16, ESlint error on the `enforce-module-boundaries` rule

### ISSUE THREAD

**Issue by basvandorst** [nrwl/nx#20368]
### Current Behavior

After an upgrade from 15 to 16 the ESlint rule for `enforce-module-boundaries` doesn't work as expected. 

```
> nx run core-interfaces:lint


Linting "core-interfaces"...
warning No cached ProjectGraph is available. The rule will be skipped.
  If you encounter this error as part of running standard `nx` commands then please open an issue on https://github.com/nrwl/nx
@nx/enforce-module-boundaries
warning No cached ProjectGraph is available. The rule will be skipped.
  If you encounter this error as part of running standard `nx` commands then please open an issue on https://github.com/nrwl/nx
@nx/enforce-module-boundaries

>  NX   Cannot read properties of undefined (reading 'findProjectWithImport')

Occurred while linting /project/x/libs/core/interfaces/src/lib/auth.ts:1
Rule: "@nx/enforce-module-boundaries"

TypeError: Cannot read properties of undefined (reading 'findProjectWithImport')
Occurred while linting //project/x/libs/core/interfaces/src/lib/auth.ts:1
Rule: "@nx/enforce-module-boundaries"
at findProjectUsingImport (/project/x/@nx/eslint-plugin/src/utils/runtime-lint-utils.js:112:41)
at run (/project/x/@nx/eslint-plugin/src/rules/enforce-module-boundaries.js:172:69)
at ImportDeclaration (/project/x/@nx/eslint-plugin/src/rules/enforce-module-boundaries.js:423:17)
at ruleErrorHandler (/project/x/eslint/lib/linter/linter.js:1091:28)
at /project/x/eslint/lib/linter/safe-emitter.js:45:58
at Array.forEach (<anonymous>)
at Object.emit (/project/x/eslint/lib/linter/safe-emitter.js:45:38)
at NodeEventGenerator.applySelector (/project/x/eslint/lib/linter/node-event-generator.js:297:26)
at NodeEventGenerator.applySelectors (/project/x/eslint/lib/linter/node-event-generator.js:326:22)
at NodeEventGenerator.enterNode (/project/x/eslint/lib/linter/node-event-generator.js:340:14)


>  NX   Running target lint for project core-interfaces failed

Failed tasks:

  - core-interfaces:lint
```

ESlint config:
```
"rules": {
  "indent": "off",
    "no-unused-vars": "off",
    "functional/no-loop-statements": "warn",
    "@typescript-eslint/indent": "warn",
    "@typescript-eslint/member-ordering": "warn",
    "@typescript-eslint/no-explicit-any": "warn",
    "@typescript-eslint/no-unused-vars": "off",
    "@typescript-eslint/func-call-spacing": "warn",
    "@nx/enforce-module-boundaries": [
    "error",
    {
      "enforceBuildableLibDependency": true,
      "depConstraints": [
        {
          "sourceTag": "*",
          "onlyDependOnLibsWithTags": ["*"]
        }
      ]
    }
  ]
}
```

Also tried to run ESlint without the additional parameters, same result.
```
  "@nx/enforce-module-boundaries":  "error",
```

1st line contains imports like:
- `import { Injectable } from '@angular/core';`
- `import { ExpressContext } from 'apollo-server-express';`
- `import { LogLevel } from '@company/enums';`

### Steps to Reproduce
- Upgrade 15 --> 16

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : darwin-x64
   npm    : 10.2.0

   nx (global)        : 17.1.2
   nx                 : 17.1.2
   @nx/js             : 16.7.0
   @nx/jest           : 16.7.0
   @nx/linter         : 16.7.0
   @nx/workspace      : 16.7.0
   @nx/angular        : 16.7.0
   @nx/cypress        : 16.7.0
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 16.7.0
   @nx/node           : 16.7.0
   @nrwl/tao          : 17.1.2
   @nx/webpack        : 16.7.0
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

similar result in the pipeline (nix machine)

**Comment by basvandorst** [comment]
Fixed by updating `eslint-plugin`:

```
"@nx/eslint-plugin": "16.7.0"
to
"@nx/eslint-plugin": "16.10.0"
```
