### ISSUE TITLE
Not sure why this build is being reported as a success?

### ISSUE THREAD

**Issue by brandoncollins7** [nrwl/nx#20392]
### Current Behavior

Build is showing as successful

### Expected Behavior

should have failed the build

### Steps to Reproduce

I am not sure...
![image](https://github.com/nrwl/nx/assets/36413482/478dbb93-f2b4-48df-89bd-6667d2713ab1)

### Nx Report

```shell
Node   : 18.15.0
   OS     : win32-x64
   pnpm   : 8.6.12
   
   nx (global)        : 17.0.1
   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/cypress        : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/esbuild        : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nx/nest           : 17.1.2
   @nx/next           : 17.1.2
   @nx/node           : 17.1.2
   @nx/react          : 17.1.2
   @nx/storybook      : 17.1.2
   @nrwl/tao          : 17.0.1
   @nx/vite           : 17.1.2
   @nx/web            : 17.1.2
   @nx/webpack        : 17.1.2
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.0.2
   @nx-tools/nx-prisma    : 5.0.2
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/tao@17.0.1

   To fix this, run `nx migrate nx@17.1.2`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by andersonba** [comment]
Same here, but using another executor (next:build), so, should I have create another issue?

<img width="1197" alt="image" src="https://github.com/nrwl/nx/assets/1501013/942888df-ada9-4498-8128-53fd2c99ee11">

**Comment by dalton-mcphaden** [comment]
Having a similar issue where builds are failing but Nx considers the task a success
![image](https://github.com/nrwl/nx/assets/122817079/75e4e14a-3ece-4ef3-9381-95acd4d11e02)

**Comment by rarmatei** [comment]
can you send an email to cloud-support@nrwl.io with the links to your runs please, so we can confirm a few things on our side?

**Comment by barbados-clemens** [comment]
Hi @brandoncollins7 In Cypress Cloud does that Test Replay show that run as failed or successful?

**Comment by brandoncollins7** [comment]
@barbados-clemens The nx command actually ran two tests. In cypress cloud one is a failure and one is a pass. The particular failure in my screenshot is recorded as a failure in cypress cloud.

I just noticed a bit more interesting errors in the logs, dunno if that helps:

```
It looks like this is your first time using Cypress: 13.0.0

[STARTED] Task without title.
[SUCCESS] Task without title.

Opening Cypress...

DevTools listening on ws://127.0.0.1:39717/devtools/browser/1ccd50cd-5f00-4c7c-87ef-784bfc9f0ee9
[2672:1121/212539.864750:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

====================================================================================================

  (Run Starting)

tput: No value for $TERM and no -T specified
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.0.0                                                                         │
  │ Browser:        Chrome 119 (headless)                                                          │
  │ Node Version:   v18.18.2 (/opt/hostedtoolcache/node/18.18.2/x64/bin/node)                      │
  │ Specs:          8 found (account_client_traders.cy.ts, app_config.cy.ts, auth.cy.ts, memo_entr │
  │                 y.cy.ts, organizations.cy.ts, pnl_report.cy.ts, reporting_config.cy.ts, users. │
  │                 cy.ts)                                                                         │
  │ Searched:       src/**/*.cy.{js,jsx,ts,tsx}                                                    │
  │ Params:         Tag: false, Group: false, Parallel: false                                      │
  │ Run URL:        https://cloud.cypress.io/projects/6sy9nz/runs/81                               │
  │ Experiments:    experimentalStudio=true                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  account_client_traders.cy.ts                                                    (1 of 8)
Still waiting to connect to Chrome, retrying in 1 second (attempt 18/62)
Still waiting to connect to Chrome, retrying in 1 second (attempt 19/62)
Still waiting to connect to Chrome, retrying in 1 second (attempt 20/62)


  frnt-back-ui
    1) "before each" hook for "should be able to list/update account client traders"


  0 passing (16s)
  1 failing

  1) frnt-back-ui
       "before each" hook for "should be able to list/update account client traders":
     CypressError: `cy.type()` can only accept a string or number. You passed in: `undefined`

https://on.cypress.io/type

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `frnt-back-ui`
      at Context.type (https://back.staging.frnt.io/__cypress/runner/cypress_runner.js:114321:68)
      at wrapped (https://back.staging.frnt.io/__cypress/runner/cypress_runner.js:138451:19)
  From Your Spec Code:
      at Context.eval (webpack:///../../support/commands.ts:16:0)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      1                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     15 seconds                                                                       │
  │ Spec Ran:     account_client_traders.cy.ts                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /home/runner/work/atlantic-dawn-monorepo/atlantic-dawn-monorepo/dist/cypress/cyp     (1280x599)
     ress/tests/frnt-back-ui/screenshots/account_client_traders.cy.ts/frnt-back-ui --               
      should be able to listupdate account client traders -- before each hook (failed               
     ).png                                                                                          


  (Uploading Cloud Artifacts)

  - Video - Nothing to upload 
  - Screenshot - 137 kB /home/runner/work/atlantic-dawn-monorepo/atlantic-dawn-monorepo/dist/cypress/cypress/tests/frnt-back-ui/screenshots/account_client_traders.cy.ts/frnt-back-ui -- should be able to listupdate account client traders -- before each hook (failed).png
  - Test Replay - 7.89 MB

  (Uploaded Cloud Artifacts)

  - Screenshot - Done Uploading 137 kB 1/2 /home/runner/work/atlantic-dawn-monorepo/atlantic-dawn-monorepo/dist/cypress/cypress/tests/frnt-back-ui/screenshots/account_client_traders.cy.ts/frnt-back-ui -- should be able to listupdate account client traders -- before each hook (failed).png
  - Test Replay - Done Uploading 7.89 MB 2/2

────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  app_config.cy.ts                                                                (2 of 8)


  app_config
[2672:1121/212626.195177:ERROR:connection.cc(46)] X connection error received.
```
