### ISSUE TITLE
Build failing because it's not finding ng-packagr-lite executor

### ISSUE THREAD

**Issue by GabrielAPineiro** [nrwl/nx#20411]
### Current Behavior

When I try to build, run storybook, it's throwing an error complaing about not finding the executor
This is an example of my build configuration
![image](https://github.com/nrwl/nx/assets/104081429/25497aaf-a9d8-49be-b83c-bacc4ec17f6f)

### Expected Behavior

to build and run storybook succesfully

### Steps to Reproduce

1. run yarn nx run :storybook or :build

### Nx Report

```shell
Node   : 18.16.1
   OS     : win32-x64
   yarn   : 1.22.19

   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/angular        : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nrwl/devkit       : 15.8.5
   @nx/eslint-plugin  : 17.0.3
   @nx/plugin         : 17.0.3
   @nx/storybook      : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/web            : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx-dotnet/core              : 1.23.0
   @storybook/angular           : 7.5.3
   @trumbitta/nx-plugin-openapi : 1.12.1
   ng-mocks                     : 14.12.1
   ---------------------------------------
   Local workspace plugins:
         @exclaimer/workspace-plugin
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/devkit@15.8.5

   To fix this, run `nx migrate nx@17.0.3`
```

### Failure Logs

```shell
>  NX   Cannot find builder 'ng-packagr-lite' in node_modules\@nx\angular\executors.json.


Error: Cannot find builder 'ng-packagr-lite' in node_modules\@nx\angular\executors.json.
    at WrappedWorkspaceNodeModulesArchitectHost.readExecutorsJson (node_modules\nx\src\adapter\ngcli-adapter.js:757:23)
    at WrappedWorkspaceNodeModulesArchitectHost.resolveBuilder (node_modules\nx\src\adapter\ngcli-adapter.js:736:64)
    at name (C:\packages\angular_devkit\architect\src\architect.ts:333:38)
    at Observable._subscribe (C:\packages\angular_devkit\architect\src\jobs\create-job-handler.ts:162:20)
    at Observable._trySubscribe (node_modules\rxjs\src\internal\Observable.ts:244:19)
    at node_modules\rxjs\src\internal\Observable.ts:234:18
    at Object.errorContext (node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
    at Observable.subscribe (node_modules\rxjs\src\internal\Observable.ts:220:5)
    at node_modules\rxjs\src\internal\operators\switchMap.ts:109:49
    at OperatorSubscriber._this._next (node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:70:13)
```

### Operating System

- [ ] macOS
- [x] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
This was fixed by https://github.com/nrwl/nx/pull/20307 and released in Nx 17.2.0. Please migrate to the latest version to get the fix.

**Comment by GabrielAPineiro** [comment]
I migrated but now I have another error
![image](https://github.com/nrwl/nx/assets/104081429/940d5995-49da-40c6-bb7d-f05e679f9961)

**Comment by leosvelperez** [comment]
Did you run the migrations? There's a migration in 17.2.0 that renames `@nx/angular:webpack-dev-server` to `@nx/angular:dev-server`. You may not have run it.

**Comment by GabrielAPineiro** [comment]
I tried, but my migration command is not working. I'm waiting to see if anyone else is experiencing it so I can create an issue
![image](https://github.com/nrwl/nx/assets/104081429/d4d3a5b7-1bc0-4b45-8088-8a63e26d1b33)

**Comment by leosvelperez** [comment]
That seems an `npm` issue. I wonder if it has to do with some funky issue where 17.2.3 is tagged as the latest version, but it should be 17.2.4. Could you try running `nx migrate 17.2.4` instead?
