### ISSUE TITLE
no such file `.nx/cache/configuration-source-maps.json`

### ISSUE THREAD

**Issue by batazor** [nrwl/nx#20559]
### Current Behavior

> NX_BATCH_MODE=true npx nx run-many -t build --all --parallel

 >  NX   ENOENT: no such file or directory, open '$USER/shortlink/ui/nx-monorepo/.nx/cache/configuration-source-maps.json'

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

### Expected Behavior

correct build

### GitHub Repo

https://github.com/shortlink-org/shortlink/tree/main/ui/nx-monorepo

### Steps to Reproduce

1. npm i
2. npm run build

### Nx Report

```shell
>  NX   ENOENT: no such file or directory, open '$USER/shortlink/ui/nx-monorepo/.nx/cache/configuration-source-maps.json'

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

### Failure Logs

```shell
[NX Daemon Server] - 2023-12-04T13:41:51.360Z - Started listening on: /var/folders/bk/s4lzyj4d0hl_q7fdr1qw0b4w0000gn/T/547d87a9dbcf9eb14a73/d.sock
[NX Daemon Server] - 2023-12-04T13:41:51.366Z - [WATCHER]: Subscribed to changes within: $USER/shortlink/ui/nx-monorepo (native)
[NX Daemon Server] - 2023-12-04T13:41:51.368Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-12-04T13:41:51.369Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-12-04T13:41:51.372Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-12-04T13:41:51.373Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-12-04T13:41:51.375Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-12-04T13:41:51.375Z - [REQUEST]: 
[NX Daemon Server] - 2023-12-04T13:41:51.376Z - [REQUEST]: 
[NX Daemon Server] - 2023-12-04T13:41:51.515Z - [REQUEST]: Responding to the client with an error. Error when preparing serialized project graph. ENOENT: no such file or directory, open '$USER/shortlink/ui/nx-monorepo/.nx/cache/configuration-source-maps.json'
Error: ENOENT: no such file or directory, open '$USER/shortlink/ui/nx-monorepo/.nx/cache/configuration-source-maps.json'
    at writeFileSync (node:fs:2352:20)
    at writeJsonFile ($USER/shortlink/ui/nx-monorepo/node_modules/nx/src/utils/fileutils.js:55:28)
    at writeSourceMaps ($USER/shortlink/ui/nx-monorepo/node_modules/nx/src/utils/source-maps.js:8:35)
    at processFilesAndCreateAndSerializeProjectGraph ($USER/shortlink/ui/nx-monorepo/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:142:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getCachedSerializedProjectGraphPromise ($USER/shortlink/ui/nx-monorepo/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:44:16)
    at async handleRequestProjectGraph ($USER/shortlink/ui/nx-monorepo/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
    at async handleResult ($USER/shortlink/ui/nx-monorepo/node_modules/nx/src/daemon/server/server.js:110:16)
    at async handleMessage ($USER/shortlink/ui/nx-monorepo/node_modules/nx/src/daemon/server/server.js:81:9)
    at async $USER/shortlink/ui/nx-monorepo/node_modules/nx/src/daemon/server/server.js:45:9 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '$USER/shortlink/ui/nx-monorepo/.nx/cache/configuration-source-maps.json'
}
[NX Daemon Server] - 2023-12-04T13:41:51.520Z - Done responding to the client null
```

### Package Manager Version

npm 10.2.4, node v21.3.0

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I tried to use nx last and next version, I tried dropping cache/node_modules/reinstalling nodejs
`npx nx reset` doesn't work

**Comment by AgentEnder** [comment]
I'm going to go ahead and close this out as it seems to be resolved in nodejs 21.4 and covered by 20551
