### ISSUE TITLE
Extension Tailwind CSS IntelliSense in VS Code is not working 

### ISSUE THREAD

**Issue by fitimsijarinaa** [nrwl/nx#20600]
### Current Behavior

In an NX project with Angular Tailwind CSS IntelliSense is not working. I see the following output in vs code:

```
[apps/admin/tailwind.config.js] Initializing...
[apps/admin/tailwind.config.js] Loaded Tailwind CSS config file: /Users/PROJECt/apps/admin/tailwind.config.js
[apps/admin/tailwind.config.js] Loaded postcss v8.4.31: /Users/PROJECt/node_modules/postcss
[apps/admin/tailwind.config.js] Loaded tailwindcss v3.3.5: /Users/PROJECt/node_modules/tailwindcss
[apps/admin/tailwind.config.js] Building...
[Error - 07:53:29] Tailwind CSS: Can't resolve '@nx/nx-darwin-arm64' in '/Users/PROJECt/node_modules/nx/src/native'
Error: Can't resolve '@nx/nx-darwin-arm64' in '/Users/PROJECt/node_modules/nx/src/native'
    at f (/Users/USER/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.3/dist/tailwindServer.js:130:7132)
    at /Users/USER/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.3/dist/tailwindServer.js:131:713
    at /Users/USER/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.3/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/USER/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.3/dist/tailwindServer.js:5:78), <anonymous>:15:1)
    at /Users/USER/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.3/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/USER/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.3/dist/tailwindServer.js:5:78), <anonymous>:27:1)
    at /Users/USER/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.3/dist/tailwindServer.js:134:7639
    at /Users/USER/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.3/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/USER/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.3/dist/tailwindServer.js:5:78), <anonymous>:15:1)
    at /Users/USER/.vscode/extensions/bradlc.vscode-tailwindcss-0.10.3/dist/tailwindServer.js:134:401
```

### Expected Behavior

Tailwind CSS Intellisense should work properly.

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 20.10.0
   OS     : darwin-x64
   npm    : 10.2.3
   
   nx (global)        : 17.1.3
   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/angular        : 17.1.2
   @nx/cypress        : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/esbuild        : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nx/nest           : 17.1.2
   @nx/node           : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/web            : 17.1.2
   @nx/webpack        : 17.0.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngneat/hot-toast    : 6.0.1
   @ngneat/transloco    : 6.0.0
   @ngrx/operators      : 17.0.1
   @ngrx/signals        : 17.0.1
   @rx-angular/template : 16.1.1
   ng2-charts           : 5.0.3
   ---------------------------------------
```

### Package Manager Version

10.2.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by yartasdev** [comment]
this problem is looks providing from Apple Silicon but NX team should fix that i think but for a while you can update your tailwind.config.ts files for TailwindCSS IntelliSense plugin. 

My tailwind config files looks like;

```js
import { join } from 'path';
import { Config } from 'tailwindcss';

export default {
   darkMode: 'class',
   content: [join(__dirname, '../**/src/**/!(*.stories|*.spec).{ts,html}'), join(__dirname, '../../libs/**/src/**/!(*.stories|*.spec).{ts,html}')],
   theme: {
      extend: {},
   },
   plugins: [require('@tailwindcss/forms'), require('@yartasdev/tailwind-color-palette')],
} as Config;

```

**Comment by Cammisuli** [comment]
@fitimsijarinaa what kind of computer do you have? Intel or Arm (M1+)?

If its arm, can you double check to see if all your applications are running in arm mode, and not through rosetta? It looks like your main node instance where you’re running `nx report` spit out `darwin-x64`, but other places are looking for arm. 

You can see which apps are running in which mode, by looking at the activity app or following this guide:
https://www.macrumors.com/how-to/tell-apps-optimized-for-m1-apple-silicon-macs/

**Comment by batamire** [comment]
i have the same issue, my `nx report` output:

```
Node   : 20.12.0
OS     : darwin-x64
yarn   : 1.22.21

nx (global)        : 18.1.3
nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/cypress        : 18.2.1
@nx/devkit         : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/next           : 18.2.1
@nx/react          : 18.2.1
@nrwl/tao          : 18.2.1
@nx/vite           : 18.2.1
@nx/web            : 18.2.1
@nx/webpack        : 18.2.1
typescript         : 5.4.3
```

@Cammisuli i have M1, i don't get what other places/apps should i check?
