### ISSUE TITLE
Build command on Azure classic deployment pipeline runs into error when apply caching with Cache@2

### ISSUE THREAD

**Issue by AnnoDomine** [nrwl/nx#20625]
### Current Behavior

While we are currently in the process of migrating our old repository structure to a monorepo format using Nx, we are taking a step-by-step approach due to our enterprise applications. Our migration initiative began with one of our smallest apps.

We have established a deployment pipeline within Azure using a classic pipeline.

The structure of the pipeline is illustrated below:
![image](https://github.com/nrwl/nx/assets/6992858/1a768569-7752-46c2-986b-3368fa07f499)
Please note that caching in the image is currently disabled due to an existing problem.

Problem:
During the pipeline execution, specifically during the "Build" phase, I encounter an error:

```bash
 >  NX   Invalid regular expression: XXXXXXXXXXXXXXXXXXXX Invalid escape


SyntaxError: Invalid regular expression: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Invalid escape
    at new RegExp (<anonymous>)
    at generatePattern (XXX/node_modules/.pnpm/vite@4.3.9_@types+node@20.10.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:41604:15)
    at definePlugin (XXX/node_modules/.pnpm/vite@4.3.9_@types+node@20.10.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:41615:28)
    at resolvePlugins (XXX/node_modules/.pnpm/vite@4.3.9_@types+node@20.10.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42305:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfig (XXX/node_modules/.pnpm/vite@4.3.9_@types+node@20.10.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64242:24)
    at async build (XXX/node_modules/.pnpm/vite@4.3.9_@types+node@20.10.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46318:20)
    at async viteBuildExecutor (XXX\node_modules\.pnpm\@nx+vite@17.1.3_@swc-node+register@1.6.8_@swc+core@1.3.99_@types+node@20.10.1_nx@17.1.3_types_kunm5klzhaedr5t3dwbeestfc4\node_modules\@nx\vite\src\executors\build\build.impl.js:40:29)
    at async getLastValueFromAsyncIterableIterator (XXX\node_modules\.pnpm\nx@17.1.3_@swc-node+register@1.6.8_@swc+core@1.3.99\node_modules\nx\src\utils\async-iterator.js:13:19)
    at async iteratorToProcessStatusCode (XXX\node_modules\.pnpm\nx@17.1.3_@swc-node+register@1.6.8_@swc+core@1.3.99\node_modules\nx\src\command-line\run\run.js:41:29)
```

The censored parts in the error trace refer to tons of process.env.

This issue arises only when caching is enabled. Disabling caching allows the pipeline to run without any problems.

Caching settings are as follows:
![image](https://github.com/nrwl/nx/assets/6992858/2886850c-34b3-447a-bbcb-b662c4bd53bb)

The "Install pnpm" settings:
![image](https://github.com/nrwl/nx/assets/6992858/9727f247-5e90-4c32-9cee-1c87e4e92d4a)

The "Install dependencies" settings involve a simple "Command line" task with the command `pnpm install`.

The "Build" task:
![image](https://github.com/nrwl/nx/assets/6992858/17836c21-0c1b-4479-a07c-799fa7dfbfcb)

### Expected Behavior

No Error while build

### GitHub Repo

It is an Azure repo which is private

### Steps to Reproduce

1. Create a Nx workspace.
2. Setup a deployment pipeline in azure with cache@2
3. Run the pipeline.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 21.2.0
   OS     : XXXXXXXXXXXXXXXXXX
   pnpm   : 8.11.0
   
   nx (global)        : 17.1.3
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/cypress        : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/react          : 17.1.3
   @nrwl/tao          : 17.1.3
   @nx/vite           : 17.1.3
   typescript         : 5.2.2
```

### Failure Logs

See above

### Package Manager Version

pnpm 8.11.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Selected machine: windows 2022

As this is a business application, I must censor some parts and cannot provide in-depth details. If you need more information, I will try to respond with it.

**Comment by MaxKless** [comment]
Hi! This is such an obscure error with many moving parts, it's impossible for me to reproduce this or see what's going on at first glance, sorry. Can you please retry this on the latest nx and see if it's still happening?
