### ISSUE TITLE
17.2.0-rc.0 broken on windows

### ISSUE THREAD

**Issue by atsjo** [nrwl/nx#20653]
### Current Behavior

nx build or report fails with
>  NX   Given napi value is not an array

### Expected Behavior

Works as with beta 15

### Steps to Reproduce

1. upgrade to 17.2.0-rc.0 on windows
2. run nx report or build

### Nx Report

```shell
fails
```

### Failure Logs

```shell
[Nxls] - 2023-12-08T01:07:53.439Z - Error: Given napi value is not an array
    at getNxWorkspaceFilesFromContext (D:\repos\teve-no\task4s\node_modules\.pnpm\nx@17.2.0-rc.0_@swc-node+register@1.6.8_@swc+core@1.3.100\node_modules\nx\src\utils\workspace-context.js:17:29)
    at retrieveWorkspaceFiles (D:\repos\teve-no\task4s\node_modules\.pnpm\nx@17.2.0-rc.0_@swc-node+register@1.6.8_@swc+core@1.3.100\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js:25:120)
    at processCollectedUpdatedAndDeletedFiles (D:\repos\teve-no\task4s\node_modules\.pnpm\nx@17.2.0-rc.0_@swc-node+register@1.6.8_@swc+core@1.3.100\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:101:108)
    at processFilesAndCreateAndSerializeProjectGraph (D:\repos\teve-no\task4s\node_modules\.pnpm\nx@17.2.0-rc.0_@swc-node+register@1.6.8_@swc+core@1.3.100\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:141:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getCachedSerializedProjectGraphPromise (D:\repos\teve-no\task4s\node_modules\.pnpm\nx@17.2.0-rc.0_@swc-node+register@1.6.8_@swc+core@1.3.100\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:43:16)
    at async handleRequestProjectGraph (D:\repos\teve-no\task4s\node_modules\.pnpm\nx@17.2.0-rc.0_@swc-node+register@1.6.8_@swc+core@1.3.100\node_modules\nx\src\daemon\server\handle-request-project-graph.js:12:24)
    at async handleResult (D:\repos\teve-no\task4s\node_modules\.pnpm\nx@17.2.0-rc.0_@swc-node+register@1.6.8_@swc+core@1.3.100\node_modules\nx\src\daemon\server\server.js:110:16)
    at async handleMessage (D:\repos\teve-no\task4s\node_modules\.pnpm\nx@17.2.0-rc.0_@swc-node+register@1.6.8_@swc+core@1.3.100\node_modules\nx\src\daemon\server\server.js:81:9)
    at async D:\repos\teve-no\task4s\node_modules\.pnpm\nx@17.2.0-rc.0_@swc-node+register@1.6.8_@swc+core@1.3.100\node_modules\nx\src\daemon\server\server.js:45:9
```

### Package Manager Version

pnpm 8.11.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by khalilou88** [comment]
Not just windows, same error on linux :

https://github.com/khalilou88/jnxplus/actions/runs/7136354109/job/19434670545
