### ISSUE TITLE
`nx run --graph` is not working

### ISSUE THREAD

**Issue by jluxenberg** [nrwl/nx#20673]
### Current Behavior

Running `nx run --graph <target>` results in an error:
```
TypeError: Cannot read properties of undefined (reading 'indexOf')
```

Full output:
```
nx-bug-01 % yarn nx run --graph nx-bug-01:build
nx run [project][:target][:configuration] [_..]

Run a target for a project
(e.g., nx run myapp:serve:production).

You can also use the infix notation to run a target:
(e.g., nx serve myapp --configuration=production)

You can skip the use of Nx cache by using the --skip-nx-cache option.

Options:
      --version         Show version number                                                                                                                               [boolean]
      --batch           Run task(s) in batches for executors which support batches                                                                       [boolean] [default: false]
  -c, --configuration   This is the configuration to use when performing tasks on projects                                                                                 [string]
      --output-style    Defines how Nx emits outputs tasks logs                             [string] [choices: "dynamic", "static", "stream", "stream-without-prefixes", "compact"]
      --exclude         Exclude certain projects from being processed                                                                                                      [string]
      --parallel        Max number of parallel processes [default is 3]                                                                                                    [string]
      --runner          This is the name of the tasks runner configured in nx.json                                                                                         [string]
      --graph           Show the task graph of the command. Pass a file path to save the graph data instead of viewing it in the browser.                                  [string]
      --verbose         Prints additional information about the commands (e.g., stack traces)                                                                             [boolean]
      --nxBail          Stop command execution after the first failed task                                                                               [boolean] [default: false]
      --nxIgnoreCycles  Ignore cycles in the task graph                                                                                                  [boolean] [default: false]
      --skipNxCache     Rerun the tasks even when the results are available in the cache                                                                 [boolean] [default: false]
      --project         Target project                                                                                                                                     [string]

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at parseRunOneOptions (/Users/jared/workspace/spikes/nx-bug-01/node_modules/nx/src/command-line/run/run-one.js:83:52)
    at Object.runOne (/Users/jared/workspace/spikes/nx-bug-01/node_modules/nx/src/command-line/run/run-one.js:22:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Behavior

`--graph` should:
> Show the task graph of the command. Pass a file path to save the graph data instead of viewing it in the browser.

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. run `nx run --graph build` in https://github.com/nrwl/nx-examples

### Nx Report

```shell
yarn run v1.22.19
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : linux-x64
   yarn   : 1.22.19
   
   nx                 : 17.2.0-beta.15
   @nx/js             : 17.2.0-beta.15
   @nx/jest           : 17.2.0-beta.15
   @nx/linter         : 17.2.0-beta.15
   @nx/eslint         : 17.2.0-beta.15
   @nx/workspace      : 17.2.0-beta.15
   @nx/angular        : 17.2.0-beta.15
   @nx/cypress        : 17.2.0-beta.15
   @nx/devkit         : 17.2.0-beta.15
   @nx/eslint-plugin  : 17.2.0-beta.15
   @nx/react          : 17.2.0-beta.15
   @nrwl/tao          : 17.2.0-beta.15
   @nx/web            : 17.2.0-beta.15
   @nx/webpack        : 17.2.0-beta.15
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 17.0.1
   @ngrx/effects         : 17.0.1
   @ngrx/entity          : 17.0.1
   @ngrx/router-store    : 17.0.1
   @ngrx/store           : 17.0.1
   @ngrx/store-devtools  : 17.0.1

Done in 0.64s.
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by andersonba** [comment]
Wouldn't the correct command be `nx run [project:target] --graph`?
Since the `--graph` argument can receive a value, it must be passed last if you don't want to assign any value to it.
@jluxenberg

**Comment by jluxenberg** [comment]
> Wouldn't the correct command be `nx run [project:target] --graph`? Since the `--graph` argument can receive a value, it must be passed last if you don't want to assign any value to it. @jluxenberg

Ah I see! Yes that does work as expected, thanks @andersonba! Closing.
