### ISSUE TITLE
Failing to run workspace-schematics

### ISSUE THREAD

**Issue by joelmuskwe** [nrwl/nx#2070]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Expecting for schematics to run.

## Current Behavior
Schematic not found in collection "@nrwl/workspace".

## Failure Information (for bugs)

```
> Executing task: ng generate @nrwl/workspace:demo test <

An unhandled exception occurred: Schematic "demo" not found in collection "@nrwl/workspace".
See "/private/var/folders/xr/7cp2hsfd139b6tx_t_tjysfw0000gn/T/ng-wUWqFS/angular-errors.log" for further details.
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
```
angular-errors.log
```
[error] Error: Schematic "demo" not found in collection "@nrwl/workspace".
    at SchematicEngine.createSchematic (/Users/dev/Projects/lab/ng-demo/node_modules/@angular-devkit/schematics/src/engine/engine.js:232:23)
    at CollectionImpl.createSchematic (/Users/dev/Projects/lab/ng-demo/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at GenerateCommand.getSchematic (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/models/schematic-command.js:135:27)
    at GenerateCommand.initialize (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/models/schematic-command.js:45:36)
    at async GenerateCommand.initialize (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/commands/generate-impl.js:12:9)
    at async GenerateCommand.validateAndRun (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/models/command.js:124:9)
    at async Object.runCommand (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/models/command-runner.js:186:24)
    at async default_1 (/Users/dev/Projects/lab/ng-demo/node_modules/@angular/cli/lib/cli/index.js:54:31)
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create-nx-workspace my-suite   (select angular)
2. ng generate @nrwl/workspace:workspace-schematic demo-schematic
3. ng generate @nrwl/workspace:demo-schematic hello

**Comment by Maus3rVonDutch** [comment]
I'm also experiencing this (again), this is with the latest version 9.1

**Comment by mbriggs** [comment]
Hi!

The way workspace schematics are run are as follows `yarn workspace-schematic demo-schematic hello`. Just tried that out, and works for me on 8.8.1 :)

Going to close this, feel free to re-open if it doesn't work for you

**Comment by joelmuskwe** [comment]
Thanks it's working guess will move this issue to angular-console cause was using it when i got the error.
