### ISSUE TITLE
Error on npm registry name when running `nx release publish`

### ISSUE THREAD

**Issue by guillempuche** [nrwl/nx#20704]
### Current Behavior

My package.json name is `every-layout`. This means organization is `@every-layout`.

nx.json
```json
"release": {
    "releaseTagPattern": "{version}",
    "git": {
      "commit": true,
      "tag": true
    },
    "changelog": {
      "interactive": true,
      "git": {
        "commit": true,
        "tag": true
      },
      "workspaceChangelog": {
        "createRelease": "github",
        "file": false
      },
      "projectChangelogs": true
    },
    "groups": {
      "npm": {
        "projects": [
          "react-tamagui"
        ],
        "version": {
          "generatorOptions": {
            "packageRoot": "dist/packages/{projectName}",
            "currentVersionResolver": "registry"
          }
        }
      }
    }
  },
  ```
  
  My packages/react-native/package.json
  ```json

  "name": "@every-layout/react-tamagui",
  "version": "0.0.1",
  "main": "./src/index",
  "types": "./src/index.d.ts",
  "private": false,
  "publishConfig": {
    "access": "public"
  },
  ```
  
    My packages/react-native/project.json
  ```json
  {
  "name": "react-tamagui",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "packages/react-tamagui/src",
  "projectType": "library",
  "tags": [],
  "targets": {
    "build": {
      "executor": "@nx/vite:build",
      "dependsOn": [
        "ensure-symlink",
        "sync-deps"
      ],
      "outputs": [
        "{options.outputPath}"
      ],
      "options": {
        "outputPath": "dist/packages/react-tamagui"
      }
    },
    "lint": {
      "executor": "@nx/eslint:lint",
      "outputs": [
        "{options.outputFile}"
      ]
    },
    "nx-release-publish": {
      "dependsOn": [
        "^nx-release-publish",
        "build"
      ],
      "executor": "@nx/js:release-publish",
      "options": {
        "registry": "https://www.npmjs.com/package/@every-layout",
        "packageRoot": "dist/packages/react-tamagui"
      }
    },
    "res:dev": {
      "executor": "nx:run-commands",
      "options": {
        "command": "yarn rescript build -w",
        "cwd": "packages/react-tamagui"
      }
    },
    "res:build": {
      "executor": "nx:run-commands",
      "options": {
        "command": "yarn rescript",
        "cwd": "packages/react-tamagui"
      }
    },
    "res:build2": {
      "executor": "nx:run-commands",
      "inputs": [
        "{projectRoot}/src/index.ts",
        "{projectRoot}/src/**.res"
      ],
      "outputs": [
        "{projectRoot}/src/index.ts",
        "{projectRoot}/src/**.bs.js",
        "{projectRoot}/src/**.gen.ts"
      ],
      "options": {
        "commands": [
          "yarn rescript build"
        ],
        "cwd": "packages/react-tamagui"
      }
    }
  }
}
```

### Expected Behavior

Publish the npm package

### GitHub Repo

https://github.com/guillempuche/every-layout-react

### Steps to Reproduce

1. Run `yarn run release2`
2. Error because of `npm view react-tamagui versions dist-tags --json --registry=https://www.npmjs.com/package/@every-layout/`
3. Runn `npm view @every-layout/react-tamagui versions dist-tags --json`. No error

### Nx Report

```shell
Node   : 18.18.2
   OS     : darwin-arm64
   yarn   : 4.0.2
   
   nx                 : 17.2.0
   @nx/js             : 17.2.0
   @nx/jest           : 17.2.0
   @nx/linter         : 17.2.0
   @nx/eslint         : 17.2.0
   @nx/workspace      : 17.2.0
   @nx/detox          : 17.2.0
   @nx/devkit         : 17.2.0
   @nx/eslint-plugin  : 17.2.0
   @nx/react          : 17.2.0
   @nx/react-native   : 17.2.0
   @nx/rollup         : 17.2.0
   @nrwl/tao          : 17.2.0
   @nx/vite           : 17.2.0
   @nx/web            : 17.2.0
   typescript         : 5.2.2
```

### Failure Logs

```shell
0 verbose cli /Users/guillem/.nvm/versions/node/v18.18.2/bin/node /Users/guillem/.nvm/versions/node/v18.18.2/bin/npm
1 info using npm@9.8.1
2 info using node@v18.18.2
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/guillem/.nvm/versions/node/v18.18.2/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/guillem/programacio/codi/cites/every-layout/dist/packages/react-tamagui/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/guillem/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/guillem/.nvm/versions/node/v18.18.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 7ms
17 timing npm:load:configload Completed in 7ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm view react-tamagui versions dist-tags
22 verbose argv "view" "react-tamagui" "versions" "dist-tags" "--json" "--registry" "https://www.npmjs.com/package/@every-layout/"
23 timing npm:load:setTitle Completed in 5ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/Users/guillem/.npm/_logs/2023-12-11T20_54_47_609Z-
26 verbose logfile /Users/guillem/.npm/_logs/2023-12-11T20_54_47_609Z-debug-0.log
27 timing npm:load:logFile Completed in 5ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 26ms
31 silly logfile start cleaning logs, removing 2 files
32 silly logfile done cleaning log files
33 http fetch GET 200 https://www.npmjs.com/package/@every-layout/react-tamagui 1891ms (cache miss)
34 timing command:view Completed in 1895ms
35 verbose type invalid-json
36 verbose stack FetchError: invalid json response body at https://www.npmjs.com/package/@every-layout/react-tamagui reason: Unexpected token < in JSON at position 1
36 verbose stack     at Response.json (/Users/guillem/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/minipass-fetch/lib/body.js:79:13)
36 verbose stack     at async RegistryFetcher.packument (/Users/guillem/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/pacote/lib/registry.js:94:25)
36 verbose stack     at async View.getData (/Users/guillem/.nvm/versions/node/v18.18.2/lib/node_modules/npm/lib/commands/view.js:197:20)
36 verbose stack     at async View.exec (/Users/guillem/.nvm/versions/node/v18.18.2/lib/node_modules/npm/lib/commands/view.js:105:28)
36 verbose stack     at async module.exports (/Users/guillem/.nvm/versions/node/v18.18.2/lib/node_modules/npm/lib/cli-entry.js:61:5)
37 verbose cwd /Users/guillem/programacio/codi/cites/every-layout/dist/packages/react-tamagui
38 verbose Darwin 23.1.0
39 verbose node v18.18.2
40 verbose npm  v9.8.1
41 error code FETCH_ERROR
42 error errno FETCH_ERROR
43 error invalid json response body at https://www.npmjs.com/package/@every-layout/react-tamagui reason: Unexpected token < in JSON at position 1
44 verbose exit 1
45 timing npm Completed in 1983ms
46 verbose code 1
47 error A complete log of this run can be found in: /Users/guillem/.npm/_logs/2023-12-11T20_54_47_609Z-debug-0.log
```

### Package Manager Version

4.0.2

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
@guillempuche I'm a bit confused by this one, `https://www.npmjs.com/package/@every-layout/` is not an npm registry it's a URL to a package in the npm UI?

`https://registry.npmjs.org` is a registry (the default one), `https://npm.pkg.github.com` is a registry (the one for github packages), `http://localhost:4873` could be a registry if running verdaccio locally...

In your specific case, what were you trying to achieve by customizing the registry?

**Comment by JamesHenry** [comment]
I'm going to close this one as I don't believe anything needs to change on the nx side, but feel free to respond on the thread

**Comment by guillempuche** [comment]
This is the package https://www.npmjs.com/package/@every-layout/react-tamagui.

I don't find Nx guides or public projects on Github (projects that release version to Github and then publishing specific packages). Releasing+publish the whole monorepo and only specific packages.

I'm looking for nx.json, package.json and project.json configurations.

**Comment by JamesHenry** [comment]
Yes, `nx release` is still a very new feature, we will be adding more guides and tutorials over the coming weeks and months. Right now it is most suitable for folks who want to opt into something new and test it out.

We have an introductory overview to the core concepts, but more specific guides are not available yet: https://nx.dev/core-features/manage-releases#manage-releases Please have a read of that, and please also read the NPM docs link I shared above to make sure you understand what `registry` means in this context (it's nothing specific to nx, it's an npm concept in general).

If after reading those things you want to continue, the best place to get help with setting things up right now is our community discord: https://go.nx.dev/community

A few quick observations in the meantime:

- I think in your case your configuration is much more complicated than it needs to be as you only have a single package in your workspace.
- Based on your setup I am guessing you are trying to emulate the nx repo itself, but that is more complex than your repo so you could start with zero config initially and see how you get on (you can run all the commands in dry-run as you go to see what would happen)
- You are currently tracking your dist folder in git, this is not usually desirable so maybe that was accidental?

Hope that helps for now!
