### ISSUE TITLE
Option "isolatedConfig" is deprecated:

### ISSUE THREAD

**Issue by ojemuyiwa** [nrwl/nx#20738]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

[Enter the URL or documentation section here.](https://nx.dev/recipes/webpack/webpack-config-setup)

### Additional context or description

WARNING: Option "isolatedConfig" is deprecated: Automatic configuration of Webpack is deprecated in favor of an explicit 'webpack.config.js' file. This option will be removed in Nx 18. See https://nx.dev/recipes/webpack/webpack-config-setup.

but isolatedConfig has been removed from my package.json and warning still shows?
```
"options": {
        "compiler": "babel",
        "outputPath": "dist/ui/browser",
        "index": "src/index.html",
        "baseHref": "/ui/",
        "main": "src/main.tsx",
        "tsConfig": "tsconfig.app.json",
        "assets": ["src/favicon.ico", "src/assets"],
        "styles": ["src/styles.css"],
        "scripts": [],
        "webpackConfig": "./webpack.config.js"
      },
```

**Comment by jaysoo** [comment]
Which version of Nx are you on? Can you run `nx report` and paste the info here?

**Comment by ojemuyiwa** [comment]
> Which version of Nx are you on? Can you run `nx report` and paste the info here?

17.2.0

**Comment by jaysoo** [comment]
can you try the latest patch 17.2.4?

**Comment by ojemuyiwa** [comment]
> can you try the latest patch 17.2.4?

Ok will do on the morrow, cheers

**Comment by ojemuyiwa** [comment]
> 17.2.4

17.2.3 is latest and new migration caused even more issues
<img width="1159" alt="Screenshot 2023-12-14 at 10 00 54" src="https://github.com/nrwl/nx/assets/13540819/f17a07f0-9154-469f-9a61-c6c2f0c06f4a">

**Comment by ojemuyiwa** [comment]
used 17.2.4 explicitly and still broken, no liveReload on SSR so i guess I'll remove it and give feedback.
<img width="1148" alt="Screenshot 2023-12-14 at 10 04 12" src="https://github.com/nrwl/nx/assets/13540819/76edd3de-322b-41e0-953f-221442277df4">

**Comment by jaysoo** [comment]
Can you provide a small reproduction for this issue?  It will help with the investigation.

**Comment by beeman** [comment]
> Can you provide a small reproduction for this issue? It will help with the investigation.

![image](https://github.com/nrwl/nx/assets/36491/6189c7ea-31b2-457f-b69a-11e4e456e489)

I'm seeing the same in [this project](https://github.com/pubkeyapp/pubkey-stack/) - maybe that helps to debug it? 


```
 >  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : darwin-arm64
   pnpm   : 8.9.2
   
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/nest           : 17.2.8
   @nx/node           : 17.2.8
   @nx/plugin         : 17.2.8
   @nx/react          : 17.2.8
   @nx/rollup         : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @pubkey-ui/generators            : 1.1.0
   @solana-developers/preset-anchor : 2.0.0
   ---------------------------------------
   Local workspace plugins:
         @pubkey-stack/tools
```

**Comment by gRoussac** [comment]
Hi, Does this help ? because it would help me to get the issue running a nestjs project. I don't have a specific webpack config for this project. (I do have     `"@angular-builders/custom-webpack": "^16.0.1",` in package.json and another project using `custom-webpack.config.js` at root folder)

```
 >  NX   Using "isolatedConfig" without a "webpackConfig" is not supported.


Error: Using "isolatedConfig" without a "webpackConfig" is not supported.
    at getWebpackConfigs (/opt2/www/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:20:15)
    at webpackExecutor (/opt2//www/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:99:27)
    at webpackExecutor.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/opt2/www/node_modules/nx/src/utils/async-iterator.js:13:27)
    at iteratorToProcessStatusCode (/opt2/www/node_modules/nx/src/command-line/run/run.js:41:94)
    at /opt2/www/node_modules/nx/src/command-line/run/run.js:155:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/opt2/www/node_modules/nx/src/utils/params.js:9:16)
    at async process.<anonymous> (/opt2/www/node_modules/nx/bin/run-executor.js:59:28)
```   
```
Node   : 21.5.0
   OS     : linux-x64
   npm    : 10.2.5
   
   nx (global)        : 17.2.8
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/nest           : 17.2.8
   @nx/node           : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   nx-cloud           : 16.5.2
   typescript         : 5.2.2

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target build for project api failed

   Failed tasks:
   
   - api:build
```

thanks

**Comment by gRoussac** [comment]
> but isolatedConfig has been removed from my package.json and warning still shows?

I think I had a similar issue migrating from a 14.8.3 to 17.2.8 forcing to use isolatedConfig in project.json (not package.json) which seems to be fixed by https://github.com/nrwl/nx/issues/20671#issuecomment-1848396559 (not sure why I have to add that webpack.config.js manually though)

**Comment by beeman** [comment]
> This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs. If we missed this issue please reply to keep it active. Thanks for being a part of the Nx community! 🙏

reply

**Comment by alextegelid** [comment]
I'm getting this warning today while upgrading to NX 18. Simply removing the line from project.json seems to work, but I'm not sure if that will come back to bite me later.

**Comment by beeman** [comment]
> Simply removing the line from project.json seems to work, but I'm not sure if that will come back to bite me later.

Same, I didn't manually remove it as I hope a migration will do it 'right'.

**Comment by beeman** [comment]
> reply 🙌

**Comment by beeman** [comment]
> reply

**Comment by konekoya** [comment]
We're getting this warning as well. We're currently on nx `17.3.2`

**Comment by beeman** [comment]
> 🙏

**Comment by beeman** [comment]
> It will be closed in 21 days if no information is provided.

Working repro here: https://github.com/nrwl/nx/issues/20738#issuecomment-1876727389

**Comment by boltex** [comment]
getting this too on my project

**Comment by beeman** [comment]
Working repro here: https://github.com/nrwl/nx/issues/20738#issuecomment-1876727389

**Comment by beeman** [comment]
> 🙏

**Comment by beeman** [comment]
![image](https://github.com/nrwl/nx/assets/36491/a303c6d2-6d54-4ea6-8451-245c8afbca6a)

**Comment by beeman** [comment]
> because more information has not been provided within 7 days

🫣

**Comment by AhmedBHameed** [comment]
We are getting this warning message also in our project.

**Comment by chtpl** [comment]
It's still annoying pls fix it!

**Comment by chtpl** [comment]
my goodness ...

**Comment by chtpl** [comment]
Here we go again ... still being ignored by nx team

**Comment by chtpl** [comment]
please at least respond whether this will be fixed

**Comment by shubham-vunet** [comment]
👍

**Comment by beeman** [comment]
It's also still happening in the example I posted like 7 months ago, in case a working demo is needed. https://github.com/nrwl/nx/issues/20738#issuecomment-1876727389

**Comment by chtpl** [comment]
as the bot says `It will be closed in 21 days if no information is provided.`
- what information does the nx team need to fix this?

**Comment by beeman** [comment]
> as the bot says `It will be closed in 21 days if no information is provided.`
> 
> * what information does the nx team need to fix this?

Maybe @jaysoo or @FrozenPandaz has any idea?

**Comment by jvinceller** [comment]
Not sure this helps, but I've just tried it, because I had the same issue. Even though using Nx `17.3.0`. I actually had two issues and fixed them both: I had to update my browserlists which I guess has nothing to do with this issue, but just wanted to tell if it indeed has to do sg. with it. Command: `npx update-browserslist-db@latest`. And then I've just removed the `isolatedConfig` line from `project.json`. So I guess 17.3.0 should do the maths.

**Comment by chtpl** [comment]
still waiting for a reply

**Comment by chtpl** [comment]
why are you ignoring us @jaysoo

**Comment by AhmedBHameed** [comment]
Is that another google dead project?

This issue has been automatically marked as stale by google. We still have this issue.

**Comment by beeman** [comment]
‎

**Comment by beeman** [comment]
[](€

**Comment by beeman** [comment]
[]()

**Comment by beeman** [comment]
> This issue has been automatically marked as stale because more information has not been provided within 7 days. It will be closed in 21 days if no information is provided. If information has been provided, please reply to keep it active. Thanks for being a part of the Nx community! 🙏

**Comment by chtpl** [comment]
@jaysoo can you please respond?

**Comment by chtpl** [comment]
🙄

**Comment by chtpl** [comment]
...

**Comment by beeman** [comment]
.

**Comment by chtpl** [comment]
🙄

**Comment by beeman** [comment]
:)

**Comment by beeman** [comment]
Coming Friday... 🥳
![Image](https://github.com/user-attachments/assets/bb0ebcf3-6d4a-4d3f-8908-7b131adb00ae)

**Comment by chtpl** [comment]
bump

**Comment by chtpl** [comment]
bump

**Comment by chtpl** [comment]
Bump

**Comment by chtpl** [comment]
Bum

**Comment by PointSingularity** [comment]
Bump

**Comment by chtpl** [comment]
bump

**Comment by beeman** [comment]
Wondering if this issue will make it to 2 years 🎂 We're ~70% on our way! 👏

**Comment by chtpl** [comment]
very unprofessional
