### ISSUE TITLE
Extending the project graph errors

### ISSUE THREAD

**Issue by TriPSs** [nrwl/nx#20762]
### Current Behavior

When extending the project graph everything works fine (the projects are found and targets are working) but building a nextjs application failes with the following error:

```bash
> Build error occurred
Error: GenericFailure
    at getNxWorkspaceFilesFromContext (/Users/tycho/GIT/Github/Sprekershuys/bug-free-fort/node_modules/nx/src/utils/workspace-context.js:16:29)
    at retrieveWorkspaceFiles (/Users/tycho/GIT/Github/Sprekershuys/bug-free-fort/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:26:138)
    at buildProjectGraphWithoutDaemon (/Users/tycho/GIT/Github/Sprekershuys/bug-free-fort/node_modules/nx/src/project-graph/project-graph.js:70:82)
    at createProjectGraphAsync (/Users/tycho/GIT/Github/Sprekershuys/bug-free-fort/node_modules/nx/src/project-graph/project-graph.js:121:25)
    at /Users/tycho/GIT/Github/Sprekershuys/bug-free-fort/node_modules/@nx/next/plugins/with-nx.js:111:27
    at normalizeConfig (/Users/tycho/GIT/Github/Sprekershuys/bug-free-fort/node_modules/next/src/server/config-shared.ts:818:10)
    at loadConfig (/Users/tycho/GIT/Github/Sprekershuys/bug-free-fort/node_modules/next/src/server/config.ts:997:24)
    at Span.traceAsyncFn (/Users/tycho/GIT/Github/Sprekershuys/bug-free-fort/node_modules/next/src/trace/trace.ts:127:14)
    at /Users/tycho/GIT/Github/Sprekershuys/bug-free-fort/node_modules/next/src/build/index.ts:386:42
    at Span.traceAsyncFn (/Users/tycho/GIT/Github/Sprekershuys/bug-free-fort/node_modules/next/src/trace/trace.ts:127:14) {
  code: 'ParseError'
```

### Expected Behavior

For the target to execute correctly

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 20.3.0
   OS     : darwin-arm64
   yarn   : 4.0.2

   nx (global)        : 17.2.3
   nx                 : 17.1.1
   @nx/js             : 17.1.1
   @nx/jest           : 17.1.1
   @nx/linter         : 17.1.1
   @nx/eslint         : 17.1.1
   @nx/workspace      : 17.1.1
   @nx/devkit         : 17.1.1
   @nx/eslint-plugin  : 17.1.1
   @nx/nest           : 17.1.1
   @nx/next           : 17.1.1
   @nx/node           : 17.1.1
   @nx/plugin         : 17.1.1
   @nx/react          : 17.1.1
   @nrwl/tao          : 17.1.1
   @nx/web            : 17.1.1
   @nx/webpack        : 17.2.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @jscutlery/semver                 : 4.0.0
   @nx-extend/changelog-notify       : 5.0.1
   @nx-extend/firebase-hosting       : 6.0.3
   @nx-extend/gcp-cloud-run          : 7.2.4
   @nx-extend/gcp-deployment-manager : 6.0.1
   @nx-extend/gcp-secrets            : 7.0.2
   @nx-extend/pulumi                 : 4.1.1
   @nx-extend/strapi                 : 8.0.5
   @nx-extend/vercel                 : 6.0.3
   ---------------------------------------
   Local workspace plugins:
   	 @plugin/data
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I tried updating to the latest version of Nx but that caused more issues with the deamon not able to hash the tasks. If I disable the plugin that extends the graph I do not get the error.

**Comment by TriPSs** [comment]
Figured out that it was caused by using `readJsonFile` from `nx/src/utils/fileutils`, If i change the implementation of the plugin from:
```ts
export const createNodes: CreateNodes = [
  '**/block-site.*.json',
  (projectConfigurationFile: string, opts, context: CreateNodesContext) => {
    const projectConfiguration = readJsonFile(projectConfigurationFile) as {
```

To
```ts
export const createNodes: CreateNodes = [
  '**/block-site.*.json',
  (projectConfigurationFile: string, opts, context: CreateNodesContext) => {
    const projectConfiguration = readJsonFile(resolve(workspaceRoot, projectConfigurationFile)) as {
```

Everything works, maybe a good idea to prepend `workspaceRoot` within `readJsonFile`?

**Comment by AgentEnder** [comment]
It doesn't make sense to add that inside the readJsonFile implementation as its commonly used together with __dirname or other qualifiers. Instead, adding workspace root in the plugin code is advised.

I'm going to close this out since  a workaround was found.

**Comment by TriPSs** [comment]
@AgentEnder maybe than update the examples of extending the project graph as it currently does not work.
