### ISSUE TITLE
`nx format:check` outputs nx-js-graph-plugin error

### ISSUE THREAD

**Issue by warnellw** [nrwl/nx#20779]
### Current Behavior

When running `nx format:check` in CI, there appears to sometimes be an issue parsing the `yarn.lock` file (see error). A re-run of the CI workflow with no changes when this happens usually passes, meaning the issue is inconsistent.

### Expected Behavior

`nx format:check` should execute with no errors

### Steps to Reproduce

1. Use Yarn v1 and a `yarn.lock` with Nx v17
2. Run `nx format:check` in GitHub Actions as part of the `parallel-commands` on the main agent in the `nrwl/ci` build/lint/test workflow

This issue is inconsistent, and is only reproducible in CI (GitHub Actions in this case). It has only appeared since migrating from Nx v16 -> Nx v17. Looking for some guidance on how to provide any additional information that could be useful in tracking down the issue 🙂

### Nx Report

```shell
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 17.2.1
   @nx/js             : 17.2.1
   @nx/jest           : 17.2.1
   @nx/linter         : 17.2.1
   @nx/eslint         : 17.2.1
   @nx/workspace      : 17.2.1
   @nx/cypress        : 17.2.1
   @nx/devkit         : 17.2.1
   @nx/eslint-plugin  : 17.2.1
   @nx/express        : 17.2.1
   @nx/nest           : 17.2.1
   @nx/next           : 17.2.1
   @nx/node           : 17.2.1
   @nx/plugin         : 17.2.1
   @nx/react          : 17.2.1
   @nrwl/tao          : 17.2.1
   @nx/web            : 17.2.1
   @nx/webpack        : 17.2.1
   typescript         : 5.2.2
   ---------------------------------------
   Local workspace plugins:
         @workspace/tooling
```

### Failure Logs

```shell
$ nx format:check
Unable to create nodes for yarn.lock using plugin nx-js-graph-plugin. 

   Inner Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at readCachedParsedLockFile (/home/runner/work/workspace/workspace/node_modules/nx/src/plugins/js/index.js:93:17)
    at exports.createNodes (/home/runner/work/workspace/workspace/node_modules/nx/src/plugins/js/index.js:36:27)
    at buildProjectsConfigurationsFromProjectPathsAndPlugins (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:125:29)
    at createProjectConfigurations (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
    at _retrieveProjectConfigurations (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
    at retrieveProjectConfigurations (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
    at async buildProjectGraphAndSourceMapsWithoutDaemon (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/project-graph.js:71:69)
    at async createProjectGraphAndSourceMapsAsync (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/project-graph.js:136:25)
    at async createProjectGraphAsync (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/project-graph.js:125:39)

 >  NX   Unable to create nodes for yarn.lock using plugin nx-js-graph-plugin. 

   
     Inner Error: SyntaxError: Unexpected end of JSON input
       at JSON.parse (<anonymous>)
       at readCachedParsedLockFile (/home/runner/work/workspace/workspace/node_modules/nx/src/plugins/js/index.js:93:17)
       at exports.createNodes (/home/runner/work/workspace/workspace/node_modules/nx/src/plugins/js/index.js:36:27)
       at buildProjectsConfigurationsFromProjectPathsAndPlugins (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:125:29)
       at createProjectConfigurations (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
       at _retrieveProjectConfigurations (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
       at retrieveProjectConfigurations (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
       at async buildProjectGraphAndSourceMapsWithoutDaemon (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/project-graph.js:71:69)
       at async createProjectGraphAndSourceMapsAsync (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/project-graph.js:136:25)
       at async createProjectGraphAsync (/home/runner/work/workspace/workspace/node_modules/nx/src/project-graph/project-graph.js:125:39)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by andersonba** [comment]
It happens to me, in fact it's inconsistent, but in my case, all locally.
