### ISSUE TITLE
Error with license-webpack-plugin while building a node app

### ISSUE THREAD

**Issue by matheo** [nrwl/nx#2083]
# Prerequisites

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

My build script got broken updating to the latest version.
It seems that `@nrwl/node` is having some kind of configuration issue that was not upgraded with the v8.8.0 release.

## Current Behavior

Build fails with this error:
`An unhandled exception occurred: license-webpack-plugin: Please specify a regular expression as the pattern property on the plugin options.`

## Failure Information (for bugs)

I'm getting this stack trace while trying to build a node app:
```
[error] Error: license-webpack-plugin: Please specify a regular expression as the pattern property on the plugin options.
   at new LicenseWebpackPluginError (/node_modules/@nrwl/node/node_modules/license-webpack-plugin/dist/LicenseWebpackPluginError.js:25:24)
   at new LicenseWebpackPlugin (/node_modules/@nrwl/node/node_modules/license-webpack-plugin/dist/LicenseWebpackPlugin.js:33:19)
   at Object.getBaseWebpackPartial (/node_modules/@nrwl/node/src/utils/config.js:74:27)
   at Object.getNodeWebpackConfig (/node_modules/@nrwl/node/src/utils/node.config.js:39:18)
   at MapSubscriber.rxjs_1.from.pipe.operators_1.map.options [as project] (/node_modules/@nrwl/node/src/builders/build/build.impl.js:28:36)
   at MapSubscriber._next (/node_modules/rxjs/internal/operators/map.js:49:35)
   at MapSubscriber.Subscriber.next (/node_modules/rxjs/internal/Subscriber.js:66:18)
   at MapSubscriber._next (/node_modules/rxjs/internal/operators/map.js:55:26)
   at MapSubscriber.Subscriber.next (/node_modules/rxjs/internal/Subscriber.js:66:18)
   at /node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
   at process._tickCallback (internal/process/next_tick.js:68:7)
   at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
   at startup (internal/bootstrap/node.js:285:19)
   at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

### Context

Please provide any relevant information about your setup:

  @nrwl/angular : 8.8.0
  @nrwl/cli : 8.8.0
  @nrwl/cypress : 8.8.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.8.0
  @nrwl/linter : 8.8.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 8.8.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.8.0
  @nrwl/web : Not Found
  @nrwl/workspace : 8.8.0
  typescript : 3.5.3

**Comment by bradtaniguchi** [comment]
Looks to be a duplicate of #2081

**Comment by matheo** [comment]
Closing this in favor of 2081.
