### ISSUE TITLE
Migration failure from 8.7.0 to 8.8.0

### ISSUE THREAD

**Issue by jaripekkala** [nrwl/nx#2085]
## Expected Behavior

Workspace to be updated.

## Current Behavior

Failing update.

### Steps to Reproduce

1. `npx create-nx-workspace@8.7.0 repro-workspace --preset=empty --cli=nx`
2. `cd repro-workspace`
3. `yarn nx migrate @nrwl/workspace`

### Context

>  NX   NOTE  Nx CLI is not installed globally.

### Failure Logs

```
Jaris-MacBook-Pro:repro-workspace jaripekkala$ yarn nx migrate @nrwl/workspace
yarn run v1.19.0
$ nx migrate @nrwl/workspace
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @nrwl/angular@undefined
Fetching @nrwl/cypress@undefined
Fetching @nrwl/eslint-plugin-nx@undefined
Fetching @nrwl/express@undefined
Fetching @nrwl/jest@undefined
Fetching @nrwl/linter@undefined
Fetching @nrwl/nest@undefined
Fetching @nrwl/next@undefined
Fetching @nrwl/node@undefined
Fetching @nrwl/react@undefined
Fetching @nrwl/tao@undefined
Fetching @nrwl/web@undefined
Fetching @ngrx/store@8.5.0
Fetching @ngrx/effects@8.5.0
Fetching @ngrx/entity@8.5.0
Fetching @ngrx/router-store@8.5.0
Fetching @ngrx/schematics@8.5.0
Fetching @ngrx/store-devtools@8.5.0
Fetching @angular-devkit/architect@0.803.14
Fetching @angular-devkit/build-angular@0.803.14
Fetching @angular-devkit/build-ng-packagr@0.803.14
Fetching @angular-devkit/build-webpack@0.803.14
Fetching @angular-devkit/core@8.3.14
Fetching @angular-devkit/schematics@8.3.14
Fetching @angular/cli@8.3.14
Fetching @angular/common@8.2.12
Fetching @angular/compiler@8.2.12
Fetching @angular/compiler-cli@8.2.12
Fetching @angular/core@8.2.12
Fetching @angular/platform-browser@8.2.12
Fetching @angular/platform-browser-dynamic@8.2.12
Fetching @angular/router@8.2.12
Fetching @angular/upgrade@8.2.12
Fetching @schematics/angular@8.3.14
Command failed: npm install @nrwl/angular@undefined --prefix=/var/folders/30/w_2g8x952v51t29y408dy08h0000gn/T/tmp-402451x2ofN7iwBby
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/angular@undefined.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jaripekkala/.npm/_logs/2019-11-21T07_05_44_423Z-debug.log

Run migrate with --to="package1@version1,package2@version2"
/Users/jaripekkala/Code/foo/repro-workspace/node_modules/yargs/yargs.js:1109
      else throw err
           ^

Error: Command failed: ./node_modules/.bin/tao migrate @nrwl/workspace
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Object.handler (/Users/jaripekkala/Code/foo/repro-workspace/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:96:21)
    at Object.runCommand (/Users/jaripekkala/Code/foo/repro-workspace/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/jaripekkala/Code/foo/repro-workspace/node_modules/yargs/yargs.js:1022:30)
    at Object.get [as argv] (/Users/jaripekkala/Code/foo/repro-workspace/node_modules/yargs/yargs.js:965:21)
    at Object.<anonymous> (/Users/jaripekkala/Code/foo/repro-workspace/node_modules/@nrwl/cli/bin/nx.js:38:26)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 40245,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by mbriggs** [comment]
Thank you for your report, we will fix this soon :)

**Comment by vsavkin** [comment]
We had an issue with the migrate in 8.7.1. We fixed it, but because of the way migrations work, you will have update `@nrwl/workspace` first.

1. Update @nrwl/workspace to 8.8.1 using yarn or npm
2. Run nx migrate `@nrwl/workspace@8.8.2 --from="@nrwl/workspace@8.7.1"`

Thank you for reporting the issue!

**Comment by jaripekkala** [comment]
Thank you guys for fixing this so fast :)

There was some errors thrown when following the instructions. However updating `@nrwl/workspace` to `8.8.2` instead of `8.8.1` beforehand did the trick and the migration succeed.

**Comment by cmalard** [comment]
Hi there, I'm having a similar issue :

```
nx migrate @nrwl/workspace@latest

Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Command failed: npm install @nrwl/workspace@latest --prefix=/tmp/tmp-29797MzwOoIGucW6X
/home/.../node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1109
      else throw err
           ^

Error: Command failed: ./node_modules/.bin/tao migrate @nrwl/workspace@latest
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Object.handler (/home/.../node_modules/@nrwl/workspace/src/command-line/nx-commands.js:99:21)
    at Object.runCommand (/home/.../node_modules/@nrwl/workspace/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/.../node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1022:30)
    at Object.get [as argv] (/home/.../node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:965:21)
    at Object.<anonymous> (/home/.../node_modules/@nrwl/cli/bin/nx.js:38:26)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 29795,
  stdout: null,
  stderr: null
}
```

`npm i @nrwl/workspace@8.8.1 && nx migrate @nrwl/workspace@8.8.2 --from="@nrwl/workspace@8.7.0"`, `npm i @nrwl/workspace@8.8.2 && nx migrate @nrwl/workspace@8.8.2 --from="@nrwl/workspace@8.7.0"` and `npm i @nrwl/workspace@latest && nx migrate @nrwl/workspace` (`--from="@nrwl/workspace@8.7.0"`) ` did not helped

Thanks for your help :-)
