### ISSUE TITLE
Cannot set properties of undefined (setting 'storybook')

### ISSUE THREAD

**Issue by cah-sourabh-singh** [nrwl/nx#20915]
### Current Behavior

**When attempting to instantiate Storybook for a project within a Lerna mono repo using the provided command:**
`npx nx generate @nx/storybook:configuration --project=@spf/styleguide --configureStaticServe=true --verbose`

**the following error is encountered:**
` >  NX   Cannot set properties of undefined (setting 'storybook')

TypeError: Cannot set properties of undefined (setting 'storybook')
    at addStorybookTask (C:\Users\soura\Projects\coldfusion\student-platform-frontend\node_modules\@nx\storybook\src\generators\configuration\lib\util-functions.js:18:40)
    at configurationGenerator (C:\Users\soura\Projects\coldfusion\student-platform-frontend\node_modules\@nx\storybook\src\generators\configuration\configuration.js:60:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\soura\Projects\coldfusion\student-platform-frontend\node_modules\nx\src\command-line\generate\generate.js:241:26
    at async handleErrors (C:\Users\soura\Projects\coldfusion\student-platform-frontend\node_modules\nx\src\utils\params.js:9:16)
    at async Object.handler (C:\Users\soura\Projects\coldfusion\student-platform-frontend\node_modules\nx\src\command-line\generate\command-object.js:13:22)`

### Expected Behavior

Storybook configuration should be generated successfully without encountering the "**_**Cannot set properties of undefined (setting 'storybook**_**')" error.

### Steps to Reproduce

1. Run the command mentioned above to generate Storybook configuration.
2. Encounter the mentioned error.

### Nx Report

```shell
npx nx report

   Node   : 20.10.0
   OS     : win32-x64
   npm    : 10.2.5

   nx             : 17.2.7
   lerna          : 8.0.1
   @nx/js         : 17.2.7
   @nx/linter     : 17.2.7
   @nx/eslint     : 17.2.7
   @nx/workspace  : 17.2.7
   @nx/cypress    : 17.2.7
   @nx/devkit     : 17.2.7
   @nx/storybook  : 17.2.7
   @nrwl/tao      : 17.2.7
   typescript     : 5.3.3
```

### Failure Logs

```shell
>  NX   Cannot set properties of undefined (setting 'storybook')


TypeError: Cannot set properties of undefined (setting 'storybook')
    at addStorybookTask (C:\Users\soura\Projects\coldfusion\student-platform-frontend\node_modules\@nx\storybook\src\generators\configuration\lib\util-functions.js:18:40)
    at configurationGenerator (C:\Users\soura\Projects\coldfusion\student-platform-frontend\node_modules\@nx\storybook\src\generators\configuration\configuration.js:60:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\soura\Projects\coldfusion\student-platform-frontend\node_modules\nx\src\command-line\generate\generate.js:241:26
    at async handleErrors (C:\Users\soura\Projects\coldfusion\student-platform-frontend\node_modules\nx\src\utils\params.js:9:16)
    at async Object.handler (C:\Users\soura\Projects\coldfusion\student-platform-frontend\node_modules\nx\src\command-line\generate\command-object.js:13:22)
```

### Package Manager Version

npm - 10.2.5

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Note that this generator (`@nx/storybook:configuration`), and most of the other generators, do not support projects that were not generated with Nx generators. The workaround is to create a `project.json` file with the following content:

```json
{
  "name": "@spf/styleguide",
  "targets": {}
}
```

That should allow the generator to run, but since the setup isn't from an Nx generator, you _may_ need to fix what's generated.
