### ISSUE TITLE
@nx/eslint Unknown options: reportUnusedDisableDirectives after upgrading to eslint 8.56.0

### ISSUE THREAD

**Issue by broksonic21** [nrwl/nx#20943]
### Current Behavior

```
 >  NX   Invalid Options:

   - Unknown options: reportUnusedDisableDirectives
   - 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.

Error: Invalid Options:
- Unknown options: reportUnusedDisableDirectives
- 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.
    at processOptions (/Users/REDACTED/REDACTED/node_modules/eslint/lib/eslint/eslint-helpers.js:783:15)
    at new FlatESLint (/Users/REDACTED/REDACTED/node_modules/eslint/lib/eslint/flat-eslint.js:556:34)
    at resolveAndInstantiateESLint (/Users/REDACTED/REDACTED/node_modules/@nx/eslint/src/executors/lint/utility/eslint-utils.js:65:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/Users/REDACTED/REDACTED/node_modules/@nx/eslint/src/executors/lint/lint.impl.js:47:32)
```

### Expected Behavior

@nx/eslint 17.2.8 and eslint  8.56.0 work same after upgrading. 

### Steps to Reproduce

have on a private repo right now, will look into a public one

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   npm    : 10.2.5

   nx             : 17.2.8
   @nx/js         : 17.2.8
   @nx/jest       : 17.2.8
   @nx/linter     : 17.2.8
   @nx/eslint     : 17.2.8
   @nx/workspace  : 17.2.8
   @nx/devkit     : 17.2.8
   @nrwl/tao      : 17.2.8
   typescript     : 5.3.3
   ---------------------------------------
   Community plugins:
   nx-stylelint : 17.1.0
```

### Failure Logs

```shell
>  NX   Invalid Options:

   - Unknown options: reportUnusedDisableDirectives
   - 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.

Error: Invalid Options:
- Unknown options: reportUnusedDisableDirectives
- 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.
    at processOptions (/Users/REDACTED/REDACTED/node_modules/eslint/lib/eslint/eslint-helpers.js:783:15)
    at new FlatESLint (/Users/REDACTED/REDACTED/node_modules/eslint/lib/eslint/flat-eslint.js:556:34)
    at resolveAndInstantiateESLint (/Users/REDACTED/REDACTED/node_modules/@nx/eslint/src/executors/lint/utility/eslint-utils.js:65:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/Users/REDACTED/REDACTED/node_modules/@nx/eslint/src/executors/lint/lint.impl.js:47:32)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

only happens after upgrading to eslint 8.56.0 using flag config

**Comment by AdarshKonchady** [comment]
Seeing this issue as well. Seems to be happening due to the option here - https://github.com/nrwl/nx/blob/master/packages/eslint/src/executors/lint/utility/eslint-utils.ts#L52-L53

**Comment by ShaneYu** [comment]
Until this issue has been resolved, does anyone know of a workaround? Is there a way to remove this option in our ESLint configuration files or something?

**Comment by arklanq** [comment]
> Until this issue has been resolved, does anyone know of a workaround? Is there a way to remove this option in our ESLint configuration files or something?

Downgrade ESLint to `8.55.X`.

**Comment by AdarshKonchady** [comment]
If you want to be on the latest eslint 8.56.0 version till there's a Nx fix for this, I was able to get it to work by using `eslint` directly in Nx project.json "lint" instead of using `@nx/linter`: 

```
"lint": {
      "executor": "nx:run-commands",
      "options": {
        "commands": ["pnpm eslint packages/PACKAGE_NAME"],
        "parallel": false
      }
    },
```

**Comment by meeroslav** [comment]
> If you want to be on the latest eslint 8.56.0 version till there's a Nx fix for this, I was able to get it to work by using eslint directly in Nx project.json "lint" instead of using @nx/linter:

Actually, this would be the proper way to do it outside of `@nx/eslint` plugin:

```jsonc
"lint": {
  "command": "eslint .", // lint everything at the current working directory
  "options": {
    "cwd": "{projectRoot}", // this tells the above command to run in your project's folder
  }
}
```
