### ISSUE TITLE
nx g @nx/storybook:configuration fail with InvalidSymbol in JSON

### ISSUE THREAD

**Issue by unional** [nrwl/nx#20951]
### Current Behavior

```sh
>  NX   Cannot parse ..snap../.eslintrc.js: InvalidSymbol in JSON at 1:1

   > 1 | module.exports = {
       | ^^^^^^^^^^^^^^
     2 |   env: {
     3 |     browser: true,
     4 |     es2020: true,

    at readJson (/..snap../node_modules/.pnpm/nx@17.2.6/node_modules/nx/src/generators/utils/json.js:20:15)
    at updateJson (/..snap../node_modules/.pnpm/nx@17.2.6/node_modules/nx/src/generators/utils/json.js:45:34)
    at updateLintConfig (/..snap../node_modules/.pnpm/@nx+storybook@17.2.8_@types+node@17.0.45_eslint@8.36.0_nx@17.2.6_typescript@5.1.6/node_modules/@nx/storybook/src/generators/configuration/lib/util-functions.js:287:33)
```

### Expected Behavior

It should not read js config file as json

### Steps to Reproduce

1. run `nx g @nx/storybook:configuration` on a project with `.eslintrc.js` (as well as `.eslintrc.cjs`
 

### Nx Report

```shell
nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 16.20.2
   OS     : darwin-arm64
   npm    : 8.19.4
   
   nx (global)    : 17.2.8
   nx             : 17.2.8
   lerna          : 7.4.2
   @nx/eslint     : 17.2.8
   @nx/storybook  : 17.2.8
   typescript     : 5.1.6
```

### Package Manager Version

pnpm@8.13.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by unional** [comment]
Not sure if it is the same. It was from someone else monorepo. What I ended up doing is to setup storybook manually as the version with nx is old.

**Comment by mandarini** [comment]
Oh I see. Then do you think we can close this issue? @unional

**Comment by unional** [comment]
Sure. thx
