### ISSUE TITLE
Component tests fail after @nx/angular:cypress-component-configuration and @nx/cypress:configuration with custom folder

### ISSUE THREAD

**Issue by szacskesz** [nrwl/nx#20965]
### Current Behavior

After adding cypress e2e testing using a custom cypress directory and addding cypress component testing to an angular monorepo, running the generated cypress component tests fails.

### Expected Behavior

The generated tests should pass.

### Steps to Reproduce

1. Create an angular monorepo using: `npx create-nx-workspace@latest app --preset=angular-monorepo --appName=app --name=app --bundler=esbuild --e2eTestRunner=none --ssr=false --style=scss --nxCloud=false  --interactive=false`
2. Added e2e test to created app by: `npx nx g @nx/cypress:configuration --project=app --directory=e2e --jsx=false --setParserOptionsProject=true --interactive=false`
3. Add cypress component testing to created app by: `npx nx g @nx/angular:cypress-component-configuration --project=app --buildTarget=app:build --generateTests=true --interactive=false`
4. Run components tests by: `npx nx run app:component-test`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : win32-x64
   npm    : 10.2.3

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
```

### Failure Logs

```shell
> nx run app:component-test

[7396:0101/220010.167:ERROR:node_bindings.cc(300)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
DevTools listening on ws://127.0.0.1:64559/devtools/browser/d85aebed-bd8a-40dd-b979-593c0f461ff2
- Generating browser application bundles (phase: setup)...
✔ Browser application bundle generation complete.
asset 801.js 11.3 MiB {801} [emitted] (id hint: default)
asset polyfills.js 5.77 MiB {429} [emitted] (name: polyfills)
asset spec-0.js 1000 KiB {135} [emitted] (name: spec-0)
asset cypress-support-file.js 853 KiB {41} [emitted] (name: cypress-support-file)
asset cypress-entry.js 749 KiB {891} [emitted] (name: cypress-entry)
asset styles.js 739 KiB {532} [emitted] (name: styles)
asset 593.js 663 KiB {593} [emitted] (id hint: default)
asset 421.js 81.3 KiB {421} [emitted] (id hint: default)
asset 3rdpartylicenses.txt 30.3 KiB [emitted]
asset runtime.js 28 KiB {666} [emitted] (name: runtime)
asset favicon.ico 14.7 KiB [emitted] [from: apps/app/src/favicon.ico] [copied]
asset spec-1.js 2.58 KiB {208} [emitted] (name: spec-1)
asset styles.css 1.46 KiB {532} [emitted] (name: styles)
asset index.html 645 bytes [emitted]
Entrypoint polyfills 5.8 MiB = runtime.js 28 KiB polyfills.js 5.77 MiB
Entrypoint cypress-entry 777 KiB = runtime.js 28 KiB cypress-entry.js 749 KiB
Entrypoint styles 768 KiB = runtime.js 28 KiB styles.css 1.46 KiB styles.js 739 KiB
chunk {41} (runtime: runtime) cypress-support-file.js (cypress-support-file) 225 KiB
chunk {135} (runtime: runtime) spec-0.js (spec-0) 273 KiB
chunk {208} (runtime: runtime) spec-1.js (spec-1) 370 bytes
chunk {421} (runtime: runtime) 421.js (id hint: default) 30.9 KiB split chunk (cache group: default)
chunk {429} (runtime: runtime) polyfills.js (polyfills) 1.54 MiB [initial]
chunk {532} (runtime: runtime) styles.css, styles.js (styles) 212 KiB (javascript) 79 bytes (css/mini-extract) [initial]
chunk {593} (runtime: runtime) 593.js (id hint: default) 185 KiB split chunk (cache group: default)
chunk {666} (runtime: runtime) runtime.js (runtime) 7.65 KiB [entry]
chunk {801} (runtime: runtime) 801.js (id hint: default) 3.11 MiB split chunk (cache group: default)
chunk {891} (runtime: runtime) cypress-entry.js (cypress-entry) 214 KiB [initial]
ERROR in ./apps/app/cypress/support/component.ts 17:0-20
Module not found: Error: Can't resolve './commands' in 'D:\Projects\nx-issue\ccc\app\apps\app\cypress\support'
2024-01-01 22:00:13: webpack compiled in 1132 ms (8a6f66a1f41603c5)
====================================================================================================
  (Run Starting)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.6.2                                                                         │
  │ Browser:        Electron 114 (headless)                                                        │
  │ Node Version:   v20.10.0 (C:\Programs\nodejs\node.exe)                                         │
  │ Specs:          2 found (app.component.cy.ts, nx-welcome.component.cy.ts)                      │
  │ Searched:       src/**/*.cy.ts, src/**/*.cy.js                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  app.component.cy.ts                                                             (1 of 2)

  1) An uncaught error was detected outside of a test
  0 passing (213ms)
  1 failing
  1) An uncaught error was detected outside of a test:
     Error: The following error originated from your test code, not from Cypress.
  > Cannot find module './commands'
When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
Cypress could not associate this error to any specific test.
We dynamically generated a new test to display this failure.
      at webpackMissingModule (http://localhost:8080/__cypress/src/cypress-support-file.js:12:50)
      at 6507 (http://localhost:8080/__cypress/src/cypress-support-file.js:12:135)
      at Function.__webpack_require__ (http://localhost:8080/__cypress/src/runtime.js:23:42)
      at _ZoneDelegate.invoke (http://localhost:8080/__cypress/src/polyfills.js:8201:158)
      at Zone.run (http://localhost:8080/__cypress/src/polyfills.js:7986:35)
      at <unknown> (http://localhost:8080/__cypress/src/polyfills.js:9061:28)
      at _ZoneDelegate.invokeTask (http://localhost:8080/__cypress/src/polyfills.js:8228:171)
      at Zone.runTask (http://localhost:8080/__cypress/src/polyfills.js:8032:37)
      at drainMicroTaskQueue (http://localhost:8080/__cypress/src/polyfills.js:8399:23)

  (Results)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     app.component.cy.ts                                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
  (Screenshots)
  -  D:\Projects\nx-issue\ccc\app\dist\cypress\apps\app\screenshots\app.component.cy.     (1280x720)
     ts\An uncaught error was detected outside of a test (failed).png
────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  nx-welcome.component.cy.ts                                                      (2 of 2)

  1) An uncaught error was detected outside of a test
  0 passing (114ms)
  1 failing
  1) An uncaught error was detected outside of a test:
     Error: The following error originated from your test code, not from Cypress.
  > Cannot find module './commands'
When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
Cypress could not associate this error to any specific test.
We dynamically generated a new test to display this failure.
      at webpackMissingModule (http://localhost:8080/__cypress/src/cypress-support-file.js:12:50)
      at 6507 (http://localhost:8080/__cypress/src/cypress-support-file.js:12:135)
      at Function.__webpack_require__ (http://localhost:8080/__cypress/src/runtime.js:23:42)
      at _ZoneDelegate.invoke (http://localhost:8080/__cypress/src/polyfills.js:8201:158)
      at Zone.run (http://localhost:8080/__cypress/src/polyfills.js:7986:35)
      at <unknown> (http://localhost:8080/__cypress/src/polyfills.js:9061:28)
      at _ZoneDelegate.invokeTask (http://localhost:8080/__cypress/src/polyfills.js:8228:171)
      at Zone.runTask (http://localhost:8080/__cypress/src/polyfills.js:8032:37)
      at drainMicroTaskQueue (http://localhost:8080/__cypress/src/polyfills.js:8399:23)

  (Results)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     nx-welcome.component.cy.ts                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
  (Screenshots)
  -  D:\Projects\nx-issue\ccc\app\dist\cypress\apps\app\screenshots\nx-welcome.compon     (1280x720)
     ent.cy.ts\An uncaught error was detected outside of a test (failed).png
====================================================================================================
  (Run Finished)
       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ×  app.component.cy.ts                      215ms        1        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ×  nx-welcome.component.cy.ts               115ms        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ×  2 of 2 failed (100%)                     330ms        2        -        2        -        -
                                                                                                                                                                                              
 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Ran target component-test for project app (10s)

    ×    1/1 failed
    √    0/1 succeeded [0 read from cache]
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I intentionally skipped generating the e2e test during the workspace generation, because I do not want a separate e2e application to be made, instead I want it to be under the application as a target.

Please let me know if the mentioned `@nx/angular:cypress-component-configuration` and the `@nx/cypress:configuration` generators should not be used together!

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Those generators are not currently prepared to handle both testing types in the same project. We recommend a separate e2e project (and we generate it like that by default) to achieve fewer affected tasks and more cache hits, but the generators should support the use case. We'll take a look.

**Comment by szacskesz** [comment]
Not stale

**Comment by szacskesz** [comment]
Not stale
