### ISSUE TITLE
nest backend not bundling vendor

### ISSUE THREAD

**Issue by arslan2012** [nrwl/nx#2096]
## Expected Behavior

after running ```ng build api --prod```
main.js in dist/apps/api should work anywhere

## Current Behavior

copying dist/apps/api onto any other location without the node_modules folder
results in an error

```
root@lawyer:~# node /root/lawyer/apps/api/main.js
internal/modules/cjs/loader.js:957
    throw err;
    ^

Error: Cannot find module 'tslib'
Require stack:
- /root/lawyer/apps/api/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/root/lawyer/apps/api/main.js:91:18)
    at __webpack_require__ (/root/lawyer/apps/api/main.js:20:30)
    at Module.<anonymous> (/root/lawyer/apps/api/main.js:1116:63)
    at __webpack_require__ (/root/lawyer/apps/api/main.js:20:30)
    at Object.<anonymous> (/root/lawyer/apps/api/main.js:1107:18)
    at __webpack_require__ (/root/lawyer/apps/api/main.js:20:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/lawyer/apps/api/main.js' ]
}
```

### Steps to Reproduce
<details>
  <summary>create command</summary>

```
 2  ✔  create-nx-workspace                                                                                                      ~/s/bisaibang 
? Workspace name (e.g., org name)     lawyer
? What to create in the new workspace angular-nest      [a workspace with a full stack application (Angular + Nest)]
? Application name                    lawyer
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
new lawyer --preset="angular-nest" --appName="lawyer" --style="scss" --collection=@nrwl/workspace
```
</details>

after running ```ng build api --prod``` i rsync the dist/apps/api folder onto my server, and got above error

Currently I temporarily averted the problem by also rsyncing the node_modules folder onto the server.

### Context

<details>
  <summary>nx report</summary>

```
 4   master  ✘  nx report                                                                                                17s  ~/s/b/lawyer 

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 8.7.1
  @nrwl/cli : 8.7.1
  @nrwl/cypress : 8.7.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.7.1
  @nrwl/linter : 8.7.1
  @nrwl/nest : 8.7.1
  @nrwl/next : Not Found
  @nrwl/node : 8.7.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.7.1
  @nrwl/web : Not Found
  @nrwl/workspace : 8.7.1
  typescript : 3.4.5
```
</details>

## Other
[yarn.lock](https://pastebin.com/cM0G7fbk)

**Comment by arslan2012** [comment]
Close because I found out this is nestjs issue.

**Comment by vincaslt** [comment]
Could you point to the resource or a solution? I'm having this exact problem.

**Comment by arslan2012** [comment]
@vincaslt nest doesn't bundle vendor at all, I fixed it by rsync the whole node_modules folder onto the server
