### ISSUE TITLE
Cannot read properties of undefined (reading 'build')

### ISSUE THREAD

**Issue by harry-uglow** [nrwl/nx#20983]
### Current Behavior

When running `nx run bohr:serve:dev` I receive the following error:

```
>  NX   Cannot read properties of undefined (reading 'build')

TypeError: Cannot read properties of undefined (reading 'build')
    at readTargetOptions (/Users/harry/bohr/node_modules/@nx/devkit/src/executors/read-target-options.js:26:61)
    at getBuildOptions (/Users/harry/bohr/node_modules/@nx/webpack/src/executors/dev-server/dev-server.impl.js:60:57)
    at devServerExecutor (/Users/harry/bohr/node_modules/@nx/webpack/src/executors/dev-server/dev-server.impl.js:18:68)
    at devServerExecutor.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/Users/harry/bohr/node_modules/nx/src/utils/async-iterator.js:13:27)
    at iteratorToProcessStatusCode (/Users/harry/bohr/node_modules/nx/src/command-line/run/run.js:41:94)
    at /Users/harry/bohr/node_modules/nx/src/command-line/run/run.js:154:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/Users/harry/bohr/node_modules/nx/src/utils/params.js:9:16)
    at async process.<anonymous> (/Users/harry/bohr/node_modules/nx/bin/run-executor.js:59:28)
```

The line that fails is in `node_modules/@nx/devkit/src/executors/read-target-options.js` and it is `const targetConfiguration = projectConfiguration.targets[target];` projectConfiguration is set above it by the line:
```
const projectConfiguration = (context.workspace || context.projectsConfigurations).projects[project];
```
I added some logs above and can see that context.workspace is not null so its projects are set as the projectConfiguration, but this is only the config from nx.json:
```
  projects: {
      bohr: { tags: [], root: 'front-end/bohr' },
      'bohr-apis': { tags: [] },
      'bohr-common': { tags: [] },
      'chrome-extension': { tags: [] }
    },
```
It does not include the additional information about the targets that are in the projectConfiguration. Is there something I need to do to get the workspace context to include the additional context provided in the project.json files for each project?

### Expected Behavior

I expect to serve my webpack dev server without error

### Steps to Reproduce

1. I migrated from nx 11.0 to nx 17.2.8, running all migration scripts. This removed my workspace.json and created project.json files.
2. Run `nx run bohr:serve:dev`

### Nx Report

```shell
Node   : 20.10.0
   OS     : darwin-x64
   npm    : 10.2.3
   
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/react          : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Here is my nx.json and project.json...

nx.json
```
{
  "affected": {
    "defaultBase": "master"
  },
  "tasksRunnerOptions": {
    "default": {
      "options": {
        "canTrackAnalytics": false,
        "showUsageWarnings": true
      }
    }
  },
  "projects": {
    "bohr": {
      "tags": [],
      "root": "front-end/bohr"
    },
    "bohr-apis": {
      "tags": []
    },
    "bohr-common": {
      "tags": []
    },
    "chrome-extension": {
      "tags": []
    }
  },
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "sharedGlobals": [
      "{workspaceRoot}/tsconfig.base.json",
      "{workspaceRoot}/babel.config.json",
      "{workspaceRoot}/package.json"
    ],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/src/test-setup.[jt]s"
    ]
  },
  "targetDefaults": {
    "build": {
      "inputs": [
        "production",
        "^production"
      ],
      "cache": true
    },
    "lint": {
      "cache": true
    },
    "@nx/jest:jest": {
      "cache": true,
      "inputs": [
        "default",
        "^production",
        "{workspaceRoot}/jest.preset.js"
      ],
      "options": {
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    }
  },
  "$schema": "./node_modules/nx/schemas/nx-schema.json"
}
```

project.json
```
{
  "name": "bohr",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "front-end/bohr/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nx/webpack:webpack",
      "options": {
        "baseHref": "/dist/",
        "outputPath": "front-end/bohr/dist",
        "tsConfig": "front-end/bohr/tsconfig.app.json",
        "webpackConfig": "@nrwl/react/plugins/webpack",
        "assets": [
          "front-end/bohr/src/assets"
        ],
        "index": "front-end/bohr/src/index.html",
        "main": "front-end/bohr/src/main.tsx",
        "polyfills": "front-end/bohr/src/polyfills.ts",
        "scripts": [],
        "stylePreprocessorOptions": {
          "includePaths": [
            "front-end/bohr/src/styles"
          ]
        }
      },
      "configurations": {
        "production": {
          "budgets": [
            {
              "maximumError": "15mb",
              "maximumWarning": "2mb",
              "type": "initial"
            }
          ],
          "extractCss": true,
          "extractLicenses": true,
          "fileReplacements": [
            {
              "replace": "front-end/bohr/src/environments/environment.ts",
              "with": "front-end/bohr/src/environments/environment.prod.ts"
            }
          ],
          "namedChunks": false,
          "optimization": true,
          "outputHashing": "all",
          "progress": true,
          "showCircularDependencies": false,
          "sourceMap": false,
          "vendorChunk": true,
          "verbose": true
        },
        "analyse": {
          "webpackConfig": "front-end/bohr/webpack.analyse.config.js"
        },
        "dev": {
          "webpackConfig": "front-end/bohr/webpack.dev.config.js"
        }
      }
    },
    "serve": {
      "executor": "@nx/webpack:dev-server",
      "options": {
        "baseHref": "/",
        "hmr": true,
        "historyApiFallback": true,
        "port": 5000,
        "ssl": true
      },
      "configurations": {
        "production": {
          "buildTarget": "bohr:build:production"
        },
        "dev-proxy": {
          "buildTarget": "bohr:build",
          "proxyConfig": "front-end/bohr/proxy.conf.js"
        },
        "dev": {
          "baseHref": "/dist/",
          "buildTarget": "bohr:build:dev",
          "port": 18080,
          "ssl": false
        }
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "options": {
        "lintFilePatterns": [
          "front-end/bohr/**/*.{ts,tsx,js,jsx}"
        ]
      }
    },
    "test": {
      "executor": "@nx/jest:jest",
      "outputs": [
        "{workspaceRoot}/coverage/front-end/bohr"
      ],
      "options": {
        "jestConfig": "front-end/bohr/jest.config.js",
        "maxWorkers": 4,
        "reporters": [
          "default",
          "jest-junit"
        ]
      }
    }
  }
}
```

**Comment by harry-uglow** [comment]
Ok likely this was broken by upgrading from 11 -> 17 directly. I have since tried a more gradual upgrade and things are working better.
