### ISSUE TITLE
Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] and .nx folder created

### ISSUE THREAD

**Issue by andreaSimonePorceddu** [nrwl/nx#21003]
### Current Behavior

Since this morning, I have issues running the `nx` command with no changes to the codebase or dependencies:

- A `.nx` folder is created (file added to the git status because the `.nx` folder is not present in the `.gitignore`.

<img width="256" alt="Screenshot 2024-01-04 alle 14 22 31" src="https://github.com/nrwl/nx/assets/55460313/5f85a967-2518-4dad-baf1-8d25ecda36a3">

- The command fails with this error:
```
Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.
```

I'm using the last 16 version `16.10.0`, node version 18.18.

```json
"@nrwl/js": "16.10.0",
"@nx/cypress": "16.10.0",
"@nx/detox": "16.10.0",
"@nx/eslint-plugin": "16.10.0",
"@nx/jest": "16.10.0",
"@nx/js": "16.10.0",
"@nx/linter": "16.10.0",
"@nx/next": "16.10.0",
"@nx/react": "16.10.0",
"@nx/react-native": "16.10.0",
"@nx/storybook": "16.10.0",
"@nx/web": "16.10.0",
"@nx/webpack": "16.10.0",
"@nx/workspace": "16.10.0",
```

I wonder if it could be related to yesterday's release of the 17 (some common dependencies changed).

### Expected Behavior

No error and nx command successfully executed

### Steps to Reproduce

Run an nx command

### Nx Report

```shell
Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
    at readCachedProjectGraph [90m(/Users/app/[39mnode_modules/[4mnx[24m/src/project-graph/project-graph.js:30:15[90m)[39m
    at run [90m(/Users/app/[39mnode_modules/[4mnx[24m/src/command-line/run/run.js:151:69[90m)[39m
    at process.<anonymous> [90m(/Users/app/[39mnode_modules/[4mnx[24m/bin/run-executor.js:59:48[90m)[39m
[90m    at process.emit (node:events:517:28)[39m
[90m    at emit (node:internal/child_process:944:14)[39m
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)[39m
```

### Failure Logs

```shell
Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
    at readCachedProjectGraph [90m(/Users/app/[39mnode_modules/[4mnx[24m/src/project-graph/project-graph.js:30:15[90m)[39m
    at run [90m(/Users/app/[39mnode_modules/[4mnx[24m/src/command-line/run/run.js:151:69[90m)[39m
    at process.<anonymous> [90m(/Users/app/[39mnode_modules/[4mnx[24m/bin/run-executor.js:59:48[90m)[39m
[90m    at process.emit (node:events:517:28)[39m
[90m    at emit (node:internal/child_process:944:14)[39m
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)[39m
```

### Package Manager Version

1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by andreaSimonePorceddu** [comment]
I managed to fix it by running:
`yarn nx reset`


Closing the issue.

**Comment by andreaSimonePorceddu** [comment]
Sorry, I'm going to reopen this, because, anyway, nx has started to create the .nx folder in the root folder, instead of into the  node_modules folder. I saw that this change should be from 17 version but we are still using the 16.

Any idea about it?

**Comment by andreaSimonePorceddu** [comment]
Sorry, I'm going to reopen this, because, anyway, nx has started to create the .nx folder in the root folder, instead of into the node_modules folder. I saw that this change should be from 17 version but we are still using the 16.

Any idea about it?

**Comment by Erbenos** [comment]
Experience same thing I am not anyhow associated to the issue author.

**Comment by andreaSimonePorceddu** [comment]
@Erbenos when it started?

**Comment by Erbenos** [comment]
Yesterday 10 GMT.

**Comment by andreaSimonePorceddu** [comment]
> Yesterday 10am GMT.
> 
> node -v v16.15.1 npm -v 8.11.0
> 
> Mac
> 
> nx-report all green. Removing all cache folders manually allows commands to pass for a time, but they eventually again degrade to the error you already provided.

The same for me, which nx version are u using?

**Comment by AgentEnder** [comment]
The cache location changed in v17 - if you downgrade to nx 16 you'd need to run `nx reset` potentially to refresh the daemon (and also not have a .nx folder present, as that's picked up and used if its already there in v16+) otherwise it'll be recreated.

Swapping between version 16 + 17 on different braches or similar can thus be a bit messy.

@Erbenos what does `nx report` look like?

**Comment by Erbenos** [comment]
Attached it to https://github.com/nrwl/nx/issues/21003#issuecomment-1877266114. No downgrade never took place as I never were on 17.

**Comment by andreaSimonePorceddu** [comment]
@AgentEnder I never switched from 17 to 16, I always used the 16. I checked the `yarn.lock` and I've no reference to the 17. Do you have some remote reference when launching nx commands?

**Comment by wrenzi** [comment]
I'm experiencing the same scenario. It started happening yesterday.

```
   Node   : 20.10.0
   OS     : darwin-arm64
   yarn   : 1.22.19

   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/plugin         : 16.7.4
   @nx/react          : 16.7.4
   @nx/rollup         : 16.7.4
   @nx/storybook      : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/web            : 16.7.4
   @nx/webpack        : 16.7.4
   nx-cloud           : 16.5.2
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @mands/nx-playwright        : 0.6.2
   @nx-aws-plugin/nx-aws-cache : 3.1.0
```

**Comment by AgentEnder** [comment]
Ah, I think this is due to Nx console using a v17 install of Nx that's not present in the workspace, which creates the .nx folder and then it fails when the default changes over to .nx but there's not expected info in there.

I'm going to transfer this over to the console repo to be worked, I don't have the context to know why console would not be picking up your installation.
