### ISSUE TITLE
Failed unit test for generators after update

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#21063]
### Current Behavior

I have a custom generator that calls applicationGenerator.  I have a unit test for this generator that is now failing in my azure pipelines with an error that performance.mark is not a function.  I tried this in ubuntu, mac and windows vms.  The unit tests passed in version 16.x but fails in 17.x.  The odd things is that I can run it locally just fine.  I am not sure if a breaking change was introduced or if I need to change some sort of config?

### Expected Behavior

Unit tests should pass since there were no "breaking changes" and no code changes on my end.

### Steps to Reproduce

1.  run your application unit test in a vm?

### Nx Report

```shell
Node   : 18.19.0
   OS     : win32-x64
   npm    : 10.2.3

   nx (global)        : 16.5.4
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/plugin         : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ng-bootstrap/ng-bootstrap : 16.0.0
   @ngrx/component-store      : 17.0.1
   @ngrx/effects              : 17.0.1
   @ngrx/entity               : 17.0.1
   @ngrx/router-store         : 17.0.1
   @ngrx/schematics           : 17.0.1
   @ngrx/store                : 17.0.1
   @ngrx/store-devtools       : 17.0.1
   eslint-plugin-ngrx         : 2.1.4
   ngx-toastr                 : 17.0.2
   ---------------------------------------
   Local workspace plugins:
         @clearsight-apps/schematics
```

### Failure Logs

```shell
TypeError: performance.mark is not a function

      at buildProjectsConfigurationsFromProjectPathsAndPlugins (../../node_modules/nx/src/project-graph/utils/project-configuration-utils.js:117:21)
      at createProjectConfigurations (../../node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
      at _retrieveProjectConfigurations (../../node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
      at retrieveProjectConfigurations (../../node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
      at async buildProjectGraphAndSourceMapsWithoutDaemon (../../node_modules/nx/src/project-graph/project-graph.js:71:69)
      at async createProjectGraphAndSourceMapsAsync (../../node_modules/nx/src/project-graph/project-graph.js:136:25)
      at async createProjectGraphAsync (../../node_modules/nx/src/project-graph/project-graph.js:125:39)
      at async configurationGenerator (../../node_modules/@nx/cypress/src/generators/configuration/configuration.js:20:26)
      at async addE2e (../../node_modules/@nx/angular/src/generators/application/lib/add-e2e.js:20:9)
      at async applicationGeneratorInternal (../../node_modules/@nx/angular/src/generators/application/application.js:34:5)
      at async applicationGenerator (../../node_modules/@nx/angular/src/generators/application/application.js:10:12)
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
The jest.config.ts for the plugin project needs to specify `testEnvironment: 'node'`, there were some changes to our generators which now invoke codepaths that require that test environment.

**Comment by jasedwards** [comment]
@AgentEnder  appreciate the quick turnaround
