### ISSUE TITLE
Esbuild application will not build - "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by bavellMTD** [nrwl/nx#21069]
### Current Behavior

When trying to build one of my applications (`nx run media-processor:build  --verbose`), I'm seeing the below error. I have no idea how to trace or debug the root issue. How/where should I troubleshoot?

```
RangeError: Maximum call stack size exceeded
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:22:34)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
```

### Expected Behavior

Application builds successfully

### Steps to Reproduce

Build target in project.json:
```json
"build": {
  "executor": "@nx/esbuild:esbuild",
  "outputs": ["{options.outputPath}"],
  "defaultConfiguration": "production",
  "options": {
    "platform": "node",
    "outputPath": "dist/apps/media-processor",
    "format": ["cjs"],
    "bundle": false,
    "main": "apps/media-processor/src/main.ts",
    "tsConfig": "apps/media-processor/tsconfig.json",
    "generatePackageJson": true,
    "esbuildOptions": {
      "sourcemap": true,
      "outExtension": {
        ".js": ".js"
      }
    }
  },
  "configurations": {
    "development": {},
    "production": {
      "esbuildOptions": {
        "sourcemap": false,
        "outExtension": {
          ".js": ".js"
        }
      }
    }
  }
},
```

tsconfig.json:
```json
{
  "extends": "../../tsconfig.base.json",
  "exclude": ["jest.config.ts", "src/**/*.spec.ts", "src/**/*.test.ts"],
  "include": ["src/**/*.ts", "types.d.ts"],
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "types": ["node"],
    "target": "ES2020"
  }
}
```

src/main.ts:
```typescript

console.log('hello world!')
```

### Nx Report

```shell
Node   : 18.19.0
   OS     : linux-x64
   yarn   : 4.0.2
   
   nx (global)    : 17.1.3
   nx             : 17.2.8
   @nx/js         : 17.2.8
   @nx/jest       : 17.2.8
   @nx/linter     : 17.2.8
   @nx/eslint     : 17.2.8
   @nx/workspace  : 17.2.8
   @nx/cypress    : 17.2.8
   @nx/devkit     : 17.2.8
   @nx/esbuild    : 17.2.8
   @nx/next       : 17.2.8
   @nx/node       : 17.2.8
   @nx/plugin     : 17.2.8
   @nx/react      : 17.2.8
   @nx/rollup     : 17.2.8
   @nrwl/tao      : 17.2.8
   @nx/web        : 17.2.8
   typescript     : 5.3.3
```

### Failure Logs

```shell
RangeError: Maximum call stack size exceeded
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:22:34)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
    at recur (/path/to/project_root/node_modules/@nx/esbuild/src/executors/esbuild/lib/get-extra-dependencies.js:29:13)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by bavellMTD** [comment]
This turned out to be a circular dependency issue, the esbuild project code was importing a lib which had a circular dep on another lib.
