### ISSUE TITLE
@nx/esbuild watch mode does not consider new/deleted files with bundle: false

### ISSUE THREAD

**Issue by twestendorff** [nrwl/nx#21072]
### Current Behavior

If the application is started with esbuild and `bundle: false` in watch mode, everything works as expected. If a file that was previously built is then deleted, the build fails because esbuild can no longer find the deleted file. Something similar happens when adding files. The difference is that esbuild does not consider the new file for compilation. This also applies if the file is imported into a file that was previously already in the scope of watched files.

### Expected Behavior

esbuild should consider new files and not give an error for deleted files. The behavior in watch mode should be comparable to that of plain TSC or Webpack.

### Steps to Reproduce

Error when deleting a file:
1. Serve the application in watch mode
2. Delete a file that was previously in the source folder
=> the change is detected and fails

Error when adding a file:
1. Serve the application in watch mode
2. Add a new file
3. Import the file into a file that was present in step 1
=> esbuild now recompiles => error `Error: Cannot find module './dummy.controller'`

esbuild version: 0.19.5  
Configuration in project.json
```
...
"projectType": "application",
  "targets": {
    "build": {
      "executor": "@nx/esbuild:esbuild",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/api",
        "main": "apps/api/src/main.ts",
        "tsConfig": "apps/api/tsconfig.app.json",
        "platform": "node",
        "format": ["cjs"],
        "bundle": false,
        "sourcemap": true,
        "esbuildOptions": {
          "outExtension": {
            ".js": ".js"
          }
        }
      },
      "configurations": {
        "development": {},
        "production": {
          "generatePackageJson": true
        }
      }
    },
    "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "api:build"
      },
      "configurations": {
        "development": {
          "buildTarget": "api:build:development"
        },
        "production": {
          "buildTarget": "api:build:production"
        }
      }
    },
...
```

### Nx Report

```shell
Node   : 20.10.0
OS     : win32-x64
npm    : 10.2.3

nx (global)        : 17.1.3
nx                 : 17.1.3
@nx/js             : 17.1.3
@nx/jest           : 17.1.3
@nx/linter         : 17.1.3
@nx/eslint         : 17.1.3
@nx/workspace      : 17.1.3
@nx/angular        : 17.1.3
@nx/cypress        : 17.1.3
@nx/devkit         : 17.1.3
@nx/esbuild        : 17.1.3
@nx/eslint-plugin  : 17.1.3
@nx/nest           : 17.1.3
@nx/node           : 17.1.3
@nrwl/tao          : 17.1.3
@nx/web            : 17.1.3
@nx/webpack        : 17.1.3
typescript         : 5.2.2
```

### Failure Logs
Logs for deleting a file:
```shell
> nx run api:serve:development

[ watch ] build succeeded, watching for changes...
Debugger listening on ws://localhost:9229/f5f12701-1890-469c-b058-96f1f2965bed
Debugger listening on ws://localhost:9229/f5f12701-1890-469c-b058-96f1f2965bed
For help, see: https://nodejs.org/en/docs/inspector

🚀 Application is running on: http://localhost:3000/
X [ERROR] Could not resolve "./apps\\api\\src\\app\\dummy.controller.ts"

[ watch ] build finished with errors (see above), watching for changes...
Build failed, waiting for changes to restart...
```
Logs for adding a file:
```shell
> nx run api:serve:development

[ watch ] build succeeded, watching for changes...
Debugger listening on ws://localhost:9229/f809060b-a2da-4c45-8d01-580dc8a3695e
Debugger listening on ws://localhost:9229/f809060b-a2da-4c45-8d01-580dc8a3695e
For help, see: https://nodejs.org/en/docs/inspector

🚀 Application is running on: http://localhost:3000/
[ watch ] build succeeded, watching for changes...
Debugger listening on ws://localhost:9229/4c44618a-923f-4aa0-ac55-d2339f34888a
Debugger listening on ws://localhost:9229/4c44618a-923f-4aa0-ac55-d2339f34888a
For help, see: https://nodejs.org/en/docs/inspector

Error: Cannot find module './dummy.controller'
Require stack:
- D:\git\crm\dist\apps\api\apps\api\src\main.js
- D:\git\crm\dist\apps\api\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.Module._resolveFilename (D:\git\crm\tmp\api\main-with-require-overrides.js:41:36)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.Module._load (D:\git\crm\node_modules\@nx\js\src\executors\node\node-with-require-overrides.js:18:31)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\git\crm\apps\api\src\main.ts:1:22)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)


>  NX  Process exited with code 1, waiting for changes to restart...
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I was able to trace the cause back to the `entryPoints` that are passed to esbuild. 
https://github.com/nrwl/nx/blob/6307a831d91fea6a45d17a0cbe98b24a1e1f445f/packages/esbuild/src/utils/get-entry-points.ts#L53-L58

It seems to me that only the files that are defined via the glob in the tsconfig and are resolved to the appropriate files are taken into account by the watch mode.

https://github.com/nrwl/nx/blob/6307a831d91fea6a45d17a0cbe98b24a1e1f445f/packages/esbuild/src/executors/esbuild/lib/build-esbuild-options.ts#L102-L106

I was also able to reproduce this behavior using esbuild directly by setting the `entryPoints` to a fixed set of source files.

**Comment by twestendorff** [comment]
The issue still exists. Would love to see some comments.
