### ISSUE TITLE
nx export crashing with Next v14

### ISSUE THREAD

**Issue by leoselig** [nrwl/nx#21087]
### Current Behavior

Trying to `nx export <app_name>` an app causes a fatal error. The app is freshly generated via `@nx/next` but I also updated Next.js to v14 because the generator is still outdated.

### Expected Behavior

Export should pass successfully.

### Steps to Reproduce

1. Add `@nx/next` generated app to existing nx repo
2. Update `next` to 14
3. Run `nx export <app_name>`

### Nx Report

```shell
Node   : 18.19.0
   OS     : darwin-x64
   npm    : 10.2.3
   
   nx (global)        : 17.1.3
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/next           : 17.2.8
   @nx/react          : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   typescript         : 5.3.3
```

### Failure Logs

```shell
nx export booking-app --verbose                                                              INT ✘  09:46:10 

> nx run booking-app:export

> nx run booking-app:build:production  [existing outputs match the cache, left as is]
   ▲ Next.js 14.0.4
   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping linting
   Checking validity of types ...
   Collecting page data ...
   Generating static pages (0/5) ...
   Generating static pages (1/5) 
   Generating static pages (2/5) 
   Generating static pages (3/5) 
 ✓ Generating static pages (5/5) 
   Finalizing page optimization ...
   Collecting build traces ...
Route (app)                              Size     First Load JS
┌ ○ /                                    4.49 kB        97.9 kB
├ ○ /_not-found                          866 B          82.8 kB
└ ○ /api/hello                           0 B                0 B
+ First Load JS shared by all            81.9 kB
  ├ chunks/16-8afac2739d8da920.js        26.7 kB
  ├ chunks/1dd3208c-a999c2afcc83b0a6.js  53.3 kB
  ├ chunks/main-app-a94e81e4cb542936.js  220 B
  └ chunks/webpack-b3240fc7efde6ec3.js   1.75 kB
○  (Static)  prerendered as static content
 
 >  NX   Successfully ran target build for project booking-app
   Nx read the output from the cache instead of running the command for 1 out of 1 tasks.
{
  statusMessage: 'Exporting',
  silent: false,
  threads: undefined,
  outdir: 'dist/apps/booking-app/exported'
}
   using build directory: /Users/leoselig/work/tiki/tiki-app/dist/apps/booking-app/.next
   Copying "static build" directory
 >  NX   Cannot read properties of undefined (reading 'app')
TypeError: Cannot read properties of undefined (reading 'app')
    at exportAppImpl (/Users/leoselig/work/tiki/tiki-app/node_modules/next/dist/export/index.js:370:28)
    at async /Users/leoselig/work/tiki/tiki-app/node_modules/next/dist/export/index.js:679:16
    at async Span.traceAsyncFn (/Users/leoselig/work/tiki/tiki-app/node_modules/next/dist/trace/trace.js:147:20)
    at async exportExecutor (/Users/leoselig/work/tiki/tiki-app/node_modules/@nx/next/src/executors/export/export.impl.js:48:5)
    at async promiseToIterator (/Users/leoselig/work/tiki/tiki-app/node_modules/nx/src/command-line/run/run.js:30:11)
    at async getLastValueFromAsyncIterableIterator (/Users/leoselig/work/tiki/tiki-app/node_modules/nx/src/utils/async-iterator.js:13:19)
    at async iteratorToProcessStatusCode (/Users/leoselig/work/tiki/tiki-app/node_modules/nx/src/command-line/run/run.js:41:29)
    at async handleErrors (/Users/leoselig/work/tiki/tiki-app/node_modules/nx/src/utils/params.js:9:16)
    at async process.<anonymous> (/Users/leoselig/work/tiki/tiki-app/node_modules/nx/bin/run-executor.js:59:28)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I'm sure this is caused by the outdated generator code here: https://github.com/jaysoo/nx/blob/21de78f1338e3c510238f55a2e5b31f7a371a858/packages/next/src/executors/export/export.impl.ts#L77
The `options` parameter in `next@14` is supposed to match [`ExportPageInput`](`https://github.com/vercel/next.js/blob/f45a15b621225a4ad3d401e4d3d114dd17647a90/packages/next/src/export/types.ts#L37C18-L37C33`) which now includes the `enabledDirectories` field. This is misssing in the current executor implementation.

**Comment by andrwagn** [comment]
Try changing the output mode to "export": https://nextjs.org/docs/app/building-your-application/deploying/static-exports
Next export is [deprecated](https://nx.dev/nx-api/next/executors/export).

**Comment by airtonix** [comment]
also getting this error: 

```

zenobi.us on git feat/keystatic [x!] via nodejs v18.17.0 took 4s 
x yarn nx export web

> nx run web:export

> nx run web:build:production  [local cache]
   ▲ Next.js 14.0.4
   - Experiments (use at your own risk):
     · typedRoutes
   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping linting
   Checking validity of types ...
   Collecting page data ...
   Generating static pages (0/7) ...
   Generating static pages (1/7) 
   Generating static pages (3/7) 
   Generating static pages (5/7) 
 ✓ Generating static pages (7/7) 
   Finalizing page optimization ...
   Collecting build traces ...
Route (app)                              Size     First Load JS
┌ ○ /                                    1.23 kB        83.4 kB
├ ○ /_not-found                          916 B          83.1 kB
├ ○ /b                                   8.44 kB         104 kB
├ λ /b/[slug]                            1.69 kB        97.4 kB
├ ○ /me                                  1.6 kB         92.3 kB
└ λ /p/[...slug]                         1.6 kB         92.3 kB
+ First Load JS shared by all            82.2 kB
  ├ chunks/1dd3208c-db9eec636a334a07.js  53.3 kB
  ├ chunks/53-c94516c07b251f7e.js        26.7 kB
  ├ chunks/main-app-b7bee2021889a694.js  267 B
  └ chunks/webpack-8264f9b8b11b3751.js   1.87 kB
○  (Static)   prerendered as static content
λ  (Dynamic)  server-rendered on demand using Node.js
 
 >  NX   Successfully ran target build for project web
   Nx read the output from the cache instead of running the command for 1 out of 1 tasks.
   using build directory: /mnt/Store/Projects/Mine/Github/zenobi.us/dist/apps/web/.next
   Copying "static build" directory
 >  NX   Cannot read properties of undefined (reading 'app')
   Pass --verbose to see the stacktrace.

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target export for project web (2s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
```

**Comment by airtonix** [comment]
meh didn't see the response.

**Comment by leoselig** [comment]
> Try changing the output mode to "export": https://nextjs.org/docs/app/building-your-application/deploying/static-exports
> 
> Next export is [deprecated](https://nx.dev/nx-api/next/executors/export). 

@andrwagn Unless I'm missing something here, this isn't something I should need to do. The `nx export` implementation by @nx/next is incorrect imo.
I would agree if I was running `next export`

**Comment by andrwagn** [comment]
Yes - would also expect that the nx cli would just tell me that this is deprecated, just like other libraries do it. Or show a warnung when i migrate nx to a newer version that deprecated methodes I use.

**Comment by airtonix** [comment]
this is often a thing i experience about nx.dev... new things on major releases are always half baked.

**Comment by ndcunningham** [comment]
Hi! Thanks for reporting this issue
This scenario was addressed about a month ago but since the team was on holiday the release was pushed back till today
- https://github.com/nrwl/nx/releases/tag/17.3.0
- PR: https://github.com/nrwl/nx/pull/20703

@leoselig your the generated app was using `nextjs` 13+ where the imported `export` was available from `nextjs` package.
Since you updated your `nextjs` version (which is fine) the API changed which resulted in the error.

The PR above now checks your `nextjs` version that you have installed and throws an error if you are at or above next 14.

Moving forward, if you want to use `export` you would declare it in your `next.config.js`  

Sorry, for the late response.

**Comment by leoselig** [comment]
No worries, thanks for the thorough explanation. Hope you had a refreshing time off! :)
