### ISSUE TITLE
TypeError: (0 , package_json_workspaces_1.getGlobPatternsFromPackageManagerWorkspaces) is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by GoGoris** [nrwl/nx#21164]
### Current Behavior

Starting from nx 17.0.0 readProjectConfiguration from @nx/devkit throws package_json_workspaces_1.getGlobPatternsFromPackageManagerWorkspaces is undefined.
TypeError: (0 , package_json_workspaces_1.getGlobPatternsFromPackageManagerWorkspaces) is not a function or its return value is not iterable

### Expected Behavior

readProjectConfiguration does not throw.

### Steps to Reproduce

1.
```typescript
import { readProjectConfiguration, Tree } from '@nx/devkit';
import { createTreeWithEmptyWorkspace } from '@nx/devkit/testing';

   it('should run successfully', async () => {
    const appTree = createTreeWithEmptyWorkspace();
    //we add a test project configuration here
    const config = readProjectConfiguration(appTree, 'test');

    expect(config).toBeDefined();
  });
```

package.json
`{
...
  "dependencies": {
...
    "@nx/devkit": "17.2.8",
    "@nx/workspace": "17.2.8",
    "nx": "17.2.8"
  }
}
`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx                      : 17.0.0
   @nx/js                  : 17.0.0
   @nx/jest                : 17.0.0
   @nx/linter              : 17.0.0
   @nx/eslint              : 17.0.0
   @nx/workspace           : 17.0.0
   @nx/devkit              : 17.0.0
   @nrwl/eslint-plugin-nx  : 17.0.0
   @nx/node                : 17.0.0
   @nx/plugin              : 17.0.0
   @nrwl/tao               : 17.0.0
   @nx/web                 : 17.0.0
   typescript              : 5.0.4
   ---------------------------------------
   Community plugins:
   @diogovcs/stryker-mutator : 0.2.6
   @jscutlery/semver         : 4.0.0
   ---------------------------------------
   Local workspace plugins:
         @integration/serverless-helpers
         @integration/generators
```

### Failure Logs

```shell
TypeError: (0 , package_json_workspaces_1.getGlobPatternsFromPackageManagerWorkspaces) is not a function or its return value is not iterable

      24 |   it('should run successfully', async () => {
      25 |     await generator(appTree, options);
    > 26 |     const config = readProjectConfiguration(appTree, 'test');
         |                                            ^
      27 |
      28 |     expect(config).toBeDefined();
      29 |   });

      at readAndCombineAllProjectConfigurations (../../node_modules/nx/src/generators/utils/project-configuration.js:133:86)
      at readProjectConfiguration (../../node_modules/nx/src/generators/utils/project-configuration.js:90:25)
      at Object.<anonymous> (src/generators/app/generator.spec.ts:26:44)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I tested that nx 16.10.0 still works but starting from version 17.0.0 readProjectConfiguration no longer works.
I also tested with 2 completely identical setups with the only difference being the @nx versions to exclude that the problem is caused by one of the nx migrations or by other dependencies.

**Comment by AgentEnder** [comment]
If I was to hazard a guess, I would say that its likely that there is an outdated version of @nx/devkit or nx lurking in node modules and being resolved in correctly. `npm ls @nx/devkit` and `npm ls nx` may be helpful to diagnose this.
