### ISSUE TITLE
Unable to create a new workspace following the getting started guide

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#2122]
I have been a nx user since the early days.  I have been just manually upgrading the dependency versions to keep my project up-to-date.

But when I tried to start from scratch and followed the current getting started guide at https://nx.dev/angular/getting-started/getting-started, I couldn't set up a workspace:

I am on MacOS 10.14.6

I do:

```
cd ~
mkdir nx-temp
cd nx-temp/
npx create-nx-workspace@latest myworkspace
```

I get:

```
An unhandled exception occurred: Cannot find module 'typescript'
See "/private/var/folders/nv/41ynbnt10rzbwghx57xg108h0000gq/T/ng-mIOuPl/angular-errors.log" for further details.
```
The log file:
```
[error] Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
...
```
I search issues regarding "Cannont find module 'typescript', all the issues have been closed.  I follow all the possible troubleshooting suggestions but I am still stuck at the same error.

Here are my globally installed npm packages
```
├── @angular/cli@8.3.19
├── @nrwl/cli@8.8.3
├── express@4.17.1
├── express-generator@4.16.1
├── http-server@0.11.1
├── npm@6.9.0
└── webdriver-manager@12.1.6
```
And I do see typescript folder inside the temp folder:
```
/var/folders/nv/41ynbnt10rzbwghx57xg108h0000gq/T/tmp-49740F26RJ2pnh6ia/node_modules/typescript
```

**Comment by dereklin** [comment]
same problem with
```
npx --ignore-existing create-nx-workspace@latest myworkspace
```

**Comment by dereklin** [comment]
Adding @nrwl/workspace into a new angular cli project produces the same problem:

**Comment by dereklin** [comment]
npm i typescript did the trick...
