### ISSUE TITLE
TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

### ISSUE THREAD

**Issue by josesaranda** [nrwl/nx#2125]
- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Make e2e tests

## Current Behavior

Failure with the following error:
TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

## Failure Information (for bugs)

It seems to be something when running e2e cypress test with a react project

### Steps to Reproduce

npm run e2e react-app-e2e

### Context

- version of Nx used 8.6.0

### Failure Logs

```
TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.exports.subscribeTo (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/util/subscribeTo.js:29:15)
    at Object.subscribeToResult (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/util/subscribeToResult.js:14:26)
    at SwitchMapSubscriber._innerSub (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapSubscriber._next (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapSubscriber._next (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Object.complete (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/observable/forkJoin.js:57:40)
    at Object.wrappedComplete (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/Subscriber.js:188:76)
    at SafeSubscriber.__tryOrUnsub (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.complete (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/Subscriber.js:190:26)
    at Subscriber._complete (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/Subscriber.js:96:26)
    at Subscriber.complete (/Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/Subscriber.js:78:18)
    at /Users/jose.sanchez/Documents/shapeletsProjects/@shapelets-cristal-ui/node_modules/rxjs/internal/util/subscribeToPromise.js:8:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by kpaxton** [comment]
I am also receiving this error with the latest NX and latest Angular CLI. Trying to get storybook to run.
`nx run libname:storybook`

**Comment by mlc-mlapis** [comment]
I have exactly the same problem. The command like `nx run liba:storybook` leads to the error message `An unhandled exception occurred: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.`.

Environment:
* "@nrwl/angular": "8.8.3"
* "rxjs": "6.5.3"
* "@angular/core": "8.2.14"
* "@angular/cli": "8.3.20"

**Comment by vsavkin** [comment]
This is because your workspace has multiple versions of RxJS. RxJS version 1 doesn't recognize observable from RxJS version 2. If you are using Yarn, you can tell Yarn to use one version of RxJS. The easier way to do with NPM is to delete every other version of RxJS except the root one.

There is a workaround with setting a special symbol that resolves it, but i can only apply it to the builders we own.

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/nx/pull/2130

**Comment by kpaxton** [comment]
> This is because your workspace has multiple versions of RxJS. RxJS version 1 doesn't recognize observable from RxJS version 2. If you are using Yarn, you can tell Yarn to use one version of RxJS. The easier way to do with NPM is to delete every other version of RxJS except the root one.

My projects seems to have `rxjs@5.5.12` installed under `cypress@3.4.1 > listr@0.12.0`. But that is a direct dependency of `listr`. So I'm not quite sure how to delete that one without other things breaking.

Thanks for the quick fix though.

**Comment by oak-wildwood** [comment]
> > This is because your workspace has multiple versions of RxJS. RxJS version 1 doesn't recognize observable from RxJS version 2. If you are using Yarn, you can tell Yarn to use one version of RxJS. The easier way to do with NPM is to delete every other version of RxJS except the root one.
> 
> My projects seems to have `rxjs@5.5.12` installed under `cypress@3.4.1 > listr@0.12.0`. But that is a direct dependency of `listr`. So I'm not quite sure how to delete that one without other things breaking.
> 
> Thanks for the quick fix though.

@kpaxton - Did you figure out a workaround? I don't really understand why this fix isn't working for me. I'm running nx 9.4.5 so I think it should be included. Currently I see `rxjs@5.5.12` installed by `cypress@3.8.3 > listr@0.12.0`. Seeing as this version of Cypress is included in by nx cli I don't see how this ever worked for anyone.

**Comment by gerhartz** [comment]
For anyone else struggling with this check your component's import statements for RXJS. My IDE had imported Subject from `rxjs/internal/Subject` instead of what it should have been from `rxjs`

Fixing the RXJS import statements fixed this error for me
