### ISSUE TITLE
@nx/next:custom-server generates .swcrc/.swcrc instead of .swcrc only

### ISSUE THREAD

**Issue by stomvi** [nrwl/nx#21481]
### Current Behavior

@nx/next:custom-server generates apps/[project]/.swcrc/.swcrc instead of .swcrc only. This will cause an `EISDIR: illegal operation on a directory` error while running `npx nx serve xxx`.

### Expected Behavior

Should generate `.swcrc` file only.

### Steps to Reproduce

1. npx create-nx-workspace test --preset=next --appName=www --nextAppDir=true --nextSrcDir=false --nxCloud=skip --style=scss --e2eTestRunner=cypress
2. cd test
3. npx nx g @nx/next:custom-server --project=www --compiler=swc 

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   npm    : 10.2.3

   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/next           : 17.3.1
   @nx/react          : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/web            : 17.3.1
   typescript         : 5.3.3
```

### Failure Logs

```shell
$ npx nx serve www

> nx run www:serve:development

node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: EISDIR: illegal operation on a directory, read
    at readFileSync (node:fs:453:20)
    at readJsonFile (test/node_modules/nx/src/utils/fileutils.js:17:43)
    at getHelperDependency (test/node_modules/@nx/js/src/utils/compiler-helper-dependency.js:49:58)
    at swcExecutor (test/node_modules/@nx/js/src/executors/swc/swc.impl.js:72:86)
    at swcExecutor.next (<anonymous>)
    at test/node_modules/@nx/js/src/executors/node/node.impl.js:191:44
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}

Node.js v20.10.0

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project www failed

   Failed tasks:

   - www:serve:development

   Hint: run the command with --verbose for more details.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
This should be addressed with: https://github.com/nrwl/nx/pull/21736
