### ISSUE TITLE
NX daemon file watcher crashes when running pnpm (8.15.0) install

### ISSUE THREAD

**Issue by rstf** [nrwl/nx#21492]
### Current Behavior

When upgrading pnpm from version 8.6.11 to 8.15.0, we noticed that the NX daemon's file watcher crashes pretty horribly and stop watching for file changes.

The error specifically occurs with the error `there should always be a path` on https://github.com/nrwl/nx/blob/65ba819019771d41ed88b568f171bc1f5bb8346f/packages/nx/src/native/watch/types.rs#L58

Daemon logs:
```
[NX Daemon Server] - 2024-02-01T16:51:54.394Z - Started listening on: /tmp/c7f795775c15028cc2de/d.sock
[NX Daemon Server] - 2024-02-01T16:51:54.395Z - [WATCHER]: Subscribed to changes within: /path/to/ui/repo/obscured (native)
[NX Daemon Server] - 2024-02-01T16:51:54.403Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-02-01T16:51:54.404Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2024-02-01T16:52:03.970Z - [WATCHER]: _tmp_173209_921131433b2bb9c1d1249e373e0c020f was deleted
[NX Daemon Server] - 2024-02-01T16:52:03.971Z - [WATCHER]: Processing file changes in outputs
[NX Daemon Server] - 2024-02-01T16:52:04.072Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX Daemon Server] - 2024-02-01T16:52:04.072Z - [REQUEST]: 
[NX Daemon Server] - 2024-02-01T16:52:04.073Z - [REQUEST]: _tmp_173209_921131433b2bb9c1d1249e373e0c020f
[NX Daemon Server] - 2024-02-01T16:52:06.217Z - Time taken for 'hash changed files from watcher' 0.6440689973533154ms
thread '<unnamed>' panicked at packages/nx/src/native/watch/types.rs:58:41:
there should always be a path
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'thread 'thread '<unnamed><unnamed>thread 'thread 'thread '<unnamed><unnamed>' panicked at thread '' panicked at <unnamed><unnamed>' panicked at packages/nx/src/native/watch/types.rs:<unnamed>' panicked at ' panicked at packages/nx/src/native/watch/types.rs<unnamed>packages/nx/src/native/watch/types.rs' panicked at 58:41' panicked at packages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rs:' panicked at :packages/nx/src/native/watch/types.rs:
there should always be a path
packages/nx/src/native/watch/types.rs::58packages/nx/src/native/watch/types.rs58::5858:41::58:41:
there should always be a path
58:::
there should always be a path5841:4141
::
41:
:
41there should always be a path
:
there should always be a paththere should always be a path:
there should always be a path

there should always be a path

thread '<unnamed>' panicked at packages/nx/src/native/watch/types.rs:58:41:
there should always be a path
thread 'thread 'thread 'thread 'thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed><unnamed><unnamed><unnamed><unnamed><unnamed>' panicked at ' panicked at ' panicked at ' panicked at ' panicked at ' panicked at ' panicked at ' panicked at packages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rs:packages/nx/src/native/watch/types.rs::::::58:585858585858:58::::::41:414141414141:
41:
:
:
:
:
:
there should always be a path:
there should always be a paththere should always be a paththere should always be a paththere should always be a paththere should always be a paththere should always be a path
there should always be a path
```

Not sure what is causing this though. We never had this issue in pnpm 8.6.11. The only thing noticeable is that pnpm creates a temp file (like ` _tmp_173209_921131433b2bb9c1d1249e373e0c020f` above) and deletes it after. It has the same behaviour as 8.15.0. The only guess we have is that it's probably some really unfortunate timing between creation and deletion in the newer version perhaps?

This is running pnpm install with no changes to the lock file.

### Expected Behavior

When running pnpm install, expect the NX daemon file watcher to not crash and continue watching for file changes to perform new hash calculations. This has caused stale files from cache to be used as modified files after the crash do not have updated hashes.

### Steps to Reproduce

1. npx nx reset && npx nx daemon --start # start a clean daemon
2. /opt/pnpm/pnpm install # run install on an unchanged package.json and subsequently unchanged pnpm-lock.yaml
3. Check daemon logs for the crash

### Nx Report

```shell
Node   : 20.10.0
   OS     : linux-x64
   pnpm   : 7.29.3
   
   nx                 : 17.3.0
   @nx/js             : 17.3.0
   @nrwl/js           : 15.8.7
   @nx/jest           : 17.3.0
   @nrwl/jest         : 15.8.7
   @nx/linter         : 17.3.0
   @nx/eslint         : 17.3.0
   @nrwl/linter       : 15.8.7
   @nx/workspace      : 17.3.0
   @nrwl/workspace    : 15.8.7
   @nx/cypress        : 17.3.0
   @nx/devkit         : 17.3.0
   @nx/esbuild        : 17.3.0
   @nx/eslint-plugin  : 17.3.0
   @nx/node           : 17.3.0
   @nx/react          : 17.3.0
   @nrwl/react        : 15.8.7
   @nx/rollup         : 17.3.0
   @nx/storybook      : 17.3.0
   @nrwl/storybook    : 15.8.7
   @nrwl/tao          : 17.3.0
   @nx/web            : 17.3.0
   @nrwl/web          : 15.8.7
   @nx/webpack        : 17.3.0
   @nrwl/webpack      : 15.8.7
   typescript         : 5.1.6
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/js@15.8.7
     - @nrwl/jest@15.8.7
     - @nrwl/linter@15.8.7
     - @nrwl/workspace@15.8.7
     - @nrwl/react@15.8.7
     - @nrwl/storybook@15.8.7
     - @nrwl/web@15.8.7
     - @nrwl/webpack@15.8.7
   
   To fix this, run `nx migrate nx@17.3.0`
```

### Failure Logs

```shell
[NX Daemon Server] - 2024-02-01T16:51:54.394Z - Started listening on: /tmp/c7f795775c15028cc2de/d.sock
[NX Daemon Server] - 2024-02-01T16:51:54.395Z - [WATCHER]: Subscribed to changes within:  /path/to/ui/repo/obscured (native)
[NX Daemon Server] - 2024-02-01T16:51:54.403Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-02-01T16:51:54.404Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2024-02-01T16:52:03.970Z - [WATCHER]: _tmp_173209_921131433b2bb9c1d1249e373e0c020f was deleted
[NX Daemon Server] - 2024-02-01T16:52:03.971Z - [WATCHER]: Processing file changes in outputs
[NX Daemon Server] - 2024-02-01T16:52:04.072Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX Daemon Server] - 2024-02-01T16:52:04.072Z - [REQUEST]: 
[NX Daemon Server] - 2024-02-01T16:52:04.073Z - [REQUEST]: _tmp_173209_921131433b2bb9c1d1249e373e0c020f
[NX Daemon Server] - 2024-02-01T16:52:06.217Z - Time taken for 'hash changed files from watcher' 0.6440689973533154ms
thread '<unnamed>' panicked at packages/nx/src/native/watch/types.rs:58:41:
there should always be a path
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'thread 'thread '<unnamed><unnamed>thread 'thread 'thread '<unnamed><unnamed>' panicked at thread '' panicked at <unnamed><unnamed>' panicked at packages/nx/src/native/watch/types.rs:<unnamed>' panicked at ' panicked at packages/nx/src/native/watch/types.rs<unnamed>packages/nx/src/native/watch/types.rs' panicked at 58:41' panicked at packages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rs:' panicked at :packages/nx/src/native/watch/types.rs:
there should always be a path
packages/nx/src/native/watch/types.rs::58packages/nx/src/native/watch/types.rs58::5858:41::58:41:
there should always be a path
58:::
there should always be a path5841:4141
::
41:
:
41there should always be a path
:
there should always be a paththere should always be a path:
there should always be a path

there should always be a path

thread '<unnamed>' panicked at packages/nx/src/native/watch/types.rs:58:41:
there should always be a path
thread 'thread 'thread 'thread 'thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed><unnamed><unnamed><unnamed><unnamed><unnamed>' panicked at ' panicked at ' panicked at ' panicked at ' panicked at ' panicked at ' panicked at ' panicked at packages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rspackages/nx/src/native/watch/types.rs:packages/nx/src/native/watch/types.rs::::::58:585858585858:58::::::41:414141414141:
41:
:
:
:
:
:
there should always be a path:
there should always be a paththere should always be a paththere should always be a paththere should always be a paththere should always be a paththere should always be a path
there should always be a path
```

### Package Manager Version

PNPM 8.15.0

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jeffbcross** [comment]
@FrozenPandaz is it possible this issue would've been resolved by other recent work with the Daemon?
