### ISSUE TITLE
indexHtmlTransformer not working with @nx/angular:application executor

### ISSUE THREAD

**Issue by atsjo** [nrwl/nx#21518]
### Current Behavior

adding indexHtmlTransformer fails schema validation when serving or building angular application

### Expected Behavior

indexHtmlTransformer  works

### Steps to Reproduce

1. add indexHtmlTransformer in angular project with @nx/angular:application
2. serve or build

### Nx Report

```shell
Node   : 20.11.0
   OS     : win32-x64
   pnpm   : 8.15.1

   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/angular        : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/esbuild        : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   angular-calendar : 0.31.0
```

### Failure Logs

```shell
Error: Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(indexHtmlTransformer).
    at name (C:\Users\atles\source\repos\teve-no\task4s\node_modules\.pnpm\@angular-devkit+architect@0.1701.2\node_modules\@angular-devkit\architect\src\architect.js:227:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by atsjo** [comment]
nx 18 works for build with an mjs transformer file, but serve fails with error below (it seems to treat it like cjs): 
```
export default (indexHtml) => indexHtml.replaceAll('{timestamp}', new Date().toISOString());
^^^^^^SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._compile (D:\repos\teve-no\task4s\node_modules\.pnpm\pirates@4.0.6\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .mjs] (D:\repos\teve-no\task4s\node_modules\.pnpm\pirates@4.0.6\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.require (D:\repos\teve-no\task4s\node_modules\.pnpm\nx@18.0.0_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\adapter\compat.js:63:40)
```
