### ISSUE TITLE
@nrwl/node v8.8.0 breaks nest app

### ISSUE THREAD

**Issue by pf1gura** [nrwl/nx#2153]
## Expected Behavior
My Nest.js apps can run without any issues

## Current Behavior
Nest.js apps fail to start or build.

## Failure Information (for bugs)
It started to happen after an upgrade to 8.8.0. Everything works as expected when I downgrade `@nrwl/node` to 8.7.1.

I am getting an error: `An unhandled exception occurred: Cannot assign to read only property '_showWarnings' of object '#<Object>'`

### Context
I even commented out my whole entry `main.js` file and the issue doesn't disappear.

#### nx report
```
  @nrwl/angular : 8.9.0
  @nrwl/cli : 8.9.0
  @nrwl/cypress : 8.9.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.9.0
  @nrwl/linter : 8.8.0
  @nrwl/nest : 8.9.0
  @nrwl/next : Not Found
  @nrwl/node : 8.8.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 8.9.0
  typescript : 3.4.5
```

### Failure Logs
```
[error] TypeError: Cannot assign to read only property '_showWarnings' of object '#<Object>'
    at TapSubscriber._tapNext (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\json\schema\visitor.js:56:210)
    at TapSubscriber._next (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\operators\tap.js:59:27)
    at TapSubscriber.Subscriber.next (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\Subscriber.js:66:18)
    at C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\operators\mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\operators\mergeMap.js:76:14)
    at MergeMapSubscriber._next (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\observable\scalar.js:6:20)
    at Observable._trySubscribe (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\Observable.js:30:22)
    at MergeMapOperator.call (C:\Users\pf1gura\Projects\Admin-Panel\node_modules\rxjs\internal\operators\mergeMap.js:39:23)
```

**Comment by pf1gura** [comment]
I was debugging the issue a bit more and I fixed the issue by upgrading some other dependencies (all changes on the screenshot). 
![image](https://user-images.githubusercontent.com/41795518/70271799-67ff8e00-17a7-11ea-980e-1b0e1a99a5cc.png)

**Comment by FrozenPandaz** [comment]
Thank you for reporting this issue.

The update to `@angular/cli` is what fixed it. I made a PR to fix the migration version.
