### ISSUE TITLE
NX 18 generate react host broken, can't find module-federation.config.ts

### ISSUE THREAD

**Issue by Aubrey-Russell** [nrwl/nx#21633]
### Current Behavior

It gets this error which says it can't find module-federation.config.ts for some reason. 

 >  NX   Could not load C:\Users\blah\source\repos\blah\blah\apps\test-fed\module-federation.config.ts. Was this project generated with "@nx/react:host"?   See: https://nx.dev/concepts/more-concepts/faster-builds-with-module-federationError: Could not load C:\Users\blah\source\repos\blah\blah\apps\test-fed\module-federation.config.ts. Was this project generated with "@nx/react:host"?
See: https://nx.dev/concepts/more-concepts/faster-builds-with-module-federation
    at getModuleFederationConfig (C:\Users\blah\source\repos\blah\blah\node_modules\.pnpm\@nx+webpack@18.0.1_@swc-node+register@1.8.0_@swc+core@1.4.0_@types+node@20.11.16_nx@18.0.1_typescript@5.3.3\node_modules\@nx\webpack\src\utils\module-federation\get-remotes-for-host.js:85:15)
    at moduleFederationDevServer (C:\Users\blah\source\repos\blah\blah\node_modules\.pnpm\@nx+react@18.0.1_@swc-node+register@1.8.0_@swc+core@1.4.0_@types+node@20.11.16_nx@18.0.1_typescript@5.3.3\node_modules\@nx\react\src\executors\module-federation-dev-server\module-federation-dev-server.impl.js:138:86)
    at moduleFederationDevServer.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (C:\Users\blah\source\repos\blah\blah\NODE_M~1\PNPM~1\NX@180~1.0\NODE_M~1\nx\src\utils\async-iterator.js:13:27)
    at iteratorToProcessStatusCode (C:\Users\blah\source\repos\blah\blah\NODE_M~1\PNPM~1\NX@180~1.0\NODE_M~1\nx\src\command-line\run\run.js:43:94)
    at C:\Users\blah\source\repos\blah\blah\NODE_M~1\PNPM~1\NX@180~1.0\NODE_M~1\nx\src\command-line\run\run.js:169:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handleErrors (C:\Users\blah\source\repos\blah\blah\NODE_M~1\PNPM~1\NX@180~1.0\NODE_M~1\nx\src\utils\params.js:9:16)
    at process.<anonymous> (C:\Users\blah\source\repos\blah\blah\NODE_M~1\PNPM~1\NX@180~1.0\NODE_M~1\nx\bin\run-executor.js:59:28)

### Expected Behavior

Generate should work on start and be able to find module-federation.config.ts which is right there in the file structure

### Steps to Reproduce

1. From nx console use generate command and select create react host
2. input required name information and dir path
3. try to serve the new host

### Nx Report

```shell
Node   : 21.1.0
   OS     : win32-x64
   pnpm   : 8.14.2

   nx                 : 18.0.1
   @nx/js             : 18.0.1
   @nx/jest           : 18.0.1
   @nx/linter         : 18.0.1
   @nx/eslint         : 18.0.1
   @nx/workspace      : 18.0.1
   @nx/cypress        : 18.0.1
   @nx/devkit         : 18.0.1
   @nx/eslint-plugin  : 18.0.1
   @nx/react          : 18.0.1
   @nrwl/tao          : 18.0.1
   @nx/web            : 18.0.1
   @nx/webpack        : 18.0.1
   typescript         : 5.3.3
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by pmieszczak** [comment]
any updates?

**Comment by tommck** [comment]
This is definitely not a good error message since the error is pointing to a file that exists. It would be really nice if we could get a real error message for this :(

**Comment by etylsarin** [comment]
Having the same issue, nx v17.3.2 on Ubuntu

**Comment by ndcunningham** [comment]
Hey! Thanks for filling out this issues.

We were aware of this issue and they have been fixed. Can you update your nx version to the latest?

Thanks! 
Feel free to reopen if the issue is still existing with a small reproduction.
