### ISSUE TITLE
ng-packagr-lite throws when validating https json schema

### ISSUE THREAD

**Issue by marleypowell** [nrwl/nx#21636]
### Current Behavior

After this #19534 PR `ng-packagr-lite` seems to be playing up when running storybook against a buildable angular lib. (`yarn nx storybook <project>`)

```
Error: no schema with key or ref "https://json-schema.org/schema"
    at Ajv.validate (C:\repo\node_modules\ajv\lib\core.ts:359:21)
    at Ajv.validateSchema (C:\repo\node_modules\ajv\lib\core.ts:515:24)
    at Ajv._addSchema (C:\repo\node_modules\ajv\lib\core.ts:721:30)
    at Ajv.compile (C:\repo\node_modules\ajv\lib\core.ts:384:22)
    at CoreSchemaRegistry._compile (C:\repo\node_modules\@angular-devkit\core\src\json\schema\registry.js:246:35)
    at CoreSchemaRegistry.compile (C:\repo\node_modules\@angular-devkit\core\src\json\schema\registry.js:231:37)
    at name (C:\repo\node_modules\@angular-devkit\architect\src\architect.js:224:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

![image](https://github.com/nrwl/nx/assets/55280588/39264486-c536-43b4-8f51-1f5cfe2638b5)

This is the schema it doesn't like - https://github.com/beeman/nx/blob/65c448727d2b6b00fea27f7f374989712cff8cec/packages/angular/src/executors/ng-packagr-lite/schema.json

![image](https://github.com/nrwl/nx/assets/55280588/43f69dd0-c3bc-4270-bca6-70321d67ad87)

### Expected Behavior

`yarn nx storybook <project>` run without any errors.

### GitHub Repo

https://github.com/mandarini/storybook-nx-17.3.1

### Steps to Reproduce

1. Create a buildable lib and point the storybook browser target to `build` instead of `build-storybook`.
2. Run `yarn nx storybook <project>`

### Nx Report

```shell
Node   : 18.18.2
   OS     : win32-x64
   yarn   : 1.22.19
   
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/angular        : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/plugin         : 17.3.1
   @nx/storybook      : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @nx-dotnet/core              : 2.2.0
   @storybook/angular           : 7.6.12
   @trumbitta/nx-plugin-openapi : 1.12.1
   ng-mocks                     : 14.12.1
   ---------------------------------------
```

### Failure Logs

```shell
Error: no schema with key or ref "https://json-schema.org/schema"
    at Ajv.validate (C:\repo\node_modules\ajv\lib\core.ts:359:21)
    at Ajv.validateSchema (C:\repo\node_modules\ajv\lib\core.ts:515:24)
    at Ajv._addSchema (C:\repo\node_modules\ajv\lib\core.ts:721:30)
    at Ajv.compile (C:\repo\node_modules\ajv\lib\core.ts:384:22)
    at CoreSchemaRegistry._compile (C:\repo\node_modules\@angular-devkit\core\src\json\schema\registry.js:246:35)
    at CoreSchemaRegistry.compile (C:\repo\node_modules\@angular-devkit\core\src\json\schema\registry.js:231:37)
    at name (C:\repo\node_modules\@angular-devkit\architect\src\architect.js:224:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

More discussion can be found in this thread https://github.com/nrwl/nx/pull/19534#issuecomment-1923927546.

**Comment by mandarini** [comment]
@marleypowell thanks for filing this issue.

Yeah, it's a known issue that `@nx/angular:ng-packagr-lite` does not support `build`, so we have to use `build-storybook`, so this is why we generate with `build-storybook` instead of `storybook` in the first place:

https://github.com/nrwl/nx/blob/master/packages/storybook/src/utils/utilities.ts#L161

I will add a note about this in the docs!

**Comment by mandarini** [comment]
Hmm @marleypowell I just remembered that we do write this in the docs: https://nx.dev/deprecated/storybook/angular-browser-target#setting-up

_"If your project is buildable (it has a build target, and uses the main Angular builder - @angular-devkit/build-angular:browser) the browserTarget for Storybook will use the build target"_

I will add the update these docs and make them more prominent!
