### ISSUE TITLE
nx release --first-release crashes when 2 git repos were merged

### ISSUE THREAD

**Issue by freakness** [nrwl/nx#21649]
### Current Behavior

When I run `nx release --first-release --dry-run --verbose` in my repository the command crashes. See below for logs.

Important to note is that I setup my repository by merging in another repo with `git merge --allow-unrelated-histories`. The first commit that is being searched is thus not one but two commits. The output from `git rev-list --max-parents=0 HEAD` has 2 lines.

### Expected Behavior

The command works without crashing and does a dry-run release

### Steps to Reproduce

1. Create an empty nx enabled repository.
2.  Create second repository
3.  Merge second into first repository with `git merge --allow-unrelated-histories`
4. Run `nx release --first-release --dry-run --verbose`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.2
   OS     : darwin-arm64
   pnpm   : 8.15.1
   
   nx (global)        : 17.3.1
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/next           : 17.3.1
   @nx/react          : 17.3.1
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.1.0
```

### Failure Logs

```shell
Determined workspace --from ref from the first commit in workspace: 36bb456c5327023c92f910d72dc9c695a016b758
ab61a513bc7941ea5a9a1816a2efc36d9c248c90
fatal: ambiguous argument '36bb456c5327023c92f910d72dc9c695a016b758
ab61a513bc7941ea5a9a1816a2efc36d9c248c90': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'


 >  NX   Unknown revision: 36bb456c5327023c92f910d72dc9c695a016b758

   ab61a513bc7941ea5a9a1816a2efc36d9c248c90

Error: Unknown revision: 36bb456c5327023c92f910d72dc9c695a016b758
ab61a513bc7941ea5a9a1816a2efc36d9c248c90
    at getCommitHash (/Users/louis/Projects/Picky/picky-ts-mono/node_modules/.pnpm/nx@17.3.1_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/command-line/release/utils/git.js:250:15)
    at async releaseChangelog (/Users/louis/Projects/Picky/picky-ts-mono/node_modules/.pnpm/nx@17.3.1_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/command-line/release/changelog.js:130:39)
    at async release (/Users/louis/Projects/Picky/picky-ts-mono/node_modules/.pnpm/nx@17.3.1_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/command-line/release/release.js:54:5)
    at async handleErrors (/Users/louis/Projects/Picky/picky-ts-mono/node_modules/.pnpm/nx@17.3.1_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/utils/params.js:9:16)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Looking at the command that is run, a fix would be to adjust this from `git rev-list --max-parents=0 HEAD` to `git rev-list --max-parents=0 --first-parent HEAD`. Otherwise the output should be parsed and only the first commit hash used.

**Comment by freakness** [comment]
See also here: https://github.com/nrwl/nx/blob/18.0.2/packages/nx/src/command-line/release/utils/git.ts#L367

**Comment by freakness** [comment]
Thanks for the fix 🎉
