### ISSUE TITLE
[Nest] Nest app build failure with generatePackageJson=true - Nx 18

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#21651]
### Current Behavior

Nest app build fails with generatePackageJson=true option

### Expected Behavior

Nest app should build without error and generate the package.json file

### Steps to Reproduce

1. Create a new workspace with nx 18
2. Install @nx/nest plugin
3. Create a nest app
4. Update webpack.config.js to include `genetarePackageJson: true`
5. Run build command to build your app

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : darwin-x64
   npm    : 10.4.0
   
   nx (global)        : 18.0.2
   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/nest           : 18.0.2
   @nx/node           : 18.0.2
   @nrwl/tao          : 18.0.2
   @nx/web            : 18.0.2
   @nx/webpack        : 18.0.2
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.2.0
```
```


### Failure Logs

```shell
sandbox on  main [!+?] via  v20.11.0 took 4s 
❯ nx run api:build --skip-nx-cache

 >  NX   --skip-nx-cache disables the connection to Nx Cloud for the current run.

   The remote cache will not be read from or written to during this run.


> nx run api:build

[webpack-cli] HookWebpackError: ENOENT: no such file or directory, open 'package-lock.json'
    at makeWebpackError (/Users/gperdomor/Downloads/sandbox/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/gperdomor/Downloads/sandbox/node_modules/webpack/lib/Compilation.js:3075:12
    at eval (eval at create (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at fn (/Users/gperdomor/Downloads/sandbox/node_modules/webpack/lib/Compilation.js:481:17)
    at _next0 (eval at create (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.eval [as callAsync] (eval at create (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/gperdomor/Downloads/sandbox/node_modules/webpack/lib/Compilation.js:516:46
    at /Users/gperdomor/Downloads/sandbox/node_modules/copy-webpack-plugin/dist/index.js:909:9
-- inner error --
Error: ENOENT: no such file or directory, open 'package-lock.json'
    at readFileSync (node:fs:453:20)
    at createLockFile (/Users/gperdomor/Downloads/sandbox/node_modules/nx/src/plugins/js/lock-file/lock-file.js:122:43)
    at /Users/gperdomor/Downloads/sandbox/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:39:138
    at fn (/Users/gperdomor/Downloads/sandbox/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.eval [as callAsync] (eval at create (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/gperdomor/Downloads/sandbox/node_modules/webpack/lib/Compilation.js:516:46
    at /Users/gperdomor/Downloads/sandbox/node_modules/copy-webpack-plugin/dist/index.js:909:9
caused by plugins in Compilation.hooks.processAssets
Error: ENOENT: no such file or directory, open 'package-lock.json'
    at readFileSync (node:fs:453:20)
    at createLockFile (/Users/gperdomor/Downloads/sandbox/node_modules/nx/src/plugins/js/lock-file/lock-file.js:122:43)
    at /Users/gperdomor/Downloads/sandbox/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:39:138
    at fn (/Users/gperdomor/Downloads/sandbox/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.eval [as callAsync] (eval at create (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/gperdomor/Downloads/sandbox/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/gperdomor/Downloads/sandbox/node_modules/webpack/lib/Compilation.js:516:46
    at /Users/gperdomor/Downloads/sandbox/node_modules/copy-webpack-plugin/dist/index.js:909:9
Warning: run-commands command "webpack-cli build --node-env=production" exited with non-zero status code
 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————
 ```
```


### Package Manager Version

npm 10.4.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by alonronin** [comment]
same here:

```shell

 >  NX   Report complete - copy this into the issue template

   Node   : 21.6.1
   OS     : darwin-arm64
   npm    : 9.8.0
   
   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/nest           : 18.0.2
   @nx/next           : 18.0.2
   @nx/node           : 18.0.2
   @nx/playwright     : 18.0.2
   @nx/react          : 18.0.2
   @nrwl/tao          : 18.0.2
   @nx/web            : 18.0.2
   @nx/webpack        : 18.0.2
   typescript         : 5.3.3
```

Error:

```shell

> nx run api:build


 

 >  NX   Running target build for project api failed

   Failed tasks:
   
   - api:build
   
   Hint: run the command with --verbose for more details.

[webpack-cli] HookWebpackError: ENOENT: no such file or directory, open 'package-lock.json'
    at makeWebpackError (/Users/alontikal/www/yum/yum/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/alontikal/www/yum/yum/node_modules/webpack/lib/Compilation.js:3075:12
    at eval (eval at create (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at fn (/Users/alontikal/www/yum/yum/node_modules/webpack/lib/Compilation.js:481:17)
    at _next0 (eval at create (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.eval [as callAsync] (eval at create (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/alontikal/www/yum/yum/node_modules/webpack/lib/Compilation.js:516:46
    at /Users/alontikal/www/yum/yum/node_modules/copy-webpack-plugin/dist/index.js:909:9
-- inner error --
Error: ENOENT: no such file or directory, open 'package-lock.json'
    at readFileSync (node:fs:456:20)
    at createLockFile (/Users/alontikal/www/yum/yum/node_modules/nx/src/plugins/js/lock-file/lock-file.js:122:43)
    at /Users/alontikal/www/yum/yum/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:39:138
    at fn (/Users/alontikal/www/yum/yum/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.eval [as callAsync] (eval at create (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/alontikal/www/yum/yum/node_modules/webpack/lib/Compilation.js:516:46
    at /Users/alontikal/www/yum/yum/node_modules/copy-webpack-plugin/dist/index.js:909:9
caused by plugins in Compilation.hooks.processAssets
Error: ENOENT: no such file or directory, open 'package-lock.json'
    at readFileSync (node:fs:456:20)
    at createLockFile (/Users/alontikal/www/yum/yum/node_modules/nx/src/plugins/js/lock-file/lock-file.js:122:43)
    at /Users/alontikal/www/yum/yum/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:39:138
    at fn (/Users/alontikal/www/yum/yum/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.eval [as callAsync] (eval at create (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/alontikal/www/yum/yum/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/alontikal/www/yum/yum/node_modules/webpack/lib/Compilation.js:516:46
    at /Users/alontikal/www/yum/yum/node_modules/copy-webpack-plugin/dist/index.js:909:9
Warning: run-commands command "webpack-cli build --node-env=production" exited with non-zero status code
```

**Comment by DGuidi** [comment]
fixed manually editing the file `node_modules\nx\src\plugins\js\lock-file\lock-file.js` 
edited the row 122:
`const content = (0, fs_1.readFileSync)(getLockFileName(packageManager), 'utf8');`
to
`const content = (0, fs_1.readFileSync)(path_1.join([workspace_root_1.workspaceRoot, getLockFileName(packageManager)], 'utf8');`

I'm unable to find the actual code in the repository, sorry.

**Comment by batamire** [comment]
I have the same issue. It is there when building @nx/express app. Steps are exactly the same, tried with npm and pnpm.

**Comment by dmastag** [comment]
I have an existing NX Project with many Nest Apps, I noticed that since upgrading to NX 18 the project.json executor is different now

```"executor": "@nx/js:node",```

Is this why its not working ?
I dont know where to put the `"generatePackageJson": true` now

**Comment by DGuidi** [comment]
> I dont know where to put the `"generatePackageJson": true` now

use the project-specific webpack.config.js
```
const { NxWebpackPlugin } = require('@nx/webpack');
const { join } = require('path');

module.exports = {
  output: {
    path: join(__dirname, '../../dist/apps/your-service'),
  },
  plugins: [
    new NxWebpackPlugin({
      target: 'node',
      compiler: 'tsc',
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      assets: ['./src/assets'],
      optimization: false,
      outputHashing: 'none',
      generatePackageJson: true,
      sourceMap: true,      
    }),
  ],
};
```

**Comment by dmastag** [comment]
I forgot to mention that I already tried that, but it kept showing an error that the package-lock.json could not be found, let me try again

**Comment by DGuidi** [comment]
Have you tried the fix I suggested?

**Comment by dmastag** [comment]
Yes I did @DGuidi

**Comment by chuckurbis** [comment]
I was having the same issue, and I added an empty package-lock.json to the project I was trying to build. This allowed the build to go through, generated a package.json but also generated an empty package-lock.json file.

**Comment by qstyler** [comment]
Same here but for 'pnpm-lock.yaml'.

**Comment by bddy** [comment]
Our temp solution until a fix is available:

```json
  "targets": {
    "sync-package-lock": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "# TODO: delete this target once https://github.com/nrwl/nx/issues/21651 is fixed",
          "npx cpy package-lock.json <path-to-project-root> --flat"
        ]
      }
    },
    "build": {
      "dependsOn": ["sync-package-lock"]
    }
  }
```

Along with adding the package-lock to the <path-to-project-root>/.gitignore.

**Comment by alonronin** [comment]
@bddy i changed it a bit to be more safer and include all package locks, also it will always copy to the directory of the targets' project:

```json
{
  "targets": {
    "sync-lock": {
      "executor": "nx:run-commands",
      "options": {
        "command": "npx shx cp *-lock.* {projectRoot}"
      }
    }  
}
```

**Comment by alex-mehdi-dev** [comment]
Thanks @alonronin and @bddy . Now I'm able to build a docker image with [nx-container](https://github.com/gperdomor/nx-tools/blob/main/packages/nx-container/README.md) without having to use a big `package.json`. So sad I need to drop [swc](https://nx.dev/nx-api/js/executors/swc) for [webpack](https://nx.dev/nx-api/webpack/executors/webpack). Sadly, I have not find a way to tell swc to generate `node_modules` inside the compiled projects inside the `dist` directory.

**Comment by alonronin** [comment]
> Thanks @alonronin and @bddy . Now I'm able to build a docker image with [nx-container](https://github.com/gperdomor/nx-tools/blob/main/packages/nx-container/README.md) without having to use a big `package.json`. So sad I need to drop [swc](https://nx.dev/nx-api/js/executors/swc) for [webpack](https://nx.dev/nx-api/webpack/executors/webpack). Sadly, I have not find a way to tell swc to generate `node_modules` inside the compiled projects inside the `dist` directory.

You can change the output dir. But what is the problem with copying files from dist?

**Comment by alex-mehdi-dev** [comment]
> > Thanks @alonronin and @bddy . Now I'm able to build a docker image with [nx-container](https://github.com/gperdomor/nx-tools/blob/main/packages/nx-container/README.md?rgh-link-date=2024-02-25T16%3A57%3A36Z) without having to use a big `package.json`. So sad I need to drop [swc](https://nx.dev/nx-api/js/executors/swc) for [webpack](https://nx.dev/nx-api/webpack/executors/webpack). Sadly, I have not find a way to tell swc to generate `node_modules` inside the compiled projects inside the `dist` directory.
> 
> You can change the output dir. But what is the problem with copying files from dist?

swc seems not to offer a `generatePackageJson` property. This feature is quite nice in order to have a `package.json` file in the `dist` directory of each project with only the minimum dependencies (smaller Docker image, lower exposure to security vulnerabilities or bugs, etc). Then with this small `package.json` file we can generate a `node_module` directory in the `dist` directory of a project when building the Docker image and copy it.

My current choice is using both swc and webpack.
- swc for development: very fast, an it is easy to set breakpoints (No specific node_modules in the dist directory of the project but not needed). It is also used of any library.
- webpack when I need to generate a small docker image (`generatePackageJson` ->` package.json` with specific dependencies -> generation of specific `node_modules` -> copy them when building the Docker image.

**Comment by alex-mehdi-dev** [comment]
@bddy Thanks for the tips. I have considered this approach too, but I got a problem. With swc, at run time my app-api seems to need `@swc/helpers` as a dependency. webpack does not add it to the dependency list when generating the `package.json` file. It is possible that my swc configuration file is wrong :/

.swcrc
```
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": false,
  "module": {
    "type": "commonjs",
    "strict": true,
    "strictMode": true
  },
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "externalHelpers": true,
    "loose": true
  },
  "minify": true,
  "exclude": [
    "jest.config.ts",
    ".*\\.spec.tsx?$",
    ".*\\.test.tsx?$",
    "./src/jest-setup.ts$",
    "./**/jest-setup.ts$",
    ".*.js$"
  ]
}
```

**Comment by bddy** [comment]
@alex-mehdi-dev try removing `"externalHelpers": true` from your config.

**Comment by alex-mehdi-dev** [comment]
> @alex-mehdi-dev try removing `"externalHelpers": true` from your config.

I try it and I still got the problem. In practice it is not that important if I can manage to build production images. I don't need a lot of speed as it is for development when building them. I will investigate this problem later. I will write here a message if I found something. Thanks for your help !

**Comment by ericbf** [comment]
@bddy and @alex-mehdi-dev to take it a step even further, enabling cache and allowing it to run before build automatically (only if needed), you can add the cache options and make it a dependency of build, something like. No need to configure any npm script this way:

```json
"targets": {
	"sync-lock": {
		"executor": "nx:run-commands",
		"options": {
			"command": "npx shx cp *-lock.* {projectRoot}"
		},
		"cache": true,
		"inputs": ["{workspaceRoot}/*-lock.*"],
		"outputs": ["{projectRoot}/*-lock.*"]
	},
	"build": {
		"dependsOn": ["sync-lock"],
		...
	},
	...
}
```

**Comment by bddy** [comment]
@ericbf i thought about `dependsOn` inside the `build` target as well but then figured i only really wanted to sync after `npm i`. Anyways, with caching and everything generic, that's an awesome solution we hopefully won't need anymore with the next update 😄

**Comment by adrian-goe** [comment]
@meeroslav the fix seems not to fix the issue.
I have a newly generated project in 18.1.2 with the added `"generatePackageJson": true` in the project.json

here is public reproduced project https://github.com/adrian-goe/nx-generate-packagejson

The expectation would be to have a package.json in the dist/apps/demo after build step.

**Comment by meeroslav** [comment]
@adrian-goe this is expected. In your repo you are manually setting up the webpack config:
```
const { NxWebpackPlugin } = require('@nx/webpack');
const { join } = require('path');

module.exports = {
  output: {
    path: join(__dirname, '../../dist/apps/demo'),
  },
  plugins: [
    new NxWebpackPlugin({
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      assets: ['./src/assets'],
      optimization: false,
      outputHashing: 'none',
    }),
  ],
};
```

The logic that generates the package.json and the lock file is missing in your config.
If you use the default config suggested by us using the hook `withNx` this would ensure the package.json handling plugin is included:
```

const { composePlugins, withNx} = require('@nx/webpack');

// Nx plugins for webpack.
module.exports = composePlugins(
  withNx({
    target: 'node',
  }),
  (config) => {
    // Update the webpack config as needed here.
    // e.g. `config.plugins.push(new MyPlugin())`
    return config;
  }
);
```

**Comment by adrian-goe** [comment]
@meeroslav hi thanks, i will check that. 
Just as a note, this repo is not manually edited, except the option. So this webpack config is done by the generation.

**Comment by SirPhemmiey** [comment]
hi @adrian-goe, could you please let us know in the thread if anything has worked for you?

**Comment by meeroslav** [comment]
Hi @adrian-goe if you add `generatePackageJson: true` to that `NxWebpackPlugin`, then it would work as expected.

We had some recent changes in this area and it could be that things are not properly documented.

cc @jaysoo @isaacplmann
