### ISSUE TITLE
nx is not working with next.js app in mac

### ISSUE THREAD

**Issue by myanzik** [nrwl/nx#21663]
### Current Behavior

I tried to setup the basic nx project following this [article](https://medium.com/readytowork-org/monorepo-setup-with-nx-nextjs-and-shadcn-ui-3b72c3599470) but i get error when i try to serve the next.js project

I am getting this error in Mac but its working fine in windows machine.
 >  NX   Cannot find configuration for task rahat-ui:serve

### Expected Behavior

It should run the next.js project

### Steps to Reproduce

- Here are the steps that i followed
https://medium.com/readytowork-org/monorepo-setup-with-nx-nextjs-and-shadcn-ui-3b72c3599470

### Nx Report

```shell
Node   : 20.10.0
   OS     : darwin-arm64
   npm    : 10.2.3
   
   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/cypress        : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/next           : 18.0.2
   @nx/react          : 18.0.2
   @nx/rollup         : 18.0.2
   @nrwl/tao          : 18.0.2
   @nx/web            : 18.0.2
   typescript         : 5.3.3
```

### Failure Logs

```shell
>  NX   Cannot find configuration for task rahat-ui:serve


Error: Cannot find configuration for task rahat-ui:serve
    at ProcessTasks.createTask (/Users/manjikshrestha/projects/rahataid/rahat-ui/node_modules/nx/src/tasks-runner/create-task-graph.js:156:19)
    at ProcessTasks.processTasks (/Users/manjikshrestha/projects/rahataid/rahat-ui/node_modules/nx/src/tasks-runner/create-task-graph.js:23:39)
    at createTaskGraph (/Users/manjikshrestha/projects/rahataid/rahat-ui/node_modules/nx/src/tasks-runner/create-task-graph.js:195:21)
    at createTaskGraphAndValidateCycles (/Users/manjikshrestha/projects/rahataid/rahat-ui/node_modules/nx/src/tasks-runner/run-command.js:62:63)
    at /Users/manjikshrestha/projects/rahataid/rahat-ui/node_modules/nx/src/tasks-runner/run-command.js:86:27
    at handleErrors (/Users/manjikshrestha/projects/rahataid/rahat-ui/node_modules/nx/src/utils/params.js:9:22)
    at runCommand (/Users/manjikshrestha/projects/rahataid/rahat-ui/node_modules/nx/src/tasks-runner/run-command.js:83:52)
    at Object.runOne (/Users/manjikshrestha/projects/rahataid/rahat-ui/node_modules/nx/src/command-line/run/run-one.js:50:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(base) manjikshrestha@Manjiks-MBP rahat-ui % npx nx report
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by alonronin** [comment]
the task name is dev now.

```shell
$ nx dev rahat-ui
```

you can see the project targets:

```shell
$ nx show project rahat-ui --web
```

**Comment by myanzik** [comment]
Thanks. it worked
