### ISSUE TITLE
 NX Module Federation - Cannot use import statement outside a module

### ISSUE THREAD

**Issue by udaya0108** [nrwl/nx#21711]
### Current Behavior

![image](https://github.com/nrwl/nx/assets/158443473/5765adc7-769c-47e0-83de-52cbea286dd9)

### Expected Behavior

Nx workspace 18.0.2

nx run host:build:production
- Host should produce the  build files

### Steps to Reproduce

> nx run host:build:production

⠋ Generating browser application bundles (phase: setup)...
 >  NX   Cannot use import statement outside a module

C:\Udaya\Projects\Nx-Frontend\myo-consult-nx\apps\host\webpack.config.ts:1
import { withModuleFederation } from '@nx/angular/module-federation';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._compile (C:\Udaya\Projects\Nx-Frontend\myo-consult-nx\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader [as .ts] (C:\Udaya\Projects\Nx-Frontend\myo-consult-nx\node_modules\pirates\lib\index.js:121:7)   
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.require (C:\Udaya\Projects\NX-FRO~1\MYO-CO~1\NODE_M~1\nx\src\adapter\compat.js:63:40)

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Running target build for project host failed

   Failed tasks:

   - host:build:production

### Nx Report

```shell
> nx run host:build:production

⠋ Generating browser application bundles (phase: setup)...
 >  NX   Cannot use import statement outside a module


C:\Udaya\Projects\Nx-Frontend\myo-consult-nx\apps\host\webpack.config.ts:1
import { withModuleFederation } from '@nx/angular/module-federation';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._compile (C:\Udaya\Projects\Nx-Frontend\myo-consult-nx\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader [as .ts] (C:\Udaya\Projects\Nx-Frontend\myo-consult-nx\node_modules\pirates\lib\index.js:121:7)   
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.require (C:\Udaya\Projects\NX-FRO~1\MYO-CO~1\NODE_M~1\nx\src\adapter\compat.js:63:40)

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Running target build for project host failed

   Failed tasks:

   - host:build:production
```

### Failure Logs

```shell
> nx run host:build:production

⠋ Generating browser application bundles (phase: setup)...
 >  NX   Cannot use import statement outside a module


C:\Udaya\Projects\Nx-Frontend\myo-consult-nx\apps\host\webpack.config.ts:1
import { withModuleFederation } from '@nx/angular/module-federation';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._compile (C:\Udaya\Projects\Nx-Frontend\myo-consult-nx\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader [as .ts] (C:\Udaya\Projects\Nx-Frontend\myo-consult-nx\node_modules\pirates\lib\index.js:121:7)   
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.require (C:\Udaya\Projects\NX-FRO~1\MYO-CO~1\NODE_M~1\nx\src\adapter\compat.js:63:40)

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Running target build for project host failed

   Failed tasks:

   - host:build:production
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by udaya0108** [comment]
![image](https://github.com/nrwl/nx/assets/158443473/78659b51-fa37-4290-9ce5-0741f342babb)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please retry with the latest Nx version (18.0.3). There was an issue fixed in that version that could have caused this one.

**Comment by udaya0108** [comment]
Hi leosvelperez, thank you for your quick response. I have resolved this issue, i was included json option in tsconfig.base.json file and after disabling this option. It is working fine now.
![image](https://github.com/nrwl/nx/assets/158443473/db763484-a7d1-49c4-9877-d205991d79b8)
