### ISSUE TITLE
Cannot read properties of undefined (reading 'test')

### ISSUE THREAD

**Issue by nbolton** [nrwl/nx#21713]
### Current Behavior

```
$ npx nx generate @nx/js:library --name=hello-world --unitTestRunner=jest --projectNameAndRootFormat=as-provided --no-interactive --verbose
Debugger attached.
Debugger attached.

>  NX  Generating @nx/js:library


 >  NX   Cannot read properties of undefined (reading 'test')


TypeError: Cannot read properties of undefined (reading 'test')
    at createJestConfig (/home/nick/Projects/web-muskoka/node_modules/@nx/jest/src/generators/configuration/lib/create-jest-config.js:47:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async configurationGeneratorInternal (/home/nick/Projects/web-muskoka/node_modules/@nx/jest/src/generators/configuration/configuration.js:60:5)
    at async addJest (/home/nick/Projects/web-muskoka/node_modules/@nx/js/src/generators/library/library.js:365:12)
    at async libraryGeneratorInternal (/home/nick/Projects/web-muskoka/node_modules/@nx/js/src/generators/library/library.js:69:30)
    at async /home/nick/Projects/web-muskoka/node_modules/nx/src/command-line/generate/generate.js:241:26
    at async handleErrors (/home/nick/Projects/web-muskoka/node_modules/nx/src/utils/params.js:9:16)
    at async Object.handler (/home/nick/Projects/web-muskoka/node_modules/nx/src/command-line/generate/command-object.js:13:22)
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

### Expected Behavior

Command succeeds.

### Steps to Reproduce

1. Setup Nx in an existing monorepo

### Nx Report

```shell
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : linux-x64
   npm    : 10.2.4
   
   nx (global)        : 18.0.2
   nx                 : 18.0.3
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/esbuild        : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/next           : 18.0.2
   @nx/playwright     : 18.0.2
   @nx/react          : 18.0.2
   @nrwl/tao          : 18.0.3
   @nx/web            : 18.0.2
   typescript         : 5.3.3
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@18.0.2
     - @nrwl/js@18.0.2
     - @nx/jest@18.0.2
     - @nrwl/jest@18.0.2
     - @nx/linter@18.0.2
     - @nx/eslint@18.0.2
     - @nx/workspace@18.0.2
     - @nrwl/workspace@18.0.2
     - @nx/devkit@18.0.2
     - @nrwl/devkit@18.0.2
     - @nx/esbuild@18.0.2
     - @nrwl/esbuild@18.0.2
     - @nx/eslint-plugin@18.0.2
     - @nrwl/eslint-plugin-nx@18.0.2
     - @nx/next@18.0.2
     - @nrwl/next@18.0.2
     - @nx/playwright@18.0.2
     - @nx/react@18.0.2
     - @nrwl/react@18.0.2
     - @nx/web@18.0.2
     - @nrwl/web@18.0.2
   
   To fix this, run `nx migrate nx@18.0.3`
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The `targets` prop is `undefined`, and you're not checking for null.

![image](https://github.com/nrwl/nx/assets/313427/35ecd1cf-ee76-40d9-8903-7aa33e7d3e77)

However, that prop is nullable:
```
export interface ProjectConfiguration {
    /**
     * Project's name. Optional if specified in workspace.json
     */
    name?: string;
    /**
     * Project's targets
     */
    targets?: {
        [targetName: string]: TargetConfiguration;
    };
```

Based on the error, it's not at all clear what causes this to be `undefined` or how to fix it.

**Comment by epliXs** [comment]
I am getting same error after upgrading from 15 to 18, and trying to create angular lib. Except in my case `rootProjectConfig` is `{ root: '.', name: 'project-name' }`.

**Comment by epliXs** [comment]
> I am getting same error after upgrading from 15 to 18, and trying to create angular lib. Except in my case `rootProjectConfig` is `{ root: '.', name: 'foo-bar' }`. `rootProject` is
> 
> ```
> {
>   name: 'foo-bar',
>   type: 'lib',
>   data: {
>     root: '.',
>     targets: { test: [Object], e2e: [Object], 'e2e-ci': [Object] },
>     sourceRoot: '.',
>     name: 'foo-bar',
>     projectType: 'library',
>     includedScripts: [],
>     implicitDependencies: [],
>     tags: []
>   }
> }
> ```

In my case issue was with `package.json` having following property
```
"nx": {
    "includedScripts": []
}
```
After removing it, I am able to create angular lib without any errors.

**Comment by nbolton** [comment]
> "includedScripts": []

Good catch, in our case we need this to solve another problem (albeit a temporary fix).

Seems like another, simpler workaround (without patching) is to add a `test` root-level script to `package.json`:
```diff
diff --git a/package.json b/package.json
index 90c9614..8210e91 100644
--- a/package.json
+++ b/package.json
@@ -4,6 +4,7 @@
   "scripts": {
+    "test": "jest",
```

However, this still has the side effect where no `test` target is added to the Nx `project.json`, so it must be manually added.

**Comment by leosvelperez** [comment]
This was fixed by https://github.com/nrwl/nx/pull/21952 and released in [Nx 18.0.5](https://github.com/nrwl/nx/releases/tag/18.0.5).
