### ISSUE TITLE
Can't run nx g @nx/vue:library my-lib because "Error: Cannot parse eslint.config.js: InvalidSymbol in JSON at 1:1" 

### ISSUE THREAD

**Issue by mklueh** [nrwl/nx#21739]
### Current Behavior

```
Error: Cannot parse my-lib/eslint.config.js: InvalidSymbol in JSON at 1:1
> 1 | const FlatCompat = require("@eslint/eslintrc");
    | ^^^^^
  2 | const js = require("@eslint/js");
  3 | const baseConfig = require("../../eslint.config.js");
  4 |

    at readJson (C:\Users\MyUser\Workspace\monorepo\node_modules\nx\src\generators\utils\json.js:20:15)
    at updateJson (C:\Users\MyUser\Workspace\monorepo\node_modules\nx\src\generators\utils\json.js:45:34)
    at editEslintConfigFiles (C:\Users\MyUser\Workspace\monorepo\node_modules\@nx\vue\src\utils\add-linting.js:46:33)
    at addLinting (C:\Users\MyUser\Workspace\monorepo\node_modules\@nx\vue\src\utils\add-linting.js:31:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at libraryGeneratorInternal (C:\Users\MyUser\Workspace\monorepo\node_modules\@nx\vue\src\generators\library\library.js:41:16)
    at C:\Users\MyUser\Workspace\monorepo\node_modules\nx\src\command-line\generate\generate.js:241:26
    at handleErrors (C:\Users\MyUser\Workspace\monorepo\node_modules\nx\src\utils\params.js:9:16)
    at Object.handler (C:\Users\MyUser\Workspace\monorepo\node_modules\nx\src\command-line\generate\command-object.js:13:22)
```

### Expected Behavior

To generate the library without failures within the process

### Steps to Reproduce

By running the command to generate a new vue library

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 21.4.0
   OS     : win32-x64
   yarn   : 4.1.0

   nx              : 18.0.3
   @nx/js          : 18.0.3
   @nx/linter      : 18.0.3
   @nx/eslint      : 18.0.3
   @nx/workspace   : 18.0.3
   @nx/devkit      : 18.0.3
   @nrwl/devkit    : 17.2.7
   @nx/playwright  : 18.0.3
   @nrwl/tao       : 15.9.7
   @nx/vite        : 18.0.3
   @nx/vue         : 18.0.3
   @nx/web         : 18.0.3
   typescript      : 5.3.3
   ---------------------------------------
   Community plugins:
   @jnxplus/nx-gradle                  : 0.19.7
   @jscutlery/semver                   : 5.1.0
   @nx/nuxt                            : 18.0.3
   @nxrocks/nx-quarkus                 : 7.2.2
   @theunderscorer/nx-semantic-release : 2.10.0
   @trumbitta/nx-plugin-openapi        : 1.12.1
   @trumbitta/nx-plugin-unused-deps    : 1.12.1
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/devkit@17.2.7
     - @nrwl/tao@15.9.7

   To fix this, run `nx migrate nx@18.0.3`
```

### Package Manager Version

yarn 4.1.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by JulianMar** [comment]
I have the same issue!
Seems to be an issue with nx expecting a eslint config in json format, but you have it in a eslint.config.js file.
It seems to be an issue here. https://github.com/nrwl/nx/blob/3b21cefd8cea62eaf1756f26083e618e8e525b97/packages/vue/src/utils/add-linting.ts#L76  It wants to parse the js file as json but that will never work.

**Comment by mklueh** [comment]
any news?

**Comment by liting-yes** [comment]
Temporary solution is to skip lint config generation
> https://nx.dev/nx-api/vue/generators/application#linter

**Comment by JulianMar** [comment]
yeah, i did the same.

**Comment by dhlavaty** [comment]
> Temporary solution is to skip lint config generation

Setting `linter=none` did not work for me. I had to replace the content of my `.eslintrc.js` with an empty `{}` JSON content temporarily. 😞
