### ISSUE TITLE
Errors in changelog rendering are swallowed by resolveChangelogRenderer

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [nrwl/nx#21787]
### Current Behavior

Right now, when a custom changelog renderer is provided in `projectChangelogs.renderer` and/or `workspaceChangelog.renderer`, the code that attempts to `require()` that path is wrapped in a `try`/`catch`. That `catch` doesn't attempt to log any caught error:

https://github.com/nrwl/nx/blob/4caa6be71a32750b4f6499586536ed55bc36c5f8/packages/nx/src/command-line/release/changelog.ts#L494

### Expected Behavior

It'd be nice to have a warning. That way we can see in CI more quickly why a changelog renderer issue is happening.

### GitHub Repo

https://github.com/typescript-eslint/typescript-eslint/pull/8439

### Steps to Reproduce

1. Create a `changelog-renderer.js` file that throws an error
2. Set it as the `renderer` for changelog settings

### Nx Report

```shell
Node   : 20.11.0
   OS     : darwin-arm64
   yarn   : 3.8.0
   
   nx             : 17.3.1
   @nx/js         : 17.3.1
   @nx/jest       : 17.3.1
   @nx/linter     : 17.3.1
   @nx/eslint     : 17.3.1
   @nx/workspace  : 17.3.1
   @nx/devkit     : 17.3.1
   @nrwl/tao      : 17.3.1
   typescript     : 5.3.3
```

### Failure Logs

I manually added a `catch (error)` and `console.log({ error })` in my local `node_modules/nx/src/command-line/release/changelog.js`.

```plaintext
{
  error: Error: Cannot find module 'nx/changelog-renderer'
  Require stack:
  - /Users/josh/repos/typescript-eslint/tools/release/changelog-renderer.js
  - /Users/josh/repos/typescript-eslint/node_modules/nx/src/command-line/release/changelog.js
  - /Users/josh/repos/typescript-eslint/node_modules/nx/src/command-line/release/index.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
      at Function.a._resolveFilename (/Users/josh/repos/typescript-eslint/node_modules/tsx/dist/cjs/index.cjs:1:1729)
      at Function.Module._resolveFilename (/Users/josh/repos/typescript-eslint/node_modules/tsconfig-paths/src/register.ts:115:36)
      at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/josh/repos/typescript-eslint/node_modules/ts-node/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
      at Function.Module._load (node:internal/modules/cjs/loader:985:27)
      at Module.require (node:internal/modules/cjs/loader:1235:19)
      at require (node:internal/modules/helpers:176:18)
      at Object.<anonymous> (/Users/josh/repos/typescript-eslint/tools/release/changelog-renderer.js:1:47)
      at Module._compile (node:internal/modules/cjs/loader:1376:14)
      at Object.S (/Users/josh/repos/typescript-eslint/node_modules/tsx/dist/cjs/index.cjs:1:1292) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/josh/repos/typescript-eslint/tools/release/changelog-renderer.js',
      '/Users/josh/repos/typescript-eslint/node_modules/nx/src/command-line/release/changelog.js',
      '/Users/josh/repos/typescript-eslint/node_modules/nx/src/command-line/release/index.js'
    ]
  }
}
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Sorry I don't have the time right now to make a full reproduction. I hope the typescript-eslint link helps. 🙂

**Comment by JamesHenry** [comment]
Thank you @JoshuaKGoldberg!

**Comment by guillempuche** [comment]
For me the error output is:

```shell
 >  NX   Updating yarn lock file

Would update yarn.lock with the following command, but --dry-run was set:
yarn install --mode update-lockfile

 >  NX   Staging changed files with git

Would stage files in git with the following command, but --dry-run was set:
git add packages/components/package.json tsconfig.base.json
Determined workspace --from ref from the first commit in workspace: 8bd1c7f461e8848ea8f4ca9dbf0e6f7f4975ba62

 >  NX   Previewing an entry in CHANGELOG.md for v0.1.0
 
 >  NX   changelogRenderer is not a function


TypeError: changelogRenderer is not a function
    at generateChangelogForWorkspace (/Users/guillem/programacio/codi/cites/nx-expo-next-tamagui/node_modules/nx/src/command-line/release/changelog.js:363:26)
    at releaseChangelog (/Users/guillem/programacio/codi/cites/nx-expo-next-tamagui/node_modules/nx/src/command-line/release/changelog.js:131:11)
    at release (/Users/guillem/programacio/codi/cites/nx-expo-next-tamagui/node_modules/nx/src/command-line/release/release.js:54:5)
    at handleErrors (/Users/guillem/programacio/codi/cites/nx-expo-next-tamagui/node_modules/nx/src/utils/params.js:9:16)
    at Object.handler (/Users/guillem/programacio/codi/cites/nx-expo-next-tamagui/node_modules/nx/src/command-line/release/command-object.js:89:24)
```

**Comment by guillempuche** [comment]
The new `release` is awesome!! Great job Nx team!

**Comment by JamesHenry** [comment]
@guillempuche what does you nx.json config look like?

**Comment by guillempuche** [comment]
https://github.com/guillempuche/nx-expo-next-tamagui/blob/main/nx.json

```json
"release": {
    "projects": [
      "packages/*"
    ],
    "changelog": {
      "version": {
        "conventionalCommits": true
      },
      "git": {
        "commit": true,
        "tag": true
      }
    }
},
```

**Comment by JamesHenry** [comment]
@guillempuche I will open an issue on your repo to discuss further, you have quite a few things going on. But yes this issue is related because it is causing us to swallow your real error, like it did for Josh

**Comment by guillempuche** [comment]
Thanks a lot for you comments @JamesHenry.
Hope my repo template can help others with Nx in an universal app. In React Native world, many repos use Turbopack. I prefer your work 👌

**Comment by JamesHenry** [comment]
Sorry for the delay in house keeping here, the error handling was addressed in https://github.com/nrwl/nx/pull/23214
