### ISSUE TITLE
Creating an Nx Workspace fails with  '@angular-devkit/core' error

### ISSUE THREAD

**Issue by skusunam** [nrwl/nx#218]
Looks like this issue is with angular-cli which is filed here:  https://github.com/angular/angular-cli/issues/9190

This is in-turn handed over to devkit issue: https://github.com/angular/devkit/issues/380

There are some suggestions on above threads on how to fix this which only work after creating the repo. Let me know if there is anything we can do locally to make it work?

`$ curl -fsSL https://raw.githubusercontent.com/nrwl/nx/master/packages/install/install.sh | bash -s tusk-desk`

> Creating a sandbox with the CLI and Nx Schematics...
> [fsevents] Success: "/private/var/folders/sp/vqlytsrd5nng36jsl35766yh0000gn/T/tmp.Ctp9nfRb/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
> Pass --update-binary to reinstall or --build-from-source to recompile
> Cached binary found at /Users/xxxxx/.npm/node-sass/4.7.2/darwin-x64-57_binding.node
> Binary found at /private/var/folders/sp/vqlytsrd5nng36jsl35766yh0000gn/T/tmp.Ctp9nfRb/node_modules/node-sass/vendor/darwin-x64-57/binding.node
> Testing binary
> Binary is fine
> added 1008 packages in 20.528s
> Creating a new project...
> module.js:529
>     throw err;
>     ^
> 
> Error: Cannot find module '@angular-devkit/core'
>     at Function.Module._resolveFilename (module.js:527:15)
>     at Function.Module._load (module.js:476:23)
>     at Module.require (module.js:568:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/private/var/folders/sp/vqlytsrd5nng36jsl35766yh0000gn/T/tmp.Ctp9nfRb/node_modules/@angular-devkit/schematics/src/tree/virtual.js:10:16)
>     at Module._compile (module.js:624:30)
>     at Object.Module._extensions..js (module.js:635:10)
>     at Module.load (module.js:545:32)
>     at tryModuleLoad (module.js:508:12)
>     at Function.Module._load (module.js:500:3)

**Comment by skusunam** [comment]
Looks like this is duplicate
