### ISSUE TITLE
`nx release` publishes TS files in combination with default (integrated) generators

### ISSUE THREAD

**Issue by lorenzodejong** [nrwl/nx#21855]
### Current Behavior

Currently setting up a default (integrated) monorepo preset yields incorrect behavior when using `nx release`. By default, packages generated from `@nx/js` with the `publishable` option will generate a `project.json` which outputs changes to the /dist folder on the root of the monorepo. However the `package.json` in the src folder points to `./src/package.json`.

Running the `nx release` command seems to be directly publishing the package from the source directory, causing the actual TypeScript source files to be published instead of the resolved build output in the `dist` folder.

It seems like the current implementation of `nx release` is only intended to be used in package-based repositories, where you specify your package.json to point to a `dist` folder present in the actual source folder.

The [documentation](https://nx.dev/recipes/nx-release/get-started-with-nx-release#run-without) also seems to be incorrect on this regard. If you look at the example of the published tarball you'll see that actual `.ts` files are getting published:

```
// ...
📦  @myorg/pkg-1@0.0.2
=== Tarball Contents ===

233B README.md
277B package.json
53B  src/index.ts
61B  src/lib/pkg-1.ts
=== Tarball Details ===
// ...
```

### Expected Behavior

I expect `nx release` to be directly compatible with projects generated from the default provided Nx generators, without having to change the behavior of the `package.json` and `project.json`.

### Steps to Reproduce

1. Create a new repository with `npx create-nx-workspace release-example-workspace`, select to create an `Integrated Monorepo` when asked for it.
2. Generate a library with `npx nx g @nx/js:lib mylib`
3. Run `npx nx release --first-release --dry-run`
4. Run `npx nx release publish --dry-run`

Observed behavior: `.ts` files are present in the tarball.

### Nx Report

```shell
Node   : 18.13.0
   OS     : darwin-arm64
   npm    : 8.19.3

   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nrwl/tao          : 18.0.4
   typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by cpierceworld** [comment]
I ran into the same issue with an Angular project with some "publishable" libraries. #21560

When I publish them (via either "nx release" or via "nx run my-library:nx-release-publish") the resulting npm package is the source code i.e. the "my-library/src/" folder.  I expected it to publish the the compiled "dist/my-library"

**Comment by thdk** [comment]
@lorenzodejong are you trying to have a standalone nx workspace? Or a nx workspace that could eventually contain multiple packages? Your description and steps to reproduce are not completely clear for me.

However, as I'm an nx enthusiast, I saw your issue and tried to see if I could be of any help.
Therefor I have prepared a github repository containing a standalone typescript nx workspace:

https://github.com/thdk/nx-release-standalone-ts-library

I have also documented my steps in the readme file in order to get it published using `nx release` command.

The final output looks like:

```sh
❯ npx nx release publish --dry-run

 >  NX   Running target nx-release-publish for project my-lib:

    - my-lib
   
   With additional flags:
     --dryRun=true

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run my-lib:nx-release-publish


📦  @my-org/my-lib@0.0.1
=== Tarball Contents ===

1.1kB  LICENSE               
10.3kB README.md             
30B    dist/index.d.ts       
200B   dist/index.js         
116B   dist/index.js.map     
41B    dist/lib/my-lib.d.ts  
200B   dist/lib/my-lib.js    
172B   dist/lib/my-lib.js.map
10.6kB dist/README.md        
1.0kB  package.json          
=== Tarball Details ===
name:          @my-org/my-lib                          
version:       0.0.1                                   
filename:      my-org-my-lib-0.0.1.tgz                 
package size:  4.3 kB                                  
unpacked size: 23.8 kB                                 
shasum:        759b65eeb426b540ea9d93f946c0854f352dcd4b
integrity:     sha512-KLpammVULAbED[...]xZDugQ6nIdk4w==
total files:   10                                      
 
Would publish to https://registry.npmjs.org/ with tag "latest", but [dry-run] was set

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target nx-release-publish for project my-lib
```

There is one downside on my setup, it doesn't use the generated `package.json` file from the `build` target but used `package.json` file from the workspace root. I have found another way to make it work with the generate `package.json` as well but still unsure if that approach would be valid. Aas is, not documented, probably likely to break.

**Comment by lorenzodejong** [comment]
@thdk thanks for the extensive answer! I think my original message was indeed incorrect, i'm creating a monorepo with multiple packages. I think you have to choose for either a `Package-based monorepo` or a `Integrated Monorepo` to get this same behavior. I'll add that in my original reproduction steps.

The point you touch upon with the generated `package.json` might be a related issue indeed, where the `package.json` from the source is being used instead of the one from the build output.

**Comment by thdk** [comment]
Think I found the solution.

If you look in the source of _Nx_ repo, they have the following:

When running `npx nx release publish` you see eventually the following:

```sh
 >  NX   Successfully ran target nx-release-publish for project my-lib
```

Note the name of the target.

When I now look at the `nx.json` file from `@nrwl/nx` (this repo). I see the following:

```json
    "release": {
       "nx-release-publish": {
         "options": {
           "packageRoot": "build/packages/{projectName}"
         }
       },
    }
```

So assuming you have a folder `packages` containing your ts / js package source code, and each project is build output is placed in `dist/packages/{projectName}` you can adjust this configuration to match your own `dist` folder.

```json
    "release": {
       "nx-release-publish": {
         "options": {
           "packageRoot": "dist/packages/{projectName}"
         }
       },
    }
```

We can also tell _Nx_ to bump the version in the generated `package.json` using the following config in `nx.json`:

```json
  "release": {
     "git": {
        "commit": true,
        "tag": true
     },
    "projectsRelationship": "independent",
    "version": {
      "generatorOptions": {
        "specifierSource": "conventional-commits",
        "currentVersionResolver": "git-tag",
        "fallbackCurrentVersionResolver": "disk",
        "projectRoot": "dist/packages/{projectName}"
      }
    },
  }
  ```
  
Using conventional commits here to get the new version and git tags to find previously released versions since the version will not be bumped in the project's `package.json` file but only in the generated `package.json`. I believe other options are possible as well such as fetching existing version from the registry.

**Comment by acc-nicholas** [comment]
I'm running into the same root issue. After adding `"packageRoot": "dist/libs/{projectName}"` to my nx.json, that solves the problem of the correct compiled code packed and published to the registry.

But the next problem is that the version in the source code `libs/foo/package.json` gets updated via `nx release version` subcommand, but the `dist/libs/foo/package.json` does not get updated. So the publish fails because the dist version is stale and that version will already exist on the registry.

If i understand the comment above, you can workaround this issue by configuring release version to update the dist folder? But then the source folder is not matching still and that could lead to confusion as well? You'd just be relying on git tags to know what version your pkgs are on?

**Comment by lorenzodejong** [comment]
Yeah i also played around a bit more with this setup and i'm running into the same issue as @acc-nicholas is mentioning. The `package.json` in the dist gets updated, however isn't published as a commit in the source folder.

Also in the last comment of @thdk it's important to note that the configuration option is `packageRoot` instead of `projectRoot`:

```json
  "release": {
     "git": {
        "commit": true,
        "tag": true
     },
    "projectsRelationship": "independent",
    "version": {
      "generatorOptions": {
        "specifierSource": "conventional-commits",
        "currentVersionResolver": "git-tag",
        "fallbackCurrentVersionResolver": "disk",
        "packageRoot": "dist/packages/{projectName}"
      }
    },
  }
```

**Comment by acc-nicholas** [comment]
i tried adding `dependsOn` to my `nx.json`, but that also didn't work.

```
"nx-release-publish": {
      "dependsOn": ["build"],
      "options": {
        "packageRoot": "dist/libs/{projectName}"
      }
    },
```

**Comment by thdk** [comment]
> If i understand the comment above, you can workaround this issue by configuring release version to update the dist folder? But then the source folder is not matching still and that could lead to confusion as well? You'd just be relying on git tags to know what version your pkgs are on?

Sorry for the type in my previous comment (and linked repo). I have fixed that for future readers.

But you are right that, also as far as I know at the moment, with this setup git tags would become your source of truth. The version property of your `package.json` in `libs/{projectName}` would never be touched.

This now becomes the same issue as my raised issue here: https://github.com/nrwl/nx/issues/20936#issue-2058500249

**Comment by lorenzodejong** [comment]
@fahslaj could you perhaps provide some insight in the recommended approach here?

It feels like the `nx release` feature currently doesn't support a pretty standard publishing workflow: determining the next version of your package(s), compiling the code and publishing the compiled output with the corresponding `package.json`. Besides that the `package.json` in the package source code including the `CHANGELOG.md` should be updated.

Currently it's possible to set the `packageRoot` option, however that will point both publishing- and git commit logic to the `dist` folder. It feels like we're missing an option where we can:
- Specify the package source path for `changelog` and `version` creation (including creating a commit)
- Specify the package output path exclusively for `publish`

I would actually love to contribute here, it would be great if we can either support this workflow from the logic or write documentation on how to achieve this. Up until now i've had a pretty rough time discovering all the configuration options and the resulting output, so i feel like there's room for improvement.

**Comment by rainerhahnekamp** [comment]
I have the same problem and wonder how many cases we can publish the source code directly.

@JamesHenry, could you help us out here a little bit? Thanks!

**Comment by fahslaj** [comment]
> @fahslaj could you perhaps provide some insight in the recommended approach here?
> 
> It feels like the `nx release` feature currently doesn't support a pretty standard publishing workflow: determining the next version of your package(s), compiling the code and publishing the compiled output with the corresponding `package.json`. Besides that the `package.json` in the package source code including the `CHANGELOG.md` should be updated.
> 
> Currently it's possible to set the `packageRoot` option, however that will point both publishing- and git commit logic to the `dist` folder. It feels like we're missing an option where we can:
> 
> * Specify the package source path for `changelog` and `version` creation (including creating a commit)
> * Specify the package output path exclusively for `publish`
> 
> I would actually love to contribute here, it would be great if we can either support this workflow from the logic or write documentation on how to achieve this. Up until now i've had a pretty rough time discovering all the configuration options and the resulting output, so i feel like there's room for improvement.

Thank you for the clear explanation. I agree that this flow should be supported better. For now, as a workaround, you can create a release script that uses the [programmatic api](https://nx.dev/features/manage-releases#using-the-programmatic-api-for-nx-release). It would call `releaseVersion(...)`, then perform your build command, then `releasePublish(...)`. 

However, I do think this should be supported entirely from the CLI. I'll bring this up with the team and follow up when I have updates.

**Comment by lorenzodejong** [comment]
@fahslaj thanks for getting back to us!

That's indeed what i ended up doing, however it did take some extra effort to only build the specific packages that are actually about to be released.

I've created a gist with the current `publish.ts` script i've created: https://gist.github.com/lorenzodejong/acde50902b55ff2b72fffeeef2c35f9d.

For anyone interested on how to actually utilise it: you can use `@swc/node` to execute this script programatically:

```bash
$ node -r @swc-node/register tools/scripts/publish.ts
```

I've also included a specific flow in which a prerelease only creates a Git tag for version tracking purposes, whereas the `latest` release also includes a changelog and version bump in the `package.json`. This allows for the following CI/CD workflow:
- You can create a PR which incrementally publishes prereleases (`1.0.0-PR123.0`, `1.0.0-PR123.1`, etc)
- After integrating the PR the actual version (`1.0.0`) gets released, creating a commit with the version bump and changelog and pushing it
- (Optionally) clean up the prerelease tags once integrated

For my team this is the ideal workflow, this allows you to test prerelease changes easily without being conflicted with version release commits on the PR branch.

## Potential bug

One thing i've noticed however with this workflow is that an incorrect version gets released when creating the prerelease using the `conventional-commits` specifier source. Lets say the previous version is `0.1.0` and i create the following commit: `feat!: this should become 1.0.0` it actually bumps it to `0.1.1-PR123.0` instead of `1.0.0-PR123.0`.

@fahslaj i'm not sure if this bug has been reported already? Otherwise i'd be happy to create another more specific report for this with reproduction steps.

**Comment by fahslaj** [comment]
@lorenzodejong I am glad you were able to make it work with that script! As for the potential bug, if you could create a specific report with repro steps that would be greatly appreciated!

**Comment by rainerhahnekamp** [comment]
Hi @fahslaj, thanks for the prompt answer but I think that this should become top priority.

At the moment, nx release feels like a smartphone than can do everything except making phone calls... you know what I mean 😅

**Comment by JamesHenry** [comment]
@rainerhahnekamp let’s try and keep the discourse productive. typescript-eslint and angular-eslint are significant repos that are publishing their source files just fine with nx release, as are many others

**Comment by ryan-mcginty-alation** [comment]
@raketeFlo does the `nx release publish` command actually run the build or do you have to do that manually?

**Comment by raketeFlo** [comment]
`nx release publish` runs the build automatically because of the dependsOn. In my GitHub workflow I only run `nx release version` then I push the changes and tags and then I run `nx release publish` which builds my libs with the updated version and then publishes them.

The only thing I don't like about this approach is that the build could fail and then I already versioned and pushed the changes...

**Comment by raketeFlo** [comment]
I just found the suggestion of @fahslaj here: https://github.com/nrwl/nx/issues/20936#issuecomment-1924513707. I think now I have a solution I can live with:

I am using file:// links now for the libs which are added as dependencies. Then I specify in the generatorOptions of the version command that the packageRoot is in the dist folder of the respective lib. So when I run `nx release version` it will update the version only there. The package.json in the source directory itself can stay unchanged because it references each other with the file:// link. Now I don't have to build anymore after versioning.

**Comment by jeffora** [comment]
> @rainerhahnekamp let’s try and keep the discourse productive. typescript-eslint and angular-eslint are significant repos that are publishing their source files just fine with nx release, as are many others

@JamesHenry thanks for this comment, I've started looking at typescript-eslint as a reference in trying to implement `nx release` in my project. I notice that it only uses the programmatic API to achieve its release workflow, rather than the CLI.

Interestingly, it also uses `tsc --build` with project references rather than `@nx/js:tsc` with a root tsconfig with path mappings, and compiles dist folder side-by-side with source, rather than under a root `dist/packages/{package-name}`. These changes all seem to sidestep one of the issues discussed here, where the source-code package.json gets updated with release, but the dist package.json doesn't. However, these are all non-standard approaches if one has just scaffolded an nx repository by using the CLI defaults from the various generators.

Are these tweaks all necessary to get an nx release experience that requires minimal custom code? I.e. is it primarily suited for package-based monorepos rather than integrated monorepos that follow nx's more opinionated structure?

**Comment by zpydee** [comment]
I've been trying to solve this problem for the last couple of days (for a react vite library), and finally settled on the following:

1. I changed to vite outDir to './dist', placing the dist folder alongside the src folder in the library.
2. I added a .npmignore as follows:

```
src
.eslintrc.json
project.json
tsconfig.json
tsconfig.lib.json
vite.config.ts
```

3. I updated the package.json as follows:

```
{
  "name": "@spwntch/react-vite-sandbox",
  "version": "0.0.11",
  "main": "./dist/index.js",
  "module": "./dist/index.mjs",
  "types": "./dist/index.d.ts",
  "keywords": [
    "react",
    "vite",
    "sandbox"
  ],
  "author": "spwntch",
  "license": "MIT"
}

```


On publishing. this resulted in the following result, which I can consume:

```
📦  @spwntch/react-vite-sandbox@0.0.11
=== Tarball Contents ===

194B   README.md
42B    dist/index.d.ts
13.5kB dist/index.js
20.8kB dist/index.mjs
189B   dist/lib/react-vite-sandbox.d.ts
263B   package.json
=== Tarball Details ===
name:          @spwntch/react-vite-sandbox
version:       0.0.11
filename:      spwntch-react-vite-sandbox-0.0.11.tgz
package size:  9.9 kB
unpacked size: 34.9 kB
shasum:        532dbf531be7b2e3c95f80e7b1b88c329bc992c8
integrity:     sha512-xKdurjlp8+ej9[...]+7vLh8+gfKcLg==
total files:   6

Published to https://registry.npmjs.org/ with tag "latest"
```

Given the intent of project crystal, is this not a better approch than trying to mess with the nx release process?

**Comment by Jordan-Hall** [comment]
```
 "targetDefaults": {
   "nx-release-publish": {
      "dependsOn": [
        "build"
      ],
      "options": {
        "packageRoot": "dist/{projectRoot}"
      }
    }
 }
```

This repaired it for me. I want to say its just documentation issue rather than a actual bug

**Comment by joeflateau** [comment]
@fahslaj i see this is closed as completed, is this solution the recommended/correct approach? https://github.com/nrwl/nx/issues/21855#issuecomment-2041030949

**Comment by Jordan-Hall** [comment]
> @fahslaj i see this is closed as completed, is this solution the recommended/correct approach? [#21855 (comment)](https://github.com/nrwl/nx/issues/21855#issuecomment-2041030949)

https://github.com/nrwl/nx/issues/21855#issuecomment-2041030949

My comment above seems to me the solution. It's missing documentation maybe worth a PR to fix

**Comment by lorenzodejong** [comment]
This eventually also fixed the issue for me, however the only minor difference in my solution is that i targeted the `packageRoot` option to the source folder, e.g. `{workspaceRoot}/packages/{projectName}`.

The reason for this being that if you want to commit the updated `CHANGELOG.md` and version in the `package.json` using the automated commit feature from `nx release`, you want this to happen in the source folder of your code instead of the build output folder.

**Comment by HosseinSalmanian** [comment]
@fahslaj I' still wondering does the problem solved by NX or we should rely on workarounds?
I've tried to use built-in functionality of NX for build and publishing libraries in mono repo for creating change log and bumping version automatically, but  as others mentioned with referencing "packageRoot" to corresponding dist folder, version of published package does not bump.

**Comment by fahslaj** [comment]
@HosseinSalmanian If you need the version of the package within source control to be updated, but also need to publish a different `packageRoot` than the source, then you will need to use a workaround for now. This case is not currently supported by nx release.

**Comment by fahslaj** [comment]
Closing this issue, as work to support this case via the CLI is not currently planned. See the [nx release docs on publishing from a dist directory](https://nx.dev/recipes/nx-release/publish-custom-dist-directory) for supported publishing scenarios.

**Comment by arifshariati** [comment]
> ```
>  "targetDefaults": {
>    "nx-release-publish": {
>       "dependsOn": [
>         "build"
>       ],
>       "options": {
>         "packageRoot": "dist/{projectRoot}"
>       }
>     }
>  }
> ```
> 
> This repaired it for me. I want to say its just documentation issue rather than a actual bug

Normally, during CI we have a step for `build`, prior to `release`. In those cases, `"dependsOn": ["build"]` might not be required.

**Comment by Jordan-Hall** [comment]
> > ```
> >  "targetDefaults": {
> >    "nx-release-publish": {
> >       "dependsOn": [
> >         "build"
> >       ],
> >       "options": {
> >         "packageRoot": "dist/{projectRoot}"
> >       }
> >     }
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This repaired it for me. I want to say its just documentation issue rather than a actual bug
> 
> Normally, during CI we have a step for `build`, prior to `release`. In those cases, `"dependsOn": ["build"]` might not be required.

While true this enforces it to run. Nx cache will just use the cache build

**Comment by pthorp** [comment]
We are using Nx with an Angular monorepo for the first time, but otherwise extremely experienced with Angular projects.  The monorep project has a few shared libraries, plus 2 apps and we are now trying to release/publish the apps into our own repository, but noticed that the publish was adding the 'src' files, rather than the 'dist' files.

So, as above, we followed the [Nx docs](https://nx.dev/recipes/nx-release/publish-custom-dist-directory) to point at the workspace root 'dist' folder for each app build to include in the tarball being published.  However, as soon as we add the `"nx-release-publish" > "options > "packageRoot": "dist/apps/{projectName}"` into the nx.json, there is a build error running `npx nx release publish --projects=app1 --dry-run --verbose`.
i.e. 
`Error: ENOENT: no such file or directory, open '/projects/my-app/dist/apps/app1/package.json'
    at readFileSync (node:fs:448:20)
    at readJsonFile (/projects/my-app/node_modules/nx/src/utils/fileutils.js:17:43)
 `

However, if the 'nx-release-publish' task is removed from the nx.json, then it builds and **only** includes the package.json 🙄 
i.e.
`
> nx run app1:nx-release-publish


📦  @myOrg/app1@X.X.X-dry-run
=== Tarball Contents ===

310B package.json
=== Tarball Details ===
name:          @myOrg/app1
version:       X.X.X-dry-run                           
filename:      app1-X.X.X-dry-run.tgz   
package size:  266 B                                   
unpacked size: 310 B                                   
shasum:        85e557bb963dc1715a07f6b90d7451cdefa85522
integrity:     sha512-FP5eUbS8qXQ1K[...]lQbQS3EoU4RMQ==
total files:   1                                       
 
Would publish to https://my-org.repo.com/repository/npm-applications/ with tag "latest", but [dry-run] was set

————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target nx-release-publish for project app1
`

Our project is using the following Nx version, along with Angular 18:
>    Node   : 22.3.0
>    OS     : darwin-arm64
>    npm    : 10.8.2
>    
>    nx                 : 18.0.4
>    @nx/js             : 18.0.4
>    @nx/linter         : 18.0.4
>    @nx/eslint         : 18.0.4
>    @nx/workspace      : 18.0.4
>    @nx/devkit         : 18.0.4
>    @nx/eslint-plugin  : 18.0.4
>    @nrwl/tao          : 18.0.4
>    typescript         : 5.3.3
> 

@thdk, I have cloned your repo, I get the same error as I am seeing locally when I run `npx nx release publish --dry-run --verbose`, where the package.json cannot be found.
i.e. 
`Error: ENOENT: no such file or directory, open '/projects/nx-release-ts-packages/dist/packages/my-lib/package.json'
    at readFileSync (node:fs:448:20)
    at readJsonFile (/projects/nx-release-ts-packages/node_modules/nx/src/utils/fileutils.js:17:43)
 `
 
Any help would be greatly appreciated.

**Comment by ThePlenkov** [comment]
To my opinion it should work, but probably this code is the reason:
![image](https://github.com/user-attachments/assets/c9d00783-0645-4d39-9f6a-220debe849b9)

So basically there is a plugin which overwrites target defaults with dependsOn: ['^nx-release-publish']. Because of this it doesn't make sense what you put into target defaults - it's just ignored...

**Comment by ThePlenkov** [comment]
I commented this line in my local node_modules and everything worked well, release now works based on configured graph, not overwritten one: https://github.com/nrwl/nx/blame/c4c8b0150d827657632596656d92040108a338aa/packages/nx/src/utils/package-json.ts#L191

**Comment by ThePlenkov** [comment]
#22720 is a duplicate issue which is also impacted

**Comment by tomavic** [comment]
Hi folks, @lorenzodejong @jeffora @pthorp @cpierceworld @JamesHenry 

I showed this issue to DeepSeen ;) and I got the following configs:


```
// nx.json

...

  "release": {
    "projects": ["libs/**"],
    "projectsRelationship": "fixed",
    "version": {
      "generatorOptions": {
        "currentVersionResolver": "git-tag",
        "specifierSource": "conventional-commits",
        "fallbackCurrentVersionResolver": "disk"
      }
    },
    "changelog": {
      "projectChangelogs": true
    },
    "releaseTagPattern": "release/{projectName}/{version}",
    "git": {
      "commitMessage": "chore({projectName}): 🚀 release {version} [skip-ci]",
      "commit": true
    },
    "conventionalCommits": {
      "types": {
        "feat": {
          "semverBump": "minor"
        },
        "fix": {
          "semverBump": "patch"
        },
        "docs": {
          "semverBump": "patch"
        },
        "chore": {
          "semverBump": "patch"
        },
        "style": {
          "semverBump": "patch"
        },
        "refactor": {
          "semverBump": "patch"
        },
        "perf": {
          "semverBump": "patch"
        },
        "build": {
          "semverBump": "none"
        },
        "release": {
          "semverBump": "none"
        },
        "ci": {
          "semverBump": "patch"
        },
        "revert": {
          "semverBump": "patch"
        }
      }
    }
  }

....

```


```
.azure.pipelines.yaml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_ENV: 'production'

steps:
# Step 1: Checkout the code
- checkout: self
  persistCredentials: true

# Step 2: Set up Node.js 22
- task: UseNode@1
  inputs:
    version: '22.x'

# Step 3: Install dependencies
- script: |
    npm install -g nx
    npm install
  displayName: 'Install Dependencies'

# Step 4: Configure Git
- script: |
    git config --global user.email "ci@example.com"
    git config --global user.name "Azure Pipeline"
  displayName: 'Configure Git'

# Step 5: Run Nx Release with Auto-Response
- script: |
    nx release --yes --verbose
  displayName: 'Run Nx Release (Auto-Response)'

# Step 6: Push Git Tags (if not done automatically by Nx)
- script: |
    git push --follow-tags
  displayName: 'Push Git Tags'

```


I then removed the `--first-release` flag from the ci/cd script
Then I used `nx release --yes --verbose` always to run the release and to force publish


The problem now which has been noticed from comments here, that we need to copy the new package.json with the new changelog.md files after the build and before publish.

Luckily, semantic-release allows this through `exec` plugin, but here you have to create your own publish script?

can't this be added to the nx release workflow?
Come on it's 2025
🎩
