### ISSUE TITLE
 Lerna (powered by Nx)   Daemon process terminated and closed the connection

### ISSUE THREAD

**Issue by nthombare-mdsol** [nrwl/nx#21896]
### Current Behavior

While doing > **npm run build** 
facing Daemon process terminated and closed the connection

More details logs here **.nx/cache/d/daemon.log**

```
node_modules/nx/src/hasher/native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: Missing field `outputs`
    at NativeTaskHasherImpl.hashTasks (/Users/nthombare/Documents/Workspace/message-center-workspace/platform_ui/node_modules/nx/src/hasher/native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (/Users/nthombare/Documents/Workspace/message-center-workspace/platform_ui/node_modules/nx/src/hasher/task-hasher.js:53:50)
    at handleHashTasks (/Users/nthombare/Documents/Workspace/message-center-workspace/platform_ui/node_modules/nx/src/daemon/server/handle-hash-tasks.js:20:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (/Users/nthombare/Documents/Workspace/message-center-workspace/platform_ui/node_modules/nx/src/daemon/server/server.js:110:16)
    at async handleMessage (/Users/nthombare/Documents/Workspace/message-center-workspace/platform_ui/node_modules/nx/src/daemon/server/server.js:84:9)
    at async /Users/nthombare/Documents/Workspace/message-center-workspace/platform_ui/node_modules/nx/src/daemon/server/server.js:45:9 {
  code: 'InvalidArg'
}

Node.js v20.9.0

### Expected Behavior

It is expecting to run proper

### GitHub Repo

_No response_

### Steps to Reproduce

1. We have a private project so we cant share repo details 


### Nx Report

```shell
npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : darwin-x64
   npm    : 10.2.4

   nx          : 17.3.2
   lerna       : 7.4.2
   @nx/devkit  : 16.10.0
   @nrwl/tao   : 17.3.2
   typescript  : 4.9.5
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/devkit@16.10.0
     - @nrwl/devkit@16.10.0

   To fix this, run `nx migrate nx@17.3.2
```

### Failure Logs

```shell
- Done responding to the client project-graph
[NX Daemon Server] - 2024-02-20T15:47:35.418Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 0. Response time: 7.
/node_modules/nx/src/hasher/native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: Missing field `outputs`
    at NativeTaskHasherImpl.hashTasks (node_modules/nx/src/hasher/native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (node_modules/nx/src/hasher/task-hasher.js:53:50)
    at handleHashTasks (node_modules/nx/src/daemon/server/handle-hash-tasks.js:20:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (/node_modules/nx/src/daemon/server/server.js:110:16)
    at async handleMessage (/node_modules/nx/src/daemon/server/server.js:84:9)
    at async /node_modules/nx/src/daemon/server/server.js:45:9 {
  code: 'InvalidArg'
}

Node.js v20.9.0
```

### Package Manager Version

10.2.4

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Without having more information as to your projects configurations this will be hard to troubleshoot.

Can you provide your project graph? Its available via `nx graph --file graph.json`.
