### ISSUE TITLE
Vite - can't import using TS paths in vite.config.ts

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#21908]
### Current Behavior

As we have multiple projects using vite, we have another library that provides some shared configurations.
It seems that TS paths are not resolved when running serve/build, when importing them inside `vite.config.ts` file. e.g:
```ts
import { svgrOptions } from '@repo/tools/svgr'
import { defineConfig } from 'vite'
// ...

export default defineConfig({
  // ...,
  plugins: [
    svgr({ svgrOptions })
  ]
})
```

this throws 
```sh
 NX   Cannot find module '@repo/tools/svgr'
```

### Expected Behavior

Should be able to import from other libraries in TS files

### GitHub Repo

https://github.com/danr-za/vite-imports

### Steps to Reproduce

1. Run `nx serve todos`

### Nx Report

```shell
Node   : 20.11.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx (global)        : 18.0.4
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/react          : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/vite           : 18.0.4
   @nx/web            : 18.0.4
   typescript         : 5.3.3
```

### Failure Logs

```shell
>  NX   Unable to create nodes for apps/todos/vite.config.ts using plugin @nx/vite/plugin. 

   
         Inner Error: Error: Cannot find module '@vite-imports/tools/vite'
   Require stack:
   - /Users/dan/work/vite-imports/apps/todos/vite.config.ts
   - /Users/dan/work/vite-imports/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js
       at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
       at Module._load (node:internal/modules/cjs/loader:985:27)
       at Module.require (node:internal/modules/cjs/loader:1235:19)
       at require (node:internal/modules/helpers:176:18)
       at Object.<anonymous> (/Users/dan/work/vite-imports/apps/todos/vite.config.ts:39:20)
       at Module._compile (node:internal/modules/cjs/loader:1376:14)
       at _require.extensions.<computed> [as .js] (file:///Users/dan/work/vite-imports/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68401:24)
       at Module.load (node:internal/modules/cjs/loader:1207:32)
       at Module._load (node:internal/modules/cjs/loader:1023:12)
       at Module.require (node:internal/modules/cjs/loader:1235:19)
   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by danr-za** [comment]
running vite directly (without nx) throws the same error.
but assuming this is supported in webpack and is wrapped in an nx executor, shouldn't it be supported as well?

**Comment by Coly010** [comment]
Unfortunately not. 

This is an issue from `vite` itself. It "builds" your config file so that it can handle the TS as JS when it starts up. 
It uses its own transpilation to do this, and we can't impact or change how it does that. 

As it is an issue outside the scope of Nx, I'm going to close this issue.
I'm sorry this isn't the result you wanted.
