### ISSUE TITLE
Error: Missing field `version`

### ISSUE THREAD

**Issue by Crocsx** [nrwl/nx#21929]
### Current Behavior

After updating to Nx18, when running `npx nx run core:serve` or other nx command in my monorepo they all fail with 

```

 >  NX   Daemon process terminated and closed the connection

   Please rerun the command, which will restart the daemon.
   If you get this error again, check for any errors in the daemon process logs found in: /Users/crocsx/Documents/Repository/anyx_mono_frontend/.nx/cache/d/daemon.log
 ```
   
### Expected Behavior

Should properly execute Nx command on my monorepo

### Steps to Reproduce

1. I was on v17.2.8
2. I migrated to v18.0.4
3. run migration

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.19.0
   OS     : darwin-arm64
   npm    : 10.2.3
   
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/react          : 18.0.4
   @nx/storybook      : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @webpro/nx-tsc : 0.0.1
```

### Failure Logs

```shell
Node.js v18.17.1
[NX Daemon Server] - 2024-02-22T07:31:20.774Z - Started listening on: /var/folders/0x/z1t3d4s164b_yt7n9dnnqrk80000gn/T/68f34f01c0c503576945/d.sock
[NX Daemon Server] - 2024-02-22T07:31:20.776Z - [WATCHER]: Subscribed to changes within: /Users/crocsx/Documents/Repository/anyx_mono_frontend (native)
[NX Daemon Server] - 2024-02-22T07:31:20.778Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-02-22T07:31:20.779Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-02-22T07:31:20.780Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-02-22T07:31:20.825Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX Daemon Server] - 2024-02-22T07:31:20.825Z - [REQUEST]: 
[NX Daemon Server] - 2024-02-22T07:31:20.825Z - [REQUEST]: 
[NX Daemon Server] - 2024-02-22T07:31:21.247Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2024-02-22T07:31:21.250Z - Time taken for 'total for creating and serializing project graph' 466.8489999999292ms
[NX Daemon Server] - 2024-02-22T07:31:21.251Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-02-22T07:31:21.254Z - Done responding to the client project-graph
[NX Daemon Server] - 2024-02-22T07:31:21.254Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 467. Response time: 7.
[NX Daemon Server] - 2024-02-22T07:31:21.268Z - [REQUEST]: Responding to the client. handleRequestFileData
[NX Daemon Server] - 2024-02-22T07:31:21.271Z - Done responding to the client handleRequestFileData
[NX Daemon Server] - 2024-02-22T07:31:21.271Z - Handled REQUEST_FILE_DATA. Handling time: 5. Response time: 3.
[NX Daemon Server] - 2024-02-22T07:31:21.283Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2024-02-22T07:31:51.750Z - [WATCHER]: nx.json was modified
[NX Daemon Server] - 2024-02-22T07:31:51.750Z - [WATCHER]: Processing file changes in outputs
[NX Daemon Server] - 2024-02-22T07:31:51.855Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX Daemon Server] - 2024-02-22T07:31:51.855Z - [REQUEST]: nx.json
[NX Daemon Server] - 2024-02-22T07:31:51.855Z - [REQUEST]: 
[NX Daemon Server] - 2024-02-22T07:31:51.969Z - Time taken for 'hash changed files from watcher' 3.250416999682784ms
[NX Daemon Server] - 2024-02-22T07:31:52.754Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-02-22T07:31:52.754Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-02-22T07:31:52.754Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-02-22T07:31:52.755Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-02-22T07:31:52.755Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2024-02-22T07:31:52.758Z - Time taken for 'total for creating and serializing project graph' 0.1559999999590218ms
[NX Daemon Server] - 2024-02-22T07:31:52.762Z - Done responding to the client project-graph
[NX Daemon Server] - 2024-02-22T07:31:52.762Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 0. Response time: 7.
[NX Daemon Server] - 2024-02-22T07:31:52.775Z - [REQUEST]: Responding to the client. handleRequestFileData
[NX Daemon Server] - 2024-02-22T07:31:52.779Z - Done responding to the client handleRequestFileData
[NX Daemon Server] - 2024-02-22T07:31:52.779Z - Handled REQUEST_FILE_DATA. Handling time: 6. Response time: 4.
[NX Daemon Server] - 2024-02-22T07:31:52.793Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2024-02-22T07:31:53.434Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-02-22T07:31:53.435Z - Closed a connection. Number of open connections: 0
[NX Daemon Server] - 2024-02-22T07:31:53.435Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-02-22T07:31:53.437Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-02-22T07:31:53.437Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2024-02-22T07:31:53.441Z - Time taken for 'total for creating and serializing project graph' 0.11900000041350722ms
[NX Daemon Server] - 2024-02-22T07:31:53.444Z - Done responding to the client project-graph
[NX Daemon Server] - 2024-02-22T07:31:53.444Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 0. Response time: 7.
/Users/crocsx/Documents/Repository/anyx_mono_frontend/node_modules/nx/src/hasher/native-task-hasher-impl.js:10
        this.projectGraphRef = (0, native_1.transferProjectGraph)((0, transform_objects_1.transformProjectGraphForRust)(projectGraph));
                                                                 ^

Error: Missing field `version`
    at new NativeTaskHasherImpl (/Users/crocsx/Documents/Repository/anyx_mono_frontend/node_modules/nx/src/hasher/native-task-hasher-impl.js:10:66)
    at new InProcessTaskHasher (/Users/crocsx/Documents/Repository/anyx_mono_frontend/node_modules/nx/src/hasher/task-hasher.js:47:15)
    at handleHashTasks (/Users/crocsx/Documents/Repository/anyx_mono_frontend/node_modules/nx/src/daemon/server/handle-hash-tasks.js:18:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (/Users/crocsx/Documents/Repository/anyx_mono_frontend/node_modules/nx/src/daemon/server/server.js:110:16)
    at async handleMessage (/Users/crocsx/Documents/Repository/anyx_mono_frontend/node_modules/nx/src/daemon/server/server.js:84:9)
    at async /Users/crocsx/Documents/Repository/anyx_mono_frontend/node_modules/nx/src/daemon/server/server.js:45:9 {
  code: 'InvalidArg'
}
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I am unsure what version is missing. I followed the migrations and tried to investigate by myself but turn out I can't get 18.0.4 to work.

**Comment by AgentEnder** [comment]
Can you run `nx reset` and check if this goes away? What version did you update from?

**Comment by Crocsx** [comment]
Hi, I was on 17.2.8 I already tried NX reset without success. Also my pipeline and my other computer fail with the same error. Unsure what version is referring to.

On February 23, 2024 04:12:39 Craigory Coppola ***@***.***> wrote:

Can you run nx reset and check if this goes away? What version did you update from?

**Comment by vendramini** [comment]
Hey guys, any news? Did the same here. I updated from the same version @Crocsx did. It's just stopped working. The daemon is not initializing anymore.
```
 NX   Report complete - copy this into the issue template

Node   : 21.6.1
OS     : darwin-arm64
npm    : 10.2.4

nx (global)        : 18.0.4
nx                 : 18.0.5
@nx/js             : 18.0.5
@nx/jest           : 18.0.5
@nx/eslint         : 18.0.5
@nx/workspace      : 18.0.5
@nx/detox          : 18.0.5
@nx/devkit         : 18.0.5
@nx/eslint-plugin  : 18.0.5
@nx/expo           : 18.0.5
@nx/next           : 18.0.5
@nx/react          : 18.0.5
@nx/react-native   : 18.0.5
@nx/storybook      : 18.0.5
@nrwl/tao          : 18.0.5
@nx/web            : 18.0.5
@nx/webpack        : 18.0.5
typescript         : 5.3.3
```

`daemon.log`
```
[NX Daemon Server] - 2024-02-24T23:03:53.425Z - Started listening on: /var/folders/bm/z5qdvvh94_q565bkp7kty3zm0000gn/T/546bd57b103e46acba28/d.sock
[NX Daemon Server] - 2024-02-24T23:03:53.428Z - [WATCHER]: Subscribed to changes within: /Users/vendramini/www/mytestingapp/app (native)
[NX Daemon Server] - 2024-02-24T23:03:53.429Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-02-24T23:03:53.430Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-02-24T23:03:53.431Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-02-24T23:03:53.432Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-02-24T23:03:53.433Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX Daemon Server] - 2024-02-24T23:03:53.433Z - [REQUEST]:
[NX Daemon Server] - 2024-02-24T23:03:53.433Z - [REQUEST]:
[NX Daemon Server] - 2024-02-24T23:03:53.680Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2024-02-24T23:03:53.680Z - Time taken for 'total for creating and serializing project graph' 247.882292ms
[NX Daemon Server] - 2024-02-24T23:03:53.683Z - Done responding to the client project-graph
[NX Daemon Server] - 2024-02-24T23:03:53.683Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 248. Response time: 3.
/Users/vendramini/www/mytestingapp/app/node_modules/nx/src/hasher/native-task-hasher-impl.js:10
        this.projectGraphRef = (0, native_1.transferProjectGraph)((0, transform_objects_1.transformProjectGraphForRust)(projectGraph));
                                                                 ^

Error: Missing field `version`
    at new NativeTaskHasherImpl (/Users/vendramini/www/mytestingapp/app/node_modules/nx/src/hasher/native-task-hasher-impl.js:10:66)
    at new InProcessTaskHasher (/Users/vendramini/www/mytestingapp/app/node_modules/nx/src/hasher/task-hasher.js:47:15)
    at handleHashTasks (/Users/vendramini/www/mytestingapp/app/node_modules/nx/src/daemon/server/handle-hash-tasks.js:18:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (/Users/vendramini/www/mytestingapp/app/node_modules/nx/src/daemon/server/server.js:110:16)
    at async handleMessage (/Users/vendramini/www/mytestingapp/app/node_modules/nx/src/daemon/server/server.js:84:9)
    at async /Users/vendramini/www/mytestingapp/app/node_modules/nx/src/daemon/server/server.js:45:9 {
  code: 'InvalidArg'
}

Node.js v21.6.1
```

![image](https://github.com/nrwl/nx/assets/510878/62ca77c4-3af1-43ae-957f-1683fcd7f7b0)

**Comment by vendramini** [comment]
News: I deleted node_modules and all caches from all projects plus the .nx folder, restarted the machine e reinstalled everything. It's working now...

**Comment by vergilfromadyen** [comment]
This happened to me too. The issue seems to come from [this issue](https://github.com/npm/cli/issues/4828). My project has the following config:
```json
    "optionalDependencies": {
        "@esbuild/darwin-x64": "^0.19.12",
        "@esbuild/darwin-arm64": "^0.19.12",
        "@esbuild/linux-x64": "^0.19.12",
        "@nx/nx-darwin-arm64": "18.0.8",
        "@nx/nx-darwin-x64": "18.0.8",
        "@nx/nx-linux-x64-gnu": "18.0.8",
        "@rollup/rollup-darwin-x64": "4.12.0",
        "@rollup/rollup-linux-x64-gnu": "4.12.0",
        "@swc/core-darwin-x64": "1.4.1",
        "@swc/core-linux-x64-gnu": "1.4.1"
    },
```

Specifically, adding the `@esbuild/*` packages solved it for me.

**Comment by Gugustinette** [comment]
I'm getting this exact error, after many months of using NX. This happens with both 17.2.6 (Local) and 18.2.1 (Global).
I use Node 20 on MacOS ARM.

I did not change anything to my configuration so I really don't know what happened, but I basically can't do anything on my project from now on 😭

**Comment by thoroc** [comment]
@Gugustinette did you have a stray `.nx` directory by any chance?

**Comment by Gugustinette** [comment]
@thoroc Nop, I did `rm -rf` the `.nx` directory 😕

**Comment by vergilfromadyen** [comment]
@Gugustinette it's not a weird NX cache issue, it's a bug in npm. My comment above references both the issue and what I expect would fix it for you.

I updated my snippet to include arm64 packages. Windows users may need to add windows packages to their optional dependencies.

**Comment by Gugustinette** [comment]
@vergilfromadyen I remember trying something like that when the problem was still there, but not 100% sure. I'll make sure to try it if I face this issue again. Thanks !

**Comment by pr033r** [comment]
I got probably similar issue. Same error log and when I open daemon logs it shows me this:
`
C:\Users\lasakada\Desktop\cis-cloud\cloud-cis-ui\node_modules\nx\src\hasher\native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: Failed to convert JavaScript value `Object {"base":"dist/apps/app"}` into rust type `String`
    at NativeTaskHasherImpl.hashTasks (C:\Users\lasakada\Desktop\cis-cloud\cloud-cis-ui\node_modules\nx\src\hasher\native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (C:\Users\lasakada\Desktop\cis-cloud\cloud-cis-ui\node_modules\nx\src\hasher\task-hasher.js:53:50)
    at handleHashTasks (C:\Users\lasakada\Desktop\cis-cloud\cloud-cis-ui\node_modules\nx\src\daemon\server\handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (C:\Users\lasakada\Desktop\cis-cloud\cloud-cis-ui\node_modules\nx\src\daemon\server\server.js:110:16)
    at async handleMessage (C:\Users\lasakada\Desktop\cis-cloud\cloud-cis-ui\node_modules\nx\src\daemon\server\server.js:84:9)
    at async C:\Users\lasakada\Desktop\cis-cloud\cloud-cis-ui\node_modules\nx\src\daemon\server\server.js:45:9 {
  code: 'StringExpected'
}
`

I did all necessary steps. nx reset, delete node_modules, npm i --legacy-peer-deps but nothing helped.

**Comment by thoroc** [comment]
Keep it

**Comment by rlindgren** [comment]
For what it's worth to anyone else who runs in to this problem: I was blocked on it and did some debugging of our decently large codebase.  I dug in to the error trace and found that the input to `require('@nx/nx-darwin-x64').transferProjectGraph` appeared to include some `dependencies` with `undefined` version.  see screenshot below.  I noticed some old @nrwl/[lib]s that were lingering around in one of the apps package.json.  I removed those, wiped all node_modules folders and package-lock.json files, ran `nx reset` and re-installed.  It was finally resolved after trying all of the above recommendations multiple times to no avail.  I won't say that this is the reason for the resolution however... While installing, I realized that the installation completed much faster this time, whereas previously it would take 10 minutes or more.  So, that got me thinking about some issues I experienced with npm recently when installing in low or sparse connectivity (could have been registry-related too in some instances..... 🤷 ) where packages appeared to only end up being partially installed (missing files).  It is probably not insignificant that this final installation was executed in a different room of my house, much closer to the wifi router....  so, I don't have an answer, unfortunately, but that's my story.  Maybe it will help.  It seems likely that I didn't have to remove those deps, especially based on other commenter's experiences, and just make sure I had a stronger wifi connection while installing.  I would explore further, but there is actual work to do.  
```
Nx Version:
- Local: v17.3.1
```
<img width="657" alt="image" src="https://github.com/nrwl/nx/assets/2103315/656b96a1-b1b6-4da8-9e20-799b570b9666">

**Comment by sale1234** [comment]
I downgraded the angular version, and after that, this problem occurred.  

The fix was that I removed node_modules and .nx folder, restarted the computer then ran npm install, and after that new package-lock.json file was created. That file was my fix, if I have removed this file, a bug would persist, but If I use this newly generated package-lock.json everything would work fine.

**Comment by GrayedFox** [comment]
We have a local node module referenced inside our package.json like so:

```json
{
      "multer-s3": "file:local_node_modules/multer-s3",
}
```

NX stores a local cached copy of the project root package.json inside `project/.nx/workspace-data/parsed-lock-file.json` and sometimes it gets populated with an entry that lists the local dependency without a version number:

![Image](https://github.com/user-attachments/assets/ccf82441-6560-4291-8599-331afba3fef1)

To get the NX daemon working again I just delete the entry without a version number and that seems to fix it. Happens sometimes after an `nx reset` 🤷🏽
