### ISSUE TITLE
playwright plugin crashes on dotenv.config in playwright config

### ISSUE THREAD

**Issue by EelcoLos** [nrwl/nx#21982]
### Current Behavior

When trying to migrate to the nx plugin of playwright with the playwright config having `dotenv.config()` before the actual config, ie:

```ts
import type { PlaywrightTestConfig } from '@playwright/test';
import dotenv from 'dotenv';

dotenv.config();

const config: PlaywrightTestConfig = {
	...baseConfig,
	use: {
		baseURL: process.env.BASEURL,
		trace: 'on',
```

the `nx show project e2e --web` will throw an error:

> CreateNodesError: Unable to create nodes for apps/e2e/playwright.config.ts using plugin @nx/playwright/plugin.
> Inner Error: TypeError: Cannot read properties of undefined (reading 'config')

### Expected Behavior

for the playwright config to use `dotenv` for using local environment variables

### Steps to Reproduce

1. have an existing repo with a playwright setup
2. in the `playwright.config.ts`, use `dotenv.config` before your playwright config, and set the baseURL to use `dotenv`
3. add the nx playwright plugin: `nx add @nx/playwright`
4. try to run `nx graph`, or the aforementioned `nx show project e2e --web`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.5

nx (global)        : 18.0.1
nx                 : 18.0.5
@nx/js             : 18.0.5
@nx/jest           : 18.0.5
@nx/linter         : 18.0.5
@nx/eslint         : 18.0.5
@nx/workspace      : 18.0.5
@nx/angular        : 18.0.5
@nx/cypress        : 18.0.5
@nx/devkit         : 18.0.5
@nx/eslint-plugin  : 18.0.5
@nx/playwright     : 18.0.5
@nx/plugin         : 18.0.5
@nrwl/tao          : 18.0.5
@nx/web            : 18.0.5
@nx/webpack        : 18.0.5
typescript         : 5.3.3
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome : 0.14.1
@ngrx/component                  : 17.1.0
@ngrx/component-store            : 17.1.0
@ngrx/effects                    : 17.1.0
@ngrx/entity                     : 17.1.0
@ngrx/router-store               : 17.1.0
@ngrx/schematics                 : 17.1.0
@ngrx/store                      : 17.1.0
@ngrx/store-devtools             : 17.1.0
@nx-dotnet/core                  : 2.2.0
---------------------------------------
```

### Failure Logs

```shell
NX   Unable to create nodes for apps/e2e/playwright.config.ts using plugin @nx/playwright/plugin.


         Inner Error: TypeError: Cannot read properties of undefined (reading 'config')
    at Object.<anonymous> (D:\test\apps\e2e\playwright.config.ts:10:17)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\test\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .ts] (D:\test\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.Mod.require (D:\test\node_modules\nx\bin\init-local.js:145:36)
    at require (node:internal/modules/helpers:176:18)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

when I removed the plugin and used the original task, the normal playwright task works.

**Comment by knoefel** [comment]
Experiencing the same issue, any news on this?

**Comment by leosvelperez** [comment]
Thanks for reporting this!

It looks like you're using a non-existent default import from `dotenv`. Please change your `dotenv` usage to one of:

```ts
import * as dotenv from 'dotenv';
dotenv.config();
```

```ts
import { config } from 'dotenv';
config();
```

```ts
const dotenv = require('dotenv');
dotenv.config();
```

See https://www.npmjs.com/package/dotenv#%EF%B8%8F-usage for more info.
