### ISSUE TITLE
Error Cannot find module '@angular-devkit/core'while creating a new workspace

### ISSUE THREAD

**Issue by alexandru-tomescu** [nrwl/nx#220]
Hi, I'm getting an error while creating a new NX workspace.
This is the stack:

```
13:12:51, 49, tests $ create-nx-workspace test-nx-workspace
Creating a sandbox with the CLI and Nx Schematics...
[fsevents] Success: "/private/var/folders/dr/xc69fqyx39s_ylv0pvd_drmw0000gn/T/tmp-127240p7zW4WV2SiQ/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
Cached binary found at /Users/alex/.npm/node-sass/4.7.2/darwin-x64-48_binding.node
Binary found at /private/var/folders/dr/xc69fqyx39s_ylv0pvd_drmw0000gn/T/tmp-127240p7zW4WV2SiQ/node_modules/node-sass/vendor/darwin-x64-48/binding.node
Testing binary
Binary is fine
added 1009 packages in 57.806s
ng new "test-nx-workspace" --collection=@nrwl/schematics
module.js:471
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/var/folders/dr/xc69fqyx39s_ylv0pvd_drmw0000gn/T/tmp-127240p7zW4WV2SiQ/node_modules/@angular-devkit/schematics/src/tree/virtual.js:10:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
child_process.js:524
    throw err;
    ^

Error: Command failed: /var/folders/dr/xc69fqyx39s_ylv0pvd_drmw0000gn/T/tmp-127240p7zW4WV2SiQ/node_modules/.bin/ng new "test-nx-workspace" --collection=@nrwl/schematics
    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/@nrwl/schematics/bin/create-nx-workspace.js:39:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
13:14:15, 50, tests $ ng new "test-nx-workspace" --collection=@nrwl/schematics
Cannot find module '@angular-devkit/schematics'
Error: Cannot find module '@angular-devkit/schematics'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@nrwl/schematics/src/collection/application/index.js:11:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Packages versions:
Angular CLI: 1.6.5
Node: 6.10.3
npm: 5.6.0
OS: MacOS High Sierra 10.13.2 (darwin x64)

Thank you :)

**Comment by alexandru-tomescu** [comment]
This is a duplicate of this issue: #213
