### ISSUE TITLE
`nx release` creates an invalid version tag

### ISSUE THREAD

**Issue by ebo-zig** [nrwl/nx#22011]
### Current Behavior

We are running `nx release --yes` in a Jenkins pipeline with the next release config in the `nx.json`:
```
"release": {
    "version": {
        "conventionalCommits": true
    }
}
```

When there are new commits in the main branch which shouldn't trigger a new release, the release command wants to create a tag without a version:

```
 >  NX   Tagging commit with git

Tagging the current commit in git with the following command:
git tag --annotate v{version} --message v{version}
```

### Expected Behavior

No tag should be created if there isn't a new version to release

### GitHub Repo

https://github.com/ebo-zig/nx-repo

### Steps to Reproduce

1. Create a Nx workspace with `nx release`
2. Configure `nx release`
```
"release": {
    "version": {
        "conventionalCommits": true
    }
}
```
3. Commit a change in conventional commit message format (for example: `feat(is-odd): initial commit`)
4. Release the changes by running`npx nx release --first-release --skip-publish` (a new release with tag v0.1.0 is created)
6. Run the release again by running `npx nx release --skip-publish` (a new release with tag v{version} is created)

### Nx Report

```shell
Node   : 20.11.0
OS     : darwin-x64
npm    : 10.2.4

nx             : 18.0.5
@nx/js         : 18.0.5
@nx/workspace  : 18.0.5
@nx/devkit     : 18.0.5
@nrwl/tao      : 18.0.5
typescript     : 5.3.3
```

### Failure Logs

```shell
nx-repo % npx nx release --skip-publish --verbose      

 NX   Running release version for project: is-even

is-even 🔍 Reading data for package "is-even" from packages/is-even/package.json
is-even 📄 Resolved the current version as 0.1.0 from git tag "v0.1.0".
is-even 🚫 No changes were detected using git history and the conventional commits standard.
is-even 🚫 Skipping versioning "is-even" as no changes were detected.

 NX   Running release version for project: is-odd

is-odd 🔍 Reading data for package "is-odd" from packages/is-odd/package.json
is-odd 📄 Using the current version 0.1.0 already resolved from git tag "v0.1.0".
is-odd 🚫 Skipping versioning "is-odd" as no changes were detected.


 NX   Updating npm lock file

Updating package-lock.json with the following command:
npm install --package-lock-only

 NX   Staging changed files with git

Staging files in git with the following command:
git add package-lock.json

 NX   No changes detected for changelogs

No changes were detected for any changelog files, so no changelog entries will be generated.


 NX   Committing changes with git

Committing files in git with the following command:
git commit --message chore(release): publish {version}

No staged files found. Skipping commit.

 NX   Tagging commit with git

Tagging the current commit in git with the following command:
git tag --annotate v{version} --message v{version}

 NX   Unexpected error when creating tag v{version}:


fatal: tag 'v{version}' already exists


Error: Unexpected error when creating tag v{version}:

fatal: tag 'v{version}' already exists

    at gitTag (nx-repo/node_modules/nx/src/command-line/release/utils/git.js:154:15)
    at async release (nx-repo/node_modules/nx/src/command-line/release/release.js:86:13)
```

### Package Manager Version

10.2.4

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
Hi @ebo-zig, I'm very sorry for the delay in formally acknowledging this one, it was fixed a while ago by https://github.com/nrwl/nx/pull/22800
