### ISSUE TITLE
running nx giving Error: Cannot find module 'ansi-styles'

### ISSUE THREAD

**Issue by KranzAklilu** [nrwl/nx#22024]
### Current Behavior

I initialized the repo with npm create nx-workspace my-app --preset=react-monorepo\
and when I run nx I get
Error: Cannot find module 'ansi-styles'

### Expected Behavior

for it to run successfully

### Steps to Reproduce

1.npm create nx-workspace SPO-AdminPanel --preset=react-monorepo
2. any nx command inside the app

### Nx Report

```shell
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'ansi-styles'
Require stack:
- /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/chalk/source/index.js
- /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/code-frames.js
- /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/json.js
- /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/fileutils.js
- /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/workspace-root.js
- /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/find-workspace-root.js
- /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/bin/nx.js
- /home/kranua/.nvm/versions/node/v18.18.1/lib/node_modules/nx/bin/nx.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/chalk/source/index.js:2:20)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/chalk/source/index.js',
    '/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/code-frames.js',
    '/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/json.js',
    '/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/fileutils.js',
    '/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/workspace-root.js',
    '/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/find-workspace-root.js',
    '/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/bin/nx.js',
    '/home/kranua/.nvm/versions/node/v18.18.1/lib/node_modules/nx/bin/nx.js'
  ]
}

Node.js v18.18.1
```

### Package Manager Version

npm: 10.4.0

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information
Nx Version:
- Local: v18.0.5
- Global: v18.0.5
node v18.18.1
npm -v 10.4.0

**Comment by KranzAklilu** [comment]
everything works perfectly when i add ansi-styles to the dependencies in my package.json but is this the expected behavior?

**Comment by KranzAklilu** [comment]
if i add ansi-styles to my dependencies I get
/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/chalk/source/index.js:2
const ansiStyles = require('ansi-styles');
                   ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/ansi-styles/index.js from /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/chalk/source/index.js not supported.
Instead change the require of /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/ansi-styles/index.js in /home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/chalk/source/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/chalk/source/index.js:2:20)
    at Object.<anonymous> (/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/code-frames.js:5:15)
    at Object.<anonymous> (/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/json.js:7:23)
    at Object.<anonymous> (/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/fileutils.js:4:16)
    at Object.<anonymous> (/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/workspace-root.js:5:21)
    at Object.<anonymous> (/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/src/utils/find-workspace-root.js:4:26)
    at Object.<anonymous> (/home/kranua/main/dev/fiverr/ale_pereira/SPO-AdminPanel/node_modules/nx/bin/nx.js:4:31) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.1

**Comment by jaysoo** [comment]
For the `Cannot find module 'ansi-styles'` error, it might be how the packages are hoisted by npm. Can you run `npm ls ansi-styles` and paste the result?

Also, can you remove `node_modules` and reinstall to see if the error goes away?

For the ESM subsequent error, do you have `"type": "module"` set in `package.json`? If that is set, then Node will load ESM rather than CJS.

**Comment by KranzAklilu** [comment]
thanks for the suggestion. removing node_modules didn't work for me. But creating a new workspace with yarn worked. I think it was an npm problem
