### ISSUE TITLE
ReferenceError: __filename is not defined in ES module scope

### ISSUE THREAD

**Issue by AceissBob** [nrwl/nx#22050]
### Current Behavior

When I run the nx e2e <app> --ui command, I get this error

### Expected Behavior

I expect it to open the UI tool to run the tests

### Steps to Reproduce

1. run nx e2e <app> --ui in the root

### Nx Report

```shell
Node   : 20.11.1
OS     : darwin-arm64
npm    : 9.8.1

nx (global)        : 18.0.2
nx                 : 18.0.5
@nx/js             : 18.0.5
@nx/linter         : 18.0.5
@nx/eslint         : 18.0.5
@nx/workspace      : 18.0.5
@nx/devkit         : 18.0.5
@nx/eslint-plugin  : 18.0.5
@nx/playwright     : 18.0.5
@nx/react          : 18.0.5
@nrwl/tao          : 18.0.5
@nx/vite           : 18.0.5
@nx/web            : 18.0.5
typescript         : 5.3.3
```

### Failure Logs

```shell
❯ nx e2e <app> --ui                                                                                                                        node 🤖 v20.11.1  [🕙 09:55:17 AM ] 

> nx run <app>:e2e --ui


 NX   Ensuring Playwright is installed.

use --skipInstall to skip installation.

Removing unused browser at .../ms-playwright/chromium-1097
Removing unused browser at .../ms-playwright/firefox-1438
Removing unused browser at .../ms-playwright/webkit-1967
Downloading Chromium 123.0.6312.4 (playwright build v1105) from https://playwright.azureedge.net/builds/chromium/1105/chromium-mac-arm64.zip
133.1 MiB [====================] 100% 0.0s
Chromium 123.0.6312.4 (playwright build v1105) downloaded to .../ms-playwright/chromium-1105
Downloading Firefox 123.0 (playwright build v1440) from https://playwright.azureedge.net/builds/firefox/1440/firefox-mac-13-arm64.zip
76.7 MiB [====================] 100% 0.0s
Firefox 123.0 (playwright build v1440) downloaded to .../ms-playwright/firefox-1440
Downloading Webkit 17.4 (playwright build v1983) from https://playwright.azureedge.net/builds/webkit/1983/webkit-mac-13-arm64.zip
65 MiB [===============     ] 73% 2.5sError: Request to https://playwright.azureedge.net/builds/webkit/1983/webkit-mac-13-arm64.zip timed out after 30000ms
    at ClientRequest.rejectOnTimeout (.../node_modules/playwright-core/lib/utils/network.js:79:15)
    at Object.onceWrapper (node:events:632:28)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:840:9)
    at Object.onceWrapper (node:events:632:28)
    at TLSSocket.emit (node:events:530:35)
    at Socket._onTimeout (node:net:589:8)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Downloading Webkit 17.4 (playwright build v1983) from https://playwright-akamai.azureedge.net/builds/webkit/1983/webkit-mac-13-arm64.zip
65 MiB [====================] 100% 0.0s
Webkit 17.4 (playwright build v1983) downloaded to .../ms-playwright/webkit-1983
ReferenceError: __filename is not defined in ES module scope
    at file:///.../playwright.config.ts:9:18
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at requireOrImport (.../node_modules/playwright/lib/transform/transform.js:192:26)
    at loadUserConfig (.../node_modules/playwright/lib/common/configLoader.js:96:46)
    at loadConfig (.../node_modules/playwright/lib/common/configLoader.js:101:22)
    at loadConfigFromFileRestartIfNeeded (.../node_modules/playwright/lib/common/configLoader.js:257:10)
    at runTests (.../node_modules/playwright/lib/program.js:167:18)
    at t.<anonymous> (.../node_modules/playwright/lib/program.js:53:7)

—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target e2e for project xxx (1m)

    With additional flags:
      --ui=true

  ✖    1/1 failed
  ✔    0/1 succeeded [0 read from cache]
```

### Package Manager Version

9.8.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

this is the playwright.config.ts contents

```
import { workspaceRoot } from '@nx/devkit'
import { nxE2EPreset } from '@nx/playwright/preset'
import { defineConfig, devices } from '@playwright/test'

require('dotenv').config()

const baseURL = process.env['E2E_URL'] || 'http://localhost:4200'
export default defineConfig({
  ...nxE2EPreset(__filename, { testDir: './e2e' }),

  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  workers: process.env.CI ? 1 : undefined,
  use: {
    baseURL,
    trace: 'on-first-retry',
  },
  webServer: {
    command: 'nx serve <app> --port 4200',
    url: baseURL,
    reuseExistingServer: !process.env.CI,
    cwd: workspaceRoot,
  },
  projects: [
    { name: 'setup', testMatch: 'auth.setup.ts' },
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
      dependencies: ['setup'],
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
      dependencies: ['setup'],
    },
  ],
})

```

**Comment by AceissBob** [comment]
I found the reason. The default expects you to be running type: commonjs, We have ours set to module. the __filename does not exist in this state.

Adding this to the config solves the issue. 

import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);

Maybe this could be added to the documentation.
