### ISSUE TITLE
New outputPath object structure not compatible with @angular-devkit/build-angular:extract-i18n

### ISSUE THREAD

**Issue by bubblegumsoldier** [nrwl/nx#22067]
### Current Behavior

I have realized that if I have a build configuration with a build target like this (simplified)

```json
{
  "...": "...",
  "targets": {
    "build": {
      "executor": "@nx/angular:application",
      "outputs": [
        "{options.outputPath}"
      ],
      "dependsOn": [],
      "options": {
        "...": "...",
        "outputPath": {
          "base": "dist/apps/my-app",
          "browser": ""
        }
      }
    }
  }
}
```

And another target for `extract-i18n` like this

```json
{
  "...": "...",
  "extract-i18n": {
    "executor": "@angular-devkit/build-angular:extract-i18n",
    "options": {
      "buildTarget": "my-app:build",
      "outFile": "messages.xlf",
      "outputPath": "apps/my-app/src/locale",
      "progress": true
    }
  }
}
```

I get the following error

```
 NX   The "path" argument must be of type string. Received an instance of Object


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at new NodeError (node:internal/errors:400:5)
    at validateString (node:internal/validators:163:11)
    at Object.resolve (node:path:167:9)
    at getCommonConfig (C:\Users\hmues\repos\freezingdata-client\node_modules\@angular-devkit\build-angular\src\tools\webpack\configs\common.js:275:24)        
    at async Promise.all (index 2)
    at async generateWebpackConfig (C:\Users\hmues\repos\freezingdata-client\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:60:22)
    at async generateBrowserWebpackConfigFromContext (C:\Users\hmues\repos\freezingdata-client\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:117:20)
    at async extractMessages (C:\Users\hmues\repos\freezingdata-client\node_modules\@angular-devkit\build-angular\src\builders\extract-i18n\webpack-extraction.js:52:24)
    at async execute (C:\Users\hmues\repos\freezingdata-client\node_modules\@angular-devkit\build-angular\src\builders\extract-i18n\builder.js:85:28)
```

I validated the assumption that the outputPath of the build-object used for extract-i18n cannot be an outputPath by adding a separate configuration for building like this

```json
{
  "targets": {
    "build": {
      "configurations": {
        "no-output-path-object": {
          "outputPath": "dist/apps/my-app"
        }
      }
    }
  }
}
```

and used that as my `buildTarget` in the `extract-i18n` target.

This workaround is okayish but should at least be documented somewhere.

### Expected Behavior

`@angular-devkit/build-angular:extract-i18n` should work with build-targets that define an outputPath object.

### Steps to Reproduce

see above

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.13.0
OS     : win32-x64
npm    : 8.19.3

nx                 : 18.0.5
@nx/js             : 18.0.4
@nx/jest           : 18.0.4
@nx/linter         : 18.0.4
@nx/eslint         : 18.0.4
@nx/workspace      : 18.0.4
@nx/angular        : 18.0.4
@nx/cypress        : 18.0.4
@nx/devkit         : 17.2.8
@nx/esbuild        : 18.0.4
@nx/eslint-plugin  : 18.0.4
@nrwl/tao          : 18.0.5
@nx/web            : 18.0.4
@nx/webpack        : 18.0.4
typescript         : 5.3.3
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome : 0.10.2
apollo-angular                   : 6.0.0
ngx-build-plus                   : 17.0.0
---------------------------------------
The following packages should match the installed version of nx
  - @nx/js@18.0.4
  - @nrwl/js@18.0.4
  - @nx/jest@18.0.4
  - @nrwl/jest@18.0.4
  - @nx/linter@18.0.4
  - @nx/eslint@18.0.4
  - @nrwl/linter@18.0.4
  - @nx/workspace@18.0.4
  - @nrwl/workspace@18.0.4
  - @nx/angular@18.0.4
  - @nrwl/angular@18.0.4
  - @nx/cypress@18.0.4
  - @nrwl/cypress@18.0.4
  - @nx/devkit@17.2.8
  - @nrwl/devkit@17.2.8
  - @nx/esbuild@18.0.4
  - @nrwl/esbuild@18.0.4
  - @nx/eslint-plugin@18.0.4
  - @nrwl/eslint-plugin-nx@18.0.4
  - @nx/web@18.0.4
  - @nrwl/web@18.0.4
  - @nx/webpack@18.0.4
  - @nrwl/webpack@18.0.4

To fix this, run `nx migrate nx@18.0.5`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This is caused by the same underlying issue that was fixed by https://github.com/nrwl/nx/pull/21802. You can see in the error logs that webpack is being used to build the application instead of esbuild. This issue has already been fixed, and it will be released in Nx v18.1 soon.
