### ISSUE TITLE
NX Remix recipe and other yarn berry (4) issues

### ISSUE THREAD

**Issue by PatrickMunsey** [nrwl/nx#22062]
### Current Behavior

I've upgraded my workspace from yarn 1 to yarn berry (4). My existing projects are working fine after the migration however i've recently tried to start a new remix project using the [nx remix recipe](https://nx.dev/recipes/react/remix) which isn't working. I tried using the recipe in a new workspace and realised that it worked with yarn 1 but not yarn berry (>2).

### Expected Behavior

I would like for the nx remix integrations/plugins/recipes to work with an nx workspace that is using yarn 4.

### GitHub Repo

https://github.com/PatrickMunsey/remix-yarn-investigation

### Steps to Reproduce

# Setup Workspace and nx remix project

```sh
# Setup nx workspace
npx create-nx-workspace remix-yarn-investigation

# ✔ Which stack do you want to use? · react
# ✔ What framework would you like to use? · none
# ✔ Integrated monorepo, or standalone project? · integrated
# ✔ Application name · app-react
# ✔ Which bundler would you like to use? · vite
# ✔ Test runner to use for end to end (E2E) tests · playwright
# ✔ Default stylesheet format · css
# ✔ Set up CI with caching, distribution and test deflaking · skip
# ✔ Would you like remote caching to make your build faster? · skip


# Open Project
cd remix-yarn-investigation
# or
code -r remix-yarn-investigation

# Generate remix project
yarn nx add @nx/remix
npx nx generate @nx/remix:application --directory=apps/app-remix --name=app-remix --e2eTestRunner=playwright --projectNameAndRootFormat=as-provided --no-interactive


# Running tasks works
yarn nx run app-remix:lint
yarn nx run app-remix:typecheck
yarn nx run app-remix:build
yarn nx run app-remix:test
yarn nx run app-remix:serve
yarn nx run app-remix:start
yarn nx run app-remix-e2e:e2e

```

# Upgrade yarn from 1 to berry/4

```sh
yarn --version # @1.22.21 by default
corepack enable
```

add the following line to the `package.json` file

```json
  "packageManager": "yarn@4.1.0",
```

run yarn to upgrade

```sh
yarn
```

add the followiung to a `.yarnrc.yml` file in the workspace root

```yml
nodeLinker: node-modules
enableGlobalCache: false
```

add the following line to the `.gitignore` file in the workspace root

```sh
# Yarn files
.yarn
!.yarn/cache
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions
```

# Running remix tasks no longer works

```sh
yarn nx run app-remix:lint # failed can't find eslint
yarn nx run app-remix:typecheck # success
yarn nx run app-remix:build # success
yarn nx run app-remix:test # failed can't find vitest
yarn nx run app-remix:serve # failed with message about package composition
yarn nx run app-remix:start # success
yarn nx run app-remix-e2e:e2e # failed with message about package composition

```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : linux-x64
yarn   : 4.1.0

nx                 : 18.0.5
@nx/js             : 18.0.5
@nx/linter         : 18.0.5
@nx/eslint         : 18.0.5
@nx/workspace      : 18.0.5
@nx/cypress        : 18.0.5
@nx/devkit         : 18.0.5
@nx/eslint-plugin  : 18.0.5
@nx/playwright     : 18.0.5
@nx/react          : 18.0.5
@nx/remix          : 18.0.5
@nrwl/tao          : 18.0.5
@nx/vite           : 18.0.5
@nx/web            : 18.0.5
typescript         : 5.3.3
```

### Failure Logs

```shell
*  Executing task: yarn nx run app-remix:serve 


> nx run app-remix:serve


 💿  remix dev

/home/patrick-munsey/repos/remix-yarn-investigation/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: yarn bin
Usage Error: The nearest package directory (/home/patrick-munsey/repos/remix-yarn-investigation/apps/app-remix) doesn't seem to be part of the project declared in /home/patrick-munsey/repos/remix-yarn-investigation.

- If /home/patrick-munsey/repos/remix-yarn-investigation isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /home/patrick-munsey/repos/remix-yarn-investigation is intended to be a project, it might be that you forgot to list apps/app-remix in its workspace configuration.
- Finally, if /home/patrick-munsey/repos/remix-yarn-investigation is fine and you intend apps/app-remix to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.

$ yarn bin [-v,--verbose] [--json] [name]
    at makeError (/home/patrick-munsey/repos/remix-yarn-investigation/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/patrick-munsey/repos/remix-yarn-investigation/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async detectBin (/home/patrick-munsey/repos/remix-yarn-investigation/node_modules/@remix-run/dev/dist/devServer_unstable/index.js:107:7)
    at async Object.serve (/home/patrick-munsey/repos/remix-yarn-investigation/node_modules/@remix-run/dev/dist/devServer_unstable/index.js:135:13) {
  shortMessage: 'Command failed with exit code 1: yarn bin',
  command: 'yarn bin',
  escapedCommand: 'yarn bin',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: "\x1B[31m\x1B[1mUsage Error\x1B[22m\x1B[39m: The nearest package directory (\x1B[38;2;215;95;215m/home/patrick-munsey/repos/remix-yarn-investigation/apps/app-remix\x1B[39m) doesn't seem to be part of the project declared in \x1B[38;2;215;95;215m/home/patrick-munsey/repos/remix-yarn-investigation\x1B[39m.\n" +
    '\n' +
    "- If \x1B[38;2;215;95;215m/home/patrick-munsey/repos/remix-yarn-investigation\x1B[39m isn't intended to be a project, remove any yarn.lock and/or package.json file there.\n" +
    '- If \x1B[38;2;215;95;215m/home/patrick-munsey/repos/remix-yarn-investigation\x1B[39m is intended to be a project, it might be that you forgot to list \x1B[38;2;215;95;215mapps/app-remix\x1B[39m in its workspace configuration.\n' +
    '- Finally, if \x1B[38;2;215;95;215m/home/patrick-munsey/repos/remix-yarn-investigation\x1B[39m is fine and you intend \x1B[38;2;215;95;215mapps/app-remix\x1B[39m to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.\n' +
    '\n' +
    '\x1B[1m$ \x1B[22myarn bin [-v,--verbose] [--json] [name]',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v20.10.0

 NX   Remix app exited with code 1

Pass --verbose to see the stacktrace.


———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target serve for project app-remix failed

Failed tasks:

- app-remix:serve
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Thank you for bringing this issue to our attention! I want to assure you that I will take a look as soon as I can. Your patience and understanding in this matter is greatly appreciated.

**Comment by Coly010** [comment]
I've pushed a PR to your repo. https://github.com/PatrickMunsey/remix-yarn-investigation/pull/1

With Latest Nx, this all works as expected, some commands needed changing and the remix apps needed added to `workspaces` in the a`package.json`.

The remix recipe will be updated also to reflect some of the changes.
