### ISSUE TITLE
Issue with releasing changelogs in GitHub workflows (ERR_BAD_RESPONSE)

### ISSUE THREAD

**Issue by someguynamedmatt** [nrwl/nx#22105]
### Current Behavior

I'm trying to work with `nx release` in my GitHub workflow, but I'm coming across an issue that is suggesting I post here. The workflow step (below), works completely fine locally and I'm using the same GitHub PAT in CI as I am on my machine. I'm unsure of what's going on. 

### Expected Behavior

`nx release` successfully creates a release on target repo.

### Steps to Reproduce
```
  last_tag=$(git tag --sort=creatordate | grep -E 'shhh@[0-9]+\.[0-9]+\.[0-9]+-prod' | tail -1)
  npx nx release changelog 100.0.0 -p shhh --from ${last_tag} --to shhh@100.0.0
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.17.0
OS     : linux-x64
npm    : 9.6.7

nx                      : 18.0.6
@nx/js                  : 18.0.3
@nx/jest                : 18.0.3
@nrwl/jest              : 17.1.3
@nx/linter              : 18.0.3
@nx/eslint              : 18.0.3
@nx/workspace           : 18.0.3
@nx/devkit              : 18.0.3
@nx/eslint-plugin       : 18.0.3
@nrwl/eslint-plugin-nx  : 17.1.3
@nx/react               : 17.1.3
@nrwl/tao               : 17.1.3
@nx/web                 : 17.1.3
@nx/webpack             : 17.1.3
typescript              : 4.9.5
---------------------------------------
Community plugins:
@nx-aws-plugin/nx-aws-cache : 3.2.0
---------------------------------------
The following packages should match the installed version of nx
  - @nx/js@18.0.3
  - @nrwl/js@18.0.3
  - @nx/jest@18.0.3
  - @nrwl/jest@17.1.3
  - @nx/linter@18.0.3
  - @nx/eslint@18.0.3
  - @nx/workspace@18.0.3
  - @nrwl/workspace@18.0.3
  - @nx/devkit@18.0.3
  - @nrwl/devkit@18.0.3
  - @nx/eslint-plugin@18.0.3
  - @nrwl/eslint-plugin-nx@17.1.3
  - @nx/react@17.1.3
  - @nrwl/react@17.1.3
  - @nrwl/tao@17.1.3
  - @nx/web@17.1.3
  - @nrwl/web@17.1.3
  - @nx/webpack@17.1.3
  - @nrwl/webpack@17.1.3
```

### Failure Logs

```shell
An unknown error occurred while trying to create a release on GitHub, please report this on https://github.com/nrwl/nx (NOTE: make sure to redact your GitHub token from the error message!)
    at settle (/opt/github-actions-runner/_work/redacted/redacted-repo/node_modules/nx/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/opt/github-actions-runner/_work/redacted/redacted-repo/node_modules/nx/node_modules/axios/lib/adapters/http.js:589:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/opt/github-actions-runner/_work/redacted/redacted-repo/node_modules/nx/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at makeGithubRequest (/opt/github-actions-runner/_work/redacted/redacted-repo/node_modules/nx/src/command-line/release/utils/github.js:251:13)
    at createGithubRelease (/opt/github-actions-runner/_work/redacted-repo/redacted-repo/node_modules/nx/src/command-line/release/utils/github.js:261:12)
    at syncGithubRelease (/opt/github-actions-runner/_work/redacted-repo/redacted-repo/node_modules/nx/src/command-line/release/utils/github.js:195:30)
    at createOrUpdateGithubReleaseInternal (/opt/github-actions-runner/_work/redacted-repo/redacted-repo/node_modules/nx/src/command-line/release/utils/github.js:96:20)
    at createOrUpdateGithubRelease (/opt/github-actions-runner/_work/redacted-repo/redacted-repo/node_modules/nx/src/command-line/release/utils/github.js:86:9)
    at /opt/github-actions-runner/_work/redacted-repo/redacted-repo/node_modules/nx/src/command-line/release/changelog.js:203:29
    at applyChangesAndExit (/opt/github-actions-runner/_work/redacted-repo/redacted-repo/node_modules/nx/src/command-line/release/changelog.js:337:9)
    at releaseChangelog (/opt/github-actions-runner/_work/redacted-repo/redacted-repo/node_modules/nx/src/command-line/release/changelog.js:243:5) {
  code: 'ERR_BAD_RESPONSE',
config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: '***',
      'User-Agent': 'axios/1.6.7',
      'Content-Length': '290',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    data: '{"tag_name":"shhh@100.0.0","name":"shhh@100.0.0","body":"# 100.0.0 (2024-03-01)\\n\\n\\n### 🩹 Fixes\\n\\n- **shhh:** add ci-trigger ([71e110ac8](https://github.com/redacted/redacted-repo/commit/71e110ac8))","prerelease":false,"target_commitish":"822a4027dbe5316f207411558afa2251e90d6b55"}',
    baseURL: 'https://api.github.com',
    url: '/repos/redacted/redacted-repo/releases'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '290',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.github.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.github.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 439,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /repos/redacted/redacted-repo/releases HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'Authorization: ***' +
      'User-Agent: axios/1.6.7\r\n' +
      'Content-Length: 290\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: api.github.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/repos/redacted/redacted-repo/releases',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.github.com/repos/redacted/redacted-repo/releases',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 50,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.github.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 290,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.github.com/repos/redacted/redacted-repo/releases',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: Object [AxiosHeaders] {
      server: 'GitHub.com',
      date: 'Fri, 01 Mar 2024 18:56:26 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '0',
      'x-oauth-scopes': 'admin:org, admin:repo_hook, project, repo, user, workflow, write:discussion',
      'x-accepted-oauth-scopes': 'repo',
      'github-authentication-token-expiration': '2024-03-31 15:50:03 UTC',
      'x-github-media-type': 'github.v3',
      'x-github-api-version-selected': '2022-11-28',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4991',
      'x-ratelimit-reset': '1709319[78](https://github.com/redacted/redacted-repo/actions/runs/8115533569/job/22184585355#step:11:79)7',
      'x-ratelimit-used': '9',
      'x-ratelimit-resource': 'core',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'access-control-allow-origin': '*',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'x-frame-options': 'deny',
      'x-content-type-options': 'nosniff',
      'x-xss-protection': '0',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      'content-security-policy': "default-src 'none'",
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-github-request-id': '7AA9:32A5:2736C12:2836B9B:65E224DA',
      connection: 'close'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      data: '{"tag_name":"shhh@100.0.0","name":"shhh@100.0.0","body":"# 100.0.0 (2024-03-01)\\n\\n\\n### 🩹 Fixes\\n\\n- **shhh:** add ci-trigger ([71e110ac8](https://github.com/redacted/redacted-repo/commit/71e110ac8))","prerelease":false,"target_commitish":"[82](https://github.com/redacted/redacted-repo/actions/runs/8115533569/job/22184585355#step:11:83)2a4027dbe5316f207411558afa2251e90d6b55"}',
      baseURL: 'https://api.github.com',
      url: '/repos/redacted/redacted-repo/releases'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '290',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /repos/redacted/redacted-repo/releases HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: ***' +
        'User-Agent: axios/1.6.7\r\n' +
        'Content-Length: 290\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api.github.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/repos/redacted/redacted-repo/releases',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.github.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 163[84](https://github.com/redacted/redacted-repo/actions/runs/8115533569/job/22184585355#step:11:85),
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: ''
  }
}
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
@someguynamedmatt how are you setting the token? Please can you share the relevant CI config?

**Comment by someguynamedmatt** [comment]
@JamesHenry (thanks for the response):

```
      - name: Generate Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_PAT }}
        run: |
          npx nx report
          npx nx --version
          last_tag=$(git tag --sort=creatordate | grep -E '${{ env.app }}@[0-9]+\.[0-9]+\.[0-9]+-prod' | tail -1)
          npx nx release changelog ${{ env.version }} -p ${{ env.app }} --from ${last_tag} --to ${{ env.app }}@${{ env.version }}
```

I've also attempted by prepending `GITHUB_TOKEN` before the `npx nx release` command with, both, the `${{ secrets.TEST_PAT }}` value and a direct copy/paste of the token itself.

**Comment by JamesHenry** [comment]
Ok yeah essentially I was wondering if the default `GITHUB_TOKEN` was coming through and then it do not have appropriate permissions. We preferentially resolve `GITHUB_TOKEN` so was checking you weren't using `GH_TOKEN` in CI

(Our logic)
```ts
  // Try and resolve from the environment
  const tokenFromEnv = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  if (tokenFromEnv) {
    return tokenFromEnv;
  }
```

As a next step I would try and take Nx out of the equation and try creating a release on the same repo directly using the PAT to make sure it is actually available and has the right perms.

You could use the official `actions/github-script` with a custom `github-token` to test it: https://github.com/actions/github-script?tab=readme-ov-file#using-a-separate-github-token

**Comment by someguynamedmatt** [comment]
@JamesHenry Thanks for the response and sorry for my delayed response, I've been out of town. I took your suggestion and performed a simple curl within my workflow and was able to confirm my github token is indeed able to create releases. 

Initially, I was unable to get a release published although no errors were being thrown. I was using the below payload.
```
 data: '{"tag_name":"shhh@100.0.0","name":"shhh@100.0.0","body":"# 100.0.0 (2024-03-01)\\n\\n\\n### 🩹 Fixes\\n\\n- **shhh:** add ci-trigger ([71e110ac8](https://github.com/redacted/redacted-repo/commit/71e110ac8))","prerelease":false,"target_commitish":"822a4027dbe5316f207411558afa2251e90d6b55"}'
```

My curl succeeded and my release was visible when I removed the `target_commitish` attribute. I'm not sure why this seems to be an issue, a hypothesis however is that this is some deleted commit removed via our merge strategy in the pull requests (total guess, I couldn't track down the sha). What might be the strategy to circumvent/test this?

**Comment by someguynamedmatt** [comment]
I've been scouring the Nx code related to releases and I've trimmed down this error to a simple `axios` request which allows me to confirm that the 500 is a result of a non-existent `target_commitish` hash. 

```javascript
const ghRelease = {
  tag_name: 'shhh@100.0.0',
  name: '100.0.0',
  prerelease: false,
  target_commitish: 'd2598b393cda33661c7dc2991944fd99b3ed7113', // <-- this SHA does not exist
  body: '# Contents of CHANGELOG',
}

const opts = {
  method: 'POST',
  data: ghRelease,
}

const ax = async () => {
  return (
    await axios('/repos/my-org/my-repo/releases', {
      ...opts,
      baseURL: 'https://api.github.com',
      headers: {
        Authorization: `Bearer ${TOKEN}`
      }
    })
  )
}

ax().then(d => {
  console.log(d)
})
```

As with my curl, if I remove (comment out) this `target_commitish` attribute from the `ghRelease` object, the request succeeds as expected.

@JamesHenry Is there any way to circumvent this? I wouldn't mind submitting a PR.

**Comment by JamesHenry** [comment]
We do a git push to ensure that the commit exists before attempting to create a release against it, have you disabled that? Are you intentionally not persisting the commit from the pipeline?

**Comment by JamesHenry** [comment]
I appreciate you doing the digging thank you! 💙

**Comment by someguynamedmatt** [comment]
Yeah, I think there was some weirdness with my git status in this workflow. A few moments ago I noticed that and this seems to be functioning as expected. Thanks!

**Comment by someguynamedmatt** [comment]
(Reopening as I still have questions)...

This has begun to fail again. I'm hoping someone can help me understand how I'm misusing this API. I'm currently doing:
```
npx nx release changelog ${{ env.version }} -p ${{ env.app }} --from ${last_tag} --to ${{ env.app }}@${{ env.version }}
```
a less abstracted example:
```
npx nx release changelog my-app@100.0.0 -p my-app --from my-app@99.0.0-prod --to my-app@100.0.0
```
in my github workflow. I see this error related to the `target_commitish` described above wherein the SHA in that attribute is the SHA affiliated with my tag. In my pipeline the `env.version` (i.e. `my-app@100.0.0`) currently exists, I'm simply trying to create the CHANGELOG for it if (and only if) that tag (`my-app@100.0.0`) is being promoted to production.

Is it problematic that this fails given that the version passed after `nx release changelog` already exists?

**Comment by someguynamedmatt** [comment]
I think I understand this.

When passing the tag in the `--to` option, the SHA resolved from Nx's `git rev-parse` is the SHA of the tag, rather than the parent commit. If I instead determine the tag's parent's SHA and pass _that_ to the option, it works.

```
git rev-parse shhh@100.0.0^0
```
rather than the Nx-resolved
```
git rev-parse shhh@100.0.0
```
This is probably something more problematic with my tagging than Nx itself, but I'm noting this for posterity.

**Comment by JamesHenry** [comment]
Given this hasn't come up for anyone else in the interim and you seem to have gotten to the bottom of it for your particular workflow, I'm going to go ahead and close this one.

Many thanks again for your proactive digging to get to the bottom of it, it means a lot!
