### ISSUE TITLE
Nx affected requiers plugins mentions in "Plugins" field in nx.json

### ISSUE THREAD

**Issue by yuvals41** [nrwl/nx#22155]
### Current Behavior

running nx affected on my jenkins slave(pod), after I downloaded:
```
npm install --no-audit --no-update-notifier --no-fund --loglevel=error nx@18.0.5 @nx/webpack@18.0.5 @nrwl/cli @nrwl/nx-linux-x64-gnu
```
but i get an error 
```
17:41:26  + node_modules/.bin/nx show projects --projects apps/* --plain --affected --base=HEAD~1 --head=HEAD --exclude
17:41:26  Plugin listed in `nx.json` not found: @nx/eslint/plugin
17:41:26  nx show projects
17:41:26  
17:41:26  Show a list of projects in the workspace
17:41:26  
17:41:26  Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
17:41:26        --base  Base of the current branch (usually main)  [string]
17:41:26  
17:41:26  or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
17:41:26        --base  Base of the current branch (usually main)  [string]
17:41:26        --head  Latest commit of the current branch (usually HEAD)  [string]
17:41:26  
17:41:26  or using:
17:41:26        --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas or spaces  [string]
17:41:26        --uncommitted  Uncommitted changes  [boolean]
17:41:26        --untracked    Untracked changes  [boolean]
17:41:26  
17:41:26  Options:
17:41:26        --help        Show help  [boolean]
17:41:26        --version     Show version number  [boolean]
17:41:26        --json        Output JSON  [boolean]
17:41:26        --exclude     Exclude certain projects from being processed  [string]
17:41:26        --affected    Show only affected projects  [boolean]
17:41:26    -p, --projects    Show only projects that match a given pattern.  [string]
17:41:26    -t, --withTarget  Show only projects that have a specific target  [string]
17:41:26        --type        Select only projects of the given type  [string] [choices: "app", "lib", "e2e"]
17:41:26  
17:41:26  Examples:
17:41:26    nx show projects --projects "apps/*"         Show all projects in the apps directory
17:41:26    nx show projects --projects "shared-*"       Show all projects that start with "shared-"
17:41:26    nx show projects --affected                  Show affected projects in the workspace
17:41:26    nx show projects --type app --affected       Show affected apps in the workspace
17:41:26    nx show projects --affected --exclude=*-e2e  Show affected projects in the workspace, excluding end-to-end projects
17:41:26  
17:41:26  Error: Cannot find module '@nx/eslint/plugin'
17:41:26  Require stack:
17:41:26  - node_modules/nx/src/utils/nx-plugin.js
17:41:26  - node_modules/nx/src/project-graph/build-project-graph.js
17:41:26  - node_modules/nx/src/project-graph/project-graph.js
17:41:26  - node_modules/nx/src/config/workspaces.js
17:41:26  - node_modules/nx/src/plugins/package-json-workspaces/create-nodes.js
17:41:26  - node_modules/nx/src/plugins/package-json-workspaces/index.js
17:41:26  - node_modules/nx/src/plugins/target-defaults/target-defaults-plugin.js
17:41:26  - node_modules/nx/src/project-graph/utils/project-configuration-utils.js
17:41:26  - node_modules/nx/src/utils/package-json.js
17:41:26  - node_modules/nx/src/utils/package-manager.js
17:41:26  - node_modules/nx/src/utils/child-process.js
17:41:26  - node_modules/nx/src/command-line/migrate/command-object.js
17:41:26  - node_modules/nx/src/command-line/nx-commands.js
17:41:26  - node_modules/nx/bin/init-local.js
17:41:26  - node_modules/nx/bin/nx.js
17:41:26      at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
17:41:26      at Function.resolve (node:internal/modules/helpers:187:19)
17:41:26      at getPluginPathAndName (node_modules/nx/src/utils/nx-plugin.js:35:30)
17:41:26      at loadNxPluginAsync (node_modules/nx/src/utils/nx-plugin.js:78:38)
17:41:26      at loadNxPlugins (node_modules/nx/src/utils/nx-plugin.js:105:27)
17:41:26      at async retrieveProjectConfigurations (node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:45:21)
17:41:26      at async buildProjectGraphAndSourceMapsWithoutDaemon (node_modules/nx/src/project-graph/project-graph.js:71:69)
17:41:26      at async createProjectGraphAndSourceMapsAsync (node_modules/nx/src/project-graph/project-graph.js:136:25)
17:41:26      at async createProjectGraphAsync (node_modules/nx/src/project-graph/project-graph.js:125:39)
17:41:26      at async Object.showProjectsHandler (node_modules/nx/src/command-line/show/show.js:15:17) {
17:41:26    code: 'MODULE_NOT_FOUND',
17:41:26    requireStack: [
17:41:26      'node_modules/nx/src/utils/nx-plugin.js',
17:41:26      'node_modules/nx/src/project-graph/build-project-graph.js',
17:41:26      'node_modules/nx/src/project-graph/project-graph.js',
17:41:26      'node_modules/nx/src/config/workspaces.js',
17:41:26      'node_modules/nx/src/plugins/package-json-workspaces/create-nodes.js',
17:41:26      'node_modules/nx/src/plugins/package-json-workspaces/index.js',
17:41:26      'node_modules/nx/src/plugins/target-defaults/target-defaults-plugin.js',
17:41:26      'node_modules/nx/src/project-graph/utils/project-configuration-utils.js',
17:41:26      'node_modules/nx/src/utils/package-json.js',
17:41:26      'node_modules/nx/src/utils/package-manager.js',
17:41:26      'node_modules/nx/src/utils/child-process.js',
17:41:26      'node_modules/nx/src/command-line/migrate/command-object.js',
17:41:26      'node_modules/nx/src/command-line/nx-commands.js',
17:41:26      'node_modules/nx/bin/init-local.js',
17:41:26      'node_modules/nx/bin/nx.js'
17:41:26    ]
17:41:26  }
```

### Expected Behavior

i dont understand why when i run nx affected it needs to have the plugins installed, I only want to see which micro services got affected

### Steps to Reproduce

1. have a plugins field in nx.json like this
```
  "plugins": [
    {
      "plugin": "@nx/webpack/plugin",
      "options": {
        "buildTargetName": "build",
        "serveTargetName": "serve",
        "previewTargetName": "preview"
      }
    },
    {
      "plugin": "@nx/eslint/plugin",
      "options": {
        "targetName": "lint"
      }
    },
    {
      "plugin": "@nx/jest/plugin",
      "options": {
        "targetName": "test"
      }
    }
  ],
  ```
  and run without installing the plugins: 
  node_modules/.bin/nx show projects --projects apps/* --plain --affected --base=HEAD~1 --head=HEAD --exclude

### Nx Report

```shell
there is not report
```

### Package Manager Version

npm version 10.2.4

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Plugins can create new projects, so they have to be ran to list all projects
