### ISSUE TITLE
Following Setup in Docs Throws Errors

### ISSUE THREAD

**Issue by scott-cornwell** [nrwl/nx#22218]
### Documentation issue

- [x ] Reporting a documentation bug

### Is there a specific documentation page you are reporting?
https://nx.dev/recipes/adopting-nx/adding-to-monorepo

### Additional context or description

Ran this command as per docs:

```js
npx nx@latest init
```

Throws errors: 
```
Error: Both project and target have to be specified
    at parseRunOneOptions (C:\projects\monorepo\.nx\installation\node_modules\nx\src\command-line\run\run-one.js:99:15)
    at Object.runOne (C:\projects\monorepo\.nx\installation\node_modules\nx\src\command-line\run\run-one.js:22:18)

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runNxSync (C:\Users\Me\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\nx\src\utils\child-process.js:25:34)
    at Object.initHandler (C:\Users\Me\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\nx\src\command-line\init\init-v2.js:35:39)
    at Object.handler (C:\Users\Me\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\nx\src\command-line\init\command-object.js:12:40)
    at C:\Users\Me\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\yargs\build\index.cjs:1:8993
    at j (C:\Users\Me\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\yargs\build\index.cjs:1:4956)
    at _.handleValidationAndGetResult (C:\Users\Me\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\yargs\build\index.cjs:1:8962)
    at _.applyMiddlewareAndGetResult (C:\Users\Me\AppData\Local\npm-cache\_npx\f948e921c5898768\node_modules\yargs\build\index.cjs:1:9604) {
```

Running on node 21.1.0 and npm 10.2.0 on Windows 10 in a mingw console.

**Comment by FrozenPandaz** [comment]
Could you try to clear your npx cache with `npx clear-npx-cache` and try again? This error does not happen for me. Maybe an old version of Nx is resolved by `npx nx@latest`
