### ISSUE TITLE
Clean expo app unable to import from libraries

### ISSUE THREAD

**Issue by rudfoss** [nrwl/nx#22261]
### Current Behavior

When creating a new expo app and library using the Nx generators in a new workspace the bundler fails with error `Cannot resolve [module name]` once the app is started `nx run expo-app:start`. This happens even in a brand new workspace.

### Expected Behavior

Imports of libraries should work.

### GitHub Repo

https://github.com/rudfoss/expo-with-lib

### Steps to Reproduce

Repo that reproduces error when importing files from libraries in expo.

## Repro steps

Init
```bash
pnpm create create-nx-workspace@latest expo-with-lib --workspaceType=integrated --nxCloud=skip --preset=apps --defaultBase=main
```

Install expo
```bash
pnpm exec nx add @nx/expo
```

Fix .npmrc
```bash
strict-peer-dependencies=false
auto-install-peers=true
node-linker=hoisted
```

Reinstall dependencies
```bash
pnpm i
```

Generate app
```bash
pnpm exec nx generate @nx/expo:application --name=expo-app --directory=apps/expo-app --e2eTestRunner=playwright --projectNameAndRootFormat=as-provided --no-interactive
```

Generate lib
```bash
pnpm exec nx generate @nx/expo:library --name=expo-lib --directory=libs/expo-lib --projectNameAndRootFormat=as-provided --no-interactive
```

Add dummy component and export

**libs/expo-lib/src/Test.tsx**
```tsx
import { View, Text } from "react-native"

export const Test = () => {
  return <View><Text>Hello from lib</Text></View>
}
```

**libs/expo-lib/src/index.ts**
```tsx
export * from './Test';
```

Use lib in App.tsx

**apps/expo-app/src/app/App.tsx
```tsx
import { Test } from '@expo-with-lib/expo-lib';

return (
  //...
    <Test/>
)
```

Run the app
```bash
pnpm exec nx run expo-app:start
```

Bundler fails with error:
```text
Web Bundling failed 1175ms (C:\projects\temp\expo-with-lib\apps\expo-app\index.js)
error: Error: Cannot resolve @expo-with-lib/expo-lib
    at firstResolver (C:\projects\temp\expo-with-lib\node_modules\@nx\expo\plugins\metro-resolver.js:33:15)
    at firstResolver (C:\projects\temp\expo-with-lib\node_modules\expo\node_modules\@expo\cli\src\start\server\metro\withMetroResolvers.ts:108:16)
    at resolveRequest (C:\projects\temp\expo-with-lib\node_modules\expo\node_modules\@expo\cli\src\start\server\metro\withMetroResolvers.ts:137:16)
    at Object.resolve (C:\projects\temp\expo-with-lib\node_modules\metro-resolver\src\resolve.js:32:12)
    at ModuleResolver.resolveDependency (C:\projects\temp\expo-with-lib\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:73:31)
    at DependencyGraph.resolveDependency (C:\projects\temp\expo-with-lib\node_modules\metro\src\node-haste\DependencyGraph.js:231:43)
    at C:\projects\temp\expo-with-lib\node_modules\metro\src\lib\transformHelpers.js:156:21
    at resolveDependencies (C:\projects\temp\expo-with-lib\node_modules\metro\src\DeltaBundler\buildSubgraph.js:42:25)
    at visit (C:\projects\temp\expo-with-lib\node_modules\metro\src\DeltaBundler\buildSubgraph.js:83:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.9.0
OS     : win32-x64
pnpm   : 8.15.4

nx                 : 18.0.8
@nx/js             : 18.0.8
@nx/jest           : 18.0.8
@nx/linter         : 18.0.8
@nx/eslint         : 18.0.8
@nx/workspace      : 18.0.8
@nx/devkit         : 18.0.8
@nx/eslint-plugin  : 18.0.8
@nx/expo           : 18.0.8
@nx/playwright     : 18.0.8
@nx/react          : 18.0.8
@nrwl/tao          : 18.0.8
@nx/web            : 18.0.8
@nx/webpack        : 18.0.8
typescript         : 5.3.3
```

### Failure Logs

```shell
Web Bundling failed 1175ms (C:\projects\temp\expo-with-lib\apps\expo-app\index.js)
error: Error: Cannot resolve @expo-with-lib/expo-lib
    at firstResolver (C:\projects\temp\expo-with-lib\node_modules\@nx\expo\plugins\metro-resolver.js:33:15)
    at firstResolver (C:\projects\temp\expo-with-lib\node_modules\expo\node_modules\@expo\cli\src\start\server\metro\withMetroResolvers.ts:108:16)
    at resolveRequest (C:\projects\temp\expo-with-lib\node_modules\expo\node_modules\@expo\cli\src\start\server\metro\withMetroResolvers.ts:137:16)
    at Object.resolve (C:\projects\temp\expo-with-lib\node_modules\metro-resolver\src\resolve.js:32:12)
    at ModuleResolver.resolveDependency (C:\projects\temp\expo-with-lib\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:73:31)
    at DependencyGraph.resolveDependency (C:\projects\temp\expo-with-lib\node_modules\metro\src\node-haste\DependencyGraph.js:231:43)
    at C:\projects\temp\expo-with-lib\node_modules\metro\src\lib\transformHelpers.js:156:21
    at resolveDependencies (C:\projects\temp\expo-with-lib\node_modules\metro\src\DeltaBundler\buildSubgraph.js:42:25)
    at visit (C:\projects\temp\expo-with-lib\node_modules\metro\src\DeltaBundler\buildSubgraph.js:83:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Package Manager Version

8.15.4

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Might be related to this: https://github.com/nrwl/nx/issues/21871

**Comment by rudfoss** [comment]
After hacking around a bit I think I stumbled upon a solution and possibly a bug in the [withNxMetro](https://github.com/nrwl/nx/blob/master/packages/expo/plugins/with-nx-metro.ts) plugin. As a test I tried to manually add the folder for my lib to `metro.config.js` like this:

```
  watchFolders: [
    path.resolve("../..", "libs")
  ],
```

and it works fine. I then tried to "resolve" all watch folders nx adds automatically and that did the trick:

**metro.config.js**
```js
const { withNxMetro } = require('@nx/expo');
const { getDefaultConfig } = require('@expo/metro-config');
const { mergeConfig } = require('metro-config');
const path = require('node:path');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const customConfig = {
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter((ext) => ext !== 'svg'),
    sourceExts: [...sourceExts, 'cjs', 'mjs', 'svg'],
  },
};

module.exports = withNxMetro(mergeConfig(defaultConfig, customConfig), {
  // Change this to true to see debugging info.
  // Useful if you have issues resolving modules
  debug: false,
  // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx', 'json'
  extensions: [],
  // Specify folders to watch, in addition to Nx defaults (workspace libraries and node_modules)
  watchFolders: [],
}).then((config) => { // Correct the paths in watchFolders before returning the final config
  config.watchFolders = config.watchFolders.map((folder) => path.resolve(folder));
  return config;
});
```

It appears that the watchFolder paths returned from [these lines](https://github.com/nrwl/nx/blob/c01b5667283a601d2c45c7b0fa00336f02b25154/packages/expo/plugins/with-nx-metro.ts#L22) (specifically the [joinPathFragments](https://github.com/nrwl/nx/blob/c01b5667283a601d2c45c7b0fa00336f02b25154/packages/expo/plugins/with-nx-metro.ts#L27) function) are always formatted as posix paths `/a/b/c` and not Windows paths: `c:\a\b\c` even when on windows. I think that causes a mismatch in the metro bundler which prevents files from being found once the bundler requests it. Performing a resolve did the trick, but maybe the devkit should respect the path syntax for the OS it runs on?
