### ISSUE TITLE
NextJS 14 build fails with NX 18

### ISSUE THREAD

**Issue by ShadiBlitz** [nrwl/nx#22273]
### Current Behavior

After the building process is almost finished and a successful nextjs build message, the NX build console errors out.

```
 NX   Successfully ran target build for project backoffice



 NX   No such file or directory (os error 2)


Error: No such file or directory (os error 2)
    at /app/node_modules/.pnpm/nx@18.0.8_@swc-node+register@1.8.0_@swc+core@1.3.95/node_modules/nx/src/tasks-runner/cache.js:145:17
    at new Promise (<anonymous>)
    at Cache.copy (/app/node_modules/.pnpm/nx@18.0.8_@swc-node+register@1.8.0_@swc+core@1.3.95/node_modules/nx/src/tasks-runner/cache.js:143:16)
    at /app/node_modules/.pnpm/nx@18.0.8_@swc-node+register@1.8.0_@swc+core@1.3.95/node_modules/nx/src/tasks-runner/cache.js:88:32
    at async Promise.all (index 0)
    at async /app/node_modules/.pnpm/nx@18.0.8_@swc-node+register@1.8.0_@swc+core@1.3.95/node_modules/nx/src/tasks-runner/cache.js:84:13
    at async _try (/app/node_modules/.pnpm/nx@18.0.8_@swc-node+register@1.8.0_@swc+core@1.3.95/node_modules/nx/src/tasks-runner/cache.js:222:24)
    at async _try (/app/node_modules/.pnpm/nx@18.0.8_@swc-node+register@1.8.0_@swc+core@1.3.95/node_modules/nx/src/tasks-runner/cache.js:230:24)
    at async _try (/app/node_modules/.pnpm/nx@18.0.8_@swc-node+register@1.8.0_@swc+core@1.3.95/node_modules/nx/src/tasks-runner/cache.js:230:24)
    at async _try (/app/node_modules/.pnpm/nx@18.0.8_@swc-node+register@1.8.0_@swc+core@1.3.95/node_modules/nx/src/tasks-runner/cache.js:230:24)

```

my nextconfig file:

```javascript
const { withSentryConfig } = require('@sentry/nextjs')
const { composePlugins, withNx } = require('@nx/next')

/**
 * @type {import('@nx/next/plugins/with-nx').WithNxOptions}
 *
 **/
const nextConfig = {
  output: 'standalone',
  nx: {
    svgr: false,
  },
  sentry: {
    hideSourceMaps: true,
  },
}

const withSentry = (config) => withSentryConfig(config)

const plugins = [withNx, withSentry]

module.exports = composePlugins(...plugins)(nextConfig)

```

I have tried removing sentry plugin, got the same issue.
I have also added the new `NX_ADD_PLUGINS=false` environment variable for inferred tasks, also got the same issue.

### Expected Behavior

build is successful.

### Steps to Reproduce

1. Upgrade a `Nextjs` app from `v13.5.6` to `v14.0.4`,
2. Upgrade NX from `v17.0.1` to `v18.0.8`.
3. Build Next app.

### Nx Report

```shell
Node   : 20.5.0
OS     : linux-x64
pnpm   : 8.10.5

nx                 : 18.0.8
@nx/js             : 18.0.8
@nx/jest           : 18.0.8
@nx/linter         : 18.0.8
@nx/eslint         : 18.0.8
@nx/workspace      : 18.0.8
@nx/cypress        : 18.0.8
@nx/devkit         : 18.0.8
@nx/eslint-plugin  : 18.0.8
@nx/next           : 18.0.8
@nx/react          : 18.0.8
@nx/storybook      : 18.0.8
@nrwl/tao          : 16.6.0
@nx/web            : 18.0.8
@nx/webpack        : 18.0.8
typescript         : 5.3.3
---------------------------------------
```

### Package Manager Version

pnpm

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by KentoMoriwaki** [comment]
I encountered this problem. I found that this error occurred because bad symlinks were generated under the output directory.

I ran this command and found that there was a bad symlink to 'node_modules/caniuse-lite'.

```
find dist/apps/frontend -type l ! -exec test -e {} \; -print
```

So, I added `caniuse-lite` using `pnpm add caniuse-lite`, and it solved the error.

I hope this helps you.

**Comment by ndcunningham** [comment]
did you run 
- `nx migrate` to upgrade your Nx version 
- `nx reset` before attempting to build (if you did not use `nx migrate`)

The error seems to be a conflict with `swc` probably a cached version. I am not really sure.

**Comment by ShadiBlitz** [comment]
This exact error was solved by updating `caniuse-lite` package.
I will mark this as resolved.
