### ISSUE TITLE
`options.outputPath` is undefined in `@nrwl/webpack` when using with nestjs

### ISSUE THREAD

**Issue by dan-cooke** [nrwl/nx#22302]
### Current Behavior

Bootstrapping a new NestJs app and adding a webpack build target as follows
 
```.json
    "build": {
      "executor": "@nx/webpack:webpack",
      "options": {
        "webpackConfig": "apps/api/webpack.config.js"
      }
    },
```

Causes the following error

```


TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:406:5)
    at validateString (node:internal/validators:162:11)
    at resolve (node:path:1101:7)
    at /home/dan/dev/templi/templi/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js:120:37
    at /home/dan/dev/templi/templi/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:35

```

### Expected Behavior

No error

### Steps to Reproduce

As above

### Nx Report

```shell
Node   : 20.9.0
OS     : linux-x64
yarn   : 1.22.21

nx (global)        : 18.0.8
nx                 : 18.0.6
@nx/js             : 18.0.6
@nx/jest           : 18.0.6
@nx/linter         : 18.0.6
@nx/eslint         : 18.0.6
@nx/workspace      : 18.0.6
@nx/cypress        : 18.0.6
@nx/devkit         : 18.0.6
@nx/esbuild        : 18.0.6
@nx/eslint-plugin  : 18.0.6
@nx/nest           : 18.0.6
@nx/node           : 18.0.6
@nx/react          : 18.0.6
@nrwl/tao          : 18.0.6
@nx/vite           : 18.0.6
@nx/web            : 18.0.6
@nx/webpack        : 18.0.6
typescript         : 5.3.3
---------------------------------------
Community plugins:
@nx-extend/shadcn-ui : 1.0.0
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Several other relevant issues raised around this, but I think they have missed the specifics

https://github.com/nrwl/nx/issues/22215

The problem is that the webpack executor is not receiving `outputFilePath` with nestjs 

I can see a [TODO](https://github.com/nrwl/nx/commit/507fe42e4f3e132a980eac39dc4eb5a2651d0fd4#diff-adc502eb83a929100a09437345a811e04c7b177667a5d9e1e742e70ab498bf19R184) from @jaysoo  that suggests there may be some edge cases with NestJs here

**Comment by dan-cooke** [comment]
I'm an idiot, I don't have an outputPath
