### ISSUE TITLE
Invalid JSON Schema enforcement of additionalProperties

### ISSUE THREAD

**Issue by JacobLey** [nrwl/nx#22349]
### Current Behavior

A executor schema that allows an object with arbitrary keys so long as the values match.

Typescript equivalent: `Record<{ foo: Record<string, number> }>`

```
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "foo": {
      "type": "object",
      "additionalProperties": {
          "type": "number"
      }
    }
  }
}
```

Running the executor throws with
```


 NX   Cannot convert undefined or null to object


TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:194:24
    at Array.find (<anonymous>)
    at validateObject (/workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:193:27)
    at validateProperty (/workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:346:9)
    at /workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:210:9
    at Array.forEach (<anonymous>)
    at validateObject (/workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:209:23)
    at validateOptsAgainstSchema (/workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:144:5)
    at combineOptionsForExecutor (/workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:432:5)
```

### Expected Behavior

Executor can run successfully. Schema is treated as valid.

### Steps to Reproduce

1. Create an executor schema that has a `"type": "object"` with `"additionalProperties"` set to anything but true.
2. Attempt to run the executor

### Nx Report

```shell
Node   : 20.11.1
OS     : linux-arm64
pnpm   : 8.15.4

nx (global)  : 18.1.1
nx           : 18.1.1
@nx/eslint   : 18.1.1
@nrwl/tao    : 18.1.1
```

### Failure Logs

```shell
NX   Cannot convert undefined or null to object


TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:194:24
    at Array.find (<anonymous>)
    at validateObject (/workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:193:27)
    at validateProperty (/workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:346:9)
    at /workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:210:9
    at Array.forEach (<anonymous>)
    at validateObject (/workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:209:23)
    at validateOptsAgainstSchema (/workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:144:5)
    at combineOptionsForExecutor (/workspace/node_modules/.pnpm/nx@18.1.1/node_modules/nx/src/utils/params.js:432:5)
```

### Package Manager Version

pnpm 8.15.4

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Offending logic is right where the error logs point us: https://github.com/nrwl/nx/blob/master/packages/nx/src/utils/params.ts#L293

If `additionalProperties` is found, the logic attempts to get the keys of `properties`. However there is no guarantee that value exists, and `Object.keys(undefined)` is an error.

The JSONSchema spec does not specify that `properties` _must_ be set in order to use `additionalProperties` (as a general rule of thumb, no fields allow/disallow others).

This logic should default `properties` to `{}` in the case where it does not exist.

Alternatively, I recommend switching to a battle tested JSON Schema validator, such as [AJV](https://ajv.js.org/guide/getting-started.html)

**Comment by ivibe** [comment]
I believe this affects linting. The library or application with project.json without
```json
"targets": {
  ...
  "lint": {
    "executor": "@nx/eslint:lint"
  },
  ...
}
```
will trigger this error when `nx run lib-name:lint --verbose`
```
NX   Cannot convert undefined or null to object


TypeError: Cannot convert undefined or null to object
```

**Comment by robertIsaac** [comment]
> I believe this affects linting. The library or application with project.json without
> 
> ```json
> "targets": {
>   ...
>   "lint": {
>     "executor": "@nx/eslint:lint"
>   },
>   ...
> }
> ```
> 
> will trigger this error when `nx run lib-name:lint --verbose`
> 
> ```
> NX   Cannot convert undefined or null to object
> 
> 
> TypeError: Cannot convert undefined or null to object
> ```

yes it fails for me as well

**Comment by mattfysh** [comment]
This breaks any usage of `nx:run-commands` where the `env` option is defined:

https://github.com/nrwl/nx/blob/master/packages/nx/src/executors/run-commands/schema.json#L121-L126

**Comment by robinsjovoll** [comment]
This also breaks the usage of the new `define` options for esbuild in Angular 17.2

**Comment by grumpyoldman-io** [comment]
Running in to the same error as @mattfysh, holistically it surprises me that there is an additionalProperties field on the schema and not a properties field. I think the bug creeped in because of that reason (someone assuming a `properties` field would be present when `additionalProperties` are).

Reverting to `nx@18.0.8` unblocked me (bug introduced here: https://github.com/nrwl/nx/commit/4b88f48a18adab94008ce9645577c1988a564cfd#diff-55a4c7f03251ea53a875e8157a13c738f318af858ce94f22c44895fa36019602R290

**Comment by c4spar** [comment]
Running into the same issue with the `headers` option from the `dev-server`.
```json
{
  "serve": {
    "executor": "@angular-devkit/build-angular:dev-server",
    "options": {
      "headers": {
        "foo": "bar"
      }
    }
  }
}
```

```console
$ pnpm nx serve <app> --verbose
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at node_modules/nx/src/utils/params.js:194:24
    at Array.find (<anonymous>)
    at validateObject (node_modules/nx/src/utils/params.js:193:27)
    at validateProperty (node_modules/nx/src/utils/params.js:346:9)
    at node_modules/nx/src/utils/params.js:210:9
    at Array.forEach (<anonymous>)
    at validateObject (node_modules/nx/src/utils/params.js:209:23)
    at validateOptsAgainstSchema (node_modules/nx/src/utils/params.js:144:5)
    at combineOptionsForExecutor (node_modules/nx/src/utils/params.js:432:5)
```

**Comment by noelsoong** [comment]
same issue here 
```bash
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/noelsoong/Workspace/iticket-stack/node_modules/.pnpm/nx@18.1.2/node_modules/nx/src/utils/params.js:194:24
    at Array.find (<anonymous>)
    at validateObject (/Users/noelsoong/Workspace/iticket-stack/node_modules/.pnpm/nx@18.1.2/node_modules/nx/src/utils/params.js:193:27)
    at validateProperty (/Users/noelsoong/Workspace/iticket-stack/node_modules/.pnpm/nx@18.1.2/node_modules/nx/src/utils/params.js:346:9)
    at /Users/noelsoong/Workspace/iticket-stack/node_modules/.pnpm/nx@18.1.2/node_modules/nx/src/utils/params.js:210:9
    at Array.forEach (<anonymous>)
    at validateObject (/Users/noelsoong/Workspace/iticket-stack/node_modules/.pnpm/nx@18.1.2/node_modules/nx/src/utils/params.js:209:23)
    at validateOptsAgainstSchema (/Users/noelsoong/Workspace/iticket-stack/node_modules/.pnpm/nx@18.1.2/node_modules/nx/src/utils/params.js:144:5)
    at combineOptionsForExecutor (/Users/noelsoong/Workspace/iticket-stack/node_modules/.pnpm/nx@18.1.2/node_modules/nx/src/utils/params.js:432:5)
```

**Comment by mattfysh** [comment]
Anyone who is running into this error, were you able to track down which option was causing it? For me it was the `env` option of the `nx:run-commands` executor

If you apply the fix (see #22426 - use patch-package, pnpm patch, or edit the node_modules folder directly), does the error go away? If yes, is the option that triggered the error being applied or ignored?

In the case of `env`, after applying the fix the error goes away but the option is not applied (ie. environment variables still not accessible in the command/commands)

**Comment by jbadeau** [comment]
Also an issue with our internal plugins. Any ETA?

**Comment by robertIsaac** [comment]
> Anyone who is running into this error, were you able to track down which option was causing it? For me it was the `env` option of the `nx:run-commands` executor
> 
> If you apply the fix (see #22426 - use patch-package, pnpm patch, or edit the node_modules folder directly), does the error go away? If yes, is the option that triggered the error being applied or ignored?
> 
> In the case of `env`, after applying the fix the error goes away but the option is not applied (ie. environment variables still not accessible in the command/commands)

I actually have no configuration at all
that's the only part related to lint in the whole project
```json
  "plugins": [
    {
      "plugin": "@nx/eslint/plugin",
      "options": {
        "targetName": "lint"
      }
    },
   ...
```

**Comment by mattfysh** [comment]
@robertIsaac in the case of plugins, they are generating configuration for you

you can see this by running `nx show project xyz --web` to see the configuration that is generated by the plugin

**Comment by jon9090** [comment]
I wish to include my custom flag (-t example) when executing the nx angular serve command.

However, I encounter an error from nx indicating:

> 't' is not found in schema

I intend to intercept this flag within proxy.mjs and handle it accordingly.

What steps should I take to pass this argument without encountering an error?

**Comment by robertIsaac** [comment]
> @robertIsaac in the case of plugins, they are generating configuration for you
> 
> you can see this by running `nx show project xyz --web` to see the configuration that is generated by the plugin

aha I see
```
{
  "cwd": "apps/fe",
  "env": {
    "ESLINT_USE_FLAT_CONFIG": "true"
  }
}
```

so env was the cause
