### ISSUE TITLE
After migrating to nx 18, facing issue with npx nx show projects --affected --type lib --json

### ISSUE THREAD

**Issue by Vishal--Patel** [nrwl/nx#22407]
### Current Behavior

I am getting this error while running through azure pipeline (all works fine locally): 

CreateNodesError: Unable to create nodes for apps/exxat-forms-e2e/cypress.config.ts using plugin @nx/cypress/plugin. 

	 Inner Error: Error: invalid type: unit value, expected struct Options
    at module.exports.__wbindgen_error_new (/home/vsts/work/1/s/node_modules/@swc/wasm/wasm.js:489:17)
    at null.<anonymous> (wasm://wasm/047124f6:1:13417760)
    at null.<anonymous> (wasm://wasm/047124f6:1:13784024)
    at null.<anonymous> (wasm://wasm/047124f6:1:13940751)
    at null.<anonymous> (wasm://wasm/047124f6:1:4307981)
    at null.<anonymous> (wasm://wasm/047124f6:1:3200484)
    at null.<anonymous> (wasm://wasm/047124f6:1:11323936)
    at null.<anonymous> (wasm://wasm/047124f6:1:2115846)
    at null.<anonymous> (wasm://wasm/047124f6:1:2968116)
    at null.<anonymous> (wasm://wasm/047124f6:1:3560985)
    at /home/vsts/work/1/s/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:155:31
    at async Promise.all (index 0)
    at async Promise.all (index 3)
    at createProjectConfigurations (/home/vsts/work/1/s/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:62)
    at buildProjectGraphAndSourceMapsWithoutDaemon (/home/vsts/work/1/s/node_modules/nx/src/project-graph/project-graph.js:73:69)
    at createProjectGraphAndSourceMapsAsync (/home/vsts/work/1/s/node_modules/nx/src/project-graph/project-graph.js:139:25)
    at createProjectGraphAsync (/home/vsts/work/1/s/node_modules/nx/src/project-graph/project-graph.js:128:39)
    at Object.showProjectsHandler (/home/vsts/work/1/s/node_modules/nx/src/command-line/show/show.js:15:17)

### Expected Behavior

Command should display list of affected libs name

### Steps to Reproduce

1. Migrate to latest nx 18 version
2. Create react library with cypress
3. Try building lib through pipeline

### Nx Report

```shell
 NX   Report complete - copy this into the issue template

Node   : 16.20.2
OS     : win32-x64
npm    : 8.19.4

nx                 : 18.1.1
@nx/js             : 18.1.1
@nx/jest           : 18.1.1
@nx/linter         : 18.1.1
@nx/eslint         : 18.1.1
@nx/workspace      : 18.1.1
@nx/cypress        : 18.1.1
@nx/devkit         : 18.1.1
@nx/eslint-plugin  : 18.1.1
@nx/react          : 18.1.1
@nrwl/tao          : 18.1.1
@nx/vite           : 18.1.1
@nx/web            : 18.1.1
typescript         : 5.3.3
```

### Failure Logs

```shell
CreateNodesError: Unable to create nodes for apps/exxat-forms-e2e/cypress.config.ts using plugin @nx/cypress/plugin. 

	 Inner Error: Error: invalid type: unit value, expected struct Options
    at module.exports.__wbindgen_error_new (/home/vsts/work/1/s/node_modules/@swc/wasm/wasm.js:489:17)
    at null.<anonymous> (wasm://wasm/047124f6:1:13417760)
    at null.<anonymous> (wasm://wasm/047124f6:1:13784024)
    at null.<anonymous> (wasm://wasm/047124f6:1:13940751)
    at null.<anonymous> (wasm://wasm/047124f6:1:4307981)
    at null.<anonymous> (wasm://wasm/047124f6:1:3200484)
    at null.<anonymous> (wasm://wasm/047124f6:1:11323936)
    at null.<anonymous> (wasm://wasm/047124f6:1:2115846)
    at null.<anonymous> (wasm://wasm/047124f6:1:2968116)
    at null.<anonymous> (wasm://wasm/047124f6:1:3560985)
    at /home/vsts/work/1/s/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:155:31
    at async Promise.all (index 0)
    at async Promise.all (index 3)
    at createProjectConfigurations (/home/vsts/work/1/s/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:62)
    at buildProjectGraphAndSourceMapsWithoutDaemon (/home/vsts/work/1/s/node_modules/nx/src/project-graph/project-graph.js:73:69)
    at createProjectGraphAndSourceMapsAsync (/home/vsts/work/1/s/node_modules/nx/src/project-graph/project-graph.js:139:25)
    at createProjectGraphAsync (/home/vsts/work/1/s/node_modules/nx/src/project-graph/project-graph.js:128:39)
    at Object.showProjectsHandler (/home/vsts/work/1/s/node_modules/nx/src/command-line/show/show.js:15:17) {
  [cause]: Error: invalid type: unit value, expected struct Options
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by saurabh-cf** [comment]
Facing the same issue. After migrating to latest nx version today `18.1.2`, the circleCI build pipeline started failing.
On investigating, found that the `yarn nx affected --target=build` is failing because it's not fetching the correct `affected` apps/libs which changed.

**Comment by pajosieg** [comment]
I get the same error when I run a custom executor. Nx `18.1.2 ` with `node:20-alpine` under `arm64`.

**Comment by FrozenPandaz** [comment]
This seems like an error coming from swc. Could you post an issue there please? https://github.com/swc-project/swc/issues

**Comment by Vishal--Patel** [comment]
This issue was resolved by deleting the package.lock.json file and always executing npm install with the force option. We were unable to identify this alternative solution and suspect that the problem might be related to the platform type (e.g., Linux, Windows). I can further help if someone is still having this issue.

**Comment by Vishal--Patel** [comment]
> I get the same error when I run a custom executor. Nx `18.1.2` with `node:20-alpine` under `arm64`.

Please try above steps.

**Comment by Vishal--Patel** [comment]
> Facing the same issue. After migrating to latest nx version today `18.1.2`, the circleCI build pipeline started failing. On investigating, found that the `nx affected --target=build` is failing because it's not fetching the correct `affected` apps/libs which changed.

Please try above mentioned steps.
