### ISSUE TITLE
Migrating to 18.1.2 and seeing this error: `Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by diegoholiveira** [nrwl/nx#22439]
### Current Behavior

Build breaks after upgrade from `18.0.8` to `18.1.2`

```

### Expected Behavior

Build completing without errors, like it does with 18.0.8.

### GitHub Repo

_No response_

### Steps to Reproduce

Not sure if this error is reproducible in other repos since it may be some specific configuration that `nx migrate` does not apply.

### Nx Report

```shell
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/diego/monorepo/node_modules/.pnpm/nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.106/node_modules/nx/src/utils/params.js:194:24
    at Array.find (<anonymous>)
    at validateObject (/Users/diego/monorepo/node_modules/.pnpm/nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.106/node_modules/nx/src/utils/params.js:193:27)
    at validateProperty (/Users/diego/monorepo/node_modules/.pnpm/nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.106/node_modules/nx/src/utils/params.js:346:9)
    at /Users/diego/monorepo/node_modules/.pnpm/nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.106/node_modules/nx/src/utils/params.js:210:9
    at Array.forEach (<anonymous>)
    at validateObject (/Users/diego/monorepo/node_modules/.pnpm/nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.106/node_modules/nx/src/utils/params.js:209:23)
    at validateOptsAgainstSchema (/Users/diego/monorepo/node_modules/.pnpm/nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.106/node_modules/nx/src/utils/params.js:144:5)
    at combineOptionsForExecutor (/Users/diego/monorepo/node_modules/.pnpm/nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.106/node_modules/nx/src/utils/params.js:432:5)
```

### Package Manager Version

pnpm 8.15.4

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Migrate done with `nx migrate latest`

**Comment by timonmasberg** [comment]
Probably related to https://github.com/nrwl/nx/issues/22349

**Comment by FrozenPandaz** [comment]
Yup, closing as a dupilcate. The fix will be released soon.
