### ISSUE TITLE
Panic when running Nx v18 in CI: "No such device or address"

### ISSUE THREAD

**Issue by johnnywalker** [nrwl/nx#22445]
### Current Behavior

Nx v18 panics when executed by Nix builder in CI environment (e.g. GitHub Actions)

Command executed by Nix builder:

```shell
nx run-many -t lint --all --output-style=static
```

Tail of output:

```
thread '<unnamed>' panicked at packages/nx/src/native/pseudo_terminal/pseudo_terminal.rs:60:27:
Failed to enter raw terminal mode: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

### Expected Behavior

Run tasks without panicking.

### GitHub Repo

https://github.com/johnnywalker/nx-panic-repro

### Steps to Reproduce

1. Run `validate` workflow in GitHub Actions.
2. Alternatively, run `nix flake check -L --system x86_64-linux` from macOS with linux-builder configured via nix-darwin.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : darwin-x64
npm    : 10.2.4

nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/linter         : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nrwl/tao          : 18.1.2
@nx/vite           : 18.1.2
@nx/web            : 18.1.2
typescript         : 5.3.3
```

### Failure Logs

```shell
thread '<unnamed>' panicked at packages/nx/src/native/pseudo_terminal/pseudo_terminal.rs:60:27:
Failed to enter raw terminal mode: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```
```


### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This seems to be related to containerization since I'm able to trigger the error from macOS by running a remote Linux build via qemu. Ultimately, can Nx just continue with raw mode [instead of panicking here](https://github.com/nrwl/nx/blob/c20e00cab86be9fe32a09320941ba0f0bb39733d/packages/nx/src/native/pseudo_terminal/pseudo_terminal.rs#L60)?

**Comment by zilia-gmethot** [comment]
I have the same issue

**Comment by pietdevries94** [comment]
I had the same problem when trying to package my app using nix.

The problem is that when nix builds a package, it doesn't use a terminal for this, because it simply doesn't run in one. However Nx 18 always needs to run in at least a pseudo terminal. The correctness of this is questionable, but luckily there is a workaround.

util-linux has a tool called script, which records everything you do within that session to a file. This is however also a pseudo terminal, which helps in our workaround. The easiest way to run a command this way is as following:
```bash
script -c "nx show projects" /dev/null
```

**The /dev/null is important!** The las argument is the file it writes to, which by default is called typescript, which nx will try to parse as the typescript package. And because the recording is useless for our usecase anyway, we can throw that away into /dev/null

For the nix squad: the package that contains script is called `util-linux`. You can also call it in your scripts as follows:
```bash
${pkgs.util-linux}/bin/script -c "nx show projects" /dev/null
```

You can also create a seperate script and call it this way to wrap away the uglyness ;)

**Comment by ryanolson-aumni** [comment]
Anyone from the NX team want to weight in? This is BS. We have an NX command that runs tests and it's failing with this same rust panic.

**Comment by ryanolson-aumni** [comment]
@AgentEnder Are you digging into this?

**Comment by pluiedev** [comment]
Also coming from Nix, requiring a pseudo-TTY to build anything with Nx is simply ridiculous. Just have a headless mode that you can switch on or better yet simply don't crash when you can't find one.

**Comment by xolox** [comment]
It's a shame to see this issue hasn't seen any official input or resolution.

I can't imagine it's that hard to work around, from my outsider perspective it seems like one or two additional `if` statements could be enough. In shell code `test -t 0` would work, in Python `sys.stdin.isatty()` would do the trick, as a guard around invoking the functionality that dumps this "fatal runtime error" into our non-interactive terminals.

For my use case we are running various `nx` commands as wrappers for build functionality and when our developers run these commands they work fine (of course, from an interactive terminal) but when we run them on our build server, in a non-interactive environment, we get the "fatal runtime error" with the nasty traceback.

For now I've wrapped `/usr/bin/script` around the `nx` invocation but it's quite ugly that this is needed...

**Comment by ryanolson-aumni** [comment]
@xiongemi ?

**Comment by Sk7Str1p3** [comment]
Same issue, not stale
