### ISSUE TITLE
Failed unit test for generator - TypeError: performance.mark is not a function (Upgrading from Nx 17.0.1 to 18.1.2)

### ISSUE THREAD

**Issue by sreenath** [nrwl/nx#22447]
### Current Behavior

I have a custom generator that calls `configurationGenerator` from `@nx/cypress` and I have a unit test to test the generator.  This results in the below error:
 
```
Error: TypeError: performance.mark is not a function
at buildProjectsConfigurationsFromProjectPathsAndPlugins (../../../node_modules/nx/src/project-graph/utils/project-configuration-utils.js:138:21)
      at createProjectConfigurations (../../../node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
      at _retrieveProjectConfigurations (../../../node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
      at retrieveProjectConfigurations (../../../node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
      at async buildProjectGraphAndSourceMapsWithoutDaemon (../../../node_modules/nx/src/project-graph/project-graph.js:73:69)
      at async createProjectGraphAndSourceMapsAsync (../../../node_modules/nx/src/project-graph/project-graph.js:139:25)
      at async createProjectGraphAsync (../../../node_modules/nx/src/project-graph/project-graph.js:128:39)
      at async configurationGeneratorInternal (../../../node_modules/@nx/cypress/src/generators/configuration/configuration.js:35:26)
      at async libraryGenerator (src/generators/library/generator.ts:66:5)
      at async Object.<anonymous> (src/generators/library/generator.spec.ts:321:5)
    FAIL src/generators/library/generator.spec.ts (10085 ms)
```

I use Jest and tried running using testEnvironment as `node` and `jsdom`. But same error. 

### Expected Behavior

Unit test should not fail as the actual library generation was successful as there were no changes other than migrating Nx and plugin versions from 17 to 18. 

### Steps to Reproduce

Run the unit test for generator.

### Nx Report

```shell
Node   : 20.11.1
OS     : darwin-arm64
yarn   : 1.22.15

nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/jest           : 18.1.2
@nx/linter         : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/cypress        : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nx/plugin         : 18.1.2
@nx/react          : 18.1.2
@nrwl/tao          : 18.1.2
@nx/vite           : 18.1.2
@nx/web            : 18.1.2
typescript         : 5.0.4
---------------------------------------
Local workspace plugins:
         @npco/react
```

### Failure Logs

```shell
Error: TypeError: performance.mark is not a function
  
      at buildProjectsConfigurationsFromProjectPathsAndPlugins (../../../node_modules/nx/src/project-graph/utils/project-configuration-utils.js:138:21)
      at createProjectConfigurations (../../../node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
      at _retrieveProjectConfigurations (../../../node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
      at retrieveProjectConfigurations (../../../node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
      at async buildProjectGraphAndSourceMapsWithoutDaemon (../../../node_modules/nx/src/project-graph/project-graph.js:73:69)
      at async createProjectGraphAndSourceMapsAsync (../../../node_modules/nx/src/project-graph/project-graph.js:139:25)
      at async createProjectGraphAsync (../../../node_modules/nx/src/project-graph/project-graph.js:128:39)
      at async configurationGeneratorInternal (../../../node_modules/@nx/cypress/src/generators/configuration/configuration.js:35:26)
      at async libraryGenerator (src/generators/library/generator.ts:66:5)
      at async Object.<anonymous> (src/generators/library/generator.spec.ts:321:5)
    FAIL src/generators/library/generator.spec.ts (10085 ms)
```

### Package Manager Version

1.22.15

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Custom generator used

```
export const generateCypressTests = (
  tree: Tree,
  { libraryName, applicationToTestAgainst }: GenerateCypressTestsArgs
) => {
  return configurationGenerator(tree, {
    project: libraryName,
    bundler: 'vite',
    devServerTarget: `${applicationToTestAgainst}:serve`,
    // Skip installing vite and eslint plugin versions
    skipPackageJson: true,
    directory: 'cypress',
  })
}
```

The error happens when calling the above function from the generator 
```
    await generateCypressTests(tree, {
      libraryName,
      applicationToTestAgainst: 'react-app'
    })
```

I already tried setting `testEnvironment: 'node'` in jest.config.ts as specified in https://github.com/nrwl/nx/issues/21063 bug.

**Comment by sreenath** [comment]
I was applying `testEnvironment: 'node'` in an incorrect config. Setting this in libraries `jest.config.ts` fixed the issue.
