### ISSUE TITLE
PluginError: Failed to resolve plugin for module

### ISSUE THREAD

**Issue by vendramini** [nrwl/nx#22465]
### Current Behavior

Running `nx build cats --local --profile=preview --platform=ios` gives me the error:
```
[READ_APP_CONFIG]
PluginError: Failed to resolve plugin for module "@config-plugins/detox" relative to "/var/folders/bm/z5qdvvh94_q565bkp7kty3zm0000gn/T/eas-build-local-nodejs/fd2cea83-5a69-47f9-9f27-ad1288cd6861/build/apps/cats"
    at resolvePluginForModule (/Users/vendramini/.npm/_npx/7cb2e17578656054/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js:72:11)
    at resolveConfigPluginFunctionWithInfo (/Users/vendramini/.npm/_npx/7cb2e17578656054/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js:152:7)
    at resolveConfigPluginFunction (/Users/vendramini/.npm/_npx/7cb2e17578656054/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js:143:7)
    at withStaticPlugin (/Users/vendramini/.npm/_npx/7cb2e17578656054/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js:87:70)
    at /Users/vendramini/.npm/_npx/7cb2e17578656054/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:84
    at Array.reduce (<anonymous>)
    at withPlugins (/Users/vendramini/.npm/_npx/7cb2e17578656054/node_modules/@expo/config-plugins/build/plugins/withPlugins.js:30:18)
    at withConfigPlugins (/Users/vendramini/.npm/_npx/7cb2e17578656054/node_modules/@expo/config/build/plugins/withConfigPlugins.js:36:47)
    at fillAndReturnConfig (/Users/vendramini/.npm/_npx/7cb2e17578656054/node_modules/@expo/config/build/Config.js:218:78)
    at getConfig (/Users/vendramini/.npm/_npx/7cb2e17578656054/node_modules/@expo/config/build/Config.js:274:10)

Build failed
Unknown error. See logs of the Read app config build phase for more information.
npx exited with non-zero code: 1
```

### Expected Behavior

Compile without error. Apparently it's not reaching the node_modules package, but the `sync-deps` and `ensure-symlink` command have been successfully executed.

### GitHub Repo

https://github.com/xiongemi/nx-expo-monorepo

### Steps to Reproduce

1. Clone the repo and `nx build cats --local --profile=preview --platform=ios`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 21.6.1
OS     : darwin-arm64
npm    : 10.2.4

nx (global)        : 18.0.4
nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/jest           : 18.1.2
@nx/linter         : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/cypress        : 18.1.2
@nx/detox          : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nx/expo           : 18.1.2
@nx/next           : 18.1.2
@nx/react          : 18.1.2
@nx/react-native   : 18.1.2
@nx/storybook      : 18.1.2
@nrwl/tao          : 18.1.2
@nx/web            : 18.1.2
@nx/webpack        : 18.1.2
typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I was following this tutorial: https://dev.to/nx/step-by-step-guide-to-creating-an-expo-monorepo-with-nx-3b17

**Comment by xiongemi** [comment]
i fixed in my repo. i think i missed @config-plugins/detox in package.json.
closing it for now.
