### ISSUE TITLE
When attempting to remove a library, getting: The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by omerfaran** [nrwl/nx#22471]
### Current Behavior

I'm trying to remove a library, for example:
` npx nx g @nrwl/workspace:remove ui`
(Tried with a few different libs)
But receiving the error:
`The "path" argument must be of type string. Received null`

For the Stacktrace when running with verbose flag - please see at Failure Logs

### Expected Behavior

Should remove the lib

### GitHub Repo

https://github.com/omerfaran/nx-test

### Steps to Reproduce

1. Please clone my repo
2. run "pnpm i"
3. run "nx generate remove ui"

### Nx Report

```shell
Node   : 20.11.0
OS     : win32-x64
pnpm   : 8.15.5

nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/linter         : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/cypress        : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nx/react          : 18.1.2
@nx/storybook      : 18.1.2
@nrwl/tao          : 18.1.2
@nx/vite           : 18.1.2
@nx/web            : 18.1.2
typescript         : 5.3.3
```

### Failure Logs

```shell
TypeError: The "path" argument must be of type string. Received null
    at validateString (node:internal/validators:162:11)
    at join (node:path:433:7)
    at FsTree.normalize (C:\Users\Omer\Documents\testdelete\nx-test\node_modules\.pnpm\nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\generators\tree.js:225:64)
    at FsTree.exists (C:\Users\Omer\Documents\testdelete\nx-test\node_modules\.pnpm\nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\generators\tree.js:94:25)   
    at updateJestConfig (C:\Users\Omer\Documents\testdelete\nx-test\node_modules\.pnpm\@nx+workspace@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\@nx\workspace\src\generators\remove\lib\update-jest-config.js:41:15)
    at removeGenerator (C:\Users\Omer\Documents\testdelete\nx-test\node_modules\.pnpm\@nx+workspace@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\@nx\workspace\src\generators\remove\remove.js:17:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at C:\Users\Omer\Documents\testdelete\nx-test\node_modules\.pnpm\nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\command-line\generate\generate.js:241:26   
    at handleErrors (C:\Users\Omer\Documents\testdelete\nx-test\node_modules\.pnpm\nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\utils\params.js:9:16)        
    at Object.handler (C:\Users\Omer\Documents\testdelete\nx-test\node_modules\.pnpm\nx@18.1.2_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\command-line\generate\command-object.js:13:22)
```

### Package Manager Version

8.15.5

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by jln-dk** [comment]
Getting the same error. Using the Nx plugin is VS Code.

![Screenshot 2024-03-27 at 12 15 02](https://github.com/nrwl/nx/assets/5707542/cb59402c-fc1d-4b6e-9bca-52d6f2c46875)

![Screenshot 2024-03-27 at 12 15 13](https://github.com/nrwl/nx/assets/5707542/3ca0c0ab-9b7b-4afe-8e2c-bf8caeb64888)

![Screenshot 2024-03-27 at 12 16 25](https://github.com/nrwl/nx/assets/5707542/b57b1cc0-d050-40d5-b2b6-52341c6e3ee7)

**Comment by kylecannon** [comment]
seeing the same issue here.

**Comment by anujmv** [comment]
Same issue

**Comment by adjiandov** [comment]
Same issue...

**Comment by alfianandinugraha** [comment]
same here in MacOS M1

<img width="987" alt="image" src="https://github.com/nrwl/nx/assets/34809276/48cf2415-33ba-4fe9-bbd7-73cafae9b28c">

**Comment by OlkaB** [comment]
Try using this solution until it's fixed (worked for me)
https://github.com/nrwl/nx/issues/22346#issuecomment-2058321237

**Comment by aklaffenboeck** [comment]
Same issue with running ` nx g @nx/angular:scam-to-standalone` on Windows 11.

**Comment by MaxKless** [comment]
thanks for the report @omerfaran and everyone else for confirming it. 
This has been fixed in https://github.com/nrwl/nx/pull/23328

@aklaffenboeck if you're still running into a similar issue on the latest nx with another generator, please create a new issue with your `nx report` & the detailed error message.
