### ISSUE TITLE
 unable to get local issuer certificate

### ISSUE THREAD

**Issue by hmaidithamer** [nrwl/nx#22561]
### Current Behavior

 NX  Generating nx:connect-to-nx-cloud

 NX   unable to get local issuer certificate

Error: unable to get local issuer certificate
    at AxiosError.from (C:\Users\thamer.hmaidi\Documents\projects\cicd\test\node_modules\axios\dist\node\axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (C:\Users\thamer.hmaidi\Documents\projects\cicd\test\node_modules\axios\dist\node\axios.cjs:3086:25)
    at RedirectableRequest.emit (node:events:518:28)
    at eventHandlers.<computed> (C:\Users\thamer.hmaidi\Documents\projects\cicd\test\node_modules\follow-redirects\index.js:38:24)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (C:\Users\thamer.hmaidi\Documents\projects\cicd\test\node_modules\axios\dist\node\axios.cjs:3876:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createNxCloudWorkspace (C:\Users\thamer.hmaidi\Documents\projects\cicd\test\node_modules\nx\src\nx-cloud\generators\connect-to-nx-cloud\connect-to-nx-cloud.js:49:22)
    at async connectToNxCloud (C:\Users\thamer.hmaidi\Documents\projects\cicd\test\node_modules\nx\src\nx-cloud\generators\connect-to-nx-cloud\connect-to-nx-cloud.js:94:19)
    at async C:\Users\thamer.hmaidi\Documents\projects\cicd\test\node_modules\nx\src\command-line\generate\generate.js:241:26
    at async handleErrors (C:\Users\thamer.hmaidi\Documents\projects\cicd\test\node_modules\nx\src\utils\params.js:9:16)
    at async Object.handler (C:\Users\thamer.hmaidi\Documents\projects\cicd\test\node_modules\nx\src\command-line\generate\command-object.js:13:22)

### Expected Behavior

connect to nx cloud 

### Steps to Reproduce

1. create new Workspace using npx create-nx-workspace@latest
Result:
✖ Setting up Nx Cloud

 NX   Failed to setup Nx Cloud
Error:
 NX   unable to get local issuer certificate

### Nx Report

```shell
✔ Installing dependencies with npm
✔ Successfully created the workspace: test.
✖ Setting up Nx Cloud

 NX   Failed to setup Nx Cloud

Error:
 NX   unable to get local issuer certificate

Pass --verbose to see the stacktrace.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Are you using a different `NX_CLOUD_API` endpoint?

**Comment by hmaidithamer** [comment]
@FrozenPandaz  No, i get this error when i try to create new workspace
