### ISSUE TITLE
Project at apps/engine-e2e has no name provided.

### ISSUE THREAD

**Issue by mpduffey** [nrwl/nx#22589]
### Current Behavior

When I create a new Angular app in NX and without doing a thing attempt to serve the app, I get an error message that says "Project at apps/engine-e2e has no name provided."

### Expected Behavior

I expect the app to serve.

### Steps to Reproduce

1. Create an nx/angular workspace
2. Create an app in the nx workspace
3. Attempt to serve the app

### Nx Report

```shell
NX   Project at apps/engine-e2e has no name provided.
```

### Failure Logs

```shell
Error: Project at apps/engine-e2e has no name provided.
    at readProjectConfigurationsFromRootMap (/home/ubuntu/monorepo/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:370:23)
    at /home/ubuntu/monorepo/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:328:26
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at processFilesAndCreateAndSerializeProjectGraph (/home/ubuntu/monorepo/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:148:26)
    at getCachedSerializedProjectGraphPromise (/home/ubuntu/monorepo/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:45:16)
    at handleRequestProjectGraph (/home/ubuntu/monorepo/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
    at handleResult (/home/ubuntu/monorepo/node_modules/nx/src/daemon/server/server.js:110:16)
    at handleMessage (/home/ubuntu/monorepo/node_modules/nx/src/daemon/server/server.js:81:9)
    at /home/ubuntu/monorepo/node_modules/nx/src/daemon/server/server.js:45:9
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mpduffey** [comment]
Updating nx resolved the issue

**Comment by beqacrc** [comment]
remove .nx folder and re-run command

**Comment by Rapol** [comment]
I was creating a new library in an nx project. I decided to copy an existing library since it was going to be similar. I renamed the files and variables correctly and got this issue. Deleting `.nx` solved it. Whats interesting was that the error said "Project at xx (copy) has no name provided.". For some reason it cached the previous folder name.

**Comment by tonivj5** [comment]
> I was creating a new library in an nx project. I decided to copy an existing library since it was going to be similar. I renamed the files and variables correctly and got this issue. Deleting `.nx` solved it. Whats interesting was that the error said "Project at xx (copy) has no name provided.". For some reason it cached the previous folder name.

I have suffered from the same issue using nx into a npm workspace monorepo. It seems like its daemon handles in a bad way...
