### ISSUE TITLE
Can't install any js plugin in a non js repo root

### ISSUE THREAD

**Issue by artsiommiksiuk** [nrwl/nx#22669]
### Current Behavior

I'm trying to manage multi language monorepo. Installing repo with ```nx init```.
Later using ```nx add @nx/js``` fails with:

```
nx add --verbose @nx/js

✔ Installing @nx/js@latest...
⠋ Initializing @nx/js...
 NX  Generating @nx/js:init

⠙ Initializing @nx/js...
 NX   Cannot find package.json
 

Error: Cannot find package.json
    at readJson (/Users/user/Projects/backend/.nx/installation/node_modules/nx/src/generators/utils/json.js:14:15)
    at addDependenciesToPackageJson (/Users/user/Projects/backend/.nx/installation/node_modules/@nx/devkit/src/utils/package-json.js:93:32)
    at initGenerator (/Users/user/Projects/backend/.nx/installation/node_modules/@nx/js/src/generators/init/init.js:100:53)
    at /Users/user/Projects/backend/.nx/installation/node_modules/nx/src/command-line/generate/generate.js:241:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/Users/user/Projects/backend/.nx/installation/node_modules/nx/src/utils/params.js:9:16)
    at async Object.handler (/Users/user/Projects/backend/.nx/installation/node_modules/nx/src/command-line/generate/command-object.js:13:22)
✖ Initializing @nx/js...
 
 Command failed: ./nx g @nx/js:init --keepExistingVersions
```

While installation of @nx/workspaces works, but seems like because it doesn't have any init logic.

### Expected Behavior

I can install any plugin into non js root repo without an issues and utilize multilanguage setup benefits while orchestrating it with nx.

### Steps to Reproduce

1. Create empty project with git
2. npx nx init
3. npx nx add @nx/js

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : darwin-arm64
pnpm   : 8.15.6

nx (global)    : 18.2.2
nx             : 18.2.2
@nx/js         : 18.2.2
@nx/jest       : 18.2.2
@nx/eslint     : 18.2.2
@nx/workspace  : 18.2.2
@nx/devkit     : 18.2.2
@nx/node       : 18.2.2
@nrwl/tao      : 18.2.2
typescript     : 5.4.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hi @artsiommiksiuk !

Thanks for raising this issue, unfortunately, the `@nx/js` package needs to install dependencies at the root of the workspace, requiring a `package.json` file to exist there. Therefore, you will have to run `npm init` before trying to run `nx add @nx/js`
