### ISSUE TITLE
regression: `run-commands` produces MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by vire** [nrwl/nx#22689]
### Current Behavior

I run my `run-commands` target and I can see in the console

```
(node:86270) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

when I CTRL+C the command I get 

```
^Cnode:internal/util:342
  throw new ERR_UNKNOWN_SIGNAL(signal);
  ^

TypeError [ERR_UNKNOWN_SIGNAL]: Unknown signal: 130
    at new NodeError (node:internal/errors:405:5)
    at convertToValidSignal (node:internal/util:342:9)
    at ChildProcess.kill (node:internal/child_process:489:5)
    at process.processExitListener (/Users/project/node_modules/.pnpm/nx@18.2.2_@swc-node+register@1.9.0_@swc+core@1.4.8/node_modules/nx/src/executors/run-commands/run-commands.impl.js:201:62)
    at process.emit (node:events:529:35)
    at process.exit (node:internal/process/per_thread:191:15)
    at process.<anonymous> (/Users/project/node_modules/.pnpm/nx@18.2.2_@swc-node+register@1.9.0_@swc+core@1.4.8/node_modules/nx/src/tasks-runner/forked-process-task-runner.js:345:21)
    at process.emit (node:events:529:35) {
  code: 'ERR_UNKNOWN_SIGNAL'
}

Node.js v18.20.1
```

### Expected Behavior

No `MaxListenersExceededWarning` are present, CTRL+C does not throw

### Steps to Reproduce

n/a

### Nx Report

```shell
Node   : 18.20.1
OS     : darwin-arm64
pnpm   : 8.15.6

nx                 : 18.2.2
@nx/js             : 18.2.2
@nx/jest           : 18.2.2
@nx/linter         : 18.2.2
@nx/eslint         : 18.2.2
@nx/workspace      : 18.2.2
@nx/cypress        : 18.2.2
@nx/devkit         : 18.2.2
@nx/esbuild        : 18.2.2
@nx/eslint-plugin  : 18.2.2
@nx/next           : 18.2.2
@nx/node           : 18.2.2
@nx/plugin         : 18.2.2
@nx/react          : 18.2.2
@nx/storybook      : 18.2.2
@nrwl/tao          : 18.2.2
@nx/web            : 18.2.2
@nx/webpack        : 18.2.2
typescript         : 5.4.3
```

### Package Manager Version

pnpm@8.15.6

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

possible regression of https://github.com/nrwl/nx/pull/20006

**Comment by xiongemi** [comment]
@vire what command were you trying to run?

**Comment by xiongemi** [comment]
i am able to replicate this issue. i think it is related to this ticket https://github.com/nrwl/nx/issues/22643. for now, maybe try set NX_NATIVE_COMMAND_RUNNER=false when running your commands.

need to do a proper fix.

**Comment by vire** [comment]
After `pnpm nx migrate latest` && `pnpm nx migrate --run-migrations` -> `18.3.4` the problem seems to be gone.

**Comment by xiongemi** [comment]
closing this issue for now
