### ISSUE TITLE
@nx/jest/plugin: Validation error, unable to parse displayName

### ISSUE THREAD

**Issue by clawrence121** [nrwl/nx#22735]
### Current Behavior

Upon generating a brand new workspace the included Jest plugin is unable to parse the generated Jest configuration.

```
import type { Config } from 'jest';

const config: Config = {
  displayName: 'api',
  preset: '../../jest.preset.js',
  testEnvironment: 'node',
  transform: {
    '^.+\\.[tj]s$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.spec.json' }],
  },
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageDirectory: '../../coverage/apps/api',
};

/* eslint-disable */
export default config;
```

As per the [Jest Docs](https://jestjs.io/docs/configuration#displayname-string-object) and the TS definition the config is correct.

Any attempt to match the recommendation from the error log causes it to change just slights to recommend something else.

### Expected Behavior

Able to run the project graph and tasks with the default Jest config.

### GitHub Repo

https://github.com/clawrence121/nx-jest-bug

### Steps to Reproduce

1. Create a new repo `npx create-nx-workspace`
2. Choose: NestJS, Integrated, No cloud
3. Open repo
4. Run `npm i` as the base install seems broken (possibly related?)
5. `nx serve {app}`
6. Make any change to the code to trigger HMR
7. It will now be stuck not able to parse the Jest config

### Nx Report

```shell
Node   : 20.10.0
OS     : darwin-arm64
npm    : 10.2.3

nx                 : 18.2.3
@nx/js             : 18.2.3
@nx/jest           : 18.2.3
@nx/linter         : 18.2.3
@nx/eslint         : 18.2.3
@nx/workspace      : 18.2.3
@nx/devkit         : 18.2.3
@nx/eslint-plugin  : 18.2.3
@nx/nest           : 18.2.3
@nx/node           : 18.2.3
@nrwl/tao          : 18.2.3
@nx/web            : 18.2.3
@nx/webpack        : 18.2.3
typescript         : 5.4.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
Failed to process project graph.
  The "@nx/jest/plugin" plugin threw an error while creating nodes from apps/api/jest.config.ts:
    Error: ● Validation Error:
    
      Option "displayName" must be of type:
        array
      but instead received:
        string
    
      Example:
      {
        "displayName": [
          "test-config",
          {
            "color": "blue",
            "name": "test-config"
          }
        ]
      }
    
      Configuration Documentation:
      https://jestjs.io/docs/configuration
```

### Package Manager Version

npm 10.2.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Removing the plugin registration in nx.json resolves the issue, but stops Jest from working

**Comment by clawrence121** [comment]
After some more testing, it might be a bug within the `.nx/cache`, as when clearing that plus node module it will briefly reset the state:

```
src git:(04-08-scaffold_api_nest_app) ✗ rm -rf dist        
➜  src git:(04-08-scaffold_api_nest_app) ✗ rm -rf node_modules
➜  src git:(04-08-scaffold_api_nest_app) ✗ rm -rf .nx         
➜  src git:(04-08-scaffold_api_nest_app) ✗ npx nx test api    

 NX   Could not find Nx modules in this workspace.

Have you run npm/yarn install?

➜  src git:(04-08-scaffold_api_nest_app) ✗ npm i
npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead

added 1050 packages, and audited 1051 packages in 5s

147 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  src git:(04-08-scaffold_api_nest_app) ✗ npx nx test api    

> nx run api:test

> jest

 FAIL   api  src/app/app.controller.spec.ts
  ● AppController › getData › should return "Hello API"

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
    -   "message": "Hello API",
    +   "message": "Hello API!",
      }

      17 |     it('should return "Hello API"', () => {
      18 |       const appController = app.get<AppController>(AppController);
    > 19 |       expect(appController.getData()).toEqual({message: 'Hello API'});
         |                                       ^
      20 |     });
      21 |   });
      22 | });

      at Object.<anonymous> (src/app/app.controller.spec.ts:19:39)

 FAIL   api  src/app/app.service.spec.ts
  ● AppService › getData › should return "Hello API"

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
    -   "message": "Hello API",
    +   "message": "Hello API!",
      }

      16 |   describe('getData', () => {
      17 |     it('should return "Hello API"', () => {
    > 18 |       expect(service.getData()).toEqual({message: 'Hello API'});
         |                                 ^
      19 |     });
      20 |   });
      21 | });

      at Object.<anonymous> (src/app/app.service.spec.ts:18:33)

Test Suites: 2 failed, 2 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        0.753 s, estimated 1 s
Ran all test suites.
Warning: command "jest" exited with non-zero status code
———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target test for project api (2s)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

➜  src git:(04-08-scaffold_api_nest_app) ✗ npx nx serve api   

> nx run api:serve:development

Build option outputFileName not set for api. Using fallback value of dist/apps/api/main.js.

> nx run api:build

> webpack-cli build --node-env=production

chunk (runtime: main) main.js (main) 2.71 KiB [entry] [rendered]
webpack compiled successfully (3df739613936a9e3)

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target build for project api (2s)

Debugger listening on ws://localhost:9229/af1beb0f-7e5f-445b-aaec-5242adc71c31
Debugger listening on ws://localhost:9229/af1beb0f-7e5f-445b-aaec-5242adc71c31
For help, see: https://nodejs.org/en/docs/inspector

[Nest] 75545  - 04/09/2024, 8:08:23 AM     LOG [NestFactory] Starting Nest application...
[Nest] 75545  - 04/09/2024, 8:08:23 AM     LOG [InstanceLoader] AppModule dependencies initialized +5ms
[Nest] 75545  - 04/09/2024, 8:08:23 AM     LOG [RoutesResolver] AppController {/api}: +2ms
[Nest] 75545  - 04/09/2024, 8:08:23 AM     LOG [RouterExplorer] Mapped {/api, GET} route +1ms
[Nest] 75545  - 04/09/2024, 8:08:23 AM     LOG [NestApplication] Nest application successfully started +1ms
[Nest] 75545  - 04/09/2024, 8:08:23 AM     LOG 🚀 Application is running on: http://localhost:3000/api

 NX  File change detected. Restarting...

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Failed to process project graph.
  The "@nx/jest/plugin" plugin threw an error while creating nodes from apps/api/jest.config.ts:
    Error: ● Validation Error:
    
      Option "displayName" must be of type:
        array
      but instead received:
        string
    
      Example:
      {
        "displayName": [
          "test-config",
          {
            "color": "blue",
            "name": "test-config"
          }
        ]
      }
    
      Configuration Documentation:
      https://jestjs.io/docs/configuration
    ] {
  name: 'ProjectGraphError'
}

Node.js v20.10.0
Build failed, waiting for changes to restart...

**Comment by clawrence121** [comment]
Resolved in the short term with by removing displayName.

Duplicate of https://github.com/nrwl/nx/issues/22478 so closing
