### ISSUE TITLE
the build is success with ng but failes with nx

### ISSUE THREAD

**Issue by its-dibo** [nrwl/nx#22758]
### Current Behavior

# issue

migrating an existing simple Angular into a NX monorepo
the monorepo has one workspace under apps/app1 which is an Angular app

`nx init` is run in the root dir to convert the monorepo into NX monorepo, 
and then inside apps/app1 to convert the project into NX project, by replacing angular.json with project.json

running the build with `nx` instead of ng` fails with this error:

```
Cannot find tsconfig file "tsconfig.app.json"
```

also, I noticed that the build is done in the top-level dir instead of apps/app1.
for example `.angular` is created in the top-level dir

### Expected Behavior

the build is success with `nx build` 

### GitHub Repo

https://github.com/its-dibo/issue-nx-angular

### Steps to Reproduce

1- install dependences

2- run `npm run build:ng` which executes `ng build` -> the build is successful

3- run `npm run build` which executes `nx build` -> the build is failed

## update
I found that creating a `nx.json` file inside each project solves the issue, but the docs mention that we need to create only one nx.json file in the top-level, and only project.json inside each project.

### Nx Report

```shell
Node   : 20.10.0
OS     : linux-x64
npm    : 10.2.3

nx (global)    : 18.2.4
nx             : 18.2.4
@nx/js         : 18.2.4
@nx/linter     : 18.2.4
@nx/eslint     : 18.2.4
@nx/workspace  : 18.2.4
@nx/angular    : 18.2.4
@nx/devkit     : 18.2.4
@nrwl/tao      : 18.2.4
@nx/web        : 18.2.4
@nx/webpack    : 18.2.4
typescript     : 5.2.2
```

### Failure Logs

```shell
> nx run app1:build:production

Application bundle generation failed. [0.741 seconds]

▲ [WARNING] TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. [plugin angular-compiler]

    tsconfig.app.json:0:0:
      0 │ 
        ╵ ^

  To control ECMA version and features use the Browserslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility


✘ [ERROR] Cannot find tsconfig file "tsconfig.app.json"


✘ [ERROR] TS500: Error: ENOENT: no such file or directory, lstat '/home/dibo/dev/@issue/dibo/nx-angular/tsconfig.app.json'
    at Object.lstatSync (node:fs:1660:3)
    at NodeJSFileSystem.lstat (file:///home/dibo/dev/@issue/dibo/nx-angular/node_modules/@angular/compiler-cli/bundles/chunk-UM6JO3VZ.js:341:16)
    at calcProjectFileAndBasePath (file:///home/dibo/dev/@issue/dibo/nx-angular/node_modules/@angular/compiler-cli/bundles/chunk-GY5NSBQT.js:10253:29)
    at readConfiguration (file:///home/dibo/dev/@issue/dibo/nx-angular/node_modules/@angular/compiler-cli/bundles/chunk-GY5NSBQT.js:10279:39)
    at /home/dibo/dev/@issue/dibo/nx-angular/node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compilation/angular-compilation.js:61:69
    at profileSync (/home/dibo/dev/@issue/dibo/nx-angular/node_modules/@angular-devkit/build-angular/src/tools/esbuild/profiling.js:68:16)
    at AotCompilation.loadConfiguration (/home/dibo/dev/@issue/dibo/nx-angular/node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compilation/angular-compilation.js:61:44)
    at async AotCompilation.initialize (/home/dibo/dev/@issue/dibo/nx-angular/node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compilation/aot-compilation.js:50:100)
    at async initialize (/home/dibo/dev/@issue/dibo/nx-angular/node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compilation/parallel-worker.js:33:50)
    at async /home/dibo/dev/@issue/dibo/nx-angular/node_modules/piscina/dist/src/worker.js:145:26 [plugin angular-compiler]


✘ [ERROR] Could not resolve "/home/dibo/dev/@issue/dibo/nx-angular/src/main.ts"


✘ [ERROR] Cannot find tsconfig file "tsconfig.app.json"


✘ [ERROR] Could not resolve "src/styles.scss"

    angular:styles/global:styles:1:8:
      1 │ @import 'src/styles.scss';
        ╵         ~~~~~~~~~~~~~~~~~

  You can mark the path "src/styles.scss" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.



———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target build for project app1 (2s)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: app1@0.0.0 
npm ERR!   at location: /home/dibo/dev/@issue/dibo/nx-angular/apps/app1 

 *  The terminal process "/usr/bin/bash '-c', 'npm run build'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by its-dibo** [comment]
I changed all paths from "src/..." to the full path "apps/app1/src/..." which makes the file project.json not same as angular.json in the term of relative paths (the docs doesn't mention that we have to change the relative paths to be relative to the nx.json path instead of project.json)

anyway, now I got this error
```

✘ [ERROR] Could not resolve "zone.js/node"

    angular:polyfills-server:angular:polyfills-server:1:7:
      1 │ import 'zone.js/node';
        ╵        ~~~~~~~~~~~~~~

  You can mark the path "zone.js/node" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

**Comment by its-dibo** [comment]
it also seems that Angular searches for zone.js in the top-level node_modules or one that is near angular.json which is not found as it replaced by project.json

this causes Angular building to fail because it cannot resolve zone.js/node

**Comment by Coly010** [comment]
Hey :) Did you delete your reproduction repo? I tried to access it there and it's returning a 404 error.

If not, could you create it again so I can investigate further?
