### ISSUE TITLE
Cannot destructure property 'major' of '(0 , angular_version_utils_1.getInstalledAngularVersionInfo)

### ISSUE THREAD

**Issue by its-dibo** [nrwl/nx#22848]
### Current Behavior

once I switched from `@angular-devkit/build-angular:application` into  `@nx/angular:application`,
this error occurred 

```
 NX   Cannot destructure property 'major' of '(0 , angular_version_utils_1.getInstalledAngularVersionInfo)(...)' as it is null.
```

debug
```
TypeError: Cannot destructure property 'major' of '(0 , angular_version_utils_1.getInstalledAngularVersionInfo)(...)' as it is null.
    at validateOptions (/home/dibo/dev/@its-dibo/dibo/node_modules/.pnpm/@nx+angular@18.2.4_@angular-devkit+build-angular@17.3.4_@angular-devkit+core@17.3.4_@angular-_4fijc2zdumg73jymm4meyxyasq/node_modules/@nx/angular/src/executors/application/utils/validate-options.js:7:20)
    at applicationExecutor (/home/dibo/dev/@its-dibo/dibo/node_modules/.pnpm/@nx+angular@18.2.4_@angular-devkit+build-angular@17.3.4_@angular-devkit+core@17.3.4_@angular-_4fijc2zdumg73jymm4meyxyasq/node_modules/@nx/angular/src/executors/application/application.impl.js:10:44)
    at applicationExecutor.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/home/dibo/dev/@its-dibo/dibo/node_modules/.pnpm/nx@18.2.4/node_modules/nx/src/utils/async-iterator.js:13:27)
    at iteratorToProcessStatusCode (/home/dibo/dev/@its-dibo/dibo/node_modules/.pnpm/nx@18.2.4/node_modules/nx/src/command-line/run/run.js:43:94)
    at /home/dibo/dev/@its-dibo/dibo/node_modules/.pnpm/nx@18.2.4/node_modules/nx/src/command-line/run/run.js:179:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/home/dibo/dev/@its-dibo/dibo/node_modules/.pnpm/nx@18.2.4/node_modules/nx/src/utils/params.js:9:16)
    at async process.<anonymous> (/home/dibo/dev/@its-dibo/dibo/node_modules/.pnpm/nx@18.2.4/node_modules/nx/bin/run-executor.js:59:28)
```

### Expected Behavior

.

### Steps to Reproduce

.

### Nx Report

```shell
Node   : 20.10.0
OS     : linux-x64
pnpm   : 8.15.7

nx (global)  : 18.2.4
nx           : 18.2.4
@nx/jest     : 18.2.4
@nx/eslint   : 18.2.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hey :) Could you provide a reproduction repo that shows this error so I can investigate further?

Thank you!
