### ISSUE TITLE
nx 18 + nest + webpack + serverless breaking with error src/main.handler is undefined or not exported

### ISSUE THREAD

**Issue by pratik-github** [nrwl/nx#22875]
### Current Behavior

I am trying to setup serverless api using stack:
nx 18 + nest + webpack + serverless
node: 20.x

gives error:
```
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "src/main.handler is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: src/main.handler is undefined or not exported",
        "    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1122:15)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

### Expected Behavior

API should work

### GitHub Repo

https://github.com/pratik-github/demo-nx-nest-serverless

### Steps to Reproduce

1. use node v20.x
2. configure aws cli credentials
3. npm install
4. npx nx deploy graphql
5. Deployment is successful but when I hit api endpoint I get error;

Internal server error 
![image](https://github.com/nrwl/nx/assets/3119180/77e7f407-6beb-43c4-ac04-683225be48f2)

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.9.0
OS     : darwin-arm64
npm    : 10.1.0

nx                 : 18.2.4
@nx/js             : 18.2.4
@nx/jest           : 18.2.4
@nx/linter         : 18.2.4
@nx/eslint         : 18.2.4
@nx/workspace      : 18.2.4
@nx/devkit         : 18.2.4
@nx/eslint-plugin  : 18.2.4
@nx/nest           : 18.2.4
@nx/node           : 18.2.4
@nrwl/tao          : 18.2.4
@nx/web            : 18.2.4
@nx/webpack        : 18.2.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "src/main.handler is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: src/main.handler is undefined or not exported",
        "    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1122:15)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}

```

### Package Manager Version

10.1.0

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

verified by deploying to aws lambda

reference:
- https://docs.nestjs.com/faq/serverless
- https://nx.dev/recipes/webpack/webpack-config-setup

initial setup was done via `npx create-nx-workspace demoapp --preset=nest --bundler=webpack

**Comment by jameelio** [comment]
HI @pratik-github you can try the following add `libraryTarget:"commonjs2"` to the webpack.config.js

**Comment by jameelio** [comment]
@pratik-github final three file changes I made 
![image](https://github.com/nrwl/nx/assets/37529112/a8c09327-0665-48f1-9786-18280be6ab36)

**Comment by pratiksyngenta** [comment]
thanks @jameelio , I'll try these options and let you know

**Comment by ugho49** [comment]
Thanks a lot, I had the same issue and adding `libraryTarget:"commonjs2"` worked for me 🙏
