### ISSUE TITLE
NX Migrate from 17.2.8 to 18.3.1 fails when trying to execute 'npx nx migrate --run-migrations' - Failed to run rename-browser-target-to-build-target from @nx/angular

### ISSUE THREAD

**Issue by bsmarcosj** [nrwl/nx#22878]
### Current Behavior

I've tried running the migration:
```
npx nx migrate latest
npm install
npx nx migrate --run-migrations
```

results in:
```
 NX   Running migrations from 'migrations.json'

    
      ✓  Updated Angular CDK to version 17


 NX   Failed to run rename-browser-target-to-build-target from @nx/angular. This workspace is NOT up to date!


 NX   Cannot update Project tgx-web at apps/web. It either doesn't exist yet, or may not use project.json for configuration. Use 'addProjectConfiguration()' instead if you want to create a new project.
```

My angular.json is attached: [angular.json](https://github.com/nrwl/nx/files/15023683/angular.json)

### Expected Behavior

Workspace migrated to latest nx.

### Steps to Reproduce

1. npx nx migrate latest
2. npm install
3. npx nx migrate --run-migrations

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.18.0
OS     : win32-x64
npm    : 9.8.1

nx                 : 18.3.1
@nx/js             : 18.3.1
@nx/jest           : 18.3.1
@nx/linter         : 18.3.1
@nx/eslint         : 18.3.1
@nx/workspace      : 18.3.1
@nx/angular        : 18.3.1
@nx/devkit         : 18.3.1
@nx/eslint-plugin  : 18.3.1
@nrwl/tao          : 18.3.1
@nx/web            : 18.3.1
@nx/webpack        : 18.3.1
typescript         : 5.4.5
---------------------------------------
Community plugins:
@nebular/theme              : 11.0.1
@ng-bootstrap/ng-bootstrap  : 15.1.1
@ngrx/store                 : 17.0.1
@nguniversal/builders       : 16.2.0
@nguniversal/express-engine : 16.2.0
@storybook/angular          : 7.5.1
apollo-angular              : 5.0.2
ngx-toastr                  : 17.0.2
```

### Failure Logs

```shell
NX   Running migrations from 'migrations.json'

    
✓  Updated Angular CDK to version 17


NX   Failed to run rename-browser-target-to-build-target from @nx/angular. This workspace is NOT up to date!


NX   Cannot update Project tgx-web at apps/web. It either doesn't exist yet, or may not use project.json for configuration. Use `addProjectConfiguration()` instead if you want to create a new project.


options-utils.js:43:51)
at forEachExecutorOptions (C:\Users\mbarragan\Documents\Platform\node_modules\@nx\devkit\src\generators\executor-options-utils.js:18:5)
at C:\Users\mbarragan\Documents\Platform\node_modules\@nx\angular\src\migrations\update-17-1-0\browser-target-to-build-target.js:15:61
at Array.forEach (<anonymous>)
at default_1 (C:\Users\mbarragan\Documents\Platform\node_modules\@nx\angular\src\migrations\update-17-1-0\browser-target-to-build-target.js:14:23)
at runNxMigration (C:\Users\mbarragan\Documents\Platform\node_modules\nx\src\command-line\migrate\migrate.js:1020:11)
Command failed: npx nx _migrate --run-migrations --verbose

NX   Command failed: npx nx migrate --run-migrations --verbose


Error: Command failed: npx nx migrate --run-migrations --verbose
at checkExecSyncError (node:child_process:890:11)
at execSync (node:child_process:962:15)
at runNxSync (C:\Users\MBARRA~1\AppData\Local\Temp\tmp-19468-dgEE6k7hfJ9s\node_modules\nx\src\utils\child-process.js:25:34)
at runMigrations (C:\Users\MBARRA~1\AppData\Local\Temp\tmp-19468-dgEE6k7hfJ9s\node_modules\nx\src\command-line\migrate\migrate.js:943:39)
at C:\Users\MBARRA~1\AppData\Local\Temp\tmp-19468-dgEE6k7hfJ9s\node_modules\nx\src\command-line\migrate\migrate.js:1037:19
at async handleErrors (C:\Users\MBARRA~1\AppData\Local\Temp\tmp-19468-dgEE6k7hfJ9s\node_modules\nx\src\utils\params.js:9:16)
Command failed: C:\Users\MBARRA~1\AppData\Local\Temp\tmp-19468-dgEE6k7hfJ9s\node_modules\.bin\nx _migrate --run-migrations --verbose
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
This has been fixed in latest Nx as part of: https://github.com/nrwl/nx/pull/23143
