### ISSUE TITLE
`'ERR_UNKNOWN_SIGNAL`  when terminating `nx run project:serve` 

### ISSUE THREAD

**Issue by SanderElias** [nrwl/nx#22877]
### Current Behavior

when I abort (^c) the serve I get this error:
![image](https://github.com/nrwl/nx/assets/1249083/43a26756-55a9-4b20-871f-0ffbeb88a0db)

### Expected Behavior

not getting the error

### Steps to Reproduce

1. start project with `nx run angular-app-project:serve`
2. stop the thing

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.12.2
OS     : linux-x64
npm    : 10.5.0

nx (global)        : 18.3.0
nx                 : 18.2.4
@nx/js             : 18.2.4
@nx/jest           : 18.2.4
@nx/linter         : 18.2.4
@nx/eslint         : 18.2.4
@nx/workspace      : 18.2.4
@nx/angular        : 18.2.4
@nx/devkit         : 18.2.4
@nx/esbuild        : 18.2.4
@nx/eslint-plugin  : 18.2.4
@nx/express        : 18.2.4
@nx/node           : 18.2.4
@nx/plugin         : 18.2.4
@nrwl/tao          : 18.2.4
@nx/web            : 18.2.4
@nx/webpack        : 18.2.4
typescript         : 5.4.5
---------------------------------------
Community plugins:
@dot-build/serve-and-run-angular : 2.0.0
@ngneat/spectator                : 16.0.0
@ngneat/transloco                : 6.0.4
ng-mocks                         : 14.12.2
ngx-toastr                       : 18.0.0
---------------------------------------
Local workspace plugins:
	@libs/workspace-plugin
```

### Failure Logs

```shell
TypeError [ERR_UNKNOWN_SIGNAL]: Unknown signal: 130
    at convertToValidSignal (node:internal/util:331:9)
    at ChildProcess.kill (node:internal/child_process:496:5)
    at process.processExitListener (/.../node_modules/nx/src/executors/run-commands/run-commands.impl.js:208:62)
    at process.emit (node:events:530:35)
    at process.processEmit [as emit] (/.../node_modules/restore-cursor/node_modules/signal-exit/index.js:191:37)
    at process.exit (node:internal/process/per_thread:187:15)
    at process.<anonymous> (/.../node_modules/nx/src/tasks-runner/forked-process-task-runner.js:346:21)
    at process.emit (node:events:530:35) {
  code: 'ERR_UNKNOWN_SIGNAL'
}
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Fixed in https://github.com/nrwl/nx/pull/22895

Thanks :)
