### ISSUE TITLE
[Nx Release] changelogRenderer is not a function

### ISSUE THREAD

**Issue by recallwei** [nrwl/nx#22928]
### Current Behavior

Nx release cannot generate changelog successfully.

![image](https://github.com/nrwl/nx/assets/62941121/fce366a7-fd3b-4485-9c71-4f15f313926f)

### Expected Behavior

Should not throw this error.

### GitHub Repo

https://github.com/bit-ocean-studio/infra

### Steps to Reproduce

1. Clone this repo
2. Exec `pnpm i`
3. Exec `pnpm nx release --skip-publish "--first-release" "--dry-run"`
4. Select `patch` version

### Nx Report

```shell
Node   : 20.12.1
OS     : win32-x64
pnpm   : 9.0.4

nx             : 18.3.3
@nx/js         : 18.3.3
@nx/jest       : 18.3.3
@nx/linter     : 18.3.3
@nx/eslint     : 18.3.3
@nx/workspace  : 18.3.3
@nx/devkit     : 18.3.3
@nx/plugin     : 18.3.3
@nrwl/tao      : 18.3.3
typescript     : 5.3.3
```

### Failure Logs

```shell
NX   changelogRenderer is not a function


TypeError: changelogRenderer is not a function
    at generateChangelogForWorkspace (C:\Users\brucesong\Desktop\Code\bit-ocean-infra\node_modules\.pnpm\nx@18.3.3_@swc-node+register@1.9.0_@swc+core@1.4.16_@swc+helpers@0.5.5__@swc+types@0.1.6_type_hiidvvqk3ap3tqbl6d2lgel27u\node_modules\nx\src\command-line\release\changelog.js:444:26)
    at releaseChangelog (C:\Users\brucesong\Desktop\Code\bit-ocean-infra\node_modules\.pnpm\nx@18.3.3_@swc-node+register@1.9.0_@swc+core@1.4.16_@swc+helpers@0.5.5__@swc+types@0.1.6_type_hiidvvqk3ap3tqbl6d2lgel27u\node_modules\nx\src\command-line\release\changelog.js:134:38)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at release (C:\Users\brucesong\Desktop\Code\bit-ocean-infra\node_modules\.pnpm\nx@18.3.3_@swc-node+register@1.9.0_@swc+core@1.4.16_@swc+helpers@0.5.5__@swc+types@0.1.6_type_hiidvvqk3ap3tqbl6d2lgel27u\node_modules\nx\src\command-line\release\release.js:56:29)
    at handleErrors (C:\Users\brucesong\Desktop\Code\bit-ocean-infra\node_modules\.pnpm\nx@18.3.3_@swc-node+register@1.9.0_@swc+core@1.4.16_@swc+helpers@0.5.5__@swc+types@0.1.6_type_hiidvvqk3ap3tqbl6d2lgel27u\node_modules\nx\src\utils\params.js:9:16)
    at Object.handler (C:\Users\brucesong\Desktop\Code\bit-ocean-infra\node_modules\.pnpm\nx@18.3.3_@swc-node+register@1.9.0_@swc+core@1.4.16_@swc+helpers@0.5.5__@swc+types@0.1.6_type_hiidvvqk3ap3tqbl6d2lgel27u\node_modules\nx\src\command-line\release\command-object.js:89:24)
```

### Package Manager Version

pnpm@9.0.4

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Note: One of these packages (@bit-ocean/cli) hasn't been published to npm.

**Comment by amaralc** [comment]
@recallwei, did you add @nx/js to your workspace as described [here](https://nx.dev/recipes/nx-release/get-started-with-nx-release#add-the-javascript-plugin)?

I have experienced the same issue when trying to run the command without installing that plugin.

**Comment by JamesHenry** [comment]
The error handling will be addressed by https://github.com/nrwl/nx/pull/23214

It was previously swallowing the real issue

**Comment by JamesHenry** [comment]
Are you still having the problem @recallwei? If so you/I could apply that PR build to your repo to reveal the actual underlying issue

**Comment by JamesHenry** [comment]
I'm going to go ahead and close this one as the error is now much clearer and more specific.

To anyone experience issues with resolving a changelog renderer, please open a fresh issue with full context/steps to reproduce.

Thanks all!
