### ISSUE TITLE
Import alias inside a libs folder

### ISSUE THREAD

**Issue by gezperez** [nrwl/nx#22923]
### Current Behavior

Error: Cannot resolve ~/src/constants
    at /Users/ezequielperez/Apps/xpenses-monorepo/node_modules/@nx/react-native/plugins/metro-resolver.js:33:15
    at Object.resolve (/Users/ezequielperez/Apps/xpenses-monorepo/node_modules/metro-resolver/src/resolve.js:32:12)
    at ModuleResolver.resolveDependency (/Users/ezequielperez/Apps/xpenses-monorepo/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:73:31)
    at DependencyGraph.resolveDependency (/Users/ezequielperez/Apps/xpenses-monorepo/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /Users/ezequielperez/Apps/xpenses-monorepo/node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (/Users/ezequielperez/Apps/xpenses-monorepo/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/Users/ezequielperez/Apps/xpenses-monorepo/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at async Promise.all (index 0)
    at async buildSubgraph (/Users/ezequielperez/Apps/xpenses-monorepo/node_modules/metro/src/DeltaBundler/buildSubgraph.js:103:3)
    at async Graph._buildDelta (/Users/ezequielperez/Apps/xpenses-monorepo/node_modules/metro/src/DeltaBundler/Graph.js:157:22)

### Expected Behavior

Import alias resolution works as expected

### GitHub Repo

https://github.com/gezperez/xpenses-monorepo

### Steps to Reproduce

1. yarn ios

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 21.7.1
OS     : darwin-arm64
yarn   : 1.22.22

nx                 : 18.3.3
@nx/js             : 18.3.3
@nx/jest           : 18.3.3
@nx/linter         : 18.3.3
@nx/eslint         : 18.3.3
@nx/workspace      : 18.3.3
@nx/detox          : 18.3.3
@nx/devkit         : 18.3.3
@nx/eslint-plugin  : 18.3.3
@nx/react          : 18.3.3
@nx/react-native   : 18.3.3
@nrwl/tao          : 18.3.3
@nx/web            : 18.3.3
@nx/webpack        : 18.3.3
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/react-native/plugin
@nx/eslint/plugin
@nx/webpack/plugin
@nx/detox/plugin
@nx/jest/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
The link to your reproduction is invalid, so I've not been able to dig in much further.

I imagine you are setting import aliases inside your libs tsconfig files?

**Comment by xiongemi** [comment]
if your import path `~/src/constants`? i don't think path with '~' would work?
could you provide a valid repo?

maybe try the path to be relative `./src/constants` or `<your library name>/src/constants`?

i am going to close this issue for now.
