### ISSUE TITLE
(0 , workspaces_1.buildWorkspaceConfigurationFromGlobs) is not a function

### ISSUE THREAD

**Issue by shanieMoonlight** [nrwl/nx#22931]
### Current Behavior

I've been getting an error every time i try to generate a library or a secondary entrypoint.

PS C:\Users\Shaneyboy\VsCode\inigo-m-o> npx nx generate @nrwl/angular:library --name=mylib --directory=libs/myLib --no-interactive --dry-run  --verbose

 NX  Generating @nrwl/angular:library

 NX   (0 , workspaces_1.buildWorkspaceConfigurationFromGlobs) is not a function

TypeError: (0 , workspaces_1.buildWorkspaceConfigurationFromGlobs) is not a function
    at readRawWorkspaceJson (C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\node_modules\@nrwl\devkit\src\generators\project-configuration.js:308:87)     
    at readWorkspaceConfiguration (C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\node_modules\@nrwl\devkit\src\generators\project-configuration.js:69:16)
    at setDefaults (C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\src\generators\init\init.js:45:63)
    at C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\src\generators\init\init.js:17:9
    at Generator.next (<anonymous>)
    at C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\tslib\tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\tslib\tslib.js:165:16)
    at angularInitGenerator (C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\src\generators\init\init.js:15:20)
    at C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\src\generators\library\library.js:34:34
PS C:\Users\Shaneyboy\VsCode\inigo-m-o> 

If I manually create the library folder an files and then reference it in tsconfig.base.json it will work but the generator always throws that error.

I can see that it's calling  @nrwl/angular and  @nrwl/devkit functions but if I go to npm it says that those packages are deprecated

### Expected Behavior

I was expecting it to just buikd the library. Which is what used to happen

### Steps to Reproduce

1.
try to generate a library using "npx nx generate @nrwl/angular:library"

### Nx Report

```shell
NX   Report complete - copy this into the issue template      

Node   : 21.1.0
OS     : win32-x64
npm    : 10.2.5

nx                 : 18.3.3
@nx/js             : 18.3.3
@nx/jest           : 18.3.3
@nx/linter         : 18.3.3
@nx/eslint         : 18.3.3
@nrwl/linter       : 13.10.6
@nx/workspace      : 18.3.3
@nrwl/workspace    : 13.10.6
@nx/angular        : 18.3.3
@nrwl/angular      : 13.10.6
@nx/cypress        : 18.3.3
@nx/devkit         : 18.3.3
@nx/eslint-plugin  : 18.3.3
@nrwl/storybook    : 13.10.6
@nrwl/tao          : 18.3.3
@nx/web            : 18.3.3
@nx/webpack        : 18.3.3
typescript         : 5.4.5
---------------------------------------
Community plugins:
@ngrx/signals         : 17.2.0
@nxtend/ionic-angular : 13.1.0
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/linter@13.10.6
  - @nrwl/workspace@13.10.6
  - @nrwl/angular@13.10.6
  - @nrwl/storybook@13.10.6

To fix this, run `nx migrate nx@18.3.3`
```

### Failure Logs

```shell
PS C:\Users\Shaneyboy\VsCode\inigo-m-o> npx nx generate @nrwl/angular:library --name=acc-feats --directory=libs/acc-feats --buildable=true --importPath=@inigo/acc-feats --prefix=acc-feats --publishable=true --skipModule=true --no-interactive --dry-run --verbose
                                                                    f7e3ba1861f7e3ba1861
 NX  Generating @nrwl/angular:library


 NX   (0 , workspaces_1.buildWorkspaceConfigurationFromGlobs) is not a function


TypeError: (0 , workspaces_1.buildWorkspaceConfigurationFromGlobs) is not a function
    at readRawWorkspaceJson (C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\node_modules\@nrwl\devkit\src\generators\project-configuration.js:308:87)
    at readWorkspaceConfiguration (C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\node_modules\@nrwl\devkit\src\generators\project-configuration.js:69:16)
    at setDefaults (C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\src\generators\init\init.js:45:63)
    at C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\src\generators\init\init.js:17:9
    at Generator.next (<anonymous>)
    at C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\tslib\tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\tslib\tslib.js:165:16)
    at angularInitGenerator (C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\src\generators\init\init.js:15:20)
    at C:\Users\Shaneyboy\VsCode\inigo-m-o\node_modules\@nrwl\angular\src\generators\library\library.js:34:34
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
```
The following packages should match the installed version of nx
  - @nrwl/linter@13.10.6
  - @nrwl/workspace@13.10.6
  - @nrwl/angular@13.10.6
  - @nrwl/storybook@13.10.6
```

Your packages have to be pretty much the same version for things to work, and v13 was a long ways back. You should remove these outdated packages and that should resolve the issue.

**Comment by shanieMoonlight** [comment]
I deleted the @nrwl node modules and that fixed the problem.  I think the console must have been using @nrwl instead of @nx.

Thanks

**Comment by shanieMoonlight** [comment]
Thanks I removed all the old @nrwl node modules and everything works now
