### ISSUE TITLE
Can't serve rollup bundle due to 'Could not find ${fileToRun}' error

### ISSUE THREAD

**Issue by adexot** [nrwl/nx#23029]
### Current Behavior

The error below occurs when I try to serve an express app bundled with `@nx/rollup:rollup`:

/Users/aoseni/Temp/analysis-web/node_modules/@nx/js/src/executors/node/node.impl.js:287
    throw new Error(`Could not find ${fileToRun}. Make sure your build succeeded.`);
          ^

Error: Could not find /Users/aoseni/Temp/analysis-web/dist/apps/ds-graphql-api/main.js. Make sure your build succeeded.
    at fileToRunCorrectPath (/Users/aoseni/Temp/analysis-web/node_modules/@nx/js/src/executors/node/node.impl.js:287:11)
    at /Users/aoseni/Temp/analysis-web/node_modules/@nx/js/src/executors/node/node.impl.js:97:49
    at new Promise (<anonymous>)
    at Object.start (/Users/aoseni/Temp/analysis-web/node_modules/@nx/js/src/executors/node/node.impl.js:91:36)
    at Timeout.processQueue [as _onTimeout] (/Users/aoseni/Temp/analysis-web/node_modules/@nx/js/src/executors/node/node.impl.js:62:13)

Node.js v18.19.0

### Expected Behavior

Express app should start correctly.

### GitHub Repo

https://github.com/adexot/nx-express-rollup

### Steps to Reproduce

1. Run yarn to install the dependencies in the repo provided
2. Run `yarn nx run express-rollup:build-rollup` to build the nx app
3. Run `yarn nx run express-rollup:serve` to serve the app

The above should result in the error:
    throw new Error(`Could not find ${fileToRun}. Make sure your build succeeded.`);

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.19.0
   OS     : darwin-arm64
   yarn   : 3.6.3
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/esbuild        : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/next           : 16.10.0
   @nx/node           : 16.10.0
   @nx/plugin         : 16.10.0
   @nx/react          : 16.10.0
   @nx/rollup         : 16.10.0
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.4.5
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by adexot** [comment]
The error above happens due to `.` being omitted from `cjs.js` at https://github.com/nrwl/nx/blob/49af691b24762ba91d72d24105593553f751e9b7/packages/js/src/executors/node/node.impl.ts#L415
