### ISSUE TITLE
Type error: Module '"./.nx-helpers/compiled.js"' has no exported member 'composePlugins'.

### ISSUE THREAD

**Issue by Bulletninja** [nrwl/nx#23048]
### Current Behavior

Always fails, in any of my projects, even though it's setup from the default next generators

### Expected Behavior

Should not complain about composePlugins not being exported.

### Steps to Reproduce

1. Generate the default next app
2. Fail to build
3. Change `"strict": false` in `tsconfig.json`
4. Build successfully
5. Change back `"strict": true` in `tsconfig.json`
6. Fail to build because of complain with `composePlugins`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.12.2
OS     : darwin-arm64
npm    : 10.5.0

nx                 : 18.3.3
@nx/js             : 18.3.3
@nx/jest           : 18.3.3
@nx/linter         : 18.3.3
@nx/eslint         : 18.3.3
@nx/workspace      : 18.3.3
@nx/cypress        : 18.3.3
@nx/devkit         : 18.3.3
@nx/eslint-plugin  : 18.3.3
@nx/next           : 18.3.3
@nx/node           : 18.3.3
@nx/playwright     : 18.3.3
@nx/react          : 18.3.3
@nrwl/tao          : 18.3.3
@nx/web            : 18.3.3
@nx/webpack        : 18.3.3
typescript         : 5.4.5
---------------------------------------
Community plugins:
@nx/rspack : 18.0.6
```

### Failure Logs

```shell
[NX CLOUD] Verifying current cloud bundle
[NX CLOUD] A local bundle currently exists:  {
  version: '2404.23.6.hotfix5',
  fullPath: '/MYPROJECTPATHHERE/.nx/cache/cloud/2404.23.6.hotfix5'
}
[NX CLOUD] Last verification was within the past 30 minutes, will not verify this time
[NX CLOUD] Done:  /MYPROJECTPATHHERE/.nx/cache/cloud/2404.23.6.hotfix5
[Nx Cloud] Unable to detect a VCS context from the environment.

 NX   RunStart


{
  "meta": {},
  "branch": null,
  "runGroup": "b4a25a8344246918ba1d860d9c515a5acc328d2c",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "13229980026899555889"
  ],
  "machineInfo": {
    "machineId": "<machineId>",
    "platform": "darwin",
    "version": "Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000",
    "cpuCores": 8
  },
  "vcsContext": null
}

RunStart duration: 200

 NX   Nx Cloud: Cache miss 13229980026899555889.


> nx run orders-clients-v2:build:production --skip-cache

  [1m[38;2;173;127;168m▲ Next.js 14.2.3[39m[22m
 [37m[1m [22m[39m Creating an optimized production build ...
 [32m[1m✓[22m[39m Compiled successfully
 [37m[1m [22m[39m Skipping linting
 [37m[1m [22m[39m Checking validity of types ...

Failed to compile.

./dist/next.config.js:4:9
Type error: Module '"./.nx-helpers/compiled.js"' has no exported member 'composePlugins'.
  2 |
  3 | // eslint-disable-next-line @typescript-eslint/no-var-requires
> 4 | const { composePlugins, withNx } = require('./.nx-helpers/compiled.js');
    |         ^
  5 |
  6 | /**
  7 |  * @type {import('./.nx-helpers/compiled.js').WithNxOptions}
Build process exited due to code 1  

 NX   Running target build for project orders-clients-v2 failed

Failed tasks:

- orders-clients-v2:build:production

Hint: run the command with --verbose for more details.

View structured, searchable error logs at https://nx.app/runs/<runId>
```

### Package Manager Version

npm version 10.5.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The only thing I could do in some places was implementing my own composer function and completely eliminate that default import.

**Comment by Bulletninja** [comment]
Ran a bunch of stuff and seems it works, but I don't know what fixed it:
- npx nx reset
- npx nx clear-cache
- rf ./node_modules/.cache/nx 
- rf ./<path-to-your-app>/.nx 
- rf ./<path-to-your-app>/dist (this is where I usually move my builds (dists) to, just use your path which might be the default one)

**Comment by AtelyPham** [comment]
Can we reopen this issue, @AgentEnder? I'm still getting this error when building a Next.js app in the ESM module.

### Nx Report

```bash
Node   : 18.19.0
OS     : darwin-arm64
yarn   : 1.22.19

nx                 : 19.0.2
@nx/js             : 19.0.2
@nx/jest           : 19.0.2
@nx/linter         : 19.0.2
@nx/eslint         : 19.0.2
@nx/workspace      : 19.0.2
@nx/cypress        : 19.0.2
@nx/devkit         : 19.0.2
@nx/eslint-plugin  : 19.0.2
@nx/next           : 19.0.2
@nx/react          : 19.0.2
@nx/rollup         : 19.0.2
@nx/storybook      : 19.0.2
@nrwl/tao          : 19.0.2
@nx/web            : 19.0.2
@nx/webpack        : 19.0.2
typescript         : 5.4.5
```

### Application `next.config.js` file

```js
//@ts-check

import { withNx, composePlugins } from '@nx/next';

/**
 * @type {import('@nx/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  reactStrictMode: true,

  nx: {
    // Set this to true if you would like to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },

  // Follow wasm example from next.js repo: https://github.com/vercel/next.js/blob/canary/examples/with-webassembly/next.config.js
  webpack(config, { isServer, dev }) {
    // Use the client static directory in the server bundle and prod mode
    // Fixes `Error occurred prerendering page "/"`
    config.output.webassemblyModuleFilename =
      isServer && !dev
        ? '../static/wasm/[modulehash].wasm'
        : 'static/wasm/[modulehash].wasm';

    // Since Webpack 5 doesn't enable WebAssembly by default, we should do it manually
    config.experiments = { ...config.experiments, asyncWebAssembly: true };

    if (!isServer) {
      config.resolve.fallback = {
        ...config.resolve.fallback,
        fs: false,
      };
    }

    // WalletConnect external modules: https://github.com/WalletConnect/walletconnect-monorepo/issues/1908#issuecomment-1487801131
    config.externals.push('pino-pretty', 'lokijs', 'encoding');

    // Hide warnings "Critical dependency: the request of a dependency is an expression"
    config.module = {
      ...config.module,
      exprContextCritical: false,
    };

    return config;
  },
};

const plugins = [
  // Add more Next.js plugins to this list if needed.
  withNx,
];

export default composePlugins(...plugins)(nextConfig);

```

### Application `package.json` file

```json
{
  "name": "tangle-dapp",
  "version": "0.0.8",
  "license": "Apache-2.0",
  "type": "module"
}
```

When I run `nx build tangle-dapp -c production` and `nx serve my-app -c production`, I get the following error:

```
  ▲ Next.js 14.2.3
  - Local:        http://localhost:4200

 ✓ Starting...
 ⨯ Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
file:///Users/tinpt2000/webb/webb-dapp/dist/apps/tangle-dapp/next.config.js:3
import { withNx, composePlugins } from './.nx-helpers/compiled.js';
                 ^^^^^^^^^^^^^^
SyntaxError: The requested module './.nx-helpers/compiled.js' does not provide an export named 'composePlugins'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)
    at async loadConfig (/Users/tinpt2000/webb/webb-dapp/node_modules/next/dist/server/config.js:698:36)
    at async initialize (/Users/tinpt2000/webb/webb-dapp/node_modules/next/dist/server/lib/router-server.js:54:20)
    at async Server.<anonymous> (/Users/tinpt2000/webb/webb-dapp/node_modules/next/dist/server/lib/start-server.js:249:36)

 NX   Next.js app exited with code 1
```

When inspecting the build, it seems the function `composePlugins` could not be imported in the `next.config.js` build file.

<table>
<tr>
 <td><img src="https://github.com/nrwl/nx/assets/60747384/acb38ae3-20cb-4d18-acf5-41f77b543f3a" atl="img1" />
 <td><img src="https://github.com/nrwl/nx/assets/60747384/4d1b8b54-11ae-4c89-9c2a-7d122be16898" atl="img2" />
</table>

_`.nx-helpers/compiled.js`_

![CleanShot 2024-05-20 at 16 46 18@2x](https://github.com/nrwl/nx/assets/60747384/dde346b5-193a-4bd2-816a-786dee7c045e)
