### ISSUE TITLE
Using @node-rs/argon2 in @nx/next prompts that loading native bindings fails

### ISSUE THREAD

**Issue by kainonly** [nrwl/nx#23057]
### Current Behavior

I use Next in my Nx project, and use `@node-rs/argon2` for verification during login. I get an error here: Failed to load native binding, and Cannot find module `@node-rs/argon2-win32-x64-msvc` , in fact it exists `node_modules`

### Expected Behavior

Hope to use libraries like `@node-rs/argon2` normally.

### GitHub Repo

https://github.com/creator-mall/workspace

### Steps to Reproduce

1. Run `npm install`
2. Run `npm run web:dev`
3. Visit `localhost:3000` and click `Make Argon2` and `Make Token`.

### Nx Report

```shell
nx report

 NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4

nx                 : 18.3.4
@nx/js             : 18.3.4
@nx/jest           : 18.3.4
@nx/linter         : 18.3.4
@nx/eslint         : 18.3.4
@nx/workspace      : 18.3.4
@nx/devkit         : 18.3.4
@nx/eslint-plugin  : 18.3.4
@nx/next           : 18.3.4
@nx/react          : 18.3.4
@nrwl/tao          : 18.3.4
@nx/web            : 18.3.4
@nx/webpack        : 18.3.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/jest/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
Error: Failed to load native binding
    at Object.<anonymous> (D:\github.com\creator-mall\workspace\web\.next\server\chunks\08b5e_23f28a._.js:260:15)
    at instantiateModule (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:490:23)
    at getOrInstantiateModuleFromParent (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:541:12)
    at esmImport (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:113:20)
    at D:\github.com\creator-mall\workspace\web\.next\server\chunks\[project]_web_2b49df._.js:12:151
    at [project]/web/app/actions.ts [app-rsc] (ecmascript, action, ecmascript) (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[project]_web_2b49df._.js:36:3)
    at instantiateModule (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:490:23)
    at getOrInstantiateModuleFromParent (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:541:12)
    at commonJsRequire (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:127:20)
    at 5009739475759018e8880de0889d78a0a15bf02c (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[project]_web_2b49df._.js:40:76)
Cause: [
  Error: Cannot find module './argon2.win32-x64-msvc.node'
      at D:\github.com\creator-mall\workspace\web\.next\server\chunks\08b5e_23f28a._.js:204:31
      at requireNative (D:\github.com\creator-mall\workspace\web\.next\server\chunks\08b5e_23f28a._.js:207:19)
      at Object.<anonymous> (D:\github.com\creator-mall\workspace\web\.next\server\chunks\08b5e_23f28a._.js:227:17)
      at [project]/node_modules/@node-rs/argon2/index.js [app-rsc] (ecmascript) (D:\github.com\creator-mall\workspace\web\.next\server\chunks\08b5e_23f28a._.js:275:3)
      at instantiateModule (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:490:23)
      at getOrInstantiateModuleFromParent (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:541:12)
      at esmImport (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:113:20)
      at D:\github.com\creator-mall\workspace\web\.next\server\chunks\[project]_web_2b49df._.js:12:151
      at [project]/web/app/actions.ts [app-rsc] (ecmascript, action, ecmascript) (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[project]_web_2b49df._.js:36:3)
      at instantiateModule (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:490:23)
      at getOrInstantiateModuleFromParent (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:541:12)
      at commonJsRequire (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:127:20)
      at 5009739475759018e8880de0889d78a0a15bf02c (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[project]_web_2b49df._.js:40:76)
      at D:\github.com\creator-mall\workspace\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:414
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async t0 (D:\github.com\creator-mall\workspace\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:5773)
      at async rh (D:\github.com\creator-mall\workspace\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:23636)
      at async doRender (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:1391:30)
      at async cacheEntry.responseCache.get.routeKind (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:1552:28)
      at async DevServer.renderToResponseWithComponentsImpl (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:1460:28)
      at async DevServer.renderPageComponent (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:1843:24)
      at async DevServer.renderToResponseImpl (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:1881:32)
      at async DevServer.pipeImpl (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:909:25)
      at async NextNodeServer.handleCatchallRenderRequest (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\next-server.js:266:17)
      at async DevServer.handleRequestImpl (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:805:17) {
    code: 'MODULE_NOT_FOUND'
  },
  Error: Cannot find module 'module "@node-rs/argon2-win32-x64-msvc"'
      at D:\github.com\creator-mall\workspace\web\.next\server\chunks\08b5e_23f28a._.js:213:31
      at requireNative (D:\github.com\creator-mall\workspace\web\.next\server\chunks\08b5e_23f28a._.js:216:19)
      at Object.<anonymous> (D:\github.com\creator-mall\workspace\web\.next\server\chunks\08b5e_23f28a._.js:227:17)
      at [project]/node_modules/@node-rs/argon2/index.js [app-rsc] (ecmascript) (D:\github.com\creator-mall\workspace\web\.next\server\chunks\08b5e_23f28a._.js:275:3)
      at instantiateModule (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:490:23)
      at getOrInstantiateModuleFromParent (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:541:12)
      at esmImport (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:113:20)
      at D:\github.com\creator-mall\workspace\web\.next\server\chunks\[project]_web_2b49df._.js:12:151
      at [project]/web/app/actions.ts [app-rsc] (ecmascript, action, ecmascript) (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[project]_web_2b49df._.js:36:3)
      at instantiateModule (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:490:23)
      at getOrInstantiateModuleFromParent (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:541:12)
      at commonJsRequire (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[turbopack]_runtime.js:127:20)
      at 5009739475759018e8880de0889d78a0a15bf02c (D:\github.com\creator-mall\workspace\web\.next\server\chunks\[project]_web_2b49df._.js:40:76)
      at D:\github.com\creator-mall\workspace\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:414
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async t0 (D:\github.com\creator-mall\workspace\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:5773)
      at async rh (D:\github.com\creator-mall\workspace\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:23636)
      at async doRender (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:1391:30)
      at async cacheEntry.responseCache.get.routeKind (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:1552:28)
      at async DevServer.renderToResponseWithComponentsImpl (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:1460:28)
      at async DevServer.renderPageComponent (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:1843:24)
      at async DevServer.renderToResponseImpl (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:1881:32)
      at async DevServer.pipeImpl (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:909:25)
      at async NextNodeServer.handleCatchallRenderRequest (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\next-server.js:266:17)
      at async DevServer.handleRequestImpl (D:\github.com\creator-mall\workspace\node_modules\next\dist\server\base-server.js:805:17) {
    code: 'MODULE_NOT_FOUND'
  }
]
```
```


### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

These are normal when using only NextJS

**Comment by ndcunningham** [comment]
I tried your repo and both buttons are working as expected on MacOS
<img width="868" alt="Screenshot 2024-04-29 at 12 49 26 PM" src="https://github.com/nrwl/nx/assets/338948/5433d53b-8ca6-456e-b455-937147cb7e37">

I will say that I had to remove your `package-lock.json` and reinstall with `npm i` as there were a lot of module errors. 
It is possible that it could be malformed in someway.

Maybe you can try that.

**Comment by kainonly** [comment]
Hi @ndcunningham,

Nx is normal without using `--turbo`. My feedback is that Turbopack is used in Nx. This problem is also normal when using `create-next-app` (turbo) alone.
