### ISSUE TITLE
Unit tests failing, but command does not return an error code

### ISSUE THREAD

**Issue by noahbroyles** [nrwl/nx#23200]
### Current Behavior

I am running the following nx command to unit test my projects:
```console
npx nx affected --target=test --base=origin/main --head=HEAD --parallel=5 --verbose=true
```
The issue that I am experiencing is that some of the unit tests are failing, however the command does not return an error code. This is causing my pipelines to succeed even though the tests failed.

I am using this bash script in my pipeline:
```bash
if npx nx affected --target=test --base=origin/main --head=HEAD --parallel=5 --verbose=true; then
    echo "Tests passed"
    export SCRIPT_TEST_AFFECTED_CALLED=true
    return 0
else
    echo "Tests failed"
    return 1
fi
```
This script is outputting "Tests passed" when they clearly didn't. Here is the tail end of the command output:

```text
     67 |
      at Object.toMatchSnapshot (tests/mapperUtils/tabPanelMapper.test.js:64:22)
 FAIL  tests/contentful-page.test.js
  ● getLocaleSlug › should end with a single slash when the uid already contains one
    expect(received).toEqual(expected) // deep equality
    Expected: "/en-US/about-you/"
    Received: "/en-US/about-us/"
       98 |     }
       99 |     const pagePath = getLocaleSlug(page);
    > 100 |     expect(pagePath).toEqual('/en-US/about-you/');
          |                      ^
      101 |   });
      102 | });
      at Object.toEqual (tests/contentful-page.test.js:100:22)
Snapshot Summary
 › 3 snapshots failed from 2 test suites. Inspect your code changes or run `npm test -- -u` to update them.
 › 1 snapshot obsolete from 1 test suite. To remove it, run `npm test -- -u`.
   ↳ tests/mapperUtils/tabPanelMapper.test.js
       • tabPanelMapper in vertical orientation should produce output which exactly matches the snapshot 1
Test Suites: 6 failed, 98 passed, 104 total
Tests:       25 failed, 891 passed, 916 total
Snapshots:   3 failed, 1 obsolete, 2 passed, 5 total
Time:        30.193 s
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @disw/component-manager@4.25.0-beta.5 
npm ERR!   at location: /opt/atlassian/pipelines/agent/build/packages/component-manager 
 
 >  NX   Successfully ran target test for project @disw/component-manager and 1 task it depends on
Tests passed
```

### Expected Behavior

I expect that the `nx affected --target=test` command would return an error code of 1 if any unit tests fail.

### Steps to Reproduce

1. In a repository with multiple projects, change one of the projects unit tests so that it will fail
2. Unit test the projects with the `nx affected --target=test` command
3. The command should fail with an exit code of something other than 0

### Nx Report

```shell
Node : 18.12.1
OS   : darwin arm64
npm  : 8.19.4
   
nx            : 15.9.7
lerna         : 6.6.2
@nrwl/cli     : 15.9.7
@nrwl/devkit  : 15.9.7
@nrwl/tao     : 15.9.7
typescript    : 4.9.5
```

### Failure Logs

```shell
FAIL  tests/contentful-page.test.js
  ● getLocaleSlug › should end with a single slash when the uid already contains one
    expect(received).toEqual(expected) // deep equality
    Expected: "/en-US/about-you/"
    Received: "/en-US/about-us/"
       98 |     }
       99 |     const pagePath = getLocaleSlug(page);
    > 100 |     expect(pagePath).toEqual('/en-US/about-you/');
          |                      ^
      101 |   });
      102 | });
      at Object.toEqual (tests/contentful-page.test.js:100:22)
Snapshot Summary
 › 3 snapshots failed from 2 test suites. Inspect your code changes or run `npm test -- -u` to update them.
 › 1 snapshot obsolete from 1 test suite. To remove it, run `npm test -- -u`.
   ↳ tests/mapperUtils/tabPanelMapper.test.js
       • tabPanelMapper in vertical orientation should produce output which exactly matches the snapshot 1
Test Suites: 6 failed, 98 passed, 104 total
Tests:       25 failed, 891 passed, 916 total
Snapshots:   3 failed, 1 obsolete, 2 passed, 5 total
Time:        30.193 s
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @disw/component-manager@4.25.0-beta.5 
npm ERR!   at location: /opt/atlassian/pipelines/agent/build/packages/component-manager 
 
 >  NX   Successfully ran target test for project @disw/component-manager and 1 task it depends on
Tests passed
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I can't reproduce this with the information provided. I get the expected exit code 1.

Please provide a repo where the issue can be reproduced. Also, note you're using a fairly old major version of Nx, so you could also try with a newer version and see if the error persists.

**Comment by leosvelperez** [comment]
I'm closing this issue since it's for a version that's [out of our support window](https://nx.dev/reference/releases#supported-versions). If you're still facing the issue and you're using a newer supported version of Nx, please create a new issue with up-to-date information.
