### ISSUE TITLE
Nx 19 not working with Angular 18.0.0-rc. The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Fafnur** [nrwl/nx#23213]
### Current Behavior

Nx doesn't work with Angular 18.0.0-rc. An error appears when starting the project:  

```bash
> nx run simple-web:serve:development


 NX   Unable to resolve @angular-devkit/build-angular:application.

The "path" argument must be of type string. Received undefined

Error: Unable to resolve @angular-devkit/build-angular:application.
The "path" argument must be of type string. Received undefined
    at WrappedWorkspaceNodeModulesArchitectHost.readExecutor (/mnt/Storage/Development/angular/simple/node_modules/nx/src/adapter/ngcli-adapter.js:840:23)
    at WrappedWorkspaceNodeModulesArchitectHost.resolveBuilder (/mnt/Storage/Development/angular/simple/node_modules/nx/src/adapter/ngcli-adapter.js:793:38)
    at name (/mnt/Storage/Development/angular/simple/node_modules/@angular-devkit/architect/src/architect.js:220:40)
    at Observable._subscribe (/mnt/Storage/Development/angular/simple/node_modules/@angular-devkit/architect/src/jobs/create-job-handler.js:104:26)
    at Observable._trySubscribe (/mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at /mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/Observable.js:35:31
    at Object.errorContext (/mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Observable.subscribe (/mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
    at /mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:63
    at OperatorSubscriber._this._next (/mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
```

### Expected Behavior

The app should run without errors

### GitHub Repo

https://github.com/Fafnur/nx-anugular-18-rc-issue

### Steps to Reproduce

1. Create a new workspace (yarn create nx-workspace (select angular, set name angular project, select ssr, skip nx cloud)

![Screenshot from 2024-05-07 18-35-52](https://github.com/nrwl/nx/assets/3624224/b4695727-a167-454c-a579-51a2ab989cf6)

p.s. Angular 17.* is work fine.

![Screenshot from 2024-05-07 18-37-44](https://github.com/nrwl/nx/assets/3624224/3c2def81-6cdf-42fb-996b-971cfbdc52c9)

2. Update angular vendors to 18.0.0-rc.0

![Screenshot from 2024-05-07 18-50-57](https://github.com/nrwl/nx/assets/3624224/ba591c59-5f2c-46b1-99e4-0a168f80e0b6)

4. Serve angular project

![Screenshot from 2024-05-07 18-40-04](https://github.com/nrwl/nx/assets/3624224/a58a1bd7-690c-44bb-be4a-a85c5ea88641)

### Nx Report

```shell
Node   : 20.12.2
OS     : linux-x64
yarn   : 1.22.22

nx                 : 19.0.0
@nx/js             : 19.0.0
@nx/jest           : 19.0.0
@nx/linter         : 19.0.0
@nx/eslint         : 19.0.0
@nx/workspace      : 19.0.0
@nx/angular        : 19.0.0
@nx/devkit         : 19.0.0
@nx/eslint-plugin  : 19.0.0
@nrwl/tao          : 19.0.0
@nx/web            : 19.0.0
@nx/webpack        : 19.0.0
typescript         : 5.4.5

Done in 0.31s.
```

### Failure Logs

```shell
The "path" argument must be of type string. Received undefined

Error: Unable to resolve @angular-devkit/build-angular:application.
The "path" argument must be of type string. Received undefined
    at WrappedWorkspaceNodeModulesArchitectHost.readExecutor (/mnt/Storage/Development/angular/simple/node_modules/nx/src/adapter/ngcli-adapter.js:840:23)
    at WrappedWorkspaceNodeModulesArchitectHost.resolveBuilder (/mnt/Storage/Development/angular/simple/node_modules/nx/src/adapter/ngcli-adapter.js:793:38)
    at name (/mnt/Storage/Development/angular/simple/node_modules/@angular-devkit/architect/src/architect.js:220:40)
    at Observable._subscribe (/mnt/Storage/Development/angular/simple/node_modules/@angular-devkit/architect/src/jobs/create-job-handler.js:104:26)
    at Observable._trySubscribe (/mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at /mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/Observable.js:35:31
    at Object.errorContext (/mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Observable.subscribe (/mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
    at /mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:63
    at OperatorSubscriber._this._next (/mnt/Storage/Development/angular/simple/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

On yarn@4.2.1 at same

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Angular 18 is still not supported by Nx. Note that Angular 18 is still not released (you're trying a pre-release version). We are already working on adding support for it (https://github.com/nrwl/nx/pull/22509), so shortly after the Angular 18 stable version is out, Nx will have support for it.
