### ISSUE TITLE
Migration command fails at npm install(nx migrate --run-migrations=migrations.json --skip-npm-install -v)

### ISSUE THREAD

**Issue by Jay1989** [nrwl/nx#23262]
### Current Behavior
Trying to migrate Angular 9 to 10
The command fails it self :
node : 14.15.0
Nx : we tried 13.1.4/ 15/latest

### Expected Behavior

It should run without erro

### Steps to Reproduce

1. nx migrate @nrwl/workspace@10.4.15
2. npm install
3. nx migrate --run-migrations=migrations.json

### Nx Report

```shell
NA
```

### Failure Logs

```shell
C:\WOA_Workspace4\CI-UI-Workspace>nx migrate --run-migrations=migrations.json --skip-npm-install -v

 >  NX   Its time to update Nx 🎉

   For more information, see https://nx.dev/more-concepts/global-nx

C:\WOA_Workspace4\CI-UI-Workspace\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: npm install
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at taoPath (C:\WOA_Workspace4\CI-UI-Workspace\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:303:21)
    at Object.handler (C:\WOA_Workspace4\CI-UI-Workspace\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:77:19)
    at Object.runCommand (C:\WOA_Workspace4\CI-UI-Workspace\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\WOA_Workspace4\CI-UI-Workspace\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\WOA_Workspace4\CI-UI-Workspace\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\WOA_Workspace4\CI-UI-Workspace\node_modules\@nrwl\cli\lib\init-local.js:24:13)
    at Object.<anonymous> (C:\WOA_Workspace4\CI-UI-Workspace\node_modules\@nrwl\cli\bin\nx.js:40:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18332,
  stdout: null,
  stderr: null
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Jay1989** [comment]
Even we tried to skip npm install but still npm install is failing

**Comment by FrozenPandaz** [comment]
Version 10.4.15 is very old at this point and is not supported by the latest versions of Nx anymore.

To migrate, I'd recommend using this command to use the same version of Nx as the version you are migrating to:

```
npx nx@10.4.15 migrate @nrwl/workspace@10.4.15
```

I would continue to use similar commands as you update to the latest version of Nx.
