### ISSUE TITLE
eslint-plugin-vitest causing circular dependency issues

### ISSUE THREAD

**Issue by waldronmatt** [nrwl/nx#23353]
### Current Behavior

NX runs into circular dependency issues using eslint-plugin-vitest. Different packages will intermittenly fail. I have tried running `nx reset`, restarting vscode, clearing nx cache.

### Expected Behavior

I expect running `pnpm lint` will pass for every package.

### GitHub Repo

https://github.com/waldronmatt/groundwork/blob/main/configs/eslint-config-custom/vitest.cjs

### Steps to Reproduce

1. Uncomment lines 5 and 6 of the `vitest.cjs` file and rerun `pnpm lint`. 
2. You will encounter either one of two errors, something like: https://cloud.nx.app/runs/36poevCR2R/task/demo-ui-storybook%3Alint  (see below):

### Nx Report

```shell
Node   : 20.10.0
   OS     : win32-x64
   pnpm   : 8.11.0

   nx          : 17.3.2
   @nrwl/tao   : 17.3.2
   nx-cloud    : 18.0.1
   typescript  : 5.4.3
```

### Failure Logs

```shell
Cannot find module './lib/daemon/process-run-end'
Require stack:
- C:\Users\mattm\repos\groundwork\node_modules\.cache\nx\cloud\2405.02.15.hotfix4\index.js
- C:\Users\mattm\repos\groundwork\node_modules\.pnpm\nx-cloud@18.0.1\node_modules\nx-cloud\lib\light-client\nx-cloud-tasks-runner-shell.js
- C:\Users\mattm\repos\groundwork\node_modules\.pnpm\nx-cloud@18.0.1\node_modules\nx-cloud\index.js
- C:\Users\mattm\repos\groundwork\node_modules\.pnpm\nx@17.3.2\node_modules\nx\src\tasks-runner\run-command.js
- C:\Users\mattm\repos\groundwork\node_modules\.pnpm\nx@17.3.2\node_modules\nx\src\command-line\run-many\run-many.js   
- C:\Users\mattm\repos\groundwork\node_modules\.pnpm\nx@17.3.2\node_modules\nx\src\command-line\run-many\command-object.js
- C:\Users\mattm\repos\groundwork\node_modules\.pnpm\nx@17.3.2\node_modules\nx\src\command-line\nx-commands.js
- C:\Users\mattm\repos\groundwork\node_modules\.pnpm\nx@17.3.2\node_modules\nx\bin\init-local.js
- C:\Users\mattm\repos\groundwork\node_modules\.pnpm\nx@17.3.2\node_modules\nx\bin\nx.js
_______

ESLint: 8.57.0

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'vitest' -> object with constructor 'Object'
    |     property 'configs' -> object with constructor 'Object'
    |     property 'recommended' -> object with constructor 'Object'
    --- property 'plugins' closes the circle
Referenced from: /home/runner/work/groundwork/groundwork/configs/eslint-config-custom/vitest.cjs
    at JSON.stringify (<anonymous>)
    at /home/runner/work/groundwork/groundwork/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2156:45
    at Array.map (<anonymous>)
    at ConfigValidator.formatErrors (/home/runner/work/groundwork/groundwork/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2147:23)
    at ConfigValidator.validateConfigSchema (/home/runner/work/groundwork/groundwork/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2177:84)
    at ConfigArrayFactory._normalizeConfigData (/home/runner/work/groundwork/groundwork/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:19)
    at ConfigArrayFactory._loadExtendedPluginConfig (/home/runner/work/groundwork/groundwork/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3239:25)
    at ConfigArrayFactory._loadExtends (/home/runner/work/groundwork/groundwork/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3154:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/runner/work/groundwork/groundwork/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Maxim-Mazurok** [comment]
I don't think it's a circular dep issue, I'm having the same one, see https://github.com/veritem/eslint-plugin-vitest/issues/432

**Comment by Maxim-Mazurok** [comment]
There are some migration steps in here: https://github.com/nrwl/nx/blob/cc9b7f3b391fafe22c1b2fd8b21a953cac0d82cd/packages/eslint/src/generators/init/init-migration.ts#L126

**Comment by waldronmatt** [comment]
thanks @Maxim-Mazurok downgrading eslint-vitest fixed the issue. That should have been my first thought with conflicts using eslint < 9.
