### ISSUE TITLE
LoadPluginError: Could not load plugin

### ISSUE THREAD

**Issue by decline** [nrwl/nx#23435]
### Current Behavior

When using the `libraryGenerator()` method from `@nx/angular/generators` inside a (Jest) test, it will fail.

Example:
```ts
import { libraryGenerator } from "@nx/angular/generators";
import { createTreeWithEmptyWorkspace } from '@nx/devkit/testing';
import { Tree } from '@nx/devkit';

describe('my-generator generator', () => {
  let tree: Tree;

  beforeEach(() => {
    tree = createTreeWithEmptyWorkspace();
  });

  it('should run successfully', async () => {
    // this will fail:
    const result =   await libraryGenerator(tree, {
      name: 'test',
      directory: '',
    });

    expect(result).toBeDefined();
  });
});

```

The test will fail with the following error message:

```sh
LoadPluginError: Could not load plugin /app/node_modules/nx/src/plugins/project-json/build-nodes/package-json-next-to-project-json
```

## Important:
This error only happens on Linux operating system. The same test passes on a MacOS operating system.

### Expected Behavior

The test should run successfully on every operating system.

### GitHub Repo

https://github.com/decline/nx-plugin-issue

### Steps to Reproduce

1. Checkout the repository
2. Run `docker compose up`

## Info:
Starting the docker container will execute the `nx run my-plugin:test` command which will fail the test. If you run the `nx run my-plugin:test` command on a MacOS system, it will pass!

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : linux-arm64
npm    : 10.2.3

nx                 : 19.0.4
@nx/js             : 19.0.4
@nx/jest           : 19.0.4
@nx/linter         : 19.0.4
@nx/eslint         : 19.0.4
@nx/workspace      : 19.0.4
@nx/angular        : 19.0.4
@nx/devkit         : 19.0.4
@nx/eslint-plugin  : 19.0.4
@nx/plugin         : 19.0.4
@nrwl/tao          : 19.0.4
@nx/web            : 19.0.4
@nx/webpack        : 19.0.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Local workspace plugins:
         @plugin-issue/my-plugin
```

### Failure Logs

```shell
LoadPluginError: Could not load plugin /app/node_modules/nx/src/plugins/project-json/build-nodes/package-json-next-to-project-json

  12 |   it('should run successfully', async () => {
  13 |     // this will fail:
> 14 |     const result =   await libraryGenerator(tree, {
     |                      ^
  15 |       name: 'test',
  16 |       directory: '',
  17 |     });

  at loadNxPluginAsync (../node_modules/nx/src/project-graph/plugins/loader.js:207:15)
  at loadNxPlugin (../node_modules/nx/src/project-graph/plugins/loader.js:180:9)
  at loadNxPlugins (../node_modules/nx/src/project-graph/plugins/internal-api.js:49:48)
  at async buildProjectGraphAndSourceMapsWithoutDaemon (../node_modules/nx/src/project-graph/project-graph.js:75:32)
  at async createProjectGraphAndSourceMapsAsync (../node_modules/nx/src/project-graph/project-graph.js:202:25)
  at async createProjectGraphAsync (../node_modules/nx/src/project-graph/project-graph.js:191:39)
  at async initEsLint (../node_modules/@nx/eslint/src/generators/init/init.js:41:19)
  at async lintInitGenerator (../node_modules/@nx/eslint/src/generators/init/init.js:80:12)
  at async lintProjectGeneratorInternal (../node_modules/@nx/eslint/src/generators/lint-project/lint-project.js:25:22)
  at async addLintingGenerator (../node_modules/@nx/angular/src/generators/add-linting/add-linting.js:14:22)
  at async addLinting (../node_modules/@nx/angular/src/generators/library/library.js:123:5)
  at async libraryGeneratorInternal (../node_modules/@nx/angular/src/generators/library/library.js:69:5)
  at async libraryGenerator (../node_modules/@nx/angular/src/generators/library/library.js:25:12)
  at async Object.<anonymous> (src/generators/my-generator/generator.spec.ts:14:22)
Cause:
TypeError: performance.mark is not a function

  12 |   it('should run successfully', async () => {
  13 |     // this will fail:
> 14 |     const result =   await libraryGenerator(tree, {
     |                      ^
  15 |       name: 'test',
  16 |       directory: '',
  17 |     });

  at loadNxPluginAsync (../node_modules/nx/src/project-graph/plugins/loader.js:198:21)
  at loadNxPlugin (../node_modules/nx/src/project-graph/plugins/loader.js:180:9)
  at loadNxPlugins (../node_modules/nx/src/project-graph/plugins/internal-api.js:49:48)
  at async buildProjectGraphAndSourceMapsWithoutDaemon (../node_modules/nx/src/project-graph/project-graph.js:75:32)
  at async createProjectGraphAndSourceMapsAsync (../node_modules/nx/src/project-graph/project-graph.js:202:25)
  at async createProjectGraphAsync (../node_modules/nx/src/project-graph/project-graph.js:191:39)
  at async initEsLint (../node_modules/@nx/eslint/src/generators/init/init.js:41:19)
  at async lintInitGenerator (../node_modules/@nx/eslint/src/generators/init/init.js:80:12)
  at async lintProjectGeneratorInternal (../node_modules/@nx/eslint/src/generators/lint-project/lint-project.js:25:22)
  at async addLintingGenerator (../node_modules/@nx/angular/src/generators/add-linting/add-linting.js:14:22)
  at async addLinting (../node_modules/@nx/angular/src/generators/library/library.js:123:5)
  at async libraryGeneratorInternal (../node_modules/@nx/angular/src/generators/library/library.js:69:5)
  at async libraryGenerator (../node_modules/@nx/angular/src/generators/library/library.js:25:12)
  at async Object.<anonymous> (src/generators/my-generator/generator.spec.ts:14:22)
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by digitalhank** [comment]
experiencing the same but with the applicationGenerator from '@nx/next' on v18.3.4

**Comment by pedroyan** [comment]
I'm experiencing the same problem. Tests work on MacOS but not on our Linux CI.

It happens when I call the `libraryGenerator` function from `@nx/nest`@18.3.4 on a Jest test

**Comment by SuneRadich** [comment]
I got my test to run by following a workaround from https://github.com/mswjs/msw/issues/1851

```
Object.defineProperties(globalThis, {
  performance: { value: performance, writable: true },
});```

Not quite sure why it works, but my test runs again with this 'fix'.

**Comment by dasco144** [comment]
I'm having the same issue when wrapping the service schematic from @schematics/angular, and executing that.

**Comment by sonikasharma1403** [comment]
facing the same issue, but only in the TeamCity environment.

**Comment by sonikasharma1403** [comment]
@AgentEnder , any update on this?

**Comment by hunhavoc** [comment]
Having the same issue. Tests run well on local Mac, but does not work on Linux env in CI.

**Comment by AgentEnder** [comment]
Hi there 👋 - so this is a bit more complex than one may imagine. Most typically getting this error during a unit test is a result of a test doing **_something_** that is causing the project graph to be created. You'll need to mock the project graph during these tests, and while that sounds rough its also going to give you much more accurate and repeatable tests.

Without mocking the graph, the tests will be running generators which create the project graph of the current Nx workspace and make some decisions about that. That's almost always not really what you want. We just recently fixed that behavior on the Nx repo.

This suddenly became a problem for some folks because several of our published generators do rely on the graph now.

You can see how we are mocking this in our unit test setup: https://github.com/nrwl/nx/blob/master/scripts/unit-test-setup.js
