### ISSUE TITLE
NX 19:  NX Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by Jesse1989pp** [nrwl/nx#23430]
### Current Behavior

When i bump my NX version from 18 to 19 i get issues in my pipelines.
This is not happening locally (at least not consistently)

It seems to run into an issue when the `runCreateNodesInParallel` hits, whether via a `nx run-many` or `nx show projects`.

The error:
```
TypeError: Cannot read properties of undefined (reading 'split')
    at new CreateNodesError (PROJECT/node_modules/nx/src/project-graph/error-types.js:136:56)
    at PROJECTm/node_modules/nx/src/project-graph/plugins/utils.js:59:25
    at async Promise.all (index 0)
    at runCreateNodesInParallel (PROJECT/node_modules/nx/src/project-graph/plugins/utils.js:66:5)
    at async Promise.all (index 1)
    at buildProjectGraphAndSourceMapsWithoutDaemon (PROJECT/node_modules/nx/src/project-graph/project-graph.js:77:31)
    at createProjectGraphAndSourceMapsAsync (PROJECT/node_modules/nx/src/project-graph/project-graph.js:202:25)
    at createProjectGraphAsync (PROJECT/node_modules/nx/src/project-graph/project-graph.js:[19]
    at Object.runMany (PROJECT/node_modules/nx/src/command-line/run-many/run-many.js:29:26)
```

### Expected Behavior

No issues, we're not using NX ENV variables. Migration should be not breaking as i understand

### Steps to Reproduce

As i am struggling understanding the issue i am not able to have a concentrated reproduction yet.

1. Starting with a working Nuxt application
2. `nx migrate latest`
3. Push to CI and the errors show up in my workflows.

node: v20.13.1
npm: 10.5.2
yarn: 1.22.22

### Nx Report

```shell
Node   : 20.13.1
OS     : darwin-arm64
yarn   : 1.22.22

nx (global)        : 19.0.4
nx                 : 19.0.4
@nx/js             : 19.0.4
@nx/linter         : 19.0.4
@nx/eslint         : 19.0.4
@nx/workspace      : 19.0.4
@nx/cypress        : 19.0.4
@nx/devkit         : 19.0.4
@nx/eslint-plugin  : 19.0.4
@nrwl/tao          : 19.0.4
@nx/vite           : 19.0.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
nx-stylelint : 17.1.4
```

### Failure Logs

```shell
at new CreateNodesError (PROJECT/node_modules/nx/src/project-graph/error-types.js:136:56)
    at PROJECTm/node_modules/nx/src/project-graph/plugins/utils.js:59:25
    at async Promise.all (index 0)
    at runCreateNodesInParallel (PROJECT/node_modules/nx/src/project-graph/plugins/utils.js:66:5)
    at async Promise.all (index 1)
    at buildProjectGraphAndSourceMapsWithoutDaemon (PROJECT/node_modules/nx/src/project-graph/project-graph.js:77:31)
    at createProjectGraphAndSourceMapsAsync (PROJECT/node_modules/nx/src/project-graph/project-graph.js:202:25)
    at createProjectGraphAsync (PROJECT/frontend-platform/node_modules/nx/src/project-graph/project-graph.js:[19](https://github.com/jumbo-supermarkten/frontend-platform/actions/runs/9110336331/job/25045213216?pr=2356#step:7:20)1:39)
    at Object.runMany (PROJECT/node_modules/nx/src/command-line/run-many/run-many.js:29:26)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hey @Jesse1989pp - can you retry with latest? The error logs have been updated so if its still breaking they'll be more helpful.

**Comment by Jesse1989pp** [comment]
@AgentEnder Thanks for the follow-up. Frankly it seems like the issue is covered within latest, so no need for the log so far. Thank you! Will close this issue on this note.

**Comment by enaluz** [comment]
I'm running into this same issue in `19.5.7` while running `npx nx show project <project-name> --web --verbose`. Stack trace:

```
TypeError: Cannot read properties of undefined (reading 'split')
    at <omitted-path>/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:255:58
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at async processFilesAndCreateAndSerializeProjectGraph (<omitted-path>/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:148:43)
    at async getCachedSerializedProjectGraphPromise (<omitted-path>/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:48:16)
    at async handleRequestProjectGraph (<omitted-path>/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
    at async handleResult (<omitted-path>/node_modules/nx/src/daemon/server/server.js:140:16)
    at async handleMessage (<omitted-path>/node_modules/nx/src/daemon/server/server.js:93:9)
    at async <omitted-path>/node_modules/nx/src/daemon/server/server.js:59:9
```

**Comment by Jesse1989pp** [comment]
I am no longer experiencing this on latest. Did have issues with docker and NX_DAEMON. Quite the reach and assumption looking at the stacktrace, but i feel like some issues are occurring with that. I had to opt out in my dockerbuild as nx also disables it on ci by default: https://nx.dev/concepts/nx-daemon#turning-it-off 

If you have another setup feel free to share more of your setup.
