### ISSUE TITLE
nx is not supported on ppc64le (power architecture)

### ISSUE THREAD

**Issue by vinodk99** [nrwl/nx#23821]
### Current Behavior

Facing issues while installing on power architecture:

yarn run build

 NX   Missing Platform Dependency

The Nx CLI could not find or load the native binary for your supported platform (linux-ppc64).
This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
For more information please see https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues

make: *** [Makefile:150: build-js] Error 1

### Expected Behavior

Installed should pass

### Steps to Reproduce

1.
Please add platform support for ppc64le architecture

### Nx Report

```shell
# This file contains the result of Yarn building a package (nx@virtual:655a650279fd53a33b875a5595ff15a3353c198884ee5237440200eaaf0cb08dcae7f5f8ae5c6ab3d0b41511876ec3f111e176e263e9ad13dac49ec362957d1d#npm:18.1.3)
# Script name: postinstall

/grafana/node_modules/nx/src/native/index.js:235
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
        ^

Error: Unsupported architecture on Linux: ppc64
    at Object.<anonymous> (/grafana/node_modules/nx/src/native/index.js:235:15)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/grafana/node_modules/nx/src/hasher/node-task-hasher-impl.js:10:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)

Node.js v18.20.2
```

### Package Manager Version

yarn --version 4.1.0

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
This will be fixed with https://github.com/nrwl/nx/pull/22870
