### ISSUE TITLE
npx create-nx-workspace  --appName=webapp fail

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#2427]
`npx create-nx-workspace@latest todo --preset=angular --cli=nx --appName=webapp --style=scss`

```
npx: installed 169 in 6.268s
Creating a sandbox with Nx...
new yeti "--style=scss" --preset="angular" --appName="webapp" --style="scss" --interactive=false --collection=@nrwl/workspace
Schematic input does not validate against the Schema: {"style":["scss","scss"],"preset":"angular","appName":"webapp","--":[{"name":"collection","possible":[]}],"name":"yeti"}
Errors:

  Data path ".style" should be string.
(node:92842) UnhandledPromiseRejectionWarning: Error: Command failed: "/var/folders/ym/_jvkpgm51tq_sbrpmny7qqv00000gn/T/tmp-92842PqMSX3VwLMHA/node_modules/.bin/tao" new yeti "--style=scss" --preset="angular" --appName="webapp" --style="scss" --interactive=false --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at createApp (/Users/schintha/.npm/_npx/92842/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:342:21)
    at /Users/schintha/.npm/_npx/92842/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:76:21
(node:92842) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:92842) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by shanepadgett** [comment]
Get the same result trying to create a react/express app interactively.

**Comment by shanepadgett** [comment]
Well I was able to get it to work. I ended up uninstalling yarn and that did it.

**Comment by xmlking** [comment]
I have the following  global npm packages: 
`yarn global list`
```
yarn global v1.22.0
info "@angular/cli@9.0.2" has binaries:
   - ng
info "@nestjs/cli@6.14.2" has binaries:
   - nest
info "@nrwl/cli@9.0.0" has binaries:
   - nx
info "commitizen@4.0.3" has binaries:
   - git-cz
   - commitizen
info "lerna@3.20.2" has binaries:
   - lerna
✨  Done in 0.72s.
```

`nx create-nx-workspace --preset=angular --cli=nx test123`  as documented won't work for me.

Error
```
  NX  The current directory isn't part of an Nx workspace.

  To create a workspace run:
  npx create-nx-workspace@latest <workspace name>


>  NX   NOTE  For more information please visit https://nx.dev/
```
