### ISSUE TITLE
[9.0.0] - workspace-schematic throws error

### ISSUE THREAD

**Issue by jerryorta-dev** [nrwl/nx#2473]
## Expected Behavior

Using a custom schematic as outlined in the Advance Workspaces course - I should be able to create libraries with tags.

## Current Behavior

Running a command like this: `nx workspace-schematic tagged-library util-inline-worker` creates a tagged library.

This works in nx ~8.

## Failure Information (for bugs)

Command throws error

### Context

Please provide any relevant information about your setup:

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results 
```
  @nrwl/angular : 9.0.0
  @nrwl/cli : 9.0.0
  @nrwl/cypress : 9.0.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : 9.0.0
  @nrwl/jest : 9.0.0
  @nrwl/linter : 9.0.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.0.0
  @nrwl/react : Not Found
  @nrwl/schematics : 8.12.4
  @nrwl/tao : 9.0.0
  @nrwl/web : Not Found
  @nrwl/workspace : 9.0.0
  typescript : 3.7.5

```

### Failure Logs

The terminal error:
```
- /my/personal/app/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js
- /my/personal/app/node_modules/@angular-devkit/schematics/tools/workflow/node-workflow.js
- /my/personal/app/node_modules/@angular-devkit/schematics/tools/index.js
- /my/personal/app/node_modules/@nrwl/workspace/src/command-line/workspace-schematic.js
- /my/personal/app/node_modules/@nrwl/workspace/src/command-line/nx-commands.js
- /my/personal/app/node_modules/@nrwl/cli/lib/init-local.js
- /my/personal/app/node_modules/@nrwl/cli/bin/nx.js
- /Users/jorta/.nvm/versions/node/v12.3.1/lib/node_modules/@nrwl/cli/lib/init-global.js
- /Users/jorta/.nvm/versions/node/v12.3.1/lib/node_modules/@nrwl/cli/bin/nx.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at NodeModulesEngineHost._resolveCollectionPath (/my/personal/app/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:39:45)
    at NodeModulesEngineHost.createCollectionDescription (/my/personal/app/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:109:27)
    at SchematicEngine._createCollectionDescription (/my/personal/app/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/my/personal/app/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at /my/personal/app/node_modules/@angular-devkit/schematics/src/rules/schematic.js:23:43
    at MergeMapSubscriber.project (/my/personal/app/node_modules/@angular-devkit/schematics/src/rules/call.js:74:24)
    at MergeMapSubscriber._tryNext (/my/personal/app/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/my/personal/app/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
```

**Comment by vsavkin** [comment]
@jerryorta-dev unfortunately, I cannot repro it. Could you provide a repo with a reproduction? 

My guess that maybe you are relying on  the `@nrwl/schematics` package in your workspace schematic. If that's the case you could update it to use `@nrwl/workspace`. That might fix it.

**Comment by jerryorta-dev** [comment]
Thanks @vsavkin, this is working when I create a vanilla nrwl/angular project via the guide instructions, so there is something wrong in my repo.
