### ISSUE TITLE
Next with SCSS and customServerPath option are failing to serve on production mode.

### ISSUE THREAD

**Issue by krizic** [nrwl/nx#2478]
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Next + Scss project should successfully serve production build when `customServerPath` is used.

On: `nx serve {next project name} --configuration=production` Nx should build and serve production build of that project.

## Current Behavior

After a successful build, any next page visited that imports .scss file throws an error!

## Failure Information (for bugs)

```
[ error ] ./pages/index.scss
TypeError: this[MODULE_TYPE] is not a function
Could not find files for /index in .next/build-manifest.json
ModuleBuildError: Module build failed (from /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function
    at /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js:141:24
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:343:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1414:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js:143:14
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:343:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1414:32
ModuleBuildError: Module build failed (from /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function
    at /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js:141:24
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:343:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1414:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/Users/vkrizic/tmp/happynrwl/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/vkrizic/tmp/happynrwl/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js:143:14
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:343:11
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/vkrizic/tmp/happynrwl/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/vkrizic/tmp/happynrwl/node_modules/webpack/lib/Compilation.js:1414:32
```

### Steps to Reproduce

1. pull my repository which sets up basic scenario to reproduce this issue. `https://github.com/krizic/nx-next-scss-prod-error`
2. run `npm install`
3. run `nx serve app-next --configuration=production`

### Context

```  
  @nrwl/angular : Not Found
  @nrwl/cli : 9.0.0
  @nrwl/cypress : 9.0.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.0
  @nrwl/linter : 9.0.0
  @nrwl/nest : Not Found
  @nrwl/next : 9.0.0
  @nrwl/node : Not Found
  @nrwl/react : 9.0.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.0
  @nrwl/web : 9.0.0
  @nrwl/workspace : 9.0.0
  typescript : 3.7.5
```

Observe that `server.js` is wired up as `customServerPath` project build property as described in the documentation

**Comment by krizic** [comment]
@elliottsj have you maybe had any issues with this?

**Comment by krizic** [comment]
@vsavkin would you be so kind to tag this to next.js scope?

**Comment by wickstargazer** [comment]
Hi, I am having the exact same issue for angular app as well

**Comment by krizic** [comment]
@wickstargazer oh wow, OK so this could be escalated? Can you too provide exact steps to reproduce or even better repo with minimum set up to to reproduce the issue?

**Comment by FrozenPandaz** [comment]
Can someone please create a repro to help us debug the issue?

**Comment by wickstargazer** [comment]
@krizic, @FrozenPandaz   The repo is private, i am off till monday night, maybe morning your time. I will set an example one up  and get the steps for you guys.

# Reproduction steps
* Upgrading nx workspace to 9, failed with **there is no command `run-schematics`** when trying to upgrade angular to 9
* Then I upgraded angular to 9 running ng upgrade instead
* Then some project is throwing the issue of scss .. when building for **production only**. Development builds fine

**Comment by krizic** [comment]
@FrozenPandaz please read the description again. The public repo and instructions were provided to start with! For your convenience, I'm linking it again [https://github.com/krizic/nx-next-scss-prod-error](https://github.com/krizic/nx-next-scss-prod-error)

**Comment by elliottsj** [comment]
@krizic I cloned your repo and I'm able to run the example without error.

I ran:

```shell
git clone https://github.com/krizic/nx-next-scss-prod-error.git
cd nx-next-scss-prod-error/
npm install
npm run nx serve app-next --configuration=production
```

Open http://localhost:4200/

<img width="1772" alt="Screen Shot 2020-02-23 at 9 43 54 PM" src="https://user-images.githubusercontent.com/2177366/75125978-dd337e80-5685-11ea-933f-80dd95955bb5.png">

**Comment by krizic** [comment]
@elliottsj  If is see correctly you haven't run production configuration really with that command. I believe npm will swallow your `--configuration=production` parameter.

Try this and let me know: `npm run nx serve app-next -- --configuration=production` or run globally installed nx with: `nx serve app-next --configuration=production`

**Comment by elliottsj** [comment]
@krizic Got it, I can repro the same issue now.

Looks like [it's a known issue with `@zeit/next-css`](https://github.com/zeit/next-plugins/issues/373).

I'd recommend upgrading to Next.js 9.3; [`.scss` support is built-in now](https://nextjs.org/blog/next-9-3#built-in-sass-css-module-support-for-component-level-styles).
