### ISSUE TITLE
Schematic "application" not found in collection "@nrwl/schematics".

### ISSUE THREAD

**Issue by fxck** [nrwl/nx#25]
I followed https://github.com/nrwl/nx/tree/master/packages/schematics#global-install and it's throwing the error in the title after trying `ng new foo --collection=@nrwl/schematics`, it might be something with my env, since I'm having problems with a clone of the default angular schematics as well (https://github.com/angular/angular-cli/issues/7744)

```
@angular/cli: 1.4.2
node: 8.1.4
os: darwin x64
```

```
➜ ng new foo --collection=@nrwl/schematics
Schematic "application" not found in collection "@nrwl/schematics".
Error: Schematic "application" not found in collection "@nrwl/schematics".
    at SchematicEngine.createSchematic (/Users/fxck/.yarn-config/global/node_modules/@angular-devkit/schematics/src/engine/engine.js:65:19)
    at CollectionImpl.createSchematic (/Users/fxck/.yarn-config/global/node_modules/@angular-devkit/schematics/src/engine/collection.js:11:29)
    at Object.getSchematic (/Users/fxck/.yarn-config/global/node_modules/@angular/cli/utilities/schematics.js:40:23)
    at Class.run (/Users/fxck/.yarn-config/global/node_modules/@angular/cli/tasks/schematic-get-options.js:12:40)
    at Class.beforeRun (/Users/fxck/.yarn-config/global/node_modules/@angular/cli/commands/new.js:99:31)
    at Promise.resolve.then (/Users/fxck/.yarn-config/global/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:150:24)
    at <anonymous>
```

**Comment by dylannnn** [comment]
@vsavkin I had the same issue.

ng add @nrwl/schematics
Installing packages for tooling via npm.
Cannot read property 'sourceRoot' of undefined

Ng version:
Angular CLI: 6.0.8
Node: 8.11.2
OS: win32 x64
Angular: 6.0.9

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
