### ISSUE TITLE
lodash-es explodes with Next.js

### ISSUE THREAD

**Issue by stramel** [nrwl/nx#2556]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Be able to use `lodash-es` in my Next.js app

## Current Behavior

Errors

### Failure Logs

```console
/project/node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at Module.require (/project/node_modules/@nrwl/tao/src/compat/compat.js:4:36)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.lodash-es (/project/dist/apps/core/server/static/development/pages/_app.js:4311:18)
    at __webpack_require__ (/project/dist/apps/core/server/static/development/pages/_app.js:23:31)
    at Module.../../libs/hooks/src/lib/useId/useId.ts (/project/dist/apps/core/server/static/development/pages/_app.js:418:67)
    at __webpack_require__ (/project/dist/apps/core/server/static/development/pages/_app.js:23:31)
    at Module.../../libs/hooks/src/lib/useId/index.ts (/project/dist/apps/core/server/static/development/pages/_app.js:394:64)
    at __webpack_require__ (/project/dist/apps/core/server/static/development/pages/_app.js:23:31)
    at Module.../../libs/hooks/src/index.ts (/project/dist/apps/core/server/static/development/pages/_app.js:291:68)
    at __webpack_require__ (/project/dist/apps/core/server/static/development/pages/_app.js:23:31)
    at Module../hoc/withAuthSync.tsx (/project/dist/apps/core/server/static/development/pages/_app.js:3624:73)
```

**Comment by stramel** [comment]
Workaround is using `lodash` for now.

**Comment by jdpearce** [comment]
Hi @stramel, thanks for raising this, however I've just tried this with a vanilla Next.js app (no Nx) and it also fails there. Perhaps this is something you should raise with them? 

I'm going to close this for now, but can re-open if it does turn out to be down to the way we've integrated Next.js

**Comment by stramel** [comment]
@jdpearce Thanks for checking into it. Didn't have much time to look into it further yesterday. I will raise an issue over there.

**Comment by stramel** [comment]
DOH 🤦‍♂ I should have searched there first. Sorry for the noise...

https://github.com/zeit/next.js/issues/2259

**Comment by dsebastien** [comment]
I've stumbled on the same issue with NestJS. I assume that the same recommendation to use lodash and not lodash-es holds there as well?

**Comment by DaSchTour** [comment]
I hope there is some other solution. It's pretty ugly to have to switch between lodash and lodash-es between different projects and it also eliminates the possibility to use lodash inside a library that is shared between server and client.
