### ISSUE TITLE
The command to create a workspace is failing

### ISSUE THREAD

**Issue by jlteodoro** [nrwl/nx#2586]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

The command to create a workspace is not working

## Current Behavior

I execute the following command to create a workspace:
npm init nx-workspace myworkspace

The command fails with the following message:

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Go to a folder on the root directory (cd ~/test)
2. Execute the command as listed in the getting started guide (npm init nx-workspace myworkspace)
3. For the workspace type I selected angular 
4. Stylesheet I selected CSS
5. Project name I typed test
4. The command fails and no namespace is created

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

- I believe it is the latest as I am running per getting started
- No third party libraries
- Trying to create a namespace fails
- I tried with npm 12.16.1 and 12.10.0
- I am running Ubuntu 18 with Windows Linux Subsystem

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs
(node:2093) UnhandledPromiseRejectionWarning: Error: Command failed: npm install --silent
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at createSandbox (/home/<changed by me>/.npm/_npx/2059/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:317:21)
    at /home/<changed by me>/.npm/_npx/2059/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:75:36
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2093) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jlteodoro** [comment]
I was able to resolve the issue by removing the ~/.npm folder, removing a old node version that was installed before I installed nvm, then running the command again.
