### ISSUE TITLE
create workspace doesn't work

### ISSUE THREAD

**Issue by alexanderPastornicky** [nrwl/nx#2591]
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

Workspace is created

## Current Behavior

Error during workspace creating

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npx create-nx-workspace@latest myworkspace`

### Context
Nodejs v12.16.1

### Failure Logs

```
/ Installing packages...npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Unexpected end of JSON input while parsing near '...SciChHreqfJIWh8f0DN4c'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abc\AppData\Roaming\npm-cache\_logs\2020-02-29T18_09_28_568Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.
Workspace creation failed, see above.
(node:10624) UnhandledPromiseRejectionWarning: Error: Command failed: "C:\Users\abc\AppData\Local\Temp\tmp-10624Rxl5u7Hufu3i\node_modules\.bin\ng" new karol-app --preset="angular" --appName="karol-app" --style="scss" --interactive=false --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at createApp (C:\Users\abc\AppData\Roaming\npm-cache\_npx\10624\node_modules\create-nx-workspace\bin\create-nx-workspace.js:343:21)
    at C:\Users\abc\AppData\Roaming\npm-cache\_npx\10624\node_modules\create-nx-workspace\bin\create-nx-workspace.js:76:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by alexanderPastornicky** [comment]
`npm cache clean --force` solved this issue
