### ISSUE TITLE
nx fails to create a workspace

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx#26012]
### Current Behavior

`npx create-nx-workspace@latest nx1907` fails to create a workspace

### Expected Behavior

should generate workspace without errors

### Steps to Reproduce

```
npx create-nx-workspace@latest nx1907  --preset=apps --workspaceType=integrated --ci=skip
```

### Nx Report

```shell
> node -v
v20.12.2

> npm -v
10.8.0
```

### Failure Logs

```shell
> npx create-nx-workspace@latest nx1907  --preset=apps --workspaceType=integrated --ci=skip

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]


 NX   Creating your v19.0.7 workspace.

✔ Installing dependencies with npm
✖ Creating your workspace in nx1907

 NX   Failed to create a workspace.

Exit code: 1
Log file: C:\Users\denis\AppData\Local\Temp\tmp-17144-Jgc73RcgeL0U\error.log

> cat C:\Users\denis\AppData\Local\Temp\tmp-17144-Jgc73RcgeL0U\error.log
 NX   Command failed: npm install


Error: Command failed: npm install
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at installPackagesTask (C:\Users\denis\AppData\Local\Temp\tmp-7716-aGyv1IhZPlxs\node_modules\@nx\devkit\src\tasks\install-packages-task.js:37:38)
    at C:\Users\denis\AppData\Local\Temp\tmp-7716-aGyv1IhZPlxs\node_modules\@nx\workspace\src\generators\new\new.js:24:46
    at C:\Users\denis\AppData\Local\Temp\tmp-7716-aGyv1IhZPlxs\node_modules\nx\src\command-line\new\new.js:26:19
    at async handleErrors (C:\Users\denis\AppData\Local\Temp\tmp-7716-aGyv1IhZPlxs\node_modules\nx\src\utils\params.js:10:16)
    at async Object.handler (C:\Users\denis\AppData\Local\Temp\tmp-7716-aGyv1IhZPlxs\node_modules\nx\src\command-line\new\command-object.js:10:22)

npm error code ETARGET
npm error notarget No matching version found for @babel/helper-environment-visitor@^7.24.6.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: C:\Users\denis\AppData\Local\npm-cache\_logs\2024-05-24T14_04_16_502Z-debug-0.log
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
I do not get the same error. Are you perhaps on a different registry url? :eyes:

**Comment by Den-dp** [comment]
@FrozenPandaz wow, you are right, it looks like my registry was out of sync, but now it works
```
> npx create-nx-workspace@latest nx1907 --preset=apps --workspaceType=integrated --ci=skip --verbose

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]


 NX   Creating your v19.0.7 workspace.

✔ Installing dependencies with npm
✔ Successfully created the workspace: nx1907.

——————————————————————————————————————————

 NX   First time using Nx? Check out this interactive Nx tutorial.

https://nx.dev/getting-started/tutorials/npm-workspaces-tutorial
```
Sorry about that!
