### ISSUE TITLE
Error start remotes Nx 19.1.0

### ISSUE THREAD

**Issue by AlanGRutter** [nrwl/nx#26169]
### Current Behavior

After upgrading and migrating Nx to 19.1.0, when I try to start my module federated host application using nx serve, I get a TypeError as shown in the failure logs.

If I use the command nx serve and specify --devRemotes, it works without any problems.

### Expected Behavior

The host app should be served correctly without errors.

### Steps to Reproduce

1. I don't have a repo in which to reproduce.

### Nx Report

```shell
Node   : 20.12.2
OS     : linux-x64
yarn   : 4.2.2

nx (global)        : 19.1.0
nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/angular        : 19.1.0
@nx/cypress        : 19.1.0
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nx/storybook      : 19.1.0
@nrwl/tao          : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
@nx/storybook/plugin
---------------------------------------
Community plugins:
@nx-tools/nx-container                : 6.0.1
@storybook/angular                    : 8.1.4
@syncfusion/ej2-angular-base          : 25.2.6
@syncfusion/ej2-angular-buttons       : 25.2.6
@syncfusion/ej2-angular-inputs        : 25.2.6
@syncfusion/ej2-angular-notifications : 25.2.3
ngxtension                            : 3.3.0
```

### Failure Logs

```shell
nx serve web --no-cloud --verbose
[NX CLOUD] Verifying current cloud bundle
[NX CLOUD] Currently installed bundle is invalid, downloading version 2405.23.7.hotfix3  from  https://cloud.nx.app/nx-cloud/static/client-bundle
[NX CLOUD] Done:  /home/alan.rutter/TAGTheAgency/YES/YoungEnterpriseV2/yes-web-portal/.nx/cache/cloud/2405.23.7.hotfix3

 NX   Nx Cloud Manually Disabled

Nx will continue running, but nothing will be written or read from the remote cache.
Run details will also not be available in the Nx Cloud UI.

If this wasn't intentional, check for the NX_NO_CLOUD environment variable, the --no-cloud flag


> nx run web:serve:development


 NX  Starting module federation dev-server for web with 1 remotes


 NX   Cannot read properties of undefined (reading 'find')


TypeError: Cannot read properties of undefined (reading 'find')
    at startRemotes (/home/alan.rutter/TAGTheAgency/YES/YoungEnterpriseV2/yes-web-portal/node_modules/@nx/angular/src/executors/module-federation-dev-server/lib/start-dev-remotes.js:16:58)
    at moduleFederationDevServerExecutor (/home/alan.rutter/TAGTheAgency/YES/YoungEnterpriseV2/yes-web-portal/node_modules/@nx/angular/src/executors/module-federation-dev-server/module-federation-dev-server.impl.js:81:61)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getLastValueFromAsyncIterableIterator (/home/alan.rutter/TAGTheAgency/YES/YoungEnterpriseV2/yes-web-portal/node_modules/nx/src/utils/async-iterator.js:15:19)
    at iteratorToProcessStatusCode (/home/alan.rutter/TAGTheAgency/YES/YoungEnterpriseV2/yes-web-portal/node_modules/nx/src/command-line/run/run.js:44:29)
    at handleErrors (/home/alan.rutter/TAGTheAgency/YES/YoungEnterpriseV2/yes-web-portal/node_modules/nx/src/utils/params.js:10:16)
    at process.<anonymous> (/home/alan.rutter/TAGTheAgency/YES/YoungEnterpriseV2/yes-web-portal/node_modules/nx/bin/run-executor.js:59:28)

————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target serve for project web failed

Failed tasks:

- web:serve:development

Hint: run the command with --verbose for more details.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by rternavskyi** [comment]
I have same problem!

**Comment by MaxSassen** [comment]
same issue when migrating to 19

```Node   : 21.5.0
OS     : darwin-x64
npm    : 10.2.4

nx (global)        : 18.0.8
nx                 : 19.1.1
@nx/js             : 19.1.1
@nx/jest           : 19.1.1
@nx/linter         : 19.1.1
@nx/eslint         : 19.1.1
@nx/workspace      : 19.1.1
@nx/angular        : 19.1.1
@nx/cypress        : 19.1.1
@nx/devkit         : 19.1.1
@nx/eslint-plugin  : 19.1.1
@nx/nest           : 19.1.1
@nx/node           : 19.1.1
@nx/playwright     : 19.1.1
@nx/plugin         : 19.1.1
@nrwl/tao          : 19.1.1
@nx/web            : 19.1.1
@nx/webpack        : 19.1.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/playwright/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc : 1.1.23
@ngneat/input-mask : 6.1.0
@nx-go/nx-go       : 2.8.0
apollo-angular     : 6.0.0```

**Comment by MaxSassen** [comment]
@leosvelperez  thanks !
