### ISSUE TITLE
Project Crystal: Using a custom plugin causes the jest plugin to crash

### ISSUE THREAD

**Issue by a88zach** [nrwl/nx#26245]
### Current Behavior

When registering  a custom plugin for project crystal, the jest plugin errors when generating the project graph

### Expected Behavior

Users should be able to create and use custom plugins

### GitHub Repo

https://github.com/a88zach/crystal-bug

### Steps to Reproduce

1.  The steps are in the repo README.md

Note:  I had to create a new repo using version 16 and then migrate to latest before I could reproduce this bug

### Nx Report

```shell
Node   : 20.13.1
OS     : darwin-arm64
yarn   : 3.8.2

nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nx/node           : 19.1.0
@nx/react          : 19.1.0
@nrwl/tao          : 19.1.0
@nx/vite           : 19.1.0
@nx/web            : 19.1.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
./tools/plugin.ts
@nx/jest/plugin
@nx/vite/plugin
```

### Failure Logs

```shell
NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

    Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
    The "@nx/jest/plugin" plugin threw an error while creating nodes from libs/test-lib-1/jest.config.ts:
        Error: Jest: Failed to parse the TypeScript config file /Users/zachtindall/Documents/repos/crystal-bug/libs/test-lib-1/jest.config.ts
        TSError: ⨯ Unable to compile TypeScript:
        libs/test-lib-1/jest.config.ts(8,7): error TS2451: Cannot redeclare block-scoped variable '_default'.

            at readConfigFileAndSetRootDir (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13)
            at processTicksAndRejections (node:internal/process/task_queues:95:5)
            at async readInitialOptions (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/jest-config/build/index.js:403:13)
            at async readConfig (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/jest-config/build/index.js:147:48)
            at async buildJestTargets (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/@nx/jest/src/plugins/plugin.js:78:20)
            at async Array.exports.createNodes (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/@nx/jest/src/plugins/plugin.js:60:32)
            at async /Users/zachtindall/Documents/repos/crystal-bug/node_modules/nx/src/project-graph/plugins/utils.js:49:27
            at async Promise.all (index 1)
            at async runCreateNodesInParallel (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/nx/src/project-graph/plugins/utils.js:66:5)
            at async Promise.all (index 3)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
Hello @a88zach - this is unfortunately a known issue. We are working on resolving it. There are some complexities caused by registering the ts transpiler to run the custom plugin.

You can try either:
- uninstalling @swc-node/register (and other swc deps if you aren't using them otherwise)
- setting NX_PREFER_TS_NODE=true in the environment
- set NX_ISOLATE_PLUGINS=true in the environment (this is our long term fix, just some small kinks we are polishing now).

Jest uses ts-node under the hood when loading config files and if another transpiler is present things get double transpiled resulting in the issue you are seeing. Our long term fix is to run all plugins in isolated threads, to avoid any kind of global pollution between them. We are hoping to get it out in 19.2 or 19.3 by default.

**Comment by a88zach** [comment]
Hey @AgentEnder, setting `NX_ISOLATE_PLUGINS=true` worked with one major caveat :) 

With that env variable set in the root `.env` file, it seems the post install script for nx hangs when install dependencies with yarn (most likely not package manager dependent).   

I've updated my example repo, and you can reproduce with the following steps

1. `rm -rf node_modules`
2. `yarn`
3.  The install process will hang when running the post install script for nx
4. Update `NX_ISOLATE_PLUGINS` in `.env` and set to *false*
5. `yarn`
6. This time dependencies should be installed and all post install scripts will run successfully

There are obviously several workarounds to the issue, but wanted to bring it to your attention.  For now, I can use `NX_PREFER_TS_NODE=true`

**Comment by AgentEnder** [comment]
The hanging should be fixed in latest

**Comment by a88zach** [comment]
@AgentEnder, the latest update did fix the hanging issue, but now there is a new error without a workaround like the previous version

Any thoughts on how to fix this one?   I also updated the example repo above (https://github.com/a88zach/crystal-bug) so you could easily reproduce the issue.

```
$ yarn exec nx show project test-lib-1 --verbose

 NX   object null is not iterable (cannot read property Symbol(Symbol.iterator))


TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at /Users/zachtindall/Documents/repos/crystal-bug/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:248:53
    at Array.map (<anonymous>)
    at /Users/zachtindall/Documents/repos/crystal-bug/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:248:49
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async processFilesAndCreateAndSerializeProjectGraph (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:148:43)
    at async getCachedSerializedProjectGraphPromise (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:46:16)
    at async handleRequestProjectGraph (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
    at async handleResult (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/nx/src/daemon/server/server.js:130:16)
    at async handleMessage (/Users/zachtindall/Documents/repos/crystal-bug/node_modules/nx/src/daemon/server/server.js:89:9)
```

**Comment by AgentEnder** [comment]
This will be fixed in the next release

**Comment by a88zach** [comment]
v19.2.2 is working as expected with `NX_ISOLATE_PLUGINS=true`.  

Thanks for the quick turnaround
