### ISSUE TITLE
`npx nx@latest init` fails on Windows when installing `nx/gradle` plugin

### ISSUE THREAD

**Issue by tacascer** [nrwl/nx#26255]
### Current Behavior

`npx nx@latest init` gives this error when the gradle plugin is selected

```shell
'.' is not recognized as an internal or external command,
operable program or batch file.
nx init

Adds Nx to any type of workspace. It installs nx, creates an nx.json configuration file and optionally sets up remote caching. For more info, check https://nx.dev/recipes/adopting-nx.

Options:
  --help                  Show help                                                                                                                                                       [boolean]
  --version               Show version number                                                                                                                                             [boolean]
  --nxCloud               Set up distributed caching with Nx Cloud.                                                                                                                       [boolean]
  --interactive           When false disables interactive input prompts for options.                                                                                      [boolean] [default: true]
  --useDotNxInstallation  Initialize an Nx workspace setup in the .nx directory of the current repository.                                                               [boolean] [default: false]

Error: Command failed: ./nx add @nx/gradle
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:889:11)
    at execSync (node:child_process:961:15)
    at M:\Projects\gradle-tutorial\.nx\installation\node_modules\nx\src\command-line\init\init-v2.js:36:42
    at Array.forEach (<anonymous>)
    at Object.initHandler (M:\Projects\gradle-tutorial\.nx\installation\node_modules\nx\src\command-line\init\init-v2.js:35:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (M:\Projects\gradle-tutorial\.nx\installation\node_modules\nx\src\command-line\init\command-object.js:14:13) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 16136,
  stdout: null,
  stderr: null
}
```

### Expected Behavior

`npx nx@latest init` should not fail when installing a plugin.

### GitHub Repo

https://github.com/tacascer/gradle-tutorial

### Steps to Reproduce

1. Run `npx nx@latest init`

### Nx Report

```shell
Node   : 22.2.0
OS     : win32-x64
npm    : 10.8.0

nx         : 19.1.1
@nrwl/tao  : 19.1.1
```
```


### Failure Logs

```shell
M:\Projects\gradle-tutorial>node M:\Projects\gradle-tutorial\\.nx\nxw.js init
Setting Nx up installation in `.nx`. You can run Nx commands like: `./nx.bat --help`
UPDATE .gitignore

 NX   Recommended Plugins:

Add these Nx plugins to integrate with the tools used in your workspace.

√ Which plugins would you like to add? Press <Space> to select and <Enter> to submit. · @nx/gradle
'.' is not recognized as an internal or external command,
operable program or batch file.
nx init

Adds Nx to any type of workspace. It installs nx, creates an nx.json configuration file and optionally sets up remote caching. For more info, check https://nx.dev/recipes/adopting-nx.

Options:
  --help                  Show help                                                                                                                                                       [boolean]
  --version               Show version number                                                                                                                                             [boolean]
  --nxCloud               Set up distributed caching with Nx Cloud.                                                                                                                       [boolean]
  --interactive           When false disables interactive input prompts for options.                                                                                      [boolean] [default: true]
  --useDotNxInstallation  Initialize an Nx workspace setup in the .nx directory of the current repository.                                                               [boolean] [default: false]

Error: Command failed: ./nx add @nx/gradle
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:889:11)
    at execSync (node:child_process:961:15)
    at M:\Projects\gradle-tutorial\.nx\installation\node_modules\nx\src\command-line\init\init-v2.js:36:42
    at Array.forEach (<anonymous>)
    at Object.initHandler (M:\Projects\gradle-tutorial\.nx\installation\node_modules\nx\src\command-line\init\init-v2.js:35:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (M:\Projects\gradle-tutorial\.nx\installation\node_modules\nx\src\command-line\init\command-object.js:14:13) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 16136,
  stdout: null,
  stderr: null
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i think it is fixed in pr https://github.com/nrwl/nx/pull/27364
