### ISSUE TITLE
Error: Target project does not exist

### ISSUE THREAD

**Issue by hydra1983** [nrwl/nx#26315]
### Current Behavior

When i run `nx show projects --verbose`, it fails

### Expected Behavior

should run the command successfully

### Steps to Reproduce

1. install dev dependency `@uni-helper/uni-app-types`
2. run the command above
3. it just fails
4. it should be caused by the dependencies definition in the `package.json` file of `@uni-helper/uni-app-types`
```
"dependencies": {
    "@dcloudio/types": "^3.4.8",
    "vue3": "npm:vue@^3.4.26"
  },
```

### Nx Report

```shell
nx report --verbose                                                                                                                                                                                           ─╯

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.
```

### Failure Logs

```shell
nx show projects --verbose                                                                                                                                                                                    ─╯

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  The "nx/js/dependencies-and-lockfile" plugin threw an error while creating dependencies:
    Error: Target project does not exist: npm:vue3@npm:vue@^3.4.26
        at validateCommonDependencyRules (/Users/edison/workspace/peakwalk/scm/gitlab/iets-dev/iets-app-mobile/node_modules/nx/src/project-graph/project-graph-builder.js:323:15)
        at validateDependency (/Users/edison/workspace/peakwalk/scm/gitlab/iets-dev/iets-app-mobile/node_modules/nx/src/project-graph/project-graph-builder.js:313:5)
        at /Users/edison/workspace/peakwalk/scm/gitlab/iets-dev/iets-app-mobile/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:214:80
        at Array.forEach (<anonymous>)
        at /Users/edison/workspace/peakwalk/scm/gitlab/iets-dev/iets-app-mobile/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:205:49
        at Array.forEach (<anonymous>)
        at /Users/edison/workspace/peakwalk/scm/gitlab/iets-dev/iets-app-mobile/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:203:72
        at Array.forEach (<anonymous>)
        at /Users/edison/workspace/peakwalk/scm/gitlab/iets-dev/iets-app-mobile/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:200:26
        at Array.forEach (<anonymous>)
```

### Package Manager Version

```shell
yarn --version                                                                                                                                                                                                ─╯
1.22.22
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

````shell
nx --version                                                                                                                                                                                                  ─╯
Nx Version:
- Local: v19.1.1
- Global: Not found
```

**Comment by alexcheng1982** [comment]
Still has the same issue in `20.1.3`. Can be reproduced with the following dependencies. Seem related to handling of dependencies with `npm:` prefix.

```
"monaco-editor": "npm:@codingame/monaco-vscode-editor-api@~11.1.1",
"monaco-editor-standalone": "npm:monaco-editor@^0.52.0",
"monaco-editor-wrapper": "~6.0.0-next.9",
"monaco-languageclient": "~9.0.0-next.9",
"monaco-languageclient-examples": "~2024.11.3",
"vscode": "npm:@codingame/monaco-vscode-api@~11.1.1"
```

This issue only occurs with Yarn, when parsing the `yarn.lock` file. The workaround is switching to a different package manager, like `npm` or `pnpm`.
