### ISSUE TITLE
uv_os_get_passwd returned ENOENT in docker

### ISSUE THREAD

**Issue by pumano** [nrwl/nx#26351]
### Current Behavior

build failed because os.userInfo posible throws exception

https://github.com/nodejs/node/issues/25714

### Expected Behavior

Should works as previously

### Steps to Reproduce

1.

### Nx Report

```shell
nx    19.1.2
@nx/* 19.1.2
docker image: LTS nodejs 18/20 based on alpine 3.19
```

### Failure Logs

```shell
[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR /home/jenkins-agent/workspace/MR-222/node_modules/nx/src/native/native-bindings.js:244

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     throw loadError

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     ^

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR 

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     at userInfo (node:os:365:11)

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     at getNativeFileCacheLocation (/home/jenkins-agent/workspace/MR-222/node_modules/nx/src/native/native-file-cache-location.js:14:39)

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     at Module._load (/home/jenkins-agent/workspace/MR-222/node_modules/nx/src/native/index.js:57:37)

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     at Module.require (node:internal/modules/cjs/loader:1231:19)

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     at require (node:internal/modules/helpers:179:18)

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     at Object.<anonymous> (/home/jenkins-agent/workspace/MR-222/node_modules/nx/src/native/native-bindings.js:171:31)

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     at Module._compile (node:internal/modules/cjs/loader:1369:14)

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     at Module.load (node:internal/modules/cjs/loader:1206:32)

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     at Module._load (node:internal/modules/cjs/loader:1022:12) {

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR   code: 'ERR_SYSTEM_ERROR',

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR   info: {

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     errno: -2,

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     code: 'ENOENT',

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     message: 'no such file or directory',

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR     syscall: 'uv_os_get_passwd'

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR   },

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR   errno: [Getter/Setter],

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR   syscall: [Getter/Setter]

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR }

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR 

[2024-06-04T13:25:11.701Z] ➤ YN0000: │ nx@npm:19.1.2 [06e84] STDERR Node.js v20.12.2
```

### Package Manager Version

yarn 4.2.2

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

problem introduced since this commit landed: https://github.com/nrwl/nx/commit/10f97b99bcbdb23f65531b3e5891dd9a26c7e06a

**Comment by MaxKless** [comment]
Hey @pumano thanks a lot for the report. I've created a PR to fix this issue, so you should be fine soon: https://github.com/nrwl/nx/pull/26381

Until then, you can set the `NX_NATIVE_FILE_CACHE_DIRECTORY` environment variable to set the location to a specific directory - this will not hit the `userInfo` path and the error should disappear.

**Comment by massimo-esposito** [comment]
What's the expected value of `NX_NATIVE_FILE_CACHE_DIRECTORY`? I'm having same issue described by @pumano and I am seeing different types of error depending on the value:

`export NX_NATIVE_FILE_CACHE_DIRECTORY=$(pwd)` 
results in 
```
Error: EACCES: permission denied, mkdir 'the-path-of-the-project/the-project'
```

and an embedded folder
`export NX_NATIVE_FILE_CACHE_DIRECTORY=/app/nx-cache`
results in

```
npm ERR! code 1
npm ERR! path /app/node_modules/@angular-eslint/builder/node_modules/nx
npm ERR! command failed
npm ERR! command sh -c node ./bin/post-install
npm ERR! /app/node_modules/@angular-eslint/builder/node_modules/nx/src/native/native-bindings.js:244
npm ERR!     throw loadError
npm ERR!     ^
npm ERR! 
npm ERR! Error: /app/nx-cache/19.1.0-nx.linux-arm64-gnu.node: invalid ELF header
npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1452:18)
```

Thank you

**Comment by MaxKless** [comment]
the `NX_NATIVE_FILE_CACHE_DIRECTORY` defines where `.node` files generated by nx native code & used by the daemon should be saved. 
It needs to be an absolute path that your machine can interpret. The nx processes will save a `.node` file there so you have to make sure the processes will have access rights on your machine. That looks like it was the issue in the first example. 

Not sure what `invalid ELF header` means but can you try again with this information?

**Comment by MaxKless** [comment]
nx `19.2.0` was just released so if you upgrade this issue should just go away without a workaround now :)
