### ISSUE TITLE
pnpm dlx nx --version -> Error: Cannot find module 'nx'

### ISSUE THREAD

**Issue by Brain2000** [nrwl/nx#26400]
### Current Behavior

I'll just leave the stacktrace below, as this just started happening today.
I cannot reproduce it on another machine, yet I cannot figure out how to fix it either.
The fact that nx cannot find itself in the isMainNxPackage( ) function seems rather odd...
I have cleaned out the local node_modules folder and the pnpm cache.
The node version is 16.20.1

I also set NX_VERBOSE_LOGGING = true so I would get an actual error message instead of just a number.

```
C:\Users\root>pnpm dlx nx --version
../../.pnpm/store/v3/tmp/dlx-20796       | +109 +++++++++++
../../.pnpm/store/v3/tmp/dlx-20796       | Progress: resolved 118, reused 109, downloaded 0, added 109, done
../../.pnpm/store/v3/tmp/dlx-20796/node_modules/.pnpm/nx@19.2.0/node_modules/nx: Running postinstall script, failed in 637ms
.../.pnpm/nx@19.2.0/node_modules/nx postinstall$ node ./bin/post-install
│ Error: Cannot find module 'nx'
│ Require stack:
│ - C:\.pnpm\store\v3\tmp\dlx-20796\node_modules\.pnpm\nx@19.2.0\node_modules\nx\bin\post-install.js
│     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
│     at Function.resolve (node:internal/modules/cjs/helpers:114:19)
│     at isMainNxPackage (C:\.pnpm\store\v3\tmp\dlx-20796\node_modules\.pnpm\nx@19.2.0\node_modules\nx\bin\post-install.js:52:32)
│     at C:\.pnpm\store\v3\tmp\dlx-20796\node_modules\.pnpm\nx@19.2.0\node_modules\nx\bin\post-install.js:20:13
│     at Object.<anonymous> (C:\.pnpm\store\v3\tmp\dlx-20796\node_modules\.pnpm\nx@19.2.0\node_modules\nx\bin\post-install.js:50:3)
│     at Module._compile (node:internal/modules/cjs/loader:1198:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
│     at Module.load (node:internal/modules/cjs/loader:1076:32)
│     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     'C:\\.pnpm\\store\\v3\\tmp\\dlx-20796\\node_modules\\.pnpm\\nx@19.2.0\\node_modules\\nx\\bin\\post-install.js'
│   ]
│ }
│ Nx postinstall steps took 13ms
└─ Failed in 638ms at C:\.pnpm\store\v3\tmp\dlx-20796\node_modules\.pnpm\nx@19.2.0\node_modules\nx
 ELIFECYCLE  Command failed with exit code 1.
```

The issue occurs in this function:
```
function isMainNxPackage() {
    const mainNxPath = require.resolve('nx', {
        paths: [workspace_root_1.workspaceRoot],
    });
    const thisNxPath = require.resolve('nx');
    return mainNxPath === thisNxPath;
}
```

### Expected Behavior

```
C:\Users\root>pnpm dlx nx --version
AppData/Local/pnpm/store/v3/tmp/dlx-5312 | +109 +++++++++++
AppData/Local/pnpm/store/v3/tmp/dlx-5312 | Progress: resolved 118, reused 109, downloaded 0, added 109, done
Nx Version:
- Local: Not found
- Global: v19.2.0

```

### Steps to Reproduce

1. Install Node 16.20.1
2. Install pnpm 8.6.11
3. Run from a cmd prompt: C:\Users\root> pnpm install -g nx@19.1.2
4. Run from a cmd prompt: C:\Users\root> pnpm dlx nx --version

### Nx Report

```shell
C:\Users\root>pnpm dlx nx report
../../.pnpm/store/v3/tmp/dlx-14204       | +109 +++++++++++
../../.pnpm/store/v3/tmp/dlx-14204       | Progress: resolved 118, reused 109, downloaded 0, added 109, done
../../.pnpm/store/v3/tmp/dlx-14204/node_modules/.pnpm/nx@19.2.0/node_modules/nx: Running postinstall script, failed in 597ms
.../.pnpm/nx@19.2.0/node_modules/nx postinstall$ node ./bin/post-install
│ Error: Cannot find module 'nx'
│ Require stack:
│ - C:\.pnpm\store\v3\tmp\dlx-14204\node_modules\.pnpm\nx@19.2.0\node_modules\nx\bin\post-install.js
│     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
│     at Function.resolve (node:internal/modules/cjs/helpers:114:19)
│     at isMainNxPackage (C:\.pnpm\store\v3\tmp\dlx-14204\node_modules\.pnpm\nx@19.2.0\node_modules\nx\bin\post-install.js:52:32)
│     at C:\.pnpm\store\v3\tmp\dlx-14204\node_modules\.pnpm\nx@19.2.0\node_modules\nx\bin\post-install.js:20:13
│     at Object.<anonymous> (C:\.pnpm\store\v3\tmp\dlx-14204\node_modules\.pnpm\nx@19.2.0\node_modules\nx\bin\post-install.js:50:3)
│     at Module._compile (node:internal/modules/cjs/loader:1198:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
│     at Module.load (node:internal/modules/cjs/loader:1076:32)
│     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     'C:\\.pnpm\\store\\v3\\tmp\\dlx-14204\\node_modules\\.pnpm\\nx@19.2.0\\node_modules\\nx\\bin\\post-install.js'
│   ]
│ }
│ Nx postinstall steps took 13ms
└─ Failed in 598ms at C:\.pnpm\store\v3\tmp\dlx-14204\node_modules\.pnpm\nx@19.2.0\node_modules\nx
 ELIFECYCLE  Command failed with exit code 1.
```

### Package Manager Version

pnpm 8.6.11

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Brain2000** [comment]
I finally figured it out. There was a global version of nx installed, version 19.1.2. After removing this, the problem is solved.
Something really weird going on here where the global version 19.1.2 conflicts with 19.2.

```
pnpm rm -g nx
```
