### ISSUE TITLE
[@nx/esbuild:esbuild] Build not working when generatePackageJson is true and local libraries are referenced

### ISSUE THREAD

**Issue by lucasvieirasilva** [nrwl/nx#26434]
### Current Behavior

After upgrading to Nx 19.x when a node.js project has a `build` target configured to `@nx/esbuild:esbuild` with `generatePackageJson: true`, `thirdParty: true`, and references a local library (e.g. `lib1`) it fails to generate the package-lock, when removes the local library reference (run the lint --fix to remove from the package.json) it generates the package-lock successfully.

### Expected Behavior

when the `thirdParty: true` only the external dependencies should be in the package.json.

As mentioned here:
https://github.com/nrwl/nx/blob/9eebe4980a41715f9993ea72782d8280f5a721c3/packages/esbuild/src/executors/esbuild/esbuild.impl.ts#L96-L101

### GitHub Repo

https://github.com/lucasvieirasilva/nx19-generate-lock-issue

### Steps to Reproduce

In the https://github.com/lucasvieirasilva/nx19-generate-lock-issue repo, the project was created as follows:

- lib1 (node.js library)
- app1 (node.js app with `esbuild` as bundler)
- app2 (node.js app with `esbuild` as bundler)

`app1` uses a function exported by `lib1`, therefore, the app1's package.json has the `lib1` listed as dependency (automatically added by the eslint `@nx/dependency-checks` rule)

`lib1` exports a simple function that uses `lodash` to capitalize a string value.

`app2` uses the `lodash` directly instead of referencing the `lib1`.

When the `build` target is executed for the `app1` project it fails with `Original error: Pruned lock file creation failed. The following package was not found in the root lock file: @example/lib1@0.0.1`

When the `build` target is executed for the `app2` project it runs successfully and generates both package.json and lock file.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.13.1
OS     : darwin-x64
pnpm   : 8.15.8

nx                 : 19.2.0
@nx/js             : 19.2.0
@nx/linter         : 19.2.0
@nx/eslint         : 19.2.0
@nx/workspace      : 19.2.0
@nx/devkit         : 19.2.0
@nx/esbuild        : 19.2.0
@nx/eslint-plugin  : 19.2.0
@nrwl/tao          : 19.2.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
```

### Failure Logs

```shell
✔  1/1 dependent project tasks succeeded [0 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run app1:build


 NX   An error occured while creating pruned lockfile

Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
To prevent the build from breaking we are returning the root lock file.
If you run `pnpm install --lockfile-only` in your output folder it will regenerate the correct pruned lockfile.

Original error: Pruned lock file creation failed. The following package was not found in the root lock file: @example/lib1@0.0.1


Error: Pruned lock file creation failed. The following package was not found in the root lock file: @example/lib1@0.0.1
    at /Users/lucasvieira/Projects/nx-workspaces/nx19-generate-lock/node_modules/.pnpm/nx@19.2.0_@swc-node+register@1.9.1_@swc+core@1.5.25/node_modules/nx/src/plugins/js/lock-file/project-graph-pruning.js:45:19
    at Array.forEach (<anonymous>)
    at normalizeDependencies (/Users/lucasvieira/Projects/nx-workspaces/nx19-generate-lock/node_modules/.pnpm/nx@19.2.0_@swc-node+register@1.9.1_@swc+core@1.5.25/node_modules/nx/src/plugins/js/lock-file/project-graph-pruning.js:31:42)
    at pruneProjectGraph (/Users/lucasvieira/Projects/nx-workspaces/nx19-generate-lock/node_modules/.pnpm/nx@19.2.0_@swc-node+register@1.9.1_@swc+core@1.5.25/node_modules/nx/src/plugins/js/lock-file/project-graph-pruning.js:13:34)
    at createLockFile (/Users/lucasvieira/Projects/nx-workspaces/nx19-generate-lock/node_modules/.pnpm/nx@19.2.0_@swc-node+register@1.9.1_@swc+core@1.5.25/node_modules/nx/src/plugins/js/lock-file/lock-file.js:166:79)
    at updatePackageJson (/Users/lucasvieira/Projects/nx-workspaces/nx19-generate-lock/node_modules/.pnpm/@nx+js@19.2.0_@swc-node+register@1.9.1_@swc+core@1.5.25_@types+node@18.16.9_nx@19.2.0_typescript@5.4.5/node_modules/@nx/js/src/utils/package-json/update-package-json.js:48:61)
    at copyPackageJson (/Users/lucasvieira/Projects/nx-workspaces/nx19-generate-lock/node_modules/.pnpm/@nx+js@19.2.0_@swc-node+register@1.9.1_@swc+core@1.5.25_@types+node@18.16.9_nx@19.2.0_typescript@5.4.5/node_modules/@nx/js/src/utils/package-json/index.js:26:53)
    at esbuildExecutor (/Users/lucasvieira/Projects/nx-workspaces/nx19-generate-lock/node_modules/.pnpm/@nx+esbuild@19.2.0_@swc-node+register@1.9.1_@swc+core@1.5.25_@types+node@18.16.9_esbuild@0.19_wrczqmr3apewhx4aoqc7oc6dii/node_modules/@nx/esbuild/src/executors/esbuild/esbuild.impl.js:65:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getLastValueFromAsyncIterableIterator (/Users/lucasvieira/Projects/nx-workspaces/nx19-generate-lock/node_modules/.pnpm/nx@19.2.0_@swc-node+register@1.9.1_@swc+core@1.5.25/node_modules/nx/src/utils/async-iterator.js:15:19)


——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target build for project app1 and 1 task it depends on (3s)
```

### Package Manager Version

pnpm 8.15.8

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by arthurgubaidullin** [comment]
Do you have any updates on this issue?

**Comment by jackofsometrade** [comment]
Same issue here 🤚

**Comment by ardabeyazoglu** [comment]
I confirm getting the same error after upgrading to nx 19, also on windows, with nestjs and webpack. It seems the issue is not related to esbuild, but to `generatePackageJson` feature. 

```
 NX   An error occured while creating pruned lockfile
Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
To prevent the build from breaking we are returning the root lock file.
If you run `npm install --package-lock-only` in your output folder it will regenerate the correct pruned lockfile.
Original error: Following packages could not be mapped to the NPM lockfile:
- npm:@aws-sdk/client-sso-oidc@3.637.0
- npm:@aws-sdk/client-sts@3.637.0
- npm:@aws-sdk/core@3.635.0
- npm:@aws-sdk/credential-provider-node@3.637.0
- npm:@aws-sdk/credential-provider-env@3.620.1
- npm:@aws-sdk/types@3.609.0
- npm:@aws-sdk/credential-provider-http@3.635.0
- npm:@aws-sdk/credential-provider-ini@3.637.0
- npm:@aws-sdk/credential-provider-process@3.620.1
- npm:@aws-sdk/credential-provider-sso@3.637.0
- npm:@aws-sdk/client-sso@3.637.0
- npm:@aws-sdk/middleware-host-header@3.620.0
- npm:@aws-sdk/middleware-logger@3.609.0
- npm:@aws-sdk/middleware-recursion-detection@3.620.0
- npm:@aws-sdk/middleware-user-agent@3.637.0
- npm:@aws-sdk/util-endpoints@3.637.0
- npm:@aws-sdk/region-config-resolver@3.614.0
- npm:@aws-sdk/util-user-agent-browser@3.609.0
- npm:@aws-sdk/util-user-agent-node@3.614.0
- npm:@aws-sdk/token-providers@3.614.0
- npm:@aws-sdk/credential-provider-web-identity@3.621.0
Error: Following packages could not be mapped to the NPM lockfile:
- npm:@aws-sdk/client-sso-oidc@3.637.0
- npm:@aws-sdk/client-sts@3.637.0
- npm:@aws-sdk/core@3.635.0
- npm:@aws-sdk/credential-provider-node@3.637.0
- npm:@aws-sdk/credential-provider-env@3.620.1
- npm:@aws-sdk/types@3.609.0
- npm:@aws-sdk/credential-provider-http@3.635.0
- npm:@aws-sdk/credential-provider-ini@3.637.0
- npm:@aws-sdk/credential-provider-process@3.620.1
- npm:@aws-sdk/credential-provider-sso@3.637.0
- npm:@aws-sdk/client-sso@3.637.0
- npm:@aws-sdk/middleware-host-header@3.620.0
- npm:@aws-sdk/middleware-logger@3.609.0
- npm:@aws-sdk/middleware-recursion-detection@3.620.0
- npm:@aws-sdk/middleware-user-agent@3.637.0
- npm:@aws-sdk/util-endpoints@3.637.0
- npm:@aws-sdk/region-config-resolver@3.614.0
- npm:@aws-sdk/util-user-agent-browser@3.609.0
- npm:@aws-sdk/util-user-agent-node@3.614.0
- npm:@aws-sdk/token-providers@3.614.0
- npm:@aws-sdk/credential-provider-web-identity@3.621.0
    at nestMappedPackages (Q:\Works\kiva\docyrus-core\node_modules\nx\src\plugins\js\lock-file\npm-parser.js:367:15)
    at nestMappedPackages (Q:\Works\kiva\docyrus-core\node_modules\nx\src\plugins\js\lock-file\npm-parser.js:373:9)
    at nestMappedPackages (Q:\Works\kiva\docyrus-core\node_modules\nx\src\plugins\js\lock-file\npm-parser.js:373:9)
    at mapSnapshots (Q:\Works\kiva\docyrus-core\node_modules\nx\src\plugins\js\lock-file\npm-parser.js:309:9)
    at stringifyNpmLockfile (Q:\Works\kiva\docyrus-core\node_modules\nx\src\plugins\js\lock-file\npm-parser.js:239:28)
    at createLockFile (Q:\Works\kiva\docyrus-core\node_modules\nx\src\plugins\js\lock-file\lock-file.js:172:58)
    at Q:\Works\kiva\docyrus-core\node_modules\@nx\webpack\src\plugins\generate-package-json-plugin.js:40:138
    at fn (Q:\Works\kiva\docyrus-core\node_modules\webpack\lib\Compilation.js:491:10)
    at _next0 (eval at create (Q:\Works\kiva\docyrus-core\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (Q:\Works\kiva\docyrus-core\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)
assets by status 2.21 MiB [big]
  asset package-lock.json 1.24 MiB [emitted] [big]
  asset main.js 992 KiB [emitted] [big] (name: main) 1 related asset
asset package.json 1.94 KiB [emitted]

webpack 5.95.0 compiled successfully (d33e5f396c04090b)
```

Webpack plugin configured like this:
```
new NxAppWebpackPlugin({
        compiler: "swc",
        main: "./src/main.ts",
        tsConfig: "./tsconfig.app.json",
        assets: [],
        memoryLimit: 2048,
        outputHashing: "none",
        optimization: false,
        generatePackageJson: true,
        sourceMap: true,
        skipTypeChecking: true,
        progress: false
})
```

**Comment by darkowic** [comment]
We are facing exactly the same issue when one of the workspace packages is referenced in an application and built with esbuild executor.

**Comment by ndcunningham** [comment]
Hi there sorry for the lack of updates,

The main issue seems to be stemming from `generatePackageJson` option. However, at this current version it is working as expected.

If your workspace is using ts solutions setup then you need to update the package.json yourself before you build as `generatePackageJson` option is not supported.

I have created a repo illustrating this: https://github.com/ndcunningham/esbuild-26434-non-ts-solution
