### ISSUE TITLE
All nx commands are failing

### ISSUE THREAD

**Issue by blaqueMani** [nrwl/nx#26469]
### Current Behavior

All nx commands are failing including `nx report`.

### Expected Behavior

`nx serve project` runs the project

### Steps to Reproduce

1. all nx commands

### Nx Report

```shell
not available
```

### Failure Logs

```shell
NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  AggregateCreateNodesError: An error occurred while processing files for the @nx/eslint/plugin plugin.
    - apps/bonisa/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - apps/bonisa-api/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - apps/bonisa-api-e2e/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - apps/bonisa-e2e/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - eslint.config.js: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
  Please open an issue with this stack trace at https://github.com/nodejs/node/issues
  
    - libs/angular/auth/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/angular/bonisa-home/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/angular/common/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/angular/flights/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/angular/login/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/angular/maps/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/bonisa-prisma-client/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/bonisa-prisma-schema/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/auth/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/auth-apple/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/auth-facebook/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/auth-google/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/auth-social/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/auth-twitter/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/config/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/file/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/logger/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/mailer/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/role/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/status/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/user/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
    - libs/nest/utils/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.
  Referenced from: 
      at createNodesFromFiles (/home/azureuser/coding/leano-aviation/node_modules/nx/src/project-graph/plugins/utils.js:58:15)
      at Array.exports.createNodesV2 (/home/azureuser/coding/leano-aviation/node_modules/@nx/eslint/src/plugins/plugin.js:92:20)
      at LoadedNxPlugin.createNodes (/home/azureuser/coding/leano-aviation/node_modules/nx/src/project-graph/plugins/internal-api.js:31:36)
      at LoadedNxPlugin.createNodes.<computed> (/home/azureuser/coding/leano-aviation/node_modules/nx/src/project-graph/plugins/internal-api.js:41:28)
      at async Promise.all (index 2)
      at processFilesAndCreateAndSerializeProjectGraph (/home/azureuser/coding/leano-aviation/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:148:43)
      at getCachedSerializedProjectGraphPromise (/home/azureuser/coding/leano-aviation/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:46:16)
      at handleRequestProjectGraph (/home/azureuser/coding/leano-aviation/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
      at handleResult (/home/azureuser/coding/leano-aviation/node_modules/nx/src/daemon/server/server.js:130:16)
      at handleMessage (/home/azureuser/coding/leano-aviation/node_modules/nx/src/daemon/server/server.js:89:9)
```

### Package Manager Version

yarn 1.22.19

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by blaqueMani** [comment]
This is the actual error:
` AggregateCreateNodesError: An error occurred while processing files for the @nx/eslint/plugin plugin.
    - apps/bonisa/eslint.config.js: Failed to load config "plugin:@ts-safeql/eslint-plugin" to extend from.`

**Comment by FrozenPandaz** [comment]
Is that `@ts-safeql/eslint-plugin` installed?

**Comment by a88zach** [comment]
repo here:  https://github.com/nrwl/nx/issues/26556
