### ISSUE TITLE
Serving apps cause npm:react-is error and restart

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nrwl/nx#26489]
### Current Behavior

Starting multiple apps via npx nx run I get an error and a restart of some running apps
```
 NX   An error occured while creating pruned lockfile
Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
To prevent the build from breaking we are returning the root lock file.
If you run `npm install --package-lock-only` in your output folder it will regenerate the correct pruned lockfile.
Original error: Target project does not exist: npm:react-is@18.2.0
Error: Target project does not exist: npm:react-is@18.2.0
    at validateCommonDependencyRules (<workspace>\node_modules\nx\src\project-graph\project-graph-builder.js:323:15)
    at validateDependency (<workspace>\node_modules\nx\src\project-graph\project-graph-builder.js:313:5)
    at ProjectGraphBuilder.addDependency (<workspace>\node_modules\nx\src\project-graph\project-graph-builder.js:190:9)
    at ProjectGraphBuilder.addStaticDependency (<workspace>\node_modules\nx\src\project-graph\project-graph-builder.js:89:14)
    at <workspace>\node_modules\nx\src\plugins\js\lock-file\project-graph-pruning.js:81:17
    at Array.forEach (<anonymous>)
    at traverseNode (<workspace>\node_modules\nx\src\plugins\js\lock-file\project-graph-pruning.js:78:36)
    at <workspace>\node_modules\nx\src\plugins\js\lock-file\project-graph-pruning.js:80:9
    at Array.forEach (<anonymous>)
    at traverseNode (<workspace>\node_modules\nx\src\plugins\js\lock-file\project-graph-pruning.js:78:36)
chunk (runtime: main) main.js (main) 103 KiB [entry]
webpack compiled successfully (c74e2fba5770bf1c)
```

### Expected Behavior

apps do not restart if some other apps are started

### Steps to Reproduce

1. npx nx run project1:serve
2. npx nx run project2:serve

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.20.2
OS     : win32-x64
npm    : 10.2.4

nx                 : 19.2.2
@nx/js             : 19.2.2
@nx/jest           : 19.2.2
@nx/linter         : 19.2.2
@nx/eslint         : 19.2.2
@nx/workspace      : 19.2.2
@nx/cypress        : 19.2.2
@nx/devkit         : 19.2.2
@nx/eslint-plugin  : 19.2.2
@nx/nest           : 19.2.2
@nx/node           : 19.2.2
@nrwl/tao          : 19.2.2
@nx/web            : 19.2.2
@nx/webpack        : 19.2.2
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
---------------------------------------
Community plugins:
@jscutlery/semver : 5.2.2
```

### Failure Logs

```shell
NX   An error occured while creating pruned lockfile
Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
To prevent the build from breaking we are returning the root lock file.
If you run `npm install --package-lock-only` in your output folder it will regenerate the correct pruned lockfile.
Original error: Target project does not exist: npm:react-is@18.2.0
Error: Target project does not exist: npm:react-is@18.2.0
    at validateCommonDependencyRules (<workspace>\node_modules\nx\src\project-graph\project-graph-builder.js:323:15)
    at validateDependency (<workspace>\node_modules\nx\src\project-graph\project-graph-builder.js:313:5)
    at ProjectGraphBuilder.addDependency (<workspace>\node_modules\nx\src\project-graph\project-graph-builder.js:190:9)
    at ProjectGraphBuilder.addStaticDependency (<workspace>\node_modules\nx\src\project-graph\project-graph-builder.js:89:14)
    at <workspace>\node_modules\nx\src\plugins\js\lock-file\project-graph-pruning.js:81:17
    at Array.forEach (<anonymous>)
    at traverseNode (<workspace>\node_modules\nx\src\plugins\js\lock-file\project-graph-pruning.js:78:36)
    at <workspace>\node_modules\nx\src\plugins\js\lock-file\project-graph-pruning.js:80:9
    at Array.forEach (<anonymous>)
    at traverseNode (<workspace>\node_modules\nx\src\plugins\js\lock-file\project-graph-pruning.js:78:36)
chunk (runtime: main) main.js (main) 103 KiB [entry]
webpack compiled successfully (c74e2fba5770bf1c)
```
```


### Package Manager Version

npm@10.2.4

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by hinogi** [comment]
#15835

**Comment by hinogi** [comment]
#15020

**Comment by hinogi** [comment]
Btw there is no react in the whole monorepo

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please provide a reproduction so we can troubleshoot the issue.
