### ISSUE TITLE
Nx not able to migrate older Angular repository (9.XX -> 10.XX)

### ISSUE THREAD

**Issue by Jay1989** [nrwl/nx#26488]
### Current Behavior

its failed at tao path since Tao path function checks latest package. even we set `NX_MIGRATE_USE_LOCAL=true` but in between migration checks latest cli package and node > 18.19.
Ideally older project runs on older node. in my case I am using node 14.15.0 since I am using Angular 9.x.x. But when We are trying to migrate Nx looking all tao, devkit,cli latest package. to install this we need to update node. if we update node then node Angular matrix will mismatch.

### Expected Behavior

it should migrate smoothly.

### Steps to Reproduce

1. nx migrate @nrwl/workspace@10.4.15
2. npm install --legacy-peer-deps
3. nx migrate --run-migrations=migrations.json

### Nx Report

```shell
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.4.15
  @nrwl/cli : 10.4.15
  @nrwl/cypress : 10.4.15
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.15
  @nrwl/linter : 10.4.15
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.4.15
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.15
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.15
  typescript : 4.0.8
```

### Failure Logs

```shell
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Node.js version v14.15.0 detected.
The Angular CLI requires a minimum Node.js version of v18.19.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.

@angular/cli migration failed, see above.
C:\CI-UI-Workspace\WOA_Workspace2\CI-UI-Workspace\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: npx tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (C:\CI-UI-Workspace\WOA_Workspace2\CI-UI-Workspace\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:84:25)
    at Object.runCommand (C:\CI-UI-Workspace\WOA_Workspace2\CI-UI-Workspace\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\CI-UI-Workspace\WOA_Workspace2\CI-UI-Workspace\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\CI-UI-Workspace\WOA_Workspace2\CI-UI-Workspace\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\CI-UI-Workspace\WOA_Workspace2\CI-UI-Workspace\node_modules\@nrwl\cli\lib\init-local.js:24:13)
    at Object.<anonymous> (C:\CI-UI-Workspace\WOA_Workspace2\CI-UI-Workspace\node_modules\@nrwl\cli\bin\nx.js:40:18)
    at Module._compile (C:\Users\sinhaj1\AppData\Roaming\npm\node_modules\@nrwl\cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 25840,
  stdout: null,
  stderr: null
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

node version : 14.15.0
npm version: 6.14.8

**Comment by leosvelperez** [comment]
Please don't create duplicated issues. You have already reported this issue at https://github.com/nrwl/nx/issues/26150. You can add any extra relevant information to the original issue, and we'll take a look.
