### ISSUE TITLE
Cannot read properties of undefined (reading 'data') in Nx 18

### ISSUE THREAD

**Issue by tachojelev** [nrwl/nx#26541]
### Current Behavior

The build was working fine with Nx `16.5.1`.
After we upgraded to Nx `18.3.5`, the build no longer works.

When building a buildable library for production, the following error is thrown:

```
NX   Cannot read properties of undefined (reading 'data')


TypeError: Cannot read properties of undefined (reading 'data')
    at getOutputsForTargetAndConfiguration (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/nx/src/tasks-runner/utils.js:118:38)
    at updateBuildableProjectPackageJsonDependencies (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/@nx/angular/node_modules/@nx/js/src/utils/buildable-libs-utils.js:209:70)
    at updatePackageJson (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/@nx/angular/src/executors/package/package.impl.js:49:94)
    at Object.next (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/@nx/angular/src/executors/package/package.impl.js:56:108)
    at /Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/operators/tap.js:20:81
    at OperatorSubscriber._this._next (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:192
    at OperatorSubscriber._this._next (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
```

### Expected Behavior

The build should pass successfully without any errors.

### Steps to Reproduce

1. Create a new Nx project/monorepo
2. Generate a new buildable library called **shared** (ideally with VS Code plugin - NX Console)
3. Build the **shared** library (`nx run shared:build:production --verbose`)

### Nx Report

```shell
Node   : 18.19.0
OS     : darwin-arm64
npm    : 10.2.3

nx (global)        : 19.2.0
nx                 : 18.3.5
@nx/js             : 18.3.5
@nx/jest           : 16.5.1
@nx/linter         : 18.3.5
@nx/eslint         : 18.3.5
@nrwl/linter       : 16.5.1
@nx/workspace      : 18.3.5
@nx/angular        : 16.5.1
@nx/cypress        : 16.5.1
@nx/devkit         : 16.5.1
@nx/eslint-plugin  : 18.3.5
@nrwl/tao          : 18.3.5
@nx/webpack        : 16.5.1
typescript         : 5.1.6
```
```


### Failure Logs

```shell
NX   Cannot read properties of undefined (reading 'data')


TypeError: Cannot read properties of undefined (reading 'data')
    at getOutputsForTargetAndConfiguration (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/nx/src/tasks-runner/utils.js:118:38)
    at updateBuildableProjectPackageJsonDependencies (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/@nx/angular/node_modules/@nx/js/src/utils/buildable-libs-utils.js:209:70)
    at updatePackageJson (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/@nx/angular/src/executors/package/package.impl.js:49:94)
    at Object.next (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/@nx/angular/src/executors/package/package.impl.js:56:108)
    at /Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/operators/tap.js:20:81
    at OperatorSubscriber._this._next (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:192
    at OperatorSubscriber._this._next (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/tacho.zhelev/Documents/git/my-monorepo/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
```
```


### Package Manager Version

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The build was working fine with Nx `16.5.1`.
After we upgraded to Nx `18.3.5`, the build no longer works.

I have seen a couple of threads that already reference the same or similar issue.
https://github.com/nrwl/nx/issues/13776
https://github.com/nrwl/nx/issues/22481

I have also tried various approaches for fixing this, but none works. 
E.g.

- Deleting `node_modules` and executing `npm install`
- Deleting `package-lock.json` and executing `npm install`

I would appreciate assistance on this, because this is quite the blocker.

**Comment by tachojelev** [comment]
Looks like it was due to inconsistencies between the @nx/* packages.
It seems the main two things that fixed it were upgrading these dependencies:
```
@nx/angular: 18.3.5
ng-packagr: 16.2.0
```

If you are doing nx migration, I would also highly recomment migrating to Nx 17 first and after that migrate to Nx 18.

Full nx report at the end:
```
Node   : 18.19.0
OS     : darwin-arm64
npm    : 10.2.3

nx (global)        : 19.2.0
nx                 : 18.3.5
@nx/js             : 18.3.5
@nx/jest           : 18.3.5
@nx/linter         : 18.3.5
@nx/eslint         : 18.3.5
@nx/workspace      : 18.3.5
@nx/angular        : 18.3.5
@nx/devkit         : 18.3.5
@nx/eslint-plugin  : 18.3.5
@nrwl/tao          : 18.3.5
@nx/web            : 18.3.5
@nx/webpack        : 18.3.5
typescript         : 5.1.6
```
