### ISSUE TITLE
Upgrade to Nx 19.1.0-19.3.0 fails on `migration-v18 from @angular/cdk` 

### ISSUE THREAD

**Issue by KeithGillette** [nrwl/nx#26557]
### Current Behavior

`nx migrate` to 19.1.0-19.3.0 from `nx@19.0.8` `@angular@17.3.11` workspace fails on `migration-v18 from @angular/cdk`.

### Expected Behavior

Migration runs without error.

### Steps to Reproduce

```
nx migrate latest
npx nx migrate --run-migrations
```

### Nx Report

```shell
Node   : 20.10.0
OS     : darwin-arm64
npm    : 10.2.3

nx             : 19.3.0
@nx/js         : 19.3.0
@nx/jest       : 19.3.0
@nx/linter     : 19.3.0
@nx/eslint     : 19.3.0
@nx/workspace  : 19.3.0
@nx/angular    : 19.3.0
@nx/cypress    : 19.3.0
@nx/devkit     : 19.3.0
@nx/node       : 19.3.0
@nrwl/tao      : 19.3.0
@nx/web        : 19.3.0
@nx/webpack    : 19.3.0
typescript     : 5.4.5
---------------------------------------
Community plugins:
apollo-angular : 7.0.0
```

### Failure Logs

```shell
NX   Failed to run migration-v18 from @angular/cdk. This workspace is NOT up to date!


 NX   Path "/node_modules/@types/../../../../typings.d.ts" is invalid.


Error: Path "/node_modules/@types/../../../../typings.d.ts" is invalid.
    at noCacheNormalize (/path/to/node_modules/@angular-devkit/core/src/virtual-fs/path.js:234:23)
    at normalize (/path/to/node_modules/@angular-devkit/core/src/virtual-fs/path.js:198:21)
    at Array.map (<anonymous>)
    at DevkitFileSystem.resolve (/path/to/node_modules/@angular/cdk/schematics/ng-update/devkit-file-system.js:28:74)
    at host.directoryExists (/path/to/node_modules/@angular/cdk/schematics/update-tool/utils/virtual-host.js:57:77)
    at directoryProbablyExists (/path/to/node_modules/typescript/lib/typescript.js:17191:42)
    at getPackageJsonInfo (/path/to/node_modules/typescript/lib/typescript.js:41221:29)
    at loadNodeModuleFromDirectory (/path/to/node_modules/typescript/lib/typescript.js:41040:47)
    at /path/to/node_modules/typescript/lib/typescript.js:39944:13
    at firstDefined (/path/to/node_modules/typescript/lib/typescript.js:79:22)
Command failed: npx nx _migrate --run-migrations --verbose

 NX   Command failed: npx nx migrate --run-migrations --verbose


Error: Command failed: npx nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runNxSync (/private/var/folders/z4/kk2jh66n10134g51dxdvybwr0000gn/T/tmp-34712-mMC6FrW9zYxW/node_modules/nx/src/utils/child-process.js:25:34)
    at runMigrations (/private/var/folders/z4/kk2jh66n10134g51dxdvybwr0000gn/T/tmp-34712-mMC6FrW9zYxW/node_modules/nx/src/command-line/migrate/migrate.js:963:39)
    at /private/var/folders/z4/kk2jh66n10134g51dxdvybwr0000gn/T/tmp-34712-mMC6FrW9zYxW/node_modules/nx/src/command-line/migrate/migrate.js:1032:19
    at async handleErrors (/private/var/folders/z4/kk2jh66n10134g51dxdvybwr0000gn/T/tmp-34712-mMC6FrW9zYxW/node_modules/nx/src/utils/params.js:9:24)
Command failed: /var/folders/z4/kk2jh66n10134g51dxdvybwr0000gn/T/tmp-34712-mMC6FrW9zYxW/node_modules/.bin/nx _migrate --run-migrations --verbose
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, the provided information is not enough to reproduce the issue. Please provide a repo where the issue can be reproduced or detailed step-by-step instructions on how to create a repo and what commands to run to reproduce the issue.
