### ISSUE TITLE
Dynamic Module federation failing when referencing a remote not in same project as host

### ISSUE THREAD

**Issue by dexster** [nrwl/nx#26551]
### Current Behavior

When serving a host with dynamic remotes it fails with this error:
`Cannot read properties of undefined (reading 'data')`

This fails in Nx 18 as well. Downgrading to Nx 17.3 works fine and the host builds and routes to all remotes

### Expected Behavior

Host should build and not fail due to a dynamic remote that is not in the same project

### GitHub Repo

https://github.com/Coly010/nx-ng-dyn-fed

### Steps to Reproduce

1. Clone your example repo (provided above)
2. Update the module-federation.manifest.json in apps/employee/src/assets to include a remote not in the same project
3. nx serve employee

### Nx Report

```shell
Node   : 20.12.2
OS     : darwin-arm64
npm    : 10.5.0

nx                 : 19.3.0
@nx/js             : 19.3.0
@nx/jest           : 19.3.0
@nx/linter         : 19.3.0
@nx/eslint         : 19.3.0
@nx/workspace      : 19.3.0
@nx/angular        : 19.3.0
@nx/devkit         : 19.3.0
@nx/eslint-plugin  : 19.3.0
@nrwl/tao          : 19.3.0
@nx/web            : 19.3.0
@nx/webpack        : 19.3.0
typescript         : 5.4.5
```

### Failure Logs

```shell
npx nx serve employee --verbose

> nx run employee:serve:development

 NX  Starting module federation dev-server for employee with 3 remotes

 NX   Cannot read properties of undefined (reading 'data')

TypeError: Cannot read properties of undefined (reading 'data')
    at /Users/..../Development/mfe19/ng-mf/node_modules/@nx/webpack/src/utils/module-federation/get-remotes-for-host.js:61:112
    at Array.map (<anonymous>)
    at getRemotes (/Users/..../Development/mfe19/ng-mf/node_modules/@nx/webpack/src/utils/module-federation/get-remotes-for-host.js:61:71)
    at moduleFederationDevServerExecutor (/Users/..../Development/mfe19/ng-mf/node_modules/@nx/angular/src/executors/module-federation-dev-server/module-federation-dev-server.impl.js:60:56)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getLastValueFromAsyncIterableIterator (/Users/..../Development/mfe19/ng-mf/node_modules/nx/src/utils/async-iterator.js:15:19)
    at iteratorToProcessStatusCode (/Users/..../Development/mfe19/ng-mf/node_modules/nx/src/command-line/run/run.js:44:29)
    at handleErrors (/Users/..../Development/mfe19/ng-mf/node_modules/nx/src/utils/params.js:9:24)
    at process.<anonymous> (/Users/..../Development/mfe19/ng-mf/node_modules/nx/bin/run-executor.js:59:28)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by robjblun** [comment]
I am having this same issue. I noticed a supposed fix made a while back [here](https://github.com/nrwl/nx/pull/17497), but the updated code in module-federation.ts never runs when executing the serve target using the @nx/angular:module-federation-dev-server executor.

**Comment by DavesCP** [comment]
I'm having this issue now: when I try to serve my host application with at least one remote app specified in the module-federation.manifest.json, it doesn't work. However, if I remove all specified remotes from the manifest and serve my host application, and then add the remote apps back into the manifest.json after the server has started, it works.

**Comment by ahillnuval** [comment]
Also running into this issue, is there a workaround?

**Comment by SpenserMG** [comment]
I am encountering the same issue described by others here. I haven't deployed to an environment yet, so am just encountering this locally. Does this issue persist when deployed or is it confined to local development?

**Comment by MaurizioCasciano** [comment]
Same error for me while using Nx 19.3.1

```
 NX   Cannot read properties of undefined (reading 'data')

TypeError: Cannot read properties of undefined (reading 'data')
    at /data/workspace/my-project/node_modules/@nx/webpack/src/utils/module-federation/get-remotes-for-host.js:61:112
    at Array.map (<anonymous>)
    at getRemotes (/data/workspace/my-project/node_modules/@nx/webpack/src/utils/module-federation/get-remotes-for-host.js:61:71)
    at moduleFederationDevServerExecutor (/data/workspace/my-project/node_modules/@nx/angular/src/executors/module-federation-dev-server/module-federation-dev-server.impl.js:60:56)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getLastValueFromAsyncIterableIterator (/data/workspace/my-project/node_modules/nx/src/utils/async-iterator.js:15:19)
    at iteratorToProcessStatusCode (/data/workspace/my-project/node_modules/nx/src/command-line/run/run.js:44:29)
    at handleErrors (/data/workspace/my-project/node_modules/nx/src/utils/params.js:9:24)
    at process.<anonymous> (/data/workspace/my-project/node_modules/nx/bin/run-executor.js:59:28)
```

The problem is that the `@nx/webpack/src/utils/module-federation/get-remotes-for-host.js` (:61:112)
https://www.npmjs.com/package/@nx/webpack?activeTab=code
https://github.com/nrwl/nx/blob/master/packages/webpack/src/utils/module-federation/get-remotes-for-host.ts#L131
 is not:

1. checking the existence of `context.projectGraph.nodes[r]` before accessing its data field:

**Comment by Coly010** [comment]
I will have a fix created for this soon, thanks everyone for raising it
