### ISSUE TITLE
the nx daemon fails to start when there is npm protocal dep with redirected resolve

### ISSUE THREAD

**Issue by franckchen** [nrwl/nx#26639]
### Current Behavior

Once dependencies include npm protocol dependencies and resolve to other dep, nx throws an error and fails to start.
even if after i install `@typefox/monaco-editor-react` dep.   nx begine failed to start.

<img width="1064" alt="image" src="https://github.com/nrwl/nx/assets/5096940/2973a8f3-d495-4bb0-9cc5-4990c4cebbc5">

error message

```
The \"nx/js/dependencies-and-lockfile\" plugin threw an error while creating dependencies: \n Target project does not exist: npm:vscode@npm:@codingame/monaco-vscode-api@5.2.0
```

### Expected Behavior

nx should work with npm protocal with redirect resolve.
work with dep like `@typefox/monaco-editor-react`

### Steps to Reproduce

1. install `@typefox/monaco-editor-react`
2. vscode nx plugin fail to start
3. All nx tasks fail to execute.

### Nx Report

```shell
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  The "nx/js/dependencies-and-lockfile" plugin threw an error while creating dependencies:
    Error: Target project does not exist: npm:vscode@npm:@codingame/monaco-vscode-api@5.2.0
        at validateCommonDependencyRules (/Users/chenfan/Documents/mycode/copilot-engine-cloud-front/node_modules/nx/src/project-graph/project-graph-builder.js:323:15)
        at validateDependency (/Users/chenfan/Documents/mycode/copilot-engine-cloud-front/node_modules/nx/src/project-graph/project-graph-builder.js:313:5)
        at /Users/chenfan/Documents/mycode/copilot-engine-cloud-front/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:214:80
        at Array.forEach (<anonymous>)
        at /Users/chenfan/Documents/mycode/copilot-engine-cloud-front/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:205:49
        at Array.forEach (<anonymous>)
        at /Users/chenfan/Documents/mycode/copilot-engine-cloud-front/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:203:72
        at Array.forEach (<anonymous>)
        at /Users/chenfan/Documents/mycode/copilot-engine-cloud-front/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:200:26
        at Array.forEach (<anonymous>)] {
  name: 'ProjectGraphError'
}

Node.js v22.3.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hi @franckchen 

Can your provide a repo with a minimal reproduction of this issue?

There is simply not enough information currently for me to understand how to get a repo into a similar state to investigate this.
