### ISSUE TITLE
nx migrate latest fails with @ngrx/signals@18.0.1

### ISSUE THREAD

**Issue by LPCmedia** [nrwl/nx#26799]
### Current Behavior

Unable to fetch migrations for @ngrx/signals@18.0.1: Command failed: yarn add -W @ngrx/signals@18.0.1
warning package.json: No license field
warning No license field
error Couldn't find any versions for "@ngrx/signals" that matches "18.0.1"

### Expected Behavior

Updates runs migrations....

### Steps to Reproduce

1.
upgrade nx from 19.3.1 to 19.4.0 with an app that has @ngrx/signals@18.0.1. 

### Nx Report

```shell
nx (global)        : 19.4.0
nx                 : 19.3.1
@nx/js             : 19.3.1
@nx/jest           : 19.3.1
@nx/linter         : 19.3.1
@nx/eslint         : 19.3.1
@nx/workspace      : 19.3.1
@nx/angular        : 19.3.1
@nx/devkit         : 19.3.1
@nrwl/devkit       : 15.9.7
@nx/esbuild        : 19.3.0
@nx/eslint-plugin  : 19.3.1
@nx/nest           : 19.3.1
@nx/node           : 19.3.1
@nrwl/tao          : 19.3.1
@nx/web            : 19.3.1
@nx/webpack        : 19.3.1
typescript         : 5.4.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/webpack/plugin
---------------------------------------
Community plugins:
@ngneat/transloco     : 5.0.7
@ngrx/component-store : 17.0.1
@ngrx/effects         : 17.0.1
@ngrx/entity          : 17.0.1
@ngrx/router-store    : 17.0.1
@ngrx/schematics      : 17.0.1
@ngrx/signals         : 17.1.1
@ngrx/store           : 17.0.1
@ngrx/store-devtools  : 17.0.1
ng-mocks              : 14.13.0
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@15.9.7
  - @nx/esbuild@19.3.0
  - @nrwl/esbuild@19.3.0

To fix this, run `nx migrate nx@19.3.1`
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by angularinterviews** [comment]
@LPCmedia This is because v18 of @ngrx/signals package is not released yet (it's still in RC)
Either you can wait for the v18 release, or if you want to proceed with the Nx update, you can temporary uninstall @ngrx/signals, proceed with the Nx update, and then manually install @ngrx/signals v18 RC.

**Comment by aahunt-cisco** [comment]
This is still a problem after the @ngrx/signals 18.0.0 release today. The `nx migrate latest` command is expecting to find 18.0.1 but that still does not exist.
<img width="949" alt="image" src="https://github.com/user-attachments/assets/22d250a8-0ec9-40e3-9e41-68b1c590c921">

**Comment by schuchard** [comment]
I'm experiencing the same results with `nx migrate latest`

```bash
npx nx migrate latest

Fetching meta data about packages.
It may take a few minutes.
Fetching nx@19.5.3
Fetching @nx/devkit@19.5.3
Fetching @nx/web@19.5.3
Fetching @nx/workspace@19.5.3
Fetching @nx/eslint-plugin@19.5.3
Fetching @nx/jest@19.5.3
Fetching @nx/storybook@19.5.3
Fetching @nx/eslint@19.5.3
Fetching @nx/js@19.5.3
Fetching @nx/playwright@19.5.3
Fetching @nx/angular@19.5.3
Fetching @ngrx/store@18.0.1
Fetching @angular/core@18.1.2
Fetching @ngrx/signals@18.0.1
Fetching @ngrx/effects@18.0.1
Unable to fetch migrations for @ngrx/signals@18.0.1: Command failed: npm install @ngrx/signals@18.0.1
```

It appears that all @ngrx deps are being installed with `18.0.1` while @ngrx/signals is currently at `18.0.0`. 

Looks like this commit https://github.com/nrwl/nx/commit/ebb42b73eb08badf614cfefa10cb91ab0583f5b8 introduced the change. 

https://github.com/nrwl/nx/issues/26985 is a duplicate.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

We're aware of the issue and looking into possible resolutions. The issue here is that the `@ngrx/signals` package version is out of sync with the rest of the NgRx packages even though is still part of the [same package update group](https://github.com/ngrx/platform/blob/main/modules/store/package.json#L29-L41).

I'll update here as soon as we make any progress.

**Comment by leosvelperez** [comment]
The NgRx team aligned the version of the `@ngrx/signals` package with the rest of the packages in version [18.0.2](https://github.com/ngrx/platform/commit/cb3f6deeb21887a288162f0cf15545b26e24a849). That fixes this issue and moving forward, there won't be a need to use the workaround mentioned in the previous comment.

I'm closing this. If you still find any issues updating this particular package when running `nx migrate latest`, please leave a message, and I'll reopen it.

**Comment by hhasenauer** [comment]
I am still having this issue even after the signal 18.0.2 release.

```
Fetching nx@19.6.0
Fetching nx@19.6.0
Fetching @nx/jest@19.6.0
Fetching @nx/js@19.6.0
Fetching @nx/eslint@19.6.0
Fetching @nx/workspace@19.6.0
Fetching @nx/devkit@19.6.0
Fetching @nx/eslint-plugin@19.6.0
Fetching @nx/angular@19.6.0
Fetching @nx/playwright@19.6.0
Fetching @nx/jest@19.6.0
Fetching @nx/js@19.6.0
Fetching @nx/eslint@19.6.0
Fetching @nx/workspace@19.6.0
Fetching @nx/devkit@19.6.0
Fetching @nx/eslint-plugin@19.6.0
Fetching @nx/angular@19.6.0
Fetching @nx/playwright@19.6.0
Fetching @angular/cdk@18.2.0
Fetching @angular/core@18.2.0
Fetching @ngrx/operators@18.0.1
Fetching @ngrx/operators@^18.0.1
Fetching @angular/cdk@~18.2.0
Fetching @angular/core@~18.2.0
Fetching @ngrx/signals@18.0.1
Unable to fetch migrations for @ngrx/signals@18.0.1: Command failed: npm install @ngrx/signals@18.0.1
npm error code ETARGET
npm error notarget No matching version found for @ngrx/signals@18.0.1.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: C:\Users\hha\AppData\Local\npm-cache\_logs\2024-08-19T07_48_51_238Z-debug-0.log
```

**Comment by hhasenauer** [comment]
Still not working. Here is the stacktrace:

```
Unable to fetch migrations for @ngrx/signals@18.0.1: Command failed: npm install @ngrx/signals@18.0.1
npm error code ETARGET
npm error notarget No matching version found for @ngrx/signals@18.0.1.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: C:\Users\hha\AppData\Local\npm-cache\_logs\2024-09-12T07_33_49_972Z-debug-0.log


 NX   The migrate command failed.


 NX   Cannot read properties of undefined (reading 'schematics')


TypeError: Cannot read properties of undefined (reading 'schematics')
    at C:\Users\hha\AppData\Local\Temp\tmp-21392-s4oTc8DStf3Q\node_modules\nx\src\command-line\migrate\migrate.js:560:24
    at async Migrator.populatePackageJsonUpdatesAndGetPackagesToCheck (C:\Users\hha\AppData\Local\Temp\tmp-21392-s4oTc8DStf3Q\node_modules\nx\src\command-line\migrate\migrate.js:147:31)
    at async Promise.all (index 0)
    at async Migrator.populatePackageJsonUpdatesAndGetPackagesToCheck (C:\Users\hha\AppData\Local\Temp\tmp-21392-s4oTc8DStf3Q\node_modules\nx\src\command-line\migrate\migrate.js:177:17)
    at async Migrator.buildPackageJsonUpdates (C:\Users\hha\AppData\Local\Temp\tmp-21392-s4oTc8DStf3Q\node_modules\nx\src\command-line\migrate\migrate.js:117:33)
    at async Promise.all (index 11)
    at async Migrator.buildPackageJsonUpdates (C:\Users\hha\AppData\Local\Temp\tmp-21392-s4oTc8DStf3Q\node_modules\nx\src\command-line\migrate\migrate.js:130:13)
    at async Migrator.migrate (C:\Users\hha\AppData\Local\Temp\tmp-21392-s4oTc8DStf3Q\node_modules\nx\src\command-line\migrate\migrate.js:83:9)
    at async generateMigrationsJsonAndUpdatePackageJson (C:\Users\hha\AppData\Local\Temp\tmp-21392-s4oTc8DStf3Q\node_modules\nx\src\command-line\migrate\migrate.js:768:78)
    at async C:\Users\hha\AppData\Local\Temp\tmp-21392-s4oTc8DStf3Q\node_modules\nx\src\command-line\migrate\migrate.js:1047:13

```

**Comment by webia1** [comment]
Can you show your `package.json` dependencies (both) ? 

For example, `@nx/linter` has been renamed to `@nx/eslint`, and that could be the issue. You should check all `nx/..` packages and their versions and remove deprecated packages. 

I suggested an alternative solution here on [Stackoverflow.](https://stackoverflow.com/questions/72799654/update-an-nx-angular-project-to-a-specific-major-version-of-angular/77861014#77861014)
