### ISSUE TITLE
NX format can't find path to prettier config

### ISSUE THREAD

**Issue by shanahobo86** [nrwl/nx#26794]
### Current Behavior

Since upgrading to nx 18.2.0, I get a strange error when trying to run nx format:write which suggests nx can't find the prettier path. I can run prettier commands directly in the cli it's just NX format that doesn't appear to work.

### Expected Behavior

nx format reads my prettier config and formats as expected

### Steps to Reproduce

1.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 21.7.3
OS     : win32-x64
npm    : 6.14.17

nx                 : 18.2.0
lerna              : 3.22.1
@nx/js             : 18.2.0
@nx/jest           : 18.2.0
@nx/linter         : 18.2.0
@nx/eslint         : 18.2.0
@nx/workspace      : 18.2.0
@nx/angular        : 18.2.0
@nx/devkit         : 18.2.0
@nx/eslint-plugin  : 18.2.0
@nrwl/tao          : 18.2.0
@nx/web            : 18.2.0
@nx/webpack        : 18.2.0
typescript         : 5.4.5
---------------------------------------
Community plugins:
@ngrx/effects        : 17.0.1
@ngrx/router-store   : 17.0.1
@ngrx/schematics     : 17.0.1
@ngrx/store          : 17.0.1
@ngrx/store-devtools : 17.0.1
ng-mocks             : 14.13.0
ngx-bootstrap        : 11.0.2
ngx-toastr           : 16.2.0
```

### Failure Logs

```shell
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at Object.join (node:path:433:7)
    at getPrettierPath (C:\Users\________\node_modules\nx\src\command-line\format\format.js:154:33)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at Mod.require (C:\Users\________\node_modules\nx\bin\init-local.js:157:36)
    at require (node:internal/modules/helpers:179:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
This is potentially related: https://github.com/nrwl/nx/pull/18672

What version of prettier do you have installed?

**Comment by shanahobo86** [comment]
Hi @AgentEnder, I was originally on 2.6.2 when I saw this issue. Subsequently bumped to the latest (3.3.2) but still seeing the same.

**Comment by AgentEnder** [comment]
Interesting, @shanahobo86  could you attach a repository showing this behavior? I've not been able to reproduce.
