### ISSUE TITLE
NX Failed to create a workspace

### ISSUE THREAD

**Issue by pt1c** [nrwl/nx#26805]
### Current Behavior

Trying to create NX workspace< and then failure:

> `
> $ npx create-nx-workspace@latest
> 
>  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]
> 
> √ Where would you like to create your workspace? · project
> √ Which stack do you want to use? · node
> √ What framework should be used? · nest
> √ Integrated monorepo, or standalone project? · integrated
> √ Application name · account
> √ Would you like to generate a Dockerfile? [https://docs.docker.com/] · No
> √ Do you want Nx Cloud to make your CI fast? · skip
> 
>  NX   Creating your v19.4.0 workspace.
> 
> ✔ Installing dependencies with npm
> ✖ Creating your workspace in project
> 
>  NX   Failed to create a workspace.
> 
> Error: npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> `

### Expected Behavior

workspace successfully created

### Steps to Reproduce

1. npx create-nx-workspace@latest

### Nx Report

```shell
Node   : 20.15.0
OS     : win32-x64
npm    : 10.8.1

nx             : 19.4.0
@nx/js         : 19.4.0
@nx/jest       : 19.4.0
@nx/linter     : 19.4.0
@nx/eslint     : 19.4.0
@nx/workspace  : 19.4.0
@nx/devkit     : 19.4.0
@nx/node       : 19.4.0
@nrwl/tao      : 19.4.0
typescript     : 5.4.5
```

### Package Manager Version

9.2.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by GestHairHome** [comment]
Exactly same issue

**Comment by AgentEnder** [comment]
Hello 👋. Few questions, as this isn't reproducable.

- Did this generate a new folder containing a package.json?
- What other files are present?
- If you try to run install do you get an error?
- If you try to run a generator do you get an error?

**Comment by pt1c** [comment]
Hello,

> * Did this generate a new folder containing a package.json?

Yes


> * What other files are present?

![image](https://github.com/nrwl/nx/assets/3617051/eeab2e95-e05c-4ef3-b7ed-3312714a6e6a)


> * If you try to run install do you get an error?

No.

```
$ cd project
$ npm i

added 57 packages, changed 2 packages, and audited 554 packages in 4s

63 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```


> * If you try to run a generator do you get an error?

Yes

```
$ npx nx g @nx/nest:module --verbose

 NX   Unable to resolve @nx/nest:module.

Cannot find module '@nx/nest/package.json'
Require stack:
- D:\test\project\node_modules\nx\src\utils\package-json.js
- D:\test\project\node_modules\nx\src\project-graph\plugins\loader.js
- D:\test\project\node_modules\nx\src\project-graph\plugins\index.js
- D:\test\project\node_modules\nx\src\command-line\run\executor-utils.js
- D:\test\project\node_modules\nx\src\devkit-internals.js
- D:\test\project\node_modules\nx\src\utils\assert-workspace-validity.js
- D:\test\project\node_modules\nx\src\project-graph\build-project-graph.js
- D:\test\project\node_modules\nx\src\project-graph\project-graph.js
- D:\test\project\node_modules\nx\src\project-graph\file-utils.js
- D:\test\project\node_modules\nx\src\utils\package-manager.js
- D:\test\project\node_modules\nx\src\utils\child-process.js
- D:\test\project\node_modules\nx\src\command-line\migrate\command-object.js
- D:\test\project\node_modules\nx\src\command-line\nx-commands.js
- D:\test\project\node_modules\nx\bin\init-local.js
- D:\test\project\node_modules\nx\bin\nx.js

Error: Unable to resolve @nx/nest:module.
Cannot find module '@nx/nest/package.json'
Require stack:
- D:\test\project\node_modules\nx\src\utils\package-json.js
- D:\test\project\node_modules\nx\src\project-graph\plugins\loader.js
- D:\test\project\node_modules\nx\src\project-graph\plugins\index.js
- D:\test\project\node_modules\nx\src\command-line\run\executor-utils.js
- D:\test\project\node_modules\nx\src\devkit-internals.js
- D:\test\project\node_modules\nx\src\utils\assert-workspace-validity.js
- D:\test\project\node_modules\nx\src\project-graph\build-project-graph.js
- D:\test\project\node_modules\nx\src\project-graph\project-graph.js
- D:\test\project\node_modules\nx\src\project-graph\file-utils.js
- D:\test\project\node_modules\nx\src\utils\package-manager.js
- D:\test\project\node_modules\nx\src\utils\child-process.js
- D:\test\project\node_modules\nx\src\command-line\migrate\command-object.js
- D:\test\project\node_modules\nx\src\command-line\nx-commands.js
- D:\test\project\node_modules\nx\bin\init-local.js
- D:\test\project\node_modules\nx\bin\nx.js
    at getGeneratorInformation (D:\test\project\node_modules\nx\src\command-line\generate\generator-utils.js:39:15)
    at D:\test\project\node_modules\nx\src\command-line\generate\generate.js:218:248
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (D:\test\project\node_modules\nx\src\utils\params.js:9:24)
    at async Object.handler (D:\test\project\node_modules\nx\src\command-line\generate\command-object.js:13:22)
```

**Comment by vqhdev** [comment]
Encounter the same error
![image](https://github.com/nrwl/nx/assets/133771786/4980fe5b-1e45-40aa-b4c1-7c93f113b793)
![image](https://github.com/nrwl/nx/assets/133771786/0e053f9e-56cb-4c73-8061-712c2f84bbd0)

- Windows 10
- NodeJs 20.15.1
- NPM 10.7.0

**Comment by pt1c** [comment]
still have a problem

**Comment by pt1c** [comment]
> This issue has been automatically marked as stale because more information has not been provided within 7 days. It will be closed in 21 days if no information is provided. If information has been provided, please reply to keep it active. Thanks for being a part of the Nx community! 🙏

still have a problem

![image](https://github.com/user-attachments/assets/c81a9469-0dd4-45b1-96bc-2a7acd591221)

**Comment by resulturan** [comment]
I have the same issue...

![image](https://github.com/user-attachments/assets/0696a119-d7b3-4510-9aea-d936d2828d17)
![image](https://github.com/user-attachments/assets/7d114373-f06d-4207-a21d-0eb49f94900f)

**Comment by nmgix** [comment]
what worked for me

√ Which stack do you want to use? · node
√ What framework should be used? · none
√ Integrated monorepo, or standalone project? · integrated

later

nx add @nx/nest
nx g @nx/nest:app <<app-name>>

**Comment by PatrickSys** [comment]
![image](https://github.com/user-attachments/assets/028e2ddf-8962-41c7-8868-9bdb9a4f2f7d)

**Comment by jorjenava** [comment]
I'm having the same issue on Pop!_OS 22.04.
 
 I ran this command from the [@nx/react-native docs](https://nx.dev/nx-api/react-native):
`npx create-nx-workspace@latest your-workspace-name --preset=react-native --appName=your-app-name`

I received this output:
```
 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Test runner to use for end to end (E2E) tests · playwright
✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · skip

 NX   Creating your v19.7.3 workspace.

✔ Installing dependencies with npm
✖ Creating your workspace in your-workspace-name

 NX   Failed to create a workspace.

Error: npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.1.4: Glob versions prior to v9 are no longer supported
```

Output of `npx nx report`:
```
 NX   Report complete - copy this into the issue template

Node           : 20.17.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.8.2

nx                 : 19.7.3
@nx/js             : 19.7.3
@nx/jest           : 19.7.3
@nx/linter         : 19.7.3
@nx/eslint         : 19.7.3
@nx/workspace      : 19.7.3
@nx/devkit         : 19.7.3
@nx/eslint-plugin  : 19.7.3
@nx/react          : 19.7.3
@nx/react-native   : 19.7.3
@nrwl/tao          : 19.7.3
@nx/web            : 19.7.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/react-native/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

Output of `cd your-workspace-name && tree -I node_modules` (node_modules excluded for brevity):
```
.
├── .editorconfig
├── .gitignore
├── .nx
│   └── workspace-data
│       ├── d
│       │   └── daemon.log
│       ├── eslint-4393011795395336301.hash
│       ├── file-map.json
│       ├── lockfile.hash
│       ├── nx_files.nxt
│       ├── parsed-lock-file.json
│       └── project-graph.json
├── nx.json
├── package.json
├── package-lock.json
├── README.md
└── .vscode
    └── extensions.json

4 directories, 14 files
```

Output of `npm install`:
```
added 89 packages, removed 2 packages, changed 4 packages, and audited 887 packages in 3s

104 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I was able to run a generator without error but there are some warnings:
`npx nx g @nx/react-native:library --directory=packages/mylib`

Output:
```
                                                                                                                                                                                                                                                                                                                              
 NX  Generating @nx/react-native:library                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                               
✔ What name would you like to use for the library? · mylib                                                                                                                                                                                                                                                                     
✔ What should be the project name and where should it be generated? · mylib @ packages/mylib                                                                                                                                                                                                                                   
Fetching prettier...                                                                                                                                                                                                                                                                                                           
CREATE tsconfig.base.json                                                                                                                                                                                                                                                                                                      
CREATE .prettierrc                                                                                                                                                                                                                                                                                                             
CREATE .prettierignore                                                                                                                                                                                                                                                                                                         
UPDATE .vscode/extensions.json                                                                                                                                                                                                                                                                                                 
UPDATE package.json                                                                                                                                                                                                                                                                                                            
UPDATE .gitignore                                                                                                                                                                                                                                                                                                              
UPDATE nx.json                                                                                                                                                                                                                                                                                                                 
CREATE packages/mylib/project.json     
CREATE packages/mylib/.babelrc.js       
CREATE packages/mylib/README.md                                                                                                                                                                                                                                                                                                
CREATE packages/mylib/src/index.ts                                                                                                                                                                                                                                                                                             
CREATE packages/mylib/tsconfig.json                                                                                                                                                                                                                                                                                            
CREATE packages/mylib/tsconfig.lib.json                                                                                                                                                                                                                                                                                        
CREATE .eslintrc.json                                                                                                                                                                                                                                                                                                          
CREATE .eslintignore                                                                                                                                           
CREATE packages/mylib/.eslintrc.json                                                                                                                           
CREATE jest.preset.js                                                                                                                                          
CREATE jest.config.ts                                                                                                                                                                                                                                                                                                          
CREATE packages/mylib/jest.config.ts                                                                                                                                                                                                                                                                                           
CREATE packages/mylib/src/test-setup.ts                                                                                                                        
CREATE packages/mylib/tsconfig.spec.json
npm warn deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm warn deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated @babel/plugin-proposal-logical-assignment-operators@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm warn deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm warn deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm warn deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead

added 503 packages, removed 44 packages, changed 11 packages, and audited 1346 packages in 14s

176 packages are looking for funding
  run `npm fund` for details


found 0 vulnerabilities

 NX   👀 View Details of mylib

Run "nx show project mylib" to view details about this project.
```

tree after `npm install` and generating mylib:
```
.
├── .editorconfig
├── .eslintignore
├── .eslintrc.json
├── .gitignore
├── jest.config.ts
├── jest.preset.js
├── .nx
│   └── workspace-data
│       ├── d
│       │   ├── daemon.log
│       │   └── server-process.json
│       ├── eslint-4393011795395336301.hash
│       ├── file-map.json
│       ├── jest-7930610538513362720.hash
│       ├── lockfile.hash
│       ├── nx_files.nxt
│       ├── parsed-lock-file.json
│       ├── project-graph.json
│       └── react-native.hash
├── nx.json
├── package.json
├── package-lock.json
├── packages
│   └── mylib
│       ├── .babelrc.js
│       ├── .eslintrc.json
│       ├── jest.config.ts
│       ├── project.json
│       ├── README.md
│       ├── src
│       │   ├── index.ts
│       │   └── test-setup.ts
│       ├── tsconfig.json
│       ├── tsconfig.lib.json
│       └── tsconfig.spec.json
├── .prettierignore
├── .prettierrc
├── README.md
├── tsconfig.base.json
└── .vscode
    └── extensions.json

7 directories, 34 files
```

Output of `cat /etc/os-release`
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```


Generated files minus node_modules (github upload size limited to 25mb)
[your-workspace-name.zip](https://github.com/user-attachments/files/17038332/your-workspace-name.zip)

**Comment by jorjenava** [comment]
I found this similar [issue](https://github.com/nrwl/nx/issues/22760) and saw that @fedevela encountered the same problem and got around it by skipping the E2E runner selection. Choosing either playwright or cypress cause the exact same output as before. Choosing none allows the workspace to be created normally.

**Comment by pi-314** [comment]
Cannot confirm that 😞 Skipping the E2E runner doesn't solve the problem.
```
npm: '10.8.3'
node: '20.17.0'

❯ npx create-nx-workspace src/main/frontend

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Which stack do you want to use? · angular
✔ Integrated monorepo, or standalone project? · standalone
✔ Which bundler would you like to use? · esbuild
✔ Default stylesheet format · css
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
✔ Test runner to use for end to end (E2E) tests · none
✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · skip

 NX   Creating your v19.7.4 workspace.

✔ Installing dependencies with npm
✖ Creating your workspace in src/main/frontend

 NX   Failed to create a workspace.

Error: npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

**Comment by pt1c** [comment]
I stopped using nx because I got tired of fighting nx-bugs instead of developing.
It was a breath of fresh air when I gave up nx

**Comment by anujmv** [comment]
Same issue

**Comment by Banzaci** [comment]
Same issue

**Comment by daviaugustos** [comment]
same issue

**Comment by Aravinthansankar977** [comment]
same issue any fix for this

**Comment by Aravinthansankar977** [comment]
### Issue with Nx Workspace for React Native App

I encountered an issue while setting up an Nx workspace for a React Native app. The problem arises when selecting a test runner for end-to-end (E2E) tests during the setup process.

#### Solution:
- **Skip the E2E Test Runner**: If you skip the selection of a test runner for E2E tests, the workspace and app are created without any issues.
  
- **Alternative**: You can also downgrade to **Nx version 18**, which works without this problem.

By following either of these solutions, you should be able to create your Nx workspace for a React Native app successfully.

---

This version should be clear for others facing the same issue!

**Comment by impankajnegi** [comment]
I Spent a whole day to find the fix but finally moved to Touborepo. Now was able to setup within 5 minutes.

**Comment by hoangngk** [comment]
Same issue

**Comment by hoangngk** [comment]
worked for me after running `sudo chown -R 501:20 "[your npm location]/.npm"`

**Comment by hassankhan** [comment]
I had this issue because I didn't have Node globally installed, only Bun.

**Comment by xiongemi** [comment]
i think there are 2 issues:
- for node, I tried on macos and windows. i could no longer reproduce this issue. i suspect it might be fixed in https://github.com/nrwl/nx/pull/27702/files. also, as mentioned above, it also might be caused by node not installed globally
- for react native, I submit a pr to fix it https://github.com/nrwl/nx/issues/26805

**Comment by vineet-innovyt** [comment]
NX support is so poor

**Comment by egexagc** [comment]
nothing fixed. still reproduced in 20.1.3 
![Image](https://github.com/user-attachments/assets/4b1c9fef-a923-4764-814c-872ed1d57344)

**Comment by mobiusy** [comment]
Still reproduced in v20.3.0
![Image](https://github.com/user-attachments/assets/a9beb3ba-58f3-4890-b67e-70943f44103e)

**Comment by kallekulp** [comment]
Same issue here with pnpm or npm. this is the error log

npx create-nx-workspace --pm pnpm --verbose

Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 376, reused 364, downloaded 0, added 0
 WARN  2 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6
Packages: +510
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 520, reused 510, downloaded 0, added 199
Progress: resolved 520, reused 510, downloaded 0, added 510, done

devDependencies:
+ @nx/node 20.3.2
+ @nx/workspace 20.3.2
+ nx 20.3.2

Done in 2.7s

 NX  Generating @nx/workspace:preset

Fetching prettier...
Fetching @nx/nest...
Fetching @nx/webpack...

 NX   generateFiles: No files found in "/Users/user/AppData/Local/Temp/tmp-18864-kfKB5uyXSkzM/node_modules/.pnpm/@nx+nest@20.3.2_@babel+traverse@7.26.5_@types+node@22.10.7_@zkochan+js-yaml@0.0.7_eslint@9.18_jgfyq5q745jtaqjvvffjfqazce/node_modules/@nx/nest/src/generators/application/files". Are you sure you specified the correct path?

Pass --verbose to see the stacktrace.


 NX   Workspace creation failed, see above.

Error: Workspace creation failed, see above.
    at ChildProcess.<anonymous> (C:\Users\user\AppData\Local\Temp\tmp-42672-W4pEePpKwDVD\node_modules\.pnpm\@nx+workspace@20.3.2\node_modules\@nx\workspace\src\generators\new\generate-preset.js:45:24)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

**Comment by IsaTalantbek** [comment]
I don’t know if this will help, but when I changed the project drive from D to C, everything worked out

**Comment by nikopol-fw** [comment]
It seems that the problem arises because of the `jest` v29.7.0 package, which adds `nx`. Despite the fact that this is the latest version, it has an outdated `glob` package in its dependencies, which causes a warning and, as a result, an error.

You should try to create a workspace by specifying the preset option manually, for example: `npx create-nx-workspace@latest project --preset=nest`. Presets can be selected here https://nx.dev/nx-api/nx/documents/create-nx-workspace#presets

In my case, it helped to ignore warnings
