### ISSUE TITLE
After upgrading to Nx 17.2.8, the generators have issues in import 

### ISSUE THREAD

**Issue by shashankvivek** [nrwl/nx#26809]
### Current Behavior

I migrated my project to Nx 17.2.8 from Nx 11 , but I never checked for generators. 

How when I running my custom generators to create a new app, I am having 2 errors which I cant find over internet.

```
import { Linter } from '@nx/workspace';

interface Schema {
  name: string;
}

export default async function (tree: Tree, schema: Schema) {
  await applicationGenerator(tree, {
    name: `qontrol-${schema.name}`,
    prefix: schema.name,
    tags: `scope:qontrol-${schema.name}`,
    routing: false,
    strict: false,
    linter: Linter.EsLint,  // this line gives an error
    style: `scss`,
  });
}
```

here I get 

> Type 'Linter.EsLint' is not assignable to type 'Linter'
> schema.d.ts(20, 3): The expected type comes from property 'linter' which is declared here on type `'Partial<Schema>'`

The second generator is

```
import { stringUtils } from '@nx/workspace';

interface Schema {
  name: string;
  clientDisplayName: string;
}

export default async function (host: Tree, schema: Schema) {
  const libraryRoot = readProjectConfiguration(host, schema.name).sourceRoot;
  if (!libraryRoot) {
    throw new Error('File path not found');
  }

  // =========================== Creation and Updation in client lib =============================
  //Generate component
  generateFiles(
    host,
    joinPathFragments(__dirname, './files/lib/component'),
    libraryRoot + '/lib',
    {
      name: schema.name,
      capitalize: stringUtils.capitalize,
    },
  );
}

```

Here I get

> Module '"@nx/workspace"' has no exported member 'stringUtils'

How to fix them ?

### Expected Behavior

The client should get created as a new app

### Steps to Reproduce

1. npx nx generate @qoncept-ui/workspace-plugin:scaffold-client --name=abc --clientDisplayName="ABC" --no-interactive --verbose

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node   : 18.13.0
   OS     : win32-x64
   npm    : 8.19.3

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/plugin         : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ngrx/component-store                  : 17.0.1
   @syncfusion/ej2-angular-buttons        : 24.1.41
   @syncfusion/ej2-angular-calendars      : 24.1.44
   @syncfusion/ej2-angular-charts         : 24.1.44
   @syncfusion/ej2-angular-dropdowns      : 24.1.44
   @syncfusion/ej2-angular-grids          : 24.1.44
   @syncfusion/ej2-angular-inputs         : 24.1.41
   @syncfusion/ej2-angular-kanban         : 24.1.43
   @syncfusion/ej2-angular-navigations    : 24.1.41
   @syncfusion/ej2-angular-notifications  : 24.1.41
   @syncfusion/ej2-angular-popups         : 24.1.44
   @syncfusion/ej2-angular-richtexteditor : 24.1.43
   @syncfusion/ej2-angular-schedule       : 24.1.41
   @syncfusion/ej2-angular-splitbuttons   : 24.1.44
   ngx-daterangepicker-material           : 6.0.4
   ---------------------------------------
   Local workspace plugins:
         @qoncept-ui/workspace-plugin
```

### Failure Logs

```shell
TypeError: Cannot read properties of undefined (reading 'capitalize')
    at D:\q_repo\qontrol-ui\tools\workspace-plugin\src\generators\setup-client\index.ts:29:31
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\q_repo\qontrol-ui\node_modules\@swc\helpers\cjs\_async_to_generator.cjs:5:28)
    at _next (D:\q_repo\qontrol-ui\node_modules\@swc\helpers\cjs\_async_to_generator.cjs:23:17)
    at D:\q_repo\qontrol-ui\node_modules\@swc\helpers\cjs\_async_to_generator.cjs:30:13
    at new Promise (<anonymous>)
    at D:\q_repo\qontrol-ui\node_modules\@swc\helpers\cjs\_async_to_generator.cjs:19:16
    at _ref (D:\q_repo\qontrol-ui\tools\workspace-plugin\src\generators\setup-client\index.ts:66:17)
    at _default (D:\q_repo\qontrol-ui\tools\workspace-plugin\src\generators\setup-client\index.ts:12:17)
    at D:\q_repo\qontrol-ui\tools\workspace-plugin\src\generators\scaffold-client\index.ts:14:20


-----------------------

TypeError: Cannot read properties of undefined (reading 'EsLint')
    at D:\q_repo\qontrol-ui\tools\workspace-plugin\src\generators\generate-client\index.ts:16:20
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\q_repo\qontrol-ui\node_modules\@swc\helpers\cjs\_async_to_generator.cjs:5:28)
    at _next (D:\q_repo\qontrol-ui\node_modules\@swc\helpers\cjs\_async_to_generator.cjs:23:17)
    at D:\q_repo\qontrol-ui\node_modules\@swc\helpers\cjs\_async_to_generator.cjs:30:13
    at new Promise (<anonymous>)
    at D:\q_repo\qontrol-ui\node_modules\@swc\helpers\cjs\_async_to_generator.cjs:19:16
    at _ref (D:\q_repo\qontrol-ui\tools\workspace-plugin\src\generators\generate-client\index.ts:36:17)
    at _default (D:\q_repo\qontrol-ui\tools\workspace-plugin\src\generators\generate-client\index.ts:13:17)
    at D:\q_repo\qontrol-ui\tools\workspace-plugin\src\generators\scaffold-client\index.ts:12:23
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by shashankvivek** [comment]
I fixed stringUtil error by creating my own capitalize function:

```
const capitalize = (clientName: string) => clientName.charAt(0).toUpperCase() + clientName.slice(1).toLowerCase();
```

but not sure about the linter change even now

**Comment by AgentEnder** [comment]
Linter moved to be exported from @nx/eslint, sorry this was not caught in a migration.
