### ISSUE TITLE
An error occurred while processing files for the @nx/jest/plugin plugin.

### ISSUE THREAD

**Issue by pipech** [nrwl/nx#26823]
### Current Behavior

Various `nx` command error on fresh install using `pnpm dlx create-nx-workspace --pm pnpm`

It failed on
- `pnpm dlx nx report`
- `pnpm dlx nx g @nx/eslint:convert-to-flat-config`

### Expected Behavior

Able to run `nx` command.

### Steps to Reproduce

1. On windows x64, use `pnpm dlx create-nx-workspace --pm pnpm`.
2. It'll failed to create workspace.
3. Manually run `pnpm dlx nx init`.
4. Run `pnpm dlx nx report`.
5. Expect an error.

### Nx Report

```shell
nx able to generate report after comment out this line.
`'^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nx/react/plugins/jest',`

---

Node   : 20.10.0
OS     : win32-x64
pnpm   : 9.4.0

nx (global)        : 19.4.0
nx                 : 19.4.0
@nx/js             : 19.4.0
@nx/jest           : 19.4.0
@nx/eslint         : 19.4.0
@nx/workspace      : 19.4.0
@nx/devkit         : 19.4.0
@nx/eslint-plugin  : 19.4.0
@nx/next           : 19.4.0
@nx/playwright     : 19.4.0
@nrwl/tao          : 19.4.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/playwright/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
NX   An error occurred while processing files for the @nx/jest/plugin plugin.
  - apps/storefront/jest.config.ts: ● Validation Error:

  Module @nx/react/plugins/jest in the transform option was not found.
         <rootDir> is: D:\panichco\apps\storefront

  Configuration Documentation:
  https://jestjs.io/docs/configuration


AggregateCreateNodesError: An error occurred while processing files for the @nx/jest/plugin plugin.
  - apps/storefront/jest.config.ts: ● Validation Error:

  Module @nx/react/plugins/jest in the transform option was not found.
         <rootDir> is: D:\panichco\apps\storefront

  Configuration Documentation:
  https://jestjs.io/docs/configuration

    at createNodesFromFiles (D:\panichco\node_modules\.pnpm\nx@19.4.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_notkuqohdjcatyfh2jltqnecbq\node_modules\nx\src\project-graph\plugins\utils.js:58:15)
    at Array.exports.createNodesV2 (D:\panichco\node_modules\.pnpm\@nx+jest@19.4.0_@babel+traverse@7.24.7_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers_nl2ege6t7uudjeogkffvbi63zy\node_modules\@nx\jest\src\plugins\plugin.js:32:20)
    at LoadedNxPlugin.createNodes (D:\panichco\node_modules\.pnpm\nx@19.4.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_notkuqohdjcatyfh2jltqnecbq\node_modules\nx\src\project-graph\plugins\internal-api.js:31:36)
    at LoadedNxPlugin.createNodes.<computed> (D:\panichco\node_modules\.pnpm\nx@19.4.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_notkuqohdjcatyfh2jltqnecbq\node_modules\nx\src\project-graph\plugins\internal-api.js:41:28)
    at async Promise.all (index 4)
    at processFilesAndCreateAndSerializeProjectGraph (D:\panichco\node_modules\.pnpm\nx@19.4.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_notkuqohdjcatyfh2jltqnecbq\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:148:43)
    at Timeout._onTimeout (D:\panichco\node_modules\.pnpm\nx@19.4.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_notkuqohdjcatyfh2jltqnecbq\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:85:13)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Base on this comment https://github.com/nrwl/nx/issues/22598#issuecomment-2072415781, I believed that `@nx/react` should be install along with `@nx/next`, but it's missing in fresh install (using `pnpm`).

```nx.json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "defaultBase": "master",
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/eslint.config.js",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/src/test-setup.[jt]s",
      "!{projectRoot}/test-setup.[jt]s"
    ],
    "sharedGlobals": []
  },
  "plugins": [
    {
      "plugin": "@nx/next/plugin",
      "options": {
        "startTargetName": "start",
        "buildTargetName": "build",
        "devTargetName": "dev",
        "serveStaticTargetName": "serve-static"
      }
    },
    {
      "plugin": "@nx/playwright/plugin",
      "options": {
        "targetName": "e2e"
      }
    },
    {
      "plugin": "@nx/eslint/plugin",
      "options": {
        "targetName": "lint"
      }
    },
    {
      "plugin": "@nx/jest/plugin",
      "options": {
        "targetName": "test"
      }
    }
  ],
  "generators": {
    "@nx/next": {
      "application": {
        "style": "tailwind",
        "linter": "eslint"
      }
    }
  }
}
```

Many people also encounter this problems (with `pnpm`).
- https://github.com/nrwl/nx/issues/22598
- https://github.com/nrwl/nx/issues/22774

---

To fix the issues

1. Comment out `'^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nx/react/plugins/jest',` this line
2. `pnpm nx add @nx/react`
3. Fixed!

**Comment by dexxiez** [comment]
Can confirm this is still an issue as of `v20.0.9`, brand new workspace missing `@nx/react`. 

Creation answers if interested:
```
❯ pnpm dlx create-nx-workspace xyz
Packages: +56
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 56, reused 55, downloaded 1, added 56, done

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Which stack do you want to use? · react
✔ What framework would you like to use? · nextjs
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · abc
✔ Would you like to use the App Router (recommended)? · Yes
✔ Would you like to use the src/ directory? · Yes
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Default stylesheet format · tailwind
✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · skip

 NX   Creating your v20.0.9 workspace.

✔ Installing dependencies with pnpm
✔ Successfully created the workspace: xyz.
```

```
❯ nx --version
Nx Version:
- Local: v20.0.9
- Global: v20.0.9
```

**Comment by joelpelaez** [comment]
It's also present in `v20.4.6`, nx command are working on start because nx daemon is started by npm instance of pnpm, after that it not works because `@nx/react` and `@next/eslint-plugin-next` are not present in top level dependencies.

nx report
```
Node           : 22.14.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 10.5.0

nx (global)        : 20.4.6
nx                 : 20.4.6
@nx/js             : 20.4.6
@nx/jest           : 20.4.6
@nx/eslint         : 20.4.6
@nx/workspace      : 20.4.6
@nx/devkit         : 20.4.6
@nx/eslint-plugin  : 20.4.6
@nx/next           : 20.4.6
@nx/playwright     : 20.4.6
typescript         : 5.7.3
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/playwright/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

Execute `nx add @nx/react` and `nx add @next/eslint-next-plugin` allows nx commands to work again.

Working nx report
```
Node           : 22.14.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 10.5.0

nx (global)        : 20.4.6
nx                 : 20.4.6
@nx/js             : 20.4.6
@nx/jest           : 20.4.6
@nx/eslint         : 20.4.6
@nx/workspace      : 20.4.6
@nx/devkit         : 20.4.6
@nx/eslint-plugin  : 20.4.6
@nx/next           : 20.4.6
@nx/playwright     : 20.4.6
@nx/react          : 20.4.6
typescript         : 5.7.3
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/playwright/plugin
@nx/eslint/plugin
@nx/jest/plugin
```
