### ISSUE TITLE
@nx/expo Error: Cannot resolve realm

### ISSUE THREAD

**Issue by cnhongwei** [nrwl/nx#26853]
### Current Behavior

I created an expo project and a lib using nx, and added the `realm` dependency. When I run `yarn nx build nx-expo-problem --profile=preview --platform=android --local`, if the realm dependency is in the project, the build is successful. However, if the realm dependency is in the lib, the build encounters the error "Error: Cannot resolve realm".

### Expected Behavior

It is possible to use Realm normally in the lib.

### GitHub Repo

https://github.com/cnhongwei/nx-expo-problem

### Steps to Reproduce

1. clone this repo.
2. `yarn`
3. `yarn nx build nx-expo-problem --profile=preview --platform=android --local`

### Nx Report

```shell
Node   : 20.15.0
OS     : darwin-arm64
yarn   : 1.22.22

nx                 : 19.4.1
@nx/js             : 19.4.1
@nx/jest           : 19.4.1
@nx/linter         : 19.4.1
@nx/eslint         : 19.4.1
@nx/workspace      : 19.4.1
@nx/detox          : 19.4.1
@nx/devkit         : 19.4.1
@nx/eslint-plugin  : 19.4.1
@nx/expo           : 19.4.1
@nx/react          : 19.4.1
@nrwl/tao          : 19.4.1
@nx/web            : 19.4.1
@nx/webpack        : 19.4.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/expo/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/detox/plugin
```

### Failure Logs

```shell
[RUN_GRADLEW] Starting Metro Bundler
[RUN_GRADLEW] warning: Bundler cache is empty, rebuilding (this may take a minute)
[RUN_GRADLEW] Android Bundling failed 4121ms index.js (598 modules)
[RUN_GRADLEW] Error: Cannot resolve realm
[RUN_GRADLEW] Error: Cannot resolve realm
[RUN_GRADLEW]     at firstResolver (/private/var/folders/8l/xq7fclpn08gbjsqtc4r4f0wm0000gn/T/eas-build-local-nodejs/d22113e2-383c-407c-ad7c-7b1765f059b6/build/apps/nx-expo-problem/node_modules/@nx/expo/plugins/metro-resolver.js:33:15)
[RUN_GRADLEW]     at firstResolver (/private/var/folders/8l/xq7fclpn08gbjsqtc4r4f0wm0000gn/T/eas-build-local-nodejs/d22113e2-383c-407c-ad7c-7b1765f059b6/build/apps/nx-expo-problem/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:108:16)
[RUN_GRADLEW]     at resolveRequest (/private/var/folders/8l/xq7fclpn08gbjsqtc4r4f0wm0000gn/T/eas-build-local-nodejs/d22113e2-383c-407c-ad7c-7b1765f059b6/build/apps/nx-expo-problem/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:137:16)
[RUN_GRADLEW]     at Object.resolve (/private/var/folders/8l/xq7fclpn08gbjsqtc4r4f0wm0000gn/T/eas-build-local-nodejs/d22113e2-383c-407c-ad7c-7b1765f059b6/build/apps/nx-expo-problem/node_modules/metro-resolver/src/resolve.js:32:12)
[RUN_GRADLEW]     at ModuleResolver.resolveDependency (/private/var/folders/8l/xq7fclpn08gbjsqtc4r4f0wm0000gn/T/eas-build-local-nodejs/d22113e2-383c-407c-ad7c-7b1765f059b6/build/apps/nx-expo-problem/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:73:31)
[RUN_GRADLEW]     at DependencyGraph.resolveDependency (/private/var/folders/8l/xq7fclpn08gbjsqtc4r4f0wm0000gn/T/eas-build-local-nodejs/d22113e2-383c-407c-ad7c-7b1765f059b6/build/apps/nx-expo-problem/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
[RUN_GRADLEW]     at /private/var/folders/8l/xq7fclpn08gbjsqtc4r4f0wm0000gn/T/eas-build-local-nodejs/d22113e2-383c-407c-ad7c-7b1765f059b6/build/apps/nx-expo-problem/node_modules/metro/src/lib/transformHelpers.js:156:21
[RUN_GRADLEW]     at resolveDependencies (/private/var/folders/8l/xq7fclpn08gbjsqtc4r4f0wm0000gn/T/eas-build-local-nodejs/d22113e2-383c-407c-ad7c-7b1765f059b6/build/apps/nx-expo-problem/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
[RUN_GRADLEW]     at visit (/private/var/folders/8l/xq7fclpn08gbjsqtc4r4f0wm0000gn/T/eas-build-local-nodejs/d22113e2-383c-407c-ad7c-7b1765f059b6/build/apps/nx-expo-problem/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
[RUN_GRADLEW]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets'.
[RUN_GRADLEW] > Process 'command 'node'' finished with non-zero exit value 1
```

### Package Manager Version

yarn 1.22.22

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i finally figure out the issue, i submit a pr https://github.com/nrwl/nx/pull/26983 for this. 
it happens because in realm's package.json, its exports is like:
```
    ".": {
      "types": "./dist/public-types/index.d.ts",
      "node": "./dist/platform/node/index.js",
      "react-native": "./index.react-native.js"
    },
```

when try to resolve it, it does not use field "node" nor "react-native". in my pr, I added these fields, also as an option exportsConditionNames to allow additional export condition names to be passed in.

**Comment by Thylacine-Software** [comment]
I was experiencing the same issue, but after upgrading NX to `19.5.3`, which includes this fix, I'm getting error: Cannot resolve node:os. 
Not sure what is happening 🤔

**Comment by LeandroTamola** [comment]
I was experiencing the same issue, but after upgrading NX to 19.5.3, which includes this fix, I'm getting error: Cannot resolve node:os.
Not sure what is happening 🤔
@cnhongwei where you able to find the solution?

**Comment by cnhongwei** [comment]
I upgraded nx to 19.5.3, error was:  Error: Cannot resolve node:fs
I don't know why.
@LeandroTamola @xiongemi

**Comment by LeandroTamola** [comment]
Hey @xiongemi Thank you so much for open the PR, unfortunately It is still not working for me. Now it fails with Cannot resolve node:os.
Dou you know why could it be happening?
