### ISSUE TITLE
Could not resolve .mjs import error in in docker when building project graph, but works locally

### ISSUE THREAD

**Issue by Zikoat** [nrwl/nx#26881]
### Current Behavior

When i run the commands as specified in the readme of the repo, the local commands work correctly and create the following output, and it prints "started server":
```sh
~/dev/organisation$ pnpm i && pnpm run build && pnpm run serve
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 1s

> myorganisation@ build /home/zikoat/dev/organisation
> nx build company-api


> nx run company-api:build

Compiling with SWC for company-api...
Successfully compiled: 3 files with swc (24.83ms)

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target build for project company-api (1s)


> myorganisation@ serve /home/zikoat/dev/organisation
> nx serve company-api-app --configuration=production


> nx run company-api-app:serve

[ watch ] build succeeded, watching for changes...
Debugger listening on ws://localhost:9229/350ba170-86b2-4506-93de-4c1b6101ea97
For help, see: https://nodejs.org/en/docs/inspector

started server

 NX  Process exited with code 0, waiting for changes to restart...
```

However, when i run the same commands in docker, then it fails when creating the project graph:

```sh
~/dev/organisation$ pnpm run docker-build && pnpm run docker-serve

> myorganisation@ docker-build /home/zikoat/dev/organisation
> docker build -t company-api .

[+] Building 14.2s (11/11) FINISHED                                                                                                         docker:default
 => [internal] load .dockerignore                                                                                                                     0.0s
 => => transferring context: 66B                                                                                                                      0.0s
 => [internal] load build definition from Dockerfile                                                                                                  0.0s
 => => transferring dockerfile: 356B                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/node:20.15.0                                                                                       3.4s
 => [stage-0 1/6] FROM docker.io/library/node:20.15.0@sha256:93d2e801dabc677ea0b30b47d3d729fab63ecb20be7ac0ab204cc3c65731297a                         0.0s
 => [internal] load build context                                                                                                                     0.0s
 => => transferring context: 4.25kB                                                                                                                   0.0s
 => CACHED [stage-0 2/6] WORKDIR /app                                                                                                                 0.0s
 => CACHED [stage-0 3/6] RUN corepack enable                                                                                                          0.0s
 => [stage-0 4/6] COPY . .                                                                                                                            0.0s
 => [stage-0 5/6] RUN --mount=type=cache,target=/pnpm   pnpm config set store-dir /pnpm &&   pnpm install --frozen-lockfile --prefer-offline          4.3s
 => [stage-0 6/6] RUN pnpm run build                                                                                                                  3.1s
 => exporting to image                                                                                                                                3.4s 
 => => exporting layers                                                                                                                               3.3s 
 => => writing image sha256:d98d3899b29e83bdb947f5565a6cd7401b714bc668aab070dcda4360fca329eb                                                          0.0s 
 => => naming to docker.io/library/company-api                                                                                                        0.0s 
                                                                                                                                                           
> myorganisation@ docker-serve /home/zikoat/dev/organisation
> docker run --rm -it -p 80:4000 -p 22:2222 company-api


> myorganisation@ serve /app
> nx serve company-api-app --configuration=production

▲ [WARNING] Cannot find base config file "../../tsconfig.base.json" [tsconfig.json]

    dist/libs/company-api/tsconfig.json:2:13:
      2 │   "extends": "../../tsconfig.base.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./vite-config.mjs"

    dist/libs/company-api/vite.config.js:12:28:
      12 │ const _viteconfig = require("./vite-config.mjs");
         ╵                             ~~~~~~~~~~~~~~~~~~~

failed to load config from /app/dist/libs/company-api/vite.config.js
Unable to create nodes for dist/libs/company-api/vite.config.js using plugin @nx/vite/plugin. 

         Inner Error: Error: Build failed with 1 error:
dist/libs/company-api/vite.config.js:12:28: ERROR: Could not resolve "./vite-config.mjs"
    at failureErrorWithLog (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1651:15)
    at /app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1059:25
    at runOnEndCallbacks (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1486:45)
    at buildResponseToResult (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1057:7)
    at /app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)

 NX   Unable to create nodes for dist/libs/company-api/vite.config.js using plugin @nx/vite/plugin. 


         Inner Error: Error: Build failed with 1 error:
dist/libs/company-api/vite.config.js:12:28: ERROR: Could not resolve "./vite-config.mjs"
    at failureErrorWithLog (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1651:15)
    at /app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1059:25
    at runOnEndCallbacks (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1486:45)
    at buildResponseToResult (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1057:7)
    at /app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/app/node_modules/.pnpm/esbuild@0.20.2/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)

 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected Behavior

1. The command in docker should not fail when creating the project graph.
1. The command in docker should print "server started".
1. The command in docker should have the same output as locally.

### GitHub Repo

https://github.com/Zikoat/nx-issue-repro

### Steps to Reproduce

```sh
git clone https://github.com/Zikoat/nx-issue-repro.git
cd nx-issue-repro/
pnpm i
pnpm run build
pnpm run serve
pnpm run docker-build
pnpm run docker-serve
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.15.0
OS     : linux-x64
pnpm   : 8.15.8

nx (global)  : 19.3.1
nx           : 18.0.8
@nx/jest     : 18.0.8
@nx/eslint   : 18.0.8
@nx/esbuild  : 18.3.5
@nrwl/tao    : 19.3.1
@nx/vite     : 18.3.5
typescript   : 5.4.5
---------------------------------------
The following packages should match the installed version of nx
  - @nx/esbuild@18.3.5
  - @nrwl/tao@19.3.1
  - @nx/vite@18.3.5

To fix this, run `nx migrate nx@19.3.1`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I tried debugging this in docker, but i wasn't able to get a breakpoint into nx's resolution step, or esbuild's build step.

**Comment by falldowngoboone** [comment]
I'm having a similar issue after updating from Nx 18.2.4 to 19.5.6. Everything builds and runs perfectly fine locally, but blows up when running in Docker:

```
Step 25/33 : RUN npx nx build admin --verbose
 ---> Running in 44d58f6622dc
 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  An error occurred while processing files for the @nx/eslint/plugin plugin.
    - apps/admin/.eslintrc.json: Failed to load config "../../.eslintrc.json" to extend from.
  Referenced from: /usr/src/app/apps/admin/.eslintrc.json
      Error: Failed to load config "../../.eslintrc.json" to extend from.
      Referenced from: /usr/src/app/apps/admin/.eslintrc.json
          at configInvalidError (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
          at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:23)
          at ConfigArrayFactory._loadExtends (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
          at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
          at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
          at _normalizeObjectConfigData.next (<anonymous>)
          at ConfigArrayFactory.loadInDirectory (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
          at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
          at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3890:20)
    - libs/date-time/.eslintrc.json: Failed to load config "../../.eslintrc.json" to extend from.
  Referenced from: /usr/src/app/libs/date-time/.eslintrc.json
      Error: Failed to load config "../../.eslintrc.json" to extend from.
      Referenced from: /usr/src/app/libs/date-time/.eslintrc.json
          at configInvalidError (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
          at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:23)
          at ConfigArrayFactory._loadExtends (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
          at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
          at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
          at _normalizeObjectConfigData.next (<anonymous>)
          at ConfigArrayFactory.loadInDirectory (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
          at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
          at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3890:20)
    - libs/feature-flags/.eslintrc.json: Failed to load config "../../.eslintrc.json" to extend from.
  Referenced from: /usr/src/app/libs/feature-flags/.eslintrc.json
      Error: Failed to load config "../../.eslintrc.json" to extend from.
      Referenced from: /usr/src/app/libs/feature-flags/.eslintrc.json
          at configInvalidError (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
          at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:23)
          at ConfigArrayFactory._loadExtends (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
          at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
          at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
          at _normalizeObjectConfigData.next (<anonymous>)
          at ConfigArrayFactory.loadInDirectory (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
          at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
          at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3890:20)
    - libs/i18n/.eslintrc.json: Failed to load config "../../.eslintrc.json" to extend from.
  Referenced from: /usr/src/app/libs/i18n/.eslintrc.json
      Error: Failed to load config "../../.eslintrc.json" to extend from.
      Referenced from: /usr/src/app/libs/i18n/.eslintrc.json
          at configInvalidError (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
          at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:23)
          at ConfigArrayFactory._loadExtends (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
          at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
          at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
          at _normalizeObjectConfigData.next (<anonymous>)
          at ConfigArrayFactory.loadInDirectory (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
          at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
          at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3890:20)
    - libs/utils/.eslintrc.json: Failed to load config "../../.eslintrc.json" to extend from.
  Referenced from: /usr/src/app/libs/utils/.eslintrc.json
      Error: Failed to load config "../../.eslintrc.json" to extend from.
      Referenced from: /usr/src/app/libs/utils/.eslintrc.json
          at configInvalidError (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
          at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:23)
          at ConfigArrayFactory._loadExtends (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
          at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
          at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
          at _normalizeObjectConfigData.next (<anonymous>)
          at ConfigArrayFactory.loadInDirectory (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
          at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
          at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3890:20)
The command '/bin/sh -c npx nx build admin --verbose' returned a non-zero code: 1
```

@jaysoo feel free to reach out if you need more info.

**Comment by namdien177** [comment]
> I'm having a similar issue after updating from Nx 18.2.4 to 19.5.6. Everything builds and runs perfectly fine locally, but blows up when running in Docker:
> 
> ```
> Step 25/33 : RUN npx nx build admin --verbose
>  ---> Running in 44d58f6622dc
>  NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.
> Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
>   An error occurred while processing files for the @nx/eslint/plugin plugin.
>     - apps/admin/.eslintrc.json: Failed to load config "../../.eslintrc.json" to extend from.
>   Referenced from: /usr/src/app/apps/admin/.eslintrc.json
>       Error: Failed to load config "../../.eslintrc.json" to extend from.
>       Referenced from: /usr/src/app/apps/admin/.eslintrc.json
>           at configInvalidError (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
>           at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:23)
>           at ConfigArrayFactory._loadExtends (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
>           at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
>           at _normalizeObjectConfigDataBody.next (<anonymous>)
>           at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
>           at _normalizeObjectConfigData.next (<anonymous>)
>           at ConfigArrayFactory.loadInDirectory (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
>           at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
>           at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3890:20)
>     - libs/date-time/.eslintrc.json: Failed to load config "../../.eslintrc.json" to extend from.
>   Referenced from: /usr/src/app/libs/date-time/.eslintrc.json
>       Error: Failed to load config "../../.eslintrc.json" to extend from.
>       Referenced from: /usr/src/app/libs/date-time/.eslintrc.json
>           at configInvalidError (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
>           at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:23)
>           at ConfigArrayFactory._loadExtends (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
>           at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
>           at _normalizeObjectConfigDataBody.next (<anonymous>)
>           at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
>           at _normalizeObjectConfigData.next (<anonymous>)
>           at ConfigArrayFactory.loadInDirectory (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
>           at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
>           at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3890:20)
>     - libs/feature-flags/.eslintrc.json: Failed to load config "../../.eslintrc.json" to extend from.
>   Referenced from: /usr/src/app/libs/feature-flags/.eslintrc.json
>       Error: Failed to load config "../../.eslintrc.json" to extend from.
>       Referenced from: /usr/src/app/libs/feature-flags/.eslintrc.json
>           at configInvalidError (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
>           at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:23)
>           at ConfigArrayFactory._loadExtends (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
>           at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
>           at _normalizeObjectConfigDataBody.next (<anonymous>)
>           at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
>           at _normalizeObjectConfigData.next (<anonymous>)
>           at ConfigArrayFactory.loadInDirectory (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
>           at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
>           at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3890:20)
>     - libs/i18n/.eslintrc.json: Failed to load config "../../.eslintrc.json" to extend from.
>   Referenced from: /usr/src/app/libs/i18n/.eslintrc.json
>       Error: Failed to load config "../../.eslintrc.json" to extend from.
>       Referenced from: /usr/src/app/libs/i18n/.eslintrc.json
>           at configInvalidError (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
>           at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:23)
>           at ConfigArrayFactory._loadExtends (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
>           at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
>           at _normalizeObjectConfigDataBody.next (<anonymous>)
>           at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
>           at _normalizeObjectConfigData.next (<anonymous>)
>           at ConfigArrayFactory.loadInDirectory (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
>           at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
>           at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3890:20)
>     - libs/utils/.eslintrc.json: Failed to load config "../../.eslintrc.json" to extend from.
>   Referenced from: /usr/src/app/libs/utils/.eslintrc.json
>       Error: Failed to load config "../../.eslintrc.json" to extend from.
>       Referenced from: /usr/src/app/libs/utils/.eslintrc.json
>           at configInvalidError (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2648:9)
>           at ConfigArrayFactory._loadExtendedShareableConfig (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:23)
>           at ConfigArrayFactory._loadExtends (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3156:25)
>           at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
>           at _normalizeObjectConfigDataBody.next (<anonymous>)
>           at ConfigArrayFactory._normalizeObjectConfigData (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
>           at _normalizeObjectConfigData.next (<anonymous>)
>           at ConfigArrayFactory.loadInDirectory (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
>           at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
>           at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/src/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3890:20)
> The command '/bin/sh -c npx nx build admin --verbose' returned a non-zero code: 1
> ```
> 
> @jaysoo feel free to reach out if you need more info.

facing the same issue (starting 3 days ago). Exactly to the package `@nx/eslint`. I'm still not sure what the root issue is though. Trying to revert most of the packages back to the old version but it still outputs the same error.
