### ISSUE TITLE
Issue when serving Storybook 8.2.2

### ISSUE THREAD

**Issue by C0ZEN** [nrwl/nx#26914]
### Current Behavior

When running a Storybook serving command like `nx storybook my-lib`, I have the following error `NX   Invariant failed: Expected package.json#version to be defined in the "undefined" package}` on Storybook `8.2.2` which was not the case in Storybook `8.1.11`.

### Expected Behavior

No error.

### Steps to Reproduce

1. Migrate from Storybook `8.1.11` to `8.2.2`
2. Serve a storybook instance

### Nx Report

```shell
Node   : 20.12.2
OS     : darwin-arm64
npm    : 10.5.0

nx                 : 19.4.2
@nx/js             : 19.4.2
@nx/linter         : 19.4.2
@nx/eslint         : 19.4.2
@nx/workspace      : 19.4.2
@nx/cypress        : 19.4.2
@nx/devkit         : 19.4.2
@nx/eslint-plugin  : 19.4.2
@nx/react          : 19.4.2
@nx/storybook      : 19.4.2
@nrwl/tao          : 19.4.2
@nx/vite           : 19.4.2
@nx/web            : 19.4.2
typescript         : 5.4.5
---------------------------------------
Community plugins:
@koliveira15/nx-sonarqube : 4.1.0
nx-stylelint              : 17.1.5
```

### Failure Logs

```shell
Error: Invariant failed: Expected package.json#version to be defined in the "undefined" package}
    at invariant (/Users/mac/Documents/github/repo-x/front/node_modules/@storybook/core/dist/core-server/index.cjs:187629:11)
    at buildDevStandalone (/Users/mac/Documents/github/repo-x/front/node_modules/@storybook/core/dist/core-server/index.cjs:189878:3)
    at Object.build (/Users/mac/Documents/github/repo-x/front/node_modules/@storybook/core/dist/core-server/index.cjs:190005:12)
    at runInstance (/Users/mac/Documents/github/repo-x/front/node_modules/@nx/storybook/src/executors/storybook/storybook.impl.js:26:18)
    at storybookExecutor (/Users/mac/Documents/github/repo-x/front/node_modules/@nx/storybook/src/executors/storybook/storybook.impl.js:12:26)
    at storybookExecutor.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/Users/mac/Documents/github/repo-x/front/node_modules/nx/src/utils/async-iterator.js:15:34)
    at iteratorToProcessStatusCode (/Users/mac/Documents/github/repo-x/front/node_modules/nx/src/command-line/run/run.js:44:94)
    at /Users/mac/Documents/github/repo-x/front/node_modules/nx/src/command-line/run/run.js:187:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Building Storybook is working (`nx build-storybook my-lib`).

**Comment by PaulACoroneos** [comment]
Seeing same issue after migrating from NX 19.3 -> 19.4.2 after already having had Storybook 8.2.2 as a dep.

**Comment by jonsoku-dev** [comment]
same nx 19.1 -> 19.4.2

If you remove the storybook-related settings from each project in the monorepo, it will work, but you will lose the ability to customize.

**Comment by C0ZEN** [comment]
Same with [8.2.4](https://github.com/storybookjs/storybook/releases/tag/v8.2.4)

**Comment by k-paxian** [comment]
Same here 😞

**Comment by Coly010** [comment]
There is a known breaking change issue with Storybook 8.2 for Nx workspaces. The storybook team have been in contact with us and we'll be working together to get a solution asap.

**Comment by Coly010** [comment]
The solution is to ensure you install the `storybook` package at the correct version you are using.

We'll be adding a migration and some updates to our generators to ensure this is installed for workspaces.

**Comment by popoleeMaster** [comment]
Sorry but I dont get what does this mean ?
> The solution is to ensure you install the storybook package at the correct version you are using.

**Comment by parostatkiem** [comment]
Can we reopen this issue?
The "solution" comment is very unclear and even if there is a workaround for the problem, is it really the **solution**?

**Comment by Coly010** [comment]
`npm install storybook@8.2` change `8.2` to match the version of the other storybook versions in your package.json (`@storybook/core` etc)

This is the solution that was agreed between ourselves and storybook after talking with their team

**Comment by roeb** [comment]
I have all `storybook` dependecies at the same version, but still get the same error.

` NX   Invariant failed: Expected package.json#version to be defined in the "undefined" package}`

```
devDependencies: {
    "@storybook/addon-docs": "^8.2.6",
    "@storybook/addon-essentials": "^8.2.6",
    "@storybook/addon-interactions": "^8.2.6",
    "@storybook/addon-links": "^8.2.6",
    "@storybook/addon-mdx-gfm": "^8.2.6",
    "@storybook/core-server": "^8.2.6",
    "@storybook/react-vite": "^8.2.6",
    "@storybook/test": "^8.2.6",
    "@storybook/test-runner": "^0.19.1",
    "@nx/storybook": "19.5.3"
}
```

@Coly010 What do I understand wrong about the solution?

**Comment by ms-tng** [comment]
I think the suggested solution is to install the `storybook` package in addition to and in the same version as the `@storybook/*` packages. That doesn't work for me either, though.

**Comment by wadamek65** [comment]
Same here, have `storybook` package installed along with `@storybook/` packages all of the same version and still the same error occurs. I also cannot downgrade to `8.11.1` because it seems like it has a major problem with test runner which doesn't support that version.

**Comment by Coly010** [comment]
Clearly this needs more investigation.

There is also an open issue on the storybook package: https://github.com/storybookjs/storybook/issues/28606

**Comment by abcdmku** [comment]
(cross posting) I opened a [PR](https://github.com/storybookjs/storybook/pull/28752) for that issue

**Comment by abcdmku** [comment]
follow up:
https://github.com/storybookjs/storybook/pull/28752#issuecomment-2257352795

**Comment by Crocsx** [comment]
Yeah got confused too. All my package are same version 

```

    "@nx/storybook": "19.5.3",
    "@storybook/addon-actions": "^8.2.6",
    "@storybook/addon-essentials": "^8.2.6",
    "@storybook/addon-interactions": "^8.2.6",
    "@storybook/addon-viewport": "^8.2.6",
    "@storybook/core-common": "^8.2.6",
    "@storybook/core-server": "^8.2.6",
    "@storybook/react": "^8.2.6",
    "@storybook/react-webpack5": "^8.2.6",
    "@storybook/test": "^8.2.6",
    "@storybook/test-runner": "^0.19.1",
    "storybook": "^8.2.6",
    "storybook-addon-remix-react-router": "^3.0.0",
    "storybook-react-i18next": "^3.1.5",
 ```
 
 I also still got the issue, only when running the local dev
 
 ```
     "storybook": {
      "executor": "@nx/storybook:storybook",
      "options": {
        "port": 4400,
        "configDir": "apps/core/.storybook"
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
```

doesn't happen with

```

    "storybook:build": {
      "executor": "@nx/storybook:build",
      "outputs": ["{options.outputDir}"],
      "options": {
        "outputDir": "dist/storybook/core",
        "configDir": "apps/core/.storybook",
        "webpackStatsJson": true
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
    "storybook:publish": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "npx nx run core:storybook:build --skip-nx-cache",
          "npx chromatic --project-token=770de6ba0ed3 -d=dist/storybook/core --exit-once-uploaded --only-changed"
        ],
        "parallel": false
      },
      "configurations": {
        "ci": {
          "commands": [
            "npx nx run core:storybook:build:ci --skip-nx-cache",
            "npx chromatic --project-token=770de6ba0ed3 -d=dist/storybook/core --ci --exit-once-uploaded --only-changed"
          ]
        }
      }
    },
    "storybook:test": {
      "executor": "nx:run-commands",
      "options": {
        "command": "test-storybook -c apps/core/.storybook --url=http://localhost:4400"
      }
    },
```

@abcdmku solution does look like its working I basically added both 

```
    "storybook": {
      "executor": "@nx/storybook:storybook",
      "options": {
        "port": 4400,
        "configDir": "apps/core/.storybook"
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
    "storybook:build": {
      "inputs": [
        "default",
        "^production",
        "{workspaceRoot}/.storybook/**/*",
        "{projectRoot}/.storybook/**/*",
        "{projectRoot}/tsconfig.storybook.json"
      ],
      "cache": true
    },
    ```

to `nx.json` instead of `project.json` althougt I am unsure if this suit everyone as they might want various configuration per app. But this is good enough for now.

**Comment by Coly010** [comment]
Looks like there is a PR for the fix on the storybook repo now: https://github.com/storybookjs/storybook/pull/28752

**Comment by parostatkiem** [comment]
Now we just need to wait for the storybook release.
Thanks @abcdmku !

**Comment by mathis-m** [comment]
> Now we just need to wait for the storybook release. Thanks @abcdmku !

Release is there: https://github.com/storybookjs/storybook/releases/tag/v8.2.8
