### ISSUE TITLE
`npx nx migrate latest` Failed to install the latest version of the migration script. Using the current version.

### ISSUE THREAD

**Issue by jahusa02** [nrwl/nx#26926]
### Current Behavior

npx nx migrate latest throws error for install script

### Expected Behavior

should not throw an error

### Steps to Reproduce

Dunno if its related but I have a private Registry defined.

1. run `npx nx migrate latest`

### Nx Report

```shell
Node   : 20.15.0
OS     : darwin-arm64
npm    : 10.8.2

nx                 : 19.4.3
@nx/js             : 19.4.3
@nx/jest           : 19.4.3
@nx/linter         : 19.4.3
@nx/eslint         : 19.4.3
@nx/workspace      : 19.4.3
@nx/angular        : 19.4.3
@nx/cypress        : 19.4.3
@nx/devkit         : 19.4.3
@nx/esbuild        : 19.4.3
@nx/eslint-plugin  : 19.4.3
@nx/express        : 19.4.3
@nx/node           : 19.4.3
@nrwl/tao          : 19.4.3
@nx/vite           : 19.4.3
@nx/web            : 19.4.3
@nx/webpack        : 19.4.3
typescript         : 5.5.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
@nx/jest/plugin
@nx/cypress/plugin
---------------------------------------
Community plugins:
@jsverse/transloco        : 7.4.2
@koliveira15/nx-sonarqube : 4.1.0
@ngrx/component-store     : 18.0.1
@ngrx/effects             : 18.0.1
@ngrx/entity              : 18.0.1
@ngrx/eslint-plugin       : 18.0.1
@ngrx/operators           : 18.0.1
@ngrx/router-store        : 18.0.1
@ngrx/schematics          : 18.0.1
@ngrx/store               : 18.0.1
@ngrx/store-devtools      : 18.0.1
@nx-tools/nx-container    : 6.0.1
ng-mocks                  : 14.13.0
ngx-matomo-client         : 6.2.0
```

### Failure Logs

```shell
Failed to install the latest version of the migration script. Using the current version.
Error: Command failed: npm install
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at nxCliPath (/Users/reneachtelik/workspace/fhp-bike/node_modules/nx/src/command-line/migrate/command-object.js:137:38)
    at runMigration (/Users/reneachtelik/workspace/fhp-bike/node_modules/nx/src/command-line/migrate/command-object.js:90:19)
    at Object.handler (/Users/reneachtelik/workspace/fhp-bike/node_modules/nx/src/command-line/migrate/command-object.js:18:9)
    at /Users/reneachtelik/workspace/fhp-bike/node_modules/yargs/build/index.cjs:1:8993
    at j (/Users/reneachtelik/workspace/fhp-bike/node_modules/yargs/build/index.cjs:1:4956)
    at _.handleValidationAndGetResult (/Users/reneachtelik/workspace/fhp-bike/node_modules/yargs/build/index.cjs:1:8962) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 36628,
  stdout: null,
  stderr: null
}
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment]
Could you tell us more about how you have the local registry defined please?

**Comment by leosvelperez** [comment]
@jahusa02 This particular issue might not be related to the registry. I think it's more likely to be related to something specific to your environment, potentially permissions, or something similar.

Given that it might be hard to reproduce (I already tried and couldn't), would you be willing to make a local change to the installed `nx` package in your `node_modules` so we can get more logs?

If so, please update the line **167** of the file `node_modules/nx/src/command-line/migrate/command-object.js` with the following:

```diff
-      stdio: ['ignore', 'ignore', 'ignore'],
+      stdio: 'inherit',
```

Then run `npx nx migrate latest` again and share the logs here 🙏🏻 

> As an aside, `nx migrate` could really use more logging for debugging purposes, so users don't need to manually update their installed packages. I'll look at that separately.

**Comment by leosvelperez** [comment]
@jahusa02 thanks for sharing the extra logs. It seems the issue is we don't copy the workspace `.npmrc` file to the temp folder where we install the latest version. I'll send a fix for that.
