### ISSUE TITLE
eslint:convert-to-inferred did not find a project inside

### ISSUE THREAD

**Issue by ChristopherPHolder** [nrwl/nx#26920]
### Current Behavior

Running:

`npx nx g @nx/eslint:convert-to-inferred --project portal-app`

Throws:

> The nx plugin did not find a project inside packages/portal-app. File an issue at https://github.com/nrwl/nx with information about your project structure.

### Expected Behavior

Should ether migrate the project or throw a error that tells me why is did not find the project or a direction to investigate where the error is coming from. 

### GitHub Repo

https://github.com/ChristopherPHolder/app-speed

### Steps to Reproduce

1. npm ci
2. npx nx g @nx/eslint:convert-to-inferred --project portal-app

### Nx Report

```shell
Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4

nx                 : 19.3.0
@nx/js             : 19.3.0
@nx/jest           : 19.3.0
@nx/linter         : 19.3.0
@nx/eslint         : 19.3.0
@nx/workspace      : 19.3.0
@nx/angular        : 19.3.0
@nx/cypress        : 19.3.0
@nx/devkit         : 19.3.0
@nx/esbuild        : 19.3.0
@nx/eslint-plugin  : 19.3.0
@nx/node           : 19.3.0
@nx/plugin         : 19.3.0
@nx/storybook      : 19.3.0
@nrwl/tao          : 19.3.0
@nx/vite           : 19.3.0
@nx/web            : 19.3.0
@nx/webpack        : 19.3.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
@rx-angular/cdk      : 18.0.0
@rx-angular/state    : 18.0.0
@rx-angular/template : 18.0.0
@storybook/angular   : 8.1.9
nx-release           : 3.3.0
---------------------------------------
Local workspace plugins:
         @app-speed/aws-deploy
```

### Failure Logs

```shell
NX   The nx plugin did not find a project inside packages/portal-app. File an issue at https://github.com/nrwl/nx with information about your project structure.


Error: The nx plugin did not find a project inside packages/portal-app. File an issue at https://github.com/nrwl/nx with information about your project structure.
    at ExecutorToPluginMigrator._ExecutorToPluginMigrator_getCreatedTargetForProjectRoot (C:\Users\christopher.holder\Projects\app-speed\node_modules\@nx\devkit\src\generators\plugin-migrations\executor-to-plugin-migrator.js:219:15)
    at ExecutorToPluginMigrator._ExecutorToPluginMigrator_migrateTarget (C:\Users\christopher.holder\Projects\app-speed\node_modules\@nx\devkit\src\generators\plugin-migrations\executor-to-plugin-migrator.js:64:143)
    at ExecutorToPluginMigrator.run (C:\Users\christopher.holder\Projects\app-speed\node_modules\@nx\devkit\src\generators\plugin-migrations\executor-to-plugin-migrator.js:44:137)
    at async migrateExecutorToPlugin (C:\Users\christopher.holder\Projects\app-speed\node_modules\@nx\devkit\src\generators\plugin-migrations\executor-to-plugin-migrator.js:256:12)
    at async convertToInferred (C:\Users\christopher.holder\Projects\app-speed\node_modules\@nx\eslint\src\generators\convert-to-inferred\convert-to-inferred.js:11:36)
    at async C:\Users\christopher.holder\Projects\app-speed\node_modules\nx\src\command-line\generate\generate.js:241:26
    at async handleErrors (C:\Users\christopher.holder\Projects\app-speed\node_modules\nx\src\utils\params.js:9:24)
    at async Object.handler (C:\Users\christopher.holder\Projects\app-speed\node_modules\nx\src\command-line\generate\command-object.js:13:22)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Read these docs but did not find any relevant info: 
https://nx.dev/troubleshooting/convert-to-inferred

**Comment by leosvelperez** [comment]
Thanks for reporting this!

This has been fixed by https://github.com/nrwl/nx/pull/26638 and released in version 19.4.4. Please migrate to at least 19.4.4 or later to address the issue.
