### ISSUE TITLE
nx migrate does not work if only yarn is installed (no npm)

### ISSUE THREAD

**Issue by TheAifam5** [nrwl/nx#2695]
## Expected Behavior

Should find one which one (npm or yarn) is used.

## Current Behavior

Does not use yarn, still tries to use npm.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install only yarn (without npm)
2. nx migrate...

### Context

nx report:
```
yarn run v1.22.4
$ nx report

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.0.4
  @nrwl/cypress : 9.0.4
  @nrwl/eslint-plugin-nx : 9.0.4
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.4
  @nrwl/linter : 9.0.4
  @nrwl/nest : 9.0.4
  @nrwl/next : Not Found
  @nrwl/node : 9.0.4
  @nrwl/react : 9.0.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.4
  @nrwl/web : 9.0.4
  @nrwl/workspace : 9.0.4
  typescript : 3.8.3

✨  Done in 0.49s.
```

### Failure Logs

```
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
The migrate command failed. Try the following to migrate your workspace:
> npm install --save-dev @nrwl/workspace@latest
> nx migrate @nrwl/workspace@latest --from="@nrwl/workspace@9.0.4"
This will use the newest version of the migrate functionality, which might have your issue resolved.
----------------------------------------------------------------------------------------------------
Command failed: npm install @nrwl/workspace@latest --prefix=/tmp/tmp-6280089vkLxKnRzUe6
/bin/sh: npm: command not found

/home/theaifam5/Documents/Projects/node_modules/yargs/yargs.js:1109
      else throw err
           ^

Error: Command failed: ./node_modules/.bin/tao migrate @nrwl/workspace
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at Object.handler (/home/theaifam5/Documents/Projects/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:76:21)
    at Object.runCommand (/home/theaifam5/Documents/Projects/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/theaifam5/Documents/Projects/node_modules/yargs/yargs.js:1022:30)
    at Object.get [as argv] (/home/theaifam5/Documents/Projects/node_modules/yargs/yargs.js:965:21)
    at Object.initLocal (/home/theaifam5/Documents/Projects/node_modules/@nrwl/cli/lib/init-local.js:20:79)
    at Object.<anonymous> (/home/theaifam5/Documents/Projects/node_modules/@nrwl/cli/bin/nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 628008,
  stdout: null,
  stderr: null
}
```
### Other
https://github.com/nrwl/nx/blob/0b7535ae92b2aaa72fa1df3c9ea45d96aee5f8c4/packages/tao/src/commands/migrate.ts#L405

**Comment by fernandouniques** [comment]
I had the same problem but using NPM. Not YARN.

nx migrate latest
/bin/sh: 1: yarn: not found

**Is there any solution to this problem?**

> nx report
>  NX  Report complete - copy this into the issue template
  nx : Not Found
  @nrwl/angular : 10.3.3
  @nrwl/cli : 10.3.3
  @nrwl/cypress : 10.3.3
  @nrwl/eslint-plugin-nx : 10.3.3
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.3
  @nrwl/linter : 10.3.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.3
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.3
  typescript : 4.0.5

**Comment by fernandouniques** [comment]
> nx migrate
/var/www/testhost/project/nxform/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn install
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at taoPath (/var/www/testhost/project/nxform/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:303:21)
    at Object.handler (/var/www/testhost/project/nxform/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:77:19)
    at Object.runCommand (/var/www/testhost/project/nxform/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/var/www/testhost/project/nxform/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/var/www/testhost/project/nxform/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/var/www/testhost/project/nxform/node_modules/@nrwl/cli/lib/init-local.js:24:13)
    at Object.<anonymous> (/var/www/testhost/project/nxform/node_modules/@nrwl/cli/bin/nx.js:12:18)
    at Module._compile (/home/fernando/.nvm/versions/node/v16.6.0/lib/node_modules/@nrwl/cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 12256,
  stdout: null,
  stderr: null
}
