### ISSUE TITLE
`nx release plan` with a project containing a scoped npm package, and no project name creates a malformed plan

### ISSUE THREAD

**Issue by jonathanmorley** [nrwl/nx#27010]
### Current Behavior

The version plan gets generated as
```
---
@cvent/pkg: patch
---

chore: release
```

### Expected Behavior

The version plan gets generated as
```
---
'@cvent/pkg': patch
---

chore: release
```

### Steps to Reproduce

1. Using nx v19
2. Make a project (without an explicit name)
3. Add a package.json with a scoped name (@foo/bar)
4. Run `nx release plan` to create a version plan
5. Run `nx release`

### Nx Report

```shell
Node   : 20.11.0
OS     : darwin-arm64
pnpm   : 8.15.6

nx             : 19.5.1
@nx/js         : 19.5.1
@nx/workspace  : 19.5.1
@nx/devkit     : 18.3.3
@nrwl/tao      : 19.5.1
typescript     : 5.5.3
---------------------------------------
Community plugins:
@cvent/cdf : 1.36.23
---------------------------------------
The following packages should match the installed version of nx
  - @nx/devkit@18.3.3
  - @nrwl/devkit@18.3.3

To fix this, run `nx migrate nx@19.5.1`
```

### Failure Logs

```shell
pnpm nx release --dry-run --verbose

 NX   end of the stream or a document separator is expected at line 1, column 1:

    @cvent/pkg: patch
    ^

YAMLException: end of the stream or a document separator is expected at line 1, column 1:
    @cvent/pkg: patch
    ^
    at generateError (/Users/jonathan/Developer/pkg/node_modules/.pnpm/js-yaml@3.14.1/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/Users/jonathan/Developer/pkg/node_modules/.pnpm/js-yaml@3.14.1/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readDocument (/Users/jonathan/Developer/pkg/node_modules/.pnpm/js-yaml@3.14.1/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
    at loadDocuments (/Users/jonathan/Developer/pkg/node_modules/.pnpm/js-yaml@3.14.1/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
    at load (/Users/jonathan/Developer/pkg/node_modules/.pnpm/js-yaml@3.14.1/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
    at safeLoad (/Users/jonathan/Developer/pkg/node_modules/.pnpm/js-yaml@3.14.1/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
    at parse (/Users/jonathan/Developer/pkg/node_modules/.pnpm/front-matter@4.0.2/node_modules/front-matter/index.js:64:20)
    at extractor (/Users/jonathan/Developer/pkg/node_modules/.pnpm/front-matter@4.0.2/node_modules/front-matter/index.js:26:12)
    at readRawVersionPlans (/Users/jonathan/Developer/pkg/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/command-line/release/config/version-plans.js:26:31)
    at async releaseVersion (/Users/jonathan/Developer/pkg/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/command-line/release/version.js:74:29)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment]
Thanks a lot for this @jonathanmorley, you are very brave to be using an undocumented feature 😄 

We will be documenting and announcing version plans once we have completed a little more dogfooding and are happy with the e2e dev experience.

You can obviously keep using it in the meantime and reporting issues, but there won't be much in the way of written help just yet.
