### ISSUE TITLE
"Cannot find module '@angular/build/package.json'" in a new monorepo workspace in generated angular app

### ISSUE THREAD

**Issue by Ignalewski** [nrwl/nx#27024]
### Current Behavior

Generating new workspace and generating new angular application results in an error when serving or building

```PS C:\lynx> npx nx run front:serve --verbose

> nx run front:serve:development

 NX   Cannot find module '@angular/build/package.json'
Require stack:
- C:\lynx\node_modules\nx\src\utils\package-json.js
- C:\lynx\node_modules\nx\src\utils\print-help.js
- C:\lynx\node_modules\nx\src\command-line\run\run.js
- C:\lynx\node_modules\nx\bin\run-executor.js
Error: Cannot find module '@angular/build/package.json'
Require stack:
- C:\lynx\node_modules\nx\src\utils\package-json.js
- C:\lynx\node_modules\nx\src\utils\print-help.js
- C:\lynx\node_modules\nx\src\command-line\run\run.js
- C:\lynx\node_modules\nx\bin\run-executor.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at readModulePackageJsonWithoutFallbacks (C:\lynx\node_modules\nx\src\utils\package-json.js:113:37)
    at readPluginPackageJson (C:\lynx\node_modules\nx\src\project-graph\plugins\loader.js:30:81)
    at WrappedWorkspaceNodeModulesArchitectHost.readExecutorsJson (C:\lynx\node_modules\nx\src\adapter\ngcli-adapter.js:803:102)
    at WrappedWorkspaceNodeModulesArchitectHost.readExecutorsJson (C:\lynx\node_modules\nx\src\adapter\ngcli-adapter.js:817:29)
    at WrappedWorkspaceNodeModulesArchitectHost.resolveBuilder (C:\lynx\node_modules\nx\src\adapter\ngcli-adapter.js:792:64)
    at name (C:\lynx\node_modules\@angular-devkit\architect\src\architect.js:220:40)
    at Observable._subscribe (C:\lynx\node_modules\@angular-devkit\architect\src\jobs\create-job-handler.js:107:26)
    at Observable._trySubscribe (C:\lynx\node_modules\rxjs\dist\cjs\internal\Observable.js:41:25)

————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target serve for project front failed

Failed tasks:

- front:serve:development

Hint: run the command with --verbose for more details.```


### Expected Behavior

Running serve on a newly generated project should serve the project without errors

### GitHub Repo

https://github.com/Ignalewski/nx-angular-repro

### Steps to Reproduce

PS C:\lynx> `npm -v`
10.8.2
PS C:\lynx> `node -v`
v20.15.1

`npx create-nx-workspace@latest lynx`
_using node, nestJs, integrated monorepo_
`cd .\lynx\`
`npm i -D @nx/angular`
using nx vs code extension: 
`npx nx generate @nx/angular:application --name=front --directory=apps/front --prefix=lynx --projectNameAndRootFormat=as-provided --style=scss --no-interactive`
`npm ci`
`npx nx run front:serve --verbose`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.15.1
OS     : win32-x64
npm    : 10.8.2

nx                 : 19.5.1
@nx/js             : 19.5.1
@nx/jest           : 19.5.1
@nx/linter         : 19.5.1
@nx/eslint         : 19.5.1
@nx/workspace      : 19.5.1
@nx/angular        : 19.5.1
@nx/devkit         : 19.5.1
@nx/eslint-plugin  : 19.5.1
@nx/nest           : 19.5.1
@nx/node           : 19.5.1
@nx/playwright     : 19.5.1
@nrwl/tao          : 19.5.1
@nx/web            : 19.5.1
@nx/webpack        : 19.5.1
typescript         : 5.5.3
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/playwright/plugin
```

### Package Manager Version

npm 10.8.2

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
This issue was fixed by https://github.com/nrwl/nx/pull/26979, and the change should be released soon. Please keep an eye on the releases to update and get the fix.
