### ISSUE TITLE
Cannot find module '@nx/nx-darwin-arm64'

### ISSUE THREAD

**Issue by Diokuz** [nrwl/nx#27031]
### Current Behavior

```
yarn --frozen-lockfile --ignore-optional
```

fails with

```
[6/7] ⠄ postinstall-postinstall
error /Users/diokuz/Projects/online/node_modules/nx: Command failed.
Exit code: 1
Command: node ./bin/post-install
Arguments:
Directory: /Users/diokuz/Projects/online/node_modules/nx
Output:
/Users/diokuz/Projects/online/node_modules/nx/src/native/native-bindings.js:244
    throw loadError
    ^

Error: Cannot find module '@nx/nx-darwin-arm64'
Require stack:
- /Users/diokuz/Projects/online/node_modules/nx/src/native/index.js
- /Users/diokuz/Projects/online/node_modules/nx/src/hasher/node-task-hasher-impl.js
- /Users/diokuz/Projects/online/node_modules/nx/src/hasher/task-hasher.js
- /Users/diokuz/Projects/online/node_modules/nx/src/hasher/hash-task.js
- /Users/diokuz/Projects/online/node_modules/nx/src/tasks-runner/run-command.js
- /Users/diokuz/Projects/online/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js
- /Users/diokuz/Projects/online/node_modules/nx/bin/post-install.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Function.resolve (node:internal/modules/helpers:188:19)
    at Module._load (/Users/diokuz/Projects/online/node_modules/nx/src/native/index.js:53:36)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/diokuz/Projects/online/node_modules/nx/src/native/native-bindings.js:135:29)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/diokuz/Projects/online/node_modules/nx/src/native/index.js',
    '/Users/diokuz/Projects/online/node_modules/nx/src/hasher/node-task-hasher-impl.js',
    '/Users/diokuz/Projects/online/node_modules/nx/src/hasher/task-hasher.js',
    '/Users/diokuz/Projects/online/node_modules/nx/src/hasher/hash-task.js',
    '/Users/diokuz/Projects/online/node_modules/nx/src/tasks-runner/run-command.js',
    '/Users/diokuz/Projects/online/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js',
    '/Users/diokuz/Projects/online/node_modules/nx/bin/post-install.js'
  ]
```

### Expected Behavior

```
yarn --frozen-lockfile --ignore-optional
```

passes without errors

### Steps to Reproduce

```
yarn add nx -WD

rm -rf node_modules

yarn --frozen-lockfile --ignore-optional
```

### Nx Report

```shell
npx nx report

 NX   Report complete - copy this into the issue template

Node   : 18.20.4
OS     : darwin-arm64
yarn   : 1.22.22

nx          : 19.4.2
@nrwl/tao   : 19.4.2
nx-cloud    : 19.0.0
typescript  : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Diokuz** [comment]
workarounds:

1. do not use `--ignore-optionals` argument
2. move nx to optionalDependencies

**Comment by FrozenPandaz** [comment]
As of `19.5.0`+ though. With wasm support, #22870, you should now be able to use Nx without the optional dependencies. Could you let me know if that works please?

**Comment by nealef** [comment]
Attempted a `npm install nx@19.5.1` and get:
```
#13 10.17 932 error /tmp/node_modules/nx/src/native/native-bindings.js:359
#13 10.17 932 error     throw new Error('Failed to load native binding', { cause: loadErrors })
#13 10.17 932 error     ^
#13 10.17 932 error
#13 10.17 932 error Error: Failed to load native binding
#13 10.17 932 error     at Object.<anonymous> (/tmp/node_modules/nx/src/native/native-bindings.js:359:11)
#13 10.17 932 error     at Module._compile (node:internal/modules/cjs/loader:1369:14)
#13 10.17 932 error     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
#13 10.17 932 error     at Module.load (node:internal/modules/cjs/loader:1206:32)
#13 10.17 932 error     at Module._load (node:internal/modules/cjs/loader:1022:12)
#13 10.17 932 error     at Module._load (/tmp/node_modules/nx/src/native/index.js:85:25)
#13 10.17 932 error     at Module.require (node:internal/modules/cjs/loader:1231:19)
#13 10.17 932 error     at require (node:internal/modules/helpers:179:18)
#13 10.17 932 error     at Object.<anonymous> (/tmp/node_modules/nx/src/native/index.js:91:21)
#13 10.17 932 error     at Module._compile (node:internal/modules/cjs/loader:1369:14) {
#13 10.17 932 error   [cause]: [
#13 10.17 932 error     Error: Cannot find module './nx.linux-s390x-gnu.node'
```

**Comment by FrozenPandaz** [comment]
No, it doesn't need anything to force it. It's the fallback for the native binary not being present for the runtime environment. @nealef I don't think your issue is the same. Could you open a new issue for s390x if you're still having trouble there with the logs from `NAPI_RS_FORCE_WASI=true nx report`?

**Comment by nealef** [comment]
> No, it doesn't need anything to force it. It's the fallback for the native binary not being present for the runtime environment. @nealef I don't think your issue is the same. Could you open a new issue for s390x if you're still having trouble there with the logs from `NAPI_RS_FORCE_WASI=true nx report`?

Issue https://github.com/nrwl/nx/issues/27104 raised. I can't run `nx report` as `nx` won't install.

**Comment by Diokuz** [comment]
as of `nx@19.5.3`

in CI pipeline works well.

On my local (mac os x, node 18.20.4) machine:

```
yarn --ignore-optional

[4/4] 🔨  Building fresh packages...
[-/7] ⡀ waiting...
[-/7] ⡀ waiting...
[7/7] ⡀ nx
[-/7] ⡀ waiting...
[-/7] ⡀ waiting...
```

never ends... (at least for 10 minutes, CPU is used)

**Comment by Diokuz** [comment]
same for node 20.9

```
yarn -v
1.22.22
```
