### ISSUE TITLE
Intermittent Postinstall error for node 18.20.3

### ISSUE THREAD

**Issue by ahernd2** [nrwl/nx#27040]
### Current Behavior

When installing node_modules with pnpm we get this error intermittently.

```
.../.pnpm/nx@19.5.1/node_modules/nx postinstall: /builds/business/services/products/thunder/thunder-ui/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/project-graph/plugins/isolation/plugin-pool.js:146
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:                 const { resolver, rejector } = pending.get(tx);
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:                         ^
.../.pnpm/nx@19.5.1/node_modules/nx postinstall: TypeError: Cannot destructure property 'resolver' of 'pending.get(...)' as it is undefined.
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at createNodesResult (/builds/business/services/products/thunder/thunder-ui/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/project-graph/plugins/isolation/plugin-pool.js:146:25)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at consumeMessage (/builds/business/services/products/thunder/thunder-ui/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:37:32)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at /builds/business/services/products/thunder/thunder-ui/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/project-graph/plugins/isolation/plugin-pool.js:73:47
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at Socket.<anonymous> (/builds/business/services/products/thunder/thunder-ui/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/utils/consume-messages-from-socket.js:13:17)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at Socket.emit (node:events:517:28)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at addChunk (node:internal/streams/readable:368:12)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at readableAddChunk (node:internal/streams/readable:341:9)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at Readable.push (node:internal/streams/readable:278:10)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall: Node.js v18.20.3
.../.pnpm/nx@19.5.1/node_modules/nx postinstall: Failed
```

### Expected Behavior

Post install should not throw an error randomly

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 18.20.3
OS     : linux-x64
pnpm   : 7.33.4

nx                 : 19.5.1
@nx/js             : 19.5.1
@nx/jest           : 19.5.1
@nx/linter         : 19.5.1
@nx/eslint         : 19.5.1
@nx/workspace      : 19.5.1
@nx/angular        : 19.5.1
@nx/cypress        : 19.5.1
@nx/devkit         : 19.5.1
@nx/esbuild        : 19.5.1
@nx/eslint-plugin  : 19.5.1
@nx/express        : 19.5.1
@nx/node           : 19.5.1
@nx/playwright     : 19.5.1
@nx/plugin         : 19.5.1
@nx/storybook      : 19.5.1
@nrwl/tao          : 19.5.1
@nx/web            : 19.5.1
@nx/webpack        : 19.5.1
typescript         : 5.5.3
---------------------------------------
Community plugins:
@ngneat/transloco    : 4.3.0
@ngrx/effects        : 18.0.1
@ngrx/operators      : 18.0.1
@ngrx/router-store   : 18.0.1
@ngrx/store          : 18.0.1
@ngrx/store-devtools : 18.0.1
@storybook/angular   : 7.5.3
ngx-build-plus       : 13.0.1
ngx-toastr           : 16.2.0
---------------------------------------
Local workspace plugins:
         workspace-plugin
```

### Failure Logs

```shell
.../.pnpm/nx@19.5.1/node_modules/nx postinstall: /builds/business/services/products/thunder/thunder-ui/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/project-graph/plugins/isolation/plugin-pool.js:146
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:                 const { resolver, rejector } = pending.get(tx);
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:                         ^
.../.pnpm/nx@19.5.1/node_modules/nx postinstall: TypeError: Cannot destructure property 'resolver' of 'pending.get(...)' as it is undefined.
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at createNodesResult (/builds/business/services/products/thunder/thunder-ui/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/project-graph/plugins/isolation/plugin-pool.js:146:25)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at consumeMessage (/builds/business/services/products/thunder/thunder-ui/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:37:32)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at /builds/business/services/products/thunder/thunder-ui/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/project-graph/plugins/isolation/plugin-pool.js:73:47
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at Socket.<anonymous> (/builds/business/services/products/thunder/thunder-ui/node_modules/.pnpm/nx@19.5.1/node_modules/nx/src/utils/consume-messages-from-socket.js:13:17)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at Socket.emit (node:events:517:28)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at addChunk (node:internal/streams/readable:368:12)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at readableAddChunk (node:internal/streams/readable:341:9)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at Readable.push (node:internal/streams/readable:278:10)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall:     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
.../.pnpm/nx@19.5.1/node_modules/nx postinstall: Node.js v18.20.3
.../.pnpm/nx@19.5.1/node_modules/nx postinstall: Failed
```
```


### Package Manager Version

pnpm 7.33.4

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by ms-tng** [comment]
Hi, I'm seeing the same error in our CI (Bitbucket pipelines), so I investigated a bit. It is due to plugin isolation now being enabled by default (https://github.com/nrwl/nx/pull/26888). As it turns out, the names of the sockets used to communicate between the main process and the isolated plugin workers become longer than the maximum length allowed by the OS and hence get truncated, causing the part that makes them unique to be cut off. Consequently, multiple workers try to listen on the same socket and fail, causing them to exit prematurely. The error you see in the log is when Nx tries to access a pending promise that has already been disposed of because the worker is no longer there.

Regarding the long names: This specifically happens with pnpm because pnpm tends to produce folder structures with very long names under `node_modules`. The maximum allowed length should be 108 characters, though in our Bitbucket pipelines setup it seems to be 119. I'm not sure why it doesn't happen every time - maybe it has to do with the way the workers are scheduled.

As a workaround, you can set `NX_ISOLATE_PLUGINS=false` to disable the isolation as used to be the default before 19.5.

**Comment by ahernd2** [comment]
@ms-tng Thanks for the workaround, it does seem to work, haven't seen any failures since

**Comment by Squixx** [comment]
Also running into this, will test using `NX_ISOLATE_PLUGINS=false` What's interesting though is that i'm only getting this on linux. MacOs seems fine

**Comment by AgentEnder** [comment]
@ms-tng Wow! Thanks for the in-depth investigation. We've been pulling our hair out a bit trying to figure out what could cause this, and didn't think to look into the socket path but that makes sense.

I'll look into how we could better produce a shorter path. Thanks again 🙏

**Comment by AgentEnder** [comment]
Also, @ms-tng do you have an example of the long path names? It sounds like you've likely captured them already. I want to make sure the linked fix is good enough here.

**Comment by ms-tng** [comment]
@AgentEnder Glad I could help!

Here is an example socket path:
```
/opt/atlassian/pipelines/agent/build/node_modules/.pnpm/nx@19.5.1_patch_hash=v6gmoqjqk3tlj6q6xv6dk5mfxa_@swc-node+register@1.10.9_@swc+core@1.7.0_@sw_vw6ll7aabdl4qlr3pnaeetdsym/node_modules/nx/ddbea83aee87088f0551/plugin134-1.sock
```

Note that it contains a patch hash because I had patched Nx to increase logging, so it's a bit on the longer side.

**Comment by ms-tng** [comment]
@FrozenPandaz After your fix in #27073, the socket path is still too long, e.g.
```
/opt/atlassian/pipelines/agent/build/node_modules/.pnpm/nx@19.5.3_patch_hash=kaneqlcv6bufy26krrufvbfnhm_@swc-node+register@1.10.9_@swc+core@1.7.1_@sw_xjzfe2hqhqzzioudxymq7jg5sy/node_modules/nx/plugin181-1.sock
```

Looking at your change, I saw that one can define the socket directory by setting `NX_DAEMON_SOCKET_DIR`, so I'm now able to use plugin isolation by setting `NX_DAEMON_SOCKET_DIR=$(mktemp -d)`. I didn't check the code and don't know all the implications, but maybe you could also use the default OS temp dir instead of a subdirectory of `node_modules`.

**Comment by viceice** [comment]
shouldn't those files land in `<project-dir/.nx` ?

**Comment by csi-lk** [comment]
We're now seeing this issue on `20.15.1`, specifically in CI environments and not locally

**Comment by gcko** [comment]
I have been seeing it as well for node `22.5.1`

**Comment by berenddeboer** [comment]
Seeing this on AWS CodeBuild too.

**Comment by briskajanis1** [comment]
Seeing this in self hosted gitlab instance with node 18.20.4 as well

**Comment by m-makara** [comment]
Seeing this in Azure CI Pipelines, with Node v20.8.1.

**Comment by Kolahzary** [comment]
This error is happening to us on Vercel builds after upgrading nx from 19.4.0 to 19.5.7

```
.../node_modules/nx postinstall: TypeError: Cannot destructure property 'resolver' of 'pending.get(...)' as it is undefined.
.../node_modules/nx postinstall:     at createNodesResult (/vercel/path0/node_modules/.pnpm/nx@19.5.7_@swc-node+register@1.9.2_@swc+core@1.5.7/node_modules/nx/src/project-graph/plugins/isolation/plugin-pool.js:165:25)
.../node_modules/nx postinstall:     at consumeMessage (/vercel/path0/node_modules/.pnpm/nx@19.5.7_@swc-node+register@1.9.2_@swc+core@1.5.7/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:37:32)
.../node_modules/nx postinstall:     at /vercel/path0/node_modules/.pnpm/nx@19.5.7_@swc-node+register@1.9.2_@swc+core@1.5.7/node_modules/nx/src/project-graph/plugins/isolation/plugin-pool.js:80:47
.../node_modules/nx postinstall:     at Socket.<anonymous> (/vercel/path0/node_modules/.pnpm/nx@19.5.7_@swc-node+register@1.9.2_@swc+core@1.5.7/node_modules/nx/src/utils/consume-messages-from-socket.js:13:17)
.../node_modules/nx postinstall:     at Socket.emit (node:events:519:28)
.../node_modules/nx postinstall:     at addChunk (node:internal/streams/readable:559:12)
.../node_modules/nx postinstall:     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
.../node_modules/nx postinstall:     at Readable.push (node:internal/streams/readable:390:5)
.../node_modules/nx postinstall:     at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)
.../node_modules/nx postinstall: Node.js v20.16.0
.../node_modules/nx postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm install" exited with 1
```
