### ISSUE TITLE
Metro unable to resolve nx libraries after upgrade from RN 0.72.8

### ISSUE THREAD

**Issue by michaelwijnands** [nrwl/nx#27064]
### Current Behavior

When trying to start the application, Metro doesn't compile the React Native app because: 
Metro has encountered an error: 

```
Error: Cannot resolve package.json
    at /Users/michaelwijnands/Projects/myapp-frontend-3/node_modules/@nx/react-native/plugins/metro-resolver.js:31:15
    at Object.resolve (/Users/michaelwijnands/Projects/myapp-frontend-3/apps/mobile/node_modules/metro-resolver/src/resolve.js:32:12)
    at ModuleResolver.resolveDependency (/Users/michaelwijnands/Projects/myapp-frontend-3/apps/mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:73:31)
    at DependencyGraph.resolveDependency (/Users/michaelwijnands/Projects/myapp-frontend-3/apps/mobile/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /Users/michaelwijnands/Projects/myapp-frontend-3/apps/mobile/node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (/Users/michaelwijnands/Projects/myapp-frontend-3/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/Users/michaelwijnands/Projects/myapp-frontend-3/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at async Promise.all (index 0)
    at async visit (/Users/michaelwijnands/Projects/myapp-frontend-3/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 4)
```

When setting debug to true in `metro.config.js`, I notice a lot of errors saying:
```
[Nx] Unable to resolve with default Metro resolver: @myappname/my-hn/icons
[Nx] Unable to resolve with default resolveRequest: @myappname/my-hn/theme
[Nx] Unable to resolve with default Metro resolver: @myappname/my-hn/theme
[Nx] Unable to resolve with default resolveRequest: @myappname/my-hn/theme
[Nx] Unable to resolve with default Metro resolver: @myappname/my-hn/theme
[Nx] Unable to resolve with default resolveRequest: @myappname/my-hn/icons
[Nx] Unable to resolve with default Metro resolver: @myappname/my-hn/icons
[Nx] Unable to resolve with default resolveRequest: @myappname/my-hn/config
[Nx] Unable to resolve with default Metro resolver: @myappname/my-hn/config
```

My metro.config.js:
```
const { withNxMetro } = require('@nx/react-native');
const { workspaceRoot } = require('@nx/devkit');
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const path = require('path');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const customConfig = {
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter((ext) => ext !== 'svg'),
    sourceExts: [...sourceExts, 'cjs', 'mjs', 'svg', 'json'],
  },
};

module.exports = withNxMetro(mergeConfig(defaultConfig, customConfig), {
  // Change this to true to see debugging info.
  // Useful if you have issues resolving modules
  debug: true,
  // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx', 'json'
  extensions: [],
  // Specify folders to watch, in addition to Nx defaults (workspace libraries and node_modules)
  watchFolders: [path.resolve(__dirname, '../../node_modules'), path.resolve(__dirname, '../../libs/my-hn')],
});
```

One of the libs, @myappname/my-hn/config, only has 3 small TypeScript files. These files export some string etc, no rocket science or any heavy code at all. All other libs also are TS files. 

### Expected Behavior

I'd expect the application to build fine after upgrading React Native and changing the code as suggested by [React Native Upgrade tool](https://react-native-community.github.io/upgrade-helper/?from=0.73.2&to=0.74.1). 

### Steps to Reproduce

1. Create a NX library that works on both React and React Native
2. Upgrade from RN 0.72.8 to 0.73.2 (we also tried 0.74.1 as NX migrate latest does)
3. Start the run-ios or run-android command

### Nx Report

```shell
Node   : 18.20.2
OS     : darwin-arm64
npm    : 10.5.0

nx                 : 19.5.2
@nx/js             : 19.5.2
@nx/jest           : 19.5.2
@nx/linter         : 19.5.2
@nx/eslint         : 19.5.2
@nx/workspace      : 19.5.2
@nx/angular        : 19.5.2
@nx/detox          : 19.5.2
@nx/devkit         : 19.5.2
@nx/eslint-plugin  : 19.5.2
@nx/express        : 19.5.2
@nx/node           : 19.5.2
@nx/react          : 19.5.2
@nx/react-native   : 19.5.2
@nrwl/tao          : 19.5.2
@nx/web            : 19.5.2
@nx/webpack        : 19.5.2
typescript         : 5.0.4
---------------------------------------
Community plugins:
@ionic/angular              : 6.7.5
@maskito/angular            : 1.9.0
@nguniversal/builders       : 16.2.0
@nguniversal/express-engine : 16.2.0
@nxext/capacitor            : 18.0.4
apollo-angular              : 5.0.2
ngx-bootstrap               : 11.0.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Yes, we also have an Angular app in our repo as we are currently migrating from Angular (web-app) with an Ionic app (mobile) to React and React Native.

**Comment by xiongemi** [comment]
i think default watchFolders will watch node_modules folder and libararies as well, maybe try to change the the watchFolders to be empty array to see whether that would fix the issue? `watchFolders: []`,

**Comment by michaelwijnands** [comment]
@xiongemi Thanks for your reply. By default we have `watchFolders: []`, the above was to try if Metro would work. So unfortunately `watchfolders: []` doesn't help.

**Comment by xiongemi** [comment]
do you have a link to your repo?

**Comment by michaelwijnands** [comment]
I am sorry, it's a private repo from the company I work for so I cannot share it :(

Today I tried it again, going to RN 0.73.x works fine but starting at 0.74.x I get the error above.

Versions:

```
nx                 : 19.5.2
@nx/js             : 19.5.2
@nx/jest           : 19.5.2
@nx/linter         : 19.5.2
@nx/eslint         : 19.5.2
@nx/workspace      : 19.5.2
@nx/angular        : 19.5.2
@nx/detox          : 19.5.2
@nx/devkit         : 19.5.2
@nx/eslint-plugin  : 19.5.2
@nx/express        : 19.5.2
@nx/node           : 19.5.2
@nx/react          : 19.5.2
@nx/react-native   : 19.5.2
@nrwl/tao          : 19.5.2
@nx/web            : 19.5.2
@nx/webpack        : 19.5.2
    "@react-native-async-storage/async-storage": "^2.0.0",
    "@react-native-clipboard/clipboard": "^1.14.0",
    "@react-native-community/netinfo": "^11.3.3",
    "@react-native-firebase/analytics": "^18.7.1",
    "@react-native-firebase/app": "^18.7.1",
    "@react-native/metro-config": "^0.74.0",
    "@react-navigation/bottom-tabs": "6.5.11",
    "@react-navigation/drawer": "6.6.6",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.9.17",
    "@react-navigation/stack": "^6.3.21",
"react": "18.2.0",
    "react-calendar": "^5.0.0",
    "react-cookie": "^4.1.1",
    "react-dom": "^18.2.0",
    "react-modal": "^3.16.1",
    "react-modern-drawer": "^1.2.0",
    "react-native": "^0.74.0",
    "react-native-blob-util": "^0.19.2",
    "react-native-date-picker": "^5.0.4",
    "react-native-device-info": "10.7.0",
    "react-native-element-dropdown": "^2.12.0",
    "react-native-gesture-handler": "^2.18.1",
    "react-native-inappbrowser-reborn": "^3.7.0",
    "react-native-keychain": "8.1.1",
    "react-native-permissions": "^4.1.4",
    "react-native-qualtrics": "^2.8.0",
    "react-native-reanimated": "^3.9.0",
    "react-native-safe-area-context": "^4.10.5",
    "react-native-screens": "^3.31.0",
    "react-native-sensitive-info": "^6.0.0-alpha.9",
    "react-native-shared-element": "0.8.9",
    "react-native-svg-web": "1.0.9",
    "react-native-unistyles": "2.7.2",
    "react-native-web": "0.19.9",
    "react-native-webview": "^13.12.2",
    "react-navigation-shared-element": "3.1.3",
    "react-navigation-stack": "2.10.4",
    "react-redux": "8.0.5",
    "react-router-dom": "6.9.0",
    "@react-native/metro-babel-transformer": "^0.74.0",
    "@react-native/typescript-config": "^0.74.0",
```

I also tried NX 18.3.5 because that's our current version, that doesn't change anything unfortunately.
