### ISSUE TITLE
Can't use local library in externalDependencies for plugin

### ISSUE THREAD

**Issue by de-don** [nrwl/nx#27088]
### Current Behavior

When I use local library in externalDependencies for plugin, nx fails with error
```
.../node_modules/nx/src/hasher/native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: The externalDependency '@front/shared' for 'demo:build-styles' could not be found
    at NativeTaskHasherImpl.hashTasks (.../node_modules/nx/src/hasher/native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (.../node_modules/nx/src/hasher/task-hasher.js:62:50)
    at handleHashTasks (.../node_modules/nx/src/daemon/server/handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (.../node_modules/nx/src/daemon/server/server.js:140:16)
    at async handleMessage (.../node_modules/nx/src/daemon/server/server.js:96:9)
    at async .../node_modules/nx/src/daemon/server/server.js:59:9 {
  code: 'GenericFailure'
}
```

### Expected Behavior

it should not fail, and read information from tsconfig

### Steps to Reproduce

1. create local library
2. specify this library as external dependency for some target in you plugin.

### Nx Report

```shell
Node   : 18.18.2
OS     : darwin-arm64
npm    : 9.8.1

nx                 : 19.5.1
@nx/js             : 19.5.1
@nx/jest           : 19.5.1
@nx/linter         : 19.5.1
@nx/eslint         : 19.5.1
@nx/workspace      : 19.5.1
@nx/angular        : 19.5.1
@nx/cypress        : 19.5.1
@nx/devkit         : 19.5.1
@nx/eslint-plugin  : 19.5.1
@nx/playwright     : 19.5.1
@nx/plugin         : 19.5.1
@nx/storybook      : 19.5.1
@nrwl/tao          : 19.5.1
@nx/web            : 19.5.1
@nx/webpack        : 19.5.1
nx-cloud           : 19.0.0
typescript         : 5.1.6
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@front/nx-i18n
@front/nx-linters
@front/nx-css-utils
---------------------------------------
Community plugins:
@front/angular-builder : 16.2.0
@storybook/angular     : 7.6.20
nx-stylelint           : 17.1.5
---------------------------------------
Local workspace plugins:
         @front/nx-css-utils
         @front/nx-linters
         @front/nx-i18n
         @mono/generators
         @mono/executors
         @mono/utils
```

### Failure Logs

```shell
.../node_modules/nx/src/hasher/native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: The externalDependency '@front/shared' for 'demo:build-styles' could not be found
    at NativeTaskHasherImpl.hashTasks (.../node_modules/nx/src/hasher/native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (.../node_modules/nx/src/hasher/task-hasher.js:62:50)
    at handleHashTasks (.../node_modules/nx/src/daemon/server/handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (.../node_modules/nx/src/daemon/server/server.js:140:16)
    at async handleMessage (.../node_modules/nx/src/daemon/server/server.js:96:9)
    at async .../node_modules/nx/src/daemon/server/server.js:59:9 {
  code: 'GenericFailure'
}
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Maybe this issue could be reproduces without plugin, just specify external dep in nx.json

**Comment by FrozenPandaz** [comment]
Local libraries are not *External* dependencies. External dependencies refer to code which is not in the repo itself such as installed node_modules.

Local library dependencies should be inferred automatically if there are js/ts imports but in the case it isn't and you know it is the case, you can add an implicitDependency: https://nx.dev/reference/project-configuration#implicitdependencies

So this is an improper usage. I'll improve the error though.

**Comment by de-don** [comment]
@FrozenPandaz but if I will use implicitDependencies, it will affect all targets, because I can't specify implicitDependencies for target, only for a project.

**Comment by FrozenPandaz** [comment]
If you would like to not use `implicitDependencies`, you can also use the long form of the `fileset` inputs:

Something like the below would work for that:

```
      "inputs": [
        {
          "input": "e2eInputs",
          "projects": ["local-executor-project"]
        },
        {
          "fileset": "{projectRoot}/src/executors/**/*",
          "projects": ["local-executor-project"]
        }
      ]
```

**Comment by de-don** [comment]
@FrozenPandaz but how I can configure it locally (only for my repo), and not ship this "inputs" to library consumers? 

Like specify common (for consumers) inputs in plugin, and override this locally in nx.json?
