### ISSUE TITLE
Target fails with @nx/rollup:rollup executor on NX 19.5.3

### ISSUE THREAD

**Issue by paperez** [nrwl/nx#27158]
### Current Behavior

After migrating our application to NX version 19.5.3, we encountered an issue where we are unable to run a target with the @nx/rollup/rollup executor. The same codebase builds successfully when using NX version 17.3.2.

### Expected Behavior

The build should succeed as it was doing on Nx 17.3.2.

### GitHub Repo

https://github.com/paperez/nx19-workspace

### Steps to Reproduce

1. Install dependencies
2. Run `nx run app-1:build`

### Nx Report

```shell
Node   : 18.19.1
OS     : darwin-arm64
npm    : 10.2.4

nx (global)        : 19.5.0
nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nx/workspace      : 19.5.3
@nx/angular        : 19.5.3
@nx/cypress        : 19.5.3
@nx/devkit         : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nx/rollup         : 19.5.3
@nrwl/tao          : 19.5.3
@nx/web            : 19.5.3
@nx/webpack        : 19.5.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
Bundling app-1...
[plugin rpt2] apps/app-1/src/loader.ts:1:29 - error TS6059: File '/Users/pedroperez/dev/nx19-workspace/common/lib1/src/index.ts' is not under 'rootDir' '/Users/pedroperez/dev/nx19-workspace/apps/app-1'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via '@nx-19-workspace/common/lib1' from file '/Users/pedroperez/dev/nx19-workspace/apps/app-1/src/loader.ts'
    Root file specified for compilation

1 import { Nx19Library } from '@nx-19-workspace/common/lib1';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


    at getRollupError (/Users/pedroperez/dev/nx19-workspace/node_modules/rollup/dist/shared/parseAst.js:282:41)
    at Object.error (/Users/pedroperez/dev/nx19-workspace/node_modules/rollup/dist/shared/parseAst.js:278:42)
    at Object.error (/Users/pedroperez/dev/nx19-workspace/node_modules/rollup/dist/shared/rollup.js:804:32)
    at RollupContext.error (/Users/pedroperez/dev/nx19-workspace/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:1457:26)
    at /Users/pedroperez/dev/nx19-workspace/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27639:26
    at Array.forEach (<anonymous>)
    at printDiagnostics (/Users/pedroperez/dev/nx19-workspace/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27615:17)
    at typecheckFile (/Users/pedroperez/dev/nx19-workspace/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27972:9)
    at Object.<anonymous> (/Users/pedroperez/dev/nx19-workspace/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:28118:21)
    at Generator.next (<anonymous>)
Bundle failed: app-1
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Working repo 
https://github.com/paperez/nx17-workspace

**Comment by WihteCrow** [comment]
+1

**Comment by bebeto84** [comment]
+1
any updates on this @ndcunningham ?

**Comment by CaueSampaio** [comment]
Any updates? Still happenning on `20.0.1`

**Comment by bebeto84** [comment]
hey guys, I've just migrated our build process to use `@nx/webpack` instead of `@nx/rollup` and with a small configuration webpack file I've made it work.
The only thing it took me there a bit of time was the impossibility to use the `tsconfig.json` file by default on Webpack, so I had to use `tsconfig-paths-webpack-plugin` and refer to the `tsConfig` file on the configuration like the following snippet

```
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = (config, context) => {
  const { options } = context || {};
  const mainFile = options.main;
  return {
    entry: './src/main.ts',
    output: {
      filename: 'bundle.js',
      path: path.resolve(options.root, options.outputPath),
    },
    resolve: {
      extensions: ['.ts', '.js'],
      plugins: [
        new TsconfigPathsPlugin({
          configFile: options.tsConfig,
        }),
      ],
    },
    module: {
      rules: [
        {
          test: /\.ts$/,
          use: 'ts-loader',
          exclude: /node_modules/,
        },
      ],
    },
  };
};
```
