### ISSUE TITLE
Can't generate storybook config

### ISSUE THREAD

**Issue by TheDevelolper** [nrwl/nx#27170]
### Current Behavior

Fails with error: `Cannot read properties of null (reading 'useInferencePlugins')`

### Expected Behavior

Should generate storybook config

### Steps to Reproduce

1. Create a new Nx Monorepo with React
2. Create a UI library project
3. run `bun nx g @nx/react:storybook-configuration ui-components --verbose`
4. Observe the error

### Nx Report

```shell
bun nx g @nx/react:storybook-configuration ui-components --verbose

 NX  Generating @nx/react:storybook-configuration

√ Do you want to set up Storybook interaction tests? (Y/n) · true
√ Automatically generate *.stories.ts files for components declared in this project? (Y/n) · true
√ Configure a static file server for the storybook instance? (Y/n) · true

 NX   Cannot read properties of null (reading 'useInferencePlugins')


TypeError: Cannot read properties of null (reading 'useInferencePlugins')
    at storybookConfigurationGeneratorInternal (Q:\repos\octo-menu-rebuild-worktree\node_modules\@nx\react\src\generators\storybook-configuration\configuration.js:34:16)
    at Q:\repos\octo-menu-rebuild-worktree\node_modules\nx\src\command-line\generate\generate.js:241:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (Q:\repos\octo-menu-rebuild-worktree\node_modules\nx\src\utils\params.js:22:24)
    at async Object.handler (Q:\repos\octo-menu-rebuild-worktree\node_modules\nx\src\command-line\generate\command-object.js:13:22)
```

### Package Manager Version

10.8.1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Full Nx report:

nx report

 NX   Report complete - copy this into the issue template

Node   : 18.20.2
OS     : win32-x64
npm    : 10.8.1

nx (global)        : 19.5.3
nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nx/workspace      : 19.5.3
@nx/cypress        : 19.5.3
@nx/devkit         : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nx/playwright     : 19.5.3
@nx/react          : 19.5.3
@nrwl/tao          : 19.5.3
@nx/vite           : 19.5.3
@nx/web            : 19.5.3
typescript         : 5.5.4

**Comment by TheDevelolper** [comment]
I realise now that I was in the parent directory and this is why the command failed. However I now have the issue where running: 
```bun nx g @nx/react:storybook-configuration ui-components --verbose```

just seems to hang!

**Comment by Coly010** [comment]
Can you try with `npx`? I want to rule out `bun` being the problem here

**Comment by TheDevelolper** [comment]
Sorry, I already solved this one, I think I may have done it with npx as you suggested.
