### ISSUE TITLE
Error: EPERM: operation not permitted, unlink '\.nx\workspace-data\d\daemon.log'

### ISSUE THREAD

**Issue by jahusa02** [nrwl/nx#27180]
### Current Behavior

Can't delete .nx folder or resetting nx via `nx reset`

I can't even open daemon.log because:

![grafik](https://github.com/user-attachments/assets/7fa19b82-697a-4139-ad08-0befbe6bf83e)

### Expected Behavior

daemon.log should be deletable

### Steps to Reproduce

1. run `nx reset` 

### Nx Report

```shell
Node   : 20.16.0
OS     : win32-x64
npm    : 10.8.2

nx (global)        : 19.5.3
nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nx/workspace      : 19.5.3
@nx/angular        : 19.5.3
@nx/cypress        : 19.5.3
@nx/devkit         : 19.5.3
@nx/esbuild        : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nx/express        : 19.5.3
@nx/node           : 19.5.3
@nrwl/tao          : 19.5.3
@nx/vite           : 19.5.3
@nx/web            : 19.5.3
@nx/webpack        : 19.5.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/cypress/plugin
@nx/vite/plugin
---------------------------------------
Community plugins:
@analogjs/vite-plugin-angular : 1.6.4
@analogjs/vitest-angular      : 1.6.4
@jsverse/transloco            : 7.4.3
@koliveira15/nx-sonarqube     : 4.1.0
@ngrx/component-store         : 18.0.1
@ngrx/effects                 : 18.0.1
@ngrx/entity                  : 18.0.1
@ngrx/eslint-plugin           : 18.0.1
@ngrx/operators               : 18.0.1
@ngrx/router-store            : 18.0.1
@ngrx/schematics              : 18.0.1
@ngrx/store                   : 18.0.1
@ngrx/store-devtools          : 18.0.1
@nx-tools/nx-container        : 6.0.1
ng-mocks                      : 14.13.0
ngx-matomo-client             : 6.3.0
---------------------------------------
⚠️ Unable to construct project graph.
EPERM: operation not permitted, open 'H:\PROJECT\.nx\workspace-data\d\daemon.log'
Error: EPERM: operation not permitted, open 'H:\PROJECT\.nx\workspace-data\d\daemon.log'
    at Object.writeFileSync (node:fs:2368:20)
    at createFileSync (H:\PROJECT\node_modules\fs-extra\lib\ensure\file.js:60:6)
    at DaemonClient.startInBackground (H:\PROJECT\node_modules\nx\src\daemon\client\client.js:363:39)
    at DaemonClient.sendMessageToDaemon (H:\PROJECT\node_modules\nx\src\daemon\client\client.js:316:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async H:\PROJECT\node_modules\nx\src\utils\promised-based-queue.js:19:21
```

### Failure Logs

```shell
[Error: EPERM: operation not permitted, unlink 'H:\PROJECT\.nx\workspace-data\d\daemon.log'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'H:\\PROJECT\\.nx\\workspace-data\\d\\daemon.log'
}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

@MaxKless 

in https://github.com/nrwl/nx/issues/11624 you said we should ping you if it happens again

**Comment by MaxKless** [comment]
Thanks for the report @jahusa02! 
It's actually a slightly different error and we're aware of it. For now you have to manually kill all nx processes and try again. We're looking into the proper fix here https://github.com/nrwl/nx/issues/27006

**Comment by MaxKless** [comment]
For now you can set `NX_ISOLATE_PLUGINS=false` in your root `.env` and it should fix it.
