### ISSUE TITLE
Intermittent issue: "Failed to process project graph."

### ISSUE THREAD

**Issue by nsmith7989** [nrwl/nx#27213]
### Current Behavior

We have an intermittent issue in our pipelines, specifically when running DTE mode. Intermittently, we run into "Failed to process project graph" on some tasks. 

Full message, with verbose logging turned on.

```
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  The "nx/js/dependencies-and-lockfile" plugin threw an error while creating dependencies:
    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at readCachedParsedLockFile (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/plugins/js/index.js:104:17)
        at Object.createDependencies (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/plugins/js/index.js:72:36)
        at LoadedNxPlugin.createDependencies (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/project-graph/plugins/internal-api.js:60:59)
        at createDependencies (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:73:49)
        at consumeMessage (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:37:32)
        at /builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:21:47
        at Socket.<anonymous> (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/utils/consume-messages-from-socket.js:13:17)
        at Socket.emit (node:events:519:28)
        at addChunk (node:internal/streams/readable:559:12)
```

Tracing [this back into the nx codebase](https://github.com/nrwl/nx/blob/c400ea3002eba058d4e4ca02b3b5144ace306f15/packages/nx/src/plugins/js/index.ts#L162)

I was able to capture the file I believe this is reading (`.nx/workspace-data/parsed-lock-file.json`) and it appears to be valid JSON. Attaching here. 
[parsed-lock-file (1).json](https://github.com/user-attachments/files/16429839/parsed-lock-file.1.json)

### Expected Behavior

Project graph should process correctly

### Steps to Reproduce

Unfortunately I don't have consistently reproducible steps. This happens intermittently on CI when running DTE. 

### Nx Report

```shell
Node   : 20.15.1
OS     : linux-x64
pnpm   : 9.5.0
nx                 : 19.5.2
@nx/js             : 19.5.2
@nx/jest           : 19.5.2
@nx/linter         : 19.5.2
@nx/eslint         : 19.5.2
@nx/workspace      : 19.5.2
@nx/cypress        : 19.5.2
@nx/devkit         : 19.5.2
@nx/esbuild        : 19.5.2
@nx/eslint-plugin  : 19.5.2
@nx/express        : 19.5.2
@nx/next           : 19.5.2
@nx/node           : 19.5.2
@nx/plugin         : 19.5.2
@nx/react          : 19.5.2
@nx/rollup         : 19.5.2
@nx/storybook      : 19.5.2
@nrwl/tao          : 19.5.2
@nx/web            : 19.5.2
@nx/webpack        : 19.5.2
typescript         : 5.4.3
---------------------------------------
Registered Plugins:
./libs/plugins/ohw-next/src/plugin/cypress.ts
---------------------------------------
Local workspace plugins:
	 @dx-ui/plugins-ohw-next
```

### Failure Logs

```shell
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  The "nx/js/dependencies-and-lockfile" plugin threw an error while creating dependencies:
    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at readCachedParsedLockFile (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/plugins/js/index.js:104:17)
        at Object.createDependencies (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/plugins/js/index.js:72:36)
        at LoadedNxPlugin.createDependencies (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/project-graph/plugins/internal-api.js:60:59)
        at createDependencies (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:73:49)
        at consumeMessage (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:37:32)
        at /builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:21:47
        at Socket.<anonymous> (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.9_typ_34zaltkvweqg6w6zkb34rm3w24/node_modules/nx/src/utils/consume-messages-from-socket.js:13:17)
        at Socket.emit (node:events:519:28)
        at addChunk (node:internal/streams/readable:559:12)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

`SyntaxError: Unexpected end of JSON input` seems to happen when calling JSON.parse on an empty string: `JSON.parse('')`

Since this is intermittent, I'm wondering if there is a race condition where this cachedParsedLock file is getting written and rewritten and happened to be blank at certain times. 

I'd be happy with logging the contents of the file, if an error is thrown, or trying to recreate the parsedLockFile on an error rather than throwing an unrecoverable error. 

### CI Scripts

```
pnpm nx-cloud start-ci-run
pnpm nx affected -t lint --quiet --parallel=3 --base=$NX_BASE --head=$NX_HEAD &
pnpm nx affected -t build --parallel=1 --base=$NX_BASE --head=$NX_HEAD &
# more tasks... same pattern, sending job to background with `&`
```

**Comment by nsmith7989** [comment]
I was able to add some more logging around these lines using [pnpm patch](https://pnpm.io/cli/patch). 

My changes added console.logs in `writeLasProcessedLockfileHash` each time this function is called across (even when in multiple processes). I also added a log if `readCachedParsedLockFile` after reading the file gets an empty string. 

My logs, when this error occurs are

```
DEBUG: writeLasProcessedLockfileHash
DEBUG: writeLasProcessedLockfileHash
DEBUG: writeLasProcessedLockfileHash

DEBUG: reading cached data returned an empty string! Error
    at readCachedParsedLockFile (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_patch_hash=pf65qfcdf7jg5c6ybhp6hdwnsa_@swc-node+register@1.9.2_@swc+core@1.5.29_@sw_icftkdthzpvidwm5gipyth4zmm/node_modules/nx/src/plugins/js/index.js:144:19)
    at Object.createDependencies (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_patch_hash=pf65qfcdf7jg5c6ybhp6hdwnsa_@swc-node+register@1.9.2_@swc+core@1.5.29_@sw_icftkdthzpvidwm5gipyth4zmm/node_modules/nx/src/plugins/js/index.js:93:30)
    at LoadedNxPlugin.createDependencies (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_patch_hash=pf65qfcdf7jg5c6ybhp6hdwnsa_@swc-node+register@1.9.2_@swc+core@1.5.29_@sw_icftkdthzpvidwm5gipyth4zmm/node_modules/nx/src/project-graph/plugins/internal-api.js:60:59)
    at createDependencies (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_patch_hash=pf65qfcdf7jg5c6ybhp6hdwnsa_@swc-node+register@1.9.2_@swc+core@1.5.29_@sw_icftkdthzpvidwm5gipyth4zmm/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:73:49)
    at consumeMessage (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_patch_hash=pf65qfcdf7jg5c6ybhp6hdwnsa_@swc-node+register@1.9.2_@swc+core@1.5.29_@sw_icftkdthzpvidwm5gipyth4zmm/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:37:32)
    at /builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_patch_hash=pf65qfcdf7jg5c6ybhp6hdwnsa_@swc-node+register@1.9.2_@swc+core@1.5.29_@sw_icftkdthzpvidwm5gipyth4zmm/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:21:47
    at Socket.<anonymous> (/builds/pac/hiw/dx-ui/node_modules/.pnpm/nx@19.5.2_patch_hash=pf65qfcdf7jg5c6ybhp6hdwnsa_@swc-node+register@1.9.2_@swc+core@1.5.29_@sw_icftkdthzpvidwm5gipyth4zmm/node_modules/nx/src/utils/consume-messages-from-socket.js:13:17)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
DEBUG: error SyntaxError: Unexpected end of JSON input
DEBUG: data 

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

 ELIFECYCLE  Command failed with exit code 1.
```

When this error does NOT occur, my logs look like

```
DEBUG: writeLastProcessedLockfileHash lockFile contents
```

## Current theory
When this error occurs, it is always proceeded by 2 or more calls to `writeLastProcessedLockfileHash`, and then a failed to parse JSON. 

What I believe is happening is a race condition where several processes (due to running multiple nx affected jobs and sending to the background with `&`) all try to generate a lockfile and hash at the same time and the data gets corrupted/truncated. 

Here is what I believe is happening: 

Process A and Process B open the file:

Process A opens parsed-lock-file.json in write mode ('w').
Process B opens parsed-lock-file.json in write mode ('w').
Process A writes data:

Process A starts writing data to the file.
Process B truncates the file:

Before Process A finishes writing, Process B truncates the file (because it opened in 'w' mode), resetting the file length to zero.
Process A completes writing:

Process A completes its write operation, but since Process B truncated the file, only part of the data might be written, or none at all if the truncation happened right after opening.
File appears empty:

If the timing is such that Process B truncates the file and either process doesn't complete its write operation properly, the file ends up being empty.

**Comment by nsmith7989** [comment]
@AgentEnder / @FrozenPandaz I'm happy to open a PR with a fix for this. 

Some options I was thinking of:

1. A file lock
2. In `lockFileNeedsReprocessing` try to read `parsed-lock-file.json` / json parse it. If that fails, return `true` meaning the lockfile should be reprocessed. 

If you have other ideas or guidance please let me know. 

cc @philipjfulcher

**Comment by FrozenPandaz** [comment]
We'll take a look into this issue. Thank you for all the details for how to reproduce it.

**Comment by nsmith7989** [comment]
Our workaround right now is to add one job that does NOT run in the background to avoid this race condition. 

```
pnpm nx-cloud record -- pnpm nx format:check --base=$NX_BASE --head=$NX_HEAD
pnpm nx-cloud start-ci-run
pnpm nx affected -t lint --quiet --parallel=3 --base=$NX_BASE --head=$NX_HEAD &
pnpm nx affected -t build --parallel=1 --base=$NX_BASE --head=$NX_HEAD &
```
Note that format check does NOT run in the background to avoid this race condition.

**Comment by tonivj5** [comment]
I've experimenting exactly the same problem. I must run `nx reset` so many times, it happens mostly when I'm moving files or renaming them

**Comment by mrfelton** [comment]
Also happening to us randomly on CI.

**Comment by galah92** [comment]
Same here - we tried to update to 19.7.3 and started getting these while running GitHub Actions workflows in parallel. We do not use Nx Cloud.
Any workaround for this?

**Comment by ryan-mcginty-alation** [comment]
I have been getting this intermittent message as well on CI/CD and locally, but only after migrating to Nx 20 and switching to inferred tasks. Before switching to inferred tasks I never received this message.
