### ISSUE TITLE
NX Storybook Plugin Error: Failed to Process Project Graph [Nx 18.3.4]

### ISSUE THREAD

**Issue by akibarika** [nrwl/nx#27257]
### Current Behavior

running `yarn nx affected --base=.... --head=.... --target=lint --verbose` on the ADO pipeline, results in this error:
```
NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  An error occurred while processing files for the @nx/storybook/plugin plugin.
    - .storybook/main.ts: Cannot find module 'node_modules/@core/dist/index.cjs'. Please verify that the package.json has a valid "main" entry
      Error: Cannot find module 'node_modules/@core/dist/index.cjs'. Please verify that the package.json has a valid "main" entry
          at tryPackage (node:internal/modules/cjs/loader:436:19)
          at Function.Module._findPath (node:internal/modules/cjs/loader:678:18)
          at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
          at Function.Module._resolveFilename (node_modules/tsconfig-paths/src/register.ts:115:36)
          at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
          at Function.resolve (node:internal/modules/cjs/helpers:116:19)
          at .storybook/utils.ts:39:42
          at Array.flatMap (<anonymous>)
          at getStoriesConfigForMonorepoPackages (.storybook/utils.ts:37:16)
          at Object.<anonymous> (.storybook/main.ts:20:51)
```

I tried upgrading Nx one version at a time:
- 18.3.0 to 18.3.3: all worked fine both locally and on ADO
- Having this issue with Nx18.3.4, 18.3.5 and 19.5.4 on ADO, but worked fine locally

`./storybook/project.json`

```json
"lint": {
  "executor": "@nx/eslint:lint",
  "outputs": ["{options.outputFile}"],
  "options": {
    "lintFilePatterns": ["apps/storybook/**/*.{ts,tsx,js,jsx}"]
  }
}
```

I also checked the package.json file in @core module locally and index.cjs was there as well
`@core/package.json`

```json
{
  "name": "@core",
  "version": "2.0.0",
  "main": "dist/index.cjs",
  "module": "dist/index.js",
  "type": "module",
  "types": "dist/index.d.ts",
  "files": [
    "dist/**/*"
  ]
}
```

### Expected Behavior

The command that was working before 18.3.4 should still work without any changes necessary.

### Steps to Reproduce

1. See above for relevant config sections required
2. Execute the target using nx via any command (eg: nx run)

### Nx Report

```shell
Node   : 20.15.1
OS     : darwin-arm64
yarn   : 3.6.4

nx                 : 18.3.4
@nx/js             : 18.3.4
@nx/linter         : 18.3.4
@nx/eslint         : 18.3.4
@nx/workspace      : 18.3.4
@nx/cypress        : 18.3.4
@nx/devkit         : 18.3.4
@nx/eslint-plugin  : 18.3.4
@nx/react          : 18.3.4
@nx/storybook      : 18.3.4
@nrwl/tao          : 13.8.3
@nx/vite           : 18.3.4
@nx/web            : 18.3.4
@nx/webpack        : 18.3.4
typescript         : 5.0.4
---------------------------------------
Registered Plugins:
@nx/storybook/plugin
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/tao@13.8.3

To fix this, run `nx migrate nx@18.3.4`
```

### Failure Logs

```shell
NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  An error occurred while processing files for the @nx/storybook/plugin plugin.
    - .storybook/main.ts: Cannot find module 'node_modules/@core/dist/index.cjs'. Please verify that the package.json has a valid "main" entry
      Error: Cannot find module 'node_modules/@core/dist/index.cjs'. Please verify that the package.json has a valid "main" entry
          at tryPackage (node:internal/modules/cjs/loader:436:19)
          at Function.Module._findPath (node:internal/modules/cjs/loader:678:18)
          at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
          at Function.Module._resolveFilename (node_modules/tsconfig-paths/src/register.ts:115:36)
          at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
          at Function.resolve (node:internal/modules/cjs/helpers:116:19)
          at .storybook/utils.ts:39:42
          at Array.flatMap (<anonymous>)
          at getStoriesConfigForMonorepoPackages (.storybook/utils.ts:37:16)
          at Object.<anonymous> (.storybook/main.ts:20:51)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by akibarika** [comment]
I believe the fix might be related to this pull request: https://github.com/nrwl/nx/pull/23068. However, I am still encountering the issue now.

Another thought on @nrwl/tao@13.8.3: Even after running `nx migrate nx@18.3.4`, the version won't change.

ty

**Comment by Coly010** [comment]
@akibarika I'll see what I can discover after some investigation.

The `@nrwl/tao` package is no longer used and can safely be removed if you have the `nx` package installed at the correct version for your workspace.

**Comment by Coly010** [comment]
@akibarika Is there any way you can provide a minimal reproduction of this issue? I've been unable to reproduce it myself. From your error, it seems like storybook is resolving your package to your node_modules, rather than local system, which could indicate that a TS Paths plugin is missing somewhere in your storybook config. But that's a guess and I can't investigate further without some kind of reproduction

**Comment by akibarika** [comment]
Hi @Coly010, thanks for that. The team and I have decided to stay on version 18.3.4 for now. I will review the resolution you provided and update you later. Thanks!

**Comment by nhhockeyplayer** [comment]
Im receiving this now

any tips appreciated

tried to hand edit the storybook configs... only 2 of them
to no avail


```
 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

meanstack02@admin meanstacknh % nx reset

 NX   Resetting the Nx cache and stopping the daemon.



 NX   Cleaning up temporary files created by Nx Cloud.

meanstack02@admin meanstacknh % nx report

 NX   Report complete - copy this into the issue template

Node           : 22.4.1
OS             : darwin-x64
Native Target  : x86_64-macos
yarn           : 1.22.22

nx (global)        : 19.4.3
nx                 : 19.8.3
@nx/js             : 19.8.3
@nx/jest           : 19.8.3
@nx/linter         : 19.8.3
@nx/eslint         : 19.8.3
@nx/workspace      : 19.8.3
@nx/angular        : 19.8.3
@nx/cypress        : 19.8.3
@nx/devkit         : 19.8.3
@nrwl/devkit       : 13.10.6
@nx/eslint-plugin  : 19.8.3
@nx/express        : 19.8.3
@nx/nest           : 19.8.3
@nx/node           : 19.8.3
@nx/storybook      : 19.8.3
@nrwl/tao          : 19.8.3
@nx/web            : 19.8.3
@nx/webpack        : 19.8.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
@nx/storybook/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc                    : 1.1.25
@fortawesome/angular-fontawesome      : 0.15.0
@ionic/angular                        : 6.7.5
@jsverse/transloco                    : 7.5.0
@ngrx/component                       : 18.0.2
@ngrx/component-store                 : 18.0.2
@ngrx/effects                         : 18.0.2
@ngrx/entity                          : 18.0.2
@ngrx/operators                       : 18.0.2
@ngrx/router-store                    : 18.0.2
@ngrx/schematics                      : 18.0.2
@ngrx/store                           : 18.0.2
@ngrx/store-devtools                  : 18.0.2
@nxtend/capacitor                     : 13.0.0
@nxtend/ionic-angular                 : 13.1.0
@storybook/angular                    : 8.3.4
angular-builder-custom-terser-options : 1.0.1
apollo-angular                        : 7.2.0
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@13.10.6

To fix this, run `nx migrate nx@19.8.3`
---------------------------------------
⚠️ Unable to construct project graph.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/storybook/plugin plugin.
    - .storybook/main.js: Cannot read properties of undefined (reading 'name')
      TypeError: Cannot read properties of undefined (reading 'name')
          at getStorybookFramework (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/plugins/plugin.js:180:66)
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
          at buildStorybookTargets (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/plugins/plugin.js:66:32)
          at exports.createNodes (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/plugins/plugin.js:51:32)
          at /Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/utils.js:47:27
          at async Promise.all (index 0)
          at createNodesFromFiles (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/utils.js:45:5)
          at Array.LoadedNxPlugin.createNodes.<computed> (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/internal-api.js:44:28)
          at createNodes (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:69:36)
          at consumeMessage (/Users/meanstack02/meanstacknh/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:38:26)
    - apps/admin/.storybook/main.js: rootMain.stories is not iterable
      TypeError: rootMain.stories is not iterable
          at Object.<anonymous> (/Users/meanstack02/meanstacknh/apps/admin/.storybook/main.js:9:21)
          at Module._compile (node:internal/modules/cjs/loader:1467:14)
          at Object.Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
          at Module.load (node:internal/modules/cjs/loader:1282:32)
          at Function.Module._load (node:internal/modules/cjs/loader:1098:12)
          at TracingChannel.traceSync (node:diagnostics_channel:315:14)
          at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
          at Module.require (node:internal/modules/cjs/loader:1304:12)
          at require (node:internal/modules/helpers:123:16)
          at load (/Users/meanstack02/meanstacknh/node_modules/@nx/devkit/src/utils/config-utils.js:76:16)
    - libs/shared/root/ui-widget/.storybook/main.js: rootMain.stories is not iterable
      TypeError: rootMain.stories is not iterable
          at Object.<anonymous> (/Users/meanstack02/meanstacknh/libs/shared/root/ui-widget/.storybook/main.js:9:21)
          at Module._compile (node:internal/modules/cjs/loader:1467:14)
          at Object.Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
          at Module.load (node:internal/modules/cjs/loader:1282:32)
          at Function.Module._load (node:internal/modules/cjs/loader:1098:12)
          at TracingChannel.traceSync (node:diagnostics_channel:315:14)
          at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
          at Module.require (node:internal/modules/cjs/loader:1304:12)
          at require (node:internal/modules/helpers:123:16)
          at load (/Users/meanstack02/meanstacknh/node_modules/@nx/devkit/src/utils/config-utils.js:76:16)

meanstack02@admin meanstacknh % 

```

**Comment by nhhockeyplayer** [comment]
seems now hurdles when trying to build now

everything use to build seamless 6mo ago

**Comment by nhhockeyplayer** [comment]
storybook refuses to migrate on simple @latest

```
error Command "storybook@latest" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 NX   Migration failed

🚨 The Storybook CLI failed to upgrade your @storybook/* packages to the latest version.
Please try running the sb upgrade command manually:
yarn storybook@latest upgrade

Error: Command failed: yarn storybook@latest upgrade --yes
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:889:11)
    at execSync (node:child_process:961:15)
    at callUpgrade (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/generators/migrate-8/calling-storybook-cli.js:18:38)
    at migrate8Generator (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/generators/migrate-8/migrate-8.js:26:49)
    at changeStorybookTargets (/Users/meanstack02/meanstacknh/node_modules/@nx/storybook/src/migrations/update-19-6-0/update-sb-8.js:29:36)
    at runNxMigration (/Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/migrate/migrate.js:1036:11)
    at executeMigrations (/Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/migrate/migrate.js:921:39)
    at runMigrations (/Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/migrate/migrate.js:1009:43) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 76958,
  stdout: null,
  stderr: null
}

 NX   ⚙️ Calling sb automigrate

ℹ️  
```
