### ISSUE TITLE
bug "nx init" script on Windows

### ISSUE THREAD

**Issue by sacru2red** [nrwl/nx#27331]
### Current Behavior

nx init fails

### Expected Behavior

no errors

### Steps to Reproduce

1. run `nx init` on windows

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.15.1
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.7.0

nx (global)    : 19.5.7
nx             : 19.5.7
@nx/js         : 19.5.7
@nx/linter     : 19.5.7
@nx/eslint     : 19.5.7
@nx/workspace  : 19.5.7
@nx/devkit     : 19.5.7
@nrwl/tao      : 19.5.7
typescript     : 5.4.5
```

### Failure Logs

```shell
$ nx init
Setting Nx up installation in `.nx`. You can run Nx commands like: `./nx.bat --help`

 NX   Recommended Plugins:

Add these Nx plugins to integrate with the tools used in your workspace.

√ Which plugins would you like to add? Press <Space> to select and <Enter> to submit. · @nx/eslint, @nx/webpack, @nx/jest, @nx/next
'.'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
nx init

Adds Nx to any type of workspace. It installs nx, creates an nx.json configuration file and optionally sets up remote caching. For more
info, check https://nx.dev/recipes/adopting-nx.

Options:
  --help                  Show help                                                                                           [boolean]
  --version               Show version number                                                                                 [boolean]
  --nxCloud               Set up distributed caching with Nx Cloud.                                                           [boolean]
  --interactive           When false disables interactive input prompts for options.                          [boolean] [default: true]
  --useDotNxInstallation  Initialize an Nx workspace setup in the .nx directory of the current repository.   [boolean] [default: false]

Error: Command failed: ./nx add @nx/eslint
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at C:\Users\...\node_modules\nx\src\command-line\init\init-v2.js:36:42
    at Array.forEach (<anonymous>)
    at Object.initHandler (C:\Users\...\node_modules\nx\src\command-line\init\init-v2.js:35:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (C:\Users\...\node_modules\nx\src\command-line\init\command-object.js:14:13) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 22232,
  stdout: null,
  stderr: null
}
```

### Package Manager Version

npm@10.7.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

https://github.com/nrwl/nx/blob/333ab7708fbb0af8fe06e2f8462de9cd39f24843/packages/nx/src/command-line/init/init-v2.ts#L55

fix to 
```js
(0, child_process_2.execSync)(`.\\nx add ${plugin}`, {
                stdio: 'inherit',
            });
```

like https://github.com/nrwl/nx/blob/333ab7708fbb0af8fe06e2f8462de9cd39f24843/packages/nx/src/utils/child-process.ts#L51

ps.
It is not related to this issue, but in my personal opinion, it would be better to check if package.json exists before running the init script, and if not, warn and exit.

**Comment by AgentEnder** [comment]
Fixed in #27364
