### ISSUE TITLE
Failed to process the project graph with "nx-js-graph-plugin" when migrating NX from 16.7.2 to 16.7.4

### ISSUE THREAD

**Issue by chess1** [nrwl/nx#27372]
### Current Behavior

I have a module federation project using RSBuild, Nx, and Yarn workspaces. As part of upgrading Nx, I am encountering issues migrating from version 16.7.2 to 16.7.4, which will cause:
```
>  NX   Failed to process the project graph with "nx-js-graph-plugin".

   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```   

The ultimate goal is to step by step migrate to the latest version of Nx.

### Expected Behavior

NX will process the project dependencies correctly.

### Steps to Reproduce

1. `yarn nx migrate 16.7.4`
2. `yarn`
3. `yarn nx graph`

### Nx Report

```shell
Node   : 21.6.1
   OS     : darwin-arm64
   yarn   : 3.5.1
   
   nx          : 16.7.2
   @nrwl/tao   : 16.7.2
   typescript  : 5.5.3
```

### Failure Logs

```shell
[NX Daemon Server] - 2024-08-12T08:16:40.611Z - Started listening on: /var/folders/qh/bl8p0rl13gvg23nj8fh9d3h00000gn/T/72d6b182bb2739e4e06d/d.sock
[NX Daemon Server] - 2024-08-12T08:16:40.618Z - [WATCHER]: Subscribed to changes within: /path/to/project (native)
[NX Daemon Server] - 2024-08-12T08:16:40.620Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-08-12T08:16:40.622Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-08-12T08:16:40.623Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-08-12T08:16:40.626Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-08-12T08:16:40.949Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2024-08-12T08:16:40.949Z - [REQUEST]: 
[NX Daemon Server] - 2024-08-12T08:16:40.949Z - [REQUEST]: 

 >  NX   Failed to parse yarn lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   
Original error: Source project does not exist: npm:regraph@file:dist/external/regraph-4.2.0+subscription-2024-08-01.tgz::locator=<hash>


   Error: Source project does not exist: npm:regraph@file:dist/external/regraph-4.2.0+subscription-2024-08-01.tgz::locator=<hash>
    at validateCommonDependencyRules (/path/to/project/node_modules/nx/src/project-graph/project-graph-builder.js:280:15)
    at validateDependency (/path/to/project/node_modules/nx/src/project-graph/project-graph-builder.js:275:5)
    at ProjectGraphBuilder.addDependency (/path/to/project/node_modules/nx/src/project-graph/project-graph-builder.js:162:9)
    at ProjectGraphBuilder.addStaticDependency (/path/to/project/node_modules/nx/src/project-graph/project-graph-builder.js:79:14)
    at /path/to/project/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:182:41
    at Array.forEach (<anonymous>)
    at /path/to/project/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:178:49
    at Array.forEach (<anonymous>)
    at /path/to/project/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:176:72
    at Array.forEach (<anonymous>)

[NX Daemon Server] - 2024-08-12T08:16:42.784Z - Error detected when creating a project graph: Failed to process the project graph with "nx-js-graph-plugin".
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
[NX Daemon Server] - 2024-08-12T08:16:42.784Z - [REQUEST]: Responding to the client with an error. Error when preparing serialized project graph. Failed to process the project graph with "nx-js-graph-plugin".
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: Failed to process the project graph with "nx-js-graph-plugin".
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at writeFileSync (node:fs:2351:5)
    at writeLastProcessedLockfileHash (/path/to/project/node_modules/nx/src/plugins/js/index.js:53:28)
    at /path/to/project/node_modules/nx/src/plugins/js/index.js:26:17
    at Generator.next (<anonymous>)
    at /path/to/project/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/path/to/project/node_modules/tslib/tslib.js:165:16)
    at Object.processProjectGraph (/path/to/project/node_modules/nx/src/plugins/js/index.js:16:57)
    at /path/to/project/node_modules/nx/src/project-graph/build-project-graph.js:138:42
    at Generator.next (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[NX Daemon Server] - 2024-08-12T08:16:42.786Z - Done responding to the client null

```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

We have a dependency entry for a package called regraph. (which is a dependency of an internal versioned package we use in my organization).
The version of regraph specified here is 4.2.0+subscription-2024-08-01 and is obtained from a specific file located at dist/external/regraph-4.2.0+subscription-2024-08-01.tgz.

**Comment by FrozenPandaz** [comment]
v16 is quite old and there have been many bug fixes in that area since. Could you please try updating further to v18 or v19 to see if the issue goes away please?

**Comment by chess1** [comment]
> v16 is quite old and there have been many bug fixes in that area since. Could you please try updating further to v18 or v19 to see if the issue goes away please?

Hi @FrozenPandaz 
Thanks for replying!

Unfortunately that didn't do the trick for me.
I tried migrating to 18.3.5 using the command: 
`yarn nx migrate latest --from=nx@16.7.2 --to=nx@18.3.5  --exclude-applied-migrations`.

Which causes a failure in processing the graph:
```
> yarn nx graph --verbose

 NX   Failed to process project graph. See errors below.

Failed to process project graph.
  The "nx/js/dependencies-and-lockfile" plugin threw an error while creating dependencies:
    Error: Source project does not exist: npm:regraph@file:dist/external/regraph-4.2.0+subscription-2024-08-01.tgz::locator=%40cisco-eti%2Flight-ui-framework%40npm%3A1.1.2%3A%3A__archiveUrl%3Dhttps%253A%252F%252Fnpm.pkg.github.com%252Fdownload%252F%2540cisco-eti%252Flight-ui-framework%252F1.1.2%252F39ec48e1d87b5d1919348a3a2eccb524a8372bd4
        at validateCommonDependencyRules (/Users/idora/WebstormProjects/cisco-eti/cnapp-ui/node_modules/nx/src/project-graph/project-graph-builder.js:318:15)
        at validateDependency (/Users/idora/WebstormProjects/cisco-eti/cnapp-ui/node_modules/nx/src/project-graph/project-graph-builder.js:313:5)
        at /Users/idora/WebstormProjects/cisco-eti/cnapp-ui/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:214:80
        at Array.forEach (<anonymous>)
        at /Users/idora/WebstormProjects/cisco-eti/cnapp-ui/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:205:49
        at Array.forEach (<anonymous>)
        at /Users/idora/WebstormProjects/cisco-eti/cnapp-ui/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:203:72
        at Array.forEach (<anonymous>)
        at /Users/idora/WebstormProjects/cisco-eti/cnapp-ui/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:200:26
        at Array.forEach (<anonymous>)
```

P.S
Also tried to migrate to the latest and encountering the same error.

**Comment by idonava** [comment]
Hi guys (@AgentEnder),
Any news on this issue?
