### ISSUE TITLE
Running migration `update-19-6-0-update-ci-webserver-for-vite` fails with `matchingPluginRegistrations is not iterable`

### ISSUE THREAD

**Issue by KeithGillette** [nrwl/nx#27498]
### Current Behavior

Migrating an `nx@19.5.7` workspace to `nx@19.6.0` fails with:

```
Running migration @nx/cypress: update-19-6-0-update-ci-webserver-for-vite

 NX   Failed to run update-19-6-0-update-ci-webserver-for-vite from @nx/cypress. This workspace is NOT up to date!

 NX   matchingPluginRegistrations is not iterable
```

We have Cypress installed but are not actually currently using it in any projects. We do not use Vite or React.

### Expected Behavior

Migration should work without error.

### Steps to Reproduce

```
nx migrate latest
npm install
npx nx migrate --run-migrations
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.15.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.7.0

nx             : 19.6.0
@nx/js         : 19.6.0
@nx/jest       : 19.6.0
@nx/linter     : 19.6.0
@nx/eslint     : 19.6.0
@nx/workspace  : 19.6.0
@nx/angular    : 19.6.0
@nx/cypress    : 19.6.0
@nx/devkit     : 19.6.0
@nx/node       : 19.6.0
@nrwl/tao      : 19.6.0
@nx/web        : 19.6.0
@nx/webpack    : 19.6.0
typescript     : 5.5.4
---------------------------------------
Community plugins:
apollo-angular : 7.0.2
```

### Failure Logs

```shell
npx nx migrate --run-migrations --verbose

 NX   Running 'npm install' to make sure necessary packages are installed


> project-name@1.20.1 postinstall
> node tools/decorate-angular-cli.js


 NX   Decoration of the Angular CLI is deprecated and will be removed in a future version

Please replace usage of "ng <command>" in any scripts, particularly for CI, with "nx <command>"


 NX   Angular CLI has been decorated to enable computation caching.


up to date, audited 3675 packages in 3s

360 packages are looking for funding
  run `npm fund` for details

38 vulnerabilities (4 low, 19 moderate, 15 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

 NX   ENOENT: no such file or directory, open '/path/to/workspace/.nx/workspace-data/d/server-process.json'


 NX   Running migrations from 'migrations.json'

Running the following migrations:
- @nx/cypress: update-19-6-0-update-ci-webserver-for-vite (Update ciWebServerCommand to use static serve for the application.)
- @nx/angular: update-19-6-0 (Ensure Module Federation DTS is turned off by default.)
- @nx/angular: update-angular-cli-version-18-2-0 (Update the @angular/cli package version to ~18.2.0.)
---------------------------------------------------------

Running migration @nx/cypress: update-19-6-0-update-ci-webserver-for-vite

 NX   Failed to run update-19-6-0-update-ci-webserver-for-vite from @nx/cypress. This workspace is NOT up to date!


 NX   matchingPluginRegistrations is not iterable


TypeError: matchingPluginRegistrations is not iterable
    at default_1 (/path/to/workspace/node_modules/@nx/cypress/src/migrations/update-19-6-0/update-ci-webserver-for-static-serve.js:14:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runNxMigration (/path/to/workspace/node_modules/nx/src/command-line/migrate/migrate.js:1036:5)
    at async executeMigrations (/path/to/workspace/node_modules/nx/src/command-line/migrate/migrate.js:921:33)
    at async runMigrations (/path/to/workspace/node_modules/nx/src/command-line/migrate/migrate.js:1009:37)
    at async /path/to/workspace/node_modules/nx/src/command-line/migrate/migrate.js:1053:13
    at async handleErrors (/path/to/workspace/node_modules/nx/src/utils/params.js:22:24)
    at async Object.handler (/path/to/workspace/node_modules/nx/src/command-line/migrate/command-object.js:26:43)
Command failed: npx nx _migrate --run-migrations --verbose

 NX   Command failed: npx nx migrate --run-migrations --verbose


Error: Command failed: npx nx migrate --run-migrations --verbose
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runNxSync (/private/var/folders/z4/kk2jh66n10134g51dxdvybwr0000gn/T/tmp-61889-aF5VN2yuUBfh/node_modules/nx/src/utils/child-process.js:27:34)
    at runMigrations (/private/var/folders/z4/kk2jh66n10134g51dxdvybwr0000gn/T/tmp-61889-aF5VN2yuUBfh/node_modules/nx/src/command-line/migrate/migrate.js:984:39)
    at /private/var/folders/z4/kk2jh66n10134g51dxdvybwr0000gn/T/tmp-61889-aF5VN2yuUBfh/node_modules/nx/src/command-line/migrate/migrate.js:1053:19
    at async handleErrors (/private/var/folders/z4/kk2jh66n10134g51dxdvybwr0000gn/T/tmp-61889-aF5VN2yuUBfh/node_modules/nx/src/utils/params.js:22:24)
Command failed: /var/folders/z4/kk2jh66n10134g51dxdvybwr0000gn/T/tmp-61889-aF5VN2yuUBfh/node_modules/.bin/nx _migrate --run-migrations --verbose
```

### Package Manager Version

10.7.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
This was fixed by https://github.com/nrwl/nx/pull/27471, and it should be released soon.
