### ISSUE TITLE
nx/next failing to build with approuter

### ISSUE THREAD

**Issue by ljacho** [nrwl/nx#27493]
### Current Behavior

![image](https://github.com/user-attachments/assets/1e463fa9-8fd3-4742-a232-266a96a11305)

correct approuter structure and I am getting the error:

```
nx run nextjs-app:build

 ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
  ▲ Next.js 14.2.5

   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
 ✓ Collecting page data
   Generating static pages (0/5)  [=   ]Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at Z (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5430)
    at I (/home/sbtge/workspace/growncode/gc_chatbots/dist/apps/nextjs-app/.next/server/chunks/34.js:6:1263)
    at renderWithHooks (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5732:15)
    at renderElement (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5957:7)
    at renderNodeDestructiveImpl (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6115:11)
    at renderNodeDestructive (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6087:14)
    at finishClassComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5954:7)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error

Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at Z (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5430)
    at I (/home/sbtge/workspace/growncode/gc_chatbots/dist/apps/nextjs-app/.next/server/chunks/34.js:6:1263)
    at renderWithHooks (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5732:15)
    at renderElement (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5957:7)
    at renderNodeDestructiveImpl (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6115:11)
    at renderNodeDestructive (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6087:14)
    at finishClassComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5954:7)
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
    at d (/home/sbtge/workspace/growncode/gc_chatbots/dist/apps/nextjs-app/.next/server/chunks/907.js:1:21721)
    at h (/home/sbtge/workspace/growncode/gc_chatbots/dist/apps/nextjs-app/.next/server/chunks/907.js:1:13641)
    at au (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908) {
  digest: '3431238367'
}
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
    at d (/home/sbtge/workspace/growncode/gc_chatbots/dist/apps/nextjs-app/.next/server/chunks/907.js:1:21721)
    at h (/home/sbtge/workspace/growncode/gc_chatbots/dist/apps/nextjs-app/.next/server/chunks/907.js:1:13641)
    at au (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)

Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:109363)
    at d (/home/sbtge/workspace/growncode/gc_chatbots/dist/apps/nextjs-app/.next/server/chunks/907.js:1:21721)
    at h (/home/sbtge/workspace/growncode/gc_chatbots/dist/apps/nextjs-app/.next/server/chunks/907.js:1:13641)
    at au (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
    at a_ (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49776)
    at ab (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11808)
    at /home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16871
    at aw (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:16908)
Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at Z (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5430)
    at I (/home/sbtge/workspace/growncode/gc_chatbots/dist/apps/nextjs-app/.next/server/chunks/34.js:6:1263)
    at renderWithHooks (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5732:15)
    at renderElement (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5957:7)
    at renderNodeDestructiveImpl (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6115:11)
    at renderNodeDestructive (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6087:14)
    at finishClassComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5954:7)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error

Error: <Html> should not be imported outside of pages/_document.
Read more: https://nextjs.org/docs/messages/no-document-import-in-page
    at Z (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/next@14.2.5_@babel+core@7.25.2_@playwright+test@1.46.1_babel-plugin-macros@3.1.0_react-dom@18_gwh2kxsrvn3wij4v6umexe7edi/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:5430)
    at I (/home/sbtge/workspace/growncode/gc_chatbots/dist/apps/nextjs-app/.next/server/chunks/34.js:6:1263)
    at renderWithHooks (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5732:15)
    at renderElement (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5957:7)
    at renderNodeDestructiveImpl (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6115:11)
    at renderNodeDestructive (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6087:14)
    at finishClassComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5688:3)
    at renderClassComponent (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5696:3)
    at renderElement (/home/sbtge/workspace/growncode/gc_chatbots/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5954:7)
 ✓ Generating static pages (5/5)

> Export encountered errors on following paths:
	/_error: /404
	/_error: /500
	/_not-found/page: /_not-found
Build process exited due to code 1
```

### Expected Behavior

build without issuses

### Steps to Reproduce

1. installing @nx/next and adding approuter structure to the project

### Nx Report

```shell
nx report                                                                                                         1 ↵ sbtge@workstation

 NX   Report complete - copy this into the issue template

Node           : 20.14.0
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 9.4.0

nx (global)        : 19.3.2
nx                 : 19.6.0
@nx/js             : 19.6.0
@nx/jest           : 19.6.0
@nx/eslint         : 19.6.0
@nx/workspace      : 19.6.0
@nx/devkit         : 19.6.0
@nx/esbuild        : 19.6.0
@nx/eslint-plugin  : 19.6.0
@nx/next           : 19.6.0
@nx/node           : 19.6.0
@nx/playwright     : 19.6.0
@nx/react          : 19.6.0
@nx/vite           : 19.6.0
@nx/web            : 19.6.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
@nx/next/plugin
@nx/playwright/plugin
@nx/vite/plugin
---------------------------------------
Community plugins:
@nx-tools/nx-prisma : 6.1.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ljacho** [comment]
problem was in wrong env file - NODE_ENV variable non-standard format, fault on my side
