### ISSUE TITLE
TypeError: isAssetFile is not a function in react-native 0.73.6 version ( nx version 19.0.0)

### ISSUE THREAD

**Issue by mobcoder-shyama** [nrwl/nx#27613]
### Current Behavior

error isAssetFile is not a function
TypeError: isAssetFile is not a function
at resolveFile (//node_modules/@nrwl/react-native/node_modules/metro-resolver/src/resolve.js:272:7)
at resolveFileOrDir (//node_modules/@nrwl/react-native/node_modules/metro-resolver/src/resolve.js:198:22)
at resolveModulePath (//node_modules/@nrwl/react-native/node_modules/metro-resolver/src/resolve.js:130:18)
at Object.resolve (//node_modules/@nrwl/react-native/node_modules/metro-resolver/src/resolve.js:37:12)
at tsconfigPathsResolver (//node_modules/@nrwl/react-native/plugins/metro-resolver.js:84:30)
at //node_modules/@nrwl/react-native/plugins/metro-resolver.js:26:13
at Object.resolve (//node_modules/metro-resolver/src/resolve.js:50:12)
at ModuleResolver.resolveDependency (//node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:79:31)
at DependencyGraph.resolveDependency (//node_modules/metro/src/node-haste/DependencyGraph.js:271:43)
at Object.resolve (//node_modules/metro/src/lib/transformHelpers.js:171:21)

### Expected Behavior

It should be working in iOS simulator

### Steps to Reproduce

Once run the nx command for iOS :- nx run sqh-mobile:run-ios

### Nx Report

```shell
error: TypeError: isAssetFile is not a function
    at resolveFile (/Users/heureux_shyama/Desktop/React Moduels/SQH.Lib.ReactModules/node_modules/@nx/react-native/node_modules/metro-resolver/src/resolve.js:272:7)
    at resolveFileOrDir (/Users/heureux_shyama/Desktop/React Moduels/SQH.Lib.ReactModules/node_modules/@nx/react-native/node_modules/metro-resolver/src/resolve.js:198:22)
    at resolveModulePath (/Users/heureux_shyama/Desktop/React Moduels/SQH.Lib.ReactModules/node_modules/@nx/react-native/node_modules/metro-resolver/src/resolve.js:130:18)
    at Object.resolve (/Users/heureux_shyama/Desktop/React Moduels/SQH.Lib.ReactModules/node_modules/@nx/react-native/node_modules/metro-resolver/src/resolve.js:37:12)
    at tsconfigPathsResolver (/Users/heureux_shyama/Desktop/React Moduels/SQH.Lib.ReactModules/node_modules/@nx/react-native/plugins/metro-resolver.js:84:30)
    at /Users/heureux_shyama/Desktop/React Moduels/SQH.Lib.ReactModules/node_modules/@nx/react-native/plugins/metro-resolver.js:26:13
    at Object.resolve (/Users/heureux_shyama/Desktop/React Moduels/SQH.Lib.ReactModules/node_modules/@react-native/community-cli-plugin/node_modules/metro-resolver/src/resolve.js:32:12)
    at ModuleResolver.resolveDependency (/Users/heureux_shyama/Desktop/React Moduels/SQH.Lib.ReactModules/node_modules/@react-native/community-cli-plugin/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:73:31)
    at DependencyGraph.resolveDependency (/Users/heureux_shyama/Desktop/React Moduels/SQH.Lib.ReactModules/node_modules/@react-native/community-cli-plugin/node_modules/metro/src/node-haste/DependencyGraph.js:235:43)
    at /Users/heureux_shyama/Desktop/React Moduels/SQH.Lib.ReactModules/node_modules/@react-native/community-cli-plugin/node_modules/metro/src/lib/transformHelpers.js:156:21
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mobcoder-shyama** [comment]
![Uploading Simulator Screenshot - iphone 13 - 2024-08-08 at 12.30.33.png…]()

**Comment by mobcoder-shyama** [comment]
![Simulator Screenshot - iPhone 15 pro - 2024-08-23 at 10 24 14](https://github.com/user-attachments/assets/17ab8e8e-b30d-419c-adb0-5c37fc35dba3)

**Comment by xiongemi** [comment]
this is likely to be react native whereas react native version not compatible with metro version. what does your package.json looks like?

**Comment by xiongemi** [comment]
i think there is something with the metro version. try to run `npm ls metro` or `yarn why metro` and see what version of metro do you have, so is there any conflict.
