### ISSUE TITLE
Error after generating react library in react-standalone example

### ISSUE THREAD

**Issue by willybeans** [nrwl/nx#27683]
### Current Behavior

When running the `react-standalone` application, after generating a library using `npx nx g lib mylib --directory=mylib` and selecting `vite` as bundler, the command `npm run start` fails with the following error: `Unable to create nodes for mylib/vite.config.ts using plugin @nx/vite/plugin. `. Im not seeing a similar error when i use rollup instead. 

### Expected Behavior

the application should still be able to run 

### GitHub Repo

https://github.com/nrwl/nx-recipes/tree/main/react-standalone

### Steps to Reproduce

1. Go to your nx-recipes repo, under `react-standalone` 
2. npm i
3. npx nx g lib mylib --directory=mylib
4. select react lib option
5. select vite as bundler
6. select first option (as provided option) for naming 
7. `npm run start`

### Nx Report

```shell
me@me-MBP  ~me/test/nx-recipes/react-standalone   main ±  npm run start

> @myreactapp/source@0.0.0 start
> nx serve


 NX   Unable to create nodes for mylib/vite.config.ts using plugin @nx/vite/plugin. 


         Inner Error: Error: Cannot find module 'ajv/dist/core'
Require stack:
- /Users/me/test/nx-recipes/react-standalone/node_modules/ajv-draft-04/dist/index.js
- /Users/me/test/nx-recipes/react-standalone/node_modules/@microsoft/api-extractor/node_modules/@rushstack/node-core-library/lib/JsonSchema.js
- /Users/me/test/nx-recipes/react-standalone/node_modules/@microsoft/api-extractor/node_modules/@rushstack/node-core-library/lib/index.js
- /Users/me/test/nx-recipes/react-standalone/node_modules/@microsoft/api-extractor/lib/api/CompilerState.js
- /Users/me/test/nx-recipes/react-standalone/node_modules/@microsoft/api-extractor/lib/index.js
- /Users/me/test/nx-recipes/react-standalone/node_modules/vite-plugin-dts/dist/index.cjs
- /Users/me/test/nx-recipes/react-standalone/mylib/vite.config.ts
- /Users/me/test/nx-recipes/react-standalone/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function.Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/will/zen/test/nx-recipes/react-standalone/node_modules/ajv-draft-04/src/index.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object._require.extensions.<computed> [as .js] (file:///Users/will/zen/test/nx-recipes/react-standalone/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68404:17)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/will/zen/test/nx-recipes/react-standalone/node_modules/@microsoft/api-extractor/node_modules/@rushstack/node-core-library/src/JsonSchema.ts:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object._require.extensions.<computed> [as .js] (file:///Users/will/zen/test/nx-recipes/react-standalone/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68404:17)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/will/zen/test/nx-recipes/react-standalone/node_modules/@microsoft/api-extractor/node_modules/@rushstack/node-core-library/src/index.ts:66:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)

Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
If the error persists, please run "nx reset".
```

### Package Manager Version

10.5.2

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ilchenkoArtem** [comment]
I have the same issue but for vitest 
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/09261f02-b173-4b1e-9cd7-642114c764eb">

**Comment by pyoner** [comment]
the bug occurs because the `ajv-draft-04` has optional peer dependency

```json
"peerDependenciesMeta": {
    "ajv": {
      "optional": true
    }
  },
```

More details here https://github.com/ajv-validator/ajv-draft-04/issues/10 
PR https://github.com/ajv-validator/ajv-draft-04/pull/11

The solution is to install `ajv` manually
```sh
npm i -D ajv@^8.5.0
```
or
```sh
pnpm add -D ajv@^8.5.0
```
or
```sh
bun add -D ajv@^8.5.0
```

**Comment by rendmath** [comment]
It seems that any attempt to add a React library with Vite as bundler currently causes this issue.

Here is a reproduction on Nx 20/21.

```
npx --yes create-nx-workspace@20 --name=my-nx-workspace --preset=ts --skipGit --nxCloud=skip --formatter=prettier
cd my-nx-workspace
npx nx add @nx/react
npx nx generate @nx/react:library --name=frontend-lib --directory=libraries/frontend-lib --useProjectJson --tags=frontend --bundler=vite --compiler=swc --linter=eslint --unitTestRunner=vitest --style=css
npx nx show project frontend-lib --json
```

**Comment by Coly010** [comment]
Can you retry this on latest version of Nx?

**Comment by rendmath** [comment]
Tried it with Nx 22.3.3 and it seems to have been fixed. Issue can be closed.
