### ISSUE TITLE
@nx/vite plugin fails to init

### ISSUE THREAD

**Issue by DannyMardini** [nrwl/nx#27721]
### Current Behavior

I am running through the [npm workspaces tutorial](https://nx.dev/getting-started/tutorials/npm-workspaces-tutorial) and when adding the @nx/vite plugin:

```shell
npx nx add @nx/vite --verbose
```

the plugin fails to initialize, giving me the following error:

```
✔ Installing @nx/vite@19.6.4...
⠋ Initializing @nx/vite...
 NX  Generating @nx/vite:init

⠼ Initializing @nx/vite...
 NX   Could not add the plugin in a way which does not conflict with existing targets. Please report this error at: https://github.com/nrwl/nx/issues/new/choose


Error: Could not add the plugin in a way which does not conflict with existing targets. Please report this error at: https://github.com/nrwl/nx/issues/new/choose
    at _addPluginInternal (/Users/dmardini/Development/nx/tuskydesign/node_modules/@nx/devkit/src/utils/add-plugin.js:81:15)
    at async initGeneratorInternal (/Users/dmardini/Development/nx/tuskydesign/node_modules/@nx/vite/src/generators/init/init.js:65:9)
    at async /Users/dmardini/Development/nx/tuskydesign/node_modules/nx/src/command-line/generate/generate.js:237:26
    at async handleErrors (/Users/dmardini/Development/nx/tuskydesign/node_modules/nx/src/utils/params.js:22:24)
    at async Object.handler (/Users/dmardini/Development/nx/tuskydesign/node_modules/nx/src/command-line/generate/command-object.js:14:22)
✖ Initializing @nx/vite...

Command failed: npx nx g @nx/vite:init --keepExistingVersions --updatePackageScripts


 NX   Failed to initialize @nx/vite. Please check the error above for more details.
```

### Expected Behavior

I expected the @nx/vite plugin to be added seamlessly to the tuskydesign workspace.

### GitHub Repo

https://github.com/nrwl/tuskydesign.git

### Steps to Reproduce

1. Check out https://github.com/nrwl/tuskydesign.git.
2. Follow the [youtube tutorial](https://www.youtube.com/watch?v=ZA9K4iT3ANc) until it gets to the `npx nx add @nx/vite` step.
3. Observe that the plugin fails to init.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 21.5.0
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.2.4

nx (global)    : 19.6.4
nx             : 19.6.4
@nx/js         : 19.6.4
@nx/workspace  : 19.6.4
@nx/devkit     : 19.6.4
@nrwl/tao      : 19.6.4
@nx/vite       : 19.6.4
typescript     : 4.9.5
```

### Failure Logs

```shell
✔ Installing @nx/vite@19.6.4...
⠙ Initializing @nx/vite...
 NX  Generating @nx/vite:init

⠦ Initializing @nx/vite...
 NX   Could not add the plugin in a way which does not conflict with existing targets. Please report this error at: https://github.com/nrwl/nx/issues/new/choose


Error: Could not add the plugin in a way which does not conflict with existing targets. Please report this error at: https://github.com/nrwl/nx/issues/new/choose
    at _addPluginInternal (/Users/dmardini/Development/nx/tuskydesign/node_modules/@nx/devkit/src/utils/add-plugin.js:81:15)
    at async initGeneratorInternal (/Users/dmardini/Development/nx/tuskydesign/node_modules/@nx/vite/src/generators/init/init.js:65:9)
    at async /Users/dmardini/Development/nx/tuskydesign/node_modules/nx/src/command-line/generate/generate.js:237:26
    at async handleErrors (/Users/dmardini/Development/nx/tuskydesign/node_modules/nx/src/utils/params.js:22:24)
    at async Object.handler (/Users/dmardini/Development/nx/tuskydesign/node_modules/nx/src/command-line/generate/command-object.js:14:22)
✖ Initializing @nx/vite...

Command failed: npx nx g @nx/vite:init --keepExistingVersions --updatePackageScripts


 NX   Failed to initialize @nx/vite. Please check the error above for more details.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
There were changes made to allow more options for certain target names that should now resolve this issue. I'm going to close this, but if it still exists in version 20, tag me so I can see
