### ISSUE TITLE
It failed when building a next application with config `output:standalone`.

### ISSUE THREAD

**Issue by ibufu** [nrwl/nx#27724]
### Current Behavior

After integrating to an existed pnpm monorepo, it failed when building a next application with config `output:standalone`.

### Expected Behavior

```bash
nx build next-app --verbose
```
```
Error: File exists (os error 17)
    at /nx-next-standalone/node_modules/.pnpm/nx@19.6.4/node_modules/nx/src/tasks-runner/cache.js:145:17
```

### GitHub Repo

https://github.com/ibufu/nx-next-standalone

### Steps to Reproduce

1. Clone the repo.
2. `pnpm i`
3. `nx build next-app`

### Nx Report

```shell
Node           : 18.20.4
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.9.0

nx (global)  : 19.6.4
nx           : 19.6.4
@nx/eslint   : 19.6.4
@nx/next     : 19.6.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/next/plugin
```

### Failure Logs

```shell
Error: File exists (os error 17)
    at /nx-next-standalone/node_modules/.pnpm/nx@19.6.4/node_modules/nx/src/tasks-runner/cache.js:145:17
```

### Package Manager Version

pnpm@9.9.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jackhefoong** [comment]
Same here

**Comment by ibufu** [comment]
Just delete the scripts in package.json and only keep scripts in
project.json

**Comment by jackhefoong** [comment]
Big help, thanks! @ibufu

**Comment by counterbeing** [comment]
I'm getting the same error.

I'm trying to understand  how not using `package.json` scripts would help? I'm also trying to understand how to update my `project.json` to actually build correctly.I went with a `package.json` script for this particular library because it has a couple of steps:

```  "scripts": {
    "bundle": "tsx ./src/bundle.ts",
    "build": "rm -rf ./dist && tsc -p tsconfig.lib.json && pnpm run bundle"
  },```

How would i convert that into a `project.json` syntax, and how would that fix the problem? Or would it?

**Comment by ibufu** [comment]
The root cause is that nx run the build script twice. You can use nx show to figure out it.

**Comment by counterbeing** [comment]
I've moved to this structure in my `project.json` for this package:

```
{
  "name": "workflow-bundler",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "packages/workflow-bundler/src",
  "projectType": "library",
  "tags": [],
  "targets": {
    "build": {
      "executor": "nx:run-commands",
      "options": {
        "command": "say 'hello';rm -rf ./dist && tsc -p tsconfig.lib.json && tsx ./src/bundle.ts"
      }
    }
  }
}
```

That `say 'hello'` is just there so i can hear if it happens to run twice. It's now only running once. I've entirely removed the scripts section from my `package.json`. However i'm still getting:

```Error: File exists (os error 17)
    at /Users/cory.logan/Code/my-project/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_t_rpge6wb46b7rpyw5yhycwpxahy/node_modules/nx/src/tasks-runner/cache.js:84:24
    at _try (/Users/cory.logan/Code/my-project/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_t_rpge6wb46b7rpyw5yhycwpxahy/node_modules/nx/src/tasks-runner/cache.js:397:26)
    at _try (/Users/cory.logan/Code/my-project/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_t_rpge6wb46b7rpyw5yhycwpxahy/node_modules/nx/src/tasks-runner/cache.js:406:26)
    at async _try (/Users/cory.logan/Code/my-project/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_t_rpge6wb46b7rpyw5yhycwpxahy/node_modules/nx/src/tasks-runner/cache.js:406:20)
    at async _try (/Users/cory.logan/Code/my-project/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_t_rpge6wb46b7rpyw5yhycwpxahy/node_modules/nx/src/tasks-runner/cache.js:406:20)
    at async _try (/Users/cory.logan/Code/my-project/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_t_rpge6wb46b7rpyw5yhycwpxahy/node_modules/nx/src/tasks-runner/cache.js:406:20)
    at async _try (/Users/cory.logan/Code/my-project/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_t_rpge6wb46b7rpyw5yhycwpxahy/node_modules/nx/src/tasks-runner/cache.js:406:20)
    at async Promise.all (index 0)
    at async TaskOrchestrator.postRunSteps (/Users/cory.logan/Code/my-project/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_t_rpge6wb46b7rpyw5yhycwpxahy/node_modules/nx/src/tasks-runner/task-orchestrator.js:345:13)
    at async TaskOrchestrator.applyFromCacheOrRunTask (/Users/cory.logan/Code/my-project/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_t_rpge6wb46b7rpyw5yhycwpxahy/node_modules/nx/src/tasks-runner/task-orchestrator.js:295:9)
```

**Comment by CristianHG2** [comment]
I'm also experiencing this issue. On my end, there seems to be some conflict with the cache entries for Nx. It seems it is trying to write to the cache, but the key already exists, which causes this issue.

Running the command with `--skipNxCache` worked for me.

**Comment by caioquirino** [comment]
For my setup, the issue was also gone after adding `--skipNxCache` (which is not the ideal solution). Tested with the latest NX version: 20.7.1

**Comment by OrenSayag** [comment]
`--skipNxCache` worked around the issue for me too

**Comment by drewandre** [comment]
This is still broken in the latest NV v20.1.0. It's unfortunate because we have to disable standalone output when running outside of CI, which produces a different build, so it's difficult to run our true production compiled next.js app locally.

**Comment by lucasvieirasilva** [comment]
Same here, I have another workaround option:

Add this to the `package.json` or `project.json`

```json
{
  ...
  "targets": {
    "build": {
      "cache": false
    }
...
```

**Comment by TalMikey** [comment]
any progress?

**Comment by gperdomor** [comment]
Same issue here :(

**Comment by eliobischof** [comment]
I solved this by using the target output `{projectRoot}/.next/standalone` instead of `{projectRoot}/.next/standalone/**/*`

**Comment by gperdomor** [comment]
Any official solution, any update?

**Comment by PapaStef** [comment]
I'm also experiencing the same on my side

**Comment by jontybrook** [comment]
ditto here, also experiencing this

**Comment by marc-wilson** [comment]
still an issue in nx 22

**Comment by sebastiandg7** [comment]
I'm still not sure why this is happening, yet I found the cleanest workaround for my needs.

The inferred plugin `outputs` paths are

`{workspaceRoot}/apps/web/.next/!(cache)/**/*`

`{workspaceRoot}/apps/web/.next/!(cache)`


I changed them by configuring the target with this output path:

```json
{
   "targets": {
      "build": {
        "outputs": [
          "{projectRoot}/.next"
        ]
      }
    }
}
```

and it works.

I tried ignoring the `.next/cache` dir following the same pattern as the default imports in the `nx.json`:

```json
{
  "targets": {
    "build": {
      "outputs": [
        "{projectRoot}/.next",
        "!{projectRoot}/.next/cache"
      ]
    }
  }
}
```

but had no luck.

**Comment by ridler** [comment]
### Regression Report: Issue reintroduced between Nx 22.0.2 and 22.4.5

We're experiencing this exact issue after upgrading from **Nx 22.0.2** to **Nx 22.4.5**. The issue did not exist on 22.0.2.

### Environment
- **Nx**: 22.4.5 (upgraded from 22.0.2 where the issue did NOT occur)
- **Next.js**: 16.0.10
- **Package Manager**: bun 1.2.21
- **OS**: macOS (darwin 25.2.0, arm64)

### Setup
We have 5 Next.js applications with `output: 'standalone'` in our Nx monorepo. All of them use the `@nx/next/plugin` for inferred targets (via `nx:run-commands` executor with `next build`).

### Behavior
The build completes successfully, but then fails during the cache save step:

```
✓ Compiled successfully
✓ Generating static pages
✓ Finalizing page optimization

 NX   Successfully ran target build for project [app-name] and 1 task it depends on

 NX   File exists (os error 17)

Error: File exists (os error 17)
    at /node_modules/nx/src/tasks-runner/cache.js:106:24
```

### Root Cause Analysis
The error occurs when Nx attempts to cache the `.next/standalone` directory, which contains symlinks. The Rust-based cache system fails with "os error 17" (EEXIST) when handling these symlinks.

### Workaround
Setting `"cache": false` on the build target for affected Next.js apps in their respective `project.json` files resolves the issue:

```json
{
  "targets": {
    "build": {
      "cache": false
    }
  }
}
```

Alternatively, in `nx.json` targetDefaults:
```json
{
  "targetDefaults": {
    "@nx/next:build": {
      "cache": false
    }
  }
}
```

**Comment by jtw-r** [comment]
Hey everyone, I've been following this issue closely because I was affected by it for a long time.

After upgrading to NX 22.7.1 and Next.js v16.2.6, I no longer get an error when building with `output: "standalone"`.

Can anyone confirm if they are still having the issue after upgrading?
