### ISSUE TITLE
Crash at build

### ISSUE THREAD

**Issue by alitahoc** [nrwl/nx#27805]
### Current Behavior

 TypeError: Cannot read properties of undefined (reading 'has')
    at /Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:251:47
    at Map.forEach (<anonymous>)
    at mapSnapshots (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:242:17)
    at stringifyYarnLockfile (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:151:23)
    at createLockFile (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/lock-file.js:133:60)
    at /Users/litaa/Code/lh/lufthansa-landingpages/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:42:124
    at fn (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at eval (eval at create (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:58:1)
    at eval (eval at create (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)

### Expected Behavior

To not crrash

### Steps to Reproduce

1. Run a build

### Nx Report

```shell
TypeError: Cannot read properties of undefined (reading 'has')
    at /Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:251:47
    at Map.forEach (<anonymous>)
    at mapSnapshots (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:242:17)
    at stringifyYarnLockfile (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:151:23)
    at createLockFile (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/lock-file.js:133:60)
    at /Users/litaa/Code/lh/lufthansa-landingpages/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:42:124
    at fn (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at eval (eval at create (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:58:1)
    at eval (eval at create (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
```

### Failure Logs

```shell
TypeError: Cannot read properties of undefined (reading 'has')
    at /Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:251:47
    at Map.forEach (<anonymous>)
    at mapSnapshots (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:242:17)
    at stringifyYarnLockfile (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:151:23)
    at createLockFile (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/nx/src/plugins/js/lock-file/lock-file.js:133:60)
    at /Users/litaa/Code/lh/lufthansa-landingpages/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:42:124
    at fn (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at eval (eval at create (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:58:1)
    at eval (eval at create (/Users/litaa/Code/lh/lufthansa-landingpages/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
@alitahoc It's understandable that you may not be able to run `nx report` if the graph isn't building correctly for you. However, if you could provide the Node Version and Nx version you are using, that would be very helpful.

`node -v` wil get you the Node version

`yarn why nx`

should give you the current installed version of nx in your repo
