### ISSUE TITLE
nx release uses npm command without --json so errors fail to be interpreted

### ISSUE THREAD

**Issue by 0xd0a** [nrwl/nx#27822]
### Current Behavior

When running nx release and an error occurs (in the stage where npm dist-tags runs) nx runs npm command without "--json" so the error from the stdout is interpreted incorrectly.

### Expected Behavior

Errors are interpreted correctly.

### Steps to Reproduce

Can't reproduce right now, for me it breaks in the pipeline. The error i am getting is:
```

npm dist-tag add error:
Something unexpected went wrong when processing the npm dist-tag add output
 TypeError: Cannot read properties of undefined (reading 'summary')
    at runExecutor [90m(/app/[39mnode_modules/[4m@nx[24m/js/src/executors/release-publish/release-publish.impl.js:114:50[90m)[39m
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async promiseToIterator [90m(/app/[39mnode_modules/[4mnx[24m/src/command-line/run/run.js:35:11[90m)[39m
    at async getLastValueFromAsyncIterableIterator [90m(/app/[39mnode_modules/[4mnx[24m/src/utils/async-iterator.js:15:19[90m)[39m
    at async iteratorToProcessStatusCode [90m(/app/[39mnode_modules/[4mnx[24m/src/command-line/run/run.js:38:25[90m)[39m
    at async handleErrors [90m(/app/[39mnode_modules/[4mnx[24m/src/utils/params.js:22:24[90m)[39m
    at async process.<anonymous> [90m(/app/[39mnode_modules/[4mnx[24m/bin/run-executor.js:59:28[90m)[39m


```

### Nx Report

```shell
Node           : 18.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 9.8.1

nx                 : 19.5.6
@nx/js             : 19.5.6
@nx/jest           : 19.5.6
@nx/linter         : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/devkit         : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/nest           : 19.5.6
@nx/node           : 19.5.6
@nx/playwright     : 19.5.6
@nx/plugin         : 19.5.6
@nx/react          : 19.5.6
@nrwl/tao          : 19.5.6
@nx/vite           : 19.5.6
@nx/web            : 19.5.6
@nx/webpack        : 19.5.6
typescript         : 5.3.2
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
```

### Operating System

- [X] macOS
- [X] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

The error is on this line: https://github.com/nrwl/nx/blob/0b99d1deff5148075bac31cbd8def7f9d12a17c5/packages/js/src/executors/release-publish/release-publish.impl.ts#L81-L83

It should be:
```
  const npmDistTagAddCommandSegments = [
    `npm dist-tag add ${packageName}@${packageJson.version} ${tag} --json --"${registryConfigKey}=${registry}"`,
  ];
```

We can see that nx expects a certain json structure which is not true when flag "--json" is not set:
https://github.com/nrwl/nx/blob/0b99d1deff5148075bac31cbd8def7f9d12a17c5/packages/js/src/executors/release-publish/release-publish.impl.ts#L141-L170

Additionally, on line 155 and further down the code nx expects "stdoutData.error.detail" and "stdoutData.error.summary" to exist but on line 141 it defines an empty object as a default fallback so this is clearly not guaranteed.

**Comment by alexandr2110pro** [comment]
Same here

https://github.com/easybread/easybread/actions/runs/11378074716/job/31653239890

**Comment by njsokol** [comment]
We just tried the fix mentioned by @0xd0a  and it does not work.  However we found that adding the flag: `excludeTaskDependencies` to our publish command does somehow solve this error. @JamesHenry any ideas?

**Comment by viters** [comment]
Hello, are there any news or findings on that problem?
