### ISSUE TITLE
Nx pseudo terminal panics on SIGKILL

### ISSUE THREAD

**Issue by JamesNimlos** [nrwl/nx#27917]
### Current Behavior

We've noticed that if we send SIGKILL to an Nx process sometimes it can crash from within the Rust Nx code and hang indefinitely. This issue is much more prevalent on our private monorepo which has 709 projects, but I've been able to create a reproduction case [https://github.com/JamesNimlos/nx-debug-on-sigkill]().

### Expected Behavior

Nx should not panic reopen a terminal session and honestly I'm not entirely sure how it could since it's a SIGKILL.

### GitHub Repo

https://github.com/JamesNimlos/nx-debug-on-sigkill

### Steps to Reproduce

The script is this:
```bash
#!/usr/bin/env bash

export RUST_BACKTRACE=full

nx start crew &
crew_pid=$!

echo "crew PID: $crew_pid"

sleep 0.3

kill -9 $crew_pid

```

Where it's running `nx start crew` and then 300 ms later sending that process a SIGKILL (`-9`).

### Nx Report

```shell
> nx report

 NX   Report complete - copy this into the issue template

Node           : 18.20.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.5.1

nx          : 19.7.3
@nrwl/tao   : 19.7.3
typescript  : 4.5.2
```

### Failure Logs

```shell
~/projects/nx-debug-stalled-process > ./try-break-nx.sh              
crew PID: 25368
~/projects/nx-debug-stalled-process > 
 NX   Running target start for project crew and 1 task it depends on:

———————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run crew:build

thread '<unnamed>' panicked at packages/nx/src/native/pseudo_terminal/pseudo_terminal.rs:61:27:
Failed to enter raw terminal mode: Os { code: 5, kind: Uncategorized, message: "Input/output error" }
stack backtrace:
   0:        0x10f108188 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h243268f17d714c7f
   1:        0x10ee99f94 - core::fmt::write::hb3cfb8a30e72d7ff
   2:        0x10f0d8aac - std::io::Write::write_fmt::hfb2314975de9ecf1
   3:        0x10f10a4d4 - std::panicking::default_hook::{{closure}}::h14c7718ccf39d316
   4:        0x10f109f24 - std::panicking::default_hook::hc62e60da3be2f352
   5:        0x10f10bc3c - std::panicking::rust_panic_with_hook::h09e8a656f11e82b2
   6:        0x10f10aecc - std::panicking::begin_panic_handler::{{closure}}::h1230eb3cc91b241c
   7:        0x10f10ae40 - std::sys::backtrace::__rust_end_short_backtrace::hc3491307aceda2c2
   8:        0x10f10ae34 - _rust_begin_unwind
   9:        0x10f308c1c - core::panicking::panic_fmt::ha4b80a05b9fff47a
  10:        0x10f308fac - core::result::unwrap_failed::h441932a0bca0dd7f
  11:        0x10ef8052c - nx::native::pseudo_terminal::rust_pseudo_terminal::RustPseudoTerminal::run_command::h3aa77d1a0a088207
  12:        0x10efb4800 - napi::tokio_runtime::within_runtime_if_available::hbb1699d95c763d42
  13:        0x10efb358c - nx::native::pseudo_terminal::rust_pseudo_terminal::__napi_impl_helper__RustPseudoTerminal__7::__napi__fork::h80ad27e8195d0428
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x10f108188 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h243268f17d714c7f
   1:        0x10ee99f94 - core::fmt::write::hb3cfb8a30e72d7ff
   2:        0x10f0d8aac - std::io::Write::write_fmt::hfb2314975de9ecf1
   3:        0x10f10a4d4 - std::panicking::default_hook::{{closure}}::h14c7718ccf39d316
   4:        0x10f109f24 - std::panicking::default_hook::hc62e60da3be2f352
   5:        0x10f10bc3c - std::panicking::rust_panic_with_hook::h09e8a656f11e82b2
   6:        0x10f10aea4 - std::panicking::begin_panic_handler::{{closure}}::h1230eb3cc91b241c
   7:        0x10f10ae40 - std::sys::backtrace::__rust_end_short_backtrace::hc3491307aceda2c2
   8:        0x10f10ae34 - _rust_begin_unwind
   9:        0x10f309090 - core::panicking::panic_nounwind_fmt::h91ee161184879b56
  10:        0x10f3090ec - core::panicking::panic_nounwind::heab7ebe7a6cd845c
  11:        0x10f3090a4 - core::panicking::panic_cannot_unwind::hedc43d82620205bf
  12:        0x10efb3738 - nx::native::pseudo_terminal::rust_pseudo_terminal::__napi_impl_helper__RustPseudoTerminal__7::__napi__fork::h80ad27e8195d0428
thread caused non-unwinding panic. aborting.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Again, we see this very consistently on our private monorepo which has 709 and millions of lines of TS which obviously means it will take longer resolving the graph etc.

Additionally, on the reproduction case I could only get it to reproduce when I use the `start` target _and_ added the `build` target to `dependsOn`.

**Comment by orestisioakeimidis** [comment]
We started seeing a similar behaviour recently. Errors like:
```
> nx build app

thread '<unnamed>' panicked at packages/nx/src/native/pseudo_terminal/pseudo_terminal.rs:61:27:
Failed to enter raw terminal mode: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
```
> nx report

Node           : 18.19.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.2.4

nx              : 19.7.3
@nx/js          : 19.7.3
@nx/jest        : 19.7.3
@nx/linter      : 19.7.3
@nx/eslint      : 19.7.3
@nx/workspace   : 19.7.3
@nx/angular     : 19.7.3
@nx/devkit      : 19.7.3
@nx/express     : 19.7.3
@nx/node        : 19.7.3
@nx/playwright  : 19.7.3
@nrwl/tao       : 19.7.3
@nx/vite        : 19.7.3
@nx/web         : 19.7.3
@nx/webpack     : 19.7.3
typescript      : 5.5.4
---------------------------------------
Community plugins:
@ng-bootstrap/ng-bootstrap : 17.0.1
@ngrx/component            : 18.0.2
@ngrx/component-store      : 18.0.2
@ngrx/effects              : 18.0.2
@ngrx/eslint-plugin        : 18.0.2
@ngrx/operators            : 18.0.2
@ngrx/router-store         : 18.0.2
@ngrx/store                : 18.0.2
@ngrx/store-devtools       : 18.0.2
ngx-toastr                 : 19.0.0
```

**Comment by l-Leniac-l** [comment]
I have the same issue on Linux and my coworkers on MacOS.
```
> nx report

Node           : 22.11.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.9.0

nx                 : 20.0.9
@nx/js             : 20.0.9
@nx/jest           : 20.0.9
@nx/eslint         : 20.0.9
@nx/workspace      : 20.0.9
@nx/devkit         : 20.0.9
@nx/eslint-plugin  : 20.0.9
@nx/express        : 20.0.9
@nx/next           : 20.0.9
@nx/node           : 20.0.9
@nx/react          : 20.0.9
@nx/web            : 20.0.9
@nx/webpack        : 20.0.9
typescript         : 5.5.4
```

**Comment by FredrikZeiner** [comment]
Same issue here. I've run `nx reset` and `nx repair` with no luck.

```
Node           : 22.12.0
OS             : darwin-x64
Native Target  : x86_64-macos
pnpm           : 9.15.4

nx (global)        : 20.3.0
nx                 : 20.3.1
@nx/js             : 20.3.1
@nx/eslint         : 20.3.1
@nx/workspace      : 20.3.1
@nx/angular        : 20.3.1
@nx/cypress        : 20.3.1
@nx/devkit         : 20.3.1
@nx/esbuild        : 20.3.1
@nx/eslint-plugin  : 20.3.1
@nx/next           : 20.3.1
@nx/node           : 20.3.1
@nx/react          : 20.3.1
@nx/vite           : 20.3.1
@nx/web            : 20.3.1
@nx/webpack        : 20.3.1
typescript         : 5.6.3
```

**Comment by heyakyra** [comment]
Is this also the cause of errors when running as a background process (using bash's `&`)?

```bash
thread '<unnamed>' panicked at packages/nx/src/native/pseudo_terminal/pseudo_terminal.rs:61:27:
Failed to enter raw terminal mode: Os { code: 5, kind: Uncategorized, message: "Input/output error" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7f1eea2a2c29 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
   1:     0x7f1ee9e1e35b - core::fmt::write::hf5713710ce10ff22
   2:     0x7f1eea2675c2 - std::io::Write::write_fmt::hda708db57927dacf
   3:     0x7f1eea2a51f8 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
   4:     0x7f1eea2a60ad - std::panicking::rust_panic_with_hook::had2118629c312a4a
   5:     0x7f1eea2a5b62 - std::panicking::begin_panic_handler::{{closure}}::h7fa5985d111bafa2
   6:     0x7f1eea2a5af9 - std::sys::backtrace::__rust_end_short_backtrace::h704d151dbefa09c5
   7:     0x7f1eea2a5ae4 - rust_begin_unwind
   8:     0x7f1ee9d83874 - core::panicking::panic_nounwind_fmt::hc0ae93930ea8f76c
   9:     0x7f1ee9d838dc - core::panicking::panic_nounwind::h9f485ff9b02bac75
  10:     0x7f1ee9d83889 - core::panicking::panic_cannot_unwind::hea865182d7ce50af
  11:     0x7f1ee9fbf259 - nx::native::pseudo_terminal::rust_pseudo_terminal::__napi_impl_helper__RustPseudoTerminal__9::__napi__new::h9787901d3be77234
  12:           0xefd8a5 - _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
  13:          0x1241c9a - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb1EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
  14:          0x1241fea - _ZN2v88internal26Builtin_HandleApiConstructEiPmPNS0_7IsolateE
  15:     0x7f1f0a66c3b6 - <unknown>
thread caused non-unwinding panic. aborting.
```

Running `npm run init` using `package.json`:

```json
{
    "init": "npm run start & npm run othercommand",
    "start": "npm install && { npm run build:watch; }",
    "build": "lerna run build",
    "build:watch": "npm run build && NX_DAEMON=true lerna watch -- npm run build"
}
```

**Comment by PaulMest** [comment]
Still reproducing on nx 22.7.2 (a year and a half later) with the same `.expect()` site, now at `pseudo_terminal.rs:279:31`. Same panic message, same `failed to initiate panic, error 5, aborting`, different `Os { code }`:

```
thread '<unnamed>' panicked at packages/nx/src/native/pseudo_terminal/pseudo_terminal.rs:279:31:
Failed to enter raw terminal mode: Os { code: 4, kind: Interrupted, message: "Interrupted system call" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5, aborting
```

Trigger in our case is `SIGINT` (Ctrl-C) delivered while the parent process is a TTY-capturing wrapper — specifically [`worktrunk`](https://worktrunk.dev/)'s `wt switch --create` pre-start hooks. Minimal reproducer: https://github.com/PaulMest/nx-22.7.2-panic-repro — `wt switch --create` reliably panics on 22.7.2, exits cleanly on 22.5.4 with the same workspace, same `wt.toml`, same iTerm2 session. Verified deterministic across multiple runs.

The full set of `errno`s the community has now reported being `.expect()`'d:

| errno | meaning | reporter / trigger |
|---|---|---|
| 4 | `EINTR` | this comment / SIGINT mid-syscall |
| 5 | `EIO` | OP, @heyakyra / SIGKILL, bg via `&` |
| 6 | `ENXIO` | OP comment / SIGKILL |

The fix likely wants to be the general pattern: every `enable_raw_mode().expect(...)` and `disable_raw_mode().expect(...)` in `pseudo_terminal.rs` (plus the matching child-side calls) should be a retry-on-`EINTR` + log-and-recover loop rather than a hard `unwrap`. The non-unwinding-panic abort makes this much worse than it needs to be — when nx is run as a subprocess of any tool that captures its output, the abort tears down the parent's reporting too.

cc @AgentEnder — still assigned to you on the issue from 18 months ago.

**Comment by montella1507** [comment]
I’m seeing a very similar panic in CI, but not caused by SIGKILL.

Environment:
- Nx: 22.7.1
- Angular: 21.x
- CI: CircleCI
- Executor: Linux Docker executor, non-interactive / no real TTY

Failure:

thread '<unnamed>' panicked at packages/nx/src/native/pseudo_terminal/pseudo_terminal.rs:279:31:
Failed to enter raw terminal mode: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
fatal runtime error: failed to initiate panic, error 5, aborting
Aborted (core dumped)

In our case it happened deterministically on:

npx nx run .... 

The interesting part is that this was the first real frontend build in that CI deploy step. Previous deployables were skipped, then this `nx run <project>:<target>:<configuration>` command started and Nx entered the native pseudo terminal path.

From inspecting the installed Nx 22.7.1 code, this looks related to the `run-one` path:

- `task-orchestrator.js` computes `disablePseudoTerminal = !this.tuiEnabled && (!this.initiatingProject || task.continuous)`
- for `nx run project:target:configuration`, `initiatingProject` is set, task is not continuous, so `disablePseudoTerminal` stays false
- then `forked-process-task-runner.js` may use `forkProcessWithPseudoTerminal` when `streamOutput` is true

Workaround that fixed it for us:

- set `NX_TUI=false`
- pass `--outputStyle=static`
- avoid `nx run project:target:configuration` in CI deploy scripts
- use `nx run-many -t <target> --projects=<project> --configuration=<configuration> --outputStyle=static` even for a single project

After changing that, the same CI deploy path no longer enters the failing pseudo-terminal path.

**Comment by montella1507** [comment]
+ had to set NX_NATIVE_COMMAND_RUNNER to false.
