### ISSUE TITLE
After upgrading to NX 19.7 and above, parallel tasks have started failing with the error: "NX FOREIGN KEY constraint failed."

### ISSUE THREAD

**Issue by ytchenak** [nrwl/nx#28035]
### Current Behavior

Parallel tasks have started failing with the error: "NX FOREIGN KEY constraint failed."

### Expected Behavior

Parallel tests have to be finished without error

### Steps to Reproduce

1. Run 4 jobs that execute non-overlapping sets of unit tests in Jenkins.  
2. One of the jobs may fail with "NX FOREIGN KEY constraint failed" or another error.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.14.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 9.9.0

nx (global)        : 19.3.0
nx                 : 19.8.0
@nx/js             : 19.8.0
@nx/jest           : 19.8.0
@nx/linter         : 19.8.0
@nx/eslint         : 19.8.0
@nx/workspace      : 19.8.0
@nx/angular        : 19.8.0
@nx/eslint-plugin  : 19.8.0
typescript         : 5.5.4
---------------------------------------
Community plugins:
@ngneat/spectator : 19.0.0
ng-mocks          : 14.13.1
ngx-bootstrap     : 18.0.2
nx-stylelint      : 17.1.5
```

### Failure Logs

```shell
[2024-09-21T15:08:06.481Z] 
[2024-09-21T15:08:06.481Z] Test Suites: 27 passed, 27 total
[2024-09-21T15:08:06.481Z] Tests:       1 skipped, 126 passed, 127 total
[2024-09-21T15:08:06.481Z] Snapshots:   0 total
[2024-09-21T15:08:06.481Z] Time:        228.117 s
[2024-09-21T15:08:06.481Z] 
[2024-09-21T15:08:06.481Z] 
[2024-09-21T15:08:06.481Z] 
[2024-09-21T15:08:06.481Z]  NX   Successfully ran target test for 27 projects
[2024-09-21T15:08:06.481Z] 
[2024-09-21T15:08:06.481Z] 
[2024-09-21T15:08:06.481Z] 
[2024-09-21T15:08:06.481Z]  NX   FOREIGN KEY constraint failed
[2024-09-21T15:08:06.481Z] 
[2024-09-21T15:08:06.481Z] Pass --verbose to see the stacktrace.
[2024-09-21T15:08:06.481Z] 
[2024-09-21T15:08:06.481Z] module build has failed
[2024-09-21T15:08:06.481Z] + errorhandle 1
[2024-09-21T15:08:06.481Z] + exitCode=1
[2024-09-21T15:08:06.481Z] + '[' 1 -ne 0 ']'
[2024-09-21T15:08:06.481Z] + retC=1
[2024-09-21T15:08:06.481Z] + echo 'module build has failed'
[2024-09-21T15:08:06.481Z] + cd /h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1047
[2024-09-21T15:08:06.481Z] + date
[2024-09-21T15:08:06.481Z] Sat Sep 21 18:08:06 IDT 2024
[2024-09-21T15:08:06.481Z] + exit 1
Docker command failed with exit code 1[2024-09-21T15:08:06.752Z] parallel_flow() has failed with hudson.AbortException: Docker command failed with exit code 1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

it work in NX 19.6 and stopped work in 19.7.3 and 19.8.0

**Comment by xiongemi** [comment]
i think the quick workaround is to try set env variable `NX_DISABLE_DB=true`.

**Comment by ytchenak** [comment]
The issue persists with the error "NX disk I/O error." I believe the error originates from SQLite, which is used in the .nx/workspace-data directory. It seems the SQLite files are not well-protected against concurrent write access, even though the directory contains a lockfile.hash file.

In my scenario, I am running two separate processes: one for build and one for lint, using the following commands:
- `pnpm nx run-many -t build`
- `pnpm nx run-many -t lint`

These processes are executed from different Jenkins agents.

Error stack:
`
Error: disk I/O error
    at /h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1182/frontend/node_modules/.pnpm/nx@19.8.4_@swc-node+register@1.10.9_@swc+core@1.7.28_@swc+helpers@0.5.13__@swc+types@0.1.12_t_3mk5x3ieogvcrsvdo72ysw5h3m/node_modules/nx/src/utils/db-connection.js:11:93
    at getEntryOrSet (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1182/frontend/node_modules/.pnpm/nx@19.8.4_@swc-node+register@1.10.9_@swc+core@1.7.28_@swc+helpers@0.5.13__@swc+types@0.1.12_t_3mk5x3ieogvcrsvdo72ysw5h3m/node_modules/nx/src/utils/db-connection.js:19:17)
    at getDbConnection (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1182/frontend/node_modules/.pnpm/nx@19.8.4_@swc-node+register@1.10.9_@swc+core@1.7.28_@swc+helpers@0.5.13__@swc+types@0.1.12_t_3mk5x3ieogvcrsvdo72ysw5h3m/node_modules/nx/src/utils/db-connection.js:11:24)
    at getTaskDetails (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1182/frontend/node_modules/.pnpm/nx@19.8.4_@swc-node+register@1.10.9_@swc+core@1.7.28_@swc+helpers@0.5.13__@swc+types@0.1.12_t_3mk5x3ieogvcrsvdo72ysw5h3m/node_modules/nx/src/hasher/hash-task.js:19:84)
    at invokeTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1182/frontend/node_modules/.pnpm/nx@19.8.4_@swc-node+register@1.10.9_@swc+core@1.7.28_@swc+helpers@0.5.13__@swc+types@0.1.12_t_3mk5x3ieogvcrsvdo72ysw5h3m/node_modules/nx/src/tasks-runner/run-command.js:367:56)
    at runCommandForTasks (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1182/frontend/node_modules/.pnpm/nx@19.8.4_@swc-node+register@1.10.9_@swc+core@1.7.28_@swc+helpers@0.5.13__@swc+types@0.1.12_t_3mk5x3ieogvcrsvdo72ysw5h3m/node_modules/nx/src/tasks-runner/run-command.js:117:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1182/frontend/node_modules/.pnpm/nx@19.8.4_@swc-node+register@1.10.9_@swc+core@1.7.28_@swc+helpers@0.5.13__@swc+types@0.1.12_t_3mk5x3ieogvcrsvdo72ysw5h3m/node_modules/nx/src/tasks-runner/run-command.js:105:29
    at async handleErrors (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1182/frontend/node_modules/.pnpm/nx@19.8.4_@swc-node+register@1.10.9_@swc+core@1.7.28_@swc+helpers@0.5.13__@swc+types@0.1.12_t_3mk5x3ieogvcrsvdo72ysw5h3m/node_modules/nx/src/utils/handle-errors.js:9:24)
    at async runCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1182/frontend/node_modules/.pnpm/nx@19.8.4_@swc-node+register@1.10.9_@swc+core@1.7.28_@swc+helpers@0.5.13__@swc+types@0.1.12_t_3mk5x3ieogvcrsvdo72ysw5h3m/node_modules/nx/src/tasks-runner/run-command.js:104:20)
`
