### ISSUE TITLE
@nx/expo executor install failing. yarn v4, Unknown Syntax Error: Unsupported option name ("--force").

### ISSUE THREAD

**Issue by alifa20** [nrwl/nx#28062]
### Current Behavior

After upgrading from 19.6.4 to 19.8.0 the install executer is failing

### Expected Behavior

It should run the @nx/expo:install successfully. 

### Steps to Reproduce

1.  npx create-nx-workspace@latest --preset=expo --appName=nx-expo-app --pm=yarn 
2. add following to the project.json
```
"targets": {
    "install": {
      "executor": "@nx/expo:install",
      "options": {
        "packages": [],
        "fix": true
      }
    }
  }
```
3.  Run following command: 
> yarn nx run nx-expo-app:install 

### Nx Report

```shell
npx nx report

 NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 4.5.0

nx                 : 19.8.0
@nx/js             : 19.8.0
@nx/jest           : 19.8.0
@nx/linter         : 19.8.0
@nx/eslint         : 19.8.0
@nx/workspace      : 19.8.0
@nx/devkit         : 19.8.0
@nx/eslint-plugin  : 19.8.0
@nx/expo           : 19.8.0
@nx/react          : 19.8.0
@nrwl/tao          : 19.8.0
@nx/web            : 19.8.0
@nx/webpack        : 19.8.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/expo/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
yarn nx run nx-expo-app:install  --verbose

> nx run nx-expo-app:install

› Installing using yarn
> yarn add --force
Unknown Syntax Error: Unsupported option name ("--force").

$ yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

 NX   yarnpkg add --force exited with non-zero code: 1

Error: yarnpkg add --force exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/ali/my-projects/pak/nx-expo-app-org/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (/Users/ali/my-projects/pak/nx-expo-app-org/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at YarnPackageManager.runAsync (/Users/ali/my-projects/pak/nx-expo-app-org/node_modules/@expo/package-manager/build/node/BasePackageManager.js:41:42)
    at /Users/ali/my-projects/pak/nx-expo-app-org/node_modules/@expo/package-manager/build/node/YarnPackageManager.js:35:127
    at /Users/ali/my-projects/pak/nx-expo-app-org/node_modules/@expo/package-manager/build/utils/spawn.js:19:34


—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target install for project nx-expo-app failed

Failed tasks:

- nx-expo-app:install
```

### Package Manager Version

yarn 4.5.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

NX 19.7.4 is working fine as well.

**Comment by xiongemi** [comment]
the quick workaround, at workspace root, run `yarn expo install --check`.
