### ISSUE TITLE
Lint broken with upgrade from 8.x to 9.x on Gitlab CI

### ISSUE THREAD

**Issue by samratshaw** [nrwl/nx#2806]
## Failure Information (for bugs)

My release branch has `Nx 8.12.2` installed. 
```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 8.12.2
  @nrwl/cypress : 8.12.2
  @nrwl/eslint-plugin-nx : 8.12.2
  @nrwl/express : Not Found
  @nrwl/jest : 8.12.2
  @nrwl/linter : 8.12.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 8.12.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.12.2
  @nrwl/web : 8.12.2
  @nrwl/workspace : 8.12.2
  typescript : 3.7.5
```

I upgraded my daily branch to `Nx 9.2.2`.

Daily branch report
```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : 9.2.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.2
  @nrwl/linter : 9.2.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 9.2.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : 9.2.2
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3
```

When I run the lint locally, it works.
However, on Gitlab CI it fails.

Command - `$ nx affected:lint --base=origin/release/1.x --parallel`

### Failure logs
```
$ yarn affected:lint --base=origin/$DAILY_BASE_BRANCH --parallel
 yarn run v1.21.1
 $ nx affected:lint --base=origin/release/1.x --parallel
 /builds/sampleProject/node_modules/yargs/yargs.js:1109
       else throw err
            ^
 Error: Command failed: git merge-base origin/release/1.x HEAD
     at checkExecSyncError (child_process.js:611:11)
     at Object.execSync (child_process.js:647:15)
     at getFilesUsingBaseAndHead (/builds/sampleProject/node_modules/@nrwl/workspace/src/command-line/shared.js:67:39)
     at Object.parseFiles (/builds/sampleProject/node_modules/@nrwl/workspace/src/command-line/shared.js:52:20)
     at Object.affected (/builds/sampleProject/node_modules/@nrwl/workspace/src/command-line/affected.js:19:108)
     at Object.handler (/builds/sampleProject/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:46:138)
     at Object.runCommand (/builds/sampleProject/node_modules/yargs/lib/command.js:235:44)
     at Object.parseArgs [as _parseArgs] (/builds/sampleProject/node_modules/yargs/yargs.js:1022:30)
     at Object.get [as argv] (/builds/sampleProject/node_modules/yargs/yargs.js:965:21)
     at Object.initLocal (/builds/sampleProject/node_modules/@nrwl/cli/lib/init-local.js:20:79) {
   status: 1,
   signal: null,
   output: [ null, <Buffer >, <Buffer > ],
   pid: 148,
   stdout: <Buffer >,
   stderr: <Buffer >
 }
 error Command failed with exit code 1.
 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ERROR: Job failed: command terminated with exit code 1
```

**Comment by footyapps27** [comment]
@vsavkin Please help.

**Comment by FrozenPandaz** [comment]
Can you please try to `git fetch origin` before running the affected command to see if the issue is caused by not having access to the branch? We need more proper error reporting here to see what's going on.

**Comment by footyapps27** [comment]
Hi @FrozenPandaz..
Will add `git fetch origin` and check if it fixes the issue.

**Comment by footyapps27** [comment]
Hi @FrozenPandaz..
Will add `git fetch origin` and check if it fixes the issue.

**Comment by samratshaw** [comment]
@FrozenPandaz 

Even after adding `git fetch origin`, it keeps on failing randomly.

```
$ git fetch origin $DAILY_BASE_BRANCH
 From {URL_path}
  * branch            release/1.x -> FETCH_HEAD
  * [new branch]      release/1.x -> origin/release/1.x
 $ yarn affected:lint --base=origin/$DAILY_BASE_BRANCH --parallel
 yarn run v1.21.1
 $ nx affected:lint --base=origin/release/1.x --parallel
 builds/frontend/node_modules/yargs/yargs.js:1109
       else throw err
            ^
 Error: Command failed: git merge-base origin/release/1.x HEAD
     at checkExecSyncError (child_process.js:611:11)
     at Object.execSync (child_process.js:647:15)
     at getFilesUsingBaseAndHead (builds/frontend/node_modules/@nrwl/workspace/src/command-line/shared.js:67:39)
     at Object.parseFiles (builds/frontend/node_modules/@nrwl/workspace/src/command-line/shared.js:52:20)
     at Object.affected (builds/frontend/node_modules/@nrwl/workspace/src/command-line/affected.js:19:108)
     at Object.handler (builds/frontend/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:46:138)
     at Object.runCommand (builds/frontend/node_modules/yargs/lib/command.js:235:44)
     at Object.parseArgs [as _parseArgs] (builds/frontend/node_modules/yargs/yargs.js:1022:30)
     at Object.get [as argv] (builds/frontend/node_modules/yargs/yargs.js:965:21)
     at Object.initLocal (builds/frontend/node_modules/@nrwl/cli/lib/init-local.js:20:79) {
   status: 1,
   signal: null,
   output: [ null, <Buffer >, <Buffer > ],
   pid: 148,
   stdout: <Buffer >,
   stderr: <Buffer >
 }
 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 error Command failed with exit code 1.
 ERROR: Job failed: command terminated with exit code 1
```

**Comment by vsavkin** [comment]
This is something we cannot really fix on the Nx side. For us to calculate affected we need to be able to execute the merge-base command. 

As @nsatohiro pointed out, one option is to increase GIT_DEPTH. You could also get the list of changed files manually and pass them using `--files`, in which case the merge-base command wont' execute.

Closing this issue.
