### ISSUE TITLE
exportOptions?.default?.search is not a function when using gojs

### ISSUE THREAD

**Issue by el-davo** [nrwl/nx#28129]
### Current Behavior

After upgrading to nx version 19.8.2 we are no longer able to import gojs and get the error below
*NOTE* We did not have this issue in nx version 19.7.3 

### Expected Behavior

No error should occur

### Steps to Reproduce

1.

### Nx Report

```shell
Node           : 18.20.3
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 7.33.4

nx                 : 19.8.2
@nx/js             : 19.8.2
@nx/jest           : 19.8.2
@nx/linter         : 19.8.2
@nx/eslint         : 19.8.2
@nx/workspace      : 19.8.2
@nx/angular        : 19.8.2
@nx/cypress        : 19.8.2
@nx/devkit         : 19.8.2
@nx/esbuild        : 19.8.2
@nx/eslint-plugin  : 19.8.2
@nx/express        : 19.8.2
@nx/node           : 19.8.2
@nx/playwright     : 19.8.2
@nx/plugin         : 19.8.2
@nx/storybook      : 19.8.2
@nrwl/tao          : 19.8.2
@nx/vite           : 19.8.2
@nx/web            : 19.8.2
@nx/webpack        : 19.8.2
typescript         : 5.5.3
---------------------------------------
Community plugins:
@jsverse/transloco   : 7.4.3
@ngrx/effects        : 18.0.2
@ngrx/operators      : 18.0.2
@ngrx/router-store   : 18.0.2
@ngrx/store          : 18.0.2
@ngrx/store-devtools : 18.0.2
@storybook/angular   : 8.2.9
ngx-build-plus       : 13.0.1
ngx-toastr           : 16.2.0
---------------------------------------
Local workspace plugins:
         workspace-plugin
```

### Failure Logs

```shell
> nx run my-lib:build:production

⠋ Generating browser application bundles (phase: setup)...    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browserslist configuration. For more information, see https://angular.dev/tools/cli/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
 NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 NX   exportOptions?.default?.search is not a function

TypeError: exportOptions?.default?.search is not a function
    at collectPackagesFromExports (/home/ahernd2/git/thunder-ui/node_modules/.pnpm/@nx+webpack@19.8.2_7wxdwx5hxa6thtqk7yxiyyhic4/node_modules/@nx/webpack/src/utils/module-federation/secondary-entry-points.js:81:41)
    at collectPackageSecondaryEntryPoints (/home/ahernd2/git/thunder-ui/node_modules/.pnpm/@nx+webpack@19.8.2_7wxdwx5hxa6thtqk7yxiyyhic4/node_modules/@nx/webpack/src/utils/module-federation/secondary-entry-points.js:118:9)
    at /home/ahernd2/git/thunder-ui/node_modules/.pnpm/@nx+webpack@19.8.2_7wxdwx5hxa6thtqk7yxiyyhic4/node_modules/@nx/webpack/src/utils/module-federation/share.js:150:73
    at Array.forEach (<anonymous>)
    at sharePackages (/home/ahernd2/git/thunder-ui/node_modules/.pnpm/@nx+webpack@19.8.2_7wxdwx5hxa6thtqk7yxiyyhic4/node_modules/@nx/webpack/src/utils/module-federation/share.js:147:14)
    at getModuleFederationConfig (/home/ahernd2/git/thunder-ui/node_modules/.pnpm/@nx+angular@19.8.2_kjt2pwzhuqrabxd36xsuntccxe/node_modules/@nx/angular/src/utils/mf/utils.js:78:63)
    at withModuleFederation (/home/ahernd2/git/thunder-ui/node_modules/.pnpm/@nx+angular@19.8.2_kjt2pwzhuqrabxd36xsuntccxe/node_modules/@nx/angular/src/utils/mf/with-module-federation.js:10:112)
    at Object.<anonymous> (/home/ahernd2/git/thunder-ui/projects/cluster-topology/webpack.prod.config.js:7:18)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
```
```


### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Using wsl on windows

**Comment by el-davo** [comment]
I put a console.log on the line where the error occurs and the output is as follows

```
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
./package.json
./fesm2022/ag-grid-community-angular.mjs
undefined
undefined
undefined
undefined
./package.json
./fesm2022/ngrx-store-devtools.mjs
{
  types: './release/go.d.ts',
  development: './release/go-debug.js',
  production: './release/go.js',
  default: './release/go.js'
}
```

Because gojs is an object instead of a string for some reason it, it cannot use the search function and throws the error.

```
exportOptions?.['default']?.search(/\.(js|mjs|cjs)$/)
```

**Comment by mcarlotta** [comment]
This also negatively affects those projects that use `withModuleFederation`. 

As @el-davo mentioned above in reference to `gojs`...`axios` also follows same pattern

**Comment by stacho91** [comment]
I am encountering a similar issue with the clsx package when using withModuleFederation. The structure of the exports object for this package is as follows:

```
pkgName clsx
exports {
  ".": {
    "import": {
      "types": "./clsx.d.mts",
      "default": "./dist/clsx.mjs"
    },
    "default": {
      "types": "./clsx.d.ts",
      "default": "./dist/clsx.js"
    }
  },
  "./lite": {
    "import": {
      "types": "./clsx.d.mts",
      "default": "./dist/lite.mjs"
    },
    "default": {
      "types": "./clsx.d.ts",
      "default": "./dist/lite.js"
    }
  }
}
```

**Comment by madangryscientist** [comment]
> This also negatively affects those projects that use `withModuleFederation`.
> 
> As @el-davo mentioned above in reference to `gojs`...`axios` also follows same pattern
> 
> File Location: https://github.com/nrwl/nx/blob/master/packages/webpack/src/utils/module-federation/secondary-entry-points.ts#L118

I am seeing the same thing.
