### ISSUE TITLE
npx nx serve - gives ENONET error on newly generated angular apps

### ISSUE THREAD

**Issue by pets87** [nrwl/nx#28195]
### Current Behavior

I tried that on 2 different PC's. Both give same error.
Doc: https://nx.dev/recipes/module-federation/create-a-host

Tried with node versions: 
v20.16.0
v20.17.0

OS: Windows 10

**1.** 
>npx create-nx-workspace
```
√ Where would you like to create your workspace? · reg
√ Which stack do you want to use? · angular
√ Integrated monorepo, or standalone project? · integrated
√ Application name · angular-monorepo
√ Which bundler would you like to use? · webpack
√ Default stylesheet format · scss
√ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
√ Test runner to use for end to end (E2E) tests · playwright
√ Which CI provider would you like to use? · skip
√ Would you like remote caching to make your build faster? · skip
```

**2.** 
>cd reg 
>npx nx g @nx/angular:host host --directory=apps/host --remotes=institutions

```
√ Which stylesheet format would you like to use? · scss
√ Which E2E test runner would you like to use? · playwright
√ What should be the project name and where should it be generated? · host @ apps/host
```

**3.** 
>npx nx serve host
```
> nx run host:serve:development

 NX  Starting module federation dev-server for host with 1 remotes
 NX  Building 1 static remotes...
 NX   Remote failed to start. A complete log can be found in: C:\Users\Muno\Downloads\proovikas\reg\.nx\workspace-data\2024-09-30T05_30_18_726Z-build.log

————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target serve for project host failed

Failed tasks:

- host:serve:development

Hint: run the command with --verbose for more details.
```

**4.** 
>npx nx serve institutions
```
> nx run institutions:serve:development

- Generating browser application bundles (phase: setup)...
    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browserslist configuration. For more information, see https://angular.dev/tools/cli/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
[ Module Federation Manifest Plugin ]: Manifest will use absolute path resolution via its host at runtime, reason: publicPath='auto'
node:fs:2368
    return binding.writeFileUtf8(
                   ^
Error: ENOENT: no such file or directory, open 'C:\Users\Muno\Downloads\proovikas\reg\data:text\javascript;charset=utf-8;base64,aW1wb3J0IGZlZGVyYXRpb24gZnJvbSAnQzovVXNlcnMvTXVuby9Eb3dubG9hZHMvcHJvb3Zpa2FzL3JlZy9ub2RlX21vZHVsZXMvQG1vZHVsZS1mZWRlcmF0aW9uL3dlYnBhY2stYnVuZGxlci1ydW50aW1lL2Rpc3QvaW5kZXguY2pzLmpzJzsKaW1wb3J0IHBsdWdpbl8wIGZyb20gJ0M6L1VzZXJzL011bm8vRG93bmxvYWRzL3Byb292aWthcy9yZWcvbm9kZV9tb2R1bGVzL0Btb2R1bGUtZmVkZXJhdGlvbi9kYXRhLXByZWZldGNoL2Rpc3QvcGx1Z2luLmVzbS5qcyc7CmltcG9ydCBwbHVnaW5fMSBmcm9tICdDOi9Vc2Vycy9NdW5vL0Rvd25sb2Fkcy9wcm9vdmlrYXMvcmVnL25vZGVfbW9kdWxlcy9AbW9kdWxlLWZlZGVyYXRpb24vZGF0YS1wcmVmZXRjaC9kaXN0L3NoYXJlZC5lc20uanMnOwoKaWYoIV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5ydW50aW1lKXsKCXZhciBwcmV2RmVkZXJhdGlvbiA9IF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbjsKCV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbiA9IHt9Cglmb3IodmFyIGtleSBpbiBmZWRlcmF0aW9uKXsKCQlfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb25ba2V5XSA9IGZlZGVyYXRpb25ba2V5XTsKCX0KCWZvcih2YXIga2V5IGluIHByZXZGZWRlcmF0aW9uKXsKCQlfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb25ba2V5XSA9IHByZXZGZWRlcmF0aW9uW2tleV07Cgl9Cn0KaWYoIV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbnN0YW5jZSl7Cgl2YXIgcGx1Z2luc1RvQWRkID0gWwoJCXBsdWdpbl8wID8gKHBsdWdpbl8wLmRlZmF1bHQgfHwgcGx1Z2luXzApKCkgOiBmYWxzZSwKCQlwbHVnaW5fMSA\IChwbHVnaW5fMS5kZWZhdWx0IHx8IHBsdWdpbl8xKSgpIDogZmFsc2UsCgldLmZpbHRlcihCb29sZWFuKTsKCV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbml0T3B0aW9ucy5wbHVnaW5zID0gX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluaXRPcHRpb25zLnBsdWdpbnMgPyAKCV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbml0T3B0aW9ucy5wbHVnaW5zLmNvbmNhdChwbHVnaW5zVG9BZGQpIDogcGx1Z2luc1RvQWRkOwoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluc3RhbmNlID0gX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLnJ1bnRpbWUuaW5pdChfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5pdE9wdGlvbnMpOwoJaWYoX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmF0dGFjaFNoYXJlU2NvcGVNYXApewoJCV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5hdHRhY2hTaGFyZVNjb3BlTWFwKF9fd2VicGFja19yZXF1aXJlX18pCgl9CglpZihfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFsbEluaXRpYWxDb25zdW1lcyl7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluc3RhbGxJbml0aWFsQ29uc3VtZXMoKQoJfQoKCWlmKCFfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaXNNRlJlbW90ZSAmJiBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucHJlZmV0Y2gpewoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLnByZWZldGNoKCkKCX0KfQ=='
    at Object.writeFileSync (node:fs:2368:20)
    at FederationRuntimePlugin.ensureFile (C:\Users\Muno\Downloads\proovikas\reg\node_modules\@module-federation\enhanced\src\lib\container\runtime\FederationRuntimePlugin.ts:206:10)
    at FederationRuntimePlugin.getDependency (C:\Users\Muno\Downloads\proovikas\reg\node_modules\@module-federation\enhanced\src\lib\container\runtime\FederationRuntimePlugin.ts:222:10)
    at C:\Users\Muno\Downloads\proovikas\reg\node_modules\@module-federation\enhanced\src\lib\container\ContainerPlugin.ts:201:43
    at Hook.eval [as callAsync] (eval at create (C:\Users\Muno\Downloads\proovikas\reg\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:33:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\Muno\Downloads\proovikas\reg\node_modules\tapable\lib\Hook.js:18:14)
    at C:\Users\Muno\Downloads\proovikas\reg\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1323:20
    at eval (eval at create (C:\Users\Muno\Downloads\proovikas\reg\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Muno\\Downloads\\proovikas\\reg\\data:text\\javascript;charset=utf-8;base64,aW1wb3J0IGZlZGVyYXRpb24gZnJvbSAnQzovVXNlcnMvTXVuby9Eb3dubG9hZHMvcHJvb3Zpa2FzL3JlZy9ub2RlX21vZHVsZXMvQG1vZHVsZS1mZWRlcmF0aW9uL3dlYnBhY2stYnVuZGxlci1ydW50aW1lL2Rpc3QvaW5kZXguY2pzLmpzJzsKaW1wb3J0IHBsdWdpbl8wIGZyb20gJ0M6L1VzZXJzL011bm8vRG93bmxvYWRzL3Byb292aWthcy9yZWcvbm9kZV9tb2R1bGVzL0Btb2R1bGUtZmVkZXJhdGlvbi9kYXRhLXByZWZldGNoL2Rpc3QvcGx1Z2luLmVzbS5qcyc7CmltcG9ydCBwbHVnaW5fMSBmcm9tICdDOi9Vc2Vycy9NdW5vL0Rvd25sb2Fkcy9wcm9vdmlrYXMvcmVnL25vZGVfbW9kdWxlcy9AbW9kdWxlLWZlZGVyYXRpb24vZGF0YS1wcmVmZXRjaC9kaXN0L3NoYXJlZC5lc20uanMnOwoKaWYoIV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5ydW50aW1lKXsKCXZhciBwcmV2RmVkZXJhdGlvbiA9IF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbjsKCV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbiA9IHt9Cglmb3IodmFyIGtleSBpbiBmZWRlcmF0aW9uKXsKCQlfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb25ba2V5XSA9IGZlZGVyYXRpb25ba2V5XTsKCX0KCWZvcih2YXIga2V5IGluIHByZXZGZWRlcmF0aW9uKXsKCQlfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb25ba2V5XSA9IHByZXZGZWRlcmF0aW9uW2tleV07Cgl9Cn0KaWYoIV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbnN0YW5jZSl7Cgl2YXIgcGx1Z2luc1RvQWRkID0gWwoJCXBsdWdpbl8wID8gKHBsdWdpbl8wLmRlZmF1bHQgfHwgcGx1Z2luXzApKCkgOiBmYWxzZSwKCQlwbHVnaW5fMSA\\IChwbHVnaW5fMS5kZWZhdWx0IHx8IHBsdWdpbl8xKSgpIDogZmFsc2UsCgldLmZpbHRlcihCb29sZWFuKTsKCV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbml0T3B0aW9ucy5wbHVnaW5zID0gX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluaXRPcHRpb25zLnBsdWdpbnMgPyAKCV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbml0T3B0aW9ucy5wbHVnaW5zLmNvbmNhdChwbHVnaW5zVG9BZGQpIDogcGx1Z2luc1RvQWRkOwoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluc3RhbmNlID0gX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLnJ1bnRpbWUuaW5pdChfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5pdE9wdGlvbnMpOwoJaWYoX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmF0dGFjaFNoYXJlU2NvcGVNYXApewoJCV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5hdHRhY2hTaGFyZVNjb3BlTWFwKF9fd2VicGFja19yZXF1aXJlX18pCgl9CglpZihfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFsbEluaXRpYWxDb25zdW1lcyl7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluc3RhbGxJbml0aWFsQ29uc3VtZXMoKQoJfQoKCWlmKCFfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaXNNRlJlbW90ZSAmJiBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucHJlZmV0Y2gpewoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLnByZWZldGNoKCkKCX0KfQ=='
}
Node.js v20.16.0
```

### Expected Behavior

Both host and remote apps will start without errors.

### Steps to Reproduce

Run commands as described in documentation:
1. npx create-nx-workspace
2. npx nx g @nx/angular:host host --directory=apps/host --remotes=institutions
3. npx nx serve host

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.3

nx                 : 19.8.2
@nx/js             : 19.8.2
@nx/jest           : 19.8.2
@nx/linter         : 19.8.2
@nx/eslint         : 19.8.2
@nx/workspace      : 19.8.2
@nx/angular        : 19.8.2
@nx/devkit         : 19.8.2
@nx/eslint-plugin  : 19.8.2
@nx/playwright     : 19.8.2
@nrwl/tao          : 19.8.2
@nx/vite           : 19.8.2
@nx/web            : 19.8.2
@nx/webpack        : 19.8.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
```

### Package Manager Version

10.8.3

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by jmajnek** [comment]
I was able to work around the issue by installing `@module-federation/enhanced@0.6.6`.

**Comment by pets87** [comment]
> I was able to work around the issue by installing `@module-federation/enhanced@0.6.6`.

Thank you, that worked

**Comment by Coly010** [comment]
Yes, it seems the latest version of `@module-federation/enhanced` introduced an issue with the virtual entry point.
I already merged a fix to pin the version while the bug is ironed out on the Module Federation side

https://github.com/nrwl/nx/pull/28196
