### ISSUE TITLE
Module Federation new react remote not working when creating a new nx workspace: Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by SombreroElGringo** [nrwl/nx#28233]
### Current Behavior

Hello,

When I create a new nx workspace with React and generate a Reac remote project I have the following error:
```
❯ npm run nx run test:serve

> @org/source@0.0.0 nx
> npx nx run test:serve


> nx run test:serve:development


 NX  Starting module federation dev-server for test with 0 remotes


 NX  Starting static remotes proxies...


 NX  Static remotes proxies started successfully

[ Module Federation Manifest Plugin ]: Manifest will use absolute path resolution via its host at runtime, reason: publicPath='auto'
node:fs:2368
    return binding.writeFileUtf8(
                   ^

Error: ENAMETOOLONG: name too long, open 'data:text/javascript;charset=utf-8;base64,aW1wb3J0IGZlZGVyYXRpb24gZnJvbSAnL1VzZXJzL2Zsb3JlbnQucGFpbGhlcy9EZXNrdG9wL29yZy9ub2RlX21vZHVsZXMvQG1vZHVsZS1mZWRlcmF0aW9uL3dlYnBhY2stYnVuZGxlci1ydW50aW1lL2Rpc3QvaW5kZXguY2pzLmpzJzsKaW1wb3J0IHBsdWdpbl8wIGZyb20gJy9Vc2Vycy9mbG9yZW50LnBhaWxoZXMvRGVza3RvcC9vcmcvbm9kZV9tb2R1bGVzL0BueC93ZWJwYWNrL3NyYy91dGlscy9tb2R1bGUtZmVkZXJhdGlvbi9wbHVnaW5zL3J1bnRpbWUtbGlicmFyeS1jb250cm9sLnBsdWdpbi5qcyc7CmltcG9ydCBwbHVnaW5fMSBmcm9tICcvVXNlcnMvZmxvcmVudC5wYWlsaGVzL0Rlc2t0b3Avb3JnL25vZGVfbW9kdWxlcy9AbW9kdWxlLWZlZGVyYXRpb24vZGF0YS1wcmVmZXRjaC9kaXN0L3BsdWdpbi5lc20uanMnOwppbXBvcnQgcGx1Z2luXzIgZnJvbSAnL1VzZXJzL2Zsb3JlbnQucGFpbGhlcy9EZXNrdG9wL29yZy9ub2RlX21vZHVsZXMvQG1vZHVsZS1mZWRlcmF0aW9uL2RhdGEtcHJlZmV0Y2gvZGlzdC9zaGFyZWQuZXNtLmpzJzsKCmlmKCFfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucnVudGltZSl7Cgl2YXIgcHJldkZlZGVyYXRpb24gPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb247CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24gPSB7fQoJZm9yKHZhciBrZXkgaW4gZmVkZXJhdGlvbil7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uW2tleV0gPSBmZWRlcmF0aW9uW2tleV07Cgl9Cglmb3IodmFyIGtleSBpbiBwcmV2RmVkZXJhdGlvbil7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uW2tleV0gPSBwcmV2RmVkZXJhdGlvbltrZXldOwoJfQp9CmlmKCFfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFuY2UpewoJdmFyIHBsdWdpbnNUb0FkZCA9IFsKCQlwbHVnaW5fMCA/IChwbHVnaW5fMC5kZWZhdWx0IHx8IHBsdWdpbl8wKSgpIDogZmFsc2UsCgkJcGx1Z2luXzEgPyAocGx1Z2luXzEuZGVmYXVsdCB8fCBwbHVnaW5fMSkoKSA6IGZhbHNlLAoJCXBsdWdpbl8yID8gKHBsdWdpbl8yLmRlZmF1bHQgfHwgcGx1Z2luXzIpKCkgOiBmYWxzZSwKCV0uZmlsdGVyKEJvb2xlYW4pOwoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluaXRPcHRpb25zLnBsdWdpbnMgPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5pdE9wdGlvbnMucGx1Z2lucyA/IAoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluaXRPcHRpb25zLnBsdWdpbnMuY29uY2F0KHBsdWdpbnNUb0FkZCkgOiBwbHVnaW5zVG9BZGQ7CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFuY2UgPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucnVudGltZS5pbml0KF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbml0T3B0aW9ucyk7CglpZihfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uYXR0YWNoU2hhcmVTY29wZU1hcCl7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmF0dGFjaFNoYXJlU2NvcGVNYXAoX193ZWJwYWNrX3JlcXVpcmVfXykKCX0KCWlmKF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbnN0YWxsSW5pdGlhbENvbnN1bWVzKXsKCQlfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFsbEluaXRpYWxDb25zdW1lcygpCgl9CgoJaWYoIV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pc01GUmVtb3RlICYmIF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5wcmVmZXRjaCl7CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucHJlZmV0Y2goKQoJfQp9'
    at Object.writeFileSync (node:fs:2368:20)
    at FederationRuntimePlugin.ensureFile (/Users/root/Desktop/org/node_modules/@module-federation/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts:206:10)
    at FederationRuntimePlugin.getDependency (/Users/root/Desktop/org/node_modules/@module-federation/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts:222:10)
    at /Users/root/Desktop/org/node_modules/@module-federation/enhanced/src/lib/container/ContainerPlugin.ts:201:43
    at Hook.eval [as callAsync] (eval at create (/Users/root/Desktop/org/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:73:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/root/Desktop/org/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/root/Desktop/org/node_modules/webpack/lib/Compiler.js:1323:20
    at Hook.eval [as callAsync] (eval at create (/Users/root/Desktop/org/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/root/Desktop/org/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/root/Desktop/org/node_modules/webpack/lib/Compiler.js:1313:28) {
  errno: -63,
  code: 'ENAMETOOLONG',
  syscall: 'open',
  path: 'data:text/javascript;charset=utf-8;base64,aW1wb3J0IGZlZGVyYXRpb24gZnJvbSAnL1VzZXJzL2Zsb3JlbnQucGFpbGhlcy9EZXNrdG9wL29yZy9ub2RlX21vZHVsZXMvQG1vZHVsZS1mZWRlcmF0aW9uL3dlYnBhY2stYnVuZGxlci1ydW50aW1lL2Rpc3QvaW5kZXguY2pzLmpzJzsKaW1wb3J0IHBsdWdpbl8wIGZyb20gJy9Vc2Vycy9mbG9yZW50LnBhaWxoZXMvRGVza3RvcC9vcmcvbm9kZV9tb2R1bGVzL0BueC93ZWJwYWNrL3NyYy91dGlscy9tb2R1bGUtZmVkZXJhdGlvbi9wbHVnaW5zL3J1bnRpbWUtbGlicmFyeS1jb250cm9sLnBsdWdpbi5qcyc7CmltcG9ydCBwbHVnaW5fMSBmcm9tICcvVXNlcnMvZmxvcmVudC5wYWlsaGVzL0Rlc2t0b3Avb3JnL25vZGVfbW9kdWxlcy9AbW9kdWxlLWZlZGVyYXRpb24vZGF0YS1wcmVmZXRjaC9kaXN0L3BsdWdpbi5lc20uanMnOwppbXBvcnQgcGx1Z2luXzIgZnJvbSAnL1VzZXJzL2Zsb3JlbnQucGFpbGhlcy9EZXNrdG9wL29yZy9ub2RlX21vZHVsZXMvQG1vZHVsZS1mZWRlcmF0aW9uL2RhdGEtcHJlZmV0Y2gvZGlzdC9zaGFyZWQuZXNtLmpzJzsKCmlmKCFfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucnVudGltZSl7Cgl2YXIgcHJldkZlZGVyYXRpb24gPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb247CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24gPSB7fQoJZm9yKHZhciBrZXkgaW4gZmVkZXJhdGlvbil7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uW2tleV0gPSBmZWRlcmF0aW9uW2tleV07Cgl9Cglmb3IodmFyIGtleSBpbiBwcmV2RmVkZXJhdGlvbil7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uW2tleV0gPSBwcmV2RmVkZXJhdGlvbltrZXldOwoJfQp9CmlmKCFfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFuY2UpewoJdmFyIHBsdWdpbnNUb0FkZCA9IFsKCQlwbHVnaW5fMCA/IChwbHVnaW5fMC5kZWZhdWx0IHx8IHBsdWdpbl8wKSgpIDogZmFsc2UsCgkJcGx1Z2luXzEgPyAocGx1Z2luXzEuZGVmYXVsdCB8fCBwbHVnaW5fMSkoKSA6IGZhbHNlLAoJCXBsdWdpbl8yID8gKHBsdWdpbl8yLmRlZmF1bHQgfHwgcGx1Z2luXzIpKCkgOiBmYWxzZSwKCV0uZmlsdGVyKEJvb2xlYW4pOwoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluaXRPcHRpb25zLnBsdWdpbnMgPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5pdE9wdGlvbnMucGx1Z2lucyA/IAoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluaXRPcHRpb25zLnBsdWdpbnMuY29uY2F0KHBsdWdpbnNUb0FkZCkgOiBwbHVnaW5zVG9BZGQ7CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFuY2UgPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucnVudGltZS5pbml0KF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbml0T3B0aW9ucyk7CglpZihfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uYXR0YWNoU2hhcmVTY29wZU1hcCl7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmF0dGFjaFNoYXJlU2NvcGVNYXAoX193ZWJwYWNrX3JlcXVpcmVfXykKCX0KCWlmKF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbnN0YWxsSW5pdGlhbENvbnN1bWVzKXsKCQlfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFsbEluaXRpYWxDb25zdW1lcygpCgl9CgoJaWYoIV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pc01GUmVtb3RlICYmIF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5wcmVmZXRjaCl7CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucHJlZmV0Y2goKQoJfQp9'
}

Node.js v20.17.0

——————————————————————————————————————————————————————————————————————————————————————

 NX   Running target serve for project test failed

Failed tasks:

- test:serve:development

Hint: run the command with --verbose for more details.
```

### Expected Behavior

It should serve the remote application without failing.

### Steps to Reproduce

1. Generate a new nx workspace:
```
~/Desktop ❯ npx create-nx-workspace        
Need to install the following packages:
create-nx-workspace@19.8.3
Ok to proceed? (y) y


 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · org
✔ Which stack do you want to use? · react
✔ What framework would you like to use? · none
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · org
✔ Which bundler would you like to use? · webpack
✔ Test runner to use for end to end (E2E) tests · none
✔ Default stylesheet format · css
✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · skip

 NX   Creating your v19.8.3 workspace.

✔ Installing dependencies with npm
✔ Successfully created the workspace: org.
```

2. Generate the react remote project: `yarn run nx g @nx/react:remote --projectNameAndRootFormat=as-provided`

3. Serve the project: `npx nx run test:serve`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.17.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.2

nx                 : 19.8.3
@nx/js             : 19.8.3
@nx/jest           : 19.8.3
@nx/linter         : 19.8.3
@nx/eslint         : 19.8.3
@nx/workspace      : 19.8.3
@nx/devkit         : 19.8.3
@nx/eslint-plugin  : 19.8.3
@nx/react          : 19.8.3
@nrwl/tao          : 19.8.3
@nx/web            : 19.8.3
@nx/webpack        : 19.8.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
npm run nx run test:serve

> @org/source@0.0.0 nx
> npx nx run test:serve


> nx run test:serve:development


 NX  Starting module federation dev-server for test with 0 remotes


 NX  Starting static remotes proxies...


 NX  Static remotes proxies started successfully

[ Module Federation Manifest Plugin ]: Manifest will use absolute path resolution via its host at runtime, reason: publicPath='auto'
node:fs:2368
    return binding.writeFileUtf8(
                   ^

Error: ENAMETOOLONG: name too long, open 'data:text/javascript;charset=utf-8;base64,aW1wb3J0IGZlZGVyYXRpb24gZnJvbSAnL1VzZXJzL2Zsb3JlbnQucGFpbGhlcy9EZXNrdG9wL29yZy9ub2RlX21vZHVsZXMvQG1vZHVsZS1mZWRlcmF0aW9uL3dlYnBhY2stYnVuZGxlci1ydW50aW1lL2Rpc3QvaW5kZXguY2pzLmpzJzsKaW1wb3J0IHBsdWdpbl8wIGZyb20gJy9Vc2Vycy9mbG9yZW50LnBhaWxoZXMvRGVza3RvcC9vcmcvbm9kZV9tb2R1bGVzL0BueC93ZWJwYWNrL3NyYy91dGlscy9tb2R1bGUtZmVkZXJhdGlvbi9wbHVnaW5zL3J1bnRpbWUtbGlicmFyeS1jb250cm9sLnBsdWdpbi5qcyc7CmltcG9ydCBwbHVnaW5fMSBmcm9tICcvVXNlcnMvZmxvcmVudC5wYWlsaGVzL0Rlc2t0b3Avb3JnL25vZGVfbW9kdWxlcy9AbW9kdWxlLWZlZGVyYXRpb24vZGF0YS1wcmVmZXRjaC9kaXN0L3BsdWdpbi5lc20uanMnOwppbXBvcnQgcGx1Z2luXzIgZnJvbSAnL1VzZXJzL2Zsb3JlbnQucGFpbGhlcy9EZXNrdG9wL29yZy9ub2RlX21vZHVsZXMvQG1vZHVsZS1mZWRlcmF0aW9uL2RhdGEtcHJlZmV0Y2gvZGlzdC9zaGFyZWQuZXNtLmpzJzsKCmlmKCFfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucnVudGltZSl7Cgl2YXIgcHJldkZlZGVyYXRpb24gPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb247CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24gPSB7fQoJZm9yKHZhciBrZXkgaW4gZmVkZXJhdGlvbil7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uW2tleV0gPSBmZWRlcmF0aW9uW2tleV07Cgl9Cglmb3IodmFyIGtleSBpbiBwcmV2RmVkZXJhdGlvbil7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uW2tleV0gPSBwcmV2RmVkZXJhdGlvbltrZXldOwoJfQp9CmlmKCFfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFuY2UpewoJdmFyIHBsdWdpbnNUb0FkZCA9IFsKCQlwbHVnaW5fMCA/IChwbHVnaW5fMC5kZWZhdWx0IHx8IHBsdWdpbl8wKSgpIDogZmFsc2UsCgkJcGx1Z2luXzEgPyAocGx1Z2luXzEuZGVmYXVsdCB8fCBwbHVnaW5fMSkoKSA6IGZhbHNlLAoJCXBsdWdpbl8yID8gKHBsdWdpbl8yLmRlZmF1bHQgfHwgcGx1Z2luXzIpKCkgOiBmYWxzZSwKCV0uZmlsdGVyKEJvb2xlYW4pOwoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluaXRPcHRpb25zLnBsdWdpbnMgPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5pdE9wdGlvbnMucGx1Z2lucyA/IAoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluaXRPcHRpb25zLnBsdWdpbnMuY29uY2F0KHBsdWdpbnNUb0FkZCkgOiBwbHVnaW5zVG9BZGQ7CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFuY2UgPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucnVudGltZS5pbml0KF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbml0T3B0aW9ucyk7CglpZihfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uYXR0YWNoU2hhcmVTY29wZU1hcCl7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmF0dGFjaFNoYXJlU2NvcGVNYXAoX193ZWJwYWNrX3JlcXVpcmVfXykKCX0KCWlmKF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbnN0YWxsSW5pdGlhbENvbnN1bWVzKXsKCQlfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFsbEluaXRpYWxDb25zdW1lcygpCgl9CgoJaWYoIV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pc01GUmVtb3RlICYmIF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5wcmVmZXRjaCl7CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucHJlZmV0Y2goKQoJfQp9'
    at Object.writeFileSync (node:fs:2368:20)
    at FederationRuntimePlugin.ensureFile (/Users/root/Desktop/org/node_modules/@module-federation/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts:206:10)
    at FederationRuntimePlugin.getDependency (/Users/root/Desktop/org/node_modules/@module-federation/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts:222:10)
    at /Users/root/Desktop/org/node_modules/@module-federation/enhanced/src/lib/container/ContainerPlugin.ts:201:43
    at Hook.eval [as callAsync] (eval at create (/Users/root/Desktop/org/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:73:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/root/Desktop/org/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/root/Desktop/org/node_modules/webpack/lib/Compiler.js:1323:20
    at Hook.eval [as callAsync] (eval at create (/Users/root/Desktop/org/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/root/Desktop/org/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/root/Desktop/org/node_modules/webpack/lib/Compiler.js:1313:28) {
  errno: -63,
  code: 'ENAMETOOLONG',
  syscall: 'open',
  path: 'data:text/javascript;charset=utf-8;base64,aW1wb3J0IGZlZGVyYXRpb24gZnJvbSAnL1VzZXJzL2Zsb3JlbnQucGFpbGhlcy9EZXNrdG9wL29yZy9ub2RlX21vZHVsZXMvQG1vZHVsZS1mZWRlcmF0aW9uL3dlYnBhY2stYnVuZGxlci1ydW50aW1lL2Rpc3QvaW5kZXguY2pzLmpzJzsKaW1wb3J0IHBsdWdpbl8wIGZyb20gJy9Vc2Vycy9mbG9yZW50LnBhaWxoZXMvRGVza3RvcC9vcmcvbm9kZV9tb2R1bGVzL0BueC93ZWJwYWNrL3NyYy91dGlscy9tb2R1bGUtZmVkZXJhdGlvbi9wbHVnaW5zL3J1bnRpbWUtbGlicmFyeS1jb250cm9sLnBsdWdpbi5qcyc7CmltcG9ydCBwbHVnaW5fMSBmcm9tICcvVXNlcnMvZmxvcmVudC5wYWlsaGVzL0Rlc2t0b3Avb3JnL25vZGVfbW9kdWxlcy9AbW9kdWxlLWZlZGVyYXRpb24vZGF0YS1wcmVmZXRjaC9kaXN0L3BsdWdpbi5lc20uanMnOwppbXBvcnQgcGx1Z2luXzIgZnJvbSAnL1VzZXJzL2Zsb3JlbnQucGFpbGhlcy9EZXNrdG9wL29yZy9ub2RlX21vZHVsZXMvQG1vZHVsZS1mZWRlcmF0aW9uL2RhdGEtcHJlZmV0Y2gvZGlzdC9zaGFyZWQuZXNtLmpzJzsKCmlmKCFfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucnVudGltZSl7Cgl2YXIgcHJldkZlZGVyYXRpb24gPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb247CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24gPSB7fQoJZm9yKHZhciBrZXkgaW4gZmVkZXJhdGlvbil7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uW2tleV0gPSBmZWRlcmF0aW9uW2tleV07Cgl9Cglmb3IodmFyIGtleSBpbiBwcmV2RmVkZXJhdGlvbil7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uW2tleV0gPSBwcmV2RmVkZXJhdGlvbltrZXldOwoJfQp9CmlmKCFfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFuY2UpewoJdmFyIHBsdWdpbnNUb0FkZCA9IFsKCQlwbHVnaW5fMCA/IChwbHVnaW5fMC5kZWZhdWx0IHx8IHBsdWdpbl8wKSgpIDogZmFsc2UsCgkJcGx1Z2luXzEgPyAocGx1Z2luXzEuZGVmYXVsdCB8fCBwbHVnaW5fMSkoKSA6IGZhbHNlLAoJCXBsdWdpbl8yID8gKHBsdWdpbl8yLmRlZmF1bHQgfHwgcGx1Z2luXzIpKCkgOiBmYWxzZSwKCV0uZmlsdGVyKEJvb2xlYW4pOwoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluaXRPcHRpb25zLnBsdWdpbnMgPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5pdE9wdGlvbnMucGx1Z2lucyA/IAoJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmluaXRPcHRpb25zLnBsdWdpbnMuY29uY2F0KHBsdWdpbnNUb0FkZCkgOiBwbHVnaW5zVG9BZGQ7CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFuY2UgPSBfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucnVudGltZS5pbml0KF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbml0T3B0aW9ucyk7CglpZihfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uYXR0YWNoU2hhcmVTY29wZU1hcCl7CgkJX193ZWJwYWNrX3JlcXVpcmVfXy5mZWRlcmF0aW9uLmF0dGFjaFNoYXJlU2NvcGVNYXAoX193ZWJwYWNrX3JlcXVpcmVfXykKCX0KCWlmKF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pbnN0YWxsSW5pdGlhbENvbnN1bWVzKXsKCQlfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24uaW5zdGFsbEluaXRpYWxDb25zdW1lcygpCgl9CgoJaWYoIV9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5pc01GUmVtb3RlICYmIF9fd2VicGFja19yZXF1aXJlX18uZmVkZXJhdGlvbi5wcmVmZXRjaCl7CglfX3dlYnBhY2tfcmVxdWlyZV9fLmZlZGVyYXRpb24ucHJlZmV0Y2goKQoJfQp9'
}

Node.js v20.17.0
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by nadavshatz** [comment]
as mentioned in https://github.com/nrwl/nx/issues/28192 switching `@module-federation/enhanced` back to 0.6.6 solved it for us.

**Comment by linux-nerd** [comment]
> as mentioned in #28192 switching `@module-federation/enhanced` back to 0.6.6 solved it for us.

I am still getting the same error even if I change the version to 0.6.6

**Comment by Coly010** [comment]
Created an issue to track this here: https://github.com/module-federation/core/issues/3036

**Comment by nadavshatz** [comment]
@Coly010 

me too https://github.com/module-federation/core/issues/3035

should i close mine as duplicate?

**Comment by ScriptedAlchemy** [comment]
hi all. 
try canary version 0.0.0-next-20241002194835
Will release fix tomorrow once @Coly010 gives me the OK

**Comment by alex-zer0** [comment]
Any updates on this?

**Comment by ScriptedAlchemy** [comment]
All released on my side.

**Comment by Coly010** [comment]
Fixed by: https://github.com/nrwl/nx/pull/28296
