### ISSUE TITLE
Error: The externalDependency 'next' for 'besideme-fe:build' could not be found

### ISSUE THREAD

**Issue by angga1992** [nrwl/nx#28318]
### Current Behavior

Error: The externalDependency 'next' for '<project_name>:build' could not be found
    at NativeTaskHasherImpl.hashTasks (d:\asd\besideme-monorepo\node_modules\nx\src\hasher\native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (d:\asd\besideme-monorepo\node_modules\nx\src\hasher\task-hasher.js:62:50)
    at handleHashTasks (d:\asd\<repo_name>\node_modules\nx\src\daemon\server\handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (d:\asd\<repo_name>\node_modules\nx\src\daemon\server\server.js:172:16)
    at async handleMessage (d:\asd\<repo_name>\node_modules\nx\src\daemon\server\server.js:110:9)
    at async d:\asd\<repo_name>\node_modules\nx\src\daemon\server\server.js:72:9 {
  code: 'GenericFailure'
}

### Expected Behavior

The project must be built

### Steps to Reproduce

1. nx build <project_name> 

### Nx Report

$ nx report

 NX   Report complete - copy this into the issue template

Node           : 18.16.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 9.5.1

nx (global)        : 19.7.4
nx                 : 19.8.4
@nx/js             : 19.8.4
@nx/jest           : 19.8.4
@nx/linter         : 19.8.4
@nx/eslint         : 19.8.4
@nx/workspace      : 19.8.4
@nx/cypress        : 19.8.4
@nx/devkit         : 19.8.4
@nx/eslint-plugin  : 19.8.4
@nx/express        : 19.8.4
@nx/next           : 19.8.4
@nx/node           : 19.8.4
@nx/react          : 19.8.4
@nrwl/tao          : 19.8.4
@nx/web            : 19.8.4
@nx/webpack        : 19.8.4
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
@nx/cypress/plugin
@nx/next/plugin

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by jessicamrbr** [comment]
https://github.com/nrwl/nx/issues/28385#issuecomment-2885275280
