### ISSUE TITLE
[NX 20] any command results in disk I/O error

### ISSUE THREAD

**Issue by ryandegruyter** [nrwl/nx#28328]
### Current Behavior

Any NX command I run returns "Error: disk I/O error" near instantly

### Expected Behavior

No "Error: disk I/O error" thrown

### Steps to Reproduce

1. Upgrade from NX 19.8.2 to 20.0.0

### Nx Report

Node           : 20.13.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.5.2

nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 19.8.2
@nx/eslint-plugin  : 20.0.0
@nx/next           : 20.0.0
@nx/node           : 20.0.0
@nx/react          : 20.0.0
@nx/storybook      : 20.0.0
@nrwl/tao          : 19.8.4
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
Community plugins:
@ng-bootstrap/ng-bootstrap  : 17.0.1
@nx-aws-plugin/nx-aws-cache : 3.2.3
@storybook/angular          : 8.3.5
ngxtension                  : 4.0.0
---------------------------------------
The following packages should match the installed version of nx
  - @nx/devkit@19.8.2
  - @nrwl/devkit@19.8.2
  - @nrwl/tao@19.8.4

To fix this, run `nx migrate nx@20.0.0`

### Failure Logs

 NX   Custom task runners will no longer be supported in Nx 21.

Use Nx Cloud or the Nx Powerpack caches instead.
For more information, see https://nx.dev/features/powerpack/custom-caching

 NX   disk I/O error

Error: disk I/O error
    at ../node_modules/nx/src/utils/db-connection.js:11:93
    at getEntryOrSet (../node_modules/nx/src/utils/db-connection.js:19:17)
    at getDbConnection (../node_modules/nx/src/utils/db-connection.js:11:24)
    at getTaskDetails (../node_modules/nx/src/hasher/hash-task.js:19:84)
    at invokeTasksRunner (../node_modules/nx/src/tasks-runner/run-command.js:367:56)
    at runCommandForTasks (../node_modules/nx/src/tasks-runner/run-command.js:117:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ../node_modules/nx/src/tasks-runner/run-command.js:105:29
    at async handleErrors (../node_modules/nx/src/utils/handle-errors.js:9:24)
    at async runCommand (../node_modules/nx/src/tasks-runner/run-command.js:104:20)

### Package Manager Version

10.5.2

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Using a custom task runner:

```
"tasksRunnerOptions": {
    "default": {
      "runner": "@nx-aws-plugin/nx-aws-cache",
      "options": {
        "cacheableOperations": ["build", "component-test", "test", "build-storybook", "lint"]
      }
    }
  },
```

**Comment by ryandegruyter** [comment]
Sorry, this error came right after I upgraded to v20, but after downgrading back the error still persisted.
Rebooted my mac and the error is gone.
