### ISSUE TITLE
application generator buggy eventually breaks after name/directory options used spoiling cache

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#28358]
### Current Behavior

SUBJECT: application generator buggy eventually breaks after name/directory options used spoiling cache

freshly generated workspace for angular integrated

Just using command line to generate dry-runs

once developer begins to use name and/or directory parameters the generator spoils the cache and become unusable

recovery is not pinpointed as of yet

below is command line sequences exercised

Better QA is encouraged with specific focus on underlying cache 
```
meanstack02@admin nhhockeyplayer % nx g @nx/angular:application  --e2eTestRunner=none --style=scss --bundler=esbuild --skipTests=true --ssr=false --prefix=app --port=4200 --strict=true --linter=eslint --tags="scope:public,type:app,target:all" --directory=apps --name=admin   --dry-run 

 NX  Generating @nx/angular:application

CREATE apps/project.json
CREATE apps/src/index.html
CREATE apps/src/styles.scss
CREATE apps/tsconfig.app.json
CREATE apps/tsconfig.editor.json
CREATE apps/tsconfig.json
CREATE apps/public/favicon.ico
CREATE apps/src/app/app.component.scss
CREATE apps/src/app/app.component.html
CREATE apps/src/app/app.component.ts
CREATE apps/src/app/app.config.ts
CREATE apps/src/app/app.routes.ts
CREATE apps/src/main.ts
CREATE apps/src/app/nx-welcome.component.ts
CREATE apps/eslint.config.js
CREATE apps/jest.config.ts
CREATE apps/src/test-setup.ts
CREATE apps/tsconfig.spec.json

NOTE: The "dryRun" flag means no changes were made.
meanstack02@admin nhhockeyplayer % nx g @nx/angular:application apps/admin --e2eTestRunner=none --style=scss --bundler=esbuild --skipTests=true --ssr=false --prefix=app --port=4200 --strict=true --linter=eslint --tags="scope:public,type:app,target:all" --name=admin   --dry-run 

 NX  Generating @nx/angular:application

CREATE apps/admin/project.json
CREATE apps/admin/src/index.html
CREATE apps/admin/src/styles.scss
CREATE apps/admin/tsconfig.app.json
CREATE apps/admin/tsconfig.editor.json
CREATE apps/admin/tsconfig.json
CREATE apps/admin/public/favicon.ico
CREATE apps/admin/src/app/app.component.scss
CREATE apps/admin/src/app/app.component.html
CREATE apps/admin/src/app/app.component.ts
CREATE apps/admin/src/app/app.config.ts
CREATE apps/admin/src/app/app.routes.ts
CREATE apps/admin/src/main.ts
CREATE apps/admin/src/app/nx-welcome.component.ts
CREATE apps/admin/eslint.config.js
CREATE apps/admin/jest.config.ts
CREATE apps/admin/src/test-setup.ts
CREATE apps/admin/tsconfig.spec.json

NOTE: The "dryRun" flag means no changes were made.
meanstack02@admin nhhockeyplayer % nx g @nx/angular:application  --e2eTestRunner=none --style=scss --bundler=esbuild --skipTests=true --ssr=false --prefix=app --port=4200 --strict=true --linter=eslint --tags="scope:public,type:app,target:all" --directory=apps  --dry-run  

 NX  Generating @nx/angular:application

CREATE apps/project.json
CREATE apps/src/index.html
CREATE apps/src/styles.scss
CREATE apps/tsconfig.app.json
CREATE apps/tsconfig.editor.json
CREATE apps/tsconfig.json
CREATE apps/public/favicon.ico
CREATE apps/src/app/app.component.scss
CREATE apps/src/app/app.component.html
CREATE apps/src/app/app.component.ts
CREATE apps/src/app/app.config.ts
CREATE apps/src/app/app.routes.ts
CREATE apps/src/main.ts
CREATE apps/src/app/nx-welcome.component.ts
CREATE apps/eslint.config.js
CREATE apps/jest.config.ts
CREATE apps/src/test-setup.ts
CREATE apps/tsconfig.spec.json

NOTE: The "dryRun" flag means no changes were made.
meanstack02@admin nhhockeyplayer % nx g @nx/angular:application apps/admin --e2eTestRunner=none --style=scss --bundler=esbuild --skipTests=true --ssr=false --prefix=app --port=4200 --strict=true --linter=eslint --tags="scope:public,type:app,target:all" --name=admin   --dry-run

 NX  Generating @nx/angular:application

CREATE apps/admin/project.json
CREATE apps/admin/src/index.html
CREATE apps/admin/src/styles.scss
CREATE apps/admin/tsconfig.app.json
CREATE apps/admin/tsconfig.editor.json
CREATE apps/admin/tsconfig.json
CREATE apps/admin/public/favicon.ico
CREATE apps/admin/src/app/app.component.scss
CREATE apps/admin/src/app/app.component.html
CREATE apps/admin/src/app/app.component.ts
CREATE apps/admin/src/app/app.config.ts
CREATE apps/admin/src/app/app.routes.ts
CREATE apps/admin/src/main.ts
CREATE apps/admin/src/app/nx-welcome.component.ts
CREATE apps/admin/eslint.config.js
CREATE apps/admin/jest.config.ts
CREATE apps/admin/src/test-setup.ts
CREATE apps/admin/tsconfig.spec.json

NOTE: The "dryRun" flag means no changes were made.
meanstack02@admin nhhockeyplayer % nx g @nx/angular:application apps/admin --e2eTestRunner=none --style=scss --bundler=esbuild --skipTests=true --ssr=false --prefix=app --port=4200 --strict=true --linter=eslint --tags="scope:public,type:app,target:all" --name=admin   --dry-run

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

meanstack02@admin nhhockeyplayer % nx g @nx/angular:application apps/admin --e2eTestRunner=none --style=scss --bundler=esbuild --skipTests=true --ssr=false --prefix=app --port=4200 --strict=true --linter=eslint --tags="scope:public,type:app,target:all" --name=admin   --dry-run

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

meanstack02@admin nhhockeyplayer % nx g @nx/angular:application  --e2eTestRunner=none --style=scss --bundler=esbuild --skipTests=true --ssr=false --prefix=app --port=4200 --strict=true --linter=eslint --tags="scope:public,type:app,target:all" --directory=apps  --dry-run       

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

meanstack02@admin nhhockeyplayer % nx g @nx/angular:application apps/admin --e2eTestRunner=none --style=scss --bundler=esbuild --skipTests=true --ssr=false --prefix=app --port=4200 --strict=true --linter=eslint --tags="scope:public,type:app,target:all" --name=admin   --dry-run

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

meanstack02@admin nhhockeyplayer % nx g @nx/angular:application apps/admin --e2eTestRunner=none --style=scss --bundler=esbuild --skipTests=true --ssr=false --prefix=app --port=4200 --strict=true --linter=eslint --tags="scope:public,type:app,target:all"   --dry-run                              

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.
```

### Expected Behavior

generator should run gracefully and not quit with spoiled cache unrecoverable

### Steps to Reproduce

see description

### Nx Report

nx report

 NX   Report complete - copy this into the issue template

Node           : 22.4.1
OS             : darwin-x64
Native Target  : x86_64-macos
yarn           : 1.22.22

nx (global)        : 20.0.0
nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/node           : 20.0.0
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@ionic/angular       : 8.3.2
@nxext/capacitor     : 19.1.2
@nxext/ionic-angular : 19.1.2
---------------------------------------
⚠️ Unable to construct project graph.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/eslint/plugin plugin.
    - .eslintrc.json: Failed to load plugin 'react' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-react'
  Require stack:
  - /Users/meanstack02/nhhockeyplayer/__placeholder__.js
      Error: Failed to load plugin 'react' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-react'
      Require stack:
      - /Users/meanstack02/nhhockeyplayer/__placeholder__.js
          at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
          at Function.resolve (node:internal/modules/helpers:133:19)
          at Object.resolve (/Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2372:46)
          at ConfigArrayFactory._loadPlugin (/Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3440:33)
          at /Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3330:33
          at Array.reduce (<anonymous>)
          at ConfigArrayFactory._loadPlugins (/Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3326:22)
          at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3126:44)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
          at ConfigArrayFactory._normalizeObjectConfigData (/Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3066:20)

### Failure Logs

see above

### Package Manager Version

yarn 1.22.22

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by nhhockeyplayer** [comment]
more info

deleting all cache, reinstalling node_modules seems to get some things back

staying away from directory option helps

but this command sequence worked but had subsequent failures advising to nx reset which did nothing

```
nx g @nx/angular:application apps/admin --e2eTestRunner=none --style=scss --bundler=esbuild --skipTests=true --ssr=false --prefix=app --port=4200 --strict=true --linter=eslint --tags="scope:public,type:app,target:all" --name=admin            

 NX  Generating @nx/angular:application

CREATE apps/admin/project.json
CREATE apps/admin/src/index.html
CREATE apps/admin/src/styles.scss
CREATE apps/admin/tsconfig.app.json
CREATE apps/admin/tsconfig.editor.json
CREATE apps/admin/tsconfig.json
CREATE apps/admin/public/favicon.ico
CREATE apps/admin/src/app/app.component.scss
CREATE apps/admin/src/app/app.component.html
CREATE apps/admin/src/app/app.component.ts
CREATE apps/admin/src/app/app.config.ts
CREATE apps/admin/src/app/app.routes.ts
CREATE apps/admin/src/main.ts
CREATE apps/admin/src/app/nx-welcome.component.ts
CREATE apps/admin/eslint.config.js
CREATE apps/admin/jest.config.ts
CREATE apps/admin/src/test-setup.ts
CREATE apps/admin/tsconfig.spec.json

 NX   👀 View Details of admin

Run "nx show project admin" to view details about this project.

meanstack02@admin nhhockeyplayer % nx run-many --all --target=build --parallel

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

meanstack02@admin nhhockeyplayer % nx reset

 NX   Resetting the Nx cache and stopping the daemon.



 NX   Cleaning up temporary files created by Nx Cloud.

meanstack02@admin nhhockeyplayer % nx run-many --all --target=build --parallel

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.


```

**Comment by nhhockeyplayer** [comment]
wish I had better to report but the product is currently broken
and all fluid development is hampered
cannot get out of the nx reset trap and whatever form the underlying cache has taken on

alot of stuff is being affected

cannot operate nxext generators

**Comment by nhhockeyplayer** [comment]
hope this helps

its my custom script launched
build fails
--verbose indicates failures


source .clean.zsh
```

 NX   Resetting the Nx cache and stopping the daemon.



 NX   Cleaning up temporary files created by Nx Cloud.

yarn install v1.22.22
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning @nx/angular > @nx/webpack > stylus > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @nx/angular > @nx/webpack > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
warning @nx/angular > @nx/webpack > stylus > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning @nx/jest > jest-config > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @nx/jest > @jest/reporters > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @nx/jest > jest-config > jest-circus > jest-runtime > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @nx/jest > jest-config > babel-jest > babel-plugin-istanbul > test-exclude > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning jest-environment-jsdom > jsdom > abab@2.0.6: Use your platform's native atob() and btoa() methods instead
warning jest-environment-jsdom > jsdom > data-urls > abab@2.0.6: Use your platform's native atob() and btoa() methods instead
warning jest-environment-jsdom > jsdom > domexception@4.0.0: Use your platform's native DOMException instead
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@nx/angular > @module-federation/enhanced > @module-federation/data-prefetch@0.6.6" has unmet peer dependency "react@>=16.9.0".
warning "@nx/angular > @module-federation/enhanced > @module-federation/data-prefetch@0.6.6" has unmet peer dependency "react-dom@>=16.9.0".
warning "@nx/angular > @nx/webpack > @module-federation/enhanced > @module-federation/data-prefetch@0.6.9" has unmet peer dependency "react@>=16.9.0".
warning "@nx/angular > @nx/webpack > @module-federation/enhanced > @module-federation/data-prefetch@0.6.9" has unmet peer dependency "react-dom@>=16.9.0".
warning " > @nx/eslint-plugin@20.0.0" has unmet peer dependency "@typescript-eslint/parser@^6.13.2 || ^7.0.0 || ^8.0.0".
warning " > @nxext/capacitor@19.1.2" has unmet peer dependency "@nx/devkit@^19.0.0".
warning " > @nxext/capacitor@19.1.2" has incorrect peer dependency "nx@^19.0.0".
warning " > @nxext/ionic-angular@19.1.2" has unmet peer dependency "@nx/devkit@^19.0.0".
warning " > @nxext/ionic-angular@19.1.2" has incorrect peer dependency "@nx/angular@^19.0.0".
warning "@swc-node/register > @swc-node/core@1.13.3" has unmet peer dependency "@swc/types@>= 0.1".
warning " > eslint-config-airbnb@19.0.4" has incorrect peer dependency "eslint@^7.32.0 || ^8.2.0".
warning " > eslint-config-airbnb@19.0.4" has unmet peer dependency "eslint-plugin-import@^2.25.3".
warning " > eslint-config-airbnb@19.0.4" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.5.1".
warning " > eslint-config-airbnb@19.0.4" has unmet peer dependency "eslint-plugin-react@^7.28.0".
warning " > eslint-config-airbnb@19.0.4" has unmet peer dependency "eslint-plugin-react-hooks@^4.3.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@15.0.0" has incorrect peer dependency "eslint@^7.32.0 || ^8.2.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@15.0.0" has unmet peer dependency "eslint-plugin-import@^2.25.2".
warning " > eslint-config-airbnb-typescript@18.0.0" has unmet peer dependency "@typescript-eslint/eslint-plugin@^7.0.0".
warning " > eslint-config-airbnb-typescript@18.0.0" has unmet peer dependency "@typescript-eslint/parser@^7.0.0".
warning " > eslint-config-airbnb-typescript@18.0.0" has incorrect peer dependency "eslint@^8.56.0".
warning " > eslint-plugin-prettier@5.2.1" has incorrect peer dependency "prettier@>=3.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ husky
✨  Done in 42.51s.

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/eslint/plugin plugin.
    - .eslintrc.json: Failed to load plugin 'react' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-react'
  Require stack:
  - /Users/meanstack02/nhhockeyplayer/__placeholder__.js
      Error: Failed to load plugin 'react' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-react'
      Require stack:
      - /Users/meanstack02/nhhockeyplayer/__placeholder__.js
          at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
          at Function.resolve (node:internal/modules/helpers:133:19)
          at Object.resolve (/Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2372:46)
          at ConfigArrayFactory._loadPlugin (/Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3440:33)
          at /Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3330:33
          at Array.reduce (<anonymous>)
          at ConfigArrayFactory._loadPlugins (/Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3326:22)
          at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3126:44)
          at _normalizeObjectConfigDataBody.next (<anonymous>)
          at ConfigArrayFactory._normalizeObjectConfigData (/Users/meanstack02/nhhockeyplayer/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3066:20)

[NX CLOUD] Verifying current cloud bundle
[NX CLOUD] A local bundle currently exists:  {
  version: '2409.26.3.hotfix7',
  fullPath: '/Users/meanstack02/nhhockeyplayer/.nx/cache/cloud/2409.26.3.hotfix7'
}
[NX CLOUD] Last verification was within the past 30 minutes, will not verify this time
[NX CLOUD] Done:  /Users/meanstack02/nhhockeyplayer/.nx/cache/cloud/2409.26.3.hotfix7
Was not able to require.resolve module nx/src/utils/app-root from the following paths: /Users/meanstack02/nhhockeyplayer/node_modules/nx/node_modules,/Users/meanstack02/nhhockeyplayer/node_modules. This may be expected.
Was not able to require.resolve module nx/src/utils/app-root from the following paths: /Users/meanstack02/nhhockeyplayer/node_modules/nx/node_modules,/Users/meanstack02/nhhockeyplayer/node_modules. This may be expected.

 NX   Running target build for project admin:

- admin

—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[NX CLOUD] Verifying current cloud bundle
[NX CLOUD] A local bundle currently exists:  {
  version: '2409.26.3.hotfix7',
  fullPath: '/Users/meanstack02/nhhockeyplayer/.nx/cache/cloud/2409.26.3.hotfix7'
}
[NX CLOUD] Last verification was within the past 30 minutes, will not verify this time
[NX CLOUD] Done:  /Users/meanstack02/nhhockeyplayer/.nx/cache/cloud/2409.26.3.hotfix7
[Nx Cloud Debug] Attempting to acquire filesystem lock with path:  /var/folders/73/pgw9tfdj5fz826zd6cc4p0vr0000gn/T/client-instance-id.lock
[Nx Cloud Debug] Failed to create folder lock at path: /var/folders/73/pgw9tfdj5fz826zd6cc4p0vr0000gn/T/client-instance-id.lock
[Nx Cloud] Unable to detect a VCS context from the environment.

 NX   RunStart


{
  "meta": {},
  "branch": null,
  "runGroup": "2f747330d4428e702300059e11692d21c2d8efe2",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "3446513663275156481"
  ],
  "machineInfo": {
    "machineId": "uHiOzR0l5SEx0kjZqAemHQ==",
    "platform": "darwin",
    "version": "Darwin Kernel Version 21.6.0: Mon Jun 24 00:56:10 PDT 2024; root:xnu-8020.240.18.709.2~1/RELEASE_X86_64",
    "cpuCores": 8
  },
  "vcsContext": null,
  "clientInstanceSource": "CLOUD_RUNNER",
  "clientInstanceId": "ffd901d3-bf68-4b23-b4d3-68a6393c6365"
}

[Nx Cloud] Unable to detect a VCS context from the environment.

 NX   RunStart


{
  "meta": {},
  "branch": null,
  "runGroup": "2f747330d4428e702300059e11692d21c2d8efe2",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "3446513663275156481"
  ],
  "machineInfo": {
    "machineId": "uHiOzR0l5SEx0kjZqAemHQ==",
    "platform": "darwin",
    "version": "Darwin Kernel Version 21.6.0: Mon Jun 24 00:56:10 PDT 2024; root:xnu-8020.240.18.709.2~1/RELEASE_X86_64",
    "cpuCores": 8
  },
  "vcsContext": null,
  "clientInstanceSource": "CLOUD_RUNNER",
  "clientInstanceId": "ffd901d3-bf68-4b23-b4d3-68a6393c6365"
}

RunStart duration: 193

 NX   FileStorage: streaming and extracting tar file

RunStart duration: 143

 NX   Nx Cloud: Downloaded 3446513663275156481


 NX   FileStorage: streaming and extracting tar file


 NX   Nx Cloud: Downloaded 3446513663275156481


> nx run admin:build:production  [remote cache]

❯ Building...
✔ Building...
Initial chunk files   | Names                |  Raw size | Estimated transfer size
chunk-JQAHFB76.js     | -                    | 404.84 kB |                99.23 kB
chunk-DOW4AU2V.js     | -                    |  38.14 kB |                12.61 kB
polyfills-FFHMD2TL.js | polyfills            |  34.52 kB |                11.28 kB
styles-LUF7REVR.css   | styles               |  29.31 kB |                 4.44 kB
chunk-C7OZ3V6J.js     | -                    |  10.29 kB |                 2.66 kB
chunk-5SHXISE6.js     | -                    |   9.26 kB |                 3.45 kB
chunk-NMYJD6OP.js     | -                    |   5.83 kB |                 2.15 kB
chunk-ROYJEYAU.js     | -                    |   3.18 kB |                 1.40 kB
chunk-7OESLGL2.js     | -                    |   2.43 kB |               872 bytes
chunk-B43CU5JX.js     | -                    |   1.02 kB |                 1.02 kB
main-LSLS4YIM.js      | main                 | 972 bytes |               972 bytes
chunk-IEWWQXK7.js     | -                    | 946 bytes |               946 bytes
chunk-B4QOHBYD.js     | -                    | 933 bytes |               933 bytes
chunk-JHI3MBHO.js     | -                    | 928 bytes |               928 bytes
chunk-F2CX2ZOZ.js     | -                    | 876 bytes |               876 bytes
chunk-TQEIIVVC.js     | -                    | 541 bytes |               541 bytes
chunk-F7XBNY6P.js     | -                    | 183 bytes |               183 bytes
chunk-4WFVMWDK.js     | -                    | 103 bytes |               103 bytes
chunk-LF5XB4YN.js     | -                    |  99 bytes |                99 bytes

                      | Initial total        | 544.39 kB |               144.69 kB

Lazy chunk files      | Names                |  Raw size | Estimated transfer size
chunk-GOQXB5UB.js     | input-shims          |   4.93 kB |                 1.91 kB
chunk-AEH2CUDJ.js     | shadow-css           |   4.17 kB |                 1.87 kB
chunk-TVGWM4AP.js     | shadow-css           |   4.17 kB |                 1.87 kB
chunk-DNM6ORMH.js     | tabs-routes          |   2.99 kB |                 1.16 kB
chunk-B3L364QS.js     | index9               |   1.60 kB |               746 bytes
chunk-EDNUWEGF.js     | tab1-page            |   1.21 kB |               545 bytes
chunk-FV6QYQWP.js     | tab2-page            |   1.21 kB |               545 bytes
chunk-P5OE7UWU.js     | tab3-page            |   1.21 kB |               545 bytes
chunk-4QAQ6KRI.js     | -                    | 994 bytes |               994 bytes
chunk-FA25AEA4.js     | focus-visible        | 952 bytes |               952 bytes
chunk-ESJZE34O.js     | swipe-back           | 685 bytes |               685 bytes
chunk-4MTZSAMP.js     | status-tap           | 567 bytes |               567 bytes
chunk-NY7FVCUI.js     | keyboard2            | 404 bytes |               404 bytes
chunk-P7N4VPWV.js     | hardware-back-button | 314 bytes |               314 bytes
chunk-2XRCCSQS.js     | ios-transition       | 282 bytes |               282 bytes
...and 2 more lazy chunks files. Use "--verbose" to show all the files.

Application bundle generation complete. [9.251 seconds]

▲ [WARNING] The glob pattern import("./**/*.entry.js*") did not match any files [empty-glob]

    node_modules/@ionic/core/node_modules/@stencil/core/internal/client/index.js:82:2:
      82 │   `./${bundleId}.entry.js${BUILD4.hotModuleReplacement && hmrVersi...
         ╵   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


▲ [WARNING] The glob pattern import("./**/*.entry.js*") did not match any files [empty-glob]

    node_modules/@stencil/core/internal/client/index.js:82:2:
      82 │   `./${bundleId}.entry.js${BUILD4.hotModuleReplacement && hmrVersi...
         ╵   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


▲ [WARNING] bundle initial exceeded maximum budget. Budget 512.00 kB was not met by 32.39 kB with a total of 544.39 kB.


▲ [WARNING] 20 rules skipped due to selector errors:
  :host-context([dir=rtl]) .ion-float-start -> Unknown pseudo-class :host-context([object Object])
  .ion-float-start:dir(rtl) -> Unknown pseudo-class :dir
  :host-context([dir=rtl]) .ion-float-end -> Unknown pseudo-class :host-context([object Object])
  .ion-float-end:dir(rtl) -> Unknown pseudo-class :dir
  :host-context([dir=rtl]) .ion-float-sm-start -> Unknown pseudo-class :host-context([object Object])
  .ion-float-sm-start:dir(rtl) -> Unknown pseudo-class :dir
  :host-context([dir=rtl]) .ion-float-sm-end -> Unknown pseudo-class :host-context([object Object])
  .ion-float-sm-end:dir(rtl) -> Unknown pseudo-class :dir
  :host-context([dir=rtl]) .ion-float-md-start -> Unknown pseudo-class :host-context([object Object])
  .ion-float-md-start:dir(rtl) -> Unknown pseudo-class :dir
  :host-context([dir=rtl]) .ion-float-md-end -> Unknown pseudo-class :host-context([object Object])
  .ion-float-md-end:dir(rtl) -> Unknown pseudo-class :dir
  :host-context([dir=rtl]) .ion-float-lg-start -> Unknown pseudo-class :host-context([object Object])
  .ion-float-lg-start:dir(rtl) -> Unknown pseudo-class :dir
  :host-context([dir=rtl]) .ion-float-lg-end -> Unknown pseudo-class :host-context([object Object])
  .ion-float-lg-end:dir(rtl) -> Unknown pseudo-class :dir
  :host-context([dir=rtl]) .ion-float-xl-start -> Unknown pseudo-class :host-context([object Object])
  .ion-float-xl-start:dir(rtl) -> Unknown pseudo-class :dir
  :host-context([dir=rtl]) .ion-float-xl-end -> Unknown pseudo-class :host-context([object Object])
  .ion-float-xl-end:dir(rtl) -> Unknown pseudo-class :dir


Output location: /Users/meanstack02/nhhockeyplayer/dist/apps/admin


—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target build for project admin

Nx read the output from the cache instead of running the command for 1 out of 1 tasks.

Nx Cloud made it possible to reuse admin: https://nx.app/runs/BqPcHxXGRo


> nx run admin:serve:development

Initial chunk files | Names         |  Raw size
polyfills.js        | polyfills     |  90.20 kB | 
styles.css          | styles        |  35.67 kB | 
main.js             | main          |   1.70 kB | 

                    | Initial total | 127.57 kB

Lazy chunk files    | Names         |  Raw size
chunk-KJ3M6DGW.js   | tabs-routes   |   2.86 kB | 
chunk-JAACAOCW.js   | -             |   2.13 kB | 
chunk-4643L56Z.js   | tab1-page     |   1.78 kB | 
chunk-7Q4PGLJ7.js   | tab2-page     |   1.78 kB | 
chunk-IL4U33OD.js   | tab3-page     |   1.78 kB | 

Application bundle generation complete. [3.227 seconds]

Watch mode enabled. Watching for file changes...
NOTE: Raw file sizes do not reflect development server per-request transformations.
  ➜  Local:   http://localhost:4200/
  ➜  press h + enter to show help


```

**Comment by Coly010** [comment]
Hey @nhhockeyplayer 

It's really quite difficult to decipher what exactly the issue is here in this thread.

From my understanding, when you generate a new angular application, the project graph is unable to be built because of an issue with the `@nx/eslint/plugin`?

**Comment by nhhockeyplayer** [comment]
this issue https://github.com/nrwl/nx/issues/28388
 should be prioritized as IMMEDIATE patch and fix it immediately
it covers alot of what other users are reporting in their issues failing locally as of recent

closing this ticket as duplicate

hopefully they will patch and get this one first https://github.com/nrwl/nx/issues/28388
 to fix everything under the hood

**Comment by nhhockeyplayer** [comment]
this issue https://github.com/nrwl/nx/issues/28388
 should be prioritized as IMMEDIATE patch and fix it immediately
it covers alot of what other users are reporting in their issues failing locally as of recent

closing this ticket as duplicate

hopefully they will patch and get this one first https://github.com/nrwl/nx/issues/28388
 to fix everything under the hood
