### ISSUE TITLE
nx serve fails running the project.

### ISSUE THREAD

**Issue by edvardma** [nrwl/nx#28371]
### Current Behavior

Hi, I developed my MFE application using nx. I keep getting this error when starting serve or building. Please help me out.

`Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.`

The issue persists after running nx reset and that's why I'm reporting here. 

### Expected Behavior

after running nx serve-host [host or appName] , serve the project on 4200 or etc.

### GitHub Repo

https://github.com/edvardma/project

### Steps to Reproduce

1. nx serve-host host
2. nx serve-host [app name]

### Nx Report

nx report                                                                       1 ✘  system 

 NX   Report complete - copy this into the issue template

Node           : 20.17.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.12.1

nx (global)        : 19.2.2
nx                 : 19.6.5
@nx/js             : 19.8.0
@nx/jest           : 19.6.5
@nx/eslint         : 19.6.5
@nx/workspace      : 19.6.5
@nx/eslint-plugin  : 19.6.5
@nx/react          : 19.6.5
@nx/vite           : 19.8.0
@nrwl/vite         : 19.6.5
@nx/vue            : 19.8.0
@nx/web            : 19.8.0
@nx/webpack        : 19.6.5
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
---------------------------------------
The following packages should match the installed version of nx
  - @nx/js@19.8.0
  - @nx/vite@19.8.0
  - @nx/vue@19.8.0
  - @nx/web@19.8.0

To fix this, run `nx migrate nx@19.8.0`

### Failure Logs

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

### Operating System

- [x] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by e-oz** [comment]
You could try adding “--verbose” to see the reason.

**Comment by edvardma** [comment]
Thanks @e-oz for your comment, this is what I get after --verbose. But still can't figure the problem out.

```
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

  The "nx/js/dependencies-and-lockfile" plugin threw an error while creating dependencies:

    Error: "Unable to load /Users/edvard/mobingilabs/v2/ripple-ui/apps/vue-app/vite.config.mts.timestamp-1728452906443-9f9ff60e9db2a.mjs: No such file or directory (os error 2)\nUnable to load /Users/edvard/mobingilabs/v2/ripple-ui/apps/invoices/vite.config.mts.timestamp-1728452906441-0956df084d791.mjs: No such file or directory (os error 2)\nUnable to load /Users/edvard/mobingilabs/v2/ripple-ui/apps/host/vite.config.mts.timestamp-1728452906439-9187bc3856d11.mjs: No such file or directory (os error 2)"
        at buildExplicitTypeScriptDependencies (/Users/edvard/mobingilabs/v2/ripple-ui/node_modules/.pnpm/nx@19.6.5_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_q57b7p7vk6b3yhorxjo3xgfo3q/node_modules/nx/src/plugins/js/project-graph/build-dependencies/explicit-project-dependencies.js:50:21)
        at buildExplicitDependencies (/Users/edvard/mobingilabs/v2/ripple-ui/node_modules/.pnpm/nx@19.6.5_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_q57b7p7vk6b3yhorxjo3xgfo3q/node_modules/nx/src/plugins/js/project-graph/build-dependencies/build-dependencies.js:32:120)
        at Object.createDependencies (/Users/edvard/mobingilabs/v2/ripple-ui/node_modules/.pnpm/nx@19.6.5_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_q57b7p7vk6b3yhorxjo3xgfo3q/node_modules/nx/src/plugins/js/index.js:81:92)
        at LoadedNxPlugin.createDependencies (/Users/edvard/mobingilabs/v2/ripple-ui/node_modules/.pnpm/nx@19.6.5_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_q57b7p7vk6b3yhorxjo3xgfo3q/node_modules/nx/src/project-graph/plugins/internal-api.js:60:59)
        at createDependencies (/Users/edvard/mobingilabs/v2/ripple-ui/node_modules/.pnpm/nx@19.6.5_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_q57b7p7vk6b3yhorxjo3xgfo3q/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:88:49)
        at consumeMessage (/Users/edvard/mobingilabs/v2/ripple-ui/node_modules/.pnpm/nx@19.6.5_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_q57b7p7vk6b3yhorxjo3xgfo3q/node_modules/nx/src/project-graph/plugins/isolation/messaging.js:38:32)
        at /Users/edvard/mobingilabs/v2/ripple-ui/node_modules/.pnpm/nx@19.6.5_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_q57b7p7vk6b3yhorxjo3xgfo3q/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:21:47
        at Socket.<anonymous> (/Users/edvard/mobingilabs/v2/ripple-ui/node_modules/.pnpm/nx@19.6.5_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_q57b7p7vk6b3yhorxjo3xgfo3q/node_modules/nx/src/utils/consume-messages-from-socket.js:13:17)
        at Socket.emit (node:events:519:28)
        at addChunk (node:internal/streams/readable:559:12)
```

**Comment by Coly010** [comment]
@edvardma Looks like you have a vite timestamp file that never got cleaned up. It only exists on your local and not in the repo you linked. I couldn't reproduce the issue when I ran it.

It could be related to the `serve-host` command running a bunch of vite commands serially. 

I'd attempt to potentially run them in a single command such as:

`nx run myproject:serve & nx run vueapp:serve` etc.

I think there might still be something we can do on our side to avoid loading the timestamp files

**Comment by edvardma** [comment]
@Coly010 Thank you for looking into this. I tried deleting and git clone and reinstalling everything again, but the issue persists.

Although I have tried running the suggested approach with the:
`nx run myproject:serve & nx run vueapp:serve` and still get `Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it`.

If there’s anything you can do on your side to prevent loading the timestamp files, that would be great. Let me know if you need more details from my end.

Thanks again for your help!
