### ISSUE TITLE
cannot execute contiguous NX command sequences in script

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#28373]
### Current Behavior

SUBJECT: cannot execute contiguous NX command sequences in script

Would like to reconstruct my new monorepo to the form of the one that failed to migrate
so I created a script

NX is not capable of handling contiguous NX command sequences in script

run this script from shell at root of workspace

and nx-reset says no to further processing/execution

if underlying cache is being operated this cache should be pristine inside/out

more QA is encouraged

hoping for quick patch so development can proceed

thanks for awesome product

### Expected Behavior

NX command sequences should execute uninterrupted fluidly from script within zsh shell

### Steps to Reproduce

run this script from workspace root
it quits after 1st line and stuck

```
/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/admin/root/feature-shell --buildable=true --lazy=true --name=feature-shell --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/admin-root-feature-shell --prefix=feature-shell --selector=feature-shell --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive --verbose
nx build feature-shell --verbose
/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/js:library --directory=libs/graphql --bundler=esbuild --importPath=@nhhockeyplayer/graphql --linter=eslint --name=graphql --unitTestRunner=jest --includeBabelRc=true "--tags=\"scope:public, type:util, target:all\"" --useProjectJson=true --compiler=tsc --no-interactive --verbose

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/api-service --buildable=true --lazy=false --name=api-service --routing=false --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/api-service --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/feature/auth --buildable=true --lazy=true --name=auth --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-feature-auth --prefix=auth --selector=auth --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/feature/user --buildable=true --lazy=true --name=user --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-feature-user --prefix=user --selector=user --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/feature/notification --buildable=true --lazy=true --name=notification --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-feature-notification --prefix=notification --selector=notification --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/feature/setting --buildable=true --lazy=true --name=setting --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-feature-setting --prefix=setting --selector=setting --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/feature/user --buildable=true --lazy=true --name=user --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-feature-user --prefix=user --selector=user --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/data-access --buildable=true --lazy=false --name=data-access --routing=false --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-data-access --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/js:library --directory=shared/util/environment --bundler=esbuild --importPath=@nhhockeyplayer/shared-util-environment --linter=eslint --name=environment --unitTestRunner=jest --includeBabelRc=true "--tags=\"scope:public, type:util, target:all\"" --useProjectJson=true --compiler=tsc --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/security/auth --buildable=true --lazy=true --name=service --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-security-auth --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/security/auth --buildable=true --lazy=true --name=auth --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-security-auth --prefix=auth --selector=auth --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/service --buildable=true --lazy=false --name=service --routing=false --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-service --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/ui-animation --buildable=true --lazy=true --name=ui-animation --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-ui-animation --prefix=ui-animation --selector=ui-animation --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/ui-assets --buildable=true --lazy=true --name=ui-assets --publishable=true --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-ui-assets --prefix=ui-assets --selector=ui-assets --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/ui-custom-material --buildable=true --lazy=true --name=ui-custom-material --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-ui-custom-material --prefix=ui-custom-material --selector=ui-custom-material --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/ui-shared-material --buildable=true --lazy=true --name=ui-shared-material --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-ui-shared-material --prefix=ui-shared-material --selector=ui-shared-material --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/ui-spinner --buildable=true --lazy=true --name=ui-spinner --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-ui-spinner --prefix=ui-spinner --selector=ui-spinner --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/ui-styles --buildable=true --lazy=true --name=ui-styles --publishable=true --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-ui-styles --prefix=ui-styles --selector=ui-styles --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:library --directory=libs/shared/root/ui-widget --buildable=true --lazy=true --name=ui-widget --publishable=true --routing=true --compilationMode=partial --displayBlock=true --flat=true --importPath=@nhhockeyplayer/shared-root-ui-widget --prefix=ui-widget --selector=ui-widget --skipSelector=true --skipTests=true --style=scss "--tags=\"scope:public, type:ui, target:all\"" --viewEncapsulation=Emulated --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/js:library --directory=shared/root/util --bundler=esbuild --importPath=@nhhockeyplayer/shared-root-util --linter=eslint --name=util --unitTestRunner=jest --includeBabelRc=true "--tags=\"scope:public, type:util, target:all\"" --useProjectJson=true --compiler=tsc --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/js:library --directory=shared/util/isomorphic --bundler=esbuild --importPath=@nhhockeyplayer/shared-util-isomorphic --linter=eslint --name=isomorphic --unitTestRunner=jest --includeBabelRc=true "--tags=\"scope:public, type:util, target:all\"" --useProjectJson=true --compiler=tsc --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/js:library --directory=shared/util/models --bundler=esbuild --importPath=@nhhockeyplayer/shared-util-models --linter=eslint --name=models --unitTestRunner=jest --includeBabelRc=true "--tags=\"scope:public, type:util, target:all\"" --useProjectJson=true --compiler=tsc --no-interactive

/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/js:library --directory=shared/util/utility --bundler=esbuild --importPath=@nhhockeyplayer/shared-util-utility --linter=eslint --name=utility --unitTestRunner=jest --includeBabelRc=true "--tags=\"scope:public, type:util, target:all\"" --useProjectJson=true --compiler=tsc --no-interactive

```

### Nx Report

nx report

 NX   Report complete - copy this into the issue template

Node           : 20.18.0
OS             : darwin-x64
Native Target  : x86_64-macos
yarn           : 1.22.22

nx (global)        : 20.0.0
nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/node           : 20.0.0
@nx/storybook      : 20.0.0
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@ionic/angular        : 8.3.2
@ngrx/component       : 18.0.2
@ngrx/component-store : 18.0.2
@ngrx/effects         : 18.0.2
@ngrx/entity          : 18.0.2
@ngrx/operators       : 18.0.2
@ngrx/router-store    : 18.0.2
@ngrx/schematics      : 18.0.2
@ngrx/store           : 18.0.2
@ngrx/store-devtools  : 18.0.2
@nxext/capacitor      : 19.1.2
@nxext/ionic-angular  : 19.1.2
---------------------------------------
⚠️ Unable to construct project graph.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/eslint/plugin plugin.
    - libs/admin/root/feature-shell/eslint.config.js: baseConfig is not iterable
      TypeError: baseConfig is not iterable
          at Object.<anonymous> (/Users/meanstack02/nhhockeyplayer/libs/admin/root/feature-shell/eslint.config.js:5:6)
          at Module._compile (node:internal/modules/cjs/loader:1469:14)
          at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
          at Module.load (node:internal/modules/cjs/loader:1288:32)
          at Module._load (node:internal/modules/cjs/loader:1104:12)
          at cjsLoader (node:internal/modules/esm/translators:346:17)
          at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
          at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
          at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
          at async loadConfigFile (/Users/meanstack02/nhhockeyplayer/node_modules/eslint/lib/config/config-loader.js:201:21)

### Failure Logs

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/eslint/plugin plugin.
    - libs/admin/root/feature-shell/eslint.config.js: baseConfig is not iterable
      TypeError: baseConfig is not iterable
          at Object.<anonymous> (/Users/meanstack02/nhhockeyplayer/libs/admin/root/feature-shell/eslint.config.js:5:6)
          at Module._compile (node:internal/modules/cjs/loader:1469:14)
          at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
          at Module.load (node:internal/modules/cjs/loader:1288:32)
          at Module._load (node:internal/modules/cjs/loader:1104:12)
          at cjsLoader (node:internal/modules/esm/translators:346:17)
          at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
          at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
          at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
          at async loadConfigFile (/Users/meanstack02/nhhockeyplayer/node_modules/eslint/lib/config/config-loader.js:201:21)

### Package Manager Version

yarn 1.22.22

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

just an FYI

to avoid any mysteries with yarn or npm I freshly uninstalled npm, yarn and node.js
I did fresh install of all securing my cmd line environment

**Comment by nhhockeyplayer** [comment]
Run "nx show project feature-shell" to view details about this project.

```
meanstack02@admin nhhockeyplayer % nx show project feature-shell

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktrac
```es.

**Comment by nhhockeyplayer** [comment]
well it seems nothing is going to work until the eslint bug is fixed

```
const baseConfig = require('../../eslint.config.js');

module.exports = [
  ...baseConfig,
```

patch please

thank you

**Comment by nhhockeyplayer** [comment]
this issue should patch and fix it
https://github.com/nrwl/nx/issues/28388

closing this as duplicate
