### ISSUE TITLE
Error: The externalDependency 'eslint' for 'myapp ' could not be found

### ISSUE THREAD

**Issue by Joredjs** [nrwl/nx#28385]
### Current Behavior

When running myapp:lint after upgrading to Nx version 19 and 20.0.0, the following error occurs:

```bash
Error: The externalDependency 'eslint' for 'myapp:lint' could not be found
```

Previously, the lint task defined in nx.json under "targetDefaults" worked fine without requiring duplication in each project's project.json. Now, I need to copy the entire lint task configuration into every project's project.json to avoid the error, which was not necessary in version 18.

### Expected Behavior

The lint task should work without needing to manually duplicate the configuration in every project.json. According to the [Nx documentation](https://nx.dev/recipes/running-tasks/reduce-repetitive-configuration), defining a lint task under "targetDefaults" in nx.json should be enough, and it should be inherited by all projects without any issues.

### Steps to Reproduce

1. Create an Nx workspace with version 18 or earlier.
2. Define a lint task inside the "targetDefaults" section of nx.json like the following:

```json
// nx.json
{
  ...
  "targetDefaults": {
    "lint": {
      "dependsOn": ["^lint", "lint"],
      "cache": true,
      "executor": "@nx/eslint:lint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["{projectRoot}/src/**/*.ts"],
        "fix": true,
        "outputFile": "{workspaceRoot}/results/lint/{projectName}.html",
        "format": "html"
      }
    }
  }
}
```

3. Ensure that each project.json has an empty "lint" target, like:

```json
// project.json
{
  ...
  "targets": {
    "lint": {}
  }
}
```
4. Upgrade the Nx workspace to version 19 or 20.
5. Run the lint command for any project using nx <project>:lint.

### Nx Report

$ nx report

 NX   Report complete - copy this into the issue template

Node           : 21.7.2
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.5.0

nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/devkit         : 20.0.0
@nx/esbuild        : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/node           : 20.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin

### Failure Logs

Error: The externalDependency 'eslint' for 'server-local:lint' could not be found
    at NativeTaskHasherImpl.hashTasks (c:\JGARAY\Personal\nxms\node_modules\nx\src\hasher\native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (c:\JGARAY\Personal\nxms\node_modules\nx\src\hasher\task-hasher.js:41:46)
    at handleHashTasks (c:\JGARAY\Personal\nxms\node_modules\nx\src\daemon\server\handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleResult (c:\JGARAY\Personal\nxms\node_modules\nx\src\daemon\server\server.js:172:16)
    at async handleMessage (c:\JGARAY\Personal\nxms\node_modules\nx\src\daemon\server\server.js:110:9)
    at async c:\JGARAY\Personal\nxms\node_modules\nx\src\daemon\server\server.js:72:9 {
  code: 'GenericFailure'
}

Node.js v18.18.2

### Package Manager Version

npm 10.5.0

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

- I resolved the error by duplicating the lint task configuration from nx.json into each project's project.json, but this contradicts the [documentation](https://nx.dev/recipes/running-tasks/reduce-repetitive-configuration), which states that targetDefaults should eliminate the need for this repetition.
- I found similar issues on GitHub: [Issue #22871](https://github.com/nrwl/nx/issues/22871) and [Issue #22929](https://github.com/nrwl/nx/issues/22929), but they did not provide a solution for this problem.
- I'm using npm (not pnpm).

**Comment by gabriel-werzner** [comment]
Can confirm, for me, the error only appears on remotes not the regular nx app

**Comment by gabriel-werzner** [comment]
I have noticed the bug only appears on remotes created two+ subdirectories deep, for instance app/remote works app/remotes/remote does not

**Comment by evanl5** [comment]
Not sure if this is helpful for anyone else but I was also running into this problem and it tuns out I had a `.gitignore` file that contained `node_modules` in the directory _above_ my nx workspace. I removed the gitignore file and this error went away.

**Comment by DrewLandgraveCbsi** [comment]
So I ran across this today on PNPM 10.4.1 and NX 20.4.5

What fixed it for me was fixing the plugin definition in my nx.json. Noticed this here https://nx.dev/recipes/adopting-nx/adding-to-monorepo

And changed this and it started working immediately 

<img width="490" alt="Image" src="https://github.com/user-attachments/assets/eea02734-422d-4ecf-86d3-8b8dddafc47d" />

**Comment by baharudin-yusup** [comment]
This issue also happening in the Nx v20.7.2

**Comment by jessicamrbr** [comment]
> Not sure if this is helpful for anyone else but I was also running into this problem and it tuns out I had a `.gitignore` file that contained `node_modules` in the directory _above_ my nx workspace. I removed the gitignore file and this error went away.

The same thing happened to me.
The problem was related to `.gitignore`
https://nx.dev/reference/nxignore

**Comment by jessicamrbr** [comment]
https://github.com/nrwl/nx/issues/29678#issue-2797342320

**Comment by jessicamrbr** [comment]
https://github.com/nrwl/nx/issues/23287#issuecomment-2126237685

**Comment by jessicamrbr** [comment]
https://github.com/nrwl/nx/issues/28653#issuecomment-2453325755

**Comment by jessicamrbr** [comment]
https://github.com/nrwl/nx/issues/29782#issue-2816053426

**Comment by jessicamrbr** [comment]
https://github.com/nrwl/nx/issues/27088#issue-2427211587

**Comment by jessicamrbr** [comment]
https://github.com/nrwl/nx/issues/22929#issue-2255002656

**Comment by JarekToro** [comment]
To add to the list. 
## Error: The externalDependency 'typescript' for '@project/email:typecheck' could not be found

```log
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.798Z - Started listening on: /var/folders/zg/s0nh9xbx76g2kkgv1rf0bmb00000gn/T/13f4925fe0d661425c0f/d.sock
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.800Z - [WATCHER]: Subscribed to changes within: /Users/john_doe/Developer/project_name (native)
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.804Z - Established a connection. Number of open connections: 1
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.805Z - Established a connection. Number of open connections: 2
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.805Z - Closed a connection. Number of open connections: 1
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.806Z - [REQUEST]: Client Request for Project Graph Received
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.860Z - [WATCHER]: Processing file changes in outputs
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.912Z - Time taken for 'Load Nx Plugin: /Users/john_doe/Developer/project_name/node_modules/nx/src/plugins/package-json' 103.013417ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.921Z - Time taken for 'Load Nx Plugin: /Users/john_doe/Developer/project_name/node_modules/nx/src/plugins/project-json/build-nodes/project-json' 112.21475ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.921Z - Time taken for 'loadDefaultNxPlugins' 112.91604199999999ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.939Z - Time taken for 'Load Nx Plugin: @nx/jest/plugin' 131.42529100000002ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.939Z - Time taken for 'Load Nx Plugin: @nx/eslint/plugin' 132.483791ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.943Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.943Z - [REQUEST]: 
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.943Z - [REQUEST]: 
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.948Z - Time taken for 'loadSpecifiedNxPlugins' 136.30395900000002ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.949Z - Established a connection. Number of open connections: 2
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.949Z - Closed a connection. Number of open connections: 1
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.949Z - Established a connection. Number of open connections: 2
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.950Z - [REQUEST]: Responding to the client. handleGlob
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.950Z - Done responding to the client handleGlob
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.950Z - Handled GLOB. Handling time: 0. Response time: 0.
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.952Z - [REQUEST]: Responding to the client. handleHashMultiGlob
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.952Z - Done responding to the client handleHashMultiGlob
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.952Z - Handled HASH_GLOB. Handling time: 1. Response time: 0.
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.953Z - Established a connection. Number of open connections: 3
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.953Z - Closed a connection. Number of open connections: 2
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.953Z - Established a connection. Number of open connections: 3
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.955Z - [REQUEST]: Responding to the client. handleHashMultiGlob
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.955Z - Done responding to the client handleHashMultiGlob
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:27.955Z - Handled HASH_GLOB. Handling time: 1. Response time: 0.
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.072Z - Time taken for 'build-project-configs' 118.26595900000001ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.072Z - Time taken for '@nx/js/typescript:createDependencies' 0.726333000000011ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.074Z - [SYNC]: collect registered sync generators
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.074Z - [SYNC]: scheduling: ["@nx/js:typescript-sync"]
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.074Z - [REQUEST]: Responding to the client. project-graph
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.074Z - Time taken for 'total for creating and serializing project graph' 268.577625ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.075Z - Done responding to the client project-graph
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.075Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 268. Response time: 1.
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.076Z - [REQUEST]: Responding to the client. handleRunPreTasksExecution
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.076Z - Done responding to the client handleRunPreTasksExecution
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.076Z - Handled PRE_TASKS_EXECUTION. Handling time: 0. Response time: 0.
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.076Z - Time taken for 'preTasksExecution' 0.14066700000000765ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.079Z - [SYNC]: get sync generators changes on demand ["@nx/js:typescript-sync"]
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.079Z - [SYNC]: clearing scheduled run
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.079Z - [SYNC]: @nx/js:typescript-sync already scheduled or not cached, running it now
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.079Z - [SYNC]: running scheduled generator @nx/js:typescript-sync
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.188Z - Established a connection. Number of open connections: 4
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.188Z - Established a connection. Number of open connections: 5
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.189Z - Closed a connection. Number of open connections: 4
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.189Z - [REQUEST]: Client Request for Project Graph Received
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.189Z - [REQUEST]: Responding to the client. project-graph
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.189Z - Time taken for 'total for creating and serializing project graph' 0.18279199999994944ms
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.189Z - Done responding to the client project-graph
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.189Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 0. Response time: 0.
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.191Z - [SYNC]: @nx/js:typescript-sync changes: 
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.191Z - [REQUEST]: Responding to the client. handleGetSyncGeneratorChanges
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.191Z - Done responding to the client handleGetSyncGeneratorChanges
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.191Z - Handled GET_SYNC_GENERATOR_CHANGES. Handling time: 112. Response time: 0.
[NX v21.1.2 Daemon Server] - 2025-06-02T03:10:28.191Z - Time taken for 'run-sync-generator:@nx/js:typescript-sync' 112.19995799999998ms
/Users/john_doe/Developer/project_name/node_modules/nx/src/hasher/native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: The externalDependency 'typescript' for '@project/email:typecheck' could not be found
    at NativeTaskHasherImpl.hashTasks (/Users/john_doe/Developer/project_name/node_modules/nx/src/hasher/native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (/Users/john_doe/Developer/project_name/node_modules/nx/src/hasher/task-hasher.js:41:46)
    at handleHashTasks (/Users/john_doe/Developer/project_name/node_modules/nx/src/daemon/server/handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleResult (/Users/john_doe/Developer/project_name/node_modules/nx/src/daemon/server/server.js:186:16)
    at async handleMessage (/Users/john_doe/Developer/project_name/node_modules/nx/src/daemon/server/server.js:112:9)
    at async /Users/john_doe/Developer/project_name/node_modules/nx/src/daemon/server/server.js:74:9 {
  code: 'GenericFailure'
}

Node.js v23.11.0
```

**Comment by ThePlenkov** [comment]
Seeing the same error on Nx 21.6.3 (Node 24.8.0, npm 11.6.0, linux-x64 via WSL).

Workspace details:
- Project: `types` at `packages/types`
- Lint target defined with `nx:run-commands` and `externalDependencies: ["eslint"]`

Running `npx nx lint types --verbose` fails immediately with:
```
The externalDependency 'eslint' for 'types:lint' could not be found
```

`eslint` is listed in the root `package.json` devDependencies and is present in `node_modules/eslint`. We have tried reinstalling (`npm install`), `npx nx reset`, and restarting the daemon; the error persists.

If we remove the `externalDependencies` entry for `eslint` in the target definition the lint task runs, but that disables the cache guard.

Happy to supply additional diagnostics if that helps track this down.

**Comment by ThePlenkov** [comment]
this is issue is just brings me one more time the thought - that using nx becomes so much unreliable.. i had a wokring project and then just out of a sudden it stopped working... migration didn't help..

**Comment by ThePlenkov** [comment]
@jessicamrbr but what is the solution? we cannot remove `.gitignore`.. what did you exactly do? Thanks!

**Comment by ThePlenkov** [comment]
ok  = got it! just solved by removing package-lock.json from .gitignore.. that's not good.. because i do not want to push it intentionally..
