### ISSUE TITLE
NX   Cannot read properties of undefined (reading 'JsxEmit')

### ISSUE THREAD

**Issue by Lee-NG915** [nrwl/nx#28397]
when i use "pnpm nx g @nx/plugin:plugin" , show me error is
 NX   Cannot read properties of undefined (reading 'JsxEmit')

decription is:
```javascript
t getNeededCompilerOptionOverrides (/Users/xxxxx/node_modules/.pnpm/@nx+js@20.0.0_@babel+traverse@7.25.7_@swc-node+register@1.9.2_@swc+core@1.5.7_@swc+helpers@0._a6x5lqx7nme34afc66opk7jsx4/node_modules/@nx/js/src/utils/typescript/configuration.js:31:49)
   at createProjectTsConfigs (/Users/xxxxx/node_modules/.pnpm/@nx+js@20.0.0_@babel+traverse@7.25.7_@swc-node+register@1.9.2_@swc+core@1.5.7_@swc+helpers@0._a6x5lqx7nme34afc66opk7jsx4/node_modules/@nx/js/src/generators/library/library.js:727:88)
   at createFiles (/Users/xxxxx/node_modules/.pnpm/@nx+js@20.0.0_@babel+traverse@7.25.7_@swc-node+register@1.9.2_@swc+core@1.5.7_@swc+helpers@0._a6x5lqx7nme34afc66opk7jsx4/node_modules/@nx/js/src/generators/library/library.js:335:5)
   at libraryGeneratorInternal (/Users/xxxxx/node_modules/.pnpm/@nx+js@20.0.0_@babel+traverse@7.25.7_@swc-node+register@1.9.2_@swc+core@1.5.7_@swc+helpers@0._a6x5lqx7nme34afc66opk7jsx4/node_modules/@nx/js/src/generators/library/library.js:45:5)
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   at async libraryGenerator (/Users/xxxxx/node_modules/.pnpm/@nx+js@20.0.0_@babel+traverse@7.25.7_@swc-node+register@1.9.2_@swc+core@1.5.7_@swc+helpers@0._a6x5lqx7nme34afc66opk7jsx4/node_modules/@nx/js/src/generators/library/library.js:28:12)
   at async pluginGenerator (/Users/xxxxx/node_modules/.pnpm/@nx+plugin@20.0.0_@babel+traverse@7.25.7_@swc-node+register@1.9.2_@swc+core@1.5.7_@swc+helper_t4szf3aixucuxd3rl3czre4fba/node_modules/@nx/plugin/src/generators/plugin/plugin.js:58:16)
   at async /Users/xxxxx/node_modules/.pnpm/nx@19.7.0_@swc-node+register@1.9.2_@swc+core@1.5.7_@swc+helpers@0.5.12__@swc+types@0.1.13_typ_3xog5zj4xtngdry2gq4dbyn2fi/node_modules/nx/src/command-line/generate/generate.js:237:26
   at async handleErrors (/Users/xxxxx/node_modules/.pnpm/nx@19.7.0_@swc-node+register@1.9.2_@swc+core@1.5.7_@swc+helpers@0.5.12__@swc+types@0.1.13_typ_3xog5zj4xtngdry2gq4dbyn2fi/node_modules/nx/src/utils/params.js:22:24)
   at async Object.handler (/Users/xxxxx/node_modules/.pnpm/nx@19.7.0_@swc-node+register@1.9.2_@swc+core@1.5.7_@swc+helpers@0.5.12__@swc+types@0.1.13_typ_3xog5zj4xtngdry2gq4dbyn2fi/node_modules/nx/src/command-line/generate/command-object.js:14:22)
```

**Comment by Lee-NG915** [comment]
nx libray:
```
    "@nx/devkit": "19.7.0",
    "@nx/eslint": "19.7.0",
    "@nx/eslint-plugin": "19.7.0",
    "@nx/jest": "19.7.0",
    "@nx/js": "19.7.0",
    "@nx/next": "19.7.0",
    "@nx/playwright": "19.7.0",
    "@nx/plugin": "^20.0.0",
    "@nx/react": "19.7.0",
    "@nx/rollup": "19.7.0",
    "@nx/storybook": "19.7.0",
    "@nx/vite": "19.7.0",
    "@nx/web": "19.7.0",
    "@nx/workspace": "19.7.0",
```

**Comment by Lee-NG915** [comment]
i need help very need

**Comment by xiongemi** [comment]
do you have typescript package in your workspace? what version of typescript do you have?

**Comment by Lee-NG915** [comment]
> do you have typescript package in your workspace? what version of typescript do you have?

yeah! 
in package.json is
```
dependencies:{
    "@babel/preset-typescript": "^7.24.7",
}
devDependencies:{
    "@typescript-eslint/eslint-plugin": "7.18.0",
    "@typescript-eslint/parser": "7.18.0",
    "typescript": "~5.1.6",
}
```

in root ts.config.base.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "jsx": "react-jsx",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2021", "dom", "DOM.Iterable"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "esModuleInterop": true,
```

**Comment by DaveMBush** [comment]
I'm getting this same error running

pnpm nx g @nx/js:library --directory=packages/eslint --bundler=esbuild --importPath=@smarttools/eslint --linter=eslint --name=eslint --publishable=true --unitTestRunner=jest --setParserOptionsProject=true --useProjectJson=true

Using nx/js 20.0.6 in a new workspace

I put some console.logs in the source (configuration.js) and found that ts.server.protocol is undefined at line29

Hope this helps you track down the issue.

Thisis a brand new workspace so if you are looking for an easy repo, you can look here https://github.com/DaveMBush/smart-eslint

**Comment by DaveMBush** [comment]
OK, it seems the schematic that creates an empty NX workspace creates it with versions of packages that are too old to work with the generator.  Once I added the @nx/angular package which then told me my @swc-node/register, @swc/core, and typescript packages needed to be updated, the @nx/js:library schematic magically started working.

Hope this helps someone else who lands on this issue.

**Comment by JustinLivi** [comment]
Thanks @DaveMBush for the tip here, I had typescript@4 installed at my root and was encountering this error. Upgrading typescript to 5 resolved it for me.

Appears there are some changes in the way typescript handles the protocol interface between 4 and 5: https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes/f75a14141243749c3015d1ed4ba4da7e92531794

**Comment by smulhall1337** [comment]
I am also getting this error consistently when running `npx nx generate @nx/plugin:plugin versioning --directory=tools --verbose
`


```
Cannot read properties of undefined (reading 'JsxEmit')

TypeError: Cannot read properties of undefined (reading 'JsxEmit')
    at getNeededCompilerOptionOverrides (\AngularPages\node_modules\@nx\js\src\utils\typescript\configuration.js:31:49)
    at createProjectTsConfigs (\AngularPages\node_modules\@nx\js\src\generators\library\library.js:727:88)
    at createFiles (AngularPages\node_modules\@nx\js\src\generators\library\library.js:335:5)
 
``` 


My package.json
```javascript
"devDependencies": {
    "@angular-devkit/build-angular": "^16.2.13",
    "@angular-devkit/core": "~16.2.13",
    "@angular-devkit/schematics": "~16.2.13",
    "@angular/cli": "~16.2.13",
    "@angular/compiler-cli": "^16.2.12",
    "@nx/angular": "^20.0.7",
    "@nx/devkit": "^20.0.7",
    "@nx/plugin": "^20.0.7",
    "@nx/workspace": "^20.0.7",
    "@schematics/angular": "~16.2.13",
    "@types/file-saver": "^2.0.5",
    "@types/jasmine": "~4.0.0",
    "jasmine": "^4.3.0",
    "jasmine-core": "~4.1.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "nx": "^20.0.7",
    "patch-package": "^8.0.0",
    "postinstall-postinstall": "^2.1.0",
    "standard-version": "^9.5.0",
    "ts-node": "^10.9.2",
    "typescript": "5.1.6"
  }
``` 


My tsconfig.base.json
```
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "es2020",
    "lib": ["es2020", "dom"],
    "strict": false,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true
  },
  "exclude": ["node_modules", "tmp"]
}
``` 

My tsconfig.json
```
{
  "extends": "./tsconfig.base.json",
  "compileOnSave": true,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": false,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "allowSyntheticDefaultImports": true,
    "useDefineForClassFields": false
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}

```

**Comment by DaveMBush** [comment]
@smulhall1337 did you run

```
nx report
```

And update the dependencies to include the NX 20 packages that are missing from your package.json?

There will also be old nrwl packages, ignore those.  Also @nx/lint is deprecated so ignore that.

Once you've done that, your next error will be regarding caching.  You can set a local environment variable `NX_SKIP_NX_CACHE=true`  I put this in my `.env` file so I can build locally.  My CI pipeline still doesn't build but when I need that I can do the same thing there until this is fixed.

**Comment by smulhall1337** [comment]
@DaveMBush 

I noticed that I removed the nx/plugin while testing earlier. I re-added, nuked node_modules and package lock, and did a fresh npm install.

still received the same error.

Here is the output from `nx report`

```
NX   Report complete - copy this into the issue template

Node           : 20.11.1
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.2.4

nx             : 20.0.8
@nx/js         : 20.0.8
@nx/jest       : 20.0.8
@nx/eslint     : 20.0.8
@nx/workspace  : 20.0.8
@nx/angular    : 20.0.8
@nx/devkit     : 20.0.8
@nx/plugin     : 20.0.8
@nx/web        : 20.0.8
@nx/webpack    : 20.0.8
typescript     : 5.1.6
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome     : 0.13.0
@progress/kendo-angular-buttons      : 16.11.0
@progress/kendo-angular-dateinputs   : 16.11.0
@progress/kendo-angular-dialog       : 16.11.0
@progress/kendo-angular-dropdowns    : 16.11.0
@progress/kendo-angular-editor       : 16.11.0
@progress/kendo-angular-filter       : 16.11.0
@progress/kendo-angular-grid         : 16.11.0
@progress/kendo-angular-icons        : 16.11.0
@progress/kendo-angular-indicators   : 16.11.0
@progress/kendo-angular-inputs       : 16.11.0
@progress/kendo-angular-intl         : 16.11.0
@progress/kendo-angular-l10n         : 16.11.0
@progress/kendo-angular-label        : 16.11.0
@progress/kendo-angular-layout       : 16.11.0
@progress/kendo-angular-listview     : 16.11.0
@progress/kendo-angular-menu         : 16.11.0
@progress/kendo-angular-notification : 16.11.0
@progress/kendo-angular-pager        : 16.11.0
@progress/kendo-angular-popup        : 16.11.0
@progress/kendo-angular-progressbar  : 16.11.0
@progress/kendo-angular-toolbar      : 16.11.0
@progress/kendo-angular-tooltip      : 16.11.0
@progress/kendo-angular-treeview     : 16.11.0
@syncfusion/ej2-angular-pdfviewer    : 25.2.7
@syncfusion/ej2-angular-popups       : 25.2.7
@syncfusion/ej2-angular-spreadsheet  : 25.2.7

```

**Comment by DaveMBush** [comment]
@smulhall1337 maybe a newer version of typescript?  But that might be a problem with your angular stuck at 16 🤷

**Comment by smulhall1337** [comment]
@DaveMBush  this is about to become a whole thing for me, isnt it? T.T

**Comment by abarghoud** [comment]
I encountered the same issue, the solution was to update typescript from 4.9.2 to 5.5.4

**Comment by travis-hubbard-alk** [comment]
@abarghoud that solved it for me thanks!

**Comment by fcFn** [comment]
It happens with typescript `~5.2.2` as well. Upgrading to `latest` (as of this writing, 5.7.3) solved the problem for me.

**Comment by Coly010** [comment]
Thanks for reporting the issue! Migrating to TS >5.5 solves this issue.
