### ISSUE TITLE
Angular module federation broke

### ISSUE THREAD

**Issue by m-l-e-n** [nrwl/nx#28408]
### Current Behavior

Since @nx/angular@20.0.0 the names of dynamically federated modules are sanitized by replacing all "-" with "_". This leads to an error when starting the dev-server since the sanitized name is not a valid project name. In this example, the remote's name is "remotes-foo":

    Error: Cannot find project "remotes_foo". Check that the name is correct in module-federation.config.js
        at getModuleFederationConfig (/workspace/keba/node_modules/@nx/angular/src/utils/mf/utils.js:70:15)
        at withModuleFederation (/workspace/keba/node_modules/@nx/angular/src/utils/mf/with-module-federation.js:10:112)
        at Object.<anonymous> (/workspace/keba/apps/remotes/io-monitor/webpack.config.js:4:18)
        at Module._compile (node:internal/modules/cjs/loader:1469:14)
        at Module._compile (/workspace/keba/node_modules/pirates/lib/index.js:117:24)
        at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
        at Object.newLoader (/workspace/keba/node_modules/pirates/lib/index.js:121:7)
        at Module.load (node:internal/modules/cjs/loader:1288:32)
        at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
        at Module.require (node:internal/modules/cjs/loader:1311:19)
    
The bug was introduced with this commit: https://github.com/nrwl/nx/commit/95d26c6bf41c299df92b8e36fe9c01431528a475

### Expected Behavior

I can use remote projects with dashes ("-") in their name.

### Steps to Reproduce

1.

### Nx Report

Node           : 20.18.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.8.2

nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/playwright     : 20.0.0
@nx/storybook      : 20.0.0
@nx/vite           : 20.0.0
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.5.4
---------------------------------------
Community plugins:
@storybook/angular : 8.3.5
ng2-charts         : 6.0.1

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by its-ratikant** [comment]
I am also getting this issue! Not able to run host application when there is one or more than remote application.

**Comment by Coly010** [comment]
Will be fixed by: https://github.com/nrwl/nx/pull/28401

**Comment by m-l-e-n** [comment]
@Coly010 & @jaysoo 
THANK YOU VERY MUCH for the quick fix! Our project now works without any modifications to the remotes. 👍
