### ISSUE TITLE
Nx lint is failing on a newly created Angular workspace

### ISSUE THREAD

**Issue by cvandradg** [nrwl/nx#28407]
### Current Behavior

Can't run npx nx lint on a newly created nx Angular workspace

$ npx nx lint testapp

> nx run testapp:lint

Linting "testapp"...
 NX   Cannot read properties of undefined (reading 'at')
Occurred while linting C:\Users\Clau\Desktop\active-work\testworkspace\apps\testapp\src\app\app.component.html:1
Rule: "@typescript-eslint/ban-ts-comment"
Pass --verbose to see the stacktrace.

### Expected Behavior

Expected to run successfully on a newly created nx Angular workspace

$ npx nx lint testapp

> nx run testapp:lint

Linting "testapp"...
✔ All files pass linting

### GitHub Repo

https://github.com/cvandradg/testnxissue

### Steps to Reproduce

1. Create a new Nx monorepo angular workspace
2. run npx nx lint <name of app>

### Nx Report

npx nx lint testapp --verbose

> nx run testapp:lint

Linting "testapp"...
 NX   Cannot read properties of undefined (reading 'at')
Occurred while linting C:\Users\Clau\Desktop\active-work\testnxissue\apps\testapp\src\app\app.component.html:1
Rule: "@typescript-eslint/ban-ts-comment"
TypeError: Cannot read properties of undefined (reading 'at')
Occurred while linting C:\Users\Clau\Desktop\active-work\testnxissue\apps\testapp\src\app\app.component.html:1
Rule: "@typescript-eslint/ban-ts-comment"
    at Program (C:\Users\Clau\Desktop\active-work\testnxissue\node_modules\@typescript-eslint\eslint-plugin\dist\rules\ban-ts-comment.js:118:50)
    at ruleErrorHandler (C:\Users\Clau\Desktop\active-work\testnxissue\node_modules\eslint\lib\linter\linter.js:1084:48)
    at C:\Users\Clau\Desktop\active-work\testnxissue\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\Clau\Desktop\active-work\testnxissue\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\Clau\Desktop\active-work\testnxissue\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (C:\Users\Clau\Desktop\active-work\testnxissue\node_modules\eslint\lib\linter\node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (C:\Users\Clau\Desktop\active-work\testnxissue\node_modules\eslint\lib\linter\node-event-generator.js:337:14)
    at runRules (C:\Users\Clau\Desktop\active-work\testnxissue\node_modules\eslint\lib\linter\linter.js:1128:40)
    at #flatVerifyWithoutProcessors (C:\Users\Clau\Desktop\active-work\testnxissue\node_modules\eslint\lib\linter\linter.js:1914:31)

 NX   Running target lint for project testapp failed

Failed tasks:

- testapp:lint

Hint: run the command with --verbose for more details.

### Package Manager Version

npm 10.9.0

### Operating System

- [ ] macOS
- [x] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

![Image](https://github.com/user-attachments/assets/36e34e12-5987-4930-bafb-01b883499635)

possible solution:

node_modules\@typescript-eslint\eslint-plugin\dist\rules\ban-ts-comment.js
line 118: const firstStatement = node.body?.at(0);

that might do the trick, not sure if it's a viable solution.

**Comment by leosvelperez** [comment]
This was fixed by https://github.com/nrwl/nx/pull/28381 and the fix will be released soon.
