### ISSUE TITLE
Nest Library generation fails in v20.0.0

### ISSUE THREAD

**Issue by anthony-b-dev** [nrwl/nx#28404]
### Current Behavior

nx g @nx/nest:lib fgb-tenant

NX  Generating @nx/nest:library

 NX   Could not find root flat config file

### Expected Behavior

Library is generated

### Steps to Reproduce

1. Run the nest library generation command

### Nx Report

Node           : 20.11.1
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 9.6.6

nx (global)        : 20.0.0
nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 20.0.0
@nx/esbuild        : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/express        : 20.0.0
@nx/nest           : 20.0.0
@nx/node           : 20.0.0
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.5.4
---------------------------------------
Community plugins:
@ngrx/component-store : 18.1.0
@ngrx/effects         : 18.1.0
@ngrx/entity          : 18.1.0
@ngrx/eslint-plugin   : 18.1.0
@ngrx/operators       : 18.1.0
@ngrx/router-store    : 18.1.0
@ngrx/schematics      : 18.1.0
@ngrx/store           : 18.1.0
@ngrx/store-devtools  : 18.1.0

### Failure Logs

NX  Generating @nx/nest:library

 NX   Could not find root flat config file

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

I have tried it with the directory command, `nx g lib`, and the fully expanded command. Nothing works.

**Comment by abdul-alim** [comment]
I am getting the below error while setting up nest project.

`NX   The "@nx/nest" plugin doesn't yet support the existing TypeScript setup`

**Comment by gperdomor** [comment]
This is related to https://github.com/nrwl/nx/issues/28322

**Comment by ndcunningham** [comment]
Hey, thanks for reporting an issue.

To paraphrase from the [above](https://github.com/nrwl/nx/issues/28322)
> As mentioned in [Nx v20 blog post announcement](https://nx.dev/blog/announcing-nx-20#typescript-project-references-for-monorepos), if you need to use other plugins while they don't support the new TS setup, please create an empty workspace with the apps preset: npx -y create-nx-workspace@latest --preset=apps

**Comment by JohnnyDevNull** [comment]
Same for Angular here:

![Image](https://github.com/user-attachments/assets/f20fbb20-bfe2-4d62-a833-0d787d545e8a)

**Comment by bdahl1** [comment]
I've run into the same issue as Johnny. It seems like this only impacts the _generator_, so you could build the Library by hand and things would still work, correct? Is there a good example of that floating around somewhere using NX20 and Angular? At least as a workaround until the generator gets fixed?

**Comment by coreConvention** [comment]
> ![Image](https://github.com/user-attachments/assets/f20fbb20-bfe2-4d62-a833-0d787d545e8a)

I am also seeing this issue currently. I have been unable find a way around it thus far.

**Comment by rajeev-john** [comment]
I also faced the same issue of @coreConvention. I got a work around for this by creating a file named eslint.config.js in the working directory. But still not sure if this is the right solution. Looking for the right fix for this

"@nx/angular": "20.1.0",
"@nx/cypress": "20.1.0",
"@nx/eslint": "20.1.0",
"@nx/eslint-plugin": "20.1.0",
"@nx/jest": "20.1.0",
"@nx/js": "20.1.0",
"@nx/workspace": "20.1.0",
"eslint": "9.14.0",
"nx": "20.1.0"

**Comment by kasir-barati** [comment]
Same here, `nx g @nx/js:lib libs/shared --bundler=esbuild --linter=eslint --unitTestRunner=jest --verbose` is upset about something since it throws this error message: 

```shell
Error: Could not find root flat config file
    at getRootESLintFlatConfigFilename (/home/kasir/projects/nestjs-materials/typeorm/node_modules/.pnpm/@nx+eslint@20.2.1_@babel+traverse@7.26.4_@swc-node+register@1.10.9_@swc+core@1.10.1_@swc+help_p7jqooqyk4oi6p3v7733sbzc7e/node_modules/@nx/eslint/src/utils/flat-config.js:18:11)
    at lintConfigHasOverride (/home/kasir/projects/nestjs-materials/typeorm/node_modules/.pnpm/@nx+eslint@20.2.1_@babel+traverse@7.26.4_@swc-node+register@1.10.9_@swc+core@1.10.1_@swc+help_p7jqooqyk4oi6p3v7733sbzc7e/node_modules/@nx/eslint/src/generators/utils/eslint-file.js:179:164)
    at addLint (/home/kasir/projects/nestjs-materials/typeorm/node_modules/.pnpm/@nx+js@20.2.1_@babel+traverse@7.26.4_@swc-node+register@1.10.9_@swc+core@1.10.1_@swc+helpers@_hy7mt26ijjtzogm4skpywoo75e/node_modules/@nx/js/src/generators/library/library.js:292:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async libraryGeneratorInternal (/home/kasir/projects/nestjs-materials/typeorm/node_modules/.pnpm/@nx+js@20.2.1_@babel+traverse@7.26.4_@swc-node+register@1.10.9_@swc+core@1.10.1_@swc+helpers@_hy7mt26ijjtzogm4skpywoo75e/node_modules/@nx/js/src/generators/library/library.js:81:30)
    at async /home/kasir/projects/nestjs-materials/typeorm/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.1_@swc+helpers@0.5.15__@swc+types@0.1.17_t_w6pixw4aadyn6222jr5o5yzwvy/node_modules/nx/src/command-line/generate/generate.js:240:26
    at async handleErrors (/home/kasir/projects/nestjs-materials/typeorm/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.1_@swc+helpers@0.5.15__@swc+types@0.1.17_t_w6pixw4aadyn6222jr5o5yzwvy/node_modules/nx/src/utils/handle-errors.js:8:24)
    at async Object.handler (/home/kasir/projects/nestjs-materials/typeorm/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.1_@swc+helpers@0.5.15__@swc+types@0.1.17_t_w6pixw4aadyn6222jr5o5yzwvy/node_modules/nx/src/command-line/generate/command-object.js:13:22)
```

I am using Nx + PNPM + NestJS. I wanted to create a new library but instead I created a new bug. BTW I am not sure if this is somehow also related to this issue I opened here: https://github.com/nrwl/nx/issues/28991

**Comment by bdahl1** [comment]
> # Workaround
> I renamed my root `.eslintrc.json` to `eslint.config.js`

That worked for me too... Very strange

**Comment by slyk** [comment]
> > # Workaround
> > I renamed my root `.eslintrc.json` to `eslint.config.js`
> 
> That worked for me too... Very strange

We can't just rename json to js. But this helped me: https://nx.dev/recipes/tips-n-tricks/flat-config
``` nx g @nx/eslint:convert-to-flat-config```

It does the "renaming :)

**Comment by kasir-barati** [comment]
@bdahl1 It is happening because some code in Nx expects to find `eslint.config.js` or `eslint.config.cjs`:

https://github.com/nrwl/nx/blob/0d1c96085e7b10fde47e3b12dd3f2b50b8f667fe/packages/eslint/src/utils/flat-config.ts#L5-L17

**Comment by ndcunningham** [comment]
Yes, if your root eslint config is in a non-JS format you should follow: https://nx.dev/recipes/tips-n-tricks/flat-config first.
Additionally, it now also supports `.mjs` by default.

Can you try with the latest version?
