### ISSUE TITLE
Migration to 20 -  Cannot read properties of undefined (reading 'cli')

### ISSUE THREAD

**Issue by mirogajdos** [nrwl/nx#28410]
### Current Behavior

I'm getting migration errors while trying to upgrade to 20 from 19.8.4. It says that workspace is not up to date but I cannot figure out where is the error and how to get workspace up to date.

### Expected Behavior

Migration works

### Steps to Reproduce

1. Run `npx nx migrate latest`
2. Run `npm install`
3. Run `npx nx migrate --run-migrations`

### Nx Report

Node           : 22.9.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.8.3

nx                 : 19.8.4
@nx/js             : 19.8.4
@nx/jest           : 19.8.4
@nx/linter         : 19.8.4
@nx/eslint         : 19.8.4
@nx/workspace      : 19.8.4
@nx/cypress        : 19.8.4
@nx/devkit         : 19.8.4
@nx/eslint-plugin  : 19.8.4
@nx/nest           : 19.8.4
@nx/node           : 19.8.4
@nx/plugin         : 19.8.4
@nx/react          : 19.8.4
@nrwl/tao          : 19.8.4
@nx/vite           : 19.8.4
@nx/web            : 19.8.4
@nx/webpack        : 19.8.4
typescript         : 5.6.3
---------------------------------------
Local workspace plugins:
         @home/workspace-plugin

### Failure Logs

NX   Running migrations from 'migrations.json'

Running the following migrations:
- nx: move-use-daemon-process (Migration for v20.0.0-beta.7)
---------------------------------------------------------

Running migration nx: move-use-daemon-process

 NX   Failed to run move-use-daemon-process from nx. This workspace is NOT up to date!

 NX   Cannot read properties of undefined (reading 'cli')

TypeError: Cannot read properties of undefined (reading 'cli')
    at isAngularMigration (/home/miro/code/home/apps/node_modules/nx/src/command-line/migrate/migrate.js:1087:15)
    at executeMigrations (/home/miro/code/home/apps/node_modules/nx/src/command-line/migrate/migrate.js:920:18)
    at runMigrations (/home/miro/code/home/apps/node_modules/nx/src/command-line/migrate/migrate.js:1009:43)
    at /home/miro/code/home/apps/node_modules/nx/src/command-line/migrate/migrate.js:1050:19
    at async handleErrors (/home/miro/code/home/apps/node_modules/nx/src/utils/handle-errors.js:9:24)

### Operating System

- [ ] macOS
- [x] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

My nx.json:
```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "workspaceLayout": {
    "appsDir": "apps",
    "libsDir": "libs"
  },
  "generators": {
    "@nx/react": {
      "application": {
        "style": "@emotion/styled",
        "linter": "eslint",
        "bundler": "vite",
        "compiler": "swc",
        "unitTestRunner": "none"
      },
      "component": {
        "style": "@emotion/styled"
      },
      "library": {
        "style": "@emotion/styled",
        "linter": "eslint",
        "unitTestRunner": "none"
      }
    }
  },
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"],
      "cache": true
    },
    "component-test": {
      "inputs": ["default", "^production"],
      "cache": true
    },
    "e2e": {
      "inputs": ["default", "^production"],
      "cache": true
    },
    "@nx/jest:jest": {
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"],
      "cache": true,
      "options": {
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    },
    "@nx/eslint:lint": {
      "inputs": ["default", "{workspaceRoot}/.eslintrc.json"],
      "cache": true
    }
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "sharedGlobals": ["{workspaceRoot}/.gitlab-ci.yml"],
    "production": [
      "default",
      "!{projectRoot}/cypress/**/*",
      "!{projectRoot}/**/*.cy.[jt]s?(x)",
      "!{projectRoot}/cypress.config.[jt]s",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/src/test-setup.[jt]s"
    ]
  },
  "defaultBase": "main"
}

```

**Comment by hannovisagie** [comment]
I also have this issue. Thought I was loosing my mind.

**Comment by jaysoo** [comment]
@mirogajdos @jahusa02 @hannovisagie Did `npm install` succeed? It looks like the Nx packages were not updated to v20, so the migration entry is missing in `node_modules/nx/migrations.json`.

You can try `npm install --force` as well, as some ESLint plugins did not update their versions so there could be peer dependencies errors/warnings.

**Comment by mirogajdos** [comment]
Going to v19.8.6 and trying again to v20 solved the issue for me. I believe my installation also passed.

**Comment by renatoaraujoc** [comment]
I also can't update to latest version.

Coming from `nx v20.0.0` to `nx v20.1.4`: 

![Image](https://github.com/user-attachments/assets/937f9a15-a216-4e9f-9fef-02d957210d96)

**Comment by St1c** [comment]
Same issue here. Updating Angular on NX is pretty annoying for me for every single major version for the past 5 angular versions. I'm starting to think about ditching NX altogether...

**Comment by thdk** [comment]
> Going to v19.8.6 and trying again to v20 solved the issue for me.

Thanks, that worked indeed! 🚀 

```sh
npx nx migrate 19.8.6
npm install
npx nx migrate --run-migrations
npx nx migrate latest
npm install
npm nx migrate --run-migrations
```


> removed package-lock.json and clean installed.. 

You probably know but you **should never remove your lock file**. If ever needed revert any changes to your lock file and run `npm install`.
