### ISSUE TITLE
@nrwl/schematics@0.7.4 breaks calculation of relative paths in nx-enforce-module-boundaries on windows

### ISSUE THREAD

**Issue by yuriyp** [nrwl/nx#285]
nx-enforce-module-boundaries produces error: "...library imports must start..."
for cases like "import { AppComponent } from './app.component';" in app.component.spec.ts
Both files are located in the same directory.
The problem is not reproduced in @nrwl/schematics@0.7.3
OS: Windows

**Comment by skydever** [comment]
I already created a [PR](https://github.com/nrwl/nx/pull/283) for that, maybe you have some thoughts on it? not sure why the CI failed...

**Comment by offwork** [comment]
Error: spawnSync /bin/sh ENOENT
    at _errnoException (util.js:1024:11)
    at spawnSync (child_process.js:579:20)
    at Object.execSync (child_process.js:635:13)
    at Object.<anonymous> (/Users/keremozdemir/.npm-global/lib/node_modules/@nrwl/schematics/bin/create-nx-workspace.js:77:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)

**Comment by ndcunningham** [comment]
Same issue as OP

**Comment by skydever** [comment]
created a new pr with the latest changes from master (that are great by the way, using the official angular cli now) - ci is passing ...

**Comment by chris5287** [comment]
@skydever thanks for the patch, be great for this to be in the next release (pretty please)
