### ISSUE TITLE
Nx does not run test tasks in jest

### ISSUE THREAD

**Issue by arthurgubaidullin** [nrwl/nx#28511]
### Current Behavior

Nx does not run test tasks

### Expected Behavior

Nx must run test tasks

### GitHub Repo

https://github.com/arthurgubaidullin/fcm-reg-token-management/tree/bug-repro/20-0-2-no-tests-run

### Steps to Reproduce

1. Clone the repro branch
1. Run command: `npx nx run-many -t test --verbose`

### Nx Report

```shell
Node           : 20.11.0
OS             : linux-arm64
Native Target  : aarch64-linux
npm            : 10.2.4

nx                 : 20.0.2
@nx/js             : 20.0.2
@nx/jest           : 20.0.2
@nx/eslint         : 20.0.2
@nx/workspace      : 20.0.2
@nx/devkit         : 20.0.2
@nx/eslint-plugin  : 20.0.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
$ npx nx run-many -t test --verbose

 NX   Running target test for project sandbox:

- sandbox

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run sandbox:test

> jest

Error: Jest: Failed to parse the TypeScript config file /workspaces/fcm-reg-token-management/packages/sandbox/jest.config.ts
  TSError: ⨯ Unable to compile TypeScript:
error TS5110: Option 'module' must be set to 'NodeNext' when option 'moduleResolution' is set to 'NodeNext'.

    at readConfigFileAndSetRootDir (/workspaces/fcm-reg-token-management/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13)
    at async readInitialOptions (/workspaces/fcm-reg-token-management/node_modules/jest-config/build/index.js:403:13)
    at async readConfig (/workspaces/fcm-reg-token-management/node_modules/jest-config/build/index.js:147:48)
    at async readConfigs (/workspaces/fcm-reg-token-management/node_modules/jest-config/build/index.js:424:26)
    at async runCLI (/workspaces/fcm-reg-token-management/node_modules/@jest/core/build/cli/index.js:151:59)
    at async Object.run (/workspaces/fcm-reg-token-management/node_modules/jest-cli/build/run.js:130:37)

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target test for project sandbox failed

Failed tasks:

- sandbox:test
```

### Package Manager Version

10.2.4

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment]
This is a jest error which is related to your tsconfig module. The error comes from https://github.com/jestjs/jest/blob/main/packages/jest-config/src/readConfigFileAndSetRootDir.ts#L145-L153

For Jest < 30, there is no way to load `jest.config.ts` file if the `tsconfig.json`/`tsconfig.base.json` sets moduleResolution to `bundler` or `nodenext`.

When you added @nx/jest you should had a warning in your console stating this as well. You need to set your `moduleResolution` to `node` or `node10`
