### ISSUE TITLE
Nx watch throws Daemon is not running when daemon is ok on windows

### ISSUE THREAD

**Issue by dennyak47** [nrwl/nx#28513]
### Current Behavior

Watch not ok when daemon is started

### Expected Behavior

Watch should be ok when daemon is already started

### Steps to Reproduce
```

    "buggy:watch": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "nx daemon && nx watch --projects=my-app --includeDependentProjects -- nx run-many -t build -p \\$NX_PROJECT_NAME --exclude=my-app",
          "rspack serve -c ./apps/my-app/rspack.config.ts -m development"
        ],
        "parallel": true
      },
      "dependsOn": [
        "daemon:start",
        "^build"
      ]
    },
```

```
 Executing task: pnpm exec nx run my-app:buggy:watch 


 NX   Running target buggy:watch for project my-app and 1 task it depends on:

—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run my-app:"daemon:start"

> nx daemon --stop


 NX   Daemon Server - Stopped

> nx daemon --start


 NX   Daemon Server - Started in a background process...

Logs from the Daemon process (ID: 20324) can be found here: C:\Users\320246111\Documents\org3\.nx\workspace-data\d\daemon.log



> nx run my-app:"buggy:watch"

> nx daemon && nx watch --projects=my-app --includeDependentProjects -- nx run-many -t build -p \$NX_PROJECT_NAME --exclude=my-app

> rspack serve -c ./apps/my-app/rspack.config.ts -m development

Nx Daemon is currently running:
  - Logs: C:\Users\me\Documents\org3\.nx\workspace-data\d\daemon.log
  - Process ID: 20324

 NX   Daemon is not running. The watch command is not supported without the Nx Daemon.
```
### Nx Report
```
Node           : 20.10.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 9.6.0

nx             : 20.0.2
@nx/js         : 20.0.2
@nx/workspace  : 20.0.2
@nx/devkit     : 20.0.2
typescript     : 5.5.4
```

### Package Manager Version

20.0.2

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by Bullfrog1234** [comment]
I get similar on new build repo with NX on node applications I get the following:

Executing task: npx nx run be-rest:serve 


 ```
NX   Running target serve for project be-rest and 1 task it depends on:

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run be-rest:build  [local cache]

> webpack-cli build --node-env=production

chunk (runtime: main) main.js (main) 118 KiB [entry] [rendered]
webpack compiled successfully (4c6bc9d3f196cfa5)

> nx run be-rest:serve:development

NX Daemon is not running. Node process will not restart automatically after file changes.
The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
> nx run be-rest:build  [local cache]
> webpack-cli build --node-env=production
chunk (runtime: main) main.js (main) 118 KiB [entry] [rendered]
webpack compiled successfully (4c6bc9d3f196cfa5)
....
```

I am using the following dependencies:
```
{
  "devDependencies": {
    "@nx/devkit": "20.1.4",
    "@nx/esbuild": "20.1.4",
    "@nx/eslint": "20.1.4",
    "@nx/eslint-plugin": "20.1.4",
    "@nx/express": "20.1.4",
    "@nx/js": "20.1.4",
    "@nx/node": "20.1.4",
    "@nx/react": "20.1.4",
    "@nx/vite": "20.1.4",
    "@nx/web": "20.1.4",
    "@nx/webpack": "20.1.4",
    "@nx/workspace": "20.1.4"
  }
}
```
Plus I am on windows using VSCode and Nx Console v18.33.0

I am sure these two issues are linked.

**Comment by heyakyra** [comment]
Is this the cause of https://github.com/lerna/lerna/issues/4054#issuecomment-3286545074 ?

Edit: Ah, I see that this is because [`NX_DAEMON=true`](https://github.com/nrwl/nx/blob/master/packages/nx/src/daemon/client/client.ts#L152) [is ignored](https://github.com/nrwl/nx/blob/master/packages/nx/src/daemon/client/client.ts#L174C9) by [`nxJsonIsNotPresent()`](https://github.com/nrwl/nx/blob/master/packages/nx/src/config/nx-json.ts#L853-L856) which was [fixed](https://github.com/nrwl/nx/pull/27585) at least [for docker](https://github.com/nrwl/nx/issues/14126) (and podman?) by @MaxKless with input from @StalkAltan & @FrozenPandaz, but it still requires a config file.

If having a basic default config baked in doesn't make sense, it would be nice if the [daemon](https://nx.dev/docs/concepts/nx-daemon) & [environment variable](https://nx.dev/docs/reference/environment-variables#nx-environment-variables) docs (which for the record don't show the default values) actually specified that `NX_DAEMON` is only meant for overriding the CI environment or the setting in the config file but **will not** override a _lack_ of config file nor the existence of [`.nx/workspace-data/d/disabled`](https://github.com/nrwl/nx/blob/master/packages/nx/src/daemon/tmp-dir.ts#L40-L47) (which also isn't documented how that is set or unset). The [output ,`Daemon is not running. The watch command is not supported without the Nx Daemon.`](https://github.com/nrwl/nx/blob/master/packages/nx/src/command-line/watch/watch.ts#L159-L165) is also confusing since having the daemon running manually with `nx daemon --start` is similarly ineffective.

**Comment by socnadmin** [comment]
hi !

I experience same issue with WSL.
Can anyone confirm it's also related ?

Interestingly, this problem only occurs with my nestjs app, but not with my react app.

Does anyone has a workaround for this issue ? 
It's a real pain to restart manually my nestjs back everytime I work on it.

**Comment by psvmk** [comment]
i have no idea what caused this for me since today morning, similar on macos too. 
I manage node versions via Mise & my sh is Fish.

```
npx nx report

 NX   Report complete - copy this into the issue template

Node           : 24.9.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 11.6.0

nx                     : 21.6.3
@nx/js                 : 21.6.3
@nx/jest               : 21.6.3
@nx/eslint             : 21.6.3
@nx/workspace          : 21.6.3
@nx/devkit             : 21.6.3
@nx/esbuild            : 21.6.3
@nx/eslint-plugin      : 21.6.3
@nx/express            : 21.6.4
@nx/module-federation  : 21.6.4
@nx/node               : 21.6.3
@nx/playwright         : 21.6.3
@nx/react              : 21.6.4
@nx/rollup             : 21.6.4
@nx/vite               : 21.6.3
@nx/web                : 21.6.3
@nx/docker             : 21.6.3
typescript             : 5.9.3
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/playwright/plugin
@nx/eslint/plugin
@nx/jest/plugin
---------------------------------------
Cache Usage: 925.17 KB / 46.04 GB
---------------------------------------
The following packages should match the installed version of nx
  - @nx/express@21.6.4
  - @nx/module-federation@21.6.4
  - @nx/react@21.6.4
  - @nx/rollup@21.6.4

To fix this, run `nx migrate nx@21.6.4`
``` 
there was this file .nx/workspace-data/d/disabled which had a value of true. deleting it seemed to make it work.

**Comment by adamghowiba** [comment]
> hi !
> 
> I experience same issue with WSL. Can anyone confirm it's also related ?
> 
> Interestingly, this problem only occurs with my nestjs app, but not with my react app.
> 
> Does anyone has a workaround for this issue ? It's a real pain to restart manually my nestjs back everytime I work on it.

Having the same issue with NestJS if feels the newest version of NX `22.6.4` is a lot more flakey, espcially with nestjs

**Comment by R1D3R175** [comment]
Having the same issue on Linux in my NestJS container (docker compose). I also have an Angular container with the same environment variables as the Nest container, `NX_DAEMON` set to `true` and `NX_DAEMON_SOCKET_DIR` set to a shared directory.

The Angular container works just fine however the NestJS container complains about the NX Daemon not running.

Interestingly, if I run `npx nx daemon` inside the NestJS container it correctly shows that the daemon is running.
```
// Here I start the daemon
$ npm run nx-daemon:start

> @my-project/source@0.0.0 nx-daemon:start
> NX_DAEMON_SOCKET_DIR=$(pwd)/docker/nx-daemon npx nx daemon --start


 NX   Daemon Server - Started in a background process...

Logs from the Daemon process (ID: 2803551) can be found here: /path/to/.nx/workspace-data/d/daemon.log

// Here I start my containers (script of "docker compose up")
$ npm run start:dev
nest-dev     | NX Daemon is not running. Node process will not restart automatically after file changes.

// I grab the container ID of nest-dev
$ docker ps
CONTAINER ID NAMES
cdd402002d61 nest-dev

// I check if it is running and it corresponds
$ docker exec -it cd /bin/sh
/app # npx nx daemon
Nx Daemon is currently running:
  - Logs: /app/.nx/workspace-data/d/daemon.log
  - Process ID: 2803551
```

```
npx nx report

 NX   Report complete - copy this into the issue template

Node           : 22.21.1
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 11.6.2

nx                     : 22.1.0
@nx/js                 : 22.1.0
@nx/jest               : 22.1.0
@nx/eslint             : 22.1.0
@nx/workspace          : 22.1.0
@nx/angular            : 22.1.0
@nx/devkit             : 22.1.0
@nx/eslint-plugin      : 22.1.0
@nx/module-federation  : 22.1.0
@nx/nest               : 22.1.0
@nx/node               : 22.1.0
@nx/playwright         : 22.1.0
@nx/rspack             : 22.1.0
@nx/web                : 22.1.0
@nx/webpack            : 22.1.0
@nx/docker             : 22.1.0
typescript             : 5.9.3
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/playwright/plugin
---------------------------------------
Community plugins:
angular-eslint : 20.6.0
---------------------------------------
Cache Usage: 1.56 MB / 85.85 GB
```

After trying to delete `.nx/workspace-data/d/disabled` as suggested by @psvmk I got the following logs
```
nest-dev     | > nx run api:build:development  [local cache]
nest-dev     | > webpack-cli build --node-env=development
nest-dev     | chunk (runtime: main) main.js (main) 2.78 KiB [entry] [rendered]
nest-dev     | webpack compiled successfully (b0e90c227fabccf6)
nest-dev     |  NX   Successfully ran target build for project api
nest-dev     | Nx read the output from the cache instead of running the command for 1 out of 1 tasks.
nest-dev     | Watch error: Daemon closed the connection
angular-dev  |  NX   Daemon process terminated and closed the connection
nest-dev     | 
nest-dev     | 
nest-dev     | 
nest-dev     |  NX   Successfully ran target serve for project api and 1 task it depends on
nest-dev     | 
nest-dev     | Nx read the output from the cache instead of running the command for 1 out of 2 tasks.
nest-dev     | 
nest-dev     |  NX   Nx Cloud Error
nest-dev     | Error: write EPIPE
nest-dev     | Messages from the log:
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.384Z - Responding to RECORD_OUTPUTS_HASH message
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.384Z - [REQUEST]: Responding to the client. recordOutputsHash
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.384Z - Done responding to the client recordOutputsHash
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.384Z - Handled json message RECORD_OUTPUTS_HASH. Handling time: 3. Response time: 0.
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.390Z - Received raw message of length 220
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.390Z - Received json message of type RECORD_TASK_RUNS
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.391Z - [REQUEST]: Responding to the client with an error. [RECORD_TASK_RUNS] DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 }, Some("FOREIGN KEY constraint failed"))
nest-dev     | Error: DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 }, Some("FOREIGN KEY constraint failed"))
nest-dev     |     at TaskHistory.recordTaskRuns (/a/path/to/node_modules/nx/src/utils/task-history.js:32:37)
nest-dev     |     at handleRecordTaskRuns (/a/path/to/node_modules/nx/src/daemon/server/handle-task-history.js:9:23)
nest-dev     |     at /a/path/to/node_modules/nx/src/daemon/server/server.js:177:122
nest-dev     |     at handleResult (/a/path/to/node_modules/nx/src/daemon/server/server.js:214:20)
nest-dev     |     at handleMessage (/a/path/to/node_modules/nx/src/daemon/server/server.js:177:15)
nest-dev     |     at /a/path/to/node_modules/nx/src/daemon/server/server.js:79:15
nest-dev     |     at Socket.<anonymous> (/a/path/to/node_modules/nx/src/utils/consume-messages-from-socket.js:23:21)
nest-dev     |     at Socket.emit (node:events:519:28)
nest-dev     |     at addChunk (node:internal/streams/readable:561:12)
nest-dev     |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.392Z - Done responding to the client null
nest-dev     | More information: /app/.nx/workspace-data/d/daemon.log
nest-dev     |  NX   DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 }, Some("FOREIGN KEY constraint failed"))
nest-dev     | Pass --verbose to see the stacktrace.
nest-dev     |  NX   Unable to connect to the daemon process.
nest-dev     | 
nest-dev     | 
nest-dev     | Messages from the log:
nest-dev     |     at TaskHistory.recordTaskRuns (/a/path/to/node_modules/nx/src/utils/task-history.js:32:37)
nest-dev     |     at handleRecordTaskRuns (/a/path/to/node_modules/nx/src/daemon/server/handle-task-history.js:9:23)
nest-dev     |     at /a/path/to/node_modules/nx/src/daemon/server/server.js:177:122
nest-dev     |     at handleResult (/a/path/to/node_modules/nx/src/daemon/server/server.js:214:20)
nest-dev     |     at handleMessage (/a/path/to/node_modules/nx/src/daemon/server/server.js:177:15)
nest-dev     |     at /a/path/to/node_modules/nx/src/daemon/server/server.js:79:15
nest-dev     |     at Socket.<anonymous> (/a/path/to/node_modules/nx/src/utils/consume-messages-from-socket.js:23:21)
nest-dev     |     at Socket.emit (node:events:519:28)
nest-dev     |     at addChunk (node:internal/streams/readable:561:12)
nest-dev     |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.392Z - Done responding to the client null
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.676Z - Started listening on: /nx-daemon/d.sock
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.679Z - [WATCHER]: Subscribed to changes within: /app (native)
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.681Z - [NX-CONSOLE]: Pulling latest Nx (latest) to check console status...
nest-dev     | Fetching nx...
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.686Z - Started listening on: /nx-daemon/d.sock
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.689Z - [WATCHER]: Subscribed to changes within: /app (native)
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:16:49.691Z - [NX-CONSOLE]: Pulling latest Nx (latest) to check console status...
nest-dev     | Fetching nx...
nest-dev     | 
nest-dev     | 
nest-dev     | 
nest-dev     | More information: /app/.nx/workspace-data/d/daemon.log
nest-dev     | Pass --verbose to see the stacktrace.
nest-dev     | 
nest-dev exited with code 1 (restarting)
nest-dev     |  NX   Unable to connect to the daemon process.
nest-dev     | 
nest-dev     | 
nest-dev     | Messages from the log:
nest-dev     | Time for 'plugin worker 11988 code loading' 8.899175
nest-dev     | Time for 'plugin worker 11995 code loading' 8.167038999999995
nest-dev     | Time for 'plugin worker 12014 code loading' 8.993581999999996
nest-dev     | Time for 'plugin worker 12002 code loading' 8.083030999999998
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:05.621Z - Established a connection. Number of open connections: 2
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:05.621Z - Closed a connection. Number of open connections: 1
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:05.662Z - Started listening on: /nx-daemon/d.sock
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:05.665Z - [WATCHER]: Subscribed to changes within: /app (native)
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:05.669Z - [NX-CONSOLE]: Pulling latest Nx (latest) to check console status...
nest-dev     | Fetching nx...
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:05.684Z - Closed a connection. Number of open connections: 0
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:05.686Z - [WATCHER]: Stopping the watcher for /a/path/to (sources)
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:05.686Z - [WATCHER]: Stopping the watcher for /a/path/to (outputs)
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:05.686Z - Server stopped because: "this process is no longer the current daemon (native)"
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:05.999Z - Started listening on: /tmp/900856e14d039b4997e0/d.sock
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:06.006Z - [WATCHER]: Subscribed to changes within: /a/path/to (native)
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:06.010Z - [NX-CONSOLE]: Pulling latest Nx (latest) to check console status...
nest-dev     | Fetching nx...
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:17:06.031Z - Established a connection. Number of open connections: 1
nest-dev     | 
nest-dev     | 
nest-dev     | 
nest-dev     | More information: /app/.nx/workspace-data/d/daemon.log
nest-dev     | Pass --verbose to see the stacktrace.
nest-dev     | 
nest-dev exited with code 1 (restarting)
```

After disabling Nx Cloud by setting the `NX_NO_CLOUD` to `true` in my container and passing `--verbose`, I am able to narrow down the logs to the following
```
nest-dev     |  NX   Nx Cloud manually disabled
nest-dev     | Nx will continue running, but nothing will be written or read from the remote cache.
nest-dev     | Run details will also not be available in the Nx Cloud UI.
nest-dev     | If this wasn't intentional, check for the NX_NO_CLOUD environment variable or the --no-cloud flag.
nest-dev     | > nx run api:build:development  [local cache]
nest-dev     | > webpack-cli build --node-env=development
nest-dev     | chunk (runtime: main) main.js (main) 2.78 KiB [entry] [rendered]
nest-dev     | webpack compiled successfully (b0e90c227fabccf6)
nest-dev     |  NX   Successfully ran target build for project api
nest-dev     | Nx read the output from the cache instead of running the command for 1 out of 1 tasks.
nest-dev     |  NX   DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 }, Some("FOREIGN KEY constraint failed"))
nest-dev     | Error: DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 }, Some("FOREIGN KEY constraint failed"))
nest-dev     |     at TaskHistory.recordTaskRuns (/a/path/to/node_modules/nx/src/utils/task-history.js:32:37)
nest-dev     |     at handleRecordTaskRuns (/a/path/to/node_modules/nx/src/daemon/server/handle-task-history.js:9:23)
nest-dev     |     at /a/path/to/node_modules/nx/src/daemon/server/server.js:177:122
nest-dev     |     at handleResult (/a/path/to/node_modules/nx/src/daemon/server/server.js:214:20)
nest-dev     |     at handleMessage (/a/path/to/node_modules/nx/src/daemon/server/server.js:177:15)
nest-dev     |     at /a/path/to/node_modules/nx/src/daemon/server/server.js:79:15
nest-dev     |     at Socket.<anonymous> (/a/path/to/node_modules/nx/src/utils/consume-messages-from-socket.js:23:21)
nest-dev     |     at Socket.emit (node:events:519:28)
nest-dev     |     at addChunk (node:internal/streams/readable:561:12)
nest-dev     |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
nest-dev     | Build failed, waiting for changes to restart...
nest-dev     | Watch error: Daemon closed the connection
nest-dev     | 
nest-dev     | 
nest-dev     | 
nest-dev     |  NX   Successfully ran target serve for project api and 1 task it depends on
nest-dev     | 
nest-dev     | Nx read the output from the cache instead of running the command for 1 out of 2 tasks.
nest-dev     | 
nest-dev     | 
nest-dev     |  NX   Error: write EPIPE
nest-dev     | 
nest-dev     | 
nest-dev     | Messages from the log:
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:31:23.242Z - Received raw message of length 220
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:31:23.242Z - Received json message of type RECORD_TASK_RUNS
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:31:23.243Z - [REQUEST]: Responding to the client with an error. [RECORD_TASK_RUNS] DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 }, Some("FOREIGN KEY constraint failed"))
nest-dev     | Error: DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 }, Some("FOREIGN KEY constraint failed"))
nest-dev     |     at TaskHistory.recordTaskRuns (/a/path/to/node_modules/nx/src/utils/task-history.js:32:37)
nest-dev     |     at handleRecordTaskRuns (/a/path/to/node_modules/nx/src/daemon/server/handle-task-history.js:9:23)
nest-dev     |     at /a/path/to/node_modules/nx/src/daemon/server/server.js:177:122
nest-dev     |     at handleResult (/a/path/to/node_modules/nx/src/daemon/server/server.js:214:20)
nest-dev     |     at handleMessage (/a/path/to/node_modules/nx/src/daemon/server/server.js:177:15)
nest-dev     |     at /a/path/to/node_modules/nx/src/daemon/server/server.js:79:15
nest-dev     |     at Socket.<anonymous> (/a/path/to/node_modules/nx/src/utils/consume-messages-from-socket.js:23:21)
nest-dev     |     at Socket.emit (node:events:519:28)
nest-dev     |     at addChunk (node:internal/streams/readable:561:12)
nest-dev     |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:31:23.244Z - Done responding to the client null
nest-dev     | Time for 'daemon-message-serialization-GLOB' 0.21095100000002276
nest-dev     | Time for 'daemon-message-serialization-HASH_GLOB' 0.332883000000038
nest-dev     | Time for 'daemon-message-serialization-HASH_MULTI_GLOB' 0.3338939999999866
nest-dev     | Time for 'daemon-message-serialization-HASH_GLOB' 0.18603800000005322
nest-dev     | 
nest-dev     | 
nest-dev     | 
nest-dev     | More information: /app/.nx/workspace-data/d/daemon.log
nest-dev     | Error: Error: write EPIPE
nest-dev     | 
nest-dev     | Messages from the log:
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:31:23.242Z - Received raw message of length 220
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:31:23.242Z - Received json message of type RECORD_TASK_RUNS
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:31:23.243Z - [REQUEST]: Responding to the client with an error. [RECORD_TASK_RUNS] DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 }, Some("FOREIGN KEY constraint failed"))
nest-dev     | Error: DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 787 }, Some("FOREIGN KEY constraint failed"))
nest-dev     |     at TaskHistory.recordTaskRuns (/a/path/to/node_modules/nx/src/utils/task-history.js:32:37)
nest-dev     |     at handleRecordTaskRuns (/a/path/to/node_modules/nx/src/daemon/server/handle-task-history.js:9:23)
nest-dev     |     at /a/path/to/node_modules/nx/src/daemon/server/server.js:177:122
nest-dev     |     at handleResult (/a/path/to/node_modules/nx/src/daemon/server/server.js:214:20)
nest-dev     |     at handleMessage (/a/path/to/node_modules/nx/src/daemon/server/server.js:177:15)
nest-dev     |     at /a/path/to/node_modules/nx/src/daemon/server/server.js:79:15
nest-dev     |     at Socket.<anonymous> (/a/path/to/node_modules/nx/src/utils/consume-messages-from-socket.js:23:21)
nest-dev     |     at Socket.emit (node:events:519:28)
nest-dev     |     at addChunk (node:internal/streams/readable:561:12)
nest-dev     |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
nest-dev     | [NX v22.1.0 Daemon Server] - 2025-11-21T07:31:23.244Z - Done responding to the client null
nest-dev     | Time for 'daemon-message-serialization-GLOB' 0.21095100000002276
nest-dev     | Time for 'daemon-message-serialization-HASH_GLOB' 0.332883000000038
nest-dev     | Time for 'daemon-message-serialization-HASH_MULTI_GLOB' 0.3338939999999866
nest-dev     | Time for 'daemon-message-serialization-HASH_GLOB' 0.18603800000005322
nest-dev     | 
nest-dev     | 
nest-dev     | 
nest-dev     | More information: /app/.nx/workspace-data/d/daemon.log
nest-dev     |     at daemonProcessException (/app/node_modules/nx/src/daemon/client/client.js:625:23)
nest-dev     |     at Socket.<anonymous> (/app/node_modules/nx/src/daemon/client/client.js:428:25)
nest-dev     |     at Socket.emit (node:events:508:28)
nest-dev     |     at emitErrorNT (node:internal/streams/destroy:170:8)
nest-dev     |     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
nest-dev     |     at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
nest-dev     | 
angular-dev  |  NX   Nx Daemon was not able to compute the project graph.
angular-dev  | Log file with the error: /app/.nx/workspace-data/d/daemon-error.log
angular-dev  | Please file an issue at https://github.com/nrwl/nx
angular-dev  | Nx Daemon is going to be disabled until you run "nx reset".
```

**Comment by SoltanReza** [comment]
Hello ,
I tested suggestions above but  i'm having the same issue only in my nestjs projects . 
Do you guys have any update on how to fix that ? 
Thank you

**Comment by yossef7525** [comment]
Same problem with nestjs projects

**Comment by AdiMarianMutu** [comment]
> i have no idea what caused this for me since today morning, similar on macos too. I manage node versions via Mise & my sh is Fish.
> 
> ```
> npx nx report
> 
>  NX   Report complete - copy this into the issue template
> 
> Node           : 24.9.0
> OS             : darwin-arm64
> Native Target  : aarch64-macos
> npm            : 11.6.0
> 
> nx                     : 21.6.3
> @nx/js                 : 21.6.3
> @nx/jest               : 21.6.3
> @nx/eslint             : 21.6.3
> @nx/workspace          : 21.6.3
> @nx/devkit             : 21.6.3
> @nx/esbuild            : 21.6.3
> @nx/eslint-plugin      : 21.6.3
> @nx/express            : 21.6.4
> @nx/module-federation  : 21.6.4
> @nx/node               : 21.6.3
> @nx/playwright         : 21.6.3
> @nx/react              : 21.6.4
> @nx/rollup             : 21.6.4
> @nx/vite               : 21.6.3
> @nx/web                : 21.6.3
> @nx/docker             : 21.6.3
> typescript             : 5.9.3
> ---------------------------------------
> Registered Plugins:
> @nx/vite/plugin
> @nx/playwright/plugin
> @nx/eslint/plugin
> @nx/jest/plugin
> ---------------------------------------
> Cache Usage: 925.17 KB / 46.04 GB
> ---------------------------------------
> The following packages should match the installed version of nx
>   - @nx/express@21.6.4
>   - @nx/module-federation@21.6.4
>   - @nx/react@21.6.4
>   - @nx/rollup@21.6.4
> 
> To fix this, run `nx migrate nx@21.6.4`
> ```
> 
> there was this file .nx/workspace-data/d/disabled which had a value of true. deleting it seemed to make it work.

Had the same issue happen only when running a `NestJS` app. 

For me the `.nx/workspace-data/d/disabled` file contained exactly the same content of ` .nx/workspace-data/d/daemon-error.log`, it worked after deleting it (the `disabled` file).

This is from the `daemon-error.log`:

```sh
[NX v22.3.3 Daemon Server] - 2026-01-26T21:58:28.931Z - Server stopped because: "this process is no longer the current daemon (native)"
```

**Comment by R1D3R175** [comment]
Hello, I solved it by setting `NX_SOCKET_DIR`, `NX_CACHE_DIRECTORY`, and `NX_WORKSPACE_DATA_DIRECTORY` environment variables to an anonymous docker volume. For more info check out the [docs](https://nx.dev/docs/reference/environment-variables#nx-environment-variables)

```yml
services:
  api:
    environment:
      NODE_ENV: development
      NX_DAEMON: true
      NX_CACHE_DIRECTORY: /nx/cache
      NX_SOCKET_DIR: /nx/socket
      NX_WORKSPACE_DATA_DIRECTORY: /nx/workspace-data
    volumes:
      - .:/monorepo
      - node_modules:/monorepo/node_modules
      - nx_cache:/nx/cache
      - nx_socket:/nx/socket
      - nx_workspace_data:/nx/workspace-data
    command: pnpm nx serve api --host=0.0.0.0 --watch

volumes:
  node_modules:
  nx_cache:
  nx_socket:
  nx_workspace_data:

```
