### ISSUE TITLE
v20.0.2 - yarn install failed on docker

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#28525]
### Current Behavior

I try to build the image: `docker build --progress=plain --no-cache  -t nx-repo .` but it's failed in `yarn install` inside the docker (outside it's working).

this is the log:

```
....
#10 91.63 [4/4] Building fresh packages...
#10 91.63 verbose 85.842249121 Error: /app/node_modules/@nrwl/devkit/node_modules/nx, /app/node_modules/@nrwl/tao/node_modules/nx, /app/node_modules/ngxtension/node_modules/nx: Command failed.
#10 91.63 Exit code: 135
#10 91.63 Command: node ./bin/post-install
#10 91.63 Arguments:
#10 91.63 Directory: /app/node_modules/ngxtension/node_modules/nx
#10 91.63 Output:
#10 91.63 Bus error
#10 91.63     at ProcessTermError.ExtendableBuiltin (/opt/yarn-v1.22.22/lib/cli.js:721:66)
#10 91.63     at ProcessTermError.MessageError (/opt/yarn-v1.22.22/lib/cli.js:750:123)
#10 91.63     at new ProcessTermError (/opt/yarn-v1.22.22/lib/cli.js:790:113)
#10 91.63     at ChildProcess.<anonymous> (/opt/yarn-v1.22.22/lib/cli.js:25789:17)
#10 91.63     at ChildProcess.emit (node:events:519:28)
#10 91.63     at maybeClose (node:internal/child_process:1105:16)
#10 91.63     at Socket.<anonymous> (node:internal/child_process:457:11)
#10 91.63     at Socket.emit (node:events:519:28)
#10 91.63     at Pipe.<anonymous> (node:net:339:12)
#10 91.63 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#10 91.63 verbose 85.847962121
#10 91.63 verbose 85.901016955
#10 91.63 verbose 86.018386121
#10 91.63 verbose 86.018475371
#10 91.63 verbose 86.306140997
#10 91.63 verbose 86.408533747
#10 91.63 verbose 89.18034579
#10 91.63 verbose 89.445007373
#10 91.63 verbose 90.45812904
#10 91.63 verbose 90.75884104
#10 91.63 verbose 90.832659665 node:internal/errors:541
#10 91.63       throw error;
#10 91.63       ^
#10 91.63
#10 91.63 TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
#10 91.63     at Module.require (node:internal/modules/cjs/loader:1304:3)
#10 91.63     at require (node:internal/modules/helpers:179:18)
#10 91.63     at load (/app/node_modules/node-gyp-build-optional-packages/node-gyp-build.js:28:10)
#10 91.63     at Object.<anonymous> (/app/node_modules/node-gyp-build-optional-packages/build-test.js:19:19)
#10 91.63     at Module._compile (node:internal/modules/cjs/loader:1469:14)
#10 91.63     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
#10 91.63     at Module.load (node:internal/modules/cjs/loader:1288:32)
#10 91.63     at Module._load (node:internal/modules/cjs/loader:1104:12)
#10 91.63     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
#10 91.63     at node:internal/main/run_main_module:28:49 {
#10 91.63   code: 'ERR_INVALID_ARG_TYPE'
#10 91.63 }
#10 91.63
#10 91.63 Node.js v20.18.0
#10 91.63
#10 91.63 The failure above indicates the primary issue with the native builds which are included for all major platforms. Will now attempt to build the package locally in case this can be resolved by re-compiling.
#10 91.63 gyp info it worked if it ends with ok
#10 91.63 gyp info using node-gyp@10.2.0
#10 91.63 gyp info using node@20.18.0 | linux | arm64
#10 91.63 gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
#10 91.63 gyp http GET https://nodejs.org/download/release/v20.18.0/node-v20.18.0-headers.tar.gz
#10 91.63 gyp http 200 https://nodejs.org/download/release/v20.18.0/node-v20.18.0-headers.tar.gz
#10 91.63
#10 91.63 gyp http GET https://nodejs.org/download/release/v20.18.0/SHASUMS256.txt
#10 91.63 gyp http 200 https://nodejs.org/download/release/v20.18.0/SHASUMS256.txt
#10 91.63 gyp info spawn /usr/bin/python3
#10 91.63 gyp info spawn args [
#10 91.63 gyp info spawn args '/app/node_modules/node-gyp/gyp/gyp_main.py',
#10 91.63 gyp info spawn args 'binding.gyp',
#10 91.63 gyp info spawn args '-f',
#10 91.63 gyp info spawn args 'make',
#10 91.63 gyp info spawn args '-I',
#10 91.63 gyp info spawn args '/app/node_modules/msgpackr-extract/build/config.gypi',
#10 91.63 gyp info spawn args '-I',
#10 91.63 gyp info spawn args '/app/node_modules/node-gyp/addon.gypi',
#10 91.63 gyp info spawn args '-I',
#10 91.63 gyp info spawn args '/root/.cache/node-gyp/20.18.0/include/node/common.gypi',
#10 91.63 gyp info spawn args '-Dlibrary=shared_library',
#10 91.63 gyp info spawn args '-Dvisibility=default',
#10 91.63 gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/20.18.0',
#10 91.63 gyp info spawn args '-Dnode_gyp_dir=/app/node_modules/node-gyp',
#10 91.63 gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/20.18.0/<(target_arch)/node.lib',
#10 91.63 gyp info spawn args '-Dmodule_root_dir=/app/node_modules/msgpackr-extract',
#10 91.63 gyp info spawn args '-Dnode_engine=v8',
#10 91.63 gyp info spawn args '--depth=.',
#10 91.63 gyp info spawn args '--no-parallel',
#10 91.63 gyp info spawn args '--generator-output',
#10 91.63 gyp info spawn args 'build',
#10 91.63 gyp info spawn args '-Goutput_dir=.'
#10 91.63 gyp info spawn args ]
#10 91.63 gyp info spawn make
#10 91.63 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
#10 91.63 make: Entering directory '/app/node_modules/msgpackr-extract/build'
#10 91.63   CXX(target) Release/obj.target/extract/src/extract.o
#10 91.63   SOLINK_MODULE(target) Release/obj.target/extract.node
#10 91.63   COPY Release/extract.node
#10 91.63 make: Leaving directory '/app/node_modules/msgpackr-extract/build'
#10 91.63 gyp info ok
#10 91.63 verbose 90.908159332
#10 91.63 verbose 90.95823754 /app/node_modules/node-gyp-build/node-gyp-build.js:60
#10 91.63   throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
#10 91.63   ^
#10 91.63
#10 91.63 Error: No native build was found for platform=linux arch=arm64 runtime=node abi=115 uv=1 armv=8 libc=glibc node=20.18.0
#10 91.63     loaded from: /app/node_modules/nice-napi
#10 91.63
#10 91.63     at load.resolve.load.path (/app/node_modules/node-gyp-build/node-gyp-build.js:60:9)
#10 91.63     at load (/app/node_modules/node-gyp-build/node-gyp-build.js:22:30)
#10 91.63     at Object.<anonymous> (/app/node_modules/node-gyp-build/build-test.js:19:19)
#10 91.63     at Module._compile (node:internal/modules/cjs/loader:1469:14)
#10 91.63     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
#10 91.63     at Module.load (node:internal/modules/cjs/loader:1288:32)
#10 91.63     at Module._load (node:internal/modules/cjs/loader:1104:12)
#10 91.63     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
#10 91.63     at node:internal/main/run_main_module:28:49
#10 91.63
#10 91.63 Node.js v20.18.0
#10 91.63
#10 91.63 gyp info it worked if it ends with ok
#10 91.63 gyp info using node-gyp@10.2.0
#10 91.63 gyp info using node@20.18.0 | linux | arm64
#10 91.63 gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
#10 91.63 gyp http GET https://nodejs.org/download/release/v20.18.0/node-v20.18.0-headers.tar.gz
#10 91.63
#10 91.63 gyp http 200 https://nodejs.org/download/release/v20.18.0/node-v20.18.0-headers.tar.gz
#10 91.63 gyp http GET https://nodejs.org/download/release/v20.18.0/SHASUMS256.txt
#10 91.63 gyp http 200 https://nodejs.org/download/release/v20.18.0/SHASUMS256.txt
#10 91.63 gyp info spawn /usr/bin/python3
#10 91.63 gyp info spawn args [
#10 91.63 gyp info spawn args '/app/node_modules/node-gyp/gyp/gyp_main.py',
#10 91.63 gyp info spawn args 'binding.gyp',
#10 91.63 gyp info spawn args '-f',
#10 91.63 gyp info spawn args 'make',
#10 91.63 gyp info spawn args '-I',
#10 91.63 gyp info spawn args '/app/node_modules/nice-napi/build/config.gypi',
#10 91.63 gyp info spawn args '-I',
#10 91.63 gyp info spawn args '/app/node_modules/node-gyp/addon.gypi',
#10 91.63 gyp info spawn args '-I',
#10 91.63 gyp info spawn args '/root/.cache/node-gyp/20.18.0/include/node/common.gypi',
#10 91.63 gyp info spawn args '-Dlibrary=shared_library',
#10 91.63 gyp info spawn args '-Dvisibility=default',
#10 91.63 gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/20.18.0',
#10 91.63 gyp info spawn args '-Dnode_gyp_dir=/app/node_modules/node-gyp',
#10 91.63 gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/20.18.0/<(target_arch)/node.lib',
#10 91.63 gyp info spawn args '-Dmodule_root_dir=/app/node_modules/nice-napi',
#10 91.63 gyp info spawn args '-Dnode_engine=v8',
#10 91.63 gyp info spawn args '--depth=.',
#10 91.63 gyp info spawn args '--no-parallel',
#10 91.63 gyp info spawn args '--generator-output',
#10 91.63 gyp info spawn args 'build',
#10 91.63 gyp info spawn args '-Goutput_dir=.'
#10 91.63 gyp info spawn args ]
#10 91.63 gyp info spawn make
#10 91.63 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
#10 91.63 make: Entering directory '/app/node_modules/nice-napi/build'
#10 91.63   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
#10 91.63 rm -f Release/obj.target/../node-addon-api/nothing.a Release/obj.target/../node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/../node-addon-api/nothing.a`
#10 91.63 ar crs Release/obj.target/../node-addon-api/nothing.a @Release/obj.target/../node-addon-api/nothing.a.ar-file-list
#10 91.63   COPY Release/nothing.a
#10 91.63   CXX(target) Release/obj.target/nice_napi/binding.o
#10 91.63   SOLINK_MODULE(target) Release/obj.target/nice_napi.node
#10 91.63   COPY Release/nice_napi.node
#10 91.63 make: Leaving directory '/app/node_modules/nice-napi/build'
#10 91.63 gyp info ok
#10 ERROR: process "/bin/sh -c yarn --frozen-lockfile --verbose" did not complete successfully: exit code: 135
------
 > [5/7] RUN yarn --frozen-lockfile --verbose:
91.63 make: Entering directory '/app/node_modules/nice-napi/build'
91.63   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
91.63 rm -f Release/obj.target/../node-addon-api/nothing.a Release/obj.target/../node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/../node-addon-api/nothing.a`
91.63 ar crs Release/obj.target/../node-addon-api/nothing.a @Release/obj.target/../node-addon-api/nothing.a.ar-file-list
91.63   COPY Release/nothing.a
91.63   CXX(target) Release/obj.target/nice_napi/binding.o
91.63   SOLINK_MODULE(target) Release/obj.target/nice_napi.node
91.63   COPY Release/nice_napi.node
91.63 make: Leaving directory '/app/node_modules/nice-napi/build'
91.63 gyp info ok
------
Dockerfile:11
--------------------
   9 |     COPY yarn.lock package.json ./
  10 |
  11 | >>> RUN yarn --frozen-lockfile --verbose
  12 |
  13 |     COPY . .
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn --frozen-lockfile --verbose" did not complete successfully: exit code: 135

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/kkoa3s6l302dfrszg4p9mrcw9
```

### Expected Behavior

yarn install should working on docker

### GitHub Repo

https://github.com/wizardnet972/nx-repo.git

### Steps to Reproduce

create a `main.sh` file with this content and then run `bash main.sh`.  or clone the github repo I provided and then try to build the image.

```
#!/bin/bash

# Define the repository name
repo="nx-repo"

rm -rf $repo

npx --yes create-nx-workspace@latest $repo --preset angular-monorepo --appName ${repo}-ui --bundler esbuild --style scss --ssr false --e2eTestRunner playwright --ci skip --pm yarn

cd $repo

yarn add ngxtension

yarn nx g @nx/angular:lib --name ng-lib --directory libs/ng-lib --buildable

yarn nx generate @nx/angular:storybook-configuration --project=${repo}-ui --no-interactive

yarn nx run-many -t build,lint,test

# Create a Dockerfile
cat <<EOF >Dockerfile
FROM node:20.18.0-bullseye-slim

# RUN apk update && apk add git g++ make py3-pip curl

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /app

COPY yarn.lock package.json ./

RUN yarn --frozen-lockfile --verbose

COPY . .

RUN yarn nx run-many -t build,lint
EOF

# Create a Dockerfile
cat <<EOF >.dockerignore
node_modules
dist
.angular
.nx
EOF

docker build --progress=plain --no-cache  -t $repo .
```

### Nx Report

n/a

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ussuritiger** [comment]
Not sure this is the same issue but after upgrading `nx` to the `20.0.2` version I am getting the following error while running `yarn install` inside the Docker container:
```
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /opt/webapp/node_modules/@lerna/create/node_modules/nx, /opt/webapp/node_modules/@nrwl/tao/node_modules/nx, /opt/webapp/node_modules/@nx/devkit/node_modules/nx, /opt/webapp/node_modules/lerna/node_modules/nx: Command failed.
Exit signal: SIGBUS
Command: node ./bin/post-install
```
Running `yarn install` just from the host (Ubuntu) machine has no problems.

**Comment by wizardnet972** [comment]
@ussuritiger it's same problem. add `--verbose` to `yarn install`.

**Comment by jaysoo** [comment]
Can you try removing `@nrwl/*` pacakges like tao and devkit? I'm not sure why they're in the lockfile, but they aren't needed and will definitely cause issues with v20 packages.

**Comment by aalbericio** [comment]
I'm running into the same issue:

Node: 22.11.0
Nx: 20.0.8

I can successfully run "npm i" locally but fails in Gitlab (Node 22-slim) saying:

```
npm error code 135
npm error path /builds/oneatms/html5-console/node_modules/@nrwl/tao/node_modules/nx
npm error command failed
npm error command sh -c node ./bin/post-install
npm error Bus error (core dumped)
```

What can I do? :(


Thanks

**Comment by aalbericio** [comment]
Turns out that lerna 8.1.8 was pulling @nrwl/tao. 

After upgrading to lerna 8.1.9 that dependency is gone and pipeline now runs successfully.
