### ISSUE TITLE
Error running cypress in parallel

### ISSUE THREAD

**Issue by jordi72** [nrwl/nx#28592]
### Current Behavior

When running cypress in parallel i'm getting this error.

![Image](https://github.com/user-attachments/assets/0b9f852d-e47b-4d15-a7e8-c7ec87660b46)

### Expected Behavior

Working fine.

### Steps to Reproduce

Nodejs 22.5, Angular monorepo + cypress, pipelines in Azure (we can debug in a call)

### Nx Report

NX   Report complete - copy this into the issue template

Node           : 22.5.1
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.8.2

nx                 : 20.0.3
@nx/js             : 20.0.3
@nx/jest           : 20.0.3
@nx/eslint         : 20.0.3
@nx/workspace      : 20.0.3
@nx/angular        : 20.0.3
@nx/cypress        : 20.0.3
@nx/devkit         : 20.0.3
@nx/eslint-plugin  : 20.0.3
@nx/web            : 20.0.3
@nx/webpack        : 20.0.3
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
@jsverse/transloco       : 7.5.0
angular-auth-oidc-client : 18.0.1
ngxtension               : 4.0.0

### Failure Logs

/azp/_work/1/s/node_modules/nx/bin/nx.js:116
    globalThis.GLOBAL_NX_VERSION ??= GLOBAL_NX_VERSION;
                                  ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

##[error]Bash exited with code '1'.

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment]
The `unexpected token ?` here really reads like an outdated node install, I know you've listed node 22 in the issue but can you run nx report in the pipeline above to verify that it is actually running node 22?
