### ISSUE TITLE
Upgrading to Nx v20 throwing error about nonexistent package version

### ISSUE THREAD

**Issue by captDaylight** [nrwl/nx#28624]
### Current Behavior

When I try to upgrade from v19 to v20 I'm seeing the error:

```
npx nx migrate nx@20              


Fetching meta data about packages.
It may take a few minutes.
Fetching nx@20.0.5
Fetching @nrwl/webpack@20.0.5
Fetching @nrwl/js@20.0.5
Fetching @nrwl/eslint-plugin-nx@20.0.5
Fetching @nrwl/cypress@20.0.5
Fetching @nrwl/workspace@20.0.5
Fetching @nrwl/react@20.0.5
Unable to fetch migrations for @nrwl/webpack@20.0.5: Command failed: npm install @nrwl/webpack@20.0.5
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/webpack@20.0.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

When I look at versions of `@nrwl/webpack@20.0.5` I see:

```
  ...
  '19.8.0',
  '19.8.1',
  '19.8.2',
  '19.8.3',
  '19.8.4',
  '19.8.5',
  '19.8.6',
  '19.9.0-canary.20240921-a510b36',
  '20.0.0-beta.0',
  '20.0.0-beta.1',
  '20.0.0-beta.2',
  '20.0.0-beta.3',
  '20.0.0-beta.4',
  '20.0.0-canary.20240924-3e1a879',
  '20.0.0-canary.20240925-6182d20',
  '20.0.0-canary.20240926-529ab94'
]
```

### Expected Behavior

I would expect that the migration would work and that it will be pointing to a current version of `@nrwl/webpack@20.0.5`.

### Steps to Reproduce

1. Have a Nx repo at version 19
2. Run `npx nx migrate nx@20`

### Nx Report

 >  NX   Report complete - copy this into the issue template

   Node : 20.12.2
   OS   : darwin arm64
   npm  : 10.5.0
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.9.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.9.7
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.9.7
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.9.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 19.0.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 5.6.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

### Package Manager Version

npm 10.5.0

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Eirmas** [comment]
Packages under the `@nrwl/*` namespace no longer exist. You should use `@nx/*` instead.

https://nx.dev/deprecated/rescope

**Comment by jaysoo** [comment]
As @Eirmas said, we no longer publish the deprecated `@nrwl/` packages. I would also suggest updating one major version are a time if you can.

**Comment by jccrosby** [comment]
I'm getting a similar issue but around `@nx/linter@20.0.5`

```sh
nx migrate latest --verbose

Fetching meta data about packages.
It may take a few minutes.
Fetching nx@20.0.5
Fetching @nx/linter@20.0.5
Unable to fetch migrations for @nx/linter@20.0.5: Command failed: npm install @nx/linter@20.0.5
npm error code ETARGET
npm error notarget No matching version found for @nx/linter@20.0.5.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.


 NX   The migrate command failed.


 NX   Cannot read properties of undefined (reading 'schematics')
```

### `nx report`

```sh
Node   : 18.20.4
OS     : darwin-arm64
yarn   : 1.22.22

nx                 : 18.0.5
@nx/js             : 18.0.5
@nx/jest           : 18.0.5
@nx/linter         : 18.0.5
@nx/eslint         : 18.0.5
@nx/workspace      : 18.0.5
@nx/cypress        : 18.0.5
@nx/devkit         : 18.0.5
@nx/esbuild        : 18.0.5
@nx/eslint-plugin  : 18.0.5
@nx/plugin         : 18.0.5
@nx/react          : 18.0.5
@nx/rollup         : 18.0.5
@nx/storybook      : 18.0.5
@nrwl/tao          : 18.0.5
@nx/web            : 18.0.5
@nx/webpack        : 18.0.5
typescript         : 5.3.3
```

**Comment by matthargett** [comment]
same problem as @jccrosby:

```
nx migrate latest --verbose
Fetching meta data about packages.
It may take a few minutes.
Fetching nx@20.0.6
Fetching @nx/linter@20.0.6
Unable to fetch migrations for @nx/linter@20.0.6: Command failed: npm install @nx/linter@20.0.6
npm error code ETARGET
npm error notarget No matching version found for @nx/linter@20.0.6.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: /Users/matt/.npm/_logs/2024-10-26T02_18_23_968Z-debug-0.log


 NX   The migrate command failed.


 NX   Cannot read properties of undefined (reading 'schematics')

TypeError: Cannot read properties of undefined (reading 'schematics')
    at /private/var/folders/dn/ft1qsj9527181lmxm545hnxm0000gn/T/tmp-34340-glrf2QHsRzPO/node_modules/nx/src/command-line/migrate/migrate.js:560:24
    at async Migrator.populatePackageJsonUpdatesAndGetPackagesToCheck (/private/var/folders/dn/ft1qsj9527181lmxm545hnxm0000gn/T/tmp-34340-glrf2QHsRzPO/node_modules/nx/src/command-line/migrate/migrate.js:147:31)
    at async Promise.all (index 2)
    at async Migrator.populatePackageJsonUpdatesAndGetPackagesToCheck (/private/var/folders/dn/ft1qsj9527181lmxm545hnxm0000gn/T/tmp-34340-glrf2QHsRzPO/node_modules/nx/src/command-line/migrate/migrate.js:177:17)
    at async Migrator.buildPackageJsonUpdates (/private/var/folders/dn/ft1qsj9527181lmxm545hnxm0000gn/T/tmp-34340-glrf2QHsRzPO/node_modules/nx/src/command-line/migrate/migrate.js:117:33)
    at async Migrator.migrate (/private/var/folders/dn/ft1qsj9527181lmxm545hnxm0000gn/T/tmp-34340-glrf2QHsRzPO/node_modules/nx/src/command-line/migrate/migrate.js:83:9)
    at async generateMigrationsJsonAndUpdatePackageJson (/private/var/folders/dn/ft1qsj9527181lmxm545hnxm0000gn/T/tmp-34340-glrf2QHsRzPO/node_modules/nx/src/command-line/migrate/migrate.js:768:78)
    at async /private/var/folders/dn/ft1qsj9527181lmxm545hnxm0000gn/T/tmp-34340-glrf2QHsRzPO/node_modules/nx/src/command-line/migrate/migrate.js:1047:13
    at async handleErrors (/private/var/folders/dn/ft1qsj9527181lmxm545hnxm0000gn/T/tmp-34340-glrf2QHsRzPO/node_modules/nx/src/utils/handle-errors.js:9:24)
    at async Object.handler (/private/var/folders/dn/ft1qsj9527181lmxm545hnxm0000gn/T/tmp-34340-glrf2QHsRzPO/node_modules/nx/src/command-line/migrate/command-object.js:27:43)
```

# nx report
```
Node           : 20.11.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.0

nx (global)        : 20.0.6
nx                 : 19.6.3
@nx/js             : 19.6.3
@nx/jest           : 19.6.3
@nx/linter         : 19.6.3
@nx/eslint         : 19.6.3
@nx/workspace      : 19.6.3
@nx/devkit         : 19.6.3
@nx/esbuild        : 19.6.3
@nx/eslint-plugin  : 19.6.3
@nx/node           : 19.6.3
@nx/react          : 19.6.3
@nrwl/tao          : 19.6.3
@nx/web            : 19.6.3
@nx/webpack        : 19.6.3
typescript         : 5.5.4
```

**Comment by rads92stx** [comment]
I don't have any dependencies with `@nrwl` prefix, but while running `pnpm nx report` I've got below: 

```➜  ts-frontend git:(debug-nx-dependencies) pnpm nx report                  

 NX   Report complete - copy this into the issue template

Node           : 22.10.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.12.2

nx                 : 20.0.6
@nx/js             : 20.0.6
@nx/eslint         : 20.0.6
@nx/workspace      : 20.0.6
@nrwl/workspace    : 19.8.4
@nx/cypress        : 20.0.6
@nx/devkit         : 20.0.6
@nrwl/devkit       : 19.8.4
@nx/eslint-plugin  : 20.0.6
@nx/next           : 20.0.6
@nx/react          : 20.0.6
@nx/storybook      : 20.0.6
@nrwl/tao          : 19.8.4
@nx/vite           : 20.0.6
@nx/web            : 20.0.6
@nx/webpack        : 20.0.6
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
@trumbitta/nx-plugin-unused-deps : 1.12.1
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/workspace@19.8.4
  - @nrwl/devkit@19.8.4
  - @nrwl/tao@19.8.4

To fix this, run `nx migrate nx@20.0.6`
```

My dependencies: 
```
  "dependencies": {
    "@emotion/react": "11.11.1",
    "@emotion/styled": "11.11.0",
    "@faker-js/faker": "^8.4.1",
    "@fontsource-variable/work-sans": "^5.0.19",
    "@mui/icons-material": "^5.15.15",
    "@mui/material": "^5.15.15",
    "@mui/x-date-pickers": "^7.7.1",
    "@nivo/axes": "^0.87.0",
    "@nivo/bar": "^0.87.0",
    "@nivo/colors": "^0.87.0",
    "@nivo/core": "^0.87.0",
    "@nivo/funnel": "^0.87.0",
    "@nivo/pie": "^0.87.0",
    "@nivo/scatterplot": "^0.87.0",
    "@nx/devkit": "20.0.6",
    "@nx/next": "20.0.6",
    "@sentry/nextjs": "^8.33.0",
    "@sentry/profiling-node": "^1.3.5",
    "@sentry/webpack-plugin": "~1.20.1",
    "@storybook/addon-interactions": "^8.2.8",
    "@testing-library/jest-dom": "^6.4.2",
    "@trumbitta/nx-plugin-unused-deps": "^1.12.1",
    "@types/lodash.debounce": "^4.0.9",
    "@types/react-mentions": "^4.1.13",
    "@vitejs/plugin-react": "4.2.1",
    "@vitest/coverage-v8": "^1.5.0",
    "dayjs": "^1.11.11",
    "event-source-polyfill": "^1.0.31",
    "i18next": "^23.11.2",
    "lodash.debounce": "^4.0.8",
    "next": "14.2.3",
    "next-auth": "^4.24.7",
    "next-i18next": "^14.0.3",
    "next-logger": "^3.0.2",
    "nx": "20.0.6",
    "pino": "^9.4.0",
    "pino-pretty": "^11.2.2",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-dropzone": "^14.2.3",
    "react-hook-form": "^7.51.3",
    "react-i18next": "^13.5.0",
    "react-markdown": "^9.0.1",
    "react-mentions": "^4.4.10",
    "rehype-raw": "^7.0.0",
    "remark-gfm": "^4.0.0",
    "remark-toc": "^9.0.0",
    "storybook": "^8.2.8",
    "suneditor": "^2.46.2",
    "suneditor-react": "^3.6.1",
    "swr": "^2.2.5",
    "tslib": "^2.6.2",
    "typescript": "~5.0.4",
    "uuid": "^9.0.1",
    "vite": "^5.2.14",
    "vite-plugin-eslint": "^1.8.1",
    "vite-tsconfig-paths": "^4.3.2",
    "zod": "^3.23.3",
    "zustand": "^4.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.24.4",
    "@babel/preset-react": "^7.24.1",
    "@chromatic-com/storybook": "^1",
    "@emotion/babel-plugin": "11.11.0",
    "@next/bundle-analyzer": "^13.5.6",
    "@nx/cypress": "20.0.6",
    "@nx/eslint": "20.0.6",
    "@nx/eslint-plugin": "20.0.6",
    "@nx/js": "20.0.6",
    "@nx/react": "20.0.6",
    "@nx/storybook": "20.0.6",
    "@nx/vite": "20.0.6",
    "@nx/web": "20.0.6",
    "@nx/workspace": "20.0.6",
    "@storybook/addon-essentials": "8.3.6",
    "@storybook/core-common": "8.0.9",
    "@storybook/core-server": "8.3.6",
    "@storybook/nextjs": "8.0.9",
    "@storybook/react": "8.3.6",
    "@swc-node/register": "1.9.2",
    "@swc/core": "1.5.7",
    "@swc/helpers": "0.5.13",
    "@testing-library/dom": "^9.3.4",
    "@testing-library/react": "15.0.6",
    "@testing-library/react-hooks": "^8.0.1",
    "@testing-library/user-event": "^14.5.2",
    "@types/event-source-polyfill": "^1.0.5",
    "@types/node": "18.16.9",
    "@types/react": "18.3.1",
    "@types/react-dom": "18.3.0",
    "@types/uuid": "^9.0.8",
    "@typescript-eslint/eslint-plugin": "7.18.0",
    "@typescript-eslint/parser": "7.18.0",
    "@vitest/ui": "1.5.0",
    "cypress": "13.15.1",
    "cypress-mochawesome-reporter": "^3.8.2",
    "eslint": "9.13.0",
    "eslint-config-next": "14.2.3",
    "eslint-config-prettier": "9.1.0",
    "eslint-plugin-cypress": "2.15.2",
    "eslint-plugin-import": "2.31.0",
    "eslint-plugin-jsx-a11y": "6.7.1",
    "eslint-plugin-mui-path-imports": "^0.0.15",
    "eslint-plugin-react": "7.32.2",
    "eslint-plugin-react-hooks": "4.6.0",
    "husky": "^8.0.3",
    "jsdom": "22.1.0",
    "license-checker": "^25.0.1",
    "prettier": "^2.8.8",
    "storybook-addon-pseudo-states": "^2.2.1",
    "ts-node": "10.9.1",
    "vite-plugin-dts": "~2.3.0",
    "vitest": "1.5.0"
  },
```

**Comment by gtteamamxx** [comment]
Similar errors.

```
PS C:\source\repos\MyRepo> nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching nx@20.0.6
Fetching nx@20.0.6
Fetching @nrwl/js@20.0.6
Fetching @nrwl/workspace@20.0.6
Unable to fetch migrations for @nrwl/js@20.0.6: Command failed: npm install @nrwl/js@20.0.6
npm error code ETARGET
npm error notarget No matching version found for @nrwl/js@20.0.6.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: C:\Users\User\AppData\Local\npm-cache\_logs\2024-10-29T09_15_40_494Z-debug-0.log
```

**Comment by matthargett** [comment]
Retested with latest 20.0.9:
```
nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching nx@20.0.9
Fetching @nx/linter@20.0.9
Unable to fetch migrations for @nx/linter@20.0.9: Command failed: npm install @nx/linter@20.0.9
npm error code ETARGET
npm error notarget No matching version found for @nx/linter@20.0.9.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: /Users/matt/.npm/_logs/2024-11-06T02_07_53_007Z-debug-0.log
```

If I comment out this line in my package.json:
```
"@nx/linter": "19.8.8",
```

and re-run the migrate command, then it seems to work around the issue.

After running migrate with @nx/linter removed, if I re-add the linter package and manually specify the last published version, things seem to work:
```
                "@nx/linter": "20.0.0-beta.4",
```

Again, it appears that the `@nx/linter` package was mis-published to 20.x. Check out `npm view @nx/linter` output:
```
canary: 20.0.0-canary.20240926-529ab94  previous: 19.8.10
latest: 19.8.4                          pull-request: 0.0.0-pr-27957-a99d5ea
next: 20.0.0-beta.4
```

Latest has not been updated correctly.
