### ISSUE TITLE
External property causing failure in @nx/js:tsc

### ISSUE THREAD

**Issue by janwiebe-glasbergen** [nrwl/nx#28638]
### Current Behavior

When adding libs to the `external` property of the `@nx/js:tsc` the nx build of the project starts throwing errors.

### Expected Behavior

In @nrwl/js@18.3.5 the external property works like expected. In the case of the sample workspace it includes the output of dep-lib into the dist folder of mylib and updates the imports to a relative import. 
When upgrading to @nrwl/js > 19.x or @nx/js it starts to fail.

I installed @nrwl/js@18.3.5 in the sample repo, so you can see the expected behavior.

### GitHub Repo

https://github.com/janwiebe-glasbergen/nx-js-issue

### Steps to Reproduce

To reproduce the issue in a empty repo:
1. Create 2 libs (mylib and dep-lib)
2. Use dep-lib in mylib
3. Add deplib as external to mylib
4. Build mylib and dep-lib with @nx/js:tsc
5. Run `npx nx build mylib`

To reproduce in the test repository:
1. Run `npx nx build mylib`

### Nx Report

Node           : 22.8.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.2

nx                 : 20.0.5
@nx/js             : 20.0.5
@nrwl/js           : 18.3.5
@nx/jest           : 20.0.5
@nx/eslint         : 20.0.5
@nx/workspace      : 20.0.5
@nrwl/workspace    : 18.3.5
@nx/angular        : 20.0.5
@nx/devkit         : 20.0.5
@nrwl/devkit       : 18.3.5
@nx/eslint-plugin  : 20.0.5
@nrwl/tao          : 19.8.6
@nx/web            : 20.0.5
@nx/webpack        : 20.0.5
typescript         : 5.5.4
---------------------------------------

### Failure Logs

nx run mylib:build

Option "external" is deprecated: Make sure all dependencies are buildable by running `nx g @nx/js:setup-build`. This option will be removed in Nx 20.
Compiling TypeScript files for project "mylib"...
error TS6059: File '/nx-test/test2/libs/mylib/src/index.ts' is not under 'rootDir' '.'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
/nx-test/test2/libs/mylib/src/index.ts:1:15 - error TS6059: File '/nx-test/test2/libs/mylib/src/lib/mylib.ts' is not under 'rootDir' '.'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via './lib/mylib' from file '/nx-test/test2/libs/mylib/src/index.ts'
    Root file specified for compilation

1 export * from './lib/mylib';
                ~~~~~~~~~~~~~

Package type is set to "module" but "cjs" format is included. Going to use "esm" format instead. You can change the package type to "commonjs" or remove type in the package.json 
file.
node:internal/fs/cp/cp-sync:56
  fsBinding.cpSyncCheckPaths(src, dest, opts.dereference, opts.recursive);
            ^
Error: Unknown system error 17: Unknown system error 17, lstat 'D:\nx-test\test2\dist\libs\mylib\libs\mylib'
    at cpSyncFn (node:internal/fs/cp/cp-sync:56:13)
    at cpSync (node:fs:3046:3)
    at movePackage (D:\nx-test\test2\node_modules\@nx\js\src\utils\inline.js:159:26)
    at D:\nx-test\test2\node_modules\@nx\js\src\executors\tsc\tsc.impl.js:71:53
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async D:\nx-test\test2\node_modules\@nx\js\src\utils\typescript\compile-typescript-files.js:35:17 {
  errno: 17,
  code: 'Unknown system error 17',
  syscall: 'lstat',
  path: 'D:\\nx-test\\test2\\dist\\libs\\mylib\\libs\\mylib'
}
Node.js v22.8.0

### Package Manager Version

_No response_

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by janwiebe-glasbergen** [comment]
Issue still occurs in `@nx/js@20.8.0` and `@nx/js@21.0.0-beta.7`

**Comment by cpanten** [comment]
Is there any plan to fix this issue?

**Comment by leosvelperez** [comment]
Thanks for reporting this!

There are no plans to fix this issue. Inlining dependencies was always an experimental feature and had many issues. The feature was deprecated for a long time and finally removed in Nx v22.
