### ISSUE TITLE
unable to add any module such as @nx/react @nx/rspack

### ISSUE THREAD

**Issue by marianzburlea** [nrwl/nx#28652]
### Current Behavior

```
$ yarn create-nx-workspace wow-ui --preset=ts
yarn run v1.22.22
error Couldn't find a package.json file in "/Users/marianzburlea/fun/test"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/fun/test ⌚ 16:50:52
$ yarn create nx-workspace wow-ui --preset=ts
yarn create v1.22.22
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "create-remix > @remix-run/dev > @remix-run/server-runtime@1.8.2" has unmet peer dependency "react@>=16.8".
warning "create-remix > @remix-run/dev > @remix-run/server-runtime@1.8.2" has unmet peer dependency "react-dom@>=16.8".
warning "create-remix > @remix-run/dev > @remix-run/server-runtime > react-router-dom@6.3.0" has unmet peer dependency "react@>=16.8".
warning "create-remix > @remix-run/dev > @remix-run/server-runtime > react-router-dom@6.3.0" has unmet peer dependency "react-dom@>=16.8".
warning "create-remix > @remix-run/dev > @remix-run/server-runtime > react-router-dom > react-router@6.3.0" has unmet peer dependency "react@>=16.8".
[4/4] 🔨  Building fresh packages...
success Installed "create-nx-workspace@20.0.6" with binaries:
      - create-nx-workspace

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Would you like to use Prettier for code formatting? · Yes
✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · skip

 NX   Creating your v20.0.6 workspace.

✔ Installing dependencies with yarn
✔ Successfully created the workspace: wow-ui.

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


 NX   First time using Nx? Check out this interactive Nx tutorial.

https://nx.dev/getting-started/tutorials/integrated-repo-tutorial

✨  Done in 41.08s.

~/fun/test ⌚ 16:51:42
$ ls
deno2               test-accordion.html wow-ui

~/fun/test ⌚ 16:51:48
$ cd wow-ui

~/fun/test/wow-ui on  main ⌚ 16:51:52
$ nx add @nx/rspack

✔ Installing @nx/rspack@20.0.6...
yarn run v1.22.22
$ /Users/marianzburlea/fun/test/wow-ui/node_modules/.bin/nx g @nx/rspack:init --keepExistingVersions --updatePackageScripts

 NX  Generating @nx/rspack:init


 NX   The "@nx/rspack" plugin doesn't yet support the existing TypeScript setup

We're working hard to support the existing TypeScript setup with the "@nx/rspack" plugin. We'll soon release a new version of Nx with support for it.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
✖ Initializing @nx/rspack...

Error: Command failed: yarn nx g @nx/rspack:init --keepExistingVersions --updatePackageScripts
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at runNxSync (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/utils/child-process.js:28:34)
    at initializePlugin (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/add.js:113:39)
    at async /Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/add.js:27:9
    at async handleErrors (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/utils/handle-errors.js:9:24)
    at async Object.handler (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/command-object.js:25:22)

 NX   Failed to initialize @nx/rspack. Please check the error above for more details.


~/fun/test/wow-ui on  main! ⌚ 16:52:16
$ nx add @nx/react

✔ Installing @nx/react@20.0.6...
yarn run v1.22.22
$ /Users/marianzburlea/fun/test/wow-ui/node_modules/.bin/nx g @nx/react:init --keepExistingVersions --updatePackageScripts

 NX  Generating @nx/react:init


 NX   The "@nx/react" plugin doesn't yet support the existing TypeScript setup

We're working hard to support the existing TypeScript setup with the "@nx/react" plugin. We'll soon release a new version of Nx with support for it.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
✖ Initializing @nx/react...

Error: Command failed: yarn nx g @nx/react:init --keepExistingVersions --updatePackageScripts
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at runNxSync (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/utils/child-process.js:28:34)
    at initializePlugin (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/add.js:113:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/add.js:27:9
    at async handleErrors (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/utils/handle-errors.js:9:24)
    at async Object.handler (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/command-object.js:25:22)

 NX   Failed to initialize @nx/react. Please check the error above for more details.
```

### Expected Behavior

to add the nx react or rspack

### Steps to Reproduce

1. generate a fresh workspace
2. run `nx add @nx/react` or `nx add @nx/rspack`

### Nx Report

```
$ yarn create-nx-workspace wow-ui --preset=ts
yarn run v1.22.22
error Couldn't find a package.json file in "/Users/marianzburlea/fun/test"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/fun/test ⌚ 16:50:52
$ yarn create nx-workspace wow-ui --preset=ts
yarn create v1.22.22
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "create-remix > @remix-run/dev > @remix-run/server-runtime@1.8.2" has unmet peer dependency "react@>=16.8".
warning "create-remix > @remix-run/dev > @remix-run/server-runtime@1.8.2" has unmet peer dependency "react-dom@>=16.8".
warning "create-remix > @remix-run/dev > @remix-run/server-runtime > react-router-dom@6.3.0" has unmet peer dependency "react@>=16.8".
warning "create-remix > @remix-run/dev > @remix-run/server-runtime > react-router-dom@6.3.0" has unmet peer dependency "react-dom@>=16.8".
warning "create-remix > @remix-run/dev > @remix-run/server-runtime > react-router-dom > react-router@6.3.0" has unmet peer dependency "react@>=16.8".
[4/4] 🔨  Building fresh packages...
success Installed "create-nx-workspace@20.0.6" with binaries:
      - create-nx-workspace

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Would you like to use Prettier for code formatting? · Yes
✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · skip

 NX   Creating your v20.0.6 workspace.

✔ Installing dependencies with yarn
✔ Successfully created the workspace: wow-ui.

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


 NX   First time using Nx? Check out this interactive Nx tutorial.

https://nx.dev/getting-started/tutorials/integrated-repo-tutorial

✨  Done in 41.08s.

~/fun/test ⌚ 16:51:42
$ ls
deno2               test-accordion.html wow-ui

~/fun/test ⌚ 16:51:48
$ cd wow-ui

~/fun/test/wow-ui on  main ⌚ 16:51:52
$ nx add @nx/rspack

✔ Installing @nx/rspack@20.0.6...
yarn run v1.22.22
$ /Users/marianzburlea/fun/test/wow-ui/node_modules/.bin/nx g @nx/rspack:init --keepExistingVersions --updatePackageScripts

 NX  Generating @nx/rspack:init


 NX   The "@nx/rspack" plugin doesn't yet support the existing TypeScript setup

We're working hard to support the existing TypeScript setup with the "@nx/rspack" plugin. We'll soon release a new version of Nx with support for it.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
✖ Initializing @nx/rspack...

Error: Command failed: yarn nx g @nx/rspack:init --keepExistingVersions --updatePackageScripts
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at runNxSync (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/utils/child-process.js:28:34)
    at initializePlugin (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/add.js:113:39)
    at async /Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/add.js:27:9
    at async handleErrors (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/utils/handle-errors.js:9:24)
    at async Object.handler (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/command-object.js:25:22)

 NX   Failed to initialize @nx/rspack. Please check the error above for more details.


~/fun/test/wow-ui on  main! ⌚ 16:52:16
$ nx add @nx/react

✔ Installing @nx/react@20.0.6...
yarn run v1.22.22
$ /Users/marianzburlea/fun/test/wow-ui/node_modules/.bin/nx g @nx/react:init --keepExistingVersions --updatePackageScripts

 NX  Generating @nx/react:init


 NX   The "@nx/react" plugin doesn't yet support the existing TypeScript setup

We're working hard to support the existing TypeScript setup with the "@nx/react" plugin. We'll soon release a new version of Nx with support for it.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
✖ Initializing @nx/react...

Error: Command failed: yarn nx g @nx/react:init --keepExistingVersions --updatePackageScripts
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at runNxSync (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/utils/child-process.js:28:34)
    at initializePlugin (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/add.js:113:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/add.js:27:9
    at async handleErrors (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/utils/handle-errors.js:9:24)
    at async Object.handler (/Users/marianzburlea/fun/test/wow-ui/node_modules/nx/src/command-line/add/command-object.js:25:22)

 NX   Failed to initialize @nx/react. Please check the error above for more details.
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ShaunKT** [comment]
Getting the same error.

**Comment by wjxalexander** [comment]
Getting the same error.

**Comment by Coly010** [comment]
This is known and expected as we work towards Plugin support for Typescript Project References support.

In the meantime, use `--preset=apps` as a workaround instead of `--preset=ts`.

**Comment by leosvelperez** [comment]
This was already fixed by https://github.com/nrwl/nx/pull/28808. Please update to the latest version of Nx to get the fix.
