### ISSUE TITLE
migration from 8.12.9 -> latest fails

### ISSUE THREAD

**Issue by danzrou** [nrwl/nx#2865]
## Expected Behavior

Migration should finish successfully

## Current Behavior

Migration fails

## Failure Information (for bugs)

I have tried the following as well before migrating as saw in other issues:
1. Install latest workspace
2. Install latest `@nrwl/tao`

Neither of them helped.

Logs:

```shell
The migrate command failed. Try the following to migrate your workspace:
> npm install --save-dev @nrwl/workspace@latest
> nx migrate @nrwl/workspace@latest --from="@nrwl/workspace@9.2.2"
This will use the newest version of the migrate functionality, which might have your issue resolved.
----------------------------------------------------------------------------------------------------
Command failed: npm install @angular/cli@~9.1.0 --prefix=C:\Users\danro\AppData\Local\Temp\tmp-19360p9C3bSW3Bira
npm ERR! Unexpected end of JSON input while parsing near '...Cg6Scp/x4zMvdHoOTsy+5'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\danro\AppData\Roaming\npm-cache\_logs\2020-04-16T09_53_46_116Z-debug.log

D:\Angular\ClientCore\node_modules\yargs\yargs.js:1109
      else throw err
           ^

Error: Command failed: .\node_modules\.bin\tao migrate @nrwl/workspace@latest --from=@nrwl/workspace@8.12.9
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.exports.commandsObject.yargs.usage.command.command.command.command.command.command.command.command.command.command.command.command.command.command.command.alias.command.command.command [as handler] (D:\Angular\ClientCore\node_modules\@nr
wl\workspace\src\command-line\nx-commands.js:76:21)
    at Object.runCommand (D:\Angular\ClientCore\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (D:\Angular\ClientCore\node_modules\yargs\yargs.js:1022:30)
    at Object.get [as argv] (D:\Angular\ClientCore\node_modules\yargs\yargs.js:965:21)
    at Object.initLocal (D:\Angular\ClientCore\node_modules\@nrwl\cli\lib\init-local.js:20:79)
    at Object.<anonymous> (D:\Angular\ClientCore\node_modules\@nrwl\cli\bin\nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)


```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

`nx migrate @nrwl/workspace@latest --from="@nrwl/workspace@8.12.9"`

**Comment by danzrou** [comment]
Well, after clearing npm cache and several retries, it sorted out. Seems like npm had some issues today.
Closing
