### ISSUE TITLE
SqliteFailure Error "DatabaseBusy" running `nx run-many --target build`

### ISSUE THREAD

**Issue by cpierceworld** [nrwl/nx#28665]
### Current Behavior

After upgrading from Nx "18.3.5" to "20.0.6", my Jenkins build (running in docker on linux) started to fail running `nx run-many --target build` with a Sqlite **DatabaseBusy** error:

`Unable to set journal_mode: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))`

More specifically, the Jenkins build runs 3 commands in a row, the 3rd being `nx run-many --target build` which fails.

NOTE: I have `"useLegacyCache": true` in my "nx.conf" file, if that matters.

### Expected Behavior

I expect it to work the way Nx 18.3.5 worked, i.e. no error from  `nx run-many --target build`, 

### Steps to Reproduce

I have a docker instance with Jenkins, runs runs 3 tasks in a row... the last task `npx nx run-many -t build` gives the Sqlite error.

```
npx nx show projects --type lib --affected --base=6541ce36aee67873fcf457302a367368aed8678e --head=HEAD
npx nx release patch --skip-publish --projects=project-one,project-two,project-three,project-four,project-five,project-six
npx nx run-many -t build --configuration=production --projects=project-one,project-two,project-three,project-four,project-five,project-six
```
The first 2 commands works, the last gives:
```
Error: Unable to set journal_mode: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
10:12:36      at /jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:11:93
10:12:36      at getEntryOrSet (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:19:17)
10:12:36      at getDbConnection (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:11:24)
10:12:36      at getTaskDetails (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/hasher/hash-task.js:19:84)
10:12:36      at invokeTasksRunner (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:367:56)
10:12:36      at runCommandForTasks (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:117:31)
10:12:36      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:12:36      at async /jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:105:29
10:12:36      at async handleErrors (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/handle-errors.js:9:24)
10:12:36      at async runCommand (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:104:20)
```

### Nx Report

Node           : 18.19.0
10:26:42  OS             : linux-x64
10:26:42  Native Target  : x86_64-linux
10:26:42  npm            : 10.2.3
10:26:42  
10:26:42  nx                 : 20.0.6
10:26:42  @nx/js             : 20.0.6
10:26:42  @nx/jest           : 20.0.6
10:26:42  @nx/eslint         : 20.0.6
10:26:42  @nx/workspace      : 20.0.6
10:26:42  @nx/angular        : 20.0.6
10:26:42  @nx/devkit         : 20.0.6
10:26:42  @nx/eslint-plugin  : 20.0.6
10:26:42  @nx/web            : 20.0.6
10:26:42  @nx/webpack        : 20.0.6
10:26:42  typescript         : 5.4.5

### Failure Logs

Error: Unable to set journal_mode: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
10:12:36      at /jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:11:93
10:12:36      at getEntryOrSet (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:19:17)
10:12:36      at getDbConnection (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:11:24)
10:12:36      at getTaskDetails (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/hasher/hash-task.js:19:84)
10:12:36      at invokeTasksRunner (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:367:56)
10:12:36      at runCommandForTasks (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:117:31)
10:12:36      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:12:36      at async /jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:105:29
10:12:36      at async handleErrors (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/handle-errors.js:9:24)
10:12:36      at async runCommand (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:104:20)

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Cammisuli** [comment]
Can you try and see if things are fixed with this version:
`0.0.0-pr-28667-e5533b1`

**Comment by Cammisuli** [comment]
Can you try running with this version:
```
0.0.0-pr-28667-309c668
```

But please set `NX_NATIVE_LOGGING=nx::native:db` in the env so that we can see more logs on why its hanging. This might still hang for you, but at least this version will give us a reason why. Thank you!

**Comment by cpierceworld** [comment]
That last PR, `0.0.0-pr-28667-6ebc1cd` is working for me.

**Comment by vincentpalita-whoz** [comment]
Hello! @Cammisuli I tried with 0.0.0-pr-28667-6ebc1cd and it is working aswell. Just noticed that my parallel tasks take longer to run (30 mins instead of 20) when cache is empty.
When cache is ready, it runs as usual.

**Comment by Cammisuli** [comment]
@vincentpalita-whoz im going to be tackling performance next. But I suspect that you have multiple nx commands running in parallel?

**Comment by vincentpalita-whoz** [comment]
@Cammisuli yes we do, full lint and full test of affected libraries at the same time. Maybe this is a bad practice?

**Comment by Cammisuli** [comment]
@vincentpalita-whoz does `nx run-many -t "test,lint" --parallel ${number}` not work well for you?

**Comment by vincentpalita-whoz** [comment]
@Cammisuli : it took almost the same time (30 mins) than running in two different jobs.
But did you mean to try without the fix?

**Comment by justinhandley** [comment]
Just reporting that I also had this error, installing that branch also fixed it for me - hopefully it will become a major patch at some point soon.
