### ISSUE TITLE
`nx g convert-to-monorepo` is not working properly and needs too many manual adjustments

### ISSUE THREAD

**Issue by kasir-barati** [nrwl/nx#28683]
### Current Behavior

I decided to convert my standalone repo to a monorepo as it is explaned here: https://nx.dev/recipes/tips-n-tricks/standalone-to-monorepo

And here is what happend: 

1. `npx create-nx-workspace@latest --preset=react-standalone --name=react --bundler=vite --pm=pnpm`.
2. ![second step screenshot](https://github.com/user-attachments/assets/e3086471-8620-4144-960f-8e52988c7fed)
3. `nx serve` works.
4. `nx g convert-to-monorepo`.
5. `nx serve` :x:! It stops working.

```shell
NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.
```

So then I tried `--verbose` flag:

```shell
NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/eslint/plugin plugin.
    - eslint.config.js: baseConfig is not iterable
      TypeError: baseConfig is not iterable
          at Object.<anonymous> (/tmp/react/eslint.config.js:4:6)
          at Module._compile (node:internal/modules/cjs/loader:1467:14)
          at Module._extensions..js (node:internal/modules/cjs/loader:1551:10)
          at Module.load (node:internal/modules/cjs/loader:1282:32)
          at Module._load (node:internal/modules/cjs/loader:1098:12)
          at TracingChannel.traceSync (node:diagnostics_channel:315:14)
          at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
          at cjsLoader (node:internal/modules/esm/translators:318:5)
          at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:258:7)
          at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
```

And of course in our root `eslint.config.js` we are trying to import `eslint.config.js` again:

![Self imporing](https://github.com/user-attachments/assets/9341269b-3e98-48a2-b76f-1d884e730436)

So I tried to revert changes: 

```js
const nx = require('@nx/eslint-plugin');

module.exports = [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
```

And tried `nx serve --verbose` yet again:

```shell
NX   Cannot find configuration for task @react/source:serve

Error: Cannot find configuration for task @react/source:serve
    at ProcessTasks.createTask (/tmp/react/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_7rv6t3h3zgijb5zl54qohu6cea/node_modules/nx/src/tasks-runner/create-task-graph.js:156:19)
    at ProcessTasks.processTasks (/tmp/react/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_7rv6t3h3zgijb5zl54qohu6cea/node_modules/nx/src/tasks-runner/create-task-graph.js:33:39)
    at createTaskGraph (/tmp/react/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_7rv6t3h3zgijb5zl54qohu6cea/node_modules/nx/src/tasks-runner/create-task-graph.js:214:21)
    at createTaskGraphAndRunValidations (/tmp/react/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_7rv6t3h3zgijb5zl54qohu6cea/node_modules/nx/src/tasks-runner/run-command.js:78:63)
    at ensureWorkspaceIsInSyncAndGetGraphs (/tmp/react/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_7rv6t3h3zgijb5zl54qohu6cea/node_modules/nx/src/tasks-runner/run-command.js:132:21)
    at runCommandForTasks (/tmp/react/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_7rv6t3h3zgijb5zl54qohu6cea/node_modules/nx/src/tasks-runner/run-command.js:114:47)
    at /tmp/react/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_7rv6t3h3zgijb5zl54qohu6cea/node_modules/nx/src/tasks-runner/run-command.js:105:35
    at handleErrors (/tmp/react/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_7rv6t3h3zgijb5zl54qohu6cea/node_modules/nx/src/utils/handle-errors.js:9:30)
    at runCommand (/tmp/react/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_7rv6t3h3zgijb5zl54qohu6cea/node_modules/nx/src/tasks-runner/run-command.js:104:59)
    at Object.runOne (/tmp/react/node_modules/.pnpm/nx@20.0.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_7rv6t3h3zgijb5zl54qohu6cea/node_modules/nx/src/command-line/run/run-one.js:48:59)
```

So there are several issues here:

1. Why this `eslint.config.js` is not a typescript file by default?
    - Related kinda to this too: https://github.com/nrwl/nx/issues/28448
2. Vite version 6 will remove CJS all together. So any plan on fixing it? Right now I added `"type": "module"` manually to my root `package.json` (this was before converting it to a monorepo using this generator).

   ```shell
   > nx run react:serve

   > vite serve

   The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

     VITE v5.4.10  ready in 386 ms

     ➜  Local:   http://localhost:4200/
     ➜  press h + enter to show help
   ```

### Expected Behavior

Just serve it!

### Steps to Reproduce

I explained it already.

### Nx Report

 NX   Report complete - copy this into the issue template

Node           : 22.4.0
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 9.6.0

nx (global)        : 20.0.6
nx                 : 20.0.6
@nx/js             : 20.0.6
@nx/eslint         : 20.0.6
@nx/workspace      : 20.0.6
@nx/eslint-plugin  : 20.0.6
@nx/react          : 20.0.6
@nx/vite           : 20.0.6
@nx/web            : 20.0.6
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin

### Failure Logs

Added already

### Package Manager Version

9.6.0

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by kasir-barati** [comment]
But the `nx serve react` works perfectly fine. I think it is thanks to the wrong value for `"name": "@react/source"` inside the `package.json`.

**Comment by kasir-barati** [comment]
Another thing, if I change the `eslint.config.js` to a ts file and ran `nx g @nx/nest:app apps/nest` it will recreate the `eslint.config.js` again which is weird since it should be able to see that I have one already.

**Comment by kasir-barati** [comment]
Then we have this issue as well with Vite and Nx: https://github.com/nrwl/nx/issues/19618

**Comment by Applicafroguy** [comment]
@kasir-barati  Did you find the solution, I tried to convert to monorepo but I get the same issues
