### ISSUE TITLE
Nx workspace with react router v7 makes all nx command to be stuck

### ISSUE THREAD

**Issue by allan-from-meiro** [nrwl/nx#28689]
### Current Behavior

I added a react-router v7 pre-release to my NX repo for testing. I simply [initialized the project with their template](https://reactrouter.com/dev/guides/start/installation#starter-templates) and added a project.json file with a `serve` target using the `"executor": "@nx/workspace:run-commands" and command of `react-router dev`.

nx@20.0.5 version.

Running the project from within the project root running `pnpm dev` that executes the same command works, but it shows this message:
"WARNING: There was an error creating glob patterns, returning an empty array
[readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data."

But running it via the executed results in a 10-minute wait and ends with an error shown in the failure log section.
In fact, running any NX command results in this, not just commands related to this project. But running other projects or something like `nx graph` is the same.

### Expected Behavior

I would expect the command to be executed, and run the project.

### Steps to Reproduce

1.Create a NX workspace
2. Add a react-router pre release (v7) project via the [template](https://reactrouter.com/dev/guides/start/installation#starter-templates)
3. Setup project.json with the serve command of `react-router dev`
4. run `pnpm nx serve {project-name}`

### Nx Report

Nx report does not work as it result in the @nx/vite/plugin error.

### Failure Logs

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/vite/plugin plugin.
    - Plugin worker @nx/vite/plugin exited unexpectedly with code 0
      Error: Plugin worker @nx/vite/plugin exited unexpectedly with code 0
          at ChildProcess.<anonymous> (/home/allank/Documents/meiro/raptor/node_modules/.pnpm/nx@20.0.5_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_c6desoc26z53updun3ssfp6oiu/node_modules/nx/src/project-graph/plugins/isolation/plugin-pool.js:171:37)
          at ChildProcess.emit (node:events:519:28)
          at ChildProcess._handle.onexit (node:internal/child_process:293:12)
    The "@nx/vite/plugin" plugin threw an error while creating dependencies: @nx/vite/plugin timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
    Error: @nx/vite/plugin timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
        at Timeout.<anonymous> (/home/allank/Documents/meiro/raptor/node_modules/.pnpm/nx@20.0.5_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_c6desoc26z53updun3ssfp6oiu/node_modules/nx/src/project-graph/plugins/isolation/plugin-pool.js:196:21)
        at listOnTimeout (node:internal/timers:594:17)
        at process.processTimers (node:internal/timers:529:7)

### Package Manager Version

9.12.1

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by charles-zablit** [comment]
Hi, did you ever fix this? I'm having the same issue with the release of react-router-v7.

**Comment by aruke** [comment]
I have the same problem here.
I'm wondering if the `@nx/remix` will go away and if there will be a new plugin for seamless integration of react-router in NX workspace.

**Comment by markusbrite** [comment]
Any updates here?

**Comment by komichar** [comment]
Any updates?
