### ISSUE TITLE
ngrx generator fails -  NX   Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#28718]
### Current Behavior

SUBJECT: ngrx generator fails -  NX   Cannot read properties of null (reading 'length')

execute the following generator from terminal

`NX_DAEMON=false /Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:ngrx-root-store  --name=store --directory=apps/admin --addDevTools=true --minimal=false --project=admin --facade=true --dry-run`

emits error
`NX   Cannot read properties of null (reading 'length')`

no getting around this

### Expected Behavior

should at least generate dry-run ngrx config

### GitHub Repo

https://github.com/nhhockeyplayer/meanstacknh

### Steps to Reproduce

1.

### Nx Report

nx report

 NX   Report complete - copy this into the issue template

Node           : 22.9.0
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.9.0

nx (global)        : 20.0.0
nx                 : 20.0.6
@nx/js             : 20.0.6
@nx/jest           : 20.0.6
@nx/eslint         : 20.0.6
@nx/workspace      : 20.0.6
@nx/angular        : 20.0.6
@nx/cypress        : 20.0.6
@nx/devkit         : 20.0.6
@nx/esbuild        : 20.0.6
@nx/eslint-plugin  : 20.0.6
@nx/express        : 20.0.6
@nx/nest           : 20.0.6
@nx/node           : 20.0.6
@nx/web            : 20.0.6
@nx/webpack        : 20.0.6
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc                    : 1.1.26
@fortawesome/angular-fontawesome      : 0.15.0
@ionic/angular                        : 6.7.5
@jsverse/transloco                    : 7.5.0
@ngrx/component                       : 18.0.2
@ngrx/component-store                 : 18.0.2
@ngrx/effects                         : 18.0.2
@ngrx/entity                          : 18.0.2
@ngrx/operators                       : 18.0.2
@ngrx/router-store                    : 18.0.2
@ngrx/schematics                      : 18.0.2
@ngrx/store                           : 18.0.2
@ngrx/store-devtools                  : 18.0.2
angular-builder-custom-terser-options : 1.0.1
apollo-angular                        : 7.2.1

### Failure Logs

NX   Cannot read properties of null (reading 'length')

### Package Manager Version

npm --version 10.9.0

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

thanks for any workaround

AND AN AWESOME PRODUCT

**Comment by nhhockeyplayer** [comment]
okay
so this occurs on a project=admin
which is just a plain workspace app converted to ionic app using @nx-extensions

I issued this command on a MFE microfront end HOST
and it worked

so this bug has to do with a plain app thats converted to ionic using nx-extensions

just an FYI

```
/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:ngrx-root-store  --name=store --directory=apps/admin --addDevTools=true --minimal=false --project=ui-host --facade=true --dry-run


 NX  Generating @nx/angular:ngrx-root-store

UPDATE apps/ui-host/src/app/app.module.ts
CREATE apps/ui-host/src/app/apps/admin/store.actions.ts
CREATE apps/ui-host/src/app/apps/admin/store.effects.spec.ts
CREATE apps/ui-host/src/app/apps/admin/store.effects.ts
CREATE apps/ui-host/src/app/apps/admin/store.facade.spec.ts
CREATE apps/ui-host/src/app/apps/admin/store.facade.ts
CREATE apps/ui-host/src/app/apps/admin/store.models.ts
CREATE apps/ui-host/src/app/apps/admin/store.reducer.spec.ts
CREATE apps/ui-host/src/app/apps/admin/store.reducer.ts
CREATE apps/ui-host/src/app/apps/admin/store.selectors.spec.ts
CREATE apps/ui-host/src/app/apps/admin/store.selectors.ts

NOTE: The "dryRun" flag means no changes were made
```.

**Comment by nhhockeyplayer** [comment]
here is the good command that works on a HOST

so I will leave this OPEN should an nx elite engineer choose to reproduce and investigate either issue

- path fault tolerance
- plain app converted to ionic

```
/Users/meanstack02/nhhockeyplayer/node_modules/.bin/nx g @nx/angular:ngrx-root-store  --name=store --addDevTools=true --minimal=false --project=ui-host --facade=true --dry-run 


 NX  Generating @nx/angular:ngrx-root-store

UPDATE apps/ui-host/src/app/app.module.ts
CREATE apps/ui-host/src/app/+state/store.actions.ts
CREATE apps/ui-host/src/app/+state/store.effects.spec.ts
CREATE apps/ui-host/src/app/+state/store.effects.ts
CREATE apps/ui-host/src/app/+state/store.facade.spec.ts
CREATE apps/ui-host/src/app/+state/store.facade.ts
CREATE apps/ui-host/src/app/+state/store.models.ts
CREATE apps/ui-host/src/app/+state/store.reducer.spec.ts
CREATE apps/ui-host/src/app/+state/store.reducer.ts
CREATE apps/ui-host/src/app/+state/store.selectors.spec.ts
CREATE apps/ui-host/src/app/+state/store.selectors.ts
```

**Comment by nhhockeyplayer** [comment]
nx generate ngrx-root-store --dry-run

```
 NX  Generating @nx/angular:ngrx-root-store

✔ What app would you like to generate a NgRx configuration for? · host
✔ Would you like to use a Facade with your NgRx state? (y/N) · false

 NX   Cannot read properties of null (reading 'length')

TypeError: Cannot read properties of null (reading 'length')
    at createSourceFile2 (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32816:52)
    at parseSourceFileWorker (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32690:24)
    at Object.parseSourceFile (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32514:20)
    at Object.createSourceFile (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32348:21)
    at addImportsToModule (/Users/meanstack02/meanstacknh/node_modules/@nx/angular/src/generators/ngrx-root-store/lib/add-imports.js:65:31)
    at ngrxRootStoreGenerator (/Users/meanstack02/meanstacknh/node_modules/@nx/angular/src/generators/ngrx-root-store/ngrx-root-store.js:12:38)
    at /Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/generate/generate.js:240:32
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at handleErrors (/Users/meanstack02/meanstacknh/node_modules/nx/src/utils/handle-errors.js:8:24)
    at Object.handler (/Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/generate/command-object.js:13:22)
```

**Comment by nhhockeyplayer** [comment]
nx g @nx/angular:ngrx-root-store --dry-run

```
 NX  Generating @nx/angular:ngrx-root-store

✔ What app would you like to generate a NgRx configuration for? · host
✔ Would you like to use a Facade with your NgRx state? (y/N) · false

 NX   Cannot read properties of null (reading 'length')

TypeError: Cannot read properties of null (reading 'length')
    at createSourceFile2 (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32816:52)
    at parseSourceFileWorker (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32690:24)
    at Object.parseSourceFile (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32514:20)
    at Object.createSourceFile (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32348:21)
    at addImportsToModule (/Users/meanstack02/meanstacknh/node_modules/@nx/angular/src/generators/ngrx-root-store/lib/add-imports.js:65:31)
    at ngrxRootStoreGenerator (/Users/meanstack02/meanstacknh/node_modules/@nx/angular/src/generators/ngrx-root-store/ngrx-root-store.js:12:38)
    at /Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/generate/generate.js:240:32
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleErrors (/Users/meanstack02/meanstacknh/node_modules/nx/src/utils/handle-errors.js:8:24)
    at async Object.handler (/Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/generate/command-object.js:13:22)

```

**Comment by Coly010** [comment]
The errors that you are seeing would indicate to me that the `ngrx-root-store` generator is having a hard time inferring the parent path for adding the providers.

The logic for doing this is:

```ts
const appConfigPath = joinPathFragments(
    project.sourceRoot,
    'app/app.config.ts'
  );
  const appMainPath =
    project.targets.build.options.main ?? project.targets.build.options.browser;

  /** If NgModule App
   * -> Use App Module
   * If Standalone
   * -> Check Config File exists (v16+)
   * --> If so, use that
   * --> If not, use main.ts
   */
  const ngModulePath = joinPathFragments(
    project.sourceRoot,
    'app/app.module.ts'
  );

/** If NgModule App
   * -> Use App Module
   * If Standalone
   * -> Check Config File exists (v16+)
   * --> If so, use that
   * --> If not, use main.ts
   */
const parent =
    !isStandalone && tree.exists(ngModulePath)
      ? ngModulePath
      : tree.exists(appConfigPath)
      ? appConfigPath
      : appMainPath;
```

Perhaps you can verify that your application is set up as expected - and if not - then it would account for why this generator is failing for you only on specific projects

**Comment by nhhockeyplayer** [comment]
closing as convoluted
to many issues encountered
closing this due to 3rd party lib causing me issues and confusion on non-compliance for esbuild
