### ISSUE TITLE
Web workers do not work in Webpack development server

### ISSUE THREAD

**Issue by edwindwalker** [nrwl/nx#28745]
### Current Behavior

Instantiating a web worker using the latest version of Nx (20.0.7) with Webpack results in the following runtime error:
```
Uncaught SyntaxError: Cannot use 'import.meta' outside a module
    at handleError (http://localhost:4200/vendor.js:39399:58)
    at http://localhost:4200/vendor.js:39418:7
```

I am currently trying to upgrade from Nx 15.0.3. Creating a new workspace with that version does not reproduce this error, but it is reproducible from at least Nx 15.5.3. 

### Expected Behavior

Nx should support web workers in the development environment.

### Steps to Reproduce

1. Create a new React workspace with the following options `npx create-nx-workspace@latest workspace --appName=test --bundler=webpack  --e2eTestRunner=none --nxCloud=skip --preset=react-monorepo --style=@emotion/styled`
2. Create a worker in `/apps/test/src/app/deep-thought.ts`:
```ts
self.onmessage = () => {
  self.postMessage({
    answer: 42,
  });
};
```
3. Import the worker in `/apps/test/src/app/app.tsx`:
```ts
import { useEffect, useState } from 'react';
import NxWelcome from './nx-welcome';

const useWorker = () => {
  const [worker] = useState(
    () => new Worker(new URL('./deep-thought.ts', import.meta.url))
  );
  useEffect(() => {
    return () => worker.terminate();
  }, [worker]);
  worker.postMessage({
    question:
      'The Answer to the Ultimate Question of Life, The Universe, and Everything.',
  });
  worker.onmessage = ({ data: { answer } }) => {
    console.log(answer);
  };
};

export function App() {
  useWorker();
  return <NxWelcome title="test" />;
}

export default App;
```
4. Launch the development server: `npx nx run test:serve`
5. Observe the runtime error

### Nx Report

Node           : 18.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 9.8.1

nx                 : 20.0.6
@nx/js             : 20.0.6
@nx/jest           : 20.0.6
@nx/eslint         : 20.0.6
@nx/workspace      : 20.0.6
@nx/devkit         : 20.0.6
@nx/eslint-plugin  : 20.0.6
@nx/react          : 20.0.6
@nx/web            : 20.0.6
@nx/webpack        : 20.0.6
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The example in the reproduction steps is adapted from Webpack's documentation: https://webpack.js.org/guides/web-workers/. The same code works with Vite out of the box.

**Comment by Coly010** [comment]
@edwindwalker I believe you need to inform webpack that you're using ESM. You can do this simply by creating a package.json if you don't already have one and setting `"type": "module"` in it.
https://webpack.js.org/guides/ecma-script-modules/

**Comment by zoran995** [comment]
@Coly010 Do you have any samples of this working? In my tests, setting `"type": "module"` is not enough and still breaks. You can check the https://github.com/zoran995/webpack-woker-dev.

In some basic tests setting `scriptType: "text/javascript"` in webpack config makes it work but I am not sure if it might break something else. It actually works even if we override it to undefined; it just fails when it is set to `module`.

p.s. it also works when setting the output module, but in that case,e the HMR doesn't work
