### ISSUE TITLE
Running nx build, lint, etc fails with "unable to authenticate"

### ISSUE THREAD

**Issue by DaveMBush** [nrwl/nx#28757]
### Current Behavior

I've created a new workspace using `npx create-nx-workspace --pm pnpm` and I've connected my repo to organization Dave-Bush.

When I commit files, the CI works as expected and shows up in the cloud app.

when I run something simple locally such as `pnpm nx affected:build` I get an "Unable to authenticate" message.

While I would expect this to work without any additional configuration, I've tried passing `--no-cloud` and I've tried adding a PAT.  I still get the same error, even after running `nx reset` 

I also verified the PAT is installed both by trying to re-install it (complains that it already exist) and by inspecting the file it is in.

I also verified that the nxCloudId in nx.json matches what is in the cloud app.

For what it is worth, I'm running in WSL.  I have another project that is working but it has not been converted to use the NX_CLOUD_ACCESS_TOKEN (yet)

Maybe there is some step I missed but I've looked all through the documentation and can't see what it might be.

For a minute there, I thought getting all the NX versions in sync would work, but that didn't help either.  I had to install quite a few packages at the top level to get the versions aligned and what isn't is also not aligned on the repo that is working correctly for me.

I noticed in the report that this was using nx-cloud 16 so I updated it to 19.1.0 which is what my working project is using. NOW, I'm getting "Cannot read properties of undefined (reading 'cacheError')"

So, the first "bug" is that creating a new workspace with the default Angular application doesn't seem to install the right versions of the dependencies, including nx-cloud, and then when I install the most recent version of nx-cloud, things seem to build but then die on the caching

### Expected Behavior

I would expect I could build a new project locally without needing any type of authentication.

### GitHub Repo

https://github.com/DaveMBush/smart-eslint

### Steps to Reproduce

1. Retrieve the repo
2. `pnpm i`
3. `pnpm build`

#### Before upgrading nx-cloud but after updating as many other dependencies as I could

 NX   Report complete - copy this into the issue template

Node           : 20.14.0
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 9.3.0

nx                      : 20.0.7
@nx/js                  : 20.0.7
@nx/jest                : 20.0.7
@nx/linter              : 17.1.2
@nx/eslint              : 20.0.7
@nx/workspace           : 20.0.7
@nx/angular             : 20.0.7
@nx/cypress             : 20.0.7
@nx/devkit              : 20.0.7
@nx/esbuild             : 20.0.7
@nx/eslint-plugin       : 20.0.7
@nrwl/eslint-plugin-nx  : 17.1.2
@nx/nest                : 20.0.7
@nx/next                : 20.0.7
@nx/node                : 20.0.7
@nx/react               : 20.0.7
@nx/web                 : 20.0.7
@nx/webpack             : 20.0.7
nx-cloud                : 16.5.2
typescript              : 5.5.4
---------------------------------------
The following packages should match the installed version of nx
  - @nx/linter@17.1.2
  - @nrwl/eslint-plugin-nx@17.1.2

To fix this, run `nx migrate nx@20.0.7`

#### After upgrading nx-cloud

 NX   Report complete - copy this into the issue template

Node           : 20.14.0
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 9.3.0

nx                      : 20.0.7
@nx/js                  : 20.0.7
@nx/jest                : 20.0.7
@nx/linter              : 17.1.2
@nx/eslint              : 20.0.7
@nx/workspace           : 20.0.7
@nx/angular             : 20.0.7
@nx/cypress             : 20.0.7
@nx/devkit              : 20.0.7
@nx/esbuild             : 20.0.7
@nx/eslint-plugin       : 20.0.7
@nrwl/eslint-plugin-nx  : 17.1.2
@nx/nest                : 20.0.7
@nx/next                : 20.0.7
@nx/node                : 20.0.7
@nx/react               : 20.0.7
@nx/web                 : 20.0.7
@nx/webpack             : 20.0.7
nx-cloud                : 19.1.0
typescript              : 5.5.4
---------------------------------------
The following packages should match the installed version of nx
  - @nx/linter@17.1.2
  - @nrwl/eslint-plugin-nx@17.1.2

To fix this, run `nx migrate nx@20.0.7`

#### Failure log before updating nx-cloud

> @smart-eslint/source@0.0.0 build /home/dave/code/smart-eslint
> nx affected:build "--verbose"

 NX   Affected criteria defaulted to --base=main --head=HEAD

[NX CLOUD] Using light client

 NX   Unable to authenticate. Either define accessToken in nx.json or set the NX_CLOUD_ACCESS_TOKEN env variable.

Error: Unable to authenticate. Either define accessToken in nx.json or set the NX_CLOUD_ACCESS_TOKEN env variable.
    at createApiAxiosInstance (/home/dave/code/node_modules/.pnpm/nx-cloud@16.5.2/node_modules/nx-cloud/lib/utilities/axios.js:31:15)
    at /home/dave/code/node_modules/.pnpm/nx-cloud@16.5.2/node_modules/nx-cloud/lib/light-client/update-manager.js:23:62
    at Generator.next (<anonymous>)
    at /home/dave/code/node_modules/.pnpm/nx-cloud@16.5.2/node_modules/nx-cloud/lib/light-client/update-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dave/code/node_modules/.pnpm/nx-cloud@16.5.2/node_modules/nx-cloud/lib/light-client/update-manager.js:4:12)
    at verifyOrUpdateCloudBundle (/home/dave/code/node_modules/.pnpm/nx-cloud@16.5.2/node_modules/nx-cloud/lib/light-client/update-manager.js:19:12)
    at /home/dave/code/node_modules/.pnpm/nx-cloud@16.5.2/node_modules/nx-cloud/lib/light-client/nx-cloud-tasks-runner-shell.js:20:89
    at Generator.next (<anonymous>)
    at /home/dave/code/node_modules/.pnpm/nx-cloud@16.5.2/node_modules/nx-cloud/lib/light-client/nx-cloud-tasks-runner-shell.js:8:71

 ELIFECYCLE  Command failed with exit code 1.

#### Failure log after updating nx-cloud

> @smart-eslint/source@0.0.0 build /home/dave/code/smart-eslint
> nx affected:build "--verbose"

 NX   Affected criteria defaulted to --base=main --head=HEAD

[NX CLOUD] Using light client
[NX CLOUD] A local bundle currently exists:  {
  version: '2410.25.5.hotfix1',
  fullPath: '/home/dave/code/smart-eslint/node_modules/.cache/nx/cloud/2410.25.5.hotfix1'
}
[NX CLOUD] Last verification was within the past 30 minutes, will not verify this time
[NX CLOUD] Using bundle path:  {
  version: '2410.25.5.hotfix1',
  fullPath: '/home/dave/code/smart-eslint/node_modules/.cache/nx/cloud/2410.25.5.hotfix1'
}

 NX   Running target build for project documentation:

- documentation

[NX CLOUD] Verifying current cloud bundle
[NX CLOUD] A local bundle currently exists:  {
  version: '2410.25.5.hotfix1',
  fullPath: '/home/dave/code/smart-eslint/.nx/cache/cloud/2410.25.5.hotfix1'
}
[NX CLOUD] Last verification was within the past 30 minutes, will not verify this time
[NX CLOUD] Done:  /home/dave/code/smart-eslint/.nx/cache/cloud/2410.25.5.hotfix1

 NX   Successfully ran target build for project documentation

 NX   Storing terminal outputs for documentation:build:production with hash 116684684147691221

[Nx Cloud Debug] Attempting to acquire filesystem lock with path:  /tmp/client-instance-id.lock
[Nx Cloud Debug] Failed to create folder lock at path: /tmp/client-instance-id.lock
[Nx Cloud] Unable to detect a VCS context from the environment.

 NX   RunStart

{
  "meta": {
    "nxCloudVersion": "19.1.0"
  },
  "branch": null,
  "runGroup": "eb09fbbc8451e6498a016a21656657a76ad5598a",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "116684684147691221"
  ],
  "machineInfo": {
    "machineId": "uwc9rM9OgKoP2ZDS47HL9w==",
    "platform": "linux",
    "version": "#1 SMP Fri Mar 29 23:14:13 UTC 2024",
    "cpuCores": 12
  },
  "vcsContext": null,
  "clientInstanceSource": "CLOUD_RUNNER",
  "clientInstanceId": "824e8e65-947e-4887-bd30-8f2a4b3826de"
}

[Nx Cloud] Unable to detect a VCS context from the environment.

 NX   RunStart

{
  "meta": {
    "nxCloudVersion": "19.1.0"
  },
  "branch": null,
  "runGroup": "eb09fbbc8451e6498a016a21656657a76ad5598a",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "116684684147691221"
  ],
  "machineInfo": {
    "machineId": "uwc9rM9OgKoP2ZDS47HL9w==",
    "platform": "linux",
    "version": "#1 SMP Fri Mar 29 23:14:13 UTC 2024",
    "cpuCores": 12
  },
  "vcsContext": null,
  "clientInstanceSource": "CLOUD_RUNNER",
  "clientInstanceId": "824e8e65-947e-4887-bd30-8f2a4b3826de"
}

RunStart duration: 85
RunStart duration: 91
View structured, searchable error logs at https://nx.app/runs/1J6OGMQwbi

 NX   Cannot read properties of undefined (reading 'cacheError')

TypeError: Cannot read properties of undefined (reading 'cacheError')
    at qd.retrieve (/home/dave/code/smart-eslint/.nx/cache/cloud/2410.25.5.hotfix1/index.js:32:3320)
    at DbCache.get (/home/dave/code/smart-eslint/node_modules/.pnpm/nx@20.0.7_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_hxtiu7xekwwx6r2tt5pl3utiee/node_modules/nx/src/tasks-runner/cache.js:63:48)
    at TaskOrchestrator.applyCachedResult (/home/dave/code/smart-eslint/node_modules/.pnpm/nx@20.0.7_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_hxtiu7xekwwx6r2tt5pl3utiee/node_modules/nx/src/tasks-runner/task-orchestrator.js:131:47)
    at /home/dave/code/smart-eslint/node_modules/.pnpm/nx@20.0.7_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_hxtiu7xekwwx6r2tt5pl3utiee/node_modules/nx/src/tasks-runner/task-orchestrator.js:126:70
    at Array.map (<anonymous>)
    at TaskOrchestrator.applyCachedResults (/home/dave/code/smart-eslint/node_modules/.pnpm/nx@20.0.7_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_hxtiu7xekwwx6r2tt5pl3utiee/node_modules/nx/src/tasks-runner/task-orchestrator.js:126:54)
    at TaskOrchestrator.applyFromCacheOrRunTask (/home/dave/code/smart-eslint/node_modules/.pnpm/nx@20.0.7_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_hxtiu7xekwwx6r2tt5pl3utiee/node_modules/nx/src/tasks-runner/task-orchestrator.js:219:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TaskOrchestrator.executeNextBatchOfTasksUsingTaskSchedule (/home/dave/code/smart-eslint/node_modules/.pnpm/nx@20.0.7_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_hxtiu7xekwwx6r2tt5pl3utiee/node_modules/nx/src/tasks-runner/task-orchestrator.js:85:13)
    at async Promise.all (index 0)

 ELIFECYCLE  Command failed with exit code 1.

### Package Manager Version

pnpm 9.3.0

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [x] Other (Please specify) Ubuntu Linux on Windows WSL

**Comment by DaveMBush** [comment]
Let me see if I can TL;DR; this.

1) `npx create-nx-workspace --pm pnpm`
  - For stack select 'none` or 'Angular'
  - Prettier `yes`
  - CI `Do it later`
  - Remote cache `Yes`
  - Github `yes`
2) If you installed angular, connect to NX
3) If you selected `none` create a lib in packages and then connect to NX
4) At this point if you build you will get errors, the next steps will resolve some of them
5) run `nx report` and update your dependencies so that you are using as many NX 20 packages as possible.  I had to specify new packages in package.json to override what got installed by some of the existing dependencies 🤷.  Don't install any nrwl packages.  Make sure you install nx-cloud 19.1.0 to override the nx-cloud 16.x that is being installed on your behave (again 🤷)
6) at this point, you should be able to build or lint or something but you'll get errors  "undefined (reading 'cacheError')" in `/.nx/cache/cloud/2410.25.5.hotfix1/index.js:32:3320` when you run using --verbose.

Setting the environment variable `NX_SKIP_NX_CACHE=true` allows me to build locally, and I could set it for CI, but I've lost the benefit of using NX caching.

**Comment by itspers** [comment]
Had this problem month ago after update, thought its some regular bug, that will be fixed in next update...
But as usual with NX - we need to wait to AGI so it will understand their docs:

https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-converttonxcloudid

> If you are connecting to Nx Cloud with a workspace that is version 19.6 or lower, this command will also install the latest version of the Nx Cloud npm package and add it into your package.json. Only Nx versions 19.7 and higher natively support the nxCloudId property in the nx.json file; for versions 19.6 and lower, the Nx Cloud npm package will be needed to use that property.

What they trying to say is actually **npm uninstall nx-cloud** 🤣

**Comment by DaveMBush** [comment]
@itspers thanks, I'll give it a shot.  But even if that works, there is still an issue.  The schematics shouldn't install NxCloud 16.

**Comment by DaveMBush** [comment]
@itspers as expected, that rolled me back to NxCloud 16. I expect that is because something in the 20 stack is still pointing  at @nx/linter@17.1.2 and @nrwl/eslint-plugin-nx@17.1.2 which I can't uninstall because they are dependencies of things I need 🤷

**Comment by itspers** [comment]
@DaveMBush why would anything require nx-cloud? Double check you package.json. Cause for me, once i did 'npm uninstall', 'nx-cloud' was really removed from node-modules, gone from package.json and build started to work immediatelly. 

And beside nx-cloud problem, you should not have @nx/linter@17.1.2 and @nrwl/eslint-plugin-nx@17.1.2: nrwl was renamed long time ago, and nx/linter is '@nx/eslint' now. You basically should have:

`    "@nx/eslint": "20.0.12",
    "@nx/eslint-plugin": "20.0.12",
` 

in modern workspace

**Comment by DaveMBush** [comment]
I KNOW I shouldn't have @nx/linter and @nrwl/eslint-plugin-nx and therein lies the main problem.  They aren't in MY dependencies.  They are dependencies of one of the other packages I AM installing.

When I upgraded an existing project from 19 to 20, I was able to do what you did. The only difference I know of is that that package did not use @nx/js to create a JS/TS lib package.

Something in the create schematic is different from what we've both done upgrading.

**Comment by LovishB** [comment]
Hey facing same issue,
lovishbadlani@Lovishs-Laptop frontend-apps-monorepo % nx report

 NX   Report complete - copy this into the issue template

Node           : 22.4.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.2

nx (global)        : 20.0.7
nx                 : 20.0.6
@nx/js             : 20.0.6
@nx/jest           : 20.0.6
@nx/eslint         : 20.0.6
@nx/workspace      : 20.0.6
@nx/devkit         : 20.0.6
@nx/eslint-plugin  : 20.0.6
@nx/next           : 20.0.6
@nx/playwright     : 20.0.6
@nx/react          : 20.0.6
@nx/vite           : 20.0.6
@nx/web            : 20.0.6
@nx/webpack        : 20.0.6
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/jest/plugin
@nx/eslint/plugin
@nx/playwright/plugin
@nx/vite/plugin


Getting CacheError:
TypeError: Cannot read properties of undefined (reading 'cacheError')
    at $v.retrieve (/Users/lovishbadlani/Projects/DXSale-Projects-Working/frontend-apps-monorepo/.nx/cache/cloud/2411.11.9/index.js:33:3328)
    at DbCache.get (/Users/lovishbadlani/Projects/DXSale-Projects-Working/frontend-apps-monorepo/node_modules/nx/src/tasks-runner/cache.js:62:48)
    at TaskOrchestrator.applyCachedResult (/Users/lovishbadlani/Projects/DXSale-Projects-Working/frontend-apps-monorepo/node_modules/nx/src/tasks-runner/task-orchestrator.js:131:47)
    at /Users/lovishbadlani/Projects/DXSale-Projects-Working/frontend-apps-monorepo/node_modules/nx/src/tasks-runner/task-orchestrator.js:126:70
    at Array.map (<anonymous>)
    at TaskOrchestrator.applyCachedResults (/Users/lovishbadlani/Projects/DXSale-Projects-Working/frontend-apps-monorepo/node_modules/nx/src/tasks-runner/task-orchestrator.js:126:54)
    at TaskOrchestrator.applyFromCacheOrRunTask (/Users/lovishbadlani/Projects/DXSale-Projects-Working/frontend-apps-monorepo/node_modules/nx/src/tasks-runner/task-orchestrator.js:219:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TaskOrchestrator.executeNextBatchOfTasksUsingTaskSchedule (/Users/lovishbadlani/Projects/DXSale-Projects-Working/frontend-apps-monorepo/node_modules/nx/src/tasks-runner/task-orchestrator.js:85:13)
    at async Promise.all (index 0)

**Comment by LovishB** [comment]
@DaveMBush @itspers error is resolved now !!

ran following commands >
nx-cloud convert-to-nx-cloud-id  
npm unistall nx-cloud

**Comment by LovishB** [comment]
@DaveMBush i had to uninstall nx-cloud so that nx version 20 can use it natively. It Worked!

**Comment by itspers** [comment]
@DaveMBush you need to just accept that v19.7+ will not work with nx-cloud packages present in node_modules.

> uninstalling nx-cloud gave me nx-cloud 16

Then it was not uninstalled - you need to find way to really get rid of it, if some 3rdparty library depends on it - its their bug, not NX - if its opensource - you can always fork it, tune and point npm to it

> " NX Unable to authenticate. Either define accessToken in nx.json or set the NX_CLOUD_ACCESS_TOKEN env variable."

Thats how it work now:

> Nx Cloud authentication is changing
From Nx 19.7 new workspaces are connected to Nx Cloud with a property called nxCloudId instead, and we recommend developers use [nx login](https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-login) to provision their own local [personal access tokens](https://nx.dev/ci/recipes/security/personal-access-tokens) for user based authentication.

So you need to use https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-login locally and env var on CI/CD https://nx.dev/ci/recipes/security/access-tokens#setting-ci-access-tokens

**Comment by DaveMBush** [comment]
It appears NX Report is reporting nx-cloud 16 as being there but when I search the lock file for a reference to is (so I can see who is loading it) it isn't there and I can't find it in node_modules.  So, now that I know that, I'm back to the "unable to authenticate" error.

I've already done the login thing and I've verified the file exist on my computer with the PAT in it.  So, I'm still stuck.

**Comment by DaveMBush** [comment]
Finlly figured it out 🙄 ... some how, probably from a mistake I made long ago, I had a node_modules directory (and  package.json file, etc) in the parent directory to all my projects.  That is where the nx version 16 was coming from.  and now, everything is working the way one would expect.

Thank you all for your patience.  It's been one of those weeks and its only Tuesday 😟

**Comment by DaveMBush** [comment]
One final issue.  On my CI, I'm getting 

``` bash
Run pnpm exec nx affected -t lint test build
  pnpm exec nx affected -t lint test build
  shell: /usr/bin/bash -e {0}
  env:
    NX_CLOUD_ACCESS_TOKEN: ***
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    NX_BASE: eb09fbbc8451e6498a016a[2](https://github.com/DaveMBush/smart-eslint/actions/runs/11809692895/job/32900430009#step:7:2)1656657a76ad5598a
    NX_HEAD: 31e9f4bea52cf0b02278e80d91b1f272a[3](https://github.com/DaveMBush/smart-eslint/actions/runs/11809692895/job/32900430009#step:7:3)3f3548
  
 NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: eb09fbbc8[4](https://github.com/DaveMBush/smart-eslint/actions/runs/11809692895/job/32900430009#step:7:4)51e6498a016a216[5](https://github.com/DaveMBush/smart-eslint/actions/runs/11809692895/job/32900430009#step:7:5)6657a76ad5598a
 NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: 31e9f4bea52cf0b022[7](https://github.com/DaveMBush/smart-eslint/actions/runs/11809692895/job/32900430009#step:7:7)8e80d91b1f272a33f3548
 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
```

This is even after running nx reset as part of the action.

**Comment by jogelin** [comment]
> [@DaveMBush](https://github.com/DaveMBush) i had to uninstall nx-cloud so that nx version 20 can use it natively. It Worked!

Same for me, uninstaling nx-cloud solves:

```
NX Cannot read properties of undefined (reading 'cacheError')
```

**Comment by nhhockeyplayer** [comment]
be nice if you guys spoke it could be accurate

        "@nrwl/nx-cloud": "19.1.0",

within local package.json

and not the global cmd line version

or is that one suppose to be uninstalled too?

thanks for clarification

**Comment by StalkAltan** [comment]
Hi all, there are _many_ different issues reported here so I am going to try and address them all in one response. As a result I will also close this issue, and if the behaviors still persist, let's open new issues and try to keep them isolated.

1) The original issue was caused by a mistaken directory structure. See this comment from OP

> I had a node_modules directory (and package.json file, etc) in the parent directory to all my projects. That is where the nx version 16 was coming from. and now, everything is working the way one would expect.

2) "When do I need to have the `nx-cloud` or `@nrwl/nx-cloud` packages explicitly defined?"

Since version 17, Nx (OSS) has the ability to run and connect to Nx Cloud without these packages. The default state should be that if you are on Nx>17, you _do not_ need either `nx-cloud` OR `@nrwl/nx-cloud` defined in your package.json. Nx migrations should have taken care of this for you. If you uninstall these packages manually, make sure that you do not still have a `taskRunnerOptions` property in your `nx.json` that contains references to either of these packages. You can replace almost all of that config with a single top-level property called `nxCloudAccessToken` (if you previously had an `accessToken` defined), or by moving the `nxCloudId` to the top-level of the `nx.json`.

Only truly exceptional cases would require the package being re-added -- if you think you have a truly exceptional case, you probably do not 😅 

3) Global versions

Don't install `nx-cloud` globally. Anything you need it for will be better served by using `npx` and it will prevent weird, difficult to diagnose and debug resolution behaviors.

4)  NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

99.9% of the time this means your config files have bad syntax in them. We have tried to improve the behavior of these error messages and in more recent versions of Nx, more information should be available about the offending plugin and file.
