### ISSUE TITLE
Unable to use Nx Nest Generator to generate new services

### ISSUE THREAD

**Issue by jasonbdt** [nrwl/nx#28769]
### Current Behavior

If I try to use `nx generate @nx/nest:service --name=src/app/users`, my terminal is printing out the following error:

```text
[ NX ]  Generating @nx/nest:service

Cannot read properties of undefined (reading 'replace')
```

Another attempt with `nx generate @nx/nest:service src/app/users --name=users` is not working too, but another error will be thrown:

```text
[ NX ]  Generating @nx/nest:service

[ NX ]  Schema does not support positional arguments. Argument 'src/app/users' found

Schema does not support positional arguments. Argument 'src/app/users' found
```

This issue force us to create the files manually as the provided generator of @nx/nest is not working.

### Expected Behavior

For me the command feels a bit confusing as positional arguments are disabled and the `--name` property misses the part where the service has to be placed. I'd like to use the nest service generator this way much more:

```text
nx generate @nx/nest:service src/app/users

[ NX ] Generating @nx/nest:service

CREATE apps/PROJECT-NAME/src/app/users/users.service.ts
CREATE apps/PROJECT-NAME/src/app/users/users.service.spec.ts
UPDATE apps/PROJECT-NAME/src/app/users/users.module.ts
```

```text
nx generate @nx/nest:service src/app/users --name=example

[ NX ] Generating @nx/nest:service

CREATE apps/PROJECT-NAME/src/app/users/example.service.ts
CREATE apps/PROJECT-NAME/src/app/users/example.service.spec.ts
UPDATE apps/PROJECT-NAME/src/app/users/users.module.ts
```

### GitHub Repo

[https://github.com/jasonbdt/nx-nest-service-generator](https://github.com/jasonbdt/nx-nest-service-generator)

### Steps to Reproduce

1. Create NX workspace using `npx create-nx-workspace@latest example-app --preset=angular-monorepo --pm=yarn`
2. Go inside the newly created workspace with your terminal (e.g. `cd example-app`)
3. Install @nx/nest plugin in order to create an nest application (use `yarn add @nx/nest`)
4. Create the nest application with `nx generate @nx/nest:app apps/my-nest-app --frontendProject=example-app`
5. Go inside the new application folder with your terminal (e.g. `cd apps/my-nest-app`)
6. Try to generate a service using the nx cli with nest schematics `nx g @nx/nest:service --name=src/app/users`
7. The error shown above should be thrown

### Nx Report

Node           : 18.20.3
OS             : win32-x64
Native Target  : x86_64-windows
yarn           : 1.22.22

nx (global)        : 20.0.7
nx                 : 20.0.7
@nx/js             : 20.0.7
@nx/jest           : 20.0.7
@nx/eslint         : 20.0.7
@nx/workspace      : 20.0.7
@nx/angular        : 20.0.7
@nx/devkit         : 20.0.7
@nx/eslint-plugin  : 20.0.7
@nx/nest           : 20.0.7
@nx/node           : 20.0.7
@nx/playwright     : 20.0.7
@nx/vite           : 20.0.7
@nx/web            : 20.0.7
@nx/webpack        : 20.0.7
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
@nx/webpack/plugin

### Failure Logs

```bash
PS C:\Users\jasonbdt\projects\example-app> nx g @nx/nest:service --name=src/app/users --verbose

[ NX ]  Generating @nx/nest:service


[ NX ]  Cannot read properties of undefined (reading 'replace')

TypeError: Cannot read properties of undefined (reading 'replace')
    at extractNameAndDirectoryFromPath (C:\Users\fsrgmbh\projects\example-app\node_modules\@nx\devkit\src\generators\artifact-name-and-directory-utils.js:69:17)
    at getNameAndDirectoryOptions (C:\Users\fsrgmbh\projects\example-app\node_modules\@nx\devkit\src\generators\artifact-name-and-directory-utils.js:19:46)
    at determineArtifactNameAndDirectoryOptions (C:\Users\fsrgmbh\projects\example-app\node_modules\@nx\devkit\src\generators\artifact-name-and-directory-utils.js:10:31)
    at normalizeOptions (C:\Users\fsrgmbh\projects\example-app\node_modules\@nx\nest\src\generators\utils\normalize-options.js:7:124)
    at normalizeServiceOptions (C:\Users\fsrgmbh\projects\example-app\node_modules\@nx\nest\src\generators\service\service.js:11:66)
    at serviceGenerator (C:\Users\fsrgmbh\projects\example-app\node_modules\@nx\nest\src\generators\service\service.js:6:27)
    at C:\Users\fsrgmbh\projects\example-app\node_modules\nx\src\command-line\generate\generate.js:238:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (C:\Users\fsrgmbh\projects\example-app\node_modules\nx\src\utils\handle-errors.js:9:24)
    at async Object.handler (C:\Users\fsrgmbh\projects\example-app\node_modules\nx\src\command-line\generate\command-object.js:14:22)
```

### Package Manager Version

yarn - 1.22.22

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

I have already took a look into this issue and might have found a way to get this working with just a few code changes. The project where I have faced this issue is a new workspace without big changes in codebase. I will create a pull request with my fix included, stay tuned 😁

**Comment by jasonbdt** [comment]
1. Added GitHub Repo to reproduce the issue
2. Added Failure Logs / Error Output

**Comment by nawab69** [comment]
I got the same issue. I tried on both mac and windows. same result.
Also the module generate has issue. 
when i set path `src/app/users`  and name `users `,  it generates on `/src/app/src/app/users.module.ts`
but when i set path `users` and name `users`, it generates on `/users/users.module.ts`
again when i set path `src/app` and name users, it generates `src/src/app/app.module.ts`

**Comment by jasonbdt** [comment]
Already have a fix for this issue but I got problems setting up a local-registry as described in CONTRIBUTING.md

Somehow I am not able to use `npm adduser --registry http://localhost:4873` as I get ERRCONN errors. Even with the browser I can not visit the url which should show up at least the versaccio dashboard.

My workspace is forked and started through a docker container. Port Forwarding is configured.

If I get done with this problem to test my changes locally, I'd like to create a pull request.

**Comment by ElroiAbergel** [comment]
Facing the same issue here

**Comment by jasonbdt** [comment]
@ElroiAbergel As I already mentioned above, yes I have found a solution to make it working.

My last problem is to create a local registry using `pnpm local-registry` as it is described in CONTRIBUTING.md to test the local changes with a local build.

I get an error that tells me, that the package manager should be the one, that is mentioned in package.json. The file contains `"packageManager": "pnpm@9.8.0"`. 

After that Verdaccio is getting started, but it seems that it doesn't allows any connections. Still looking for a Solution for this.

**Comment by jasonbdt** [comment]
Have some good news today - I got my local registry up and running thanks to the issue mentioned above.

I have updated my local nx copy to 20.0.10 and built a new version with my local changes to test them right after with a newly created project. I am not sure, but it seems that this command works as expected. If you want to use the command, you have to specify the full path, where you want the service to be created (project path included).

```bash
PS C:\Users\jasonbdt\projects\example-app> nx g @nx/nest:service apps/nest-app/src/app/users
```

Another possible way is by entering the application path using your terminal

```bash
PS C:\Users\jasonbdt\projects\example-app> cd ./apps/nest-app
PS C:\Users\jasonbdt\projects\example-app\apps\nest-app> nx g @nx/nest:service src/app/users
```

Using the name parameter is working too.

Tested module generation too, is this the expected output after running the command @nawab69:

```bash
PS C:\Users\jasonbdt\projects\example-app> nx g @nx/nest:module apps/example-app/src/app/users

[ NX ]  Generating @nx/nest:module

✔ What name would you like to use? · users
[ CREATE ]  apps/example-app/src/app/users/users.module.ts
[ UPDATE ]  apps/example-app/src/app/app.module.ts
```

**Comment by leosvelperez** [comment]
Thanks for reporting this! I apologize for the delay.

These issues should have been fixed since Nx v20.3.0. Please note that the `--name` option no longer exists and the first positional argument should be the path to the service file. You can check the examples in the generator docs: https://nx.dev/nx-api/nest/generators/service#examples.

I'm going to close this, but if someone still has an issue after migrating to the latest version, please leave a message, and I'll take a look or create a new issue with the relevant information.

**Comment by tones-griff** [comment]
Hi there, would this be related maybe? https://github.com/nrwl/nx/issues/29957. I am unable to generate components.
