### ISSUE TITLE
NX parallel tasks fail with the errors 'database disk image is malformed' and 'NX   DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 1555 }, Some("UNIQUE constraint failed: task_details.hash"))'

### ISSUE THREAD

**Issue by ytchenak** [nrwl/nx#28772]
### Current Behavior

NX parallel tasks fail with the errors 'database disk image is malformed' and 'NX   DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 1555 }, Some("UNIQUE constraint failed: task_details.hash"))'

### Expected Behavior

Parallel tests have to be finished without error

### Steps to Reproduce

Run two or more jobs that execute non-overlapping sets of NX tasks

### Nx Report

Node           : 20.18.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 9.12.1

nx (global)        : 19.8.4
nx                 : 19.8.8
@nx/js             : 19.8.8
@nx/jest           : 19.8.8
@nx/linter         : 19.8.8
@nx/eslint         : 19.8.8
@nx/workspace      : 19.8.8
@nx/angular        : 19.8.8
@nx/eslint-plugin  : 19.8.8
typescript         : 5.5.4
---------------------------------------
Community plugins:
@ngneat/spectator : 19.0.0
ng-mocks          : 14.13.1
ngx-bootstrap     : 18.0.2
nx-stylelint      : 17.1.6

### Failure Logs

first job:
```
NX   database disk image is malformed
[2024-11-03T08:02:14.318Z] 
[2024-11-03T08:02:14.318Z] Error: database disk image is malformed
[2024-11-03T08:02:14.318Z]     at TaskHistory.getEstimatedTaskTimings (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/utils/task-history.js:20:37)
[2024-11-03T08:02:14.318Z]     at TasksSchedule.init (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/tasks-schedule.js:28:40)
[2024-11-03T08:02:14.318Z]     at TaskOrchestrator.run (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/task-orchestrator.js:48:32)
[2024-11-03T08:02:14.318Z]     at runAllTasks (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/default-tasks-runner.js:60:25)
[2024-11-03T08:02:14.318Z]     at defaultTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/default-tasks-runner.js:51:22)
[2024-11-03T08:02:14.318Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-11-03T08:02:14.318Z]     at async invokeTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/run-command.js:441:5)
[2024-11-03T08:02:14.318Z]     at async runCommandForTasks (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/run-command.js:117:25)
[2024-11-03T08:02:14.318Z]     at async /h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/run-command.js:105:29
[2024-11-03T08:02:14.318Z]     at async handleErrors (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/utils/handle-errors.js:9:24)
```

second job:
```
|NX   DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 1555 }, Some("UNIQUE constraint failed: task_details.hash"))
[2024-11-03T08:02:18.848Z] 
[2024-11-03T08:02:18.848Z] Error: DB transaction operation error: SqliteFailure(Error { code: ConstraintViolation, extended_code: 1555 }, Some("UNIQUE constraint failed: task_details.hash"))
[2024-11-03T08:02:18.848Z]     at hashTasksThatDoNotDependOnOutputsOfOtherTasks (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/hasher/hash-task.js:46:22)
[2024-11-03T08:02:18.848Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-11-03T08:02:18.848Z]     at async invokeTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/run-command.js:373:5)
[2024-11-03T08:02:18.848Z]     at async runCommandForTasks (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/run-command.js:117:25)
[2024-11-03T08:02:18.848Z]     at async /h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/run-command.js:105:29
[2024-11-03T08:02:18.848Z]     at async handleErrors (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/utils/handle-errors.js:9:24)
[2024-11-03T08:02:18.848Z]     at async runCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/tasks-runner/run-command.js:104:20)
[2024-11-03T08:02:18.848Z]     at async Object.runMany (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/command-line/run-many/run-many.js:46:24)
[2024-11-03T08:02:18.848Z]     at async /h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/command-line/run-many/command-object.js:13:13
[2024-11-03T08:02:18.848Z]     at async handleErrors (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1454/frontend/node_modules/.pnpm/nx@19.8.9_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_7idvw5wocp6v2fkns4phtyxxzi/node_modules/nx/src/utils/handle-errors.js:9:24)
```

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

It seems that the original issue [https://github.com/nrwl/nx/issues/28424](https://github.com/nrwl/nx/issues/28424) was not completely resolved. The issue persists in version 19.8.8, even after the fix [https://github.com/nrwl/nx/pull/28544](https://github.com/nrwl/nx/pull/28544). It appears that the SQLite files are still not adequately protected against concurrent write access, despite the presence of the `lockfile.hash` file in the directory.

**Comment by DaSchTour** [comment]
Maybe related to #28640

**Comment by ytchenak** [comment]
I believe this issue is related to multiple NX processes running concurrently and using the same workspace, which leads to conflicts in the cache metadata SQLite database. I tried upgrading to the latest version (20.0.10) but still encountered an SQLite error.

````

 NX   database disk image is malformed

Error: database disk image is malformed
    at TaskHistory.getEstimatedTaskTimings (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1523/frontend/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.13__@swc+types@0.1.14_t_yc76nam4t7wmmxixmaewf25aca/node_modules/nx/src/utils/task-history.js:20:37)
    at TasksSchedule.init (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1523/frontend/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.13__@swc+types@0.1.14_t_yc76nam4t7wmmxixmaewf25aca/node_modules/nx/src/tasks-runner/tasks-schedule.js:28:40)
    at TaskOrchestrator.run (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1523/frontend/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.13__@swc+types@0.1.14_t_yc76nam4t7wmmxixmaewf25aca/node_modules/nx/src/tasks-runner/task-orchestrator.js:48:32)
    at runAllTasks (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1523/frontend/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.13__@swc+types@0.1.14_t_yc76nam4t7wmmxixmaewf25aca/node_modules/nx/src/tasks-runner/default-tasks-runner.js:60:25)
    at defaultTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1523/frontend/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.13__@swc+types@0.1.14_t_yc76nam4t7wmmxixmaewf25aca/node_modules/nx/src/tasks-runner/default-tasks-runner.js:51:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1523/frontend/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.13__@swc+types@0.1.14_t_yc76nam4t7wmmxixmaewf25aca/node_modules/nx/src/tasks-runner/run-command.js:441:5)
    at async runCommandForTasks (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1523/frontend/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.13__@swc+types@0.1.14_t_yc76nam4t7wmmxixmaewf25aca/node_modules/nx/src/tasks-runner/run-command.js:117:25)
    at async /h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1523/frontend/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.13__@swc+types@0.1.14_t_yc76nam4t7wmmxixmaewf25aca/node_modules/nx/src/tasks-runner/run-command.js:105:29
    at async handleErrors (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1523/frontend/node_modules/.pnpm/nx@20.0.10_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.13__@swc+types@0.1.14_t_yc76nam4t7wmmxixmaewf25aca/node_modules/nx/src/utils/handle-errors.js:9:24)
```

**Comment by gregroyal** [comment]
I'm seeing this issue as well 20.0.7

specifically when i add
{"dependentTasksOutputFiles":} to a task input

**Comment by ytchenak** [comment]
I tested the latest version (20.1.2), and the issue is still persistent. When two concurrent NX processes run on the same workspace, one of the jobs fails with a SQLite error.  

Is there any progress on this? This issue is preventing us from upgrading to the latest NX versions. I am currently forced to use the last NX version that does not rely on SQLite.

@vsavkin - FYI

`
[2024-11-19T11:42:48.653Z]  NX   DB transaction operation error: SqliteFailure(Error { code: NotADatabase, extended_code: 26 }, Some("file is not a database"))
[2024-11-19T11:42:48.653Z] 
[2024-11-19T11:42:48.653Z] Error: DB transaction operation error: SqliteFailure(Error { code: NotADatabase, extended_code: 26 }, Some("file is not a database"))
[2024-11-19T11:42:48.653Z]     at TaskHistory.recordTaskRuns (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1671/frontend/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_hvi7kj5btq7ix24w7wn7bi43b4/node_modules/nx/src/utils/task-history.js:32:37)
[2024-11-19T11:42:48.653Z]     at TaskHistoryLifeCycle.endCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1671/frontend/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_hvi7kj5btq7ix24w7wn7bi43b4/node_modules/nx/src/tasks-runner/life-cycles/task-history-life-cycle.js:37:32)
[2024-11-19T11:42:48.653Z]     at CompositeLifeCycle.endCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1671/frontend/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_hvi7kj5btq7ix24w7wn7bi43b4/node_modules/nx/src/tasks-runner/life-cycle.js:18:25)
[2024-11-19T11:42:48.653Z]     at async defaultTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1671/frontend/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_hvi7kj5btq7ix24w7wn7bi43b4/node_modules/nx/src/tasks-runner/default-tasks-runner.js:54:9)
[2024-11-19T11:42:48.653Z]     at async invokeTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1671/frontend/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_hvi7kj5btq7ix24w7wn7bi43b4/node_modules/nx/src/tasks-runner/run-command.js:441:5)
[2024-11-19T11:42:48.653Z]     at async runCommandForTasks (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1671/frontend/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_hvi7kj5btq7ix24w7wn7bi43b4/node_modules/nx/src/tasks-runner/run-command.js:117:25)
[2024-11-19T11:42:48.653Z]     at async /h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1671/frontend/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_hvi7kj5btq7ix24w7wn7bi43b4/node_modules/nx/src/tasks-runner/run-command.js:105:29
[2024-11-19T11:42:48.653Z]     at async handleErrors (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1671/frontend/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_hvi7kj5btq7ix24w7wn7bi43b4/node_modules/nx/src/utils/handle-errors.js:8:24)
[2024-11-19T11:42:48.653Z]     at async runCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1671/frontend/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_hvi7kj5btq7ix24w7wn7bi43b4/node_modules/nx/src/tasks-runner/run-command.js:104:20)
[2024-11-19T11:42:48.653Z]     at async Object.runMany (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1671/frontend/node_modules/.pnpm/nx@20.1.2_@swc-node+register@1.10.9_@swc+core@1.7.42_@swc+helpers@0.5.13__@swc+types@0.1.13_t_hvi7kj5btq7ix24w7wn7bi43b4/node_modules/nx/src/command-line/run-many/run-many.js:43:24)
`

**Comment by maxfriedmann** [comment]
I get a similar error every now and then, we recently upgraded from 19.x to 20.x but no change. 

```
NX   DB transaction operation error: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
```

**Comment by ytchenak** [comment]
I reproduced the issue with the latest version of Nx (20.2.1).  

The issue occurs when two Nx jobs run in parallel. For example:  
- First job: `nx affected -t build`  
- Second job: `nx affected -t lint`  

The monorepo contains many buildable libraries.  

It seems that each job attempts to update the monorepo's SQLite database simultaneously. Due to insufficient concurrency control for write operations between different processes, the database can become corrupted.

first job:
```
 NX   DB transaction operation error: SqliteFailure(Error { code: SystemIoFailure, extended_code: 522 }, Some("disk I/O error"))

Error: DB transaction operation error: SqliteFailure(Error { code: SystemIoFailure, extended_code: 522 }, Some("disk I/O error"))
    at TaskHistory.recordTaskRuns (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/utils/task-history.js:32:37)
    at TaskHistoryLifeCycle.endCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/life-cycles/task-history-life-cycle.js:37:32)
    at CompositeLifeCycle.endCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/life-cycle.js:18:25)
    at async defaultTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/default-tasks-runner.js:54:9)
    at async invokeTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/run-command.js:441:5)
    at async runCommandForTasks (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/run-command.js:117:25)
    at async /h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/run-command.js:105:29
    at async handleErrors (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/utils/handle-errors.js:8:24)
    at async runCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/run-command.js:104:20)
    at async Object.runMany (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/command-line/run-many/run-many.js:43:24)
```

second job: 
```

 NX   DB transaction operation error: SqliteFailure(Error { code: NotADatabase, extended_code: 26 }, Some("file is not a database"))

Error: DB transaction operation error: SqliteFailure(Error { code: NotADatabase, extended_code: 26 }, Some("file is not a database"))
    at TaskHistory.recordTaskRuns (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/utils/task-history.js:32:37)
    at TaskHistoryLifeCycle.endCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/life-cycles/task-history-life-cycle.js:37:32)
    at CompositeLifeCycle.endCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/life-cycle.js:18:25)
    at async defaultTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/default-tasks-runner.js:54:9)
    at async invokeTasksRunner (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/run-command.js:441:5)
    at async runCommandForTasks (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/run-command.js:117:25)
    at async /h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/run-command.js:105:29
    at async handleErrors (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/utils/handle-errors.js:8:24)
    at async runCommand (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/tasks-runner/run-command.js:104:20)
    at async Object.runMany (/h/bldrtlv/jenkins/git_repo/prod/emweb_PR-1899/frontend/node_modules/.pnpm/nx@20.2.1_@swc-node+register@1.10.9_@swc+core@1.10.0_@swc+helpers@0.5.15__@swc+types@0.1.17_t_ey4e52b45zjxsgoc7c6u5skcde/node_modules/nx/src/command-line/run-many/run-many.js:43:24)
```

**Comment by raknjarasoa** [comment]
I'm also facing the same issue with the latest version 20.3.0.

**Comment by Cammisuli** [comment]
@ytchenak you can use `NX_WORKSPACE_DATA_DIRECTORY` to change the directory of the workspace data. 

And can you give me an example on how the manual distribution will fail with the db? Is it because of the network drive you have set up?

**Comment by ytchenak** [comment]
Hello @Cammisuli 
We run multiple Jenkins jobs in parallel to enhance CI/CD performance. This is particularly important for JEST tests, which are known for their performance limitations, especially in NX monorepos due to ESM-CommonJS translation for each project. 

To address this, we run number parallel Jenkins jobs, each executing NX test target on a distinct, non-overlapping set of NX projects. Each Jenkins job runs on a separate agent but uses the same NX workspace, mapped via a network path.

**Comment by raknjarasoa** [comment]
> I can bypass the issue by setting NX_DISABLE_DB to true. However, I understand that this option will be deprecated in the next version. As a result, the existing NX concepts described here (https://nx.dev/ci/concepts/parallelization-distribution#manual-distribution) will no longer be supported.
> 
> I would like to hear from the NX team about possible alternatives to support manual distribution once NX_DISABLE_DB is removed, without requiring a transition to paid NX Cloud or NX Powerpack.

Fix my issue. 
Thanks

**Comment by FrozenPandaz** [comment]
It looks like you all have figured out your issues.

For those who disabled the db with `NX_DISABLE_DB=true`, this will not work in Nx 21.

As of just a few weeks ago, the [Shared FS Cache](https://nx.dev/nx-api/shared-fs-cache#nxsharedfscache) is now completely free without the need for Powerpack.

Please take some time before updating to Nx 21 to set `@nx/shared-fs-cache` up.

Thank you all!
