### ISSUE TITLE
Incremental build of angular application broken when custom webpack config is present

### ISSUE THREAD

**Issue by MaGnaL** [nrwl/nx#28804]
### Current Behavior

I have an angular application which is configured for incremental builds:

```json
    "build": {
      "executor": "@nx/angular:webpack-browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "buildLibsFromSource": false,
        "customWebpackConfig": {
          "path": "apps/app-broken/webpack.config.ts"
        },
        "outputPath": "dist/apps/app-broken",
        "index": "apps/app-broken/src/index.html",
        "main": "apps/app-broken/src/main.ts",
        "polyfills": ["zone.js"],
        "tsConfig": "apps/app-broken/tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "assets": [
          {
            "glob": "**/*",
            "input": "apps/app-broken/public"
          }
        ],
        "styles": ["apps/app-broken/src/styles.scss"],
        "scripts": []
      },
      ...
    },
```

Executor is `@nx/angular:webpack-browser` and `buildLibsFromSource` is set to `false`. There is also a `customWebpackConfig` present for some reason.

Additionally, there is a buildable angular library present, with a secondary entry-point using ng-packagr. Both, the secondary entry-point and the main entry-point are used in the application.

As soon as there is a `customWebpackConfig` present in the application, the build fails with the following message:

```shell
 NX   Running target build for project app-broken and 1 task it depends on:

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run lib1:build:production  [existing outputs match the cache, left as is]

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@latest-ws/lib1'
------------------------------------------------------------------------------
- Compiling with Angular sources in Ivy full compilation mode.
✔ Compiling with Angular sources in Ivy full compilation mode.
Copying assets
Writing package manifest
Built @latest-ws/lib1

------------------------------------------------------------------------------
Building entry point '@latest-ws/lib1/sub1'
------------------------------------------------------------------------------
- Compiling with Angular sources in Ivy full compilation mode.
✔ Compiling with Angular sources in Ivy full compilation mode.
Built @latest-ws/lib1/sub1

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/manuel/Code/TEMP/latest-ws/libs/lib1
 - to:   /Users/manuel/Code/TEMP/latest-ws/dist/libs/lib1
------------------------------------------------------------------------------

Build at: 2024-11-05T17:08:29.472Z - Time: 904ms


> nx run app-broken:build:production

⠋ Generating browser application bundles (phase: setup)...thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_loader-0.45.28/src/resolvers/tsc.rs:83:21:
assertion `left == right` failed: value of `paths.@latest-ws/lib1/sub1` should be an array with one element because the src path does not contains * (wildcard)
  left: 3
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 NX   failed to handle: assertion `left == right` failed: value of `paths.@latest-ws/lib1/sub1` should be an array with one element because the src path does not contains * (wildcard)

  left: 3
 right: 1
Error: failed to handle: assertion `left == right` failed: value of `paths.@latest-ws/lib1/sub1` should be an array with one element because the src path does not contains * (wildcard)
  left: 3
 right: 1
    at Compiler.transformSync (/Users/manuel/Code/TEMP/latest-ws/node_modules/@swc/core/index.js:246:29)
    at transformSync (/Users/manuel/Code/TEMP/latest-ws/node_modules/@swc/core/index.js:356:21)
    at transformSync (/Users/manuel/Code/TEMP/latest-ws/node_modules/@swc-node/core/index.ts:93:26)
    at compile (/Users/manuel/Code/TEMP/latest-ws/node_modules/@swc-node/register/register.ts:124:40)
    at exts (/Users/manuel/Code/TEMP/latest-ws/node_modules/@swc-node/register/register.ts:135:38)
    at Module._compile (/Users/manuel/Code/TEMP/latest-ws/node_modules/pirates/lib/index.js:113:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.newLoader [as .ts] (/Users/manuel/Code/TEMP/latest-ws/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)


——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target build for project app-broken and 1 task it depends on failed

Failed tasks:

- app-broken:build:production

Hint: run the command with --verbose for more details.

```

The content of the webpack config is irrelevant from what I can tell.

When there is no `customWebpackConfig` the build succeeds without problem.

---

When there is no secondary entry-point, the error message looks like this:

```shell
 NX   Running target build for project app-broken and 1 task it depends on:

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run lib1:build:production

Building Angular Package

------------------------------------------------------------------------------
Building entry point '@latest-ws/lib1'
------------------------------------------------------------------------------
- Compiling with Angular sources in Ivy full compilation mode.
✔ Compiling with Angular sources in Ivy full compilation mode.
Copying assets
Writing package manifest
Built @latest-ws/lib1

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/manuel/Code/TEMP/latest-ws/libs/lib1
 - to:   /Users/manuel/Code/TEMP/latest-ws/dist/libs/lib1
------------------------------------------------------------------------------

Build at: 2024-11-05T17:22:29.607Z - Time: 783ms


> nx run app-broken:build:production

⠋ Generating browser application bundles (phase: setup)...
 NX   Cannot read properties of undefined (reading 'find')

TypeError: Cannot read properties of undefined (reading 'find')
    at mergeCustomWebpackConfig (/Users/manuel/Code/TEMP/latest-ws/node_modules/@nx/angular/src/builders/utilities/webpack.js:31:45)
    at initialize (/Users/manuel/Code/TEMP/latest-ws/node_modules/@angular-devkit/build-angular/src/builders/browser/index.js:71:29)
    at /Users/manuel/Code/TEMP/latest-ws/node_modules/@angular-devkit/build-angular/src/builders/browser/index.js:95:32


——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target build for project app-broken and 1 task it depends on failed

Failed tasks:

- app-broken:build:production

Hint: run the command with --verbose for more details.

```

### Expected Behavior

I would expect the incremental build setup to work with `customWebpackConfig` as well or a note in the documentation on what config needs to be changed (https://nx.dev/recipes/angular/setup-incremental-builds-angular).

### GitHub Repo

https://github.com/MaGnaL/reproduction-nx-incremental-build

### Steps to Reproduce

1. checkout and install (npm was used)
2. run `nx run app-broken:build`

### Nx Report

Node           : 20.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.2

nx                 : 20.0.8
@nx/js             : 20.0.8
@nx/jest           : 20.0.8
@nx/eslint         : 20.0.8
@nx/workspace      : 20.0.8
@nx/angular        : 20.0.8
@nx/devkit         : 20.0.8
@nx/eslint-plugin  : 20.0.8
@nx/web            : 20.0.8
@nx/webpack        : 20.0.8
typescript         : 5.5.4

### Operating System

- [x] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

The problem is identical on windows and macos. I noticed the problem with Nx 18 already (which I use in production currently).

**Comment by SebastianPodgajny** [comment]
Same thing happens with esbuild plugin
```
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_loader-0.45.28/src/resolvers/tsc.rs:83:21:
assertion `left == right` failed: value of `paths.@domain/abilities` should be an array with one element because the src path does not contains * (wildcard)
  left: 4
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 NX   failed to handle: assertion `left == right` failed: value of `paths.@domain/abilities` should be an array with one element because the src path does not contains * (wildcard)

  left: 4
 right: 1
Pass --verbose to see the stacktrace.
```

**Comment by tonyganchev** [comment]
We are also hitting this:

```
 NX   Report complete - copy this into the issue template

Node           : 22.14.0
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 9.1.0

nx                     : 20.4.6
@nx/js                 : 20.4.6
@nx/jest               : 20.4.6
@nx/eslint             : 20.4.6
@nx/workspace          : 20.4.6
@nx/angular            : 20.4.6
@nx/devkit             : 20.4.6
@nx/eslint-plugin      : 20.4.6
@nx/module-federation  : 20.4.6
@nx/node               : 20.4.6
@nx/rollup             : 20.4.6
@nx/web                : 20.4.6
@nx/webpack            : 20.4.6
typescript             : 5.4.5
---------------------------------------
Community plugins:
ngx-build-plus : 17.0.0
---------------------------------------
Local workspace plugins:
         [redacted]
```

**Comment by LuanVenterMRI** [comment]
Same for us running an angular app with module federation:

`Node           : 23.1.0
OS             : win32-x64
Native Target  : x86_64-windows
yarn           : 1.22.22

nx (global)        : 20.4.6
nx                 : 20.0.8
@nx/js             : 20.0.8
@nx/jest           : 20.0.8
@nx/eslint         : 20.0.8
@nx/workspace      : 20.0.8
@nx/angular        : 20.0.8
@nx/cypress        : 20.0.8
@nx/devkit         : 20.0.8
@nx/eslint-plugin  : 20.0.8
@nx/plugin         : 20.0.8
@nx/react          : 20.0.8
@nx/storybook      : 20.0.8
@nx/web            : 20.0.8
@nx/webpack        : 20.0.8
typescript         : 5.5.4`

`thread '<unnamed>' panicked at C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_loader-1.0.0\src\resolvers\tsc.rs:83:21:
assertion `left == right` failed: value of `paths.@mri/angular-wfe-proxy-oidc` should be an array with one element because the src path does not contains * (wildcard)
  left: 4
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 NX   failed to handle: assertion `left == right` failed: value of `paths.@mri/angular-wfe-proxy-oidc` should be an array with one element because the src path does not contains * (wildcard)
  left: 4
 right: 1
Pass --verbose to see the stacktrace.
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by mguay22** [comment]
We're seeing the same issue as well, and is a huge blocker since we have so much TS to compile. I will start to dig in and see if I can spot where it is originating from, but I don't a lot of familiarity with Nx repo/Rust.

**Comment by mguay22** [comment]
So I was able to trace the origin of the error down to here: https://github.com/nrwl/nx/blob/master/packages/angular/src/builders/utilities/webpack.ts#L68

I think the issue is that we're registering the `@swc` compiler *before* we load the Webpack configuration, which is adversely affecting it's resolution.

If I instead move the load of the Webpack configuration to come first, the error no longer occurs: https://github.com/mguay22/nx/commit/64e8da83571350866a84db93894760b178b896a6

Before:

```
export function resolveCustomWebpackConfig(path: string, tsConfig: string) {
  const cleanupTranspiler = registerTsProject(tsConfig);
  const customWebpackConfig = require(path);
  cleanupTranspiler();
  // If the user provides a configuration in TS file
  // then there are 2 cases for exporting an object. The first one is:
  // `module.exports = { ... }`. And the second one is:
  // `export default { ... }`. The ESM format is compiled into:
  // `{ default: { ... } }`
  return customWebpackConfig.default ?? customWebpackConfig;
}
```

After:

```
export function resolveCustomWebpackConfig(path: string, tsConfig: string) {
  const customWebpackConfig = require(path);
  const cleanupTranspiler = registerTsProject(tsConfig);
  cleanupTranspiler();
  // If the user provides a configuration in TS file
  // then there are 2 cases for exporting an object. The first one is:
  // `module.exports = { ... }`. And the second one is:
  // `export default { ... }`. The ESM format is compiled into:
  // `{ default: { ... } }`
  return customWebpackConfig.default ?? customWebpackConfig;
}
```

**Comment by leosvelperez** [comment]
I'm closing this given it's an issue with an upstream dependency, and it's not currently actionable by Nx. Please note you can work around the issue by running the broken tasks with `NX_PREFER_TS_NODE=true`. See the previous comment for more context.
