### ISSUE TITLE
Powerpack License could not be read: Unable to create directories

### ISSUE THREAD

**Issue by tidusjar** [nrwl/nx#28818]
### Current Behavior

Running `yarn nx activate-powerpack LICENSE` results in the following:

```
License could not be read: Unable to create directories, C:\git\project/.nx/powerpack/license.ini

Error: License could not be read: Unable to create directories, C:\git\project/.nx/powerpack/license.ini
    at napi_create_error (C:\git\project\node_modules\@emnapi\core\dist\emnapi-core.cjs.js:4535:25)
    at wasm://wasm/004db3ba:wasm-function[264]:0x95caa
    at wasm://wasm/004db3ba:wasm-function[63]:0x40831
    at C:\git\project\node_modules\@emnapi\core\dist\emnapi-core.cjs.js:3095:64
    at NodeEnv.callIntoModule (C:\git\project\node_modules\@emnapi\runtime\dist\emnapi.cjs.js:639:19)
    at C:\git\project\node_modules\@emnapi\core\dist\emnapi-core.cjs.js:3094:42
    at activatePowerpack (eval at emnapiCreateFunction (C:\git\project\node_modules\@emnapi\core\dist\emnapi-core.cjs.js:3115:26), <anonymous>:3:59)
    at Object.handleActivatePowerpack (C:\git\project\node_modules\nx\src\command-line\activate-powerpack\activate-powerpack.js:16:5)
    at async handleErrors (C:\git\project\node_modules\nx\src\utils\handle-errors.js:9:24)
    at async Object.handler (C:\git\projecti\node_modules\nx\src\command-line\activate-powerpack\command-object.js:21:26)
```

A guess would be to do with the way windows handles paths

### Expected Behavior

Activate the license and create the license file

### Steps to Reproduce

1. Windows machine
2. run `yarn nx activate-powerpack`

### Nx Report

```
Node           : 18.20.3
OS             : win32-x64
Native Target  : x86_64-windows
yarn           : 1.22.22

nx                 : 20.0.9
@nx/js             : 20.0.9
@nx/jest           : 20.0.9
@nx/eslint         : 20.0.9
@nx/workspace      : 20.0.9
@nx/angular        : 20.0.9
@nx/cypress        : 20.0.9
@nx/devkit         : 20.0.9
@nrwl/devkit       : 17.0.2
@nx/eslint-plugin  : 20.0.9
@nx/plugin         : 20.0.9
@nx/storybook      : 20.0.9
@nx/web            : 20.0.9
@nx/webpack        : 20.0.9
typescript         : 5.5.4

Nx Powerpack
---------------------------------------
License could not be read: failed to find a pre-opened file descriptor through which "C:\\git\\project/.nx/powerpack/license.ini" could be opened

---------------------------------------
Registered Plugins:
@project/plugins/dotnet-project-graph
@project/workspace-plugin
---------------------------------------
Community plugins:
@driimus/nx-plugin-openapi : 3.0.0
@nx-dotnet/core            : 2.2.0
@storybook/angular         : 8.2.0
ng-mocks                   : 14.13.1
nx-stylelint               : 17.1.5
---------------------------------------
```

### Package Manager Version

Yarn 1.22.22

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by Cammisuli** [comment]
Sorry about that! This should be fixed with the latest version of powerpack (1.0.12)
