### ISSUE TITLE
@nx/eslint-plugin react config adds `import` plugin that breaks global import rules if present

### ISSUE THREAD

**Issue by rudfoss-rr** [nrwl/nx#28871]
### Current Behavior

The current setup for the `@nx/eslint-plugin` for react configurations uses `eslint-plugin-import` in @nx v19 with eslint flat config breaks if I specify any rules for the import plugin in the global eslint configuration file.

This appears to be because the [react base config](https://github.com/nrwl/nx/blob/master/packages/eslint-plugin/src/flat-configs/react-base.ts) also imports `eslint-plugin-import` which causes it to be redeclared. This means that any ruleset that uses this config:

```js
const nx = require("@nx/eslint-plugin")
nx.configs["flat/react"]
```

breaks because I've already declared the plugin in my global `eslint.config.js` in order to specify my own rules.

### Expected Behavior

I should be able to override `eslint-plugin-import` rules in the root `eslint.config.js` file without having them break for react app.

### Steps to Reproduce

1. Create an empty workspace using `npx create-nx-workspace@19` (v20 does not work)
2. Add React `npx nx add @nx/react`
3. Create a react app with `eslint`
4. Add any `eslint-plugin-import` rule to the base `eslint.config.js`
5. Run `lint` target for the app

### Nx Report

```shell
Node           : 22.11.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.9.0

nx                 : 19.8.4
@nx/js             : 19.8.4
@nx/linter         : 19.8.4
@nx/eslint         : 19.8.4
@nx/workspace      : 19.8.4
@nx/devkit         : 19.8.4
@nx/eslint-plugin  : 19.8.4
@nx/next           : 20.0.6
@nx/playwright     : 19.8.4
@nx/react          : 19.8.4
@nrwl/tao          : 19.8.4
@nx/vite           : 19.8.4
@nx/web            : 19.8.4
@nx/webpack        : 20.0.6
@nrwl/webpack      : 19.8.4
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx-dotnet/core
---------------------------------------
Community plugins:
@nx-dotnet/core        : 2.4.5
@nx-tools/nx-container : 6.0.4
---------------------------------------
The following packages should match the installed version of nx
  - @nx/next@20.0.6
  - @nx/webpack@20.0.6

To fix this, run `nx migrate nx@20.0.6`
```

### Failure Logs

```shell
Error: Key "plugins": Cannot redefine plugin "import".
    at /home/rudfoss/qgrid/node_modules/@eslint/object-schema/dist/cjs/index.cjs:399:12
    at Array.reduce (<anonymous>)
    at ObjectSchema.merge (/home/rudfoss/qgrid/node_modules/@eslint/object-schema/dist/cjs/index.cjs:382:18)
    at /home/rudfoss/qgrid/node_modules/@eslint/config-array/dist/cjs/index.cjs:1093:43
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (/home/rudfoss/qgrid/node_modules/@eslint/config-array/dist/cjs/index.cjs:1091:43)
    at FlatConfigArray.getConfig (/home/rudfoss/qgrid/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
    at entryFilter (/home/rudfoss/qgrid/node_modules/eslint/lib/eslint/eslint-helpers.js:286:40)
    at async NodeHfs.<anonymous> (file:///home/rudfoss/qgrid/node_modules/@humanfs/core/src/hfs.js:560:24)
    at async NodeHfs.walk (file:///home/rudfoss/qgrid/node_modules/@humanfs/core/src/hfs.js:600:3)
```

### Package Manager Version

10.9.0

### Operating System

- [ ] macOS
- [x] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

As a workaround, I've written a small function that removes the duplicate import plugin:

```js
const removeDuplicateImportPlugin = (config) => {
	for (const singleConfig of config) {
		if (singleConfig?.plugins?.["import"]) {
			console.log("eslint.config.js: Stripped import plugin")
			delete singleConfig.plugins["import"]
		}
	}
	return config
}

module.exports = [
	...baseConfig,
	...removeDuplicateImportPlugin(nx.configs["flat/react"]),
	{
		files: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"],
		// Override or add rules here
		rules: {}
	}
]
```

**Comment by husseinakbari** [comment]
@rudfoss-rr I also have this issue on nx version `20.1.3` that blocked me. I found The temporary solution to unblock developers, putting eslint file in `.nxignore` to prevent checking eslint file by nx.

Create a `.nxignore` file at the root of your project.
`eslint.config.js`

**Comment by Smile040501** [comment]
I found that we can override `import` plugin rules in the react app's specific `eslint.config. mjs` file but not in the global one. Also, if we want to have these rules for any other non-react projects, we have to define this plugin there first before specifying the plugin rules.
