### ISSUE TITLE
bug: workspace/task-runner has issues when building projectGraph

### ISSUE THREAD

**Issue by Hotell** [nrwl/nx#2892]
## Expected Behavior

- properly resolve `projectGraph` context when feeding task runner
- if that's hard to do/impossible, provide proper Error message to consumer (
"You cannot name workspace project same as your npm dependencies...-> workspace project clashing with npm dependency: [dotenv] " )

## Current Behavior

when we name workspace project by the same name as one of installed npm dependencies, `context.projectGraph` has wrong shape and thus will fail on executing default task runner when invoking https://github.com/nrwl/nx/blob/70a64c1776/packages/workspace/src/tasks-runner/utils.ts#L53 .

**workspace.json**
![image](https://user-images.githubusercontent.com/1223799/79970532-5a674e00-8493-11ea-92b9-1509622d114e.png)

**package.json**

![image](https://user-images.githubusercontent.com/1223799/79970602-723ed200-8493-11ea-9207-e61583588f88.png)

**Project Graph**

```js
{
 projectGraph: {
    nodes: {
       'eslint-config': [Object],
        'builder-test': [Object],
        dotenv: [Object],
        tools: [Object],
        react: [Object],
        'react-dom': [Object],
        '@babel/cli': [Object],
        '@babel/preset-react': [Object],
        '@babel/register': [Object],
        '@nrwl/eslint-plugin-nx': [Object],
        '@nrwl/jest': [Object],
        '@nrwl/node': [Object],
        '@nrwl/react': [Object],
        '@nrwl/web': [Object],
        '@nrwl/workspace': [Object],
        '@schematics/update': [Object],
        '@types/babel__core': [Object],
        '@types/dateformat': [Object],
        '@types/eslint': [Object],
        '@types/jest': [Object],
        '@types/node': [Object],
        '@types/react': [Object],
        '@types/react-dom': [Object],
        '@typescript-eslint/eslint-plugin': [Object],
        '@typescript-eslint/parser': [Object],
        'confusing-browser-globals': [Object],
        dateformat: [Object],
        eslint: [Object],
        'eslint-config-prettier': [Object],
        'eslint-plugin-etc': [Object],
        'eslint-plugin-filenames': [Object],
        'eslint-plugin-header': [Object],
        'eslint-plugin-import': [Object],
        'eslint-plugin-jest': [Object],
        'eslint-plugin-jsdoc': [Object],
        'eslint-plugin-jsx-a11y': [Object],
        'eslint-plugin-react': [Object],
        'eslint-plugin-react-hooks': [Object],
        'eslint-plugin-sonarjs': [Object],
        jest: [Object],
        prettier: [Object],
        'ts-jest': [Object],
        'ts-node': [Object],
        tslint: [Object],
        typescript: [Object]
     },
     dependencies: {
        'eslint-config': [Array],
        'builder-test': [],
        dotenv: [],
        tools: [Array],
        react: [],
        'react-dom': [],
        '@babel/cli': [],
        '@babel/preset-react': [],
        '@babel/register': [],
        '@nrwl/eslint-plugin-nx': [],
        '@nrwl/jest': [],
        '@nrwl/node': [],
        '@nrwl/react': [],
        '@nrwl/web': [],
        '@nrwl/workspace': [],
        '@schematics/update': [],
        '@types/babel__core': [],
        '@types/dateformat': [],
        '@types/eslint': [],
        '@types/jest': [],
        '@types/node': [],
        '@types/react': [],
        '@types/react-dom': [],
        '@typescript-eslint/eslint-plugin': [],
        '@typescript-eslint/parser': [],
        'confusing-browser-globals': [],
        dateformat: [],
        eslint: [],
        'eslint-config-prettier': [],
        'eslint-plugin-etc': [],
        'eslint-plugin-filenames': [],
        'eslint-plugin-header': [],
        'eslint-plugin-import': [],
        'eslint-plugin-jest': [],
        'eslint-plugin-jsdoc': [],
        'eslint-plugin-jsx-a11y': [],
        'eslint-plugin-react': [],
        'eslint-plugin-react-hooks': [],
        'eslint-plugin-sonarjs': [],
        jest: [],
        prettier: [],
        'ts-jest': [],
        'ts-node': [],
        tslint: [],
        typescript: []
      }
   }
}
```

dotenv value from nodes:
```
{ type: 'npm',
     name: 'dotenv',
     data: { version: '6.2.0', files: [] }
}
```

dotenv value from dependencies:
```
[]
```

## Failure Information (for bugs)

```
Unexpected error:
TypeError: Cannot read property 'lint' of undefined
    at getOutputsForTargetAndConfiguration (/Users/hotell/Projects/devel/productboardlabs/multioss/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:45:42)
    at Object.getOutputs (/Users/hotell/Projects/devel/productboardlabs/multioss/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:41:12)
    at TaskOrchestrator.forkProcess (/Users/hotell/Projects/devel/productboardlabs/multioss/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:122:37)
    at takeFromQueue (/Users/hotell/Projects/devel/productboardlabs/multioss/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:50:26)
    at TaskOrchestrator.<anonymous> (/Users/hotell/Projects/devel/productboardlabs/multioss/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:71:27)
    at Generator.next (<anonymous>)
    at /Users/hotell/Projects/devel/productboardlabs/multioss/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/hotell/Projects/devel/productboardlabs/multioss/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:4:12)
    at TaskOrchestrator.runRest (/Users/hotell/Projects/devel/productboardlabs/multioss/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:42:
```

### Steps to Reproduce

1. npx create-nx-workspace@latest repro-workspace
2. nx g @nrwl/workspace:lib dotenv
3. nx lint dotenv

### Context

```
  @nrwl/angular : Not Found
  @nrwl/cli : 9.2.3
  @nrwl/cypress : 9.2.3
  @nrwl/eslint-plugin-nx : 9.2.3
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.3
  @nrwl/linter : 9.2.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.3
  @nrwl/react : 9.2.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.3
  @nrwl/web : 9.2.3
  @nrwl/workspace : 9.2.3
  typescript : 3.8.3
```

**Comment by FrozenPandaz** [comment]
This is the same issue as described in https://github.com/nrwl/nx/issues/2396.

I will elaborate on the issue there.
