### ISSUE TITLE
Multiple errors after switching to nx-cloud CLI

### ISSUE THREAD

**Issue by ksdc-grantw** [nrwl/nx#28930]
### Current Behavior

Seeing console log errors regarding node_modules/nx-cloud and cacheErrors when running nx commands

### Expected Behavior

There not to be errors, just the console output.

### Steps to Reproduce

1. Have a project that is using the legecy 'nxCloudAccessToken' to connect to nx cloud
2. Run `nx reset` to ensure the local cache is empty (I wanted to test that the remote cache would be retrived usign the new nx cloud auth methoid)
3. Run `npx nx-cloud convert-to-nx-cloud-id`
 - Note: Access Levels for workspac are configure to **ID access level**: None; **PAT access level**: Read Only
4. Run a cachable task, in my case it was `lint`
5. Note the results

### Nx Report

```shell
Report complete - copy this into the issue template

Node           : 20.15.1
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.7.0

nx (global)        : 20.0.0
nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/react          : 20.0.0
@nx/storybook      : 20.0.0
@nx/vite           : 20.0.0
@nx/web            : 20.0.0
nx-cloud           : 19.1.0
typescript         : 5.6.2
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/storybook/plugin
```

### Failure Logs

```shell
$ nx lint contracts --verbose

[NX CLOUD] Using light client
[NX CLOUD] A local bundle currently exists:  {
  version: '2411.13.2',
  fullPath: 'C:\\Work\\KSDC\\blue-file-web\\node_modules\\.cache\\nx\\cloud\\2411.13.2'
}
[NX CLOUD] Last verification was within the past 30 minutes, will not verify this time
[NX CLOUD] Using bundle path:  {
  version: '2411.13.2',
  fullPath: 'C:\\Work\\KSDC\\blue-file-web\\node_modules\\.cache\\nx\\cloud\\2411.13.2'
}
Was not able to require.resolve module nx/src/utils/app-root from the following paths: C:\Work\KSDC\blue-file-web\node_modules\nx-cloud\node_modules,C:\Work\KSDC\blue-file-web\node_modules. This may be expected.
Was not able to require.resolve module nx/src/utils/app-root from the following paths: C:\Work\KSDC\blue-file-web\node_modules\nx-cloud\node_modules,C:\Work\KSDC\blue-file-web\node_modules. This may be expected.
[NX CLOUD] Verifying current cloud bundle
[NX CLOUD] A local bundle currently exists:  {
  version: '2411.13.2',
  fullPath: 'C:\\Work\\KSDC\\blue-file-web\\.nx\\cache\\cloud\\2411.13.2'
}
[NX CLOUD] Last verification was within the past 30 minutes, will not verify this time
[NX CLOUD] Done:  C:\Work\KSDC\blue-file-web\.nx\cache\cloud\2411.13.2
Was not able to require.resolve module nx/src/utils/app-root from the following paths: C:\Work\KSDC\blue-file-web\node_modules\nx-cloud\node_modules,C:\Work\KSDC\blue-file-web\node_modules. This may be expected.

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 NX   Successfully ran target lint for project contracts



 NX   Storing terminal outputs for contracts:lint with hash 2524258014223557229

[Nx Cloud Debug] Attempting to acquire filesystem lock with path:  C:\Users\GrantW\AppData\Local\Temp\client-instance-id.lock
[Nx Cloud Debug] Failed to create folder lock at path: C:\Users\GrantW\AppData\Local\Temp\client-instance-id.lock
[Nx Cloud] Unable to detect a VCS context from the environment.

 NX   RunStart


{
  "meta": {
    "nxCloudVersion": "latest"
  },
  "branch": null,
  "runGroup": "dafd6435f1f128e0fc4fbe1f14bbf40f824dbe59",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "2524258014223557229"
  ],
  "machineInfo": {
    "machineId": "16jKMW+7dXT2d/dtn2SmFg==",
    "platform": "win32",
    "version": "Windows 11 Pro",
    "cpuCores": 12
  },
  "vcsContext": null,
  "clientInstanceSource": "CLOUD_RUNNER",
  "clientInstanceId": "2e686a63-37c2-4d08-90ce-07396e3e3f24"
}

[Nx Cloud] Unable to detect a VCS context from the environment.

 NX   RunStart


{
  "meta": {
    "nxCloudVersion": "latest"
  },
  "branch": null,
  "runGroup": "dafd6435f1f128e0fc4fbe1f14bbf40f824dbe59",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "2524258014223557229"
  ],
  "machineInfo": {
    "machineId": "16jKMW+7dXT2d/dtn2SmFg==",
    "platform": "win32",
    "version": "Windows 11 Pro",
    "cpuCores": 12
  },
  "vcsContext": null,
  "clientInstanceSource": "CLOUD_RUNNER",
  "clientInstanceId": "2e686a63-37c2-4d08-90ce-07396e3e3f24"
}

RunStart duration: 449
RunStart duration: 357
View structured, searchable error logs at https://nx.app/runs/5Wpaddn5MM


 NX   Cannot read properties of undefined (reading 'cacheError')

TypeError: Cannot read properties of undefined (reading 'cacheError')
    at $v.retrieve (C:\Work\KSDC\blue-file-web\.nx\cache\cloud\2411.13.2\index.js:34:3328)
    at DbCache.get (C:\Work\KSDC\blue-file-web\node_modules\nx\src\tasks-runner\cache.js:61:48)
    at TaskOrchestrator.applyCachedResult (C:\Work\KSDC\blue-file-web\node_modules\nx\src\tasks-runner\task-orchestrator.js:131:47)
    at C:\Work\KSDC\blue-file-web\node_modules\nx\src\tasks-runner\task-orchestrator.js:126:70
    at Array.map (<anonymous>)
    at TaskOrchestrator.applyCachedResults (C:\Work\KSDC\blue-file-web\node_modules\nx\src\tasks-runner\task-orchestrator.js:126:54)
    at TaskOrchestrator.applyFromCacheOrRunTask (C:\Work\KSDC\blue-file-web\node_modules\nx\src\tasks-runner\task-orchestrator.js:219:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TaskOrchestrator.executeNextBatchOfTasksUsingTaskSchedule (C:\Work\KSDC\blue-file-web\node_modules\nx\src\tasks-runner\task-orchestrator.js:85:13)     
    at async Promise.all (index 0)
```

### Package Manager Version

10.7.0

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

I see that the task _was_ executed successfully, but what about the caching errors or errors regarding module resultion, ie '_Was not able to require.resolve module nx/src/utils/app-root_ '

**Comment by ksdc-grantw** [comment]
@Cammisuli Hi, has there been any progress on this investigation? Thanks

**Comment by lucas-sesti** [comment]
Same issue here, how to resolve it?

**Comment by craigmatthew412** [comment]
I also have the same issue. I even made sure to connect to Nx Cloud using the `nx-cloud login` command and providing the PAT that I generated after running the `nx-cloud convert-to-nx-cloud-id` command as I saw there were 401 errors in the console. If I leave "useLegacyCache" in nx.json to true, it "works fine" but then uses the legacy cache and gives me the deprecation warnings...but setting to false or removing gives me the "Cannot read properties of undefined (reading 'cacheError')" error. I also noticed that the `convert-to-nx-cloud-id` command updated my nx.json using the "tasksRunnerOptions" property syntax instead of root "nxCloudId" syntax even though I am on version 20.2.1 of nx. I tried using both configuration syntaxes in nx.json to no avail. I am assuming we're missing some updates to the nx-cloud package since the latest is 19.1.0?

**Comment by just-be-weird** [comment]
Facing the same issue, was anyone able to fix this?

**Comment by nicolas-godefroy-dev** [comment]
I had the same issue, i fixed it by adding `"useLegacyCache": true` to my `nx.json`

**Comment by faileon** [comment]
I am having exactly the same  issue as described here. Only solution so far is to `  "useLegacyCache": true` running Nx v20.3.0

**Comment by sleeyax** [comment]
`"useLegacyCache": true` is not a real fix because it will be deprecated soon. I'm getting the same error and I don't know how to solve it. Anyone had better luck solving this?

**Comment by sleeyax** [comment]
I just figured it out thanks to this comment: https://github.com/nrwl/nx/issues/28757#issuecomment-2515360013.

Uninstalling the `nx-cloud` dependency (so it uses the bundled nx CLI instead) fixed it for me.

I also ran `npx nx-cloud convert-to-nx-cloud-id` so the `nxCloudAccessToken` field in my  `nx.json` config got replaced with:

```json
 "tasksRunnerOptions": {
    "default": {
      "runner": "nx-cloud",
      "options": {
        "nxCloudId": "<YOUR_ID>"
      }
    }
  }
```

So, in a nutshell:

```
npx nx-cloud convert-to-nx-cloud-id
npm uninstall nx-cloud
```

Then it should work.

**Comment by faileon** [comment]
Wow, what a gotcha, yeah that works! thanks @sleeyax

**Comment by ksdc-grantw** [comment]
Thanks @sleeyax .
