### ISSUE TITLE
MFE host cannot generate root ngrx state for app - broken

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#28970]
### Current Behavior

SUBJECT: MFE host cannot generate root ngrx state for app - broken

causes error
```
 NX  Generating @nx/angular:ngrx-root-store
 NX   Cannot read properties of null (reading 'length')
```

### Expected Behavior

should generate root ngrx state for MFE host app

### GitHub Repo

https://github.com/nhhockeyplayer/meanstacknh

### Steps to Reproduce

nx g @nx/angular:ngrx-root-store --project=host --minimal=false --name=root --addDevTools=true --facade=true --no-interactive --dry-run

### Nx Report

```shell
nx report

 NX   Report complete - copy this into the issue template

Node           : 22.9.0
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.9.0

nx (global)        : 20.0.0
nx                 : 20.1.2
@nx/js             : 20.1.2
@nx/jest           : 20.1.2
@nx/eslint         : 20.1.2
@nx/workspace      : 20.1.2
@nx/angular        : 20.1.2
@nx/cypress        : 20.1.2
@nx/devkit         : 20.1.2
@nx/esbuild        : 20.1.2
@nx/eslint-plugin  : 20.1.2
@nx/express        : 20.1.2
@nx/nest           : 20.1.2
@nx/node           : 20.1.2
@nx/playwright     : 20.1.2
@nx/vite           : 20.1.2
@nx/web            : 20.1.2
@nx/webpack        : 20.1.2
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
@nx/playwright/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc               : 1.1.26
@fortawesome/angular-fontawesome : 0.15.0
@ionic/angular                   : 6.7.5
@jsverse/transloco               : 7.5.0
@ngrx/component                  : 18.0.2
@ngrx/component-store            : 18.0.2
@ngrx/effects                    : 18.0.2
@ngrx/entity                     : 18.0.2
@ngrx/operators                  : 18.0.2
@ngrx/router-store               : 18.0.2
@ngrx/schematics                 : 18.0.2
@ngrx/store                      : 18.0.2
@ngrx/store-devtools             : 18.0.2
apollo-angular                   : 7.2.1
```

### Failure Logs

```shell
nx g @nx/angular:ngrx-root-store --project=host --minimal=false --name=root --addDevTools=true --facade=true --no-interactive --dry-run

 NX  Generating @nx/angular:ngrx-root-store


 NX   Cannot read properties of null (reading 'length')

TypeError: Cannot read properties of null (reading 'length')
    at createSourceFile2 (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32816:52)
    at parseSourceFileWorker (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32690:24)
    at Object.parseSourceFile (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32514:20)
    at Object.createSourceFile (/Users/meanstack02/meanstacknh/node_modules/typescript/lib/typescript.js:32348:21)
    at addImportsToModule (/Users/meanstack02/meanstacknh/node_modules/@nx/angular/src/generators/ngrx-root-store/lib/add-imports.js:65:31)
    at ngrxRootStoreGenerator (/Users/meanstack02/meanstacknh/node_modules/@nx/angular/src/generators/ngrx-root-store/ngrx-root-store.js:12:38)
    at /Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/generate/generate.js:240:32
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleErrors (/Users/meanstack02/meanstacknh/node_modules/nx/src/utils/handle-errors.js:8:24)
    at async Object.handler (/Users/meanstack02/meanstacknh/node_modules/nx/src/command-line/generate/command-object.js:13:22)
```

### Package Manager Version

npm --version 10.9.0

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

this is a show stopper I cannot get NgRX on the map for my hosts/apps

**Comment by nhhockeyplayer** [comment]
Hi
If this can be prioritized, 

the nx-console UI is failing with this error in the webstorm terminal
the mac terminal shows the failure too when executing the command manually

thanks for an awesome product

**Comment by nhhockeyplayer** [comment]
does anyone have a workaround for this issue?
How can I generate a rootState for my MFR host?
Thanks for any assist
