### ISSUE TITLE
Get error "Failed to process project graph" during run "nx@latest init"

### ISSUE THREAD

**Issue by Pavel-Liteiniy** [nrwl/nx#29108]
### Current Behavior

Hello! : ) Could you please help me with this issue?

I'm trying to add nx into my current project (next.js with app structure) but facing with errors:
- `Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.`
- `Error: Command failed: pnpm exec nx g @nx/eslint:init --keepExistingVersions --updatePackageScripts`

I'm using node v20.18.1, pnpm v9.14.2

Here is my package.json:
```
{
  "private": true,
  "scripts": {
    "dev": "NODE_OPTIONS='--inspect' next dev -p 3005",
    "build": "next build && cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/",
    "start": "node .next/standalone/server.js",
    "lint": "eslint . --cache",
    "ts": "tsc --noEmit",
    "supabase:types": "supabase gen types typescript --project-id PROJECT_ID > types/Database.ts",
    "format": "prettier --write .",
    "test": "jest",
    "test:watch": "jest --watch"
  },
  "dependencies": {
    "@hookform/resolvers": "^3.9.1",
    "@radix-ui/react-avatar": "^1.1.1",
    "@radix-ui/react-checkbox": "^1.1.2",
    "@radix-ui/react-dialog": "^1.1.2",
    "@radix-ui/react-dropdown-menu": "^2.1.2",
    "@radix-ui/react-label": "^2.1.0",
    "@radix-ui/react-navigation-menu": "^1.2.1",
    "@radix-ui/react-popover": "^1.1.2",
    "@radix-ui/react-scroll-area": "^1.2.1",
    "@radix-ui/react-select": "^2.1.2",
    "@radix-ui/react-separator": "^1.1.0",
    "@radix-ui/react-slot": "^1.1.0",
    "@radix-ui/react-switch": "^1.1.1",
    "@radix-ui/react-toast": "^1.2.2",
    "@radix-ui/react-toggle": "^1.1.0",
    "@radix-ui/react-tooltip": "^1.1.4",
    "@reduxjs/toolkit": "^2.3.0",
    "@supabase/ssr": "latest",
    "@supabase/supabase-js": "latest",
    "@swc-node/register": "^1.10.9",
    "@tanstack/react-table": "^8.20.5",
    "autoprefixer": "^10.4.20",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "cmdk": "^1.0.4",
    "cookies-next": "^4.3.0",
    "date-fns": "^3.6.0",
    "dayjs": "^1.11.13",
    "framer-motion": "^11.11.17",
    "geist": "^1.3.1",
    "lodash": "^4.17.21",
    "lucide-react": "^0.414.0",
    "next": "^14.2.18",
    "pluralize": "^8.0.0",
    "postcss": "^8.4.49",
    "qs": "^6.13.1",
    "react": "^18.3.1",
    "react-day-picker": "^8.10.1",
    "react-dom": "^18.3.1",
    "react-hook-form": "^7.53.2",
    "react-redux": "^9.1.2",
    "server-only": "^0.0.1",
    "tailwind-merge": "^2.5.5",
    "tailwindcss": "^3.4.15",
    "tailwindcss-animate": "^1.0.7",
    "typescript": "^5.7.2",
    "use-immer": "^0.10.0",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^6.6.3",
    "@testing-library/react": "^16.0.1",
    "@types/jest": "^29.5.14",
    "@types/lodash": "^4.17.13",
    "@types/node": "^22.10.0",
    "@types/pluralize": "^0.0.33",
    "@types/qs": "^6.9.17",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@typescript-eslint/eslint-plugin": "^8.16.0",
    "@typescript-eslint/parser": "^8.16.0",
    "encoding": "^0.1.13",
    "eslint": "^8.57.1",
    "eslint-config-next": "^14.2.18",
    "eslint-config-prettier": "^9.1.0",
    "eslint-config-standard": "^17.1.0",
    "eslint-plugin-import": "^2.31.0",
    "eslint-plugin-n": "^16.6.2",
    "eslint-plugin-prettier": "^5.2.1",
    "eslint-plugin-promise": "^6.6.0",
    "eslint-plugin-react": "^7.37.2",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "prettier": "^3.4.1",
    "prettier-plugin-tailwindcss": "^0.6.9",
    "ts-node": "^10.9.2",
    "type-fest": "^4.29.0"
  }
}
```

### Expected Behavior

https://nx.dev/recipes/adopting-nx/adding-to-existing-project#install-nx-on-a-nonmonorepo-project

### Steps to Reproduce

1. pnpm dlx nx@latest init --pm=pnpm

### Nx Report

```shell
pnpm dlx nx@latest report        

 NX   Report complete - copy this into the issue template

Node           : 22.11.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.14.2

nx (global)  : 20.1.3
nx           : 20.1.3
@nx/jest     : 20.1.3
@nx/eslint   : 20.1.3
@nx/next     : 20.1.3
typescript   : 5.7.2
---------------------------------------
⚠️ Unable to construct project graph.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the nx/core/package-json plugin.
    - package.json: Nx requires the root package.json to specify a name if it is being used as an Nx project.
      Error: Nx requires the root package.json to specify a name if it is being used as an Nx project.
          at buildProjectConfigurationFromPackageJson (/Users/liteiniy/pets/budget_buddy/node_modules/.pnpm/nx@20.1.3_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.5__@swc+types@0.1.14_typ_5eeec7e7tpteabjzkpwu5wg55q/node_modules/nx/src/plugins/package-json/create-nodes.js:105:15)
          at createNodeFromPackageJson (/Users/liteiniy/pets/budget_buddy/node_modules/.pnpm/nx@20.1.3_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.5__@swc+types@0.1.14_typ_5eeec7e7tpteabjzkpwu5wg55q/node_modules/nx/src/plugins/package-json/create-nodes.js:80:21)
          at /Users/liteiniy/pets/budget_buddy/node_modules/.pnpm/nx@20.1.3_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.5__@swc+types@0.1.14_typ_5eeec7e7tpteabjzkpwu5wg55q/node_modules/nx/src/plugins/package-json/create-nodes.js:36:20
          at /Users/liteiniy/pets/budget_buddy/node_modules/.pnpm/nx@20.1.3_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.5__@swc+types@0.1.14_typ_5eeec7e7tpteabjzkpwu5wg55q/node_modules/nx/src/project-graph/plugins/utils.js:10:33
          at Array.map (<anonymous>)
          at createNodesFromFiles (/Users/liteiniy/pets/budget_buddy/node_modules/.pnpm/nx@20.1.3_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.5__@swc+types@0.1.14_typ_5eeec7e7tpteabjzkpwu5wg55q/node_modules/nx/src/project-graph/plugins/utils.js:8:35)
          at exports.createNodesV2 (/Users/liteiniy/pets/budget_buddy/node_modules/.pnpm/nx@20.1.3_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.5__@swc+types@0.1.14_typ_5eeec7e7tpteabjzkpwu5wg55q/node_modules/nx/src/plugins/package-json/create-nodes.js:30:51)
          at LoadedNxPlugin.createNodes (/Users/liteiniy/pets/budget_buddy/node_modules/.pnpm/nx@20.1.3_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.5__@swc+types@0.1.14_typ_5eeec7e7tpteabjzkpwu5wg55q/node_modules/nx/src/project-graph/plugins/internal-api.js:34:65)
          at LoadedNxPlugin.createNodes.<computed> (/Users/liteiniy/pets/budget_buddy/node_modules/.pnpm/nx@20.1.3_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.5__@swc+types@0.1.14_typ_5eeec7e7tpteabjzkpwu5wg55q/node_modules/nx/src/project-graph/plugins/internal-api.js:44:34)
          at createNodes (/Users/liteiniy/pets/budget_buddy/node_modules/.pnpm/nx@20.1.3_@swc-node+register@1.10.9_@swc+core@1.9.1_@swc+helpers@0.5.5__@swc+types@0.1.14_typ_5eeec7e7tpteabjzkpwu5wg55q/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:66:63)
```

### Failure Logs

```shell
pnpm dlx nx@latest init --pm=pnpm

 NX   🐳 Nx initialization


 NX   🧑‍🔧 Please answer the following questions about the scripts found in your package.json in order to generate task runner configuration

✔ Which of the following scripts are cacheable? (Produce the same output given the same input, e.g. build, test and lint usually are, serve and start are not). You can use spacebar to select one or more scripts. · build, lint, ts, test


✔ Does the "build" script create any outputs? If not, leave blank, otherwise provide a path (e.g. dist, lib, build, coverage) · .next

✔ Does the "lint" script create any outputs? If not, leave blank, otherwise provide a path (e.g. dist, lib, build, coverage) · .eslintcache

✔ Does the "ts" script create any outputs? If not, leave blank, otherwise provide a path (e.g. dist, lib, build, coverage) · tsconfig.tsbuildinfo

✔ Does the "test" script create any outputs? If not, leave blank, otherwise provide a path (e.g. dist, lib, build, coverage) · .jestcache


 NX   📦 Installing dependencies

 WARN  deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
 WARN  7 deprecated subdependencies found: @humanwhocodes/config-array@0.13.0, @humanwhocodes/object-schema@2.0.3, abab@2.0.6, domexception@4.0.0, glob@7.2.3, inflight@1.0.6, rimraf@3.0.2
Already up to date
Progress: resolved 847, reused 811, downloaded 0, added 0, done
Done in 2.6s
✔ Would you like remote caching to make your build faster? · yes

 NX   🧐 Checking dependencies


 NX   Recommended Plugins:

Add these Nx plugins to integrate with the tools used in your workspace.

✔ Which plugins would you like to add? Press <Space> to select and <Enter> to submit. · @nx/eslint, @nx/jest, @nx/next

✔ Do you want to start using Nx in your package.json scripts? · Yes

 NX   📦 Installing Nx

 WARN  deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
 WARN  7 deprecated subdependencies found: @humanwhocodes/config-array@0.13.0, @humanwhocodes/object-schema@2.0.3, abab@2.0.6, domexception@4.0.0, glob@7.2.3, inflight@1.0.6, rimraf@3.0.2
Packages: +561
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1413, reused 1365, downloaded 0, added 561, done

devDependencies:
+ @nx/eslint 20.1.3
+ @nx/jest 20.1.3
+ @nx/next 20.1.3

Done in 11s

 NX   🔨 Configuring plugins


 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

nx init

Adds Nx to any type of workspace. It installs nx, creates an nx.json configuration file and optionally sets up
remote caching. For more info, check https://nx.dev/recipes/adopting-nx.

Options:
  --help                  Show help                                                                       [boolean]
  --version               Show version number                                                             [boolean]
  --nxCloud               Set up distributed caching with Nx Cloud.                                       [boolean]
  --interactive           When false disables interactive input prompts for options.      [boolean] [default: true]
  --useDotNxInstallation  Initialize an Nx workspace setup in the .nx directory of the current repository.
                                                                                         [boolean] [default: false]

Error: Command failed: pnpm exec nx g @nx/eslint:init --keepExistingVersions --updatePackageScripts
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:888:11)
    at execSync (node:child_process:960:15)
    at installPlugins (/Users/liteiniy/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1937272575a-9a77/node_modules/.pnpm/nx@20.1.3/node_modules/nx/src/command-line/init/init-v2.js:32:38)
    at Object.initHandler (/Users/liteiniy/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1937272575a-9a77/node_modules/.pnpm/nx@20.1.3/node_modules/nx/src/command-line/init/init-v2.js:101:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handler (/Users/liteiniy/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1937272575a-9a77/node_modules/.pnpm/nx@20.1.3/node_modules/nx/src/command-line/init/command-object.js:12:13) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 84420,
  stdout: null,
  stderr: null
}
```

### Package Manager Version

pnpm v9.14.2

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Pavel-Liteiniy** [comment]
Hey! I think that it's fixed. It seems that the problem was with package.json file - it hadn't `name` prop
