### ISSUE TITLE
Error: The externalDependency 'webpack-cli' for 'project:build' could not be found

### ISSUE THREAD

**Issue by Fafnur** [nrwl/nx#29116]
### Current Behavior

If you add yarn.lock to .gitignore for a monorepo with nestjs, the project will crash with an error. 

 ![Image](https://github.com/user-attachments/assets/80854569-31d6-4e3d-ae1b-e53af4f1a551)

Error message: 

```bash
NX   Daemon process terminated and closed the connection

Please rerun the command, which will restart the daemon.
If you get this error again, check for any errors in the daemon process logs found in: /mnt/Storage/Development/angular/nx-gitignore-bug/.nx/workspace-data/d/daemon.log
```

If you remove yarn.lock from .gitignore, everything is fine.

![Image](https://github.com/user-attachments/assets/fd52005d-68e4-4452-91a5-104c02379a98)

### Expected Behavior

Adding yarn.lock should not affect server startup with yarn.

### GitHub Repo

https://github.com/Fafnur/nx-gitignore-bug

### Steps to Reproduce

1. Generate a new workspace with nx ![Image](https://github.com/user-attachments/assets/b80c1075-e0d7-4a75-bd57-2379becbb13c)
2. Set yarn as default manager  in package.json `"packageManager": "yarn@4.5.3"`
3. Create .yarnrc.yml with content `nodeLinker: node-modules`
4. Add `yarn.lock` in .gitignore

### Nx Report

```shell
Node           : 22.11.0
OS             : linux-x64
Native Target  : x86_64-linux
yarn           : 4.5.3

nx                 : 20.1.4
@nx/js             : 20.1.4
@nx/jest           : 20.1.4
@nx/eslint         : 20.1.4
@nx/workspace      : 20.1.4
@nx/devkit         : 20.1.4
@nx/eslint-plugin  : 20.1.4
@nx/nest           : 20.1.4
@nx/node           : 20.1.4
@nx/web            : 20.1.4
@nx/webpack        : 20.1.4
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
/mnt/Storage/Development/angular/taro/node_modules/nx/src/hasher/native-task-hasher-impl.js:32
        const plans = this.planner.getPlansReference(tasks.map((t) => t.id), taskGraph);
                                   ^

Error: The externalDependency 'webpack-cli' for 'backend:build' could not be found
    at NativeTaskHasherImpl.hashTasks (/mnt/Storage/Development/angular/taro/node_modules/nx/src/hasher/native-task-hasher-impl.js:32:36)
    at InProcessTaskHasher.hashTasks (/mnt/Storage/Development/angular/taro/node_modules/nx/src/hasher/task-hasher.js:41:46)
    at handleHashTasks (/mnt/Storage/Development/angular/taro/node_modules/nx/src/daemon/server/handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleResult (/mnt/Storage/Development/angular/taro/node_modules/nx/src/daemon/server/server.js:172:16)
    at async handleMessage (/mnt/Storage/Development/angular/taro/node_modules/nx/src/daemon/server/server.js:110:9)
    at async /mnt/Storage/Development/angular/taro/node_modules/nx/src/daemon/server/server.js:72:9 {
  code: 'GenericFailure'
}

Node.js v22.11.0
```

### Package Manager Version

4.5.3

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mataai** [comment]
I have the same exact problem. Added package-lock.json to gitignore monorepo wouldn't start even after re-cloning the repo and fresh modules install. 
![Image](https://github.com/user-attachments/assets/f9e08b30-74f0-4855-b881-48c559deee26)

Removing package-lock.json from .gitignore instantly fixed it.

**Comment by sfd-mhrana** [comment]
i also face same problem in my nx with nest and angular app.

Error: The externalDependency 'webpack-cli' for 'ECOMMERCE-API:build' could not be found
    at NativeTaskHasherImpl.hashTasks (E:\Rana\Test\ECOMMERCE\node_modules\nx\src\hasher\native-task-hasher-impl.js:33:36)
    at InProcessTaskHasher.hashTasks (E:\Rana\Test\ECOMMERCE\node_modules\nx\src\hasher\task-hasher.js:41:46)
    at handleHashTasks (E:\Rana\Test\ECOMMERCE\node_modules\nx\src\daemon\server\handle-hash-tasks.js:30:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleResult (E:\Rana\Test\ECOMMERCE\node_modules\nx\src\daemon\server\server.js:172:16)
    at async handleMessage (E:\Rana\Test\ECOMMERCE\node_modules\nx\src\daemon\server\server.js:110:9)
    at async E:\Rana\Test\ECOMMERCE\node_modules\nx\src\daemon\server\server.js:72:9 {
  code: 'GenericFailure'
}

**Comment by ahmadelafify** [comment]
Error resolved for me after deleting my `bun.lockb` that I forgot about after attempting to get bun to be reliable with NX. After deleting that lock file and sticking with npm, all is working well now

**Comment by MNPCMW6444** [comment]
Happening to me also. Using macos and node lts (v22.14.0), creating a fresh project:
`npx create-nx-workspace somename --preset=nest`
then running `nx serve appname` produces this bug

**Comment by MNPCMW6444** [comment]
@Coly010 if you want i can try to fix this

**Comment by ArinSantry** [comment]
> I have the same exact problem. Added package-lock.json to gitignore monorepo wouldn't start even after re-cloning the repo and fresh modules install. Removing package-lock.json from .gitignore instantly fixed it.

This fixed my issue, thank you @mataai

**Comment by jessicamrbr** [comment]
https://github.com/nrwl/nx/issues/28385#issuecomment-2885275280

**Comment by Coly010** [comment]
Lockfiles should not be placed in the `.gitignore` file. 
They are necessary for consistent packages and reproducibility. 

Nx is designed to take into account what you have in your `.gitignore` file and _not_ process anything that matches the path patterns within it.

Nx is _also_ designed to read your package-lock file to determine the dependencies and packages used in your workspace.

By placing your lockfiles in the `.gitignore` file, Nx will not process them, resulting in these errors.
