### ISSUE TITLE
ConfigService Injection Issue in Nx/NestJS Library

### ISSUE THREAD

**Issue by ziyadev** [nrwl/nx#29136]
### Current Behavior
I created a new Nx-based NestJS library and used the ConfigService from @nestjs/config. The ConfigModule is imported in the library, and the ConfigService is injected into one of the services. However, when I use this service in a consuming NestJS app, I encounter the following error:
```bash
[Nest] 21784  - 12/01/2024, 7:33:51 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'get')

TypeError: Cannot read properties of undefined (reading 'get')
    at EnvService.getServerEnv (/Users/ziyadev/Desktop/repos/fannaq/dist/apps/testing/webpack:/packages/env/src/nestjs/env.service.ts:12:38)
```
This indicates that ConfigService is not properly injected, even though ConfigModule has been imported both in the library and as a global module in the app.

 

 

 

### Expected Behavior

The ConfigService should be correctly injected into the library service, and configuration values should be accessible without errors.

### Steps to Reproduce

1.

### Nx Report

```shell
Node           : 20.15.1
OS             : darwin-x64
Native Target  : x86_64-macos

nx (global)        : 20.0.0
nx                 : 20.0.0
@nx/nest           : 20.0.0
@nx/workspace      : 20.0.0
@nestjs/config     : 2.3.1
typescript         : 5.5.4
```

### Failure Logs

```shell
> nx run testing:build:development

asset main.js 11.6 KiB [emitted] (name: main) 1 related asset
asset assets/.gitkeep 0 bytes [emitted] [from: apps/testing/src/assets/.gitkeep] [copied]
orphan modules 2.77 KiB [orphan] 4 modules
runtime modules 670 bytes 3 modules
built modules 8.16 KiB [built]
  modules by path ./ 8.04 KiB
    modules by path ./apps/testing/src/app/*.ts 4.56 KiB
      ./apps/testing/src/app/app.module.ts 1.34 KiB [built] [code generated]
      ./apps/testing/src/app/app.controller.ts 1.6 KiB [built] [code generated]
      ./apps/testing/src/app/app.service.ts 1.62 KiB [built] [code generated]
    ./apps/testing/src/main.ts 665 bytes [built] [code generated]
    ./packages/env/src/nestjs/index.ts + 4 modules 2.83 KiB [not cacheable] [built] [code generated]
  modules by path external "@nestjs/ 126 bytes
    external "@nestjs/common" 42 bytes [built] [code generated]
    external "@nestjs/core" 42 bytes [built] [code generated]
    external "@nestjs/config" 42 bytes [built] [code generated]
webpack 5.96.1 compiled successfully in 7317 ms

———————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Successfully ran target build for project testing (13s)

Debugger listening on ws://localhost:9229/d9d08e05-e76b-4972-98e9-200ab780f2ab

Debugger listening on ws://localhost:9229/d9d08e05-e76b-4972-98e9-200ab780f2ab
For help, see: https://nodejs.org/en/docs/inspector

[Nest] 21784  - 12/01/2024, 7:33:41 AM     LOG [NestFactory] Starting Nest application...
[Nest] 21784  - 12/01/2024, 7:33:41 AM     LOG [InstanceLoader] EnvModule dependencies initialized +25ms
[Nest] 21784  - 12/01/2024, 7:33:41 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +3ms
[Nest] 21784  - 12/01/2024, 7:33:41 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 21784  - 12/01/2024, 7:33:41 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 21784  - 12/01/2024, 7:33:41 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 21784  - 12/01/2024, 7:33:41 AM     LOG [RoutesResolver] AppController {/api}: +11ms
[Nest] 21784  - 12/01/2024, 7:33:41 AM     LOG [RouterExplorer] Mapped {/api, GET} route +4ms
[Nest] 21784  - 12/01/2024, 7:33:41 AM     LOG [NestApplication] Nest application successfully started +3ms
[Nest] 21784  - 12/01/2024, 7:33:41 AM     LOG 🚀 Application is running on: http://localhost:3000/api
[Nest] 21784  - 12/01/2024, 7:33:50 AM     LOG [EnvService] undefined
[Nest] 21784  - 12/01/2024, 7:33:51 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'get')

TypeError: Cannot read properties of undefined (reading 'get')
    at EnvService.getServerEnv (/Users/ziyadev/Desktop/repos/fannaq/dist/apps/testing/webpack:/packages/env/src/nestjs/env.service.ts:12:38)
    at AppService.getData (/Users/ziyadev/Desktop/repos/fannaq/dist/apps/testing/webpack:/apps/testing/src/app/app.service.ts:12:32)
    at AppController.getData (/Users/ziyadev/Desktop/repos/fannaq/dist/apps/testing/webpack:/apps/testing/src/app/app.controller.ts:11:28)
    at /Users/ziyadev/Desktop/repos/fannaq/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at InterceptorsConsumer.intercept (/Users/ziyadev/Desktop/repos/fannaq/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:12:20)
    at /Users/ziyadev/Desktop/repos/fannaq/node_modules/@nestjs/core/router/router-execution-context.js:46:60
    at /Users/ziyadev/Desktop/repos/fannaq/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/Users/ziyadev/Desktop/repos/fannaq/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ziyadev/Desktop/repos/fannaq/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/Users/ziyadev/Desktop/repos/fannaq/node_modules/express/lib/router/route.js:119:3)
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ziyaDev** [comment]
The issue seems to be related to the SWC compiler. In the webpack.config.js, changing the compiler option from swc to tsc resolves the problem:

```typescript
...
NxAppWebpackPlugin({
      target: 'node',
      compiler: 'tsc', // Switched from 'swc' to 'tsc' and the issue is gone
     ...
 
    }),
```

**Comment by ndcunningham** [comment]
Hi, thanks for reporting this issue.

Can you provide a small repro highlighting the issue?

NestJS has a specific requirement for monorepos, it could be that we missed something for `NxAppWebpackPlugin`

**Comment by ziyaDev** [comment]
Here’s a small repro along with the NxAppWebpackPlugin configuration I’m using:

``` typescript
const { NxAppWebpackPlugin } = require('@nx/webpack/app-plugin');
const { join } = require('node:path');

module.exports = {
  output: {
    path: join(__dirname, '../../dist/apps/testing'),
  },
  plugins: [
    new NxAppWebpackPlugin({
      target: 'node',
      compiler: 'tsc',
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      assets: ['./src/assets'],
      optimization: false,
      outputHashing: 'none',
      generatePackageJson: false,
      progress: false,
    }),
  ],
};
```
project.json:
```json
"targets": {
    "build": {
      "executor": "@nx/webpack:webpack",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/testing",
        "webpackConfig": "apps/testing/webpack.config.cjs",
        "main": "apps/testing/src/main.ts",
        "tsConfig": "apps/testing/tsconfig.app.json",
        "assets": ["apps/testing/src/assets"],
        "inspect": true
      },
      "configurations": {
        "development": {},
        "production": {}
      }
    },
    "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "dependsOn": [
        "build",
        {
          "dependencies": true,
          "target": "build"
        }
      ],
      "options": {
        "buildTarget": "testing:build",
        "runBuildTargetDependencies": true
      },
      "configurations": {
        "development": {
          "buildTarget": "testing:build:development"
        },
        "production": {
          "buildTarget": "testing:build:production"
        }
      }
    }
  }
```

**Comment by eXist-FraGGer** [comment]
Same problem, without webpack.

project.json
```json
{
  "name": "auth",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "{projectRoot}/src",
  "projectType": "application",
  "tags": [],
  "targets": {
    "build": {
      "executor": "@nx/rspack:rspack",
      "cache": true,
      "options": {
        "target": "node",
        "outputPath": "{workspaceRoot}/build/apps/auth",
        "outputHashing": "none",
        "main": "{projectRoot}/src/main.ts",
        "tsConfig": "{projectRoot}/tsconfig.app.json",
        "rspackConfig": "{projectRoot}/rspack.config.ts",
        "assets": [],
        "generatePackageJson": true
      }
    }
  }
}
```

rspack.config.ts
```typescript
import { composePlugins, withNx } from '@nx/rspack';

export default composePlugins(withNx());
```

tsconfig.app.json
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "types": [
      "node"
    ],
    "emitDecoratorMetadata": true,
    "target": "es2021"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "src/**/*.spec.ts",
    "src/**/*.test.ts"
  ]
}
```

Points:
1. I had to add `"outputHashing": "none"`, because of now it is outputing `main.[hash].js` (not like in @nx/rspack 20.1.*)
2. TS compiler option `"emitDecoratorMetadata": true` is added, but it is losing decorators and the injection does not work.
3. "@nx/rspack": "20.1.4" - works fine

**Comment by zvn2060** [comment]
> Same problem, with rspack.

It seems due to the module.rules process the typescript wrongly

https://github.com/nrwl/nx/blob/f24a869b67f4de3db678cec7c18bb054e790bfa1/packages/rspack/src/plugins/utils/apply-base-config.ts#L396-L425

when I remove above lines in node_modules dirtyly, and add below code according to the **rspack official nestjs example**

https://github.com/nrwl/nx/blob/f24a869b67f4de3db678cec7c18bb054e790bfa1/packages/rspack/src/plugins/utils/apply-base-config.ts#L396-L425

the nestjs work correctly.

**Comment by eXist-FraGGer** [comment]
@zvn2060 I just investigated what is generating `withNx` and found the small difference.

So I have created a small plugin that fixes the `config module rules`.

@ndcunningham I hope it will help you to understand the problem and add this to a next fix/release.

The original rule:
```json
{
        "test": {},
        "loader": "builtin:swc-loader",
        "exclude": {},
        "type": "javascript/auto",
        "options": {
            "jsc": {
                "parser": {
                    "syntax": "typescript",
                    "decorators": true,
                    "tsx": true
                },
                "transform": {
                    "react": {
                        "runtime": "automatic",
                        "pragma": "React.createElement",
                        "pragmaFrag": "React.Fragment",
                        "throwIfNamespace": true,
                        "development": false,
                        "refresh": false,
                        "useBuiltins": false
                    }
                }
            }
        }
    }
```

As we can see there are no `rule.options.jsc.transform.legacyDecorator` and `rule.options.jsc.transform.decoratorMetadata`.

Solution:
rspack.config.ts
```typescript
import { composePlugins, withNx } from '@nx/rspack';

export default composePlugins(
  withNx(),
  (config) => {
    config.module.rules = config.module.rules.map((rule) => {
      if (typeof rule === 'object' && 'loader' in rule && rule.loader === 'builtin:swc-loader') {
        (rule.options as any).jsc.transform.legacyDecorator = true;
        (rule.options as any).jsc.transform.decoratorMetadata = true;
      }

      return rule;
    });

    return config;
  },
);
```

In this case it still works together with `NX` and target executor `@nx/rspack:rspack`, everything can be easily configured with replacements like `{workspaceRoot}`, `{projectRoot}` and etc.

**Comment by ndcunningham** [comment]
Hey! Thanks for the feedback and examples they are appreciated.
I see that there is an issue with `swc` relating to how it handles decorators.

A PR will be out shortly and then you should be able to access the changes in the follow-up release.
