### ISSUE TITLE
`pnpm dlx nx@latest init` failed

### ISSUE THREAD

**Issue by zmzlois** [nrwl/nx#29159]
### Current Behavior

initialise a project in an Nx workspace (not generated by Nx) run into failure 
ran command: `pnpm dlx nx@latest init` in sub folder: `apps/MobileHost` 
output: 
```
Packages: +106
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 115, reused 106, downloaded 0, added 106, done
Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1938a7617d9-ed5d/node_modules/.pnpm/nx@20.1.4/node_modules/nx: Running postinstall script, done in 632ms

 NX   🐳 Nx initialization


 NX   🧑‍🔧 Please answer the following questions about the scripts found in your package.json in order to generate task runner configuration

✔ Which of the following scripts are cacheable? (Produce the same output given the same input, e.g. build, test and lint usually are, serve and start are not). You can use spacebar to select one or more scripts. · android, ios, start

✔ Does the "android" script create any outputs? If not, leave blank, otherwise provide a path (e.g. dist, lib, build, coverage) ·
✔ Does the "ios" script create any outputs? If not, leave blank, otherwise provide a path (e.g. dist, lib, build, coverage) ·
✔ Does the "start" script create any outputs? If not, leave blank, otherwise provide a path (e.g. dist, lib, build, coverage) ·

 NX   📦 Installing dependencies

npm error code 127
npm error path /Users/lois/Documents/GitHub/zephyr/test/zephyr-merch/node_modules/.pnpm/webpack@5.96.1_@swc+core@1.5.29_@swc+helpers@0.5.15_/node_modules/webpack
npm error command failed
npm error command sh -c husky
npm error sh: husky: command not found
npm error A complete log of this run can be found in: /Users/lois/.npm/_logs/2024-12-03T03_03_44_236Z-debug-0.log
nx init

Adds Nx to any type of workspace. It installs nx, creates an nx.json configuration file and optionally sets up remote caching. For more info, check
https://nx.dev/recipes/adopting-nx.

Options:
  --help                  Show help                                                                                                                               [boolean]
  --version               Show version number                                                                                                                     [boolean]
  --nxCloud               Set up distributed caching with Nx Cloud.                                                                                               [boolean]
  --interactive           When false disables interactive input prompts for options.                                                              [boolean] [default: true]
  --useDotNxInstallation  Initialize an Nx workspace setup in the .nx directory of the current repository.                                       [boolean] [default: false]

Error: Command failed: npm install
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runInstall (/Users/lois/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1938a7617d9-ed5d/node_modules/.pnpm/nx@20.1.4/node_modules/nx/src/command-line/init/implementation/utils.js:145:34)
    at addNxToNpmRepo (/Users/lois/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1938a7617d9-ed5d/node_modules/.pnpm/nx@20.1.4/node_modules/nx/src/command-line/init/implementation/add-nx-to-npm-repo.js:67:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.initHandler (/Users/lois/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1938a7617d9-ed5d/node_modules/.pnpm/nx@20.1.4/node_modules/nx/src/command-line/init/init-v2.js:83:9)
    at async Object.handler (/Users/lois/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1938a7617d9-ed5d/node_modules/.pnpm/nx@20.1.4/node_modules/nx/src/command-line/init/command-object.js:12:13) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 61825,
  stdout: null,
  stderr: null
}
```

### Expected Behavior

initialise the application (the nice project.json) in this application

### GitHub Repo

https://github.com/zmzlois/zephyr-merch

### Steps to Reproduce

1. `git clone https://github.com/zmzlois/zephyr-merch`
2. `cd zephyr-merch/apps/MobileHost` 
3. `pnpm dlx nx@latest init`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.12.2
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.2

nx (global)        : 20.1.4
nx                 : 20.1.4
@nx/js             : 20.1.4
@nx/eslint         : 20.1.4
@nx/eslint-plugin  : 20.1.4
@nx/react          : 20.1.4
@nx/rspack         : 20.1.4
@nx/vite           : 20.1.4
@nx/web            : 20.1.4
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/vite/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
Packages: +106
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 115, reused 106, downloaded 0, added 106, done
Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1938a7617d9-ed5d/node_modules/.pnpm/nx@20.1.4/node_modules/nx: Running postinstall script, done in 632ms

 NX   🐳 Nx initialization


 NX   🧑‍🔧 Please answer the following questions about the scripts found in your package.json in order to generate task runner configuration

✔ Which of the following scripts are cacheable? (Produce the same output given the same input, e.g. build, test and lint usually are, serve and start are not). You can use spacebar to select one or more scripts. · android, ios, start

✔ Does the "android" script create any outputs? If not, leave blank, otherwise provide a path (e.g. dist, lib, build, coverage) ·
✔ Does the "ios" script create any outputs? If not, leave blank, otherwise provide a path (e.g. dist, lib, build, coverage) ·
✔ Does the "start" script create any outputs? If not, leave blank, otherwise provide a path (e.g. dist, lib, build, coverage) ·

 NX   📦 Installing dependencies

npm error code 127
npm error path /Users/lois/Documents/GitHub/zephyr/test/zephyr-merch/node_modules/.pnpm/webpack@5.96.1_@swc+core@1.5.29_@swc+helpers@0.5.15_/node_modules/webpack
npm error command failed
npm error command sh -c husky
npm error sh: husky: command not found
npm error A complete log of this run can be found in: /Users/lois/.npm/_logs/2024-12-03T03_03_44_236Z-debug-0.log
nx init

Adds Nx to any type of workspace. It installs nx, creates an nx.json configuration file and optionally sets up remote caching. For more info, check
https://nx.dev/recipes/adopting-nx.

Options:
  --help                  Show help                                                                                                                               [boolean]
  --version               Show version number                                                                                                                     [boolean]
  --nxCloud               Set up distributed caching with Nx Cloud.                                                                                               [boolean]
  --interactive           When false disables interactive input prompts for options.                                                              [boolean] [default: true]
  --useDotNxInstallation  Initialize an Nx workspace setup in the .nx directory of the current repository.                                       [boolean] [default: false]

Error: Command failed: npm install
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runInstall (/Users/lois/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1938a7617d9-ed5d/node_modules/.pnpm/nx@20.1.4/node_modules/nx/src/command-line/init/implementation/utils.js:145:34)
    at addNxToNpmRepo (/Users/lois/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1938a7617d9-ed5d/node_modules/.pnpm/nx@20.1.4/node_modules/nx/src/command-line/init/implementation/add-nx-to-npm-repo.js:67:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.initHandler (/Users/lois/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1938a7617d9-ed5d/node_modules/.pnpm/nx@20.1.4/node_modules/nx/src/command-line/init/init-v2.js:83:9)
    at async Object.handler (/Users/lois/Library/Caches/pnpm/dlx/ea3d7dajaiyrxizdg2nflyuquu/1938a7617d9-ed5d/node_modules/.pnpm/nx@20.1.4/node_modules/nx/src/command-line/init/command-object.js:12:13) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 61825,
  stdout: null,
  stderr: null
}
```

### Package Manager Version

pnpm 9.12.1

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by zmzlois** [comment]
There is no command to generate a project.json for an app
