### ISSUE TITLE
Vite Build Executor: Can't control output directory using a project's Vite config

### ISSUE THREAD

**Issue by wilcoxmd** [nrwl/nx#29168]
### Current Behavior

Hi! When using the `@nx/vite:build` executor, I'd like to be able to set the `build.outDir` value in my `vite.config.ts`, rather than needing to specify an `outputPath` in our `project.json` or on the NX CLI. This may be the intent already, since the [outputPath setting](https://github.com/nrwl/nx/blob/3ec539065dded9e02e7eeedf13993fac706b71e7/packages/vite/src/executors/build/schema.d.ts#L6) is optional.

When I try to do this and omit the `outputPath` configuration, an error is thrown: 

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1175:7)
    at joinPathFragments (<path-to-workspace>/node_modules/nx/src/utils/path.js:23:31)
    at viteBuildExecutor (<path-to-workspace>/node_modules/@nx/vite/src/executors/build/build.impl.js:45:72)
    ... rest of stack trace omitted
```

It looks like the issue might be with [this logic](https://github.com/nrwl/nx/blob/3ec539065dded9e02e7eeedf13993fac706b71e7/packages/vite/src/executors/build/build.impl.ts#L69-L71), which doesn't check for the whether `outputPath` exists before trying to create a path using it. 

### Expected Behavior

If `outputPath` is not defined in project.json or on the NX CLI, I'd like the value I set in my Vite configuration's `build.outDir` setting to be used to determine the output directory.

### GitHub Repo

https://github.com/wilcoxmd/vite-nx-no-outputPath

### Steps to Reproduce

Reproduction steps are listed in the example repo. 

### Nx Report

```shell
Node           : 20.5.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 9.8.0

nx                 : 20.1.4
@nx/js             : 20.1.4
@nx/eslint         : 20.1.4
@nx/workspace      : 20.1.4
@nx/devkit         : 20.1.4
@nx/eslint-plugin  : 20.1.4
@nx/react          : 20.1.4
@nx/vite           : 20.1.4
@nx/web            : 20.1.4
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
```

### Package Manager Version

npm --version
9.8.0

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Happy to help patch this if you can confirm whether this behavior is or isn't intentional, and provide guidance on any other considerations!

**Comment by Coly010** [comment]
Hey @wilcoxmd ! 

It seems like what you really want is for your config file to dictate how your vite build operates. 

If that is the case, then Inferred Tasks are worth looking into: https://nx.dev/concepts/inferred-tasks

The shift in mentality here is that the config file is the source of truth for the build.
You also do not need an executor or a target in your project.json when you use inferred tasks, as they are inferred from the vite config itself.

With an executor, the options in the project.json are seen as the source of truth and are used to override what is in the config file.

If you want to switch to using inferred tasks, you can check our the `convert-to-inferred` generator: https://nx.dev/nx-api/vite/generators/convert-to-inferred

More info: https://nx.dev/recipes/running-tasks/convert-to-inferred
