### ISSUE TITLE
Can't use non-angular schematics if project has angular.json

### ISSUE THREAD

**Issue by gavindoughtie-aon** [nrwl/nx#2916]
## Expected Behavior

`npm i --save-dev @aiao/stencil-toolkit`
`nx g @aiao/stencil-toolkit library --directory=mylibs --name=web-components`

Should result in a new library under libs/mylibs/web-components

## Current Behavior

What is the current behavior?

An unhandled exception occurred: Schematic "@aiao/stencil-toolkit" not found in collection "@nrwl/angular".
See "/private/var/folders/8c/bq32p1p92rx0qkmjy1g5vnch0000gn/T/ng-IbKGYf/angular-errors.log" for further details.

## Failure Information (for bugs)

```
[error] Error: Schematic "@aiao/stencil-toolkit" not found in collection "@nrwl/angular".
    at SchematicEngine.createSchematic (/Users/gavin/Projects/monorepo/aon/node_modules/@angular-devkit/schematics/src/engine/engine.js:232:23)
    at CollectionImpl.createSchematic (/Users/gavin/Projects/monorepo/aon/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at GenerateCommand.getSchematic (/Users/gavin/Projects/monorepo/aon/node_modules/@angular/cli/models/schematic-command.js:134:27)
    at GenerateCommand.initialize (/Users/gavin/Projects/monorepo/aon/node_modules/@angular/cli/models/schematic-command.js:44:36)
    at async GenerateCommand.initialize (/Users/gavin/Projects/monorepo/aon/node_modules/@angular/cli/commands/generate-impl.js:12:9)
    at async GenerateCommand.validateAndRun (/Users/gavin/Projects/monorepo/aon/node_modules/@angular/cli/models/command.js:124:9)
    at async Object.runCommand (/Users/gavin/Projects/monorepo/aon/node_modules/@angular/cli/models/command-runner.js:201:24)
    at async default_1 (/Users/gavin/Projects/monorepo/aon/node_modules/@angular/cli/lib/cli/index.js:62:31)
```
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. ...

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results here if you are using Nx 8.6.1 or greater_)
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails
```nx report

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.2.2
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : 9.2.2
  @nrwl/jest : 9.2.2
  @nrwl/linter : 9.2.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3
```

**Comment by gavindoughtie-aon** [comment]
Syntax error on my part. Should be:

`nx g @aiao/stencil-toolkit:library --directory=cre --name=web-components`
