### ISSUE TITLE
Generated @nx/react:library Rollup Config Incompatible with package.json type: module in Nx 20.2.0-beta.6

### ISSUE THREAD

**Issue by ashkanhosseini** [nrwl/nx#29193]
### Current Behavior

Current Behavior
When creating a new library using `@nx/react@20.2.0-beta.6` with TypeScript's composite mode (using ts references) and Rollup as the bundler, the generated rollup.config.js file is in CommonJS format. However, the package’s package.json includes "type": "module", which means all .js files are treated as ES Modules.

This results in an error when running any Nx commands (e.g., nx build, nx sync):

```
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
An error occurred while processing files for the @nx/rollup/plugin plugin.
- packages/package-1/rollup.config.js: Node tried to load your configuration as an ES module even though it is likely CommonJS. To resolve this, change the extension of your configuration to ".cjs" or pass the "--bundleConfigAsCjs" flag.

Original error: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'packages/package-1/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

```

Other commands such as nx lint also fail due to the same issue in eslint.config.js:

```
packages/package-1/eslint.config.js: require is not defined in ES module scope, you can use import instead

```

### Expected Behavior

The generated rollup.config.js should either:

1. Be written in ES module syntax to match the "type": "module" in the package.json.
2. Use a .cjs extension to indicate that it is CommonJS.

### GitHub Repo

https://github.com/ashkanhosseini/nx-next-release/pull/1/files

### Steps to Reproduce

1. clone [this repo](https://github.com/ashkanhosseini/nx-next-release/pull/1/files) 
2. switch to rollup-config-issue branch 
3. run yarn 
4. run `npx nx build package-1`

Alternatively create a new package by running `npx nx g @nx/react:library packages/package-1 --bundler=rollup --publishable --importPath=@myorg/package-1 --verbose` and then run `npx nx sync`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.11.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 1.22.22

nx                 : 20.2.0-beta.6
@nx/js             : 20.2.0-beta.6
@nx/jest           : 20.2.0-beta.6
@nx/eslint         : 20.2.0-beta.6
@nx/workspace      : 20.2.0-beta.6
@nx/devkit         : 20.2.0-beta.6
@nx/eslint-plugin  : 20.2.0-beta.6
@nx/react          : 20.2.0-beta.6
@nx/rollup         : 20.2.0-beta.6
@nx/web            : 20.2.0-beta.6
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/eslint/plugin
@nx/rollup/plugin
@nx/jest/plugin
---------------------------------------
⚠️ Unable to construct project graph.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/rollup/plugin plugin.
    - packages/package-1/rollup.config.js: Node tried to load your configuration as an ES module even though it is likely CommonJS. To resolve this, change the extension of your configuration to ".cjs" or pass the "--bundleConfigAsCjs" flag.
  
  Original error: require is not defined in ES module scope, you can use import instead
  This file is being treated as an ES module because it has a '.js' file extension and '/Users/ashkanhosseini/projects/nx-next-release/packages/package-1/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
      ReferenceError: Node tried to load your configuration as an ES module even though it is likely CommonJS. To resolve this, change the extension of your configuration to ".cjs" or pass the "--bundleConfigAsCjs" flag.
      
      Original error: require is not defined in ES module scope, you can use import instead
      This file is being treated as an ES module because it has a '.js' file extension and '/Users/ashkanhosseini/projects/nx-next-release/packages/package-1/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
          at file:///Users/ashkanhosseini/projects/nx-next-release/packages/package-1/rollup.config.js?1733323139965:1:20
          at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
          at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
          at async getConfigFileExport (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup/dist/shared/loadConfigFile.js:471:17)
          at async loadConfigFile (/Users/ashkanhosseini/projects/nx-next-release/node_modules/rollup/dist/shared/loadConfigFile.js:430:59)
          at async buildRollupTarget (/Users/ashkanhosseini/projects/nx-next-release/node_modules/@nx/rollup/src/plugins/plugin.js:87:27)
          at async createNodesInternal (/Users/ashkanhosseini/projects/nx-next-release/node_modules/@nx/rollup/src/plugins/plugin.js:59:28)
          at async /Users/ashkanhosseini/projects/nx-next-release/node_modules/nx/src/project-graph/plugins/utils.js:10:27
          at async Promise.all (index 0)
          at async createNodesFromFiles (/Users/ashkanhosseini/projects/nx-next-release/node_modules/nx/src/project-graph/plugins/utils.js:8:5)
    An error occurred while processing files for the @nx/eslint/plugin plugin.
    - packages/package-1/eslint.config.js: require is not defined in ES module scope, you can use import instead
  This file is being treated as an ES module because it has a '.js' file extension and '/Users/ashkanhosseini/projects/nx-next-release/packages/package-1/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
      ReferenceError: require is not defined in ES module scope, you can use import instead
      This file is being treated as an ES module because it has a '.js' file extension and '/Users/ashkanhosseini/projects/nx-next-release/packages/package-1/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
          at file:///Users/ashkanhosseini/projects/nx-next-release/packages/package-1/eslint.config.js?mtime=1733322055990:1:12
          at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
          at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
          at async loadConfigFile (/Users/ashkanhosseini/projects/nx-next-release/node_modules/eslint/lib/config/config-loader.js:202:21)
          at async ConfigLoader.calculateConfigArray (/Users/ashkanhosseini/projects/nx-next-release/node_modules/eslint/lib/config/config-loader.js:512:32)
          at async #calculateConfigArray (/Users/ashkanhosseini/projects/nx-next-release/node_modules/eslint/lib/config/config-loader.js:646:29)
          at async ESLint.calculateConfigForFile (/Users/ashkanhosseini/projects/nx-next-release/node_modules/eslint/lib/eslint/eslint.js:1060:25)
          at async ESLint.isPathIgnored (/Users/ashkanhosseini/projects/nx-next-release/node_modules/eslint/lib/eslint/eslint.js:1099:24)
          at async /Users/ashkanhosseini/projects/nx-next-release/node_modules/@nx/eslint/src/plugins/plugin.js:123:19
          at async Promise.all (index 0)
```

### Failure Logs

```shell

```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by jaysoo** [comment]
Hi @ashkanhosseini , the workaround for now is to rename `rollup.config.js` to `rollup.config.cjs` to force CommonJS resolution. We'll update our generators to use `rollup.config.cjs` to avoid this error out of the box.

**Comment by ashkanhosseini** [comment]
> Hi [@ashkanhosseini](https://github.com/ashkanhosseini) , the workaround for now is to rename `rollup.config.js` to `rollup.config.cjs` to force CommonJS resolution. We'll update our generators to use `rollup.config.cjs` to avoid this error out of the box.

Thanks @jaysoo, that's what we're doing for now, so this is not a blocker. Many thanks!
