### ISSUE TITLE
nx migrate 19.8.9 --run-migrations time outs and fails

### ISSUE THREAD

**Issue by enorfelt** [nrwl/nx#29215]
### Current Behavior

Runing `nx migrate 19.8.9 --run-migrations --verbose` time outs and failes 

### Expected Behavior

Migrations should succeed

### Steps to Reproduce

1. nx migrate 19.8.9 --run-migrations --verbose

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.15.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.7.0

nx             : 19.8.9
@nx/js         : 19.8.9
@nx/jest       : 19.8.9
@nx/linter     : 19.8.9
@nx/eslint     : 19.8.9
@nx/workspace  : 19.8.9
@nx/angular    : 19.8.9
@nx/devkit     : 19.8.9
@nrwl/tao      : 19.8.9
@nx/web        : 19.8.9
@nx/webpack    : 19.8.9
typescript     : 5.5.4
---------------------------------------
Registered Plugins:
@nx/jest/plugin
@nx-dotnet/core
---------------------------------------
Community plugins:
@ngrx/effects            : 18.0.2
@ngrx/eslint-plugin      : 18.0.2
@ngrx/router-store       : 18.0.2
@ngrx/store              : 18.0.2
@ngrx/store-devtools     : 18.0.2
@nx-dotnet/core          : 2.4.2
@testing-library/angular : 15.2.0
devextreme-angular       : 24.1.7
ng-mocks                 : 14.13.1
ngrx-immer               : 2.1.1
```

### Failure Logs

```shell
> client-app@0.0.0 nx
> nx migrate 19.8.9 --run-migrations --verbose


 NX   Running migrations from 'migrations.json'

Running the following migrations:
- @angular/material: migration-v18 (Updates Angular Material to v18)
- @angular/cdk: migration-v18 (Updates the Angular CDK to v18)
- @ngrx/store: ngrx-store-migration-18-beta (As of NgRx v18, the `TypedAction` has been removed in favor of `Action`.)
- @ngrx/effects: ngrx-effects-migration-18-beta (As of NgRx v18, the `concatLatestFrom` import has been removed from `@ngrx/effects` in favor of the `@ngrx/operators` package.)
- @angular/core: invalid-two-way-bindings (Updates two-way bindings that have an invalid expression to use the longform expression instead.)
- @angular/core: migration-http-providers (Replace deprecated HTTP related modules with provider functions)
- @angular/core: migration-after-render-phase (Updates calls to afterRender with an explicit phase to the new API)
- @nx/angular: update-angular-cli-version-18-0-0 (Update the @angular/cli package version to ~18.0.0.)
- nx: 19-2-0-move-graph-cache-directory (Updates the default workspace data directory to .nx/workspace-data)
- nx: 19-2-2-update-nx-wrapper (Updates the nx wrapper.)
- nx: 19-2-4-set-project-name (Set project name in nx.json explicitly)
- @nx/angular: update-angular-cli-version-18-1-0 (Update the @angular/cli package version to ~18.1.0.)
- @nx/angular: update-19-6-0 (Ensure Module Federation DTS is turned off by default.)
- @nx/angular: update-angular-cli-version-18-2-0 (Update the @angular/cli package version to ~18.2.0.)
- @nx/angular: update-19-6-1-ensure-module-federation-target-defaults (Ensure Target Defaults are set correctly for Module Federation.)
---------------------------------------------------------

Running migration @angular/material: migration-v18

 NX   Failed to run migration-v18 from @angular/material. This workspace is NOT up to date!


 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx-dotnet/core plugin.
    - Plugin worker @nx-dotnet/core exited unexpectedly with code 0
      Error: Plugin worker @nx-dotnet/core exited unexpectedly with code 0
          at ChildProcess.<anonymous> (C:\src\****\node_modules\nx\src\project-graph\plugins\isolation\plugin-pool.js:194:37)
          at ChildProcess.emit (node:events:519:28)
          at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    The "@nx-dotnet/core" plugin threw an error while creating dependencies: @nx-dotnet/core timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
    Error: @nx-dotnet/core timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
        at Timeout.<anonymous> (C:\src\***\node_modules\nx\src\project-graph\plugins\isolation\plugin-pool.js:219:21)
        at listOnTimeout (node:internal/timers:573:17)
        at process.processTimers (node:internal/timers:514:7)
  Caused by:
      Error: @nx-dotnet/core timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
        at Timeout.<anonymous> (C:\src\***\node_modules\nx\src\project-graph\plugins\isolation\plugin-pool.js:219:21)
        at listOnTimeout (node:internal/timers:573:17)
        at process.processTimers (node:internal/timers:514:7)

Command failed: npx nx _migrate 19.8.9 --run-migrations --verbose

 NX   Command failed: npx nx migrate 19.8.9 --run-migrations --verbose

Error: Command failed: npx nx migrate 19.8.9 --run-migrations --verbose
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runNxSync (C:\Users\***\AppData\Local\Temp\tmp-65160-fEpWCN5ejiqA\node_modules\nx\src\utils\child-process.js:28:34)
    at runMigrations (C:\Users\***\AppData\Local\Temp\tmp-65160-fEpWCN5ejiqA\node_modules\nx\src\command-line\migrate\migrate.js:985:39)
    at C:\Users\***\AppData\Local\Temp\tmp-65160-fEpWCN5ejiqA\node_modules\nx\src\command-line\migrate\migrate.js:1051:19
    at async handleErrors (C:\Users\***\AppData\Local\Temp\tmp-65160-fEpWCN5ejiqA\node_modules\nx\src\utils\handle-errors.js:8:24)

Command failed: C:\Users\***\AppData\Local\Temp\tmp-65160-fEpWCN5ejiqA\node_modules\.bin\nx _migrate 19.8.9 --run-migrations --verbose
```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

Have alos tried with latest with same result

**Comment by kbrilla** [comment]
I was able to run migration but in very specific way:

install nx globally 
`npm i -g nx`
and after than run it with ENV variable
`NX_MIGRATE_USE_LOCAL=true  nx migrate --run-migrations`
but today when I tried to update to [20.2.1](https://github.com/nrwl/nx/releases/tag/20.2.1) it stopped working. What's more I cant find information about NX_MIGRATE_USE_LOCAL on NX website anymore 
Before and today still it did not work when I run `npx nx migrate --run-migrations` or `npm run nx migrate --run-migrations` or `NX_MIGRATE_USE_LOCAL=true npm run nx migrate --run-migrations`  so I dont understand what's going on anymore

**Comment by SnakeSVx** [comment]
Having the same issue when upgrading from 20.1.x to 20.2.1

```
 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/vite/plugin plugin.
    - Plugin worker @nx/vite/plugin exited unexpectedly with code 0
      Error: Plugin worker @nx/vite/plugin exited unexpectedly with code 0
          at ChildProcess.<anonymous> (C:\dev\projects\npm-packages\node_modules\nx\src\project-graph\plugins\isolation\plugin-pool.js:173:37)
          at ChildProcess.emit (node:events:519:28)
          at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    The "@nx/vite/plugin" plugin threw an error while creating dependencies: @nx/vite/plugin timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
    Error: @nx/vite/plugin timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
        at Timeout.<anonymous> (C:\dev\projects\npm-packages\node_modules\nx\src\project-graph\plugins\isolation\plugin-pool.js:183:17)
        at listOnTimeout (node:internal/timers:581:17)
        at process.processTimers (node:internal/timers:519:7)
  Caused by:
      Error: @nx/vite/plugin timed out after 10 minutes during createDependencies. As a last resort, you can set NX_PLUGIN_NO_TIMEOUTS=true to bypass this timeout.
        at Timeout.<anonymous> (C:\dev\projects\npm-packages\node_modules\nx\src\project-graph\plugins\isolation\plugin-pool.js:183:17)
        at listOnTimeout (node:internal/timers:581:17)
        at process.processTimers (node:internal/timers:519:7)
```

**Comment by enorfelt** [comment]
It was the nx-dotnet/core plugin that caused this for me
