### ISSUE TITLE
nx-freebsd-arm64 nowhere to be found

### ISSUE THREAD

**Issue by ELDiablO59152** [nrwl/nx#29257]
### Discussed in https://github.com/nrwl/nx/discussions/29065

<div type='discussions-op-text'>

<sup>Originally posted by **ELDiablO59152** November 25, 2024</sup>
Hi,
I made a port of mongosh on FreeBSD recently.
It builds correctly on amd64 but I faced issues on arm64 and i386 (ia32)

The root cause is found here in nx package because there isn't any release for **nx-freebsd-arm64**.
```
lerna run compile --scope @mongosh/cli-repl --include-dependencies


/wrkdirs/usr/ports/databases/mongosh/work/mongosh-2.2.5/node_modules/lerna/node_modules/nx/src/native/index.js:147
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
      ^

Error: Unsupported architecture on FreeBSD: arm64
    at Object.<anonymous> (/wrkdirs/usr/ports/databases/mongosh/work/mongosh-2.2.5/node_modules/lerna/node_modules/nx/src/native/index.js:147:13)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/wrkdirs/usr/ports/databases/mongosh/work/mongosh-2.2.5/node_modules/lerna/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
```
But It is mentionned here: https://github.com/nrwl/nx/blob/6904789b1092e2591524d58f806e2004482750a2/packages/nx/src/native/native-bindings.js#L180-L194

So is it possible to add it on npm ? Or maybe I can build myself this **nx.freebsd-arm64.node** ?

This build steps seams relevant, do you have any suggestion for the build on arm64 and i386
https://github.com/nrwl/nx/blob/6904789b1092e2591524d58f806e2004482750a2/.github/workflows/publish.yml#L289-L343</div>

**Comment by ELDiablO59152** [comment]
Hi @Cammisuli, @FrozenPandaz,
Hope your going well !
For now, what are the steps to build a version for freebsd arm64 by myself please ?

**Comment by ELDiablO59152** [comment]
Any news ?

**Comment by ELDiablO59152** [comment]
Up
