### ISSUE TITLE
The nx plugin did not find a project inside apps/website/website

### ISSUE THREAD

**Issue by ryandegruyter** [nrwl/nx#29284]
### Current Behavior

Running `npx nx generate convert-to-inferred --project=website --verbose`
results in:

```
 NX   The nx plugin did not find a project inside apps/website/website. File an issue at https://github.com/nrwl/nx with information about your project structure.
```

### Expected Behavior

Running `npx nx generate convert-to-inferred --project=website --verbose` throwing no error and successfully migrating the existing lint target

### Steps to Reproduce

Structure is 

root-project > apps > website > website

### Nx Report

```shell
Node           : 20.13.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.5.2

nx                 : 20.1.4
@nx/js             : 20.1.4
@nx/jest           : 20.1.4
@nx/eslint         : 20.1.4
@nx/workspace      : 20.1.4
@nx/angular        : 20.1.4
@nx/cypress        : 20.1.4
@nx/devkit         : 20.1.4
@nx/eslint-plugin  : 20.1.4
@nx/next           : 20.1.4
@nx/node           : 20.1.4
@nx/react          : 20.1.4
@nx/storybook      : 20.1.4
@nx/web            : 20.1.4
@nx/webpack        : 20.1.4
nx-cloud           : 19.1.0
typescript         : 5.5.4
---------------------------------------
Community plugins:
@ng-bootstrap/ng-bootstrap  : 17.0.1
@nx-aws-plugin/nx-aws-cache : 3.2.3
@storybook/angular          : 8.3.7
ngxtension                  : 4.1.0
```

### Failure Logs

```shell
Error: The nx plugin did not find a project inside apps/website/website. File an issue at https://github.com/nrwl/nx with information about your project structure.
    at ExecutorToPluginMigrator._ExecutorToPluginMigrator_getCreatedTargetForProjectRoot (/Users/...!!removed!!.../node_modules/@nx/devkit/src/generators/plugin-migrations/executor-to-plugin-migrator.js:175:15)
    at ExecutorToPluginMigrator._ExecutorToPluginMigrator_migrateProject (/Users/...!!removed!!.../node_modules/@nx/devkit/src/generators/plugin-migrations/executor-to-plugin-migrator.js:75:164)
    at ExecutorToPluginMigrator._ExecutorToPluginMigrator_migrateTarget (/Users/...!!removed!!.../node_modules/@nx/devkit/src/generators/plugin-migrations/executor-to-plugin-migrator.js:70:136)
    at ExecutorToPluginMigrator.run (/Users/...!!removed!!.../node_modules/@nx/devkit/src/generators/plugin-migrations/executor-to-plugin-migrator.js:52:143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async migrateProjects (/Users/...!!removed!!.../node_modules/@nx/devkit/src/generators/plugin-migrations/executor-to-plugin-migrator.js:222:28)
    at async migrateProjectExecutorsToPlugin (/Users/...!!removed!!.../node_modules/@nx/devkit/src/generators/plugin-migrations/executor-to-plugin-migrator.js:207:22)
    at async convertToInferred (/Users/...!!removed!!.../node_modules/@nx/eslint/src/generators/convert-to-inferred/convert-to-inferred.js:14:30)
    at async /Users/...!!removed!!.../node_modules/nx/src/command-line/generate/generate.js:240:26
    at async handleErrors (/Users/...!!removed!!.../node_modules/nx/src/utils/handle-errors.js:8:24)


```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Hi @ryandegruyter !

What Plugin did you use when you called `npx nx generate convert-to-inferred`? 

Can you provide any more information at all? Such as if there is an existing config file for the plugin you chose at the project root, and/or the project.json you're trying to convert?

**Comment by Coly010** [comment]
@ryandegruyter No problem. Let's close it out and if someone else has an issue and encounters this issue, tag me and we can reopen.
