### ISSUE TITLE
NX v. 20.2.2 migration with rspack causes "throw new Error(`Could not find ${fileToRun}. Make sure your build succeeded.`);"

### ISSUE THREAD

**Issue by rujorgensen** [nrwl/nx#29388]
### Current Behavior

Serving NestJS application with RSPack configuration, fails with "throw new Error(`Could not find ${fileToRun}. Make sure your build succeeded.`);"
          ^

This happened after the latest NX migration to v. 20.2.2, which updates "@nx/rspack" to v. "20.2.2" too. Downgrading "@nx/rspack" to v. 20.1.4, appears to fix the issue.

### Expected Behavior

I expect the app to serve like before the migration.

### Steps to Reproduce

1. I ran `nx migrate latest`, then applied the migration
2. Serve the app `nx serve backend-server` 

### Nx Report

```shell
Node           : 20.11.1
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 9.10.0

nx (global)            : 20.0.0
nx                     : 20.2.2
@nx/js                 : 20.2.2
@nx/jest               : 20.2.2
@nx/eslint             : 20.2.2
@nx/workspace          : 20.2.2
@nx/angular            : 20.2.2
@nx/cypress            : 20.2.2
@nx/devkit             : 20.2.2
@nx/eslint-plugin      : 20.2.2
@nx/express            : 20.2.2
@nx/module-federation  : 20.2.2
@nx/nest               : 20.2.2
@nx/node               : 20.2.2
@nx/plugin             : 20.2.2
@nx/rspack             : 20.2.2
@nx/storybook          : 20.2.2
@nx/vite               : 20.2.2
@nx/web                : 20.2.2
@nx/webpack            : 20.2.2
typescript             : 5.6.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome : 0.15.0
@ionic/angular                   : 8.4.1
@ngneat/spectator                : 19.0.0
@nxext/ionic-angular             : 17.0.1
@storybook/angular               : 8.4.7
angular-eslint                   : 19.0.2
ng-mocks                         : 14.13.1
---------------------------------------
Local workspace plugins:
         @project-name/workspace-plugin
```

### Failure Logs

```shell
(node:92088) DeprecationWarning: A 'callback' argument needs to be provided to the 'rspack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
(Use `node --trace-deprecation ...` to show where the warning was created)
●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (100%) emitting after emit                                                                                                                                                           
chunk (runtime: main) main.46afa6f5135ce981.js (main) 4.02 MiB (javascript) 982 bytes (runtime) [entry] [rendered]
Rspack compiled successfully (f48b85e3058beb99)
Watcher closed
/home/name/company-name/project-name-wsl/node_modules/.pnpm/@nx+js@20.2.2_@babel+traverse@7.25.9_@swc-node+register@1.10.9_@swc+core@1.9.3_@swc+helpers@0_jw6tco35l7zktrglrqwqwwneaq/node_modules/@nx/js/src/executors/node/node.impl.js:312
    throw new Error(`Could not find ${fileToRun}. Make sure your build succeeded.`);
          ^

Error: Could not find /home/name/company-name/project-name-wsl/dist/apps/backend/server/main.js. Make sure your build succeeded.
    at fileToRunCorrectPath (/home/name/company-name/project-name-wsl/node_modules/.pnpm/@nx+js@20.2.2_@babel+traverse@7.25.9_@swc-node+register@1.10.9_@swc+core@1.9.3_@swc+helpers@0_jw6tco35l7zktrglrqwqwwneaq/node_modules/@nx/js/src/executors/node/node.impl.js:312:11)
    at /home/name/company-name/project-name-wsl/node_modules/.pnpm/@nx+js@20.2.2_@babel+traverse@7.25.9_@swc-node+register@1.10.9_@swc+core@1.9.3_@swc+helpers@0_jw6tco35l7zktrglrqwqwwneaq/node_modules/@nx/js/src/executors/node/node.impl.js:98:49
    at new Promise (<anonymous>)
    at Object.start (/home/name/company-name/project-name--wsl/node_modules/.pnpm/@nx+js@20.2.2_@babel+traverse@7.25.9_@swc-node+register@1.10.9_@swc+core@1.9.3_@swc+helpers@0_jw6tco35l7zktrglrqwqwwneaq/node_modules/@nx/js/src/executors/node/node.impl.js:92:36)
    at async Timeout.processQueue [as _onTimeout] (/home/name/company-name/project-name--wsl/node_modules/.pnpm/@nx+js@20.2.2_@babel+traverse@7.25.9_@swc-node+register@1.10.9_@swc+core@1.9.3_@swc+helpers@0_jw6tco35l7zktrglrqwqwwneaq/node_modules/@nx/js/src/executors/node/node.impl.js:63:13)

Node.js v20.11.1
```

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [x] Other (Please specify)

### Additional Information

Running on Windows in WSL.

This is the contents of the `rspack.config.js` of the application.

```JavaScript
const { composePlugins, withNx } = require('@nx/rspack');

module.exports = composePlugins(withNx(), (config) => {
    return {
        ...config,
        ignoreWarnings: [
            /Critical dependency:/, warning => false,
            /HarmonyLinkingWarning/, warning => false,
            /Resolve error/, warning => false,
        ],
    };
});
```

**Comment by rujorgensen** [comment]
The `serve`-command expects a file called main.js to be produced in the dist-folder, but after the update to 20.2.2, produces a file with fingerprinting:

**Before update:**
![Image](https://github.com/user-attachments/assets/99a89de9-072a-4809-835b-97f57e693549)

**After update:**
![Image](https://github.com/user-attachments/assets/7445ce76-4b57-4698-ad1f-738dd2429570)

**Comment by Coly010** [comment]
Hey @rujorgensen Could you provide a repo with a minimal reproduction of this so i can assist you further?

**Comment by rujorgensen** [comment]
Hi @Coly010, thanks for getting back, sorry for the delay--holidays and stuff 🎅.

So disclaimer first: while going through the steps of reproducing this, it appears there there are generally some issues with running the @nx/rspack conversion tool, which might have led to a bad setup in the first place, but this reproduces the issue

**Reproduction**
1. Run `npx create-nx-workspace@20.1.4 my-workspace --preset=nest` (v. 20.1.4 was the version I migrated from originally)
2. Add the @nx/rspack: `cd my-workspace && nx add @nx/rspack`
3. Convert the webpack configuration to rspack: `npx nx generate @nx/rspack:convert-webpack --project=my-workspace` **NOTE!** This command now completes without touching any files. When I did this originally, it was many NX versions back, so I don't know when or why this stopped working. See steps below where I did this manually. 
This is the repo at this stage: https://github.com/rujorgensen/nx-rspack-issue
5. ✅ Check that it runs (and main.js is generated in dist/apps/my-workspace):  `nx serve my-workspace`
6. Migrate the workspace to NX v. 20.2.2: `nx migrate 20.2.2`
7. Install the updated dependencies and apply migrations: `npm install && npx nx migrate --run-migrations`
8. 🛑 Run now fails as described in my opening post of this issue

**Convert webpack config to rspack config (manually)**
1. Add rspack.config.js 
```JavaScript
const { composePlugins, withNx } = require('@nx/rspack');

module.exports = composePlugins(withNx(), (config) => config);
```

2. Replace the "build"-target in apps/my-workspace/project.json with (this is what I have from an earlier @nx/rspack auto webpack -> rspack migration):
```
    "build": {
      "executor": "@nx/rspack:rspack",
      "outputs": [
        "{options.outputPath}"
      ],
      "defaultConfiguration": "production",
      "options": {
        "outputPath": "dist/apps/my-workspace",
        "main": "apps/my-workspace/src/main.ts",
        "tsConfig": "apps/my-workspace/tsconfig.app.json",
        "assets": [
          "apps/my-workspace/src/assets"
        ],
        "target": "node",
        "rspackConfig": "apps/my-workspace/rspack.config.js"
      },
      "configurations": {
        "development": {
          "mode": "development"
        },
        "production": {
          "mode": "production",
          "sourceMap": false
        }
      }
    }
```
3. To get this to run, I have to delete the inferred target in nx.json (perhaps it has something to do with [this](https://github.com/nrwl/nx-labs/issues/408))

Cheers!

**Comment by rujorgensen** [comment]
Bumping because a reproduction was provided, but the label was not changed causing the issue to be marked as stale by automation. @Coly010

**Comment by rujorgensen** [comment]
Bumping again because a reproduction was provided, but the label was not changed causing the issue to be marked as stale by automation. @Coly010

**Comment by rujorgensen** [comment]
@Coly010 we're currently stuck on @nx/rspack@20.1.4, and we now have new issues (although unrelated) with the 20.3.1 migration. I'd rather not start opening the box on those issues while we still have dept here. Is there a way we can get this issue confirmed or closed, so our team can work on a path forward from here 🙂?

**Comment by Coly010** [comment]
@rujorgensen Sorry for the delay in the response. It will likely be the end of this week or start of next before I can dig into this more thoroughly. Thank you for providing the reproduction steps and the repo. These will both help immensely.

**Comment by rujorgensen** [comment]
@itspers did you find a solution to this issue 🙂? Have you been able to update @nx/rspack above 20.1.4?
