### ISSUE TITLE
Failed to convert JavaScript value `Null` into rust type `String`

### ISSUE THREAD

**Issue by adgoudz** [nrwl/nx#29429]
### Current Behavior

`nx graph` outputs an error for each tsconfig file in [agdz/sample-workspace](https://github.com/adgoudz/sample-workspace):

```
 NX   Failed to create nodes

An error occurred while processing files for the @nx/js/typescript plugin.
  - packages/foo/tsconfig.json: Failed to convert JavaScript value `Null` into rust type `String`
    Error: Failed to convert JavaScript value `Null` into rust type `String`
        at hashArray (/path/to/sample-workspace/node_modules/nx/src/hasher/file-hasher.js:9:12)
        at createNodesInternal (/path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:97:50)
        at /path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:41:95
        at /path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/utils.js:10:33
        at Array.map (<anonymous>)
        at createNodesFromFiles (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/utils.js:8:35)
        at exports.createNodesV2 (/path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:41:60)
        at LoadedNxPlugin.createNodes (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/internal-api.js:34:65)
        at LoadedNxPlugin.createNodes.<computed> (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/internal-api.js:44:34)
  - ...
```

Other commands fail with:

```
 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue
```

### Expected Behavior

Nx should ignore optional files when hashing nodes. In my case, Nx is failing to process the project graph when a project doesn't create a lockfile (i.e., package-lock.json).

### GitHub Repo

https://github.com/adgoudz/sample-workspace

### Steps to Reproduce

1. `npx nx graph`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.5.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.2

nx (global)    : 20.2.2
nx             : 20.2.2
@nx/js         : 20.2.2
@nx/workspace  : 20.2.2
@nx/devkit     : 20.2.2
typescript     : 5.6.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
---------------------------------------
⚠️ Unable to construct project graph.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/js/typescript plugin.
    - packages/bar/tsconfig.json: Failed to convert JavaScript value `Null` into rust type `String`
      Error: Failed to convert JavaScript value `Null` into rust type `String`
          at hashArray (/path/to/sample-workspace/node_modules/nx/src/hasher/file-hasher.js:9:12)
          at createNodesInternal (/path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:97:50)
          at /path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:41:95
          at /path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/utils.js:10:33
          at Array.map (<anonymous>)
          at createNodesFromFiles (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/utils.js:8:35)
          at exports.createNodesV2 (/path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:41:60)
          at LoadedNxPlugin.createNodes (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/internal-api.js:34:65)
          at LoadedNxPlugin.createNodes.<computed> (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/internal-api.js:44:34)
          at createNodes (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:71:63)
    - packages/bar/tsconfig.lib.json: Failed to convert JavaScript value `Null` into rust type `String`
      Error: Failed to convert JavaScript value `Null` into rust type `String`
          at hashArray (/path/to/sample-workspace/node_modules/nx/src/hasher/file-hasher.js:9:12)
          at createNodesInternal (/path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:97:50)
          at /path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:41:95
          at /path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/utils.js:10:33
          at Array.map (<anonymous>)
          at createNodesFromFiles (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/utils.js:8:35)
          at exports.createNodesV2 (/path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:41:60)
          at LoadedNxPlugin.createNodes (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/internal-api.js:34:65)
          at LoadedNxPlugin.createNodes.<computed> (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/internal-api.js:44:34)
          at createNodes (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:71:63)
    - packages/foo/tsconfig.json: Failed to convert JavaScript value `Null` into rust type `String`
      Error: Failed to convert JavaScript value `Null` into rust type `String`
          at hashArray (/path/to/sample-workspace/node_modules/nx/src/hasher/file-hasher.js:9:12)
          at createNodesInternal (/path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:97:50)
          at /path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:41:95
          at /path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/utils.js:10:33
          at Array.map (<anonymous>)
          at createNodesFromFiles (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/utils.js:8:35)
          at exports.createNodesV2 (/path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:41:60)
          at LoadedNxPlugin.createNodes (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/internal-api.js:34:65)
          at LoadedNxPlugin.createNodes.<computed> (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/internal-api.js:44:34)
          at createNodes (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:71:63)
    - packages/foo/tsconfig.lib.json: Failed to convert JavaScript value `Null` into rust type `String`
      Error: Failed to convert JavaScript value `Null` into rust type `String`
          at hashArray (/path/to/sample-workspace/node_modules/nx/src/hasher/file-hasher.js:9:12)
          at createNodesInternal (/path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:97:50)
          at /path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:41:95
          at /path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/utils.js:10:33
          at Array.map (<anonymous>)
          at createNodesFromFiles (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/utils.js:8:35)
          at exports.createNodesV2 (/path/to/sample-workspace/node_modules/@nx/js/src/plugins/typescript/plugin.js:41:60)
          at LoadedNxPlugin.createNodes (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/internal-api.js:34:65)
          at LoadedNxPlugin.createNodes.<computed> (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/internal-api.js:44:34)
          at createNodes (/path/to/sample-workspace/node_modules/nx/src/project-graph/plugins/isolation/plugin-worker.js:71:63)
```

### Failure Logs

```shell

```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The error messages refer to the `null` value created when hashing this path:

https://github.com/nrwl/nx/blob/7d864c8db815dfa95e5fac2110a608d7499de4ea/packages/js/src/plugins/typescript/plugin.ts#L232

**Comment by adgoudz** [comment]
> In my case I have a lock file bun.lock, and I get the same error

@dvictory I updated the issue to be more general... the error probably appears whenever Nx tries to hash any file that doesn't exist:

https://github.com/nrwl/nx/blob/7d864c8db815dfa95e5fac2110a608d7499de4ea/packages/js/src/plugins/typescript/plugin.ts#L226-L236

**Comment by nicky-lenaers-phoenicks** [comment]
I have the same error but with a `pnpm-lock.yaml` file, all `tsconfig.X.json` files are showing this error on Nx `20.4.1`.
