### ISSUE TITLE
NX_VERSION_CHANGED for format:write without any further text

### ISSUE THREAD

**Issue by ThePlenkov** [nrwl/nx#29446]
### Current Behavior

I mirgrated to a new NX version using `nx migrate latest` including post-install and run-migrations.

At same time I'm using following husky hook which just worked perfectly:
```
# .husky/pre-commit
nx format:write --uncommitted --verbose
git update-index --again
```

So now when I try to commit a change I have some weird error:
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -

 NX   NX_VERSION_CHANGED


husky - pre-commit script failed (code 1)
```

If I run nx format:write command separately - it just works. So it does not work from inside the hook.

Unfortunately --verbose flag is useless. nx reset also doesn't not help. Using npx nx also doesn't change anything. Please help!

### Expected Behavior

Well nx should work also from git hooks and it should not be impacted by a version change.

I think this check is not working well. Also would be nice even if it's error to have more meaningful explanation

### Steps to Reproduce

Not sure if you can. But try this.

- init repo, install nx 19.6.5 ( it's what i had )
- install husky, add hook as mentioned above, commit.
- migrate to latest nx
- commit again 

That's what i did..

### Nx Report

```shell
Node           : 18.20.4
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.7.0

nx             : 20.2.2
@nx/js         : 20.2.2
@nx/jest       : 20.2.2
@nx/eslint     : 20.2.2
@nx/workspace  : 20.2.2
@nx/devkit     : 20.2.2
@nx/plugin     : 20.2.2
typescript     : 5.6.3
---------------------------------------
Registered Plugins:
nx-array-args
```

### Failure Logs

```shell

```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ThePlenkov** [comment]
So it's funny, i was able to solve this issue by adding `nx reset` into my hook!

So I tried many time to run `nx reset` and `npx nx reset` from the project root - but it had no impact on the hook execution

**Comment by ThePlenkov** [comment]
Actually after few more issues i figured out that just needed to disable daemon:
```
# .husky/pre-commit
NX_DAEMON=false nx format:write --uncommitted
git update-index --again
```

**Comment by ThePlenkov** [comment]
However I'd like still to keep this issue open in a hope that someone from nx team can check why daemon in a hook is different from a daemon in a root package and NX_VERSION_CHANGED error occurs

**Comment by bbecker-te** [comment]
I just got this error and don't know what to do to resolve
```
beckerb4@BECKERB4-M-N747 te-cc % npm run build                                                                             
> prebuild
> npm run clean

> clean
> npx lerna run clean

lerna notice cli v7.4.2
lerna ERR! Error: NX_VERSION_CHANGED
lerna ERR!     at handleMessage (/Users/beckerb4/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/daemon/server/server.js:92:88)
lerna ERR!     at /Users/beckerb4/.npm/_npx/d5cad42883f80c04/node_modules/nx/src/daemon/server/server.js:72:15
```

**Comment by MaxKless** [comment]
Could you provide a minimal repro that I can clone to check the issue? That will increase the chances I can repro & fix this :)
