### ISSUE TITLE
module federation failure in wildcard ts mapping

### ISSUE THREAD

**Issue by jmvtrinidad** [nrwl/nx#29477]
### Current Behavior

it throws an error when building, looks like related to this [issue](https://github.com/nrwl/nx/issues/26765)
<img width="1062" alt="Image" src="https://github.com/user-attachments/assets/e85abd08-4b5a-41cc-9eba-c80347d131af" />
library.name has value `@company/app/config/*`

### Expected Behavior

handle wildcard ts import

### Steps to Reproduce

1. build app with wildcard

### Nx Report

```shell
Node           : 22.4.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.15.0

nx (global)            : 20.2.2
nx                     : 20.3.0
@nx/js                 : 20.3.0
@nx/jest               : 20.3.0
@nx/eslint             : 20.3.0
@nx/workspace          : 20.3.0
@nx/devkit             : 20.3.0
@nx/eslint-plugin      : 20.3.0
@nx/module-federation  : 20.3.0
@nx/plugin             : 20.3.0
@nx/react              : 20.3.0
@nx/rspack             : 20.3.0
@nx/storybook          : 20.3.0
@nx/vite               : 20.3.0
@nx/web                : 20.3.0
@nx/webpack            : 20.3.0
nx-cloud               : 19.1.0
typescript             : 5.6.3
---------------------------------------
Community plugins:
@koliveira15/nx-sonarqube : 3.5.1
@nx-tools/nx-container    : 6.2.0
---------------------------------------
Local workspace plugins:
         fe-tools
```

### Failure Logs

```shell
× TypeError: The "path" argument must be of type string. Received undefined
│     at join (node:path:1175:7)
│     at /app/node_modules/.pnpm/@nx+module-federation@20.3.0_@babel+traverse@7.23.9_@swc-node+register@1.10.9_@swc+core@1.10._6allat2eyhmrem2zood2ybjpjq/node_modules/@nx/module-federation/src/utils/share.js:117:45
│     at Object.fn (/app/node_modules/.pnpm/@rspack+core@1.1.8_@swc+helpers@0.5.15/node_modules/@rspack/core/dist/index.js:18922:15)
│     at next (/app/node_modules/.pnpm/@rspack+lite-tapable@1.0.1/node_modules/@rspack/lite-tapable/dist/index.js:619:29)
│     at AsyncSeriesBailHook.callAsyncStageRange (/app/node_modules/.pnpm/@rspack+lite-tapable@1.0.1/node_modules/@rspack/lite-tapable/dist/index.js:642:9)
│     at /app/node_modules/.pnpm/@rspack+lite-tapable@1.0.1/node_modules/@rspack/lite-tapable/dist/index.js:86:18
│     at new Promise (<anonymous>)
│     a
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

when i try to replace the share.js with below code it builds fine
```ts
              let newReq = req.request
              try {
                newReq = library.name.endsWith('/*')
                    ? /**
                       * req usually is in the form of "../../../path/to/file"
                       * library.path is usually in the form of "/Users/username/path/to/Workspace/path/to/library"
                       *
                       * When a wildcard is used in the TS path mappings, we want to get everything after the import to
                       * re-route the request correctly inline with the webpack/rspack resolve.alias
                       */
                        (0, path_1.join)(library.name, req.request.split(library.path.replace(devkit_1.workspaceRoot, '').replace('/*', ''))[1])
                    : library.name;
              } catch (e) {
              }
              req.request = newReq;
```

**Comment by Coly010** [comment]
Hey @jmvtrinidad can you provide a minimal repo that reproduces this error?
