### ISSUE TITLE
Hiccups upgrading from 0.7.4 to 0.8.0

### ISSUE THREAD

**Issue by dereklin** [nrwl/nx#301]
I manually changed these to:
```
    "@nrwl/nx": "0.8.0",
    "@nrwl/schematics": "0.8.0",
    "@angular/cli": "1.7.1",
```
I ran
```
npm i
npm nx-migrate
npm i
npm run update
npm i
```
I can see that @angular-devkit/schematics and some others were removed by the migration/update

Then I did
```
ng generate lib test --dry-run
```

I got:
```
Cannot find module '@angular-devkit/schematics'
Error: Cannot find module '@angular-devkit/schematics'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
```

**Comment by dereklin** [comment]
removing node_modules and package-lock.json and npm i again made it work

**Comment by Yonet** [comment]
@dereklin can you check your local version of your nrwl node_modules. You don't need the @angular-devkit/schematics with 0.8.0.
