### ISSUE TITLE
Running tests in intellij with JEST

### ISSUE THREAD

**Issue by HackPoint** [nrwl/nx#3022]
Issue:
I'm trying to run tests from intellij, but receiving an error.

Nwrl:
` "@angular/animations": "9.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "9.0.0",
    "@angular/compiler": "9.0.0",
    "@angular/core": "9.0.0",
    "@angular/forms": "9.0.0",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "9.0.0",
    "@angular/platform-browser-dynamic": "9.0.0",
    "@angular/router": "9.0.0",
    "@datorama/akita": "^4.20.0",
    "@nebular/auth": "^4.6.0",
    "@nebular/bootstrap": "^5.0.0",
    "@nebular/eva-icons": "^4.6.0",
    "@nebular/moment": "^5.0.0",
    "@nebular/theme": "^4.6.0",
    "@nestjs/common": "^6.8.3",
    "@nestjs/core": "^6.8.3",
    "@nestjs/platform-express": "^6.8.3",
    "@nrwl/angular": "9.0.2",`

Error:
`  console.error ../../node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.dispatchError (/Users/gena/projects/private/my-tray/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
        at Request.<anonymous> (/Users/gena/projects/private/my-tray/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
        at Request.emit (events.js:327:22)
        at Request.onRequestError (/Users/gena/projects/private/my-tray/node_modules/request/request.js:877:8)
        at ClientRequest.emit (events.js:315:20)
        at Socket.socketErrorListener (_http_client.js:432:9)
        at Socket.emit (events.js:315:20)
        at emitErrorNT (internal/streams/destroy.js:84:8)
        at processTicksAndRejections (internal/process/task_queues.js:84:21) undefined

Error: Uncaught (in promise): Failed to load devices.component.html

    at resolvePromise (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/zone.js:836:35)
    at resolvePromise (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/zone.js:795:21)
    at /Users/gena/projects/private/my-tray/node_modules/zone.js/dist/zone.js:897:21
    at ZoneDelegate.invokeTask (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/zone.js:431:35)
    at AsyncTestZoneSpec.onInvokeTask (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/async-test.js:86:33)
    at ProxyZoneSpec.onInvokeTask (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/proxy.js:145:43)
    at ZoneDelegate.invokeTask (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/zone.js:430:40)
    at Zone.runTask (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/zone.js:198:51)
    at drainMicroTaskQueue (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/zone.js:611:39)
    at ZoneTask.invokeTask [as invoke] (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/zone.js:517:25)
    at invokeTask (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/zone.js:1671:18)
    at XMLHttpRequest.globalZoneAwareCallback (/Users/gena/projects/private/my-tray/node_modules/zone.js/dist/zone.js:1697:21)
    at invokeEventListeners (/Users/gena/projects/private/my-tray/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at XMLHttpRequestEventTargetImpl._dispatch (/Users/gena/projects/private/my-tray/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at XMLHttpRequestEventTargetImpl.dispatchEvent (/Users/gena/projects/private/my-tray/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
    at XMLHttpRequest.dispatchEvent (/Users/gena/projects/private/my-tray/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
    at requestErrorSteps (/Users/gena/projects/private/my-tray/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:132:7)
    at Object.dispatchError (/Users/gena/projects/private/my-tray/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:62:3)
    at Request.<anonymous> (/Users/gena/projects/private/my-tray/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
    at Request.emit (events.js:327:22)
    at Request.onRequestError (/Users/gena/projects/private/my-tray/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:432:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by Cammisuli** [comment]
Fixed with #3224
