### ISSUE TITLE
--width-deps causes Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by conor-mac-aoidh** [nrwl/nx#3055]
## Expected Behavior

The `nx affected:build --with-deps` command should determine the build time dependencies of a publishable library and build those dependencies first. 

Following on from the issue resolution [here](https://github.com/nrwl/nx/issues/602), I have removed my custom script and started using the `--with-deps` argument.

## Current Behavior

Running `nx affected:build --with-deps` throws a `Maximum call stack size exceeded` error.

## Failure Information (for bugs)

The command throws the following error:

```
RangeError: Maximum call stack size exceeded
    at recur (node_modules/@nrwl/workspace/src/core/project-graph/operators.js:72:19)
    at node_modules/@nrwl/workspace/src/core/project-graph/operators.js:76:13
    at Array.forEach (<anonymous>)
    at recur (node_modules/@nrwl/workspace/src/core/project-graph/operators.js:75:12)
    at node_modules/@nrwl/workspace/src/core/project-graph/operators.js:76:13
    at Array.forEach (<anonymous>)
    at recur (node_modules/@nrwl/workspace/src/core/project-graph/operators.js:75:12)
    at node_modules/@nrwl/workspace/src/core/project-graph/operators.js:76:13
    at Array.forEach (<anonymous>)
    at recur (node_modules/@nrwl/workspace/src/core/project-graph/operators.js:75:12)
```

### Steps to Reproduce

I spent a few hours trying to reproduce this issue in a test repository but I wasn't able to. I will keep working on this and try to reproduce it.

### Context

I am using the latest version of NX (`9.3.0`) and Angular 9.

There are no circular dependencies in my repository.

The repository contains 4 applications and 18 libraries, 4 of which are publishable. The publishable libraries only depend on other publishable libraries.

The `Maximum call stack size exceeded` error on my CI/CD platform and on other developers' machines, so it is consistently reproducible in my project (which I can't share..).

**Comment by conor-mac-aoidh** [comment]
This issue for me was caused by having a circular implicit dependency in `nx.json`:

```json
{
  "npmScope": "test",
  "implicitDependencies": {
    "angular.json": "*",
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    "tsconfig.json": "*",
    "tslint.json": "*",
    "nx.json": "*"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/workspace/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
      }
    }
  },
  "projects": {
    "test-app": {
      "tags": [],
      "implicitDependencies": ["test-app-e2e"]
    },
    "test-app-e2e": {
      "tags": []
    },
    "a": {
      "tags": []
    },
    "b": {
      "tags": []
    },
    "c": {
      "tags": []
    },
    "d": {
      "tags": []
    }
  }
}
```

I had added `test-app-e2e` as an implicit dependency of `test-app`. But in the dep-graph, the implicit dependency is showing both ways - between `test-app-e2e`->`test-app` and `test-app` -> `test-app-e2e`.. removing this dependency in `nx.json` has resolved the issue.
