### ISSUE TITLE
ts-mockito spy console problem

### ISSUE THREAD

**Issue by KarmaCop213** [nrwl/nx#3129]
## Current Behavior
When I use ts-mockito spy an error is thrown when I use the command `npm test`:

```
    TypeError: Cannot read property 'get' of undefined

      172 |   test.only("test", () => {
      173 |     const spiedConsole = spy(console)
    > 174 |     console.log("hello")
          |             ^
      175 |     var x = capture(spiedConsole.log).first()[0]
      176 |     console.log(x)
      177 |     expect(capture(spiedConsole.log).first()[0]).toEqual("hello")

      at Spy.Object.<anonymous>.Spy.getEmptyMethodStub (../../../../node_modules/ts-mockito/src/Spy.ts:34:50)
      at Spy.Object.<anonymous>.Mocker.getMethodStub (../../../../node_modules/ts-mockito/src/Mock.ts:242:25)
      at CustomConsole._formatBuffer (../../../../node_modules/ts-mockito/src/Mock.ts:161:37)
      at CallThroughMethodStub.Object.<anonymous>.CallThroughMethodStub.execute (../../../../node_modules/ts-mockito/src/stub/CallThroughMethodStub.ts:18:35)
      at CustomConsole._log (../../../../node_modules/ts-mockito/src/Mock.ts:162:24)
      at CallThroughMethodStub.Object.<anonymous>.CallThroughMethodStub.execute (../../../../node_modules/ts-mockito/src/stub/CallThroughMethodStub.ts:18:35)
      at CustomConsole.log (../../../../node_modules/ts-mockito/src/Mock.ts:162:24)
      at Object.<anonymous> (src/lib/config.service.spec.ts:174:13)
```

It works fine I run the test using the `jest` command

I've tried using the jest.spyOn at it works fine with both `jest` and `npm test` commands:

```javascript
    const spiedJestConsole = jest.spyOn(console, "log")
    console.log("hello")
    expect(spiedJestConsole.mock.calls[0][0]).toEqual("hello")
    spiedJestConsole.mockRestore()
```

## Expected Behavior
Running tests using `npm test` which use ts-mockito to spy on the console should not fail.

## Steps to Reproduce

This is the test I'm using:
``` javascript 
  test.only("test", () => {
    // ts-mockito spy test
    const spiedConsole = spy(console)
    console.log("hello")
    expect(capture(spiedConsole.log).first()[0]).toEqual("hello")
    reset(spiedConsole)

    // jest spyOn test
    const spiedJestConsole = jest.spyOn(console, "log")
    console.log("hello")
    expect(spiedJestConsole.mock.calls[0][0]).toEqual("hello")
    spiedJestConsole.mockRestore()
  })
```

### Environment
```
  @nrwl/angular : 8.7.0
  @nrwl/cli : 8.7.0
  @nrwl/cypress : 8.7.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.7.0
  @nrwl/linter : 8.7.0
  @nrwl/nest : 8.7.0
  @nrwl/next : Not Found
  @nrwl/node : 8.7.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.7.0
  @nrwl/web : Not Found
  @nrwl/workspace : 8.7.0
  typescript : 3.8.3
```

Also using:
```
"jest": "25.5.4",
"jest-preset-angular": "7.1.1",
"ts-jest": "24.0.2",
"ts-mockito": "2.5.0",
```

**Comment by Cammisuli** [comment]
Hi @KarmaCop213, can you try this with Nx 10+? We changed the way we execute jest, where we do not touch any config files, and jest handles everything. So hopefully it should fix this issue.
