### ISSUE TITLE
Cannot create angular component in monorepo with express + angular app

### ISSUE THREAD

**Issue by adams-family** [nrwl/nx#3211]
## Current Behavior
`ng g c component --project=angular` fails with:

```
An unhandled exception occurred: Schematic "c" not found in collection "@nrwl/express".
See "/tmp/ng-bL0uEB/angular-errors.log" for further details.
```

## Expected Behavior
If should create a component called `component` in the project called `angular`

## Steps to Reproduce
1) Init empty workspace
```
npm init nx-workspace nxworkspace
```
  Preset: empty
  CLI: Angular
  NX Cloud: No

2) Install express & angular packages
```
cd nxworkspace
npm i @nrwl/express --save-dev
npm i @nrwl/angular --save-dev
```

3) Generate 2 applications: `express` and `angular`
```
ng g @nrwl/express:application express
ng g @nrwl/angular:application angular
```
  Styles: LESS
  Routing: Yes

4) Attempt to create a component
```
ng g c component --project=angular
```

### Failure Logs
cat /tmp/ng-bL0uEB/angular-errors.log:
```
[error] Error: Schematic "c" not found in collection "@nrwl/express".
    at SchematicEngine.createSchematic (/var/docker/Monorepo/nxworkspace-expressfirst/node_modules/@angular-devkit/schematics/src/engine/engine.js:232:23)
    at CollectionImpl.createSchematic (/var/docker/Monorepo/nxworkspace-expressfirst/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at GenerateCommand.getSchematic (/var/docker/Monorepo/nxworkspace-expressfirst/node_modules/@angular/cli/models/schematic-command.js:134:27)
    at GenerateCommand.initialize (/var/docker/Monorepo/nxworkspace-expressfirst/node_modules/@angular/cli/models/schematic-command.js:44:36)
    at async GenerateCommand.initialize (/var/docker/Monorepo/nxworkspace-expressfirst/node_modules/@angular/cli/commands/generate-impl.js:12:9)
    at async GenerateCommand.validateAndRun (/var/docker/Monorepo/nxworkspace-expressfirst/node_modules/@angular/cli/models/command.js:124:9)
    at async Object.runCommand (/var/docker/Monorepo/nxworkspace-expressfirst/node_modules/@angular/cli/models/command-runner.js:201:24)
    at async default_1 (/var/docker/Monorepo/nxworkspace-expressfirst/node_modules/@angular/cli/lib/cli/index.js:62:31)
```

### Environment
```
  @nrwl/angular : 9.4.5
  @nrwl/cli : 9.4.5
  @nrwl/cypress : 9.4.5
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : 9.4.5
  @nrwl/jest : 9.4.5
  @nrwl/linter : 9.4.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.4.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.5
  @nrwl/web : Not Found
  @nrwl/workspace : 9.4.5
  typescript : 3.8.3
```

**Comment by adams-family** [comment]
I actually found one more interesting thing. Whether this works or fails depends on whether the `cli` in `angular.json` is set to `@nrwl/express` of `@nrwl/angular`:

Works:
```
  "cli": {
    "defaultCollection": "@nrwl/angular"
  },
```

Does not work:
```
  "cli": {
    "defaultCollection": "@nrwl/express"
  },
```

This sounds very logical. However, my question is, in a mixed environment (express/angular) what is the right solution?

**Comment by FrozenPandaz** [comment]
Hi!

As you've found, there are multiple collections that are provided.

`@nrwl/express` and `@nrwl/angular` are two separate sets of schematics that suit each technology.

However, you may only have one default so I recommend getting used to passing the collection when you generate code.

```
ng g @nrwl/angular:component button
```

Using [Nx Console](https://nx.dev/angular/cli/console) will make this easier for you to do:

![image](https://user-images.githubusercontent.com/8104246/85207562-92560a80-b2f7-11ea-83e7-64407733a347.png)

**Comment by adams-family** [comment]
@FrozenPandaz Thanks, this is perfect! Excatly what I was looking for.
