### ISSUE TITLE
Lint Error: SyntaxError: Unexpected token } in JSON at position 25067

### ISSUE THREAD

**Issue by tommyc38** [nrwl/nx#3214]
## Current Behavior
I am getting a lint error that I cannot track down.

## Expected Behavior
Any file read from Nx file utils that would cause a lint error, should specify which file has incorrect syntax.

## Steps to Reproduce

It looks like Nx is reading nx.json and workspace.json in my workspace and one of them is causing the issue.  I don't have a workspace.json file so that only leaves nx.json.  I have opened that file up and don't see any errors.   My IDE isn't telling me any json files are wrong either so I am stumped at which file is causing this error.  Is nx fileutils reading all tslint.json files? 
### Failure Logs

`SyntaxError: Unexpected token } in JSON at position 25067
    at JSON.parse (<anonymous>)
    at Object.readJsonFile (/Users/tomconley/WebstormProjects/umbrelo-org/umbrelo/node_modules/@nrwl/workspace/src/utils/fileutils.js:39:17)
    at Object.readWorkspaceJson (/Users/tomconley/WebstormProjects/umbrelo-org/umbrelo/node_modules/@nrwl/workspace/src/core/file-utils.js:131:24)
    at new Rule (/Users/tomconley/WebstormProjects/umbrelo-org/umbrelo/node_modules/@nrwl/workspace/src/tslint/nxEnforceModuleBoundariesRule.js:20:52)
    at Object.loadRules (/Users/tomconley/WebstormProjects/umbrelo-org/umbrelo/node_modules/tslint/lib/ruleLoader.js:46:24)
    at Linter.getEnabledRules (/Users/tomconley/WebstormProjects/umbrelo-org/umbrelo/node_modules/tslint/lib/linter.js:231:29)
    at Linter.lint (/Users/tomconley/WebstormProjects/umbrelo-org/umbrelo/node_modules/tslint/lib/linter.js:106:33)
    at TSLintPlugin.processLinting (/Applications/WebStorm.app/Contents/plugins/tslint/js/languageService/tslint-plugin.js:85:22)
    at TSLintPlugin.getErrors (/Applications/WebStorm.app/Contents/plugins/tslint/js/languageService/tslint-plugin.js:65:21)
    at TSLintPlugin.process (/Applications/WebStorm.app/Contents/plugins/tslint/js/languageService/tslint-plugin.js:34:29)
`
### Environment
 @nrwl/angular : 9.4.3
  @nrwl/cli : 9.4.3
  @nrwl/cypress : 9.4.3
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.4.3
  @nrwl/linter : 9.4.3
  @nrwl/nest : 9.4.3
  @nrwl/next : Not Found
  @nrwl/node : 9.4.3
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.3
  @nrwl/web : Not Found
  @nrwl/workspace : 9.4.3
  typescript : 3.8.3

**Comment by tommyc38** [comment]
I believe this is related to: #3189

**Comment by tommyc38** [comment]
My IDE was using json5 as .json.  When I fixed that setting, the JSON error appeared, it was ','.  Closing issue.
