### ISSUE TITLE
Nx 8 -> 9 migration issue: Unregistered task "run-schematic" in schematic "update-9-0-0"

### ISSUE THREAD

**Issue by carlitoborrito** [nrwl/nx#3244]
## Current Behavior

When running the migration from Nx 8 to 9, the `@nrwl/angular` update fails.  All other updates succeed.

## Expected Behavior

All steps in `migrations.json` should succeed

## Steps to Reproduce

These are the steps that were followed that led to this issue:

- Create the `migrations.json` with `nx migrate @nrwl/workspace`
- `npm install` with no modifications to `package.json`
- run `nx migrate --run-migrations=migrations.json`

Removing the `@nrwl/angular` update from `migrations.json` results in a successful migration.  Running the  `@nrwl/angular` update from `migrations.json` in isolation results in the same error

### Failure Logs

````
Running migration @nrwl/angular:update-9-0-0
Unregistered task "run-schematic" in schematic "update-9-0-0".
C:\----\node_modules\@nrwl\workspace\node_modules\yargs\yargs.js:1109
      else throw err
           ^

Error: Command failed: .\node_modules\.bin\tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Object.handler (C:\----\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:76:21)
    at Object.runCommand (C:\----\node_modules\@nrwl\workspace\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\----\node_modules\@nrwl\workspace\node_modules\yargs\yargs.js:1022:30)
    at Object.get [as argv] (C:\----\node_modules\@nrwl\workspace\node_modules\yargs\yargs.js:965:21)
    at Object.initLocal (C:\----\node_modules\@nrwl\cli\lib\init-local.js:20:79)
    at Object.<anonymous> (C:\----\node_modules\@nrwl\cli\bin\nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 35900,
  stdout: null,
  stderr: null
}
````

#### Before migrations
  @nrwl/angular : 8.12.11
  @nrwl/cli : 8.12.11
  @nrwl/cypress : 8.12.11
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.12.11
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.12.11
  @nrwl/web : Not Found
  @nrwl/workspace : 8.12.11
  typescript : 3.8.3

#### After creating migrations.json
  @nrwl/angular : 9.0.0
  @nrwl/cli : 8.12.11
  @nrwl/cypress : 9.0.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.0
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.12.11
  @nrwl/web : Not Found
  @nrwl/workspace : 9.0.0
  typescript : 3.8.3

#### migrations.json
````
{
  "migrations": [
    {
      "version": "9.0.0-beta.1",
      "description": "Update typescript to 3.6 and angular/cli to version 9",
      "factory": "./src/migrations/update-9-0-0/update-9-0-0",
      "package": "@nrwl/workspace",
      "name": "update-9-0-0"
    },
    {
      "version": "9.1.0-beta.1",
      "description": "Update prettier to 1.19.1 with support for typescript 3.7; Update eslint and tslint",
      "factory": "./src/migrations/update-9-1-0/update-9-1-0",
      "package": "@nrwl/workspace",
      "name": "update-9-1-0"
    },
    {
      "version": "9.1.0-beta.1",
      "description": "Update eslint and tslint config to provide better IDE support",
      "factory": "./src/migrations/update-9-1-0/update-lint-config",
      "package": "@nrwl/workspace",
      "name": "update-lint-config-9-1-0"
    },
    {
      "version": "9.2.0-beta.1",
      "description": "Add cacheable operations to nx.json",
      "factory": "./src/migrations/update-9-2-0/update-9-2-0",
      "package": "@nrwl/workspace",
      "name": "update-9-2-0"
    },
    {
      "version": "9.3.0-beta.1",
      "description": "Update prettier to v2",
      "factory": "./src/migrations/update-9-3-0/update-9-3-0",
      "package": "@nrwl/workspace",
      "name": "update-9-3-0"
    },
    {
      "version": "9.4.0-beta.1",
      "description": "Remove config builder option when using eslint to enable automatic detection",
      "factory": "./src/migrations/update-9-4-0/update-eslint-config",
      "package": "@nrwl/workspace",
      "name": "update-eslint-config"
    },
    {
      "version": "9.4.0-beta.1",
      "description": "Fix exclude patterns in tslint and eslint to ensure it does not break linting when a files option is defined",
      "factory": "./src/migrations/update-9-4-0/update-linters-exclude",
      "package": "@nrwl/workspace",
      "name": "update-linters-exclude"
    },
    {
      "version": "9.4.0-beta.1",
      "description": "Decorate cli to enable computation caching",
      "factory": "./src/migrations/update-9-4-0/add-decorate-cli",
      "package": "@nrwl/workspace",
      "name": "add-decorate-cli"
    },
    {
      "version": "9.0.0-beta.1",
      "description": "Upgrades Angular and Angular CLI to 9.0.0",
      "factory": "./src/migrations/update-9-0-0/update-9-0-0",
      "package": "@nrwl/angular",
      "name": "update-9-0-0"
    },
    {
      "version": "9.4.0-beta.1",
      "description": "Add Cypress ESLint plugin",
      "factory": "./src/migrations/update-9-4-0/add-cypress-eslint-plugin-9-4-0",
      "package": "@nrwl/cypress",
      "name": "add-cypress-eslint-plugin-9.4.0"
    },
    {
      "version": "9.0.0-beta.1",
      "description": "Upgrades jest-preset-angular to 8.0.0",
      "factory": "./src/migrations/update-9-0-0/update-9-0-0",
      "package": "@nrwl/jest",
      "name": "update-9.0.0"
    },
    {
      "version": "9.0.1-beta.1",
      "description": "Correctly sets passWithNoTests option",
      "factory": "./src/migrations/update-9-0-1/update-9-0-1",
      "package": "@nrwl/jest",
      "name": "update-9.0.1"
    },
    {
      "version": "9.2.0-beta.3",
      "description": "Update jest to v25",
      "factory": "./src/migrations/update-9-2-0/update-9-2-0",
      "package": "@nrwl/jest",
      "name": "update-9.2.0"
    }
  ]
}
````

**Comment by carlitoborrito** [comment]
This was resolved by updating `@nrwl/cli` to the latest version.  Not sure why that was not done automatically in the initial migration but that seems to have been the issue.
