### ISSUE TITLE
Gatsby new site gives MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#3247]
Hi,

Just tried using the gatsby (new feature), following this blog

https://blog.nrwl.io/gatsby-support-custom-workspace-layouts-and-more-in-nx-9-4-497ae105bf4

but I get the following error

```
➜  gatsby-try git:(master) ✗ nr -i
? Which script do you want to execute? start
running command with prefix "start"

> gatsby-try@0.0.0 start /Users/ian/Development/Personal/typescript/gatsby-try
> nx serve


> nx run myblog:serve
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '/Users/ian/Development/Personal/typescript/gatsby-try/node_modules/gatsby-cli/lib/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Error during serve
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-try@0.0.0 start: `nx serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-try@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ian/.npm/_logs/2020-06-28T07_28_28_283Z-debug.log
NPM command npm run start -- failed with code 1
```

**Comment by jaysoo** [comment]
Tracking it here https://github.com/nrwl/gatsby/issues/19
