### ISSUE TITLE
Error migrating to Nx 10

### ISSUE THREAD

**Issue by cbejensen** [nrwl/nx#3307]
I realize Nx 10 is still in beta at this point but thought you may want to know.

## Current Behavior
Cannot migrate to `@nrwl/workspace@10.0.0-beta.1`

## Expected Behavior
Successful migration

## Steps to Reproduce
```
> nx migrate @nrwl/workspace@10.0.0-beta.1
...
> nx migrate --run-migrations=migrations.json
```

I get the same failure when I run the above commands on [your example repo](https://github.com/nrwl/nx-examples)

### Failure Logs
The first command to update `package.json` and generate `migration.json` seems mostly fine, with a couple warnings:
```
> nx migrate @nrwl/workspace@10.0.0-beta.1
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@10.0.0-beta.1
...
Could not find '@schematics/angular/migrations/migration-collection.json' in '@angular/cli'. Skipping it
...
Could not find '@schematics/angular/migrations/migration-collection.json' in '@angular/cli'. Skipping it
...
The migrate command has run successfully.
...
```

The second command to actually perform the migration fails quickly:
```
> nx migrate --run-migrations=migrations.json
Running migration @nrwl/workspace:add-default-branch-to-nx-json
Successfully finished @nrwl/workspace:add-default-branch-to-nx-json
---------------------------------------------------------
Running migration @nrwl/workspace:solution-tsconfigs
Schematic "solution-tsconfigs" not found in collection "@nrwl/workspace".
/Users/cj/Code/recover-ui/node_modules/yargs/yargs.js:1109
      else throw err
           ^

Error: Command failed: ./node_modules/.bin/tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at Object.handler (/Users/cj/Code/recover-ui/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:76:21)
    at Object.runCommand (/Users/cj/Code/recover-ui/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/cj/Code/recover-ui/node_modules/yargs/yargs.js:1022:30)
    at Object.get [as argv] (/Users/cj/Code/recover-ui/node_modules/yargs/yargs.js:965:21)
    at Object.initLocal (/Users/cj/Code/recover-ui/node_modules/@nrwl/cli/lib/init-local.js:22:13)
    at Object.<anonymous> (/Users/cj/Code/recover-ui/node_modules/@nrwl/cli/bin/nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13587,
  stdout: null,
  stderr: null
}
```

### Environment
```
@nrwl/angular : 9.5.0
@nrwl/cli : 9.5.0
@nrwl/cypress : 9.5.0
@nrwl/eslint-plugin-nx : Not Found
@nrwl/express : Not Found
@nrwl/jest : 9.5.0
@nrwl/linter : Not Found
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 9.5.0
@nrwl/web : Not Found
@nrwl/workspace : 9.5.0
typescript : 3.8.3
```

**Comment by FrozenPandaz** [comment]
Hi, did you run `npm install` before running `nx migrate --run-migrations=migrations.json`?

**Comment by cbejensen** [comment]
I ran `yarn` before the first command. Do I need to run it after the first and before the second?

**Comment by cbejensen** [comment]
So sorry, I apparently misread the instructions at the end of the first `nx migrate` command's logs. This worked for me:

```
> nx migrate @nrwl/workspace@10.0.0-beta.1
> yarn
> nx migrate --run-migrations=migrations.json
```
