### ISSUE TITLE
Error: spawnSync

### ISSUE THREAD

**Issue by daniele-zurico** [nrwl/nx#335]
Hi guys,
I'm trying to follow the tutoria to install a project. I run this command:
```
create-nx-workspace support-ticket-suite --directory=ticket-suite --npm-scope=suite
```
But I'm getting this error:
```
Project 'support-ticket-suite' successfully created.
child_process.js:533
    throw err;
    ^

Error: spawnSync /bin/sh ENOENT
    at exports._errnoException (util.js:1028:11)
    at spawnSync (child_process.js:468:20)
    at Object.execSync (child_process.js:524:13)
    at Object.<anonymous> (/Users/danielezurico/.nvm/versions/node/v7.6.0/lib/node_modules/@nrwl/schematics/bin/create-nx-workspace.js:68:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

OS: Mac Os High Sierra (10.13.3)
Angular CLI: 1.7.3
Node: 7.6.0
bs-dzurico:Desktop danielezurico$ sudo npm list -g @nrwl/schematics
/Users/danielezurico/.nvm/versions/node/v7.6.0/lib
└── @nrwl/schematics@0.8.0

**Comment by Yonet** [comment]
@daniele-zurico fixed here: https://github.com/nrwl/nx/commit/da9310e9dbb4eb3294200ca72bfa70b14faec2c2
You can update your global @nrwl/schematics before creating the workspace by running:
```
yarn add global @nrwl/schematics@next
//Or
npm install -g  @nrwl/schematics@next
```
Closing. Thanks!
