### ISSUE TITLE
"The Schematic workflow and Workspace creation failed" with Next.js preset.

### ISSUE THREAD

**Issue by metebyte** [nrwl/nx#3359]
I can't create Nx Workspace with Next.js preset. Throws "The Schematic workflow failed." error.

## Current Behavior

```
⠙ Installing packages...warning node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning "@zeit/next-sass > sass-loader@6.0.6" has unmet peer dependency "webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0".
warning "@zeit/next-sass > @zeit/next-css > css-loader@1.0.0" has unmet peer dependency "webpack@^4.0.0".
warning "@zeit/next-sass > @zeit/next-css > mini-css-extract-plugin@0.4.3" has unmet peer dependency "webpack@^4.4.0".
warning "@nrwl/next > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".
warning "@nrwl/next > @nrwl/react > @nrwl/cypress > @cypress/webpack-preprocessor@4.1.5" has unmet peer dependency "webpack@^4.18.1".
✖ Package install failed, see above.
The Schematic workflow failed. See above.
Workspace creation failed, see above.
(node:47565) UnhandledPromiseRejectionWarning: Error: Command failed: "/var/folders/4l/1yq_5m5958l9kwk5xrjtfqzc0000gn/T/tmp-47565MLd85l6F98zV/node_modules/.bin/tao" new orduhedefreklam --preset="next" --appName="web" --style="scss" --interactive=false --collection=/var/folders/4l/1yq_5m5958l9kwk5xrjtfqzc0000gn/T/tmp-47565MLd85l6F98zV/node_modules/@nrwl/workspace/collection.json
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createApp (/Users/metebyte/.npm/_npx/47565/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:366:21)
    at /Users/metebyte/.npm/_npx/47565/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:85:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:47565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected Behavior

Expected to create Nx workspace with Next.js preset.

## Steps to Reproduce

Platform versions:
```
❯ node -v
v14.5.0

❯ npm -v
6.14.6
```

Dependency versions:
```
"@angular/cli": "9.1.0",
"@nrwl/workspace": "9.5.1",
```

With the specified versions above, run:
```
❯ npx create-nx-workspace@latest app_name
❯ Choose next.js
❯ Choose SASS (.scss)
❯ Choose local development.
```

[Here's](https://github.com/metebyte/nx-next-error) the repo that I'm having this problem.

### Environment

```
❯ nx report

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.5.1
  @nrwl/cli : 9.5.1
  @nrwl/cypress : 9.5.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.1
  @nrwl/linter : 9.5.1
  @nrwl/nest : 9.5.1
  @nrwl/next : Not Found
  @nrwl/node : 9.5.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 9.5.1
  typescript : 3.8.3
```

**Comment by vsavkin** [comment]
Hi there! Thank you for submitting the issue.

I'm a bit puzzled by the result of nx report. Did you manually provided Angular CLI as the chosen CLI?

What happens if you run this:

```
npx create-nx-workspace@10.0.1 --preset=next
```

**Comment by metebyte** [comment]
> Hi there! Thank you for submitting the issue.
> 
> I'm a bit puzzled by the result of nx report. Did you manually provided Angular CLI as the chosen CLI?
> 
> What happens if you run this:
> 
> ```
> npx create-nx-workspace@10.0.1 --preset=next
> ```

Here's the result 🙂 I think my npm and nx configurations are messed up.

```
❯ npx create-nx-workspace@10.0.1 --preset=next
npx: installed 193 in 118.759s
? Workspace name (e.g., org name)     orduhedefreklam
? Application name                    web
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
? Use the free tier of the distributed cache provided by Nx Cloud? No  [Only use local computation cache]
Creating a sandbox with Nx...
error Couldn't find package "@angular-devkit/core@~10.0.0" required by "@nrwl/workspace@10.0.1" on the "npm" registry.
Error: Couldn't find package "@angular-devkit/schematics@~10.0.0" required by "@nrwl/workspace@10.0.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "rxjs@^6.5.4" required by "@nrwl/workspace@10.0.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at listOnTimeout (internal/timers.js:520:9)
Error: Couldn't find package "fs-extra@6.0.0" required by "@nrwl/workspace@10.0.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@angular-devkit/core@~10.0.0" required by "@nrwl/tao@10.0.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@angular-devkit/schematics@~10.0.0" required by "@nrwl/tao@10.0.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "rxjs@^6.4.0" required by "inquirer@^6.3.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "rxjs@6.5.5" required by "@angular-devkit/architect@~0.1000.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@angular-devkit/core@10.0.4" required by "@angular-devkit/architect@~0.1000.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:10090) UnhandledPromiseRejectionWarning: Error: Command failed: yarn install --silent
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createSandbox (/Users/metebyte/.npm/_npx/10090/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:332:21)
    at /Users/metebyte/.npm/_npx/10090/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:84:40
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10090) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mandarini** [comment]
Hi there @metebyte! Thanks for filing an issue! Unfortunately, I could not reproduce your issue. Can you please try with the latest version of Nx and let me know if the problem persists?
