### ISSUE TITLE
nrwl/nest:update migration fails when migrating to 10.0.4

### ISSUE THREAD

**Issue by zaunermax** [nrwl/nx#3387]
## Current Behavior
We tried migrating from nx `9.5.1` to `10.0.4` with in our nest/react nx project but the nest migration failed when executing all the migrations from `migrations.json`.

## Expected Behavior
All migrations from `migrations.json` should run through without erroring.

## Steps to Reproduce
We have a quite complicated nest module structure, where modules live in subdirectories. Basically to reproduce, create a project with a nest app, create some libraries with the `--directory` command and then pass some nested directory like `api-core/modules`. Not sure if that's the actual culprit tho... Then migrate from nx` 9.5.1` to `10.0.4`. When running the `migrations.json` file it should error.

### Failure Logs
(i changed the paths due to obv. reasons)
```
Running migration @nrwl/nest:update-10-0-0
Cannot read property 'startsWith' of undefined
/home/user/dev/coolProject/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1109
      else throw err
           ^

Error: Command failed: ./node_modules/.bin/tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.handler (/home/user/dev/coolProject/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:77:21)
    at Object.runCommand (/home/user/dev/coolProject/node_modules/@nrwl/workspace/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/user/dev/coolProject/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1022:30)
    at Object.get [as argv] (/home/user/dev/coolProject/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:965:21)
    at Object.initLocal (/home/user/dev/coolProject/node_modules/@nrwl/cli/lib/init-local.js:22:13)
    at Object.<anonymous> (/home/user/dev/coolProject/node_modules/@nrwl/cli/bin/nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 20166,
  stdout: null,
  stderr: null
}
```

### Environment
```
  @nrwl/angular : Not Found
  @nrwl/cli : 10.0.4
  @nrwl/cypress : 10.0.4
  @nrwl/eslint-plugin-nx : 10.0.4
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.4
  @nrwl/linter : 10.0.4
  @nrwl/nest : 10.0.4
  @nrwl/next : Not Found
  @nrwl/node : 10.0.4
  @nrwl/react : 10.0.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.4
  @nrwl/web : 10.0.4
  @nrwl/workspace : 10.0.4
  typescript : 3.9.7

```

**Comment by DenysVuika** [comment]
Also, I am getting this:

```
❯ Migrate tsconfigs to solution style tsconfigs
✖ Migration failed: Root tsconfig.json does not exist
```

**Comment by FrozenPandaz** [comment]
Hm, we've migrated a few workspaces that use NestJS and didn't run into this issue. If possible, please provide a repo that exhibits the issue so that we can easily take a look.

**Comment by zaunermax** [comment]
jfyi - I think my migration problem might have to do something with the fact, that we manually upgraded nest to version 7. Maybe the migration isn't written defensively enough but after reading the migration code we saw that we already did the steps in the nest migration. Closing this issue now, thanks!
