### ISSUE TITLE
Using 'make-angular-cli-faster' for multi project in one workplace

### ISSUE THREAD

**Issue by narlack** [nrwl/nx#3410]
## Current Behavior
make-angular-cli-faster cant be used for multi projects.

## Expected Behavior
make-angular-cli-faster can be used for multi projects.

## Steps to Reproduce

1. Create a few angular app with nx in one workplace (we have 2 angular apps).
2. Run command: `npx make-angular-cli-faster`.

### Failure Logs
```
>  NX  Nx initialization

The schematic can only be used with Angular CLI workspaces with a single project.
Error: Command failed: nx g @nrwl/workspace:ng-add --preserveAngularCLILayout
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at /Users/username/.npm/_npx/63961/lib/node_modules/make-angular-cli-faster/make-angular-cli-faster.js:59:25
    at Generator.next (<anonymous>)
    at /Users/username/.npm/_npx/63961/lib/node_modules/make-angular-cli-faster/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/username/.npm/_npx/63961/lib/node_modules/make-angular-cli-faster/node_modules/tslib/tslib.js:111:16)
    at main (/Users/username/.npm/_npx/63961/lib/node_modules/make-angular-cli-faster/make-angular-cli-faster.js:54:20)
    at Object.<anonymous> (/Users/username/.npm/_npx/63961/lib/node_modules/make-angular-cli-faster/make-angular-cli-faster.js:76:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 64055,
  stdout: null,
  stderr: null
}
```

### Environment
  @nrwl/angular : 10.0.6
  @nrwl/cli : 10.0.6
  @nrwl/cypress : 10.0.6
  @nrwl/jest : 10.0.6
  @nrwl/linter : 10.0.6
  @nrwl/nest : 10.0.6
  @nrwl/node : 10.0.6
  @nrwl/tao : 10.0.6
  @nrwl/workspace : 10.0.6
  typescript : 3.9.7

**Comment by gilsdav** [comment]
+/- the same problem. I did not use NX to create my mono-repo but I would like to add the nx cache with this command.

@narlack If you created your project with NX, why don't you add nx-cloud yourself like in [this example](https://github.com/nrwl/nx-distributed-cache-example) ? If I understand the behavior of `make-angular-cli-faster` command : it's add nx-cloud feature on non nx project. So this is not what you need.
