### ISSUE TITLE
Storybooks lib: no such file or directory, stat 'tsconfig.json' with nx 10

### ISSUE THREAD

**Issue by ericwooley** [nrwl/nx#3428]
Adding a tsconfig.json file at the root, with the contents: 
```
{ "extends": "./tsconfig.base.json" }
```

Fixes the problem

## Current Behavior

After upgrading to nx 10, storybooks addon no longer works. It throws the error:
`no such file or directory, stat 'tsconfig.json'`
## Expected Behavior

Storybooks should work

## Steps to Reproduce
Create a react ui lib with storybooks in nx 9, then upgrade to nx 10.

### Failure Logs

```
12:14:36 tengable  master [⇡!] is 📦 v0.0.0 ⬢ v13.14.0 🐳 v19.03.12 
➜ nx storybook ui

> nx run ui:storybook 
info => Loading presets
info => Loading presets
info => Loading custom manager config.
info => Loading config/preview file in "libs/ui/.storybook".
info => Loading custom Webpack config (full-control mode).
info => Using base config because react-scripts is not installed.
ERR! Error: ENOENT: no such file or directory, stat 'tsconfig.json'
ERR!     at Object.statSync (fs.js:1029:3)
ERR!     at resolveConfigPath (/home/ericwooley/tengable/node_modules/tsconfig-paths/lib/tsconfig-loader.js:48:12)
ERR!     at loadSyncDefault (/home/ericwooley/tengable/node_modules/tsconfig-paths/lib/tsconfig-loader.js:26:22)
ERR!     at tsConfigLoader (/home/ericwooley/tengable/node_modules/tsconfig-paths/lib/tsconfig-loader.js:20:22)
ERR!     at configLoader (/home/ericwooley/tengable/node_modules/tsconfig-paths/lib/config-loader.js:29:22)
ERR!     at Object.loadConfig (/home/ericwooley/tengable/node_modules/tsconfig-paths/lib/config-loader.js:8:12)
ERR!     at new TsconfigPathsPlugin (/home/ericwooley/tengable/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:19:42)
ERR!     at module.exports (/home/ericwooley/tengable/.storybook/webpack.config.js:4:19)
ERR!     at module.exports (/home/ericwooley/tengable/libs/ui/.storybook/webpack.config.js:4:18)
ERR!     at Object.webpack (/home/ericwooley/tengable/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:56:12)
ERR!     at async Promise.all (index 1)
ERR!     at async Object.buildDevStandalone (/home/ericwooley/tengable/node_modules/@storybook/core/dist/server/build-dev.js:343:9)
ERR!  Error: ENOENT: no such file or directory, stat 'tsconfig.json'
ERR!     at Object.statSync (fs.js:1029:3)
ERR!     at resolveConfigPath (/home/ericwooley/tengable/node_modules/tsconfig-paths/lib/tsconfig-loader.js:48:12)
ERR!     at loadSyncDefault (/home/ericwooley/tengable/node_modules/tsconfig-paths/lib/tsconfig-loader.js:26:22)
ERR!     at tsConfigLoader (/home/ericwooley/tengable/node_modules/tsconfig-paths/lib/tsconfig-loader.js:20:22)
ERR!     at configLoader (/home/ericwooley/tengable/node_modules/tsconfig-paths/lib/config-loader.js:29:22)
ERR!     at Object.loadConfig (/home/ericwooley/tengable/node_modules/tsconfig-paths/lib/config-loader.js:8:12)
ERR!     at new TsconfigPathsPlugin (/home/ericwooley/tengable/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:19:42)
ERR!     at module.exports (/home/ericwooley/tengable/.storybook/webpack.config.js:4:19)
ERR!     at module.exports (/home/ericwooley/tengable/libs/ui/.storybook/webpack.config.js:4:18)
ERR!     at Object.webpack (/home/ericwooley/tengable/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:56:12)
ERR!     at async Promise.all (index 1)
ERR!     at async Object.buildDevStandalone (/home/ericwooley/tengable/node_modules/@storybook/core/dist/server/build-dev.js:343:9) {
ERR!   errno: -2,
ERR!   syscall: 'stat',
ERR!   code: 'ENOENT',
ERR!   path: 'tsconfig.json'
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

^[[A^C
```
### Environment

```
➜ nx report                

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 10.0.6
  @nrwl/cypress : 10.0.6
  @nrwl/eslint-plugin-nx : 10.0.6
  @nrwl/express : 10.0.6
  @nrwl/jest : 10.0.6
  @nrwl/linter : 10.0.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.0.6
  @nrwl/react : 10.0.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.6
  @nrwl/web : 10.0.6
  @nrwl/workspace : 10.0.6
  typescript : 3.9.7
```

**Comment by mandarini** [comment]
Hi @ericwooley ! Thanks for filing an issue!

Unfortunately, I could not reproduce your issue 😞 . 
Let me tell you the steps I followed, and you can tell me if you did the same!

1. Create an Nx workspace with Nx v9
    - `npx create-nx-workspace@9.0.0 test-workspace`
    - choose to create a `react` app
2. From within the workspace, generate a react library and a react component in the library
    - `nx g @nrwl/react:lib ui`
    - `nx g @nrwl/react:component test-component --project=ui --export`
3. The above commands result in the following files being created:
```
CREATE libs/ui/.eslintrc (7019 bytes)
CREATE libs/ui/README.md (158 bytes)
CREATE libs/ui/tsconfig.json (405 bytes)
CREATE libs/ui/tsconfig.lib.json (224 bytes)
CREATE libs/ui/src/index.ts (26 bytes)
CREATE libs/ui/tsconfig.spec.json (273 bytes)
CREATE libs/ui/jest.config.js (228 bytes)
CREATE libs/ui/src/lib/ui.css (0 bytes)
CREATE libs/ui/src/lib/ui.spec.tsx (260 bytes)
CREATE libs/ui/src/lib/ui.tsx (248 bytes)
UPDATE tsconfig.json (567 bytes)
UPDATE workspace.json (5349 bytes)
UPDATE nx.json (437 bytes)
CREATE libs/ui/src/lib/test-component/test-component.css (0 bytes)
CREATE libs/ui/src/lib/test-component/test-component.spec.tsx (305 bytes)
CREATE libs/ui/src/lib/test-component/test-component.tsx (316 bytes)
UPDATE libs/ui/src/index.ts (79 bytes)
```
4. Add Storybook of Nx version 9:
    - `yarn add --dev @nrwl/storybook@9.0.0`

and now in my `package.json` my `devDependencies` look like this:
```
"devDependencies": {
    ...,
    "@nrwl/react": "9.0.0",
    "@nrwl/storybook": "9.0.0",
    "@nrwl/workspace": "9.0.0",
    ...
```
5. Generate Storybook for the `ui` library I created in step 3:
    - ` nx g @nrwl/react:storybook-configuration --name=ui`
which gives me the following files:
```
CREATE .storybook/addons.js (42 bytes)
CREATE .storybook/tsconfig.json (113 bytes)
CREATE .storybook/webpack.config.js (396 bytes)
CREATE libs/ui/.storybook/tsconfig.json (180 bytes)
CREATE libs/ui/.storybook/addons.js (37 bytes)
CREATE libs/ui/.storybook/config.js (214 bytes)
CREATE libs/ui/.storybook/webpack.config.js (590 bytes)
CREATE tslint.json (1622 bytes)
CREATE apps/ui-e2e/tslint.json (42 bytes)
CREATE apps/ui-e2e/cypress.json (442 bytes)
CREATE apps/ui-e2e/tsconfig.e2e.json (167 bytes)
CREATE apps/ui-e2e/tsconfig.json (137 bytes)
CREATE apps/ui-e2e/src/fixtures/example.json (80 bytes)
CREATE apps/ui-e2e/src/plugins/index.js (832 bytes)
CREATE apps/ui-e2e/src/support/commands.ts (1068 bytes)
CREATE apps/ui-e2e/src/support/index.ts (599 bytes)
UPDATE package.json (1589 bytes)
UPDATE libs/ui/tsconfig.lib.json (302 bytes)
UPDATE workspace.json (7209 bytes)
UPDATE nx.json (547 bytes)
```
6. Check to see if Storybook runs
    - `nx run ui:storybook`
    - Storybook for Nx v9 runs successfully
7. **MIGRATION**: Run the migration command that will update the dependencies:
    - `nx migrate @nrwl/workspace`
8. Check that `package.json` looks ok
```
  "devDependencies": {
     ...,
    "@nrwl/react": "10.1.0",
    "@nrwl/storybook": "10.1.0",
    "@nrwl/workspace": "10.1.0",
    ...
```
9. Run `yarn` again
10. Run the actual migrations:
    - `nx migrate --run-migrations=migrations.json`
11. Migrations complete, run Storybook again to see if it works:
    - `nx run ui:storybook`
    - Storybook runs successfully!

I also tried the same procedure with Nx version `9.6.0` (`npx create-nx-workspace@9.0.0 test-workspace`) and then migrate to latest, and I got the same, successful, results. 😕 

I see that you tried the migration with `10.0.6`, can you please try once more and let me know if the error persists?

Also, did you try migrating from a different version than `9.0.0` or `9.6.0`? Please let me know what I can do to reproduce your issue, or if you have any more information that I could find useful, so that I can help you out!

Thanks again!

**Comment by ericwooley** [comment]
I can no longer reproduce either, I am not sure what was causing the issue. Maybe so kind of misconfiguration with global typescript install or something. 

Sorry for wasting your time with that, and thank you for looking into it.

**Comment by mandarini** [comment]
Hi @ericwooley ! Thank you so much for checking again! No worries at all, we're always glad to help out the community! I'm so happy you worked it out! 😄

**Comment by paustint** [comment]
For anyone else that encounters this problem, I wanted to add my notes here for how I resolved it.

I am using `tailwindcss` which required some (painful to figure out) custom configuration to get working, which may have been the reason why the above error occurred.

**Versions**: nrwl `"9.4.2` --> `10.2.1`

**Error when running storybook**:
```
info => Using base config because react-scripts is not installed.
ERR! Error: ENOENT: no such file or directory, stat 'tsconfig.json'
ERR!     at Object.statSync (fs.js:933:3)
ERR!     at resolveConfigPath (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:48:12)
ERR!     at loadSyncDefault (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:26:22)
ERR!     at tsConfigLoader (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:20:22)
ERR!     at configLoader (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths/lib/config-loader.js:29:22)
ERR!     at Object.loadConfig (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths/lib/config-loader.js:8:12)
ERR!     at new TsconfigPathsPlugin (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:19:42)
ERR!     at module.exports (/Users/foo/dev/node/my-app/libs/ui/.storybook/webpack.config.js:10:19)
ERR!  Error: ENOENT: no such file or directory, stat 'tsconfig.json'
ERR!     at Object.statSync (fs.js:933:3)
ERR!     at resolveConfigPath (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:48:12)
ERR!     at loadSyncDefault (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:26:22)
ERR!     at tsConfigLoader (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths/lib/tsconfig-loader.js:20:22)
ERR!     at configLoader (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths/lib/config-loader.js:29:22)
ERR!     at Object.loadConfig (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths/lib/config-loader.js:8:12)
ERR!     at new TsconfigPathsPlugin (/Users/foo/dev/node/my-app/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.js:19:42)
ERR!     at module.exports (/Users/foo/dev/node/my-app/libs/ui/.storybook/webpack.config.js:10:19) {
ERR!   errno: -2,
ERR!   syscall: 'stat',
ERR!   code: 'ENOENT',
ERR!   path: 'tsconfig.json'
ERR! }
```

I have a `webpack.config.js` file that looked like this

```javascript
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const rootWebpackConfig = require('../../../.storybook/webpack.config');
// Export a function. Accept the base config as the only param.
module.exports = async ({ config, mode }) => {
  config = await rootWebpackConfig({ config, mode });

  config.resolve.extensions.push('.tsx');
  config.resolve.extensions.push('.ts');

  const tsPaths = new TsconfigPathsPlugin();

  config.resolve.plugins ? config.resolve.plugins.push(tsPaths) : (config.resolve.plugins = [tsPaths]);

  config.module.rules.push({
    test: /\.(ts|tsx)$/,
    loader: require.resolve('babel-loader'),
    options: {
      presets: ['@babel/preset-env', '@babel/preset-react', '@babel/preset-typescript'],
      plugins: ['@babel/plugin-proposal-class-properties'],
    },
  });
  return config;
};
```

I updated this part to point to the current tsconfig that is in the same directory as my `webpack.config.js` for storybook:

```javascript
  const tsPaths = new TsconfigPathsPlugin({
    configFile: 'libs/ui/.storybook/tsconfig.json',
  });
```

Then for some reason the build still failed for a missing plugin - `postcss-preset-env`. I have no idea why things worked before without this but now they do not, but I installed this library and storybook started without any issues.

**Comment by Stupidism** [comment]
Encountered the same problem when upgrade from `9.4.1` to `10`, and @paustint 's solution didn't match my `webpack.config.js`. And my final solution is to remove old storybook configs and regenerate them with cmd line:

```bash
mv .storybook .storybook1
mv libs/my-lib/.storybook libs/my-lib/.storybook1
```
 and remove the two task configurations in workspace.json
```diff
"my-lib"."architect": {
  ...
- "storybook" : {
-  ...
-},
-  "build-storybook": {
- ...
-}
}
```
and then regenerate the storybook configs with cmd:

```bash
npm run nx g @nrwl/react:storybook-configuration -- --name=my-lib

> abs@0.0.0 nx /Users/zishizi/Documents/abs
> nx "g" "@nrwl/react:storybook-configuration" "--name=my-lib"

? Configure a cypress e2e app to run against the storybook instance? No
? Automatically generate story files for components declared in this library? No
? Automatically generate *.spec.ts files in the cypress e2e app generated by the cypress-configure schematic? No
            There is already an e2e project setup
CREATE .storybook/main.js (84 bytes)
CREATE .storybook/tsconfig.json (180 bytes)
CREATE .storybook/webpack.config.js (472 bytes)
CREATE libs/my-lib/.storybook/main.js (256 bytes)
CREATE libs/my-lib/.storybook/preview.js (126 bytes)
CREATE libs/my-lib/.storybook/tsconfig.json (222 bytes)
CREATE libs/my-lib/.storybook/webpack.config.js (2181 bytes)
UPDATE package.json (3900 bytes)
UPDATE nx.json (820 bytes)
UPDATE libs/my-lib/tsconfig.lib.json (760 bytes)
UPDATE libs/my-lib/tsconfig.json (610 bytes)
UPDATE workspace.json (9452 bytes)
UPDATE libs/my-lib/.eslintrc.json (7682 bytes)
```

**Comment by mxa0079** [comment]
If anyone runs into this issue: make sure you are running the `nx` command from the root of your repo. If you run it from inside your package or app directory, you will run into this problem. 

I hope this helps, have fun coding!

**Comment by MiguelNiblock** [comment]
> If anyone runs into this issue: make sure you are running the `nx` command from the root of your repo. If you run it from inside your package or app directory, you will run into this problem.
> 
> I hope this helps, have fun coding!

This helped. The documentation doesn't specify that you have to be on the root directory to run nx serve commands reliably.

**Comment by asheroto** [comment]
> If anyone runs into this issue: make sure you are running the `nx` command from the root of your repo. If you run it from inside your package or app directory, you will run into this problem.
> 
> I hope this helps, have fun coding!

As mentioned 😊...

from root...

`nx serve --project <your project name>`
