### ISSUE TITLE
Using affected:test with multiple Jest reporters fails because of flags merging

### ISSUE THREAD

**Issue by aramperes** [nrwl/nx#3450]
## Current Behavior
Running the command:

```
nx affected:test --reporters=default --reporters=jest-junit --base=master
```

Nx merges the `--reporters` flags into one:

```
>  NX  Running target test for projects:

  [ snip ]
  
  With flags:
    --reporters=default,jest-junit
```

Which causes the following error:

```
> ng run [library]:test --reporters=default,jest-junit 
An unhandled exception occurred: Could not resolve a module for a custom reporter.
  Module name: default,jest-junit
See "/tmp/ng-hrBzEh/angular-errors.log" for further details.
```

In fact, Jest doesn't know to split the reporters by commas. It expects two flags.

## Expected Behavior

Multiple flags being passed should be preserved that way, instead of merging with `,` when passing down to the actual script.

## Steps to Reproduce

1. Run `nx affected:test` with two flags of the same name, e.g. `nx affected:test --blah=a --blah=b`
2. Observe that the `With flags:` section lists `--blah=a,b`

### Failure Logs
The failure on the Jest side:

```
[error] Error: Could not resolve a module for a custom reporter.
  Module name: default,jest-junit
    at node_modules/jest-config/build/normalize.js:567:15
    at Array.map (<anonymous>)
    at normalizeReporters (node_modules/jest-config/build/normalize.js:549:33)
    at normalize (node_modules/jest-config/build/normalize.js:642:5)
    at readConfig (node_modules/jest-config/build/index.js:220:68)
    at async readConfigs (node_modules/jest-config/build/index.js:401:26)
    at async Object.runCLI (node_modules/@jest/core/build/cli/index.js:198:59
```

### Environment

```
  @nrwl/angular : 10.0.6
  @nrwl/cli : 10.0.6
  @nrwl/cypress : 10.0.6
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.0.6
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.0.6
  @nrwl/web : Not Found
  @nrwl/workspace : 10.0.6
  typescript : 3.9.7
```

**Comment by aramperes** [comment]
As a workaround, we can specify `reporters` in `jest.config.js`. Since we wanted to have different reporters for different commands, we can use environment variables in there:

```js
// jest.config.js
module.exports = {
    testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
    transform: {
        '^.+\\.(ts|js|html)$': 'ts-jest',
    },
    resolver: '@nrwl/jest/plugins/resolver',
    moduleFileExtensions: ['ts', 'js', 'html'],
    coverageReporters: ['html'],
    reporters: process.env['CI'] === '1' ? ['default', 'jest-junit'] : ['default']
};
```
