### ISSUE TITLE
Migrate command failed

### ISSUE THREAD

**Issue by juuyan** [nrwl/nx#3463]
## Current Behavior
Migrate to new versions from 9.3.0 and failed with the following error
I've tried to migrate to 10.0.7, 10.0.6 and.9.5.1, all failed with same error.
Also have tried the suggestion which is adding the workspace package and using the newest version of the migrate functionality to migrate but failed again.
```
Command failed: npm install @nrwl/next@9.5.1 --prefix=/var/folders/w9/j15n_h5n45z2d2wbp799ykdh0000gn/T/tmp-152716lly9y54hKWR
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! Unexpected end of JSON input while parsing near '...trib-concat":"^0.5.0"'

.../node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1109
      else throw err
           ^

Error: Command failed: ./node_modules/.bin/tao migrate @nrwl/workspace@9.5.1 --from=@nrwl/workspace@9.3.0
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at Object.handler (.../node_modules/@nrwl/workspace/src/command-line/nx-commands.js:76:21)
    at Object.runCommand (.../node_modules/@nrwl/workspace/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (.../node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1022:30)
    at Object.get [as argv] (.../node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:965:21)
    at Object.initLocal (.../node_modules/@nrwl/cli/lib/init-local.js:22:13)
    at Object.<anonymous> (.../node_modules/@nrwl/cli/bin/nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 15271,
  stdout: null,
  stderr: null
}
```

### Failure Logs
```
1364 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...trib-concat":"^0.5.0"'
1364 verbose stack     at JSON.parse (<anonymous>)
1364 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
1364 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
1364 verbose stack     at runMicrotasks (<anonymous>)
1364 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

Unfortunately, I'm not able to reproduce it. Could you try to create a repo using 9.3.0 that fails to be migrated?

**Comment by juuyan** [comment]
Thanks for the reply, yet I am not sure how to reproduce it. I tried a lot and failed thus simply recreated a mono repo...😅

**Comment by vsavkin** [comment]
So you aren't able to reproduce the problem with a different repo, right?

If you do the following, it will work, right?:

- npx create-nx-workspace@9.3.0 myorg --preset=next
- cd myorg
- nx migrate latest
