### ISSUE TITLE
Copy Plugin errors out with Nx 10.1.0

### ISSUE THREAD

**Issue by nartc** [nrwl/nx#3590]
## Current Behavior

Running NestJS backend with Nx 10.1.0 errors out with the following error:

```
[error] ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options.patterns should be an non-empty array.
    at validate (/Users/chautran/Code/Projects/@nartc/jira-clone-angular/ngvn/node_modules/schema-utils/dist/validate.js:96:11)
    at new CopyPlugin (/Users/chautran/Code/Projects/@nartc/jira-clone-angular/ngvn/node_modules/copy-webpack-plugin/dist/index.js:24:30)
    at Object.getBaseWebpackPartial (/Users/chautran/Code/Projects/@nartc/jira-clone-angular/ngvn/node_modules/@nrwl/node/src/utils/config.js:89:43)
    at Object.getNodeWebpackConfig (/Users/chautran/Code/Projects/@nartc/jira-clone-angular/ngvn/node_modules/@nrwl/node/src/utils/node.config.js:40:18)
    at MapSubscriber.project (/Users/chautran/Code/Projects/@nartc/jira-clone-angular/ngvn/node_modules/@nrwl/node/src/builders/build/build.impl.js:28:36)
    at MapSubscriber._next (/Users/chautran/Code/Projects/@nartc/jira-clone-angular/ngvn/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/chautran/Code/Projects/@nartc/jira-clone-angular/ngvn/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapSubscriber._next (/Users/chautran/Code/Projects/@nartc/jira-clone-angular/ngvn/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/chautran/Code/Projects/@nartc/jira-clone-angular/ngvn/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /Users/chautran/Code/Projects/@nartc/jira-clone-angular/ngvn/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
```

## Expected Behavior

Should work.

10.0.13 worked fine.

## Steps to Reproduce

https://github.com/angular-vietnam/jira-clone-angular/tree/feature/github-signin/ngvn 
The issue can be reproduced using this repo.
1. Clone the repo
2. Check out branch feature/github-signin
3. `cd ngvn`
4. Update nx to 10.1.0 and install dependencies
5. `npm run start:api`

Error will show

### Failure Logs

Log is provided above.

### Environment

```
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.1.0
  @nrwl/cli : 10.1.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.1.0
  @nrwl/nest : 10.1.0
  @nrwl/next : Not Found
  @nrwl/node : 10.1.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.1.0
  @nrwl/web : Not Found
  @nrwl/workspace : 10.1.0
  typescript : 3.9.7
```

**Comment by dbvcode** [comment]
> As a workaround you can add an empty assets folder to each affected project and reference it in the build options inside angular.json

Seems creating a file in the fake assets folder is also needed.

**Comment by mraustinmiller** [comment]
> > As a workaround you can add an empty assets folder to each affected project and reference it in the build options inside angular.json
> 
> Seems creating a file in the fake assets folder is also needed.

This was needed for me also.
