### ISSUE TITLE
Nx commands not working after migration - Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by koliveira15** [nrwl/nx#3633]
## Current Behavior
Getting an error when running any nx command specific to a project (nx build project-name, nx test project-name, etc)

## Expected Behavior
Nx commands function properly after migration

## Steps to Reproduce

1. Run nx migrate @nrwl/workspace@latest from @nrwl/workspace@**9.1.2**
2. npm install
3. nx migrate --run-migrations=migrations.json
4. Run any nx command with project (nx test demo-app)

### Failure Logs
```
nx test demo-app
C:\Users\ko\git\demo-workspace\node_modules\@nrwl\workspace\node_modules\yargs-parser\index.js:802
  var result = parse(args.slice(), opts)
                          ^

TypeError: Cannot read property 'slice' of undefined
    at Parser (C:\Users\ko\git\demo-workspace\node_modules\@nrwl\workspace\node_modules\yargs-parser\index.js:802:27)
    at Object.splitArgsIntoNxArgsAndOverrides (C:\Users\ko\git\demo-workspace\node_modules\@nrwl\workspace\src\command-line\utils.js:44:23)
    at Object.runOne (C:\Users\ko\git\demo-workspace\node_modules\@nrwl\workspace\src\command-line\run-one.js:11:43)
    at Object.initLocal (C:\Users\ko\git\demo-workspace\node_modules\@nrwl\cli\lib\init-local.js:27:65)
    at Object.<anonymous> (C:\Users\ko\git\demo-workspace\node_modules\@nrwl\cli\bin\nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
```

### Environment
```
{
  "name": "demo-workspace",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "nx",
    "nx": "nx",
    "start": "node app.js",
    "build": "ng build",
    "test": "ng test",
    "lint": "nx workspace-lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "prettier": "prettier --write \"*/**/*.{js,ts}\"",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "ng update @nrwl/workspace",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points && node ./decorate-angular-cli.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "10.0.14",
    "@angular/common": "10.0.14",
    "@angular/compiler": "10.0.14",
    "@angular/core": "10.0.14",
    "@angular/forms": "10.0.14",
    "@angular/platform-browser": "10.0.14",
    "@angular/platform-browser-dynamic": "10.0.14",
    "@angular/router": "10.0.14",
    "@nestjs/common": "7.4.2",
    "@nestjs/config": "^0.5.0",
    "@nestjs/core": "7.4.2",
    "@nestjs/graphql": "^7.5.5",
    "@nestjs/platform-express": "7.4.2",
    "@nestjs/swagger": "^4.5.1",
    "angular-highcharts": "^9.0.9",
    "apollo-angular": "^1.10.0",
    "apollo-angular-link-http": "^1.11.0",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "apollo-link-error": "^1.1.13",
    "apollo-server-express": "^2.15.1",
    "class-transformer": "^0.2.3",
    "class-validator": "^0.12.2",
    "core-js": "^2.5.4",
    "csurf": "^1.11.0",
    "cucumber-html-reporter": "^5.2.0",
    "dotenv": "^6.2.0",
    "express-healthcheck": "^0.1.0",
    "graphql": "^15.3.0",
    "graphql-tools": "^6.0.12",
    "highcharts": "^8.1.2",
    "memory-cache": "^0.2.0",
    "morgan": "^1.10.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "6.5.5",
    "serve-favicon": "^2.5.0",
    "shelljs": "^0.8.4",
    "supertest": "^4.0.2",
    "swagger-ui-express": "^4.1.4",
    "winston": "^2.4.4",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-architects/ddd": "^1.0.3",
    "@angular-devkit/build-angular": "0.1000.8",
    "@angular/cli": "10.0.8",
    "@angular/compiler-cli": "10.0.14",
    "@angular/language-service": "10.0.14",
    "@nestjs/schematics": "7.1.1",
    "@nestjs/testing": "7.4.2",
    "@nrwl/angular": "10.1.0",
    "@nrwl/cypress": "10.1.0",
    "@nrwl/jest": "10.1.0",
    "@nrwl/nest": "10.1.0",
    "@nrwl/node": "10.1.0",
    "@nrwl/schematics": "^8.12.11",
    "@nrwl/workspace": "10.1.0",
    "@types/jest": "26.0.8",
    "@types/node": "~8.9.4",
    "axios": "^0.19.2",
    "codelyzer": "~5.0.1",
    "commit-message-validator": "^0.1.11",
    "concurrently": "^5.1.0",
    "cypress": "^4.11.0",
    "cypress-cucumber-preprocessor": "^2.3.1",
    "cypress-shadow-dom": "^1.3.0",
    "eslint": "6.8.0",
    "husky": "^4.2.3",
    "istanbul-combine": "^0.3.0",
    "jest": "26.2.2",
    "jest-environment-jsdom-sixteen": "^1.0.3",
    "jest-html-reporter": "^3.1.3",
    "jest-junit": "^11.0.1",
    "jest-preset-angular": "8.2.1",
    "jest-sonar": "^0.2.8",
    "jest-sonar-reporter": "^2.0.0",
    "prettier": "2.0.4",
    "simple-git": "^1.132.0",
    "ts-jest": "26.1.4",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "3.9.7",
    "eslint-plugin-cypress": "^2.10.3"
  }
}
```

**Comment by koliveira15** [comment]
Issue was with including @nrwl/schematics which is pulling in an older version of @nrwl/cli. Removing this package from dev dependencies solved the issue.

**Comment by koliveira15** [comment]
Issue was with including @nrwl/schematics which is pulling in an older version of @nrwl/cli. Removing this package from dev dependencies solved the issue.
