### ISSUE TITLE
Schematics in VS Code ENOTEMPTY

### ISSUE THREAD

**Issue by s4m0r4m4** [nrwl/nx#3660]
## Current Behavior

When I am updating my schematics and trying to rebuild and use then, I try to run a schematic `nx workspace-schematic ...` or through the VS Code Nx Extension, it throws the following error (see logs below) and the schematic fails.

## Expected Behavior

No error

## Steps to Reproduce

1) Modify a custom schematic under tools/schematics
2) Try to run that schematic
3) Looks like there is some kind of file access issue when it tries to clear out the tools/schematics folder to build a new version of the schematic.

### Failure Logs

```
Error: ENOTEMPTY: directory not empty, rmdir 'C:\AIMDev\CI-Web\dist\tools\schematics\aim-resource-string'
    at Object.rmdirSync (fs.js:769:3)
    at rmkidsSync (C:\AIMDev\CI-Web\node_modules\@nrwl\workspace\node_modules\fs-extra\lib\remove\rimraf.js:304:27)
    at rmdirSync (C:\AIMDev\CI-Web\node_modules\@nrwl\workspace\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at rimrafSync (C:\AIMDev\CI-Web\node_modules\@nrwl\workspace\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at C:\AIMDev\CI-Web\node_modules\@nrwl\workspace\node_modules\fs-extra\lib\remove\rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\AIMDev\CI-Web\node_modules\@nrwl\workspace\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync (C:\AIMDev\CI-Web\node_modules\@nrwl\workspace\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at rimrafSync (C:\AIMDev\CI-Web\node_modules\@nrwl\workspace\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at C:\AIMDev\CI-Web\node_modules\@nrwl\workspace\node_modules\fs-extra\lib\remove\rimraf.js:291:39 {
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'C:\\AIMDev\\CI-Web\\dist\\tools\\schematics\\aim-resource-string'
}
```

### Environment

VS Code 1.48.2
Nx Console: 13.0.0

nx report: 
```
  nx : Not Found
  @nrwl/angular : 10.1.0
  @nrwl/cli : 10.1.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : 10.1.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.1.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.1.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.1.0
  @nrwl/web : Not Found
  @nrwl/workspace : 10.1.0
  typescript : 3.9.7
```

**Comment by s4m0r4m4** [comment]
Note - this seems to be related to the way schematics are run in the VS code extension (and the way it hangs onto file handles). If I just run the schematic in a console it works ok, but once VS code (with the extension enabled) is open, it wreaks havoc by locking files in the dist and essentially preventing nx from running any schematics.
