### ISSUE TITLE
Unable to run npm script

### ISSUE THREAD

**Issue by vrapalis** [nrwl/nx#3668]
### Current Behavior

cli command inside project 'npm run start' cause error

## Steps to Reproduce

Created project => npx create-nx-workspace@latest
Run cli command => npm run start 

### Failure Logs

> web@0.0.0 start /home/vitali/Workspace/vrapalis/monorepo/frontend/web
> ng serve

/home/vitali/Workspace/vrapalis/monorepo/frontend/web/node_modules/ignore/index.js:354
  throw new Ctor(message)
  ^

RangeError: path should be a `path.relative()`d string, but got "./"
    at throwError (/home/vitali/Workspace/vrapalis/monorepo/frontend/web/node_modules/ignore/index.js:354:9)
    at checkPath (/home/vitali/Workspace/vrapalis/monorepo/frontend/web/node_modules/ignore/index.js:375:12)
    at Ignore._test (/home/vitali/Workspace/vrapalis/monorepo/frontend/web/node_modules/ignore/index.js:483:5)
    at Ignore.ignores (/home/vitali/Workspace/vrapalis/monorepo/frontend/web/node_modules/ignore/index.js:518:17)
    at /home/vitali/Workspace/vrapalis/monorepo/frontend/web/node_modules/@nrwl/workspace/src/core/file-utils.js:186:42
    at Array.filter (<anonymous>)
    at Object.readWorkspaceFiles (/home/vitali/Workspace/vrapalis/monorepo/frontend/web/node_modules/@nrwl/workspace/src/core/file-utils.js:186:14)
    at Object.createProjectGraph (/home/vitali/Workspace/vrapalis/monorepo/frontend/web/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:13:145)
    at Object.runOne (/home/vitali/Workspace/vrapalis/monorepo/frontend/web/node_modules/@nrwl/workspace/src/command-line/run-one.js:12:42)
    at Object.initLocal (/home/vitali/Workspace/vrapalis/monorepo/frontend/web/node_modules/@nrwl/cli/lib/init-local.js:31:70)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vitali/.npm/_logs/2020-09-05T07_17_47_501Z-debug.log

### Environment
node -v => v12.16.1
npm -v => 6.14.4

**Comment by vrapalis** [comment]
Unbelievable when i name the project web, then error happens, realy strange :) => npx create-nx-workspace@latest web
