### ISSUE TITLE
Add - between words in npm scripts

### ISSUE THREAD

**Issue by vivekmore** [nrwl/nx#3670]
## Description
I'm trying to submit my first PR to this awesome project.
There were some challenges that I was/am facing
e.g.
- I can't run `npm run format` from command line on Windows since it complains of not being able to run `.sh` scripts
C:\dev\idea\nx>npm run format
```bash
C:\dev\idea\nx>npm run format

> @nrwl/nx-source@10.1.0 format C:\dev\idea\nx
> ./scripts/format.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nrwl/nx-source@10.1.0 format: `./scripts/format.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nrwl/nx-source@10.1.0 format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vivzt\AppData\Roaming\npm-cache\_logs\2020-09-06T14_40_28_761Z-debug.log

```
- Running the same `format` script from my IDE (IntelliJ) results in `*.md` files changing to have `LF` line endings and show up as changed.
  - There are few ways we could resolve this issue. One option that comes to mind is adding `.gitattributes` to make this platform agnostic. I'm open to suggestions and willing to submit a PR for this based on Nx team's feedback.

----

Now about the trivial change I was trying to submit as my first PR - https://github.com/nrwl/nx/pull/3672
I'd like to suggest that the scripts 

- `checkcommit`
- `checkformat`
- `checkimports`
- `checkversions`

be renamed to:

- `check-commit`
- `check-format`
- `check-imports`
- `check-versions`

**Comment by JakubKoralewski** [comment]
I'm having similar issue on WSL while running `yarn documentation` (current https://github.com/nrwl/nx/tree/12102c258c52df01a9e4721229fbf6fd0659c845):

```
$ yarn documentation
yarn run v1.19.0
$ ./scripts/documentation/documentation.sh && ./scripts/documentation/check-documentation.sh && npm run check-documentation-map
/usr/bin/env: ‘bash\r’: No such file or directory
```

dunno what to do tbh

**Comment by vivekmore** [comment]
I don't think it's just you.
I get a more detailed error when I do the same with npm instead or yarn, as you can see below.
The issue appears to be with the `rxjs-for-await` package's type definition or the lack thereof.

```

/mnt/c/dev/idea/nx/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
packages/tao/src/commands/run.ts:20:31 - error TS2307: Cannot find module 'rxjs-for-await' or its corresponding type declarations.

20 import { eachValueFrom } from 'rxjs-for-await';
                                 ~~~~~~~~~~~~~~~~

    at createTSError (/mnt/c/dev/idea/nx/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/mnt/c/dev/idea/nx/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/mnt/c/dev/idea/nx/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/mnt/c/dev/idea/nx/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/mnt/c/dev/idea/nx/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/mnt/c/dev/idea/nx/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nrwl/nx-source@11.2.6 documentation: `./scripts/documentation/documentation.sh && ./scripts/documentation/check-documentation.sh && npm run check-documentation-map`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nrwl/nx-source@11.2.6 documentation script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vivek/.npm/_logs/2021-02-07T13_01_49_530Z-debug.log
```

I'm also in the process of using nx for new projects, so let me know if you're blocked by anything else.
If you're submitting a PR and the documentation target is keeping you from pushing your changes to remote, try the `--no-verify` option like so:

```
git push your-branch --no-verify
```

**Comment by JakubKoralewski** [comment]
@vivekmore Thanks.
I used the `--no-verify` successfully too.

> I'm having similar issue on WSL while running yarn documentation

I actually fixed this by adding a `.gitattributes` file (with this content `* text eol=lf`), then commiting it, then removing git cache and then resetting (i know its confusing I followed a SO answer), this finally sucessfully changed all the bash script and other file's line endings to LF, which allowed me to run the bash scripts on WSL for first time. This didn't fix all issues tho:

> I'm also in the process of using nx for new projects, so let me know if you're blocked by anything else.

1. chalk doesn't have types (when running `yarn documentation`)
<details>

```
...snipped for brevity
Finished Generating Documentation for Generators

/mnt/d/projects/github/nx/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
packages/workspace/src/utilities/output.ts:33:41 - error TS2339: Property 'cyan' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

33   private readonly NX_PREFIX = `${chalk.cyan(
                                           ~~~~
packages/workspace/src/utilities/output.ts:35:14 - error TS2339: Property 'reset' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

35   )} ${chalk.reset.inverse.bold.cyan(' NX ')}`;
                ~~~~~
packages/workspace/src/utilities/output.ts:49:17 - error TS2339: Property 'gray' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

49     gray: chalk.gray,
                   ~~~~
packages/workspace/src/utilities/output.ts:51:16 - error TS2339: Property 'bold' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

51   bold = chalk.bold;
                  ~~~~
packages/workspace/src/utilities/output.ts:52:21 - error TS2339: Property 'underline' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

52   underline = chalk.underline;
                       ~~~~~~~~~
packages/workspace/src/utilities/output.ts:87:35 - error TS2339: Property 'gray' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

87     this.writeToStdOut(`\n${chalk.gray(this.VERTICAL_SEPARATOR)}\n\n`);
                                     ~~~~
packages/workspace/src/utilities/output.ts:91:33 - error TS2339: Property 'gray' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

91     this.writeToStdOut(`${chalk.gray(this.VERTICAL_SEPARATOR)}\n`);
                                   ~~~~
packages/workspace/src/utilities/output.ts:98:20 - error TS2339: Property 'reset' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

98       label: chalk.reset.inverse.bold.red(' ERROR '),
                      ~~~~~
packages/workspace/src/utilities/output.ts:99:20 - error TS2339: Property 'bold' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

99       title: chalk.bold.red(title),
                      ~~~~
packages/workspace/src/utilities/output.ts:110:15 - error TS2339: Property 'grey' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

110         chalk.grey('  ' + 'Learn more about this error: ') +
                  ~~~~
packages/workspace/src/utilities/output.ts:124:20 - error TS2339: Property 'reset' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

124       label: chalk.reset.inverse.bold.yellow(' WARNING '),
                       ~~~~~
packages/workspace/src/utilities/output.ts:125:20 - error TS2339: Property 'bold' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

125       title: chalk.bold.yellow(title),
                       ~~~~
packages/workspace/src/utilities/output.ts:136:15 - error TS2339: Property 'grey' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

136         chalk.grey('  ' + 'Learn more about this warning: ') +
                  ~~~~
packages/workspace/src/utilities/output.ts:150:20 - error TS2339: Property 'reset' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

150       label: chalk.reset.inverse.bold.keyword('orange')(' NOTE '),
                       ~~~~~
packages/workspace/src/utilities/output.ts:151:20 - error TS2339: Property 'bold' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

151       title: chalk.bold.keyword('orange')(title),
                       ~~~~
packages/workspace/src/utilities/output.ts:163:20 - error TS2339: Property 'reset' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

163       label: chalk.reset.inverse.bold.green(' SUCCESS '),
                       ~~~~~
packages/workspace/src/utilities/output.ts:164:20 - error TS2339: Property 'bold' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

164       title: chalk.bold.green(title),
                       ~~~~
packages/workspace/src/utilities/output.ts:185:30 - error TS2339: Property 'bold' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

185     this.writeToStdOut(chalk.bold(`> ${message} `));
                                 ~~~~
packages/workspace/src/utilities/output.ts:188:32 - error TS2339: Property 'bold' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

188       this.writeToStdOut(chalk.bold.grey(`[retrieved from cache]`));
                                   ~~~~
packages/workspace/src/utilities/output.ts:198:20 - error TS2339: Property 'white' does not exist on type 'typeof import("/mnt/d/projects/github/nx/node_modules/chalk/types/index")'.

198       title: chalk.white(title),
                       ~~~~~

    at createTSError (/mnt/d/projects/github/nx/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/mnt/d/projects/github/nx/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/mnt/d/projects/github/nx/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/mnt/d/projects/github/nx/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/mnt/d/projects/github/nx/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/mnt/d/projects/github/nx/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>
2. To be able to test my changes locally I tried following [this nice video](https://www.youtube.com/watch?v=Tx257WpNsxc), but when running the command `yarn nx-release 999.9.9 --local` I get:

<details>

```console
$ yarn nx-release 999.9.9 --local
yarn run v1.19.0
$ ./scripts/nx-release.js 999.9.9 --local
parsedArgs { _:
   [ '/usr/bin/node',
     '/mnt/d/projects/github/nx/scripts/nx-release.js',
     '999.9.9' ],
  local: true,
  l: true }
> git fetch --all
Fetching origin
Enter passphrase for key '/home/jcubed/.ssh/id_rsa':
Fetching orig
Enter passphrase for key '/home/jcubed/.ssh/id_rsa':
parsed version:  {"version":"999.9.9","isValid":true,"isPrerelease":false}
Executing build script:
> ./scripts/package.sh 999.9.9 ~11.0.1 4.0.5 2.2.1

>  NX  No projects with "build" were run


———————————————————————————————————————————————

>  NX   SUCCESS  Running target "build" succeeded


./scripts/package.sh: line 17: cd: build/packages: No such file or directory
sed: can't read react/src/utils/versions.js: No such file or directory
sed: can't read next/src/utils/versions.js: No such file or directory
sed: can't read gatsby/src/utils/versions.js: No such file or directory
sed: can't read web/src/utils/versions.js: No such file or directory
sed: can't read jest/src/utils/versions.js: No such file or directory
sed: can't read node/src/utils/versions.js: No such file or directory
sed: can't read linter/src/utils/versions.js: No such file or directory
sed: can't read express/src/utils/versions.js: No such file or directory
sed: can't read nest/src/utils/versions.js: No such file or directory
sed: can't read cypress/src/utils/versions.js: No such file or directory
sed: can't read storybook/src/utils/versions.js: No such file or directory
sed: can't read angular/src/utils/versions.js: No such file or directory
sed: can't read workspace/src/utils/versions.js: No such file or directory
sed: can't read react/package.json: No such file or directory
sed: can't read next/package.json: No such file or directory
sed: can't read gatsby/package.json: No such file or directory
sed: can't read web/package.json: No such file or directory
sed: can't read jest/package.json: No such file or directory
sed: can't read node/package.json: No such file or directory
sed: can't read express/package.json: No such file or directory
sed: can't read nest/package.json: No such file or directory
sed: can't read cypress/package.json: No such file or directory
sed: can't read storybook/package.json: No such file or directory
sed: can't read angular/package.json: No such file or directory
sed: can't read workspace/package.json: No such file or directory
sed: can't read cli/package.json: No such file or directory
sed: can't read linter/package.json: No such file or directory
sed: can't read tao/package.json: No such file or directory
sed: can't read devkit/package.json: No such file or directory
sed: can't read eslint-plugin-nx/package.json: No such file or directory
sed: can't read create-nx-workspace/package.json: No such file or directory
sed: can't read create-nx-plugin/package.json: No such file or directory
sed: can't read nx-plugin/package.json: No such file or directory
sed: can't read create-nx-workspace/bin/create-nx-workspace.js: No such file or directory
sed: can't read create-nx-workspace/bin/create-nx-workspace.js: No such file or directory
sed: can't read create-nx-workspace/bin/create-nx-workspace.js: No such file or directory
sed: can't read create-nx-workspace/bin/create-nx-workspace.js: No such file or directory
sed: can't read create-nx-plugin/bin/create-nx-plugin.js: No such file or directory
sed: can't read create-nx-plugin/bin/create-nx-plugin.js: No such file or directory
sed: can't read create-nx-plugin/bin/create-nx-plugin.js: No such file or directory
sed: can't read create-nx-plugin/bin/create-nx-plugin.js: No such file or directory
cp: cannot stat 'build/packages/*': No such file or directory
child_process.js:669
    throw err;
    ^

Error: Command failed: cp -R build/packages/* build/npm
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.<anonymous> (/mnt/d/projects/github/nx/scripts/nx-release.js:118:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

Overall my experience with trying to contribute to `nx` has been very frustrating. Works fine while using it as a user and I think it's a great project, but it's imo too opinionated and every little thing requires contributing and fixing issues (and I'm sure there is more because I'm not able to really get going with seting up the monorepo as I'm constantly fixing issues...), like for example:

3. The `generatePackageJson` option is only available for `node` apps. I'm using a Nextjs app, even though it technically is a node app I don't think the `node` options are transient to `next` options.

**Comment by vivekmore** [comment]
I realized my issue was due to the stale state of my `node_modules` 😞 
Running `npm i` solved the issue for me.

As for adding `.gitattributes`, thats a step in the right direction, not sure if that's enough (as you may have already discovered).
I'm given to understand that nx team has tried to have the workspace `Windows`-friendly/compatible but never succeeded in achieving a configuration that was agnostic to MacOS/Linux/Windows operating systems. - Hence I've resorted to developing nx in WSL2. [background](https://github.com/nrwl/nx/pull/3672#issuecomment-690287381)

Although, I share some of your sentiments, but it's open-source and I can appreciate that the nrwl team needs to prioritize their business over the tool. Moreover, I see this as an opportunity to fix some easy bugs and contribute to an otherwise awesome tool.
I'm slightly biased because I'm huge fan of scaffolding tools 😄

**Comment by vivekmore** [comment]
I tried to reproduce your issue locally, but got stuck somewhere else after:
```bash
npm run local-registry enable
```
My WSL2 doesn't seem to expose the port `4873`
