### ISSUE TITLE
npx create-nx-workspace failing

### ISSUE THREAD

**Issue by bcabanes** [nrwl/nx#3807]
## Current Behavior
The following command ends up with an error:

## Expected Behavior
`create-nx-workspace` should setup the project properly.

## Steps to Reproduce
Issue reproducible 4 times out of 4 attempts with the following command:
```
npx create-nx-workspace
```

### Failure Logs

```
npx create-nx-workspace nxCloudTravisCi
npx: installed 179 in 7.028s
? What to create in the new workspace react             [a workspace with a single React application]
? Application name                    Sample
? Default stylesheet format           CSS
? Use Nx Cloud? (It's free and doesn't require registration.) Yes [Faster builds, run details, Github integrat
ion. Learn more at https://nx.app]
Creating a sandbox with Nx...
[-----------------------------------------------------------------------------------------------------] 0/324
new nxCloudTravisCi  --preset="react" --appName="Sample" --style="css" --nxCloud --interactive=false --collection=@nrwl/workspace
yarn run v1.22.4
$ /private/var/folders/sx/yl_s7v6x7dg89wy1twh4dt3r0000gn/T/tmp-357412Bad8yK6H3QO/node_modules/.bin/tao new nxCloudTravisCi --preset=react --appName=Sample --style=css --nxCloud --interactive=false --collection=/private/var/folders/sx/yl_s7v6x7dg89wy1twh4dt3r0000gn/T/tmp-357412Bad8yK6H3QO/node_modules/@nrwl/workspace/collection.json --cli=tao --nxWorkspaceRoot=/Users/benjamincabanes/Documents/projects
✔ Packages installed successfully.
$ nx g @nrwl/workspace:preset --name=Sample --style=css --npmScope=nx-cloud-travis-ci --preset=react --cli=nx --interactive=false
✔ Packages installed successfully.
CREATE jest.config.js (252 bytes)
CREATE babel.config.json (62 bytes)
CREATE .eslintrc (1037 bytes)
CREATE apps/sample/.eslintrc (7150 bytes)
CREATE apps/sample/tsconfig.app.json (365 bytes)
CREATE apps/sample/.babelrc (56 bytes)
CREATE apps/sample/.browserslistrc (562 bytes)
CREATE apps/sample/tsconfig.json (336 bytes)
CREATE apps/sample/src/favicon.ico (15086 bytes)
CREATE apps/sample/src/index.html (321 bytes)
CREATE apps/sample/src/main.tsx (202 bytes)
CREATE apps/sample/src/polyfills.ts (218 bytes)
CREATE apps/sample/src/styles.css (80 bytes)
CREATE apps/sample/src/app/logo.svg (2930 bytes)
CREATE apps/sample/src/app/star.svg (347 bytes)
CREATE apps/sample/src/app/app.css (2108 bytes)
CREATE apps/sample/src/app/app.spec.tsx (425 bytes)
CREATE apps/sample/src/app/app.tsx (3510 bytes)
CREATE apps/sample/src/assets/.gitkeep (0 bytes)
CREATE apps/sample/src/environments/environment.prod.ts (52 bytes)
CREATE apps/sample/src/environments/environment.ts (218 bytes)
CREATE apps/sample-e2e/.eslintrc (292 bytes)
CREATE apps/sample-e2e/cypress.json (412 bytes)
CREATE apps/sample-e2e/tsconfig.e2e.json (222 bytes)
CREATE apps/sample-e2e/tsconfig.json (147 bytes)
CREATE apps/sample-e2e/src/fixtures/example.json (80 bytes)
CREATE apps/sample-e2e/src/integration/app.spec.ts (404 bytes)
CREATE apps/sample-e2e/src/plugins/index.js (832 bytes)
CREATE apps/sample-e2e/src/support/app.po.ts (47 bytes)
CREATE apps/sample-e2e/src/support/commands.ts (1068 bytes)
CREATE apps/sample-e2e/src/support/index.ts (599 bytes)
CREATE apps/sample/babel-jest.config.json (196 bytes)
CREATE apps/sample/jest.config.js (385 bytes)
CREATE apps/sample/tsconfig.spec.json (408 bytes)
UPDATE workspace.json (3642 bytes)
UPDATE package.json (2096 bytes)
UPDATE nx.json (655 bytes)
✔ Packages installed successfully.
    Successfully initialized git.
CREATE nx-cloud-travis-ci/nx.json (527 bytes)
CREATE nx-cloud-travis-ci/tsconfig.base.json (509 bytes)
CREATE nx-cloud-travis-ci/README.md (3266 bytes)
CREATE nx-cloud-travis-ci/.editorconfig (245 bytes)
CREATE nx-cloud-travis-ci/.gitignore (503 bytes)
CREATE nx-cloud-travis-ci/.prettierignore (74 bytes)
CREATE nx-cloud-travis-ci/.prettierrc (26 bytes)
CREATE nx-cloud-travis-ci/workspace.json (96 bytes)
CREATE nx-cloud-travis-ci/package.json (1172 bytes)
CREATE nx-cloud-travis-ci/tools/tsconfig.tools.json (223 bytes)
CREATE nx-cloud-travis-ci/tools/schematics/.gitkeep (0 bytes)
CREATE nx-cloud-travis-ci/apps/.gitkeep (0 bytes)
CREATE nx-cloud-travis-ci/libs/.gitkeep (0 bytes)
✨  Done in 48.86s.

———————————————————————————————————————————————

(node:35741) UnhandledPromiseRejectionWarning: Error: spawnSync /bin/sh ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execSync (child_process.js:652:15)
    at createApp (/Users/benjamincabanes/.npm/_npx/35741/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:383:25)
    at /Users/benjamincabanes/.npm/_npx/35741/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:91:25
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:35741) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35741) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Environment
```
node -v
v12.14.1

yarn -v
1.22.4

macOS Catalina
```

**Comment by overthemike** [comment]
Is there a reason this was closed? Doesn't seem like it was fixed. I just got this:

```
(node:99728) UnhandledPromiseRejectionWarning: Error: spawnSync /bin/sh ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Object.execSync (child_process.js:652:15)
    at createApp (/Users/Michael/.npm/_npx/99728/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:400:25)
    at /Users/Michael/.npm/_npx/99728/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:102:29
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:99728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:99728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

This is just a warning, but it is a bit off-putting. The fix seems simple enough (just add a .catch() to the createApp call on line 126 in `/packages/create-nx-workspace/bin/create-nx-workspace.ts`. This is just a guess, however, as I wasn't able to really test it. I tried creating a sandbox as the contributing video said to do, however I was getting errors there as well...but that's a different issue. I'll link to that issue as soon as I figure out where the best place to file it is...

**Comment by dmitrygorkun** [comment]
The same error ;(
Why this was closed?
