### ISSUE TITLE
__dirname , __filename , process.cwd() , path.dirname() none of them work

### ISSUE THREAD

**Issue by mhasanjb** [nrwl/nx#3898]
## Current Behavior

you can not use __dirname , __filename , process.cwd() , in `require()` , `libs` or `apps`  

## Expected Behavior

to be able to use:    
`const file = require(__dirname + "/assets/file.json")`

### Failure Logs

When you are using that in your `libs` or `apps` , in your terminal this error will show:    
```
C:\monorepo\dist\apps\todo\webpack:\libs\acl-directive\src\lib sync:2
        var e = new Error("Cannot find module '" + req + "'");
^
Error: Cannot find module 'C:\monorepo\dist\apps\todo\assets\roles.json'
    at webpackEmptyContext (C:\monorepo\dist\apps\todo\webpack:\libs\acl-directive\src\lib sync:2:1)
    at Module../libs/acl-directive/src/lib/acl-directive.ts (C:\monorepo\dist\apps\todo\webpack:\libs\acl-directive\src\lib\acl-directive.ts:29:15)
    at __webpack_require__ (C:\monorepo\dist\apps\todo\webpack:\webpack\bootstrap:19:1)
    at Module../libs/acl-directive/src/index.ts (C:\monorepo\dist\apps\todo\webpack:\libs\acl-directive\src\index.ts:1:1)
    at __webpack_require__ (C:\monorepo\dist\apps\todo\webpack:\webpack\bootstrap:19:1)
    at Module../apps/todo/src/main.ts (C:\monorepo\dist\apps\todo\main.js:335:78)
    at __webpack_require__ (C:\monorepo\dist\apps\todo\webpack:\webpack\bootstrap:19:1)
    at Object.0 (C:\monorepo\dist\apps\todo\main.js:482:18)
    at __webpack_require__ (C:\monorepo\dist\apps\todo\webpack:\webpack\bootstrap:19:1)
    at C:\monorepo\dist\apps\todo\webpack:\webpack\bootstrap:83:1
    at Object.<anonymous> (C:\monorepo\dist\apps\todo\main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
```
But the file is exist in `dist` and `apps`

### Environment

```
    "@nrwl/angular": "^10.3.0",
    "@nrwl/cli": "10.3.0",
    "@nrwl/eslint-plugin-nx": "10.3.0",
    "@nrwl/express": "^10.3.0",
    "@nrwl/jest": "10.3.0",
    "@nrwl/node": "10.3.0",
    "@nrwl/workspace": "10.3.0",
    "@types/jest": "26.0.8",
    "@types/node": "^8.10.64",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.3.0",
    "eslint": "7.10.0",
    "eslint-config-prettier": "6.0.0",
    "jest": "26.2.2",
    "prettier": "2.0.4",
    "ts-jest": "26.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "~4.0.3"
```

**Comment by FrozenPandaz** [comment]
Hi, is this for a node app correct?

Is it possible to push a repo showcasing the issue to help us debug the issue please?

**Comment by mhasanjb** [comment]
@FrozenPandaz 
Hi yes this is node, 
here is repo: https://github.com/mhasanjb/nx
Thanks

**Comment by ryancraigmartin** [comment]
Also currently running into this issue.

**Comment by bekos** [comment]
@mhasanjb I suppose we can enable `__dirname` and `__filename` options in webpack, but does `const file = require("./assets/file.json")` works for you? If you can provide a repro to understand your use case would be very helpful 😃

**Comment by bekos** [comment]
Closing as I haven't heard back, but feel free to reopen in case your issue is still relevant and have more info to share.
