### ISSUE TITLE
@nrwl/storybook migration code to 10.2.1 - Cannot read property 'storybook' of undefined

### ISSUE THREAD

**Issue by erkobridee** [nrwl/nx#3911]
## Current Behavior
When I executed the migration I got an error message:
`Cannot read property 'storybook' of undefined`

## Expected Behavior
Correctly execution without any error

## Steps to Reproduce
- from the nx workspace v10.0.12
- a library with storybook and others without it
- `nx migrate @nrwl/workspace@10.2.1`
- `npm i`
- `nx migrate --run-migrations=migrations.json`

### Failure Logs
```
Running migration @nrwl/storybook:update-10.2.1
Cannot read property 'storybook' of undefined
/Users/erkobridee/nx-project/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: npx tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.handler (/Users/erkobridee/nx-project/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:74:21)
    at Object.runCommand (/Users/erkobridee/nx-project/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/erkobridee/nx-project/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/erkobridee/nx-project/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/erkobridee/nx-project/node_modules/@nrwl/cli/lib/init-local.js:24:13)
    at Object.<anonymous> (/Users/erkobridee/nx-project/node_modules/@nrwl/cli/bin/nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 24115,
  stdout: null,
  stderr: null
}
```

### Environment
- macOS Catalina (10.15.7)
- node v12.16.1
- migrating from the nx workspace v10.0.12
```
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : 10.2.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.1
  @nrwl/linter : 10.2.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.2.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.1
  @nrwl/web : 10.2.1
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7
```

### My local solution to fix the issue

change the code from inside of `/node_modules/@nrwl/storybook/migrations/update-10-2-1/update-10-2-1.js`

at line 28

from:
```
const hasStorybookConfig = architect.storybook && tree.exists(paths.tsConfigStorybook);
```
to:
```
const hasStorybookConfig = architect && architect.storybook && tree.exists(paths.tsConfigStorybook);
```

it seems that to projects/libs that don't have the storybook on it, it gets the `architect` as an undefined value, and by adding that check that fixes the migration execution issue

---

on the current code of @nrwl/storybook, we need to apply the same fix to the lines 65 and 66
https://github.com/nrwl/nx/blob/master/packages/storybook/src/migrations/update-10-2-1/update-10-2-1.ts#L65-L66

and I suspect that the migration code to 10.3.0 it will face the same issue and could have the same solution
https://github.com/nrwl/nx/blob/master/packages/storybook/src/migrations/update-10-3-0/update-10-3-0.ts#L64-L65

**Comment by Bodom78** [comment]
Has this issue regressed?, I got a similar issue with StoryBook migration 11-5-3

Manually applied https://github.com/nrwl/nx/commit/57ea3ac98210d91d65fa6a07c341759327637505 to the 11-5-3 file and it completed.

`
Running migration update-11-5-3
Cannot read property 'storybook' of undefined
D:\Work\Development\chic-websites\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\Fady\AppData\Local\Temp\tmp-29324-H4zb4cFyix3A\node_modules\.bin\tao migrate --run-migrations
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (D:\Work\Development\chic-websites\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:87:25)
    at Object.runCommand (D:\Work\Development\chic-websites\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (D:\Work\Development\chic-websites\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (D:\Work\Development\chic-websites\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (D:\Work\Development\chic-websites\node_modules\@nrwl\cli\lib\init-local.js:24:13)
    at Object.<anonymous> (D:\Work\Development\chic-websites\node_modules\@nrwl\cli\bin\nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 17800,
  stdout: null,
  stderr: null
}
`
