### ISSUE TITLE
Fresh Install Nx workspace fail

### ISSUE THREAD

**Issue by duard** [nrwl/nx#3945]
## Current Behavior
nx fail when creating a new workspace

## Steps to Reproduce
`npm cache clean --force;npx create-nx-workspace@latest
`
### Failure Logs
```⠇ Installing packages...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: simples@0.0.0
npm ERR! Found: typescript@4.0.3
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"~4.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"^3.4.5" from @nestjs/schematics@7.1.2
npm ERR! node_modules/@nestjs/schematics
npm ERR!   dev @nestjs/schematics@"^7.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/duard/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/duard/.npm/_logs/2020-10-20T14_11_40_147Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.
npm ERR! code 1
npm ERR! path /home/duard/z-dev/simples
npm ERR! command failed
npm ERR! command sh -c ng g '@nrwl/workspace:preset' '--name=front' '--style=scss' '--npmScope=simples' '--preset=angular-nest' '--cli=ng' '--interactive=false'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/duard/.npm/_logs/2020-10-20T14_11_40_185Z-debug.log
Workspace creation failed, see above.
npm ERR! code 1
npm ERR! path /tmp/tmp-8019TPpCfwyAcT2Q
npm ERR! command failed
npm ERR! command sh -c tao new simples '--preset=angular-nest' '--appName=front' '--style=scss' '--linter=tslint' '--interactive=false' '--collection=/tmp/tmp-8019TPpCfwyAcT2Q/node_modules/@nrwl/workspace/collection.json' '--cli=ng' '--nxWorkspaceRoot=/home/duard/z-dev'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/duard/.npm/_logs/2020-10-20T14_11_40_220Z-debug.log
(node:8019) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new simples  --preset="angular-nest" --appName="front" --style="scss" --linter="tslint" --interactive=false --collection=/tmp/tmp-8019TPpCfwyAcT2Q/node_modules/@nrwl/workspace/collection.json --cli=ng --nxWorkspaceRoot=/home/duard/z-dev
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at createApp (/home/duard/.npm/_npx/505743838affa773/node_modules/create-nx-workspace/bin/create-nx-workspace.js:424:21)
    at /home/duard/.npm/_npx/505743838affa773/node_modules/create-nx-workspace/bin/create-nx-workspace.js:92:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
### Environment
```     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 10.1.7
Node: 12.18.3
OS: linux x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.7 (cli-only)
@angular-devkit/core         10.1.7 (cli-only)
@angular-devkit/schematics   10.1.7 (cli-only)
@schematics/angular          10.1.7 (cli-only)
@schematics/update           0.1001.7 (cli-only)```

**Comment by duard** [comment]
fixed :
` npm uninstall  @nrwl/schematics; npm install -g @nrwl/schematics npm cache clean --force;npx create-nx-workspace@latest`
