### ISSUE TITLE
Unable to override default jest globals in Nx 9 workspace

### ISSUE THREAD

**Issue by dtodt** [nrwl/nx#4027]
I'm trying to override `jest config` to support the new version `9.0.0-next.1`, wich seems to be compatible with `ivy`.
I'm following [these](https://github.com/thymikee/jest-preset-angular/blob/master/CHANGELOG.md) steps, from `9.0.0-next.0` and up.
> They changed some paths on this new version.

I've made two repositories, one on [v9](https://github.com/dtodt/jest-preset-angular-v9) and one on [v10](https://github.com/dtodt/jest-preset-angular-v10).
The code on v10 runs the tests, the v9 one doesn't.

> It would be very good, if this could work on v9, because my code is tied to Angular 9, and migrate to Angular 10 now would be too much of time and work.
>
> Too much `resolvers` to resolve 😥

Well, without further do, Thanks.

## Current Behavior
When I overrride the `globals` key in `jest.config.js`, it'll not be propagated to the project jest config itself.
The keys `snapshotSerializers` and `transform ` are propagated just fine.

Giving me the error on `Failure Logs` when I run my tests.

When I run `yarn test --show-config` it shows me that the global config was not overridden:
```json
{
  "configs": [
    {
      ... // omitted for simplicity
      "globals": {
        "ts-jest": {
          "tsconfig": "<rootDir>/tsconfig.spec.json",
          "stringifyContentPathRegex": "\\.(html|svg)$",
          "astTransformers": [
            "jest-preset-angular/build/InlineFilesTransformer",
            "jest-preset-angular/build/StripStylesTransformer"
          ],
          "tsConfig": "/__my_machine__/prj-971/apps/prj/tsconfig.spec.json"
        }
      },
      ...
      "snapshotSerializers": [
        "/__my_machine__/prj-971/node_modules/jest-preset-angular/build/serializers/html-comment.js",
        "/__my_machine__/prj-971/node_modules/jest-preset-angular/build/serializers/ng-snapshot.js",
        "/__my_machine__/prj-971/node_modules/jest-preset-angular/build/serializers/no-ng-attributes.js"
      ],
      ...
      "transform": [
        [
          "^.+\\.(ts|js|html)$",
          "/__my_machine__/prj-971/node_modules/jest-preset-angular/build/index.js",
          {}
        ]
      ],
      ...
    }
  ],
  ...
  "version": "26.6.3"
}
```

## Expected Behavior
It should propagate the overriden keys properly, as of it does on v10.

When I run `yarn test --show-config` it shows me that all keys were overridden:
```json
{
  "configs": [
    {
      ... // omitted for simplicity
      "globals": {
        "ts-jest": {
          "tsconfig": "<rootDir>/tsconfig.spec.json",
          "stringifyContentPathRegex": "\\.(html|svg)$",
          "astTransformers": {
            "before": [
              "node_modules/jest-preset-angular/build/transformers/inline-files",
              "node_modules/jest-preset-angular/build/transformers/strip-styles"
            ]
          }
        }
      },
      ...
      "snapshotSerializers": [
        "/__my_machine__/prj-latest/node_modules/jest-preset-angular/build/serializers/html-comment.js",
        "/__my_machine__/prj-latest/node_modules/jest-preset-angular/build/serializers/ng-snapshot.js",
        "/__my_machine__/prj-latest/node_modules/jest-preset-angular/build/serializers/no-ng-attributes.js"
      ],
      ...
      "transform": [
        [
          "^.+\\.(ts|js|html)$",
          "/__my_machine__/prj-latest/node_modules/jest-preset-angular/build/index.js",
          {}
        ]
      ],
      ...
    }
  ],
  ...
  "version": "26.6.3"
}
```

## Steps to Reproduce

In [v9](https://github.com/dtodt/jest-preset-angular-v9), you can reproduce the `error` bellow and in [v10](https://github.com/dtodt/jest-preset-angular-v10), the test `success`.

Both are new projects, with stock tests, just to validate the `jest` issue.

- git clone
- `yarn install`
- `yarn test`
  - or
- `yarn test --show-config`

### Failure Logs

Error given when tests are runned:
```shell
> ng run prj:test 
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
ts-jest[config] (WARN) The configuration for astTransformers as string[] is deprecated and will be removed in ts-jest 27. Please define your custom AST transformers in a form of an object. More information you can check online documentation https://kulshekhar.github.io/ts-jest/user/config/astTransformers
 FAIL  apps/prj/src/app/app.component.spec.ts
  ● Test suite failed to run

    File not found: jest-preset-angular/build/InlineFilesTransformer (resolved as: /__my_machine__/prj-971/jest-preset-angular/build/InlineFilesTransformer)

      at NgJestConfig.ConfigSet.resolvePath (../../node_modules/ts-jest/dist/config/config-set.js:507:19)
      at ../../node_modules/ts-jest/dist/config/config-set.js:236:53
          at Array.map (<anonymous>)
      at NgJestConfig.ConfigSet._setupTsJestCfg (../../node_modules/ts-jest/dist/config/config-set.js:235:86)
      at NgJestConfig.ConfigSet (../../node_modules/ts-jest/dist/config/config-set.js:152:14)
      at AngularJestTransformer.TsJestTransformer.getCacheKey (../../node_modules/ts-jest/dist/ts-jest-transformer.js:72:14)
      at ScriptTransformer._getCacheKey (../../node_modules/@jest/transform/build/ScriptTransformer.js:256:23)
      at ScriptTransformer._getFileCachePath (../../node_modules/@jest/transform/build/ScriptTransformer.js:290:27)
```

### Environment

v9:
```shell
  @nrwl/angular : 9.7.1
  @nrwl/cli : 9.7.1
  @nrwl/cypress : 9.7.1
  @nrwl/jest : 9.7.1
  @nrwl/tao : 9.7.1
  @nrwl/workspace : 9.7.1
  typescript : 3.8.3
```

v10:
```shell
  @nrwl/angular : 10.3.2
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.3.2
  @nrwl/jest : 10.3.2
  @nrwl/linter : 10.3.2
  @nrwl/tao : 10.3.2
  @nrwl/workspace : 10.3.2
  typescript : 4.0.5
```

**Comment by FrozenPandaz** [comment]
We made a lot of improvements to our `jest` support in v10 :tada:.

Unfortunately, these improvements were not backported because they had introduced some breaking changes.

You can try to migrate only Nx and Angular CLI to v10 while keeping your `@angular` runtime at v9.

**Comment by dtodt** [comment]
@FrozenPandaz It actually worked. I've made some refactorings on my v9 workspace, and the tests worked with the new `jest-angular-preset`.

> I've tryed to run update workspace, but it updated Angular along with the workspace

My versions became like this:
```
  @angular/* : 9.1.12
  @nrwl/angular : 10.3.2
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.3.2
  @nrwl/eslint-plugin-nx : Not Found -- do I need it ?
  @nrwl/jest : 10.3.2
  @nrwl/linter : 10.3.2
  @nrwl/tao : 10.3.2
  @nrwl/workspace : 10.3.2
  typescript : 3.8.3
```

Branch Comparison: [HERE](https://github.com/dtodt/jest-preset-angular-v9/compare/nx-10?expand=1)
