### ISSUE TITLE
npx create-nx-workspace@latest not working, only work if remove yarn but get other error

### ISSUE THREAD

**Issue by hiepxanh** [nrwl/nx#4051]
## Current Behavior
cannot create workspace on fresh start

## Expected Behavior
shoud create new workspace

## Steps to Reproduce
aready checked `https://github.com/nrwl/nx/issues/3954` and `https://github.com/nrwl/nx/issues/3945`

`npx create-nx-workspace awread` failed

### Failure Logs
```
G:\batcave>npx create-nx-workspace@latest
npx: installed 182 in 21.187s
? Workspace name (e.g., org name)     awreadbook
? What to create in the new workspace angular-nest      [a workspace with a full stack application (Angular + Nest)]
? Application name                    awreadbook
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
? Default linter                      ESLint [ Modern linting tool ]
? Use Nx Cloud? (It's free and doesn't require registration.) Yes [Faster builds, run details, Github integration. Learn
 more at https://nx.app]
Creating a sandbox with Nx...
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 3s 611ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ wrap-ansi@npm:6.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ y18n@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:18.1.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:20.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:15.4.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1s 111ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 479ms
➤ YN0000: Done in 5s 244ms
new awreadbook  --preset="angular-nest" --appName="awreadbook" --style="scss" --linter="eslint" --nxCloud --interactive=false --collection=@nrwl/workspace
(node:5828) UnhandledPromiseRejectionWarning: Error: Cannot find module '@nrwl/workspace/collection.json'
Require stack:
- C:\Users\hiepx\AppData\Roaming\npm-cache\_npx\5828\node_modules\create-nx-workspace\bin\create-nx-workspace.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at createApp (C:\Users\hiepx\AppData\Roaming\npm-cache\_npx\5828\node_modules\create-nx-workspace\bin\create-nx-workspace.js:423:40)
    at C:\Users\hiepx\AppData\Roaming\npm-cache\_npx\5828\node_modules\create-nx-workspace\bin\create-nx-workspace.js:92:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### If I remove yarn , it got other error

```

G:\batcave>npx create-nx-workspace@latest awreadbook
npx: installed 182 in 13.638s
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    awreadbook
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
? Default linter                      ESLint [ Modern linting tool ]
? Use Nx Cloud? (It's free and doesn't require registration.) Yes [Faster builds, run details, Github integration. Learn
 more at https://nx.app]
Creating a sandbox with Nx...
added 194 packages from 153 contributors and audited 195 packages in 11.741s
found 0 vulnerabilities

new awreadbook  --preset="angular" --appName="awreadbook" --style="scss" --linter="eslint" --nxCloud --interactive=false --collection=@nrwl/workspace
√ Packages installed successfully.
? Would you like to share anonymous usage data about this project with the Angular Team at
? Would you like to share anonymous usage data about this project with the Angular Team at
Google under Google’s Privacy Policy at https://policies.google.com/privacy? For more
details and how to change this setting, see http://angular.io/analytics. No

CREATE jest.config.js (65 bytes)
CREATE jest.preset.js (82 bytes)
CREATE apps/awreadbook/tsconfig.editor.json (119 bytes)
CREATE apps/awreadbook/tsconfig.json (249 bytes)
CREATE apps/awreadbook/src/favicon.ico (15086 bytes)
CREATE apps/awreadbook/.browserslistrc (853 bytes)
CREATE apps/awreadbook/tsconfig.app.json (163 bytes)
CREATE apps/awreadbook/src/index.html (338 bytes)
CREATE apps/awreadbook/src/main.ts (377 bytes)
CREATE apps/awreadbook/src/polyfills.ts (2833 bytes)
CREATE apps/awreadbook/src/styles.scss (80 bytes)
CREATE apps/awreadbook/src/assets/.gitkeep (0 bytes)
CREATE apps/awreadbook/src/environments/environment.prod.ts (52 bytes)
CREATE apps/awreadbook/src/environments/environment.ts (663 bytes)
CREATE apps/awreadbook/src/app/app.module.ts (298 bytes)
CREATE apps/awreadbook/src/app/app.component.html (2984 bytes)
CREATE apps/awreadbook/src/app/app.component.spec.ts (933 bytes)
CREATE apps/awreadbook/src/app/app.component.ts (223 bytes)
CREATE apps/awreadbook/src/app/app.component.scss (2088 bytes)
CREATE .eslintrc.json (1101 bytes)
CREATE apps/awreadbook/.eslintrc.json (80 bytes)
CREATE apps/awreadbook/jest.config.js (749 bytes)
CREATE apps/awreadbook/tsconfig.spec.json (233 bytes)
CREATE apps/awreadbook/src/test-setup.ts (30 bytes)
CREATE apps/awreadbook-e2e/.eslintrc.json (282 bytes)
CREATE apps/awreadbook-e2e/cypress.json (420 bytes)
CREATE apps/awreadbook-e2e/tsconfig.e2e.json (222 bytes)
CREATE apps/awreadbook-e2e/tsconfig.json (147 bytes)
CREATE apps/awreadbook-e2e/src/fixtures/example.json (80 bytes)
CREATE apps/awreadbook-e2e/src/integration/app.spec.ts (412 bytes)
CREATE apps/awreadbook-e2e/src/plugins/index.js (832 bytes)
CREATE apps/awreadbook-e2e/src/support/app.po.ts (47 bytes)
CREATE apps/awreadbook-e2e/src/support/commands.ts (1133 bytes)
CREATE apps/awreadbook-e2e/src/support/index.ts (599 bytes)
UPDATE angular.json (4188 bytes)
UPDATE package.json (2309 bytes)
UPDATE .vscode/extensions.json (200 bytes)
UPDATE nx.json (684 bytes)
- Installing packages...'yarn' is not recognized as an internal or external command,
operable program or batch file.
× Package install failed, see above.
The Schematic workflow failed. See above.
Workspace creation failed, see above.
(node:21172) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new awreadbook  --preset="angular" --appName="awreadbook" --style="scss" --linter="eslint" --nxCloud --interactive=false --collection=C:\Users\hiepx\AppData\Local\Temp\tmp-21172MnloayTQ79nQ\node_modules\@nrwl\workspace\collection.json --cli=ng --nxWorkspaceRoot="G:\batcave"
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at createApp (C:\Users\hiepx\AppData\Roaming\npm-cache\_npx\21172\node_modules\create-nx-workspace\bin\create-nx-workspace.js:424:21)
    at C:\Users\hiepx\AppData\Roaming\npm-cache\_npx\21172\node_modules\create-nx-workspace\bin\create-nx-workspace.js:92:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:21172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Environment
```
node: 12.16.1
npm: 6.13.1
windows: 10
```

**Comment by mandarini** [comment]
Hi there @hiepxanh ! Thanks for filing an issue!

Can you please try to install the latest versions of `node` (v14.15.0) and `npm` (6.14.8), and please retry the `create-nx-workspace` command?

Maybe there's an issue there!

**Comment by hiepxanh** [comment]
sadly, I try downgrade and it just have the same error

```
G:\test>npx create-nx-workspace@latest test-nx
npx: installed 182 in 13.131s
? What to create in the new workspace angular-nest      [a workspace with a full stack application (Angular + Nest)]
? Application name                    test-nx
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
? Default linter                      ESLint [ Modern linting tool ]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 3s 61ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ wrap-ansi@npm:6.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ y18n@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:18.1.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:20.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:15.4.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1s 160ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 494ms
➤ YN0000: Done in 4s 762ms
new test-nx  --preset="angular-nest" --appName="test-nx" --style="scss" --linter="eslint" --interactive=false --collection=@nrwl/workspace
(node:24508) UnhandledPromiseRejectionWarning: Error: Cannot find module '@nrwl/workspace/collection.json'
Require stack:
- C:\Users\hiepx\AppData\Roaming\npm-cache\_npx\24508\node_modules\create-nx-workspace\bin\create-nx-workspace.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at createApp (C:\Users\hiepx\AppData\Roaming\npm-cache\_npx\24508\node_modules\create-nx-workspace\bin\create-nx-workspace.js:423:40)
    at C:\Users\hiepx\AppData\Roaming\npm-cache\_npx\24508\node_modules\create-nx-workspace\bin\create-nx-workspace.js:92:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
windows: 10
node --version
v14.15.0
npm --version
6.14.8
yarn --version
2.3.3
```

LOL must be yarn bug because I'm using yarn 2, trying switch back to yarn 1 resolved the problem.

**Comment by alonspr** [comment]
same here. using yarn instead of npm did the trick.
