### ISSUE TITLE
Can't create nx-workspace using create-nx-workspace@latest on Mac

### ISSUE THREAD

**Issue by bostondevin** [nrwl/nx#4063]
Cannot create workspace

Workspace is created with terminal errors

## Steps to Reproduce

On Catalina, latest node.js LTS using create-nx-workspace@latest is giving an error.

? What to create in the new workspace react             [a workspace with a single React application]
? Application name                    test-app
? Default stylesheet format           CSS
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
error Couldn't find package "@nrwl/workspace" on the "npm" registry.
(node:9798) UnhandledPromiseRejectionWarning: Error: Command failed: yarn install --silent
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createSandbox (/usr/local/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:386:21)
    at /usr/local/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:91:44
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9798) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9798) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bostondevin** [comment]
I fixed it by uninstalling yarn with Homebrew: brew uninstall yarn

Then it worked - thanks!
