### ISSUE TITLE
Getting"Error: spawn pgrep EAGAIN" when saving the code changes in running nestjs app

### ISSUE THREAD

**Issue by evgenyfedorenko** [nrwl/nx#4066]
## Current Behavior
Serving the nestjs app is working until I attempt to change some code, save it and refresh the browser.
Getting this error:

`events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn pgrep EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EAGAIN',
  code: 'EAGAIN',
  syscall: 'spawn pgrep',
  path: 'pgrep',
  spawnargs: [ '-P', 66975 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

## Expected Behavior
It should not crash.

## Steps to Reproduce
Create new nestjs app.
Start it with command:
nx run app_name:serve

### Environment
macOS Catalina
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.2
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : 10.3.2
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.2
  @nrwl/linter : 10.3.2
  @nrwl/nest : 10.3.2
  @nrwl/next : Not Found
  @nrwl/node : 10.3.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.2
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.2
  typescript : 4.0.5

**Comment by evgenyfedorenko** [comment]
I had pgrep installed on my machine via brew. After removing it serve started working. Closing the issue
