### ISSUE TITLE
schematics does not support yarn / npm link

### ISSUE THREAD

**Issue by noelmace** [nrwl/nx#408]
## error
 
```
~/git/test-nx$ ./node_modules/.bin/nx lint
fs.js:660
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/home/osboxes/git/nx/build/packages/schematics/.angular-cli.json'
    at Object.fs.openSync (fs.js:660:18)
    at Object.fs.readFileSync (fs.js:565:33)
    at Object.readJsonFile (/home/osboxes/git/nx/build/packages/schematics/src/utils/fileutils.js:56:26)
    at Object.readCliConfig (/home/osboxes/git/nx/build/packages/schematics/src/command-line/shared.js:92:30)
    at Object.lint (/home/osboxes/git/nx/build/packages/schematics/src/command-line/lint.js:9:51)
    at Object.<anonymous> (/home/osboxes/git/nx/build/packages/schematics/src/command-line/nx.js:37:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
```

## reproduce

1. (in nx) yarn build
2. `cd build/packages/schematics`
3. `yarn link`
4. (in another folder) `create-nx-workspace test-nx && cd test-nx`
5. `yarn link @nrwl/schematics`

## diagnostic

app-root-path does not support this kind of use case.

I'll make a PR with a workaround for that : add a --project-path option and use app-root-path.setPath.

But since app-root-path isn't maintained and is really light, I think we could (should ?) delete this dependency in the future.

**Comment by mrxz** [comment]
I introduced app-root-path in #170 to allow tslint to be executed from other working directories than the "app root", which was needed for tslint plugins in both Atom and Sublime. In those cases, specifying the app root path as an argument isn't an option. So if the dependency would be removed, there still has to be some logic in place that can correctly determine the app root path for those cases.

**Comment by noelmace** [comment]
@mrxz Thanks a lot for this informations. The cli option was only a cheap workaround, and I really just wanted to learn more about your development process. https://github.com/nrwl/nx/pull/410#issuecomment-382001011 answered to my questions on this. I still think that npm link would be better, but it's just a developpers' issue, not a user's one. I may take a look on this, following https://github.com/nrwl/nx/pull/410#issuecomment-382000654, the next time I'll  work on Nx.
