### ISSUE TITLE
 Error when migrating angular application 11

### ISSUE THREAD

**Issue by CABRALBRUNO000** [nrwl/nx#4114]
## Current Behavior

The application of the error when trying to run in the development environment, this after having migrated to NX

## Expected Behavior

desire for the application to rise

## Steps to Reproduce
1º ng add @nrwl/workspace
2º nx serve

### Failure Logs
`Warning: Fell back to using 'fs' to identify browserslist as deleted. Please open an issue at https://github.com/nrwl/nx so we can investigate.
(node:11844) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 1338
    at JSON.parse (<anonymous>)
    at buildNpmPackageNodes (C:\Users\Bruno\Desktop\aidup\aidme-volunteers\node_modules\@nrwl\workspace\src\core\project-graph\build-nodes\npm-packages.js:6:30)
    at C:\Users\Bruno\Desktop\aidup\aidme-volunteers\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:59:34      
    at Array.forEach (<anonymous>)
    at buildProjectGraph (C:\Users\Bruno\Desktop\aidup\aidme-volunteers\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:59:19)
    at Object.createProjectGraph (C:\Users\Bruno\Desktop\aidup\aidme-volunteers\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:40:30)
    at Object.<anonymous> (C:\Users\Bruno\Desktop\aidup\aidme-volunteers\node_modules\@nrwl\workspace\src\command-line\run-one.js:16:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Bruno\Desktop\aidup\aidme-volunteers\node_modules\@nrwl\workspace\node_modules\tslib\tslib.js:111:62)     
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

### Environment
Angular 11
RXJS
NX

**Comment by mandarini** [comment]
Hi there @CABRALBRUNO000 ! Thanks for filing an issue!

Unfortunately, I could not reproduce your issue. Let me tell you the steps I followed to see if we're on the same page:
1. Make sure I have the latest version of the Angular CLI which will generate an Angular application of version 11.
`ng --version` gives me this: `Angular CLI: 11.0.2`
<img width="443" alt="Screenshot 2020-11-24 at 4 48 13 PM" src="https://user-images.githubusercontent.com/6603745/100109774-d932c800-2e74-11eb-8ba6-22d094a7d7cb.png">

2. Generate a new Angular app using the Angular CLI: `ng new my-new-app`
3. Then follow your steps:
4. `ng add @nrwl/workspace`
5. `nx serve`

And my application runs!

Can you provide a repository which I can use to reproduce your issue? Or else, can you tell me the exact steps you followed, and also let me know of the versions of Nx and Angular CLI which you are using?

Thank you! :)

**Comment by AhmedHlaimi** [comment]
hey guuuuus, just fixed with the stash , try git stash , its work for me
