### ISSUE TITLE
nx migrate command on npm@7

### ISSUE THREAD

**Issue by Phillip9587** [nrwl/nx#4116]
## Current Behavior
```nx migate @nrwl/workspace``` results in an error.

## Steps to Reproduce
* Install node 15.2.1 and npm 7.0.8
* Run ```nx migate @nrwl/workspace```

### Failure Logs

```ERROR: The migrate command failed. Try the following to migrate your workspace:
> npm install --save-dev @nrwl/workspace@latest
> nx migrate @nrwl\workspace@latest --from="@nrwl/workspace@10.3.3"
This will use the newest version of the migrate functionality, which might have your issue resolved.
----------------------------------------------------------------------------------------------------
Command failed: npm install @nrwl\workspace@latest --prefix=C:\Users\barta\AppData\Local\Temp\tmp-70209YVOp1h41q1P
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@nrwl\workspace": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\barta\AppData\Local\npm-cache\_logs\2020-11-19T09_31_52_472Z-debug.log
```

### Environment
  nx : Not Found
  @nrwl/angular : 10.3.3
  @nrwl/cli : 10.3.3
  @nrwl/cypress : 10.3.3
  @nrwl/eslint-plugin-nx : 10.3.3
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.3
  @nrwl/linter : 10.3.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.3
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.3
  typescript : 4.0.5

**Comment by bekos** [comment]
@Phillip9587 Unfortunately I couldn't reproduce your issue. I would suggest to try removing node_modules and reinstall and/or run it using another terminal, like PowerShell, and let us know if this fixed the issue.

**Comment by hiepxanh** [comment]
@Phillip9587 please update the npm version to at least 7.11.0 and try again

**Comment by Phillip9587** [comment]
Updated to npm 7.0.13 an still getting the following error

```
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl\workspace@latest

 ERROR  The migrate command failed. Try the following to migrate your workspace:

> npx @nrwl/tao@latest migrate @nrwl\workspace@latest
This will use the newest version of the migrate functionality, which might have your issue resolved.
----------------------------------------------------------------------------------------------------
Command failed: npm install @nrwl\workspace@latest
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@nrwl\workspace": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\barta\AppData\Local\npm-cache\_logs\2020-11-21T10_37_09_916Z-debug.log

npm ERR! code 1
npm ERR! path C:\...\
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c tao migrate @nrwl\workspace

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\barta\AppData\Local\npm-cache\_logs\2020-11-21T10_37_10_009Z-debug.log
                throw err;
                ^

Error: Command failed: npx tao migrate @nrwl/workspace
    at checkExecSyncError (node:child_process:636:11)
    at Object.execSync (node:child_process:672:15)
    at Object.handler (C:\...\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:74:21)
    at Object.runCommand (C:\...\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\...\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\...\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\...\node_modules\@nrwl\cli\lib\init-local.js:24:13)
    at Object.<anonymous> (C:\...\node_modules\@nrwl\cli\bin\nx.js:40:18)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1212,
  stdout: null,
  stderr: null
}
```

Also running the suggested **npx @nrwl/tao@latest migrate @nrwl\workspace@latest** results in the same error
```
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl\workspace@latest

 ERROR  The migrate command failed. Try the following to migrate your workspace:

> npx @nrwl/tao@latest migrate @nrwl\workspace@latest
This will use the newest version of the migrate functionality, which might have your issue resolved.
----------------------------------------------------------------------------------------------------
Command failed: npm install @nrwl\workspace@latest
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@nrwl\workspace": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\barta\AppData\Local\npm-cache\_logs\2020-11-21T10_39_43_219Z-debug.log

npm ERR! code 1
npm ERR! path C:\...\
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c tao migrate @nrwl\workspace@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Local\npm-cache\_logs\2020-11-21T10_39_43_317Z-debug.log
```

**Log File Content: **
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   '@nrwl/tao@latest',
0 verbose cli   'migrate',
0 verbose cli   '@nrwl/workspace@latest'
0 verbose cli ]
1 info using npm@7.0.13
2 info using node@v15.2.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Users\...\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:C:\...\.npmrc Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:C:\Users\...\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session 3402a93d05e13392
20 timing npm:load Completed in 21ms
21 http fetch GET 200 https://registry.npmjs.org/@nrwl%2ftao 12ms (from cache)
22 timing arborist:ctor Completed in 1ms
23 timing command:exec Completed in 2855ms
24 verbose stack Error: command failed
24 verbose stack     at ChildProcess.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
24 verbose stack     at ChildProcess.emit (node:events:329:20)
24 verbose stack     at maybeClose (node:internal/child_process:1055:16)
24 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
25 verbose pkgid sn-wb-frd@0.1.5
26 verbose cwd C:\...\
27 verbose Windows_NT 10.0.18363
28 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "exec" "--" "@nrwl/tao@latest" "migrate" "@nrwl/workspace@latest"
29 verbose node v15.2.1
30 verbose npm  v7.0.13
31 error code 1
32 error path C:\...\
33 error command failed
34 error command C:\Windows\system32\cmd.exe /d /s /c tao migrate @nrwl\workspace@latest
35 verbose exit 1
```

**Comment by bekos** [comment]
@Phillip9587 Did you try using Powershell? Also try to run it like `npm run nx migate @nrwl/workspace`, instead of using the global package.

**Comment by Phillip9587** [comment]
@bekos Yes i tried using powershell. It seems that the npm run nx command invokes the angular cli.

**Comment by bekos** [comment]
This is very odd! Can you paste the results of `npm info @nrwl/workspace dist-tags`? Also try to run `npm install -g nx@latest` and run migrations again.

**Comment by Phillip9587** [comment]
npm info returns:
 **{ next: '11.0.0-beta.6', latest: '10.4.4' }**

Global nx package was already at the latest version. I uninstalled it and installed it again and still got the same error message.

**Comment by Phillip9587** [comment]
nx command invokes the angular cli but only in my nx workspace folder
```
PS C:\...> nx
Available Commands:
  add Adds support for an external library to your project.
  analytics Configures the gathering of Angular CLI usage metrics. See https://angular.io/cli/usage-analytics-gathering.
  build (b) Compiles an Angular app into an output directory named dist/ at the given output path. Must be executed from within a workspace directory.
  deploy Invokes the deploy builder for a specified project or for the default project in the workspace.
  config Retrieves or sets Angular configuration values in the angular.json file for the workspace.
  doc (d) Opens the official Angular documentation (angular.io) in a browser, and searches for a given keyword.
  e2e (e) Builds and serves an Angular app, then runs end-to-end tests using Protractor.
  generate (g) Generates and/or modifies files based on a schematic.
  help Lists available commands and their short descriptions.
  lint (l) Runs linting tools on Angular app code in a given project folder.
  new (n) Creates a new workspace and an initial Angular app.
  run Runs an Architect target with an optional custom builder configuration defined in your project.
  serve (s) Builds and serves your app, rebuilding on file changes.
  test (t) Runs unit tests in a project.
  update Updates your application and its dependencies. See https://update.angular.io/
  version (v) Outputs Angular CLI version.
  xi18n (i18n-extract) Extracts i18n messages from source code.
```

**Comment by bekos** [comment]
@Phillip9587 it's really weird, but I was able to reproduce it when invoking the command with `npx` 🤔 Anyways, I have sent a PR that will probably fix it 😃

**Comment by Phillip9587** [comment]
Thanks for your efforts @bekos

**Comment by bekos** [comment]
@Phillip9587 can you plz paste me the result if you run the migration using: `npm run nx migate @nrwl/workspace`?

**Comment by Phillip9587** [comment]
❯ npm run nx migate @nrwl/workspace

> sn-wb-frd@0.1.5 nx
> nx "migate" "@nrwl/workspace"

The specified command ("migate") is invalid. For a list of available options,
run "ng help".

Did you mean "update"?
npm ERR! code 1
npm ERR! path C:\...\
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c nx migate @nrwl/workspace

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Local\npm-cache\_logs\2020-11-26T10_03_02_581Z-debug.log

**Comment by Phillip9587** [comment]
@bekos i tried with another workspace an got the same error with this stacktrace

```
C:\...\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^
Error: Command failed: npx tao migrate @nrwl/workspace
    at checkExecSyncError (node:child_process:636:11)
    at Object.execSync (node:child_process:672:15)
    at Object.handler (C:\...\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:74:21)
    at Object.runCommand (C:\...\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\...\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\...\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\...\node_modules\@nrwl\cli\lib\init-local.js:24:13)
    at Object.<anonymous> (C:\...\node_modules\@nrwl\cli\bin\nx.js:12:18)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10340,
  stdout: null,
  stderr: null
}
```

**Comment by crates** [comment]
For anyone else in the future who is looking at this, the issue was that he was using a backslash instead of a forward slash.

It's:
`nx migrate @nrwl/workspace@latest`

... NOT:
`nx migrate @nrwl\workspace@latest`

lol
