### ISSUE TITLE
Error after update (probably not NX issue)

### ISSUE THREAD

**Issue by zoltanradics** [nrwl/nx#4140]
I am not an NX pro so please bare with me! We have an NX workspace and i made an attempt to update our dependencies. After i followed @ngcli migration instructions from 9.1 to 10.2. All looks working locally but when we are doing the build on Gitlab, i got the following error:

```
internal/modules/cjs/loader.js:621
  throw e;
  ^
Error: No valid exports main found for '/client-workspace/node_modules/@nrwl/cli/node_modules/yargs-parser'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/client-workspace/node_modules/@nrwl/cli/lib/parse-run-one-options.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1128:30) {
  code: 'MODULE_NOT_FOUND'
}

```

I could never reproduce the error out of Gitlab. Does anyone has the slightlest clue what do I do wrong?
Thank you for any idea!

**Comment by eddiewang** [comment]
experiencing this as well in gitlab-ci. any help would be greatly appreciated!

**Comment by fxck** [comment]
same here

**Comment by fxck** [comment]
seems to be working with node v14.15.4
