### ISSUE TITLE
Creating a new workspace using next preset fails

### ISSUE THREAD

**Issue by westmark** [nrwl/nx#4196]
## Current Behavior
When trying to create a new workspace using the `next` preset, npm errors.

## Expected Behavior
The workspace should be created successfully.

## Steps to Reproduce
Cannot provide any repo for obvious reasons.

### Failure Logs
```
➜  projects npx create-nx-workspace komob
? What to create in the new workspace next.js           [a workspace with a single Next.js application]
? Application name                    komob-public
? Default stylesheet format           styled-components [ https://styled-components.com            ]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new komob  --preset="next" --appName="komob-public" --style="styled-components" --linter="eslint" --interactive=false --collection=@nrwl/workspace
✔ Packages installed successfully.
⠏ Installing packages...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: next@10.0.0
npm ERR! node_modules/next
npm ERR!   next@"10.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^9.3.3" from @nrwl/next@10.4.4
npm ERR! node_modules/@nrwl/next
npm ERR!   dev @nrwl/next@"10.4.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/westmark/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/westmark/.npm/_logs/2020-12-03T20_40_36_540Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.
npm ERR! code 1
npm ERR! path /Users/westmark/projects/komob
npm ERR! command failed
npm ERR! command sh -c nx g '@nrwl/workspace:preset' '--name=komob-public' '--style=styled-components' '--npmScope=komob' '--preset=next' '--cli=nx' '--interactive=false'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/westmark/.npm/_logs/2020-12-03T20_40_36_565Z-debug.log
Workspace creation failed, see above.
npm ERR! code 1
npm ERR! path /private/var/folders/99/z65p5jd15g56kfzfwjxmlsvc0000gn/T/tmp-4661Pazvv0dhZ2nN
npm ERR! command failed
npm ERR! command sh -c tao new komob '--preset=next' '--appName=komob-public' '--style=styled-components' '--linter=eslint' '--interactive=false' '--collection=@nrwl/workspace/collection.json' '--cli=tao' '--nxWorkspaceRoot=/Users/westmark/projects'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/westmark/.npm/_logs/2020-12-03T20_40_36_596Z-debug.log
node:child_process:636
    err = new Error(msg);
          ^

Error: Command failed: npx tao new komob  --preset="next" --appName="komob-public" --style="styled-components" --linter="eslint" --interactive=false --collection=@nrwl/workspace/collection.json --cli=tao --nxWorkspaceRoot="/Users/westmark/projects"
    at checkExecSyncError (node:child_process:636:11)
    at Object.execSync (node:child_process:672:15)
    at createApp (/Users/westmark/.npm/_npx/d2207cf76adb22dc/node_modules/create-nx-workspace/bin/create-nx-workspace.js:431:21)
    at /Users/westmark/.npm/_npx/d2207cf76adb22dc/node_modules/create-nx-workspace/bin/create-nx-workspace.js:100:29
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 4663,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /Users/westmark/projects
npm ERR! command failed
npm ERR! command sh -c create-nx-workspace komob

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/westmark/.npm/_logs/2020-12-03T20_40_36_627Z-debug.log
```
### Environment
Node 15.3.0
NPM 7.0.14

Cannot really run `nx report` since the workspace is not created properly. Here is some output from a workspace I created with the `empty` preset and then added the next plugin to

```
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.4.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.4
  @nrwl/linter : 10.4.4
  @nrwl/nest : Not Found
  @nrwl/next : 10.4.4
  @nrwl/node : 10.4.4
  @nrwl/react : 10.4.4
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : 10.4.4
  @nrwl/workspace : 10.4.4
  typescript : 4.0.5
```

**Comment by BigAB** [comment]
This is caused by npm v7's new ["auto-installing peerDependencies" feature](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major)

As a workaround, you can just `cd` into the workspace that should've been created, even though it errored, delete the `node_modules` and `package-lock.json` and do a 
```sh
npm install --legacy-peer-deps
```
Which should work.

**Comment by westmark** [comment]
Ah, I completely missed that feature. 😳
