### ISSUE TITLE
Can't Run generated custom schematics

### ISSUE THREAD

**Issue by lexcaraig** [nrwl/nx#4221]
---
name: "🐞 Can't Run generated custom schematics"
about: Followed the guidelines and got some unexpected behaviour
labels: "type: bug"

---

## Current Behavior

Getting an Error when trying to run the custom schematics

## Expected Behavior

Should be able to run the custom schematics properly

## Steps to Reproduce

```
ng g workspace-schematic my-test-schematic
nx workspace-schematic my-test-schematic mylib 
```

### Failure Logs
```
> app workspace-schematic /PATH_TO_WORKSPACE/tools
> nx workspace-schematic "my-test-schematic" "mylib"

nx workspace-schematic [name]

Runs a workspace schematic from the tools/schematics directory

Positionals:
  name  The name of your schematic`                          [string] [required]

Options:
  --help             Show help                                         [boolean]
  --version          Show version number                               [boolean]
  --list-schematics  List the available workspace-schematics           [boolean]

Error: ENOENT: no such file or directory, open '/PATH_TO_WORKSPACE/tools/tsconfig.tools.json'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at getToolsOutDir (/PATH_TO_WORKSPACE/node_modules/@nrwl/workspace/src/command-line/workspace-schematic.js:51:65)
    at compileTools (/PATH_TO_WORKSPACE/node_modules/@nrwl/workspace/src/command-line/workspace-schematic.js:42:25)
    at Object.<anonymous> (/PATH_TO_WORKSPACE/node_modules/@nrwl/workspace/src/command-line/workspace-schematic.js:23:24)
    at Generator.next (<anonymous>)
    at /PATH_TO_WORKSPACE/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/PATH_TO_WORKSPACE/node_modules/tslib/tslib.js:110:16)
    at Object.workspaceSchematic (/PATH_TO_WORKSPACE/node_modules/@nrwl/workspace/src/command-line/workspace-schematic.js:22:20) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/PATH_TO_WORKSPACE/tools/tsconfig.tools.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mercury-ui@0.0.0 workspace-schematic: `nx workspace-schematic "rpg-widget" "test"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mercury-ui@0.0.0 workspace-schematic script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lexcaraig/.npm/_logs/2020-12-08T09_14_36_721Z-debug.log
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.7.0
  @nrwl/cli : 9.7.0
  @nrwl/cypress : 9.7.0
  @nrwl/eslint-plugin-nx : 9.7.0
  @nrwl/express : Not Found
  @nrwl/jest : 9.7.0
  @nrwl/linter : 9.7.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 9.7.0
  @nrwl/web : Not Found
  @nrwl/workspace : 9.7.0
  typescript : 3.8.3
```

**Comment by FrozenPandaz** [comment]
It looks like you have both `@nrwl/workspace` and `@nrwl/schematics`. `@nrwl/schematics` is deprecated and can be removed. Can you please remove it and try again? If you still have issues, please provide a repo that we can pull down to help us investigate the issue.

**Comment by lexcaraig** [comment]
I tried reproducing the same scenario with the newly created workspace, and it seems that the `tools.condig.json` under tools folder and `collection.json` under schematics folder is missing. So I tried copying those and it works fine. This can be close. Thank you!
