### ISSUE TITLE
ng update @nrwl/workspace failed with exception (update from 10.1 to 11 workspace)

### ISSUE THREAD

**Issue by manju-reddys** [nrwl/nx#4269]
## Current Behavior
The update filed with error.

## Expected Behavior
The update should have been successful.

## Steps to Reproduce
Just ran command ` ng update @nrwl/workspace` (command was generated by nx when the workspace was created for the first time)

### Failure Logs
```
yarn run v1.22.10
$ ng update @nrwl/workspace
Using package manager: 'yarn'
Collecting installed dependencies...
Found 99 dependencies.
Fetching dependency metadata from registry...
                  Package "@nrwl/cypress" has a missing peer dependency of "cypress" @ ">= 3 < 6".
    Updating package.json with dependency @nrwl/angular @ "11.0.1" (was "10.4.4")...
    Updating package.json with dependency @nrwl/cypress @ "11.0.1" (was "10.4.4")...
    Updating package.json with dependency @nrwl/eslint-plugin-nx @ "11.0.1" (was "10.4.4")...
    Updating package.json with dependency @nrwl/jest @ "11.0.1" (was "10.4.4")...
    Updating package.json with dependency @nrwl/nest @ "11.0.1" (was "10.4.4")...
    Updating package.json with dependency @nrwl/node @ "11.0.1" (was "10.4.4")...
    Updating package.json with dependency @nrwl/workspace @ "11.0.1" (was "10.4.4")...
  UPDATE package.json (4671 bytes)
✔ Packages installed successfully.
An unhandled exception occurred: Cannot find module '/Users/projects/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
See "/private/var/folders/ks/7qhvtbnj6q9c3zvlwljb5n340000gn/T/ng-voxzDd/angular-errors.log" for further details.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
`/private/var/folders/ks/7qhvtbnj6q9c3zvlwljb5n340000gn/T/ng-voxzDd/angular-errors.log` is below

```
[error] Error: Cannot find module '/Users/projects/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:333:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:714:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1067:27)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at Module.require (/Users/projects/node_modules/@nrwl/tao/src/compat/compat.js:7:40)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/projects/node_modules/@nrwl/angular/src/migrations/update-8-5-0/upgrade-cli-8-3.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at Module.require (/Users/projects/node_modules/@nrwl/tao/src/compat/compat.js:7:40)
    at require (internal/modules/cjs/helpers.js:75:18)
    at new ExportStringRef (/Users/projects/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js:19:25)

```

### Environment
OS: mac 10.1

`package.json`

```
{
   "name": "project",
   "version": "3.5.0",
   "license": "private",
   "private": true,
   "scripts": {
      "ng": "nx",
      "nx": "nx",
      "start": "ng serve --ssl=true",
      "build": "ng build",
      "test": "ng test",
      "lint": "nx workspace-lint && ng lint",
      "e2e": "ng e2e",
      "affected:apps": "nx affected:apps",
      "affected:libs": "nx affected:libs",
      "affected:build": "nx affected:build",
      "affected:e2e": "nx affected:e2e",
      "affected:test": "nx affected:test",
      "affected:lint": "nx affected:lint",
      "affected:dep-graph": "nx affected:dep-graph",
      "affected": "nx affected",
      "format": "nx format:write",
      "format:write": "nx format:write",
      "format:check": "nx format:check",
      "update": "ng update @nrwl/workspace",
      "workspace-schematic": "nx workspace-schematic",
      "dep-graph": "nx dep-graph",
      "help": "nx help",
      "ci.client.post.build": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
   },
   "dependencies": {
      "@angular/animations": "11.0.4",
      "@angular/common": "11.0.4",
      "@angular/compiler": "11.0.4",
      "@angular/core": "11.0.4",
      "@angular/forms": "11.0.4",
      "@angular/platform-browser": "11.0.4",
      "@angular/platform-browser-dynamic": "11.0.4",
      "@angular/router": "11.0.4",
      "@angular/service-worker": "11.0.4",
      "@rx-angular/template": "^1.0.0-beta.0",
      "ag-grid-angular": "24.1.0",
      "ag-grid-community": "24.1.0",
      "bignumber.js": "9.0.1",
      "bootstrap": "5.0.0-beta1",
      "d3": "6.3.1",
      "rxjs": "6.6.3",
      "zone.js": "0.11.3"
   },
   "devDependencies": {
      "@angular-devkit/architect": "0.1100.4",
      "@angular-devkit/build-angular": "0.1100.4",
      "@angular-eslint/builder": "0.8.0-beta.5",
      "@angular-eslint/eslint-plugin": "0.8.0-beta.5",
      "@angular-eslint/eslint-plugin-template": "0.8.0-beta.5",
      "@angular-eslint/schematics": "0.8.0-beta.5",
      "@angular-eslint/template-parser": "0.8.0-beta.5",
      "@angular/cli": "11.0.4",
      "@angular/compiler-cli": "11.0.4",
      "@angular/language-service": "11.0.4",
      "@nestjs/common": "7.5.5",
      "@nestjs/core": "7.5.5",
      "@nestjs/graphql": "7.9.1",
      "@nestjs/platform-fastify": "7.5.5",
      "@nestjs/schematics": "7.2.5",
      "@nestjs/serve-static": "2.1.4",
      "@nestjs/testing": "7.5.5",
      "@nestjs/typeorm": "7.1.5",
      "@nrwl/angular": "10.4.4",
      "@nrwl/cypress": "10.4.4",
      "@nrwl/eslint-plugin-nx": "10.4.4",
      "@nrwl/jest": "10.4.4",
      "@nrwl/nest": "10.4.4",
      "@nrwl/node": "10.4.4",
      "@nrwl/workspace": "10.4.4",
      "@types/busboy": "0.2.3",
      "@types/cookie": "0.4.0",
      "@types/cookie-signature": "1.0.3",
      "@types/d3": "6.2.0",
      "@types/end-of-stream": "1.4.0",
      "@types/helmet": "4.0.0",
      "@types/jest": "26.0.18",
      "@types/js-yaml": "3.12.5",
      "@types/node": "14.14.11",
      "@types/pino-http": "5.0.6",
      "@types/puppeteer": "5.4.2",
      "@types/sodium-native": "2.3.5",
      "@typescript-eslint/eslint-plugin": "4.9.1",
      "@typescript-eslint/parser": "4.9.1",
      "@vercel/ncc": "0.25.1",
      "apollo-server-fastify": "3.0.0-alpha.3",
      "axios": "0.21.0",
      "busboy": "0.3.1",
      "class-transformer": "0.3.1",
      "class-validator": "0.12.2",
      "codelyzer": "6.0.1",
      "cookie": "0.4.1",
      "cookie-signature": "1.1.0",
      "csv": "5.3.2",
      "eslint": "7.14.0",
      "eslint-config-prettier": "6.15.0",
      "eslint-import-resolver-typescript": "2.3.0",
      "eslint-plugin-import": "2.22.1",
      "eslint-plugin-jest": "24.1.3",
      "eslint-plugin-prettier": "3.1.4",
      "express-ctx": "0.1.1",
      "fastify-compress": "3.4.0",
      "fastify-cookie": "4.1.0",
      "fastify-static": "3.3.0",
      "graphql": "15.4.0",
      "graphql-tools": "7.0.1",
      "helmet": "4.2.0",
      "install": "0.13.0",
      "jest": "26.6.3",
      "jest-preset-angular": "8.3.2",
      "js-yaml": "3.14.1",
      "openid-client": "4.2.2",
      "pg": "8.5.1",
      "mysql": "2.18.1",
      "pino-http": "5.3.0",
      "postgres": "1.0.2",
      "prettier": "2.2.1",
      "puppeteer": "5.5.0",
      "reflect-metadata": "0.1.13",
      "rimraf": "3.0.2",
      "sodium-native": "3.2.0",
      "ts-jest": "26.4.4",
      "ts-node": "9.1.1",
      "tslint": "6.1.3",
      "typeorm": "0.2.29",
      "typescript": "4.0.5"
   }
}
```

**Comment by manju-reddys** [comment]
It appear `npx nx migrate @nrwl/workspace@latest` bumps the `workspace` dep to 11.01 and nothing much
![image](https://user-images.githubusercontent.com/1906881/101969101-6a28d380-3bd7-11eb-9f9b-43c50f4286d0.png)

**Comment by mehrad-rafigh** [comment]
@manju-reddys Give [nx migrate](https://nx.dev/latest/angular/workspace/update#how-to-migrate) a chance

**Comment by manju-reddys** [comment]
@mehrad-rafigh `nx-migrate` also failed with `Command "tao" not found`

```
npx nx migrate
npx: installed 103 in 5.91s
yarn run v1.22.10
error Command "tao" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn tao migrate
```

**Comment by vsavkin** [comment]
@manju-reddys Thank you for submitting the issue. 

Unfortunately, I'm not able to reproduce it.

- Do you see tao in node_modules/.bin/tao?
- What happens if you run `npx @nrwl/tao@latest migrate latest`?

**Comment by manju-reddys** [comment]
@vsavkin `npx @nrwl/tao@latest migrate latest` successfully run but `npx @nrwl/tao@latest migrate --run-migrations=migrations.json` failed (see the for logs).

```
 npx @nrwl/tao@latest migrate latest
npx: installed 76 in 12.932s
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @types/node@12.12.38
Fetching tslint@~6.1.0
Fetching ts-node@~9.1.1
Fetching @nrwl/angular@11.0.11
Fetching @nrwl/cli@11.0.11
Fetching @nrwl/cypress@11.0.11
Fetching @nrwl/eslint-plugin-nx@11.0.11
Fetching @nrwl/jest@11.0.11
Fetching @nrwl/linter@11.0.11
Fetching @nrwl/nest@11.0.11
Fetching @nrwl/node@11.0.11
Fetching @nrwl/tao@11.0.11
Fetching @angular/cli@~11.0.0
Fetching @angular-devkit/build-angular@~0.1100.1
Fetching codelyzer@^6.0.0
Fetching @angular/core@^11.0.3
Fetching @angular/common@^11.0.3
Fetching @angular/forms@^11.0.3
Fetching @angular/compiler@^11.0.3
Fetching @angular/compiler-cli@^11.0.3
Fetching @angular/platform-browser@^11.0.3
Fetching @angular/platform-browser-dynamic@^11.0.3
Fetching @angular/router@^11.0.3
Fetching @angular/language-service@^11.0.3
Fetching @angular/animations@^11.0.3
Fetching @angular/service-worker@^11.0.3
Fetching @nrwl/workspace@11.0.11
Fetching tslint@6.1.3
Fetching ts-node@9.1.1
Fetching @angular/cli@11.0.5
Fetching @angular-devkit/build-angular@0.1100.5
Fetching codelyzer@6.0.1
Fetching @angular/core@11.0.5
Fetching @angular/common@11.0.5
Fetching @angular/forms@11.0.5
Fetching @angular/compiler@11.0.5
Fetching @angular/compiler-cli@11.0.5
Fetching @angular/platform-browser@11.0.5
Fetching @angular/platform-browser-dynamic@11.0.5
Fetching @angular/router@11.0.5
Fetching @angular/language-service@11.0.5
Fetching @angular/animations@11.0.5
Fetching @angular/service-worker@11.0.5

>  NX  The migrate command has run successfully.

- package.json has been updated
- migrations.json has been generated

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'yarn'
- Run 'nx migrate --run-migrations=migrations.json'

```

Note `npx nx migrate --run-migrations=migrations.json` didn't work 

```
npx nx migrate --run-migrations=migrations.json
npx: installed 103 in 5.323s
yarn run v1.22.10
error Command "tao" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn tao migrate --run-migrations=migrations.json

```
So I used your recommended command `npx @nrwl/tao@latest migrate --run-migrations=migrations.json` and it failed with following error:

```
npx @nrwl/tao@latest migrate --run-migrations=migrations.json
npx: installed 76 in 3.886s
Running migration update-script-to-invoke-nx-migrate
Cannot find module '@nrwl/workspace/package.json'
Require stack:
- /Users/manjunathreddy/.npm/_npx/60516/lib/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/manjunathreddy/.npm/_npx/60516/lib/node_modules/@nrwl/tao/src/commands/migrate.js
- /Users/manjunathreddy/.npm/_npx/60516/lib/node_modules/@nrwl/tao/index.js

```

**Comment by manju-reddys** [comment]
@vsavkin Do I need to install NX in global scope?

**Comment by manju-reddys** [comment]
@vsavkin Finally I see it worked, Installed `@nrwl/tao` and `@nrwl/workspace` manually  and then `npx @nrwl/tao@latest migrate latest` after it successfully completes, run `npx nx migrate --run-migrations=migrations.json`.

**Comment by mehrad-rafigh** [comment]
@manju-reddys After `nx migrate` you need to run `npm install` and then `nx migrate --run-migrations=migrations.json`
