### ISSUE TITLE
Add dependency to format

### ISSUE THREAD

**Issue by noumaans** [nrwl/nx#434]
I believe package dependency to format is missing, which is being used to generate ngrx feature files.

As mentioned in #431 there is an error when generating schematics.

```
  create app/modules/tabs/+state/template.actions.ts (644 bytes)
  create app/modules/tabs/+state/template.reducer.ts (828 bytes)
  create app/modules/tabs/+state/template.effects.ts (821 bytes)
  create app/modules/tabs/+state/template.effects.spec.ts (1044 bytes)
  create app/modules/tabs/+state/template.reducer.spec.ts (345 bytes)
  update app/modules/tabs/tabs.module.ts (1456 bytes)
  update package.json (3898 bytes)
npm ERR! missing script: format
```

NPM Log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@8/8.11.1/bin/node',
1 verbose cli   '/usr/local/opt/node@8/bin/npm',
1 verbose cli   'run',
1 verbose cli   'format',
1 verbose cli   '--',
1 verbose cli   '--untracked',
1 verbose cli   '--quiet' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose stack Error: missing script: format
4 verbose stack     at run (/usr/local/Cellar/node@8/8.11.1/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/Cellar/node@8/8.11.1/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/Cellar/node@8/8.11.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/Cellar/node@8/8.11.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:402:5
4 verbose stack     at checkBinReferences_ (/usr/local/Cellar/node@8/8.11.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:357:45)
4 verbose stack     at final (/usr/local/Cellar/node@8/8.11.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:400:3)
4 verbose stack     at then (/usr/local/Cellar/node@8/8.11.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/Cellar/node@8/8.11.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (/usr/local/Cellar/node@8/8.11.1/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
5 verbose cwd /Users/.../work/foo/apps/bar
6 verbose Darwin 17.5.0
7 verbose argv "/usr/local/Cellar/node@8/8.11.1/bin/node" "/usr/local/opt/node@8/bin/npm" "run" "format" "--" "--untracked" "--quiet"
8 verbose node v8.11.1
9 verbose npm  v5.6.0
10 error missing script: format
11 verbose exit [ 1, true ]
```

From workspace's package.json:
```
  "dependencies": {
...
    "@nrwl/nx": "^1.0.1-beta.1",
  },
  "devDependencies": {
...
    "@nrwl/schematics": "^1.0.1-beta.1",
}
```

Global package.json:
```
"@nrwl/schematics": "^1.0.1-beta.1"
```

**Comment by vsavkin** [comment]
Could you point to a github repository with a repro?
