### ISSUE TITLE
The ng command does not create the component correctly

### ISSUE THREAD

**Issue by StringKe** [nrwl/nx#4344]
## Current Behavior

```ng g c test``` Unable to create component

## Expected Behavior

create a angular component

## Steps to Reproduce
You can view the terminal video here [asciinema](https://asciinema.org/a/N3IUtIeCiY8PpEbt62sB4PgUO)

### Failure Logs

```
TypeError: Cannot read property 'match' of undefined
    at noCacheNormalize (/Users/chenquan/Project/Company/new/test-workspace/node_modules/@angular-devkit/core/src/virtual-fs/path.js:207:14)
    at Object.normalize (/Users/chenquan/Project/Company/new/test-workspace/node_modules/@angular-devkit/core/src/virtual-fs/path.js:189:21)
    at Object.parseName (/Users/chenquan/Project/Company/new/test-workspace/node_modules/@schematics/angular/utility/parse-name.js:15:56)
    at /Users/chenquan/Project/Company/new/test-workspace/node_modules/@schematics/angular/component/index.js:96:41
Cannot read property 'match' of undefined
```

### Environment

```

  Node : 14.15.1
  OS   : darwin x64
  npm  : 6.14.9

  nx : Not Found
  @nrwl/angular : 11.0.12
  @nrwl/cli : 11.0.12
  @nrwl/cypress : 11.0.12
  @nrwl/devkit : 11.0.12
  @nrwl/eslint-plugin-nx : 11.0.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.12
  @nrwl/linter : 11.0.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.12
  typescript : 4.0.5

```

**Comment by StringKe** [comment]
I ran a trace on the program and found the following, which I hope will help to fix the problem

https://github.com/nrwl/nx/blob/00ece927aa49a7099c890ddf2a7aa644f3a6881e/packages/tao/src/commands/generate.ts#L224-L248

I always get to the else code block。

https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/component/index.ts#L132

options.path is always undefined
