### ISSUE TITLE
npx create-nx-workspace@latest fails - unable to build workspace

### ISSUE THREAD

**Issue by cuznerdexter** [nrwl/nx#4354]
## Current Behavior
npx create-nx-workspace@latest fails to run and exits with errors
"Unable to resolve @nrwl/workspace/collection.json:new."

## Expected Behavior
npx create-nx-workspace@latest should build the workspace and allow apps to be added

## Steps to Reproduce
create new folder, cd into folder.
type npx create-nx-workspace@latest in the terminal

### Failure Logs
```
➜  multipleNX npx create-nx-workspace@latest 
npx: installed 192 in 7.769s
? Workspace name (e.g., org name)     chicnraw
? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    webstore
? Default stylesheet format           CSS
? Default linter                      TSLint [ Used by Angular CLI ]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
added 192 packages from 155 contributors and audited 193 packages in 4.786s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

new chicnraw --no-interactive --preset=angular --appName=webstore --style=css --linter=tslint --no-nxCloud --collection=@nrwl/workspace
Unable to resolve @nrwl/workspace/collection.json:new.
Cannot find generator 'new' in /Users/cuznerdexter/node_modules/@nrwl/workspace/collection.json.
(node:32464) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new chicnraw --no-interactive --preset=angular --appName=webstore --style=css --linter=tslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot="/Users/cuznerdexter/Development/Projects/experiments/multipleNX"
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at createApp (/Users/cuznerdexter/.npm/_npx/32459/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:366:21)
    at askAboutNxCloud.then (/Users/cuznerdexter/.npm/_npx/32459/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:92:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:32464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
➜  multipleNX 
```

### Environment
unable to use nx report as no workspace is created.
OS:  MacOS Catalina
NVM installed.
Using node v12.4.0
Using npm 6.14.4

**Comment by vsavkin** [comment]
Thanks for submitting the issue. 

I'm not able to repro but I have a few ideas. 

Can you try the following:

```
cd /tmp
npx create-nx-workpspace@11.0.15
```

**Comment by cuznerdexter** [comment]
Thanks for looking at this Victor,

I followed your advice and it worked in the tmp folder.
cd to /tmp
```
➜  /tmp npx create-nx-workspace@11.0.15 
npx: installed 192 in 6.602s
? Workspace name (e.g., org name)     chicnraw
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building 
apps]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
added 192 packages from 155 contributors and audited 193 packages in 4.091s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

new chicnraw --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
✔ Packages installed successfully.
    Successfully initialized git.
CREATE chicnraw/nx.json (544 bytes)
CREATE chicnraw/tsconfig.base.json (467 bytes)
CREATE chicnraw/README.md (3249 bytes)
CREATE chicnraw/.editorconfig (245 bytes)
CREATE chicnraw/.gitignore (503 bytes)
CREATE chicnraw/.prettierignore (74 bytes)
CREATE chicnraw/.prettierrc (26 bytes)
CREATE chicnraw/workspace.json (97 bytes)
CREATE chicnraw/package.json (1161 bytes)
CREATE chicnraw/tools/tsconfig.tools.json (223 bytes)
CREATE chicnraw/tools/generators/.gitkeep (0 bytes)
CREATE chicnraw/.vscode/extensions.json (109 bytes)
CREATE chicnraw/apps/.gitkeep (0 bytes)
CREATE chicnraw/libs/.gitkeep (0 bytes)
➜  /tmp 
```

**Comment by cuznerdexter** [comment]
I tried the exact same nx workspace version in my project folders and it failed again.
Guess it must be a node / npm issue in my system somewhere.

Thanks for the help, would not have thought of trying it in the /tmp folder.

**Comment by cuznerdexter** [comment]
If anyone has the same issue.
My current work-around is to run `npx create-nx-workpspace@11.0.15`  in my `/tmp folder` then move the folder to somewhere useful.
After this all the nx commands are working as normal for me so far.

Not a great solution but will do for now.

**Comment by vsavkin** [comment]
I think the issue is that you somehow got node_module in your home folder, and they have an old version of @nrwl/workspace in them. So basically you are trying to create a new nx workspace from within another nx workspace, which happens to be old. Just remove the node modules in your home dir and it should fix the issue.
