### ISSUE TITLE
E2E tests fails when creating a new nx-plugin workspace

### ISSUE THREAD

**Issue by stefan-karlsson** [nrwl/nx#4359]
## Current Behavior
When creating a new NX plugin workspace using `npx create-nx-plugin my-plugin-workspace --pluginName my-plugin` the E2E tests timeout. 

## Expected Behavior
The E2E tests should pass

## Steps to Reproduce
- `npx create-nx-plugin@latest my-plugin-workspace --pluginName my-plugin`
- `cd my-plugin-workspace`
- `npm run e2e my-plugin-e2e`

### Failure Logs
```
 FAIL   my-plugin-e2e  e2e/my-plugin-e2e/tests/my-plugin.spec.ts (28.243 s)
  my-plugin e2e
    × should create my-plugin (25347 ms)
    --directory
      × should create src in the specified directory (29 ms)
    --tags
      × should add tags to nx.json (3 ms)

  ● my-plugin e2e › should create my-plugin

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

       7 | } from '@nrwl/nx-plugin/testing';
       8 | describe('my-plugin e2e', () => {
    >  9 |   it('should create my-plugin', async (done) => {
         |   ^
      10 |     const plugin = uniq('my-plugin');
      11 |     ensureNxProject(
      12 |       '@my-plugin-workspace/my-plugin',

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/my-plugin.spec.ts:9:3)
      at Object.<anonymous> (tests/my-plugin.spec.ts:8:1)

  ● my-plugin e2e › --directory › should create src in the specified directory

    EBUSY: resource busy or locked, rmdir 'C:\Development\Personal\my-plugin-workspace/tmp/nx-e2e/proj'

      at rmdirSync (../../node_modules/fs-extra/lib/remove/rimraf.js:276:13)
      at Object.rimrafSync (../../node_modules/fs-extra/lib/remove/rimraf.js:252:7)
      at Object.cleanup (../../packages/nx-plugin/src/utils/testing-utils/utils.ts:119:3)
      at newNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:67:3)
      at Object.ensureNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:82:3)
      at tests/my-plugin.spec.ts:28:7
      at ../../node_modules/tslib/tslib.js:114:75

  ● my-plugin e2e › --tags › should add tags to nx.json

    EBUSY: resource busy or locked, rmdir 'C:\Development\Personal\my-plugin-workspace/tmp/nx-e2e/proj'

      at rmdirSync (../../node_modules/fs-extra/lib/remove/rimraf.js:276:13)
      at Object.rimrafSync (../../node_modules/fs-extra/lib/remove/rimraf.js:252:7)
      at Object.cleanup (../../packages/nx-plugin/src/utils/testing-utils/utils.ts:119:3)
      at newNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:67:3)
      at Object.ensureNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:82:3)
      at tests/my-plugin.spec.ts:45:7
      at ../../node_modules/tslib/tslib.js:114:75

Test Suites: 1 failed, 1 total
Tests:       3 failed, 3 total
Snapshots:   0 total
Time:        29.911 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-plugin-workspace@0.0.0 e2e: `nx e2e "my-plugin-e2e"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-plugin-workspace@0.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stefa\AppData\Roaming\npm-cache\_logs\2020-12-20T12_04_00_253Z-debug.log
```

### Environment
```
  Node : 14.15.0
  OS   : win32 x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.15
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.0.15
  @nrwl/eslint-plugin-nx : 11.0.15
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.15
  @nrwl/linter : 11.0.15
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.0.15
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.15
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.15
  typescript : 4.0.5
```

**Comment by stefan-karlsson** [comment]
When checking the generated e2e application in the `tmp` folder i can see a one inconsistency, not sure if this causes the error.

**package.json**
Contains this strange looking path: `"@my-plugin-workspace/my-plugin": "file:C:\\Development\\Personal\\my-plugin-workspace/dist/packages/my-plugin"` under `devDependencies`

**Comment by BLaZeKiLL** [comment]
faced the same issue, as a work around I changed the timeout (in ms) value and the test passes

```
it('test', async(done) => {

}, 500000);
```

**Comment by Cammisuli** [comment]
This error is the interesting part:
```
 EBUSY: resource busy or locked, rmdir
```

I suspect it's something to do with Windows. I'll have to get a Windows machine/vm and check it out there.

**Comment by adamstret** [comment]
Why the hell was this closed? The errors are still there!!! Brand new create-nx-plugin and the e2e tests fail. Ridiculous...

**Comment by Jameskmonger** [comment]
This is still an issue for me, on Windows.

When I run the e2e (on a freshly generated plugin):

```
  ● pipenv e2e › --tags › should add tags to the project

    Command failed: node D:\Development\my_company\backend\node_modules\nx\bin\nx.js new proj --nx-workspace-root=D:\Development\my_company\backend/tmp/nx-e2e --no-interactive --skip-install --collection=@nrwl/workspace --npmScope=proj --preset=empty

      at runNxNewCommand (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:15:18)
      at newNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:72:3)
      at ensureNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:86:3)
      at tests/pipenv.spec.ts:48:22
      at ../../node_modules/tslib/tslib.js:118:75
      at Object.__awaiter (../../node_modules/tslib/tslib.js:114:16)
```

When I run that inner `node` command I get:

```
λ node D:/Development/my_company/backend/node_modules/nx/bin/nx.js new proj --nx-workspace-root=D:/Development/my_company/backend/tmp/nx-e2e --no-interactive --skip-install --collection=@nrwl/workspace --npmScope=proj --preset=empty

 >  NX   D:\Development\my_company\backend\tmp\nx-e2e\proj is not an empty directory.

   Pass --verbose to see the stacktrace.
```

**Comment by Jameskmonger** [comment]
I'm quite new to NX, not sure where to start with looking into this. Will try my best but if anyone has any pointers please let me know. I like the look of NX and I'd like to start using it.
