### ISSUE TITLE
Comments not supported in angular.json

### ISSUE THREAD

**Issue by MaximSagan** [nrwl/nx#4375]
## Current Behavior
When NX runs `affected:lint`, an error is thrown by nrwl/tao.

## Expected Behavior
Comments in JSON files should be ignored

## Steps to Reproduce
Add a comment to your angular.json file and run `affect:lint`.

### Failure Logs
```
SyntaxError: Unexpected token / in JSON at position 8289
    at JSON.parse (<anonymous>)
    at Workspaces.readWorkspaceConfiguration (C:\Apps\Projects\ui\node_modules\@nrwl\tao\src\shared\workspace.js:19:24)
    at Object.readWorkspaceJson (C:\Apps\Projects\ui\node_modules\@nrwl\workspace\src\core\file-utils.js:135:15)
    at Object.createProjectGraph (C:\Apps\Projects\ui\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:13:58)
    at Object.<anonymous> (C:\Apps\Projects\ui\node_modules\@nrwl\workspace\src\command-line\affected.js:23:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Apps\Projects\ui\node_modules\tslib\tslib.js:111:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
```

### Environment
```
  Node : 10.16.0
  OS   : win32 x64
  npm  : 6.9.0
  
  nx : Not Found
  @nrwl/angular : 11.0.2
  @nrwl/cli : 11.0.2
  @nrwl/cypress : 11.0.2
  @nrwl/devkit : 11.0.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.2
  @nrwl/linter : 11.0.2
  @nrwl/nest : 11.0.2
  @nrwl/next : Not Found
  @nrwl/node : 11.0.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.2
  typescript : 4.0.5
```

**Comment by vsavkin** [comment]
Fixed here: https://github.com/nrwl/nx/commit/cd8efa47ac0694d7199c9b7612a0aa4cb0b7bd65

Thank you!
