### ISSUE TITLE
Error: spawnSync on create-nx-workspace

### ISSUE THREAD

**Issue by emmalivingstone** [nrwl/nx#443]
Just ran the command `npm install @nrwl/schematics -g` to get version 1.0.2 of the schematics. Then ran `create-nx-workspace test-workspace --directory=frontend` and I got this error:

Error: spawnSync C:\WINDOWS\system32\cmd.exe ENOENT
    at _errnoException (util.js:1022:11)
    at spawnSync (child_process.js:579:20)
    at Object.execSync (child_process.js:635:13)
    at Object.<anonymous> (C:\Users\emliv\AppData\Local\Yarn\config\global\node_modules\@nrwl\schematics\bin\create-nx-workspace.js:77:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

OS: Windows 10
Angular CLI: 1.7.4

**Comment by nortain** [comment]
I did a little more digging into my issue and it looks like I was missing dependent modules from my global namespace.  The modules I was missing were:
```
@ngrx/schematics
@angular-devkit/schematics
@angular-devkit/core
cosmiconfig
```

After installing each of these with the -g flag I was able to get the create-nx-workspace command to work for me.
