### ISSUE TITLE
failing `rename-ng-update-into-nx-migrate` migration

### ISSUE THREAD

**Issue by peterbsmith2** [nrwl/nx#4464]
## Current Behavior

Failing migration from Nx 10 to Nx 11

## Expected Behavior

Error handling or successful migration

## Steps to Reproduce

Cannot provide reproduction steps. 

### Failure Logs

```
Running migration rename-ng-update-into-nx-migrate
host.exists is not a function
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/Users/upstateinteractive/code/community/nx-ddd-plugin/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (/Users/upstateinteractive/code/community/nx-ddd-plugin/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:76:21)
    at Object.runCommand (/Users/upstateinteractive/code/community/nx-ddd-plugin/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/upstateinteractive/code/community/nx-ddd-plugin/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/upstateinteractive/code/community/nx-ddd-plugin/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/upstateinteractive/code/community/nx-ddd-plugin/node_modules/@nrwl/cli/lib/init-local.js:23:13)
    at Object.<anonymous> (/Users/upstateinteractive/code/community/nx-ddd-plugin/node_modules/@nrwl/cli/bin/nx.js:41:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3189,
  stdout: null,
  stderr: null
}
```

**Comment by vsavkin** [comment]
Unfortunately I'm not able to repro it. Did you run `npm install` before running the migrations? 

Could you provide a repo with a repro?

**Comment by DUBANGARCIA** [comment]
+1

**Comment by DUBANGARCIA** [comment]
The same error had also happened to me since I was trying to update from angular 9 to angular 10, so I deleted the migrations of the beta versions and only left the stable ones in the migrations file and the problem was solved, but I must clarify that I do not know if it omits migrations or if it would simply be in stable versions such migrations

**Comment by tinesoft** [comment]
Hi 

I'm facing the same issue decribed by @peterbsmith2 ...
After the `yarn update`, i did perform a `rm -rf node_modules`, follow by `yarn`, then `nx migrate --run-migrations=migrations.json`)but nothing changed...

You can reproduce by doing the same my project here: https://github.com/tinesoft/nxrocks

**Comment by vsavkin** [comment]
Folks. I fixed it in 11.3.0-beta.2 (if you run nx migrate 11.3.0-beta.2, the issue won't be there). We are going to cut a stable release next week.

Thank you!

**Comment by laurentsd** [comment]
@vsavkin Hi Victor, FYI I am running into this error today when upgrading Nx from 10.4.12 to 11.6.3

**Comment by laurentsd** [comment]
it worked when I updated from Node 10.19.0 to 12.16.3.  Does this mean than Nx 11 is not compatible with Node < 12?
