### ISSUE TITLE
nx serve dying in webpack rebuilds due to outdated fork-ts-checker-webpack-plugin

### ISSUE THREAD

**Issue by ultd** [nrwl/nx#4494]
Nx running in Minikube results in webpack failing at times 

## Current Behavior
Running `nx serve $(REACT_PROJECT)` after a few recompiles results in this error: 

```
ℹ ｢wdm｣: Compiling...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:679:16)
    at RpcProvider._dispatch (/usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/cluster.js:42:20)
    at RpcProvider.rpc (/usr/src/app/node_modules/worker-rpc/lib/RpcProvider.js:32:14)
    at /usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/cluster.js:53:83
    at Array.map (<anonymous>)
    at Object.<anonymous> (/usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/cluster.js:53:56)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/cluster.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/cluster.js:3:12)
Emitted 'error' event on ChildProcess instance at:
    at internal/child_process.js:683:35
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```

The bug is fixed in `fork-ts-checker-webpack-plugin@v4.0.4` as mentioned [here](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/363#issuecomment-585601162)

## Expected Behavior
No error to be thrown.

### Environment
Minikube 
Node v12.20.0

Can we please upgrade `fork-ts-checker-webpack-plugin` dependency to `@V4.0.4`?

**Comment by mehrad-rafigh** [comment]
Shouldn't we update that to ^6.1.0? I can open a PR for this

**Comment by ultd** [comment]
@mehrad-rafigh You're right I meant update it to `@v4.0.4` or higher. Please do make the PR :)

**Comment by mehrad-rafigh** [comment]
@ultd There are a ton of breaking changes. I can give it a try, but that might take a while
