### ISSUE TITLE
Migrating from Nx 10 to 11 fails with "maximum call stack size exceeded" 

### ISSUE THREAD

**Issue by tommueller** [nrwl/nx#4496]
I am trying to migrate from Nx 10 to Nx 11. I successfully updated the npm dependencies, but now running `nx migrate --run-migrations=migrations.json` fails with the error:

```
Running migration @nrwl/angular:add-template-support-and-presets-to-eslint
Maximum call stack size exceeded
/home/user/workspace-ts/ts_web_app/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: npx tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at Object.handler (/home/user/workspace-ts/ts_web_app/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:76:21)
    at Object.runCommand (/home/user/workspace-ts/ts_web_app/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/user/workspace-ts/ts_web_app/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/home/user/workspace-ts/ts_web_app/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/home/user/workspace-ts/ts_web_app/node_modules/@nrwl/cli/lib/init-local.js:24:13)
    at Object.<anonymous> (/home/user/workspace-ts/ts_web_app/node_modules/@nrwl/cli/bin/nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 73163,
  stdout: null,
  stderr: null
}
```

Any additional information I should provide?

**Comment by vsavkin** [comment]
Hi there. Thank you for submitting the issue. 

Unfortunately I'm not able to reproduce it. Can you create a repo with a repro?

**Comment by tommueller** [comment]
Thanks @vsavkin. I managed to find the cause, it was actually a misconfiguration in our `angular.json`: one of the projects root property was set incorrectly.
So the only take-away from this ticket might be, that a clearer error-message would have been helpful. Not sure, if that would be detectable though :)
