### ISSUE TITLE
[nx-plugin] Running a wrapped schematic in a unit test fails

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#4538]
## Current Behavior

In an Nx Plugin project, when running a 'wrapped schematic' (like `applicationGenerator` from `@nrwl/nest`) in a unit test, the operation fails with this error message:

```
Error: ENOENT: no such file or directory, open '/virtual/workspace.json'
```

When inspecting the `host: Tree`, it turns out that the file `/workspace.json` exists in the root, not in `virtual/`.

When I run this same code inside an e2e test, it does seem to work as expected.

It's very likely that I'm doing something wrong, I'm just not sure what.

## Expected Behavior

The wrapped schematic should be executed correctly.

## Steps to Reproduce

Here is a repro [here](https://github.com/beeman/nx-plugin-wrap-schematic), or follow these steps:

```
npm create-nx-plugin nx11-plugin --plugin-name wrapper
cd nx11-plugin
npm i -D @nrwl/nest
```

Then edit `packages/wrapper/src/generators/wrapper/generator.ts`:

Add the import:
```ts
import { applicationGenerator } from '@nrwl/nest';
```

Update the generator:
```ts
export default async function (host: Tree, options: WrapperGeneratorSchema) {
  const normalizedOptions = normalizeOptions(host, options);
  await applicationGenerator(host, { name: normalizedOptions.projectName });
  addFiles(host, normalizedOptions);
  await formatFiles(host);
}
```

Now run the unit test:

```
nx test wrapper
```

### Failure Logs
```
Error: ENOENT: no such file or directory, open '/virtual/workspace.json'

    at Object.openSync (fs.js:474:3)
    at Object.readFileSync (fs.js:375:35)
    at Observable._subscribe (/Users/beeman/dev/nxpm/node_modules/@angular-devkit/core/node/host.js:192:35)
    at Observable.Object.<anonymous>.Observable._trySubscribe (/Users/beeman/dev/nxpm/node_modules/rxjs/src/internal/Observable.ts:238:19)
    at Observable.Object.<anonymous>.Observable.subscribe (/Users/beeman/dev/nxpm/node_modules/rxjs/src/internal/Observable.ts:219:14)
    at MapOperator.Object.<anonymous>.MapOperator.call (/Users/beeman/dev/nxpm/node_modules/rxjs/src/internal/operators/map.ts:59:19)
    at Observable.Object.<anonymous>.Observable.subscribe (/Users/beeman/dev/nxpm/node_modules/rxjs/src/internal/Observable.ts:214:25)
    at Object.innerSubscribe (/Users/beeman/dev/nxpm/node_modules/rxjs/src/internal/innerSubscribe.ts:111:19)
    at SwitchMapSubscriber.Object.<anonymous>.SwitchMapSubscriber._innerSub (/Users/beeman/dev/nxpm/node_modules/rxjs/src/internal/operators/switchMap.ts:137:30)
    at SwitchMapSubscriber.Object.<anonymous>.SwitchMapSubscriber._next (/Users/beeman/dev/nxpm/node_modules/rxjs/src/internal/operators/switchMap.ts:126:10)
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.13.1
  OS   : darwin x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : 11.1.5
  @nrwl/next : Not Found
  @nrwl/node : 11.1.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5
```

**Comment by webberwang** [comment]
I'm also looking for a way to access external generators from a generator, doesn't seem to work at the moment

**Comment by beeman** [comment]
Thanks @vsavkin!
