### ISSUE TITLE
pnpm + vercel: Unable to resolve @nrwl/next:build

### ISSUE THREAD

**Issue by cyrus-za** [nrwl/nx#4540]
I am using a complex setup with nx, next, prisma and deploying on vercel.

## The problem

Every 2nd run on vercel results in an error. Clicking `Redeploy` usually fixes it, until the next PR is opened. 

I change `build` for my app (`flow`) to call multiple nx commands ending with `next-build` which calls the `@nrwl/next:build` builder. The reason for this is due to having a lib called `flow-data` that handles the prisma part and I need the prisma client to be generated (`flow-data:build`) and the prisma migrations applied to the DB (`flow-data:deploy`) before nextjs can build and generate static pages (that call prisma client in `getStaticProps`). 

## related issue (potentially)
Searching for the error took me to https://github.com/nrwl/nx/issues/4516

This might be a deep import

## vercel

This only happens when deploying to vercel and not in my github actions. The error only occurs on the next.js build.

As @JamesHenry suggested in #3051 and #4416 I am running `nx build flow` from the root. 

## pnpm

I am using `pnpm` as package manager, but I do use `--shamefully-hoist` to flatten the modules. This issue may or may not be related to `pnpm`. 

To install on vercel I run `npx --ignore-existing pnpm  i --ignore-scripts --shamefully-hoist`

## workspace.json

```json
{
  "version": 1,
  "projects": {
    "flow": {
      "root": "apps/flow",
      "sourceRoot": "apps/flow",
      "projectType": "application",
      "schematics": {},
      "architect": {
        "next-build": {
          "builder": "@nrwl/next:build",
          "options": {
            "root": "apps/flow",
            "outputPath": "dist/apps/flow"
          },
          "configurations": {
            "production": {}
          },
          "outputs": ["{options.outputPath}"]
        },
        "build": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              "nx build flow-data --skip-nx-cache",
              "nx deploy flow-data",
              "nx next-build flow"
            ],
            "parallel": false
          },
          "configurations": {
            "production": {
              "commands": [
                "nx build flow-data --skip-nx-cache",
                "nx deploy flow-data",
                "nx next-build flow --prod --outputPath=."
              ]
            }
          }
        },
        "serve": {
          "builder": "@nrwl/next:server",
          "options": {
            "buildTarget": "flow:next-build",
            "dev": true
          },
          "configurations": {
            "production": {
              "buildTarget": "flow:next-build:production",
              "dev": false
            }
          }
        },
        "export": {
          "builder": "@nrwl/next:export",
          "options": {
            "buildTarget": "flow:next-build:production"
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["apps/flow/**/*.{ts,tsx}"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/flow/jest.config.js",
            "passWithNoTests": true,
            "tsConfig": "apps/flow/tsconfig.spec.json"
          },
          "outputs": ["coverage/apps/flow"]
        }
      }
    },
    "flow-e2e": {
      "root": "apps/flow-e2e",
      "sourceRoot": "apps/flow-e2e/src",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/flow-e2e/cypress.json",
            "tsConfig": "apps/flow-e2e/tsconfig.e2e.json",
            "devServerTarget": "flow:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "flow:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["apps/flow-e2e/**/*.{js,ts}"]
          }
        }
      }
    },
    "authorization": {
      "root": "libs/authorization",
      "sourceRoot": "libs/authorization/src",
      "projectType": "library",
      "schematics": {},
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/authorization/**/*.ts"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/authorization/jest.config.js",
            "passWithNoTests": true,
            "tsConfig": "libs/authorization/tsconfig.spec.json"
          },
          "outputs": ["coverage/libs/authorization"]
        }
      }
    },
    "authentication": {
      "root": "libs/authentication",
      "sourceRoot": "libs/authentication/src",
      "projectType": "library",
      "schematics": {},
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/authentication/**/*.ts"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/authentication/jest.config.js",
            "passWithNoTests": true,
            "tsConfig": "libs/authentication/tsconfig.spec.json"
          },
          "outputs": ["coverage/libs/authentication"]
        }
      }
    },
    "flow-data": {
      "root": "libs/flow-data",
      "sourceRoot": "libs/flow-data/src",
      "projectType": "library",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@nrwl/workspace:run-commands",
          "outputs": ["node_modules/.prisma/client"],
          "options": {
            "command": "npx prisma generate",
            "cwd": "libs/flow-data"
          }
        },
        "seed": {
          "builder": "@nrwl/workspace:run-commands",
          "outputs": [],
          "options": {
            "command": "ts-node --project tsconfig.spec.json src/lib/seed.ts",
            "cwd": "libs/flow-data"
          }
        },
        "migrate-db": {
          "builder": "@nrwl/workspace:run-commands",
          "outputs": [],
          "options": {
            "command": "npx prisma migrate dev --preview-feature",
            "cwd": "libs/flow-data"
          }
        },
        "studio": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "command": "npx prisma studio",
            "cwd": "libs/flow-data"
          }
        },
        "deploy": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "command": "npx prisma migrate deploy --preview-feature",
            "cwd": "libs/flow-data"
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/flow-data/**/*.ts"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/flow-data/jest.config.js",
            "passWithNoTests": true,
            "tsConfig": "libs/flow-data/tsconfig.spec.json"
          },
          "outputs": ["coverage/libs/flow-data"]
        }
      }
    },
    "use-local-store": {
      "root": "libs/use-local-store",
      "sourceRoot": "libs/use-local-store/src",
      "projectType": "library",
      "schematics": {},
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/use-local-store/**/*.{ts,tsx,js,jsx}"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/use-local-store/jest.config.js",
            "passWithNoTests": true,
            "tsConfig": "libs/use-local-store/tsconfig.spec.json"
          },
          "outputs": ["coverage/libs/use-local-store"]
        }
      }
    },
    "ui-topbar": {
      "root": "libs/ui/topbar",
      "sourceRoot": "libs/ui/topbar/src",
      "projectType": "library",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/ui/topbar/**/*.{ts,tsx,js,jsx}"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/ui/topbar/jest.config.js",
            "passWithNoTests": true,
            "tsConfig": "libs/ui/topbar/tsconfig.spec.json"
          },
          "outputs": ["coverage/libs/ui/topbar"]
        }
      }
    },
    "ui-avatar": {
      "root": "libs/ui/avatar",
      "sourceRoot": "libs/ui/avatar/src",
      "projectType": "library",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/ui/avatar/**/*.{ts,tsx,js,jsx}"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/ui/avatar/jest.config.js",
            "passWithNoTests": true,
            "tsConfig": "libs/ui/avatar/tsconfig.spec.json"
          },
          "outputs": ["coverage/libs/ui/avatar"]
        }
      }
    },
    "ui-icons": {
      "root": "libs/ui/icons",
      "sourceRoot": "libs/ui/icons/src",
      "projectType": "library",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/ui/icons/**/*.{ts,tsx,js,jsx}"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": ["coverage/libs/ui/icons"],
          "options": {
            "jestConfig": "libs/ui/icons/jest.config.js",
            "passWithNoTests": true
          }
        }
      }
    }
  },
  "cli": {
    "defaultCollection": "@nrwl/next"
  },
  "schematics": {
    "@nrwl/react": {
      "application": {
        "babel": true
      }
    },
    "@nrwl/next": {
      "application": {
        "style": "styled-components",
        "linter": "eslint"
      }
    }
  },
  "defaultProject": "flow"
}
```

## logs

```sh
19:43:06.643 | Cloning completed in 589ms
19:43:06.650 | Analyzing source code...
19:43:08.532 | Installing build runtime...
19:43:09.106 | Build runtime installed: 573.488ms
19:43:09.979 | Looking up build cache...
19:43:10.379 | Build cache found. Downloading...
19:43:18.334 | Build cache downloaded [133.09 MB]: 7951.786ms
19:43:19.220 | Running "install" command: `npx --ignore-existing pnpm  i --ignore-scripts --shamefully-hoist`...
19:43:20.954 | npx: installed 1 in 1.616s
19:43:21.640 | Lockfile is up-to-date, resolution step is skipped
19:43:21.861 | Progress: resolved 1, reused 0, downloaded 0, added 0
19:43:22.007 | Packages: +2
19:43:22.010 | ++
19:43:22.111 | Progress: resolved 2, reused 0, downloaded 2, added 2, done
19:43:22.246 | WARN  Failed to find "/fsevents/2.1.3" in lockfile during hoisting. Next aliases will not be hoisted: fsevents
19:43:23.085 | Cannot link binary 'jest' of 'jest-cli' to '/vercel/workpath0/node_modules/.bin': binary of 'jest' is already linked
19:43:23.465 | dependencies:
19:43:23.465 | + @casl/ability 5.1.1
19:43:23.465 | + @casl/react 2.2.1
19:43:23.465 | + @fortawesome/fontawesome-svg-core 1.2.32
19:43:23.465 | + @fortawesome/free-solid-svg-icons 5.15.1
19:43:23.466 | + @fortawesome/react-fontawesome 0.1.14
19:43:23.466 | + @handsontable/react 4.0.0
19:43:23.466 | + @invisible/logger 3.0.2
19:43:23.466 | + @invisible/ui 2.29.2
19:43:23.466 | + @prisma/client 2.14.0
19:43:23.466 | + document-register-element 1.14.10
19:43:23.466 | + env-var 7.0.0
19:43:23.466 | + faker 5.1.0
19:43:23.466 | + handsontable 8.2.0
19:43:23.466 | + lodash 4.17.20
19:43:23.466 | + next 10.0.4
19:43:23.466 | + next-auth 3.2.0-canary.16
19:43:23.466 | + react 17.0.1
19:43:23.466 | + react-dom 17.0.1
19:43:23.467 | + react-is 17.0.1
19:43:23.467 | + react-post 1.0.3
19:43:23.467 | + rebass 4.0.7
19:43:23.467 | + slugify 1.4.6
19:43:23.467 | + styled-components 5.2.1
19:43:23.467 | + swr 0.4.0
19:43:23.467 | + tslib 2.0.3
19:43:23.467 | devDependencies:
19:43:23.467 | + @babel/core 7.12.10
19:43:23.467 | + @babel/preset-env 7.12.11
19:43:23.467 | + @babel/preset-react 7.12.10
19:43:23.467 | + @babel/preset-typescript 7.12.7
19:43:23.468 | + @nrwl/cli 11.1.1
19:43:23.468 | + @nrwl/cypress 11.1.1
19:43:23.468 | + @nrwl/eslint-plugin-nx 11.1.1
19:43:23.468 | + @nrwl/jest 11.1.1
19:43:23.468 | + @nrwl/next 11.1.1
19:43:23.468 | + @nrwl/node 11.1.1
19:43:23.468 | + @nrwl/nx-cloud 11.0.1
19:43:23.468 | + @nrwl/react 11.1.1
19:43:23.468 | + @nrwl/tao 11.1.1
19:43:23.468 | + @nrwl/web 11.1.1
19:43:23.468 | + @nrwl/workspace 11.1.1
19:43:23.468 | + @prisma/cli 2.14.0
19:43:23.468 | + @testing-library/react 11.2.2
19:43:23.469 | + @types/faker 5.1.5
19:43:23.469 | + @types/jest 26.0.19
19:43:23.469 | + @types/lodash 4.14.166
19:43:23.469 | + @types/next-auth 3.1.19
19:43:23.469 | + @types/node 12.19.12
19:43:23.469 | + @types/react 17.0.0
19:43:23.469 | + @types/react-dom 17.0.0
19:43:23.469 | + @types/react-is 17.0.0
19:43:23.469 | + @types/styled-components 5.1.7
19:43:23.469 | + @typescript-eslint/eslint-plugin 4.12.0
19:43:23.469 | + @typescript-eslint/parser 4.12.0
19:43:23.469 | + babel-jest 26.6.3
19:43:23.470 | + babel-plugin-styled-components 1.12.0
19:43:23.470 | + cypress 6.2.0
19:43:23.470 | + dotenv 8.2.0
19:43:23.470 | + eslint 7.17.0
19:43:23.470 | + eslint-config-prettier 7.1.0
19:43:23.470 | + eslint-plugin-cypress 2.11.2
19:43:23.470 | + eslint-plugin-import 2.22.1
19:43:23.470 | + eslint-plugin-jsx-a11y 6.4.1
19:43:23.470 | + eslint-plugin-react 7.22.0
19:43:23.470 | + eslint-plugin-react-hooks 4.2.0
19:43:23.470 | + jest 26.6.3
19:43:23.470 | + jest-localstorage-mock 2.4.6
19:43:23.470 | + pnpm 5.14.3
19:43:23.470 | + prettier 2.2.1
19:43:23.470 | + prisma-dbml-generator 0.4.0
19:43:23.470 | + ts-jest 26.4.4
19:43:23.470 | + ts-node 9.1.1
19:43:23.470 | + ts-node-dev 1.1.1
19:43:23.471 | + typescript 4.1.3
19:43:23.471 | + vercel 21.0.1
19:43:23.864 | Running "npx nx build flow --prod --skip-nx-cache"
19:43:24.906 | > nx run flow:build:production
19:43:26.219 | > nx run flow-data:build
19:43:27.270 | Environment variables loaded from .env
19:43:27.349 | Prisma schema loaded from prisma/schema.prisma
19:43:28.150 | ✔ Generated Prisma Client (2.14.0) to ./../../node_modules/.pnpm/@prisma/client@2.14.0_@prisma+cli@2.14.0/node_modules/@prisma/client in 211ms
19:43:28.150 | ✔ Generated DBML Schema to ./prisma/dbml in 28ms
19:43:28.150 | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
19:43:28.150 | ```
19:43:28.150 | import { PrismaClient } from '@prisma/client'
19:43:28.150 | const prisma = new PrismaClient()
19:43:28.150 | ```
19:43:28.150 | warn Prisma 2.12.0 has breaking changes.
19:43:28.152 | You can update your code with
19:43:28.152 | `npx @prisma/codemods update-2.12 ./`
19:43:28.153 | Read more at https://pris.ly/2.12
19:43:29.937 | > nx run flow-data:deploy
19:43:30.997 | Environment variables loaded from .env
19:43:31.072 | Prisma schema loaded from prisma/schema.prisma
19:43:31.107 | Datasource "db": PostgreSQL database "postgres", schema "public" at "sg-flow-1553-pgsql-master.servers.mongodirector.com:6432"
19:43:31.290 | 11 migrations found in prisma/migrations
19:43:31.290 | WARNING The following migrations have been modified since they were applied:
19:43:31.290 | 20201230174829_table_names_lowercase_plural
19:43:31.328 | No pending migrations to apply.
19:43:33.192 | > nx run flow:next-build:production --outputPath=.
19:43:34.270 | Unable to resolve @nrwl/next:build.
19:43:34.270 | Class extends value undefined is not a constructor or null
19:43:34.319 | (node:1407) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
19:43:34.319 | at Object.error (/vercel/workpath0/node_modules/.pnpm/@nrwl/tao@11.1.1/node_modules/@nrwl/tao/src/shared/logger.js:10:15)
19:43:34.319 | at Object.<anonymous> (/vercel/workpath0/node_modules/.pnpm/@nrwl/tao@11.1.1/node_modules/@nrwl/tao/src/shared/params.js:17:33)
19:43:34.320 | at Generator.throw (<anonymous>)
19:43:34.320 | at rejected (/vercel/workpath0/node_modules/.pnpm/tslib@2.0.3/node_modules/tslib/tslib.js:112:69)
19:43:34.320 | (node:1407) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
19:43:34.320 | (node:1407) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
19:43:34.433 | >  NX   CLOUD  See run details at https://nx.app/runs/GMTI9mLMmEh
19:43:34.447 | Error: A "routes-manifest.json" couldn't be found. This is normally caused by a misconfiguration in your project.
19:43:34.447 | Please check the following, and reach out to support if you cannot resolve the problem:
19:43:34.447 | 1. If present, be sure your `build` script in "package.json" calls `next build`.  2. Navigate to your project's settings in the Vercel dashboard, and verify that the "Build Command" is not overridden, or that it calls `next build`.  3. Navigate to your project's settings in the Vercel dashboard, and verify that the "Output Directory" is not overridden. Note that `next export` does **not** require you change this setting, even if you customize the `next export` output directory. Learn More: https://err.sh/vercel/vercel/now-next-routes-manifest
19:43:39.271 | Done with "package.json"
```

**Comment by bekos** [comment]
@cyrus-za have you tried to execute your commands using `pnpm run nx --` instead of global `nx`?

**Comment by cyrus-za** [comment]
Sorry @bekos I only saw your reply now. 

No I have not, but I use direnv to add node_modules/bin to my path, so it's not running it globally. I havent installed nx globally. 

What ended up fixing it was adding --force to my install command. It appears that vercel's caching of node_modules do not work that great with pnpm. I have spoken to them and they are working on better pnpm support

**Comment by kirjai** [comment]
thanks for the update @cyrus-za 

seeing how you suspect it's a pnpm + vercel node_modules caching issue, doesn't seem like there's anything for us to do for this on the Nx side? If that's the case, seems like this issue can be closed

**Comment by cyrus-za** [comment]
Agreed
