### ISSUE TITLE
Jest: Tests including components with SVG templates are not executed

### ISSUE THREAD

**Issue by GregOnNet** [nrwl/nx#4565]
## Current Behavior
- Having component having an SVG-Template.
- Executing `nx test`
- Command fails

```
 Details:

    /Users/gregor/workbench/scratch/angular/playground/libs/component-svg/src/lib/hello/hello.component.svg:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<svg height="100" width="100">
                                                                                             ^

    SyntaxError: Unexpected token '<'

      3 | @Component({
      4 |   selector: 'playground-hello',
    > 5 |   templateUrl: './hello.component.svg',
        |   ^
      6 |   styleUrls: ['./hello.component.scss'],
      7 | })
      8 | export class HelloComponent {}

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (../../libs/component-svg/src/lib/hello/hello.component.ts:5:3)
```

## Expected Behavior
- SVG should be inlined and transformed correctly
- `nx test` should succeed

## Steps to Reproduce
- `git clone https://github.com/GregOnNet/nx-jest-svg-components`
- `cd nx-jest-svg-components`
- `nx test`

### What I did

- Create a new workspace
- Create a library
- Create a component in the library
- Use SVG Template in component
- Use component from library in app
- Reference library in TestBed of `app.component.spec.ts`
- Execute `nx test`

Can you reproduce this on https://github.com/nrwl/nx-examples?
- Yes
 
If so, open a PR with your changes and link it below.
- https://github.com/nrwl/nx-examples/pull/126

### Failure Logs
```
 FAIL   products-home-page  libs/products/home-page/src/lib/products-home-page.module.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/gregor/workbench/scratch/angular/nx-examples/libs/products/home-page/src/lib/svg-component/svg.component.svg:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<svg height="100" width="100">
                                                                                             ^

    SyntaxError: Unexpected token '<'

      3 | @Component({
      4 |   selector: 'products-svg',
    > 5 |   templateUrl: './svg.component.svg',
        |   ^
      6 |   styleUrls: ['./svg.component.scss'],
      7 | })
      8 | export class SvgComponent {}

      at Runtime.createScriptFromCode (../../../node_modules/jest-runtime/build/index.js:1270:14)
      at Object.<anonymous> (src/lib/svg-component/svg.component.ts:5:3)
```

### Environment

```
↑ nx report

>  NX  Report complete - copy this into the issue template

  Node : 12.18.3
  OS   : darwin x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 11.0.1-rc.0
  @nrwl/cli : 11.0.1-rc.0
  @nrwl/cypress : 11.0.1-rc.0
  @nrwl/devkit : 11.0.1-rc.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.1-rc.0
  @nrwl/linter : 11.0.1-rc.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.0.1-rc.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.1-rc.0
  @nrwl/web : 11.0.1-rc.0
  @nrwl/workspace : 11.0.1-rc.0
  typescript : 4.0.3
```

**Comment by Markus-Ende** [comment]
Thats because the nx preset doesn't add svg to the transform regex: ` transform: { '^.+\\.(ts|js|html)$': 'ts-jest' }`.
You can overwrite it in your `jest.preset.js` to make jest accept svg components:

```js
module.exports = {
  ...nxPreset,
  transform: {
    '^.+\\.(ts|js|html|svg)$': 'ts-jest',
  },
};

```

**Comment by LouisLecouturier** [comment]
Have you found the solution ? I'm struggling with that too

**Comment by Vovch** [comment]
In my case with an Angular project the problem was solved by adding an svg transform rule to my default `jest.config.ts` inside of the project.

So to the rule was
```ts
transform: {
    '^.+\\.(ts|mjs|js|html)$': 'jest-preset-angular',
},
```

And to make it work I used:
```ts
transform: {
  '^.+\\.(ts|mjs|js|html|svg)$': 'jest-preset-angular',
},
```

Hope that helps someone.
