### ISSUE TITLE
fn.bind is not a function - Angular & Storybook

### ISSUE THREAD

**Issue by ChazUK** [nrwl/nx#4589]
After creating a brand new workspace, app, library and component with Nx CLI, then installing Storybook and running the configuration script I am viewing the following error.

```
fn.bind is not a function
TypeError: fn.bind is not a function
    at newTrustedFunctionForJIT (http://localhost:4400/vendors~main.e6612a4cb4753e0a1e78.bundle.js:12552:15)
    at JitEvaluator.evaluateCode (http://localhost:4400/vendors~main.e6612a4cb4753e0a1e78.bundle.js:12616:29)
    at JitEvaluator.evaluateStatements (http://localhost:4400/vendors~main.e6612a4cb4753e0a1e78.bundle.js:12590:21)
    at JitCompiler._interpretOrJit (http://localhost:4400/vendors~main.e6612a4cb4753e0a1e78.bundle.js:34717:39)
    at JitCompiler._compileTemplate (http://localhost:4400/vendors~main.e6612a4cb4753e0a1e78.bundle.js:34689:33)
    at http://localhost:4400/vendors~main.e6612a4cb4753e0a1e78.bundle.js:34631:46
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (http://localhost:4400/vendors~main.e6612a4cb4753e0a1e78.bundle.js:34631:19)
    at http://localhost:4400/vendors~main.e6612a4cb4753e0a1e78.bundle.js:34544:18
    at Object.then (http://localhost:4400/vendors~main.e6612a4cb4753e0a1e78.bundle.js:8209:52)
```

## Steps to Reproduce
```terminal
npx create-nx-workspace nx-storybook --preset=angular
cd nx-storybook
ng generate lib ui
ng generate component atoms/card --project=ui
npm i -D @nrwl/storybook
ng generate storybook-configuration ui
ng run ui:storybook
```

### Environment
```
  Node : 14.14.0
  OS   : darwin x64
  npm  : 6.14.10
  
  nx : Not Found
  @nrwl/angular : 11.0.4
  @nrwl/cli : 11.0.4
  @nrwl/cypress : 11.0.4
  @nrwl/devkit : 11.0.4
  @nrwl/eslint-plugin-nx : 11.0.4
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.4
  @nrwl/linter : 11.0.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.4
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.4
  typescript : 4.0.5
```

_package.json_
```
{
  "name": "nx-storybook",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points",
    "nx": "nx",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "nx workspace-lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-generator": "nx workspace-generator",
    "dep-graph": "nx dep-graph",
    "help": "nx help"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^11.0.0",
    "@angular/common": "^11.0.0",
    "@angular/compiler": "^11.0.0",
    "@angular/core": "^11.0.0",
    "@angular/forms": "^11.0.0",
    "@angular/platform-browser": "^11.0.0",
    "@angular/platform-browser-dynamic": "^11.0.0",
    "@angular/router": "^11.0.0",
    "@nrwl/angular": "11.0.4",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.1",
    "@angular-eslint/eslint-plugin": "0.8.0-beta.1",
    "@angular-eslint/eslint-plugin-template": "0.8.0-beta.1",
    "@angular-eslint/template-parser": "0.8.0-beta.1",
    "@angular/cli": "~11.0.0",
    "@angular/compiler-cli": "^11.0.0",
    "@angular/language-service": "^11.0.0",
    "@nrwl/cli": "11.0.4",
    "@nrwl/cypress": "11.0.4",
    "@nrwl/eslint-plugin-nx": "11.0.4",
    "@nrwl/jest": "11.0.4",
    "@nrwl/storybook": "^11.1.5",
    "@nrwl/tao": "11.0.4",
    "@nrwl/workspace": "11.0.4",
    "@storybook/addon-knobs": "^6.1.11",
    "@storybook/angular": "^6.1.11",
    "@types/jest": "26.0.8",
    "@types/node": "12.12.38",
    "@types/webpack": "4.41.21",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.3.0",
    "codelyzer": "^6.0.0",
    "cypress": "^5.5.0",
    "dotenv": "6.2.0",
    "eslint": "7.10.0",
    "eslint-config-prettier": "6.0.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jest": "26.2.2",
    "jest-preset-angular": "8.3.1",
    "prettier": "2.1.2",
    "ts-jest": "26.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "~4.0.3"
  }
}
```

**Comment by juristr** [comment]
Hey @ChazUK! thx for reporting this.

I tried a couple of variations to reproduce the issue but wasn't able to. I'm on the same environment as you (even used ur package.json), but no luck. Works as expected on my side.

Could you try again? Or push up some reproduction repository where I can reproduce it?

**Comment by ChazUK** [comment]
I've just grabbed another laptop and it's working fine on there for some reason. Is there an easy way to share my package-lock.json?

**Comment by ChazUK** [comment]
Created a gist for the package-lock.json https://gist.github.com/ChazUK/0637b936708b2566c4dbc3537df5893b

**Comment by juristr** [comment]
Unfortunately if I use your package-lock it fails during installation. I'm getting integrity issues

![image](https://user-images.githubusercontent.com/542458/105527818-77f86b00-5ce4-11eb-836a-37ac39de57af.png)

but at this point, could you try deleting ur package-lock.json and re-installing node modules to see whether the issue vanishes. Also, maybe try updating to our latest v11.

**Comment by ChazUK** [comment]
Does `npx create-nx-workspace nx-storybook --preset=angular` not use the latest version?

Annoyingly I'm using an alternative secure registry, I've checked all the packages versions etc and have imported them. Ran npm install and comparing the versions and there still seems to be an issue. I'll close this ticket as I don't think it's directly related to Nx or Storybook.

Sorry for wasting your time :(
