### ISSUE TITLE
Failure on new project - Dependency resolution errors with angular template in npx create-nx-workspace

### ISSUE THREAD

**Issue by bmcilw1** [nrwl/nx#4596]
## Current Behavior

npx create-nx-workspace is throwing dependency resolution errors with angular cli with the angular template. Seems like angular-cli depends on an older version of typescript.

## Expected Behavior

npx create-nx-workspace should not throw errors when used.

## Steps to Reproduce

```bash
mkdir nx-ng-sls
cd nx-ng-sls 
npx create-nx-workspace test --preset=angular --nx-cloud=false --linter=eslint --style=css --appName=testapp
```

### Failure Logs

```text
npx create-nx-workspace test --preset=angular --nx-cloud=false --linter=eslint --style=css --appName=testapp
Creating a sandbox with Nx...
new test --preset=angular --no-nxCloud --linter=eslint --style=css --appName=testapp --no-interactive --collection=@nrwl/workspace
✔ Packages installed successfully.
⠼ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@0.0.0
npm ERR! Found: typescript@4.1.3
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">=4.0 <4.2" from @angular/compiler-cli@11.1.0
npm ERR!   node_modules/@angular/compiler-cli
npm ERR!     peer @angular/compiler-cli@"^11.0.0" from @angular-devkit/build-angular@0.1100.7
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"~4.0.0" from @angular-devkit/build-angular@0.1100.7
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/brianmcilwain/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brianmcilwain/.npm/_logs/2021-01-22T23_11_39_701Z-debug.log
✖ Package install failed, see above.
UnsuccessfulWorkflowExecution [Error]: Workflow did not execute successfully.
    at ChildProcess.<anonymous> (/Users/brianmcilwain/source/nx-ng-sls/test/node_modules/@angular-devkit/schematics/tasks/package-manager/executor.js:109:31)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)
The generator workflow failed. See above.
npm ERR! code 1
npm ERR! path /Users/brianmcilwain/source/nx-ng-sls/test
npm ERR! command failed
npm ERR! command sh -c ng g @nrwl/workspace:preset --name=testapp --style=css --linter=eslint --npmScope=test --preset=angular --cli=ng --interactive=false

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brianmcilwain/.npm/_logs/2021-01-22T23_11_39_774Z-debug.log
Error: Workspace creation failed, see above.
    at ChildProcess.<anonymous> (/private/var/folders/r8/5tt87lwn71z4679z4gkkt6880000gn/T/tmp-5283g51nhTrINIGc/node_modules/@nrwl/workspace/src/schematics/new/new.js:71:39)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
Workspace creation failed, see above.
npm ERR! code 1
npm ERR! path /private/var/folders/r8/5tt87lwn71z4679z4gkkt6880000gn/T/tmp-5283g51nhTrINIGc
npm ERR! command failed
npm ERR! command sh -c tao new test --preset=angular --no-nxCloud --linter=eslint --style=css --appName=testapp --no-interactive --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot=/Users/brianmcilwain/source/nx-ng-sls

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brianmcilwain/.npm/_logs/2021-01-22T23_11_39_831Z-debug.log
node:child_process:680
    err = new Error(msg);
          ^

Error: Command failed: npx tao new test --preset=angular --no-nxCloud --linter=eslint --style=css --appName=testapp --no-interactive --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot="/Users/brianmcilwain/source/nx-ng-sls"
    at checkExecSyncError (node:child_process:680:11)
    at Object.execSync (node:child_process:717:15)
    at createApp (/Users/brianmcilwain/.npm/_npx/d2207cf76adb22dc/node_modules/create-nx-workspace/bin/create-nx-workspace.js:373:21)
    at /Users/brianmcilwain/.npm/_npx/d2207cf76adb22dc/node_modules/create-nx-workspace/bin/create-nx-workspace.js:92:29 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5286,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /Users/brianmcilwain/source/nx-ng-sls
npm ERR! command failed
npm ERR! command sh -c create-nx-workspace test --preset=angular --nx-cloud=false --linter=eslint --style=css --appName=testapp

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brianmcilwain/.npm/_logs/2021-01-22T23_11_39_893Z-debug.log

```

### Environment

```text
nx report

>  NX  Report complete - copy this into the issue template

  Node : 15.5.1
  OS   : darwin x64
  npm  : 7.3.0
  
  nx : Not Found
  @nrwl/angular : 11.1.2
  @nrwl/cli : 11.1.2
  @nrwl/cypress : 11.1.2
  @nrwl/devkit : 11.1.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.2
  @nrwl/linter : 11.1.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.2
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.2
  typescript : 4.0.5

```

**Comment by clovergaze** [comment]
I also get a dependency error doing just `npm install`.

```stacktrace
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xyz@0.1.0
npm ERR! Found: @angular/compiler@11.0.9
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"~11.0.8" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"11.1.0" from @angular/compiler-cli@11.1.0
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   peer @angular/compiler-cli@"^11.0.0" from @angular-devkit/build-angular@0.1100.7
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/clovergaze/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/clovergaze/.npm/_logs/2021-01-24T13_05_45_642Z-debug.log
```

I do not understand where `@angular/compiler@11.0.9` comes from, in the `package.json` I use version `11.0.8`. I also do not unserstand where `peer @angular/compiler@"11.1.0" from @angular/compiler-cli@11.1.0` comes from. I am not using that versions, everything is at version `11.0.8`. I am also not using `@angular-devkit/build-angular@0.1100.7`, the `package.json` refers to version `0.1100.6`.

I do not see any relevant changes to the `package.json` in recent time and I am pretty sure this error is new. I just wanted to do a fresh installation of all dependencies today.

**Comment by mandarini** [comment]
Hi there! I could not reproduce your error, unfortunately. We do have different versions of node/npm installed, though. I see you are using the current version of node with the latest features, `15.x`. Can you try running the same commands but using the latest stable versions of node/npm?

![Screenshot 2021-01-25 at 2 03 11 PM](https://user-images.githubusercontent.com/6603745/105703589-246d6380-5f16-11eb-98b3-49f57c8cf23c.png)


![Screenshot 2021-01-25 at 2 02 52 PM](https://user-images.githubusercontent.com/6603745/105703577-1ddeec00-5f16-11eb-82b7-e88cd544c7c0.png)

**Comment by bmcilw1** [comment]
That fixes it! For those who find this later, this setup resolved the problem:

```text
nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : darwin x64
  npm  : 6.14.10
  
  nx : Not Found
  @nrwl/angular : 11.1.5
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5
```

**Comment by mandarini** [comment]
Thank you @bmcilw1 ! Yes, the stable versions of `node/npm` should do the trick! :)

**Comment by edmundo096** [comment]
Related but trying to use `nx migrate latest`.
Using npm version 7.6.0 (and probably any 7 version) gives an error about permissions on the `tao` binary, this while on Node 14.
After downgrading to npm version 6 (the latest) the command executed successfully.

So, the point is, it seems that npm 7 is not supported (somehow).
