### ISSUE TITLE
nx affected:lint throws obtuse error if tsconfig is not strict json

### ISSUE THREAD

**Issue by miloofcroton** [nrwl/nx#4685]
## Current Behavior

I left a trailing comma in an array in my root tsconfig file, which did not throw an error in VSCode. Upon running `nx affected:lint`, I get weird error messages that don't help me.

## Expected Behavior

tsconfigs don't technically have to be simple JSON files. They are able to have comments normally. They can have trailing commas after every value in an array. Either `nx affected:lint` should be able to use it successfully, or it should throw a useful error.

## Steps to Reproduce

Create a valid tsconfig but invalid JSON file, then run nx affected:lint.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
SyntaxError: Unexpected token ] in JSON at position 446
    at JSON.parse (<anonymous>)
    at Object.parseJsonWithComments (<project_dir>/node_modules/@nrwl/workspace/src/utils/fileutils.js:44:17)
    at new TargetProjectLocator (<project_dir>/node_modules/@nrwl/workspace/src/core/target-project-locator.js:22:46)
    at buildExplicitTypeScriptDependencies (<project_dir>/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:8:34)
    at <project_dir>/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:60:41
    at Array.forEach (<anonymous>)
    at buildProjectGraph (<project_dir>/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:60:26)
    at Object.createProjectGraph (<project_dir>/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:40:30)
    at Object.<anonymous> (<project_dir>/node_modules/@nrwl/workspace/src/command-line/affected.js:23:46)
    at Generator.next (<anonymous>)
```

### Environment

  Node : 14.15.1
  OS   : darwin x64
  npm  : 7.4.2

  nx : 11.1.5
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.1.5
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : 11.1.5
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.1.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.1.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5

**Comment by FrozenPandaz** [comment]
Does anybody know any good libraries for parsing non-strict JSON files?

We already strip comments from the JSON using `strip-json-comments` but I found the following alternatives...

Typescript has their own parser for JSON. I'm not sure if they are following a specific spec.

JSON5 seems promising but at the moment I don't think it's a stable spec.

Does anybody else have recommendations for a json parser?
