### ISSUE TITLE
npx nx g move - TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by stianmorsund** [nrwl/nx#4687]
## Current Behavior
When running `npx nx g move --project=foo --destination=foobar` i get the following error and stacktrace:

``
TypeError: Cannot read property '1' of undefined
    at /repo/node_modules/@nrwl/devkit/src/utils/invoke-nx-generator.js:46:55
    at Generator.next (<anonymous>)
    at /repo/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/repo/node_modules/tslib/tslib.js:113:16)
    at /repo/node_modules/@nrwl/devkit/src/utils/invoke-nx-generator.js:40:39
    at MergeMapSubscriber.project (/repo/node_modules/@angular-devkit/schematics/src/rules/call.js:74:24)
    at MergeMapSubscriber._tryNext (/repo/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/repo/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/repo/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
Cannot read property '1' of undefined``

### Environment
```
  Node : 14.15.2
  OS   : darwin x64
  yarn : 1.22.4
  
  nx : Not Found
  @nrwl/angular : 11.2.7
  @nrwl/cli : 11.2.7
  @nrwl/cypress : 11.2.7
  @nrwl/devkit : 11.2.7
  @nrwl/eslint-plugin-nx : 11.2.7
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.7
  @nrwl/linter : 11.2.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.2.7
  @nrwl/react : Not Found
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 11.2.7
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.7
  typescript : 4.0.5
```

**Comment by tw2as** [comment]
I am having a similar problem when creating a new workspace

```
C:\src\nrwl11>npm i -g @nrwl/workspace

+ @nrwl/workspace@11.2.9
added 238 packages from 231 contributors in 10.364s

C:\src\nrwl11>npx create-nx-workspace --preset=angular
npx: installed 240 in 10.97s
? Workspace name (e.g., org name)     nx11test2
? Application name                    nx11app2
? Default stylesheet format           SASS(.scss)  [ http://sass-lang.com   ]
? Default linter                      TSLint [ Used by Angular CLI. Deprecated. ]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
added 240 packages from 232 contributors and audited 241 packages in 6.714s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

new nx11test2 --preset=angular --no-interactive --appName=nx11app2 --style=scss --linter=tslint --no-nxCloud --collection=@nrwl/workspace
CREATE nx11test2/nx.json
CREATE nx11test2/package.json
CREATE nx11test2/README.md
CREATE nx11test2/tools/generators/.gitkeep
CREATE nx11test2/tools/tsconfig.tools.json
CREATE nx11test2/tsconfig.base.json
CREATE nx11test2/.editorconfig
CREATE nx11test2/.gitignore
CREATE nx11test2/.prettierignore
CREATE nx11test2/.vscode/extensions.json
CREATE nx11test2/angular.json
CREATE nx11test2/.prettierrc
CREATE nx11test2/decorate-angular-cli.js
CREATE nx11test2/apps/.gitkeep
CREATE nx11test2/libs/.gitkeep
Cannot read property '1' of undefined
Workspace creation failed, see above.
(node:13104) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new nx11test2 --preset=angular --no-interactive --appName=nx11app2 --style=scss --linter=tslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot=\"C:/src/nrwl11\"
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at createApp (C:\Users\######\AppData\Roaming\npm-cache\_npx\13104\node_modules\create-nx-workspace\bin\create-nx-workspace.js:380:21)
    at C:\Users\######\AppData\Roaming\npm-cache\_npx\13104\node_modules\create-nx-workspace\bin\create-nx-workspace.js:97:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Environment**

```
OS: Win 11

C:\src\nrwl11>node -v
v12.18.1

C:\src\nrwl11>npm -v
6.14.5
```

**Comment by stianmorsund** [comment]
This is now working for me after upgrading to 11.2.10.

**Comment by FrozenPandaz** [comment]
> This is now working for me after upgrading to 11.2.10.

Awesome, closing this issue then.

There were some refactors that made this issue go away.

I'm not sure if https://github.com/nrwl/nx/pull/4675 is still needed?

If it is, can we open another issue with a reproduction of the issue that it solves please?
