### ISSUE TITLE
Error: Cannot find module '@nrwl/cypress/plugins/preprocessor'

### ISSUE THREAD

**Issue by hadrien-toma** [nrwl/nx#4704]
## Current Behavior

Unability to run Cypress tests from official Cypress Docker image.

### Underlying need

Managing Cypress installations/configurations on CI is not an "out of the box" feature and could even be quite cumbersome (at least it was in my cases) so if it would be possible to simply use their official "included" image, it would be nice: nothing to install, no binaries nor custom Docker image to store: simply target an Nx project which is an e2e one, mount it in the container and here it goes!

## Expected Behavior
Ability to successfully run the tests.

## Steps to Reproduce
In order to reproduce the issue, you can use the following bash script:

```bash
#!/usr/bin/env bash

hereDir=$(dirname "${0}" | while read -r a; do cd "${a}" && pwd && break; done )

startDateAsS=$(date +%s)

workspaceDir="${hereDir}/tmp/attempt-${startDateAsS}"
workspaceName="workspace"
baseHref="/frontend/browser/"
cypressIncludedVersion="3.2.0"
nodeVersion="latest"
createNxWorkspaceVersion="latest"
nginxVersion="latest"

echo "workspaceDir=${workspaceDir}"
echo "workspaceName=${workspaceName}"
echo "baseHref=${baseHref}"
echo "cypressIncludedVersion=${cypressIncludedVersion}"
echo "nodeVersion=${nodeVersion}"
echo "createNxWorkspaceVersion=${createNxWorkspaceVersion}"
echo "nginxVersion=${nginxVersion}"

mkdir \
	--parents \
	"${workspaceDir}"

createContainerName="nx"

docker stop "${createContainerName}"
docker rm "${createContainerName}"

docker run \
	--name "${createContainerName}" \
	--user node \
	-v ${workspaceDir}:/home/node/workspace-dir \
	node:${nodeVersion} \
	/bin/bash -c "
		cd /home/node/workspace-dir \
		&& \
		npx create-nx-workspace@${createNxWorkspaceVersion} \
				${workspaceName} \
					--preset=empty \
					--cli=nx \
					--interactive=false \
					--nx-cloud=false \
					--skip-git \
		&& \
		cd /home/node/workspace-dir/${workspaceName} \
		&& \
		yarn add \
			--dev \
				@nrwl/angular \
				@nrwl/cypress \
		&& \
		yarn run nx generate \
			@nrwl/angular:application \
				--name=frontend  \
				--style=scss \
				--routing=true \
		&& \
		yarn run nx report \
	"

e2eContainerName="cypress"

docker stop "${e2eContainerName}"
docker rm "${e2eContainerName}"

docker run \
	--name "${e2eContainerName}" \
	--interactive \
	--tty \
	--entrypoint=cypress \
	-w /e2e \
	-v ${workspaceDir}/${workspaceName}/apps/frontend-e2e:/e2e \
	cypress/included:${cypressIncludedVersion} \
		run
```

### Failure Logs

```bash
workspaceDir=/home/hadrien_toma_1/gitlab/bashroom-devs/monorepo/scripts/monorepo-builder/issue/tmp/attempt-1612448724
workspaceName=workspace
baseHref=/frontend/browser/
cypressIncludedVersion=3.2.0
nodeVersion=latest
createNxWorkspaceVersion=latest
nginxVersion=latest
nx
nx
npx: installed 240 in 26.31s
Creating a sandbox with Nx...
added 240 packages from 232 contributors and audited 241 packages in 14.805s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

new workspace --preset=empty --no-interactive --no-nxCloud --skipGit --appName= --linter=eslint --collection=@nrwl/workspace
CREATE workspace/README.md
CREATE workspace/.editorconfig
CREATE workspace/.gitignore
CREATE workspace/.prettierignore
CREATE workspace/.vscode/extensions.json
CREATE workspace/workspace.json
CREATE workspace/nx.json
CREATE workspace/package.json
CREATE workspace/tools/generators/.gitkeep
CREATE workspace/tools/tsconfig.tools.json
CREATE workspace/tsconfig.base.json
CREATE workspace/.prettierrc
CREATE workspace/apps/.gitkeep
CREATE workspace/libs/.gitkeep
npm notice created a lockfile as package-lock.json. You should commit this file.
added 249 packages from 235 contributors and audited 251 packages in 16.289s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


———————————————————————————————————————————————


>  NX   NOTE  Nx CLI is not installed globally.

  This means that you might have to use "yarn nx" or "npm nx" to execute commands in the workspace.
  Run "yarn global add nx" or "npm install -g nx" to be able to execute command directly.

yarn add v1.22.5
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning @nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning @nrwl/angular > @nrwl/cypress > ts-loader > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @nrwl/angular > @nrwl/cypress > ts-loader > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@nrwl/angular > jasmine-marbles@0.6.0" has unmet peer dependency "rxjs@^6.4.0".
warning " > @nrwl/cypress@11.2.10" has unmet peer dependency "cypress@>= 3 < 7".
warning "@nrwl/cypress > @cypress/webpack-preprocessor@4.1.5" has unmet peer dependency "webpack@^4.18.1".
warning "@nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
warning " > @nrwl/cypress@11.2.10" has unmet peer dependency "cypress@>= 3 < 7".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 317 new dependencies.
info Direct dependencies
├─ @nrwl/angular@11.2.10
├─ @nrwl/cypress@11.2.10
├─ @nrwl/workspace@11.2.10
├─ @types/node@12.12.38
├─ prettier@2.2.1
├─ ts-node@9.1.1
└─ typescript@4.0.5
info All dependencies
├─ @angular-devkit/architect@0.1100.7
├─ @angular-devkit/schematics@11.0.7
├─ @babel/core@7.12.13
├─ @babel/helper-builder-binary-assignment-operator-visitor@7.12.13
├─ @babel/helper-compilation-targets@7.12.13
├─ @babel/helper-explode-assignable-expression@7.12.13
├─ @babel/helper-get-function-arity@7.12.13
├─ @babel/helper-hoist-variables@7.12.13
├─ @babel/helper-wrap-function@7.12.13
├─ @babel/helpers@7.12.13
├─ @babel/highlight@7.12.13
├─ @babel/plugin-proposal-async-generator-functions@7.12.13
├─ @babel/plugin-proposal-class-properties@7.12.13
├─ @babel/plugin-proposal-dynamic-import@7.12.1
├─ @babel/plugin-proposal-export-namespace-from@7.12.13
├─ @babel/plugin-proposal-json-strings@7.12.13
├─ @babel/plugin-proposal-logical-assignment-operators@7.12.13
├─ @babel/plugin-proposal-nullish-coalescing-operator@7.12.13
├─ @babel/plugin-proposal-numeric-separator@7.12.13
├─ @babel/plugin-proposal-object-rest-spread@7.12.13
├─ @babel/plugin-proposal-optional-catch-binding@7.12.13
├─ @babel/plugin-proposal-optional-chaining@7.12.13
├─ @babel/plugin-proposal-private-methods@7.12.13
├─ @babel/plugin-proposal-unicode-property-regex@7.12.13
├─ @babel/plugin-syntax-class-properties@7.12.13
├─ @babel/plugin-syntax-top-level-await@7.12.13
├─ @babel/plugin-transform-arrow-functions@7.12.13
├─ @babel/plugin-transform-async-to-generator@7.12.13
├─ @babel/plugin-transform-block-scoped-functions@7.12.13
├─ @babel/plugin-transform-block-scoping@7.12.13
├─ @babel/plugin-transform-classes@7.12.13
├─ @babel/plugin-transform-computed-properties@7.12.13
├─ @babel/plugin-transform-destructuring@7.12.13
├─ @babel/plugin-transform-dotall-regex@7.12.13
├─ @babel/plugin-transform-duplicate-keys@7.12.13
├─ @babel/plugin-transform-exponentiation-operator@7.12.13
├─ @babel/plugin-transform-for-of@7.12.13
├─ @babel/plugin-transform-function-name@7.12.13
├─ @babel/plugin-transform-literals@7.12.13
├─ @babel/plugin-transform-member-expression-literals@7.12.13
├─ @babel/plugin-transform-modules-amd@7.12.13
├─ @babel/plugin-transform-modules-commonjs@7.12.13
├─ @babel/plugin-transform-modules-systemjs@7.12.13
├─ @babel/plugin-transform-modules-umd@7.12.13
├─ @babel/plugin-transform-named-capturing-groups-regex@7.12.13
├─ @babel/plugin-transform-new-target@7.12.13
├─ @babel/plugin-transform-object-super@7.12.13
├─ @babel/plugin-transform-property-literals@7.12.13
├─ @babel/plugin-transform-regenerator@7.12.13
├─ @babel/plugin-transform-reserved-words@7.12.13
├─ @babel/plugin-transform-shorthand-properties@7.12.13
├─ @babel/plugin-transform-spread@7.12.13
├─ @babel/plugin-transform-sticky-regex@7.12.13
├─ @babel/plugin-transform-template-literals@7.12.13
├─ @babel/plugin-transform-typeof-symbol@7.12.13
├─ @babel/plugin-transform-unicode-escapes@7.12.13
├─ @babel/plugin-transform-unicode-regex@7.12.13
├─ @babel/preset-env@7.12.13
├─ @babel/preset-modules@0.1.4
├─ @babel/runtime@7.12.13
├─ @nrwl/angular@11.2.10
├─ @nrwl/cypress@11.2.10
├─ @nrwl/workspace@11.2.10
├─ @schematics/angular@11.0.7
├─ @types/istanbul-lib-coverage@2.0.3
├─ @types/istanbul-lib-report@3.0.0
├─ @types/istanbul-reports@3.0.0
├─ @types/json-schema@7.0.7
├─ @types/json5@0.0.29
├─ @types/node@12.12.38
├─ @types/normalize-package-data@2.4.0
├─ @types/yargs-parser@20.2.0
├─ @types/yargs@15.0.13
├─ ajv-keywords@3.5.2
├─ ajv@6.12.6
├─ ansi-escapes@3.2.0
├─ anymatch@3.1.1
├─ arg@4.1.3
├─ argparse@1.0.10
├─ arr-flatten@1.1.0
├─ assign-symbols@1.0.0
├─ async@0.9.2
├─ atob@2.1.2
├─ axios@0.21.1
├─ babel-code-frame@6.26.0
├─ babel-loader@8.2.2
├─ balanced-match@1.0.0
├─ base@0.11.2
├─ big.js@5.2.2
├─ binary-extensions@2.2.0
├─ bluebird@3.7.1
├─ brace-expansion@1.1.11
├─ braces@3.0.2
├─ browserslist@4.16.3
├─ buffer-from@1.1.1
├─ cache-base@1.0.1
├─ camelcase@5.3.1
├─ caniuse-lite@1.0.30001183
├─ chardet@0.7.0
├─ chokidar@3.5.1
├─ ci-info@2.0.0
├─ class-utils@0.3.6
├─ cli-cursor@2.1.0
├─ cli-spinners@2.5.0
├─ cli-width@2.2.1
├─ cliui@6.0.0
├─ clone@1.0.4
├─ collection-visit@1.0.0
├─ color-convert@1.9.3
├─ color-name@1.1.3
├─ colorette@1.2.1
├─ commondir@1.0.1
├─ concat-map@0.0.1
├─ convert-source-map@1.7.0
├─ copy-descriptor@0.1.1
├─ core-js-compat@3.8.3
├─ core-util-is@1.0.2
├─ cosmiconfig@4.0.0
├─ create-require@1.1.1
├─ cross-spawn@6.0.5
├─ debug@2.6.9
├─ decode-uri-component@0.2.0
├─ defaults@1.0.3
├─ diff@4.0.2
├─ ejs@3.1.5
├─ electron-to-chromium@1.3.653
├─ emoji-regex@8.0.0
├─ emojis-list@3.0.0
├─ errno@0.1.8
├─ es-abstract@1.18.0-next.2
├─ es-to-primitive@1.2.1
├─ escalade@3.1.1
├─ escape-string-regexp@1.0.5
├─ esprima@4.0.1
├─ esutils@2.0.3
├─ expand-brackets@2.1.4
├─ external-editor@3.1.0
├─ extglob@2.0.4
├─ fast-deep-equal@3.1.3
├─ fast-json-stable-stringify@2.1.0
├─ figures@2.0.0
├─ filelist@1.0.1
├─ fill-range@7.0.1
├─ find-cache-dir@3.3.1
├─ find-up@4.1.0
├─ flat@5.0.2
├─ follow-redirects@1.13.2
├─ for-in@1.0.2
├─ fs.realpath@1.0.0
├─ gensync@1.0.0-beta.2
├─ get-caller-file@2.0.5
├─ get-value@2.0.6
├─ glob-parent@5.1.1
├─ glob@7.1.4
├─ has-ansi@2.0.0
├─ has-flag@4.0.0
├─ has-value@1.0.0
├─ hosted-git-info@2.8.8
├─ iconv-lite@0.4.24
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ is-accessor-descriptor@1.0.0
├─ is-arrayish@0.2.1
├─ is-binary-path@2.1.0
├─ is-callable@1.2.3
├─ is-ci@2.0.0
├─ is-core-module@2.2.0
├─ is-data-descriptor@1.0.0
├─ is-date-object@1.0.2
├─ is-descriptor@1.0.2
├─ is-directory@0.3.1
├─ is-extglob@2.1.1
├─ is-fullwidth-code-point@3.0.0
├─ is-glob@4.0.1
├─ is-interactive@1.0.0
├─ is-negative-zero@2.0.1
├─ is-plain-object@2.0.4
├─ is-regex@1.1.2
├─ is-symbol@1.0.3
├─ is-windows@1.0.2
├─ is-wsl@1.1.0
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ jake@10.8.2
├─ jasmine-marbles@0.6.0
├─ jest-pnp-resolver@1.2.2
├─ jest-resolve@26.6.2
├─ jest-util@26.6.2
├─ js-tokens@3.0.2
├─ js-yaml@3.14.1
├─ jsesc@2.5.2
├─ json-parse-better-errors@1.0.2
├─ json-parse-even-better-errors@2.3.1
├─ json-schema-traverse@0.4.1
├─ jsonc-parser@2.3.1
├─ jsonfile@4.0.0
├─ kind-of@3.2.2
├─ lines-and-columns@1.1.6
├─ load-json-file@4.0.0
├─ loader-utils@1.4.0
├─ locate-path@5.0.0
├─ log-symbols@4.0.0
├─ magic-string@0.25.7
├─ make-dir@3.1.0
├─ make-error@1.3.6
├─ map-visit@1.0.0
├─ memory-fs@0.5.0
├─ memorystream@0.3.1
├─ microevent.ts@0.1.1
├─ micromatch@3.1.10
├─ mimic-fn@1.2.0
├─ minimist@1.2.5
├─ mixin-deep@1.3.2
├─ ms@2.0.0
├─ mute-stream@0.0.7
├─ nanomatch@1.2.13
├─ nice-try@1.0.5
├─ node-releases@1.1.70
├─ normalize-package-data@2.5.0
├─ normalize-path@3.0.0
├─ npm-run-all@4.1.5
├─ object-copy@0.1.0
├─ object-inspect@1.9.0
├─ object.assign@4.1.2
├─ onetime@2.0.1
├─ opn@5.5.0
├─ ora@5.1.0
├─ os-tmpdir@1.0.2
├─ p-limit@2.3.0
├─ p-locate@4.1.0
├─ p-try@2.2.0
├─ pascalcase@0.1.1
├─ path-exists@4.0.0
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ path-type@3.0.0
├─ picomatch@2.2.2
├─ pidtree@0.3.1
├─ pkg-dir@4.2.0
├─ posix-character-classes@0.1.1
├─ prettier@2.2.1
├─ process-nextick-args@2.0.1
├─ prr@1.0.1
├─ punycode@2.1.1
├─ read-pkg-up@7.0.1
├─ read-pkg@3.0.0
├─ readable-stream@2.3.7
├─ readdirp@3.5.0
├─ regenerate-unicode-properties@8.2.0
├─ regenerator-runtime@0.13.7
├─ regenerator-transform@0.14.5
├─ regexpu-core@4.7.1
├─ regjsgen@0.5.2
├─ regjsparser@0.6.7
├─ repeat-element@1.1.3
├─ require-directory@2.1.1
├─ require-from-string@2.0.2
├─ require-main-filename@2.0.0
├─ resolve-url@0.2.1
├─ resolve@1.19.0
├─ restore-cursor@2.0.0
├─ ret@0.1.15
├─ run-async@2.4.1
├─ rxjs-for-await@0.0.2
├─ safe-buffer@5.1.2
├─ safer-buffer@2.1.2
├─ schema-utils@2.7.1
├─ set-blocking@2.0.0
├─ set-value@2.0.1
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ shell-quote@1.7.2
├─ slash@3.0.0
├─ snapdragon-node@2.1.1
├─ snapdragon-util@3.0.1
├─ source-map-resolve@0.5.3
├─ source-map-support@0.5.19
├─ source-map-url@0.4.1
├─ sourcemap-codec@1.4.8
├─ spdx-correct@3.1.1
├─ spdx-exceptions@2.3.0
├─ split-string@3.1.0
├─ sprintf-js@1.0.3
├─ static-extend@0.1.2
├─ string_decoder@1.1.1
├─ string-width@4.2.0
├─ string.prototype.padend@3.1.1
├─ string.prototype.trimend@1.0.3
├─ string.prototype.trimstart@1.0.3
├─ supports-color@7.2.0
├─ through@2.3.8
├─ to-fast-properties@2.0.0
├─ to-object-path@0.3.0
├─ to-regex-range@5.0.1
├─ ts-node@9.1.1
├─ tsconfig-paths@3.9.0
├─ type-fest@0.8.1
├─ typescript@4.0.5
├─ unicode-canonical-property-names-ecmascript@1.0.4
├─ unicode-match-property-ecmascript@1.0.4
├─ unicode-match-property-value-ecmascript@1.2.0
├─ unicode-property-aliases-ecmascript@1.1.0
├─ union-value@1.0.1
├─ universalify@0.1.2
├─ unset-value@1.0.0
├─ uri-js@4.4.1
├─ urix@0.1.0
├─ use@3.1.1
├─ util-deprecate@1.0.2
├─ validate-npm-package-license@3.0.4
├─ wcwidth@1.0.1
├─ which-module@2.0.0
├─ which@1.3.1
├─ worker-rpc@0.1.1
├─ wrap-ansi@6.2.0
├─ y18n@4.0.1
└─ yn@3.1.1
Done in 37.74s.
yarn run v1.22.5
$ nx generate @nrwl/angular:application --name=frontend --style=scss --routing=true
- Installing packages (yarn)...
✔ Packages installed successfully.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
$ ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
$ ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
CREATE jest.config.js
CREATE jest.preset.js
CREATE apps/frontend/tsconfig.editor.json
CREATE apps/frontend/tsconfig.json
CREATE apps/frontend/src/favicon.ico
CREATE apps/frontend/.browserslistrc
CREATE apps/frontend/tsconfig.app.json
CREATE apps/frontend/src/index.html
CREATE apps/frontend/src/main.ts
CREATE apps/frontend/src/polyfills.ts
CREATE apps/frontend/src/styles.scss
CREATE apps/frontend/src/assets/.gitkeep
CREATE apps/frontend/src/environments/environment.prod.ts
CREATE apps/frontend/src/environments/environment.ts
CREATE apps/frontend/src/app/app.module.ts
CREATE apps/frontend/src/app/app.component.scss
CREATE apps/frontend/src/app/app.component.html
CREATE apps/frontend/src/app/app.component.spec.ts
CREATE apps/frontend/src/app/app.component.ts
CREATE .eslintrc.json
CREATE apps/frontend/.eslintrc.json
CREATE apps/frontend/jest.config.js
CREATE apps/frontend/src/test-setup.ts
CREATE apps/frontend/tsconfig.spec.json
CREATE apps/frontend-e2e/cypress.json
CREATE apps/frontend-e2e/src/fixtures/example.json
CREATE apps/frontend-e2e/src/integration/app.spec.ts
CREATE apps/frontend-e2e/src/plugins/index.js
CREATE apps/frontend-e2e/src/support/app.po.ts
CREATE apps/frontend-e2e/src/support/commands.ts
CREATE apps/frontend-e2e/src/support/index.ts
CREATE apps/frontend-e2e/tsconfig.e2e.json
CREATE apps/frontend-e2e/tsconfig.json
CREATE apps/frontend-e2e/.eslintrc.json
UPDATE workspace.json
UPDATE package.json
UPDATE .vscode/extensions.json
UPDATE nx.json
Done in 111.19s.
yarn run v1.22.5
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.9.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : 11.2.10
  @nrwl/cli : 11.2.10
  @nrwl/cypress : 11.2.10
  @nrwl/devkit : 11.2.10
  @nrwl/eslint-plugin-nx : 11.2.10
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.10
  @nrwl/linter : 11.2.10
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.10
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.10
  typescript : 4.0.5

Done in 2.22s.
cypress
cypress
The plugins file is missing or invalid.

Your `pluginsFile` is set to `/e2e/src/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js` or `.coffee` file.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

 Error: Cannot find module '@nrwl/cypress/plugins/preprocessor'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/e2e/src/plugins/index.js:14:34)
    at Object.<anonymous> (/e2e/src/plugins/index.js:24:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:118:15)
    at Object.<anonymous> (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js:14:25)
    at Object.<anonymous> (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js:16:3)
```

### Environment

```bash
>  NX  Report complete - copy this into the issue template

  Node : 14.9.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : 11.2.10
  @nrwl/cli : 11.2.10
  @nrwl/cypress : 11.2.10
  @nrwl/devkit : 11.2.10
  @nrwl/eslint-plugin-nx : 11.2.10
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.10
  @nrwl/linter : 11.2.10
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.10
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.10
  typescript : 4.0.5
```

### Notes

The tests successfully run using the following command, on localhost (outside of a masterized, containerized, Docker environment).
```
yarn run nx e2e \
		--project=frontend-e2e \
		--configuration=production \
		--devServerTarget='' \
		--base-url=http://localhost:4200 \
		--headless=true \
		--watch=false
```

**Comment by hadrien-toma** [comment]
I also tried to manually install `@nrwl/cypress/plugins/preprocessor` but it was not found on registry.

**Comment by steflen** [comment]
a bit hacky but this can be solved => 
1) COPY a package.json that contains the necesarry dependencies for nx (@angular/cli, @nrwl stuff, cypress, typescript, webpack, tsconfig-paths-webpack-plugin, @types/node ...), then RUN npm i
2) build your own image like that, then run this image
3) use nx as --entrypoint for docker run (the configuration for cypress can be done inside angular.json)

**Comment by FrozenPandaz** [comment]
Hey, I noticed a few issues:

1. >-v ${workspaceDir}/${workspaceName}/apps/frontend-e2e:/e2e
  a. This only mounts the e2e project and not the full workspace (including `node_modules`. You'd want to mount `${workspaceDir}/${workspaceName}`
2. You use `cypress run` instead of `nx e2e`.
  a. This won't work right now because we currently read the `tsConfig` from the angular.json config.

**Comment by hadrien-toma** [comment]
Thank you both for your feedbacks.

@steflen this is what I currently do to workaround the fact that using the official Cypress docker image is not supported but this imply to maintain code to build the image, the image and its release/deployment lifecycle etc. This would be much more easy and clean to simply be able to use the official Docker image built for it.

@FrozenPandaz 
1. I try to follow the instructions on [this page](https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/) of the Cypress website (for what I understand, they only mount the e2e folder).
2. I run the official docker image of Cypress which is not aware of Nx, the executable they provide are the cypress commands.
  a. I see, thank you. Maybe I can configure the Cypress image to mount the correct tsConfig in the expected place for Cypress? Do you have any key for going this way? I know I can build another image the Cypress one and install nx and other dependencies over it but this is what I would like to avoid to reduce technical debt to its minimum...

**Comment by hadrien-toma** [comment]
:tada: As I explained [here](https://github.com/cypress-io/cypress/issues/15029):

I am now able to use the cypress/included image only as I wanted. What I have done:

- Use --entrypoint docker run argument in order to set it to /bin/bash and bypass the default cypress command execution
- Mount the Nx workspace in the container
- Set the Docker container "working directory" to the Nx workspace
- Execute the standard npm run nx e2e command inside the container

Being able to run E2E tests with `cypress/included` image, using same command on local machine than in CI is soooo nice (no pain induced by the need of propagating the Cypress binary or its installations files, nor to maintain the sharing of this binary across developers teams etc.).

Nx is so amazing :heart_eyes:, thank you very much Nrwl team for developing it (and especially @FrozenPandaz for joining the conversation, your feedback helped me to rethink the problem and to write the correct Docker commands, thank you very much!).
