### ISSUE TITLE
Next plugin is importing a function from a wrong path

### ISSUE THREAD

**Issue by rcanessa89** [nrwl/nx#4731]
## Current Behavior
Project generated with Next plugin is trowing an error when I try to use `serve` comand

Looking in to `node_modules/@nrwl/next/plugins/with-nx.js` in the line 2 `const { appRootPath } = require('@nrwl/workspace/src/utilities/app-root');` but should be `const { appRootPath } = require('@nrwl/workspace/src/utils/app-root');`

## Expected Behavior
Run the server for the Next project

## Steps to Reproduce
- run `npm install @nrwl/next`
- run `nx g @nrwl/next:app myapp`
- run `nx serve myapp`

### Failure Logs
```
Cannot find module '@nrwl/workspace/src/utilities/app-root'
Require stack:
- C:\Users\rcane\Desktop\projects\cr-lottery\apps\web-site\next.config.js
- C:\Users\rcane\Desktop\projects\cr-lottery\node_modules\next\dist\next-server\server\config.js
- C:\Users\rcane\Desktop\projects\cr-lottery\node_modules\@nrwl\next\src\utils\config.js
- C:\Users\rcane\Desktop\projects\cr-lottery\node_modules\@nrwl\next\src\builders\server\server.impl.js
- C:\Users\rcane\Desktop\projects\cr-lottery\node_modules\@nrwl\tao\src\shared\workspace.js
- C:\Users\rcane\Desktop\projects\cr-lottery\node_modules\@nrwl\tao\src\commands\run.js
- C:\Users\rcane\Desktop\projects\cr-lottery\node_modules\@nrwl\cli\lib\run-cli.js
```

### Environment
```
Node : 14.15.3
  OS   : win32 x64
  npm  : 6.14.9

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.20
  @nrwl/cypress : 11.2.10
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : 11.0.20
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.20
  @nrwl/linter : 11.0.20
  @nrwl/nest : 11.0.20
  @nrwl/next : 11.2.10
  @nrwl/node : 11.0.20
  @nrwl/react : 11.2.10
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.20
  @nrwl/web : 11.2.10
  @nrwl/workspace : 11.0.20
  typescript : 4.0.5
  ```

**Comment by juristr** [comment]
@rcanessa89 hmm...it seems correct. I think the problem is that you have `@nrwl/next@11.2.10` but `@nrwl/workspace@11.0.20`.

Can you try to get them in sync? Either upgrade them all to the latest or downgrade `@nrwl/next` to match the `@nrwl/workspace` version :)

sorry for the trouble. Feel free to re-open if the issue persists

**Comment by parksj10** [comment]
@juristr and @rcanessa89, I can confirm this is breaking for me too. when I alter the `enforce-module-boundaries.js` to

```
const app_root_1 = require("@nrwl/workspace/src/utils/app-root");
```
it begins functioning for me (linting was breaking in my case)

**Comment by juristr** [comment]
@parksj10 make sure your `@nrwl/next` version is aligned with the `@nrwl/workspace`

**Comment by parksj10** [comment]
confirmed, already ran `nx migrate latest` and am now running the following

```
    "@nrwl/cypress": "11.2.10",
    "@nrwl/eslint-plugin-nx": "11.2.10",
    "@nrwl/jest": "11.2.10",
    "@nrwl/nest": "11.2.10",
    "@nrwl/node": "11.2.10",
    "@nrwl/react": "11.2.10",
    "@nrwl/storybook": "11.2.10",
    "@nrwl/web": "11.2.10",
    "@nrwl/workspace": "11.2.10",
    "@storybook/addon-actions": "^6.1.16",
    "@storybook/addon-backgrounds": "^6.1.16",
    "@storybook/addon-console": "^1.2.2",
    "@storybook/addon-controls": "^6.1.16",
    "@storybook/addon-docs": "^6.1.16",
    "@storybook/addon-essentials": "^6.1.15",
    "@storybook/addon-info": "^5.3.21",
```

**Comment by juristr** [comment]
Is it working now?

**Comment by parksj10** [comment]
No, it still yields errors when I have don't have the above referenced line changed to `const app_root_1 = require("@nrwl/workspace/src/utils/app-root");` 

Again, these errors only occur and prevent linting when a file shares a name (or subname) with it's parent folder, e.g. `.../svg/svgExports.tsx` yielding the following error

```
╰─ eslint /Users/josh/Code/js/reflect/apps/browser-overlay/src/components/SelectionToolTip/SelectionToolTip.tsx                                 ─╯

Oops! Something went wrong! :(

ESLint: 7.19.0

TypeError: runtime_lint_utils_1.isCircular is not a function
Occurred while linting /Users/josh/Code/js/reflect/apps/browser-overlay/src/components/SelectionToolTip/SelectionToolTip.tsx:1
    at ImportDeclaration (/Users/josh/Code/js/reflect/node_modules/@nrwl/eslint-plugin-nx/src/rules/enforce-module-boundaries.js:109:42)
    at /usr/local/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/usr/local/lib/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /usr/local/lib/node_modules/eslint/lib/linter/linter.js:952:32
    at Array.forEach (<anonymous>)
```
Linting continues as normal when I disable the `enforce-module-boundary` rule in the `.eslintrc`

**Comment by rcanessa89** [comment]
@juristr I moved the Nx versions with `nx migrate latest` and it's works

```
Node : 12.18.3
  OS   : darwin x64
  npm  : 7.5.3
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : 11.2.12
  @nrwl/next : 11.2.12
  @nrwl/node : 11.2.12
  @nrwl/react : 11.2.12
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : 11.2.12
  @nrwl/workspace : 11.2.12
  typescript : 4.0.5
```

**Comment by danieldanielecki** [comment]
In an `Angular` application though, but still I've fixed it by changing:

`"@nrwl/nx-cloud": "latest",`
to
`"@nrwl/nx-cloud": "12.2.7",`

Of course, in the `package.json`.
