### ISSUE TITLE
"contains invalid WIN#@ path characters" error with 11.2.12

### ISSUE THREAD

**Issue by cvjava** [nrwl/nx#4771]
Am having this same issue as below with 11.2.12
Cleared npm cache and tried again.
Uninstalled/Reinstalled everything - still same error.

-----------------------------------------
Windows 10 20H2 19042.746
Windows Power Shell v1.0
node v14.15.4
npm 7.5.2

```
PS D:\yananbak> npx create-nx-workspace@11.2.12
? Workspace name (e.g., org name)     sf
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building a
pps]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new sf --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE sf/nx.json
CREATE sf/package.json
CREATE sf/README.md
CREATE sf/tools/generators/.gitkeep
CREATE sf/tools/tsconfig.tools.json
CREATE sf/tsconfig.base.json
CREATE sf/.editorconfig
CREATE sf/.gitignore
CREATE sf/.prettierignore
CREATE sf/.vscode/extensions.json
CREATE sf/workspace.json
CREATE sf/.prettierrc
CREATE sf/apps/.gitkeep
CREATE sf/libs/.gitkeep
\D:\yananbak\sf contains invalid WIN32 path characters.
npm ERR! code 1
npm ERR! path C:\Users\fuxiao\AppData\Local\Temp\tmp-13320TXTHI2dmfsKg
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tao new sf --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\D:/yananbak\

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fuxiao\AppData\Local\npm-cache\_logs\2021-02-11T15_43_27_765Z-debug.log
(node:13320) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new sf --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\"D:/yananbak\"
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createApp (C:\Users\fuxiao\AppData\Local\npm-cache\_npx\7c02767d5c9c4159\node_modules\create-nx-workspace\bin\create-nx-workspace.js:380:21)
    at C:\Users\fuxiao\AppData\Local\npm-cache\_npx\7c02767d5c9c4159\node_modules\create-nx-workspace\bin\create-nx-workspace.js:97:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS D:\yananbak>
```

_Originally posted by @fxioi in https://github.com/nrwl/nx/issues/4690#issuecomment-777591305_

**Comment by cvjava** [comment]
cleared cache again.  able to create workspace in root c:\ but not in subfolder.

**Comment by fxioi** [comment]
npx create-nx-workspace@10.4.13

new version fixed.
