### ISSUE TITLE
nx@6  ng g lib output  misleading message. 

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#478]
`ng g lib` command generate misleading output:  

none of the below files are generated:

CREATE libs/socketio-plugin/src/lib/socketio-plugin.component.spec.ts (685 bytes)
CREATE libs/socketio-plugin/src/lib/socketio-plugin.component.ts (282 bytes)
CREATE libs/socketio-plugin/src/lib/socketio-plugin.service.spec.ts (423 bytes)
CREATE libs/socketio-plugin/src/lib/socketio-plugin.service.ts (143 bytes)

Env:  @nrwl/nx": "6.0.0-alpha.2, "@nrwl/schematics": "6.0.0-alpha.2"
```
ngular CLI: 6.0.1
Node: 10.1.0
OS: darwin x64
Angular: 6.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.1
@angular-devkit/build-angular      0.6.1
@angular-devkit/build-ng-packagr   0.6.1
@angular-devkit/build-optimizer    0.6.1
@angular-devkit/core               0.6.1
@angular-devkit/schematics         0.6.1
@angular/flex-layout               6.0.0-beta.15
@angular/pwa                       0.6.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.1
@schematics/angular                0.6.1
@schematics/update                 0.6.1
ng-packagr                         3.0.0-rc.5
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0
```

command:
```bash
$ ng g lib socketioPlugin --tags=public-module  --publishable=true
```
Output : 
```
CREATE libs/socketio-plugin/karma.conf.js (968 bytes)
CREATE libs/socketio-plugin/ng-package.json (186 bytes)
CREATE libs/socketio-plugin/ng-package.prod.json (147 bytes)
CREATE libs/socketio-plugin/package.json (175 bytes)
CREATE libs/socketio-plugin/src/index.ts (115 bytes)
CREATE libs/socketio-plugin/src/test.ts (700 bytes)
CREATE libs/socketio-plugin/tsconfig.lib.json (769 bytes)
CREATE libs/socketio-plugin/tsconfig.spec.json (267 bytes)
CREATE libs/socketio-plugin/tslint.json (247 bytes)
CREATE libs/socketio-plugin/src/lib/socketio-plugin.module.ts (232 bytes)
CREATE libs/socketio-plugin/src/lib/socketio-plugin.component.spec.ts (685 bytes)
CREATE libs/socketio-plugin/src/lib/socketio-plugin.component.ts (282 bytes)
CREATE libs/socketio-plugin/src/lib/socketio-plugin.service.spec.ts (423 bytes)
CREATE libs/socketio-plugin/src/lib/socketio-plugin.service.ts (143 bytes)
CREATE libs/socketio-plugin/src/lib/socketio-plugin.module.spec.ts (403 bytes)
UPDATE angular.json (6309 bytes)
UPDATE package.json (3610 bytes)
UPDATE tsconfig.json (791 bytes)
UPDATE nx.json (346 bytes)
```

**Comment by matheo** [comment]
@vsavkin the `ng-package.prod.json` is missing and `ng build my-lib-name` throws:
```
Target 'build' could not be found in project 'my-lib-name'.
Error: Target 'build' could not be found in project 'my-lib-name'.
    at Architect._getProjectTarget (node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:90:19)
    at Architect.getBuilderConfiguration (node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:97:29)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (node_modules/@angular/cli/models/architect-command.js:64:55)
    at MergeMapSubscriber._tryNext (node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:103:18)
    at TapSubscriber._next (node_modules/rxjs/internal/operators/tap.js:109:26)
    at TapSubscriber.Subscriber.next (node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (node_modules/rxjs/internal/InnerSubscriber.js:30:21)
```

**Comment by FrozenPandaz** [comment]
Fixed with https://github.com/nrwl/nx/pull/667.

@matheo This probably seems like a bug since the message was misleading, but this is intended. You should use the `--publishable` flag if you would like to publish your library.
