### ISSUE TITLE
Error: Cannot read property 'extensions' of undefined

### ISSUE THREAD

**Issue by rupeshtiwari** [nrwl/nx#4844]
I am trying to move angular library to some folder within libs. I am using nx monorepo without angular.json

## Current Behavior
Executing task: 
```
nx generate @nrwl/angular:move --destination=/libs/branding/infrastructure-essentials --projectName=branding-log --importPath=@scci-client/branding/infrastructure-essentials/log --no-interactive --dry-run 
```
TypeError: Cannot read property 'extensions' of undefined
    at MapSubscriber.project (C:\Projects\Branding-JS\scci-client\node_modules\@nrwl\angular\src\schematics\move\lib\update-module-name.js:22:25)
    at MapSubscriber._next (C:\Projects\Branding-JS\scci-client\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (C:\Projects\Branding-JS\scci-client\node_modules\rxjs\internal\Subscriber.js:66:18)
    at C:\Projects\Branding-JS\scci-client\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24       
Cannot read property 'extensions' of undefined

Terminal will be reused by tasks, press any key to close it.

## Expected Behavior
should  move angular project
## Steps to Reproduce
I have nx workspace no angular.json. And move any angular project to some folder and change the import path. 
### Failure Logs
TypeError: Cannot read property 'extensions' of undefined
    at MapSubscriber.project (C:\Projects\Branding-JS\scci-client\node_modules\@nrwl\angular\src\schematics\move\lib\update-module-name.js:22:25)
    at MapSubscriber._next (C:\Projects\Branding-JS\scci-client\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (C:\Projects\Branding-JS\scci-client\node_modules\rxjs\internal\Subscriber.js:66:18)
    at C:\Projects\Branding-JS\scci-client\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24       
Cannot read property 'extensions' of undefined

### Environment
>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : win32 x64
  npm  : 6.14.11

  nx : Not Found
  @nrwl/angular : 11.2.12
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7

**Comment by FrozenPandaz** [comment]
Sorry, that's a confusing error. The destination you provided was not what was expected.

It should be something like `branding/infrastructure-essentials`:
![image](https://user-images.githubusercontent.com/8104246/108570409-d14fbc00-72db-11eb-9e64-4bcae88be30c.png)

Those types of inputs should either be normalized or the format should be checked.

**Comment by rupeshtiwari** [comment]
@FrozenPandaz thank you so much for clarification. I will try to work on this.
