### ISSUE TITLE
No module factory available for dependency type: ContextElementDependency @nx 6

### ISSUE THREAD

**Issue by darwinyo-enterprise** [nrwl/nx#485]
last night i was update my angular app from 5 to 6. 
this is my package json

`
"@angular/cli": "6.0.1",
    "@angular-devkit/build-angular": "~0.6.1",
    "@angular/common": "6.0.1",
    "@angular/compiler": "6.0.1",
    "@angular/compiler-cli": "6.0.1",
    "@angular/core": "6.0.1",
    "@angular/platform-browser": "6.0.1",
    "@angular/platform-browser-dynamic": "6.0.1",
    "@angular/router": "6.0.1",
    "@angular/upgrade": "6.0.1",
    "@angular-devkit/schematics": "^0.6.1",
    "@angular-devkit/core": "0.6.1",
    "@angular/animations": "6.0.1",
    "@angular/cdk": "6.0.1",
    "@angular/forms": "6.0.1",
    "@angular/http": "6.0.1",
    "@angular/language-service": "6.0.1",
    "@angular/material": "6.0.1",
    "@angular/platform-server": "6.0.1",
    "@covalent/core": "^2.0.0-beta.1",
    "@ngrx/effects": "5.2.0",
    "@ngrx/router-store": "5.2.0",
    "@ngrx/schematics": "5.2.0",
    "@ngrx/store": "5.2.0",
    "@ngrx/store-devtools": "5.2.0",
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "@ngxs/devtools-plugin": "^3.0.1",
    "@ngxs/logger-plugin": "^3.0.1",
    "@ngxs/store": "^3.0.1",
    "@nrwl/nx": "6.0.0-rc.1",
    "@nrwl/schematics": "0.9.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "@types/prettier": "^1.10.0",
    "@types/yargs": "^11.0.0",
    "angular": "1.6.6",
    "app-root-path": "^2.0.1",
    "autoprefixer": "^7.2.3",
    "express": "^4.16.3",
    "jasmine": "^3.1.0",
    "circular-dependency-plugin": "^4.2.1",
    "codelyzer": "^4.0.1",
    "conventional-changelog-cli": "^1.3.21",
    "copy-webpack-plugin": "~4.4.1",
    "core-js": "^2.4.1",
    "cosmiconfig": "^4.0.0",
    "file-loader": "^1.1.5",
    "fs-extra": "5.0.0",
    "graphviz": "^0.0.8",
    "hammerjs": "^2.0.8",
    "html-webpack-plugin": "^3.2.0",
    "husky": "^0.14.3",
    "istanbul-instrumenter-loader": "^3.0.0",
    "jasmine-core": "~2.99.1",
    "jasmine-marbles": "^0.3.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "20.0.4",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-webpack": "3.0.0",
    "less-loader": "^4.0.5",
    "ng-packagr": "3.0.0-rc.2",
    "ngrx-store-freeze": "^0.2.1",
    "npm-run-all": "4.1.2",
    "opn": "^5.3.0",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.10",
    "postcss-url": "^7.1.2",
    "precise-commits": "1.0.2",
    "prettier": "1.10.2",
    "protractor": "~5.1.2",
    "raw-loader": "^0.5.1",
    "release-it": "^7.4.0",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.0.0",
    "sass-loader": "^6.0.6",
    "semver": "5.4.1",
    "strip-json-comments": "2.0.1",
    "style-loader": "^0.19.1",
    "stylus-loader": "^3.0.1",
    "tmp": "0.0.33",
    "ts-loader": "^3.2.0",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": ">=2.7.2 <2.8.0",
    "uglifyjs-webpack-plugin": "^1.1.8",
    "url-loader": "^0.6.2",
    "viz.js": "^1.8.1",
    "webpack": "^4.8.1",
    "webpack-dev-server": "^3.1.4",
    "yargs": "^11.0.0",
    "yargs-parser": "10.0.0",
    "zone.js": "^0.8.26"
`
when run ng serve error occured

 21% building modules 92/100 modules 8 active  …e\node_modules\@nrwl\nx\esm5\nrwl-nx.js× ｢wdm｣: Error: No module factory available for dependency type: ContextElementDependency
    at addDependency (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:407:12)
    at iterationOfArrayCallback (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:88:3)
    at addDependenciesBlock (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:423:5)
    at iterationOfArrayCallback (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:88:3)
    at addDependenciesBlock (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:426:5)
    at Compilation.processModuleDependencies (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:434:4)
    at afterBuild (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:556:15)
    at buildModule.err (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:600:11)
    at callback (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:358:35)
    at module.build.error (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:394:12)
    at resolveDependencies (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ContextModule.js:233:4)
    at ContextModule.result.resolveDependencies (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:476:25)
    at ContextModule.build (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ContextModule.js:158:8)
    at Compilation.buildModule (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:362:10)
    at factory.create (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:583:14)
    at hooks.afterResolve.callAsync (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ContextModuleFactory.js:150:16)
C:\Enterprise\js\enterprise.frontend.workspace\node_modules\neo-async\async.js:14
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (C:\Enterprise\js\enterprise.frontend.workspace\node_modules\neo-async\async.js:14:11)
    at C:\Enterprise\js\enterprise.frontend.workspace\node_modules\neo-async\async.js:2805:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
thanks.

**Comment by darwinyo-enterprise** [comment]
im suspecting angular cli who cause this... but not sure...

**Comment by darwinyo-enterprise** [comment]
i have fix this issue. seem like my dependencies has problem...

**Comment by dereklin** [comment]
@darwinyo-enterprise How did you fix the problem?  I am experiencing the same issue.

**Comment by SoerenAksglaede** [comment]
I ran into the same problem as well, and would like to know how you fixed it @darwinyo-enterprise

**Comment by iansamz** [comment]
That solution would be wonderful if shared

**Comment by dereklin** [comment]
As @darwinyo-enterprise reported originally, when we upgrade from 1.0.3 to 6, we have many other dependencies that are not compatible with 6.

For my project, here is the right list of dependencies for it: https://github.com/dereklin/nrwl-nx-workspace-demo/blob/feature/upgrade-nrwl-6/package.json

Your projects' dependencies might differ.

As @ThomasBurleson suggested, I had to remove package-lock.json and node_modules and reinstall everything to get things working at times.

For me, this branch is fully upgraded: https://github.com/dereklin/nrwl-nx-workspace-demo/tree/feature/upgrade-nrwl-6

**Comment by stilltrackin** [comment]
This worked for me: "@angular-devkit/build-angular": "~0.7.0-beta.2"

**Comment by tanimakar** [comment]
I am getting this issue as well. Tried deleting node_modules folder and install again. But of no help
