### ISSUE TITLE
UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token } in JSON at position 3543

### ISSUE THREAD

**Issue by VILLAN3LL3** [nrwl/nx#4855]
## Current Behavior
ng serve/ng build throws the following error immediately:

> (node:21868) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token } in JSON at position 3543
>     at JSON.parse (<anonymous>)
>     at Object.parseJsonWithComments (C:\<myproject>\node_modules\@nrwl\workspace\src\utilities\fileutils.js:44:17)
>     at new TargetProjectLocator (C:\<myproject>\node_modules\@nrwl\workspace\src\core\target-project-locator.js:22:46)
>     at buildExplicitTypeScriptDependencies (C:\<myproject>\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\explicit-project-dependencies.js:8:34)   
>     at C:\<myproject>\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:61:41
>     at Array.forEach (<anonymous>)
>     at buildProjectGraph (C:\<myproject>\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:61:26)
>     at Object.createProjectGraph (C:\<myproject>\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:40:30)
>     at Object.<anonymous> (C:\<myproject>\node_modules\@nrwl\workspace\src\command-line\run-one.js:16:46)
>     at Generator.next (<anonymous>)
> (node:21868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:21868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit 
> code.

The error still occurs after the update to version 11.3.0 and also after deleting the node_modules folder and also after deleting the package-lock.json

## Expected Behavior
No error on ng serve/build

### Environment
  Node : 12.11.0
  OS   : win32 x64
  npm  : 6.14.5

  nx : Not Found
  @nrwl/angular : 11.3.0
  @nrwl/cli : 11.3.0
  @nrwl/cypress : 11.3.0
  @nrwl/devkit : 11.3.0
  @nrwl/eslint-plugin-nx : 11.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.3.0
  @nrwl/linter : 11.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.3.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.3.0
  typescript : 4.0.5

**Comment by VILLAN3LL3** [comment]
The cause of this error was the section "angularCompilerOptions" in the tsconfig file. After moving it to tsconfig.app.json, everything works again. Issue closed.
