### ISSUE TITLE
nx v6: Could not find module "@nrwl/schematics" when creating a new workspace

### ISSUE THREAD

**Issue by juristr** [nrwl/nx#489]
Tested with both
- latest  `v6.0.0-rc.1` candidate installed globally
- build from master of this repo here

When I execute `create-nx-workspace nxv6-testapp --yarn` I get the following error

```
Could not find module "@nrwl/schematics" from "/Users/jstrumpflohner/mystuff/tests".
Error: Could not find module "@nrwl/schematics" from "/Users/jstrumpflohner/mystuff/tests".
    at Object.resolve (/Users/jstrumpflohner/mystuff/tests/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at NodeModulesEngineHost._resolvePackageJson (/Users/jstrumpflohner/mystuff/tests/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:29:21)
    at NodeModulesEngineHost._resolveCollectionPath (/Users/jstrumpflohner/mystuff/tests/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:70:40)
    at NodeModulesEngineHost.createCollectionDescription (/Users/jstrumpflohner/mystuff/tests/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:106:27)
    at SchematicEngine._createCollectionDescription (/Users/jstrumpflohner/mystuff/tests/node_modules/@angular-devkit/schematics/src/engine/engine.js:78:40)
    at SchematicEngine.createCollection (/Users/jstrumpflohner/mystuff/tests/node_modules/@angular-devkit/schematics/src/engine/engine.js:71:43)
    at Object.getCollection (/Users/jstrumpflohner/mystuff/tests/node_modules/@angular/cli/utilities/schematics.js:28:31)
    at NewCommand.getOptions (/Users/jstrumpflohner/mystuff/tests/node_modules/@angular/cli/models/schematic-command.js:194:41)
    at NewCommand.initialize (/Users/jstrumpflohner/mystuff/tests/node_modules/@angular/cli/commands/new.js:48:21)
    at Object.<anonymous> (/Users/jstrumpflohner/mystuff/tests/node_modules/@angular/cli/models/command-runner.js:87:23)
```

It looks like the `@nrwl/schematics` is being searched in the folder where I execute the `create-nx-workspace` command.

It strangely works if I clone this repo (`master`), and execute the creation of a workspace inside the Nx repo, like

```
node build/packages/schematics/bin/create-nx-workspace.js nxv6-testapp --yarn
```

Doing the same outside the Nx repo (i.e. `../nx/build/packages/.../create-nx-workspace ...`) also fails.

**Comment by bhaidar** [comment]
@juristr How is that resolved? I am facing the same issue here.
