### ISSUE TITLE
nx v6.0.0-rc.2: Cannot find module 'strip-json-comments'

### ISSUE THREAD

**Issue by NathanWalker** [nrwl/nx#492]
The following error occurs with `v6.0.0-rc.2` when creating a new workspace:
```
ng new "golocal" --collection=@nrwl/schematics
Cannot find module 'strip-json-comments'
Error: Cannot find module 'strip-json-comments'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/folders/y_/z7673yw95yz1vg297jxvp_300000gn/T/tmp-6113RIuRwKJkU6Ke/node_modules/@nrwl/schematics/src/utils/ast-utils.js:9:25)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
child_process.js:614
    throw err;
    ^

Error: Command failed: /var/folders/y_/z7673yw95yz1vg297jxvp_300000gn/T/tmp-6113RIuRwKJkU6Ke/node_modules/.bin/ng new "golocal" --skip-install --collection=@nrwl/schematics
```

@vsavkin I can help look in PR but perhaps something quick?

**Comment by FrozenPandaz** [comment]
Ah sorry, we probably need to add this as a dependency
