### ISSUE TITLE
EINVAL: invalid argument, mkdir

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#4922]
## Current Behavior

When I create empty repo, nx cli throw error: `EINVAL: invalid argument, mkdir`.
see error log below.

## Expected Behavior

nx should create an empty repo.

## Steps to Reproduce

Run the command:  `npx create-nx-workspace`  with the following inputs:
```
? Workspace name (e.g., org name)     myorg
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? Use Nx Cloud? (It's free and doesn't require registration.) No
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
λ npx create-nx-workspace
? Workspace name (e.g., org name)     myorg
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new myorg --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE myorg/nx.json
CREATE myorg/package.json
CREATE myorg/README.md
CREATE myorg/tools/generators/.gitkeep
CREATE myorg/tools/tsconfig.tools.json
CREATE myorg/tsconfig.base.json
CREATE myorg/.editorconfig
CREATE myorg/.gitignore
CREATE myorg/.prettierignore
CREATE myorg/.vscode/extensions.json
CREATE myorg/workspace.json
CREATE myorg/.prettierrc
CREATE myorg/apps/.gitkeep
CREATE myorg/libs/.gitkeep
EINVAL: invalid argument, mkdir 'C:\C:\sandbox\myorg'
node:child_process:636
    err = new Error(msg);
          ^

Error: Command failed: npx tao new myorg --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\"C:/sandbox\"
    at checkExecSyncError (node:child_process:636:11)
    at Object.execSync (node:child_process:672:15)
    at createApp (C:\Users\wizar\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:385:21)
    at C:\Users\wizar\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:98:29
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 15228,
  stdout: null,
  stderr: null
}
```

### Environment

nx - latest.
windows 10
node version: v15.0.1
npm version: 7.6.0

**Comment by bekos** [comment]
@wizardnet972 can you tell me if you use cmd, git bash, powershell etc?

**Comment by wizardnet972** [comment]
@bekos I use [cmder](https://cmder.net/) it's kind of `git bash` and windows-cmd.

**Comment by bekos** [comment]
@wizardnet972 thx for the info. Is it possible to check if you have the same error with npm@6?

**Comment by wizardnet972** [comment]
@bekos I tested it in npm@6 and it works fine.

**Comment by bekos** [comment]
@wizardnet972 thx again 👍 I will send a fix soon.

**Comment by wizardnet972** [comment]
@bekos @FrozenPandaz 
Sorry but the error still happens. see log:

```
C:\sandbox
λ npm i npm -g
C:\Users\wizar\AppData\Roaming\npm\npm -> C:\Users\wizar\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\wizar\AppData\Roaming\npm\npx -> C:\Users\wizar\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
+ npm@7.6.0
added 59 packages from 24 contributors, removed 241 packages and updated 194 packages in 30.449s

C:\sandbox
λ npx create-nx-workspace
? Workspace name (e.g., org name)     myorg
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new myorg --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE myorg/nx.json
CREATE myorg/package.json
CREATE myorg/README.md
CREATE myorg/tools/generators/.gitkeep
CREATE myorg/tools/tsconfig.tools.json
CREATE myorg/tsconfig.base.json
CREATE myorg/.editorconfig
CREATE myorg/.gitignore
CREATE myorg/.prettierignore
CREATE myorg/.vscode/extensions.json
CREATE myorg/workspace.json
CREATE myorg/.prettierrc
CREATE myorg/apps/.gitkeep
CREATE myorg/libs/.gitkeep
EINVAL: invalid argument, mkdir 'C:\C:\sandbox\myorg'
node:child_process:636
    err = new Error(msg);
          ^

Error: Command failed: npx tao new myorg --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\"C:/sandbox\"
    at checkExecSyncError (node:child_process:636:11)
    at Object.execSync (node:child_process:672:15)
    at createApp (C:\Users\wizar\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:385:21)
    at C:\Users\wizar\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:98:29
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 21556,
  stdout: null,
  stderr: null
}

C:\sandbox
λ npm cache verify
Cache verified and compressed (~\AppData\Local\npm-cache\_cacache)
Content verified: 2389 (123720547 bytes)
Content garbage-collected: 27 (30523682 bytes)
Index entries: 2389
Finished in 26.631s

C:\sandbox
λ npx create-nx-workspace
? Workspace name (e.g., org name)     myorg
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? Use Nx Cloud? (It's free and doesn't require registration.) No
Creating a sandbox with Nx...
new myorg --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace
CREATE myorg/nx.json
CREATE myorg/package.json
CREATE myorg/README.md
CREATE myorg/tools/generators/.gitkeep
CREATE myorg/tools/tsconfig.tools.json
CREATE myorg/tsconfig.base.json
CREATE myorg/.editorconfig
CREATE myorg/.gitignore
CREATE myorg/.prettierignore
CREATE myorg/.vscode/extensions.json
CREATE myorg/workspace.json
CREATE myorg/.prettierrc
CREATE myorg/apps/.gitkeep
CREATE myorg/libs/.gitkeep
EINVAL: invalid argument, mkdir 'C:\C:\sandbox\myorg'
node:child_process:636
    err = new Error(msg);
          ^

Error: Command failed: npx tao new myorg --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot=\"C:/sandbox\"
    at checkExecSyncError (node:child_process:636:11)
    at Object.execSync (node:child_process:672:15)
    at createApp (C:\Users\wizar\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:385:21)
    at C:\Users\wizar\AppData\Local\npm-cache\_npx\d2207cf76adb22dc\node_modules\create-nx-workspace\bin\create-nx-workspace.js:98:29
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13928,
  stdout: null,
  stderr: null
}

```

**Comment by bekos** [comment]
@wizardnet972 we haven't made a new release yet. I suppose this will happen soon 😃
