### ISSUE TITLE
nx e2e with --tag results in "Unknown option: '--tag'"

### ISSUE THREAD

**Issue by kpmck** [nrwl/nx#4998]
## Current Behavior

In attempting to tag my Cypress runs with the cypress CLI option --tag, I receive an error indicating `Unknown option: '--tag'`
## Expected Behavior

I would like to be able to use the `--tag` CLI option shown in the list of available options [here](https://docs.cypress.io/guides/guides/command-line.html#Options) to identify specific e2e runs with tags for reporting in the Cypress dashboard.

## Steps to Reproduce

1. Create an app with a Cypress e2e project
2. Run the command nx e2e your-app-e2e --tag testTag 

### Failure Logs

`Unknown option: '--t'`

### Environment

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'e2e:ci:smoke'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'pree2e:ci:smoke', 'e2e:ci:smoke', 'poste2e:ci:smoke' ]
5 info lifecycle thisCompany@0.0.0~pree2e:ci:smoke: thisCompany@0.0.0
6 info lifecycle thisCompany@0.0.0~e2e:ci:smoke: thisCompany@0.0.0
7 verbose lifecycle thisCompany@0.0.0~e2e:ci:smoke: unsafe-perm in lifecycle true
8 verbose lifecycle thisCompany@0.0.0~e2e:ci:smoke: PATH: {{pathDetails}}
9 verbose lifecycle thisCompany@0.0.0~e2e:ci:smoke: CWD: C:\thisCompany\thisApp\thisCompany
10 silly lifecycle thisCompany@0.0.0~e2e:ci:smoke: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   "ng e2e thisApp-e2e  --parallel -- --parallel -c ci-smoke --headless --spec './apps/thisApp-e2e/src/tests/e2e/**/*.feature' --parallel --record --key {{dashboardKey}} --t test"
10 silly lifecycle ]
11 silly lifecycle thisCompany@0.0.0~e2e:ci:smoke: Returned: code: 1  signal: null
12 info lifecycle thisCompany@0.0.0~e2e:ci:smoke: Failed to exec e2e:ci:smoke script
13 verbose stack Error: thisCompany@0.0.0 e2e:ci:smoke: `ng e2e thisApp-e2e  --parallel -- --parallel -c ci-smoke --headless --spec './apps/thisApp-e2e/src/tests/e2e/**/*.feature' --parallel --record --key {{dashboardKey}} --t test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid thisCompany@0.0.0
15 verbose cwd C:\thisCompany\thisApp\thisCompany
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e:ci:smoke"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error thisCompany@0.0.0 e2e:ci:smoke: `ng e2e thisApp-e2e  --parallel -- --parallel -c ci-smoke --headless --spec './apps/thisApp-e2e/src/tests/e2e/**/*.feature' --parallel --record --key {{dashboardKey}} --t test`
22 error Exit status 1
23 error Failed at the thisCompany@0.0.0 e2e:ci:smoke script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kpmck** [comment]
Bumping this guy. Does anyone have any reasonable workaround that may work?

**Comment by itsTalwar** [comment]
@kpmck you can do custom: and then try it.

`nx e2e your-app-e2e custom: --tag testTag`

**Comment by kpl1** [comment]
any news on this ?

**Comment by modern-sapien** [comment]
I'm trying to record to the Dashboard utilizing the --tag. 

This is also not listed as an option in your [documentation](https://nx.dev/cypress/cypress) either regarding Cypress arguments that can be passed.

I'm currently working through this now and available if you need eyes.

**Comment by barbados-clemens** [comment]
Hi all, 

I've checked this out this morning and found the fix, looking to get a PR here soon.

Thanks for reporting 😄
