### ISSUE TITLE
babel transpilation has failed when upgrading 11.4.0 to 11.5.1

### ISSUE THREAD

**Issue by takakobem** [nrwl/nx#5001]
## Current Behavior

The code including async function make babel errors with nx@11.5.1.

```ts
class Hoge {
  hoge = async() => {  // error!
    console.log("hoge")
  }
}
```

## Expected Behavior

No error occurs.

## Steps to Reproduce

In this repository ( https://github.com/takakobem/nx-babel-error ) , you run `nx serve` and you can see the error.

### Failure Logs

```
ERROR in ./main.tsx
Module build failed (from /Workspace/nx-storybook-test/node_modules/@nrwl/web/src/utils/web-babel-loader.js):
SyntaxError: /Workspace/nx-storybook-test/apps/main/src/main.tsx: Cannot convert non-arrow function to a function expression.
   6 |
   7 | class Hoge {
>  8 |   hoge = async() => {  // error!
     |          ^
   9 |     console.log("hoge")
  10 |   }
  11 | }
    at File.buildCodeFrameError (/Workspace/nx-storybook-test/node_modules/@babel/core/lib/transformation/file/file.js:248:12)
    at NodePath.buildCodeFrameError (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/path/index.js:138:21)
    at NodePath.arrowFunctionToExpression (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/path/conversion.js:102:16)
    at PluginPass.ArrowFunctionExpression (/Workspace/nx-storybook-test/node_modules/@babel/preset-modules/lib/plugins/transform-async-arrows-in-class/index.js:37:14)
    at newFn (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitSingle (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/context.js:85:19)
    at TraversalContext.visit (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/path/context.js:99:18)
    at TraversalContext.visitQueue (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitSingle (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/context.js:85:19)
    at TraversalContext.visit (/Workspace/nx-storybook-test/node_modules/@babel/traverse/lib/context.js:144:19)
```

### Environment

node 14.16
Mac OS Catalina

**Comment by ValiDraganescu** [comment]
I'm in the same situation

**Comment by kirjai** [comment]
thanks for reporting the issue @takakobem !

We've introduced some changes to how babel works in `11.5`, but that introduced problems with some existing projects. What I'm seeing from [your repro repo](https://github.com/takakobem/nx-babel-error), the fix that we recently merged (#5041) includes migrations that should fix this issue. So keep an eye out for next release

**Comment by kirjai** [comment]
@takakobem , Nx version `11.5.2` has been released a few days ago. Could you try migrating to that version (including running the migrations) and see if that fixes your issue?

**Comment by takakobem** [comment]
@kirjai thanks! I upgraded to `11.5.2` and confirmed that the bug was fixed 🎉
