### ISSUE TITLE
Error while running nx migrate

### ISSUE THREAD

**Issue by shashankvivek** [nrwl/nx#5050]
I am trying to migrate my Angular 9 project to Angular 11, To being with, I started with 

* `nx migrate latest` 
It ran successfully and I have updates in `package.json` and a `migrations.json` file created. I ran:

* `npm i` (success here)
* `nx migrate --run-migrations=migrations.json` (error out with below error)

```
Running migration update-linters-exclude
Successfully finished update-linters-exclude
---------------------------------------------------------
Running migration add-decorate-cli
Path "/decorate-angular-cli.js" already exist.
/home/shan/workspace/TestProj/sample-ui/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /tmp/tmp-71581bTGLEvsankji/node_modules/.bin/tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (/home/shan/workspace/TestProj/sample-ui/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:80:25)
    at Object.runCommand (/home/shan/workspace/TestProj/sample-ui/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/shan/workspace/TestProj/sample-ui/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/home/shan/workspace/TestProj/sample-ui/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/home/shan/workspace/TestProj/sample-ui/node_modules/@nrwl/cli/lib/init-local.js:23:13)
    at Object.<anonymous> (/home/shan/workspace/TestProj/sample-ui/node_modules/@nrwl/cli/bin/nx.js:42:18)
``` 

Can you please help me understand the reason ?

**Comment by junekpavel** [comment]
Hi, we were facing the same issue. Finally fixed it via adding following into package.json scripts
`"nx": "node --max_old_space_size=8192 ./node_modules/@nrwl/cli/bin/nx",`

And then for build and other commands: `yarn nx build`.
