### ISSUE TITLE
Plugin @nrwl/devtools  ensureNxProject  tree dependency issues

### ISSUE THREAD

**Issue by Brian-McBride** [nrwl/nx#5073]
## Current Behavior
I am using the `@nrwl/devkit` tools to generate an e2e test environment. 

I have a plugin called `@anatine/esbuildnx` that I am running inside the test project `./tmp/nx-e2e/proj`. 
```typescript
await runNxCommandAsync(`generate @anatine/esbuildnx:esbuildnx ${plugin}`);
```

Ok, so far so good. 

Now, I add a lib dependency: `import { esbuildDecorators } from '@anatine/esbuild-decorators';` into my `esbuildrnx` codebase. 

This package is in my monorepo, and also happens to be published to NPM as well. 

I can't figure out why the package isn't resolving. This is the error
```
Error: Command failed: npx nx build in-progress --skip-nx-cache
Cannot find module '@anatine/esbuild-decorators'
Require stack:
- /Users/brian/Development/anatine/esbuildnx/dist/packages/esbuildnx/src/executors/build/executor.js
- /Users/brian/Development/anatine/esbuildnx/tmp/nx-e2e/proj/node_modules/@nrwl/tao/src/shared/workspace.js
- /Users/brian/Development/anatine/esbuildnx/tmp/nx-e2e/proj/node_modules/@nrwl/tao/src/commands/run.js
- /Users/brian/Development/anatine/esbuildnx/tmp/nx-e2e/proj/node_modules/@nrwl/tao/index.js
- /Users/brian/Development/anatine/esbuildnx/tmp/nx-e2e/proj/node_modules/@nrwl/cli/lib/run-cli.js


    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
```

The generated package.json in the e2e tests created this entry:
```json
"@anatine/esbuildnx": "file:/Users/brian/Development/anatine/esbuildnx/dist/packages/esbuildnx",
```
Of course that works until I put in the dependency. And external deps work too. I have no problem importing something like webpack or whatever. 

I've tried adding a line to my temp project's package.json ( no luck )
```
"@anatine/esbuild-decorators": "file:/Users/brian/Development/anatine/esbuildnx/dist/packages/esbuild-decorators",
```

## Expected Behavior
Importing a package from the namespace should just work. 

## Steps to Reproduce
1. Generate a plugin repo
2. Create 2ne supporting package
3. Import supporting package into main package and use that imported function
4. Run existing e2e tests

### Failure Logs
```
> nx run in-progress:build 
Cannot find module '@anatine/esbuild-decorators'
Require stack:
- /Users/brian/Development/anatine/esbuildnx/dist/packages/esbuildnx/src/executors/build/executor.js
- /Users/brian/Development/anatine/esbuildnx/tmp/nx-e2e/proj/node_modules/@nrwl/tao/src/shared/workspace.js
- /Users/brian/Development/anatine/esbuildnx/tmp/nx-e2e/proj/node_modules/@nrwl/tao/src/commands/run.js
- /Users/brian/Development/anatine/esbuildnx/tmp/nx-e2e/proj/node_modules/@nrwl/tao/index.js
- /Users/brian/Development/anatine/esbuildnx/tmp/nx-e2e/proj/node_modules/@nrwl/cli/lib/run-cli.js
- 
```

#### Plugin Project
```
>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : darwin x64
  npm  : 7.6.3
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.1
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.5.1
  @nrwl/nest : 11.5.1
  @nrwl/next : Not Found
  @nrwl/node : 11.5.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.5.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.3
```

#### nx-e2e generated project
```
>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : darwin x64
  npm  : 7.6.3
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.1
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.5.1
  @nrwl/nest : 11.5.1
  @nrwl/next : Not Found
  @nrwl/node : 11.5.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.5.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

**Comment by Brian-McBride** [comment]
I managed to get my code working by doing an npm install inside the `dist/packages/esbuildnx` folder. That fixed the missing package issue. 

I'm not sure if that would be as easy  if I hadn't already published the former package.
So, in this case, the process to get the runtime working was:

1. Build dep package
2. Publish dep package
3. Build plugin package
4. run `npm install` in the plugin package `dist` directory
5. Run E2E testing using: `ensureNxProject()` and `runNxCommandAsync`  It is also handy to put `--skip-nx-cache` in your tests while you develop so that you don't accidently test against cache for your builder. 

It would be nice to get dependency resolution to work in all this.
