### ISSUE TITLE
Can't invoke NX binary from bazel

### ISSUE THREAD

**Issue by martaver** [nrwl/nx#5076]
Hi!

I'm trying to find a way to harmoniously integrate NX with an external bazel-driven build system. The approach I'm trying to take is to let NX do its magic, and simply use bazel to 'drive' nx's own processes.

Each app/lib has a BUILD file... and in that build file I want to use nx to invoke a build for that app/lib.

To do this, I load the nx binary which bazel then creates a `nodejs_binary` target for:
```
load("@npm//nx:index.bzl", "nx")
```

And try to get the 'help' text as a simple test:
```
nx(
    name = "build",
    data = [
        ":www",
        "@npm//:node_modules"        
    ],
    output_dir = True,
    args = ["--help"]
)
```

Where `www` is a nextjs app living in `apps/www` (not that it matters really for invoking `nx --help`)

I run `yarn bazelisk build //apps/www:build`

## Current Behavior
Bazel conks out with:
```
ERROR: [...]Projects/experiments/nx/cleric/apps/www/BUILD.bazel:45:3: Action apps/www/build failed: missing input file 'external/npm/node_modules/@ampproject/toolbox-optimizer/.cache/318e5f7b116d88814fbdd7050ca3995a.json', owner: '@npm//:node_modules/@ampproject/toolbox-optimizer/.cache/318e5f7b116d88814fbdd7050ca3995a.json'
Target //apps/www:build failed to build
ERROR: [...]Projects/experiments/nx/cleric/apps/www/BUILD.bazel:45:3 Action apps/www/build failed: 1 input file(s) do not exist
```

Some kind of cached file either doesn't get created or can't be found...

## Expected Behavior
NX's help dialogue to be outputted

## Steps to Reproduce

Pull this branch: https://github.com/cleric-sh/experiments-nx/tree/bazel
Do `yarn install`
Run `yarn bazelisk build //apps/www:build`

### Environment

```
 Node : 14.14.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : 11.5.1
  @nrwl/angular : Not Found
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.5.1
  @nrwl/nest : Not Found
  @nrwl/next : 11.5.1
  @nrwl/node : Not Found
  @nrwl/react : 11.1.5
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : 11.1.5
  @nrwl/workspace : 11.1.5
  typescript : 4.2.3
```

To be honest, this whole thing might not necessarily be a great idea, but since NX has given up on use bazel under the hood, I think it would be handy if there were a reasonable layer for interacting with it.

Appreciate any advice!

**Comment by martaver** [comment]
Adding `strict_visibility = False,` to the workspace's `yarn_install` rule fixed this. It allows transitive dependencies to be visible to targets other than their immediate parents.

NX runs now, however I get this error instead:
```
node:36672) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/private/var/tmp/_bazel_martaver/330290205f1b212a9c469cb81c3a410c/sandbox/darwin-sandbox/5/execroot/cleric/tsconfig.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at TargetProjectLocator.defaultFileRead [as fileRead] (/private/var/tmp/_bazel_martaver/330290205f1b212a9c469cb81c3a410c/sandbox/darwin-sandbox/5/execroot/cleric/node_modules/@nrwl/workspace/src/core/file-utils.js:159:17)
    at new TargetProjectLocator (/private/var/tmp/_bazel_martaver/330290205f1b212a9c469cb81c3a410c/sandbox/darwin-sandbox/5/execroot/cleric/node_modules/@nrwl/workspace/src/core/target-project-locator.js:22:73)
    at buildExplicitTypeScriptDependencies (/private/var/tmp/_bazel_martaver/330290205f1b212a9c469cb81c3a410c/sandbox/darwin-sandbox/5/execroot/cleric/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:8:34)
    at /private/var/tmp/_bazel_martaver/330290205f1b212a9c469cb81c3a410c/sandbox/darwin-sandbox/5/execroot/cleric/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:60:41
    at Array.forEach (<anonymous>)
    at buildProjectGraph (/private/var/tmp/_bazel_martaver/330290205f1b212a9c469cb81c3a410c/sandbox/darwin-sandbox/5/execroot/cleric/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:60:26)
    at Object.createProjectGraph (/private/var/tmp/_bazel_martaver/330290205f1b212a9c469cb81c3a410c/sandbox/darwin-sandbox/5/execroot/cleric/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:40:30)
    at Object.<anonymous> (/private/var/tmp/_bazel_martaver/330290205f1b212a9c469cb81c3a410c/sandbox/darwin-sandbox/5/execroot/cleric/node_modules/@nrwl/workspace/src/command-line/run-one.js:16:46)
(node:36672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Target //apps/www:build up-to-date:
  dist/bin/apps/www/build
```

It's trying to find a `tsconfig.json` in the workspace root... but in the standard NX setup, there's only `tsconfig.base.json` there. 

Headscratching continues...

**Comment by ubergeoff** [comment]
And if you rename the tsconfig.base.json file...?

i.e. just use the "old/standard" naming of tsconfig.json

**Comment by sgammon** [comment]
👀
