### ISSUE TITLE
Unexpected top-level property "nx-enforce-module-boundaries"

### ISSUE THREAD

**Issue by kenptr** [nrwl/nx#5081]
## Current Behavior
Eslint is crashing on VS Code when setting `nx-enforce-module-boundaries` to `.eslintrc.json`. I was following https://github.com/nrwl/nx/blob/master/docs/shared/monorepo-tags.md

.eslintrc.json
```
{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nrwl/nx", "@typescript-eslint/eslint-plugin"],
  "extends": ["prettier"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "enforceBuildableLibDependency": true,
            "allow": [],
            "depConstraints": [{ "sourceTag": "*", "onlyDependOnLibsWithTags": ["*"] }]
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "rules": {
        "@typescript-eslint/no-explicit-any": "off"
      }
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nrwl/nx/javascript"],
      "rules": {}
    }
  ],
  "nx-enforce-module-boundaries": [
    true,
    {
      "allow": [],
      "depConstraints": [
        {
          "sourceTag": "scope:shared",
          "onlyDependOnLibsWithTags": ["scope:shared"]
        },
        {
          "sourceTag": "scope:admin",
          "onlyDependOnLibsWithTags": ["scope:shared", "scope:admin"]
        },
        {
          "sourceTag": "scope:client",
          "onlyDependOnLibsWithTags": ["scope:shared", "scope:client"]
        }
      ]
    }
  ]
}

```

## Crash Logs

```
[Info  - 7:15:19 PM] ESLint server is starting
[Info  - 7:15:19 PM] ESLint server running in node v12.18.3
[Info  - 7:15:19 PM] ESLint server is running.
[Info  - 7:15:20 PM] ESLint library loaded from: /Users/PATH/mono/node/node_modules/eslint/lib/api.js
[Error - 7:42:10 PM] ESLint stack trace:
[Error - 7:42:10 PM] Error: ESLint configuration in libs/backend/iihack/.eslintrc.json » ../../../.eslintrc.json is invalid:
	- Unexpected top-level property "nx-enforce-module-boundaries".

Referenced from: /Users/PATH/mono/node/libs/backend/iihack/.eslintrc.json
    at ConfigValidator.validateConfigSchema (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:271:19)
    at ConfigArrayFactory._normalizeConfigData (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:644:19)
    at ConfigArrayFactory._loadConfigData (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:609:21)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:889:21)
    at ConfigArrayFactory._loadExtends (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
[Error - 7:42:10 PM] ESLint stack trace:
[Error - 7:42:10 PM] Error: ESLint configuration in apps/servak/.eslintrc.json » ../../.eslintrc.json is invalid:
	- Unexpected top-level property "nx-enforce-module-boundaries".

Referenced from: /Users/PATH/mono/node/apps/servak/.eslintrc.json
    at ConfigValidator.validateConfigSchema (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:271:19)
    at ConfigArrayFactory._normalizeConfigData (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:644:19)
    at ConfigArrayFactory._loadConfigData (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:609:21)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:889:21)
    at ConfigArrayFactory._loadExtends (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/PATH/mono/node/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
```

### Environment

```
  Node : 12.18.3
  OS   : darwin x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.1
  @nrwl/cypress : 11.5.1
  @nrwl/devkit : 11.5.2
  @nrwl/eslint-plugin-nx : 11.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.5.1
  @nrwl/nest : 11.5.2
  @nrwl/next : Not Found
  @nrwl/node : 11.5.1
  @nrwl/react : 11.5.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : 11.5.1
  @nrwl/workspace : 11.5.1
  @nrwl/storybook : 11.5.2
  @nrwl/gatsby : Not Found
  typescript : 4.2.3
```

**Comment by puku0x** [comment]
I think the doc is out of date because `nx-enforce-module-boundaries` rule is for TSLint and it should be in `rules` property.

```js
// tslint.json
{
  "rulesDirectory": [
    "node_modules/@nrwl/workspace/src/tslint",
    "node_modules/codelyzer"
  ],
  "linterOptions": {
    "exclude": ["**/*"]
  },
  "rules": {
    ...,
    "nx-enforce-module-boundaries": [
      true,
      {
        "enforceBuildableLibDependency": true,
        "allow": [],
        "depConstraints": [
          {
            "sourceTag": "*",
            "onlyDependOnLibsWithTags": ["*"]
          }
        ]
      }
    ],
  }
}
```

If you are using ESLint, you should override `@nrwl/nx/enforce-module-boundaries` rule.
```js
// eslintrc.json
{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nrwl/nx"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "enforceBuildableLibDependency": true,
            "allow": [],
            "depConstraints": [
              {
                "sourceTag": "scope:shared",
                "onlyDependOnLibsWithTags": ["scope:shared"]
              },
              {
                "sourceTag": "scope:admin",
                "onlyDependOnLibsWithTags": ["scope:shared", "scope:admin"]
              },
              {
                "sourceTag": "scope:client",
                "onlyDependOnLibsWithTags": ["scope:shared", "scope:client"]
              }
            ]
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "rules": {}
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nrwl/nx/javascript"],
      "rules": {}
    }
  ]
}
```

**Comment by kenptr** [comment]
It works! (I'll leave it open for tracking the docfix)
