### ISSUE TITLE
Cannot use custom nextConfig with next build executor when using Next 10.0.1 + Nx 11.5.2

### ISSUE THREAD

**Issue by james-gibson** [nrwl/nx#5093]
## Current Behavior
When using a brand new Next workspace generated by Nx I am unable to use a custom `next.config.js` for at least two reasons.
1) Nx `Cannot find module 'next.config.js'` with a custom path
2) When provided a fully qualified path the provided `next.config.js` does not export a method as the Nx code expects.

## Expected Behavior
Per the documentation at https://nx.dev/latest/react/next/build#nextconfig I expect providing configuration for a custom next.config.js should be valid

## Steps to Reproduce
Pr with code, logs, and notes => https://github.com/james-gibson/nx-next-config-bug

I think bug one is somewhere near https://github.com/nrwl/nx/blob/master/packages/next/src/utils/config.ts#L130

I think bug two is related and is caused by this method execution https://github.com/nrwl/nx/blob/master/packages/next/src/utils/config.ts#L145

### Nx Build
```
❯ nx-next-config-bug (main) ✘ nx build
nx run nx-next-config-bug:build
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Cannot find module 'next.config.js'
```
### Nx Build Verbose
```
nx build --verbose
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Cannot find module 'next.config.js'
Error: Cannot find module 'next.config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.require (/Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/tao/src/compat/compat.js:7:40)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.prepareConfig (/Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/next/src/utils/config.js:85:11)
    at /Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/next/src/executors/build/build.impl.js:19:33
    at Generator.next (<anonymous>)
    at /Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/tslib/tslib.js:113:16)
    at buildExecutor (/Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/next/src/executors/build/build.impl.js:17:20)
    at /Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/tao/src/commands/run.js:122:23
    at Generator.next (<anonymous>)
    at /Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
```

### Nx build (modified) [bug 2]
Delta: Replace `next.config.js` with fully qualified file path to the location
Example: https://github.com/james-gibson/nx-next-config-bug/blob/main/workspace.json#L32
Note: The module is found when referenced this way but is not correct.
```
nx run nx-next-config-bug:build --verbose
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
userNextConfig is not a function
TypeError: userNextConfig is not a function
    at Object.prepareConfig (/Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/next/src/utils/config.js:94:12)
    at /Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/next/src/executors/build/build.impl.js:19:33
    at Generator.next (<anonymous>)
    at /Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/tslib/tslib.js:113:16)
    at buildExecutor (/Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/next/src/executors/build/build.impl.js:17:20)
    at /Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/tao/src/commands/run.js:122:23
    at Generator.next (<anonymous>)
    at /Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/tslib/tslib.js:113:16)
    at runExecutorInternal (/Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/tao/src/commands/run.js:103:20)
    at Object.<anonymous(/Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/@nrwl/tao/src/commands/run.js:191:54)
    at Generator.next (<anonymous>)
    at /Users/jgibson/src/prototypes/nx-next-config-bug/node_modules/tslib/tslib.js:117:75
```

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 10.16.3
  OS   : darwin x64
  npm  : 6.9.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.2
  @nrwl/cypress : 11.5.2
  @nrwl/devkit : 11.5.2
  @nrwl/eslint-plugin-nx : 11.5.2
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.2
  @nrwl/linter : 11.5.2
  @nrwl/nest : Not Found
  @nrwl/next : 11.5.2
  @nrwl/node : Not Found
  @nrwl/react : 11.5.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.2
  @nrwl/web : 11.5.2
  @nrwl/workspace : 11.5.2
  @nrwl/storybook : 11.5.2
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

## Similar issues
https://github.com/nrwl/nx/issues/4990

**Comment by jaysoo** [comment]
Hey @james-gibson 👋

The `nextConfig` option is probably not documented well. If you are using a normal `next.config.js` file for the app you shouldn't need this option. Just like normal Next.js, we will pick up `next.config.js` automatically.

So the **fix** is to remove the `nextConfig` option from `workspace.json` and let `next.config.js` be picked up automatically.

The option was meant for more advanced use cases, especially involving custom executors that extend our `@nrwl/next:build` executor. 

See here for the original reason the option was added: https://github.com/nrwl/nx/pull/3782#issuecomment-698967729.

There still seems to be a bug where the path of the config isn't resolving unless it is absolute. We will make sure the documentation is more clear and that relative paths can resolve correctly.

Let me know if there are further problems.

**Comment by james-gibson** [comment]
@jaysoo !!! It's been a while!

Thanks for taking a look at this. It had us pretty confused. I've gone ahead and removed the custom `nextConfig` from our config as recommended. I think the documentation led us into thinking we were supposed to supply it and in our case our private repo actually had two next configs (it shouldn't have, oversight really) which increased our confusion as to why it wasn't working. To your point, the next cli would have been trying to resolve the config for us. We will continue implementing and report back if we find any other oddities. Thanks!

**Comment by kirjai** [comment]
seeing how #5098 is now merged, should we close this issue?
