### ISSUE TITLE
Error: Command failed: git merge-base --fork-point Azure Devops agent pipeline

### ISSUE THREAD

**Issue by jlabaj** [nrwl/nx#5145]
## Current Behavior

NX is at 11.5.2, Angular at 11.2.5

getting this in azure pipeline

cross-env NODE_OPTIONS=--max_old_space_size=8192 nx affected:lint --base develop --parallel=true --maxParallel=17

'''
Error: Command failed: git merge-base --fork-point develop HEAD
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at getFilesUsingBaseAndHead (C:\devopsagent\_work\1\s\src\...\wwwroot\...\node_modules\@nrwl\workspace\src\command-line\shared.js:55:37)
    at Object.parseFiles (C:\devopsagent\_work\1\s\src\...\wwwroot\..\node_modules\@nrwl\workspace\src\command-line\shared.js:31:20)
    at Object.<anonymous> (C:\devopsagent\_work\1\s\src\...\wwwroot\...\node_modules\@nrwl\workspace\src\command-line\affected.js:26:112)
    at Generator.next (<anonymous>)
    at fulfilled (C:\devopsagent\_work\1\s\src\...\wwwroot\...\node_modules\tslib\tslib.js:111:62) {
  status: 1,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 3892,
  stdout: <Buffer >,
  stderr: <Buffer >
}

**Comment by FrozenPandaz** [comment]
Can you confirm that `develop` exists locally in the pipeline? (CI systems sometimes only checkout the PR Branch)

Maybe using this repo as a reference will help? https://github.com/nrwl/nx-azure-build

Can you please provide an example repo that's hooked up to azure to help us reproduce the issue?
