### ISSUE TITLE
affected command fails if base argument could be a number

### ISSUE THREAD

**Issue by ronderksen** [nrwl/nx#5191]
## Current Behavior
In our build setup we determine the commit id for the base against which to run the affected command.
Sometimes this returns a double commit id. If the second id is a value that could be a number (e.g., 34236742 or 64356e2), the affected command fails with arg.match is undefined.
Wrapping both ids in quotes solves the issue.

## Expected Behavior
The affected command does not fail.

As a full numeric id is not a common occurrence, I don't know if this is a regression.

## Steps to Reproduce
Not sure if you could manipulate a git repo to generate a commit id that only has numbers. 

### Failure Logs
```
npm run affected:apps -- --plain --target=HEAD --base=ff06f01a 389521e4 |grep -v '>' | grep '\S' | tr ' ' '\n'

/workspace/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1109
      else throw err
           ^

TypeError: arg.match is not a function
    at parse (/workspace/node_modules/@nrwl/workspace/node_modules/yargs-parser/index.js:130:13)
    at Parser (/workspace/node_modules/@nrwl/workspace/node_modules/yargs-parser/index.js:802:16)
    at Object.splitArgsIntoNxArgsAndOverrides (/workspace/node_modules/@nrwl/workspace/src/command-line/utils.js:44:23)
    at Object.affected (/workspace/node_modules/@nrwl/workspace/src/command-line/affected.js:16:43)
    at Object.handler (/workspace/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:40:115)
    at Object.runCommand (/workspace/node_modules/@nrwl/workspace/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/workspace/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:1022:30)
    at Object.get [as argv] (/workspace/node_modules/@nrwl/workspace/node_modules/yargs/yargs.js:965:21)
    at Object.initLocal (/workspace/node_modules/@nrwl/cli/lib/init-local.js:24:13)
    at Object.<anonymous> (/workspace/node_modules/@nrwl/cli/bin/nx.js:12:18)
```

### Environment
It happens both on my local Mac and on google cloud during a build.

**Comment by ronderksen** [comment]
@FrozenPandaz Added the error output. Let me know if you need more info.
