### ISSUE TITLE
Cannot read property 'pos' of undefined

### ISSUE THREAD

**Issue by kenobi-io** [nrwl/nx#5196]
## Current Behavior
nx run build 

### Failure Logs
```bash
An error occurred during the build:
TypeError: Cannot read property 'pos' of undefined
    at createFileDiagnosticAtReference (/node_modules/typescript/lib/typescript.js:107529:68)
    at addProgramDiagnosticAtRefPath (/node_modules/typescript/lib/typescript.js:107547:93)
    at checkSourceFilesBelongToPath (/node_modules/typescript/lib/typescript.js:107208:25)
    at Object.getCommonSourceDirectory (/ode_modules/typescript/lib/typescript.js:105612:40)
    at Object.getDeclarationEmitOutputFilePath (/node_modules/typescript/lib/typescript.js:17179:125)
    at getOutputPathsFor (/node_modules/typescript/lib/typescript.js:99488:112)
    at forEachEmittedFile (/node_modules/typescript/lib/typescript.js:99425:41)
    at Object.emitFiles (/node_modules/typescript/lib/typescript.js:99654:9)
    at emitWorker (/node_modules/typescript/lib/typescript.js:106125:33)
    at /node_modules/typescript/lib/typescript.js:106102:72
    at runWithCancellationToken (/node_modules/typescript/lib/typescript.js:106205:24)
    at Object.emit (node_modules/typescript/lib/typescript.js:106102:26)
    at getFileEmitOutput (/node_modules/typescript/lib/typescript.js:108003:26)
    at updateShapeSignature (/node_modules/typescript/lib/typescript.js:108239:36)
    at getFilesAffectedByUpdatedShapeWhenModuleEmit (/node_modules/typescript/lib/typescript.js:108442:46)
    at Object.getFilesAffectedBy (/node_modules/typescript/lib/typescript.js:108194:144)
Cannot read property 'pos' of undefined
```

### Environment

```json
"compileOnSave": false,
"compilerOptions": {
"rootDir": **".",**
"sourceMap": true,
"declaration": false,
"moduleResolution": "node",
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"importHelpers": true,
"target": "es2015",
"module": "esnext",
"lib": ["es2017", "dom"],
"skipLibCheck": true,
"skipDefaultLibCheck": true,
"baseUrl": "./",
"paths": {
  "@local/core": ["../core/src/index.ts"]
}

  "dependencies": {
    "@angular/animations": "^11.2.0",
    "@angular/common": "^11.2.0",
    "@angular/compiler": "^11.2.0",
    "@angular/core": "^11.2.0",
    "@angular/forms": "^11.2.0",
    "@angular/platform-browser": "^11.2.0",
    "@angular/platform-browser-dynamic": "^11.2.0",
    "@angular/router": "^11.2.0",
    "@nrwl/angular": "11.6.0",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.0",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.0",
    "@angular/cli": "~11.0.0",
    "@angular/compiler-cli": "^11.2.0",
    "@angular/language-service": "^11.2.0",
    "@nrwl/cli": "11.6.0",
    "@nrwl/cypress": "11.6.0",
    "@nrwl/jest": "11.6.0",
    "@nrwl/tao": "11.6.0",
    "@nrwl/workspace": "11.6.0",
    "typescript": "~4.1.5"
```

_if **"@local/core": ["../core/src/index.ts"]** remove then building success_

**Comment by vsavkin** [comment]
Thank you for submitting the issue. Unfortunately, the information provided isn't enough for us to troubleshoot the problem. Could you provide a repo with a repro?
