### ISSUE TITLE
NX ERROR Something went wrong - create-nx-workspace@latest - Failed to format: workspace/workspace.json

### ISSUE THREAD

**Issue by hadrien-toma** [nrwl/nx#5203]
## Current Behavior

Error when trying to create a workspace from the latest version.

## Expected Behavior

Run the command without any error, correctly creating the workspace.

## Steps to Reproduce

```
docker run --rm --interactive --tty node /bin/bash -c "npx --yes create-nx-workspace@latest workspace --preset=empty --cli=nx --interactive=false --nx-cloud=false"
```

### Failure Logs

```
>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

npm notice 
npm notice New minor version of npm available! 7.6.3 -> 7.8.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.8.0
npm notice Run npm install -g npm@7.8.0 to update!
npm notice 
⠼ Creating your workspace
>  NX   ERROR  Something went wrong. Rerunning the command with verbose logging.

Failed to format: workspace/workspace.json
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:329:5)
    at Function.from (node:buffer:323:9)
    at FsTree.write (/tmp/tmp-19OWiMQhGOzsXC/node_modules/@nrwl/tao/src/shared/tree.js:35:20)
    at writeJson (/tmp/tmp-19OWiMQhGOzsXC/node_modules/@nrwl/devkit/src/utils/json.js:32:10)
    at Object.updateJson (/tmp/tmp-19OWiMQhGOzsXC/node_modules/@nrwl/devkit/src/utils/json.js:44:5)
    at formatWorkspaceJson (/tmp/tmp-19OWiMQhGOzsXC/node_modules/@nrwl/workspace/src/generators/workspace/workspace.js:53:18)
    at Object.<anonymous> (/tmp/tmp-19OWiMQhGOzsXC/node_modules/@nrwl/workspace/src/generators/workspace/workspace.js:78:9)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/tmp-19OWiMQhGOzsXC/node_modules/tslib/tslib.js:114:62) {
  code: 'ERR_INVALID_ARG_TYPE'
}
UPDATE workspace/package.json

up to date, audited 238 packages in 1s

32 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Directory is already under version control. Skipping initialization of git.

>  NX   SUCCESS  Nx has successfully created the workspace.


———————————————————————————————————————————————


>  NX   NOTE  Nx CLI is not installed globally.

  This means that you might have to use "yarn nx" or "npx nx" to execute commands in the workspace.
  Run "yarn global add nx" or "npm install -g nx" to be able to execute command directly.
```

### Environment

```
docker run --rm --interactive --tty node /bin/bash -c "node -v ; npx -v" 

v15.12.0
7.6.3
```

**Comment by hadrien-toma** [comment]
This works again now.
