### ISSUE TITLE
Dynamic import breaks '@nrwl/nx/enforce-module-boundaries' ESLint rule

### ISSUE THREAD

**Issue by ronnetzer** [nrwl/nx#5224]
## Current Behavior

ESLint breaks in files with dynamic imports that contains a variable in the import path (i.e ```import(`/some/path/${withVariable}`)```) with the following error:
`Cannot read property 'startsWith' of undefined`

## Expected Behavior

It is expected to work correctly as it did for TSLint.
It is expected that adding a `/** eslint-disable */` comment above the dynamic import will cause the rule to skip this import

## Steps to Reproduce

1. Create a publishable lib and add a dynamic import in it.
2. make sure this lib is affected by the "enforce-module-boundaries" rule.

### Failure Logs

```bash
TypeError: Cannot read property 'startsWith' of undefined
    at isRelative (/node_modules/@nrwl/workspace/src/utils/runtime-lint-utils.js:43:14)
    at Object.isRelativeImportIntoAnotherProject (/node_modules/@nrwl/workspace/src/utils/runtime-lint-utils.js:47:10)
    at run (/node_modules/@nrwl/eslint-plugin-nx/src/rules/enforce-module-boundaries.js:88:38)
    at ImportExpression (/node_modules/@nrwl/eslint-plugin-nx/src/rules/enforce-module-boundaries.js:201:17)
```

### Environment

```bash
  Node : 12.10.0
  OS   : darwin x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : 11.6.1
  @nrwl/cli : 11.6.1
  @nrwl/cypress : 11.6.1
  @nrwl/devkit : 11.6.1
  @nrwl/eslint-plugin-nx : 11.6.1
  @nrwl/jest : 11.6.1
  @nrwl/linter : 11.6.1
  @nrwl/nest : 11.6.1
  @nrwl/node : 11.6.1
  @nrwl/tao : 11.6.1
  @nrwl/workspace : 11.6.1
  @nrwl/storybook : 11.6.1
  typescript : 4.0.7
```

**Comment by puku0x** [comment]
I confirmed the bug.

It seems there is no `node.source.parent.value` for import expressions with template literal. 

```
<ref *1> {
  type: 'TemplateLiteral',
  quasis: [
    {
      type: 'TemplateElement',
      value: [Object],
      tail: false,
      range: [Array],
      loc: [Object],
      parent: [Circular *1]
    },
    {
      type: 'TemplateElement',
      value: [Object],
      tail: true,
      range: [Array],
      loc: [Object],
      parent: [Circular *1]
    }
  ],
  expressions: [
    {
      type: 'Identifier',
      name: 'todo',
      range: [Array],
      loc: [Object],
      parent: [Circular *1]
    }
  ],
  range: [ 193, 228 ],
  loc: { start: { line: 8, column: 9 }, end: { line: 8, column: 44 } },
  parent: <ref *2> {
    type: 'ImportExpression',
    source: [Circular *1],
    // no value!
    range: [ 186, 229 ],
    loc: { start: [Object], end: [Object] },
    parent: {
      type: 'MemberExpression',
      object: [Circular *2],
      property: [Object],
      computed: false,
      optional: false,
      range: [Array],
      loc: [Object],
      parent: [Object]
    }
  }
}
```

I will fix the following line.
https://github.com/nrwl/nx/blob/master/packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts#L126
