### ISSUE TITLE
failed to compile nested lazy loaded libs

### ISSUE THREAD

**Issue by olakara** [nrwl/nx#528]
I am having a lazily loaded module which in turn loads different routes lazily. I get the following error:

`ERROR in D:/trail/libs/builder/src/lib/builder.module.ts
Module build failed: Error: D:\trail\libs\builder\src\lib\builder.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (D:\trail\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
    at plugin.done.then (D:\trail\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
i ｢wdm｣: Failed to compile.`

Here Is how I setup my application, I have a `Lookups` module which is a parent module that's lazy loaded. `Lookups` module have multiple routes that are also lazy loaded `Lookup` & `Builder`.. Here is how I set them up using CLI

`ng generate app myapp --routing
ng generate lib home --routing --lazy --parent-module=apps/myapp/src/app/app.module.ts
ng generate lib lookups --routing --lazy --parent-module=apps/myapp/src/app/app.module.ts
ng generate lib lookup --routing --lazy --parent-module=libs/lookups/src/lib/lookups.module.ts
ng generate lib builder --routing --lazy --parent-module=libs/lookups/src/lib/lookups.module.ts`

The modules seems to be created and configured successfully with the lazy load routes in it. But upon running I get the above error. My understanding is that `Lookups` module ( Parent module ) is not able to get the child lazy modules.. How do I get around this error.

**Note:** I was able to do the same with nrwl 1.*

I am using all latest package:
nrwl: 6.0.1
Angular: 6.0.3
rxjs: 6.2.0

**Comment by olakara** [comment]
After more digging, I found that `tsconfig.app.json` file didn't have the appropriate entries. For example my config's include section was:
`"include": [
    "**/*.ts"
  
    , "../../libs/lookups/src/index.ts"

    , "../../libs/home/src/index.ts"
`
There is no path for the nested modules in here.. Once I added the new path, things started to work smooth :)

Result: 
`"include": [
    "**/*.ts"
  
    , "../../libs/lookups/src/index.ts"
    , "../../libs/lookup/src/index.ts"
    , "../../libs/builder/src/index.ts"
    , "../../libs/home/src/index.ts"
`

**Comment by vsavkin** [comment]
We should use dependency analysis to get the list of affected apps and update their tsconfig.app.json files.
