### ISSUE TITLE
Nx migrate latest erroring out

### ISSUE THREAD

**Issue by sasha-arrabi** [nrwl/nx#5284]
## Current Behavior

I am unable to run the `nx migrate latest` command to update my nx dependencies from 11.5 to 11.6. See error logs below.

## Expected Behavior

I am expecting that `nx migrate latest` performs the migration, or at least outputs a migration file.

## Steps to Reproduce

Run `nx migrate latest`.

Unfortunately, the source code is proprietary, but I can include the `package.json`, `angular.json`, `nx.json`, and whatever else may be necessary. I haven't been able to reproduce this in a fresh repo, so there is likely something going on locally.

I am able to run the `npm install --legacy-peer-deps` command just fine, so the error message does not seem to be matching up correctly, unless I'm misunderstanding it!

I also ran `npm ci` to ensure there was nothing corrupted in `node_modules`, though that didn't seem to have any effect.

### Failure Logs

```
$ nx migrate latest
C:\devl\repos\ssc-mfe\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: npm install --legacy-peer-deps
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at taoPath (C:\devl\repos\ssc-mfe\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:303:21)
    at Object.handler (C:\devl\repos\ssc-mfe\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:79:19)
    at Object.runCommand (C:\devl\repos\ssc-mfe\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\devl\repos\ssc-mfe\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\devl\repos\ssc-mfe\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\devl\repos\ssc-mfe\node_modules\@nrwl\cli\lib\init-local.js:23:13)
    at Object.<anonymous> (C:\devl\repos\ssc-mfe\node_modules\@nrwl\cli\bin\nx.js:42:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 27660,
  stdout: null,
  stderr: null
}
```

### Environment

```
  Node : 12.20.1
  OS   : win32 x64
  npm  : 6.14.10

  nx : Not Found
  @nrwl/angular : 11.5.2
  @nrwl/cli : 11.5.2
  @nrwl/cypress : 11.5.2
  @nrwl/devkit : 11.5.2
  @nrwl/eslint-plugin-nx : 11.5.2
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.2
  @nrwl/linter : 11.5.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.5.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.2
  @nrwl/web : 11.5.2
  @nrwl/workspace : 11.5.2
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

Any help would be really, really appreciated. Thank you!

**Comment by sasha-arrabi** [comment]
Welp, figured out what was the issue. I did an `npm login` a while back, which I guess setup my profile's `.npmrc` file with some now-outdated auth tokens.

It looks like the `nx migrate` command was using that `.npmrc` to perform the `npm install` command, which then failed.

Removing the outdated auth tokens ended up allowing the `nx migrate latest` command to succeed. Hopefully this helps somebody else out there!
