### ISSUE TITLE
how to test ngrx effects ? 

### ISSUE THREAD

**Issue by syedirfan7** [nrwl/nx#530]
config 

```console
   "@ngrx/effects": "5.2.0",
    "@ngrx/entity": "5.2.0",
    "@ngrx/router-store": "5.0.1",
    "@ngrx/store": "5.2.0",
    "@ngrx/store-devtools": "5.2.0",
    "@nrwl/nx": "1.0.0",`

```

Below is my effects and i am trying to test this and i am getting errors shown below

**Effects.ts**

```ts
export class ItemEffects {
@Effect()
  loadItem$ = this.dataPersistence.fetch(
    ItemAction.ItemActionTypes.LoadItem,
    {
      run: (action: ItemAction.LoadItem, state: ItemState) => {
        return this.ItemService
          .getItemData()
          .pipe(
          map(ItemData => new ItemAction.ItemLoaded(ItemData)),
          catchError(error => of(new ItemAction.ErrorAction(error)))
          );
     },
 }
 );
 constructor(
    private actions$: Actions,
    private ItemService: GroupService,
    private dataPersistence: DataPersistence<ItemState>
  ) { }
}
```

Please help me in  testing them. i have come across marble tests but could get through.

tried **spec.ts** file. below is the spec file attached and i get this error
[effect.spec.txt](https://github.com/nrwl/nx/files/2039151/effect.spec.txt)

```console
Error: Expected $.length = 1 to equal 2.
Expected $[0].frame = 10 to equal 0.
Expected $[0].notification.kind = 'E' to equal 'N'.
Expected $[0].notification.value = undefined to equal GroupLoaded({ payload: [ Object({ $id: 0, GroupId: '2', GroupName: 'India', GroupDescription: 'India', GroupParentId: 1, SubGroup: [ Object({ $id: 3, GroupId: '3', GroupName: 'Bangalore', GroupDescription: 'Bangalore', GroupParentId: 2, SubGroup: [  ], GroupCreatedBy: '1', GroupCreatedOn: '5/11/2018 1:51:21 PM', GroupStatus: 2 }) ], GroupCreatedBy: '1', GroupCreatedOn: '4/11/2018 1:51:21 PM', GroupStatus: 1 }), Object({ $id: 0, GroupId: '4', GroupName: 'USA', GroupDescription: 'USA', GroupParentId: 1, SubGroup: [  ], GroupCreatedBy: 'leader', GroupCreatedOn: '4/11/2018 2:51:21 PM', GroupStatus: 1 }) ], type: '[Group] Data Loaded' }).
Expected $[0].notification.error = TypeError: onError is not a function to equal undefined.
Expected $[0].notification.hasValue = false to equal true.
Expected $[1] = undefined to equal Object({ frame: 10, notification: Notification({ kind: 'C', value: undefined, error: undefined, hasValue: false }) }).
    at stack (http://localhost:9878/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2338:17)
    at buildExpectationResult (http://localhost:9878/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2308:14)
    at Spec.expectationResultFactory (http://localhost:9878/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:858:18)
    at Spec.addExpectationResult (http://localhost:9878/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:487:34)
    at Expectation.addExpectationResult (http://localhost:9878/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:802:21)
    at Expectation.toEqual (http://localhost:9878/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2252:12)
    at compare (http://localhost:9878/_karma_webpack_/webpack:/node_modules/jasmine-marbles/index.js:82:1)
    at Expectation.toBeObservable (http://localhost:9878/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2231:35)
    at Object.<anonymous> (http://localhost:9878/_karma_webpack_/webpack:/libs/groupmanagement/src/+state/group.effects.spec.ts:75:36)
    at step (http://localhost:9878/_karma_webpack_/main.bundle.js:748:23)
```

**Comment by tashoecraft** [comment]
this really isn't the correct repo to ask this. Try stackoverflow or the @ngrx repo

**Comment by vsavkin** [comment]
@syedirfan7 this is a question about using RxJS marbles, which you can read about in this blog post: https://blog.nrwl.io/rxjs-advanced-techniques-testing-race-conditions-using-rxjs-marbles-53e7e789fba5 

Closing this issue
