### ISSUE TITLE
Error in creating workspace for angular application

### ISSUE THREAD

**Issue by HosseinSalmanian** [nrwl/nx#5309]
## Current Behavior
when I try to create new workspace with `nx create-nx-workspace@latest` command, with following arguments

```
D:\test work spaces>npx create-nx-workspace@latest
npx: installed 38 in 7.614s
√ Workspace name (e.g., org name)     · asa
√ What to create in the new workspace · angular
√ Application name                    · todos
√ Default stylesheet format           · scss
√ Default linter                      · eslint
√ Use Nx Cloud? (It's free and doesn't require registration.) · No
```
creating the work space finishes with error and created angular.json file is incomplete
the create command generates following error in output.

## Expected Behavior
according to documentations I expected to have a fresh angular app in a new workspace

## Steps to Reproduce
Executing `nx create-nx-workspace@latest` command.

### Failure Logs
```
>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

added 198 packages from 167 contributors and audited 199 packages in 15.299s

32 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

| Creating your workspace
>  NX   ERROR  Something went wrong. Rerunning the command with verbose logging.

Failed to format: asa\angular.json
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:333:9)
    at FsTree.write (C:\Users\H610D~1.SOL\AppData\Local\Temp\tmp-9292uhADhYkusLf2\node_modules\@nrwl\tao\src\shared\tree.js:35:20)
    at writeJson (C:\Users\H610D~1.SOL\AppData\Local\Temp\tmp-9292uhADhYkusLf2\node_modules\@nrwl\devkit\src\utils\json.js:32:10)
    at Object.updateJson (C:\Users\H610D~1.SOL\AppData\Local\Temp\tmp-9292uhADhYkusLf2\node_modules\@nrwl\devkit\src\utils\json.js:44:5)
    at formatWorkspaceJson (C:\Users\H610D~1.SOL\AppData\Local\Temp\tmp-9292uhADhYkusLf2\node_modules\@nrwl\workspace\src\generators\workspace\workspace.js:53:18)
    at Object.<anonymous> (C:\Users\H610D~1.SOL\AppData\Local\Temp\tmp-9292uhADhYkusLf2\node_modules\@nrwl\workspace\src\generators\workspace\workspace.js:78:9)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\H610D~1.SOL\AppData\Local\Temp\tmp-9292uhADhYkusLf2\node_modules\tslib\tslib.js:114:62) {
  code: 'ERR_INVALID_ARG_TYPE'
}
UPDATE asa/nx.json
UPDATE asa/package.json
UPDATE asa/.vscode/extensions.json
UPDATE asa/angular.json

> asa@0.0.0 postinstall D:\test work spaces\asa
> node ./decorate-angular-cli.js


>  NX  Angular CLI has been decorated to enable computation caching.

npm WARN @cypress/webpack-preprocessor@4.1.5 requires a peer of webpack@^4.18.1 but none is installed. You must install peer dependencies yourself.
npm WARN @nrwl/cypress@12.0.1 requires a peer of cypress@>= 3 < 7 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.2.2 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

removed 1391 packages and audited 748 packages in 29.074s

57 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

MergeConflictException [Error]: A merge conflicted on path "/apps/todos/tsconfig.editor.json".
    at D:\test work spaces\asa\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:142:35
    at Array.forEach (<anonymous>)
    at HostTree.merge (D:\test work spaces\asa\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:131:23)
    at MapSubscriber.project (D:\test work spaces\asa\node_modules\@angular-devkit\schematics\src\rules\base.js:54:91)
    at MapSubscriber._next (D:\test work spaces\asa\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (D:\test work spaces\asa\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TapSubscriber._next (D:\test work spaces\asa\node_modules\rxjs\internal\operators\tap.js:65:26)
    at TapSubscriber.Subscriber.next (D:\test work spaces\asa\node_modules\rxjs\internal\Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (D:\test work spaces\asa\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (D:\test work spaces\asa\node_modules\rxjs\internal\Subscriber.js:66:18)
A merge conflicted on path "/apps/todos/tsconfig.editor.json".
Workspace creation failed, see above.

>  NX   ERROR  Something went wrong! v12.0.1

(node:9292) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new asa --no-interactive --preset=angular --appName=todos --style=scss --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot=\"D:/test work spaces\"
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at C:\Users\H.Soleymanian\AppData\Roaming\npm-cache\_npx\9292\node_modules\create-nx-workspace\bin\create-nx-workspace.js:449:29
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\H.Soleymanian\AppData\Roaming\npm-cache\_npx\9292\node_modules\create-nx-workspace\node_modules\tslib\tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

### Environment
node version v14.16.1
OS windows 10 (OS build 19042.870)

**Comment by leosvelperez** [comment]
@HosseinSalmanian thanks for reporting this! Could you please confirm you're trying to generate the workspace in an empty directory? That error normally arise when the workspace is being created in a non-empty directory. The following #5296 is adding a better error message for this scenario.

**Comment by galwa** [comment]
Same issue with an empty directory
tried  :
node 10.15.1 / 12.22.1 / 14.15.1
npm 7.9.0 / 6.4.1
Ubuntu 18.04

`~/Workspace/test$ npx create-nx-workspace@latest
(node:31562) ExperimentalWarning: The fs.promises API is experimental
✔ Workspace name (e.g., org name)     · test
✔ What to create in the new workspace · angular-nest
✔ Application name                    · test
✔ Default stylesheet format           · scss
✔ Default linter                      · eslint
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

(node:31585) ExperimentalWarning: The fs.promises API is experimental
⠏ Creating your workspace
>  NX   ERROR  Something went wrong. Rerunning the command with verbose logging.

(node:31854) ExperimentalWarning: The fs.promises API is experimental
Failed to format: test/angular.json
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:207:11)
    at FsTree.write (/tmp/tmp-315757m69ApOW1FAN/node_modules/@nrwl/tao/src/shared/tree.js:35:20)
    at writeJson (/tmp/tmp-315757m69ApOW1FAN/node_modules/@nrwl/devkit/src/utils/json.js:32:10)
    at Object.updateJson (/tmp/tmp-315757m69ApOW1FAN/node_modules/@nrwl/devkit/src/utils/json.js:44:5)
    at formatWorkspaceJson (/tmp/tmp-315757m69ApOW1FAN/node_modules/@nrwl/workspace/src/generators/workspace/workspace.js:53:18)
    at Object.<anonymous> (/tmp/tmp-315757m69ApOW1FAN/node_modules/@nrwl/workspace/src/generators/workspace/workspace.js:78:9)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/tmp-315757m69ApOW1FAN/node_modules/tslib/tslib.js:114:62)
UPDATE test/.vscode/extensions.json
UPDATE test/angular.json
UPDATE test/nx.json
UPDATE test/package.json
UPDATE test/tsconfig.base.json
(node:31878) ExperimentalWarning: The fs.promises API is experimental

> test@0.0.0 postinstall
> node ./decorate-angular-cli.js


>  NX  Angular CLI has been decorated to enable computation caching.


removed 1161 packages, and audited 1226 packages in 3s

68 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
(node:31904) ExperimentalWarning: The fs.promises API is experimental
Error: A merge conflicted on path "/apps/test/tsconfig.editor.json".
    at other.actions.forEach.action (/home/me/Workspace/test/test/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:142:35)
    at Array.forEach (<anonymous>)
    at HostTree.merge (/home/me/Workspace/test/test/node_modules/@angular-devkit/schematics/src/tree/host-tree.js:131:23)
    at MapSubscriber.call_1.callSource.pipe.operators_1.map.sourceTree [as project] (/home/me/Workspace/test/test/node_modules/@angular-devkit/schematics/src/rules/base.js:54:91)
    at MapSubscriber._next (/home/me/Workspace/test/test/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/home/me/Workspace/test/test/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TapSubscriber._next (/home/me/Workspace/test/test/node_modules/rxjs/internal/operators/tap.js:65:26)
    at TapSubscriber.Subscriber.next (/home/me/Workspace/test/test/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (/home/me/Workspace/test/test/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (/home/me/Workspace/test/test/node_modules/rxjs/internal/Subscriber.js:66:18)
A merge conflicted on path "/apps/test/tsconfig.editor.json".
Workspace creation failed, see above.

>  NX   ERROR  Something went wrong! v12.0.1

(node:31575) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new test --no-interactive --preset=angular-nest --appName=test --style=scss --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=angular --nxWorkspaceRoot="/home/me/Workspace/test"
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at /home/me/.npm/_npx/505743838affa773/node_modules/create-nx-workspace/bin/create-nx-workspace.js:449:29
    at Generator.throw (<anonymous>)
    at rejected (/home/me/.npm/_npx/505743838affa773/node_modules/tslib/tslib.js:115:69)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:31575) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31575) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by leosvelperez** [comment]
I'm closing this since it seems to be a duplicate of #5287. You can continue to follow any updates there.
