### ISSUE TITLE
Cannot install NX or CLI due to Tao version mismatch

### ISSUE THREAD

**Issue by jagannathsrs** [nrwl/nx#5327]
## Current Behavior

When trying to install NX or CLI iva npm, it errors out saying `No matching version found for @nrwl/tao@12.99.0.`
## Expected Behavior

It should be looking for available versions
## Steps to Reproduce

Try to install NX or @nrwl/cli on a global scope or a project without a package lock.

### Failure Logs

```
❯ npm i @nrwl/cli
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/tao@12.99.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@nrwl/cli'
npm ERR! notarget
```

**Comment by bstruthers** [comment]
The `migrate` command is also failing due to version `12.99.0`. 

```
ERROR  The migrate command failed.

Command failed: yarn add @nrwl/workspace@latest
error Couldn't find any versions for "@nrwl/cli" that matches "12.99.0"
Error: Couldn't find any versions for "@nrwl/devkit" that matches "12.99.0"
    at MessageError.ExtendableBuiltin (C:\Users\strub01\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:721:66)
```

**Comment by jagannathsrs** [comment]
`npm i nx@12.0.1` is failing as well.

**Comment by aemonm** [comment]
so is `npm i -D @nrwl/storybook`

**Comment by joejordanbrown** [comment]
It seems the release 12.0.2 that was published 1 hour ago is broken. 

I've just had to set the version to 12.0.1 when installing a package.

Example:
```
npm install -D @nrwl/nest@12.0.1
```

**Comment by devsezer** [comment]
npx create-nx-workspace@12.0.1 is working.

**Comment by jagannathsrs** [comment]
```
❯ npm i nx@12.0.1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/tao@12.99.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@nrwl/cli'
npm ERR! notarget
```

Getting the same error even when using 12.0.1

**Comment by jagannathsrs** [comment]
> It seems the release 12.0.2 that was published 1 hour ago is broken.
> 
> I've just had to set the version to 12.0.1 when installing a package.
> 
> Example:
> 
> ```
> npm install -D @nrwl/nest@12.0.1
> ```

I don't think nest has the dependency of Tao.

**Comment by arilaen** [comment]
Was able to get around this with `npm i @nrwl/cli@12.0.1` (also see related issue that happened a few months ago: https://github.com/nrwl/nx/issues/4311)

**Comment by sgomanf** [comment]
same issue 12.0.2 version is broken

**Comment by jredl-va** [comment]
In terms of the migrate command this worked for me:

```
nx migrate @nrwl/workspace@12.0.1
```

**Comment by bjornharvold** [comment]
12.0.2 is broken. 12.0.1 worked for me.

**Comment by Crocsx** [comment]
Similar here, latest give me 

```
Command failed: npm install --legacy-peer-deps @nrwl/workspace@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/linter@12.99.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@nrwl/workspace'
npm ERR! notarget 
```

**Comment by TristanTouchain** [comment]
#5333

**Comment by FrozenPandaz** [comment]
Sorry all,

12.0.3 was published to resolve the issue.

12.0.2 was mispublished so I deprecated it and you should use 12.0.3 or 12.0.1 instead.

**Comment by bstruthers** [comment]
Can confirm that the `migrate` command is working as expected now.  Thank you, @FrozenPandaz

**Comment by jagannathsrs** [comment]
Can confirm `npm i -g nx` and `npm i -g @nrwl\cli` are working. Thank you @FrozenPandaz !

**Comment by magallegos1996** [comment]
I'm having this issue again: https://github.com/nrwl/nx/issues/5327#issue-856394660

**Comment by dustinlacewell** [comment]
I am getting this issue again on 12.0.7

```
npx --ignore-existing create-nx-workspace@12.0.7 react-ecs
npx: installed 48 in 3.349s
✔ What to create in the new workspace · next
✔ Application name                    · site
✔ Default stylesheet format           · scss
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.


>  NX   ERROR  Something went wrong! v12.0.7

(node:19160) UnhandledPromiseRejectionWarning: Error: Command failed: npm install --silent
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createSandbox (/home/ldlework/.npm/_npx/19160/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:417:21)
    at /home/ldlework/.npm/_npx/19160/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:112:24
    at Generator.next (<anonymous>)
    at fulfilled (/home/ldlework/.npm/_npx/19160/lib/node_modules/create-nx-workspace/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
