### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by artem-a** [nrwl/nx#5351]
Hi, I'm trying to install nx cli and getting an issue of broken dependencies

Here is the output
```
$ sudo npm i -g nx
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/tao@12.99.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@nrwl/cli'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-14T18_25_21_544Z-debug.log
```
Here is the log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '-g', 'nx' ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose npm-session 9d5d7e329e2fd411
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/nx 462ms (from cache)
8 silly pacote tag manifest for nx@latest fetched in 471ms
9 timing stage:loadCurrentTree Completed in 495ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule nx@12.0.5 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@nrwl%2fcli 313ms (from cache)
18 silly pacote range manifest for @nrwl/cli@* fetched in 321ms
19 silly resolveWithNewModule @nrwl/cli@12.0.5 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/tmp 135ms (from cache)
21 silly pacote version manifest for tmp@0.0.33 fetched in 141ms
22 silly resolveWithNewModule tmp@0.0.33 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/yargs 328ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/v8-compile-cache 326ms (from cache)
25 silly pacote version manifest for yargs@15.4.1 fetched in 334ms
26 silly resolveWithNewModule yargs@15.4.1 checking installable status
27 http fetch GET 304 https://registry.npmjs.org/chalk 329ms (from cache)
28 http fetch GET 304 https://registry.npmjs.org/yargs-parser 332ms (from cache)
29 silly pacote version manifest for v8-compile-cache@2.3.0 fetched in 330ms
30 silly resolveWithNewModule v8-compile-cache@2.3.0 checking installable status
31 silly pacote version manifest for chalk@4.1.0 fetched in 332ms
32 silly resolveWithNewModule chalk@4.1.0 checking installable status
33 silly pacote version manifest for yargs-parser@20.0.0 fetched in 337ms
34 silly resolveWithNewModule yargs-parser@20.0.0 checking installable status
35 http fetch GET 200 https://registry.npmjs.org/@nrwl%2ftao 2103ms
36 silly fetchPackageMetaData error for @nrwl/tao@12.99.0 No matching version found for @nrwl/tao@12.99.0.
37 timing stage:rollbackFailedOptional Completed in 0ms
38 timing stage:runTopLevelLifecycles Completed in 2953ms
39 verbose type version
40 verbose stack @nrwl/tao: No matching version found for @nrwl/tao@12.99.0.
40 verbose stack     at pickManifest (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:122:13)
40 verbose stack     at /usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14
40 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
40 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
40 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
40 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
40 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
40 verbose stack     at _drainQueueStep (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
40 verbose stack     at _drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
40 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
40 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
40 verbose stack     at processImmediate (internal/timers.js:461:21)
41 verbose cwd /home/artem/Work/js/ts-apps/oop
42 verbose Linux 5.4.0-70-generic
43 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "nx"
44 verbose node v14.16.1
45 verbose npm  v6.14.12
46 error code ETARGET
47 error notarget No matching version found for @nrwl/tao@12.99.0.
48 error notarget In most cases you or one of your dependencies are requesting
48 error notarget a package version that doesn't exist.
48 error notarget
48 error notarget It was specified as a dependency of '@nrwl/cli'
49 verbose exit [ 1, true ]

```

**Comment by justinrassier** [comment]
Similar error happens if you run `nx migrate latest`

**Comment by adavis26** [comment]
Also experiencing this issue, it is blocking our deployments: 
![image](https://user-images.githubusercontent.com/41963628/114765397-bcffcc80-9d2a-11eb-8353-55b18524d3f5.png)

**Comment by FrozenPandaz** [comment]
Sorry, 12.0.5 is a mispublish. 12.0.6 has been published and the issues should be resolved.

**Comment by justinrassier** [comment]
@FrozenPandaz it looks like there is still something going on with dependency versions when running `nx migrate latest`

![image](https://user-images.githubusercontent.com/1228424/114767492-4d3f1100-9d2d-11eb-8397-5e42ea243f71.png)


If you would like me to put in a new ticket, I can!

**Comment by artem-a** [comment]
@FrozenPandaz Thanks, now it works fine.

**Comment by FrozenPandaz** [comment]
@justinrassier give Npm some time to propogate the version and try again. Let me know if it still does not work.

**Comment by justinrassier** [comment]
@FrozenPandaz  Not sure how long it takes for all changes to propagate, or if this is yet another one:

![image](https://user-images.githubusercontent.com/1228424/114772528-85e1e900-9d33-11eb-9914-4456a7948b0d.png)


I will wait another hour and try it out again. Just wanted to keep you updated.

**Comment by justinrassier** [comment]
@FrozenPandaz FYI still having issues

**Comment by FrozenPandaz** [comment]
Thanks for the updates.

Are you perhaps behind a private npm registry or a proxy?

I have noticed npm has taken longer recently to propagate the versions.

The two errors you posted are different so it is catching up slowly.

`@nrwl/devkit@12.0.6` does exist though. I can see it here:

https://www.npmjs.com/package/@nrwl/devkit
https://unpkg.com/browse/@nrwl/devkit@12.0.6/package.json

Stay patient :crossed_fingers:.

**Comment by justinrassier** [comment]
Thanks for the response!

I set my registry back to regular old npm, so it shouldn't be a problem with our internal registry. I'm fine with waiting a bit, just wanted to make sure you had all the information you needed to look into it. 

Thanks again!

**Comment by justinrassier** [comment]
I had a different `.npmrc` file hanging out still pointing at our internal registry. Whoops! So sorry about that. Pointed at public npm and everything installed great.

**Comment by FrozenPandaz** [comment]
Awesome, glad it's working for you :+1:

Closing this issue as it's resolved.
