### ISSUE TITLE
Error on build to production [Angular][ENOENT: no such file or directory, open '\package.json']

### ISSUE THREAD

**Issue by ronaldohoch** [nrwl/nx#5361]
## Current Behavior
Build don't finish.

## Expected Behavior
The build should over without errors

## Steps to Reproduce

Run 

`npx create-nx-workspace`
```shell
npx: instalou 38 em 6.518s
√ Workspace name (e.g., org name)     · production-build-error
√ What to create in the new workspace · angular
√ Application name                    · app-shell
√ Default stylesheet format           · scss 
√ Default linter                      · eslint
√ Use Nx Cloud? (It's free and doesn't require registration.) · No

```

(Generated by Nx Console extension from vsCode)
then:

`ng generate @nrwl/angular:application --name=app-content --routing`

Add the module-federation to the projects:

`ng add @angular-architects/module-federation --project app-shell --port 4200`

`ng add @angular-architects/module-federation --project app-content --port 4201`

Then, configure the webpack.config.js from app-shell and app-content:

```javascript
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");
const path = require("path");

const sharedMappings = new mf.SharedMappings();
sharedMappings.register(
  path.join(__dirname, '../../tsconfig.base.json'),
  [/* mapped paths to share */]);

module.exports = {
  output: {
    uniqueName: "appShell"
  },
  optimization: {
    runtimeChunk: false
  },
  plugins: [
    new ModuleFederationPlugin({
        remotes: {
          "appContent": "appContent@http://localhost:4201/remoteEntry.js",
        },

        shared: {
          "@angular/core": { singleton: true, strictVersion: true }, 
          "@angular/common": { singleton: true, strictVersion: true }, 
          "@angular/router": { singleton: true, strictVersion: true },

          ...sharedMappings.getDescriptors()
        }
        
    }),
    sharedMappings.getPlugin(),
  ],
};

```

```javascript
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");
const path = require("path");

const sharedMappings = new mf.SharedMappings();
sharedMappings.register(
  path.join(__dirname, '../../tsconfig.base.json'),
  [/* mapped paths to share */]);

module.exports = {
  output: {
    uniqueName: "appContent"
  },
  optimization: {
    runtimeChunk: false
  },
  plugins: [
    new ModuleFederationPlugin({
        name: "appContent",
        filename: "remoteEntry.js",
        exposes: {
            './Component': './apps/app-content/src/app/app.component.ts',
        },
        shared: {
          "@angular/core": { singleton: true, strictVersion: true }, 
          "@angular/common": { singleton: true, strictVersion: true }, 
          "@angular/router": { singleton: true, strictVersion: true },

          ...sharedMappings.getDescriptors()
        }
        
    }),
    sharedMappings.getPlugin(),
  ],
};

```

Added the route to MFE in app-shell app.module.ts

```typescript
import { loadRemoteModule } from '@angular-architects/module-federation';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    RouterModule.forRoot([
      {
        path: 'content',
        loadChildren: () =>
          loadRemoteModule({
            remoteEntry: 'http://localhost:4201/remoteEntry.js',
            remoteName: 'appContent',
            exposedModule: './Component',
          }).then((m) => m.AdminPanelModule),
      },
    ])
  ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule { }
```

then...

`ng build --prod app-content`

the log:

```shell
> nx run content:build:production 
✔ Browser application bundle generation complete.
ENOENT: no such file or directory, open '\package.json'
```

### Failure Logs
```shell
> nx run content:build:production 
✔ Browser application bundle generation complete.
ENOENT: no such file or directory, open '\package.json'
```

### Environment
npm nx --version: 6.14.10
@angular-architects/module-federation: 1.2.3
Angular CLI: 11.2.8
Node: 14.15.4
OS: win32 x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.8 (cli-only)      
@angular-devkit/core         11.2.8 (cli-only)        
@angular-devkit/schematics   11.2.8 (cli-only)        
@schematics/angular          11.2.8 (cli-only)        
@schematics/update           0.1102.8 (cli-only)

## npx nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 12.0.6
  @nrwl/cli : 12.0.6
  @nrwl/cypress : 12.0.6
  @nrwl/devkit : 12.0.6
  @nrwl/eslint-plugin-nx : 12.0.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.6
  @nrwl/linter : 12.0.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.6
  @nrwl/web : Not Found
  @nrwl/workspace : 12.0.6
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by ronaldohoch** [comment]
Things i've found until now..:

2 possible solutions for what happened:
1st - I had 2 components inside libs/ui using the same tag "dina-tabs", I fixed that.
2nd - I was adding a scss directly to angular.json for each project, and it wasn’t working,

"styles": [
   "projects/emkt-config/src/styles.scss",
   "projects/ui/src/lib/web/style/theme.scss"
 ],
I took it from angular.json and added it to styles.scss with @import and it's building.

But, i've made it to my two projects, one using NX and other not using NX, the project using NX still throwing the error


```
C:\Users\ronal\Documents\projetos\dinamize\MFE>ng build emkt-config --prod --verbose
Your global Angular CLI version (11.2.8) is greater than your local version (11.0.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

> nx run emkt-config:build:production --verbose 
✔ Browser application bundle generation complete.
ENOENT: no such file or directory, open '\package.json'
HookWebpackError: ENOENT: no such file or directory, open '\package.json'
    at makeWebpackError (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\lib\Compilation.js:1995:11
    at _next4 (eval at create (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:19:1)      
    at eval (eval at create (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:49:1)        
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- inner error --
Error: ENOENT: no such file or directory, open '\package.json'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at CacheBackend.provideSync (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:233:32)
    at WebpackFileSystem.readFileAsUtf8 (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:52:24)
    at PluginChunkReadHandler.getPackageJson (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:35:43)        
    at PluginChunkReadHandler.processModule (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:45:40)
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:29:23
    at WebpackModuleFileIterator.internalCallback (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:28:13)
    at WebpackModuleFileIterator.iterateFiles (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:8:9)      
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:27:32
    at WebpackChunkModuleIterator.iterateModules (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\WebpackChunkModuleIterator.js:39:21)
    at PluginChunkReadHandler.processChunk (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:26:29)
    at _loop_1 (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:89:37)
    at WebpackCompilerHandler.iterateChunks (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:124:17)        
    at C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:41:31
    at _next4 (eval at create (C:\Users\ronal\Documents\projetos\dinamize\MFE\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)    
```

**Comment by Coly010** [comment]
Hi @ronaldohoch 

I would like to rule out if this might be a Windows-specific issue.

Using the reproduction steps you gave, and using Nx v12.1.0 & Nx v12.0.6 on PopOS(Linux), I was able to get the production bundle building without error.

```
> nx run app-content:build:production 
✔ Browser application bundle generation complete.
⠋ Copying assets...✔ Browser application bundle generation complete.
(node:247353) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_INDEXER] DeprecationWarning: chunk.files was changed from Array to Set (indexing Array is deprecated)
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files               | Names      |      Size
polyfills.8f3f048c93dd7bb8b018.js | polyfills  |  42.30 kB
styles.cfcf1d93134d6e9a1008.js    | styles     |   9.67 kB
remoteEntry.js                    | appContent |   7.44 kB
main.4a9574ab1bf9eb9bd4bb.js      | main       |   6.95 kB

Lazy Chunk Files                  | Names      |      Size
135.8f5c2706c2435cbcd8ce.js       | -          | 242.03 kB
463.b1b7d1ef7e094535adac.js       | -          |  78.89 kB
374.2afa27aaff6ae6a6c5f6.js       | -          |  56.55 kB
810.4ad315c5ff976c91023f.js       | -          |  20.34 kB
718.c28d28237671a52e3633.js       | -          |  18.04 kB
38.d2b9f5b08233e8d84749.js        | -          |   7.59 kB

3 unchanged chunks

Build at: 2021-05-05T10:54:01.527Z - Hash: 6c3cd7562f62554d875c - Time: 12181ms
```

I _did_ have to use `yarn` to install the dependencies and force usage of `webpack@5.72.2` by adding:

```json
  "resolutions": {
    "webpack": "5.27.2"
  }
```

to my root `package.json` file.

---

To help us narrow down the cause of this issue could you try the following for me please:

1. Retry your reproduction steps using `npx create-nx-workspace@latest`
2. Add the following to your `package.json`:
  ```json
  "resolutions": {
    "webpack": "5.27.2"
  }
```
3. Delete your `node_modules` folder
4. Use [yarn](https://yarnpkg.com/) to install your dependencies with the following command: `yarn`
5. Set up your applications with MFE as per your reproduction steps
6. Run `ng build --prod app-content`

---

### Some Concerns

Some concerns I do have with using `webpack@5.72.2`:
 - `@angular-devkit` has a peer dependency of `webpack@4.44.2`. 
   - This could potentially lead to erroneous results
