### ISSUE TITLE
ERR_INVALID_PERFORMANCE_MARK in Node 16

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#5436]
## Current Behavior
Task runner fails with Node 16

## Expected Behavior
Apps should be able to compile, serve, etc

## Steps to Reproduce
Create a new workspace with node 16 and try to do something (build, test, etc)

### Failure Logs
```
Unexpected error:
Error [ERR_INVALID_PERFORMANCE_MARK]: The "command-execution-begins" performance mark has not been set
    at new NodeError (node:internal/errors:363:5)
    at getMark (node:internal/perf/usertiming:49:11)
    at calculateStartDuration (node:internal/perf/usertiming:113:13)
    at EventTarget.measure (node:internal/perf/usertiming:133:7)
    at TaskOrchestrator.<anonymous> (/Users/gperdomor/Downloads/falabella-commerce-config/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:29:38)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/.../workspace/node_modules/tslib/tslib.js:114:62) {
  code: 'ERR_INVALID_PERFORMANCE_MARK'
```
¡

**Comment by redaxmedia** [comment]
This error is still present as of 05.07.2021...
