### ISSUE TITLE
Can't create workspace with --bazel flag

### ISSUE THREAD

**Issue by mikekamornikov** [nrwl/nx#545]
I can't get through "Running the schematics" step from https://blog.nrwl.io/introduction-to-nrwl-bazel-schematics-c391911a5e9f

Deps:
```bash
npm -g ls --depth=0
/Users/mak/.nvm/versions/node/v8.11.2/lib
├── @angular-devkit/schematics@0.6.7
├── @bazel/ibazel@0.3.1
├── @nrwl/bazel@6.0.2
├── @nrwl/schematics@6.0.2
└── npm@5.6.0
```

Creating workspace:
```bash
~/Dev/angulardemo » create-nx-workspace angularbazel --bazel  
                                                                                                 
Creating a sandbox with the CLI and Nx Bazel...
[fsevents] Success: "/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
added 373 packages in 10.592s
ng new "angularbazel" --collection=@nrwl/bazel
Cannot find module '/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/@nrwl/bazel/src/collection/application'
Error: Cannot find module '/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/@nrwl/bazel/src/collection/application'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at new ExportStringRef (/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/@angular-devkit/schematics/tools/export-ref.js:15:32)
    at NodeModulesEngineHost._resolveReferenceString (/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:92:21)
    at NodeModulesEngineHost.createSchematicDescription (/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:167:34)
    at SchematicEngine.createSchematic (/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/@angular-devkit/schematics/src/engine/engine.js:142:38)
    at CollectionImpl.createSchematic (/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/@angular-devkit/schematics/src/engine/collection.js:12:29)
    at Object.getSchematic (/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/@angular/cli/utilities/schematics.js:36:23)
    at NewCommand.getOptions (/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/@angular/cli/models/schematic-command.js:195:40)
    at NewCommand.initialize (/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/@angular/cli/commands/new.js:48:21)
child_process.js:644
    throw err;
    ^

Error: Command failed: /var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32235tHir4IQLhDZj/node_modules/.bin/ng new "angularbazel" --skip-install --collection=@nrwl/bazel
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/@nrwl/schematics/bin/create-nx-workspace.js:83:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
```

@nrwl/bazel/src/collection/application:
```bash
~/Dev/angulardemo » tree /private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32322wc4U9j1vxdRn/node_modules/@nrwl/bazel/src/collection/application         1 ↵
/private/var/folders/td/55yg8f954496rp7km50qnrkh0000gn/T/tmp-32322wc4U9j1vxdRn/node_modules/@nrwl/bazel/src/collection/application
├── files
│   └── __directory__
│       ├── BUILD.bazel
│       ├── README.md
│       ├── WORKSPACE
│       ├── __dot__angular-cli.json
│       ├── __dot__editorconfig
│       ├── __dot__gitignore
│       ├── apps
│       ├── karma.conf.js
│       ├── libs
│       ├── ngc.tsconfig.json
│       ├── package.json
│       ├── protractor.conf.js
│       ├── test.js
│       ├── tools
│       │   └── bazel.rc
│       ├── tsconfig.json
│       ├── tsconfig.spec.json
│       └── tslint.json
└── schema.json

5 directories, 16 files
```

**Comment by matthewharwood** [comment]
@vsavkin are their any plans to add  `ng add @nrwl/schematic --bazel` ?

**Comment by vsavkin** [comment]
Sorry for the late response. 

The bazel support doesn't work with Nx 6. We are planning to make it work, but I'm not 100% sure on the date.

**Comment by dhondiramjawade** [comment]
getting Unknown option: '--bazel'  with nx bazel 
![Screenshot from 2019-11-12 22-33-50](https://user-images.githubusercontent.com/46644972/68693070-9f11c380-059c-11ea-8959-fd5ae806a89c.png)
