### ISSUE TITLE
ng lint --fix and --format failing working for nx workspace

### ISSUE THREAD

**Issue by sdurnov** [nrwl/nx#546]
```
$ ng lint --fix
Architect commands with multiple targets cannot specify overrides.'lint' would be run on the following projects: crionic-website,crionic-website-e2e,shell,models,utils,utils2,utils3,utils4
Error: Architect commands with multiple targets cannot specify overrides.'lint' would be run on the
following projects: crionic-website,crionic-website-e2e,shell,models,utils,utils2,utils3,utils4
    at LintCommand.validate (C:\Users\serge\Documents\Projects\nx\node_modules\@angular\cli\models\architect-command.js:75:23)
    at C:\Users\serge\Documents\Projects\nx\node_modules\@angular\cli\models\command-runner.js:274:39
    at Generator.next (<anonymous>)
    at C:\Users\serge\Documents\Projects\nx\node_modules\@angular\cli\models\command-runner.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\serge\Documents\Projects\nx\node_modules\@angular\cli\models\command-runner.js:3:12)
    at validateAndRunCommand (C:\Users\serge\Documents\Projects\nx\node_modules\@angular\cli\models\command-runner.js:273:12)
    at Object.<anonymous> (C:\Users\serge\Documents\Projects\nx\node_modules\@angular\cli\models\command-runner.js:100:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\serge\Documents\Projects\nx\node_modules\@angular\cli\models\command-runner.js:4:58)
```
"@nrwl/schematics": "6.0.2". Same error for ng lint --format=stylish command

**Comment by vsavkin** [comment]
This is the change in the Angular CLI 6. It no longer allows to run `ng lint` for all the projects.

You can run lint for one project like this:

```
ng lint myapp-or-lib --fix
```

You can also run it for all projects using `affected:*`, like this:

```
yarn affected:lint --files=package.json
```

And you can also do it in parallel:

```
yarn affected:lint --files=package.json --parallel
```
