### ISSUE TITLE
NX ERROR Something went wrong - create-nx-workspace@latest - 

### ISSUE THREAD

**Issue by hadrien-toma** [nrwl/nx#5469]
## Current Behavior

Error when trying to create a workspace from the latest version.

## Expected Behavior

Run the command without any error, correctly creating the workspace.

## Steps to Reproduce

```bash
docker run --rm --interactive --tty node /bin/bash -c "cd && npx --yes create-nx-workspace@latest workspace --preset=empty --cli=nx --interactive=false --nx-cloud=false"
```

### Failure Logs

```bash
>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

⠙ Creating your workspace
>  NX   ERROR  Something went wrong. Rerunning the command with verbose logging.

/workspace is not an empty directory.

>  NX   ERROR  Something went wrong! v12.0.8

node:child_process:690
    err = new Error(msg);
          ^

Error: Command failed: npx tao new workspace --preset=empty --no-interactive --no-nxCloud --appName= --linter=eslint --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot="/"
    at checkExecSyncError (node:child_process:690:11)
    at Object.execSync (node:child_process:727:15)
    at /root/.npm/_npx/505743838affa773/node_modules/create-nx-workspace/bin/create-nx-workspace.js:464:29
    at Generator.throw (<anonymous>)
    at rejected (/root/.npm/_npx/505743838affa773/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 104,
  stdout: null,
  stderr: null
}
npm notice 
npm notice New minor version of npm available! 7.6.3 -> 7.11.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.11.1
npm notice Run npm install -g npm@7.11.1 to update!
npm notice
```

### Environment

```
docker run --rm --interactive --tty node /bin/bash -c "node -v ; npx -v"
v15.12.0
7.6.3
```

**Comment by iamandrewluca** [comment]
That is strange. I tried both `v12.0.8` (latest) and `v11.6.3` same error

```
➜  iamandrewluca rm -rf code4moldova 
➜  iamandrewluca npx create-nx-workspace@11.6.3
npx: installed 66 in 4.679s
? Workspace name (e.g., org name)     code4moldova
? What to create in the new workspace empty             [an empty workspace with a layout that works best for building apps]
? Use Nx Cloud? (It's free and doesn't require registration.) No

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

⠋ Creating your workspace
>  NX   ERROR  Something went wrong. Rerunning the command with verbose logging.

/home/iamandrewluca/Projects/github.com/iamandrewluca/code4moldova is not an empty directory.
(node:15806) UnhandledPromiseRejectionWarning: Error: Command failed: npx tao new code4moldova --no-interactive --preset=empty --appName= --linter=eslint --no-nxCloud --collection=@nrwl/workspace/collection.json --cli=nx --nxWorkspaceRoot="/home/iamandrewluca/Projects/github.com/iamandrewluca"
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at /home/iamandrewluca/.npm/_npx/15806/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:439:29
    at Generator.throw (<anonymous>)
    at rejected (/home/iamandrewluca/.npm/_npx/15806/lib/node_modules/create-nx-workspace/node_modules/tslib/tslib.js:113:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15806) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15806) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

Could you try with Nx 12.1?  I changed how create-nx-workspace, so `Rerunning the command with verbose logging.` should never appear. It won't fix the command in your env, but it will show the real error message.

Thank you!

**Comment by hadrien-toma** [comment]
Thanks for your comments :+1:.

I changed the command a little bit in order to be able to mount the produced log file:

- New command to reproduce:

```bash
mkdir $(pwd)/tmp-nx-test ; docker run --rm --interactive --user node -v "$(pwd)/tmp-nx-test:/tmp" --tty node /bin/bash -c "cd && npx --yes create-nx-workspace@latest workspace --preset=empty --cli=nx --interactive=false --nx-cloud=false"
```

- Error in `stdout`:

```bash
>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.

⠼ Creating your workspace
>  NX   ERROR  Nx failed to create a workspace.

  Exit code: 1
  Log file: /tmp/tmp-19-eLGOxXgKqQF6/error.log


>  NX   SUCCESS  Nx has successfully created the workspace.


———————————————————————————————————————————————


>  NX   NOTE  Nx CLI is not installed globally.

  This means that you might have to use "yarn nx" or "npx nx" to execute commands in the workspace.
  Run "yarn global add nx" or "npm install -g nx" to be able to execute command directly.
```

- Content of `$(pwd)/tmp-nx-text/tmp-19-eLGOxXgKqQF6/error.log`:

```bash
CREATE workspace/README.md
CREATE workspace/.editorconfig
CREATE workspace/.gitignore
CREATE workspace/.prettierignore
CREATE workspace/.vscode/extensions.json
CREATE workspace/workspace.json
CREATE workspace/nx.json
CREATE workspace/package.json
CREATE workspace/tools/generators/.gitkeep
CREATE workspace/tools/tsconfig.tools.json
CREATE workspace/tsconfig.base.json
CREATE workspace/.prettierrc
CREATE workspace/apps/.gitkeep
CREATE workspace/libs/.gitkeep

added 204 packages, and audited 205 packages in 21s

36 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'node@fdcb861620a2.(none)')
```

So I added `--skip-git=true` at the end of the command like:

```bash
docker run --rm --interactive --user node -v "$(pwd)/tmp-nx-test:/tmp" --tty node /bin/bash -c "cd && npx --yes create-nx-workspace@latest workspace --preset=empty --cli=nx --interactive=false --nx-cloud=false --skip-git=true
```

And the workspace creation ended in a success, so I close the issue. Thanks again for your comments and support :blush:.
