### ISSUE TITLE
nx run `<custom command>` does not display full error messages

### ISSUE THREAD

**Issue by the-ult** [nrwl/nx#5472]
## Current Behavior
When running a custom command, in this case [graphql-code-generator](https://www.graphql-code-generator.com/), the error messages are not shown. 
The custom commands seems to filter/mask/hide them.

## Expected Behavior
Would expect to see the same error message, as when the _script_ is run in the terminal

## Steps to Reproduce
custom command:
```json
"codegen-server": {
        "builder": "@nrwl/workspace:run-commands",
        "options": {
           "color": true,
            "commands": [
              {
                "command": "npx graphql-codegen --config apps/ddb-graphql-server/server.codegen.yml"
              }
            ]
          }
```
results in:
```console
❯ nx run ddb-graphql-server:codegen-server

> nx run ddb-graphql-server:codegen-server 
[09:51:00] Parse configuration [started]
[09:51:00] Parse configuration [completed]
[09:51:00] Generate outputs [started]
[09:51:00] Generate to ./apps/ddb-graphql-server/src/app/ (using EXPERIMENTAL preset "graphql-modules") [started]
[09:51:00] Generate ./tools/graphql/__generated__/types.graphql-gen.__generated__.ts [started]
[09:51:00] Generate ./tools/graphql/__generated__/schema.__generated__.json [started]
[09:51:00] Generate ./tools/graphql/__generated__/possible-types.__generated__.ts [started]
[09:51:00] Load GraphQL schemas [started]
[09:51:00] Load GraphQL schemas [started]
[09:51:00] Load GraphQL schemas [started]
[09:51:00] Load GraphQL schemas [started]
[09:51:00] Load GraphQL schemas [failed]
[09:51:00] → Failed to load schema
[09:51:00] Generate to ./apps/ddb-graphql-server/src/app/ (using EXPERIMENTAL preset "graphql-modules") [failed]
[09:51:00] → Failed to load schema
[09:51:00] Generate ./tools/graphql/__generated__/type-policies.__generated__.ts [started]
[09:51:00] Load GraphQL schemas [started]
[09:51:00] Load GraphQL schemas [failed]
[09:51:00] → Failed to load schema
[09:51:00] Generate ./tools/graphql/__generated__/types.graphql-gen.__generated__.ts [failed]
[09:51:00] → Failed to load schema
[09:51:00] Generate ./tools/graphql/__generated__/schema.__generated__.graphql [started]
[09:51:00] Load GraphQL schemas [started]
[09:51:00] Load GraphQL schemas [failed]
[09:51:00] → Failed to load schema
[09:51:00] Generate ./tools/graphql/__generated__/schema.__generated__.json [failed]
[09:51:00] → Failed to load schema
[09:51:00] Load GraphQL schemas [failed]
[09:51:00] → Failed to load schema
[09:51:00] Generate ./tools/graphql/__generated__/possible-types.__generated__.ts [failed]
[09:51:00] → Failed to load schema
[09:51:00] Load GraphQL schemas [failed]
[09:51:00] → Failed to load schema
[09:51:00] Generate ./tools/graphql/__generated__/type-policies.__generated__.ts [failed]
[09:51:00] → Failed to load schema
[09:51:00] Load GraphQL schemas [failed]
[09:51:00] → Failed to load schema
[09:51:00] Generate ./tools/graphql/__generated__/schema.__generated__.graphql [failed]
[09:51:00] → Failed to load schema
[09:51:00] Generate outputs [failed]
Something went wrong
Warning: @nrwl/run-commands command "npx graphql-codegen --config apps/ddb-graphql-server/server.codegen.yml" exited with non-zero status code%   
```

Running the _script_  `npx graphql-codegen --config apps/ddb-graphql-server/server.codegen.yml` standalone in the terminal shows better formatting, colors and the actual error, so we know what we have to fix.

```console
❯ npx graphql-codegen --config apps/ddb-graphql-server/server.codegen.yml
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate to ./apps/ddb-graphql-server/src/app/ (using EXPERIMENTAL preset "graphql-modules")
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate
    ❯ Generate ./tools/graphql/__generated__/types.graphql-gen.__generated__.ts
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate
    ❯ Generate ./tools/graphql/__generated__/schema.__generated__.json
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate
    ❯ Generate ./tools/graphql/__generated__/possible-types.__generated__.ts
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate
    ❯ Generate ./tools/graphql/__generated__/type-policies.__generated__.ts
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate
    ❯ Generate ./tools/graphql/__generated__/schema.__generated__.graphql
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate


 Found 6 errors

  ✖ ./apps/ddb-graphql-server/src/app/
    Failed to load schema from ./apps/ddb-graphql-server/src/app/**/*.graphql,./apps/ddb-gupo/src/app/client.schema.graphql:

        Unknown type: "JSON".
        Error: Unknown type: "JSON".
    at getNamedType (.../node_modules/graphql/utilities/extendSchema.js:360:13)
    at getWrappedType (.../node_modules/graphql/utilities/extendSchema.js:375:12)
    at buildFieldMap (.../node_modules/graphql/utilities/extendSchema.js:409:17)

 ... and more
```

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 15.14.0
  OS   : darwin x64
  npm  : 7.11.1
  
  nx : Not Found
  @nrwl/angular : 12.0.8
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : 12.0.8
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.0.8
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by vsavkin** [comment]
Thank you for submitting the issue!

What happens if you pass --verbose when you invoke the command?

**Comment by the-ult** [comment]
Verbose gives the same formattig:
```
❯ nx run ddb-graphql-server:codegen-server --verbose

> nx run ddb-graphql-server:codegen-server --verbose 
[21:45:40] Parse configuration [started]
[21:45:40] Parse configuration [completed]
[21:45:40] Generate outputs [started]
[21:45:40] Generate to ./apps/ddb-graphql-server/src/app/ (using EXPERIMENTAL preset "graphql-modules") [started]
[21:45:40] Generate ./tools/graphql/__generated__/types.graphql-gen.__generated__.ts [started]
[21:45:40] Generate ./tools/graphql/__generated__/schema.__generated__.json [started]
[21:45:40] Generate ./tools/graphql/__generated__/possible-types.__generated__.ts [started]
[21:45:40] Load GraphQL schemas [started]
[21:45:40] Load GraphQL schemas [started]
[21:45:40] Load GraphQL schemas [started]
[21:45:40] Load GraphQL schemas [started]
[21:45:40] Load GraphQL schemas [completed]
[21:45:40] Load GraphQL documents [started]
[21:45:40] Load GraphQL documents [completed]
[21:45:40] Generate [started]
[21:45:40] Generate [completed]
[21:45:40] Generate to ./apps/ddb-graphql-server/src/app/ (using EXPERIMENTAL preset "graphql-modules") [completed]
[21:45:40] Generate ./tools/graphql/__generated__/type-policies.__generated__.ts [started]
[21:45:40] Load GraphQL schemas [started]
[21:45:40] Load GraphQL schemas [completed]
[21:45:40] Load GraphQL documents [started]
[21:45:40] Load GraphQL documents [completed]
```

the npx command:
```
❯ npx graphql-codegen --config apps/ddb-graphql-server/server.codegen.yml
  ✔ Parse configuration
  ✔ Generate outputs
```

(with the npx command it seemed to 'flash', the log was replaced with the _shorter_ log like above)

**Comment by the-ult** [comment]
@vsavkin any idea what could be causing this?
Do you need any more information?

**Comment by vsavkin** [comment]
@the-ult could you try adding "parallel": false to the list of options?

or changing it to this:

```
{
  "builder": "@nrwl/workspace:run-commands",
        "options": {
           "color": true,
           "command": "npx graphql-codegen --config apps/ddb-graphql-server/server.codegen.yml"
         }
}
```

Using 1 command will set parallel to false.

**Comment by the-ult** [comment]
Hey @vsavkin 

Indeed. both `"parallel": false` and the single `command` fixes the output issue. 👍

**Comment by the-ult** [comment]
Hey @vsavkin 

Both `"parallel": false` and the single `command` seem to work for a single command

```
❯ nx run ddb-graphql-server:codegen-server
  ✔ Parse configuration
  ❯ Generate outputs
  ✔ Parse configuration
  ✔ Generate outputs
```

However, running with `run-many` seems to fail

```
// base command works
❯ npx graphql-codegen --config libs/gupo/feature-dashboard/client.codegen.yml
  ✔ Parse configuration
  ✔ Generate outputs
```
```
// NX command works
❯ nx run gupo-feature-dashboard:codegen
  ✔ Parse configuration
  ✔ Generate outputs
```
``` 
// npm script works
❯ npm run codegen:dashboard

> ddb-dpf-backoffice-workspace@0.0.0 codegen:dashboard
> nx run gupo-feature-dashboard:codegen

  ✔ Parse configuration
  ✔ Generate outputs

```
❯ npm run codegen:clients
// nx run-many seems to fail

> ddb-dpf-backoffice-workspace@0.0.0 codegen:clients
> nx run-many --all --target=codegen


>  NX  Running target codegen for 13 project(s):
  
  ...
  - gupo-feature-dashboard
  ...

———————————————————————————————————————————————

...

> nx run gupo-feature-dashboard:codegen 
[21:28:14] Parse configuration [started]
[21:28:14] Parse configuration [completed]
[21:28:14] Generate outputs [started]
[21:28:14] Generate to src/ (using EXPERIMENTAL preset "near-operation-file") [started]
[21:28:14] Load GraphQL schemas [started]
[21:28:14] Load GraphQL schemas [completed]
[21:28:14] Load GraphQL documents [started]
[21:28:14] Load GraphQL documents [completed]
[21:28:14] Generate [started]
[21:28:14] Generate [completed]
[21:28:14] Generate to src/ (using EXPERIMENTAL preset "near-operation-file") [completed]
[21:28:14] Generate outputs [completed]

... other projects
———————————————————————————————————————————————

>  NX   SUCCESS  Running target "codegen" succeeded
```

**Comment by vsavkin** [comment]
> However, running with run-many seems to fail
What do you mean? Is it the same issue? What run-many commands are you using?

**Comment by the-ult** [comment]
Hi @vsavkin 
Excuses for my late reply (holidays)

We created custom commands like:
```
"codegen": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "color": true,
        "command": "npx graphql-codegen --config libs/gupo/feature-dashboard/client.codegen.yml"
      }
    }
```

Running them like this:
`nx run-many --all --target=codegen` does not parse the output correctly.

However, when you a single command like: `nx run gupo-feature-dashboard:codegen`, the parsing of the messages is correct.

**Comment by the-ult** [comment]
The issue with the incorrect parsing seems to be with the `run-many` command.
