### ISSUE TITLE
Library assets missing on serve

### ISSUE THREAD

**Issue by rkreienbuehl** [nrwl/nx#5546]
## Current Behavior
serving an app with `@nrwl/node:execue` doesn't copy assets from libraries. 

## Expected Behavior
Serving an app should also copy assets from libraries.

## Steps to Reproduce
1. create a node app with `nx g @nrwl/node:app`
2. create a node library with `nx g @nrwl/node:lib --publishable`
3. add font asset
4. use function like `registerFont()` from `canvas`
5. use the library in the app results in an exception `Error: ENOENT: no such file or directory`

Sample project:
[https://github.com/rkreienbuehl/nx-lib-assets](https://github.com/rkreienbuehl/nx-lib-assets)

### Failure Logs
```
Error: ENOENT: no such file or directory, lstat '/Users/rogerkreienbuehl/Projekte/test/nx-lib-assets/dist/apps/assets'
    at Object.realpathSync (fs.js:1643:7)
    at Object.registerFont (/Users/rogerkreienbuehl/Projekte/test/nx-lib-assets/node_modules/canvas/index.js:48:34)
    at Object../libs/sample-lib/src/lib/sample-lib.ts (/Users/rogerkreienbuehl/Projekte/test/nx-lib-assets/dist/apps/sample-app/webpack:/libs/sample-lib/src/lib/sample-lib.ts:4:1)
    at __webpack_require__ (/Users/rogerkreienbuehl/Projekte/test/nx-lib-assets/dist/apps/sample-app/webpack:/webpack/bootstrap:19:1)
    at Object../libs/sample-lib/src/index.ts (/Users/rogerkreienbuehl/Projekte/test/nx-lib-assets/dist/apps/sample-app/webpack:/libs/sample-lib/src/index.ts:1:1)
    at __webpack_require__ (/Users/rogerkreienbuehl/Projekte/test/nx-lib-assets/dist/apps/sample-app/webpack:/webpack/bootstrap:19:1)
    at Object../apps/sample-app/src/main.ts (/Users/rogerkreienbuehl/Projekte/test/nx-lib-assets/dist/apps/sample-app/webpack:/apps/sample-app/src/main.ts:1:1)
    at __webpack_require__ (/Users/rogerkreienbuehl/Projekte/test/nx-lib-assets/dist/apps/sample-app/webpack:/webpack/bootstrap:19:1)
    at Object.0 (/Users/rogerkreienbuehl/Projekte/test/nx-lib-assets/dist/apps/sample-app/main.js:152:18)
    at __webpack_require__ (/Users/rogerkreienbuehl/Projekte/test/nx-lib-assets/dist/apps/sample-app/webpack:/webpack/bootstrap:19:1)
```

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 12.19.0
  OS   : darwin x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.1.0
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.1.0
  @nrwl/eslint-plugin-nx : 12.1.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.1.0
  @nrwl/linter : 12.1.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.1.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.1.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.1.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by rkreienbuehl** [comment]
Sorry, my bad, I put the
```
{
  "input": "libs/sample-lib/src/assets",
  "glob": "**/*",
  "output": "assets"
 }
```
into the wrong build section.
