### ISSUE TITLE
[Lint Rule] Using template literals in dynamic import statements throws an error

### ISSUE THREAD

**Issue by jdpearce** [nrwl/nx#5550]
## Current Behavior

When linting a file with dynamic import statements (e.g. a router module) which contain a template literal rather than a normal string, the lint process throws an exception while checking module boundaries:

e.g.

[lint.ts] TypeError: Cannot read property 'startsWith' of undefined
[lint.ts] Occurred while linting <snipped>/router.module.ts:101
[lint.ts]     at isRelative (<snipped>/node_modules/@nrwl/workspace/src/utils/runtime-lint-utils.js:43:14)
[lint.ts]     at Object.isRelativeImportIntoAnotherProject (<snipped>/node_modules/@nrwl/workspace/src/utils/runtime-lint-utils.js:47:10)
[lint.ts]     at run (<snipped>/node_modules/@nrwl/eslint-plugin-nx/src/rules/enforce-module-boundaries.js:88:38)
...

## Expected Behavior

Either linting should pass, or it should warn you about using template literals in dynamic imports.

### Environment

Node : 12.16.3
  OS   : darwin x64
  npm  : 6.14.4
  
  nx : Not Found
  @nrwl/angular : 11.6.1
  @nrwl/cli : 11.6.1
  @nrwl/cypress : 11.6.1
  @nrwl/devkit : 11.6.1
  @nrwl/eslint-plugin-nx : 11.6.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.1
  @nrwl/linter : 11.6.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.6.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.1
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.3

**Comment by jdpearce** [comment]
Looks like this is fixed in the latest version (12.1.0).
