### ISSUE TITLE
V6: Can not get protractor baseUrl to work

### ISSUE THREAD

**Issue by jared-christensen** [nrwl/nx#557]
@angular /cli@6.0.7
@nrwl /schematics@6.0.2

I tried setting baseUrl directly in the potractor.conf.js and also using `ng e2e dashboard-e2e --base-url=http://google.com` with no luck.

I got an error when trying
`npm run affected:e2e -- --base=master --head=HEAD --base-url=https://google.com`

```
Testing dashboard-e2e, forgot-e2e, login-e2e
Schema validation failed with the following errors:
  Data path ".baseUrl" should be string.
/Users/jaredc/Repositories/customer-apps/node_modules/@nrwl/schematics/node_modules/yargs/yargs.js:1101
      else throw err
           ^

Error: Command failed: node /Users/jaredc/Repositories/customer-apps/node_modules/@angular/cli/bin/ng e2e --base-url=https://google.com --baseUrl=https://google.com --project=dashboard-e2e
    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:640:13)
    at /Users/jaredc/Repositories/customer-apps/node_modules/@nrwl/schematics/src/command-line/affected.js:139:29
    at Array.forEach (<anonymous>)
    at e2e (/Users/jaredc/Repositories/customer-apps/node_modules/@nrwl/schematics/src/command-line/affected.js:138:14)
    at Object.affected (/Users/jaredc/Repositories/customer-apps/node_modules/@nrwl/schematics/src/command-line/affected.js:46:13)
    at Object.handler (/Users/jaredc/Repositories/customer-apps/node_modules/@nrwl/schematics/src/command-line/nx.js:19:145)
    at Object.runCommand (/Users/jaredc/Repositories/customer-apps/node_modules/@nrwl/schematics/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/jaredc/Repositories/customer-apps/node_modules/@nrwl/schematics/node_modules/yargs/yargs.js:1014:30)
    at Object.get [as argv] (/Users/jaredc/Repositories/customer-apps/node_modules/@nrwl/schematics/node_modules/yargs/yargs.js:957:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! customer-apps@0.0.1-0 affected:e2e: `nx affected:e2e "--base=master" "--head=HEAD" "--base-url=https://dice.com"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the customer-apps@0.0.1-0 affected:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jaredc/.npm/_logs/2018-05-31T19_59_17_612Z-debug.log
```

**Comment by FrozenPandaz** [comment]
> npm run affected:e2e -- --base=master --head=HEAD --baseUrl=https://google.com

That does indeed work :)

**Comment by jared-christensen** [comment]
@FrozenPandaz Am I dreaming up the issue with the Angular CLI not using the base url I pass it? Was not sure if you just tested the affected:e2e script or if you ran the test and the baseUrl worked.

**Comment by FrozenPandaz** [comment]
Ah sorry... You are right, that does not work right now. But theoretically, it should. Can we keep this issue here closed and track progress in angular/angular-cli#11089?

Thank you.
