### ISSUE TITLE
`wrapAngularDevkitSchematic` fails with Angular 12 component schematic

### ISSUE THREAD

**Issue by ashley-hunter** [nrwl/nx#5681]
## Current Behavior
We have a workspace generator that automates the creation of an Angular Component using `wrapAngularDevkitSchematic`, e.g.:

```typescript
  await wrapAngularDevkitSchematic('@schematics/angular', 'component')(host, {
    name: 'components/' + schema.name,
    project: schema.project,
    style: 'scss',
    changeDetection: 'OnPush',
    export: true,
    prefix: 'uxa',
  });
```

However as of Angular 12 this now fails with the following issue:

```
InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"name":"components/button","project":"button","style":"scss","changeDetection":"OnPush","export":true,"prefix":"uxa","_":[]}
Errors:

  Data path "" must NOT have additional properties(_).
    at MapSubscriber.project (/Users/Ashley/Desktop/universal/node_modules/@angular-devkit/schematics/tools/schema-option-transform.js:30:27)
    at MapSubscriber._next (/Users/Ashley/Desktop/universal/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/Ashley/Desktop/universal/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (/Users/Ashley/Desktop/universal/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (/Users/Ashley/Desktop/universal/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/Users/Ashley/Desktop/universal/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/Users/Ashley/Desktop/universal/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/Ashley/Desktop/universal/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/Users/Ashley/Desktop/universal/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/Users/Ashley/Desktop/universal/node_modules/rxjs/internal/Subscriber.js:66:18) {
  errors: [
    {
      instancePath: '',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: [Object],
      message: 'must NOT have additional properties'
    }
  ]
}
Schematic input does not validate against the Schema: {"name":"components/button","project":"button","style":"scss","changeDetection":"OnPush","export":true,"prefix":"uxa","_":[]}
Errors:

  Data path "" must NOT have additional properties(_).
```

It appears that the ngcli-adapter is adding a property: `"_": []" to the schematics options:

https://github.com/nrwl/nx/blob/ff691343737d4b470aef89723c597769e7299799/packages/tao/src/commands/ngcli-adapter.ts#L765

Which looks like this is causing validation to fail.

Thanks

## Expected Behavior
The schematic options do not get altered by `wrapAngularDevkitSchematic` to prevent option validation from failing.

## Steps to Reproduce

Create a workspace generator with the code shown above.

### Failure Logs
See error above

### Environment

```
Node : 14.16.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.3.3
  @nrwl/cli : 12.3.3
  @nrwl/cypress : 12.3.3
  @nrwl/devkit : 12.3.3
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.3
  @nrwl/linter : 12.3.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.3
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.3
  @nrwl/storybook : 12.3.3
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by vsavkin** [comment]
Thank you for reporting the issue. Fixed it here: https://github.com/nrwl/nx/pull/5693

We are going to cut a patch release later this week which will contain the fix.

**Comment by ashley-hunter** [comment]
Great! Thank you very much!
