### ISSUE TITLE
ng add @angular/pwa fails to find ngsw-config.json on angular cli to nx workspace

### ISSUE THREAD

**Issue by matthewharwood** [nrwl/nx#569]
```
ng new morningharwood --routing
ng generate universal --client-project morningharwood
ng generate app-shell --universal-project  --route=app-shell-path --client-project=morningharwood
ng add @angular/pwa --project morningharwood
ng build --prod
cd dist/morningharwood
http-server
```
Open up inspector go to appication tab and you'll see the service working working as intended.

Ok now lets convert to nx
```
ng add @nrwl/schematics --project morningharwood
npm install --save rxjs-compat 
ng build --prod
```
`ng build --prod ` will fail and throw this error:

```
Error: Expected to find an ngsw-config.json configuration file in the /Users/mharwo/workspace/www/test/morningharwood/apps/morningharwood folder. Either provide one or disable Service Worker in your angular.json configuration file.
Error: Error: Expected to find an ngsw-config.json configuration file in the /Users/mharwo/workspace/www/test/morningharwood/apps/morningharwood folder. Either provide one or disable Service Worker in your angular.json configuration file.
    at SwitchMapSubscriber.host.exists.pipe.operators_1.switchMap.exists [as project] (/Users/mharwo/workspace/www/test/morningharwood/node_modules/@angular-devkit/build-angular/src/angular-cli-files/utilities/service-worker/index.js:91:19)
    at SwitchMapSubscriber._next (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/switchMap.js:90:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Subscriber.js:103:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/Users/mharwo/workspace/www/test/morningharwood/node_modules/@angular-devkit/core/node/host.js:207:17)
    at Observable._trySubscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:177:25)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:162:93)
    at SwitchMapOperator.call (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at MapOperator.call (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/map.js:62:23)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at SwitchMapOperator.call (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at SwitchMapOperator.call (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at SwitchMapOperator.call (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
```

I would guess the project doesnt transfer the `ngsw-config.json`

**Comment by matthewharwood** [comment]
@michelcve
From: https://github.com/angular/angular-cli/issues/10357

> ... I guess that's how service worker works implicitly within the new CLI.

[stackoverflow](https://stackoverflow.com/questions/50196187/after-angular-6-update-ng-build-prod-yields-error-expected-to-find-an-ngsw/50196597#50196597)

If we need the ngswConfigPath where does it go in nx's angular.json, it seems as if this caused errors for others.

**Comment by michelcve** [comment]
My apologies. I didn't have the code available to me during the weekend, so I gave some wrong advice.

I actually removed the `ngswConfigPath` from the `projects->yourproject->architect->configurations` section in the `angular.js` file, and moved the `ngsw-config.json` from the `src` dir to the app's root dir (so, one level up).

I know my case was different from yours, but perhaps it helps.

**Comment by matthewharwood** [comment]
@michelcve yeah the case is a bit different.  But still cannot find the ngsw-config  even when I manually add.

**Comment by Yonet** [comment]
@matthewharwood do you have a repo that we can take a look at? 
There are multiple open related issues, unfortunately, this might take some time to fix.
[pwa with angular 6 does not work #926](https://github.com/angular/devkit/issues/926)

**Comment by matthewharwood** [comment]
@Yonet I've created a repo showcasing `@angular/pwa` working as intended in a vanilla angular-cli project on branch `master`. Then I converted the angular-cli project to an nx workspace, where it then fails, test on branch `nx`.

## Step 1
Test the angular-cli app to see if `@angular/pwa` is working as intended.
# **[repo: run from `master` branch](https://github.com/matthewharwood/nx-569)**

The recreation steps of this repo are verbatim, as follows:
```
ng new morningharwood --routing
ng generate universal --client-project morningharwood
ng generate app-shell --universal-project  --route=app-shell-path --client-project=morningharwood
ng add @angular/pwa --project morningharwood
```
You can confirm a working pwa with the following commands:

```
ng build --prod
cd dist/morningharwood
http-server // or any other local server you have.
```
Or heres a screenshot to confirm: https://imgur.com/a/lrnJ6Zp

#####################################################

## Step2
**Next we need to make this workspace an nx workspace**

# **[repo: run from `nx` branch](https://github.com/matthewharwood/nx-569)**
Or run these steps verbatim:

```
ng add @nrwl/schematics --project morningharwood
npm install --save rxjs-compat 
ng build --prod
```

An on the build you will get the
# **error:**

```
Error: Expected to find an ngsw-config.json configuration file in the /Users/mharwo/workspace/www/test/morningharwood/apps/morningharwood folder. Either provide one or disable Service Worker in your angular.json configuration file.
Error: Error: Expected to find an ngsw-config.json configuration file in the /Users/mharwo/workspace/www/test/morningharwood/apps/morningharwood folder. Either provide one or disable Service Worker in your angular.json configuration file.
    at SwitchMapSubscriber.host.exists.pipe.operators_1.switchMap.exists [as project] (/Users/mharwo/workspace/www/test/morningharwood/node_modules/@angular-devkit/build-angular/src/angular-cli-files/utilities/service-worker/index.js:91:19)
    at SwitchMapSubscriber._next (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/switchMap.js:90:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Subscriber.js:103:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/Users/mharwo/workspace/www/test/morningharwood/node_modules/@angular-devkit/core/node/host.js:207:17)
    at Observable._trySubscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:177:25)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:162:93)
    at SwitchMapOperator.call (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at MapOperator.call (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/map.js:62:23)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at SwitchMapOperator.call (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at SwitchMapOperator.call (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at SwitchMapOperator.call (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/operators/switchMap.js:69:23)
    at Observable.subscribe (/Users/mharwo/workspace/www/test/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
```

# Reason:
When you run `ng add @angular/pwa` the schematic will add/update these files
```
CREATE ngsw-config.json (392 bytes)
CREATE src/assets/icons/icon-128x128.png (1253 bytes)
CREATE src/assets/icons/icon-144x144.png (1394 bytes)
CREATE src/assets/icons/icon-152x152.png (1427 bytes)
CREATE src/assets/icons/icon-192x192.png (1790 bytes)
CREATE src/assets/icons/icon-384x384.png (3557 bytes)
CREATE src/assets/icons/icon-512x512.png (5008 bytes)
CREATE src/assets/icons/icon-72x72.png (792 bytes)
CREATE src/assets/icons/icon-96x96.png (958 bytes)
CREATE src/manifest.json (1085 bytes)
UPDATE angular.json (4128 bytes)
UPDATE package.json (1438 bytes)
UPDATE src/app/app.module.ts (716 bytes)
UPDATE src/index.html (476 bytes)
```
When you run `ng add @nrwl/schematics` the `src/manifest` and the `ngsw-config.json` **do not carry over** to the nx workspace.  Now even when you manually add them after `ng add @nrwl/schematics`, the build step of angular-cli will complain that it cannot find the `ngsw-config.json`.  This is got to be some kind of configuration inside of `angular.json` but I'm just not sure what the key value is and how to wire together nx and or angular-cli to re-link the `ngsw-config.json`. Also mentioned by @michelcve [Stackoverflow](https://stackoverflow.com/questions/50196187/after-angular-6-update-ng-build-prod-yields-error-expected-to-find-an-ngsw/50196597#50196597) that there is some implicit magic going on where you no longer need to configure the ngsw-config in `angular.json` but this fails in nx because that magic link is broken. 

**Solution:**
I'm pretty confident that `@angular/pwa` with nx without much work. we just need nx to resolve link to the`ngsw-config.json`.  Would you have

**Comment by michelcve** [comment]
I checked the NX branch of your repo. Your ngsw-config.json is in the wrong directory. Instead of in the root, it should be in `apps/morningharwood`, as it is app specific.

**Comment by matthewharwood** [comment]
@michelcve ahh I feel so stupid ... thanks!  It works now.

**Comment by matthewharwood** [comment]
@vsavkin  I'm most concerned with the composition of these `ng add` commands. For example, 
angular cli + pwa + nx will fail because the `ngsw-config.json` is misplaced.  This scenerio not a huge blocker but I can see this problem growing.  I see errors getting worse with the next batch of `ng add` commands coming out like `ng add @angular/universal` or `ng add @ngrx/xxx`.   Or what if, `nx` adds a new flag like `ng add @nrwl/schematics --bazel` that flag I'm assuming could have no compatibilities with other schematics but it would be amazing if it was possible. I don't think theres a good solution but I was wondering if you're magical brain had any ideas on how this experience of composition of `ng add` commands could improve?

> Blocked: repro needed:

Repoduction steps (failure in angular-cli + pwa + nx):
```
ng new morningharwood --routing
ng generate universal --client-project morningharwood
ng generate app-shell --universal-project  --route=app-shell-path --client-project=morningharwood
ng add @angular/pwa --project morningharwood
ng build --prod
cd dist/morningharwood
http-server
```
When kept in angular cli the service worker will work.
However, once you add nx: 

```
ng add @nrwl/schematics --project morningharwood
ng build --prod
```
Build will fail.  This is only because the `ngsw-config.json` is now in the wrong directory.  Now this is easy to fix manually but it took me out like a few hours >_<.

**Comment by ndcunningham** [comment]
I tried this a similar setup only however i was already inside an `nx-workspace`  from using `@nrwl/schematics`
**nothing** _service-worker_ related was created example:
```
CREATE ngsw-config.json (392 bytes)
CREATE src/assets/icons/icon-128x128.png (1253 bytes)
CREATE src/assets/icons/icon-144x144.png (1394 bytes)
CREATE src/assets/icons/icon-152x152.png (1427 bytes)
CREATE src/assets/icons/icon-192x192.png (1790 bytes)
CREATE src/assets/icons/icon-384x384.png (3557 bytes)
CREATE src/assets/icons/icon-512x512.png (5008 bytes)
CREATE src/assets/icons/icon-72x72.png (792 bytes)
```

So on inside my existing `nx-workspace` i did 
`ng g app my-pwa-app --service-worker` No service-worker files were created
`ng g app my-pwa-app` => `ng add @angular/pwa --project my-pwa-app`
This added the service-worker dependency inside my `package.json` however thats all it did.

**Comment by vsavkin** [comment]
Are you using Nx 6? 

CLI6 has an independent schematic called Service Worker. And it works with Nx 6. CLI6 no longer has  the "--service-worker" flag.

Btw, it's easy to play with these using Angular Console (https://angularconsole.com/).

Let me know if it makes sense and if you have an issue using the service worker schematic.

**Comment by matthewharwood** [comment]
@vsavkin pretty sure angular console fixes this problem because it's now scoped to the schematics that angular console offers.  Great solve @vsavkin and team.

**Comment by ndcunningham** [comment]
@vsavkin with the advent of the Angular Console this is no longer an issue for me as it simplifies a lot things and in general a visual experience makes it really easy to use. 
Thanks.
