### ISSUE TITLE
With an angular 12 upgrades, my storybook is failing 

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#5732]
My storybook is failing with the following error, 

NX   ERROR  Running target "stories:storybook" failed

Can someone please check this and advise?

**Comment by FrozenPandaz** [comment]
Please provide more information about the issue you are seeing. What is the error? Can you provide a repo?

**Comment by dongood** [comment]
I too am having the same issue.  Migrating from 11.6.1 to 12.3.4.

Very little information is provided.

From terminal:
```
>  NX   ERROR  Running target "cw:storybook" failed

  Failed tasks:
  
  - cw:storybook

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwk@0.0.0 cw-runStorybook: `nx run cw:storybook`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwk@0.0.0 cw-runStorybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[redacted]/.npm/_logs/2021-05-25T02_11_19_161Z-debug.log
The terminal process "zsh '-c', 'npm run cw-runStorybook'" terminated with exit code: 1.
```

Contents of log file (partially redacted)
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'cw-runStorybook'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose run-script [ 'precw-runStorybook', 'cw-runStorybook', 'postcw-runStorybook' ]
5 info lifecycle lwk@0.0.0~precw-runStorybook: lwk@0.0.0
6 info lifecycle lwk@0.0.0~cw-runStorybook: lwk@0.0.0
7 verbose lifecycle lwk@0.0.0~cw-runStorybook: unsafe-perm in lifecycle true
8 verbose lifecycle lwk@0.0.0~cw-runStorybook: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/[redacted]/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle lwk@0.0.0~cw-runStorybook: CWD: /Users/[redacted]
10 silly lifecycle lwk@0.0.0~cw-runStorybook: Args: [ '-c', 'nx run cw:storybook' ]
11 silly lifecycle lwk@0.0.0~cw-runStorybook: Returned: code: 1  signal: null
12 info lifecycle lwk@0.0.0~cw-runStorybook: Failed to exec cw-runStorybook script
13 verbose stack Error: lwk@0.0.0 cw-runStorybook: `nx run cw:storybook`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid lwk@0.0.0
15 verbose cwd /Users/[redacted]/Source Code/Repos/lwk
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "cw-runStorybook"
18 verbose node v14.15.4
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 1
22 error lwk@0.0.0 cw-runStorybook: `nx run cw:storybook`
22 error Exit status 1
23 error Failed at the lwk@0.0.0 cw-runStorybook script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dean-g** [comment]
@dongood Here is the workaround I got it: [5688](https://github.com/nrwl/nx/issues/5688)

**Comment by juristr** [comment]
Closing this as the tracking issue for Storybook & Webpack 5 related issues is #5688
