### ISSUE TITLE
Babel issue @nrwl/web/babel & @nrwl/react/babel: Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by rrooding** [nrwl/nx#5736]
After upgrading Nx to 12.3.4 I'm getting the following error when trying to build React apps: 
`Cannot read property 'android' of undefined`

Snippet from package.json:
```
"@nrwl/cli": "12.3.4",
"@nrwl/cypress": "12.3.4",
"@nrwl/eslint-plugin-nx": "12.3.4",
"@nrwl/express": "12.3.4",
"@nrwl/jest": "12.3.4",
"@nrwl/next": "12.3.4",
"@nrwl/node": "12.3.4",
"@nrwl/react": "12.3.4",
"@nrwl/storybook": "12.3.4",
"@nrwl/tao": "12.3.4",
"@nrwl/web": "12.3.4",
"@nrwl/workspace": "12.3.4",
```

I'm getting the following backtrace:
```
$ nx build global-landing --configuration=test
...

ERROR in ./main.tsx
Module build failed (from repo/node_modules/@nrwl/web/src/utils/web-babel-loader.js):
TypeError: [BABEL] repo/apps/global-landing/src/main.tsx: Cannot read property 'android' of undefined (While processing: "repo/node_modules/@nrwl/web/node_modules/@babel/preset-env/lib/index.js")
    at getLowestImplementedVersion (repo/node_modules/@nrwl/web/node_modules/@babel/helper-compilation-targets/lib/utils.js:62:24)
    at repo/node_modules/@nrwl/web/node_modules/@babel/helper-compilation-targets/lib/filter-items.js:26:77
    at Array.filter (<anonymous>)
    at targetsSupported (repo/node_modules/@nrwl/web/node_modules/@babel/helper-compilation-targets/lib/filter-items.js:25:54)
    at isRequired (repo/node_modules/@nrwl/web/node_modules/@babel/helper-compilation-targets/lib/filter-items.js:58:11)
    at repo/node_modules/@nrwl/web/node_modules/@babel/preset-env/lib/index.js:269:201
    at repo/node_modules/@nrwl/web/node_modules/@babel/preset-env/node_modules/@babel/helper-plugin-utils/lib/index.js:22:12
    at repo/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/core/lib/config/full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (repo/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at step (repo/node_modules/gensync/index.js:261:32)
    at evaluateAsync (repo/node_modules/gensync/index.js:291:5)
    at Function.errback (repo/node_modules/gensync/index.js:113:7)
    at errback (repo/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/core/lib/gensync-utils/async.js:70:18)
    at async (repo/node_modules/gensync/index.js:188:31)
```

The .babelrc file looks like this (default):
```
{
  "presets": ["@nrwl/react/babel"],
  "plugins": []
}
```

The problems go away if I use the top-level @babel packages, not the ones included in Nx:
```
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-typescript",
    "@babel/preset-env"
  ],
  "plugins": []
}
```

Here @babel/preset-env is version 7.14.2 while the bundled version is 7.12.13

**Comment by rrooding** [comment]
The same issue is still there with 12.3.5

**Comment by tholander** [comment]
Any update here ? I have the same issue on 13.2.1

**Comment by gucolin** [comment]
Still seeing this in 14.5.8
