### ISSUE TITLE
E2E Test possibly broken

### ISSUE THREAD

**Issue by Phillip9587** [nrwl/nx#5767]
## Current Behavior
All my recent PRs CI fails because of the same E2E Test. 

Alls fails happen because of a ` EACCES: permission denied` Error during the `Move Angular Project › should work for libraries` test from `e2e/workspace/src/workspace-aux-commands.test.ts`

See: 
- https://nx.app/runs/JwHooMedj3X 
- https://nx.app/runs/tPvd5zDh6VV

## Expected Behavior
CI should run E2E Tests without any errors.

### Failure Logs

<details>
  <summary>Error Log</summary>
 
```
/home/circleci/.npm/_npx/7705/pnpm-global/4:
+ create-nx-workspace 9999.0.2


>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "pnpm install" several times. Please wait.

- Installing dependencies with pnpm
✔ Installing dependencies with pnpm
- Creating your workspace
✔ Nx has successfully created the workspace.
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 150, reused 20, downloaded 0, added 0
Progress: resolved 150, reused 21, downloaded 0, added 0
Progress: resolved 367, reused 72, downloaded 0, added 0
Progress: resolved 368, reused 72, downloaded 0, added 0
Progress: resolved 607, reused 162, downloaded 0, added 0
Progress: resolved 607, reused 163, downloaded 0, added 0
Progress: resolved 853, reused 582, downloaded 0, added 0
Progress: resolved 854, reused 582, downloaded 0, added 0
Progress: resolved 1267, reused 655, downloaded 0, added 0
Progress: resolved 1267, reused 656, downloaded 0, added 0
 WARN  @nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor: babel-loader@8.2.2 requires a peer of webpack@>=2 but none was installed.
 WARN  @nrwl/angular > @nrwl/cypress: @cypress/webpack-preprocessor@4.1.5 requires a peer of webpack@^4.18.1 but none was installed.
 WARN  @nrwl/angular: @nrwl/cypress@9999.0.2 requires a peer of cypress@>= 3 < 8 but none was installed.
 WARN  @nrwl/angular: jasmine-marbles@0.6.0 requires a peer of rxjs@^6.4.0 but none was installed.
 WARN  @nrwl/angular: rxjs-for-await@0.0.2 requires a peer of rxjs@^6.0.0 but none was installed.
 WARN  1 other warnings
 WARN  2 other warnings
 WARN  3 other warnings
 WARN  4 other warnings
 WARN  5 other warnings
 WARN  6 other warnings
 WARN  7 other warnings
 WARN  8 other warnings
 WARN  9 other warnings
 WARN  10 other warnings
 WARN  11 other warnings
 WARN  12 other warnings
 WARN  13 other warnings
 WARN  14 other warnings
 WARN  15 other warnings
 WARN  16 other warnings
Packages: +1457
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1569, reused 682, downloaded 0, added 0
Progress: resolved 1569, reused 682, downloaded 0, added 1
Progress: resolved 1569, reused 1269, downloaded 0, added 1169
Progress: resolved 1569, reused 1270, downloaded 0, added 1169
Progress: resolved 1569, reused 1569, downloaded 0, added 1457, done
 WARN  17 other warnings
.../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../core-js@3.12.1/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../node_modules/core-js-pure postinstall: Done
.../node_modules/gatsby-telemetry postinstall$ node src/postinstall.js || true
.../core-js@3.12.1/node_modules/core-js postinstall: Done
.../node_modules/gatsby-telemetry postinstall: Done
.../node_modules/gatsby-cli postinstall$ node scripts/postinstall.js
.../node_modules/gatsby-cli postinstall: Done

devDependencies:
+ @nrwl/angular 9999.0.2
+ @nrwl/eslint-plugin-nx 9999.0.2
+ @nrwl/express 9999.0.2
+ @nrwl/gatsby 9999.0.2
+ @nrwl/jest 9999.0.2
+ @nrwl/linter 9999.0.2
+ @nrwl/nest 9999.0.2
+ @nrwl/next 9999.0.2
+ @nrwl/node 9999.0.2
+ @nrwl/nx-plugin 9999.0.2
+ @nrwl/react 9999.0.2
+ @nrwl/storybook 9999.0.2
+ @nrwl/web 9999.0.2

mylib9191023 is still depended on by the following projects:
mylib1217591
 FAIL   e2e-workspace  e2e/workspace/src/workspace-aux-commands.test.ts (515.9 s)
  ● Console

    console.log
      original command workspace-generator custom-failing1028327 --no-interactive

      at Object.runCLI (../utils/index.ts:349:15)

    console.log
      
      > proj2352665@0.0.0 nx /tmp/nx-e2e--2737-zvNj8ZJEP65J/proj2352665
      > nx "workspace-generator" "custom-failing1028327" "--no-interactive"
      
       ERROR  Command failed with exit code 1.

      at Object.runCLI (../utils/index.ts:350:15)

    console.log
      original command generate @nrwl/angular:move --projectName=mylib4947285 --destination=shared/mylib4947285

      at Object.runCLI (../utils/index.ts:349:15)

    console.log
      
      > proj3909429@0.0.0 nx /tmp/nx-e2e--2737-zvNj8ZJEP65J/proj3909429
      > nx "generate" "@nrwl/angular:move" "--projectName=mylib4947285" "--destination=shared/mylib4947285"
      
      CREATE libs/shared/mylib4947285/.eslintrc.json
      DELETE libs/mylib4947285/.eslintrc.json
      CREATE libs/shared/mylib4947285/README.md
      DELETE libs/mylib4947285/README.md
      CREATE libs/shared/mylib4947285/jest.config.js
      DELETE libs/mylib4947285/jest.config.js
      CREATE libs/shared/mylib4947285/src/index.ts
      DELETE libs/mylib4947285/src/index.ts
      DELETE libs/mylib4947285/src/lib/mylib4947285.module.ts
      DELETE libs/mylib4947285/src/lib
      CREATE libs/shared/mylib4947285/src/test-setup.ts
      DELETE libs/mylib4947285/src/test-setup.ts
      DELETE libs/mylib4947285/src
      CREATE libs/shared/mylib4947285/tsconfig.json
      DELETE libs/mylib4947285/tsconfig.json
      CREATE libs/shared/mylib4947285/tsconfig.lib.json
      DELETE libs/mylib4947285/tsconfig.lib.json
      CREATE libs/shared/mylib4947285/tsconfig.spec.json
      DELETE libs/mylib4947285/tsconfig.spec.json
      DELETE libs/mylib4947285
      UPDATE libs/mylib1196418/src/lib/mylib1196418.module.ts
      UPDATE tsconfig.base.json
      UPDATE jest.config.js
      UPDATE nx.json
      UPDATE workspace.json
      CREATE libs/shared/mylib4947285/src/lib/shared-mylib4947285.module.ts
      UPDATE .git/index
      UPDATE .git/objects/0d/904b36e7d24210e8edc6a05778906b40b7f690
      UPDATE .git/objects/11/253ac5c2b7bc7ccc8003036c9379134582575c
      UPDATE .git/objects/36/949df5444a12f7ed3c97a756276d3bf04261ff
      UPDATE .git/objects/43/4d899a93f3f0fd9394325224b2eb6c84a2e19e
      UPDATE .git/objects/52/5dbebd70f9c0331cb4772e47c4a091ea33d51f
      UPDATE .git/objects/6c/a92c850c4e7b22091232f0eff08e54164bf04c
      UPDATE .git/objects/6e/87a003da89defd554080af5af93600cc9f91fe
      UPDATE .git/objects/90/36c20b13ed837d32a2c82096090e097fb83780
      UPDATE .git/objects/92/cde390acffd172f20258bb02c1840a4a9d0d13
      UPDATE .git/objects/99/428e1473febd3534100c4ce261c5904b461d8a
      UPDATE .git/objects/d0/b804da2a462044bb1c63364440b2c2164e86ad
      UPDATE .git/objects/d5/64d0bc3dd917926892c55e3706cc116d5b165e
      UPDATE .git/objects/e3/41003143e5d1f9396c280bee80aa43ceeca13c
      UPDATE .git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391
      UPDATE .git/objects/ed/1384f98ee9a32d1c10c14b847535cbfa8ea7d2
      UPDATE .git/objects/ee/5c9d8336b76b3bb5658d0888bdec86eb7b0990
      UPDATE .git/objects/ee/b426601326cca582b3db233a0fe89087ca40dd
      UPDATE .git/objects/ef/09d2d63852d816840d37e30a113aa85e9c0f04
      UPDATE apps/app18343948/src/favicon.ico
       ERROR  Command failed with exit code 1.
       EACCES: permission denied, open '/tmp/nx-e2e--2737-zvNj8ZJEP65J/proj3909429/.git/objects/0d/904b36e7d24210e8edc6a05778906b40b7f690'

      at Object.runCLI (../utils/index.ts:350:15)

    console.log
      original command generate @nrwl/workspace:remove --project mylib9191023

      at Object.runCLI (../utils/index.ts:349:15)

    console.log
      
      > proj197555@0.0.0 nx /tmp/nx-e2e--2737-zvNj8ZJEP65J/proj197555
      > nx "generate" "@nrwl/workspace:remove" "--project" "mylib9191023"
      
       ERROR  Command failed with exit code 1.
       mylib9191023 is still depended on by the following projects:
      mylib1217591

      at Object.runCLI (../utils/index.ts:350:15)

  ● Move Angular Project › should work for libraries

    Command failed: pnpm run nx -- generate @nrwl/angular:move --projectName=mylib4947285 --destination=shared/mylib4947285
    EACCES: permission denied, open '/tmp/nx-e2e--2737-zvNj8ZJEP65J/proj3909429/.git/objects/0d/904b36e7d24210e8edc6a05778906b40b7f690'

      324 |   try {
      325 |     const pm = getPackageManagerCommand();
    > 326 |     let r = execSync(`${pm.runNx} ${command}`, {
          |             ^
      327 |       cwd: opts.cwd || tmpProjPath(),
      328 |       env: { ...(opts.env || process.env), NX_INVOKED_BY_RUNNER: undefined },
      329 |     }).toString();

      at Object.runCLI (../utils/index.ts:326:13)
      at Object.<anonymous> (src/workspace-aux-commands.test.ts:687:24)
```

</details>

### Environment

CircleCI Pipeline:

Build-agent version 1.0.63969-66df1645 (2021-05-24T10:50:40+0000)
System information:
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Kernel Version: 4.15.0-1102-aws
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64

**Comment by puku0x** [comment]
I'm facing the E2E error right now 😂 https://github.com/nrwl/nx/issues/5763

**Comment by meeroslav** [comment]
Can you rebase to the latest version. This should have been fixed with https://github.com/nrwl/nx/commit/4b758f842e7ecbe963051cd1bcbdbff0121cd30b.

**Comment by puku0x** [comment]
It works now, thank you.

**Comment by Phillip9587** [comment]
@meeroslav Sorry i already did and forgot to close the issue.
