### ISSUE TITLE
Angular 12 upgrade build failed: Could not interpolate output {{options.outputPath}}!

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#5787]
ng build is throwing the following error, 

An unhandled exception occurred: Could not interpolate output {{options.outputPath}}!
See "/private/var/folders/pb/s03nms253k15m33xkxhqhhxc0000gn/T/ng-Uyom48/angular-errors.log" for further details.

Can someone please advise on this?

**Comment by dean-g** [comment]
angular-error.log: 

`[error] Error: Could not interpolate output {{options.outputPath}}!
    at node_modules/@nrwl/workspace/src/tasks-runner/utils.js:145:23
    at String.replace (<anonymous>)
    at interpolateOutputs (node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:21)
    at node_modules/@nrwl/workspace/src/tasks-runner/utils.js:86:48
    at Array.map (<anonymous>)
    at Object.getOutputsForTargetAndConfiguration (node_modules/@nrwl/workspace/src/tasks-runner/utils.js:86:32)
    at node_modules/@nrwl/workspace/src/utils/buildable-libs-utils.js:27:34
    at Array.map (<anonymous>)
    at Object.calculateProjectDependencies (node_modules/@nrwl/workspace/src/utils/buildable-libs-utils.js:20:10)
    at run (node_modules/@nrwl/angular/src/builders/webpack-browser/webpack-browser.impl.js:56:61)
    at onInput (node_modules/@angular-devkit/architect/src/create-builder.js:162:30)
    at SafeSubscriber._next (node_modules/@angular-devkit/architect/src/create-builder.js:65:29)
    at SafeSubscriber.__tryOrUnsub (node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (node_modules/rxjs/internal/Subscriber.js:66:18)`

**Comment by dean-g** [comment]
My angular JSON having following error: 
![image](https://user-images.githubusercontent.com/12157452/119582160-b896ec80-bd89-11eb-9520-71c0adb06d33.png)

**Comment by dean-g** [comment]
that was supported by: @angular-builders/custom-webpack:browser builder. since I changed that with the "@nrwl/angular:webpack-browser". build stopped processing

**Comment by vsavkin** [comment]
Thank you for submitting the issue.

It looks like you are missing the outputPath property. Can you share your angular.json, and the command you are trying to run?

**Comment by offwork** [comment]
every update turns into a torture, using node for UI is a real problem. I miss Flash.

**Comment by iAVP** [comment]
I have the same issue. Each time I generate lib or app it creates twice options
```json
"architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "outputs": ["{options.outputPath}"],
          "options": {
            "outputPath": "dist/apps/xxxx",
            "index": "apps/xxxx/src/index.html",
            "main": "apps/xxxx/src/main.ts",
            "polyfills": "apps/xxxx/src/polyfills.ts",
            "tsConfig": "apps/xxxx/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "apps/xxxx/src/favicon.ico",
              "apps/xxxx/src/assets"
            ],
            "styles": ["apps/km-leasing/src/styles.scss"],
            "scripts": []
          },
```
and then I have to delete this row manually :(
this is problem for enterprise projects within workspace
