### ISSUE TITLE
NX error when communicating with nx-cloud - Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by dhlavaty** [nrwl/nx#5794]
## Current Behavior

I came across a strange behavior with `nx` and especially with `nx-cloud`. Some of my NX runs ends up with error (see bellow). I guess it is when `nx` wants to connect to `nx-cloud` at the very end.

I have 2 laptops next to each other. They have same setup ( `yarn versions` are same, env variables same, I'm on the same git commit, `yarn install` was run).

I was able to isolate it to this point:

This works on both my laptops (see good result bellow):
```
yarn run nx run admin-e2e:lint
```

This works on my **laptop1**, but ends with error on a **laptop2**:
```
yarn run nx run admin:lint
```

This is "the good result" - on **laptop1**:
```
Lint warnings found in the listed files.


———————————————————————————————————————————————

>  NX   SUCCESS  Running target "lint" succeeded



>  NX   CLOUD  See run details at https://nx.app/runs/LN-CENSORED-IS
```

This is how it ends on **laptop2**:
```
Lint warnings found in the listed files.

(node:24636) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'code' of undefined
    at MessageReporter.extractErrorMessage (/Users/duhlavat/Developer/censored-frontend/node_modules/@nrwl/nx-cloud/lib/nx-cloud-tasks-runner.js:1:14001)
    at CloudApi.<anonymous> (/Users/duhlavat/Developer/censored-frontend/node_modules/@nrwl/nx-cloud/lib/nx-cloud-tasks-runner.js:1:7893)
    at Generator.throw (<anonymous>)
    at _0x3f8a6f (/Users/duhlavat/Developer/censored-frontend/node_modules/@nrwl/nx-cloud/lib/nx-cloud-tasks-runner.js:1:4382)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:24636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

Any idea, how can I debug this further ? I'm not the only one, my colleague has very same issue on his computer on same project.

## Expected Behavior

Expected is not getting an error.

## Steps to Reproduce

Really hard to reproduce - see above.

### Environment

```
$ nx report
  Node : 16.1.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.2.0
  @nrwl/cli : 12.2.0
  @nrwl/cypress : 12.2.0
  @nrwl/devkit : 12.2.0
  @nrwl/eslint-plugin-nx : 12.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.2.0
  @nrwl/linter : 12.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.2.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.2.0
  @nrwl/web : 12.2.0
  @nrwl/workspace : 12.2.0
  @nrwl/storybook : 12.2.0
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

```
$ yarn versions
{
  yarn: '1.22.10',
  'slido-frontend': '38.109.1',
  node: '16.1.0',
  v8: '9.0.257.24-node.11',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '6.0.1',
  openssl: '1.1.1k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```

**Comment by dhlavaty** [comment]
More info I noticed:

1.
**laptop1** is macOS Catalina (Intel) ; **laptop2** is macOS BigSur (Intel)

2.
I've copied whole project directory (with installed node_modules) from **laptop2** to **laptop1**, and just directly ran `yarn run nx run admin:lint` ... and it works ok. 🤯

**Comment by miluoshi** [comment]
It happens to me as well. 

I've noticed, that `lint` target throws this error (`@nrwl/linter:eslint` builder), but other target (using `@nrwl/workspace:run-commands` builder) is not throwing, while both targets are marked as `cacheableOperations` in `nx.json/tasksRunnerOptions` and the other working target is getting cached results successfully.

**Comment by StalkAltan** [comment]
Hi @dhlavaty! cc: @miluoshi since you are reporting the same issue.

I've spent a couple of hours trying to reproduce this (two macbooks, Catalina and Big Sur, `lint` target, Nx 12.2.0), and this has yet to show up for me. Have you been able to recreate this issue in another repo connected to Nx Cloud?

If so, would it be possible to share that repo with me?

I believe we can make this not blow up fairly easily -- I will keep this thread up-to-date with regards to that. However, without being able to repro this (even with both machines), it will be very difficult to track down the root cause.

Thanks!

**Comment by jozefizso** [comment]
Hi, I have a similar problem. Unfortunately we cannot share the repository as it is a private code.

I tried it with Node.JS v14 and v16 - the error shows in both.

```
webpack 5.37.1 compiled successfully in 21455 ms
(node:65359) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'code' of undefined
    at MessageReporter.extractErrorMessage (/Users/izso/dev/monorepo/node_modules/@nrwl/nx-cloud/lib/nx-cloud-tasks-runner.js:1:14001)
    at CloudRemoteCache.<anonymous> (/Users/izso/dev/monorepo/node_modules/@nrwl/nx-cloud/lib/nx-cloud-tasks-runner.js:1:10095)
    at Generator.throw (<anonymous>)
    at _0x3f8a6f (/Users/izso/dev/monorepo/node_modules/@nrwl/nx-cloud/lib/nx-cloud-tasks-runner.js:1:4382)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:65359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:65359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 26.48s.
```

```sh
nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.2.0
  @nrwl/cli : 12.2.0
  @nrwl/cypress : 12.2.0
  @nrwl/devkit : 12.2.0
  @nrwl/eslint-plugin-nx : 12.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.2.0
  @nrwl/linter : 12.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.2.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.2.0
  @nrwl/web : 12.2.0
  @nrwl/workspace : 12.2.0
  @nrwl/storybook : 12.2.0
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

✨  Done in 0.66s.
```

```sh
yarn versions
yarn versions v1.22.10
{
  yarn: '1.22.10',
  'slido-frontend': '38.153.1',
  node: '14.17.0',
  v8: '8.4.371.23-node.63',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}
✨  Done in 0.04s.
```
