### ISSUE TITLE
App compilation error after creating nx library 

### ISSUE THREAD

**Issue by vegeta03** [nrwl/nx#586]
``` 
$ ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-06-13T06:15:18.540Z
Hash: e1d93dcaa94503966b75
Time: 42413ms
chunk {TestWorkspace-shared-auth} TestWorkspace-shared-auth.js, TestWorkspace-shared-auth.js.map (TestWorkspace-shared-auth) 1.27 kB  [rendered]
chunk {main} main.js, main.js.map (main) 13.1 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 239 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.02 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.2 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.84 MB [initial] [rendered]

ERROR in D:/Shyam/Workspace/nxworkspace/TestWorkspace/libs/shared/auth/src/lib/shared-auth.module.ts
Module build failed: Error: D:\Shyam\Workspace\nxworkspace\TestWorkspace\libs\shared\auth\src\lib\shared-auth.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (D:\Shyam\Workspace\nxworkspace\TestWorkspace\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
    at plugin.done.then (D:\Shyam\Workspace\nxworkspace\TestWorkspace\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
i ｢wdm｣: Failed to compile.
 ```
I tried adding the `index.ts` of libs in tsconfig, still the error occurs.
How to fix this?

Thanks

**Comment by skydever** [comment]
hi! the path to the index is correct? I would double check that, as far as I remember the typescript compiler does not throw if the path is pointing to a file that does not exist.

**Comment by vegeta03** [comment]
Hi @skydever ,
I tried with both relative and absolute path. The same error is occurring.
Just after creating nx library, even then when nothing is modified.
These are the steps i followed to generate the workspace and app: 

`create-nx-workspace TestWorkspace`
`ng generate app TestApp --routing`
`ng g ngrx app --module=apps\test-app\src\app\app.module.ts --onlyEmptyRoot`
`ng g lib auth --routing --lazy --parent-module=apps\test-app\src\app\app.module.ts --directory=shared`

Thanks

**Comment by skydever** [comment]
can you create a repro repo? would make the investigation much easier and save me or anyone else looking at it some time...

maybe in the meantime, where did you put what exactly after all this steps? did you add `"../../libs/auth/src/index.ts"` at the `include` entry in `tsconfig.app.json` of the test-app? I think there is one `../` too much at the [guide](https://nrwl.io/nx/guide-nx-workspace), maybe thats the issue? to be honest, I am a little confused about the new structure and what you get when you migrate vs. a new clean workspace. the [nx-examples](https://github.com/nrwl/nx-examples) also differs compared to a new clean workspace (e.g. the `index.ts` of a lib is not under `src`, the `lib` folder is not there - seems like a mix of the old and the new structure ...), and I am not sure how the structure using `create-nx-workspace` looks like. I created my workspace with `ng new myworkspacename --collection=@nrwl/schematics` - maybe you can try that out and check the diffs?

**Comment by mrmeku** [comment]
Hi @vegeta03 , sorry that you're having trouble getting this feature to work for you. If you can provide a small, sample repo where we can reproduce the bug we'll get right on fixing it and trying to make changes to NX to make it harder to get compilations like yours in the future.

**Comment by vegeta03** [comment]
Hi @skydever and @mrmeku ,
 thanks for the response, i am traveling now, i ll provide a repo asap.

**Comment by jsonberry** [comment]
I got the same error, got through a couple errors to get the TS compilation working correctly.

First, I got the error `missing from the TypeScript compilation` when VSCode auto imported one of my libs like this:

```javascript
import { BarModule } from '../../../../../../node_modules/foo/libs/bar/baz/src';
```

I updated the import to this:
```javascript
import {BarModule} from '@app-name/foo/bar';
```

Then I got an error about TS not being able to find the module. The fix for that was to make sure my `paths` in my root level `tsconfig.json` had the proper entry:

```json
{
  "paths": [
    "@app-name/foo/bar": [
      "libs/foo/bar/src/src/index.ts"
    ]
  ]
}
```

**Comment by vegeta03** [comment]
I had to add the lib's barrel file to the include property of the app's tsconfig file.

Now its working.

Thanks @vsavkin
