### ISSUE TITLE
TypeError: hasher.hashCommand is not a function

### ISSUE THREAD

**Issue by Xenfo** [nrwl/nx#5882]
## Current Behavior
Linter errors out.

## Expected Behavior
It to lint successfully.

## Steps to Reproduce
https://github.com/Xenfo/muz

### Failure Logs
```
Unexpected error:
TypeError: hasher.hashCommand is not a function
    at /home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/@nrwl+linter@12.3.6/node_modules/@nrwl/linter/src/executors/eslint/hasher.js:12:32
    at Generator.next (<anonymous>)
    at /home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/tslib@2.2.0/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/tslib@2.2.0/node_modules/tslib/tslib.js:113:16)
    at run (/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/@nrwl+linter@12.3.6/node_modules/@nrwl/linter/src/executors/eslint/hasher.js:8:20)
    at TaskOrchestrator.<anonymous> (/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/@nrwl+workspace@12.3.4_prettier@2.2.1/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:120:24)
    at Generator.next (<anonymous>)
    at /home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.pnpm/tslib@2.2.0/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
The terminal process "/usr/bin/bash '-l', '-c', '/home/xenfo/Desktop/Projects/discord-bots/muz/node_modules/.bin/nx lint bot', 'nx lint bot'" terminated with exit code: 1.
```

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : linux x64
  pnpm : 6.6.2
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.4
  @nrwl/cypress : Not Found
  @nrwl/devkit : Not Found
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : 12.3.6
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.4
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.4
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by Xenfo** [comment]
Problem fixed, forgot to upgrade dependencies. https://github.com/Xenfo/muz/tree/master/typings my typings aren't working though

**Comment by Xenfo** [comment]
Turns out I can't have global typings :/
