### ISSUE TITLE
Storybook build fails

### ISSUE THREAD

**Issue by yusijs** [nrwl/nx#5887]
## Current Behavior
Created a new workspace, added an application + 6 libraries (migrating from angular cli). I've finished migrating the libs, and I generated storybook config + stories for the application-project, and used `nx run application:storybook`. This resulted in an error being thrown:
```
/node_modules/webpack/lib/util/MapHelpers.js:17
        const value = map.get(key);
```

Calling function:
```
const mainValue = /** @type {Set<string>} */ (provide(
					compilation.valueCacheVersions,
					VALUE_DEP_MAIN,
					() => new Set()
				));
```

I tried changing the compilation.valueCacheVersions to send in a `new Map()` if undefined, but that started giving me new errors. 

## Expected Behavior
Storybook should serve

## Steps to Reproduce
* Create new workspace
* Create app
* Install @nrwl/storybook
* Run storybook generator (I used the webstorm plugin)
* nx run appname:storybook
* Failure

![image](https://user-images.githubusercontent.com/11261560/120773232-6f7d3000-c521-11eb-9838-940443a9bee0.png)

### Failure Logs
<details>
<summary>Stacktrace</summary>

```
> nx run oilmod-web:storybook 
info => Loading presets
info => Loading 1 config file in "/Users/RHENRI/dev/oilmod-web-nx/apps/oilmod-web/.storybook"
info => Adding stories defined in "/Users/RHENRI/dev/oilmod-web-nx/apps/oilmod-web/.storybook/main.js"
info => Found custom tsconfig.json
info => Using implicit CSS loaders
info => Using angular project 'oilmod-web' for configuring Storybook.
info => Loading angular-cli config.
info => Get angular-cli webpack config.
info => Loading custom Webpack config (full-control mode).
<i> [webpack-dev-middleware] wait until bundle finished
Starting type checking service...
ℹ ｢wdm｣: wait until bundle finished: 
/Users/RHENRI/dev/oilmod-web-nx/node_modules/webpack/lib/util/MapHelpers.js:17
        const value = map.get(key);
                          ^

TypeError: Cannot read property 'get' of undefined
    at exports.provide (/Users/RHENRI/dev/oilmod-web-nx/node_modules/webpack/lib/util/MapHelpers.js:17:20)
    at /Users/RHENRI/dev/oilmod-web-nx/node_modules/webpack/lib/DefinePlugin.js:289:51
    at SyncHook.eval [as call] (eval at create (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:1)
    at SyncHook.lazyCompileHook (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Watching.js:77:18
    at _next0 (eval at create (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at eval (eval at create (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
    at watchRunHook (/Users/RHENRI/dev/oilmod-web-nx/node_modules/webpack-virtual-modules/index.js:173:5)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Watching.js:41:32)
```

</details>

<details>
<summary>Stacktrace with new Map() fallback</summary>

```
> nx run oilmod-web:storybook 
info => Loading presets
info => Loading 1 config file in "/Users/RHENRI/dev/oilmod-web-nx/apps/oilmod-web/.storybook"
WARN We found no files matching any of the following globs:
WARN 
WARN ../src/app/**/*.stories.mdx
WARN ../src/app/**/*.stories.@(js|jsx|ts|tsx)
WARN 
WARN Maybe your glob was invalid?
WARN see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
info => Found custom tsconfig.json
info => Using implicit CSS loaders
info => Using angular project 'oilmod-web' for configuring Storybook.
info => Loading angular-cli config.
info => Get angular-cli webpack config.
info => Loading custom Webpack config (full-control mode).
<i> [webpack-dev-middleware] wait until bundle finished
Starting type checking service...
ℹ ｢wdm｣: wait until bundle finished: 
(node:37536) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createSnapshot' of undefined
    at /Users/RHENRI/dev/oilmod-web-nx/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
    at new Promise (<anonymous>)
    at Object.createSnapshot (/Users/RHENRI/dev/oilmod-web-nx/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
    at /Users/RHENRI/dev/oilmod-web-nx/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35
(node:37536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:37536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
(node:37536) UnhandledPromiseRejectionWarning: TypeError: compilation.getAssetPath is not a function
    at /Users/RHENRI/dev/oilmod-web-nx/node_modules/html-webpack-plugin/index.js:169:25
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Compiler.js:491:19)
    at onCompiled (/Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Watching.js:51:19)
    at /Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/RHENRI/dev/oilmod-web-nx/node_modules/@storybook/core-server/node_modules/webpack/lib/Compilation.js:1414:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/RHENRI/dev/oilmod-web-nx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
(node:37536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
webpack built preview 38dd544b56223b9c5e47 in 15400ms
webpack built preview bcd9f629a197b75314f7 in 283ms

```
</details>

### Environment
>  NX  Report complete - copy this into the issue template

  Node : 12.16.1
  OS   : darwin x64
  npm  : 6.13.4
  
  nx : Not Found
  @nrwl/angular : 12.3.5
  @nrwl/cli : 12.3.5
  @nrwl/cypress : 12.3.5
  @nrwl/devkit : 12.3.5
  @nrwl/eslint-plugin-nx : 12.3.5
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.5
  @nrwl/linter : 12.3.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.5
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.5
  @nrwl/storybook : 12.3.6
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by yusijs** [comment]
May be related to https://github.com/nrwl/nx/issues/5688

**Comment by yusijs** [comment]
Yep, implemented fixes suggested in https://github.com/nrwl/nx/issues/5688 and it works for me now :)
