### ISSUE TITLE
@nrwl/web:file-server does not work with ssl turned on

### ISSUE THREAD

**Issue by DibyodyutiMondal** [nrwl/nx#5908]
This is literally the same as #4701, but that is 'fixed' and closed so I made a new one

I was following the instructions to prepare angular apps to take advantage of incremental builds
https://nx.dev/latest/angular/ci/setup-incremental-builds-angular

## Current Behavior
It builds fine, then errors out with following:

```
_tls_common.js:149
      c.context.setKey(key, passphrase);
                ^

Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:149:17)
    at Server.setSecureContext (_tls_wrap.js:1326:27)
    at Server (_tls_wrap.js:1181:8)
    at new Server (https.js:67:14)
    at Object.createServer (https.js:92:10)
    at Object.core.createServer (D:\folder\node_modules\union\lib\core.js:93:18)
    at new HttpServer (D:\folder\node_modules\http-server\lib\http-server.js:198:23)
    at Object.exports.createServer (D:\folder\node_modules\http-server\lib\http-server.js:47:10)
    at listen (D:\folder\node_modules\http-server\bin\http-server:162:27)
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

## Expected Behavior
The server should start with ssl

## Steps to Reproduce
Create a default angular application with @nrwl/angular, and follow the steps as provided here:
https://nx.dev/latest/angular/ci/setup-incremental-builds-angular

Final look of the `serve` target:
```
        "serve": {
          "executor": "@nrwl/web:file-server",
          "options": {
            "ssl": true,
            "sslKey": "apps/public-client/dev-cert-key.pem",
            "sslCert": "apps/public-client/dev-cert.pem"
          },
          "configurations": {
            "production": {
              "buildTarget": "public-client:build:production"
            },
            "development": {
              "buildTarget": "public-client:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
```

### Environment
```
Node : 14.17.0
  OS   : win32 x64
  npm  : 7.13.0

  nx : Not Found
  @nrwl/angular : 12.3.6
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : 12.3.6
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by DibyodyutiMondal** [comment]
Seems like this may possibly be an error with certificate/key and not nrwl/web itself...
Will confirm and get back ASAP

**Comment by DibyodyutiMondal** [comment]
Yes, the problem was the key file. Windows really makes it tough to export private keys, which is good, I guess?
