### ISSUE TITLE
`affected:build` failing in the pipeline

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#5960]
## Current Behavior

The `affected:build` is failing with the message:
```
fatal: Not a valid object name master
fatal: No such ref: 'master'
```
Although, the `git fetch` is being called and branches are existing at the time the command is called
```
Successfully extracted cache
Executing "step_script" stage of the job script 00:02
$ git fetch
From https://some-path
 * [new branch]      add-linting-pipeline -> origin/add-linting-pipeline
 * [new branch]      master               -> origin/master
 * ...
$ NODE_ENV=production nx affected:build --parallel --maxParallel=8 --configuration=dev --deployUrl=./
>  NX   NOTE  Affected criteria defaulted to --base=master --head=HEAD
fatal: Not a valid object name master
fatal: No such ref: 'master'
nx affected:build
Build applications and publishable libraries affected by changes
Run command using --base=[SHA1] (affected by the committed, uncommitted and
untracked changes):
  --base  Base of the current branch (usually master)                   [string]
or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
  --base  Base of the current branch (usually master)                   [string]
  --head  Latest commit of the current branch (usually HEAD)            [string]
or using:
  --files        Change the way Nx is calculating the affected command by
                 providing directly changed files, list of files delimited by
                 commas                                                  [array]
  --uncommitted  Uncommitted changes                                   [boolean]
  --untracked    Untracked changes                                     [boolean]
Options:
  --help           Show help                                           [boolean]
  --version        Show version number                                 [boolean]
  --parallel       Parallelize the command (default: false)            [boolean]
  --maxParallel    Max number of parallel processes. This flag is ignored if the
                   parallel option is set to `false`. (default: 3)      [number]
  --all            All projects                                        [boolean]
  --exclude        Exclude certain projects from being processed
                                                           [array] [default: []]
  --runner         This is the name of the tasks runner configured in nx.json
                                                                        [string]
  --skip-nx-cache  Rerun the tasks even when the results are available in the
                   cache                              [boolean] [default: false]
  --configuration  This is the configuration to use when performing tasks on
                   projects                                             [string]
  --only-failed    Isolate projects which previously failed
                                                      [boolean] [default: false]
  --verbose        Print additional error stack trace on failure
Error: Command failed: git merge-base --fork-point "master" "HEAD"
fatal: No such ref: 'master'
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at getFilesUsingBaseAndHead (/builds/fo7brMD7/1/.../node_modules/@nrwl/workspace/src/command-line/shared.js:55:37)
    at Object.parseFiles (/builds/fo7brMD7/1/.../node_modules/@nrwl/workspace/src/command-line/shared.js:31:20)
    at projectsToRun (/builds/fo7brMD7/1/.../node_modules/@nrwl/workspace/src/command-line/affected.js:97:108)
    at Object.<anonymous> (/builds/fo7brMD7/1/.../node_modules/@nrwl/workspace/src/command-line/affected.js:27:26)
    at Generator.next (<anonymous>)
    at fulfilled (/builds/fo7brMD7/1/.../node_modules/@nrwl/workspace/node_modules/tslib/tslib.js:114:62) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 4e 6f 20 73 75 63 68 20 72 65 66 3a 20 27 6d 61 73 74 65 72 27 0a>
  ],
  pid: 36,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 4e 6f 20 73 75 63 68 20 72 65 66 3a 20 27 6d 61 73 74 65 72 27 0a>
}
Cleaning up file based variables 00:00
ERROR: Job failed: command terminated with exit code 1
```
### Environment

 Node : 14.15.4
  OS   : win32 x64
  yarn : 2.4.2

  nx : 11.1.1
  @nrwl/angular : Not Found
  @nrwl/cli : 12.1.1
  @nrwl/cypress : 12.1.1
  @nrwl/devkit : 12.1.1
  @nrwl/eslint-plugin-nx : 12.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.1.1
  @nrwl/linter : 12.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.1.1
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 12.1.1
  @nrwl/web : 12.1.1
  @nrwl/workspace : 12.1.1
  @nrwl/storybook : 12.1.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.2

**Comment by FrozenPandaz** [comment]
What is your pipeline?

FYI:
`git fetch origin` creates the `origin/master` reference, not `master`.

You would still need to do `git checkout master` after  that to create the `master` branch.

**Comment by nemonemi** [comment]
@FrozenPandaz,
The pipeline is in GitLab.

I've adjusted the steps to include checking out master branch, and that passed, but a new problem occurs:

```
Previous HEAD position was 2fe2caf Adjust the git steps
Branch 'master' set up to track remote branch 'master' from 'origin'.
$ NODE_ENV=production nx affected:build --parallel --maxParallel=8 --configuration=dev --deployUrl=./
Switched to a new branch 'master'
>  NX   NOTE  Affected criteria defaulted to --base=master --head=HEAD
>  NX  No projects with "build" that are configured for "dev" were run
———————————————————————————————————————————————
>  NX   SUCCESS  Running target "build" succeeded
$ cp -r ./docker/nginx_files ./dist/apps/
cp: cannot create directory './dist/apps/': No such file or directory
Cleaning up file based variables 00:01
ERROR: Job failed: command terminated with exit code 1
```

<details>
<summary>If at all helpful, here is my <strong>workspace.json</strong> configuration.</summary>

```json
{
  "version": 1,
  "cli": {
    "defaultCollection": "@nrwl/react"
  },
  "defaultProject": "app-1",
  "schematics": {
    "@nrwl/workspace": {
      "library": {
        "linter": "eslint"
      }
    },
    "@nrwl/cypress": {
      "cypress-project": {
        "linter": "eslint"
      }
    },
    "@nrwl/react": {
      "application": {
        "style": "styled-components",
        "linter": "eslint",
        "babel": true
      },
      "component": {
        "style": "styled-components"
      },
      "library": {
        "style": "styled-components",
        "linter": "eslint"
      }
    }
  },
  "projects": {
    "app-2": {
      "root": "apps/app-2",
      "sourceRoot": "apps/app-2/src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@nrwl/web:build",
          "outputs": ["{options.outputPath}"],
          "options": {
            "baseHref": "/survey/form/",
            "outputPath": "dist/apps/app-2",
            "index": "apps/app-2/src/index.html",
            "main": "apps/app-2/src/main.tsx",
            "polyfills": "apps/app-2/src/polyfills.ts",
            "tsConfig": "apps/app-2/tsconfig.app.json",
            "assets": ["apps/app-2/src/favicon.ico", "apps/app-2/src/assets"],
            "styles": [],
            "scripts": [],
            "webpackConfig": "utils/webpack-shared.config.js"
          },
          "configurations": {
            "dev": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            },
            "prod": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": false,
              "vendorChunk": false,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@nrwl/web:dev-server",
          "options": {
            "buildTarget": "app-2:build"
          },
          "configurations": {
            "dev": {
              "buildTarget": "app-2:build:dev"
            },
            "prod": {
              "buildTarget": "app-2:build:prod"
            }
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["apps/app-2/**/*.{ts,tsx,js,jsx}"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": ["coverage/apps/app-2"],
          "options": {
            "jestConfig": "apps/app-2/jest.config.js",
            "passWithNoTests": true
          }
        }
      }
    },
    "app-2-e2e": {
      "root": "apps/app-2-e2e",
      "sourceRoot": "apps/app-2-e2e/src",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/app-2-e2e/cypress.json",
            "tsConfig": "apps/app-2-e2e/tsconfig.e2e.json",
            "devServerTarget": "app-2:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "app-2:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["apps/app-2-e2e/**/*.{js,ts}"]
          }
        }
      }
    },
    "app-app-2": {
      "root": "libs/app-app-2",
      "sourceRoot": "libs/app-app-2/src",
      "projectType": "library",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/app-app-2/**/*.{ts,tsx,js,jsx}"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": ["coverage/libs/app-app-2"],
          "options": {
            "jestConfig": "libs/app-app-2/jest.config.js",
            "passWithNoTests": true
          }
        }
      }
    },
    "ui": {
      "root": "libs/ui",
      "sourceRoot": "libs/ui/src",
      "projectType": "library",
      "architect": {
        "build": {
          "builder": "@nrwl/web:package",
          "outputs": ["{options.outputPath}"],
          "options": {
            "outputPath": "dist/libs/ui",
            "tsConfig": "libs/ui/tsconfig.lib.json",
            "project": "libs/ui/package.json",
            "entryFile": "libs/ui/src/index.ts",
            "external": ["react", "react-dom", "react-is", "styled-components"],
            "babelConfig": "@nrwl/react/plugins/bundle-babel",
            "rollupConfig": "@nrwl/react/plugins/bundle-rollup",
            "assets": [
              {
                "glob": "README.md",
                "input": ".",
                "output": "."
              }
            ]
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["libs/ui/**/*.{ts,tsx,js,jsx}"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": ["coverage/libs/ui"],
          "options": {
            "jestConfig": "libs/ui/jest.config.js",
            "passWithNoTests": true
          }
        },
        "storybook": {
          "builder": "@nrwl/storybook:storybook",
          "options": {
            "uiFramework": "@storybook/react",
            "port": 4400,
            "config": {
              "configFolder": "libs/ui/.storybook"
            }
          },
          "configurations": {
            "ci": {
              "quiet": true
            }
          }
        },
        "build-storybook": {
          "builder": "@nrwl/storybook:build",
          "options": {
            "uiFramework": "@storybook/react",
            "outputPath": "dist/ui/storybook",
            "config": {
              "configFolder": "libs/ui/.storybook"
            }
          },
          "configurations": {
            "ci": {
              "quiet": true
            }
          }
        }
      }
    },
    "ui-e2e": {
      "root": "apps/ui-e2e",
      "sourceRoot": "apps/ui-e2e/src",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/ui-e2e/cypress.json",
            "tsConfig": "apps/ui-e2e/tsconfig.e2e.json",
            "devServerTarget": "ui:storybook"
          },
          "configurations": {
            "ci": {
              "devServerTarget": "ui:storybook:ci"
            }
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["apps/ui-e2e/**/*.{js,ts}"]
          }
        }
      }
    },
    "app-1": {
      "root": "apps/bd/certificates",
      "sourceRoot": "apps/bd/certificates/src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@nrwl/web:build",
          "outputs": ["{options.outputPath}"],
          "options": {
            "outputPath": "dist/apps/bd/certificates",
            "index": "apps/bd/certificates/src/index.html",
            "main": "apps/bd/certificates/src/main.tsx",
            "polyfills": "apps/bd/certificates/src/polyfills.ts",
            "tsConfig": "apps/bd/certificates/tsconfig.app.json",
            "assets": [
              "apps/bd/certificates/src/favicon.ico",
              "apps/bd/certificates/src/assets",
              {
                "glob": "**/*",
                "input": "libs/ui/src/lib/layout-and-navigation/main-navigation-bar/shared-assets/",
                "output": "./assets"
              }
            ],
            "styles": [],
            "scripts": [],
            "webpackConfig": "utils/webpack-shared.config.js"
          },
          "configurations": {
            "dev": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            },
            "prod": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": false,
              "vendorChunk": false,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@nrwl/web:dev-server",
          "options": {
            "buildTarget": "app-1:build",
            "port": 4203
          },
          "configurations": {
            "dev": {
              "buildTarget": "app-1:build:dev"
            },
            "prod": {
              "buildTarget": "app-1:build:prod"
            }
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["apps/bd/certificates/**/*.{ts,tsx,js,jsx}"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": ["coverage/apps/bd/certificates"],
          "options": {
            "jestConfig": "apps/bd/certificates/jest.config.js",
            "passWithNoTests": true
          }
        },
        "generate": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": ["yarn bd-api-generate-schema", "yarn gqless generate"],
            "cwd": "apps/bd/certificates",
            "parallel": false
          }
        }
      }
    },
    "app-1-e2e": {
      "root": "apps/bd/certificates-e2e",
      "sourceRoot": "apps/bd/certificates-e2e/src",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/bd/certificates-e2e/cypress.json",
            "tsConfig": "apps/bd/certificates-e2e/tsconfig.e2e.json",
            "devServerTarget": "app-1:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "app-1:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["apps/bd/certificates-e2e/**/*.{js,ts}"]
          }
        }
      }
    },
    "bd-api": {
      "root": "apps/bd/api",
      "sourceRoot": "apps/bd/api/src",
      "projectType": "application",
      "architect": {
        "serve": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "command": "yarn bd-api"
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": ["apps/bd/api/**/*.ts"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": ["coverage/apps/bd/api"],
          "options": {
            "jestConfig": "apps/bd/api/jest.config.js",
            "passWithNoTests": true
          }
        }
      }
    }
  }
}
```
</detail>

**Comment by Anenth** [comment]
These worked for me
1. Add `--base origin/master` to `nx affected:build`
2. Fetch all the branches with GitHub action by setting fetch-depth: 0
```:yaml
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

**Comment by michelepatrassi** [comment]
@nemonemi that's because there are no affected builds hence dist/apps has not been created. You can add an extra check before the next command 
```
if [ -d ./dist/apps ] then cp -r ./docker/nginx_files ./dist/apps/

**Comment by DannyPark1** [comment]
the same error occurs on github action pipeline, does any body know how to solve this problem? settings fetch-depth did not solve the issue :(

**Comment by erdysson** [comment]
For the ones running into issue on Gitlab CI, two things to make it work;

First; **set the git depth via UI to 0**, under _settings -> CI CD -> General pipelines -> git depth_
And second, add `GIT_FETCH_EXTRA_FLAGS: --unshallow` in **.gitlab-ci.yml** under **variables**

**Comment by lkurzyniec** [comment]
For Azure DevOps, below fixed the issue
```yaml
- checkout: self
  fetchDepth: 0
```
