### ISSUE TITLE
Running NX affected command causes ERR_INVALID_PERFORMANCE_MARK error

### ISSUE THREAD

**Issue by bpk68** [nrwl/nx#6026]
## Current Behavior
When running the NX command `nx affected:test` I'm getting a strange 'unexpected error' that mentions `ERR_INVALID_PERFORMANCE_MARK` in the console. I've tried scouring the Internet for a similar issue but it looks like there's nothing to be found and was hoping someone else had come across this.

Note that I can run tests fine using `nx run myprojectname:test`, but to just test the affected files, this error kills the command dead.

## Expected Behavior
I would expect that running `nx affected:test` would run my unit tests without crashing out immediately.

### Failure Logs
```
>  NX   NOTE  Affected criteria defaulted to --base=main --head=HEAD


>  NX  Running target test for projects:

  - dashboard
  - gb-api
  - app-services
  - data
  - utils

———————————————————————————————————————————————
Unexpected error:
Error [ERR_INVALID_PERFORMANCE_MARK]: The "command-execution-begins" performance mark has not been set
    at new NodeError (node:internal/errors:363:5)
    at getMark (node:internal/perf/usertiming:49:11)
    at calculateStartDuration (node:internal/perf/usertiming:113:13)
    at EventTarget.measure (node:internal/perf/usertiming:133:7)
    at TaskOrchestrator.<anonymous> (/Users/robkendal/Code/gb-products/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:29:38)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/robkendal/Code/gb-products/node_modules/tslib/tslib.js:114:62) {
  code: 'ERR_INVALID_PERFORMANCE_MARK'
}
```

### Environment
```
Node : 16.1.0
OS   : darwin arm64
yarn : 1.22.10

nx : Not Found
@nrwl/angular : Not Found
@nrwl/cli : 12.0.8
@nrwl/cypress : 12.0.8
@nrwl/devkit : 12.3.6
@nrwl/eslint-plugin-nx : 12.0.8
@nrwl/express : 12.3.6
@nrwl/jest : 12.0.8
@nrwl/linter : 12.0.8
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : 12.0.8
@nrwl/react : 12.3.6
@nrwl/schematics : Not Found
@nrwl/tao : 12.0.8
@nrwl/web : 12.0.8
@nrwl/workspace : 12.0.8
@nrwl/storybook : 12.3.6
@nrwl/gatsby : Not Found
typescript : 4.1.5
```

**Comment by FrozenPandaz** [comment]
This issue was fixed with https://github.com/nrwl/nx/commit/ae5722eb508fbb8f0de499076f8aaf20c4463b65

Please retry with Nx version `>12.1.0`.
