### ISSUE TITLE
Build a project needs other projects for building which have no reference at all

### ISSUE THREAD

**Issue by shinjucommunications** [nrwl/nx#6087]
## Current Behavior

We've a huge mono repo with lot's off apps and libraries.

So what we do by check-out is we remove all the unnecessary projects by checkout. 
except the project **project-a** which we wanna run a build for we keep there and the belonging **shared** libraries.
When we run a build for the specific project  **project-a** it is failing on other project that have no reference at all by **project-a**.

## Expected Behavior
When building **project-a**  with **--with-deps --prod**. It will succeed and not access other projects that are not being referenced at all.

## Steps to Reproduce
```
nx -- run project-a:lint --with-deps
```

### Failure Logs
```
> nx "run" "project-a:lint "--with-deps"

(node:5044) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\repos\project-a\nx\apps\app-b-e2e\src\integration\hide-tree.spec
.ts'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.defaultFileRead (C:\repos\project-a\nx\node_modules\@nrwl\workspace\src\core\file-utils.js:164:17)
    at TypeScriptImportLocator.fromFile (C:\repos\project-a\nx\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\typescript-import-locator.js:22:38)
    at C:\repos\project-a\nx\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\explicit-project-dependencies.js:11:27
    at Array.forEach (<anonymous>)
    at C:\repos\project-a\nx\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\explicit-project-dependencies.js:10:44
    at Array.forEach (<anonymous>)
    at buildExplicitTypeScriptDependencies (C:\repos\project-a\nx\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\explicit-project-dependencies.js:9:30)
    at C:\repos\project-a\nx\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:72:41
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting
 a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org
/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with
a non-zero exit code.
```

### Environment
```
  Node : 14.16.1
  OS   : win32 x64
  npm  : 7.11.2

  nx : Not Found
  @nrwl/angular : 12.0.8
  @nrwl/cli : 12.0.8
  @nrwl/cypress : 12.0.8
  @nrwl/devkit : 12.0.8
  @nrwl/eslint-plugin-nx : 12.0.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.8
  @nrwl/linter : 12.0.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.8
  @nrwl/web : 12.3.3
  @nrwl/workspace : 12.0.8
  @nrwl/storybook : 12.3.5
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

**Comment by FrozenPandaz** [comment]
Can you please provide how exactly you are checking out only portions of the code?

Are you using a `sparse-checkout` or `git submodules`?

**Comment by jahller** [comment]
Hello, we actually have the exactly the same problem after upgrading "nrwl/workspaces" from "9.2.4" to "12.5.8".
We are using `spare-checkout`
