### ISSUE TITLE
Failed Migration: Add testEnvironment: 'jsdom' in web apps + libraries

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#6090]
The following migration command is not working, 

"migrations": [
    {
      "version": "12.4.0-beta.1",
      "cli": "nx",
      "description": "Add testEnvironment: 'jsdom' in web apps + libraries",
      "factory": "./src/migrations/update-12-4-0/add-test-environment-for-node",
      "package": "@nrwl/jest",
      "name": "support-jest-27"
    }
  ]

Getting the following error, 
```
Running migration support-jest-27
Cannot read property 'includes' of undefined
node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;

Error: Command failed: /var/folders/pb/s03nms253k15m33xkxhqhhxc0000gn/T/tmp-10696-Di9JT6wMOQDu/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (ui-code/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:90:25)
    at Object.runCommand (ui-code/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (ui-code/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (ui-code/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (ui-code/node_modules/@nrwl/cli/lib/init-local.js:26:79)
    at Object.<anonymous> (ui-code/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10708,
  stdout: null,
  stderr: null
}

#

```
Can you please check this and advise?

**Comment by rickvandermey** [comment]
in your `jest.preset.js` you should set a testEnvironment. something like this:
```
const nxPreset = require('@nrwl/jest/preset');
module.exports = {
	...nxPreset,
	testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
	transform: {
		'^.+\\.(ts|js|html)$': 'ts-jest',
	},
	testEnvironment: 'jest-environment-jsdom',
	resolver: '@nrwl/jest/plugins/resolver',
	moduleFileExtensions: ['ts', 'js', 'html'],
	coverageReporters: ['html'],
};
```

**Comment by dean-g** [comment]
I am getting the following error now, 

```
Test suite failed to run
    ReferenceError: global is not defined
      at Object.<anonymous> (../../node_modules/jest-canvas-mock/lib/index.js:19:3)
      at async TestScheduler.scheduleTests (../../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at async runJest (../../node_modules/@jest/core/build/runJest.js:387:19)
      at async _run10000 (../../node_modules/@jest/core/build/cli/index.js:408:7)
      at async Object.runCLI (../../node_modules/@jest/core/build/cli/index.js:261:3)
```

**Comment by dean-g** [comment]
upgraded jest-environment-jsdom package. 

 "jest-environment-jsdom": "27.0.5",

now getting new error, 

 FAIL   my-lib  src/lib/tesing.spec.ts
  ● Test suite failed to run

    File not found: jest-preset-angular/build/InlineFilesTransformer (resolved as: jest-preset-angular/build/InlineFilesTransformer)

      at ConfigSet.resolvePath (../../../../node_modules/ts-jest/dist/config/config-set.js:444:19)
      at ../../../../node_modules/ts-jest/dist/config/config-set.js:225:46
          at Array.map (<anonymous>)
      at resolveTransformers (../../../../node_modules/ts-jest/dist/config/config-set.js:223:37)
      at ConfigSet._setupConfigSet (../../../../node_modules/ts-jest/dist/config/config-set.js:233:137)
      at new ConfigSet (../../../../node_modules/ts-jest/dist/config/config-set.js:142:14)
      at NgJestTransformer.TsJestTransformer._createConfigSet (../../../../node_modules/ts-jest/dist/ts-jest-transformer.js:111:16)
      at NgJestTransformer.TsJestTransformer._configsFor (../../../../node_modules/ts-jest/dist/ts-jest-transformer.js:89:34)
      at NgJestTransformer.TsJestTransformer.getCacheKey (../../../../node_modules/ts-jest/dist/ts-jest-transformer.js:172:28)
      at ScriptTransformer._getCacheKey (../../../../node_modules/@jest/transform/build/ScriptTransformer.js:280:41)

**Comment by dean-g** [comment]
@here can someone please check this and advise?

**Comment by thutinavaneethreddy** [comment]
@dean-g Can you see if your jest.confi.js has this line? `  transform: { '^.+\\.(ts|js|html)$': 'jest-preset-angular' }
`

**Comment by AgentEnder** [comment]
@dean-g The migration failing makes it sound like you have a target in workspace.json that does not have an executor defined, can you check if this is the case?

**Comment by dean-g** [comment]
Thanks @AgentEnder. Is there anything wrong with the migration command. I tried to rerun but it doesn't show anything for 12.4.0? Very wired

**Comment by AgentEnder** [comment]
If you are already on 12.4.0 the migration would not come through, you could do `nx migrate @nrwl/jest@12.4.0 --from @nrwl/jest@12.3.0` to redo that migration.

**Comment by dean-g** [comment]
thank you very much @AgentEnder.

**Comment by dean-g** [comment]
> @dean-g The migration failing makes it sound like you have a target in workspace.json that does not have an executor defined, can you check if this is the case?
> 
> Additionally, check your jest.config.js files. The jest-preset-angular/build/* transformers should be removed. An example jest.config.js for an angular app should look something like this after the Jest 27 update:
> 
> ```js
> module.exports = {
>   displayName: 'test-ng-app',
>   preset: '../../jest.preset.js',
>   setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
>   globals: {
>     'ts-jest': {
>       tsconfig: '<rootDir>/tsconfig.spec.json',
>       stringifyContentPathRegex: '\\.(html|svg)$',
>     },
>   },
>   coverageDirectory: '../../coverage/apps/test-ng-app',
>   transform: {
>     '^.+\\.(ts|js|html)$': 'jest-preset-angular',
>   },
>   snapshotSerializers: [
>     'jest-preset-angular/build/serializers/no-ng-attributes',
>     'jest-preset-angular/build/serializers/ng-snapshot',
>     'jest-preset-angular/build/serializers/html-comment',
>   ],
> };
> ```

My angular.json file had the following builder for all the libs. not sure what else required for this in terms of executor?

"builder": "@nrwl/jest:jest",

**Comment by AgentEnder** [comment]
Hey, this would be for all architect targets in your angular.json file (not just the linting ones).

**Comment by dean-g** [comment]
okay!. what could be the expected value on the targets?

can you please give me one example?

**Comment by AgentEnder** [comment]
The lint architect target that you mentioned the builder on is a valid example, it sounds like there is another target (think build / lint / serve / e2e ) on some project that does not have a builder or executor listed.
