### ISSUE TITLE
migrate 11.5.2 to 12.4.0 "Cannot read property 'implementation' of undefined" on running migration remove-eslint-project-config-if-no-type-checking-rules 

### ISSUE THREAD

**Issue by hiepxanh** [nrwl/nx#6142]
## Current Behavior
error on migration

## Expected Behavior
hope it not error

## Steps to Reproduce
I making migration from 11.5.2 to 12.4.0 and get this error

```
Running migration remove-eslint-project-config-if-no-type-checking-rules
Cannot read property 'implementation' of undefined
/Users/hiepxanh/Documents/batcave/awread-project/node_modules/.pnpm/yargs@15.4.1/node_modules/yargs/build/lib/yargs.js:1132
```

### Failure Logs
```
Running migration update-ts-jest-and-jest-preset-angular
Successfully finished update-ts-jest-and-jest-preset-angular
---------------------------------------------------------
Running migration remove-eslint-project-config-if-no-type-checking-rules
Cannot read property 'implementation' of undefined
/Users/hiepxanh/Documents/batcave/awread-project/node_modules/.pnpm/yargs@15.4.1/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/sz/gb25dqnx7sl189pk1yk997wr0000gn/T/tmp-61454-9e3WR7s4JC9O/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at Object.handler (/Users/hiepxanh/Documents/batcave/awread-project/node_modules/.pnpm/@nrwl+workspace@12.4.0_prettier@2.2.1/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:90:25)
    at Object.runCommand (/Users/hiepxanh/Documents/batcave/awread-project/node_modules/.pnpm/yargs@15.4.1/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/hiepxanh/Documents/batcave/awread-project/node_modules/.pnpm/yargs@15.4.1/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/hiepxanh/Documents/batcave/awread-project/node_modules/.pnpm/yargs@15.4.1/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/hiepxanh/Documents/batcave/awread-project/node_modules/.pnpm/@nrwl+cli@12.4.0/node_modules/@nrwl/cli/lib/init-local.js:26:79)
    at Object.<anonymous> (/Users/hiepxanh/Documents/batcave/awread-project/node_modules/.pnpm/@nrwl+cli@12.4.0/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 61462,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! awread@0.0.0 nx-run-migration: `nx migrate --run-migrations`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the awread@0.0.0 nx-run-migration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hiepxanh/.npm/_logs/2021-06-26T08_41_02_759Z-debug.log
```

### Environment

```

  Node : 14.17.1
  OS   : darwin x64
  pnpm : 6.9.1
  
  nx : Not Found
  @nrwl/angular : 12.4.0
  @nrwl/cli : 12.4.0
  @nrwl/cypress : 12.4.0
  @nrwl/devkit : 11.5.2
  @nrwl/eslint-plugin-nx : 12.4.0
  @nrwl/express : 12.4.0
  @nrwl/jest : 12.4.0
  @nrwl/linter : 11.5.2
  @nrwl/nest : 12.4.0
  @nrwl/next : Not Found
  @nrwl/node : 12.4.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.4.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.4.0
  @nrwl/storybook : 12.4.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
  ```

**Comment by hiepxanh** [comment]
all migration is smooth, only this, I try to read source code https://github.com/nrwl/nx/blob/a3c08a9153360371ee09771389299201b3407e00/packages/linter/src/utils/rules-requiring-type-checking.ts but no clue for .implementaion

**Comment by hiepxanh** [comment]
close since I upgrade all package to newest version, then delete node_modules, re install

**Comment by justinhandley** [comment]
I am getting this exact error, and clearing node_modules isn't solving it for me - was that all it took to get to a solution for you?
