### ISSUE TITLE
Unable to run 'update-angular-config-v12' migration

### ISSUE THREAD

**Issue by labeled** [nrwl/nx#6206]
## Current Behavior
Unable to run `nx migrate --run-migrations` from Angular 11 to 12.
Migration name = update-angular-config-v12.

## Expected Behavior
Run `nx migrate --run-migrations` without errors

## Steps to Reproduce
We upgarded our nx version from 11.0 to 11.6 without issues. We then upgraded nx from 11.6 to 12.0 without issue. Upgrading from 12.0 to 12.5 introduced the error when running migration `update-angular-config-v12`.
Run npm install
Run nx migrate --run-migrations

Yes

I get a 403 when trying to push a branch up:
remote: Permission to nrwl/nx-examples.git denied to labeled.
fatal: unable to access 'https://github.com/nrwl/nx-examples.git/': The requested URL returned error: 403

https://github.com/labeled/nx-examples

### Failure Logs
```
Running migration update-angular-config-v12
PropertyNameExpected in JSON at position 65188
ui\node_modules\yargs\build\lib\yargs.js:1043:55)      c.voyager.web-ui\node_modules\yargs\build\lib\yargs.js:1132
    at Object.get [as argv] (C:\PIT\Source\Repos\altec.voyager-11\altec.voyager\altec.voyager.web-ui\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\PIT\Source\Repos\altec.voyaTemp\tmp-12680-7DyKGaFdpbMG\node_modules\.bin\tao migrate --run-migrationsger-11\altec.voyager\altec.voyager.web-ui\node_modules\@nrwl\cli\lib\init-local.js:25:79)
    at Object.<anonymous> (C:\PIT\Source\Repos\altec.vor-11\altec.voyager\altec.voyager.web-ui\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:89:25)yager-11\altec.voyager\altec.voyager.web-ui\node_moduleager-11\altec.voyager\altec.voyager.web-ui\node_modules\yargs\build\lib\command.js:197:48)s\@nrwl\cli\bin\nx.js:43:18)                           Repos\altec.voyager-11\altec.voyager\altec.voyager.web-ui\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Module._compile (internal/modules/cjs/loader.js:voyager-11\altec.voyager\altec.voyager.web-ui\node_modules\yargs\build\lib\yargs.js:986:25)1063:30)                                               ger-11\altec.voyager\altec.voyager.web-ui\node_modules\@nrwl\cli\lib\init-local.js:25:79)
    at Object.Module._extensions..js (internal/modules/yager-11\altec.voyager\altec.voyager.web-ui\node_modules\@nrwl\cli\bin\nx.js:43:18)cjs/loader.js:1092:10) {                               1063:30)
  status: 1,                                           cjs/loader.js:1092:10) {
  signal: null,
  output: [ null, null, null ],
  pid: 5456,
  stdout: null,
  stderr: null
}
```

### Environment
>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : win32 x64
  npm  : 7.16.0

  nx : Not Found
  @nrwl/angular : 12.5.0
  @nrwl/cli : 12.5.0
  @nrwl/cypress : 12.5.0
  @nrwl/devkit : 12.5.0
  @nrwl/eslint-plugin-nx : 12.5.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.0
  @nrwl/linter : 12.5.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.0
  @nrwl/storybook : 12.5.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by FrozenPandaz** [comment]
Can you please re-run the migrations with `nx migrate --run-migrations --verbose` and paste the resulting logs?

**Comment by labeled** [comment]
@FrozenPandaz Thank you for the request. I was able to run with the verbose flag but got the same message.

> C:\PIT\Source\Repos\nx-examples>nx migrate --run-migrations --verbose
C:\PIT\Source\Repos\nx-examples\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

>Error: Command failed: yarn
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at taoPath (C:\PIT\Source\Repos\nx-examples\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:324:21)      
    at Object.handler (C:\PIT\Source\Repos\nx-examples\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:88:19)
    at Object.runCommand (C:\PIT\Source\Repos\nx-examples\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\PIT\Source\Repos\nx-examples\node_modules\yargs\build\lib\yargs.js:1043:55)   
    at Object.get [as argv] (C:\PIT\Source\Repos\nx-examples\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\PIT\Source\Repos\nx-examples\node_modules\@nrwl\cli\lib\init-local.js:25:79)
    at Object.<anonymous> (C:\PIT\Source\Repos\nx-examples\node_modules\@nrwl\cli\bin\nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 23452,
  stdout: null,
  stderr: null
}

**Comment by labeled** [comment]
@FrozenPandaz  I was able to run with the verbose flag but it resulted in the same message

>  NX  Running migrations from 'migrations.json'

> Running migration update-angular-config-v12
PropertyNameExpected in JSON at position 72220
Error: PropertyNameExpected in JSON at position 72220
    at Object.parseJson (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules\@nrwl\tao\src\utils\json.js:30:15)
    at NxScopedHostForMigrations.writeWorkspaceConfiguration (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules\@nrwl\tao\src\commands\ngcli-adapter.js:221:31)
    at SwitchMapSubscriber.project (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules\@nrwl\tao\src\commands\ngcli-adapter.js:154:29)
    at SwitchMapSubscriber._next (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules\rxjs\internal\operators\switchMap.js:47:27)
    at SwitchMapSubscriber.Subscriber.next (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules\rxjs\internal\operators\switchMap.js:85:26)
    at SimpleInnerSubscriber._next (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules\rxjs\internal\innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MapSubscriber._next (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules\rxjs\internal\operators\map.js:55:26)
    at MapSubscriber.Subscriber.next (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules\rxjs\internal\Subscriber.js:66:18)

**Comment by labeled** [comment]
@FrozenPandaz  I've done as much as I think I can in researching this issue. It comes down to something the JSON isn't parse using the ta\src\utils\json.js file. 
I was trying to get the output of the JSON it's trying to parse but failing gracefully. Any help you can give would be greatly appreciated.

**Comment by labeled** [comment]
Jason I replied a few days ago and am awaiting further instruction. I wish
I was able to better help debug.

**Comment by SergeyCherman** [comment]
FYI a similar error happened to me and the root cause was I had a trailing comma in one of my objects in the angular.json. Removing it fixed the issue.

**Comment by labeled** [comment]
@SergeyCherman We are using ESLINT to prevent trailing commas in our JSON files. My concern is that some part of the conversion process is removing a property and creating a trailing comma. I however, am unable to debug as I'm not that smart :D I may take some time later to deep dive into the source code to see if I can output the json it's attempting to parse.

**Comment by SergeyCherman** [comment]
I found my issue by issue by adding more logs to the place in nx where exception is thrown. IE in the below file you can add more logs like for example logging the `input` object such that you know which object is causing the issue:

`at Object.parseJson (C:\Users\tlpeters\AppData\Local\Temp\tmp-25916-9dryXxItnHgp\node_modules@nrwl\tao\src\utils\json.js:30:15)
`

**Comment by labeled** [comment]
Unfortunately it appears to create a new tmp folder location every time I run the command so my console.log changes are not applied.

**Comment by SergeyCherman** [comment]
@labeled Not sure if this will work, but maybe it's copying it from the project source node modules... can you try adding logging to this file and see what happens? `node_modules/@nrwl/devkit/node_modules/@nrwl/tao/src/utils/json.js` line 30 is the error handler so you can add debug stmts to it.

**Comment by labeled** [comment]
Thank you @SergeyCherman ! Upon further investigation it looks like the nx-commands.js function `taoPath()` was generating a random path for each run and running npm install. Modifying that random path to an explicit path allowed me to modify the source for subsequent runs. The json was too large for an output window so I stored it in a file and allowed me to see the issue more clearly.

Here is the problem. We use build configurations to change assets based on environments like this.
`"build": {
      "configurations": {
        "dev": {
          "assets": [
            {
              "glob": "configuration.json",
              "input": "./libs/shared/assets/configurations/develop",
              "output": "./assets/configurations"
            },
            {
              "glob": "**/*",
              "input": "./libs/shared/assets",
              "output": "./assets"
            }
          ],
          "buildOptimizer": false,
          "optimization": false,
          "sourceMap": true
        },`
After nx does it's thing it looks like this:
`"build": {
          "configurations": {
            "dev": {
              "assets": [
                {
                  "glob": "configuration.json",
                  "input": "./libs/shared/assets/configurations/develop",
                  "output": "./assets/configurations"
                },
                {
                  "glob": "**/*",
                  "input": "./libs/shared/assets",
                  "output": "./assets"
                }
              ],
            },`
See how the array in assets leaves a trailing comma.

**Comment by labeled** [comment]
I added a few lines of code to remove the trailing commas from within json.js and was able to finish running migrations. (Which didn't actually change anything so it's probably not the right path forward.
let regex = /\,(?!\s*?[\{\[\"\'\w])/g;
let correct = input.replace(regex, '');
const result = jsonc_parser_1.parse(correct, errors);
