### ISSUE TITLE
nx migrate latest fail

### ISSUE THREAD

**Issue by memee** [nrwl/nx#6214]
## Current Behavior

When I run `nx migrate latest`
I get:
```
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest

 ERROR  The migrate command failed. Try the following to migrate your workspace:

> npm install --save-dev @nrwl/workspace@latest
> nx migrate @nrwl/workspace@latest --from="@nrwl/workspace@10.3.3"
This will use the newest version of the migrate functionality, which might have your issue resolved.
----------------------------------------------------------------------------------------------------
Command failed: npm install @nrwl/workspace@latest --prefix=/var/folders/ll/667l8bks4wx2yg04_zs6q01h0000gn/T/tmp-82966TUw3UDqZ61RW
npm ERR! Cannot read property 'spec' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macio/.npm/_logs/2021-07-01T12_37_00_936Z-debug.log

/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: npx tao migrate latest
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15)
    at Object.handler (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:74:21)
    at Object.runCommand (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/cli/lib/init-local.js:24:13)
    at Object.<anonymous> (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/cli/bin/nx.js:12:18)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 82965,
  stdout: null,
  stderr: null
}
```

## Expected Behavior

I expect no error happen when running command.
not a regression

## Steps to Reproduce

run `nx migrate latest`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

https://gist.github.com/memee/b95701573fa2c71ad4b55245b2456a60

### Environment

```
nx report

>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.3.3
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.3
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.3
  @nrwl/linter : 10.3.3
  @nrwl/nest : 10.3.3
  @nrwl/next : Not Found
  @nrwl/node : 10.3.3
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.3
  typescript : 4.0.3
```

**Comment by pete-mcwilliams** [comment]
Similar with update from 12.4 to 12.5.1

Running migration add-target-dependencies
Cannot read property 'default' of undefined

Error: Command failed: /var/folders/2g/x5mf23357m38y6ll4070kftw0000gn/T/tmp-6950-zym2sJ5LjHnH/node_modules/.bin/tao migrate --run-migrations

**Comment by mandarini** [comment]
Hi there @memee ! Did you try the suggestions? If yes, did they solve your issue? If not, can you show the new errors?

(the suggestions I see in your error logs)
```
Try the following to migrate your workspace:

> npm install --save-dev @nrwl/workspace@latest
> nx migrate @nrwl/workspace@latest --from="@nrwl/workspace@10.3.3"
This will use the newest version of the migrate functionality, which might have your issue resolved.
```

**Comment by FrozenPandaz** [comment]
@pete-mcwilliams I think you have a different issue which will be fixed with: https://github.com/nrwl/nx/pull/6252

@memee Please try the suggestion as @mandarini pointed out :smile:

**Comment by memee** [comment]
@FrozenPandaz now I get after first command:
```
npm ERR! While resolving: myproject@1.1.6
npm ERR! Found: prettier@2.0.4
npm ERR! node_modules/prettier
npm ERR!   dev prettier@"2.0.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer prettier@"^2.3.0" from @nrwl/workspace@12.5.7
npm ERR! node_modules/@nrwl/workspace
npm ERR!   dev @nrwl/workspace@"12.5.7" from the root project
```

**Comment by memee** [comment]
Seems I need to upgrade prettier?

**Comment by memee** [comment]
Thank you, some how I managed to go through the process although there was lots of conflicts in peer deps.

**Comment by memee** [comment]
Although now I get:
```
nx migrate --run-migrations

>  NX  Running 'npm install' to make sure necessary packages are installed

npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> smartom@1.1.6 preinstall
> [ -r .env ] && echo '.env file exists, skipping' || cp env.example .env && mkdir -p ./node_modules && touch ./node_modules/.metadata_never_index

.env file exists, skipping

> smartom@1.1.6 postinstall
> node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points


>  NX  Angular CLI has been decorated to enable computation caching.

Compiling @ngrx/store-devtools : es2015 as esm2015
Compiling @nrwl/angular : es2015 as esm2015
Compiling @nrwl/angular/testing : es2015 as esm2015

added 316 packages, removed 218 packages, changed 439 packages, and audited 3084 packages in 54s

143 packages are looking for funding
  run `npm fund` for details

33 vulnerabilities (1 low, 7 moderate, 19 high, 6 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

>  NX  Running migrations from 'migrations.json'

Running migration add-explicit-dep-on-tao
Successfully finished add-explicit-dep-on-tao
---------------------------------------------------------
Running migration update-script-to-invoke-nx-migrate
Successfully finished update-script-to-invoke-nx-migrate
---------------------------------------------------------
Running migration update-decorate-angular-cli
Successfully finished update-decorate-angular-cli
---------------------------------------------------------
Running migration update-node-types
Successfully finished update-node-types
---------------------------------------------------------
Running migration rename-workspace-schematics
Successfully finished rename-workspace-schematics
---------------------------------------------------------
Running migration add-outputs-in-workspace
Successfully finished add-outputs-in-workspace
---------------------------------------------------------
Running migration update-command-check
Successfully finished update-command-check
---------------------------------------------------------
Running migration rename-workspace-schematic-script
Successfully finished rename-workspace-schematic-script
---------------------------------------------------------
Running migration add-target-dependencies

>  NX   NOTE  Target dependencies have been updated in nx.json

  Nx has deprecated strictlyOrderedTargets in favour of targetDependencies.
  Based on your configuration the migration has configured targetDependencies for the following targets: build.
  Read more here: https://nx.dev/core-concepts/configuration

Successfully finished add-target-dependencies
---------------------------------------------------------
Running migration update-10-4-0
Successfully finished update-10-4-0
---------------------------------------------------------
Running migration add-template-support-and-presets-to-eslint
Successfully finished add-template-support-and-presets-to-eslint
---------------------------------------------------------
Running migration update-11-0-0
Successfully finished update-11-0-0
---------------------------------------------------------
Running migration update-ngcc-postinstall
Successfully finished update-ngcc-postinstall
---------------------------------------------------------
Running migration update-webpack-browser-config
Successfully finished update-webpack-browser-config
---------------------------------------------------------
Running migration update-storybook
Successfully finished update-storybook
---------------------------------------------------------
Running migration update-angular-eslint-rules
Successfully finished update-angular-eslint-rules
---------------------------------------------------------
Running migration convert-webpack-browser-build-target-to-delegate-build
Successfully finished convert-webpack-browser-build-target-to-delegate-build
---------------------------------------------------------
Running migration update-jest-preset-angular-8-4-0
Successfully finished update-jest-preset-angular-8-4-0
---------------------------------------------------------
Running migration update-ts-jest-6-5-5
Successfully finished update-ts-jest-6-5-5
---------------------------------------------------------
Running migration support-jest-27
Successfully finished support-jest-27
---------------------------------------------------------
Running migration update-ts-jest-and-jest-preset-angular
transformers.some is not a function
/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/ll/667l8bks4wx2yg04_zs6q01h0000gn/T/tmp-55839-SNg0lBqRg0JG/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15)
    at Object.handler (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:89:25)
    at Object.runCommand (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/cli/lib/init-local.js:24:13)
    at Object.<anonymous> (/Users/macio/Projects/smartfm-workspace/smartfm/node_modules/@nrwl/cli/bin/nx.js:12:18)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 55843,
  stdout: null,
  stderr: null
}
```

**Comment by Mathuzan** [comment]
Any updates, I couldn't figure out the answer for the question from the above suggestions.
