### ISSUE TITLE
unable to build something is anchored to typescript 4.3.5 ecosystem breached blocked

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#6223]
Blocked, cant build... too lengthy of operations to list concisely

the chronology I logged mostly at this ticket
https://github.com/nrwl/nx/issues/5487

## Current Behavior
cannot build being blocked something is hooking typescript revision at 4.3.5 when 4.1.6 is successfully installed

## Expected Behavior
typescript should be gracefully installed and maintained in the npm yarn ecosystem so we can build our nrwl/nx workspace of 200k+ lines of code apps servers

something is preventing typescript from building when its successfully installed
both yarn and npm permutations were exercised

## Steps to Reproduce
attempt upgrade of workspace to angular@12+
performed nx migrate latest
too many flanking issues prompted me to roll back though nrwl was fine the angular/webpack issues with 'fs', cb.apply(), jest impact to ecosystem and a slew of other issues too many to log

rollback to @angular/cli@11.6.3
rollback @nrwl@11.6.3

all attempts to install typescript using yarn or npm succeed but the build continuies to fail seeking typescript@4.3.5

something under the hood is anchored to typescript@4.3.5

and I am blocked

lengthy build details are in chronological order at this ticket

https://github.com/nrwl/nx/issues/5487

and this one
https://github.com/nrwl/nx/issues/907

### Failure Logs
```
> nx run mobile-app:build 

An error occurred during the build:
Error: The Angular Compiler requires TypeScript >=4.0.0 and <4.2.0 but 4.3.5 was found instead.
    at checkVersion (/Users/meanstack02/new/energy/node_modules/@angular/compiler-cli/src/typescript_support.js:65:19)
    at Object.verifySupportedTypeScriptVersion (/Users/meanstack02/new/energy/node_modules/@angular/compiler-cli/src/typescript_support.js:70:9)
    at new NgtscProgram (/Users/meanstack02/new/energy/node_modules/@angular/compiler-cli/src/ngtsc/program.js:44:38)
    at AngularWebpackPlugin.updateAotProgram (/Users/meanstack02/new/energy/node_modules/@ngtools/webpack/src/ivy/plugin.js:275:32)
    at /Users/meanstack02/new/energy/node_modules/@ngtools/webpack/src/ivy/plugin.js:164:24
    at SyncHook.eval [as call] (eval at create (/Users/meanstack02/new/energy/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/meanstack02/new/energy/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/meanstack02/new/energy/node_modules/webpack/lib/Compiler.js:630:30)
    at /Users/meanstack02/new/energy/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/meanstack02/new/energy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/meanstack02/new/energy/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/meanstack02/new/energy/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/meanstack02/new/energy/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Users/meanstack02/new/energy/node_modules/webpack/lib/Compiler.js:529:11)
    at /Users/meanstack02/new/energy/node_modules/webpack/lib/Compiler.js:318:10
    at eval (eval at create (/Users/meanstack02/new/energy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
The Angular Compiler requires TypeScript >=4.0.0 and <4.2.0 but 4.3.5 was found instead.

>  NX   CLOUD  See run details at https://nx.app/runs/xcFlXJSsG7X

make: *** [mob] Error 1
meanstack02@admin energy % 
```

### Environment
mac os

node.js v12.22.1

@angular/cli@11.6.3

@nrwl@11.6.3

typescript@4.1.6

**Comment by nhhockeyplayer** [comment]
just an update on this

I created a brand new workspace using latest nrwl/nx

and observed that typescript isnt even part of the package.json

so I took the leap of faith and  did

yarn remove typescript
nx migrate latest
rm -rf node_modules
yarn install

and I am building now

I dont see anywhere docs or notes stating that a higher order build entity has taken charge of typescript at this juncture

but it feels valid at this time

and I am building

fingers crossed

nrwl/nx is the best

keep up the elite work guys

**Comment by nhhockeyplayer** [comment]
webpack is menacing to my monorepo and I have not used it nor asked for it

here is one error

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
```

maybe webpack needs to be put on ice also... like the way typescript is being handled?

feedback is appreciated

these kinds of problems are ruining builds and some of the threads I see sound very frustrating and burning folks out

if Nrwl can put a stop to this I would love to see it

**Comment by nhhockeyplayer** [comment]
I closed this but it remains an issue. Feel free to re-open
