### ISSUE TITLE
Nest app creation + standalone options prints errors logs

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#6249]
## Current Behavior
Nest app creation + standalone config option, show error logs

## Expected Behavior
Nest app should be created with the standalone config without errors in the logs

## Steps to Reproduce
1. Creante an empty workspace
2. Install @nrwl/nest package
3. run `nx generate @nrwl/nest:application --name=api --standaloneConfig --no-interactive`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
```
Terminal will be reused by tasks, press any key to close it.

> Executing task: nx generate @nrwl/nest:application --name=api --standaloneConfig --no-interactive --dry-run <

Failed to format: /angular.json
Error: 'project.json' files are incompatible with version 1 workspace schemas.
    at /Users/gperdomor/Downloads/empty/node_modules/@nrwl/node/node_modules/@nrwl/tao/src/shared/workspace.js:208:19
    at Array.forEach (<anonymous>)
    at toOldFormatOrNull (/Users/gperdomor/Downloads/empty/node_modules/@nrwl/node/node_modules/@nrwl/tao/src/shared/workspace.js:206:37)
    at Object.reformattedWorkspaceJsonOrNull (/Users/gperdomor/Downloads/empty/node_modules/@nrwl/node/node_modules/@nrwl/tao/src/shared/workspace.js:167:53)
    at updateWorkspaceJsonToMatchFormatVersion (/Users/gperdomor/Downloads/empty/node_modules/@nrwl/node/node_modules/@nrwl/devkit/src/generators/format-files.js:59:41)
    at Object.<anonymous> (/Users/gperdomor/Downloads/empty/node_modules/@nrwl/node/node_modules/@nrwl/devkit/src/generators/format-files.js:21:9)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/gperdomor/Downloads/empty/node_modules/tslib/tslib.js:114:62)
Failed to format: /angular.json
Error: 'project.json' files are incompatible with version 1 workspace schemas.
    at /Users/gperdomor/Downloads/empty/node_modules/@nrwl/node/node_modules/@nrwl/tao/src/shared/workspace.js:208:19
    at Array.forEach (<anonymous>)
    at toOldFormatOrNull (/Users/gperdomor/Downloads/empty/node_modules/@nrwl/node/node_modules/@nrwl/tao/src/shared/workspace.js:206:37)
    at Object.reformattedWorkspaceJsonOrNull (/Users/gperdomor/Downloads/empty/node_modules/@nrwl/node/node_modules/@nrwl/tao/src/shared/workspace.js:167:53)
    at updateWorkspaceJsonToMatchFormatVersion (/Users/gperdomor/Downloads/empty/node_modules/@nrwl/node/node_modules/@nrwl/devkit/src/generators/format-files.js:59:41)
    at Object.<anonymous> (/Users/gperdomor/Downloads/empty/node_modules/@nrwl/node/node_modules/@nrwl/devkit/src/generators/format-files.js:21:9)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/gperdomor/Downloads/empty/node_modules/tslib/tslib.js:114:62)
CREATE jest.config.js
CREATE jest.preset.js
CREATE apps/api/src/app/.gitkeep
CREATE apps/api/src/assets/.gitkeep
CREATE apps/api/src/environments/environment.prod.ts
CREATE apps/api/src/environments/environment.ts
CREATE apps/api/src/main.ts
CREATE apps/api/tsconfig.app.json
CREATE apps/api/tsconfig.json
CREATE apps/api/project.json
CREATE .eslintrc.json
CREATE apps/api/.eslintrc.json
CREATE apps/api/jest.config.js
CREATE apps/api/tsconfig.spec.json
CREATE apps/api/src/app/app.controller.spec.ts
CREATE apps/api/src/app/app.controller.ts
CREATE apps/api/src/app/app.module.ts
CREATE apps/api/src/app/app.service.spec.ts
CREATE apps/api/src/app/app.service.ts
UPDATE workspace.json
UPDATE nx.json
UPDATE package.json
UPDATE .vscode/extensions.json
UPDATE tsconfig.base.json

NOTE: The "dryRun" flag means no changes were made.
```
### Environment

 NX  Report complete - copy this into the issue template

  Node : 16.4.1
  OS   : darwin x64
  npm  : 7.19.1
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.5
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.5.5
  @nrwl/eslint-plugin-nx : 12.5.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.6
  @nrwl/linter : 12.5.6
  @nrwl/nest : 12.5.6
  @nrwl/next : Not Found
  @nrwl/node : 12.5.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.5
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.5
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by brandonroberts** [comment]
@gperdomor Your `angular.json` has to be on version 2 or later. So you'll need to update the `version` in your `angular.json` to `2`, and run `nx format` to run the update the file.

**Comment by gperdomor** [comment]
@brandonroberts I'm using `workspace.json` not `angular.json`

**Comment by AgentEnder** [comment]
This is fixed in latest master, and should be fixed in the next release. If you are still experiencing this issue afterwards, please reopen this issue.
