### ISSUE TITLE
Error nx in pipeline

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [nrwl/nx#6292]
## Current Behavior
Periodically when running commands:
```
npm run nx affected -- --target=lint --base=refs/remotes/origin/dev --parallel
npm run nx affected -- --target=test --base=origin/dev --codeCoverage=true --maxWorkers=4 --parallel --ci --silent
npm run nx affected:dep-graph -- --base=origin/dev --file=./tmp/affected.json', {stdio: 'inherit'}
nx print-affected --select=tasks.target.project --target=build --base=origin/dev --head=HEAD
```
An error appears, you have to restart it several times for the job to be completed successfully.
nx version 12.0.8
git version  2.20.1
GITLAB version 13.10.5-ee.0
Gitlab was recently updated to 2 major versions.
What could be the problem with this behavior?

### Failure Logs

```

 npm run conditional:lint

> project@0.0.0 conditional:lint /builds/frontend/project
> node ./tools/scripts/conditional --lint

> project@0.0.0 nx /builds/frontend/project
> nx "affected:dep-graph" "--base=origin/dev" "--file=./tmp/affected.json"

nx affected:dep-graph

Graph dependencies affected by changes

Run command using --base=[SHA1] (affected by the committed, uncommitted and
untracked changes):
  --base  Base of the current branch (usually master)                   [string]

or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
  --base  Base of the current branch (usually master)                   [string]
  --head  Latest commit of the current branch (usually HEAD)            [string]

or using:
  --files        Change the way Nx is calculating the affected command by
                 providing directly changed files, list of files delimited by
                 commas                                                  [array]
  --uncommitted  Uncommitted changes                                   [boolean]
  --untracked    Untracked changes                                     [boolean]

Options:
  --help           Show help                                           [boolean]
  --version        Show version number                                 [boolean]
  --file           output file (e.g. --file=output.json or
                   --file=dep-graph.html)                               [string]
  --focus          Use to show the dependency graph for a particular project and
                   every node that is either an ancestor or a descendant.
                                                                        [string]
  --exclude        Exclude certain projects from being processed
                                                           [array] [default: []]
  --groupByFolder  Group projects by folder in dependency graph        [boolean]
  --host           Bind the dep graph server to a specific ip address.  [string]
  --port           Bind the dep graph server to a specific port.        [number]
  --all            All projects                                        [boolean]
  --runner         This is the name of the tasks runner configured in nx.json
                                                                        [string]
  --skip-nx-cache  Rerun the tasks even when the results are available in the
                   cache                              [boolean] [default: false]
  --configuration  This is the configuration to use when performing tasks on
                   projects                                             [string]
  --only-failed    Isolate projects which previously failed
                                                      [boolean] [default: false]
  --verbose        Print additional error stack trace on failure

Error: Command failed: git merge-base --fork-point "origin/dev" "HEAD"
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at getFilesUsingBaseAndHead (/builds/frontend/project/node_modules/@nrwl/workspace/src/command-line/shared.js:55:37)
    at Object.parseFiles (/builds/frontend/project/node_modules/@nrwl/workspace/src/command-line/shared.js:31:20)
    at Object.<anonymous> (/builds/frontend/project/node_modules/@nrwl/workspace/src/command-line/affected.js:26:112)
    at Generator.next (<anonymous>)
    at fulfilled (/builds/frontend/project/node_modules/tslib/tslib.js:114:62) {
  status: 1,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 73,
  stdout: <Buffer >,
  stderr: <Buffer >
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.0.0 nx: `nx "affected:dep-graph" "--base=origin/dev" "--file=./tmp/affected.json"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project@0.0.0 nx script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-08T09_10_26_538Z-debug.log
child_process.js:674
    throw err;
    ^

Error: Command failed: npm run nx affected:dep-graph -- --base=origin/dev --file=./tmp/affected.json
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at Object.<anonymous> (/builds/frontend/project/tools/scripts/conditional.js:49:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 30,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.0.0 conditional:lint: `node ./tools/scripts/conditional --lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project@0.0.0 conditional:lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-08T09_10_26_594Z-debug.log
```
When executing such a command, I get the following error. Restarting the build several times helps to solve the problem.
>nx print-affected --select=tasks.target.project --target=build --base=origin/dev --head=HEAD
```
nx print-affected

Graph execution plan

Run command using --base=[SHA1] (affected by the committed, uncommitted and
untracked changes):
  --base  Base of the current branch (usually master)                   [string]

or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
  --base  Base of the current branch (usually master)                   [string]
  --head  Latest commit of the current branch (usually HEAD)            [string]

or using:
  --files        Change the way Nx is calculating the affected command by
                 providing directly changed files, list of files delimited by
                 commas                                                  [array]
  --uncommitted  Uncommitted changes                                   [boolean]
  --untracked    Untracked changes                                     [boolean]

Options:
  --help           Show help                                           [boolean]
  --version        Show version number                                 [boolean]
  --select                                                              [string]
  --all            All projects                                        [boolean]
  --exclude        Exclude certain projects from being processed
                                                           [array] [default: []]
  --runner         This is the name of the tasks runner configured in nx.json
                                                                        [string]
  --skip-nx-cache  Rerun the tasks even when the results are available in the
                   cache                              [boolean] [default: false]
  --configuration  This is the configuration to use when performing tasks on
                   projects                                             [string]
  --only-failed    Isolate projects which previously failed
                                                      [boolean] [default: false]
  --verbose        Print additional error stack trace on failure

Error: Command failed: git merge-base --fork-point "origin/dev" "HEAD"
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at getFilesUsingBaseAndHead (/builds/frontend/project/node_modules/@nrwl/workspace/src/command-line/shared.js:55:37)
    at Object.parseFiles (/builds/frontend/project/node_modules/@nrwl/workspace/src/command-line/shared.js:25:20)
    at Object.<anonymous> (/builds/frontend/project/node_modules/@nrwl/workspace/src/command-line/affected.js:26:112)
    at Generator.next (<anonymous>)
    at fulfilled (/builds/frontend/project/node_modules/tslib/tslib.js:114:62) {
  status: 1,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 57,
  stdout: <Buffer >,
  stderr: <Buffer >
}
```

**Comment by FrozenPandaz** [comment]
It's hard to tell but it seems like your `HEAD` has no common ancestor commits to `origin/dev`.

Does this happen for PRs where there are many commits? I suspect either `origin/dev` or `HEAD` is checked out shallowly and might have enough commits to contain the ancestor commit. Could you try to increase the depth at which the checkout occurs?

Is it possible to provide a repo with some specific instructions for checking out the branch that exhibits this issue?

**Comment by IlyaNakhaichuk** [comment]
This happens in a new branch, and 5 commits in a row can be successful, and then similar errors start to appear.
Pulling back on main, dev, solves the problem for the next few commits.
I increased the depth on jobs to 200-500, but this did not help, the problem still remained.
Tried adding a key to nx --with-deps, didn't help solve either.

**Comment by iKrishnaSahu** [comment]
@IlyaNakhaichuk did you find any solution to fix this issue coz I am also facing the same issue?
