### ISSUE TITLE
Renaming exports from a shared lib breaks e2e cypress tests

### ISSUE THREAD

**Issue by ramorris3** [nrwl/nx#6337]
## Current Behavior
When I rename exports in a common library (i.e. `export * as NavConstants from './nav.const';`), importing them into e2e tests causes a webpack error:

```
Error: Webpack Compilation Error
/Users/grumpus/code/halcyon/libs/common/src/lib/index.ts 1:9
Module parse failed: Unexpected token (1:9)
File was processed with these loaders:
 * ../../node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
> export * as NavConstants from './nav.const';
```

## Expected Behavior
I should be able to rename exports from the shared lib, and have e2e test code compile without errors, the same way it does when serving the app. (I don't get the same webpack error when running `yarn nx serve ...`)

## Steps to Reproduce

Reproduced here: https://github.com/ramorris3/nx-cypress with these steps:

* create Nx repo: `npx --ignore-existing create-nx-workspace halcyon` (choose `empty`)
* add Next support: `yarn add @nrwl/next`
* generate Next app with e2e: `yarn nx g @nrwl/next:app garden`
* run e2e, notice it works: `yarn nx e2e garden-e2e`
* generate common lib: `yarn nx g lib common`
* export '*' from common lib and rename, i.e. `export * as NavConstants from './nav.const';` 
* import into `apps/garden-e2e/src/integration/app.spec.ts`.
* run e2e, notice it fails with the above webpack compilation error

### Failure Logs
```
> nx run garden-e2e:e2e
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
info  - automatically enabled Fast Refresh for 1 custom loader
info  - Using external babel configuration from /Users/grumpus/code/halcyon/apps/garden/.babelrc
event - compiled successfully
[ ready ] on http://localhost:4200
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
info  - Using external babel configuration from /Users/grumpus/code/halcyon/libs/common/.babelrc
event - compiled successfully

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    7.7.0                                                                              │
  │ Browser:    Electron 89                                                                        │
  │ Specs:      1 found (app.spec.ts)                                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  app.spec.ts                                                                     (1 of 1)
Starting type checking service...
Using 1 worker with 2048MB memory limit
Starting type checking service...
Using 1 worker with 2048MB memory limit

Oops...we found an error preparing this test file:

  src/integration/app.spec.ts

The error was:

Error: Webpack Compilation Error
/Users/grumpus/code/halcyon/libs/common/src/lib/index.ts 1:9
Module parse failed: Unexpected token (1:9)
File was processed with these loaders:
 * ../../node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
> export * as NavConstants from './nav.const';
|
 @ /Users/grumpus/code/halcyon/libs/common/src/index.ts 1:0-22 1:0-22
 @ ./src/integration/app.spec.ts
 @ multi ./src/integration/app.spec.ts
    at handle (/Users/grumpus/code/halcyon/node_modules/@cypress/webpack-preprocessor/index.js:128:15)
    at finalCallback (/Users/grumpus/code/halcyon/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/grumpus/code/halcyon/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/grumpus/code/halcyon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/grumpus/code/halcyon/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/grumpus/code/halcyon/node_modules/webpack/lib/Compiler.js:271:21)
    at /Users/grumpus/code/halcyon/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/grumpus/code/halcyon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/grumpus/code/halcyon/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/grumpus/code/halcyon/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/grumpus/code/halcyon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/grumpus/code/halcyon/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/grumpus/code/halcyon/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/grumpus/code/halcyon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/grumpus/code/halcyon/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/grumpus/code/halcyon/node_modules/webpack/lib/Compilation.js:1414:32
    at eval (eval at create (/Users/grumpus/code/halcyon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/grumpus/code/halcyon/node_modules/webpack/node_modules/terser-webpack-plugin/dist/index.js:321:9
    at TaskRunner.run (/Users/grumpus/code/halcyon/node_modules/webpack/node_modules/terser-webpack-plugin/dist/TaskRunner.js:48:7)
    at TerserPlugin.optimizeFn (/Users/grumpus/code/halcyon/node_modules/webpack/node_modules/terser-webpack-plugin/dist/index.js:227:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/grumpus/code/halcyon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/grumpus/code/halcyon/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/grumpus/code/halcyon/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/grumpus/code/halcyon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/grumpus/code/halcyon/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/grumpus/code/halcyon/node_modules/webpack/lib/Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/grumpus/code/halcyon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/grumpus/code/halcyon/node_modules/tapable/lib/Hook.js:154:20)
    at createDeferred (/Users/grumpus/code/halcyon/node_modules/@cypress/webpack-preprocessor/deferred.js:6:22)
    at /Users/grumpus/code/halcyon/node_modules/@cypress/webpack-preprocessor/index.js:103:24
    at /Users/grumpus/code/halcyon/packages/cypress/src/plugins/preprocessor.ts:20:34
    at Generator.next (<anonymous>)
    at /Users/grumpus/code/halcyon/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/grumpus/code/halcyon/node_modules/tslib/tslib.js:113:16)
    at Object.handler (/Users/grumpus/code/halcyon/packages/cypress/src/plugins/preprocessor.ts:16:28)
    at invoke (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:22:16)
    at /Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:45:14
    at Object.wrapChildPromise (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:44:23)
    at Object.wrap (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/preprocessor.js:28:8)
    at execute (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:119:27)
    at EventEmitter.<anonymous> (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:202:5)
    at EventEmitter.emit (events.js:315:20)
    at process.<anonymous> (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:19:22)
    at process.emit (events.js:315:20)
    at process.emit (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
From previous event:
    at Object.wrapParentPromise (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:63:12)
    at Object.file:preprocessor (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:132:23)
    at Object.execute (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/index.js:217:33)
    at /Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/preprocessor.js:102:22
From previous event:
    at Object.getFile (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/preprocessor.js:101:65)
    at SocketE2E.watchTestFileByPath (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/socket-e2e.js:71:39)
    at Socket.<anonymous> (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/socket-e2e.js:83:26)
    at Socket.emit (events.js:315:20)
    at Socket.emitUntyped (/Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/grumpus/Library/Caches/Cypress/7.7.0/Cypress.app/Contents/Resources/app/packages/socket/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

### Environment

```  
  Node : 14.16.1
  OS   : darwin x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.7
  @nrwl/cypress : 12.5.7
  @nrwl/devkit : 12.5.7
  @nrwl/eslint-plugin-nx : 12.5.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.7
  @nrwl/linter : 12.5.7
  @nrwl/nest : Not Found
  @nrwl/next : 12.5.7
  @nrwl/node : Not Found
  @nrwl/react : 12.5.7
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.7
  @nrwl/web : 12.5.7
  @nrwl/workspace : 12.5.7
  @nrwl/storybook : 12.5.7
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by ramorris3** [comment]
The `You may need an additional loader to handle the result of these loaders` line is also showing up in https://github.com/nrwl/nx/issues/5288.  

Is this issue possibly happening because of the default usage of `ts-loader`?  I *think* the Next app in my test repo uses a babel loader when serving the app (with no webpack error), which is different from the OOTB config for e2e apps in Nx, which seem to use this ts-loader instead

Based on this readme: https://github.com/cypress-io/cypress/tree/master/npm/webpack-preprocessor#webpackoptions, cypress needs some specific options to be set in order to use babel instead of ts-loader

**Comment by kevinolivar** [comment]
Could it be related to this? https://github.com/nrwl/nx/issues/6370

**Comment by ramorris3** [comment]
> Could it be related to this? #6370

Hmm I'm not sure, but I don't think so?  I'm not doing any file renaming or file structure flattening

**Comment by docwhite** [comment]
I'm having this same issue... If I do not do the renaming then it works:

```
export * from './nav.const';
```

For now I will do the renaming on the import side I guess... I got stuck for hours already.

**Comment by barbados-clemens** [comment]
Is this still an issue on the latest version of nx?
