### ISSUE TITLE
nx g @nrwl/nest:application changes `/` in project paths to `\\` in workspace.json

### ISSUE THREAD

**Issue by Ionaru** [nrwl/nx#6353]
## Current Behavior
When I generate a new NestJS application in my Nx workspace, `\\` is now used where a `/` was in the workspace.json file for project paths.
However this only applies to existing projects, the newly generated project does use `/`.

## Expected Behavior
The application generator does not change or mix `/` and `\\` usage.

## Steps to Reproduce
1. `create-nx-workspace --name test-project --preset empty --nx-cloud false`
2. `cd test-project`
3. `cat workspace.json`

```json
{
  "version": 2,
  "projects": {},
  "cli": {
    "defaultCollection": "@nrwl/workspace"
  }
}
```

4. `npm i -D @nrwl/nest`
5. `nx g @nrwl/nest:application api --standaloneConfig`

Above command prints out an error but does succeed, see issue #6249, possibly relevant. However this behaviour still occurs even if I omit `--standaloneConfig` from the second command (step 7) and the error does not happen then.

```
Failed to format: /angular.json
Error: 'project.json' files are incompatible with version 1 workspace schemas.
    at C:\Users\Jeroen\Projects\test-project\node_modules\@nrwl\tao\src\shared\workspace.js:208:19
    at Array.forEach (<anonymous>)
    at toOldFormatOrNull (C:\Users\Jeroen\Projects\test-project\node_modules\@nrwl\tao\src\shared\workspace.js:206:37)
    at Object.reformattedWorkspaceJsonOrNull (C:\Users\Jeroen\Projects\test-project\node_modules\@nrwl\tao\src\shared\workspace.js:167:53)
    at updateWorkspaceJsonToMatchFormatVersion (C:\Users\Jeroen\Projects\test-project\node_modules\@nrwl\devkit\src\generators\format-files.js:59:41)
    at Object.<anonymous> (C:\Users\Jeroen\Projects\test-project\node_modules\@nrwl\devkit\src\generators\format-files.js:21:9)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Jeroen\Projects\test-project\node_modules\tslib\tslib.js:114:62)
Failed to format: /angular.json
Error: 'project.json' files are incompatible with version 1 workspace schemas.
    at C:\Users\Jeroen\Projects\test-project\node_modules\@nrwl\tao\src\shared\workspace.js:208:19
    at Array.forEach (<anonymous>)
    at toOldFormatOrNull (C:\Users\Jeroen\Projects\test-project\node_modules\@nrwl\tao\src\shared\workspace.js:206:37)
    at Object.reformattedWorkspaceJsonOrNull (C:\Users\Jeroen\Projects\test-project\node_modules\@nrwl\tao\src\shared\workspace.js:167:53)
    at updateWorkspaceJsonToMatchFormatVersion (C:\Users\Jeroen\Projects\test-project\node_modules\@nrwl\devkit\src\generators\format-files.js:59:41)
    at Object.<anonymous> (C:\Users\Jeroen\Projects\test-project\node_modules\@nrwl\devkit\src\generators\format-files.js:21:9)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Jeroen\Projects\test-project\node_modules\tslib\tslib.js:114:62)
```

6. `cat workspace.json`

```json
{
  "version": 2,
  "projects": {
    "api": "apps/api"
  },
  "cli": {
    "defaultCollection": "@nrwl/nest"
  },
  "defaultProject": "api"
}
```

7. `nx g @nrwl/nest:application api2 --standaloneConfig`
8. `cat workspace.json`

```json
{
  "version": 2,
  "projects": {
    "api": "apps\\api",
    "api2": "apps/api2"
  },
  "cli": {
    "defaultCollection": "@nrwl/nest"
  },
  "defaultProject": "api"
}
```

### Failure Logs
None.

### Environment
```
  Node : 14.16.0
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.8
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : 12.5.8
  @nrwl/next : Not Found
  @nrwl/node : 12.5.8
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by FrozenPandaz** [comment]
@AgentEnder I thought https://github.com/nrwl/nx/pull/6276/files would fix this issue? Can you take a look please?

**Comment by Ionaru** [comment]
@AgentEnder @FrozenPandaz This still happens with the `@nrwl/angular:app` generator but slightly different.

The generator leaves the existing configs alone, but the created application (not the e2e one) uses `\\` in its path.
![image](https://user-images.githubusercontent.com/3472373/126882869-69c6eb73-a227-4613-8000-70d2e02ecca6.png)

Environment:
```
  Node : 16.5.0
  OS   : win32 x64
  npm  : 7.20.1

  nx : Not Found
  @nrwl/angular : 12.6.2
  @nrwl/cli : 12.6.2
  @nrwl/cypress : 12.6.2
  @nrwl/devkit : 12.6.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.2
  @nrwl/linter : 12.6.2
  @nrwl/nest : 12.6.2
  @nrwl/next : Not Found
  @nrwl/node : 12.6.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.2
  @nrwl/storybook : 12.6.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by AgentEnder** [comment]
Hey, I've been looking into this recently and have almost pinned it down. I could fix it easily by forcing the workspace path to be normalized, but it's set on project.root currently. I want to figure out what's causing that to be pulling in a windows path rather than fixing a symptom.

**Comment by AgentEnder** [comment]
I'm tracking work on this under #6411, which is currently open.

**Comment by Ionaru** [comment]
Sounds good. Thank you for the quick reply!
