### ISSUE TITLE
nx serve crashes after renaming a file (ProjectGraph related)

### ISSUE THREAD

**Issue by skydever** [nrwl/nx#6360]
## Current Behavior
After renaming a file (in a lib) and adopting the references accordingly, `nx run my-app:serve:my-config` crashes with the following message:

```
(node:35320) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '...some-path...\my-workspace\libs\my-lib\src\lib\some-path-to-directive\old-directive-name.directive.ts'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.defaultFileRead (...some-path...\my-workspace\node_modules\@nrwl\workspace\src\core\file-utils.js:160:17)
    at TypeScriptImportLocator.fromFile (...some-path...\my-workspace\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\typescript-import-locator.js:22:38)
    at ...some-path...\my-workspace\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\explicit-project-dependencies.js:11:27
    at Array.forEach (<anonymous>)
    at ...some-path...\my-workspace\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\explicit-project-dependencies.js:10:44
    at Array.forEach (<anonymous>)
    at buildExplicitTypeScriptDependencies (...some-path...\my-workspace\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\explicit-project-dependencies.js:9:30)
    at ...some-path...\my-workspace\node_modules\@nrwl\workspace\src\core\project-graph\project-graph.js:72:41
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After committing the rename, `nx run my-app:serve:my-config` starts to work again.

## Expected Behavior

`nx run my-app:serve:my-config` should not crash after renaming a file.

### Environment

```
  Node : 14.17.1
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : 12.6.0-beta.6
  @nrwl/cli : 12.6.0-beta.6
  @nrwl/cypress : 12.6.0-beta.6
  @nrwl/devkit : 12.6.0-beta.6
  @nrwl/eslint-plugin-nx : 12.6.0-beta.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.0-beta.6
  @nrwl/linter : 12.6.0-beta.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.0-beta.6
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.0-beta.6
  @nrwl/storybook : 12.6.0-beta.6
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by kevinolivar** [comment]
Most likely related to https://github.com/nrwl/nx/issues/6370
