### ISSUE TITLE
Error: ENOENT: no such file or directory" for deleted file

### ISSUE THREAD

**Issue by kevinolivar** [nrwl/nx#6370]
This bug is already described here https://github.com/nrwl/nx/issues/3370 and recently, there has been a request to have it re-opened but seems still not.

The present ticket was opened in the hope that this will be fixed once and for all. Indeed, this bug is detrimental to the developer's workflow. Therefore, questioning the use of NX. The next information in this ticket is mostly repeated from https://github.com/nrwl/nx/issues/3370. 

## Note
In my case, it was resolved after making sure that the nx root folder was the git root folder.

Not working:
```
project
     - .git/
     - nx folder
     - documentation
     - security
     - ...
```

Working:
```
project
     - nx folder
        - .git/
        - documentation
        - security
        - ...
```

However, there is a need for the sub-folder structure for other developers and sometimes, it is not possible to change the folder structure. In addition, the different mentioned work arounds (git stash, git -ma) are not considered the proper solutions as NX should correctly handle the deleted, renamed or moved files.

## Current Behavior
After deleting any file in the repository there is an error with `yarn start` (also with other "affected" commands such as `yarn affected:lint`, `yarn affected:test`) 

"Error: ENOENT: no such file or directory {{old location of the file}}". 

### Note
This is also affecting the components importing those files as well as modification to the files itself in some cases (!).
It is not related to NX cache but rather this https://github.com/nrwl/nx/issues/3370#issuecomment-858391601

## Expected Behavior
Should not be an error after file is removed in case it is not used in project source locally. 
It also happens when renaming or moving any file around.

## Steps to Reproduce

1. create new workspace via npx create-nx-workspace@latest with Angular or React app
2. run yarn start or affected:lint
3. delete any component (eg. app.component.spec.ts)
4. run yarn start or affected:lint again
5. get error message

## Failure logs

`Error: ENOENT: no such file or directory, open {{old location of the file}}
at Object.openSync (fs.js:458:3)
at Object.readFileSync (fs.js:360:35) [...]`

## Environment

```
macOS Big Sur 11.2.3
git version 2.30.1
```
    "@nrwl/cli": "12.5.8",
    "@nrwl/cypress": "12.5.8",
    "@nrwl/eslint-plugin-nx": "12.5.8",
    "@nrwl/express": "12.5.8",
    "@nrwl/jest": "12.5.8",
    "@nrwl/linter": "12.5.8",
    "@nrwl/next": "12.5.8",
    "@nrwl/node": "12.5.8",
    "@nrwl/react": "12.5.8",
    "@nrwl/storybook": "12.5.8",
    "@nrwl/tao": "12.5.8",
    "@nrwl/web": "12.5.8",
    "@nrwl/workspace": "12.5.8",
    "typescript": "~4.3.5",
    "next": "11.0.1",
    "react": "17.0.2",

**Comment by edbzn** [comment]
I'm also facing this after renaming a folder and running a build executor. I use `@nrwl/workspace@12.3.4` and here is the stack trace:

```
Error: ENOENT: no such file or directory, open '***/index.spec.ts'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.defaultFileRead (***/node_modules/@nrwl/workspace/src/core/file-utils.js:160:17)
    at TypeScriptImportLocator.fromFile (***/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/typescript-import-locator.js:22:38)
    at ***/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:11:27
    at Array.forEach (<anonymous>)
    at ***/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:10:44
    at Array.forEach (<anonymous>)
    at buildExplicitTypeScriptDependencies (***/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:9:30)
    at ***/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:72:41 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '***/index.spec.ts'
}
```

Running the command with `--skip-nx-cache` does not fix the issue as well as removing `node_modules/.cache/nx` cache folder.

**Comment by FrozenPandaz** [comment]
Hey all, I'm having trouble reproducing this issue.

1. This is happening when nx workspace is not the root of the git repo?

I have this repo: https://github.com/FrozenPandaz/nx-examples/tree/inner-workspace

It has `nx-workspace` as a directory within the repo as well as some other files and directories.

When I `cd nx-workspace` and `nx serve app1`, things work as expected.

Then, when I stop it and I `rm apps/app1/src/app/app.module.css` then `nx serve app1` it still works. :thinking: 

I believe those are the reproduction steps that you listed?

Could you please provide a repo that I can pull down and see the issue?

Also, some claim it happens even when Nx is in the root of the git repo?

Can this be reproduced on https://github.com/nrwl/nx-examples? If so, what are the steps for that repo?

**Comment by Lonli-Lokli** [comment]
It's really not alays happened. Moreover, I've searched for the file name in the content for all files (eslint cache was involved), deleted node_modules and file still was complaining.

Going further, I searched for the file in all disks - it was in browsers cache (I believe as it was somewhere in sourcemaps) and VSCode worspace. But even after deletion from all this places I still observe same error. It's gone with some time so as for me it's still somwhere cached, just dont know yet where.

**Comment by tsvetan-ganev** [comment]
@FrozenPandaz, I was able to reproduce the issue using your repo.

Steps (all commands are run from the `nx-workspace` folder):
1. Generate a new dummy component: `nx g component --name=TestComponent --export=false`
2. Run tests & lint: `nx test && nx lint`.
3. Stage the changes and commit. `git add . && git commit -m "Adds TestComponent"`
4. Rename the `app` component & fix the imports so that the project builds correctly:
```
renamed:    apps/app1/src/app/app.module.css -> apps/app1/src/app/app-1.module.css
renamed:    apps/app1/src/app/app.spec.tsx -> apps/app1/src/app/app-1.spec.tsx
renamed:    apps/app1/src/app/app.tsx -> apps/app1/src/app/app-1.tsx
```
5. Stage the changes: `git add .`
6. Run `nx test`:
```
(node:75939) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'git/nx-examples/nx-workspace/apps/app1/src/app/app.spec.tsx'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.defaultFileRead (git/nx-examples/nx-workspace/node_modules/@nrwl/workspace/src/core/file-utils.js:161:17)
    at TypeScriptImportLocator.fromFile (git/nx-examples/nx-workspace/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/typescript-import-locator.js:22:38)
    at git/nx-examples/nx-workspace/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:11:27
    at Array.forEach (<anonymous>)
    at git/nx-examples/nx-workspace/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:10:51
    at Array.forEach (<anonymous>)
    at Object.buildExplicitTypeScriptDependencies (git/nx-examples/nx-workspace/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:9:37)
    at buildProjectGraph (git/nx-examples/nx-workspace/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:103:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:75939) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:75939) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hudzenko** [comment]
Hey thanks for reopening this. I have created the first issue for this bug https://github.com/nrwl/nx/issues/3370 , which is closed now. But I retrieve email notifications from github that people still facing this almost each day.

Originally we have aborted using nx because of this annoying issue. Now in my new angular and nest.js proj I would like to try NX again, but I do not understand why this bug is ignored for so long time by Nx team.

i consider the tool/product really cool. But so not understand why such an annoying thing is not fixed for so long

**Comment by HonoluluHenk** [comment]
bumpity-bump because still b0rked

**Comment by khanyuriy** [comment]
unable to use lint and format in precommit hook, because of this annoying issue

**Comment by eyassud** [comment]
have the same issue with "@nrwl/workspace": "12.7.2"

**Comment by kevinolivar** [comment]
What else can we do in order to have this issue fixed or at least getting feedback from the NX people?
This issue seems just ignored lol.

**Comment by pavandv** [comment]
@FrozenPandaz @vsavkin Any update on this?? This error is really annoying, as it requires us to commit our changes even before testing them.

**Comment by flensrocker** [comment]
I got hit by this today and didn't know what to do. Removed node_modules & dist but error existed.
After reading this issue I just commited my changes and now I can build againg.

It would be nice, if this gets resolved some day. On a monorepo `nx` is nicer than pure `ng`.

Thank you!

**Comment by maxisam** [comment]
Same issue on v12.9.0

@pavandv you don't have to commit to get rid of this error. Just do `git stash` and `git stash pop`

**Comment by kevinolivar** [comment]
@maxisam a fix would be better than a work around.

**Comment by kevinolivar** [comment]
Here, another bug ticket for the same problem. Maybe one day, this issue will be fixed. Make NX great again!

https://github.com/nrwl/nx/issues/7177

**Comment by vmasek** [comment]
I don't think this one should be closed due to inactivity, it is pretty unexpected and annoying behaviour.

**Comment by BobDankert** [comment]
Definitely shouldn't be closed - I ran into this yesterday.

**Comment by flensrocker** [comment]
Just a friendly reminder, that this issue should not be closed.

Thank you!

**Comment by HonoluluHenk** [comment]
Le Bump

**Comment by maxisam** [comment]
@FrozenPandaz Could you remove the bot action for this issue? I don't mind it might take a long time to fix this issue. 

I can understand it is not the priority. 
However, it is just annoy to keep the bot away by making more useless comments, including this one.

**Comment by willpritchard** [comment]
Update for this issue here: https://github.com/nrwl/nx/issues/7177#issuecomment-1007399846

**Comment by tsvetan-ganev** [comment]
Bot, it's not stale.On Jan 22, 2022 02:12, "github-actions[bot]" ***@***.***> wrote:

This issue has been automatically marked as stale because it hasn't had any recent activity. It will be closed in 14 days if no further activity occurs.

If we missed this issue please reply to keep it active.

Thanks for being a part of the Nx community! 🙏

**Comment by maxisam** [comment]
![image](https://user-images.githubusercontent.com/456807/152667735-94c2760c-ed32-4e9e-9879-298c9065ca69.png)

Seriously, we are adding to global warming by making this kinda useless post

**Comment by TemitopeAgbaje** [comment]
A suggested fix is to remove the file in the workspace.json file

**Comment by hudzenko** [comment]
Happens for me with 13.8.1.
I moved file into another library.
And now nx linter does not want to catch this. It keeps thinking the file is in old location.
And even stash / commit does not help. Weird...

**Comment by maxisam** [comment]
not dead

**Comment by mikededo** [comment]
> not dead

In my case, I was getting the following error:

```shell
 FAIL  <file name>
  ● Test suite failed to run

    libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

      at Runtime._loadModule (../../node_modules/jest-runtime/build/index.js:1180:29)
      at Object.<anonymous> (../../node_modules/bcrypt/bcrypt.js:6:16)
```

Since it was related with a module, I removed `node_modules` and run `npm install`. It seems to have solved the issues. Probably you already have tried, but I have not found any other solution to it.

**Comment by flensrocker** [comment]
Unstale comment

**Comment by HonoluluHenk** [comment]
To all subscribers of this issue: there seems to be progress in #7177 which is another clone of the originating issue.

**Comment by abomadev** [comment]
For anyone still experiencing this issue, check the `workspace.json` file.  For me, there was a reference to the deleted folder in there. Removing the reference fixed it.

**Comment by evgeny-kirichuk** [comment]
I've just faced the issue while trying to build the app.
Stash -  stash pop doesn't help.
What are the options in such a case?
I just can't build the app anymore.

**Comment by flensrocker** [comment]
@evgeny-kirichuk 
Commit the changes. That works for me.

**Comment by jmsalcido** [comment]
just for the sake of helping someout if you are still having issues with this:

https://github.com/nrwl/nx/issues/3370#issuecomment-1261391072
