### ISSUE TITLE
Component generator fails after upgrade to nx 12

### ISSUE THREAD

**Issue by david-bulte** [nrwl/nx#6420]
Not sure wheter this is an angular or NX issue. But after upgrading to the latest version, we noticed the following:

When generating a component via the component schematic ("ng g component --project <my-project-name> <component-name>") , I get the following error:

```
Schematic input does not validate against the Schema: {"style":"scss","project":"shared-toolkit-ui-toggle","name":"toggle-list-option","inlineStyle":false,"inlineTemplate":false,"changeDetection":"Default","styleext":"css","spec":tr
ue,"skipTests":false,"flat":false,"skipImport":false,"skipSelector":false,"export":false,"entryComponent":false,"lintFix":false}
Errors:

  Data path undefined should NOT have additional properties(styleext).
```

Nowhere in the source code I can find back the "styleext" property.

### Failure Logs
InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"style":"scss","project":"shared-toolkit-ui-toggle","name":"toggle-list-option","inlineStyle":false,"inlineTemplate":false,"changeDetection":"Defaul
t","styleext":"css","spec":true,"skipTests":false,"flat":false,"skipImport":false,"skipSelector":false,"export":false,"entryComponent":false,"lintFix":false}
Errors:

  Data path undefined should NOT have additional properties(styleext).
    at MapSubscriber.project (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular-devkit\schematics\tools\schema-option-transform.js:30:27)
    at MapSubscriber._next (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:145:22)
    at Subscriber._next (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\rxjs\internal\Subscriber.js:143:22)
    at ThrowIfEmptySubscriber._next (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\rxjs\internal\operators\throwIfEmpty.js:44:26) {
  errors: [
    {
      keyword: 'additionalProperties',
      dataPath: '',
      schemaPath: '#/additionalProperties',
      params: [Object],
      message: 'should NOT have additional properties'
    }
  ]
}
Schematic input does not validate against the Schema: {"style":"scss","project":"shared-toolkit-ui-toggle","name":"toggle-list-option","inlineStyle":false,"inlineTemplate":false,"changeDetection":"Default","styleext":"css","spec":tr
ue,"skipTests":false,"flat":false,"skipImport":false,"skipSelector":false,"export":false,"entryComponent":false,"lintFix":false}
Errors:

  Data path undefined should NOT have additional properties(styleext).

### Environment
angular: ~12.1.2
nrwl nx: 12.5.8

**Comment by david-bulte** [comment]
I have the impression it has to do with akita and not with NX. Still, I am not sure how it works. Going to ask @ akita as well.

After removing akita, listing @schematics/angular looks like so:

![image](https://user-images.githubusercontent.com/4194465/126313979-021316c3-42b2-4a70-952d-ace88b6ab2c9.png)

node_modules does *not* contain an entry @schematics/angular:

![image](https://user-images.githubusercontent.com/4194465/126314025-f4698006-2cac-4dd4-874d-d8cfcf081ab9.png)

ng g component *does* work, nx generate @nrwl/angular:component not:

![image](https://user-images.githubusercontent.com/4194465/126314097-16fe95ad-a39c-4952-b88d-ac44a886c983.png)

After reinstalling akita, ng generate and nx generate do not work, both give the same error:

![image](https://user-images.githubusercontent.com/4194465/126314221-56550591-57cc-4ff1-a048-8de02ab358b6.png)

And npm list gives the following result:

![image](https://user-images.githubusercontent.com/4194465/126314584-4d0730c0-d537-4c02-86ce-e21701b88f7d.png)

Notice the old schematics version underneath akita.

node_modules *does* now contain the @schematics/angular package:

![image](https://user-images.githubusercontent.com/4194465/126314388-ffef4d57-fc9d-47e4-a059-0f4d19811da9.png)

*Its component/schema.json file is an old file, it contains old attributes like styleext, entrycomponent etc...*

So I assume now that somehow the akita schematics dependency precedes the NX dependency? But how come initially there is no @schematics/angular package in node_modules, that one is only there after installing akita?

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you please share a minimal reproduction of the issue to help us troubleshoot this?

As you mentioned above, `styleext` was deprecated and removed from the Angular CLI several versions ago. Also, Akita dependency shouldn't affect the Nx or Angular CLI one (they should both use the nested ones).

If your workspace has configured the Akita collection as the `defaultCollection`, then when you run `ng g component` or `ng g component` (notice no collection is specified) it would be using it from the Akita collection by default.

**Comment by david-bulte** [comment]
Unfortunately I cannot share the entire repo. Also, I don't manage to reproduce the issue in another repo :(

Here's some more info though.

From angular.json:

```
{
  "version": 1,
  "cli": {
    "warnings": {
      "typescriptMismatch": false,
      "versionMismatch": false
    },
    "defaultCollection": "@nrwl/angular",
    "packageManager": "npm",
    "analytics": "c31bc86d-0b84-4209-b726-0bcf09bc2bfc"
  },
  "schematics": {
    "@nrwl/angular": {
      "application": {
        "linter": "eslint"
      },
      "library": {
        "linter": "eslint"
      },
      "storybook-configuration": {
        "linter": "eslint"
      },
      "convert-tslint-to-eslint": {
        "removeTSLintIfNoMoreTSLintTargets": true
      }
    },
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "none"
    },
    "@nrwl/angular:library": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "strict": true
    },
    "@nrwl/angular:component": {
      "style": "scss"
    }
  },
```

I also noticed *some* (but not all) libs have the "component" schematic, e.g.

```
    "<lib-name>": {
      ...
      "schematics": {
        "@nrwl/angular:component": {
          "style": "scss"
        }
      }
    },
```

But so it is configured for the 'NX' schematics to be active.

So summarizing:

- akita has a dependency on an 'old' schematics library, NX has a dependency on the most recent one 
- when I try to reproduce the problem by creating a new project, the NX dependency *does* end up under @schematics/angular in node_modules. 
- But in the problematic repo, the 'old' one ends up in @schematics/angular (as can also be seen in the package-lock.json), even after removing all node_modules and removing the package.lock
- when running the schematic, the schematic under @schematics/angular is run, *not* the one that is embedded in the NX libs

**Comment by david-bulte** [comment]
Sorry I was on holiday. As a (temporary?) workaround we now explicitly import @schematics/angular": "12.1.3"

**Comment by allout58** [comment]
I ran into this issue when I accidentally forgot to upgrade `@schematics/angular` from v11 to v12
