### ISSUE TITLE
Cannot read property 'implementation' of undefined

### ISSUE THREAD

**Issue by ild0tt0re** [nrwl/nx#6441]
## Current Behavior
Error updating from Nx **12.5.8** to **12.6.0-beta.6** on
```$ nx migrate --run-migrations```

### Failure Logs
```
Running migration add-next-eslint-12.6.0
Cannot read property 'implementation' of undefined
/Users/angeloca/Projects/fe.monorepo/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/nx/kp68t8117w3_p64cqg7q7wzw0000gn/T/tmp-54202-FS1yuFE2rZzv/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:640:11)
    at Object.execSync (child_process.js:676:15)
    at Object.handler (/Users/angeloca/Projects/fe.monorepo/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:89:25)
    at Object.runCommand (/Users/angeloca/Projects/fe.monorepo/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/angeloca/Projects/fe.monorepo/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/angeloca/Projects/fe.monorepo/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/angeloca/Projects/fe.monorepo/node_modules/@nrwl/cli/lib/init-local.js:25:79)
    at Object.<anonymous> (/Users/angeloca/Projects/fe.monorepo/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (/Users/angeloca/Projects/fe.monorepo/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

### Environment
```
  Node : 14.17.0
  OS   : darwin x64
  yarn : 1.22.10

  nx : 12.3.5
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.0-beta.6
  @nrwl/cypress : 12.6.0-beta.6
  @nrwl/devkit : 12.6.0-beta.6
  @nrwl/eslint-plugin-nx : 12.6.0-beta.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.0-beta.6
  @nrwl/linter : 12.6.0-beta.6
  @nrwl/nest : Not Found
  @nrwl/next : 12.4.0
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.6.0-beta.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.0-beta.6
  @nrwl/web : 12.6.0-beta.6
  @nrwl/workspace : 12.6.0-beta.6
  @nrwl/storybook : 12.6.0-beta.6
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by kirjai** [comment]
thanks for reporting the issue!

Looking at your environment - looks like the version of `@nrwl/next` is not `12.6.0-beta.6`, but `12.4.0` instead. Could you try re-running the migrations after upgrading `@nrwl/next` to `12.6.0-beta.6` to see if it fixes it?

**Comment by ild0tt0re** [comment]
> thanks for reporting the issue!
> 
> Looking at your environment - looks like the version of `@nrwl/next` is not `12.6.0-beta.6`, but `12.4.0` instead. Could you try re-running the migrations after upgrading `@nrwl/next` to `12.6.0-beta.6` to see if it fixes it?

Manual installation fix the issue.
Thanks!

**Comment by jaqua** [comment]
@ild0tt0re How did you do the manual installation. I'm facing the same problem.
