### ISSUE TITLE
nx migrate latest exits with error

### ISSUE THREAD

**Issue by trumbitta** [nrwl/nx#6467]
## Current Behavior

`nx migrate latest` fails

same thing with `nx migrate @nrwl/workspace@12.5.9`

same thing with `nx migrate @nrwl/workspace@12.6.0-rc.0`

It could be something wrong with 12.5.8... and now I can't migrate to the next version? 😨 

## Expected Behavior

Migration starts and ends successfully

## Steps to Reproduce

- have a 12.5.8 workspace
- launch `nx migrate latest`

### Failure Logs

```
❯ nx migrate latest
/Users/w.ghelfi/woah/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: npm install
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at taoPath (/Users/w.ghelfi/woah/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:324:21)
    at Object.handler (/Users/w.ghelfi/woah/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:88:19)
    at Object.runCommand (/Users/w.ghelfi/woah/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/w.ghelfi/woah/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/w.ghelfi/woah/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/w.ghelfi/woah/node_modules/@nrwl/cli/lib/init-local.js:25:79)
    at Object.<anonymous> (/Users/w.ghelfi/woah/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 34528,
  stdout: null,
  stderr: null
}
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 12.18.3
  OS   : darwin x64
  npm  : 6.14.6
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.8
  @nrwl/cypress : 12.5.8
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.8
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.8
  @nrwl/linter : 12.5.8
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.5.8
  @nrwl/nx-cloud : 12.2.7
  @nrwl/react : 12.5.8
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.8
  @nrwl/web : 12.5.8
  @nrwl/workspace : 12.5.8
  @nrwl/storybook : 12.5.8
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I can't reproduce it using the provided information. Could you please share a minimal repo where the issue can be reproduced?

**Comment by trumbitta** [comment]
@leosvelperez thanks! You taking the time to reproduce this, and not being able to, led me to retry and... it worked!

It didn't the last 5 times I tried yesterday, but it just did. So I guess it must've been some hiccup somewhere on the road between my machine and the NPM registry.

✌️
