### ISSUE TITLE
Building React app with Webpack 5 does not work with when loading external scripts

### ISSUE THREAD

**Issue by ashwinGokhale** [nrwl/nx#6483]
## Current Behavior
Nx fails to build a React app with Webpack 5 that has the `scripts` property defined in `workspace.json` or `angular.json`.

## Expected Behavior
Nx should be able to build a React app with Webpack 5

## Steps to Reproduce
1. Clone the [nx-examples repo](https://github.com/nrwl/nx-examples)
2. Run `yarn`
3. Run `yarn nx g @nrwl/web:webpack5` to migrate to Webpack 5
4. Add this line to `apps/cart/project.json` at the path: `targets.build.options.scripts`
    4.1. `"scripts": ["node_modules/regenerator-runtime/runtime.js"],`
5. Try to serve the cart app: `yarn nx serve cart`

### Failure Logs
```
> nx run cart:serve

>  NX  Using webpack 5. Reason: detected version 5 in node_modules/webpack/package.json


>  NX  Web Development Server is listening at http://localhost:4200/

(node:17224) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_PUSH] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'push' is deprecated)
    at Set.set.push (C:\Users\USER\source\REPO\node_modules\webpack\lib\util\deprecation.js:108:3)
    at ScriptsWebpackPlugin._insertOutput (C:\Users\USER\source\REPO\node_modules\@nrwl\web\src\utils\third-party\cli-files\plugins\scripts-webpack-plugin.js:62:28)
    at C:\Users\USER\source\REPO\node_modules\@nrwl\web\src\utils\third-party\cli-files\plugins\scripts-webpack-plugin.js:117:22
(node:17224) UnhandledPromiseRejectionWarning: TypeError: chunk.auxiliaryFiles is not iterable
    at C:\Users\USER\source\REPO\node_modules\webpack\lib\SourceMapDevToolPlugin.js:189:32
    at fn (C:\Users\USER\source\REPO\node_modules\webpack\lib\Compilation.js:481:9)
    at _next2 (eval at create (C:\Users\USER\source\REPO\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (C:\Users\USER\source\REPO\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:17224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)  
```

### Environment
```
  Node : 14.16.1
  OS   : win32 x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : 12.6.0
  @nrwl/cli : 12.6.0
  @nrwl/cypress : 12.6.0
  @nrwl/devkit : 12.6.0
  @nrwl/eslint-plugin-nx : 12.6.0
  @nrwl/express : 12.6.0
  @nrwl/jest : 12.6.0
  @nrwl/linter : 12.6.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.6.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.6.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.0
  @nrwl/web : 12.6.0
  @nrwl/workspace : 12.6.0
  @nrwl/storybook : 12.6.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by kazamov** [comment]
I have the same issue, but with Webpack 4 and when try to build an application in production mode.

**Comment by CaffeinatedCodeMonkey** [comment]
I, too, am experiencing this issue. Has anyone come up with a solution?

**Comment by writam-roy** [comment]
I am getting the same issue with react apps and webpack 5,when trying to load external scripts from workspace.json, this is a blocker issue for my development work, can anyone kindly look into it?

**Comment by jogelin** [comment]
The same issue for me, I get this error on generated `@nrwl/web` application after adding `scripts` in the `project.json`:

![image](https://user-images.githubusercontent.com/954509/135241899-f7e81227-942a-4bb1-a225-f945c6f89fb4.png)

![image](https://user-images.githubusercontent.com/954509/135242002-da51651c-9c6d-42e7-aaf0-bfde549c31b8.png)
