### ISSUE TITLE
TypeError occuring during run command execution

### ISSUE THREAD

**Issue by shertu** [nrwl/nx#6500]
## Current Behavior
When I execute a `run` command I get the following error:

![image](https://user-images.githubusercontent.com/7973587/126858491-0dbe3388-df18-428f-bf42-8a69174652bf.png)

## Expected Behavior
The expected behaviour is for the CLI to run the NPM script inside of the lib or app. 

This is a regression as previously on version `12.5.8` this issue did not occur.

## Steps to Reproduce
[This](https://github.com/shertu/zukte) is my code repository.

### Failure Logs
```
> nx run api-client:build

D:\shertu\zukte\node_modules\.pnpm\typescript@4.3.5\node_modules\typescript\lib\typescript.js:39486
            if (!host.fileExists(extendedConfigPath) && !ts.endsWith(extendedConfigPath, ".json" /* Json */)) {
                      ^

TypeError: host.fileExists is not a function
    at getExtendsConfigPath (D:\shertu\zukte\node_modules\.pnpm\typescript@4.3.5\node_modules\typescript\lib\typescript.js:39486:23)
    at parseOwnConfigOfJson (D:\shertu\zukte\node_modules\.pnpm\typescript@4.3.5\node_modules\typescript\lib\typescript.js:39418:38)
    at parseConfig (D:\shertu\zukte\node_modules\.pnpm\typescript@4.3.5\node_modules\typescript\lib\typescript.js:39364:13)
    at parseJsonConfigFileContentWorker (D:\shertu\zukte\node_modules\.pnpm\typescript@4.3.5\node_modules\typescript\lib\typescript.js:39185:28)
    at Object.parseJsonConfigFileContent (D:\shertu\zukte\node_modules\.pnpm\typescript@4.3.5\node_modules\typescript\lib\typescript.js:39141:16)
    at readTsConfigOptions (D:\shertu\zukte\node_modules\.pnpm\@nrwl+workspace@12.6.2_prettier@2.3.2\node_modules\@nrwl\workspace\src\utilities\typescript.js:29:21)
    at getCompilerHost (D:\shertu\zukte\node_modules\.pnpm\@nrwl+workspace@12.6.2_prettier@2.3.2\node_modules\@nrwl\workspace\src\utilities\typescript.js:52:21)
    at Object.resolveModuleByImport (D:\shertu\zukte\node_modules\.pnpm\@nrwl+workspace@12.6.2_prettier@2.3.2\node_modules\@nrwl\workspace\src\utilities\typescript.js:40:36)
    at TargetProjectLocator.findProjectWithImport (D:\shertu\zukte\node_modules\.pnpm\@nrwl+workspace@12.6.2_prettier@2.3.2\node_modules\@nrwl\workspace\src\core\target-project-locator.js:55:43)
    at D:\shertu\zukte\node_modules\.pnpm\@nrwl+workspace@12.6.2_prettier@2.3.2\node_modules\@nrwl\workspace\src\core\project-graph\build-dependencies\explicit-project-dependencies.js:12:53
```

### Environment
```
  Node : 16.4.1
  OS   : win32 x64
  pnpm : 6.10.3

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.2
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.6.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.2
  @nrwl/linter : 12.6.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.2
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by kylecordes** [comment]
While awaiting a fix, I'm patching things back in to operation with a postinstall script:

~~~
const fs = require('fs');

const fileName =
  'node_modules/@nrwl/workspace/src/utilities/typescript.js';
let text = fs.readFileSync(fileName, 'utf-8');

text = text.replace(
  '{ readDirectory: () => [] }',
  '{ readDirectory: () => [], fileExists: () => true }'
);

fs.writeFileSync(fileName, text);
~~~

I **don't** recommend this... but it works.

**Comment by literalpie** [comment]
I think this has something to do with `"extends": "./node_modules/..."`. @shertu 's project has a config like this, and so does the project where I'm running into it. Removing the `extends` from my project fixes the issue.
I think there's more required to reproduce it though. When I made a new nx project with an `extends`, it doesn't cause the error.

**Comment by kylecordes** [comment]
This error reproduces for me in a fresh new project. All I did was create a new workspace then add two new empty Angular projects to it. No manual code edits of any time, and no `"extends": "./node_modules/...`.

I first saw the error in a large complex project; that project also has no `"extends": "./node_modules/...`.

Therefore, I think this construct is @shertu 's project is at least not the *only* trigger.

**Comment by shertu** [comment]
The issue still seems to be occurring?

**Comment by ianldgs** [comment]
> The issue still seems to be occurring?

Are you on 12.6.7+?

**Comment by shertu** [comment]
@ianldgs 12.7.2

![image](https://user-images.githubusercontent.com/7973587/129906538-2956b821-c273-420c-a305-143ca8313e7e.png)
