### ISSUE TITLE
Unable to successfully execute: nx migrate 

### ISSUE THREAD

**Issue by marckassay** [nrwl/nx#6509]
## Current Behavior
The expression `nx migrate` throws an exception.

## Expected Behavior
The expression `nx migrate` to (perhaps unconditionally) generate a migrations.json file and update packages if available.

## Steps to Reproduce
```shell
yarn create nx-workspace --name superorg --preset react --appName subapp --cli nx --style scss --packageManager yarn --nx-cloud false
cd superorg
yarn set version berry
yarn rebuild
yarn install
yarn nx migrate
```

Using npm, instead of yarn, yields the same exception listed below. I'm unsure if migrations.json file is generated when just an update is available at the time `migrate` is executed, hence my uncertainty in the Expected Behavior section. 

As a workaround, I created a new nx workspace using the latest, copy-and-pasted dependencies listed in package.json to my existing workspace. And then in my existing workspace, deleted lock file, node_modules and finally executed `npm install`.

```shell
~\source\repos\superorg [master]> npm run nx migrate

> superorg@0.0.0 nx C:\Users\Mkassay\source\repos\superorg
> nx "migrate"

Provide the correct package name and version. E.g., @nrwl/workspace@9.0.0.
C:\Users\Mkassay\source\repos\superorg\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\Mkassay\AppData\Local\Temp\tmp-10768-iSfK3Ak7L5I4\node_modules\.bin\tao migrate
    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at Object.handler (C:\Users\Mkassay\source\repos\superorg\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:89:25)
    at Object.runCommand (C:\Users\Mkassay\source\repos\superorg\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Users\Mkassay\source\repos\superorg\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\Users\Mkassay\source\repos\superorg\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\Users\Mkassay\source\repos\superorg\node_modules\@nrwl\cli\lib\init-local.js:25:79)
    at Object.<anonymous> (C:\Users\Mkassay\source\repos\superorg\node_modules\@nrwl\cli\bin\nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 96,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superorg@0.0.0 nx: `nx "migrate"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the superorg@0.0.0 nx script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Environment
```shell
  Node : 14.17.3
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.2
  @nrwl/cypress : 12.6.2
  @nrwl/devkit : 12.6.2
  @nrwl/eslint-plugin-nx : 12.6.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.2
  @nrwl/linter : 12.6.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.6.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.2
  @nrwl/web : 12.6.2
  @nrwl/workspace : 12.6.2
  @nrwl/storybook : 12.6.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by marckassay** [comment]
I attempted again in the workspace created with npm appending 'latest' to the end of expression and it seems to have ran successfully, just nothing to update. 

```shell
~\source\repos\superorg [master]> npm run nx migrate latest
```

```
>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.
```

But I attempted the same in my yarn workspace, but yielded the same exception from my opening post.

**Comment by FrozenPandaz** [comment]
Could you try using `yarn` v1 please? Nx does not yet support yarn v2.

**Comment by marckassay** [comment]
Same results:
```shell
~\source\repos\superorg [master]> yarn nx migrate
yarn run v1.22.10
$ nx migrate
Provide the correct package name and version. E.g., @nrwl/workspace@9.0.0.
C:\Users\Mkassay\source\repos\superorg\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\Mkassay\AppData\Local\Temp\tmp-15556-L8X9AO6Ltfzn\node_modules\.bin\tao migrate
    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at Object.handler (C:\Users\Mkassay\source\repos\superorg\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:89:25)
    at Object.runCommand (C:\Users\Mkassay\source\repos\superorg\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Users\Mkassay\source\repos\superorg\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\Users\Mkassay\source\repos\superorg\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\Users\Mkassay\source\repos\superorg\node_modules\@nrwl\cli\lib\init-local.js:25:79)
    at Object.<anonymous> (C:\Users\Mkassay\source\repos\superorg\node_modules\@nrwl\cli\bin\nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10044,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~\source\repos\superorg [master]>
```

Fyi, I used yarn v2 in my previous post with Plug'n'Play disabled; `nodeLinker: node-modules` set in .yarnrc.yml, which I was guided by these [instructions](https://yarnpkg.com/getting-started/migration#why-should-you-migrate).

**Comment by marckassay** [comment]
But appending `latest` works:
```shell
~\source\repos\superorg [master]> yarn nx migrate latest
yarn run v1.22.10
$ nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @nrwl/workspace@12.6.3

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'yarn'
- To learn more go to https://nx.dev/latest/core-concepts/updating-nx
- You may run "nx connect-to-nx-cloud" to get faster builds, Github integration, and more. Check out https://nx.app
Done in 69.37s.
```

**Comment by marckassay** [comment]
And also, using yarn v2 and executing, `yarn nx migrate latest` does indeed fail. This was mentioned in issue [#2386](https://github.com/nrwl/nx/issues/2386#issuecomment-830728384). Perhaps [react migrate doc](https://nx.dev/latest/react/cli/migrate) can explicitly state that this parameter is required.

**Comment by benpsnyder** [comment]
@marckassay check out [feat(core): implement Yarn v3](https://github.com/nrwl/nx/pull/7918)

**Comment by HackPoint** [comment]
> And also, using yarn v2 and executing, `yarn nx migrate latest` does indeed fail. This was mentioned in issue [#2386](https://github.com/nrwl/nx/issues/2386#issuecomment-830728384). Perhaps [react migrate doc](https://nx.dev/latest/react/cli/migrate) can explicitly state that this parameter is required.

That's worked for me but I was using pnpm.

`pnpm nx migrate latest'
