### ISSUE TITLE
Error Upgrading from 9.4.5 to 10.4.13: Running migration update-10.0.0 Unable to determine format for workspace path.

### ISSUE THREAD

**Issue by cnd5041** [nrwl/nx#6551]
## Current Behavior
```
npx @nrwl/tao@latest migrate 10.4.12
<!-- Only  changes package.json to "@nrwl/workspace": "10.4.12" -->
<!-- COMMIT -->
npm install
nx migrate 10.4.13
<!-- COMMIT -->
npm install
<!-- Deleted update-10-2-0 from migrations due to missing migration (https://github.com/nrwl/nx/issues/4526) -->
<!-- COMMIT -->
nx migrate --run-migrations=migrations.json
<!-- This changed  @angular-devkit/build-angular from "0.901.9" to "0.1000.0", -->
```
Observe Error: 
```
Running migration update-10.0.0
Unable to determine format for workspace path.
c:\Code\web-ui\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: \AppData\Local\Temp\tmp-23332ujm6sszJePh7\node_modules\.bin\tao migrate --run-migrations=migrations.json
```
Here is the package diff when I went to 10.4.13: https://imgur.com/a/Xhxjls6

## Expected Behavior
No errors, then to infinity and beyond (or at least v11). 

## Steps to Reproduce
* Start at version 9.4.5
* Follow the above steps
* Sorry, this is a private repo that can't be shared. 

### Failure Logs
```
Successfully finished update-10-0-0
---------------------------------------------------------
Running migration update-10-3-0
Successfully finished update-10-3-0
---------------------------------------------------------
Running migration update-10-4-0
Successfully finished update-10-4-0
---------------------------------------------------------
Running migration update-10.0.0
Unable to determine format for workspace path.
c:\Code\web-ui\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\redacted\AppData\Local\Temp\tmp-23332ujm6sszJePh7\node_modules\.bin\tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at Object.handler (c:\Code\web-ui\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:78:25)
    at Object.runCommand (c:\Code\web-ui\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (c:\Code\web-ui\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (c:\Code\web-ui\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (c:\Code\web-ui\node_modules\@nrwl\cli\lib\init-local.js:24:13)
    at Object.<anonymous> (c:\Code\web-ui\node_modules\@nrwl\cli\bin\nx.js:40:18)
    at Module._compile (C:\.npm-global\node_modules\@nrwl\cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 28064,
  stdout: null,
  stderr: null
}
```

### Environment
* Windows 10
* Node v10.17.3
* NPM: 6.14.13
* NRWL: Start at version 9.4.5
* See package.json diff: https://imgur.com/a/Xhxjls6

```
nx : Not Found
  @nrwl/angular : 10.4.13
  @nrwl/cli : 10.4.13
  @nrwl/cypress : 10.4.13
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.13
  @nrwl/linter : 10.4.13
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.13
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.13
  typescript : 3.9.7
```

## Migrations File: 
```
{
  "migrations": [
    {
      "version": "10.0.0-beta.1",
      "description": "Upgrades Angular and Angular CLI to 10.0.0",
      "factory": "./src/migrations/update-10-0-0/update-10-0-0",
      "package": "@nrwl/angular",
      "name": "update-10-0-0"
    },
    {
      "version": "10.3.0-beta.1",
      "description": "Add tsconfig.editor.json to angular apps and update jest-angular-preset",
      "factory": "./src/migrations/update-10-3-0/update-10-3-0",
      "package": "@nrwl/angular",
      "name": "update-10-3-0"
    },
    {
      "version": "10.4.0-beta.3",
      "description": "Adjust karma and protractor setup",
      "factory": "./src/migrations/update-10-4-0/update-10-4-0",
      "package": "@nrwl/angular",
      "name": "update-10-4-0"
    },
    {
      "version": "10.0.0-beta.2",
      "description": "update jest configs to include setup env files",
      "factory": "./src/migrations/update-10-0-0/update-jest-configs",
      "package": "@nrwl/jest",
      "name": "update-10.0.0"
    },
    {
      "version": "10.1.0-beta.4",
      "description": "Update jest to v26",
      "factory": "./src/migrations/update-10-1-0/update-10-1-0",
      "package": "@nrwl/jest",
      "name": "update-10.1.0"
    },
    {
      "version": "10.2.0",
      "description": "Remove deprecated jest builder options",
      "factory": "./src/migrations/update-10-2-0/update-10-2-0",
      "package": "@nrwl/jest",
      "name": "update-10.2.0"
    },
    {
      "version": "10.3.0-beta.1",
      "description": "Adds all jest projects into the root jest config",
      "factory": "./src/migrations/update-10-3-0/update-projects-property",
      "package": "@nrwl/jest",
      "name": "update-projects-property"
    },
    {
      "version": "10.3.1-beta.1",
      "description": "Fix ts-jest migration",
      "factory": "./src/migrations/update-10-3-0/update-ts-jest",
      "package": "@nrwl/jest",
      "name": "update-ts-jest"
    },
    {
      "version": "10.3.0-beta.1",
      "description": "Adds a jest extension to the recommended extensions for vscode",
      "factory": "./src/migrations/update-10-3-0/add-jest-extension",
      "package": "@nrwl/jest",
      "name": "add-jest-extension"
    }
  ]
}
```

**Comment by cnd5041** [comment]
Does this have to do with the `nx : Not Found` in the report?

FWIW, I can't upgrade from a fresh 9.4.5 to 10.4.13. 

Steps: 
* `npx create-nx-workspace@9.4.5 --preset=angular`
* nx migrate 10.4.13
* npm install
* nx migrate --run-migrations=migrations.json
Output: 
```
Updating @angular/core to 10.0.0

>  NX   ERROR  "ng update" is deprecated in favor of "nx migrate". Read more: https://nx.dev/latest/angular/workspace/update


>  NX   ERROR  "ng update" is deprecated in favor of "nx migrate". Read more: https://nx.dev/latest/angular/workspace/update

Unknown error: Error
@angular/core migration failed, see above.
C:\Code\testniner\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\redacted-\AppData\Local\Temp\tmp-242047cjUWS4KAZxt\node_modules\.bin\tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at Object.handler (C:\Code\testniner\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:78:25)
    at Object.runCommand (C:\Code\testniner\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Code\testniner\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\Code\testniner\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\Code\testniner\node_modules\@nrwl\cli\lib\init-local.js:24:13)
    at Object.<anonymous> (C:\Code\testniner\node_modules\@nrwl\cli\bin\nx.js:40:18)
    at Module._compile (C:\.npm-global\node_modules\@nrwl\cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9504,
  stdout: null,
  stderr: null
}
```

**Comment by FrozenPandaz** [comment]
Sorry about the issues you are having.

I was able to successfully go from `9.4.5` to `10.4.13` by doing the following steps:

1. `npx @nrwl/tao@latest migrate 10.4.12`
2. Remove the following item from `migrations.json`, this is handled by `nx migrate`
```
{
      "version": "10.0.0-beta.1",
      "description": "Upgrades Angular and Angular CLI to 10.0.0",
      "factory": "./src/migrations/update-10-0-0/update-10-0-0",
      "package": "@nrwl/angular",
      "name": "update-10-0-0"
    },
```

3. I wouldn't normally recommend this but this resolves your issue... `npx @nrwl/tao@10.4.13 migrate --run-migrations migrations.json`.

Running the migrations with an older version of Nx in this case works in your favor because the version that you have installed is not compatible with the latest version of Nx.

I hope that resolves your issue.

**Comment by cnd5041** [comment]
@FrozenPandaz that seems to work if I run `npx @nrwl/tao@10.4.13 migrate --run-migrations migrations.json` on the migrations file generated from `nx migrate 10.4.13`. This differs a bit from your steps, but also when I run the 10.4.12 migrations, it only updates the `@nrwl/workspace` version (it doesn't generate any migrations). It's not until 10.4.13 that I get migrations generated. 

Fingers crossed that once this is resolved, I can move past 10.4.12 without issues.

**Comment by cnd5041** [comment]
`npx @nrwl/tao@10.4.13 migrate --run-migrations migrations.json` worked.

**Comment by gtayloraamc** [comment]
I was running into this and not sure why but even `npx @nrwl/tao@10.4.13 migrate --run-migrations=migrations.json` was still somehow using the latest version of tao. I installed @nrwl/tao 10.4.13  as a devdependency and ran this which worked. `npx tao migrate --run-migrations=migrations.json`
