### ISSUE TITLE
Angular + mfe: `nx serve` fails to generate bundles showing UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by max-che** [nrwl/nx#6579]
## Current Behavior
`nx serve` fails to run local dev server and hanging forever on `Generating browser application bundles (phase: sealing)...`

## Expected Behavior
`nx serve` actually serves the application at localhost.
It is reproduceable out of the box on fresh installation of NX.

## Steps to Reproduce
Minimal Github repo: [nx-serve-error](https://github.com/max-che/nx-serve-error/commits/main)

**Steps to reproduce:**

`npx create-nx-workspace@latest`
```
√ Workspace name (e.g., org name)     · widgets
√ What to create in the new workspace · angular
√ Application name                    · test
√ Default stylesheet format           · scss
√ Use Nx Cloud? (It's free and doesn't require registration.) · No
```
`cd widgets/`
`npm i -D webpack`
`nx g @nrwl/angular:setup-mfe test`
`cd apps/test/`
`nx serve`

### Failure Logs
```
$ nx serve

> nx run test:serve:development 
⠇ Generating browser application bundles (phase: sealing)...(node:1580) UnhandledPromiseRejectionWarning: TypeError: this._source.node is not a function
    at PrefixSource.node (C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\PrefixSource.js:49:29)
    at C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\ConcatSource.js:105:54
    at Array.map (<anonymous>)
    at ConcatSource.node (C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\ConcatSource.js:104:19)
    at PrefixSource.node (C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\PrefixSource.js:49:29)
    at C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\ConcatSource.js:105:54
    at Array.map (<anonymous>)
    at ConcatSource.node (C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\ConcatSource.js:104:19)
    at exports.getSourceAndMap (C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\helpers.js:20:27)
    at ConcatSource.sourceAndMap (C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\ConcatSource.js:95:10)
    at CachedSource.sourceAndMap (C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\CachedSource.js:211:41)
    at getTaskForFile (C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\SourceMapDevToolPlugin.js:84:30)
    at C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\SourceMapDevToolPlugin.js:272:22
    at C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Cache.js:91:34
    at Array.<anonymous> (C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\cache\MemoryWithGcCachePlugin.js:116:13)
    at C:\workspace\nx-serve-error\widgets\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Cache.js:91:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise
 rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠇ Generating browser application bundles (phase: sealing)...

```

### Environment
```
  Node : 14.17.4
  OS   : win32 x64
  npm  : 6.14.14

  nx : Not Found
  @nrwl/angular : 12.6.3
  @nrwl/cli : 12.6.3
  @nrwl/cypress : 12.6.3
  @nrwl/devkit : 12.6.3
  @nrwl/eslint-plugin-nx : 12.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.3
  @nrwl/linter : 12.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.3
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.3
  @nrwl/storybook : 12.6.3
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by max-che** [comment]
UPD: `nx run test:serve:production` successfully running. It turns out that enabling **source map generation** gives above failing result. Think this might give us a clue.

**Comment by Coly010** [comment]
Hi!

I've tried to reproduce this with Nx 12.7.1 and cannot.
Could you try it again with the latest version of Nx and see if it still occurs?

Thank you!

**Comment by gerardcastell** [comment]
Hi there!
I stumbled upon the same problem. This time, I tried to create the workspace with the latest Nx version 12.7.2 , (npm v6.14.12, node 12.22.1O and Angular/CLI 12.1.3) and following the steps described by @max-che  and it didn't work as well. I strongly think that the problem is related with this feature: https://github.com/nrwl/nx/issues/6756. The problem is that while Angular 12 is including Webpack 5, @nrwl/cypress  is using Webpack v4 and there is some kind of mislead right there.

----
Temporally workaround: Yarn allows to add 
` "resolutions": {
    "webpack": "^5.0.0"
  },`
 in the package.json. If you run then yarn to install all the node modules and afterwards serve the app it is working for me.
 If you need a repository reproducing the problem or even the solution with yarn just tell me.
 I think that the key is on the Cypress dependency but @Coly010 take a glance when you can. Thank you in adavance!

**Comment by Coly010** [comment]
@gerardcastell Yep so after investigating this, this is the outcome I've seen:

Potential breaking change in a minor update to webpack to be aware about:
webpack@5.45.1 uses webpack-sources@2.3.1  and it parses sourcemaps in angular apps with no problem
webpack@5.50.0 uses webpack-sources@3.2.0 and it fails to parse angular sourcemaps correctly. It falls over itself with the error above.
at least in the context of MFEs

So I have a PR up now to set a fixed version: https://github.com/nrwl/nx/pull/6789

**Comment by khanyuriy** [comment]
i still have this issue on webpack@5.53.0

 Generating browser application bundles (phase: sealing)...(node:22580) UnhandledPromiseRejectionWarning: TypeError: this._source.node is not a function
    at PrefixSource.node (c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\PrefixSource.js:49:29)
    at c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\ConcatSource.js:105:54
    at Array.map (<anonymous>)
    at ConcatSource.node (c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\ConcatSource.js:104:19)
    at PrefixSource.node (c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\PrefixSource.js:49:29)
    at c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\ConcatSource.js:105:54
    at Array.map (<anonymous>)
    at ConcatSource.node (c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\ConcatSource.js:104:19)
    at exports.getSourceAndMap (c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\helpers.js:20:27)
    at ConcatSource.sourceAndMap (c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\ConcatSource.js:95:10)
    at CachedSource.sourceAndMap (c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack-sources\lib\CachedSource.js:211:41)
    at getTaskForFile (c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\SourceMapDevToolPlugin.js:84:30)
    at c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\SourceMapDevToolPlugin.js:272:22
    at c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Cache.js:91:34
    at Array.<anonymous> (c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\cache\MemoryWithGcCachePlugin.js:116:13)
    at c:\code\yaklass\frontend\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Cache.js:91:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
\ Generating browser application bundles (phase: sealing)...

**Comment by khanyuriy** [comment]
stil have this issue on webpack@5.53.0
