### ISSUE TITLE
The schematic can only be used with Angular CLI workspaces with a single application.

### ISSUE THREAD

**Issue by Drovosek01** [nrwl/nx#6692]
I have a small project that I generated using nx with the "empty" preset, and then I added angular to this project using npm.

Then I had to make sure that when generating the application's angular inside the workspace, a cypress template for tests was generated next to it, as it happens in a workspace created using nx with the "angular"preset.

I decided to convert the current workspace with the "empty" preset to angular workspace using the command I found here:
`npx make-angular-cli-faster`

https://nx.dev/latest/angular/getting-started/nx-setup

But this led to an error.

### Failure Logs
```
npx make-angular-cli-faster
npx: установлен 240 в 21.429s

>  NX  Nx initialization

Error: The schematic can only be used with Angular CLI workspaces with a single application.
    at createNxJson (G:\Egor\Documents\my-test-project\node_modules\@nrwl\workspace\src\generators\init\init.js:399:15)
    at G:\Egor\Documents\my-test-project\node_modules\@nrwl\workspace\src\generators\init\init.js:486:13
    at Generator.next (<anonymous>)
    at G:\Egor\Documents\my-test-project\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (G:\Egor\Documents\my-test-project\node_modules\tslib\tslib.js:113:16)
    at initGenerator (G:\Egor\Documents\my-test-project\node_modules\@nrwl\workspace\src\generators\init\init.js:483:20)
    at G:\Egor\Documents\my-test-project\node_modules\@nrwl\workspace\node_modules\@nrwl\devkit\src\utils\invoke-nx-generator.js:51:30
    at Generator.next (<anonymous>)
    at G:\Egor\Documents\my-test-project\node_modules\tslib\tslib.js:117:75
The schematic can only be used with Angular CLI workspaces with a single application.
Error: Command failed: nx g @nrwl/workspace:ng-add --preserveAngularCLILayout
    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at C:\Users\Egor\AppData\Roaming\npm-cache\_npx\3444\node_modules\make-angular-cli-faster\make-angular-cli-faster.js:61:25
    at Generator.next (<anonymous>)
    at C:\Users\Egor\AppData\Roaming\npm-cache\_npx\3444\node_modules\make-angular-cli-faster\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Egor\AppData\Roaming\npm-cache\_npx\3444\node_modules\make-angular-cli-faster\node_modules\tslib\tslib.js:113:16)
    at main (C:\Users\Egor\AppData\Roaming\npm-cache\_npx\3444\node_modules\make-angular-cli-faster\make-angular-cli-faster.js:54:20)
    at Object.<anonymous> (C:\Users\Egor\AppData\Roaming\npm-cache\_npx\3444\node_modules\make-angular-cli-faster\make-angular-cli-faster.js:80:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9632,
  stdout: null,
  stderr: null
}
```

### Environment
Windows 10 21H1 x86_64 
Visual Studio Code 1.59
Windows CMD

**Comment by FrozenPandaz** [comment]
Sorry, the docs are a little confusing.

The docs state:
> If you have an existing Angular CLI project, you can gain the benefits of Nx's computation cache without modifying the file structure by running this command:

I will edit the docs so that the title of that section reads `Adding Nx to an Existing Angular CLI Project`
