### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by hmaidithamer** [nrwl/nx#6694]
After creating a new plugin to generate a lib based on specific architecture it's working fine with angular 12, but when I use with angular 11 I have this issue:

TypeError: Cannot convert undefined or null to object
    at F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@nrwl\angular\src\schematics\library\lib\update-project.js:81:17
    at F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@nrwl\workspace\src\utils\ast-utils.js:375:56
    at MergeMapSubscriber.project (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24)
    at MergeMapSubscriber._tryNext (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:67:27)
    at MergeMapSubscriber._next (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:30:22)
    at MergeMapOperator.call (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:37:23)
TypeError: Cannot convert undefined or null to object
    at F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@nrwl\angular\src\schematics\library\lib\update-project.js:81:17
    at F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@nrwl\workspace\src\utils\ast-utils.js:375:56
    at MergeMapSubscriber.project (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24)
    at MergeMapSubscriber._tryNext (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:67:27)
    at MergeMapSubscriber._next (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:30:22)
    at MergeMapOperator.call (F:\Users\thamer.hmaidi\Documents\NX-labs\px-architecture\px-starter-ws\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:37:23)
Cannot convert undefined or null to object

**Comment by FrozenPandaz** [comment]
Sorry, there's not enough information here for me to reproduce the issue.

Could you please provide a repo that exhibits the issue to help us reproduce this?

**Comment by hmaidithamer** [comment]
Thanks @FrozenPandaz  for your ansower,
I generated a new custom plugin using the cmd line npx create-nx-plugin my-org --pluginName my-plugin
i have a generator named generate-lib to generate a new library based on specific architecture.
it's working fine when i generate a new angular project using nax latest version , but when i try to use the custom generator with a angular 11 project, i get the 'Cannot convert undefined or null to object' issue.
below the source code
import {
  formatFiles,
  generateFiles,
  names,
  Tree,
} from '@nrwl/devkit';
import * as path from 'path';
import { GenerateDomainGeneratorSchema } from './schema';
import { wrapAngularDevkitSchematic } from '@nrwl/devkit/ngcli-adapter';
function addFiles(host: Tree, options: GenerateDomainGeneratorSchema) {
  const templateOptions = {
    ...options,
    ...names(options.domain),
    __filename: options.entity.toLocaleLowerCase(),
    name: options.entity.toLocaleLowerCase(),
    scope: options.domain,
    facadeName: names(options.entity).className,
    modelName: names(options.entity).className,
    template: '',
  };
  generateFiles(
    host,
    path.join(__dirname, 'files'),
    `libs/${options.domain}/domain/src/lib/`,
    templateOptions
  );
}
export default async function (
  host: Tree,
  options: GenerateDomainGeneratorSchema
) {
  const libGenerator = wrapAngularDevkitSchematic('@nrwl/angular', 'library');
  const ngrxGenerator = wrapAngularDevkitSchematic('@nrwl/angular', 'ngrx');
  const componentGenerator = wrapAngularDevkitSchematic(
    '@nrwl/angular',
    'component'
  );
  await libGenerator(host, {
    name: 'domain',
    directory: options.domain,
    tags: `domain:${options.domain}, type:domain`,
  }).catch((e) => {
    console.log(e);
    throw e;
  });
  await ngrxGenerator(host, {
    name: options.entity,
    module: `libs/${options.domain}/domain/src/lib/${options.domain}-domain.module.ts`,
    directory: '+state/' + options.entity,
    minimal: true,
    facade: false,
    syntax: 'creators',
  }).catch((e) => {
    console.log(e);
    throw e;
  });
  if (options.feature) {
    await libGenerator(host, {
      name: `feature-${options.domain}`,
      directory: options.domain,
      routing: true,
      lazy: true,
      tags: `domain:${options.domain}, type:feature`,
    }).catch((e) => {
      console.log(e);
      throw e;
    });
    await componentGenerator(host, {
      name: options.domain,
      style: 'scss',
      skipImport: true,
      project: `${options.domain}-feature-${options.domain}`,
      changeDetection: 'OnPush',
    });
  }
  if (options.api) {
    await libGenerator(host, {
      name: `api-${options.domain}`,
      directory: options.domain,
      tags: `domain:${options.domain}, type:api`,
    }).catch((e) => {
      console.log(e);
      throw e;
    });
  }
  if (options.utils) {
    await libGenerator(host, {
      name: `util-${options.domain}`,
      directory: options.domain,
      tags: `domain:${options.domain}, type:util`,
    }).catch((e) => {
      console.log(e);
      throw e;
    });
  }
  if (options.ui) {
    await libGenerator(host, {
      name: `ui-${options.domain}`,
      directory: options.domain,
      tags: `domain:${options.domain}, type:ui`,
    });
  }
  addFiles(host, options);
  await formatFiles(host);
}
