### ISSUE TITLE
React Storybook plugin doesn't work with `@storybook/addon-postcss` (Unknown word)

### ISSUE THREAD

**Issue by BorisZubchenko** [nrwl/nx#6720]
## Current Behavior
Adding `@storybook/addon-postcss` which is needed for the Tailwind integration fails the build.

## Expected Behavior
Providing `@storybook/addon-postcss` (as well as other addons) must not fail the build.

## Steps to Reproduce
[Adding the addon line](https://github.com/BorisZubchenko/bz/pull/12/files#diff-0fbe92e5d1ae97063068c2b5cd35a6d4ecbd2e4875ada419bc939a729af60708R16)

You can also check out the `storybook` branch from the [PR](https://github.com/BorisZubchenko/bz/pull/12). It's a new NX workspace with Tailwind and Storybook only.

### Failure Logs
<details>
  <summary>Logs</summary>

```
ℹ ｢wdm｣: Compiled successfully.
webpack built preview 5b4b7a815195dc69dc7a in 12150ms
✖ ｢wdm｣: Hash: 5b4b7a815195dc69dc7a
Version: webpack 4.46.0
Time: 12150ms
Built at: 08/13/2021 10:36:59 PM
                            Asset      Size        Chunks                          Chunk Names
               0.iframe.bundle.js   206 KiB             0  [emitted]               
           0.iframe.bundle.js.map   144 KiB             0  [emitted] [dev]         
               1.iframe.bundle.js   222 KiB             1  [emitted]               
           1.iframe.bundle.js.map   212 KiB             1  [emitted] [dev]         
               2.iframe.bundle.js  91.7 KiB             2  [emitted]               
           2.iframe.bundle.js.map  83.6 KiB             2  [emitted] [dev]         
               3.iframe.bundle.js   372 KiB             3  [emitted]        [big]  
           3.iframe.bundle.js.map   412 KiB             3  [emitted] [dev]         
               4.iframe.bundle.js  15.7 KiB             4  [emitted]               
           4.iframe.bundle.js.map  16.6 KiB             4  [emitted] [dev]         
                      iframe.html  4.45 KiB                [emitted]               
            main.iframe.bundle.js  28.3 KiB          main  [emitted]               main
        main.iframe.bundle.js.map  9.78 KiB          main  [emitted] [dev]         main
    runtime~main.iframe.bundle.js  36.3 KiB  runtime~main  [emitted]               runtime~main
runtime~main.iframe.bundle.js.map  37.6 KiB  runtime~main  [emitted] [dev]         runtime~main
    vendors~main.iframe.bundle.js  5.11 MiB  vendors~main  [emitted]        [big]  vendors~main
vendors~main.iframe.bundle.js.map  4.65 MiB  vendors~main  [emitted] [dev]         vendors~main
Entrypoint main [big] = runtime~main.iframe.bundle.js runtime~main.iframe.bundle.js.map vendors~main.iframe.bundle.js vendors~main.iframe.bundle.js.map main.iframe.bundle.js main.iframe.bundle.js.map
[0] multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./apps/client/.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./apps/client/.storybook/preview.js-generated-config-entry.js ./apps/client/.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=true 184 bytes {main} [built]
[./apps/client/.storybook/generated-stories-entry.js] 404 bytes {main} [built]
[./apps/client/.storybook/preview.js-generated-config-entry.js] 2.88 KiB {main} [built]
[./apps/client/.storybook/storybook-init-framework-entry.js] 26 bytes {main} [built]
[./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js] 2.77 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js] 2.77 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js] 2.78 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js] 2.78 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js] 2.77 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js] 2.77 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js] 2.77 KiB {vendors~main} [built]
[./node_modules/@storybook/core-client/dist/esm/globals/globals.js] 105 bytes {vendors~main} [built]
[./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js] 97 bytes {vendors~main} [built]
[./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js] 2.77 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=true] (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=true 7.68 KiB {vendors~main} [built]
    + 1194 hidden modules

ERROR in ./apps/client/src/components/button/button.module.css (./node_modules/css-loader/dist/cjs.js??ref--12-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js??ref--12-oneOf-0-2!./node_modules/@storybook/addon-postcss/node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ref--15-2!./apps/client/src/components/button/button.module.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) /home/boris/projects/me/bz/apps/client/src/components/button/button.module.css Unknown word

> 1 | var api = require("!../../../../../node_modules/@storybook/addon-postcss/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js");
    | ^
  2 |             var content = require("!!../../../../../node_modules/css-loader/dist/cjs.js!../../../../../node_modules/postcss-loader/dist/cjs.js??ref--15-2!./button.module.css");
  3 | 

 @ ./apps/client/src/components/button/button.module.css 1:14-398 20:4-31:5 23:25-409
 @ ./apps/client/src/components/button/button.tsx
 @ ./apps/client/src/components/button/button.stories.tsx
 @ ./apps/client/src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./apps/client/.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./apps/client/.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./apps/client/.storybook/preview.js-generated-config-entry.js ./apps/client/.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=true
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.22 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 1.97 KiB {HtmlWebpackPlugin_0} [built]
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) /home/boris/projects/me/bz/apps/client/src/components/button/button.module.css Unknown word

> 1 | var api = require("!../../../../../node_modules/@storybook/addon-postcss/node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js");
    | ^
  2 |             var content = require("!!../../../../../node_modules/css-loader/dist/cjs.js!../../../../../node_modules/postcss-loader/dist/cjs.js??ref--15-2!./button.module.css");
  3 | 

    at /home/boris/projects/me/bz/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/boris/projects/me/bz/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/boris/projects/me/bz/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/boris/projects/me/bz/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/boris/projects/me/bz/node_modules/postcss-loader/dist/index.js:102:7)


          Broken build, fix the error above.
          You may need to refresh the browser.
        

———————————————————————————————————————————————

>  NX   ERROR  Running target "client:storybook" failed

  Failed tasks:
  
  - client:storybook
  
  Hint: run the command with --verbose for more details.


>  NX   CLOUD  See run details at https://nx.app/runs/iZr7sGJ1LeV


Process finished with exit code 1

```
</details>

### Environment
<details>
  <summary>`nx report`</summary>
  
 ```
  Node : 14.17.3
  OS   : linux x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.7.1
  @nrwl/cypress : 12.7.1
  @nrwl/devkit : 12.7.1
  @nrwl/eslint-plugin-nx : 12.7.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.1
  @nrwl/linter : 12.7.1
  @nrwl/nest : Not Found
  @nrwl/next : 12.7.1
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : 12.7.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.1
  @nrwl/web : 12.7.1
  @nrwl/workspace : 12.7.1
  @nrwl/storybook : 12.7.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
 ```
</details>

**Comment by juristr** [comment]
@BorisZubchenko thanks for reporting this, I'll have a look. Can you try to setup your Storybook + Tailwind as described here? https://blog.nrwl.io/use-storybook-with-tailwind-in-an-nx-workspace-5ceb08edad71 (the link to the repository src is at the end of the blog post)

Using the `@nrwl/react/plugin/storybook` should not require the configuration of the postcss addon separately, as the `@nrwl/react` preset handles that already.

Let me know how that goes. I'll keep this open anyway to look into the conflict that arises from also having the Storybook postcss addon

**Comment by BorisZubchenko** [comment]
@juristr, so I followed your instructions and made Tailwind work with Storybook. But it still doesn't work with JIT, so [`bg-[#fe3]`](https://github.com/BorisZubchenko/bz/pull/12/commits/23ef051ba1b075ca1a8e87f864982cba06e444b5#diff-b28011f6f36cddc6db9c0904d2dc5164ec43aa7ef7cb802b457829208ab17736R9) doesn't work on the library level (although it works when the application is serving)

**Comment by juristr** [comment]
@BorisZubchenko interesting. I'll have a look at that.

When you run Storybook, did you run the command prefixed with `TAILWIND_MODE=watch nx storybook <your-lib-name>`? Does that work?

**Comment by BorisZubchenko** [comment]
Yes, I did. Still doesn't work.

**Comment by med-albert** [comment]
Got the same issue here.

**Comment by juristr** [comment]
@BorisZubchenko sorry, been super busy lately, so couldn't come back earlier. Let me recap. 

I just quickly gave a look at the PR you mentioned, and I think you're missing to properly reference the tailwind config in your postcss.config.js of the library. Changing it to this makes it work for me:

![Screenshot 2021-09-16 at 10 14 36](https://user-images.githubusercontent.com/542458/133576383-e3421dab-e4af-4b6a-af46-0a42d98f7cba.png)

Also, you mention you need the `@storybook/addon-postcss` for the Tailwind integration. That should not be required since the `@nrwl/react/plugins/storybook` preset already takes care of that.
May I ask why you still want to have the `@storybook/addon-postcss`?

**Regarding the JIT issue:** Let's continue that discussion on #6332 which you've opened previously.

**Comment by BorisZubchenko** [comment]
@juristr, now it works, thanks! Even with JIT when the `TAILWIND_MODE=watch` is enabled (although it's indeed #6332).

> May I ask why you still want to have the @storybook/addon-postcss?

I wanted to have `@storybook/addon-postcss` to overwrite some plugins, but since we can do it right within the lib's `postcss.config.js` (with `@nrwl/react/plugins/storybook`), it's now irrelevant.

So I think this issue can be closed and further discussion can indeed be moved to the #6332.

**Comment by juristr** [comment]
sounds good, thanks.
