### ISSUE TITLE
Next.js SSR pages are failing in production builds

### ISSUE THREAD

**Issue by aboqasem** [nrwl/nx#6736]
## Current Behavior

Building and starting a next.js project that has an SSR page with `nx build` is giving `Internal Server Error`, but not with `nx serve`.

## Expected Behavior

Not to fail or fail in both production and development at least.

## Steps to Reproduce

- Just create a workspace with a next.js project
- Add an SSR page
- Build and launch

Or:
```shell
git clone https://github.com/aboqasem/bug-reprod-nx-next-ssr.git
cd bug-reprod-nx-next-ssr
npm install
nx build ssr-bug
next start dist/apps/ssr-bug --port 4200
```
Then `open http://localhost:4200/ssr`

### Failure Logs

```
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (/Users/aboqasem/dev/miscellaneous/nextjs-bug-reprod/node_modules/react/cjs/react.production.min.js:18:327)
    at exports.useContext (/Users/aboqasem/dev/miscellaneous/nextjs-bug-reprod/node_modules/react/cjs/react.production.min.js:22:269)
    at Head (/Users/aboqasem/dev/miscellaneous/nextjs-bug-reprod/node_modules/next/dist/next-server/lib/head.js:16:66)
    at d (/Users/aboqasem/.nvm/versions/node/v14.16.0/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/Users/aboqasem/.nvm/versions/node/v14.16.0/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/Users/aboqasem/.nvm/versions/node/v14.16.0/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/Users/aboqasem/.nvm/versions/node/v14.16.0/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/Users/aboqasem/.nvm/versions/node/v14.16.0/lib/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/Users/aboqasem/.nvm/versions/node/v14.16.0/lib/node_modules/next/dist/server/render.js:626:31)
    at Function.getInitialProps (/Users/aboqasem/dev/miscellaneous/nextjs-bug-reprod/dist/apps/ssr-bug/.next/server/pages/_document.js:539:19)
```

Trying to deploy the [reprod](https://github.com/aboqasem/bug-reprod-nx-next-ssr) to vercel:
```
23:15:08.469 >  NX   SUCCESS  Running target "build" succeeded
23:15:08.469
23:15:08.469
23:15:08.485 Error: The file "/vercel/path0/dist/apps/ssr-bug/routes-manifest.json" couldn't be found. This is normally caused by a misconfiguration in your project.
23:15:08.485 Please check the following, and reach out to support if you cannot resolve the problem:
23:15:08.486 1. If present, be sure your `build` script in "package.json" calls `next build`.  2. Navigate to your project's settings in the Vercel dashboard, and verify that the "Build Command" is not overridden, or that it calls `next build`.  3. Navigate to your project's settings in the Vercel dashboard, and verify that the "Output Directory" is not overridden. Note that `next export` does **not** require you change this setting, even if you customize the `next export` output directory. Learn More: https://err.sh/vercel/vercel/now-next-routes-manifest
```

### Environment

```
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.7.1
  @nrwl/cypress : 12.7.1
  @nrwl/devkit : 12.7.1
  @nrwl/eslint-plugin-nx : 12.7.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.1
  @nrwl/linter : 12.7.1
  @nrwl/nest : Not Found
  @nrwl/next : 12.7.1
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.7.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.1
  @nrwl/web : 12.7.1
  @nrwl/workspace : 12.7.1
  @nrwl/storybook : 12.7.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by aboqasem** [comment]
The reproduction is actually working on vercel: https://bug-reprod-nx-next-ssr.vercel.app/ssr. The deployment issue is my mistake; forgot `.next` in the output directory.

I tried multiple things and the problem seems to be something with global next and react stuff.

Locally I added `"generatePackageJson": true` then had to `cd dist/apps/myapp; npm start`.
Otherwise if I run `next start` from the workspace root:
```
The module 'react' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react'
The module 'react-dom' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react-dom'
ready - started server on 0.0.0.0:4200, url: http://localhost:4200
(node:98453) UnhandledPromiseRejectionWarning: Error: Cannot find module 'react'
```

Is this what is supposed to happen?

**Comment by aboqasem** [comment]
Thank you @kirjai! Yes, it does!
