### ISSUE TITLE
NextJS build fails on Vercel, but not on GitHub/locally

### ISSUE THREAD

**Issue by westmark** [nrwl/nx#6748]
## Current Behavior
Building an NX-powered (12.7.1) NextJS (11.0.1) locally and on GitHub works as expected, but fails on Vercel

## Expected Behavior
Build should work on Vercel

## Steps to Reproduce
Presumably any NX/Next app should fail on Vercel, but I have not tried this.

### Failure Logs
```
14:26:07.443 | Unexpected error:
-- | --
14:26:07.445 | Error: Cannot copy '/vercel/path0' to a subdirectory of itself, '/vercel/path0/node_modules/.cache/nx/6bbfde49814775959f953879fed4648f04a597f7f81b83319ce44286eb4509b5/outputs'.
14:26:07.445 | at Object.checkPathsSync (/vercel/path0/node_modules/@nrwl/workspace/node_modules/fs-extra/lib/util/stat.js:54:11)
14:26:07.445 | at Object.copySync (/vercel/path0/node_modules/@nrwl/workspace/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
14:26:07.445 | at /vercel/path0/node_modules/@nrwl/workspace/src/tasks-runner/cache.js:74:32
14:26:07.446 | at Array.forEach (<anonymous>)
14:26:07.446 | at Cache.<anonymous> (/vercel/path0/node_modules/@nrwl/workspace/src/tasks-runner/cache.js:66:21)
14:26:07.446 | at Generator.next (<anonymous>)
14:26:07.446 | at /vercel/path0/node_modules/tslib/tslib.js:114:75
14:26:07.446 | at new Promise (<anonymous>)
14:26:07.446 | at Object.__awaiter (/vercel/path0/node_modules/tslib/tslib.js:110:16)
14:26:07.446 | at Cache.put (/vercel/path0/node_modules/@nrwl/workspace/src/tasks-runner/cache.js:57:24)
14:26:07.472 | error Command failed with exit code 1.
```

### Environment
```
  Node : 16.3.0
  OS   : darwin arm64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.7.1
  @nrwl/cypress : 12.7.1
  @nrwl/devkit : 12.7.1
  @nrwl/eslint-plugin-nx : 12.7.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.1
  @nrwl/linter : 12.7.1
  @nrwl/nest : Not Found
  @nrwl/next : 12.7.1
  @nrwl/node : 12.7.1
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.7.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.1
  @nrwl/web : 12.7.1
  @nrwl/workspace : 12.7.1
  @nrwl/storybook : 12.7.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by westmark** [comment]
Never mind. The configuration on https://nx.dev/latest/react/guides/deploy-nextjs-to-vercel seems to have changed since I setup the project. I seem to remember you were supposed to include `--outputPath=.` but removing that fixed the issue.
