### ISSUE TITLE
Error when building libraries on circleci

### ISSUE THREAD

**Issue by mattlewis92** [nrwl/nx#6770]
## Current Behavior

Building a large project with ~250 libraries on circleci fails with this error:

```
Error reading '/home/circleci/repo/node_modules/.cache/nx/nxdeps.json'. Continue the process without the cache.
Error: UnexpectedEndOfString in JSON at position 2744315
    at Object.parseJson (/home/circleci/repo/node_modules/@nrwl/tao/src/utils/json.js:31:15)
    at Object.readJsonFile (/home/circleci/repo/node_modules/@nrwl/tao/src/utils/fileutils.js:20:19)
    at Object.readCache (/home/circleci/repo/node_modules/@nrwl/workspace/src/core/nx-deps/nx-deps-cache.js:38:32)
    at Object.readCachedProjectGraph (/home/circleci/repo/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:24:47)
    at /home/circleci/repo/node_modules/@nrwl/angular/src/executors/package/package.impl.js:34:114
    at Generator.next (<anonymous>)
    at resume (/home/circleci/repo/node_modules/tslib/tslib.js:221:48)
    at /home/circleci/repo/node_modules/tslib/tslib.js:220:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (/home/circleci/repo/node_modules/tslib/tslib.js:220:67)
    at /home/circleci/repo/node_modules/@nrwl/tao/src/commands/run.js:92:35
    at Generator.next (<anonymous>)
    at /home/circleci/repo/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/circleci/repo/node_modules/tslib/tslib.js:113:16)
    at iteratorToProcessStatusCode (/home/circleci/repo/node_modules/@nrwl/tao/src/commands/run.js:78:20)
```

## Expected Behavior

The library compiles without issue

## Steps to Reproduce
Making a reproduction for this is unfortunately gonna be really tricky. I can only reproduce it in circleci (locally it works fine). Smaller apps that use ~120 libs from the project build ok, it's only bigger apps that use ~150+ libs that it seems to happen on. It's also inconsistent, sometimes it works ok but often it fails. I added a simple `console.log(input);` on what `@nrwl/tao/src/utils/json.js` is trying to parse and it looks like the cause of the issue is the json file is getting cut off:

```
~~~ I abbreviated above this as it's a massive output ~~~
          {
            "file": "libs/pulse/core/src/lib/people-group/search-members/search-members.pipe.ts",
            "hash": "549ad62eb6ae95f26cd4d78eb44fa86bb603e677",
            "ext": ".ts",
            "deps": [
              "npm:@angular/core",
              "core-model"
            ]
          },
          {
            "file": "libs/pulse/core/src/lib/store/live-view.action.ts",
            "hash": "3b471bbadc64b4334b6f5fde77f42542c84fbd35",
            "ext": ".ts",
            "deps": [
              "npm:@ngrx/store",
              "core-model"
            ]
          },
          {
            "file": "libs/pulse/core/src/lib/store/live-view.effect.ts",
            "hash": "114a2ea6baa6de33dfe3efb268ce793a14b57cc4",
            "ext": ".ts",
            "deps": [
              "npm:@angular/core",
              "npm:@ngrx/effects",
              "npm:@ngrx/store",
              "npm:rxjs",
              "core-model",
              "core-state"
            ]
          },
          {
            "file
Error reading '/home/circleci/repo/node_modules/.cache/nx/nxdeps.json'. Continue the process without the cache.
Error: UnexpectedEndOfString in JSON at position 2744315
    at Object.parseJson (/home/circleci/repo/node_modules/@nrwl/tao/src/utils/json.js:31:15)
    at Object.readJsonFile (/home/circleci/repo/node_modules/@nrwl/tao/src/utils/fileutils.js:20:19)
    at Object.readCache (/home/circleci/repo/node_modules/@nrwl/workspace/src/core/nx-deps/nx-deps-cache.js:38:32)
    at Object.readCachedProjectGraph (/home/circleci/repo/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:24:47)
    at /home/circleci/repo/node_modules/@nrwl/angular/src/executors/package/package.impl.js:34:114
    at Generator.next (<anonymous>)
    at resume (/home/circleci/repo/node_modules/tslib/tslib.js:221:48)
    at /home/circleci/repo/node_modules/tslib/tslib.js:220:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (/home/circleci/repo/node_modules/tslib/tslib.js:220:67)
    at /home/circleci/repo/node_modules/@nrwl/tao/src/commands/run.js:92:35
    at Generator.next (<anonymous>)
    at /home/circleci/repo/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/circleci/repo/node_modules/tslib/tslib.js:113:16)
    at iteratorToProcessStatusCode (/home/circleci/repo/node_modules/@nrwl/tao/src/commands/run.js:78:20)
```

### Failure Logs

See above

### Environment

```
  Node : 14.17.0
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.7.1
  @nrwl/cli : 12.7.1
  @nrwl/cypress : 12.7.1
  @nrwl/devkit : 12.7.1
  @nrwl/eslint-plugin-nx : 12.7.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.1
  @nrwl/linter : 12.7.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.7.1
  @nrwl/storybook : 12.7.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by mattlewis92** [comment]
> Hm could you provide what commands you are running in circleci?
> 
> Is it in parallel? Does it perhaps work without parallel? I know it might take a long time and isn't a solution but it might help us narrow down the cause of the issue.
> 
> Is there any information that might help us attempt to make a reproduction?

Sure! This is the command we're running: `nx build --parallel --maxParallel=7 --with-deps "--project" "public-sharing" "--base-href=/nx-test/public-sharing/"` (on an 8 cpu, 16gb RAM machine)

Switching off parallel does indeed get it to pass! 

> Is there any information that might help us attempt to make a reproduction?

Unfortunately not, it seems to be related to having a massive number of libs, it's only when you go past ~150 buildable libs that it starts to occur. Maybe adding more libs to https://github.com/nrwl/nx-incremental-large-repo and setting up circle could get it to reproduce? 🤔 

We managed to find a workaround by just forking the nx ng-packagr builder and going back to this:

```
    return from(createProjectGraphAsync()).pipe(
      switchMap((projGraph) => {
        const { target, dependencies } = calculateProjectDependencies(
          projGraph,
          context.workspaceRoot,
          context.target.project,
          context.target.target,
          context.target.configuration
        );
```

So it's not a massive priority to get it fixed, as we have a workable solution for now 😄
