### ISSUE TITLE
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

### ISSUE THREAD

**Issue by memee** [nrwl/nx#6918]
After migrating to the latest version 12.8.0-beta.0, I get an error when using `npm run start`, "You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser"

## Expected Behavior

SCSS files are compiled successfully

Yes, it's a regression

## Steps to Reproduce

1. Migrate nx from 10.3.1-beta.1 to 12.8.0-beta.0
2. Run `nx serve`

I found this: https://github.com/angular/angular-cli/issues/20812. But it didn't help me. There are no `*.scss` files in my assets. I think that if `nx` takes care of migrating angular there should be some mechanism to mitigate those issues.

Error happen for `@import` statements.

Please let me know if minimal reproduction repo is really needed here.

### Failure Logs

```
/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/apps/project/src/app/users/components/employees-list/employees-list.component.scss - Error: /Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/apps/project/src/app/users/components/employees-list/employees-list.component.scss from Css Minimizer 
/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/apps/project/src/app/users/components/employees-list/employees-list.component.scss:1:1: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser [/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/apps/project/src/app/users/components/employees-list/employees-list.component.scss:1,1]
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
    at Input.error (/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/postcss/lib/input.js:123:16)
    at Parser.unknownWord (/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/postcss/lib/parser.js:518:22)
    at Parser.other (/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/postcss/lib/parser.js:149:12)
    at Parser.parse (/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/postcss/lib/parser.js:59:16)
    at parse (/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/postcss/lib/parse.js:11:12)
    at new LazyResult (/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/postcss/lib/processor.js:36:12)
    at cssnanoMinify (/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/css-minimizer-webpack-plugin/dist/utils.js:58:61)
    at minify (/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/css-minimizer-webpack-plugin/dist/minify.js:15:32)
    at /Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/css-minimizer-webpack-plugin/dist/index.js:262:128
    at /Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/p-limit/index.js:23:31
    at run (/Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/p-limit/index.js:23:43)
    at /Users/macio/Projects/project-workspace/SMFM-443-create-drag-and-drop-functionality/node_modules/p-limit/index.js:45:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Environment

```
Node : 16.1.0
  OS   : darwin x64
  npm  : 7.11.2
  
  nx : Not Found
  @nrwl/angular : 12.8.0
  @nrwl/cli : 12.8.0
  @nrwl/cypress : 12.8.0
  @nrwl/devkit : 12.8.0
  @nrwl/eslint-plugin-nx : 12.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.8.0
  @nrwl/linter : 12.8.0
  @nrwl/nest : 12.8.0
  @nrwl/next : Not Found
  @nrwl/node : 12.8.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.8.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.8.0
  @nrwl/storybook : 12.8.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you provide a minimal repo where the issue can be reproduced?
