### ISSUE TITLE
Cannot read property 'implementation' of undefined

### ISSUE THREAD

**Issue by justinhandley** [nrwl/nx#6932]
## Current Behavior
Attempting to upgrade from nx 11.1.1 to 12.8.0 using nx migrate fails

## Expected Behavior
Migration works

## Steps to Reproduce
Upgrading using nx migrate latest from 11.1.1 to 12.8.0

### Failure Logs
>  NX  Running migrations from 'migrations.json'

Running migration add-target-dependencies
Successfully finished add-target-dependencies
---------------------------------------------------------
Running migration update-ngcc-postinstall
Successfully finished update-ngcc-postinstall
---------------------------------------------------------
Running migration update-webpack-browser-config
Cannot read property 'implementation' of undefined
/Users/xxx/IdeaProjects/tmi-nx-stack/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/82/zwr5h2f13ws2061t3rz7vv2h0000gn/T/tmp-19170-TRN2UPBJbwfV/node_modules/.bin/tao migrate --run-migrations=migrations.json
    at checkExecSyncError (node:child_process:680:11)
    at Object.execSync (node:child_process:717:15)
    at Object.handler (/Users/xxx/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:97:25)
    at Object.runCommand (/Users/xxx/IdeaProjects/tmi-nx-stack/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/xxx/IdeaProjects/tmi-nx-stack/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/xxx/IdeaProjects/tmi-nx-stack/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/xxx/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/cli/lib/init-local.js:25:79)
    at Object.<anonymous> (/Users/xxx/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19174,
  stdout: null,
  stderr: null
}

### Environment
  Node : 15.4.0
  OS   : darwin x64
  yarn : 1.22.11
  
  nx : Not Found
  @nrwl/angular : 11.5.1
  @nrwl/cli : 12.8.0
  @nrwl/cypress : 12.8.0
  @nrwl/devkit : 12.8.0
  @nrwl/eslint-plugin-nx : 12.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.8.0
  @nrwl/linter : 12.8.0
  @nrwl/nest : 12.8.0
  @nrwl/next : Not Found
  @nrwl/node : 12.8.0
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : 12.8.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.8.0
  @nrwl/web : 12.8.0
  @nrwl/workspace : 12.8.0
  @nrwl/storybook : 12.8.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by FrozenPandaz** [comment]
Sorry, I tried running the migrations and wasn't able to reproduce the issue.

Can you please post the logs from `nx migrate --run-migrations --verbose`?

**Comment by giridharprakash** [comment]
Running migrations from 'migrations.json'

Running migration add-target-dependencies
Cannot read property 'implementation' of undefined
TypeError: Cannot read property 'implementation' of undefined
    at /private/var/folders/7g/n233tbgd4fq60kbltq338qgw0000gn/T/tmp-50647-Bv041BzRINeZ/node_modules/@nrwl/tao/src/commands/migrate.js:537:42
    at Generator.next (<anonymous>)
    at /private/var/folders/7g/n233tbgd4fq60kbltq338qgw0000gn/T/tmp-50647-Bv041BzRINeZ/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/private/var/folders/7g/n233tbgd4fq60kbltq338qgw0000gn/T/tmp-50647-Bv041BzRINeZ/node_modules/tslib/tslib.js:113:16)
    at runNxMigration (/private/var/folders/7g/n233tbgd4fq60kbltq338qgw0000gn/T/tmp-50647-Bv041BzRINeZ/node_modules/@nrwl/tao/src/commands/migrate.js:533:20)
    at /private/var/folders/7g/n233tbgd4fq60kbltq338qgw0000gn/T/tmp-50647-Bv041BzRINeZ/node_modules/@nrwl/tao/src/commands/migrate.js:515:27
    at Generator.next (<anonymous>)
    at /private/var/folders/7g/n233tbgd4fq60kbltq338qgw0000gn/T/tmp-50647-Bv041BzRINeZ/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
/Users/giridharyellapu/MyData/projects/allegion/managekeyingweb/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;

Error: Command failed: /var/folders/7g/n233tbgd4fq60kbltq338qgw0000gn/T/tmp-50647-Bv041BzRINeZ/node_modules/.bin/tao migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.handler (/Users/giridharyellapu/MyData/projects/allegion/managekeyingweb/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:90:25)
    at Object.runCommand (/Users/giridharyellapu/MyData/projects/allegion/managekeyingweb/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/giridharyellapu/MyData/projects/allegion/managekeyingweb/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/giridharyellapu/MyData/projects/allegion/managekeyingweb/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/giridharyellapu/MyData/projects/allegion/managekeyingweb/node_modules/@nrwl/cli/lib/init-local.js:26:79)
    at Object.<anonymous> (/Users/giridharyellapu/MyData/projects/allegion/managekeyingweb/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (/Users/giridharyellapu/.npm-global/lib/node_modules/@nrwl/cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 50650,
  stdout: null,
  stderr: null
}

**Comment by justinhandley** [comment]
Here is another set...

```[justinhandley@Justins-iMac.local] tmi-nx-stack (jbh/nx-upgrade) ✗ $ nx migrate --run-migrations=migrations.json --verbose
yarn run v1.22.11
$ /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/.bin/tao migrate --run-migrations=migrations.json --verbose
Running migration add-target-dependencies
Cannot read property 'implementation' of undefined
TypeError: Cannot read property 'implementation' of undefined
    at /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/tao/src/commands/migrate.js:451:42
    at Generator.next (<anonymous>)
    at /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/tslib/tslib.js:113:16)
    at runNxMigration (/Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/tao/src/commands/migrate.js:447:20)
    at /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/tao/src/commands/migrate.js:436:23
    at Generator.next (<anonymous>)
    at /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn tao migrate --run-migrations=migrations.json --verbose
    at checkExecSyncError (node:child_process:680:11)
    at Object.execSync (node:child_process:717:15)
    at Object.handler (/Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:76:21)
    at Object.runCommand (/Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/cli/lib/init-local.js:23:13)
    at Object.<anonymous> (/Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/@nrwl/cli/bin/nx.js:41:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 8861,
  stdout: null,
  stderr: null
}
```

**Comment by justinhandley** [comment]
Although, I ran that because that is what the script told me to do.  If I just run without =migrations.json I get the following.

```nx migrate --run-migrations --verbose 
yarn run v1.22.11
$ /Users/justinhandley/IdeaProjects/tmi-nx-stack/node_modules/.bin/tao migrate --run-migrations --verbose
Fetching meta data about packages.
It may take a few minutes.

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'yarn'
✨  Done in 0.81s.
```

**Comment by justinhandley** [comment]
Unfortunately, I checked, and I don't have a similar situation - everything is in devDependencies.
