### ISSUE TITLE
babel.config.json nrwl preset causing next serve to fail

### ISSUE THREAD

**Issue by DaveLo** [nrwl/nx#6980]
## Current Behavior

I added @nrwl/next to an existing workspace, I think originally made around v11 but have kept up with migrations.
- ran `npx nx g @nrwl/next:app myAppName --style=css`
- app was generated
- ran `npm start myAppName`
- error on compile

## Expected Behavior

expected the default app to build

## Steps to Reproduce

I know the cause of the issue, but I'm not sure where it changed?
If you add 
```json
{
  "presets": ["@nrwl/web/babel"],
  "babelrcRoots": ["*"]
}
```
to your `babel.config.json` file at root the issue occurs. 

I feel like this is something that migrate should have removed as it is an @nrwl/web dependency not a custom babel config

The error itself is also not a good developer experience, all of the issues seem to be coming from next and react without babel coming up. As I'm just using default config for babel it was some time before I thought to compare a new workspace config to my existing one.

### Failure Logs

<details>
   <summary>Stack Trace</summary>

  ```
       error - ../../node_modules/next/dist/pages/_document.js (180:54) @ eval
    TypeError: f.endsWith is not a function
    null
    TypeError: f.endsWith is not a function
        at eval (webpack-internal:///../../node_modules/next/dist/pages/_document.js:283:16)
        at Array.filter (<anonymous>)
        at Head.getCssLinks (webpack-internal:///../../node_modules/next/dist/pages/_document.js:282:35)
        at Head.render (webpack-internal:///../../node_modules/next/dist/pages/_document.js:626:23)
        at processChild (/Users/**/**/**/**/node_modules/react-dom/cjs/react-dom-server.node.development.js:3450:18)
        at resolve (/Users/**/**/**/**/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
        at ReactDOMServerRenderer.render (/Users/**/**/**/**/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
        at ReactDOMServerRenderer.read (/Users/**/**/**/**/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
        at Object.renderToStaticMarkup (/Users/**/**/**/**/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
        at Object.renderToHTML (/Users/**/**/**/**/node_modules/next/dist/server/render.js:711:41)
    TypeError: f.endsWith is not a function
        at eval (webpack-internal:///../../node_modules/next/dist/pages/_document.js:283:16)
        at Array.filter (<anonymous>)
        at Head.getCssLinks (webpack-internal:///../../node_modules/next/dist/pages/_document.js:282:35)
        at Head.render (webpack-internal:///../../node_modules/next/dist/pages/_document.js:626:23)
        at processChild (/Users/**/**/**/**/node_modules/react-dom/cjs/react-dom-server.node.development.js:3450:18)
        at resolve (/Users/**/**/**/**/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
        at ReactDOMServerRenderer.render (/Users/**/**/**/**/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
        at ReactDOMServerRenderer.read (/Users/**/**/**/**/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
        at Object.renderToStaticMarkup (/Users/**/**/**/**/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
        at Object.renderToHTML (/Users/**/**/**/**/node_modules/next/dist/server/render.js:711:41)
  ```

</details>

### Environment

```  Node : 14.17.1
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : 12.9.0
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.4.2
```

**Comment by Uter1007** [comment]
- "@nrwl/next": "12.6.6",
+ "@nrwl/next": "12.10.0",
