### ISSUE TITLE
Error when running affected:test with --parallel

### ISSUE THREAD

**Issue by AnyFlippingUsernameWillDo** [nrwl/nx#700]
Hi,
Apologies if this has been mentioned before or if I'm doing something stupid but I'm getting a "Cannot read property 'forEach' of undefined" when I try to run any of the affected commands with --parallel.
This is with version 6.2.0 but doesn't work with earlier versions.
Windows, Node v9.11.1

For example.

$ ./node_modules/.bin/nx affected:test a1d95f6dda5fd1a20f3ae3135255018d5cd825b1 f93c998bd93921b0cf4b639cea410a7a16a31b13 --parallel Testing a, b, c, d, e with flags: --no-watch
(node:15732) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at C:\Projects\blah\node_modules\@nrwl\schematics\src\command-line\affected.js:237:33
    at step (C:\Projects\blah\node_modules\@nrwl\schematics\src\command-line\affected.js:40:23)
    at Object.throw (C:\Projects\blah\node_modules\@nrwl\schematics\src\command-line\affected.js:21:53)
    at rejected (C:\Projects\blah\node_modules\@nrwl\schematics\src\command-line\affected.js:13:65)
    at <anonymous>
(node:15732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit code.
Done in 8.67s.

Without trying to run in parallel everything works fine.

If anyone could point me in the right direction to either fix or diagnose the problem I would be very grateful.

Thanks.

**Comment by AnyFlippingUsernameWillDo** [comment]
Ah ... I have found the problem.
My upgraded project was missing the following from my package.json file
```
  "scripts": {
    "ng": "ng",
```

Adding that has fixed the issue.
I guess it might be nice if the error message was a little more helpful.

**Comment by kpaxton** [comment]
Having that as a requirement is not documented anywhere. There should at least be a fallback if that is not present.

I just ran into this same issue and that's a bit frustrating that I have to have a pointless reference in the package.json for this to work.
