### ISSUE TITLE
bug: Angular CLI 12.2.7 new WASM feature causes libraries to fail if configuration is not present such as 'staging'

### ISSUE THREAD

**Issue by bjornharvold** [nrwl/nx#7128]
## Current Behavior
When updating to Angular & Angular CLI 12.2.7 and running a command such as this:
`node --max_old_space_size=16384 ./node_modules/.bin/nx run-many --target build --projects=app1,app2 --configuration production --parallel --max-parallel=4`

It now fails with the following error:
```
error	24-Sep-2021 16:25:02	runtime: nameOff 0x616b6361 out of range 0xd840 - 0x201ac5
error	24-Sep-2021 16:25:02	fatal error: runtime: name offset out of range
error	24-Sep-2021 16:25:02	
error	24-Sep-2021 16:25:02	goroutine 1 [running]:
error	24-Sep-2021 16:25:02	runtime.throw({0x83a95, 0x21})
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/panic.go:1198 +0x7 fp=0x46e858 sp=0x46e830 pc=0x12000007
error	24-Sep-2021 16:25:02	runtime.resolveNameOff(0xf228, 0x616b6361)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/type.go:195 +0x37 fp=0x46e8c0 sp=0x46e858 pc=0x134e0037
error	24-Sep-2021 16:25:02	runtime.name.pkgPath({0xf228})
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/type.go:511 +0x21 fp=0x46e8e8 sp=0x46e8c0 pc=0x13530021
error	24-Sep-2021 16:25:02	runtime.(*itab).init(0xc35858)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/iface.go:212 +0x1d fp=0x46e9a8 sp=0x46e8e8 pc=0x107a001d
error	24-Sep-2021 16:25:02	runtime.getitab(0x42b40, 0x4c9c0, 0x1)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/iface.go:75 +0x22 fp=0x46e9f0 sp=0x46e9a8 pc=0x10760022
error	24-Sep-2021 16:25:02	runtime.assertI2I2(0x42b40, {0xe74b8, 0x462210})
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/iface.go:467 +0x5 fp=0x46ea18 sp=0x46e9f0 pc=0x10870005
error	24-Sep-2021 16:25:02	math/rand.New(...)
error	24-Sep-2021 16:25:02		/usr/local/go/src/math/rand/rand.go:67
error	24-Sep-2021 16:25:02	math/rand.init()
error	24-Sep-2021 16:25:02		/usr/local/go/src/math/rand/rand.go:293 +0xe fp=0x46ea68 sp=0x46ea18 pc=0x1682000e
error	24-Sep-2021 16:25:02	runtime.doInit(0x2edca0)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/proc.go:6498 +0x1e fp=0x46ebb0 sp=0x46ea68 pc=0x12a9001e
error	24-Sep-2021 16:25:02	runtime.doInit(0x2f20a0)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/proc.go:6475 +0x9 fp=0x46ecf8 sp=0x46ebb0 pc=0x12a90009
error	24-Sep-2021 16:25:02	runtime.doInit(0x2f0d20)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/proc.go:6475 +0x9 fp=0x46ee40 sp=0x46ecf8 pc=0x12a90009
error	24-Sep-2021 16:25:02	runtime.doInit(0x2f1900)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/proc.go:6475 +0x9 fp=0x46ef88 sp=0x46ee40 pc=0x12a90009
error	24-Sep-2021 16:25:02	runtime.main()
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/proc.go:238 +0x24 fp=0x46efe0 sp=0x46ef88 pc=0x121f0024
error	24-Sep-2021 16:25:02	runtime.goexit()
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/asm_wasm.s:431 +0x1 fp=0x46efe8 sp=0x46efe0 pc=0x13d10001
```

## Expected Behavior
The build should build successfully. 

## Steps to Reproduce
- Use Angular 12.2.7 
- Use the run-may command with parallel enabled to build your apps

### Environment
```
 Node : 14.15.3
  OS   : linux x64
  yarn : 1.22.5
  
  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

The only change that occurred that matches the error was this fix in Angular CLI:
https://github.com/angular/angular-cli/commit/d856b4d2369bea76ce65fc5f6d1585145ad41618

**Comment by leosvelperez** [comment]
Thanks for reporting this!

I was not able to reproduce it. Would you be able to provide a repo with a minimal reproduction of the issue?

**Comment by bjornharvold** [comment]
Hi,

We have a 1000+ module monorepo. When we upgraded Angular CLI, our CI
server immediately complained… until we removed “—with-parallel”. The last
error message indicates that wasm is involved.

I wouldn’t know how to replicate this.

**Comment by leosvelperez** [comment]
I see. I'll see if I can somehow reproduce it with a bigger workspace, but I guess is gonna be tricky to troubleshoot, this is one of those :)

**Comment by bjornharvold** [comment]
I want to follow up on this ticket as I think I've figured out what is going on.

We have no problems building for production. However, when we build for staging, this error crops up a lot at random. I think the issue is this:

When you build a SPA for a certain environment: e.g. `nx build myspa --configuration staging`, Nx will go ahead and build all dependent libraries and then build the SPA while replacing environment.ts with environment.staging.ts. However, each library only has development and production configurations in angular.json and default configuration for each library is set to production.

When we try to build a SPA with the staging environment, libraries will fail at random (or maybe not so random). After a failed run, we try to build each failed library one by one. This works without a hitch because it's using the production configuration. Trying to run nx build my-library --configuration staging will fail because that environment doesn't exist. After each failed library has compiled [and is in the cache], we try to build the SPA for staging again. Eventually, we will have compiled all libraries that fail and the SPA will success for staging as well.

So what to do with this? We don't need a staging configuration and the default is production as we desire. So why did this start happening with Angular CLI 12.2.7 and the WASM update... or was it because it around the same time we re-configured our staging environment. Not sure. 

We tried looking up the error and apparently this came up: https://github.com/golang/go/issues/15372

Cheers

**Comment by leosvelperez** [comment]
Thanks for sharing those details. I still haven't been able to reproduce it and I don't know Go enough to have a better idea of what could be happening.

Looking at the logs file you shared there's an important detail though. The issue is happening when trying to process component stylesheets. Every error in the log have something like this:

```
error	07-Oct-2021 21:20:59	The service was stopped in stylesheet file /media/user/external/bamboo/xml-data/build-dir/TRAV-INMRFB-JOB1/libs/shared/ui-required-field-indicator/src/lib/components/required-field-indicator/required-field-indicator.component.scss.
error	07-Oct-2021 21:20:59	
error	07-Oct-2021 21:20:59	The service is no longer running in stylesheet file /media/user/external/bamboo/xml-data/build-dir/TRAV-INMRFB-JOB1/libs/shared/ui-required-field-indicator/src/lib/components/required-field-indicator/required-field-indicator.component.scss.
error	07-Oct-2021 21:21:00	[96mlibs/shared/ui-required-field-indicator/src/lib/components/required-field-indicator/required-field-indicator.component.ts[0m:[93m11[0m:[93m15[0m - [91merror[0m[90m NG2008: [0mCould not find stylesheet file './required-field-indicator.component.scss'.
error	07-Oct-2021 21:21:00	
error	07-Oct-2021 21:21:00	[7m11[0m   styleUrls: ['./required-field-indicator.component.scss'],
error	07-Oct-2021 21:21:00	[7m  [0m [91m              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
```

I did a search of those error messages and they come from `esbuild` and `ng-packagr`. This line in `ng-packagr` https://github.com/ng-packagr/ng-packagr/blob/v12.2/src/lib/ts/cache-compiler-host.ts#L141 seems to be logging that and re-throw the error.

**Comment by bjornharvold** [comment]
Last update is also not correct. I am able to build a prod build on my Mac but not on our CI server, there is also another error: 

```
build	08-Oct-2021 10:04:23	> nx run shared-ui-select-object-input-form:build:production 
build	08-Oct-2021 10:04:25	Building Angular Package
build	08-Oct-2021 10:04:25	
build	08-Oct-2021 10:04:25	------------------------------------------------------------------------------
build	08-Oct-2021 10:04:25	Building entry point '@iko/shared/ui-select-object-input-form'
build	08-Oct-2021 10:04:25	------------------------------------------------------------------------------
error	08-Oct-2021 10:04:27	RuntimeError: invalid index into function table
error	08-Oct-2021 10:04:27	    at <anonymous>:wasm-function[204]:0x2245a
error	08-Oct-2021 10:04:27	    at <anonymous>:wasm-function[2299]:0x265f31
error	08-Oct-2021 10:04:27	    at <anonymous>:wasm-function[2300]:0x26649d
error	08-Oct-2021 10:04:27	    at <anonymous>:wasm-function[703]:0xa0e31
error	08-Oct-2021 10:04:27	    at <anonymous>:wasm-function[703]:0xa0cae
error	08-Oct-2021 10:04:27	    at <anonymous>:wasm-function[1007]:0xdfc31
error	08-Oct-2021 10:04:27	    at run (<anonymous>:wasm-function[1005]:0xdfc04)
error	08-Oct-2021 10:04:27	    at global.Go.run (eval at <anonymous> (/media/user/external/bamboo/xml-data/build-dir/TRAV-INMRFB-JOB1/node_modules/ng-packagr/node_modules/esbuild-wasm/bin/esbuild:15:17), <anonymous>:597:23)
error	08-Oct-2021 10:04:27	    at eval (eval at <anonymous> (/media/user/external/bamboo/xml-data/build-dir/TRAV-INMRFB-JOB1/node_modules/ng-packagr/node_modules/esbuild-wasm/bin/esbuild:15:17), <anonymous>:650:14)
error	08-Oct-2021 10:04:27	
error	08-Oct-2021 10:04:27	The service was stopped in stylesheet file /media/user/external/bamboo/xml-data/build-dir/TRAV-INMRFB-JOB1/libs/shared/ui-select-object-input-form/src/lib/components/select-object-input-form/select-object-input-form.component.scss.
error	08-Oct-2021 10:04:27	
error	08-Oct-2021 10:04:27	The service is no longer running in stylesheet file /media/user/external/bamboo/xml-data/build-dir/TRAV-INMRFB-JOB1/libs/shared/ui-select-object-input-form/src/lib/components/select-object-input-form/select-object-input-form.component.scss.
error	08-Oct-2021 10:04:28	[96mlibs/shared/ui-select-object-input-form/src/lib/components/select-object-input-form/select-object-input-form.component.ts[0m:[93m14[0m:[93m15[0m - [91merror[0m[90m NG2008: [0mCould not find stylesheet file './select-object-input-form.component.scss'.
error	08-Oct-2021 10:04:28	
error	08-Oct-2021 10:04:28	[7m14[0m   styleUrls: ['./select-object-input-form.component.scss'],
error	08-Oct-2021 10:04:28	[7m  [0m [91m              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
error	08-Oct-2021 10:04:28	
```
