### ISSUE TITLE
Cannot find module '@myworkspace/mobile/app-navigation'

### ISSUE THREAD

**Issue by jeremiahlachica** [nrwl/nx#7216]
## Current Behavior

- I have react-native project named "mobile". It compiles and runs fine on simulator (no-errors). 
- But when I try to test the component using jest, it gives me this error:
```
 Cannot find module '@myworkspace/mobile/app-navigation' from 'src/home-screen/HomeScreen.tsx'
```

## Expected Behavior

- Testing using Jest should run without import errors

### Failure Logs
```
Cannot find module '@myworkspace/mobile/app-navigation' from 'src/home-screen/HomeScreen.tsx'

    Require stack:
      src/home-screen/HomeScreen.tsx
      src/home-screen/HomeScreen.spec.tsx

      2 | import { observer } from 'mobx-react';
      3 | import { Text } from 'react-native';
    > 4 | import { AppNavigation } from '@myworkspace/mobile/app-navigation';
        |                      ^
      5 | import { EmailTextInput, PasswordTextInput } from '@myworkspace/mobile/text-input';
      6 | import { RoundedSolidButton } from '@myworkspace/mobile-button';
      7 | import { VerticalSpaceMicro } from '@myworkspace/mobile/space';

      at Resolver.resolveModule (../../node_modules/jest-runtime/node_modules/jest-resolve/build/resolver.js:322:11)
      at Object.<anonymous> (src/home-screen/HomeScreen.tsx:4:22)
```
Please help. Thanks.

**Comment by xiongemi** [comment]
maybe add `resolver: '@nrwl/jest/plugins/resolver',` in the jest.config.js.
it works for me and my jest.config.js looks like:
```
module.exports = {
  preset: 'react-native',
  testRunner: 'jest-jasmine2',
  resolver: '@nrwl/jest/plugins/resolver',
...
```
