### ISSUE TITLE
Cannot find module when TypeScript path has asterisks

### ISSUE THREAD

**Issue by muuvmuuv** [nrwl/nx#7218]
## Current Behavior

We have two `paths` that uses asterisks, so we can point to a specific file and not import dependencies that are not available in node/browser env (webpack configs and browser window functions). Unfortunately, `nx` always prints an error but VS Code for example does not and shows the correct files on autocomplete.

## Expected Behavior

Resolve the path.

## Steps to Reproduce

tsconfig.base.json:

```jsonc
//...
    "paths": {
      "@entergon/webpack/*": [
        "libs/webpack/src/*"
      ],
//...
```

<img width="166" alt="Bildschirmfoto 2021-10-04 um 09 09 34" src="https://user-images.githubusercontent.com/11534760/135808215-74051444-8659-4834-acf0-9e9e544e85d1.png">

Repro: uploading...

### Failure Logs

```
; pnpm nx build --verbose

> nx run entergon:build:production --verbose
    WARNING: Zone.js does not support native async/await in ES2017.
    These blocks are not intercepted by zone.js and will not triggering change detection.
    See: https://github.com/angular/zone.js/pull/1140 for more information.
⨯ Unable to compile TypeScript:
apps/entergon/webpack.config.ts:3:34 - error TS2307: Cannot find module '@entergon/common/webpack' or its corresponding type declarations.

3 import { getProjectConfig } from "@entergon/common/webpack"
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~

TSError: ⨯ Unable to compile TypeScript:
apps/entergon/webpack.config.ts:3:34 - error TS2307: Cannot find module '@entergon/common/webpack' or its corresponding type declarations.

3 import { getProjectConfig } from "@entergon/common/webpack"
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/marvin/Development/app/node_modules/.pnpm/ts-node@9.1.1_typescript@3.9.10/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/marvin/Development/app/node_modules/.pnpm/ts-node@9.1.1_typescript@3.9.10/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/marvin/Development/app/node_modules/.pnpm/ts-node@9.1.1_typescript@3.9.10/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/marvin/Development/app/node_modules/.pnpm/ts-node@9.1.1_typescript@3.9.10/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/marvin/Development/app/node_modules/.pnpm/ts-node@9.1.1_typescript@3.9.10/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/marvin/Development/app/node_modules/.pnpm/ts-node@9.1.1_typescript@3.9.10/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (/Users/marvin/Development/app/node_modules/.pnpm/@nrwl+tao@12.9.0/packages/tao/src/compat/compat.ts:9:36)
    at require (node:internal/modules/cjs/helpers:94:18)
    at resolveCustomWebpackConfig (/Users/marvin/Development/app/node_modules/.pnpm/@angular-builders+custom-webpack@10.0.1_7913a8bbcf76dfb5c47281d6c299ccc3/node_modules/@angular-builders/custom-webpack/src/custom-webpack-builder.ts:62:31)
    at Function.<anonymous> (/Users/marvin/Development/app/node_modules/.pnpm/@angular-builders+custom-webpack@10.0.1_7913a8bbcf76dfb5c47281d6c299ccc3/node_modules/@angular-builders/custom-webpack/src/custom-webpack-builder.ts:32:38)
    at Generator.next (<anonymous>)
    at /Users/marvin/Development/app/node_modules/.pnpm/@angular-builders+custom-webpack@10.0.1_7913a8bbcf76dfb5c47281d6c299ccc3/node_modules/@angular-builders/custom-webpack/dist/custom-webpack-builder.js:8:71

———————————————————————————————————————————————

>  NX   ERROR  Running target "entergon:build" failed

  Failed tasks:

  - entergon:build:production

  Hint: run the command with --verbose for more details.
```

### Environment

```
; pnpm nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.9.0
  OS   : darwin arm64
  pnpm : 6.14.7

  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 3.9.10
```

**Comment by muuvmuuv** [comment]
Ah sorry my mistake it was because angular builders custom webpack had issues with resolving paths during typescript compilation.
