### ISSUE TITLE
update-invalid-import-paths 12.9.0: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#7250]
I am getting following error when i try to migrate the latest version,
```

{
      "cli": "nx",
      "version": "12.9.0",
      "description": "Fixes invalid importPaths for buildable and publishable libs.",
      "factory": "./src/migrations/update-12-9-0/update-invalid-import-paths",
      "package": "@nrwl/angular",
      "name": "update-invalid-import-paths"
    }

```
```
Running migration update-invalid-import-paths
Cannot read property 'split' of undefined
node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/pb/s03nms253k15m33xkxhqhhxc0000gn/T/tmp-57569-hc4GqRvSQQ79/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (node_modules/@nrwl/workspace/src/command-line/nx-commands.js:97:25)
    at Object.runCommand (node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (node_modules/@nrwl/cli/lib/init-local.js:25:79)
    at Object.<anonymous> (node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 57588,
  stdout: null,
  stderr: null
}
```

Can someone please check this and advise?

**Comment by Coly010** [comment]
Hi @dean-g ! 

Could you share a repo that contains the minimum requirement to reproduce this bug? That would be super helpful, thank you!
