### ISSUE TITLE
npm uninstall type-graphql or tsyringe causes error

### ISSUE THREAD

**Issue by Cuboctaedro** [nrwl/nx#7284]
I have setup a project with nx using express, graphql and react. I had installed type-graphql and tsyringe and they were working fine. At some point I decided to remove them from my code and then I ran `npm uninstall -S type-graphql tsyringe` . After that all nx cli commands give the following error:
```
(node:9660) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at Object.isNpmProject (C:\0_nelios\e-consierge\e-consierge\node_modules\@nrwl\workspace\src\core\project-graph\operators.js:52:20)
    at ProjectHasher.<anonymous> (C:\0_nelios\e-consierge\e-consierge\node_modules\@nrwl\workspace\src\core\hasher\hasher.js:244:41)
    at Generator.next (<anonymous>)
    at C:\0_nelios\e-consierge\e-consierge\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\0_nelios\e-consierge\e-consierge\node_modules\tslib\tslib.js:113:16)
    at C:\0_nelios\e-consierge\e-consierge\node_modules\@nrwl\workspace\src\core\hasher\hasher.js:241:79
    at new Promise (<anonymous>)
    at ProjectHasher.<anonymous> (C:\0_nelios\e-consierge\e-consierge\node_modules\@nrwl\workspace\src\core\hasher\hasher.js:241:50)
    at Generator.next (<anonymous>)
```
If I re-install both packages the error is fixed. Uninstalling reflect-metadata which is a requirement of type-graphql does not cause an error, so it does not happen at every uninstall.

**Comment by Cuboctaedro** [comment]
The problem is caused by type-graphql ONLY. I am trying to find the point where it happened and reproduce it but unfortunatelly it is between two commits where a lot has happened. Do you have any clues as to what should I look for? npm installs? changes in tsconfig? new apps or libraries generated?
