### ISSUE TITLE
yarn nx migrate latest (from 12.9.0 to 12.10.0) fails

### ISSUE THREAD

**Issue by jvskriubakken** [nrwl/nx#7308]
## Current Behavior

I'm trying to migrate to latest (12.10.0) from 12.9.0, but get the following error:

```
yarn nx migrate latest
yarn run v1.22.10
$ nx migrate latest
/Users/joerund/Code/xxxx.GUI/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn
    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at taoPath (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:340:21)
    at Object.handler (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:96:19)
    at Object.runCommand (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)

```

## Expected Behavior

Migration to run properly.

### Environment

My package.json (which might be the cause?):

```
{
  "name": "xxxx-gui",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "nx": "nx",
    "start": "nx serve",
    "start-local": "cross-env REACT_APP_INSIGHT_API_URL=http://localhost:44398/api react-scripts start",
    "build": "nx build",
    "test": "nx test",
    "lint": "nx workspace-lint && nx lint",
    "e2e": "nx e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
accept-changes",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-generator": "nx workspace-generator",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "prepare": "nx g @nx-dotnet/core:restore"
  },
  "private": true,
  "dependencies": {
    "@mui/icons-material": "^5.0.1",
    "@mui/lab": "^5.0.0-alpha.48",
    "@mui/material": "^5.0.1",
    "@mui/styled-engine": "npm:@mui/styled-engine-sc@latest",
    "@mui/styles": "^5.0.1",
    "@mui/system": "^5.0.1",
    "@mui/x-data-grid-pro": "5.0.0-beta.1",
    "@reduxjs/toolkit": "1.6.1",
    "core-js": "^3.6.5",
    "document-register-element": "1.13.1",
    "luxon": "2.0.2",
    "mousetrap": "1.6.5",
    "react": "17.0.2",
    "react-device-detect": "1.17.0",
    "react-dom": "17.0.2",
    "react-is": "17.0.2",
    "react-redux": "7.2.5",
    "react-resize-detector": "^6.7.3",
    "react-virtualized": "^9.22.3",
    "react-vis": "1.11.7",
    "redux-thunk": "2.3.0",
    "regenerator-runtime": "0.13.7",
    "styled-components": "5.3.1",
    "tslib": "^2.0.0",
    "uuid": "8.3.2"
  },
  "devDependencies": {
    "@babel/core": "7.12.13",
    "@babel/preset-env": "7.12.13",
    "@babel/preset-react": "7.12.13",
    "@babel/preset-typescript": "7.12.13",
    "@nrwl/cli": "12.9.0",
    "@nrwl/cypress": "12.9.0",
    "@nrwl/eslint-plugin-nx": "12.9.0",
    "@nrwl/jest": "12.9.0",
    "@nrwl/linter": "12.9.0",
    "@nrwl/react": "12.9.0",
    "@nrwl/storybook": "12.9.0",
    "@nrwl/tao": "12.9.0",
    "@nrwl/web": "12.9.0",
    "@nrwl/workspace": "12.9.0",
    "@nx-dotnet/core": "^1.3.2",
    "@storybook/addon-docs": "6.3.7",
    "@storybook/addon-essentials": "6.3.7",
    "@storybook/addon-knobs": "6.3.0",
    "@storybook/react": "6.3.7",
    "@svgr/webpack": "^5.4.0",
    "@testing-library/react": "11.2.6",
    "@testing-library/react-hooks": "7.0.1",
    "@types/jest": "26.0.24",
    "@types/libnpmpublish": "4.0.1",
    "@types/pacote": "11.1.1",
    "@types/luxon": "2.0.4",
    "@types/mousetrap": "1.6.8",
    "@types/node": "14.14.33",
    "@types/react": "17.0.24",
    "@types/react-dom": "17.0.9",
    "@types/react-is": "17.0.0",
    "@types/react-resize-detector": "^6.1.0",
    "@types/styled-components": "5.1.14",
    "@types/uuid": "8.3.1",
    "@types/webpack": "4.41.21",
    "@typescript-eslint/eslint-plugin": "4.28.5",
    "@typescript-eslint/parser": "4.28.5",
    "babel-jest": "26.2.2",
    "babel-loader": "8.1.0",
    "babel-plugin-styled-components": "1.10.7",
    "chromatic": "^5.10.1",
    "cypress": "^8.3.0",
    "dotenv": "10.0.0",
    "eslint": "7.22.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.23.1",
    "eslint-plugin-react-hooks": "4.2.0",
    "jest": "27.0.3",
    "libnpmpublish": "^4.0.2",
    "pacote": "^11.3.5",
    "prettier": "^2.3.1",
    "storybook-addon-designs": "^6.0.1",
    "ts-jest": "27.0.3",
    "ts-node": "~9.1.1",
    "typescript": "~4.3.5",
    "url-loader": "^3.0.0"
  },
  "resolutions": {
    "@mui/styled-engine": "npm:@mui/styled-engine-sc@latest"
  }
}
```

nx report:
```

  Node : 14.18.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.10.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

```

**Comment by RichieThirteenMillion** [comment]
I encountered this issue today while trying to migrate using node v16 - but it looks like the migrate is working now that I switched down to node v14.

**Comment by jvskriubakken** [comment]
I am now using node v14, but that did not help :(

Running with --verbose does not seem to give any more useful info, but here is the printout:

```
yarn nx migrate latest --verbose
yarn run v1.22.10
$ nx migrate latest --verbose
/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn
    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at taoPath (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:340:21)
    at Object.handler (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:96:19)
    at Object.runCommand (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/cli/lib/init-local.js:25:79)
    at Object.<anonymous> (/Users/joerund/Code/eSmart.GUI/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 20183,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
```

**Comment by jvskriubakken** [comment]
What is Nx trying to do when it fails? What is taoPath about?
