### ISSUE TITLE
normalize-options.js does use context.root to check if options.main exists.

### ISSUE THREAD

**Issue by jblevins1991** [nrwl/nx#7407]
## Current Behavior

Currently, when you build your nx plugin, the `normalizeOptions` function passes `options.main` to `fs.existsSync`. This will be an issue as `options.main` is a relative path name. It will always check for `options.main` relative to the cwd.

## Expected Behavior

I expect to be able to run any of my `nx` commands from any directory in the project.

## Steps to Reproduce

1. generate a workspace with a plugin in it
2. cd to your plugins root directory
3. run `nx build <plugin-name> --verbose
4. observe a build error stating `Please verify that the "main" option for project "plugin-name" is valid.`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
Josh@DESKTOP-6QMMK8N MINGW64 ~/Development/nightowl/libs (main)
$ nx build sanity --verbose

> nx run sanity:build --verbose 
Please verify that the "main" option for project "sanity" is valid.
Error: Please verify that the "main" option for project "sanity" is valid.
    at Object.normalizeOptions [as default] (C:\Users\Josh\Development\nightowl\node_modules\@nrwl\node\src\executors\package\utils\normalize-options.js:14:15)
    at C:\Users\Josh\Development\nightowl\node_modules\@nrwl\node\src\executors\package\package.impl.js:15:62
    at Generator.next (<anonymous>)
    at C:\Users\Josh\Development\nightowl\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Josh\Development\nightowl\node_modules\tslib\tslib.js:113:16)
    at packageExecutor (C:\Users\Josh\Development\nightowl\node_modules\@nrwl\node\src\executors\package\package.impl.js:13:20)
    at C:\Users\Josh\Development\nightowl\node_modules\@nrwl\tao\src\commands\run.js:134:23
    at Generator.next (<anonymous>)
    at C:\Users\Josh\Development\nightowl\node_modules\tslib\tslib.js:117:75

———————————————————————————————————————————————

>  NX   ERROR  Running target "sanity:build" failed

  Failed tasks:

  - sanity:build

  Hint: run the command with --verbose for more details.
```

### Environment

```
Josh@DESKTOP-6QMMK8N MINGW64 ~/Development/nightowl/libs (main)
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.18.0
  OS   : win32 x64
  npm  : 6.14.15

  nx : 12.10.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.10.0
  @nrwl/cypress : 12.10.0
  @nrwl/devkit : 12.10.0
  @nrwl/eslint-plugin-nx : 12.10.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.10.0
  @nrwl/linter : 12.10.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.10.0
  @nrwl/nx-cloud : 12.3.14
  @nrwl/react : 12.10.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.10.0
  @nrwl/web : 12.10.0
  @nrwl/workspace : 12.10.0
  @nrwl/storybook : 12.10.0
  @nrwl/gatsby : 12.10.0
  typescript : 4.3.5
```

**Comment by ashbrener** [comment]
I am also experiencing this, is there a fix ?
