### ISSUE TITLE
nxdaemon: Error on library remove

### ISSUE THREAD

**Issue by bjornharvold** [nrwl/nx#7503]
## Current Behavior
Second library removal throws an error

## Expected Behavior
Library should just be removed

## Steps to Reproduce
After having deleted a library such as:
`nx g @nrwl/workspace:remove developer-ui-my-card`

Then executing a second command such another removal:
`nx g @nrwl/workspace:remove developer-ui-my-table`

### Failure Logs
```
 ERROR  Daemon Client - The server returned an Error

ENOENT: no such file or directory, open '/Users/crash/git/iko-travel-spa/libs/developer/ui-my-card/jest.config.js'
```

### Environment
```
Node : 12.22.7
  OS   : darwin x64
  yarn : 1.22.17
  
  nx : 13.0.2
  @nrwl/angular : 13.0.2
  @nrwl/cli : 13.0.2
  @nrwl/cypress : 13.0.2
  @nrwl/devkit : 13.0.2
  @nrwl/eslint-plugin-nx : 13.0.2
  @nrwl/express : Not Found
  @nrwl/jest : 13.0.2
  @nrwl/linter : 13.0.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 13.0.2
  @nrwl/storybook : 13.0.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by bjornharvold** [comment]
Another issue that comes up is the app no longer wants to start:

```
 ERROR  Daemon Client - The server returned an Error

(node:3747) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/crash/git/iko-travel-spa/libs/developer/ui-my-table/jest.config.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.defaultFileRead (/Users/crash/git/iko-travel-spa/node_modules/@nrwl/workspace/src/core/file-utils.js:160:17)
    at TypeScriptImportLocator.fromFile (/Users/crash/git/iko-travel-spa/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/typescript-import-locator.js:22:38)
    at /Users/crash/git/iko-travel-spa/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:12:27
    at Array.forEach (<anonymous>)
    at /Users/crash/git/iko-travel-spa/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:11:47
    at Array.forEach (<anonymous>)
    at Object.buildExplicitTypeScriptDependencies (/Users/crash/git/iko-travel-spa/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:10:33)
    at Object.buildExplicitTypescriptAndPackageJsonDependencies (/Users/crash/git/iko-travel-spa/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/build-explicit-typescript-and-package-json-dependencies.js:8:49)
```

**Comment by bjornharvold** [comment]
This also goes away after waiting a bit and trying again.
