### ISSUE TITLE
NX Plugin e2e tests unable to create project in Githib Actions

### ISSUE THREAD

**Issue by TriPSs** [nrwl/nx#7504]
## Current Behavior
When running `npx nx run-many --target=e2e --projects=<project name>` inside Github actions the tests fail when creating a new project

## Expected Behavior
The tests to pass like on local machine

## Steps to Reproduce
Repo that has the issue: [tripss/nx-extend](https://github.com/tripss/nx-extend) [this build](https://github.com/TriPSs/nx-extend/runs/3989770640) for example.

### Failure Logs
```
    Command failed: yarn

      at runPackageManagerInstall (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:54:19)
      at newNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:74:3)
      at Object.ensureNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:86:3)
      at tests/gcp-deployment-manager.spec.ts:12:5
      at ../../node_modules/tslib/tslib.js:117:75
      at Object.__awaiter (../../node_modules/tslib/tslib.js:113:16)
```

### Environment
Github actions

**Comment by benpsnyder** [comment]
@vsavkin  I am using Yarn v3 on most of my projects. I have found [@yarnpkg/plugin-patch](https://www.npmjs.com/package/@yarnpkg/plugin-patch) to be helpful in patching and testing this issue.  Check [@srleecode/domain - Fix all of the e2e tests](https://github.com/srleecode/domain/pull/30/commits/5573c2ac4263a3246449ae25d99e34a435285f19) which is a WIP ... I'll post back here with some additional helpful info when I have made more progress

**Comment by benpsnyder** [comment]
@vsavkin I have figured this out after 6 hours of debugging :) ... please reference https://github.com/srleecode/domain/pull/30/files

this `.yarn/patches/@nrwl-nx-plugin-npm-13.2.2-9ae4bffcd4`
````
diff --git a/src/utils/testing-utils/nx-project.js b/src/utils/testing-utils/nx-project.js
index 7284da90de99a43453af342e2686273b66132738..e2974e7158ed8ab5359312dd252af004fff25cf6 100644
--- a/src/utils/testing-utils/nx-project.js
+++ b/src/utils/testing-utils/nx-project.js
@@ -10,7 +10,7 @@ const paths_1 = require("./paths");
 const utils_1 = require("./utils");
 function runNxNewCommand(args, silent) {
     const localTmpDir = (0, path_1.dirname)((0, paths_1.tmpProjPath)());
-    return (0, child_process_1.execSync)(`node ${require.resolve('@nrwl/tao')} new proj --nx-workspace-root=${localTmpDir} --no-interactive --skip-install --collection=@nrwl/workspace --npmScope=proj --preset=empty ${args || ''}`, Object.assign({ cwd: localTmpDir }, (silent && false ? { stdio: ['ignore', 'ignore', 'ignore'] } : {})));
+    return (0, child_process_1.execSync)(`node ${require.resolve('@nrwl/tao')} new proj --nx-workspace-root=${localTmpDir} --no-interactive --skip-install --collection=@nrwl/workspace --npmScope=proj --packageManager=yarn --preset=empty ${args || ''}`, Object.assign({ cwd: localTmpDir }, (silent && false ? { stdio: ['ignore', 'ignore', 'ignore'] } : {})));
 }
 function patchPackageJsonForPlugin(npmPackageName, distPath) {
     const path = (0, paths_1.tmpProjPath)('package.json');
````
and `.yarn/patches/@nrwl-tao-npm-13.2.2-701855e572`
````
diff --git a/src/shared/package-manager.js b/src/shared/package-manager.js
index 259ff28b90bea84abd71e53d410798d9e71ba1db..921e72f111704bc3d5ddb3ac32e40abe96939849 100644
--- a/src/shared/package-manager.js
+++ b/src/shared/package-manager.js
@@ -29,7 +29,7 @@ exports.detectPackageManager = detectPackageManager;
 function getPackageManagerCommand(packageManager = detectPackageManager()) {
     const commands = {
         yarn: () => ({
-            install: 'yarn',
+            install: 'touch yarn.lock && yarn install',
             add: 'yarn add',
             addDev: 'yarn add -D',
             rm: 'yarn remove',
````

Yarn v3 expects there to be a `yarn.lock` file. I know `touch yarn.lock` isn't going to wrok cross-platform, but I am sure you can take inspiration from what I've done above and implement properly 👯
