### ISSUE TITLE
'nx migrate latest' command failed by npm error code 'EINVALIDPACKAGENAME' 

### ISSUE THREAD

**Issue by Arvi2k17** [nrwl/nx#7550]
While Migrating from the @nrwl/workspace@11.5.1 to @nrwl/workspace@latest command failed.

I tried  'nx migrate latest' it failed.

I thought my workspace will be migrated to the latest but remains the same.

NX Report 
```
 NX  Report complete - copy this into the issue template

  Node : 12.14.1
  OS   : win32 x64
  npm  : 6.14.15

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.1
  @nrwl/cypress : 11.5.1
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.5.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.5.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : 11.5.1
  @nrwl/workspace : 11.5.1
  @nrwl/storybook : 11.5.1
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```
**Error: Invalid Package Name  "__ngcc_entry_points__.json": name cannot start with an underscore** 
```
Error:-
Fetching meta data about packages.
It may take a few minutes.     
Fetching @nrwl/workspace@latest

 ERROR  The migrate command failed.

Command failed: npm install @nrwl/workspace@latest
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "__ngcc_entry_points__.json": name cannot start with an underscore

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aravinth2k17\AppData\Roaming\npm-cache\_logs\2021-10-28T07_46_16_779Z-debug.log

C:\Workspace\React\admin-clone\fcm-admin-app\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\ARAVIN~1\AppData\Local\Temp\tmp-20052-TWb5i19JOnld\node_modules\.bin\tao migrate latest
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at Object.handler (C:\Workspace\React\admin-clone\fcm-admin-app\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:114:25)
    at Object.runCommand (C:\Workspace\React\admin-clone\fcm-admin-app\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Workspace\React\admin-clone\fcm-admin-app\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\Workspace\React\admin-clone\fcm-admin-app\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\Workspace\React\admin-clone\fcm-admin-app\node_modules\@nrwl\cli\lib\init-local.js:23:13)
    at Object.<anonymous> (C:\Workspace\React\admin-clone\fcm-admin-app\node_modules\@nrwl\cli\bin\nx.js:42:18)     
    at Module._compile (C:\Users\Aravinth2k17\AppData\Roaming\npm\node_modules\nx\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9692,
  stdout: null,
  stderr: null
}
```

![image](https://user-images.githubusercontent.com/70632639/139227862-5ab1ca6c-417f-4fa9-bd59-5d0f3c2625db.png)

**Comment by Arvi2k17** [comment]
@vsavkin could please help me with this?

**Comment by always-maap** [comment]
nx migrate next with node 16.12.0

```
ROR  The migrate command failed.

Package subpath './package.json' is not defined by "exports" in /tmp/tmp-132774-cJ3nZio2Rkac/node_modules/sass/package.json
/home/tur1ng/Documents/programming/zoomit/Zoomit/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /tmp/tmp-132743-sQVnvM0BLfFl/node_modules/.bin/tao migrate next
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.handler (/home/tur1ng/Documents/programming/zoomit/Zoomit/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:89:25)
    at Object.runCommand (/home/tur1ng/Documents/programming/zoomit/Zoomit/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/tur1ng/Documents/programming/zoomit/Zoomit/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/home/tur1ng/Documents/programming/zoomit/Zoomit/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/home/tur1ng/Documents/programming/zoomit/Zoomit/node_modules/@nrwl/cli/lib/init-local.js:25:79)
    at Object.<anonymous> (/home/tur1ng/Documents/programming/zoomit/Zoomit/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 132774,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
