### ISSUE TITLE
`@nrwl/react/plugins/storybook` fails with webpack5

### ISSUE THREAD

**Issue by CWSites** [nrwl/nx#7558]
## Current Behavior
When I run any of the following commands I receive an error that doesn't specify any particular file that failed to parse.

`nx run dot-components:storybook`

## Expected Behavior
This previously worked with version 12

## Steps to Reproduce
I followed all of the steps here: https://nx.dev/l/r/storybook/migrate-webpack-final and removed most of my webpack config. 

### root `main.js`
```js
module.exports = {
  features: {
    postcss: false,
  },
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-a11y',
    '@react-theming/storybook-addon',
  ],
  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
    });

    return config;
  },
};
```

### project specific `main.js`
```js
const rootMain = require('../../../.storybook/main');

module.exports = {
  ...rootMain,
  core: {
    builder: 'webpack5',
  },
  stories: [
    ...rootMain.stories,
    '../src/lib/**/*.stories.mdx',
    '../src/lib/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [...rootMain.addons, '@nrwl/react/plugins/storybook'],
  webpackFinal: async (config, { configType }) => {
    if (rootMain.webpackFinal) {
      config = await rootMain.webpackFinal(config, { configType });
    }

    return config;
  },
};
```

### Failure Logs
```
yarn storybook
yarn run v1.22.17
$ nx run dot-components:storybook

> nx run dot-components:storybook 
info => Loading presets
info => Serving static files from ./libs/dot-components/src/lib at /
info => Loading 1 config file in "/Users/mhaff/_work/dot-components/libs/dot-components/.storybook"
info => Loading 8 other files in "/Users/mhaff/_work/dot-components/libs/dot-components/.storybook"
info => Loading custom manager config
info => Adding stories defined in "/Users/mhaff/_work/dot-components/libs/dot-components/.storybook/main.js"
info => Loading custom manager config
<i> [webpack-dev-middleware] wait until bundle finished
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
assets by chunk 5.02 MiB (id hint: vendors)
  assets by status 4.64 MiB [big]
    asset vendors-node_modules_storybook_addon-actions_dist_esm_register_js-node_modules_storybook_addo-8ef9cf.manager.bundle.js 4.28 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_OverlayScrollbars_js.manager.bundle.js 372 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_syntaxhighlighter_syntaxhighlighter_js.manager.bundle.js 195 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_tooltip_WithTooltip_js.manager.bundle.js 112 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_controls_Color_js.manager.bundle.js 63.5 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_GlobalScrollAreaStyles_js.manager.bundle.js 15.7 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.1 KiB [emitted] (name: runtime~main)
asset index.html 2.46 KiB [emitted]
asset main.manager.bundle.js 2.37 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.28 KiB [emitted]
Entrypoint main [big] 4.29 MiB = runtime~main.manager.bundle.js 14.1 KiB vendors-node_modules_storybook_addon-actions_dist_esm_register_js-node_modules_storybook_addo-8ef9cf.manager.bundle.js 4.28 MiB main.manager.bundle.js 2.37 KiB
orphan modules 1.56 MiB [orphan] 343 modules
runtime modules 8.7 KiB 14 modules
javascript modules 4.48 MiB
  modules by path ./node_modules/ 4.47 MiB 832 modules
  ./libs/dot-components/.storybook/manager.js 338 bytes [built] [code generated]
  ./util.inspect (ignored) 15 bytes [built] [code generated]
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]
manager (webpack 5.61.0) compiled successfully in 12558 ms
webpack built preview 12828befdbb4c81e05c2 in 20801ms
ModuleParseError: Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:969:19)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:1088:5
    at processResult (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:793:11)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:827:15
    at Array.eval (eval at create (/Users/mhaff/_work/dot-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (/Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /Users/mhaff/_work/dot-components/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
ModuleParseError: Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:969:19)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:1088:5
    at processResult (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:793:11)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:827:15
    at Array.eval (eval at create (/Users/mhaff/_work/dot-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (/Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /Users/mhaff/_work/dot-components/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
ModuleParseError: Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:969:19)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:1088:5
    at processResult (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:793:11)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:827:15
    at Array.eval (eval at create (/Users/mhaff/_work/dot-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (/Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /Users/mhaff/_work/dot-components/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)


          Broken build, fix the error above.
          You may need to refresh the browser.
        

———————————————————————————————————————————————

>  NX   ERROR  Running target "dot-components:storybook" failed

```

### Environment

```
yarn run v1.22.17
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.11.1
  OS   : darwin x64
  yarn : 1.22.17
  
  nx : 13.1.2
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.2
  @nrwl/cypress : 13.1.2
  @nrwl/devkit : 13.1.2
  @nrwl/eslint-plugin-nx : 13.1.2
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.2
  @nrwl/linter : 13.1.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.2
  @nrwl/web : 13.1.2
  @nrwl/workspace : 13.1.2
  @nrwl/storybook : 13.1.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by CWSites** [comment]
@juristr any ideas of how to get me in the right direction here? I went through my upgrade step by step and confirmed as soon as I upgrade to `webpack@5.0.0` the `@nrwl/react/plugins/storybook` fails to start.

**Comment by CWSites** [comment]
Narrowing this down to the following. This appears to be strictly an issue with how `@nrwl` is using `storybook`. My `e2e` tests rely on having storybook up and running so if that can't happen (it can't) then my `e2e` won't work either.

This is as far as I've been able to get it. It looks like an issue with parsing a file, however I don't get any information on what file it's not able to parse. It just says "binary".

```
yarn storybook
yarn run v1.22.17
$ nx run dot-components:storybook

> nx run dot-components:storybook 
info => Loading presets
info => Serving static files from ./libs/dot-components/src/lib at /
info => Loading 1 config file in "/Users/mhaff/_work/dot-components/libs/dot-components/.storybook"
info => Loading 8 other files in "/Users/mhaff/_work/dot-components/libs/dot-components/.storybook"
info => Loading custom manager config
info => Adding stories defined in "/Users/mhaff/_work/dot-components/libs/dot-components/.storybook/main.js"
info => Loading custom manager config
<i> [webpack-dev-middleware] wait until bundle finished
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
assets by chunk 5.02 MiB (id hint: vendors)
  assets by status 4.64 MiB [big]
    asset vendors-node_modules_storybook_addon-actions_dist_esm_register_js-node_modules_storybook_addo-8ef9cf.manager.bundle.js 4.28 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_OverlayScrollbars_js.manager.bundle.js 372 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_syntaxhighlighter_syntaxhighlighter_js.manager.bundle.js 195 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_tooltip_WithTooltip_js.manager.bundle.js 112 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_controls_Color_js.manager.bundle.js 63.5 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_GlobalScrollAreaStyles_js.manager.bundle.js 15.7 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.1 KiB [emitted] (name: runtime~main)
asset index.html 2.46 KiB [emitted]
asset main.manager.bundle.js 2.37 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.28 KiB [emitted]
Entrypoint main [big] 4.29 MiB = runtime~main.manager.bundle.js 14.1 KiB vendors-node_modules_storybook_addon-actions_dist_esm_register_js-node_modules_storybook_addo-8ef9cf.manager.bundle.js 4.28 MiB main.manager.bundle.js 2.37 KiB
orphan modules 1.56 MiB [orphan] 343 modules
runtime modules 8.7 KiB 14 modules
javascript modules 4.48 MiB
  modules by path ./node_modules/ 4.47 MiB 832 modules
  ./libs/dot-components/.storybook/manager.js 338 bytes [built] [code generated]
  ./util.inspect (ignored) 15 bytes [built] [code generated]
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]
manager (webpack 5.61.0) compiled successfully in 12558 ms
webpack built preview 12828befdbb4c81e05c2 in 20801ms
ModuleParseError: Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:969:19)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:1088:5
    at processResult (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:793:11)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:827:15
    at Array.eval (eval at create (/Users/mhaff/_work/dot-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (/Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /Users/mhaff/_work/dot-components/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
ModuleParseError: Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:969:19)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:1088:5
    at processResult (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:793:11)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:827:15
    at Array.eval (eval at create (/Users/mhaff/_work/dot-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (/Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /Users/mhaff/_work/dot-components/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
ModuleParseError: Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:969:19)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:1088:5
    at processResult (/Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:793:11)
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at /Users/mhaff/_work/dot-components/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at /Users/mhaff/_work/dot-components/node_modules/webpack/lib/NormalModule.js:827:15
    at Array.eval (eval at create (/Users/mhaff/_work/dot-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (/Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /Users/mhaff/_work/dot-components/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /Users/mhaff/_work/dot-components/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)


          Broken build, fix the error above.
          You may need to refresh the browser.
        

———————————————————————————————————————————————

>  NX   ERROR  Running target "dot-components:storybook" failed
```

**Comment by juristr** [comment]
@CWSites could you setup a small Github repo where I'm able to easily reproduce the issue? 🙏  that helps a lot to speed up the debugging and fixing process :)

**Comment by CWSites** [comment]
@juristr I can, it will take a little time.

**Comment by juristr** [comment]
@CWSites have you been able to create a repro? Also, just saw you have still this loader pushed to the Webpack configuration on the global `main.js`

```js
 config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
    });
```

In theory, the React Nrwl Storybook preset adds that already, so it shouldn't be required. I wonder whether that creates the issue in your case.

**Comment by CWSites** [comment]
I had to revert some of my changes at the time of writing. I will be re-evaluating this in the next couple weeks and can give more feedback.

**Comment by CWSites** [comment]
@juristr I removed that and it's still occurring. I also disabled all plugins except for `@storybook/addon-essentials` and it's still not working. Just updated all of my `@nrwl/` libraries to latest `13.4.3` and all of my `@storybook/` libraries to latest `6.4.9`.

Is there anything else that I can share short of re-creating the entire project in a repo that I can share?

**Comment by CWSites** [comment]
I'm focusing on one part at a time. I've upgraded Storybook to `6.3.13` and I'm using Webpack `5.4.0`. Storybook is able to compile with Material UI with one exception, the Drawer component. 

This is where my instance freezes up

![Screen Shot 2022-01-24 at 3 26 29 PM](https://user-images.githubusercontent.com/1242102/150869706-0f110f8a-e976-4499-a752-de1799d01f04.png)

**Comment by CWSites** [comment]
I ended up having to update quite a bit of code to work. The primary issue that I had was the warnings were completely useless in troubleshooting.
