### ISSUE TITLE
The "path" argument must be of type string. Received undefined (After installing another app after react app)

### ISSUE THREAD

**Issue by rjvim** [nrwl/nx#7575]
## Current Behavior
I keep getting `The "path" argument must be of type string. Received undefined` error whenever I run a React App

## Expected Behavior
I am expecting the application to work

## Steps to Reproduce

0. Create empty nx workspace
1. Add React Plugin:`yarn add -D @nrwl/react`
2. Create React Application: `yarn nx g @nrwl/react:application dash --js`
3. Serve Application: `yarn nx serve dash` -> It works, stop the command
4. Add NextJS Plugin: `yarn add @nrwl/next`
5. Create NextJS application: `yarn nx g @nrwl/next:app land --js`
6. Server Next App: `yarn nx serve land` -> It works, stop the command
7. Serve React Application again: `yarn nx serve dash`
8. I get `The "path" argument must be of type string. Received undefined`
9. NextJS application works fine

Some solutions suggest to change version of "react-scripts", but Nx.Dev doesn't use it I guess?

### Failure Logs
```
> nx run dash:serve --verbose 
The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:1098:7)
    at normalizeBuildOptions (/Users/rajiv/Projects/Reusejs/stack2/node_modules/@nrwl/web/src/utils/normalize.js:10:34)
    at Object.normalizeWebBuildOptions (/Users/rajiv/Projects/Reusejs/stack2/node_modules/@nrwl/web/src/utils/normalize.js:66:44)
    at devServerExecutor_1 (/Users/rajiv/Projects/Reusejs/stack2/node_modules/@nrwl/web/src/executors/dev-server/dev-server.impl.js:17:42)
    at devServerExecutor_1.next (<anonymous>)
    at resume (/Users/rajiv/Projects/Reusejs/stack2/node_modules/tslib/tslib.js:225:48)
    at /Users/rajiv/Projects/Reusejs/stack2/node_modules/tslib/tslib.js:224:125
    at new Promise (<anonymous>)
```

### Environment

  Node : 16.7.0
  OS   : darwin arm64
  yarn : 1.22.11
  
  nx : 13.1.2
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.2
  @nrwl/cypress : 13.1.2
  @nrwl/devkit : 13.1.2
  @nrwl/eslint-plugin-nx : 13.1.2
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.2
  @nrwl/linter : 13.1.2
  @nrwl/nest : Not Found
  @nrwl/next : 13.1.2
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.2
  @nrwl/web : 13.1.2
  @nrwl/workspace : 13.1.2
  @nrwl/storybook : 13.1.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by rjvim** [comment]
I have changed commands in my project.json, to make it work with Tailwind production build. Just checked that `@nrwl/web:dev-server` needs "build" command.
