### ISSUE TITLE
ng serve gives Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mackelito** [nrwl/nx#7577]
## Steps to Reproduce
Getting the following errors when running `ng serve`

### Note
I have tried ` npm ci ` and also checked so that everything should be up to date..

### Failure Logs
````
➜  web-client git:(feat/hotfix-new-mega-menu) ng serve                         
(node:83556) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Object.filesChanged (/Users/me/Projects/web-client/node_modules/@nrwl/workspace/src/core/file-utils.js:245:24)
    at Object.createProjectGraph (/Users/me/Projects/web-client/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:21:32)
    at Object.<anonymous> (/Users/me/Projects/web-client/node_modules/@nrwl/workspace/src/command-line/run-one.js:19:46)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/me/Projects/web-client/node_modules/tslib/tslib.js:114:62)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:83556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:83556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````
### Environment

````
>  NX  Report complete - copy this into the issue template

  Node : 14.15.1
  OS   : darwin x64
  npm  : 6.14.8
  
  nx : Not Found
  @nrwl/angular : 12.3.6
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : 12.3.6
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
````

**Comment by mackelito** [comment]
Some more info:

````
➜  ecom-web-client git:(feat/hotfix-new-mega-menu) node --trace-warnings ./node_modules/@angular/cli/bin/ng serve      
(node:88593) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Object.filesChanged (/Users/me/Projects/web-client/node_modules/@nrwl/workspace/src/core/file-utils.js:245:24)
    at Object.createProjectGraph (/Users/me/Projects/web-client/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:21:32)
    at Object.<anonymous> (/Users/me/Projects/web-client/node_modules/@nrwl/workspace/src/command-line/run-one.js:19:46)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/me/Projects/web-client/node_modules/tslib/tslib.js:114:62)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:88593) TypeError: Cannot read property 'length' of undefined
    at Object.filesChanged (/Users/me/Projects/web-client/node_modules/@nrwl/workspace/src/core/file-utils.js:245:24)
    at Object.createProjectGraph (/Users/me/Projects/web-client/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:21:32)
    at Object.<anonymous> (/Users/me/Projects/web-client/node_modules/@nrwl/workspace/src/command-line/run-one.js:19:46)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/me/Projects/web-client/node_modules/tslib/tslib.js:114:62)
(node:88593) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
````

**Comment by mackelito** [comment]
For some reason.. switching node version seems to have done the trick.. not sure why...
