### ISSUE TITLE
after nx migrate latest, npm install fails

### ISSUE THREAD

**Issue by jeffschulzusc** [nrwl/nx#7636]
## Current Behavior
after nx migrate latest, npm install fails

## Expected Behavior
expect npm install to succeed

## Steps to Reproduce

going from 12->13

### Failure Logs
npm resolve report:
```
# npm resolution error report

2021-11-05T23:06:41.168Z

While resolving: vhap@0.0.0
Found: @typescript-eslint/parser@4.19.0
node_modules/@typescript-eslint/parser
  dev @typescript-eslint/parser@"4.19.0" from the root project

Could not resolve dependency:
peer @typescript-eslint/parser@"~4.33.0" from @nrwl/eslint-plugin-nx@13.1.3
node_modules/@nrwl/eslint-plugin-nx
  dev @nrwl/eslint-plugin-nx@"13.1.3" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "@typescript-eslint/parser",
    "version": "4.19.0",
    "whileInstalling": {
      "name": "vhap",
      "version": "0.0.0",
      "path": "/uscsf/fork.vhap.ws"
    },
    "location": "node_modules/@typescript-eslint/parser",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "dev",
        "name": "@typescript-eslint/parser",
        "spec": "4.19.0",
        "from": {
          "location": "/uscsf/fork.vhap.ws"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "dev",
    "name": "@typescript-eslint/parser",
    "spec": "4.19.0",
    "from": {
      "location": "/uscsf/fork.vhap.ws"
    }
  },
  "edge": {
    "type": "peer",
    "name": "@typescript-eslint/parser",
    "spec": "~4.33.0",
    "error": "INVALID",
    "from": {
      "name": "@nrwl/eslint-plugin-nx",
      "version": "13.1.3",
      "whileInstalling": {
        "name": "vhap",
        "version": "0.0.0",
        "path": "/uscsf/fork.vhap.ws"
      },
      "location": "node_modules/@nrwl/eslint-plugin-nx",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "dev",
          "name": "@nrwl/eslint-plugin-nx",
          "spec": "13.1.3",
          "from": {
            "location": "/uscsf/fork.vhap.ws"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```

npm log:
```
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
1 info using npm@7.20.0
2 info using node@v16.5.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/uscsf/fork.vhap.ws/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/jeffschulz/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:setTitle Completed in 13ms
21 timing npm:load:setupLog Completed in 2ms
22 timing npm:load:cleanupLog Completed in 1ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 25ms
26 timing config:load:flatten Completed in 2ms
27 timing arborist:ctor Completed in 1ms
28 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
29 timing idealTree:init Completed in 779ms
30 timing idealTree:userRequests Completed in 0ms
31 silly idealTree buildDeps
32 silly fetch manifest @angular/animations@12.2.13
33 http fetch GET 200 https://registry.npmjs.org/@angular%2fanimations 127ms (cache hit)
34 silly fetch manifest @angular/core@12.2.13
35 http fetch GET 200 https://registry.npmjs.org/@angular%2fcore 1027ms (cache hit)
36 silly fetch manifest rxjs@~6.5.5
37 http fetch GET 200 https://registry.npmjs.org/rxjs 4ms (cache hit)
38 silly fetch manifest zone.js@0.11.4
39 http fetch GET 200 https://registry.npmjs.org/zone.js 5ms (cache hit)
40 silly fetch manifest @angular/cdk@12.2.12
41 http fetch GET 200 https://registry.npmjs.org/@angular%2fcdk 3ms (cache hit)
42 silly fetch manifest @angular/common@12.2.13
43 http fetch GET 200 https://registry.npmjs.org/@angular%2fcommon 4ms (cache hit)
44 silly fetch manifest @angular/compiler@12.2.13
45 http fetch GET 200 https://registry.npmjs.org/@angular%2fcompiler 4ms (cache hit)
46 silly fetch manifest @angular/forms@12.2.13
47 http fetch GET 200 https://registry.npmjs.org/@angular%2fforms 4ms (cache hit)
48 silly fetch manifest @angular/platform-browser@12.2.13
49 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser 4ms (cache hit)
50 silly fetch manifest @angular/material@12.2.12
51 http fetch GET 200 https://registry.npmjs.org/@angular%2fmaterial 3ms (cache hit)
52 silly fetch manifest @angular/platform-browser-dynamic@12.2.13
53 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser-dynamic 4ms (cache hit)
54 silly fetch manifest @angular/router@12.2.13
55 http fetch GET 200 https://registry.npmjs.org/@angular%2frouter 4ms (cache hit)
56 silly fetch manifest @ngrx/effects@12.5.1
57 http fetch GET 200 https://registry.npmjs.org/@ngrx%2feffects 3ms (cache hit)
58 silly fetch manifest @ngrx/store@12.5.1
59 http fetch GET 200 https://registry.npmjs.org/@ngrx%2fstore 6ms (cache hit)
60 silly fetch manifest @ngrx/entity@12.5.1
61 http fetch GET 200 https://registry.npmjs.org/@ngrx%2fentity 3ms (cache hit)
62 silly fetch manifest @ngrx/router-store@12.5.1
63 http fetch GET 200 https://registry.npmjs.org/@ngrx%2frouter-store 4ms (cache hit)
64 silly fetch manifest @ngrx/schematics@12.5.1
65 http fetch GET 200 https://registry.npmjs.org/@ngrx%2fschematics 3ms (cache hit)
66 silly fetch manifest @ngrx/store-devtools@12.5.1
67 http fetch GET 200 https://registry.npmjs.org/@ngrx%2fstore-devtools 2ms (cache hit)
68 silly fetch manifest @nrwl/angular@13.1.3
69 http fetch GET 200 https://registry.npmjs.org/@nrwl%2fangular 8ms (cache hit)
70 silly fetch manifest @angular-devkit/build-angular@12.2.13
71 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fbuild-angular 8ms (cache hit)
72 silly fetch manifest @angular/compiler-cli@12.2.13
73 http fetch GET 200 https://registry.npmjs.org/@angular%2fcompiler-cli 8ms (cache hit)
74 silly fetch manifest typescript@4.3.5
75 http fetch GET 200 https://registry.npmjs.org/typescript 12ms (cache hit)
76 silly fetch manifest @angular/localize@^11.2.14
77 http fetch GET 200 https://registry.npmjs.org/@angular%2flocalize 506ms (cache revalidated)
78 silly fetch manifest @angular/localize@^12.0.0
79 silly fetch manifest @angular/compiler@11.2.14
80 silly fetch manifest @angular/compiler-cli@11.2.14
81 silly fetch manifest typescript@>=4.0 <4.2
82 silly fetch manifest @angular/service-worker@^12.0.0
83 http fetch GET 200 https://registry.npmjs.org/@angular%2fservice-worker 370ms (cache revalidated)
84 silly fetch manifest karma@^6.3.0
85 http fetch GET 200 https://registry.npmjs.org/karma 43ms (cache revalidated)
86 silly fetch manifest ng-packagr@^12.0.0
87 http fetch GET 200 https://registry.npmjs.org/ng-packagr 91ms (cache updated)
88 silly fetch manifest tslib@^2.3.0
89 http fetch GET 200 https://registry.npmjs.org/tslib 3ms (cache hit)
90 silly fetch manifest protractor@^7.0.0
91 http fetch GET 200 https://registry.npmjs.org/protractor 170ms (cache revalidated)
92 silly fetch manifest tailwindcss@^2.0.0
93 http fetch GET 200 https://registry.npmjs.org/tailwindcss 414ms (cache updated)
94 silly fetch manifest autoprefixer@^10.0.2
95 http fetch GET 200 https://registry.npmjs.org/autoprefixer 6ms (cache hit)
96 silly fetch manifest postcss@^8.1.0
97 http fetch GET 200 https://registry.npmjs.org/postcss 5ms (cache hit)
98 silly fetch manifest tslint@^6.1.0
99 http fetch GET 200 https://registry.npmjs.org/tslint 39ms (cache revalidated)
100 silly fetch manifest @angular-eslint/eslint-plugin@12.3.1
101 http fetch GET 200 https://registry.npmjs.org/@angular-eslint%2feslint-plugin 7ms (cache hit)
102 silly fetch manifest eslint@7.22.0
103 http fetch GET 200 https://registry.npmjs.org/eslint 5ms (cache hit)
104 silly fetch manifest @angular-eslint/eslint-plugin-template@12.3.1
105 http fetch GET 200 https://registry.npmjs.org/@angular-eslint%2feslint-plugin-template 4ms (cache hit)
106 silly fetch manifest @angular-eslint/template-parser@12.3.1
107 http fetch GET 200 https://registry.npmjs.org/@angular-eslint%2ftemplate-parser 3ms (cache hit)
108 silly fetch manifest @angular/cli@12.2.13
109 http fetch GET 200 https://registry.npmjs.org/@angular%2fcli 51ms (cache revalidated)
110 silly fetch manifest @angular/language-service@12.2.13
111 http fetch GET 200 https://registry.npmjs.org/@angular%2flanguage-service 7ms (cache hit)
112 silly fetch manifest @nrwl/cli@13.1.3
113 http fetch GET 200 https://registry.npmjs.org/@nrwl%2fcli 5ms (cache hit)
114 silly fetch manifest @nrwl/cypress@13.1.3
115 http fetch GET 200 https://registry.npmjs.org/@nrwl%2fcypress 7ms (cache hit)
116 silly fetch manifest cypress@^5.5.0
117 http fetch GET 200 https://registry.npmjs.org/cypress 45ms (cache revalidated)
118 silly fetch manifest @nrwl/eslint-plugin-nx@13.1.3
119 http fetch GET 200 https://registry.npmjs.org/@nrwl%2feslint-plugin-nx 6ms (cache hit)
120 silly fetch manifest @typescript-eslint/parser@4.19.0
121 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fparser 71ms (cache revalidated)
122 silly fetch manifest @typescript-eslint/parser@~4.33.0
123 timing idealTree Completed in 4161ms
124 timing command:install Completed in 4183ms
125 verbose stack Error: unable to resolve dependency tree
125 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1216:25)
125 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1183:34)
125 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:886:11)
125 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
125 verbose stack     at async Promise.all (index 1)
125 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
125 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:150:5)
126 verbose cwd /uscsf/fork.vhap.ws
127 verbose Darwin 17.7.0
128 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
129 verbose node v16.5.0
130 verbose npm  v7.20.0
131 error code ERESOLVE
132 error ERESOLVE unable to resolve dependency tree
133 error
134 error While resolving: [1mvhap[22m@[1m0.0.0[22m
134 error Found: [1m@typescript-eslint/parser[22m@[1m4.19.0[22m[2m[22m
134 error [2mnode_modules/@typescript-eslint/parser[22m
134 error   [33mdev[39m [1m@typescript-eslint/parser[22m@"[1m4.19.0[22m" from the root project
134 error
134 error Could not resolve dependency:
134 error [35mpeer[39m [1m@typescript-eslint/parser[22m@"[1m~4.33.0[22m" from [1m@nrwl/eslint-plugin-nx[22m@[1m13.1.3[22m[2m[22m
134 error [2mnode_modules/@nrwl/eslint-plugin-nx[22m
134 error   [33mdev[39m [1m@nrwl/eslint-plugin-nx[22m@"[1m13.1.3[22m" from the root project
134 error
134 error Fix the upstream dependency conflict, or retry
134 error this command with --force, or --legacy-peer-deps
134 error to accept an incorrect (and potentially broken) dependency resolution.
134 error
134 error See /Users/jeffschulz/.npm/eresolve-report.txt for a full report.
135 verbose exit 1
```

### Environment
```
  Node : 16.5.0
  OS   : darwin x64
  npm  : 7.20.0
  
  nx : Not Found
  @nrwl/angular : 12.3.6
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : 12.3.6
  @nrwl/next : Not Found
  @nrwl/node : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
```

**Comment by meeroslav** [comment]
Hi @jeffschulzusc, thank you for reporting the error.

Unfortunately, my attempt to reproduce it was not successful. You can see the repo here: https://github.com/meeroslav/nx-issue-7636

It's a basic angular app created with `v12.3.6` and successfully migrated to `v13.1.3`.
According to the log you provided, there seems to be an issue while installing `@typescript-eslint/parser` (going from v4.19.0 to v4.33.0).

Can you provide a minimal repo where we can see this error? Perhaps sending us the original `package.json` dependencies block would reveal potential issue.

Tip: If you want to target custom version with migration use `nx migrate 13.1.3`.

**Comment by DmitryKandratsenka** [comment]
I have the same issue:
![image](https://user-images.githubusercontent.com/74970709/143506734-e28ce198-d404-45af-a017-d41bcaa27f62.png)
![image](https://user-images.githubusercontent.com/74970709/143506752-0487c675-835b-4999-be95-f8072e0d0e1f.png)
![image](https://user-images.githubusercontent.com/74970709/143506763-845bd8fd-3eea-43ba-9954-7345791e0d65.png)

**Comment by timonohe** [comment]
Same here for the latest version 13.2.3

**Comment by ryancraigmartin** [comment]
I'm running into issues as well. After running migrate latest, running the migrations, and installing the dependencies, it throws an error asking if I've run npm install as if I had not installed my node modules.

**Comment by jeffschulzusc** [comment]
update on my end, i now have success at nx 13.3.11 ... follow three steps of mx migrate with the caveat as per below:

1. nx migrate latest
2. npm install
3. nx migrate --run-migrations
   error: nx format ..
     had to remove "projects" section in nx.json, ran nx format as per 
     https://githubmemory.com/repo/nrwl/nx/issues/7490
     then rerun nx migrate --run-migrations
