### ISSUE TITLE
nx migrate errors in yarn with any arguments

### ISSUE THREAD

**Issue by david-morris** [nrwl/nx#7662]
## Current Behavior

Running `nx migrate` with no arguments, `latest`, `12.10.0`, etc., all result in `Error: Command failed: yarn`.

## Expected Behavior

I expect migrate to initiate an update, I believe this is how I upgraded to nx 12.9.0.

## Steps to Reproduce

`nx migrate`

Unfortunately, this is happening in a corporate monorepo which has been through a lot.  I'll be active to respond to any requests for more information.

### Failure Logs

```
root ➜ /workspaces/react (feature/DEV-2057-upgrade-nextjs-12-try-2) $ nx migrate latest
/workspaces/react/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15)
    at taoPath (/workspaces/react/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:340:21)
    at Object.handler (/workspaces/react/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:96:19)
    at Object.runCommand (/workspaces/react/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/workspaces/react/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/workspaces/react/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/workspaces/react/node_modules/@nrwl/cli/lib/init-local.js:25:79)
    at Object.<anonymous> (/workspaces/react/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (/usr/local/share/.config/yarn/global/node_modules/v8-compile-cache/v8-compile-cache.js:192:30) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 6976,
  stdout: null,
  stderr: null
}
```
### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 16.3.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : 12.9.0
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

I've tried with `yarn` version 1.22.5 and 1.22.15.

**Comment by Lavhe** [comment]
Any solution to this problem?

I am also facing this problem

**Comment by david-morris** [comment]
> 
> 
> Any solution to this problem?
> 
> I am also facing this problem

I've updated by manually changing my `package.json` and running `yarn install`, and then invoking `nx format` myself.

**Comment by AgentEnder** [comment]
Hey are you using any packages from a nonstandard registry? `nx migrate` works by fetching the new versions in a temporary folder first, to see what migrations those packages has. It uses whatever package manager your repo uses to do this. 

In your case, it seems Nx is picking up `yarn` as the installation command, but it fails in the temporary folder for some reason.

**Comment by david-morris** [comment]
@AgentEnder, if I understand your question correctly, you're asking if I've configured `yarn` to install packages not in the node package registry?  To my knowledge, all packages we use are either in the node package registry or are part of the registry, managed by nx.  Would my `package.json` answer your question?  Here it is, after I've manually run this update.

```
{
  "name": CENSORED,
  "version": "0.0.0",
  "private": true,
  "license": CENSORED,
  "scripts": {
    "gen:theme-typings": "npx @chakra-ui/cli tokens libs/theme/src/index.ts",
    "nx": "nx",
    "start": "nx serve",
    "build": "nx build",
    "test-all": "nx run-many --all --target=test",
    "test": "nx test",
    "type-check": "nx run-many --all --target=type-check",
    "lint": "nx workspace-lint && nx lint",
    "e2e": "nx e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint-fix": "nx affected:lint --fix",
    "affected:format-fix": "nx format:write",
    "affected:type-check": "nx affected --target=type-check",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-generator": "nx workspace-generator",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "storybook": "STORYBOOK_DEV=true start-storybook -p 6006 -s .storybook/public",
    "generate-gql-types": "graphql-codegen --config codegen.yml",
    "download-schema": "if [ \"$VERCEL_ENV\" != \"development\" ] && [ \"$VERCEL_ENV\" != \"preview\" ]; then get-graphql-schema ${NEXT_PUBLIC_API_URL:-http://django:8000} > libs/graphql/src/schema.graphql; else echo \"Skip downloading schema\"; fi ",
    "prepare": "husky install",
    "postinstall": "yarn gen:theme-typings && yarn generate-gql-types"
  },
  "dependencies": {
    "@apollo/client": "^3.4.16",
    "@chakra-ui/icons": "^1.0.13",
    "@chakra-ui/react": "^1.6.3",
    "@emotion/css": "^11.1.3",
    "@emotion/react": "^11.1.4",
    "@emotion/styled": "^11.0.0",
    "@hookform/error-message": "^2.0.0",
    "@hookform/resolvers": "^2.4.0",
    "@mapbox/mapbox-gl-language": "^1.0.0",
    "@notionhq/client": "^0.2.4",
    "@turf/turf": "^6.5.0",
    "apollo-server": "^2.20.0",
    "apollo-server-micro": "^2.20.0",
    "casual": "^1.6.2",
    "core-js": "^3.6.5",
    "date-fns": "^2.23.0",
    "document-register-element": "1.13.1",
    "downshift": "^6.1.0",
    "framer-motion": "^3.2.2-rc.1",
    "i18next": "^19.8.7",
    "jsonwebtoken": "^8.5.1",
    "msw": "^0.26.0",
    "next": "^12.0.1",
    "next-router-mock": "^0.5.2",
    "overmind": "^28.0.0",
    "overmind-react": "^29.0.0",
    "react": "^17.0.2",
    "react-datepicker": "^4.2.0",
    "react-dom": "^17.0.2",
    "react-hook-form": "^7.15.4",
    "react-i18next": "^11.8.5",
    "react-icons": "^4.2.0",
    "react-json-pretty": "^2.2.0",
    "react-map-gl": "^6.1.17",
    "react-table": "^7.6.3",
    "regenerator-runtime": "0.13.7",
    "supercluster": "^7.1.4",
    "tslib": "^2.0.0",
    "use-supercluster": "^0.3.0",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/plugin-transform-runtime": "^7.13.15",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-react": "7.9.4",
    "@babel/preset-typescript": "7.9.0",
    "@chakra-ui/cli": "^1.4.0",
    "@graphql-codegen/cli": "^1.19.4",
    "@graphql-codegen/import-types-preset": "^1.18.1",
    "@graphql-codegen/introspection": "^1.18.1",
    "@graphql-codegen/near-operation-file-preset": "^1.17.13",
    "@graphql-codegen/typescript": "^1.19.0",
    "@graphql-codegen/typescript-operations": "^1.17.12",
    "@graphql-codegen/typescript-react-apollo": "^2.2.1",
    "@graphql-codegen/typescript-resolvers": "^1.18.0",
    "@hookform/devtools": "^3.1.0",
    "@next/eslint-plugin-next": "^11.0.1",
    "@nrwl/cli": "^13.0.0",
    "@nrwl/eslint-plugin-nx": "^13.0.0",
    "@nrwl/jest": "^13.0.0",
    "@nrwl/linter": "^13.0.0",
    "@nrwl/next": "^13.0.0",
    "@nrwl/react": "^13.0.0",
    "@nrwl/tao": "^13.0.0",
    "@nrwl/web": "^13.0.0",
    "@nrwl/workspace": "^13.0.0",
    "@storybook/addon-actions": "^6.3.4",
    "@storybook/addon-essentials": "^6.3.4",
    "@storybook/addon-links": "^6.3.4",
    "@storybook/builder-webpack5": "^6.3.4",
    "@storybook/react": "^6.3.4",
    "@swc/core": "^1.2.106",
    "@swc/jest": "^0.2.5",
    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.3",
    "@testing-library/user-event": "^12.6.2",
    "@types/jest": "^26.0.20",
    "@types/node": "^14.14.22",
    "@types/react": "^17.0.14",
    "@types/react-dom": "^17.0.9",
    "@types/react-table": "^7.0.28",
    "@typescript-eslint/eslint-plugin": "^4.14.1",
    "@typescript-eslint/parser": "^4.14.1",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.2.2",
    "check": "^1.0.0",
    "eslint": "^7.19.0",
    "eslint-config-next": "^11.0.1",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jest-dom": "^3.6.5",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-mdx": "^1.12.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-testing-library": "^3.10.1",
    "get-graphql-schema": "^2.1.2",
    "husky": "^7.0.0",
    "jest": "^27.0.6",
    "jest-fetch-mock": "^3.0.3",
    "jest-transform-graphql": "^2.1.0",
    "jest-watch-typeahead": "^0.6.1",
    "lint-staged": "^10.5.3",
    "mutation-observer": "^1.0.3",
    "npm": "^6.14.11",
    "prettier": "^2.2.1",
    "storybook-dark-mode": "^1.0.8",
    "ts-jest": "^27.0.0",
    "tsconfig-paths-webpack-plugin": "^3.5.1",
    "typescript": "^4.3.5",
    "webpack": "^5.45.1",
    "whatwg-fetch": "^3.5.0",
    "wildcard-mock-link": "^2.0.2",
    "graphql": "^15.0.0"
  },
  "lint-staged": {
    "**/*.{ts,tsx,js,jsx}": [
      "npx --prefix /workspaces/react/node_modules/@nrwl/workspace/node_modules eslint --fix",
      "npx --prefix /workspaces/react/node_modules/@nrwl/workspace/node_modules prettier -w",
      "git add"
    ]
  }
}
```

**Comment by AgentEnder** [comment]
Do you care to check if this still occurs on node 14.x.x? I've not ran into this and am strugglign to reproduce.

**Comment by MaxSassen** [comment]
I've got the same issue:
Migrating NX from 12 to Latest
Running Node version: 16.4.0

        git:(master) nx migrate latest
        /Users/xxx/Projects/xxx/xxx-solution/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                        throw err;
                        ^

        Error: Command failed: yarn
            at checkExecSyncError (node:child_process:826:11)
            at Object.execSync (node:child_process:900:15)
            at taoPath (/Users/xxx/Projects/xxx/xxx-solution/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:324:21)
            at Object.handler (/Users/xxx/Projects/xxx/xxx-solution/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:88:19)
            at Object.runCommand (/Users/xxx/Projects/xxx/xxx-solution/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
            at Object.parseArgs [as _parseArgs] (/Users/xxx/Projects/xxx/xxx-solution/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
            at Object.get [as argv] (/Users/xxx/Projects/xxx/xxx-solution/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
            at Object.initLocal (/Users/xxx/Projects/xxx/xxx-solution/node_modules/@nrwl/cli/lib/init-local.js:25:79)
            at Object.<anonymous> (/Users/xxx/Projects/xxx/xxx-solution/node_modules/@nrwl/cli/bin/nx.js:43:18)
            at Module._compile (/usr/local/lib/node_modules/nx/node_modules/v8-compile-cache/v8-compile-cache.js:192:30) {
          status: 1,
          signal: null,
          output: [ null, null, null ],
          pid: 86408,
          stdout: null,
          stderr: null
        }

**Comment by AgentEnder** [comment]
@MaxSassen @david-morris It looks like the portion here that fails is when we are setting up a copy of the newest NX CLI for use w/ running migrations. If you run with `NX_MIGRATE_USE_LOCAL=true nx migrate` do you get further?

**Comment by MaxSassen** [comment]
@AgentEnder Thanks for your response, it seems to work with `NX_MIGRATE_USE_LOCAL=true nx migrate latest` weird enough is that i've tried this yesterday but it didn't work... 
But thanks!

**Comment by hbj** [comment]
Having the exact same issue with this config:
- Mac OS Big Sur 11.6
- Node v12.18.4
- Yarn 1.22.11
- Nx packages 13.1.3 (same with 13.1.4)

`NX_MIGRATE_USE_LOCAL=true yarn nx migrate latest` works.

**Comment by AgentEnder** [comment]
@hbj @MaxSassen Do either of you have a .npmrc file at workspace root? Trying to narrow down why the fetch fails for @nrwl/tao, but not during the actual migration.

**Comment by hbj** [comment]
@AgentEnder I don't have one.

Here are the configs of `yarn` and `npm` in case it's helpful:

`yarn config list` from the workspace root:

```
yarn config v1.22.11
info yarn config
{
  'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.22.11 npm/? node/v12.18.4 darwin x64',
  lastUpdateCheck: 1636699469544
}
info npm config
{}
```

`npm config ls -l` from the workspace root:

```
; "default" config from default values

_auth = (protected)
access = null
all = false
allow-same-version = false
also = null
audit = true
audit-level = null
auth-type = "legacy"
before = null
bin-links = true
browser = null
ca = null
cache = "/Users/haykel/.npm"
cache-max = null
cache-min = 0
cafile = null
call = ""
cert = null
ci-name = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
diff = []
diff-dst-prefix = "b/"
diff-ignore-all-space = false
diff-name-only = false
diff-no-prefix = false
diff-src-prefix = "a/"
diff-text = false
diff-unified = 3
dry-run = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
fetch-timeout = 300000
force = false
foreground-scripts = false
format-package-lock = true
fund = true
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/Users/haykel/.nvm/versions/node/v12.18.4/etc/npmrc"
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
include = []
include-staged = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/Users/haykel/.npm-init.js"
init-version = "1.0.0"
init.author.email = ""
init.author.name = ""
init.author.url = ""
init.license = "ISC"
init.module = "/Users/haykel/.npm-init.js"
init.version = "1.0.0"
json = false
key = null
legacy-bundling = false
legacy-peer-deps = false
link = false
local-address = null
location = "user"
loglevel = "notice"
logs-max = 10
; long = false ; overridden by cli
maxsockets = 15
message = "%s"
metrics-registry = "https://registry.npmjs.org/"
node-options = null
node-version = "v12.18.4"
noproxy = [""]
npm-version = "7.24.0"
offline = false
omit = []
only = null
optional = null
otp = null
pack-destination = "."
package = []
package-lock = true
package-lock-only = false
parseable = false
prefer-offline = false
prefer-online = false
prefix = "/Users/haykel/.nvm/versions/node/v12.18.4"
preid = ""
production = null
progress = true
proxy = null
read-only = false
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-peer = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
searchexclude = ""
searchlimit = 20
searchopts = ""
searchstaleness = 900
shell = "/bin/bash"
shrinkwrap = true
sign-git-commit = false
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-peer-deps = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "/var/folders/p7/x2xx1t816rz3knyyzv2__kv00000gn/T"
umask = 0
unicode = true
update-notifier = true
usage = false
user-agent = "npm/{npm-version} node/{node-version} {platform} {arch} workspaces/{workspaces} {ci}"
userconfig = "/Users/haykel/.npmrc"
version = false
versions = false
viewer = "man"
which = null
workspace = []
workspaces = false
yes = null

; "cli" config from command line options

long = true
```

**Comment by MaxSassen** [comment]
> npmrc

Hi @AgentEnder , we don't have that file in our workspace

**Comment by david-morris** [comment]
```
 $ export NX_MIGRATE_USE_LOCAL=true
 $ nx migrate
yarn run v1.22.5
$ /workspaces/react/node_modules/.bin/tao migrate
Provide the correct package name and version. E.g., @nrwl/workspace@9.0.0.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/workspaces/react/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn tao migrate 
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15)
    at Object.handler (/workspaces/react/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:120:25)
    at Object.runCommand (/workspaces/react/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/workspaces/react/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/workspaces/react/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/workspaces/react/node_modules/@nrwl/cli/lib/init-local.js:28:79)
    at Object.<anonymous> (/workspaces/react/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (/usr/local/share/.config/yarn/global/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1680,
  stdout: null,
  stderr: null
}
```

I'd like to note, we have our `nx` installed in our container's `devcontainer.json`:
```
$ which nx
/usr/local/share/npm-global/bin/nx
```
```
...
  "postCreateCommand": "yarn global add nx@^13.1.0 && yarn install"
...
```

**Comment by AgentEnder** [comment]
@david-morris In this case it looks like `latest` is not being inferred. Try `nx migrate latest` instead of just `nx migrate`

**Comment by david-morris** [comment]
@AgentEnder That ran and changed the package.json and migrations.json!  I will try to make time to actually run the update later in the week.

Which of these steps are workarounds and which of these steps are needed user configuration?

**Comment by hbj** [comment]
@AgentEnder any updates on this?
