### ISSUE TITLE
Storybook won't run after migrate (next)

### ISSUE THREAD

**Issue by nidomiro** [nrwl/nx#7694]
## Current Behavior
After running `yarn nx migrate latest` storybook doesn't work anymore

## Expected Behavior
storybook starts normally

## Steps to Reproduce
1. check out commit https://github.com/nidomiro/nx-storybook-bug-showcase/commit/bf2121feb6e88e888514d84a76fe1b14199488dd
2. run `yarn`
3. run `yarn nx migrate latest`
4. run `yarn`
5. run `yarn nx migrate --run-migrations`
6. run `yarn nx run nx-storybook-bug-showcase-app:storybook`

Steps 3 to 5 can be omitted by checking out https://github.com/nidomiro/nx-storybook-bug-showcase/commit/aad6d0c94f293c850e088c931441d15745ab1fbd

The problem, as far as I got, is https://github.com/nrwl/nx/blob/e818f61806ea5c28a3282e15f4dab24a3b1dcb32/packages/next/src/migrations/update-13-1-1/enable-swc.ts#L27 as it removes `.babelrc` of my next app. If I restore the file storybook works as expected.

### Failure Logs
```shell
yarn nx run nx-storybook-bug-showcase-app:storybook
yarn run v1.22.17
$ nx run nx-storybook-bug-showcase-app:storybook

> nx run nx-storybook-bug-showcase-app:storybook 
info => Loading presets
info => Loading 1 config file in "/path/to/workspace/nx-storybook-bug-showcase/apps/nx-storybook-bug-showcase-app/.storybook"
info => Loading 8 other files in "/path/to/workspace/nx-storybook-bug-showcase/apps/nx-storybook-bug-showcase-app/.storybook"
info => Adding stories defined in "/path/to/workspace/nx-storybook-bug-showcase/apps/nx-storybook-bug-showcase-app/.storybook/main.js"
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
<i> [webpack-dev-middleware] wait until bundle finished
assets by chunk 5.12 MiB (id hint: vendors)
  assets by status 4.75 MiB [big]
    asset vendors-node_modules_storybook_addon-actions_dist_esm_register_js-node_modules_storybook_addo-8ef9cf.manager.bundle.js 4.38 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_ui_node_modules_storybook_components_dist_esm_ScrollArea_Overl-dcb01a.manager.bundle.js 372 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_ui_node_modules_storybook_components_dist_esm_syntaxhighlighte-d3ae8f.manager.bundle.js 194 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_ui_node_modules_storybook_components_dist_esm_tooltip_WithTooltip_js.manager.bundle.js 113 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_ui_node_modules_storybook_components_dist_esm_controls_Color_js.manager.bundle.js 63.9 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_ui_node_modules_storybook_components_dist_esm_ScrollArea_Globa-dbae17.manager.bundle.js 15.8 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.1 KiB [emitted] (name: runtime~main)
asset index.html 2.46 KiB [emitted]
asset main.manager.bundle.js 1.49 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.3 KiB [emitted]
Entrypoint main [big] 4.4 MiB = runtime~main.manager.bundle.js 14.1 KiB vendors-node_modules_storybook_addon-actions_dist_esm_register_js-node_modules_storybook_addo-8ef9cf.manager.bundle.js 4.38 MiB main.manager.bundle.js 1.49 KiB
orphan modules 1.6 MiB [orphan] 341 modules
runtime modules 8.73 KiB 14 modules
javascript modules 4.57 MiB 870 modules
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]
manager (webpack 5.59.1) compiled successfully in 11103 ms
webpack built preview 1ea51dd6ee5c804fc6ff in 13507ms
ModuleBuildError: Module build failed (from ./node_modules/@nrwl/web/src/utils/web-babel-loader.js):
SyntaxError: /path/to/workspace/nx-storybook-bug-showcase/apps/nx-storybook-bug-showcase-app/pages/Button.tsx: Unexpected reserved word 'interface'. (3:0)

  1 | import { MouseEvent } from 'react';
  2 |
> 3 | interface Props {
    | ^
  4 |   label: string;
  5 |   onClick: (event: MouseEvent) => void;
  6 | }
    at Parser._raise (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:510:17)
    at Parser.raiseWithData (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:503:17)
    at Parser.raise (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:464:17)
    at Parser.checkReservedWord (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:12541:12)
    at Parser.parseIdentifierName (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:12495:12)
    at Parser.parseIdentifier (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:12467:23)
    at Parser.parseExprAtom (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:11486:27)
    at Parser.parseExprSubscripts (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:11217:23)
    at Parser.parseUpdate (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:11197:21)
    at Parser.parseMaybeUnary (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:11172:23)
    at Parser.parseMaybeUnaryOrPrivate (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:10986:59)
    at Parser.parseExprOps (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:10993:23)
    at Parser.parseMaybeConditional (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:10963:23)
    at Parser.parseMaybeAssign (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:10926:21)
    at Parser.parseExpressionBase (/path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:10866:23)
    at /path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/node_modules/@babel/parser/lib/index.js:10860:39
    at processResult (/path/to/workspace/nx-storybook-bug-showcase/node_modules/webpack/lib/NormalModule.js:748:19)
    at /path/to/workspace/nx-storybook-bug-showcase/node_modules/webpack/lib/NormalModule.js:847:5
    at /path/to/workspace/nx-storybook-bug-showcase/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /path/to/workspace/nx-storybook-bug-showcase/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/path/to/workspace/nx-storybook-bug-showcase/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /path/to/workspace/nx-storybook-bug-showcase/node_modules/@nrwl/web/node_modules/babel-loader/lib/index.js:59:103


          Broken build, fix the error above.
          You may need to refresh the browser.
        

———————————————————————————————————————————————

>  NX   ERROR  Running target "nx-storybook-bug-showcase-app:storybook" failed

  Failed tasks:
  
  - nx-storybook-bug-showcase-app:storybook
  
  Hint: run the command with --verbose for more details.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment
```shell
$ yarn nx report
yarn run v1.22.17
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.17.3
  OS   : linux x64
  yarn : 1.22.17
  
  nx : 13.1.3
  @nrwl/angular : Not Found
  @nrwl/cli : 13.1.3
  @nrwl/cypress : 13.1.3
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : 13.1.3
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.3
  @nrwl/linter : 13.1.3
  @nrwl/nest : 13.1.3
  @nrwl/next : 13.1.3
  @nrwl/node : 13.1.3
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.1.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.3
  @nrwl/web : 13.1.3
  @nrwl/workspace : 13.1.3
  @nrwl/storybook : 13.1.3
  @nrwl/gatsby : Not Found
  typescript : 4.4.3

Done in 0.32s.
```

**Comment by amosbastian** [comment]
I am getting the same problem after one of my other [issues](https://github.com/nrwl/nx/issues/7640#event-5677970007) was fixed.

### Failure Logs

```
info => Loading presets
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
<i> [webpack-dev-middleware] wait until bundle finished
assets by chunk 5.15 MiB (id hint: vendors)
  assets by status 4.77 MiB [big]
    asset vendors-node_modules_storybook_addon-a11y_dist_esm_register_js-node_modules_storybook_addon-a-bdcdc3.manager.bundle.js 4.4 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_OverlayScrollbars_js.manager.bundle.js 372 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_syntaxhighlighter_syntaxhighlighter_js.manager.bundle.js 195 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_tooltip_WithTooltip_js.manager.bundle.js 115 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_controls_Color_js.manager.bundle.js 72.6 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_GlobalScrollAreaStyles_js.manager.bundle.js 15.7 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.1 KiB [emitted] (name: runtime~main)
asset index.html 2.62 KiB [emitted]
asset main.manager.bundle.js 2.4 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.28 KiB [emitted]
Entrypoint main [big] 4.42 MiB = runtime~main.manager.bundle.js 14.1 KiB vendors-node_modules_storybook_addon-a11y_dist_esm_register_js-node_modules_storybook_addon-a-bdcdc3.manager.bundle.js 4.4 MiB main.manager.bundle.js 2.4 KiB
orphan modules 1.56 MiB [orphan] 334 modules
runtime modules 8.69 KiB 14 modules
javascript modules 4.58 MiB
  modules by path ./node_modules/ 4.58 MiB 828 modules
  ./libs/shared/storybook/.storybook/generated-refs.js 299 bytes [built] [code generated]
  ./util.inspect (ignored) 15 bytes [built] [code generated]
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]
manager (webpack 5.64.4) compiled successfully in 10720 ms
webpack built preview 688f8dbf223c7e96e178 in 12720ms
ModuleBuildError: Module build failed (from ./node_modules/@nrwl/web/src/utils/web-babel-loader.js):
SyntaxError: /Users/amosbastian/Development/boilerplate/libs/shared/storybook/.storybook/preview.js: Support for the experimental syntax 'jsx' isn't currently enabled (61:5):

  59 |
  60 |   return (
> 61 |     <IconButton
     |     ^
  62 |       position="absolute"
  63 |       size="md"
  64 |       fontSize="lg"

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
    at Parser._raise (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:541:17)
    at Parser.raiseWithData (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:534:17)
    at Parser.expectOnePlugin (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:3595:18)
    at Parser.parseExprAtom (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11981:18)
    at Parser.parseExprSubscripts (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11584:23)
    at Parser.parseUpdate (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11564:21)
    at Parser.parseMaybeUnary (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11539:23)
    at Parser.parseMaybeUnaryOrPrivate (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11353:61)
    at Parser.parseExprOps (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11360:23)
    at Parser.parseMaybeConditional (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11330:23)
    at Parser.parseMaybeAssign (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11290:21)
    at /Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11248:39
    at Parser.allowInAnd (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:13137:12)
    at Parser.parseMaybeAssignAllowIn (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11248:17)
    at Parser.parseParenAndDistinguishExpression (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:12294:28)
    at Parser.parseExprAtom (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11891:23)
    at processResult (/Users/amosbastian/Development/boilerplate/node_modules/webpack/lib/NormalModule.js:751:19)
    at /Users/amosbastian/Development/boilerplate/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/amosbastian/Development/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/amosbastian/Development/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/amosbastian/Development/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/amosbastian/Development/boilerplate/node_modules/babel-loader/lib/index.js:59:103


          Broken build, fix the error above.
          You may need to refresh the browser.
 ```
 
 ## Steps to reproduce
 
https://github.com/amosbastian/boilerplate/tree/feature/storybook

nx serve shared-storybook:storybook
 
 ### Environment
 
 ```
  Node : 14.16.1
  OS   : darwin x64
  npm  : 7.20.5

  nx : 13.2.3
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.3
  @nrwl/cypress : 13.2.3
  @nrwl/devkit : 13.2.3
  @nrwl/eslint-plugin-nx : 13.2.3
  @nrwl/express : 13.2.3
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : undefined
  @nrwl/next : 13.2.3
  @nrwl/node : 13.2.3
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.2.3
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : 13.2.3
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : 13.2.3
  @nrwl/gatsby : undefined
  typescript : 4.5.2
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
  ```

**Comment by amosbastian** [comment]
I am getting the same problem after one of my other [issues](https://github.com/nrwl/nx/issues/7640#event-5677970007) was fixed.

### Failure Logs

```
info => Loading presets
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
<i> [webpack-dev-middleware] wait until bundle finished
assets by chunk 5.15 MiB (id hint: vendors)
  assets by status 4.77 MiB [big]
    asset vendors-node_modules_storybook_addon-a11y_dist_esm_register_js-node_modules_storybook_addon-a-bdcdc3.manager.bundle.js 4.4 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_OverlayScrollbars_js.manager.bundle.js 372 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_syntaxhighlighter_syntaxhighlighter_js.manager.bundle.js 195 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_tooltip_WithTooltip_js.manager.bundle.js 115 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_controls_Color_js.manager.bundle.js 72.6 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_GlobalScrollAreaStyles_js.manager.bundle.js 15.7 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.1 KiB [emitted] (name: runtime~main)
asset index.html 2.62 KiB [emitted]
asset main.manager.bundle.js 2.4 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.28 KiB [emitted]
Entrypoint main [big] 4.42 MiB = runtime~main.manager.bundle.js 14.1 KiB vendors-node_modules_storybook_addon-a11y_dist_esm_register_js-node_modules_storybook_addon-a-bdcdc3.manager.bundle.js 4.4 MiB main.manager.bundle.js 2.4 KiB
orphan modules 1.56 MiB [orphan] 334 modules
runtime modules 8.69 KiB 14 modules
javascript modules 4.58 MiB
  modules by path ./node_modules/ 4.58 MiB 828 modules
  ./libs/shared/storybook/.storybook/generated-refs.js 299 bytes [built] [code generated]
  ./util.inspect (ignored) 15 bytes [built] [code generated]
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]
manager (webpack 5.64.4) compiled successfully in 10720 ms
webpack built preview 688f8dbf223c7e96e178 in 12720ms
ModuleBuildError: Module build failed (from ./node_modules/@nrwl/web/src/utils/web-babel-loader.js):
SyntaxError: /Users/amosbastian/Development/boilerplate/libs/shared/storybook/.storybook/preview.js: Support for the experimental syntax 'jsx' isn't currently enabled (61:5):

  59 |
  60 |   return (
> 61 |     <IconButton
     |     ^
  62 |       position="absolute"
  63 |       size="md"
  64 |       fontSize="lg"

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
    at Parser._raise (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:541:17)
    at Parser.raiseWithData (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:534:17)
    at Parser.expectOnePlugin (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:3595:18)
    at Parser.parseExprAtom (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11981:18)
    at Parser.parseExprSubscripts (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11584:23)
    at Parser.parseUpdate (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11564:21)
    at Parser.parseMaybeUnary (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11539:23)
    at Parser.parseMaybeUnaryOrPrivate (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11353:61)
    at Parser.parseExprOps (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11360:23)
    at Parser.parseMaybeConditional (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11330:23)
    at Parser.parseMaybeAssign (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11290:21)
    at /Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11248:39
    at Parser.allowInAnd (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:13137:12)
    at Parser.parseMaybeAssignAllowIn (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11248:17)
    at Parser.parseParenAndDistinguishExpression (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:12294:28)
    at Parser.parseExprAtom (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11891:23)
    at processResult (/Users/amosbastian/Development/boilerplate/node_modules/webpack/lib/NormalModule.js:751:19)
    at /Users/amosbastian/Development/boilerplate/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/amosbastian/Development/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/amosbastian/Development/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/amosbastian/Development/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/amosbastian/Development/boilerplate/node_modules/babel-loader/lib/index.js:59:103


          Broken build, fix the error above.
          You may need to refresh the browser.
 ```
 
 ## Steps to reproduce
 
https://github.com/amosbastian/boilerplate/tree/feature/storybook

nx serve shared-storybook:storybook
 
 ### Environment
 
 ```
  Node : 14.16.1
  OS   : darwin x64
  npm  : 7.20.5

  nx : 13.2.3
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.3
  @nrwl/cypress : 13.2.3
  @nrwl/devkit : 13.2.3
  @nrwl/eslint-plugin-nx : 13.2.3
  @nrwl/express : 13.2.3
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : undefined
  @nrwl/next : 13.2.3
  @nrwl/node : 13.2.3
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.2.3
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : 13.2.3
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : 13.2.3
  @nrwl/gatsby : undefined
  typescript : 4.5.2
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
  ```

**Comment by kirjai** [comment]
thanks for opening the issue @nidomiro , and for an update @amosbastian .

looks like we jumped the gun a bit on our swc migration, without taking storybook setups into consieration. we'll keep working on in, so in the meantime we've disabled that migration. so hopefully it shouldn't affect any more users going forward. but for those that have already migrated, please read below:

#### IMPORTANT. for anyone stumbling upon this issue in the meantime - you'd need to restore your `.babelrc` file, as previous comments suggest, in order to fix the storybook setup.
