### ISSUE TITLE
ng eject command is not working after using this to setup new project

### ISSUE THREAD

**Issue by mlakmal** [nrwl/nx#77]
when running ng eject command give below error.

`
Cannot read property 'root' of undefined
TypeError: Cannot read property 'root' of undefined
    at Class.run (/Users/xyz/stash/cli-test/test-ui/node_modules/@angular/cli/tasks/eject.js:436:64)
    at Class.run (/Users/xyz/stash/cli-test/test-ui/node_modules/@angular/cli/commands/eject.js:34:26)
    at resolve (/Users/xyz/stash/cli-test/test-ui/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at Promise (<anonymous>)
    at Class.validateAndRun (/Users/xyz/stash/cli-test/test-ui/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/Users/xyz/stash/cli-test/test-ui/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)
    at <anonymous>
`

**Comment by vsavkin** [comment]
eject isn't currently supported. We should definitely make it work though.

**Comment by emilio-martinez** [comment]
Is this still an issue? I've had no problems running `ng eject`.

**Comment by SwamyKottur** [comment]
@vsavkin I didn't had any problems as well but, since the ng eject with Angular v5 is adding AngularCompilerPlugin replacing the exisiting AOTPlugin and this is compiling all typescript files under apps even thought the right app path is specified in entryPath and module (eg. apps/my-app/src). In dist folder under my-app i am seeing other lazy loaded module chuck files which are not part of this app but the other apps inside apps folder. Any help in this regards is greatly appreciated.

**Comment by bcabanes** [comment]
Hi!

Closing this old issue cause `ng eject` is now deprecated and will be soon removed from AngularCLI.
