### ISSUE TITLE
Error "Cannot convert undefined or null to object" when migrating workspace to 13.2.0-beta.3/4/5

### ISSUE THREAD

**Issue by tFaster** [nrwl/nx#7718]
I hope this issue helps to release a stable Nx 13.2

## Current Behavior
When trying to migrate my Nx workspace from version 13.1.4 to 13.2.0-beta.5 I get the error "Cannot convert undefined or null to object" when calling run-migrations.
I tried with beta 3, 4, and 5

## Expected Behavior
No error when calling run-migrations

## Steps to Reproduce
Prior to this migraton my angular.json was transformed with your tool and has version "2". The individual apps and libs have their own project.json 

Run 
```
nx migrate 13.2.0-beta.5
nx migrate --run-migrations
```

the first command runs smoothly, the second fails.

### Failure Logs
```
>  NX  Running migrations from 'migrations.json'

Running migration update-angular-config
Cannot convert undefined or null to object
D:\Git\MY_PROJECT\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\MY_USER\AppData\Local\Temp\tmp-18540-27oXir6Mqkju\node_modules\.bin\tao migrate --run-migrations
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.handler (D:\Git\MY_PROJECT\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:114:25)
    at Object.runCommand (D:\Git\MY_PROJECT\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (D:\Git\MY_PROJECT\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (D:\Git\MY_PROJECT\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (D:\Git\MY_PROJECT\node_modules\@nrwl\cli\lib\init-local.js:28:79)
    at Object.<anonymous> (D:\Git\MY_PROJECT\node_modules\@nrwl\cli\bin\nx.js:43:18)
    at Module._compile (C:\Users\MY_USER\AppData\Roaming\nvm\v16.13.0\node_modules\nx\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10024,
  stdout: null,
  stderr: null
}
```

### Environment
Windows 10, NodeJS 14.18.0 and 16.13.0 (tried both)

**Comment by tFaster** [comment]
Hi again,

unfortunately I still get a similar error when doing a fresh migration from nx 13.1.4 to 13.2.0.rc.0.
Although it now gets past 'running migration update-angular-config' it now fails in 'update-libraries:

```
nx migrate 13.2.0-rc.0
nx migrate --run-migrations
```

```
>  NX  Running migrations from 'migrations.json'

Running migration update-angular-config
Successfully finished update-angular-config
---------------------------------------------------------
Running migration update-libraries
Cannot convert undefined or null to object
D:\Git\opr-html\opr-ngx\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\schnelle\AppData\Local\Temp\tmp-25224-4GDi8gVQWnpB\node_modules\.bin\tao migrate --run-migrations
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.handler (D:\Git\opr-html\opr-ngx\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:114:25)
    at Object.runCommand (D:\Git\opr-html\opr-ngx\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (D:\Git\opr-html\opr-ngx\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (D:\Git\opr-html\opr-ngx\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (D:\Git\opr-html\opr-ngx\node_modules\@nrwl\cli\lib\init-local.js:28:79)
    at Object.<anonymous> (D:\Git\opr-html\opr-ngx\node_modules\@nrwl\cli\bin\nx.js:43:18)
    at Module._compile (C:\Users\schnelle\AppData\Roaming\nvm\v16.13.0\node_modules\nx\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 26428,
  stdout: null,
  stderr: null
}
```

Nx report:

```
Node : 16.13.0
  OS   : win32 x64
  npm  : 8.1.0

  nx : 13.2.0-rc.0
  @nrwl/angular : 13.2.0-rc.0
  @nrwl/cli : 13.2.0-rc.0
  @nrwl/cypress : 13.2.0-rc.0
  @nrwl/devkit : 13.2.0-rc.0
  @nrwl/eslint-plugin-nx : 13.2.0-rc.0
  @nrwl/express : 13.2.0-rc.0
  @nrwl/jest : 13.2.0-rc.0
  @nrwl/linter : 13.2.0-rc.0
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.2.0-rc.0
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.0-rc.0
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.0-rc.0
  @nrwl/storybook : 13.2.0-rc.0
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.0
         @angular/cdk: 13.0.0
         @angular/common: 13.0.0
         @angular/compiler: 13.0.0
         @angular/core: 13.0.0
         @angular/forms: 13.0.0
         @angular/platform-browser: 13.0.0
         @angular/platform-browser-dynamic: 13.0.0
         @angular/router: 13.0.0
         @angular/upgrade: 13.0.0
         @ngrx/component: 12.3.0
         ngx-bootstrap: 5.6.2
         @angular-devkit/build-angular: 13.0.2
         @angular/cli: 13.0.2
         @angular/compiler-cli: 13.0.0
         @angular/language-service: 13.0.0
```

Is there anything you can point me to? Or do you have to apply s similar fix for the update-libraries migration?

**Comment by tFaster** [comment]
Update: I was able to get past the 'update-libraries' migration by removing one of my libraries that did not have any targets!
So it seems a similar fix is needed in this migration step as well!
