### ISSUE TITLE
Serve with CRA preset does not work out of the box

### ISSUE THREAD

**Issue by oguera** [nrwl/nx#7827]
## Current Behavior

I created a fresh app with the following command: `npx create-nx-workspace@latest --preset=react --nx-cloud=false --packageManager=yarn --appName=app-name --name=my-name`. After that i tried to serve the app `app-name` with `nx serve app-name`.
## Expected Behavior

The app `app-name` opens on port 4200.
## Steps to Reproduce

Execute the following commands
1. `npx create-nx-workspace@latest --preset=react --nx-cloud=false --packageManager=yarn --appName=app-name --name=my-name`
2. `nx serve app-name`

### Failure Logs

```
nx serve app-name --verbose

> nx run app-name:serve --verbose
Cannot find module '/absolute/path/to/project/node_modules/lines-and-columns/build/index.mjs'
Error: Cannot find module '/absolute/path/to/project/node_modules/lines-and-columns/build/index.mjs'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/absolute/path/to/project/node_modules/fork-ts-checker-webpack-plugin/node_modules/parse-json/index.js:4:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

———————————————————————————————————————————————

>  NX   ERROR  Running target "app-name:serve" failed

  Failed tasks:

  - app-name:serve

  Hint: run the command with --verbose for more details.
```
### Environment

```
nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.17.1
  OS   : darwin x64
  yarn : 1.22.11

  nx : 13.2.1
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.1
  @nrwl/cypress : 13.2.1
  @nrwl/devkit : 13.2.1
  @nrwl/eslint-plugin-nx : 13.2.1
  @nrwl/express : undefined
  @nrwl/jest : 13.2.1
  @nrwl/linter : 13.2.1
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.2.1
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.1
  @nrwl/web : 13.2.1
  @nrwl/workspace : 13.2.1
  @nrwl/storybook : 13.2.1
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
```

**Comment by oguera** [comment]
After doing some more binary debugging and installing different versions of nx up until the `latest` version it somehow worked again. Now the node_modules/lines-and-colums directory acutally contains a `.mjs` file. 

Maybe a hick up. I'll close this :)
