### ISSUE TITLE
Cannot find module '@angular-devkit/core' on migrate from 13.1.4 to 13.2.1

### ISSUE THREAD

**Issue by RicardoJBarrios** [nrwl/nx#7837]
I'm trying to migrate a 13.1.4 project to 13.2.1, but the migrate step throws and error saying that cannot find module '@angular-devkit/core'. I've checked and this module is in `yarn.lock` and in `node_modules`.

```bash
$ readlink -e node_modules/@angular-devkit/core/package.json
/c/dev/kaikokeke/kaikokeke/node_modules/@angular-devkit/core/package.json
```

```bash
$ grep @angular-devkit/core yarn.lock
    "@angular-devkit/core" "13.0.3"
    "@angular-devkit/core" "8.3.23"
    "@angular-devkit/core" "13.0.3"
"@angular-devkit/core@13.0.3":
  resolved "https://registry.npmjs.org/@angular-devkit/core/-/core-13.0.3.tgz#05911ab964f8cbd5cade9bd48215424836ab9c87"
"@angular-devkit/core@8.3.23":
  resolved "https://registry.npmjs.org/@angular-devkit/core/-/core-8.3.23.tgz#612bf8a76b1ccde40cd6a5e85a02dc083bb666c6"
"@angular-devkit/core@8.3.29", "@angular-devkit/core@^8.3.8":
  resolved "https://registry.npmjs.org/@angular-devkit/core/-/core-8.3.29.tgz#3477edd6458653f83e6d78684b100c1bef81382f"
    "@angular-devkit/core" "13.0.3"
    "@angular-devkit/core" "8.3.23"
    "@angular-devkit/core" "8.3.29"
    "@angular-devkit/core" "13.0.3"
    "@angular-devkit/core" "8.3.23"
    "@angular-devkit/core" "8.3.23"
    "@angular-devkit/core" "8.3.23"
    "@angular-devkit/core" "8.3.23"
    "@angular-devkit/core" "13.0.3"
    "@angular-devkit/core" "8.3.23"
    "@angular-devkit/core" "8.3.29"
    "@angular-devkit/core" "8.3.29"
    "@angular-devkit/core" "^8.3.8"
```

Here I found that the installed version by default was 8.3, so forced the library update with

```bash
 $ yarn add -D @angular-devkit/core@13.0.3
```

But the problem continues.

## Current Behavior
The migration script stops after an error. 

## Expected Behavior
Complete the migration script.

## Steps to Reproduce
1. Clone the repo in Nx 13.1.4 `git clone -b nx-migrate-error --single-branch https://github.com/kaikokeke/kaikokeke.git`
2. run `yarn`
3. run `yarn update`
4. run `yarn`
5. run `nx migrate --run-migrations`

```bash
>  NX  Running migrations from 'migrations.json'

Running migration set-parallel-default
Successfully finished set-parallel-default
---------------------------------------------------------
Running migration update-angular-config
Successfully finished update-angular-config
---------------------------------------------------------
Running migration update-libraries
Successfully finished update-libraries
---------------------------------------------------------
Running migration update-angular-jest-config
Successfully finished update-angular-jest-config
---------------------------------------------------------
Running migration update-testing-imports
Successfully finished update-testing-imports
---------------------------------------------------------
Running migration schematic-options-13
Cannot find module '@angular-devkit/core'
Require stack:
- C:\Users\Ricardo\AppData\Local\Temp\tmp-192-K58PSva8hQ92\node_modules\@nrwl\tao\src\commands\ngcli-adapter.js
- C:\Users\Ricardo\AppData\Local\Temp\tmp-192-K58PSva8hQ92\node_modules\@nrwl\tao\src\commands\migrate.js
- C:\Users\Ricardo\AppData\Local\Temp\tmp-192-K58PSva8hQ92\node_modules\@nrwl\tao\index.js
C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\Ricardo\AppData\Local\Temp\tmp-192-K58PSva8hQ92\node_modules\.bin\tao migrate --run-migrations=migrations.json
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.handler (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:125:42)
    at Object.runCommand (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at initLocal (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\cli\lib\init-local.js:28:79)
    at Object.<anonymous> (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\cli\bin\nx.js:43:32)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12880,
  stdout: null,
  stderr: null
}
```

### Failure Logs

```bash
Cannot find module '@angular-devkit/core'
Require stack:
- C:\Users\Ricardo\AppData\Local\Temp\tmp-12260-lTvq4ftI6fPb\node_modules\@nrwl\tao\src\commands\ngcli-adapter.js
- C:\Users\Ricardo\AppData\Local\Temp\tmp-12260-lTvq4ftI6fPb\node_modules\@nrwl\tao\src\commands\migrate.js
- C:\Users\Ricardo\AppData\Local\Temp\tmp-12260-lTvq4ftI6fPb\node_modules\@nrwl\tao\index.js
C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\Ricardo\AppData\Local\Temp\tmp-12260-lTvq4ftI6fPb\node_modules\.bin\tao migrate --run-migrations
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.handler (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:125:42)
    at Object.runCommand (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at initLocal (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\cli\lib\init-local.js:28:79)
    at Object.<anonymous> (C:\dev\kaikokeke\kaikokeke\node_modules\@nrwl\cli\bin\nx.js:43:32)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 8948,
  stdout: null,
  stderr: null
}
```
### Environment
  Node : 14.15.3
  OS   : win32 x64
  yarn : 1.22.15

  nx : 13.1.4
  @nrwl/angular : 13.1.4
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 13.1.4
  @nrwl/nx-cloud : 12.5.2
  @nrwl/react : Not Found
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 13.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by RicardoJBarrios** [comment]
Checked. It's working now. Thanks.

**Comment by kmaraz** [comment]
I had the same problem even after installing version 13.2.2

What fixed this issue for me was running: `npx @nrwl/tao migrate --run-migrations`

**Comment by brunobertechini** [comment]
I just had the same issue with version 13.10.6`. Is it a regression?
