### ISSUE TITLE
set-parallel-default migration fails (nx 12->13)

### ISSUE THREAD

**Issue by Zwergenpunk** [nrwl/nx#7852]
## Current Behavior
While upgrading an angular app from nx 12 to nx 13.2 I get an error while migrating:

When executing `nx migrate --run-migrations` an error occurs:
```
Running migration set-parallel-default
Cannot read properties of undefined (reading 'default')
D:\Git\FaMa\Dah.FaMa.Web.Frontend\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\xx\AppData\Local\Temp\tmp-37424-pKcWMRI5UMNv\node_modules\.bin\tao migrate --run-migrations
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.handler (D:\Git\FaMa\Dah.FaMa.Web.Frontend\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:125:42)
    at Object.runCommand (D:\Git\FaMa\Dah.FaMa.Web.Frontend\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)       
    at Object.parseArgs [as _parseArgs] (D:\Git\FaMa\Dah.FaMa.Web.Frontend\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (D:\Git\FaMa\Dah.FaMa.Web.Frontend\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)      
    at initLocal (D:\Git\FaMa\Dah.FaMa.Web.Frontend\node_modules\@nrwl\cli\lib\init-local.js:28:79)
    at Object.<anonymous> (D:\Git\FaMa\Dah.FaMa.Web.Frontend\node_modules\@nrwl\cli\bin\nx.js:43:32)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 25608,
  stdout: null,
  stderr: null
}
```

My migrations.json (the failing migration is the first one):  
```
{
  "migrations": [
    {
      "version": "13.2.0",
      "description": "Set --parallel=1 for existing repos to preserve the existing behavior",
      "cli": "nx",
      "implementation": "./src/migrations/update-13-2-0/set-parallel-default",
      "package": "@nrwl/workspace",
      "name": "set-parallel-default"
    },
    ...
 ```

## Expected Behavior
No error while migrating

### Environment
```
Node : 16.11.1
  OS   : win32 x64
  npm  : 7.18.1

  nx : 13.2.2
  @nrwl/angular : 13.2.2
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : undefined
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.0
         @angular/cdk: 13.0.0
         @angular/common: 13.0.0
         @angular/compiler: 13.0.0
         @angular/core: 13.0.0
         @angular/forms: 13.0.0
         @angular/localize: 13.0.0
         @angular/material: 13.0.0
         @angular/platform-browser: 13.0.0
         @angular/platform-browser-dynamic: 13.0.0
         @angular/router: 13.0.0
         @ng-bootstrap/ng-bootstrap: 11.0.0-beta.2
         @ngneat/reactive-forms: 2.0.0
         @angular-devkit/build-angular: 13.0.3
         @angular-eslint/schematics: 12.4.1
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.0
         @angular/language-service: 13.0.0
 ```

**Comment by Zwergenpunk** [comment]
I found the issue:
I had no `tasksRunnerOptions` option in my nx.json
