### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'paths')

### ISSUE THREAD

**Issue by shertu** [nrwl/nx#7945]
## Current Behavior
When I execute certain nx commands, e.g. `dep-graph` or `run-many`, then I get an error.

## Expected Behavior
I expect the commands to run as described in the documentation without type errors.

I am unaware if this is a regression issue.

## Steps to Reproduce

1. [Clone this repository.](https://github.com/shertu/zukte)
2. Execute `npm install`
3. Execute `npm run lint` which executes `nx run-many --target=lint --all`

### Failure Logs
```
TypeError: Cannot read properties of undefined (reading 'paths')
    at createCache (D:\shertu\zukte\node_modules\.pnpm\@nrwl+workspace@13.2.3_prettier@2.5.0\node_modules\@nrwl\workspace\src\core\nx-deps\nx-deps-cache.js:62:48)
    at D:\shertu\zukte\node_modules\.pnpm\@nrwl+workspace@13.2.3_prettier@2.5.0\node_modules\@nrwl\workspace\src\core\project-graph\build-project-graph.js:47:67
    at Generator.next (<anonymous>)
    at fulfilled (D:\shertu\zukte\node_modules\.pnpm\tslib@2.3.1\node_modules\tslib\tslib.js:114:62)
```

### Environment

```
  Node : 17.1.0
  OS   : win32 x64
  pnpm : 6.23.2

  nx : 13.2.3
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.3
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.2.3
  @nrwl/eslint-plugin-nx : undefined
  @nrwl/express : undefined
  @nrwl/jest : 13.2.3
  @nrwl/linter : 13.2.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.3
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.3
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.5.2
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
```

**Comment by shertu** [comment]
Closing because I am no longer using nx.
