### ISSUE TITLE
Running migration "update-angular-config-v13" results in: "PropertyNameExpected in JSON at position 12007"

### ISSUE THREAD

**Issue by webia1** [nrwl/nx#8017]
## Current Behavior

Running migration "update-angular-config-v13" results in: "PropertyNameExpected in JSON at position 12007".

## Expected Behavior

Migration is done sucessfully.

## Steps to Reproduce

```shell
nx migrate latest
rm -rf node_modules
npm i
nx migrate --run-migrations
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```shell
Running migration update-angular-config-v13
PropertyNameExpected in JSON at position 12007
node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/mv/hymt5clj6bv0_wbsgldkqmp40000gn/T/tmp-19542-lSPX5tkjvDkm/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.handler (node_modules/@nrwl/workspace/src/command-line/nx-commands.js:125:42)
    at Object.runCommand (node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (node_modules/yargs/build/lib/yargs.js:986:25)
    at initLocal (node_modules/@nrwl/cli/lib/init-local.js:28:79)
    at Object.<anonymous> (node_modules/@nrwl/cli/bin/nx.js:45:32)
    at Module._compile (/usr/local/lib/node_modules/@nrwl/cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19584,
  stdout: null,
  stderr: null
}
```

### Environment

MacOS Catalina v10.15.7
Node v17.2.0
Npm v8.1.4

Last but not least: Many thanks!

**Comment by webia1** [comment]
Solved: There were some deprecated properties like "sourceMap, vendorChunk" etc., in the serve section.
