### ISSUE TITLE
Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by amosbastian** [nrwl/nx#8047]
## Current Behavior

When running Storybook in my monorepo I get the following error:

```
SyntaxError: /Users/amosbastian/Development/boilerplate/libs/shared/storybook/.storybook/preview.js: Support for the experimental syntax 'jsx' isn't currently enabled
```

## Expected Behavior

Storybook used to work fine, but has been giving me problems for the last month or longer. I had [another issue](https://github.com/nrwl/nx/issues/7640#event-5677970007) recently, which was fixed, but with the new update came this error.

## Steps to Reproduce

Clone https://github.com/amosbastian/boilerplate/tree/feature/storybook, `npm i` and run

```
nx serve shared-storybook:storybook
```

### Failure Logs

```
info => Loading presets
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
<i> [webpack-dev-middleware] wait until bundle finished
assets by chunk 5.15 MiB (id hint: vendors)
  assets by status 4.77 MiB [big]
    asset vendors-node_modules_storybook_addon-a11y_dist_esm_register_js-node_modules_storybook_addon-a-bdcdc3.manager.bundle.js 4.4 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_OverlayScrollbars_js.manager.bundle.js 372 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_syntaxhighlighter_syntaxhighlighter_js.manager.bundle.js 195 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_tooltip_WithTooltip_js.manager.bundle.js 115 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_controls_Color_js.manager.bundle.js 72.6 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_GlobalScrollAreaStyles_js.manager.bundle.js 15.7 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.1 KiB [emitted] (name: runtime~main)
asset index.html 2.65 KiB [emitted]
asset main.manager.bundle.js 2.4 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.28 KiB [emitted]
Entrypoint main [big] 4.42 MiB = runtime~main.manager.bundle.js 14.1 KiB vendors-node_modules_storybook_addon-a11y_dist_esm_register_js-node_modules_storybook_addon-a-bdcdc3.manager.bundle.js 4.4 MiB main.manager.bundle.js 2.4 KiB
orphan modules 1.56 MiB [orphan] 334 modules
runtime modules 8.69 KiB 14 modules
javascript modules 4.58 MiB
  modules by path ./node_modules/ 4.58 MiB 829 modules
  ./libs/shared/storybook/.storybook/generated-refs.js 299 bytes [built] [code generated]
  ./util.inspect (ignored) 15 bytes [built] [code generated]
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]
manager (webpack 5.64.4) compiled successfully in 8350 ms
webpack built preview 193ff3c840f85309ab55 in 9989ms

ModuleBuildError: Module build failed (from ./node_modules/@nrwl/web/src/utils/web-babel-loader.js):
SyntaxError: /Users/amosbastian/Development/boilerplate/libs/shared/storybook/.storybook/preview.js: Support for the experimental syntax 'jsx' isn't currently enabled (61:5):

  59 |
  60 |   return (
> 61 |     <IconButton
     |     ^
  62 |       position="absolute"
  63 |       size="md"
  64 |       fontSize="lg"

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
    at Parser._raise (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:541:17)
    at Parser.raiseWithData (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:534:17)
    at Parser.expectOnePlugin (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:3595:18)
    at Parser.parseExprAtom (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11981:18)
    at Parser.parseExprSubscripts (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11584:23)
    at Parser.parseUpdate (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11564:21)
    at Parser.parseMaybeUnary (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11539:23)
    at Parser.parseMaybeUnaryOrPrivate (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11353:61)
    at Parser.parseExprOps (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11360:23)
    at Parser.parseMaybeConditional (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11330:23)
    at Parser.parseMaybeAssign (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11290:21)
    at /Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11248:39
    at Parser.allowInAnd (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:13137:12)
    at Parser.parseMaybeAssignAllowIn (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11248:17)
    at Parser.parseParenAndDistinguishExpression (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:12294:28)
    at Parser.parseExprAtom (/Users/amosbastian/Development/boilerplate/node_modules/@babel/parser/lib/index.js:11891:23)
    at processResult (/Users/amosbastian/Development/boilerplate/node_modules/webpack/lib/NormalModule.js:751:19)
    at /Users/amosbastian/Development/boilerplate/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/amosbastian/Development/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/amosbastian/Development/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/amosbastian/Development/boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/amosbastian/Development/boilerplate/node_modules/babel-loader/lib/index.js:59:103
```

### Environment

```
  Node : 14.16.1
  OS   : darwin x64
  npm  : 8.1.4

  nx : 13.2.4
  @nrwl/angular : undefined
  @nrwl/cli : 13.2.4
  @nrwl/cypress : 13.2.4
  @nrwl/devkit : 13.2.4
  @nrwl/eslint-plugin-nx : 13.2.4
  @nrwl/express : 13.2.4
  @nrwl/jest : 13.2.4
  @nrwl/linter : 13.2.4
  @nrwl/nest : undefined
  @nrwl/next : 13.2.4
  @nrwl/node : 13.2.4
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.2.4
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.4
  @nrwl/web : 13.2.4
  @nrwl/workspace : 13.2.4
  @nrwl/storybook : 13.2.4
  @nrwl/gatsby : undefined
  typescript : 4.5.2
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
```

**Comment by puku0x** [comment]
Adding `.babelrc` may be a workaround.
https://github.com/nrwl/nx/issues/8032#issuecomment-988004844

**Comment by amosbastian** [comment]
> Adding `.babelrc` may be a workaround. [#8032 (comment)](https://github.com/nrwl/nx/issues/8032#issuecomment-988004844)

I have a `.babelrc` for my shared Storybook, but you are right, adding `"@nrwl/next/babel"` to `.babelrc`'s `presets` actually makes Storybook run properly, however it stops being able to find any stories.
