### ISSUE TITLE
Fails to serve with @nrwl/web:dev-server

### ISSUE THREAD

**Issue by playnox** [nrwl/nx#8073]
The stack produces an error when **serving** project with **@nrwl/web:dev-server**
However it loads with **@nrwl/angular:webpack-server** whats the difference ?!?

## Current Behavior
**nx serve** trows an error:

```
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at parseTargetString (/.../node_modules/@nrwl/devkit/src/executors/parse-target-string.js:16:59)
    at getBuildOptions (/.../node_modules/@nrwl/web/src/executors/dev-server/dev-server.impl.js:45:51)
    at devServerExecutor_1 (/.../nx/node_modules/@nrwl/web/src/executors/dev-server/dev-server.impl.js:18:72)
    at devServerExecutor_1.next (<anonymous>)
    at resume (/.../node_modules/tslib/tslib.js:225:48)
    at /.../nx/node_modules/tslib/tslib.js:224:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (/.../node_modules/tslib/tslib.js:224:67)
    at /.../node_modules/@nrwl/tao/src/commands/run.js:93:35
    at Generator.next (<anonymous>)
```

## Expected Behavior
Has to load with no errors...

## Steps to Reproduce

Create new nx as new Angular project
`yarn create nx-workspace --package-manager=yarn`

Install missing package
`yarn add @nrwl/web --dev ` 

Update angular.json with
`"serve": { "executor": "@nrwl/web:dev-server"`

Run serve:
`nx serve YOUR_PROJECT_NAME`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at parseTargetString (/.../node_modules/@nrwl/devkit/src/executors/parse-target-string.js:16:59)
    at getBuildOptions (/.../node_modules/@nrwl/web/src/executors/dev-server/dev-server.impl.js:45:51)
    at devServerExecutor_1 (/.../nx/node_modules/@nrwl/web/src/executors/dev-server/dev-server.impl.js:18:72)
    at devServerExecutor_1.next (<anonymous>)
    at resume (/.../node_modules/tslib/tslib.js:225:48)
    at /.../nx/node_modules/tslib/tslib.js:224:125
    at new Promise (<anonymous>)
    at Object.i.<computed> [as next] (/.../node_modules/tslib/tslib.js:224:67)
    at /.../node_modules/@nrwl/tao/src/commands/run.js:93:35
    at Generator.next (<anonymous>)
```

### Environment

Nx Report:

```
  Node : 12.22.5
  OS   : darwin x64
  yarn : 1.22.11
  
  nx : 13.2.4
  @nrwl/angular : 13.2.4
  @nrwl/cli : 13.2.4
  @nrwl/cypress : 13.2.4
  @nrwl/devkit : 13.2.4
  @nrwl/eslint-plugin-nx : 13.2.4
  @nrwl/express : undefined
  @nrwl/jest : 13.2.4
  @nrwl/linter : 13.2.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.4
  @nrwl/web : 13.2.4
  @nrwl/workspace : 13.2.4
  @nrwl/storybook : 13.2.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.0.3
  	 @angular/common: 13.0.3
  	 @angular/compiler: 13.0.3
  	 @angular/core: 13.0.3
  	 @angular/forms: 13.0.3
  	 @angular/platform-browser: 13.0.3
  	 @angular/platform-browser-dynamic: 13.0.3
  	 @angular/router: 13.0.3
  	 @angular-devkit/build-angular: 13.0.4
  	 @angular/cli: 13.0.4
  	 @angular/compiler-cli: 13.0.3
  	 @angular/language-service: 13.0.3
```

**Comment by AgentEnder** [comment]
Hey @playnox! Can you paste the target configuration here? The schemas are slightly different between the two executors IIRC

**Comment by playnox** [comment]
Everything out of the box... no changes done to any options besides mentioned in **Steps to Reproduce**
```
"configurations": {
    "production": {
        "browserTarget": "site:build:production"
    },
    "development": {
        "browserTarget": "site:build:development"
    }
}
```

**Comment by AgentEnder** [comment]
The different executors options are slightly different. Particularly, you want to use buildTarget instead of browserTarget.

https://nx.dev/l/n/web/dev-server
https://nx.dev/l/n/angular/webpack-server

**Comment by playnox** [comment]
Updating params did resolved an issue, however it's now throwing this one https://github.com/nrwl/nx/issues/5736

**Comment by AgentEnder** [comment]
Ok, thanks for confirming. I'll close this issue out, since the other issue is already being tracked.
