### ISSUE TITLE
Unexpected token } in JSON at position

### ISSUE THREAD

**Issue by mackelito** [nrwl/nx#8108]
## Current Behavior
Running `nx migrate --run-migrations`

### Failure Logs
````
Running migration update-ts-config-for-test-filenames
Unexpected token } in JSON at position 188
/Users/Projects/web-client/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/81/h58z2qgj7fn0qkb3zznn16_c0000gn/T/tmp-62889-m14rcOfW1fq1/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (/Users/Projects/web-client/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:114:25)
    at Object.runCommand (/Users/Projects/web-client/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/Projects/web-client/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/Projects/web-client/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/Projects/web-client/node_modules/@nrwl/cli/lib/init-local.js:28:79)
    at Object.<anonymous> (/Users/Projects/web-client/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 62899,
  stdout: null,
  stderr: null
}
````

### Environment

````
  NX  Report complete - copy this into the issue template

  Node : 14.15.1
  OS   : darwin x64
  npm  : 6.14.15
  
  nx : Not Found
  @nrwl/angular : 13.1.4
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 13.0.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
````

**Comment by AgentEnder** [comment]
Hey @mackelito, can you post the migrations.json file that you are trying to run here?

**Comment by mackelito** [comment]
```
{
  "migrations": [
    {
      "version": "12.5.0-beta.1",
      "description": "Rename the workspace-schematic script into workspace-generator script",
      "factory": "./src/migrations/update-12-5-0/add-target-dependencies",
      "cli": "nx",
      "package": "@nrwl/workspace",
      "name": "add-target-dependencies"
    },
    {
      "version": "13.0.0-beta.1",
      "description": "Add default base to nx.json if its not currently set",
      "factory": "./src/migrations/update-13-0-0/set-default-base-if-not-set",
      "cli": "nx",
      "package": "@nrwl/workspace",
      "name": "set-default-base-if-not-set"
    },
    {
      "version": "13.0.0-beta.4",
      "description": "Move global settings into nx.json, and project specific settings into workspace.json",
      "cli": "nx",
      "implementation": "./src/migrations/update-13-0-0/config-locations/config-locations",
      "package": "@nrwl/workspace",
      "name": "13-0-0-config-locations"
    },
    {
      "cli": "nx",
      "version": "12.9.0",
      "description": "Fixes invalid importPaths for buildable and publishable libs.",
      "factory": "./src/migrations/update-12-9-0/update-invalid-import-paths",
      "package": "@nrwl/angular",
      "name": "update-invalid-import-paths"
    },
    {
      "cli": "nx",
      "version": "13.0.0-beta.10",
      "description": "Adds postcss packages needed for Tailwind support if ng-packagr is already installed.",
      "factory": "./src/migrations/update-13-0-0/add-postcss-packages",
      "package": "@nrwl/angular",
      "name": "add-postcss-packages"
    },
    {
      "version": "12.0.0-0",
      "description": "Updates Angular Material to v12",
      "factory": "./ng-update/index#updateToV12",
      "package": "@angular/material",
      "name": "migration-v12"
    },
    {
      "version": "12.0.0-0",
      "description": "Updates the Angular CDK to v12",
      "factory": "./ng-update/index#updateToV12",
      "package": "@angular/cdk",
      "name": "migration-v12"
    },
    {
      "cli": "nx",
      "version": "12.8.0-beta.0",
      "description": "Remove Typescript Preprocessor Plugin",
      "factory": "./src/migrations/update-12-8-0/remove-typescript-plugin",
      "package": "@nrwl/cypress",
      "name": "remove-typescript-plugin"
    },
    {
      "version": "12.4.0-beta.1",
      "cli": "nx",
      "description": "Add testEnvironment: 'jsdom' in web apps + libraries",
      "factory": "./src/migrations/update-12-4-0/add-test-environment-for-node",
      "package": "@nrwl/jest",
      "name": "support-jest-27"
    },
    {
      "version": "12.4.0-beta.1",
      "cli": "nx",
      "description": "Support for Jest 27 via updating ts-jest + jest-preset-angular",
      "factory": "./src/migrations/update-12-4-0/update-jest-preset-angular",
      "package": "@nrwl/jest",
      "name": "update-ts-jest-and-jest-preset-angular"
    },
    {
      "version": "12.6.0-beta.0",
      "cli": "nx",
      "description": "Uses `getJestProjects()` to populate projects array in root level `jest.config.js` file.",
      "factory": "./src/migrations/update-12-6-0/update-base-jest-config",
      "package": "@nrwl/jest",
      "name": "update-jest-config-to-use-util"
    },
    {
      "version": "13.1.2-beta.0",
      "cli": "nx",
      "description": "Support .test. file names in tsconfigs",
      "factory": "./src/migrations/update-13-1-2/update-tsconfigs-for-tests",
      "package": "@nrwl/jest",
      "name": "update-ts-config-for-test-filenames"
    },
    {
      "cli": "nx",
      "version": "12.4.0-beta.0",
      "description": "Remove ESLint parserOptions.project config if no rules requiring type-checking are in use",
      "factory": "./src/migrations/update-12-4-0/remove-eslint-project-config-if-no-type-checking-rules",
      "package": "@nrwl/linter",
      "name": "remove-eslint-project-config-if-no-type-checking-rules"
    },
    {
      "cli": "nx",
      "version": "12.9.0-beta.0",
      "description": "Add outputs for caching",
      "factory": "./src/migrations/update-12-9-0/add-outputs",
      "package": "@nrwl/linter",
      "name": "add-outputs"
    },
    {
      "cli": "nx",
      "version": "12.9.0-beta.0",
      "description": "Remove ESLint parserOptions.project config if no rules requiring type-checking are in use",
      "factory": "./src/migrations/update-12-4-0/remove-eslint-project-config-if-no-type-checking-rules",
      "package": "@nrwl/linter",
      "name": "remove-eslint-project-config-if-no-type-checking-rules-again"
    },
    {
      "version": "12.5.0-beta.5",
      "cli": "nx",
      "description": "Upgrade Storybook to v6.3",
      "factory": "./src/migrations/update-12-5-0/migrate-storybook-6-3",
      "package": "@nrwl/storybook",
      "name": "update-12-5-0"
    },
    {
      "version": "12.5.0-beta.5",
      "cli": "nx",
      "description": "Install the @storybook/addon-essentials package",
      "factory": "./src/migrations/update-12-5-0/install-addon-essentials",
      "package": "@nrwl/storybook",
      "name": "install-addon-essentials"
    },
    {
      "version": "12.5.9-beta.1",
      "cli": "nx",
      "description": "Update Storybook React typings in tsconfig files",
      "factory": "./src/migrations/update-12-5-9/update-storybook-react-typings",
      "package": "@nrwl/storybook",
      "name": "update-12-5-9-beta.1"
    },
    {
      "version": "12.8.0-beta.11",
      "cli": "nx",
      "description": "Adjust Storybook tsconfig to add styled-jsx typings",
      "factory": "./src/migrations/update-12-8-0/update-storybook-styled-jsx-typings",
      "package": "@nrwl/storybook",
      "name": "update-12-8.0"
    }
  ]
}

```

**Comment by mackelito** [comment]
@AgentEnder have you had a chance to take a look?

**Comment by mackelito** [comment]
I would think that there is some lib of ours that might not be buildable that needs to be.. but as there is no output then I have no way of knowing :(

**Comment by mackelito** [comment]
Any updates here?
