### ISSUE TITLE
Cannot read properties of undefined (reading 'tap') React

### ISSUE THREAD

**Issue by ainulhassanml** [nrwl/nx#8190]
After installing dependencies through npm I start the server like `nx run abc:serve` the way I configured. I'm getting the following error

```
>  NX  Using webpack 5. Reason: detected version 5 in node_modules/webpack/package.json

Found an outdated version of webpack-sources

If you want to use webpack 5, try installing compatible versions of the plugins.
See: https://nx.dev/guides/webpack-5

>  NX  Falling back to webpack 4 due to incompatible plugin versions

Cannot read properties of undefined (reading 'tap')
TypeError: Cannot read properties of undefined (reading 'tap')
    at /Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:236:65
    at SyncHook.eval [as call] (eval at create (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:19:1)
    at SyncHook.lazyCompileHook (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@nrwl/web/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@nrwl/web/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@nrwl/web/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@nrwl/web/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@nrwl/web/node_modules/webpack/lib/Watching.js:41:32)
    at /Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@nrwl/web/node_modules/webpack/lib/Watching.js:33:9
    at Compiler.readRecords (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@nrwl/web/node_modules/webpack/lib/Compiler.js:529:11)
    at new Watching (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@nrwl/web/node_modules/webpack/lib/Watching.js:30:17)
    at Compiler.watch (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@nrwl/web/node_modules/webpack/lib/Compiler.js:244:10)
```
It looks like the issue is with webpack I've also tried with upgrading and downgrading the webpack version but failed to successfully run the project

When I upgrade on webpack 5 following errors occur

```
>  NX  Using webpack 5. Reason: detected version 5 in node_modules/webpack/package.json

Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[3].oneOf[0].issuer has an unknown property 'test'. These properties are valid:
   object { and?, not?, or? }
   -> Logic operators used in a condition matcher.
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[3].oneOf[0].issuer has an unknown property 'test'. These properties are valid:
   object { and?, not?, or? }
   -> Logic operators used in a condition matcher.
    at validate (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/schema-utils/dist/validate.js:105:11)
    at validateSchema (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/webpack/lib/validateSchema.js:78:2)
    at create (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/webpack/lib/webpack.js:111:24)
    at webpack (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/webpack/lib/webpack.js:158:32)
    at f (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/webpack/lib/index.js:58:16)
    at Observable._subscribe (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/@nrwl/web/node_modules/@nrwl/workspace/src/utilities/run-webpack.js:43:33)
    at Observable._trySubscribe (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/rxjs/internal/Observable.js:30:22)
    at DoOperator.call (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/rxjs/internal/operators/tap.js:32:23)
    at Observable.subscribe (/Users/muhammadain/Projects/Pro/nx-configuration/node_modules/rxjs/internal/Observable.js:25:31)
```

I've also tried all suggestions on the following URLs

https://nx.dev/l/r/guides/webpack-5
https://stackoverflow.com/questions/53227877/progressplugin-typeerror-cannot-read-property-tap-of-undefined
https://github.com/vercel/next.js/issues/5781
https://stackoverflow.com/questions/56680415/cannot-resolve-the-error-progressplugin-typeerror-cannot-read-property-tap-of
https://stackoverflow.com/questions/53046371/react-webpack-cannot-read-property-tap-of-undefined
https://newbedev.com/progressplugin-typeerror-cannot-read-property-tap-of-undefined

Any help would be greatly appreciated.

**Comment by FrozenPandaz** [comment]
@jaysoo Maybe we can remove this since... we don't really support webpack 4 anymore?

**Comment by ainulhassanml** [comment]
@FrozenPandaz 

After running `npx nx g @nrwl/web:webpack5` facing following error

```
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[3].oneOf[0].issuer has an unknown property 'test'. These properties are valid:
   object { and?, not?, or? }
   -> Logic operators used in a condition matcher.
```
any workaround to this issue?
