### ISSUE TITLE
nextjs doesn't support eslint-config-airbnb

### ISSUE THREAD

**Issue by BorisZubchenko** [nrwl/nx#8191]
## Current Behavior

I try to integrate `eslint-config-airbnb` into my workspace but without success. It works with a standalone Nextjs app, without NX.

## Expected Behavior

I want to extend my eslint's config with the `airbnb` eslint plugin.

## Steps to Reproduce

[repro repo](https://github.com/BorisZubchenko/nx-nextjs-airbnb-bug)

1. `npx create-nx-workspace`
2. choose `nextjs` template
3. `npm i -D eslint-config-airbnb`
4. drop `"extends": ["airbnb"],` into `/.eslintrc.json`
5. navigate to any `.tsx` file
6. see the following error:
![image](https://user-images.githubusercontent.com/31354262/146256764-6b41045a-027c-4944-a937-4639eda5a53a.png)

### Failure Logs
```
Error: Plugin "jsx-a11y" was conflicted between ".eslintrc.json » eslint-config-next/core-web-vitals » /home/boris/projects/acme/node_modules/eslint-config-next/index.js" and ".eslintrc.json » ../../.eslintrc.json » eslint-config-airbnb » /home/boris/projects/acme/node_modules/eslint-config-airbnb/rules/react-a11y.js".

Error: Plugin "jsx-a11y" was conflicted between ".eslintrc.json » eslint-config-next/core-web-vitals » /home/boris/projects/acme/node_modules/eslint-config-next/index.js" and ".eslintrc.json » ../../.eslintrc.json » eslint-config-airbnb » /home/boris/projects/acme/node_modules/eslint-config-airbnb/rules/react-a11y.js".
    at mergePlugins (/home/boris/projects/acme/node_modules/@eslint/eslintrc/lib/config-array/config-array.js:201:19)
    at createConfig (/home/boris/projects/acme/node_modules/@eslint/eslintrc/lib/config-array/config-array.js:304:9)
    at ConfigArray.extractConfig (/home/boris/projects/acme/node_modules/@eslint/eslintrc/lib/config-array/config-array.js:480:33)
    at CLIEngine.isPathIgnored (/home/boris/projects/acme/node_modules/eslint/lib/cli-engine/cli-engine.js:982:18)
    at ESLint.isPathIgnored (/home/boris/projects/acme/node_modules/eslint/lib/eslint/eslint.js:679:26)
    at ESLint8Plugin.<anonymous> (/home/boris/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/213.5744.224/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint8-plugin.js:155:57)
    at step (/home/boris/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/213.5744.224/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint8-plugin.js:44:23)
    at Object.next (/home/boris/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/213.5744.224/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint8-plugin.js:25:53)
    at /home/boris/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/213.5744.224/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint8-plugin.js:19:71
    at new Promise (<anonymous>)
```

### Environment

```
  Node : 14.17.3
  OS   : linux x64
  npm  : 6.14.13
  
  nx : 13.3.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.3.6
  @nrwl/cypress : 13.3.6
  @nrwl/devkit : 13.3.6
  @nrwl/eslint-plugin-nx : 13.3.6
  @nrwl/express : undefined
  @nrwl/jest : 13.3.6
  @nrwl/linter : 13.3.6
  @nrwl/nest : undefined
  @nrwl/next : 13.3.6
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.3.6
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.6
  @nrwl/web : 13.3.6
  @nrwl/workspace : 13.3.6
  @nrwl/storybook : 13.3.6
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
```

**Comment by AmalRichwin** [comment]
Same issue

**Comment by kirjai** [comment]
thanks for opening the issue!

- looks like the difference in the `jsx-a11y` plugin comes from the fact that npm installs two different versions of `eslint-plugin-jsx-a11y` at the same time. one is in `node_modules`, and one in `node_modules/eslint-config-next/node_modules`.

- `@nrwl/react` depends on `eslint-plugin-jsx-a11y@^6.4.1`
- `eslint-config-next` depends on `eslint-plugin-jsx-a11y@^6.5.1`

looks like there's a similar problem with `eslint-plugin-react` - `7.23.1` vs `7.27.0`

---

steps on the Nx side:

- we'll bring the versions of `eslint-plugin-jsx-a11y` and `eslint-plugin-react` that Nx depends on to match those of `eslint-config-next`

---

what you can do right now to fix this yourself:

- install `eslint-plugin-jsx-a11y@^6.5.1` and `eslint-plugin-react@^7.27.0` in your project
- run `npm dedupe`

based on what i see locally myself - that should solve the problem.

note that once we'll release a fix that matches the versions of those plugins - you might need to run `npm dedupe` if the problem persists. Sometimes, once npm gets into a weird state like that - it's hard to correct it, sadly..

**Comment by BorisZubchenko** [comment]
From now, adding `"airbnb/hooks"` gives me the following error:
```
Plugin "react-hooks" was conflicted between "apps/site/.eslintrc.json » eslint-config-next/core-web-vitals » /home/boris/projects/repo/node_modules/eslint-config-next/index.js » plugin:react-hooks/recommended" and "apps/site/.eslintrc.json » ../../.eslintrc.json » eslint-config-airbnb/hooks » /home/boris/projects/repo/node_modules/eslint-config-airbnb/rules/react-hooks.js".
```

**Comment by Elanum** [comment]
This issue is still happening on my side. even with the solution of @kirjai
I am using `yarn` as pacakge manager.

Dependencies: 
```json
"dependencies": {
    "@nrwl/next": "13.9.4",
    "core-js": "^3.6.5",
    "express": "4.17.2",
    "next": "12.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "regenerator-runtime": "0.13.7",
    "tslib": "^2.0.0"
  },
  "devDependencies": {
    "@nrwl/cli": "13.9.4",
    "@nrwl/eslint-plugin-nx": "13.9.4",
    "@nrwl/express": "^13.9.4",
    "@nrwl/jest": "13.9.4",
    "@nrwl/linter": "13.9.4",
    "@nrwl/node": "13.9.4",
    "@nrwl/react": "13.9.4",
    "@nrwl/web": "13.9.4",
    "@nrwl/workspace": "13.9.4",
    "@testing-library/react": "12.1.4",
    "@testing-library/react-hooks": "7.0.2",
    "@types/express": "4.17.13",
    "@types/jest": "27.0.2",
    "@types/node": "16.11.7",
    "@types/react": "17.0.40",
    "@types/react-dom": "17.0.13",
    "@typescript-eslint/eslint-plugin": "~5.10.0",
    "@typescript-eslint/parser": "~5.10.0",
    "babel-jest": "27.2.3",
    "eslint": "~8.7.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-typescript": "^16.1.4",
    "eslint-config-next": "12.1.1-canary.3",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-jsx-a11y": "6.5.1",
    "eslint-plugin-react": "7.29.3",
    "eslint-plugin-react-hooks": "4.3.0",
    "husky": "^7.0.4",
    "jest": "27.2.3",
    "lint-staged": "^12.3.7",
    "nx": "13.9.4",
    "prettier": "^2.5.1",
    "react-test-renderer": "17.0.2",
    "ts-jest": "27.0.5",
    "typescript": "~4.5.2"
  }
``` 

Error: 
```bash
Plugin "react" was conflicted between "apps/frontend/.eslintrc.json » eslint-config-next/core-web-vitals » /home/manuel/Projects/hurrado/node_modules/eslint-config-next/index.js" and "apps/frontend/.eslintrc.json » ../../.eslintrc.json#overrides[0] » eslint-config-airbnb » /home/manuel/Projects/hurrado/node_modules/eslint-config-airbnb/rules/react-a11y.js"
```

**Comment by jparksecurity** [comment]
@BorisZubchenko Hi, can you run `yarn why eslint-plugin-react-hooks` to see if you have more than one version of `eslint-plugin-react-hooks` in your node modules?

My case was that my package.json has `"eslint-plugin-react-hooks": "^4.3.0"` which allows me to have the latest version, `v4.4.0`. Then I have `v4.3.0` from `eslint-config-next#eslint-plugin-react-hooks`

The fix was to update my package.json to `"eslint-plugin-react-hooks": "4.3.0",` without the hat.
