### ISSUE TITLE
Error running lint in parallel

### ISSUE THREAD

**Issue by skydever** [nrwl/nx#820]
## Current Behavior

Running `affected:lint` in parallel can cause the following error (a second run after the error mostly fixes this, it is hard to reproduce - but still happens from time to time in our CI):

```bash
Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.readJsonFile (/builds/demo-ws/node_modules/@nrwl/schematics/src/utils/fileutils.js:57:17)
    at Object.readDependencies (/builds/demo-ws/node_modules/@nrwl/schematics/src/command-line/shared.js:333:28)
    at new Rule (/builds/demo-ws/node_modules/@nrwl/schematics/src/tslint/nxEnforceModuleBoundariesRule.js:41:40)
    at Object.loadRules (/builds/demo-ws/node_modules/tslint/lib/ruleLoader.js:46:24)
    at Linter.getEnabledRules (/builds/demo-ws/node_modules/tslint/lib/linter.js:215:29)
    at Linter.lint (/builds/demo-ws/node_modules/tslint/lib/linter.js:98:33)
    at lint (/builds/demo-ws/node_modules/@angular-devkit/build-angular/src/tslint/index.js:138:20)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/builds/demo-ws/node_modules/@angular-devkit/build-angular/src/tslint/index.js:63:37)
    at Observable._trySubscribe (/builds/demo-ws/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Observable.js:43:25)
```

## Expected Behavior

Running `affected:lint` in parallel should be stable.

## Others

My guess is that the [access](https://github.com/nrwl/nx/blob/master/packages/schematics/src/command-line/shared.ts#L408) to `/dist/nxdeps.json` is not safe for a parallel execution? If the file does not exist or is outdated each lint process tries to update it, sometimes causing this error if the timeline of the file access clashes? I was thinking about a preprocessing as a solution for this, bringing the file up to date prior the parallel call to be sure to only have reads (that should be ok?) - but somehow this is already the case indirectly [here](https://github.com/nrwl/nx/blob/master/packages/schematics/src/command-line/affected.ts#L236) (`readDepGraph` is calling `readDependencies` prior the par. execution)? Any ideas?

**Comment by skydever** [comment]
I am so sorry, my mistake 😞 I did not migrate our CI to use the `affected:lint` script - I was still using my custom CLI that is just calling `ng lint` in parallel without that preprocessing I was talking about. I changed our CI script to use the `affected:lint` script now and will reopen the issue if I run into that again (happened very rarely before, but I guess this is gone now).
