### ISSUE TITLE
Live reload fails when adding scripts to project.json

### ISSUE THREAD

**Issue by adornala** [nrwl/nx#8230]
## Current Behavior

nrwl workspace: ^13.3.9

Getting node error: 

`(node:65678) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined at ScriptsWebpackPlugin.shouldSkip (/Users/dornaa01/IdeaProjects/botw-lib/node_modules/@nrwl/web/src/utils/webpack/plugins/scripts-webpack-plugin.js:29:59)`

 when running nx serve with scripts added in projects.json -> targets > build > options > scripts

## Expected Behavior
Safely revive webpack from failing when user makes changes in code. (Live reload shouldn't fail)

## Steps to Reproduce
Add jQuery to scripts for any project's projects.json -> targets > build > options > scripts

### Failure Logs
(node:65678) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at ScriptsWebpackPlugin.shouldSkip (/Users/dornaa01/IdeaProjects/botw-lib/node_modules/@nrwl/web/src/utils/webpack/plugins/scripts-webpack-plugin.js:29:59)
    at /Users/dornaa01/IdeaProjects/botw-lib/node_modules/@nrwl/web/src/utils/webpack/plugins/scripts-webpack-plugin.js:58:22
    at /Users/dornaa01/IdeaProjects/botw-lib/node_modules/@nrwl/web/src/utils/webpack/plugins/scripts-webpack-plugin.js:16:93
    at /Users/dornaa01/IdeaProjects/botw-lib/node_modules/webpack/lib/Compilation.js:591:47
    at fn (/Users/dornaa01/IdeaProjects/botw-lib/node_modules/webpack/lib/Compilation.js:507:9)
    at _next0 (eval at create (/Users/dornaa01/IdeaProjects/botw-lib/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at eval (eval at create (/Users/dornaa01/IdeaProjects/botw-lib/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:58:1)
    at eval (eval at create (/Users/dornaa01/IdeaProjects/botw-lib/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/dornaa01/IdeaProjects/botw-lib/node_modules/webpack/lib/Compilation.js:500:10
    at Hook.eval [as callAsync] (eval at create (/Users/dornaa01/IdeaProjects/botw-lib/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
(node:65678) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 33)
(node:65678) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Environment
Local environment

**Comment by adornala** [comment]
**Temporary fix** to get this resolved:

Open node_modules/@nrwl/web/src/utils/webpack/plugins/scripts-webpack-plugin.js:29:59 and add null check on fileTimestamps

![Screen Shot 2021-12-19 at 2 25 31 AM](https://user-images.githubusercontent.com/8496324/146668487-b7913fee-3dc6-4cd0-ac81-db5dc76183c8.png)


Temporary fix: I have a note to make sure when ever I do an npm install I need to make above change.
