### ISSUE TITLE
missing dependencies on fresh install

### ISSUE THREAD

**Issue by mathpaquette** [nrwl/nx#838]
Hey guys, I'm a little bit confused in the installation process. I'm starting completely from scratch using these commands:

$ node -v
v8.12.0

$ npm -v
6.4.1

npm ls -g --depth=0

npm install -g @angular/cli

npm install -g @nrwl/schematics

$ ng new myworkspacename --collection=@nrwl/schematics
Cannot find module '@angular-devkit/schematics'
Error: Cannot find module '@angular-devkit/schematics'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\freemind\AppData\Roaming\npm\node_modules\@nrwl\schematics\src\collection\ng-new\index.                                js:11:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

Is it working as it suppose to be? Why you're not grabbing all the required dependencies ?

**Comment by bcabanes** [comment]
Hi @mathpaquette,

This issue is because this way of setting up the Nx workspace in **not compatible with npm** and is not the way we recommend creating one.

**We recommend to create a new Nx workspace with the following command**:
```
create-nx-workspace myWorkspaceName
```
You can see more information on [the official documentation here](https://nrwl.io/nx/guide-nx-workspace).

Please, could you point the source where you saw how to do it like that?
_We have updated our doc few releases back but it seems to be a big source of confusion._
