### ISSUE TITLE
[yarn install] Schematic "ngrx" not found in collection "@schematics/angular".

### ISSUE THREAD

**Issue by Matmo10** [nrwl/nx#84]
I installed via yarn:
`yarn add @nrwl/schematics`
`yarn add @nrwl/nx`

Using `@angular/cli@1.5.0`

```
./node_modules/.bin/ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.0
Node: 8.6.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.31
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

When I run `./node_modules/.bin/ng generate ngrx mystate --module=src/app/app.module.ts  --root`, I get the following:

```
Error: Schematic "ngrx" not found in collection "@schematics/angular".
    at NodeModulesEngineHost.createSchematicDescription (/Users/matmo10/new-ng-app/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:126:19)
    at SchematicEngine.createSchematic (/Users/matmo10/new-ng-app/node_modules/@angular-devkit/schematics/src/engine/engine.js:82:40)
    at CollectionImpl.createSchematic (/Users/matmo10/new-ng-app/node_modules/@angular-devkit/schematics/src/engine/collection.js:11:29)
    at Object.getSchematic (/Users/matmo10/new-ng-app/node_modules/@angular/cli/utilities/schematics.js:45:23)
    at Class.run (/Users/matmo10/new-ng-app/node_modules/@angular/cli/tasks/schematic-get-options.js:12:40)
    at Class.beforeRun (/Users/matmo10/new-ng-app/node_modules/@angular/cli/commands/generate.js:90:31)
    at Promise.resolve.then (/Users/matmo10/new-ng-app/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:138:24)
    at <anonymous>
```

I can see the @nrwl packages installed in my node_modules though. I tried installing everything globally also and got the same result.

**Comment by Matmo10** [comment]
I'm just trying to use the ngrx schematics for code generation - not any of the workspace stuff.

**Comment by sylvaindumont** [comment]
You have to add
```json
"schematics": {
  "collection": "@nrwl/schematics"
}
```
in the  `"defaults": {}` section of your `.angular-cli.json` to use `ng generate ngrx` in a classic angular cli project

**Comment by Matmo10** [comment]
Thanks, I'll try that out shortly. I didn't see it in the guide though.

**Comment by Matmo10** [comment]
That works, would be nice to see that mentioned somewhere in the guide though.

**Comment by CharlieGreenman** [comment]
One can see it in the guide here: https://nrwl.io/nx/guide-getting-started at the bottom of the page.
