### ISSUE TITLE
Error: Project name already exists. Although there is no project with that name.

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#8447]
## Current Behavior

Run the command:
```
yarn nx g @nrwl/angular:lib lib-ui-2 --buildable
```
Got an error: 
```
Error: Project name already exists.
    at ProjectDefinitionCollection.add (/Users/wizardnet972/code/nx-cache-problem/node_modules/@angular-devkit/core/src/workspace/definitions.js:88:19)
    at /Users/wizardnet972/code/nx-cache-problem/node_modules/@schematics/angular/library/index.js:67:28
    at /Users/wizardnet972/code/nx-cache-problem/node_modules/@schematics/angular/utility/workspace.js:40:34
```
Although there is no project with that name.. 

https://github.com/wizardnet972/nx-create-lib-problem/blob/main/workspace.json

## Expected Behavior

Create "lib-ui-2" library.

## Steps to Reproduce

Clone:
```
git clone https://github.com/wizardnet972/nx-create-lib-problem.git
yarn
yarn nx g @nrwl/angular:lib lib-ui-2 --buildable
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
 Node : 16.13.0
  OS   : darwin arm64
  yarn : 1.22.11

  nx : 13.4.3
  @nrwl/angular : 13.4.3
  @nrwl/cli : 13.4.3
  @nrwl/cypress : 13.4.3
  @nrwl/devkit : 13.4.3
  @nrwl/eslint-plugin-nx : 13.4.3
  @nrwl/express : undefined
  @nrwl/jest : 13.4.3
  @nrwl/linter : 13.4.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.3
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.3
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.3
  @nrwl/storybook : 13.4.3
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.1.1
  	 @angular/common: 13.1.1
  	 @angular/compiler: 13.1.1
  	 @angular/core: 13.1.1
  	 @angular/forms: 13.1.1
  	 @angular/platform-browser: 13.1.1
  	 @angular/platform-browser-dynamic: 13.1.1
  	 @angular/router: 13.1.1
  	 @angular-devkit/build-angular: 13.1.2
  	 @angular/cli: 13.1.2
  	 @angular/compiler-cli: 13.1.1
  	 @angular/language-service: 13.1.1
  	 @nrwl/js: 13.4.3

```

**Comment by FrozenPandaz** [comment]
Hi this is due to name of the library. Could you run the following instead?

```bash
yarn nx g @nrwl/angular:lib lib-ui2 --buildable
```

**Comment by defaultbranch** [comment]
@FrozenPandaz could you say what the reason for this problem is? I observed that `-\d+-` (numbers between dashes) are sometimes filtered out, eg. when deriving the module name (eg. `epsg-2056-region` leads to `@NgModule class EpsgRegion`.
