### ISSUE TITLE
Error: Cannot find configuration for task build after upgrading from 13.2.x -> 13.4.x

### ISSUE THREAD

**Issue by tbergquist-godaddy** [nrwl/nx#8478]
## Current Behavior

In our monorepo, we are using lerna to deploy packages to a private npm repository.
We are running `nx run @local/packagename:build` in a prepack script in each package to get all relevant packages built. 

This works great on `13.2.x`, but after upgrading to `13.4.x` this no longer works. 

## Expected Behavior

Expected this to still work on latest version.

## Steps to Reproduce

I guess the steps should be explained above, our repository is unfortunately closed source, but I can try to get a minimal reproduction repo going if that helps. 

### Failure Logs

```
yarn nx build @uds/currency-symbol

[2022-01-11T15:07:56.160Z] 

[2022-01-11T15:07:56.727Z] $ /ux-monorepo/node_modules/.bin/nx build @uds/currency-symbol

[2022-01-11T15:08:00.916Z] 

[2022-01-11T15:08:00.916Z] >  NX  Running target build for project @uds/currency-symbol and 3 task(s) that it depends on.

[2022-01-11T15:08:00.916Z]         

[2022-01-11T15:08:00.916Z] 

[2022-01-11T15:08:00.916Z] ���������������������������������������������������������������������������������������������������������������������������������������������

[2022-01-11T15:08:00.916Z] Error: Cannot find configuration for task @ux/whitelabel:build

[2022-01-11T15:08:00.916Z]     at getExecutorNameForTask (/ux-monorepo/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:127:15)

[2022-01-11T15:08:00.916Z]     at getExecutorForTask (/ux-monorepo/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:133:22)

[2022-01-11T15:08:00.916Z]     at getCustomHasher (/ux-monorepo/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:25)

[2022-01-11T15:08:00.916Z]     at TasksSchedule.<anonymous> (/ux-monorepo/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)

[2022-01-11T15:08:00.916Z]     at Generator.next (<anonymous>)

[2022-01-11T15:08:00.916Z]     at /ux-monorepo/node_modules/tslib/tslib.js:117:75

[2022-01-11T15:08:00.916Z]     at new Promise (<anonymous>)

[2022-01-11T15:08:00.916Z]     at __awaiter (/ux-monorepo/node_modules/tslib/tslib.js:113:16)

[2022-01-11T15:08:00.916Z]     at TasksSchedule.hashTask (/ux-monorepo/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:113:38)

[2022-01-11T15:08:00.916Z]     at TasksSchedule.<anonymous> (/ux-monorepo/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:58:24)

[2022-01-11T15:08:00.916Z] Unexpected error:

[2022-01-11T15:08:00.916Z] Error: Unable to load hasher for task "@ux/whitelabel:build"

[2022-01-11T15:08:00.916Z]     at getCustomHasher (/ux-monorepo/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:145:15)

[2022-01-11T15:08:00.917Z]     at TasksSchedule.<anonymous> (/ux-monorepo/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)

[2022-01-11T15:08:00.917Z]     at Generator.next (<anonymous>)

[2022-01-11T15:08:00.917Z]     at /ux-monorepo/node_modules/tslib/tslib.js:117:75

[2022-01-11T15:08:00.917Z]     at new Promise (<anonymous>)

[2022-01-11T15:08:00.917Z]     at __awaiter (/ux-monorepo/node_modules/tslib/tslib.js:113:16)

[2022-01-11T15:08:00.917Z]     at TasksSchedule.hashTask (/ux-monorepo/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:113:38)

[2022-01-11T15:08:00.917Z]     at TasksSchedule.<anonymous> (/ux-monorepo/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:58:24)

[2022-01-11T15:08:00.917Z]     at Generator.next (<anonymous>)

[2022-01-11T15:08:00.917Z]     at /ux-monorepo/node_modules/tslib/tslib.js:117:75

[2022-01-11T15:08:00.917Z] error Command failed with exit code 1.
```

### Environment

```
Node : 16.13.0
  OS   : darwin x64
  yarn : 1.22.17
  
  nx : 13.4.3
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.3
  @nrwl/cypress : undefined
  @nrwl/devkit : 13.4.3
  @nrwl/eslint-plugin-nx : undefined
  @nrwl/express : undefined
  @nrwl/jest : 13.4.3
  @nrwl/linter : 13.4.3
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.3
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.3
  @nrwl/storybook : undefined
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
```

**Comment by FrozenPandaz** [comment]
@leosvelperez was this fixed?

**Comment by tbergquist-godaddy** [comment]
I just upgrade to version 14 now, and it is working now.

**Comment by tbergquist-godaddy** [comment]
No, seems like it is still failing after all.

**Comment by aleixsuau** [comment]
Hi @tbergquist-godaddy 👋 

Did you manage to find a fix for this?

I just migrated to `14.8.4` and I'm having the same issue.
