### ISSUE TITLE
Unexpected end of JSON input when running migrate

### ISSUE THREAD

**Issue by Lightw3ight** [nrwl/nx#8501]
## Current Behavior
When I run `nx migrate latest` I eventually get an error 
`npm ERR! Unexpected end of JSON input while parsing near '..."name":"Hoàng Văn Khả'`

## Expected Behavior
I expect it to generate `migrations.json` and update `package.json`

## Steps to Reproduce
Using my supplied package.json file, attempt to run a migration to the latest nx

I was able to successfully run the migration command after I manually edited the following two files and removed the special characters from the file
`node_modules\cypress\node_modules\@types\node\package.json` (Version 14.14.33)
`node_modules\@types\node\package.json` (Version 12.12.50)

### Failure Logs

Console log:
```
❯ nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching prettier@^2.3.1
Fetching typescript@~4.3.5
Fetching dotenv@~10.0.0
Fetching @nrwl/angular@13.4.4
Fetching @nrwl/cli@13.4.4
Fetching @nrwl/cypress@13.4.4
Fetching @nrwl/devkit@13.4.4
Fetching @nrwl/eslint-plugin-nx@13.4.4
Fetching @nrwl/jest@13.4.4
Fetching @nrwl/linter@13.4.4
Fetching @nrwl/node@13.4.4
Fetching @nrwl/nx-cloud@latest
Fetching @nrwl/tao@13.4.4
Fetching @ngrx/store@~13.0.0
Fetching @ngrx/effects@~13.0.0
Fetching @ngrx/store-devtools@~13.0.0
Fetching @ngrx/component-store@~13.0.0
Fetching @angular-eslint/eslint-plugin@~13.0.1
Fetching @angular-eslint/eslint-plugin-template@~13.0.1
Fetching @angular-eslint/template-parser@~13.0.1
Fetching @angular/cli@~13.1.0
Fetching @angular-devkit/build-angular@~13.1.0
Fetching @angular/core@~13.1.0
Fetching @angular/common@~13.1.0
Fetching @angular/forms@~13.1.0
Fetching @angular/compiler@~13.1.0
Fetching @angular/compiler-cli@~13.1.0
Fetching @angular/platform-browser@~13.1.0
Fetching @angular/platform-browser-dynamic@~13.1.0
Fetching @angular/router@~13.1.0
Fetching @angular/language-service@~13.1.0
Fetching @angular/animations@~13.1.0
Fetching zone.js@~0.11.4
Fetching ng-packagr@~13.1.0
Fetching typescript@~4.5.2
Fetching @angular/cdk@~13.1.0
Fetching jest-preset-angular@11.0.0
Fetching @angular/localize@~13.1.0
Fetching jest-preset-angular@9.0.3
Fetching ts-jest@27.0.5
Fetching jest@27.2.3
Fetching @types/jest@27.0.2
Fetching @typescript-eslint/parser@~5.3.0
Fetching @typescript-eslint/eslint-plugin@~5.3.0
Fetching eslint@8.2.0

 ERROR  The migrate command failed.

Command failed: npm install @nrwl/node@13.4.4
npm ERR! Unexpected end of JSON input while parsing near '..."name":"Hoàng Văn Khả'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2022-01-12T22_36_54_512Z-debug.log

C:\xxx\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\xxxC\AppData\Local\Temp\tmp-36452S8jXHa30eBjV\node_modules\.bin\tao migrate latest
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at Object.handler (C:\xxx\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:80:25)
    at Object.runCommand (C:\xxx\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\xxx\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\xxx\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\xxx\node_modules\@nrwl\cli\lib\init-local.js:23:13)
    at Object.<anonymous> (C:\xxx\node_modules\@nrwl\cli\bin\nx.js:42:18)
    at Module._compile (C:\Users\xxx\AppData\Roaming\npm\node_modules\nx\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 21084,
  stdout: null,
  stderr: null
}
```

Package.json file:

```json
{
    "name": "xxx",
    "version": "0.0.0",
    "scripts": {
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^11.2.0",
        "@angular/cdk": "^11.2.13",
        "@angular/common": "^11.2.0",
        "@angular/compiler": "^11.2.0",
        "@angular/core": "^11.2.0",
        "@angular/forms": "^11.2.0",
        "@angular/localize": "^11.2.0",
        "@angular/platform-browser": "^11.2.0",
        "@angular/platform-browser-dynamic": "^11.2.0",
        "@angular/router": "^11.2.0",
        "@auth0/auth0-angular": "^1.8.0",
        "@emotion/core": "^10.1.1",
        "@infragistics/igniteui-angular": "^11.1.2",
        "@ngrx/component-store": "^10.1.2",
        "@ngrx/effects": "^10.1.2",
        "@ngrx/store": "^10.1.2",
        "@nrwl/angular": "11.6.3",
        "@nrwl/nx-cloud": "^11.2.0",
        "accounting-js": "^1.1.1",
        "ag-grid-angular": "25.0.1",
        "ag-grid-community": "25.0.1",
        "bignumber.js": "~2.4.0",
        "chart.js": "^2.9.4",
        "date-fns": "^2.23.0",
        "emotion": "^10.0.27",
        "enzyme": "^3.11.0",
        "jsbarcode": "^3.11.0",
        "mobx": "^5.15.4",
        "mobx-react-lite": "^2.2.2",
        "moment": "^2.29.1",
        "ng2-charts": "^2.4.3",
        "ngrx-store-logger": "^0.2.4",
        "ngx-color": "^6.2.0",
        "ngx-markdown": "^11.1.3",
        "prismjs": "^1.24.1",
        "qrcode": "^1.4.4",
        "quill": "^1.3.7",
        "quill-delta": "^3.6.3",
        "quill-delta-to-html": "^0.7.2",
        "ramda": "^0.27.1",
        "rxjs": "~6.6.3",
        "tslib": "^2.0.0",
        "unique-names-generator": "^4.6.0",
        "web-animations-js": "^2.3.2",
        "zone.js": "^0.10.2"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.1102.0",
        "@angular-eslint/eslint-plugin": "~1.0.0",
        "@angular-eslint/eslint-plugin-template": "~1.0.0",
        "@angular-eslint/template-parser": "~1.0.0",
        "@angular/cli": "~11.0.0",
        "@angular/compiler-cli": "^11.2.0",
        "@angular/language-service": "^11.2.0",
        "@hirez_io/observer-spy": "^2.1.0",
        "@ngrx/store-devtools": "^10.1.2",
        "@nrwl/cli": "11.6.3",
        "@nrwl/cypress": "11.6.3",
        "@nrwl/devkit": "11.6.3",
        "@nrwl/eslint-plugin-nx": "11.6.3",
        "@nrwl/jest": "11.6.3",
        "@nrwl/linter": "11.6.3",
        "@nrwl/node": "11.6.3",
        "@nrwl/tao": "11.6.3",
        "@nrwl/workspace": "11.6.3",
        "@phenomnomnominal/tsquery": "^4.1.1",
        "@types/adm-zip": "^0.4.34",
        "@types/chart.js": "^2.9.34",
        "@types/commander": "^2.12.2",
        "@types/enzyme": "^3.10.9",
        "@types/fs-extra": "^9.0.12",
        "@types/jasmine": "~3.6.0",
        "@types/jest": "26.0.8",
        "@types/node": "14.14.33",
        "@types/node-fetch": "^2.5.12",
        "@types/prismjs": "^1.16.6",
        "@types/qrcode": "^1.3.4",
        "@types/quill": "^1.3.6",
        "@types/ramda": "^0.27.44",
        "@types/svgo": "2.4.0",
        "@types/xml2js": "^0.4.9",
        "@typescript-eslint/eslint-plugin": "4.19.0",
        "@typescript-eslint/parser": "4.19.0",
        "adm-zip": "^0.5.5",
        "azure-devops-node-api": "^11.0.1",
        "commander": "^8.2.0",
        "copyfiles": "^2.4.1",
        "cypress": "^6.0.1",
        "dotenv": "8.2.0",
        "emailjs": "^3.5.0",
        "eslint": "7.10.0",
        "eslint-config-prettier": "8.1.0",
        "eslint-plugin-cypress": "^2.10.3",
        "fs-extra": "^10.0.0",
        "ineeda": "^0.11.3",
        "jasmine-core": "~3.6.0",
        "jasmine-spec-reporter": "~5.0.0",
        "jest": "26.2.2",
        "jest-preset-angular": "8.3.2",
        "karma": "~6.3.3",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage": "^2.0.3",
        "karma-jasmine": "~4.0.0",
        "karma-jasmine-html-reporter": "^1.5.0",
        "ng-packagr": "^11.0.0",
        "node-fetch": "^2.6.1",
        "prettier": "2.2.1",
        "stylelint": "^13.8.0",
        "stylelint-config-prettier": "^8.0.2",
        "stylelint-prettier": "^1.1.2",
        "stylelint-scss": "^3.18.0",
        "svgo": "~2.4.0",
        "ts-jest": "26.4.0",
        "ts-node": "~9.1.1",
        "typescript": "~4.1.3",
        "xml2js": "^0.4.23"
    }
}
```

### Environment
  Node : 12.22.6
  OS   : win32 x64
  npm  : 6.14.15

  nx : Not Found
  @nrwl/angular : 11.6.3
  @nrwl/cli : 11.6.3
  @nrwl/cypress : 11.6.3
  @nrwl/devkit : 11.6.3
  @nrwl/eslint-plugin-nx : 11.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.3
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.6.3
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.3
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.6

**Comment by FrozenPandaz** [comment]
Hi, could you please try migrating to `12.10.0` first before migrating to `13.x`?

Also, could you provide a repo that we could pull down and reproduce the issue?

**Comment by Lightw3ight** [comment]
Sorry, as I mentioned, I was able to work around the issue by editing the files in my node_modules folder, so I have successfully migrated to 13 and dont have something to reproduce, I just figured I should post here so you were aware of it
