### ISSUE TITLE
Storybook is not running after compodoc added

### ISSUE THREAD

**Issue by vrady** [nrwl/nx#8554]
## Current Behavior
After adding compodoc for the library and setup it in preview.js, storybook fails on start.

Its not fails when you do this step by step from scratch, but when you delete `package-lock.json` and `node_modules` and then reinstall it, Storybook fails with errors below. Or pull this repo on another machine and try to start Storybook after `npm install`

Seems like storybook dependency looking for `node_modules/@babel/runtime/regenerator/index.js`. But the path of it not absolute from root folder, its relative to `node_modules/@angular-devkit/build-angular` and there is no correct path `/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js`

Maybe there is solution how to configure it or fix this issue?

## Expected Behavior
Storybook should launch via `@nrwl/storybook:storybook` executor

## Steps to Reproduce

1. Install empty Nx workspace
2. Add angular app
3. Add angular library
4. Add some component in library
5. Add storybook for the library
6. Storybook works on this step
7. Add @twittwer/compodoc to nx and generate compodoc for the library
8. Add compodoc code to the preview.js of library storybook
9. Run storybook and its fail

Example project: https://github.com/vrady/angular-storybook

### Failure Logs
```
ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js' in '/Users/vrady/WebstormProjects/angular-storybook/node_modules/@storybook/addon-docs/dist/esm/blocks'
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/vrady/WebstormProjects/angular-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/vrady/WebstormProjects/angular-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/neo-async/async.js:6883:13
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/Users/vrady/WebstormProjects/angular-storybook/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/vrady/WebstormProjects/angular-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
resolve '/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js' in '/Users/vrady/WebstormProjects/angular-storybook/node_modules/@storybook/addon-docs/dist/esm/blocks'
  using description file: /Users/vrady/WebstormProjects/angular-storybook/node_modules/@storybook/addon-docs/package.json (relative path: ./dist/esm/blocks)
    Field 'browser' doesn't contain a valid alias configuration
    root path /Users/vrady/WebstormProjects/angular-storybook
      using description file: /Users/vrady/WebstormProjects/angular-storybook/package.json (relative path: ./Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js)
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /Users/vrady/WebstormProjects/angular-storybook/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
          /Users/vrady/WebstormProjects/angular-storybook/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /Users/vrady/WebstormProjects/angular-storybook/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.js doesn't exist
        .jsx
          Field 'browser' doesn't contain a valid alias configuration
          /Users/vrady/WebstormProjects/angular-storybook/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.jsx doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
          /Users/vrady/WebstormProjects/angular-storybook/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
          /Users/vrady/WebstormProjects/angular-storybook/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.tsx doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          /Users/vrady/WebstormProjects/angular-storybook/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.json doesn't exist
        .cjs
          Field 'browser' doesn't contain a valid alias configuration
          /Users/vrady/WebstormProjects/angular-storybook/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.cjs doesn't exist
        as directory
          /Users/vrady/WebstormProjects/angular-storybook/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js doesn't exist
    using description file: /Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/package.json (relative path: ./node_modules/@babel/runtime/regenerator/index.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.jsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.tsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.json doesn't exist
      .cjs
        Field 'browser' doesn't contain a valid alias configuration
        /Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js.cjs doesn't exist
      as directory
        /Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/vrady/WebstormProjects/angular-storybook/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/regenerator/index.js' in '/Users/vrady/WebstormProjects/angular-storybook/node_modules/@storybook/addon-docs/dist/esm/frameworks/angular'
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/vrady/WebstormProjects/angular-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/vrady/WebstormProjects/angular-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/neo-async/async.js:6883:13
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/Users/vrady/WebstormProjects/angular-storybook/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/vrady/WebstormProjects/angular-storybook/node_modules/enhanced-resolve/lib/Resolver.js:410:5
```

### Environment
```
Report complete - copy this into the issue template

  Node : 14.18.3
  OS   : darwin x64
  npm  : 6.14.15
  
  nx : 13.4.5
  @nrwl/angular : 13.4.5
  @nrwl/cli : 13.4.5
  @nrwl/cypress : 13.4.5
  @nrwl/devkit : 13.4.5
  @nrwl/eslint-plugin-nx : 13.4.5
  @nrwl/express : undefined
  @nrwl/jest : 13.4.5
  @nrwl/linter : 13.4.5
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.5
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.5
  @nrwl/storybook : 13.4.5
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.1.2
         @angular/common: 13.1.2
         @angular/compiler: 13.1.2
         @angular/core: 13.1.2
         @angular/forms: 13.1.2
         @angular/platform-browser: 13.1.2
         @angular/platform-browser-dynamic: 13.1.2
         @angular/router: 13.1.2
         @twittwer/compodoc: 1.6.6
         @angular-devkit/build-angular: 13.1.3
         @angular/cli: 13.1.3
         @angular/compiler-cli: 13.1.2
         @angular/language-service: 13.1.2
         @compodoc/compodoc: 1.1.18
         @storybook/angular: 6.4.12
```

**Comment by hudzenko** [comment]
Happens for me as well!

**Comment by mandarini** [comment]
Hi there @vrady !

I could get it to run without errors after I added the `projectBuildConfig` option to the `build-storybook` target. 
I see you have set the `projectBuildConfig` option on the `storybook` target. If you set it on the `build-storybook` target as well, it should run. 

In your `libs/ui/project.json`
```
    "build-storybook": {
      "executor": "@nrwl/storybook:build",
      "outputs": ["{options.outputPath}"],
      "options": {
        "uiFramework": "@storybook/angular",
        "outputPath": "dist/storybook/ui",
        "config": {
          "configFolder": "libs/ui/.storybook"
        },
       "projectBuildConfig": "ui:build-storybook"
      },
      "configurations": {
        "ci": {
          "quiet": true
        }
      }
    },
```

Let me know please if that fixes your issue. We also have a [PR](https://github.com/nrwl/nx/pull/8494) coming up which will help out in such issues in the future.

**Comment by vrady** [comment]
> Hi there @vrady !
> 
> I could get it to run without errors after I added the `projectBuildConfig` option to the `build-storybook` target. I see you have set the `projectBuildConfig` option on the `storybook` target. If you set it on the `build-storybook` target as well, it should run.
> 
> In your `libs/ui/project.json`
> 
> ```
>     "build-storybook": {
>       "executor": "@nrwl/storybook:build",
>       "outputs": ["{options.outputPath}"],
>       "options": {
>         "uiFramework": "@storybook/angular",
>         "outputPath": "dist/storybook/ui",
>         "config": {
>           "configFolder": "libs/ui/.storybook"
>         },
>        "projectBuildConfig": "ui:build-storybook"
>       },
>       "configurations": {
>         "ci": {
>           "quiet": true
>         }
>       }
>     },
> ```
> 
> Let me know please if that fixes your issue. We also have a [PR](https://github.com/nrwl/nx/pull/8494) coming up which will help out in such issues in the future.

Hi,  thanks for your response!

I've added `projectBuildConfig` to the storybook target as you mention above. It was still not working, but I upgraded `angular` to version `13.1.2` and especially `@angular-devkit/build-angular` to `13.1.3` and then Storybook runs.

The problem was in `@angular-devkit/build-angular` version, I had `13.1.2` version, which not works with this storybook config. I've updated via `--force` flag, because we have `@nguniversal` on our project, and this dependency not allows us update Angular to latest `13.1.2` version (I hope that guys from Universal will release new tag soon with updated dependencies)

Thanks, for help 😊
