### ISSUE TITLE
Parallel builds in gitlab fails with ERR_STREAM_NULL_VALUES

### ISSUE THREAD

**Issue by the-ult** [nrwl/nx#8565]
## Current Behavior
A parallel build (`run-many`) fails in gitlab-ci with:
```
TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
```

## Steps to Reproduce
_Seems to be an issue since NX 13.4.4_

In our `gitlab-ci`
```
pnpm nx  run-many -- --all --target=build --prod --parallel --maxParallel=3
# Fails with npm as well
# and with the default parallel settings as well.
# only `parallel=1 fixes the problem
```

`nx.json`
```json
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/workspace/tasks-runners/default",
      "options": {
        "parallel": 3,
        "cacheDirectory": "./.cache/nx",
        "cacheableOperations": ["build", "lint", "test", "e2e", "build-storybook"],
        "useDeamonProcess": true
      }
    }
  },

```

### Failure Logs
```console
> nx run my-app:build:production 
node:internal/streams/writable:299
    throw new ERR_STREAM_NULL_VALUES();
    ^
TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
    at new NodeError (node:internal/errors:371:5)
    at _write (node:internal/streams/writable:299:11)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at RunManyTerminalOutputLifeCycle.printTaskTerminalOutput (/builds/.../.../node_modules/.pnpm/@nrwl+workspace@13.4.4_451c6917a69c5c23f897ab677b8e83cf/node_modules/@nrwl/workspace/src/tasks-runner/run-many-terminal-output-life-cycle.js:87:24)
    at CompositeLifeCycle.printTaskTerminalOutput (/.../.../node_modules/.pnpm/@nrwl+workspace@13.4.4_451c6917a69c5c23f897ab677b8e83cf/node_modules/@nrwl/workspace/src/tasks-runner/life-cycle.js:66:19)
    at ChildProcess.<anonymous> (/.../.../node_modules/.pnpm/@nrwl+workspace@13.4.4_451c6917a69c5c23f897ab677b8e83cf/node_modules/@nrwl/workspace/src/tasks-runner/forked-process-task-runner.js:140:48)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  code: 'ERR_STREAM_NULL_VALUES'
}
 ELIFECYCLE  Command failed with exit code 1.
```

### Environment
```console
>  NX  Report complete - copy this into the issue template
  Node : 16.7.0
  OS   : linux x64
  pnpm : 6.26.1
  
  nx : undefined
  @nrwl/angular : 13.4.4
  @nrwl/cli : 13.4.4
  @nrwl/cypress : 13.4.4
  @nrwl/devkit : undefined
  @nrwl/eslint-plugin-nx : 13.4.4
  @nrwl/express : 13.4.4
  @nrwl/jest : 13.4.4
  @nrwl/linter : 13.4.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.4
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.4
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.4
  @nrwl/storybook : 13.4.5
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 7.5.2
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.1.2
  	 @angular/cdk: 13.1.2
  	 @angular/common: 13.1.2
  	 @angular/compiler: 13.1.2
  	 @angular/core: 13.1.2
  	 @angular/forms: 13.1.2
  	 @angular/material: 13.1.2
  	 @angular/material-date-fns-adapter: 13.1.2
  	 @angular/platform-browser: 13.1.2
  	 @angular/platform-browser-dynamic: 13.1.2
  	 @angular/router: 13.1.2
  	 @taiga-ui/core: 2.29.0
  	 apollo-angular: 2.6.0
  	 @angular-devkit/build-angular: 13.1.3
  	 @angular/cli: 13.1.3
  	 @angular/compiler-cli: 13.1.2
  	 @angular/language-service: 13.1.2
  	 @jscutlery/semver: 2.17.5
  	 @ngneat/aim: 2.0.0
  	 @nrwl/js: 13.4.4
  	 @storybook/angular: 6.4.13
  	 @testing-library/angular: 11.0.2
```

**Comment by jasonmacdonald** [comment]
I just started getting this a well. Not sure why.

**Comment by ricardotestuser** [comment]
subscribe

**Comment by vsavkin** [comment]
It looks like the file with the terminal output wasn't written. I sent a PR showing the error: https://github.com/nrwl/nx/pull/8623

**Comment by the-ult** [comment]
Will try it out next week 👍

**Comment by jredl-va** [comment]
I was going to open a similar issue for this, but its already open. The difference we are running our builds via google cloud build. 

NX Report:

```
   Node : 14.18.3
   OS   : darwin x64 (this is from my local machine not the build machines)
   npm  : 6.14.15

   nx : undefined
   @nrwl/angular : 13.5.2
   @nrwl/cli : 13.5.2
   @nrwl/cypress : 13.5.2
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.2
   @nrwl/eslint-plugin-nx : 13.5.2
   @nrwl/express : undefined
   @nrwl/jest : 13.5.2
   @nrwl/js : undefined
   @nrwl/linter : 13.5.2
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.2
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 13.5.2
   @nrwl/tao : 13.5.2
   @nrwl/web : undefined
   @nrwl/workspace : 13.5.2
   typescript : 4.5.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
   	 @angular-devkit/architect: 0.1301.4
   	 @angular/animations: 13.1.3
   	 @angular/cdk: 13.1.3
   	 @angular/common: 13.1.3
   	 @angular/compiler: 13.1.3
   	 @angular/core: 13.1.3
   	 @angular/elements: 13.1.3
   	 @angular/fire: 6.1.4
   	 @angular/forms: 13.1.3
   	 @angular/localize: 13.1.3
   	 @angular/material: 13.1.3
   	 @angular/material-moment-adapter: 13.1.3
   	 @angular/platform-browser: 13.1.3
   	 @angular/platform-browser-dynamic: 13.1.3
   	 @angular/router: 13.1.3
   	 @angular/service-worker: 13.1.3
   	 @ngrx/effects: 13.0.1
   	 @ngrx/store: 13.0.1
   	 @ngrx/store-devtools: 13.0.1
   	 angular-calendar: 0.28.26
   	 ngx-bootstrap: 6.2.0
   	 @angular-builders/custom-webpack: 13.0.0
   	 @angular-devkit/build-angular: 13.1.4
   	 @angular/cli: 13.1.4
   	 @angular/compiler-cli: 13.1.3
   	 @angular/language-service: 13.1.3
   	 @ngneat/spectator: 6.1.3
   	 @testing-library/angular: 10.11.0
```

The google cloud build step: 
```
  - name: 'node:14'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npx nx affected:build --base=$BASE --head=$HEAD --with-deps --prod --parallel
    waitFor: ['npm-install']
```


The build output: 

``` 
internal/streams/writable.js:272
    throw new ERR_STREAM_NULL_VALUES();
    ^

TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
    at new NodeError (internal/errors.js:322:7)
    at Socket.Writable.write (internal/streams/writable.js:272:11)
    at RunManyTerminalOutputLifeCycle.printTaskTerminalOutput (/workspace/node_modules/@nrwl/workspace/src/tasks-runner/run-many-terminal-output-life-cycle.js:87:24)
    at CompositeLifeCycle.printTaskTerminalOutput (/workspace/node_modules/@nrwl/workspace/src/tasks-runner/life-cycle.js:66:19)
    at CompositeLifeCycle.printTaskTerminalOutput (/workspace/node_modules/@nrwl/workspace/src/tasks-runner/life-cycle.js:66:19)
    at ChildProcess.<anonymous> (/workspace/node_modules/@nrwl/workspace/src/tasks-runner/forked-process-task-runner.js:140:48)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12) {
  code: 'ERR_STREAM_NULL_VALUES'
}
```

**Comment by ubergeoff** [comment]
This was also happening to me on CI. 
I then switched to `parallel="1"` - which seems to have sorted it out initially.

```
"tasksRunnerOptions": {
        "default": {
            "runner": "@nrwl/workspace/tasks-runners/default",
            "options": {
                "cacheableOperations": ["build", "lint", "test"],
                "parallel": 1,
                "useDeamonProcess": true,
                "cacheDirectory": "./.cache/nx"
            }
        }
    },
```

But now - I still see this error happen intermittently on my CI even with  `parallel="1"`

**Comment by yackinn** [comment]
We also see a similar error on version 13.5.3 no matter using parallel or non parallel execution.
This error only occurs inside jenkins pipelines. It's running correctly locally.
Before updating nx the issue didn't exist.

```
...
11:09:50  Test Suites: 1 passed, 1 total
11:09:50  Tests:       26 passed, 26 total
11:09:50  Snapshots:   0 total
11:09:50  Time:        8.68 s
11:09:50  Ran all test suites.
11:10:03  buffer.js:1069								// it seems this happens when starting the next test suite
11:10:03      return this.utf8Write(string, 0, this.length);
11:10:03                  ^
11:10:03  
11:10:03  TypeError: argument must be a string
11:10:03      at Buffer.write (buffer.js:1069:17)
11:10:03      at SyncWriteStream.process.stdout._write (/home/jenkins/project/workspace/m-frontend_feat_update-workspace/node_modules/@nrwl/cli/lib/run-cli.js:43:20)
11:10:03      at writeOrBuffer (internal/streams/writable.js:358:12)
11:10:03      at SyncWriteStream.Writable.write (internal/streams/writable.js:303:10)
11:10:03      at flushBufferedOutput (/home/jenkins/project/workspace/m-frontend_feat_update-workspace/node_modules/@jest/core/node_modules/@jest/reporters/build/DefaultReporter.js:113:9)
11:10:03      at Timeout._onTimeout (/home/jenkins/project/workspace/m-frontend_feat_update-workspace/node_modules/@jest/core/node_modules/@jest/reporters/build/DefaultReporter.js:132:13)
11:10:03      at listOnTimeout (internal/timers.js:557:17)
11:10:03      at processTimers (internal/timers.js:500:7) {
11:10:03    code: 'ERR_INVALID_ARG_TYPE'
11:10:03  }
```
That's the command we're running.
`nx run-many --all --target=test`

```json
 "@nrwl/angular": "13.5.3",
"@nrwl/cli": "13.5.3",
"@nrwl/cypress": "13.5.3",
"@nrwl/eslint-plugin-nx": "13.5.3",
"@nrwl/jest": "13.5.3",
"@nrwl/linter": "13.5.3",
"@nrwl/nest": "13.5.3",
"@nrwl/node": "13.5.3",
"@nrwl/tao": "13.5.3",
"@nrwl/workspace": "13.5.3",
```

**Comment by yackinn** [comment]
Using `--runInBand` the error changes slightly when ran in jenkins.

```
16:05:09  > nx run personal-data-server:test --verbose=false --silent --runInBand
16:05:09  
16:05:09  ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfig" is deprecated, use "[jest-config].globals.ts-jest.tsconfig" instead.
16:05:09  ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to help migrating it: ts-jest config:migrate <config-file>.
16:05:09  PASS personal-data-server libs/personal-data/server/src/lib/controller/personal-data.controller.spec.ts (9.393 s)
16:05:09  FAIL personal-data-server libs/personal-data/server/src/lib/controller/personal-data.controller.spec.ts
16:05:09    ● Test suite failed to run
16:05:09  
16:05:09      TypeError: argument must be a string
16:05:09  
16:05:09        at SyncWriteStream.process.stdout._write (../../../packages/cli/lib/run-cli.ts:53:16)
16:05:09        at flushBufferedOutput (../../../node_modules/@jest/core/node_modules/@jest/reporters/build/DefaultReporter.js:113:9)
16:05:09        at DefaultReporter.forceFlushBufferedOutput (../../../node_modules/@jest/core/node_modules/@jest/reporters/build/DefaultReporter.js:148:7)
16:05:09        at DefaultReporter.onTestResult (../../../node_modules/@jest/core/node_modules/@jest/reporters/build/DefaultReporter.js:214:10)
16:05:09        at ReporterDispatcher.onTestFileResult (../../../node_modules/@jest/core/build/ReporterDispatcher.js:52:24)
16:05:09        at onResult (../../../node_modules/@jest/core/build/TestScheduler.js:195:30)
16:05:09        at ../../../node_modules/@jest/core/build/TestScheduler.js:316:17
```

**Comment by ubergeoff** [comment]
Just an update - my "intermittent" issues have gone away. Everything all good again - using:

```
        "@nrwl/cli": "13.5.3",
        "@nrwl/cypress": "13.5.3",
        "@nrwl/eslint-plugin-nx": "13.5.3",
        "@nrwl/jest": "13.5.3",
        "@nrwl/linter": "13.5.3",
        "@nrwl/tao": "13.5.3",
```

Also switch to:

```
        "jest": "27.4.7",
        "jest-canvas-mock": "^2.3.1",
        "jest-preset-angular": "~11.0.1",
```

**Comment by jredl-va** [comment]
@ubergeoff @vsavkin I was also able to resolve this on the pinned jest commits. I have no idea why but I haven't seen these build failures since rolling forward. 

![image](https://user-images.githubusercontent.com/2300103/152245941-d5fb6ca0-8fc5-43f2-8de8-b05a5481882b.png)
