### ISSUE TITLE
"Cannot find configuration for task" on project with preserved existing structure and Nx 13

### ISSUE THREAD

**Issue by DRYmag** [nrwl/nx#8585]
# Current Behavior

I try to migrate to Nx 13 and tasks on our primary application (the one whois not in the apps directory but still in `src/app` because we have [preserved our structure](https://nx.dev/migration/migration-angular#using-ng-add-and-preserving-your-existing-structure)) don't work, they throw an error : 
```
$ ng test client
Error: Cannot find configuration for task client:test
    at getExecutorNameForTask (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\src\tasks-runner\utils.js:127:15)
    at getExecutorForTask (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\src\tasks-runner\utils.js:133:22)
    at getCustomHasher (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\src\tasks-runner\utils.js:140:25)
    at TasksSchedule.<anonymous> (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\src\tasks-runner\tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\node_modules\tslib\tslib.js:113:16)
    at TasksSchedule.hashTask (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\src\tasks-runner\tasks-schedule.js:113:38)
    at TasksSchedule.<anonymous> (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\src\tasks-runner\tasks-schedule.js:58:24)
Unexpected error:
Error: Unable to load hasher for task "client:test"
    at getCustomHasher (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\src\tasks-runner\utils.js:145:15)
    at TasksSchedule.<anonymous> (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\src\tasks-runner\tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\node_modules\tslib\tslib.js:113:16)
    at TasksSchedule.hashTask (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\src\tasks-runner\tasks-schedule.js:113:38)
    at TasksSchedule.<anonymous> (D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\src\tasks-runner\tasks-schedule.js:58:24)
    at Generator.next (<anonymous>)
    at D:\Arya\Arya-frontend\node_modules\@nrwl\workspace\node_modules\tslib\tslib.js:117:75
```

# Expected Behavior

Tasks like `ng server`, `ng test`, ... work fine on all applications/libs.

# Steps to Reproduce

This can be easily reproduce wwith a fresh project :
- create a new Angular project : `ng new test`
- add Nx with preserving structure : `ng add @nrwl/workspace --preserveAngularCLILayout`
- execute a task for example : `ng serve`

The task doesn't start, it throw an error, even if I try to update the config with `project.json` file per project like explained [here](https://nx.dev/getting-started/nx-and-angular#angularjson).

# Environment

```
Node : 16.13.2
  OS   : win32 x64
  npm  : 8.3.1

  nx : 13.4.5
  @nrwl/angular : 13.4.5
  @nrwl/cli : 13.4.5
  @nrwl/cypress : 13.4.5
  @nrwl/devkit : 13.4.5
  @nrwl/eslint-plugin-nx : 13.4.5
  @nrwl/express : undefined
  @nrwl/jest : 13.4.5
  @nrwl/linter : 13.4.5
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.5
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.5
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.5
  @nrwl/storybook : 13.4.5
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 6.6.3
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.1.2
         @angular/cdk: 13.1.2
         @angular/common: 13.1.2
         @angular/compiler: 13.1.2
         @angular/core: 13.1.2
         @angular/forms: 13.1.2
         @angular/localize: 13.1.2
         @angular/platform-browser: 13.1.2
         @angular/platform-browser-dynamic: 13.1.2
         @angular/router: 13.1.2
         @syncfusion/ej2-angular-schedule: 19.2.46
         ng-zorro-antd: 12.0.1
         @angular-devkit/build-angular: 13.1.3
         @angular-eslint/builder: 12.0.0
         @angular-eslint/schematics: 12.3.1
         @angular/cli: 13.1.3
         @angular/compiler-cli: 13.1.2
         @angular/language-service: 13.1.2
```

**Comment by vsavkin** [comment]
Thank you for submitting the issue!

Can you provide a repo with a repro?

**Comment by DRYmag** [comment]
Our repos is private but you can check this one (I just follow the "Steps to Reproduce" section) : https://github.com/DRYmag/nxissue8585demo

**Comment by FrozenPandaz** [comment]
Thank you for the reproduction. I was able to find and fix the issue :smile:

**Comment by DRYmag** [comment]
Thank for your support, that's a good news !
