### ISSUE TITLE
Angular project: migration task failed for add-missing-root-babel-config 

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#8645]
I am getting errors while running the following migration job: add-missing-root-babel-config

```
Running migration add-missing-root-babel-config

Cannot convert undefined or null to object
../node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/v6/7bsk5h7x67j6gqkrmvj5wnn80000gp/T/tmp-12775-wodO1X1nbD3T/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:640:11)
    at execSync (child_process.js:676:15)
    at Object.handler (../node_modules/@nrwl/workspace/src/command-line/nx-commands.js:125:42)
    at Object.runCommand (../node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (../node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (../node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at initLocal (../node_modules/@nrwl/cli/lib/init-local.js:27:79)
    at Object.<anonymous> (../node_modules/@nrwl/cli/bin/nx.js:45:32)
    at Module._compile (/usr/local/lib/node_modules/@nrwl/cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12810,
  stdout: null,
  stderr: null
}
```

Can someone please advise on this?

**Comment by bradtaniguchi** [comment]
I did a little digging, and found that this commit will prevent this from happening:
93095f561a81c812e29ccc19a121314a66d8c9b4

Which also points to this issue:
#8566

So this issue is probably a dupe of 8566.

---

You can get the fix **now** with:
```
npm install --save-dev @nrwl/jest@13.5.0-beta.9
```
then running the migration.

**Comment by dean-g** [comment]
Thank you @bradtaniguchi. that is worked!
