### ISSUE TITLE
@nrwl:angular:library - NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by sir-captainmorgan21** [nrwl/nx#8655]
## Current Behavior
When I run... `npx nx generate @nrwl/angular:library --name=adobe --no-interactive --dry-run` I get the following. Removing dry run doesn't change the result. @nrwl/workspace:library works fine.

```
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/codegen/index.js:568:18)
```

## Expected Behavior
I'd expect this to be able to show the results of the dry run and run successfully.

## Steps to Reproduce
Use @nrwl/angular:library generator to create a library.

### Failure Logs
```
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/zach.morgan/Development/Web.Seeker/node_modules/ajv/dist/compile/codegen/index.js:568:18)
```

### Environment
```
Node : 16.12.0
  OS   : darwin x64
  npm  : 8.1.0
  
  nx : 13.4.6
  @nrwl/angular : 13.3.0
  @nrwl/cli : 13.3.0
  @nrwl/cypress : 13.3.0
  @nrwl/devkit : 13.1.3
  @nrwl/eslint-plugin-nx : 13.3.0
  @nrwl/express : undefined
  @nrwl/jest : 13.3.0
  @nrwl/linter : 13.3.0
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.0
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.0
  @nrwl/storybook : 13.3.0
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.1.0
  	 @angular/cdk: 13.1.0
  	 @angular/common: 13.1.0
  	 @angular/compiler: 13.1.0
  	 @angular/core: 13.1.0
  	 @angular/forms: 13.1.0
  	 @angular/material: 13.1.0
  	 @angular/platform-browser: 13.1.0
  	 @angular/platform-browser-dynamic: 13.1.0
  	 @angular/platform-server: 13.1.0
  	 @angular/router: 13.1.0
  	 @angular/service-worker: 13.1.0
  	 @ngrx/effects: 13.0.2
  	 @ngrx/router-store: 13.0.2
  	 @ngrx/store: 13.0.2
  	 @ngrx/store-devtools: 13.0.2
  	 @nguniversal/aspnetcore-engine: 13.0.1
  	 @nguniversal/common: 13.0.1
  	 @nguniversal/express-engine: 13.0.1
  	 @angular-builders/custom-webpack: 13.0.0
  	 @angular-devkit/build-angular: 13.0.4
  	 @angular-devkit/build-ng-packagr: 0.1000.4
  	 @angular-eslint/builder: 13.0.1
  	 @angular-eslint/schematics: 13.0.1
  	 @angular/cli: 13.0.4
  	 @angular/compiler-cli: 13.1.0
  	 @angular/language-service: 13.1.0
  	 @nguniversal/builders: 13.0.1
  	 @wdio/schematics: 1.2.1
```

**Comment by sir-captainmorgan21** [comment]
NVM on this. We were on a crazy old version of @shcematics/angular. So FYI, you should not have to explicitly have @schematics/angular as a dependency of your app. @angular/cli and @nrwl both take care of that for you.

**Comment by sir-captainmorgan21** [comment]
@simcoder upgrade to latest version of @angular/cli and @nrwl/nx and remove the explicit dependencies of @schematics/angular if you have it in your package.json
