### ISSUE TITLE
ng g lib throws an error after update to 7.0.2

### ISSUE THREAD

**Issue by jimdubbs** [nrwl/nx#866]
When running ng g lib "lib name" I get the below error:
![image](https://user-images.githubusercontent.com/3068059/47808580-99469880-dd21-11e8-9489-e177ef0657d5.png)

dependencies:
![image](https://user-images.githubusercontent.com/3068059/47808633-b8ddc100-dd21-11e8-96b9-1e69644d00ce.png)

Deleted node_modules and installed fresh, no luck.

**Comment by bcabanes** [comment]
Hi @jimdubbs,

I tried setting a project with the AngularCLI and Nx at version 6.x and do the update towards version 7.x, but can't reproduce your error.

Could you add a link of a reproduction please?

**Comment by markgoho** [comment]
``` bash
$ ng g lib file-upload
? In which directory should the library be generated?
? Which module should import the library?
? Would you like to add a routing configuration to the library? No
? Will this library be lazy loaded? No
? Would you like to generate an NgModule within the library? Yes
? Which tags would you like to add to the library? (used for linting)
? Which Unit Test Runner would you like to use for the library? Jest (https://jestjs.io/)
CREATE libs/file-upload/tsconfig.lib.json (744 bytes)
CREATE libs/file-upload/tslint.json (267 bytes)
CREATE libs/file-upload/src/index.ts (59 bytes)
CREATE libs/file-upload/src/lib/file-upload.module.ts (255 bytes)
CREATE libs/file-upload/src/lib/file-upload.module.spec.ts (447 bytes)
CREATE libs/file-upload/jest.config.js (134 bytes)
CREATE libs/file-upload/tsconfig.spec.json (254 bytes)
CREATE libs/file-upload/src/test-setup.ts (30 bytes)
UPDATE angular.json (30297 bytes)
UPDATE nx.json (1218 bytes)
UPDATE tsconfig.json (672 bytes)
C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\rxjs\internal\util\hostReportError.js:4
    setTimeout(function () { throw err; });
                             ^

Error: ENOENT: no such file or directory, stat 'C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\@angular\cli\.bin\ng'
    at Object.statSync (fs.js:848:3)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\@angular-devkit\core\node\host.js:263:29)
    at Observable._trySubscribe (C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\rxjs\internal\Observable.js:30:22)
    at MapOperator.call (C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\rxjs\internal\operators\map.js:32:23)
    at Observable.subscribe (C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\rxjs\internal\Observable.js:25:22)
    at MergeMapSubscriber.originalBackend.list.pipe.operators_1.concatMap.path [as project] (C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:354:51)
    at MergeMapSubscriber._tryNext (C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\Mark\Documents\GitHub\ui-suite\node_modules\rxjs\internal\Subscriber.js:67:18)
```

**Comment by jimdubbs** [comment]
Hey @bcabanes,

Ill see if I can repro in a stack blitz - but I did exactly what you just mentioned. Upgraded from 6.x to 7.0.1 and got the above error when trying to generate a lib.
