### ISSUE TITLE
Error when booting a fresh react-native app: The following files share their name; please adjust your hasteImpl

### ISSUE THREAD

**Issue by binary64** [nrwl/nx#8669]
## Current Behavior
I created a neew react-native app and ran it, but when I `yarn serve mobile` I get `The following files share their name; please adjust your hasteImpl: xxxx`

## Expected Behavior
No errors. I tried react-native app a year ago and I remember it booted without an error.

## Steps to Reproduce
```
yarn add -D @nrwl/react-native
yarn nx generate @nrwl/react-native:app mobile --compiler=swc
yarn serve mobile
```
And then wait about 7 seconds.

### Failure Logs

```
                    Welcome to Metro!
              Fast - Scalable - Integrated



To reload the app press "r"
To open developer menu press "d"

jest-haste-map: Haste module naming collision: pabau
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>\package.json
    * <rootDir>\dist\out-tsc\package.json

Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (C:\p\pab\monorepo\node_modules\metro\node_modules\jest-haste-map\build\index.js:543:17)
    at workerReply (C:\p\pab\monorepo\node_modules\metro\node_modules\jest-haste-map\build\index.js:614:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 118)
    at async C:\p\pab\monorepo\node_modules\metro\node_modules\jest-haste-map\build\index.js:426:22
    at async Function.load (C:\p\pab\monorepo\node_modules\metro\src\node-haste\DependencyGraph.js:143:36) {
  mockPath1: 'package.json',
  mockPath2: 'dist\\out-tsc\\package.json'
}
```

### Environment
Windows 10, Node 17

**Comment by binary64** [comment]
I realize this bug is on my shoulders -- `rm -rf dist` solved this problem. However for DX, would it be possible to fix this on the Nx level somehow? Just curious.

**Comment by mandajoan** [comment]
Also encountered this error but my steps to reproduce are different. 
1. Updated working branch with main. 
2. Run `yarn install`
3. Start react native project via `nx start` command
4. Separate project (not react native) is listed in error 

removing the dist directory worked for me as well

**Comment by mandajoan** [comment]
if you're using metro bundler see this  https://stackoverflow.com/questions/61419633/exclude-only-a-top-level-directory-in-metro-bundler-using-blacklist-regex-blac

**Comment by xiongemi** [comment]
as shown in https://stackoverflow.com/questions/41813211/how-to-make-react-native-packager-ignore-certain-directories, need to change the metro.config.js:
```
const exclusionList = require('metro-config/src/defaults/exclusionList');

...
resolver: {
        ...
        blacklistRE: exclusionList([/dist\/.*/]),
      },

```
