### ISSUE TITLE
Not able to build project's that have buildable dependencies without `package.json`'s

### ISSUE THREAD

**Issue by pemsbr** [nrwl/nx#8707]
## Current Behavior
[calculateProjectDependencies](https://github.com/nrwl/nx/blob/b23f2d8b8027795184b74e0bcdf0567a87e9a4b4/packages/workspace/src/utilities/buildable-libs-utils.ts#L25) fails when buildable dependencies don't have `package.json`'s

## Expected Behavior
Build should work as expected.

## Steps to Reproduce
1. Create a buildable `@nrwl/js:tsc` library named target-lib
2. Create a buildable library that doesn't have a `package.json` named dep-lib (e.g., create a dotnet project using the [nx-dotnet](https://github.com/nx-dotnet/nx-dotnet) plugin)
3. Set dep-lib as an implicit dependency of target-lib
```json5
// target-lib's project.json
"implicitDependencies": ["dep-lib"]
```

4. Invoke `nx build target-lib`

### Failure Logs

```console
ENOENT: no such file or directory, open '/Users/pedro/Developer/demo/libs/dep-lib/package.json'
Error: ENOENT: no such file or directory, open '/Users/pedro/Developer/demo/libs/dep-lib/package.json'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at readJsonFile (/Users/pedro/Developer/demo/node_modules/.pnpm/@nrwl+tao@13.5.1/node_modules/@nrwl/tao/src/utils/fileutils.js:16:43)
    at /Users/pedro/Developer/demo/node_modules/.pnpm/@nrwl+workspace@13.5.1_77aa66af867b7a7d7364671ca12d39bb/node_modules/@nrwl/workspace/src/utilities/buildable-libs-utils.js:26:66
    at Array.map (<anonymous>)
    at calculateProjectDependencies (/Users/pedro/Developer/demo/node_modules/.pnpm/@nrwl+workspace@13.5.1_77aa66af867b7a7d7364671ca12d39bb/node_modules/@nrwl/workspace/src/utilities/buildable-libs-utils.js:22:10)
    at checkDependencies (/Users/pedro/Developer/demo/node_modules/.pnpm/@nrwl+js@13.5.1_77aa66af867b7a7d7364671ca12d39bb/node_modules/@nrwl/js/src/utils/check-dependencies.js:9:120)
    at tscExecutor_1 (/Users/pedro/Developer/demo/node_modules/.pnpm/@nrwl+js@13.5.1_77aa66af867b7a7d7364671ca12d39bb/node_modules/@nrwl/js/src/executors/tsc/tsc.impl.js:30:89)
    at tscExecutor_1.next (<anonymous>)
    at resume (/Users/pedro/Developer/demo/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:225:48)
```
### Environment
```json5
// nx.json
"targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
```

```console
Node : 17.3.1
   OS   : darwin arm64
   pnpm : 6.28.0
   
   nx : 13.5.1
   @nrwl/angular : undefined
   @nrwl/cli : 13.5.1
   @nrwl/cypress : 13.5.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.1
   @nrwl/eslint-plugin-nx : 13.5.1
   @nrwl/express : undefined
   @nrwl/jest : 13.5.1
   @nrwl/js : 13.5.1
   @nrwl/linter : 13.5.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.5.1
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.5.1
   @nrwl/tao : 13.5.1
   @nrwl/web : 13.5.1
   @nrwl/workspace : 13.5.1
   typescript : 4.5.5
   rxjs : 7.5.2
   ---------------------------------------
   Community plugins:
         @nx-dotnet/core: 1.8.0
```

### Context
https://github.com/nrwl/nx/blob/b23f2d8b8027795184b74e0bcdf0567a87e9a4b4/packages/workspace/src/utilities/buildable-libs-utils.ts#L45-L47

**Comment by pemsbr** [comment]
@AgentEnder is this something that can be fixed on nx-dotnet's side?

**Comment by AgentEnder** [comment]
I posted a PR with workaround for nx-dotnet yesterday. IMHO we should still fix it here too.

**Comment by AgentEnder** [comment]
Not really, we should be checking that the lib actually has a package.json and skipping it if it doesn't on the NX side, should be easy fix. 

If you want to open a PR it looks like you've already identified the piece of code, and I could review.

**Comment by Camo30** [comment]
Same issue here - without using nx-dotnet. My application contains a lib that has no package.json. This lib was simply created with `nx generate @nrwl/angular:library`.

### Environment
```
   Node : 14.18.1
   OS   : win32 x64
   pnpm : 6.29.1

   nx : 13.8.0
   @nrwl/angular : 13.8.0
   @nrwl/cli : 13.8.0
   @nrwl/cypress : 13.8.0
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.0
   @nrwl/eslint-plugin-nx : 13.8.0
   @nrwl/express : undefined
   @nrwl/jest : 13.8.0
   @nrwl/js : undefined
   @nrwl/linter : 13.8.0
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.0
   @nrwl/tao : 13.8.0
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.0
   typescript : 4.5.5
   rxjs : 7.5.1
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.2
         @angular/common: 13.2.2
         @angular/compiler: 13.2.2
         @angular/core: 13.2.2
         @angular/forms: 13.2.2
         @angular/localize: 13.2.2
         @angular/platform-browser: 13.2.2
         @angular/platform-browser-dynamic: 13.2.2
         @angular/router: 13.2.2
         @angular/upgrade: 13.2.2
         @ng-bootstrap/ng-bootstrap: 11.0.0
         @ngrx/effects: 13.0.2
         @ngrx/router-store: 13.0.2
         @ngrx/store: 13.0.2
         @progress/kendo-popup-common: 1.9.0
         @angular-devkit/build-angular: 13.2.3
         @angular/cli: 13.2.3
         @angular/compiler-cli: 13.2.2
         @angular/language-service: 13.2.2
         @ngrx/store-devtools: 13.0.2
```

**Comment by pemsbr** [comment]
hey @AgentEnder 👋 can we get this merged?

**Comment by AgentEnder** [comment]
Hey, sorry. Yeah, let me take a look.
