### ISSUE TITLE
Error when building a fresh @nrwl/next workspace app

### ISSUE THREAD

**Issue by hmbrg** [nrwl/nx#8714]
## Current Behavior
When setting up a fresh workspace using `npx create-nx-workspace@latest --preset=next`,  and then running `npx nx build <app>`, the build fails with an error (see log below).

## Expected Behavior

The build should run without any errors.

## Steps to Reproduce

1. Run `npx create-nx-workspace@latest --preset=next`
2. Run `cd <app>`
3. Run `npx nx build <app>`

### Failure Logs

```
❯ npx nx build web

> nx run web:build:production

We detected TypeScript in your project and reconfigured your tsconfig.json file for you. Strict-mode is set to false by default.

The following suggested values were added to your tsconfig.json. These values can be changed to fit your project's needs:

	- incremental was set to true

info  - Checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (3/3)
info  - Finalizing page optimization

Page                                       Size     First Load JS
┌ ○ /                                      3.67 kB        75.3 kB
├   └ css/ef46db3751d8e999.css             20 B
├   /_app                                  0 B            71.6 kB
└ ○ /404                                   193 B          71.8 kB
+ First Load JS shared by all              71.6 kB
  ├ chunks/framework-c4190dd27fdc6a34.js   42 kB
  ├ chunks/main-770e124cf078f84c.js        28.2 kB
  ├ chunks/pages/_app-9971065c73d09c4b.js  596 B
  ├ chunks/webpack-514908bffb652963.js     770 B
  └ css/8560734f0101022a.css               1.8 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)

node:fs:884
  handleErrorFromBinding(ctx);
  ^

Error: EBADF: bad file descriptor, write
    at Object.writeSync (node:fs:884:3)
    at Object.writeFileSync (node:fs:2159:26)
    at appendFileSync (node:fs:2215:6)
    at WriteStream.process.stderr._write (/Users/matthias/Code/fakeorg/node_modules/@nrwl/cli/lib/run-cli.js:53:33)
    at writeOrBuffer (node:internal/streams/writable:390:12)
    at _write (node:internal/streams/writable:331:10)
    at WriteStream.Writable.write (node:internal/streams/writable:335:10)
    at EventEmitter.i.alwaysLast (/Users/matthias/Code/fakeorg/node_modules/next/dist/compiled/ora/index.js:1:15955)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.emit (node:domain:475:12) {
  errno: -9,
  syscall: 'write',
  code: 'EBADF'
}

Node.js v17.2.0
```

### Environment

```
❯ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 17.2.0
   OS   : darwin arm64
   npm  : 8.1.4

   nx : 13.5.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.5.3
   @nrwl/cypress : 13.5.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.3
   @nrwl/eslint-plugin-nx : 13.5.3
   @nrwl/express : undefined
   @nrwl/jest : 13.5.3
   @nrwl/js : 13.5.3
   @nrwl/linter : 13.5.3
   @nrwl/nest : undefined
   @nrwl/next : 13.5.3
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.2
   @nrwl/react : 13.5.3
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.5.3
   @nrwl/tao : 13.5.3
   @nrwl/web : 13.5.3
   @nrwl/workspace : 13.5.3
   typescript : 4.4.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by sebacruz** [comment]
I'm having the same issue.

**Comment by FrozenPandaz** [comment]
Sorry about that. This is fixed in `13.7.0`by https://github.com/nrwl/nx/commit/f72c6796a571845506a10b9b3cd495d4326fa213

**Comment by EhsanHerai** [comment]
@FrozenPandaz the problem still exists

**Comment by EhsanHerai** [comment]
@FrozenPandaz I know this is a stupid question. how can I upgrade nx ?
```npm i -g nx```
```yarn global add nx```
I have used both of these commmands but still when I run ```nx run ...``` inside my project it uses version `12`

**Comment by hmbrg** [comment]
> @FrozenPandaz I know this is a stupid question. how can I upgrade nx ? `npm i -g nx` `yarn global add nx` I have used both of these commmands but still when I run `nx run ...` inside my project it uses version `12`

They have very nice docs on that: https://nx.dev/using-nx/updating-nx

**Comment by EhsanHerai** [comment]
@hmbrg I don't want to migrate whole packages I just want to update nx cli to version 13

**Comment by EhsanHerai** [comment]
@hmbrg I need to upgrade my local `@nrwl/cli` not global one.

**Comment by hmbrg** [comment]
Did you try `yarn global upgrade @nrwl/cli`?

**Comment by sebacruz** [comment]
@EhsanHerai why don't you ask on the discussion page or in a new issue to keep the comments relevance to each issue?
