### ISSUE TITLE
Error: initial exceeded maximum budget. Budget 5.00 MB was not met by 2.14 MB with a total of 7.14 MB.

### ISSUE THREAD

**Issue by Chirlancharamana** [nrwl/nx#8732]
## Current Behavior

Getting error while building an application.

Error: initial exceeded maximum budget. Budget 5.00 MB was not met by 2.14 MB with a total of 7.14 MB.

## Expected Behavior
An application build should get succeeded.

## Steps to Reproduce

./apps/xyz/web/src/app/app.module.ts

Getting build budget exceed issue when i import a service/component from 'abc' library in npm scope way (Ex: @xyz/abc).

ex: ./libs/xyz/src/lib/abc.component.ts

However, the build budget is in allowed size when imported a component by using relative path in app.module.ts

Note: Relative path imports are disabled in lint in my projects.

Project info :

"@angular/cli": "12.2.12",
"@nrwl/cli": "13.1.2",

**Comment by FrozenPandaz** [comment]
Could you please provide a repo where we can reproduce the issue? Is a huge dependency being brought in?

**Comment by Chirlancharamana** [comment]
I cannot provide a repo on this. I think we are bringing in a huge dependency of my library when imported in npm scope way @proj_name/library_name

**Comment by Coly010** [comment]
Without a repo this will be very hard to solve as it’ll likely be to do with your specific workspace and what packages and libraries are being used in your app. 

You can use webpack-bundle-analyzer (https://www.npmjs.com/package/webpack-bundle-analyzer) to help identifier where the increase in bundle size is coming from so you can make decisions on how to reduce it.

Alternatively you can increase the bundle limits in your angular.json/project.json file. 
this article might be of help

https://web.dev/performance-budgets-with-the-angular-cli/

**Comment by Chirlancharamana** [comment]
Solved!

Analysed with the help of the above package. the library which i imported is causing the issue.
So i've imported only files which i wanted like below.


created a new directory at libraries source level adding index.ts file inside it

`appImports/index.ts`.

Added config:
tsconfig.base.json
"@proj_name/lib_name/appImports": ["libs/lib_name/src/appImports/index.ts"],

Imported the things needed from the path `appImports/index.ts`.

This approach is solved my issue.

**Comment by Coly010** [comment]
Great to hear! 🎉 

Going to close this as it has been solved :)

**Comment by TimJ0212** [comment]
Sorry for asking, but this is the only thread about this problem.
How do I extend the angular.json in nx? If I use the method from the given link ([https://github.com/nrwl/nx/issues/8732#issuecomment-1027745408),](https://github.com/nrwl/nx/issues/8732#issuecomment-1027745408)) then I get the following error message while building:

`>NX Cannot read properties of undefined (reading 'split')`

Stacktrace with --verbose:
```
TypeError: Cannot read properties of undefined (reading 'split')
    at getExecutorForTask (/Users/x/workspace/node_modules/nx/src/tasks-runner/utils.js:132:49)
    at getCustomHasher (/Users/x/workspace/node_modules/nx/src/tasks-runner/utils.js:137:21)
    at hashDependsOnOtherTasks (/Users/x/workspace/node_modules/nx/src/hasher/hash-task.js:8:54)
    at /Users/x/workspace/node_modules/nx/src/tasks-runner/run-command.js:69:58
    at Generator.next (<anonymous>)
    at /Users/x/workspace/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/x/workspace/node_modules/tslib/tslib.js:114:16)
    at hashTasksThatDontDependOnOtherTasks (/Users/x/workspace/node_modules/nx/src/tasks-runner/run-command.js:66:20)
    at /x/workspace/node_modules/nx/src/tasks-runner/run-command.js:84:19

```
Reducing the bundle size is not possible. I need to increase the bundle size.
I have only specified the budgets:
I thought this would override the specific section of the angular config from nx, but it doesn't seem to work.

```json
{
  "$schema": "./node_modules/nx/schemas/workspace-schema.json",
  "version": 2,
  "projects": {
    "api": "apps/api",
    "app": {
      "root": "apps/app",
      "architect": {
        "build": {
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ]
            }
          }
        }
      }
    },
    "app-e2e": "apps/app-e2e",
    "domain-lib": "libs/domain-lib"
  }
}
```

**Comment by lenhhoxung32** [comment]
hi @TimJ0212 
this won't work for nx projects. For Nx projects, you should update the file `project.json` which located inside each  nx-app folder.
Hope that help!
