### ISSUE TITLE
Package not found in npm registry when nx migrate latest from 13.5.3 to 13.6.1

### ISSUE THREAD

**Issue by JWood48** [nrwl/nx#8733]
Running migrate fails with packages not found in npm registry:

```
$ nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @nrwl/cli@13.6.1
Fetching @nrwl/cypress@13.6.1
Fetching @nrwl/eslint-plugin-nx@13.6.1
Fetching @nrwl/jest@13.6.1
Fetching @nrwl/linter@13.6.1
Fetching @nrwl/react@13.6.1
Fetching @nrwl/tao@13.6.1
Fetching @nrwl/web@13.6.1

 ERROR  The migrate command failed.

Command failed: yarn add -W @nrwl/react@13.6.1
warning @nrwl/react > @nrwl/web > stylus > css > source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
error Couldn't find package "onetime@^5.1.2" required by "execa@^5.0.0" on the "npm" registry.
Error: Couldn't find package "onetime@^5.1.0" required by "restore-cursor@^3.1.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Users\jakobs.NOVOTEK\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:721:66)
    at new MessageError (C:\Users\jakobs.NOVOTEK\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:750:123)
    at PackageRequest.<anonymous> (C:\Users\jakobs.NOVOTEK\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:36582:17)
    at Generator.throw (<anonymous>)
    at step (C:\Users\jakobs.NOVOTEK\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:310:30)
    at C:\Users\jakobs.NOVOTEK\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

C:\Users\jakobs.NOVOTEK\git\jsk\sambuca\smbdk\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\JAKOBS~1.NOV\AppData\Local\Temp\tmp-23296-e8bvOs4PDBbD\node_modules\.bin\tao migrate latest
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.handler (C:\Users\jakobs.NOVOTEK\git\jsk\sambuca\smbdk\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:137:42)
    at Object.runCommand (C:\Users\jakobs.NOVOTEK\git\jsk\sambuca\smbdk\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Users\jakobs.NOVOTEK\git\jsk\sambuca\smbdk\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\Users\jakobs.NOVOTEK\git\jsk\sambuca\smbdk\node_modules\yargs\build\lib\yargs.js:986:25)
    at initLocal (C:\Users\jakobs.NOVOTEK\git\jsk\sambuca\smbdk\node_modules\@nrwl\cli\lib\init-local.js:27:79)
    at Object.<anonymous> (C:\Users\jakobs.NOVOTEK\git\jsk\sambuca\smbdk\node_modules\@nrwl\cli\bin\nx.js:45:32)
    at Module._compile (C:\Users\jakobs.NOVOTEK\AppData\Roaming\npm\node_modules\nx\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 6552,
  stdout: null,
  stderr: null
}
```

**Comment by JWood48** [comment]
Seems to have been an VPN issue :-/
