### ISSUE TITLE
Running `test` on Nest libraries with dependencies fails with SWC

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#8791]
I realize SWC is not directly supported for Nest libs _yet_ but figured I would report regardless to help get the ball rolling.

## Current Behavior

Let's assume we have the following setup (all incrementally buildable and using the`swc` compiler):

`nestlib1` that has some `Module`s and `Service`s in it that use some code from `nestlib2` which also had some modules and services.

Running `nx build nestlib1` works totally fine (builds `nestlib2` first)

Running `nx test nestlib1` fails with:

```
 FAIL   bullet-shared-service-itemized-receipt-builder  libs/bullet/shared/service/itemized-receipt-builder/src/lib/itemized-receipt-builder.service.spec.ts
  ● Test suite failed to run

    error: Unexpected token `@`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier
      
       |
    49 | @Module({
       | ^



    Caused by:
        0: failed to process js file
        1: Syntax Error

      at Compiler.transformSync (../../../../../node_modules/@swc/core/index.js:137:25)
      at transformSync (../../../../../node_modules/@swc/core/index.js:217:21)
      at Object.process (../../../../../node_modules/@swc/jest/index.js:71:45)
      at ScriptTransformer.transformSource (../../../../../node_modules/@jest/transform/build/ScriptTransformer.js:612:31)
      at ScriptTransformer._transformAndBuildScript (../../../../../node_modules/@jest/transform/build/ScriptTransformer.js:758:40)
      at ScriptTransformer.transform (../../../../../node_modules/@jest/transform/build/ScriptTransformer.js:815:19)

Test Suites: 3 failed, 1 passed, 4 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        2.305 s
Ran all test suites.
```

I did some debugging and it is failing on the decorators in `nestlib2` not in `nestlib1`

This got me thinking, if we ran tests on `nestlib1` using precompiled artifacts (https://github.com/nrwl/nx/pull/7707) instead of source would it work?

so in `nestlib1`s jest.config.js I setup a `moduleNameMapper` object that mapped `nestlib2` to `dist/libs/nestlib2/src/index.js`, built `nestlib2` and then ran tests on `nestlib1`. It worked!

## Expected Behavior

Should be able to use `@swc/jest` with Nest code.

## Steps to Reproduce

I have tried to reproduce this in a fresh repo by making some nest libraries and importing them and running tests but have yet to be able to repro it. There must be some way our code is written that isn't the same as a fresh repo as I have compared all of the configurations and cannot find anything different.

Open to ideas to try and narrow it down even more.

### Failure Logs

<img width="1758" alt="image" src="https://user-images.githubusercontent.com/9469090/151847506-6779d44f-9b81-4ec6-bf51-733a9d8bde48.png">

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 12.22.7
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 13.5.3
   @nrwl/angular : 13.5.3
   @nrwl/cli : 13.5.3
   @nrwl/cypress : 13.5.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.3
   @nrwl/eslint-plugin-nx : 13.5.3
   @nrwl/express : 13.5.3
   @nrwl/jest : 13.5.3
   @nrwl/js : 13.5.3
   @nrwl/linter : 13.5.3
   @nrwl/nest : 13.5.3
   @nrwl/next : undefined
   @nrwl/node : 13.5.3
   @nrwl/nx-cloud : 13.1.2
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.5.3
   @nrwl/tao : 13.5.3
   @nrwl/web : 13.5.3
   @nrwl/workspace : 13.5.3
   typescript : 4.5.4
   rxjs : 7.4.0

**Comment by yharaskrik** [comment]
This seems to have been fixed.
