### ISSUE TITLE
Storybook fails: Module '"@lib/my-lib"' has no exported member 'testFunction'.

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#8805]
I am getting the following error with the Nrwl and angular upgrade 

Storybook is not able to find the module from another nrwl library 

```
testFunction,
     ~~~~~~~~~~~~~~~~~

    at addError (/Users//node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:31:29)
    at /Users//node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/diagnostics.js:17:17
    at AngularWebpackPlugin.updateJitProgram (/Users//node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/plugin.js:479:9)
    at /Users//node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/plugin.js:199:24
    at Hook.eval [as call] (eval at create (/Users//node_modules/@storybook/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:1)
    at Hook.CALL_DELEGATE [as _call] (/Users//node_modules/@storybook/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users//node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compiler.js:1054:30)
    at /Users//node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compiler.js:1099:29
    at _next0 (eval at create (/Users//node_modules/@storybook/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at eval (eval at create (/Users//node_modules/@storybook/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:35:1)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: src/lib/my-comp/test-comp.component.stories.ts:16:3 - error TS2305: Module '"@lib/my-lib"' has no exported member 'testFunction'.
```

**Comment by dean-g** [comment]
it's a valid error message. please ignore
