### ISSUE TITLE
Can't generate new application in workspace converted from Angular CLI

### ISSUE THREAD

**Issue by johnbwoodruff** [nrwl/nx#8851]
## Current Behavior

When attempting to generate a new application in a workspace that was converted from Angular CLI I get the following error:

```shell
Error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
```

I am generating the command using `nx generate application`.

## Expected Behavior

This should properly generate a new application in the NX workspace.

## Steps to Reproduce

1. Generate a new Angular CLI application with `ng new test-app`
2. Convert the Angular CLI application to an NX Workspace using `ng add @nrwl/workspace`
3. Attempt to generate a new application in the NX Workspace using `nx generate application second-app`

You'll get the above error.

### Failure Logs

This is the full error:

```shell
Error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
    at findModule (/Users/username/dev/frontend/test-ng-to-nx-add-app/node_modules/@schematics/angular/utility/find-module.js:81:11)
    at findModuleFromOptions (/Users/username/dev/frontend/test-ng-to-nx-add-app/node_modules/@schematics/angular/utility/find-module.js:26:38)
    at /Users/username/dev/frontend/test-ng-to-nx-add-app/node_modules/@schematics/angular/component/index.js:105:66
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

```shell
 >  NX   Report complete - copy this into the issue template

   Node : 12.22.9
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 13.7.2
   @nrwl/angular : 13.7.2
   @nrwl/cli : 13.7.2
   @nrwl/cypress : 13.7.2
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.2
   @nrwl/eslint-plugin-nx : undefined
   @nrwl/express : undefined
   @nrwl/jest : 13.7.2
   @nrwl/js : undefined
   @nrwl/linter : 13.7.2
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.7.2
   @nrwl/tao : 13.7.2
   @nrwl/web : undefined
   @nrwl/workspace : 13.7.2
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.1
         @angular/cdk: 13.2.1
         @angular/common: 13.2.1
         @angular/compiler: 13.2.1
         @angular/core: 13.2.1
         @angular/forms: 13.2.1
         @angular/material: 13.2.1
         @angular/platform-browser: 13.2.1
         @angular/platform-browser-dynamic: 13.2.1
         @angular/router: 13.2.1
         @angular/service-worker: 13.2.1
         @angular-devkit/build-angular: 13.2.2
         @angular-eslint/builder: 13.0.0-alpha.1
         @angular-eslint/schematics: 13.0.0-alpha.1
         @angular/cli: 13.2.2
         @angular/compiler-cli: 13.2.1
         @angular/language-service: 13.2.1
         @cypress/schematic: 1.6.0
```

**Comment by taftsandbakken** [comment]
I need this as well. Thanks!

**Comment by johnbwoodruff** [comment]
I may have discovered the solution. It would appear that an Angular CLI project converted to an NX Workspace has the `"newProjectRoot": "projects"` entry in the `angular.json` file. That key doesn't align with the NX project structure which does not have a `projects` directory. That configuration would obviously interfere with the schematics that would assume a projects directory where there isn't one.

I believe the best solution here is to ensure that during the conversion happening in `ng add @nrwl/workspace`, that `newProjectRoot` entry should be removed. That will ensure the rest of the generator schematics work properly.

**Comment by johnbwoodruff** [comment]
Confirmed the problem with a failing test. I went ahead and submitted PR #8865 to address this issue.
