### ISSUE TITLE
Problems running `ng add`

### ISSUE THREAD

**Issue by moniuch** [nrwl/nx#8854]
## Current Behavior

Problems running ng add and the suggested nx workaround fails.

I started to observe massive problems running `ng add` within nx workspace.
THe pattern so far has been:
- I run `ng add` (without `@angular/cli` installed globally - should that matter)
- Nx informs me that it does not support `ng` natively and suggests an alternative syntax, asking if I want to run it
- I accept it
- The schematic crashes

Details follow below.

I probably would open a ticket if this was just a one-off case, but as I said, it's been a series of failures by now.
Will provide more logs if encountered.

## Expected Behavior

`ng add` (whether native or not) should complete smoothly.

## Steps to Reproduce

I don't know how to reproduce, and what to check for.
However I managed to successfully run the schematic on a brand new `ng new` app.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

This is an example of attempting to install `@ngrx/component` using `ng add @ngrx/component@latest`

```
$ npx ng add @ngrx/component@latest
Ng add is not natively supported by Nx
Instead, we recommend running `npm install @ngrx/component@latest && npx nx g @ngrx/component@latest:ng-add`
✔ Run this command? (y/N) · true
# ( ...100 lines of optional deps warnings... )
+ @ngrx/component@13.0.2
added 1 package from 1 contributor, removed 2 packages and audited 1450 packages in 10.217s

126 packages are looking for funding
  run `npm fund` for details

found 38 vulnerabilities (2 low, 36 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
Unable to resolve @ngrx/component@latest:ng-add.
Cannot find module '@ngrx/component@latest/package.json'
Require stack:
- /Users/.../node_modules/@nrwl/tao/src/shared/workspace.js
- /Users/.../node_modules/@nrwl/cli/lib/init-local.js
- /Users/.../node_modules/@nrwl/cli/bin/nx.js
- /Users/.../node_modules/nx/bin/nx.js
(node:60249) UnhandledPromiseRejectionWarning: Error: Command failed: npm install @ngrx/component@latest && npx nx g @ngrx/component@latest:ng-add
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at /Users/.../node_modules/@nrwl/cli/lib/init-local.js:72:54
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:60249) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:60249) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and in a fresh app:

```
$ cd nxadd-problems 
$ ng add @ngrx/component@latest
zsh: command not found: ng
$ npx ng add @ngrx/component@latest
ℹ Using package manager: npm
✔ Package information loaded.

The package @ngrx/component@latest will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
UPDATE package.json (1110 bytes)
✔ Packages installed successfully.
$ 
```

### Environment

I don't have @angular cli installed globally. This is intentional, although not sure it matters for this case.

```
"dependencies": {
    "@angular/animations": "~13.1.0",
    "@angular/cdk": "^13.1.2",
    "@angular/common": "~13.1.0",
    "@angular/compiler": "~13.1.0",
    "@angular/core": "~13.1.0",
    "@angular/forms": "~13.1.0",
    "@angular/platform-browser": "~13.1.0",
    "@angular/platform-browser-dynamic": "~13.1.0",
    "@angular/router": "~13.1.0",
    "@auth0/angular-jwt": "^5.0.2",
    "@fortawesome/angular-fontawesome": "^0.10.1",
    "@fortawesome/fontawesome-svg-core": "~1.2.36",
    "@fortawesome/free-regular-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@ngrx/component-store": "~13.0.0",
    "@ngrx/effects": "~13.0.0",
    "@ngrx/entity": "~13.0.0",
    "@ngrx/router-store": "~13.0.0",
    "@ngrx/store": "~13.0.0",
    "@nrwl/angular": "13.4.5",
    "bulma": "^0.9.3",
    "rxjs": "~7.4.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.1.0",
    "@angular-eslint/eslint-plugin": "~13.0.1",
    "@angular-eslint/eslint-plugin-template": "~13.0.1",
    "@angular-eslint/template-parser": "~13.0.1",
    "@angular/cli": "~13.1.0",
    "@angular/compiler-cli": "~13.1.0",
    "@angular/language-service": "~13.1.0",
    "@ngrx/schematics": "~13.0.0",
    "@ngrx/store-devtools": "~13.0.0",
    "@nrwl/cli": "13.4.5",
    "@nrwl/cypress": "13.4.5",
    "@nrwl/eslint-plugin-nx": "13.4.5",
    "@nrwl/jest": "13.4.5",
    "@nrwl/linter": "13.4.5",
    "@nrwl/tao": "13.4.5",
    "@nrwl/workspace": "13.4.5",
    "@types/jest": "27.0.2",
    "@types/node": "14.14.33",
    "@typescript-eslint/eslint-plugin": "~5.3.0",
    "@typescript-eslint/parser": "~5.3.0",
    "cypress": "^9.1.0",
    "eslint": "8.2.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "jasmine-marbles": "~0.9.1",
    "jest": "27.2.3",
    "jest-preset-angular": "11.0.0",
    "prettier": "^2.3.1",
    "ts-jest": "27.0.5",
    "typescript": "~4.4.3"
  }
```

**Comment by moniuch** [comment]
One more thing: what has been symptomatic so far is that, following "unsuccessful" install the package can be found in node_modules, but the auto-complete in VSCode doesn't pick it up. Neither do `Reac...` autocomplete `ReactiveComponentModule` (however the import provided manually is recognized), nor does `*ngrxL...` autocomplete `*ngrxLet`. When completed manually, it seems to be recognized, but then fails in the browser:

`Can't bind to 'ngrxLet' since it isn't a known property of 'ng-container'.`

(I had a similar problem with one of the angular Bootstrap packages)

**Comment by moniuch** [comment]
OK. Can be closed. Node version was the culprit. Not the reason of all evil, but solved at least failing schematics for @ngrx/component. Sorry for the noise.
