### ISSUE TITLE
@nrwl/js:library can't be used in a @nrwl/web:application unless .babelrc added manually

### ISSUE THREAD

**Issue by ziacik** [nrwl/nx#8943]
## Current Behavior
I've generated a @nrwl/web application and a (buildable) @nrwl/js library. The application uses the library. Now the app build ends with error. I have to add a `.babelrc` to the library's root (copied from the app), then the app builds.

## Expected Behavior
The lib generator should generate all the files required to be able to use the lib in the app.

## Steps to Reproduce
1. create a workspace with a @nrwl/web:app and @nrwl/js:lib
2. use the lib in the app
3. nx build app

Repro repo:
https://github.com/ziacik/nx-bug-3

### Failure Logs
```bash
ERROR in ../../libs/jslib/src/lib/jslib.ts
Module build failed (from ../../node_modules/@nrwl/web/src/utils/web-babel-loader.js):
SyntaxError: /home/ziacik/Workspaces/Experimental/nx-bug-3/libs/jslib/src/lib/jslib.ts: Unexpected token, expected "{" (1:23)

> 1 | export function jslib(): string {
    |                        ^
  2 |   return 'jslib';
  3 | }
  4 |
    at Parser._raise (/home/ziacik/Workspaces/Experimental/nx-bug-3/node_modules/@babel/parser/lib/index.js:476:17)
    at Parser.raiseWithData (/home/ziacik/Workspaces/Experimental/nx-bug-3/node_modules/@babel/parser/lib/index.js:469:17)
    at Parser.raise (/home/ziacik/Workspaces/Experimental/nx-bug-3/node_modules/@babel/parser/lib/index.js:430:17)
    at Parser.unexpected (/home/ziacik/Workspaces/Experimental/nx-bug-3/node_modules/@babel/parser/lib/index.js:3789:16)
    at Parser.expect (/home/ziacik/Workspaces/Experimental/nx-bug-3/node_modules/@babel/parser/lib/index.js:3773:28)
    at Parser.parseBlock (/home/ziacik/Workspaces/Experimental/nx-bug-3/node_modules/@babel/parser/lib/index.js:14708:10)
    at Parser.parseFunctionBody (/home/ziacik/Workspaces/Experimental/nx-bug-3/node_modules/@babel/parser/lib/index.js:13440:24)
    at Parser.parseFunctionBodyAndFinish (/home/ziacik/Workspaces/Experimental/nx-bug-3/node_modules/@babel/parser/lib/index.js:13424:10)
    at /home/ziacik/Workspaces/Experimental/nx-bug-3/node_modules/@babel/parser/lib/index.js:14884:12
    at Parser.withSmartMixTopicForbiddingContext (/home/ziacik/Workspaces/Experimental/nx-bug-3/node_modules/@babel/parser/lib/index.js:13794:14)

webpack compiled with 1 error (80e24ac16f0a83e1)

```

### Environment
```
 >  NX   Report complete - copy this into the issue template

   Node : 14.17.6
   OS   : linux x64
   npm  : 6.14.15
   
   nx : undefined
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : 13.8.1
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.1
   @nrwl/web : 13.8.1
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

```

**Comment by floroz** [comment]
I have created a reproduction repo: https://github.com/floroz/nx-error-babel-storybook

## Steps to reproduce

1. `npm install`
2. `nx run web-app:build-storybook` or nx run web-app:storybook`

Error message:
```
ENOENT: no such file or directory, open '/{myLocalFolders}/tundra-nx-demo/tundra/apps/web-app/.babelrc'
```
