### ISSUE TITLE
Adding Detox app fails due to "Cannot find module '@angular-devkit/core'"

### ISSUE THREAD

**Issue by RayVR** [nrwl/nx#8949]
## Current Behavior
Following the docs here: https://nx.dev/detox/overview
I run `nx g @nrwl/detox:app <app-name>-e2e --project=<app-name>`

and hit this: 
```
Cannot find module '@angular-devkit/core'
Require stack:
- /Users/<user>/projects/<ws-name>/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /Users/<user>/projects/<ws-name>/node_modules/@nrwl/tao/src/commands/generate.js
- /Users/<user>/projects/<ws-name>/node_modules/@nrwl/tao/index.js
- /Users/<user>/projects/<ws-name>/node_modules/@nrwl/cli/lib/init-local.js
- /Users/<user>/projects/<ws-name>/node_modules/@nrwl/cli/bin/nx.js
- /Users/<user>/.nvm/<ws-name>/node/v16.13.2/lib/node_modules/nx/node_modules/@nrwl/cli/bin/nx.js
- /Users/<user>/.nvm/<ws-name>/node/v16.13.2/lib/node_modules/nx/bin/nx.js
- 
```
## Expected Behavior
Generate a new detox app

## Steps to Reproduce
Follow the steps from the nx docs on detox. 
This same error happens in a completely fresh workspace with a react-native application if I attempt to add a new detox app.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
```
- /Users/<user>/.nvm/versions/node/v16.13.2/lib/node_modules/nx/bin/nx.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (/Users/<user>/projects/test-workspace/node_modules/@nrwl/tao/src/compat/compat.js:13:40)
    at require (/Users/<user>/projects/test-workspace/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/<user>/projects/test-workspace/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js:6:16)
    at Module._compile (/Users/<user>/projects/test-workspace/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

### Environment
```
   Node : 16.13.2
   OS   : darwin x64
   yarn : 1.21.1

   nx : 13.8.1
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : 13.8.1
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : 13.8.1
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.1
   @nrwl/react-native : 13.8.1
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.1
   @nrwl/tao : 13.8.1
   @nrwl/web : 13.8.1
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

```

**Comment by xiongemi** [comment]
how about try in a new different terminal, run `nx start ...` then run the detox app again?

**Comment by xiongemi** [comment]
it should be fixed with the latest version of nx. I never run into this issue, so i closed this issue.
