### ISSUE TITLE
React Native iOS Libraries Do Not Resolve

### ISSUE THREAD

**Issue by enchorb** [nrwl/nx#8953]
## Current Behavior
When running the built-in `run-ios` command for the debug build everything runs as expected, the app builds and all libraries resolve. However, if built directly inside Xcode (this is the case in CI/CD, as fastlane will build with the xcode command line), then get the following module resolution errors for my libraries:

In Metro:
```
at ModuleResolver.resolveDependency (/Users/project_dir/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:129:15)
at DependencyGraph.resolveDependency (/Users/project_dir/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
at Object.resolve (/Users/project_dir/node_modules/metro/src/lib/transformHelpers.js:129:24)
at resolve (/Users/project_dir/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
at /Users/project_dir/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
at Array.reduce (<anonymous>)
at resolveDependencies (/Users/project_dir/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
at processModule (/Users/project_dir/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async addDependency (/Users/project_dir/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
```

In App:
```
Unable to resolve module @company/common/http from /Users/aproject_dir/apps/mobile/app_name/src/contexts/Http.tsx: @company/common/http could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

## Expected Behavior
The app should resolve the libraries in all cases

## Steps to Reproduce
Listed above, manually run a release build from inside Xcode

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by xiongemi** [comment]
this issue should be fixed with nx version 13.10.0
