### ISSUE TITLE
Can't input numeric values in generators

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx#9008]
## Current Behavior
```
> ng add single-spa-angular

Ng add is not natively supported by Nx
Instead, we recommend running `npm install single-spa-angular && npx nx g single-spa-angular:ng-add`
√ Run this command? (y/N) · true

+ single-spa-angular@6.0.1
...

? Does your application use Angular routing? (Y/n) » true
√ Does your application use Angular routing? (Y/n) · true
√ What port should your project run on? · 4200                         
Property 'port' does not match the schema. '4200' should be a 'number'.
```

## Expected Behavior
It should be possible to input numeric values in the generator's prompt.

## Steps to Reproduce
```
npx create-nx-workspace nx1382-angular --preset=angular --appName=some-angular-app --style=css --nx-cloud=false
cd nx1382-angular
ng add single-spa-angular
```
or another one with such schema https://github.com/single-spa/single-spa-angular/blob/master/schematics/ng-add/schema.json#L20-L25

### Failure Logs
```
Property 'port' does not match the schema. '4200' should be a 'number'.
(node:22876) UnhandledPromiseRejectionWarning: Error: Command failed: npm install single-spa-angular && npx nx g single-spa-angular:ng-add
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at C:\Users\denis\temp\nx1382-angular\node_modules\@nrwl\cli\lib\init-local.js:76:54
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:22876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Environment
```
> nx report

 >  NX   Report complete - copy this into the issue template

   Node : 12.21.0
   OS   : win32 x64
   npm  : 6.14.15

   nx : 13.8.2
   @nrwl/angular : 13.8.2
   @nrwl/cli : 13.8.2
   @nrwl/cypress : 13.8.2
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.2
   @nrwl/eslint-plugin-nx : 13.8.2
   @nrwl/express : undefined
   @nrwl/jest : 13.8.2
   @nrwl/js : undefined
   @nrwl/linter : 13.8.2
   @nrwl/nest : undefined
         @angular/platform-browser: 13.2.2
         @angular/platform-browser-dynamic: 13.2.2
         @angular/router: 13.2.2
         @angular-devkit/build-angular: 13.2.3
         @angular/cli: 13.2.3
         @angular/compiler-cli: 13.2.2
         @angular/language-service: 13.2.2
```

**Comment by khalilou88** [comment]
same issue: https://github.com/khalilou88/jnxplus/issues/19

**Comment by FrozenPandaz** [comment]
Currently, It should be
```json
    "port": {
      "type": "number",
      "description": "Port to listen on.",
      "x-prompt": {
        "message": "What port to listen on?",
        "type": "number"
      },
    }
```

But do you expect it to be inferred based on the type of the property?

**Comment by Den-dp** [comment]
> But do you expect it to be inferred based on the type of the property?

That's correct.

I see that this makes sense because of at least 2 reasons:
* current 13.8.2 behavior breaks prompts for ng ecosystem (without a simple way to omit nx while doing ng add)
* prompt is meant to help with inputting the right value, so types should be inferred.

Here is what angular-cli states: https://github.com/angular/angular-cli/blob/master/docs/specifications/schematic-prompts.md#basic-usage
> When using the shorthand form, the most appropriate type will automatically be selected based on the property's schema. In the example, the name prompt will use an input type because it it is a string property. The useColor prompt will use a confirmation type because it is a boolean property with yes corresponding to true and no corresponding to false.
