### ISSUE TITLE
Migrating angular project fails from NX 13.7.0 on with "Class extends value undefined is not a constructor or null" error

### ISSUE THREAD

**Issue by david-bulte** [nrwl/nx#9067]
## Current Behavior
I'm currently migrating our application(s) from nx 12 -> 13. When I build the project, all libraries are being build, but at the end, I get the following error message: "Class extends value undefined is not a constructor or null" (see screenshot below). This looks very similar as what is described here: https://github.com/nrwl/nx/issues/4712.

In fact, when migrating one release after the other, I noticed the problem is introduced in version 13.7.0 (which introduces angular 13.2.x). Now what could be the problem? When browsing the Issues, I noticed this error also appeared because of eslint issues, but this is not the case here, linting goes fine.

## Expected Behavior
Build should just run fine.

## Steps to Reproduce

ng build --project ...
ng serve --project ...
...

### Failure Logs

![image](https://user-images.githubusercontent.com/4194465/155011315-359996ff-1c83-4a94-a7f5-e03a273b179f.png)

**Verbose output:**

> nx run user-portal:build --verbose

Class extends value undefined is not a constructor or null
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\private\moaprfrontend\moapr\node_modules\webpack-subresource-integrity\index.js:38:49)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.require (C:\private\moaprfrontend\moapr\node_modules\@nrwl\tao\src\compat\compat.js:13:40)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\private\moaprfrontend\moapr\node_modules\@angular-devkit\build-angular\src\webpack\configs\common.js:38:41)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.require (C:\private\moaprfrontend\moapr\node_modules\@nrwl\tao\src\compat\compat.js:13:40)
    at require (internal/modules/cjs/helpers.js:88:18)

### Environment

Note that we use incremental builds to build the project (so using ths @nrwl/angular:webpack-browser builder)

Heres the output from 'nx report':

   Node : 14.15.3
   OS   : win32 x64
   npm  : 6.14.5

   nx : undefined
   @nrwl/angular : 13.7.3
   @nrwl/cli : 13.7.3
   @nrwl/cypress : 13.7.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.3
   @nrwl/eslint-plugin-nx : 13.7.3
   @nrwl/express : undefined
   @nrwl/jest : 13.7.3
   @nrwl/js : 13.7.3
   @nrwl/linter : 13.7.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.7.3
   @nrwl/tao : 13.7.3
   @nrwl/web : 13.7.3
   @nrwl/workspace : 13.7.3
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.3
         @angular/cdk: 13.2.3
         @angular/common: 13.2.3
         @angular/core: 13.2.3
         @angular/forms: 13.2.3
         @angular/localize: 13.2.3
         @angular/platform-browser: 13.2.3
         @angular/platform-browser-dynamic: 13.2.3
         @angular/router: 13.2.3
         @datorama/akita: 6.2.4
         @fortawesome/angular-fontawesome: 0.9.0
         @ng-bootstrap/ng-bootstrap: 9.1.3
         @storybook/angular: 6.4.19
         ngx-bootstrap: 5.6.2
         @angular-devkit/build-angular: 13.2.4
         @angular/cli: 13.2.4
         @angular/compiler: 13.2.3
         @angular/compiler-cli: 13.2.3
         @angular/elements: 13.2.3
         @angular/language-service: 13.2.3
         @ngneat/spectator: 8.3.2
         ng-mocks: 12.5.0

**Comment by david-bulte** [comment]
Sorry my bad. This was due to the storybook dependencies being imported as dependencies iso dev dependencies.
