### ISSUE TITLE
nx migrate throws "Cannot read properties of undefined (reading 'implementation')"

### ISSUE THREAD

**Issue by ajsaraujo** [nrwl/nx#9107]
### Current Behavior
I'm trying to migrate my Nx workspace from v11 to v13. I ran `nx migrate @nrwl/workspace latest`, which worked fine. However, when I run `nx migrate --run-migrations=migrations.json` to complete the migration, it throws the error `Cannot read properties of undefined (reading 'implementation')"`. 

### Command output 
```
> nx migrate --run-migrations=migrations.json --verbose
Running migration add-target-dependencies
Cannot read properties of undefined (reading 'implementation')
TypeError: Cannot read properties of undefined (reading 'implementation')
    at C:\Users\allan\sefaz-monorepo\node_modules\@nrwl\tao\src\commands\migrate.js:451:42
    at Generator.next (<anonymous>)
    at C:\Users\allan\sefaz-monorepo\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\allan\sefaz-monorepo\node_modules\tslib\tslib.js:110:16)
    at runNxMigration (C:\Users\allan\sefaz-monorepo\node_modules\@nrwl\tao\src\commands\migrate.js:447:20)
    at C:\Users\allan\sefaz-monorepo\node_modules\@nrwl\tao\src\commands\migrate.js:436:23
    at Generator.next (<anonymous>)
    at C:\Users\allan\sefaz-monorepo\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
C:\Users\allan\sefaz-monorepo\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: npx tao migrate --run-migrations=migrations.json --verbose
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at Object.handler (C:\Users\allan\sefaz-monorepo\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:76:21)
    at Object.runCommand (C:\Users\allan\sefaz-monorepo\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Users\allan\sefaz-monorepo\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\Users\allan\sefaz-monorepo\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\Users\allan\sefaz-monorepo\node_modules\@nrwl\cli\lib\init-local.js:23:13)
    at Object.<anonymous> (C:\Users\allan\sefaz-monorepo\node_modules\@nrwl\cli\bin\nx.js:41:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7300,
  stdout: null,
  stderr: null
}
```

### Environment
```
  Node : 16.14.0
  OS   : win32 x64
  npm  : 8.3.1

  nx : Not Found
  @nrwl/angular : 11.0.20
  @nrwl/cli : 11.0.20
  @nrwl/cypress : 11.0.20
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : 11.0.20
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.20
  @nrwl/linter : 11.0.20
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.20
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.20
  typescript : 4.5.5
```

### An educated guess

There is another issue (#6932) with the very same error, which was closed by the author since he managed to fix it by installing @nrwl/angular (which I already have). So I checked out the code that is throwing the error to see if I could find something:

```typescript
async function runNxMigration(root: string, packageName: string, name: string) {
  const collectionPath = packageToMigrationsFilePath(packageName, root);
  const collection = readJsonFile(collectionPath);
  const g = collection.generators || collection.schematics;
  const implRelativePath = g[name].implementation || g[name].factory;

  let implPath;

  try {
    implPath = require.resolve(implRelativePath, {
      paths: [dirname(collectionPath)],
    });
  } catch (e) {
    // workaround for a bug in node 12
    implPath = require.resolve(
      `${dirname(collectionPath)}/${implRelativePath}`
    );
  }

  const fn = require(implPath).default;
  const host = new FsTree(root, false);
  await fn(host, {});
  const changes = host.listChanges();
  flushChanges(root, changes);
}
```

This is the function that's throwing the error, more specifically at `g[name].implementation`. So that should mean that the collection doesn't have `generators` nor `schematics`, but I don't know where to go from that point... 

Anyhow, another thing which might be related - this is my `migrations.json` file:
```json
{
  "migrations": [
    {
      "version": "12.5.0-beta.1",
      "description": "Rename the workspace-schematic script into workspace-generator script",
      "factory": "./src/migrations/update-12-5-0/add-target-dependencies",
      "cli": "nx",
      "package": "@nrwl/workspace",
      "name": "add-target-dependencies"
    },
    {
      "version": "13.0.0-beta.1",
      "description": "Add default base to nx.json if its not currently set",
      "factory": "./src/migrations/update-13-0-0/set-default-base-if-not-set",
      "cli": "nx",
      "package": "@nrwl/workspace",
      "name": "set-default-base-if-not-set"
    },
    {
      "version": "13.0.0-beta.4",
      "description": "Move global settings into nx.json, and project specific settings into workspace.json",
      "cli": "nx",
      "implementation": "./src/migrations/update-13-0-0/config-locations/config-locations",
      "package": "@nrwl/workspace",
      "name": "13-0-0-config-locations"
    },
    {
      "version": "13.2.0",
      "description": "Set --parallel=1 for existing repos to preserve the existing behavior",
      "cli": "nx",
      "implementation": "./src/migrations/update-13-2-0/set-parallel-default",
      "package": "@nrwl/workspace",
      "name": "set-parallel-default"
    },
    {
      "version": "13.3.0-beta.0",
      "description": "@nrwl/workspace:tsc is now @nrwl/js:tsc",
      "cli": "nx",
      "implementation": "./src/migrations/update-13-3-0/update-tsc-executor-location",
      "package": "@nrwl/workspace",
      "name": "13-3-0-tsc-location"
    },
    {
      "version": "13.6.0-beta.0",
      "description": "Remove old options that are no longer used",
      "cli": "nx",
      "implementation": "./src/migrations/update-13-6-0/remove-old-task-runner-options",
      "package": "@nrwl/workspace",
      "name": "13-6-0-remove-old-task-runner-options"
    },
    {
      "cli": "nx",
      "version": "12.8.0-beta.0",
      "description": "Remove Typescript Preprocessor Plugin",
      "factory": "./src/migrations/update-12-8-0/remove-typescript-plugin",
      "package": "@nrwl/cypress",
      "name": "remove-typescript-plugin"
    },
    {
      "version": "12.1.0-beta.1",
      "cli": "nx",
      "description": "Update jest-preset-angular to version 8.4.0",
      "factory": "./src/migrations/update-12-1-2/update-jest-preset-angular",
      "package": "@nrwl/jest",
      "name": "update-jest-preset-angular-8-4-0"
    },
    {
      "version": "12.1.2-beta.1",
      "cli": "nx",
      "description": "Replace tsConfig with tsconfig for ts-jest in jest.config.js",
      "factory": "./src/migrations/update-12-1-2/update-ts-jest",
      "package": "@nrwl/jest",
      "name": "update-ts-jest-6-5-5"
    },
    {
      "version": "12.4.0-beta.1",
      "cli": "nx",
      "description": "Add testEnvironment: 'jsdom' in web apps + libraries",
      "factory": "./src/migrations/update-12-4-0/add-test-environment-for-node",
      "package": "@nrwl/jest",
      "name": "support-jest-27"
    },
    {
      "version": "12.4.0-beta.1",
      "cli": "nx",
      "description": "Support for Jest 27 via updating ts-jest + jest-preset-angular",
      "factory": "./src/migrations/update-12-4-0/update-jest-preset-angular",
      "package": "@nrwl/jest",
      "name": "update-ts-jest-and-jest-preset-angular"
    },
    {
      "version": "12.6.0-beta.0",
      "cli": "nx",
      "description": "Uses `getJestProjects()` to populate projects array in root level `jest.config.js` file.",
      "factory": "./src/migrations/update-12-6-0/update-base-jest-config",
      "package": "@nrwl/jest",
      "name": "update-jest-config-to-use-util"
    },
    {
      "version": "13.1.2-beta.0",
      "cli": "nx",
      "description": "Support .test. file names in tsconfigs",
      "factory": "./src/migrations/update-13-1-2/update-tsconfigs-for-tests",
      "package": "@nrwl/jest",
      "name": "update-ts-config-for-test-filenames"
    },
    {
      "version": "13.4.4-beta.0",
      "cli": "nx",
      "description": "Create a root babel config file if it doesn't exist and using babel-jest in jest.config.js and add @nrwl/web as needed",
      "factory": "./src/migrations/update-13-4-4/add-missing-root-babel-config",
      "package": "@nrwl/jest",
      "name": "add-missing-root-babel-config"
    },
    {
      "cli": "nx",
      "version": "11.5.0-beta.0",
      "description": "Update project .eslintrc.json files to always use project level tsconfigs",
      "factory": "./src/migrations/update-11-5-0/always-use-project-level-tsconfigs-with-eslint",
      "package": "@nrwl/linter",
      "name": "always-use-project-level-tsconfigs-with-eslint"
    },
    {
      "cli": "nx",
      "version": "12.4.0-beta.0",
      "description": "Remove ESLint parserOptions.project config if no rules requiring type-checking are in use",
      "factory": "./src/migrations/update-12-4-0/remove-eslint-project-config-if-no-type-checking-rules",
      "package": "@nrwl/linter",
      "name": "remove-eslint-project-config-if-no-type-checking-rules"
    },
    {
      "cli": "nx",
      "version": "12.9.0-beta.0",
      "description": "Add outputs for caching",
      "factory": "./src/migrations/update-12-9-0/add-outputs",
      "package": "@nrwl/linter",
      "name": "add-outputs"
    },
    {
      "cli": "nx",
      "version": "12.9.0-beta.0",
      "description": "Remove ESLint parserOptions.project config if no rules requiring type-checking are in use",
      "factory": "./src/migrations/update-12-4-0/remove-eslint-project-config-if-no-type-checking-rules",
      "package": "@nrwl/linter",
      "name": "remove-eslint-project-config-if-no-type-checking-rules-again"
    },
    {
      "cli": "nx",
      "version": "13.3.0-beta.0",
      "description": "Update eslint-rules jest.config.js in order to support ESLint v8 exports mapping, remove category field",
      "factory": "./src/migrations/update-13-3-0/eslint-8-updates",
      "package": "@nrwl/linter",
      "name": "eslint-8-updates"
    }
  ]
}
```

And this is a screenshot from the `workspace` folder structure in my `node_modules`:
![image](https://user-images.githubusercontent.com/34658414/155532741-9421f19e-75c1-4175-a545-f68afda9598e.png)

See? The updates I need aren't there! I wonder if that's expected behavior or not.

**Comment by ajsaraujo** [comment]
It seems that I forgot to run `npm install` before running the migrations.
