### ISSUE TITLE
production build fails in data-persistence.js

### ISSUE THREAD

**Issue by lexcaraig** [nrwl/nx#919]
```
Angular CLI: 7.0.6
Node: 8.11.3
OS: darwin x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.7
@angular-devkit/build-angular     0.8.7
@angular-devkit/build-optimizer   0.8.7
@angular-devkit/build-webpack     0.8.7
@angular-devkit/core              0.8.7
@angular-devkit/schematics        7.0.6
@angular/cdk                      7.1.0
@angular/cli                      7.0.6
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.1.0
@angular/pwa                      0.8.7
@ngtools/webpack                  6.2.7
@schematics/angular               0.8.7
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.16.4

@nrwl/nx:                         7.1.0
```

When Running 

`ng build --prod --build-optimizer --vendor-chunk -c <envinroment>`

the build process fails and it outputs this.

```
Date: 2018-11-21T23:11:46.329Z
Hash: 7e8e5caef82f2472744c
Time: 49734ms
chunk {0} 0.8957953408d810e8d41d.js () 289 kB  [rendered]
chunk {1} common.da59797b17db099fdb34.js (common) 12.2 kB  [rendered]
chunk {2} 2.9a8926d281c14521fa6d.js () 53.1 kB  [rendered]
chunk {3} runtime.ce473be8ddfdcc17bf31.js (runtime) 2.44 kB [entry] [rendered]
chunk {4} 4.b811331f0ef46a22fb16.js () 25.7 kB  [rendered]
chunk {5} main.b323c1196adabc5f8320.js (main) 260 kB [initial] [rendered]
chunk {6} polyfills.f94431c5bdd5445683bd.js (polyfills) 101 kB [initial] [rendered]
chunk {7} styles.8beeb01da5a3bfe76152.css (styles) 118 kB [initial] [rendered]
chunk {8} 8.6968e49883b718cdc73a.js () 296 kB  [rendered]
chunk {9} 9.c6941a7af39ab57ed430.js () 69.4 kB  [rendered]
chunk {10} 10.7a9a0092d4b727102b8b.js () 135 kB  [rendered]
chunk {11} 11.944a9f6e86d399f75f1c.js () 179 kB  [rendered]
chunk {12} 12.e772fcb4fd92f526f69b.js () 548 kB  [rendered]
chunk {13} vendor.9c8e936e40e36ba74817.js (vendor) 1.77 MB [initial] [rendered]

ERROR in /Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@nrwl/nx/esm5/src/data-persistence.js
Module build failed (from /Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
Error: Debug Failure. False expression.
    at Object.assertDefined (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:4507:13)
    at getJSDocHost (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:10547:25)
    at getHostSignatureFromJSDoc (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:10533:46)
    at Object.getParameterSymbolFromJSDoc (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:10524:20)
    at checkJSDocParameterTag (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:47154:21)
    at checkSourceElement (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:49806:28)
    at Object.forEach (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:1792:30)
    at checkSourceElement (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:49738:24)
    at Object.forEach (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:1792:30)
    at checkBlock (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:47525:20)
    at checkSourceElement (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:49831:28)
    at checkIfStatement (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:47912:13)
    at checkSourceElement (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:49837:28)
    at Object.forEach (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:1792:30)
    at checkSourceFileWorker (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:50023:20)
    at checkSourceFile (/Users/name_of_user/Desktop/projects_folder/project_name/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:49991:13)
```

**Comment by FrozenPandaz** [comment]
If you could provide a repro, I would know for sure, but you can try this:

Please try to update your `@angular-devkit/build-angular to `~0.10.0`.

**Comment by RobinPel** [comment]
We had the same issue. It is solved by updating @angular-devkit/build-angular, as @FrozenPandaz mentioned.

**Comment by juristr** [comment]
Same 👍 upgrading `@angular-devkit/build-angular` fixes the issue. For some reason that wasn't upgraded automatically with the `yarn update`

**Comment by lexcaraig** [comment]
Got it @FrozenPandaz Thanks!
