### ISSUE TITLE
affected:dep-graph throw error

### ISSUE THREAD

**Issue by xmlking** [nrwl/nx#920]
`npm run affected:dep-graph -- --uncommitted`
 
## Expected Behavior

The affected:dep-graph commands should  open the browser to show the graph.

## Current Behavior
Throws error.

This command was working before. 

### Workaround
`npm run affected -- --target dep-graph --uncommitted`
 
## Failure Information (for bugs)

```
> ngx-starter-kit@1.2.0 affected:dep-graph /Developer/Work/SPA/ngx-starter-kit
> nx affected:dep-graph "--uncommitted"

/Developer/Work/SPA/ngx-starter-kit/node_modules/@nrwl/schematics/node_modules/yargs/yargs.js:1133
      else throw err
           ^

Error: Unrecognized file extension. Supported extensions are "json", "html", and "dot"
    at extractDataFromJson (/Developer/Work/SPA/ngx-starter-kit/node_modules/@nrwl/schematics/src/command-line/dep-graph.js:238:19)
    at Object.generateGraph (/Developer/Work/SPA/ngx-starter-kit/node_modules/@nrwl/schematics/src/command-line/dep-graph.js:245:15)
    at Object.affected (/Developer/Work/SPA/ngx-starter-kit/node_modules/@nrwl/schematics/src/command-line/affected.js:116:25)
    at Object.handler (/Developer/Work/SPA/ngx-starter-kit/node_modules/@nrwl/schematics/src/command-line/nx.js:44:23)
    at Object.runCommand (/Developer/Work/SPA/ngx-starter-kit/node_modules/@nrwl/schematics/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Developer/Work/SPA/ngx-starter-kit/node_modules/@nrwl/schematics/node_modules/yargs/yargs.js:1046:30)
    at Object.get [as argv] (/Developer/Work/SPA/ngx-starter-kit/node_modules/@nrwl/schematics/node_modules/yargs/yargs.js:989:21)
    at Object.<anonymous> (/Developer/Work/SPA/ngx-starter-kit/node_modules/@nrwl/schematics/src/command-line/nx.js:71:21)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-starter-kit@1.2.0 affected:dep-graph: `nx affected:dep-graph "--uncommitted"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngx-starter-kit@1.2.0 affected:dep-graph script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Context

Please provide any relevant information about your setup:

* version of Nx 7.1.0
```
Angular CLI: 7.1.0-rc.0
Node: 11.1.0
OS: darwin x64
Angular: 7.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.0-rc.0
@angular-devkit/build-angular      0.11.0-rc.0
@angular-devkit/build-ng-packagr   0.11.0-rc.0
@angular-devkit/build-optimizer    0.11.0-rc.0
@angular-devkit/build-webpack      0.11.0-rc.0
@angular-devkit/core               7.1.0-rc.0
@angular-devkit/schematics         7.1.0-rc.0
@angular/cli                       7.1.0-rc.0
@angular/flex-layout               7.0.0-beta.19
@angular/pwa                       0.11.0-rc.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.0-rc.0
@schematics/angular                7.1.0-rc.0
@schematics/update                 0.11.0-rc.0
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1
```
**A minimal reproduce scenario using allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**
https://github.com/xmlking/ngx-starter-kit

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by markgoho** [comment]
Getting the same error. If it persists, I'll open a new bug.
