### ISSUE TITLE
Update migrations on 13.8.4 were not picked up

### ISSUE THREAD

**Issue by diegovilar** [nrwl/nx#9211]
It seems that updating to 13.8.4 didn't lined up the migrations needed:

![image](https://user-images.githubusercontent.com/759416/156891029-bf3d1a3a-7024-4608-aed7-c21c363ab0be.png)

## Current Behavior
After updating to 13.8.4, projects using executors `@nrwl/node:package`, `@nrwl/node:build` and `@nrwl/node:execute` fail to build/run.

## Expected Behavior
Such projects should have been migrated to use the new executors after #9086 and thus should build/run correctly

## Steps to Reproduce

1. Have libraries that use the cited executors
2. Migrate to Nx 13.8.4
3. Note that there is no migrations.json created and that projects keep referring to the old executors
4. Try to run/build projects of item 1

### Failure Logs
```
Error: Unable to resolve @nrwl/node:package.
Cannot find executor 'package' in /home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+node@13.8.4_5ecac316e76ba9ad04ea759449f7c978/node_modules/@nrwl/node/executors.json.
    at Workspaces.readExecutor (/home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+tao@13.8.4/node_modules/@nrwl/tao/src/shared/workspace.js:92:19)
    at getExecutorForTask (/home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+workspace@13.8.4_269c61067e951242bf0108f160295560/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:135:22)
    at getCustomHasher (/home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+workspace@13.8.4_269c61067e951242bf0108f160295560/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:25)
    at TasksSchedule.<anonymous> (/home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+workspace@13.8.4_269c61067e951242bf0108f160295560/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at /home/diego/dev/3t/mono/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home/diego/dev/3t/mono/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:113:16)
    at TasksSchedule.hashTask (/home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+workspace@13.8.4_269c61067e951242bf0108f160295560/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:113:38)
    at TasksSchedule.<anonymous> (/home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+workspace@13.8.4_269c61067e951242bf0108f160295560/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:58:24)
Unexpected error:
Error: Unable to load hasher for task "plugins-3tecnos-nx-plugin:build"
    at getCustomHasher (/home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+workspace@13.8.4_269c61067e951242bf0108f160295560/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:145:15)
    at TasksSchedule.<anonymous> (/home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+workspace@13.8.4_269c61067e951242bf0108f160295560/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at /home/diego/dev/3t/mono/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home/diego/dev/3t/mono/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:113:16)
    at TasksSchedule.hashTask (/home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+workspace@13.8.4_269c61067e951242bf0108f160295560/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:113:38)
    at TasksSchedule.<anonymous> (/home/diego/dev/3t/mono/node_modules/.pnpm/@nrwl+workspace@13.8.4_269c61067e951242bf0108f160295560/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:58:24)
    at Generator.next (<anonymous>)
    at /home/diego/dev/3t/mono/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.js:117:75
```

### Environment
````
Node : 14.18.1
OS   : linux x64
pnpm : 6.32.2

nx : 13.8.4
@nrwl/angular : undefined
@nrwl/cli : 13.8.4
@nrwl/cypress : 13.8.4
@nrwl/detox : undefined
@nrwl/devkit : 13.8.4
@nrwl/eslint-plugin-nx : 13.8.4
@nrwl/express : 13.8.4
@nrwl/jest : 13.8.4
@nrwl/js : 13.8.4
@nrwl/linter : 13.8.4
@nrwl/nest : undefined
@nrwl/next : undefined
@nrwl/node : 13.8.4
@nrwl/nx-cloud : 13.1.6
@nrwl/react : 13.8.4
@nrwl/react-native : undefined
@nrwl/schematics : undefined
@nrwl/storybook : 13.8.4
@nrwl/tao : 13.8.4
@nrwl/web : 13.8.4
@nrwl/workspace : 13.8.4
typescript : 4.5.5
rxjs : 7.4.0
---------------------------------------
Community plugins:
     @nrwl/nx-plugin: 13.8.4
     nx-stylelint: 13.2.0
````

**Comment by samuelfernandez** [comment]
Just releasing a new minor version 13.9.0 can solve this problem

**Comment by diegovilar** [comment]
> Just releasing a new minor version 13.9.0 can solve this problem

Cool, I'll try it as soon as you publish it

**Comment by nartc** [comment]
@diegovilar Sorry for this inconvenience. The next patch version (13.8.5) will contain the migration for this.

**Comment by diegovilar** [comment]
> @diegovilar Sorry for this inconvenience. The next patch version (13.8.5) will contain the migration for this.

@nartc Don't sweat it. Happy to help 👍
