### ISSUE TITLE
nx migrate latest reports a wrong node version detected

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#9221]
## Current Behavior
When trying to update the framework, the process detects the wrong node version and fails.

I've had node version 14.16.0, and I've updated it to 16.14.0.
![image](https://user-images.githubusercontent.com/77624664/157062036-e86f005e-c1f3-4125-9900-3a87331ca692.png)

```ts
λ npm config list
; node bin location = C:\Users\@@@\AppData\Local\Volta\tools\image\node\16.14.0\node.exe
; cwd = C:\@@@
; HOME = C:\Users\@@@
; Run `npm config ls -l` to show all defaults.
```

## Expected Behavior
The migration should recognize the correct node version.

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/77624664/157059891-ea8d92bb-81eb-4cc2-92d4-39e27cee3f70.png)

### Failure Logs

```ts
λ nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching prettier@^2.5.1
Fetching @nrwl/cli@13.8.4
Fetching @nrwl/cypress@13.8.4
Fetching @nrwl/eslint-plugin-nx@13.8.4
Fetching @nrwl/jest@13.8.4
Fetching @nrwl/react@13.8.4
Fetching @nrwl/storybook@13.8.4
Fetching @nrwl/tao@13.8.4
Fetching @nrwl/web@13.8.4
Fetching jest@27.2.3
Fetching @types/jest@27.0.2
Fetching ts-jest@27.0.5
Fetching babel-jest@27.2.3
Fetching @testing-library/react@12.1.2
Fetching @types/react@17.0.30
Fetching @types/react-dom@17.0.9
Fetching @types/react-is@17.0.2
Fetching styled-components@5.3.3
Fetching @types/styled-components@5.1.15
Fetching react-router-dom@5.3.0
Fetching @types/react-router-dom@5.3.1
Fetching @testing-library/react-hooks@7.0.2
Fetching eslint-plugin-import@2.25.2
Fetching eslint-plugin-react@7.26.1
Fetching eslint-plugin-react-hooks@4.3.0
Fetching @storybook/react@~6.4.5
Fetching @storybook/addon-essentials@~6.4.5

 ERROR  The migrate command failed.

Command failed: yarn add -W @nrwl/eslint-plugin-nx@13.8.4
error @typescript-eslint/experimental-utils@5.10.2: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.16.0"
error Found incompatible module.

C:\@@@\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\@@@\AppData\Local\Temp\tmp-29300-7jpGCWW5xvJq\node_modules\.bin\tao migrate latest
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (C:\@@@\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:97:25)
    at Object.runCommand (C:\@@@\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\@@@\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\@@@\node_modules\@nrwl\workspace\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\@@@\node_modules\@nrwl\cli\lib\init-local.js:25:79)
    at Object.<anonymous> (C:\@@@\node_modules\@nrwl\cli\bin\nx.js:43:18)
    at Module._compile (C:\Users\@@@\AppData\Local\Volta\tools\image\packages\nx\lib\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 25032,
  stdout: null,
  stderr: null
}
```
### Environment

Also, in the report, NX is picking up a wrong node version.
```
λ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : win32 x64
  yarn : 3.0.2

  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by AgentEnder** [comment]
`nx report` looks at `process.versions.node`, which is populated by the node runtime. If it states a certain version, that **_is_** what is running, even if it may not be what you intended to be running. Somehow it sounds like your node version from running `node` doesn't match up with what is running when you execute Nx commands.

Is Nx installed globally in your case? If so, try removing it and running Nx through `npx`, `yarn`, or `pnpx`

**Comment by nemonemi** [comment]
That looks to be the problem. It works when I'm using it through `yarn`. 

However, I believe the global NX package has a bug. I have reverted my node version to the old one, 14.16.0, and reinstalled NX globally. Now when I run the `nx report` command it reports the 16.14.0 version, incorrect again.
![image](https://user-images.githubusercontent.com/77624664/157437404-f90facdd-74bb-4106-8bde-e02c5748da3b.png)

**Comment by nemonemi** [comment]
I propose closing this ticket.

Feel free to re-open it, should the need arise.
