### ISSUE TITLE
Error: Unable to resolve @nrwl/node:package. nx v13.8.5

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#9268]
## Current Behavior

Failed to build node packages
See the error trace below.

## Expected Behavior

To be able to run build command with run-many.

## Steps to Reproduce

```
npx create-nx-workspace nx-cache
Need to install the following packages:
  create-nx-workspace
Ok to proceed? (y) y
✔ What to create in the new workspace · apps
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

cd nx-cache

yarn add @nrwl/node

yarn nx g @nrwl/node:app nx-api
yarn nx g @nrwl/node:lib liba-api --buildable
yarn nx g @nrwl/node:lib libb-api --buildable
yarn nx g @nrwl/node:lib libc-api --buildable

yarn nx run-many --target build --all

yarn run v1.22.11
$ /Users/wizardnet972/code/nx-cache/node_modules/.bin/nx run-many --target build --all

Error: Unable to resolve @nrwl/node:package.
Cannot find executor 'package' in /Users/wizardnet972/code/nx-cache/node_modules/@nrwl/node/executors.json.
    at Workspaces.readExecutor (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/tao/src/shared/workspace.js:92:19)
    at getExecutorForTask (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:135:22)
    at getCustomHasher (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:25)
    at TasksSchedule.<anonymous> (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at /Users/wizardnet972/code/nx-cache/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/wizardnet972/code/nx-cache/node_modules/tslib/tslib.js:113:16)
    at TasksSchedule.hashTask (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:113:38)
    at TasksSchedule.<anonymous> (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:58:24)
Unexpected error:
Error: Unable to load hasher for task "liba-api:build"
    at getCustomHasher (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:145:15)
    at TasksSchedule.<anonymous> (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at /Users/wizardnet972/code/nx-cache/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/wizardnet972/code/nx-cache/node_modules/tslib/tslib.js:113:16)
    at TasksSchedule.hashTask (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:113:38)
    at TasksSchedule.<anonymous> (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:58:24)
    at Generator.next (<anonymous>)
    at /Users/wizardnet972/code/nx-cache/node_modules/tslib/tslib.js:117:75
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Failure Logs

```

Error: Unable to resolve @nrwl/node:package.
Cannot find executor 'package' in /Users/wizardnet972/code/nx-cache/node_modules/@nrwl/node/executors.json.
    at Workspaces.readExecutor (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/tao/src/shared/workspace.js:92:19)
    at getExecutorForTask (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:135:22)
    at getCustomHasher (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:25)
    at TasksSchedule.<anonymous> (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at /Users/wizardnet972/code/nx-cache/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/wizardnet972/code/nx-cache/node_modules/tslib/tslib.js:113:16)
    at TasksSchedule.hashTask (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:113:38)
    at TasksSchedule.<anonymous> (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:58:24)
Unexpected error:
Error: Unable to load hasher for task "liba-api:build"
    at getCustomHasher (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:145:15)
    at TasksSchedule.<anonymous> (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at /Users/wizardnet972/code/nx-cache/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/wizardnet972/code/nx-cache/node_modules/tslib/tslib.js:113:16)
    at TasksSchedule.hashTask (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:113:38)
    at TasksSchedule.<anonymous> (/Users/wizardnet972/code/nx-cache/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:58:24)
    at Generator.next (<anonymous>)
    at /Users/wizardnet972/code/nx-cache/node_modules/tslib/tslib.js:117:75
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### Environment

```

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin arm64
   yarn : 1.22.11

   nx : 13.8.5
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.5
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.5
   @nrwl/eslint-plugin-nx : 13.8.5
   @nrwl/express : undefined
   @nrwl/jest : 13.8.5
   @nrwl/js : 13.8.5
   @nrwl/linter : 13.8.5
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.8.5
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.5
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.5
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

(node:63102) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/wizardnet972/code/nx-cache/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
✨  Done in 0.87s.
```

**Comment by jberrydev** [comment]
This seems to be back in 13.9.4

**Comment by AgentEnder** [comment]
The equivalent for @nrwl/node: package would be @nrwl/js:tsc, since package didn't bundle in the past.
