### ISSUE TITLE
Storybook won't build if component imports from another monorepo library.

### ISSUE THREAD

**Issue by adonaicandido** [nrwl/nx#9372]
## Current Behavior
When I have a react-library with storybook setup, if the component in any story imports anything from other library in the monorepo, it won't build.

## Expected Behavior
Run normally, as if the external import was internal.

## Steps to Reproduce
1. [Clone this repo](https://github.com/adonaicandido/nx-storybook-stitches-bug);
2. `npx nx storybook site-ui`

### Failure Logs

```
> nx run site-ui:storybook

info => Loading presets
info => Loading Nrwl React Storybook preset from "@nrwl/react/plugins/storybook"
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
<i> [webpack-dev-middleware] wait until bundle finished
<i> [webpack-dev-middleware] wait until bundle finished: /__webpack_hmr
assets by chunk 5.09 MiB (id hint: vendors)
  assets by status 4.7 MiB [big]
    asset vendors-node_modules_storybook_addon-actions_dist_esm_register_js-node_modules_storybook_addo-93ef89.manager.bundle.js 4.33 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_OverlayScrollbars_js.manager.bundle.js 372 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_syntaxhighlighter_syntaxhighlighter_js.manager.bundle.js 197 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_tooltip_WithTooltip_js.manager.bundle.js 115 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_controls_Color_js.manager.bundle.js 72.6 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_ScrollArea_GlobalScrollAreaStyles_js.manager.bundle.js 15.6 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.1 KiB [emitted] (name: runtime~main)
asset index.html 2.65 KiB [emitted]
asset main.manager.bundle.js 1.49 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.28 KiB [emitted]
Entrypoint main [big] 4.35 MiB = runtime~main.manager.bundle.js 14.1 KiB vendors-node_modules_storybook_addon-actions_dist_esm_register_js-node_modules_storybook_addo-93ef89.manager.bundle.js 4.33 MiB main.manager.bundle.js 1.49 KiB
orphan modules 1.54 MiB [orphan] 326 modules
runtime modules 8.68 KiB 14 modules
javascript modules 4.54 MiB 908 modules
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]
manager (webpack 5.70.0) compiled successfully in 16185 ms
webpack built preview 7aeb05a2b787e0753a0a in 21649ms
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/adonai/repos/testrepo/libs/site/styles/src/lib/stitches.config.ts: Unexpected token, expected "from" (2:12)

  1 | import { createStitches } from "@stitches/core"
> 2 | import type { PropertyValue } from "@stitches/core"
    |             ^
  3 |
  4 | export const {
  5 |   css,
    at instantiate (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:358:12)
    at Parser.raise (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:3334:19)
    at Parser.unexpected (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:3372:16)
    at Parser.expectContextual (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:3972:18)
    at Parser.parseImport (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:16175:12)
    at Parser.parseStatementContent (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:14666:27)
    at Parser.parseStatement (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:14556:17)
    at Parser.parseBlockOrModuleBlockBody (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:15195:25)
    at Parser.parseBlockBody (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:15186:10)
    at Parser.parseProgram (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:14474:10)
    at Parser.parseTopLevel (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:14461:25)
    at Parser.parse (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:16420:10)
    at parse (/home/adonai/repos/testrepo/node_modules/@babel/parser/lib/index.js:16472:38)
    at parser (/home/adonai/repos/testrepo/node_modules/@babel/core/lib/parser/index.js:52:34)
    at parser.next (<anonymous>)
    at processResult (/home/adonai/repos/testrepo/node_modules/webpack/lib/NormalModule.js:758:19)
    at /home/adonai/repos/testrepo/node_modules/webpack/lib/NormalModule.js:860:5
    at /home/adonai/repos/testrepo/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/adonai/repos/testrepo/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/adonai/repos/testrepo/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/adonai/repos/testrepo/node_modules/babel-loader/lib/index.js:59:103


          Broken build, fix the error above.
          You may need to refresh the browser.
        

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "site-ui:storybook" failed

   Failed tasks:
   
   - site-ui:storybook
   
   Hint: run the command with --verbose for more details.
```

**Comment by AgentEnder** [comment]
@adonaicandido It looks like the error isn't hit until line 2 in your error message, is it coming from the `import type ...` statement? What happens if you remove `type`?

**Comment by AgentEnder** [comment]
Also, what's the output of `nx report`?
