### ISSUE TITLE
[bug] js: rootDir checks work differently after migrating to @nrwl/js:tsc from @nrwl/node:package

### ISSUE THREAD

**Issue by DominikPieper** [nrwl/nx#9385]
Good morning,

we've a strange problem after the migration script changed `"executor": "@nrwl/node:package",`to `"executor": "@nrwl/js:tsc",`.

We have the `@nxext/svelte`plugin which imports the init generator from `@nxext/vitest`.
It's just called after imported with the full package import (`import { vitestInitGenerator } from '@nxext/vitest';`).

If I run the build step after the migration I get an error like:
```
Error: dist/packages/vitest/src/generators/init/init.ts:9:42 - error TS6059: File '/Users/dominikpieper/Projects/angular/nxext/dist/packages/vitest/src/utils/versions.ts' is not under 'rootDir' 'packages/svelte'. 'rootDir' is expected to contain all source files.
```

This is just an example, I get this error for all plugins that import something from the same repo. All nxext plugins that import from another plugin within the repo fails with errors like that.

The plugins without dependencies inside the same repo are working fine.

## Current Behavior
The build fails. (worked before with @nrwl/node:package)

## Expected Behavior
The build works again.

## Steps to Reproduce
Create a repo with two nx plugins where one import ech other.

Here my PR: https://github.com/nxext/nx-extensions/pull/562/files
And the build logs: https://github.com/nxext/nx-extensions/runs/5596574166?check_suite_focus=true

### Failure Logs
```
nx run svelte:build

Compiling TypeScript files for project "svelte"...
dist/packages/vitest/src/generators/init/init.ts:9:42 - error TS6059: File '/Users/dominikpieper/Projects/angular/nxext/dist/packages/vitest/src/utils/versions.ts' is not under 'rootDir' 'packages/svelte'. 'rootDir' is expected to contain all source files.

9 import { c8Version, vitestVersion } from '../../utils/versions';
                                           ~~~~~~~~~~~~~~~~~~~~~~

/Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/workspace/src/utilities/typescript/compilation.js:99
        throw new Error(diagnostics);
              ^

Error: dist/packages/vitest/src/generators/init/init.ts:9:42 - error TS6059: File '/Users/dominikpieper/Projects/angular/nxext/dist/packages/vitest/src/utils/versions.ts' is not under 'rootDir' 'packages/svelte'. 'rootDir' is expected to contain all source files.

9 import { c8Version, vitestVersion } from '../../utils/versions';
                                           ~~~~~~~~~~~~~~~~~~~~~~

    at createProgram (/Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/workspace/src/utilities/typescript/compilation.js:99:15)
    at compileTypeScript (/Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/workspace/src/utilities/typescript/compilation.js:15:12)
    at /Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/js/src/utils/typescript/compile-typescript-files.js:38:73
    at Generator.next (<anonymous>)
    at /Users/dominikpieper/Projects/angular/nxext/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/dominikpieper/Projects/angular/nxext/node_modules/tslib/tslib.js:113:16)
    at /Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/js/src/utils/typescript/compile-typescript-files.js:28:227
    at Object.[Symbol.asyncIterator] (/Users/dominikpieper/Projects/angular/nxext/node_modules/@nrwl/js/src/utils/create-async-iterable/create-async-iteratable.js:11:13)
    at __asyncValues (/Users/dominikpieper/Projects/angular/nxext/node_modules/tslib/tslib.js:241:22)
```

### Environment
```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin x64
   yarn : 1.22.15

   nx : 13.9.2
   @nrwl/angular : 13.9.2
   @nrwl/cypress : 13.9.2
   @nrwl/detox : undefined
   @nrwl/devkit : 13.9.2
   @nrwl/eslint-plugin-nx : 13.9.2
   @nrwl/express : undefined
   @nrwl/jest : 13.9.2
   @nrwl/js : 13.9.2
   @nrwl/linter : 13.9.2
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.9.2
   @nrwl/nx-cloud : 13.1.6
   @nrwl/nx-plugin : 13.9.2
   @nrwl/react : 13.9.2
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.9.2
   @nrwl/web : 13.9.2
   @nrwl/workspace : 13.9.2
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
```

**Comment by DominikPieper** [comment]
Oh yes, sorry that's a better scope ^^'

**Comment by DominikPieper** [comment]
@AgentEnder I experimented a little and could be that this one is related to the Giora found (in Slack) about the .ts files in dist. If I remove the .ts files of the dependencies it's all fine again (at least for my short tryout)

**Comment by DominikPieper** [comment]
Related to #9283. The workaround from there fixed it.
