### ISSUE TITLE
Jest - react native - Cannot find module 'babel-preset-react-native'

### ISSUE THREAD

**Issue by saravanakumargn** [nrwl/nx#9416]
## Current Behavior

Jest testing failed with `'react-native-elements'`

```

    Cannot find module 'babel-preset-react-native'
    Require stack:
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/config/files/plugins.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/config/files/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/InlineSnapshots.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/State.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-runtime/build/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@jest/core/build/cli/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@jest/core/build/jest.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest/build/jest.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@nrwl/jest/src/executors/jest/jest.impl.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/shared/workspace.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/commands/run.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/cli/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/cli/run-cli.js
    - If you want to resolve "react-native", use "module:react-native"

    Require stack:
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/config/files/plugins.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/config/files/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/InlineSnapshots.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/State.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-runtime/build/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@jest/core/build/cli/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@jest/core/build/jest.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest/build/jest.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@nrwl/jest/src/executors/jest/jest.impl.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/shared/workspace.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/commands/run.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/cli/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/cli/run-cli.js

      at tryRequireResolve (../../node_modules/@babel/core/lib/config/files/plugins.js:157:9)
      at resolveStandardizedNameForRequrie (../../node_modules/@babel/core/lib/config/files/plugins.js:195:19)
      at sync (../../node_modules/@babel/core/lib/config/files/plugins.js:224:12)
      at sync (../../node_modules/gensync/index.js:182:19)
      at ../../node_modules/gensync/index.js:210:24
      at resolvePreset (../../node_modules/@babel/core/lib/config/files/plugins.js:87:17)
          at resolvePreset.next (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.624 s
Ran all test suites.
```

## Steps to Reproduce

1. `npx create-nx-workspace happynrwl`
```
npx: installed 48 in 9.067s
✔ What to create in the new workspace · react-native
✔ Application name                    · mobile
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

 >  NX   Nx is creating your v13.9.3 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace.
```
2. `nx test mobile`
```

> nx run mobile:test

 PASS   mobile  apps/mobile/src/app/App.spec.tsx (6.989 s)
  ✓ renders correctly (4751 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        7.975 s
Ran all test suites.

 ————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target test for project mobile (10s)
```
3. `npm install react-native-elements react-native-safe-area-context`
4. 
```
import { Button } from 'react-native-elements';

<Button
  title="Solid Button"
/>
```
5. `nx test mobile`
```

> nx run mobile:test

 FAIL   mobile  apps/mobile/src/app/App.spec.tsx
  ● Test suite failed to run

    Cannot find module 'babel-preset-react-native'
    Require stack:
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/config/files/plugins.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/config/files/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/InlineSnapshots.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/State.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-runtime/build/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@jest/core/build/cli/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@jest/core/build/jest.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest/build/jest.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@nrwl/jest/src/executors/jest/jest.impl.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/shared/workspace.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/commands/run.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/cli/index.js
    - /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/cli/run-cli.js
    - If you want to resolve "react-native", use "module:react-native"

    Require stack:
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/config/files/plugins.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/config/files/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@babel/core/lib/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/InlineSnapshots.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/State.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-snapshot/build/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest-runtime/build/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@jest/core/build/cli/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@jest/core/build/jest.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/jest/build/jest.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/@nrwl/jest/src/executors/jest/jest.impl.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/shared/workspace.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/commands/run.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/cli/index.js
      /Users/saravanakumar/My/code/ReactNative/happynrwl/node_modules/nx/src/cli/run-cli.js

      at tryRequireResolve (../../node_modules/@babel/core/lib/config/files/plugins.js:157:9)
      at resolveStandardizedNameForRequrie (../../node_modules/@babel/core/lib/config/files/plugins.js:195:19)
      at sync (../../node_modules/@babel/core/lib/config/files/plugins.js:224:12)
      at sync (../../node_modules/gensync/index.js:182:19)
      at ../../node_modules/gensync/index.js:210:24
      at resolvePreset (../../node_modules/@babel/core/lib/config/files/plugins.js:87:17)
          at resolvePreset.next (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.624 s
Ran all test suites.

 ————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test for project mobile (6s)

    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```

 >  NX   Report complete - copy this into the issue template

   Node : 14.17.0
   OS   : darwin x64
   npm  : 6.14.16

   nx : 13.9.3
   @nrwl/angular : undefined
   @nrwl/cypress : 13.9.3
   @nrwl/detox : 13.9.3
   @nrwl/devkit : 13.9.3
   @nrwl/eslint-plugin-nx : 13.9.3
   @nrwl/express : undefined
   @nrwl/jest : 13.9.3
   @nrwl/js : 13.9.3
   @nrwl/linter : 13.9.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/nx-plugin : undefined
   @nrwl/react : 13.9.3
   @nrwl/react-native : 13.9.3
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.9.3
   @nrwl/web : 13.9.3
   @nrwl/workspace : 13.9.3
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by diginikkari** [comment]
This problem seems to be related to change from NX 13.8.1 -> 13.8.2. Specially the change from "react-native": "0.66.4" -> "0.67.2". I tried to read change log for react-native, but didn't figure out what change affected this.

**Comment by diginikkari** [comment]
That is not the only explanation. With same package versions it is working in workspace created with `npx react-native init MyApp --template react-native-template-typescript`. It has something to do with either transforming or metro config. I just can't figure it out. Unfortunately my babel knowledge is not efficient for this. 

Here is bear minimum repo created with [react-native init](https://github.com/diginikkari/ReactNativeRepoIssue9416)
Here failing bear minimum repo created with [NX](https://github.com/diginikkari/NXRepoIssue9416)

**Comment by diginikkari** [comment]
@xiongemi I was able to get tests working by changing transform from: `'\\.(js|ts|tsx)$': require.resolve('react-native/jest/preprocessor.js'),` to `'^.+\\.(js|ts|tsx)$': ['babel-jest', { cwd: __dirname }],` and changing from .babelrc to babel.config.js with:
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};

```
I updated my bear minimum NX repo [NX](https://github.com/diginikkari/NXRepoIssue9416) with commit fixing the setup.
It seems that one should not use `react-native/jest/preprocessor.js` directly. At least that is now mentioned in latest [react-native repo](https://github.com/facebook/react-native/commit/c1e9aa9a272aed3cba60c4aeff783eeb8bffce68). So probably correct way is to use babel-jest and configure it so that it will use config form project directory. By default it seem to ignore config from project directory.
