### ISSUE TITLE
npm install fails during create-nx-workspace

### ISSUE THREAD

**Issue by undunion** [nrwl/nx#947]
i run 
```js 
npm install -g @angular/cli @nrwl/schematics
create-nx-workspace workspace
```

the error like this 

```js
ng new "workspace" --collection=@nrwl/schematics
? What is the npm scope you would like to use for your Nx Workspace? aa
? Which Package Manager would you like to use for your workspace? npm
CREATE workspace/.prettierignore (57 bytes)
CREATE workspace/.prettierrc (25 bytes)
CREATE workspace/angular.json (307 bytes)
CREATE workspace/karma.conf.js (1012 bytes)
CREATE workspace/nx.json (194 bytes)
CREATE workspace/package.json (2520 bytes)
CREATE workspace/README.md (1861 bytes)
CREATE workspace/tsconfig.json (423 bytes)
CREATE workspace/tslint.json (2307 bytes)
CREATE workspace/.editorconfig (245 bytes)
CREATE workspace/.gitignore (503 bytes)
CREATE workspace/apps/.gitkeep (1 bytes)
CREATE workspace/libs/.gitkeep (0 bytes)
CREATE workspace/tools/tsconfig.tools.json (254 bytes)
CREATE workspace/tools/schematics/.gitkeep (0 bytes)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
child_process.js:643
    throw err;
    ^

Error: Command failed: C:\Users\ADMINI~1\AppData\Local\Temp\tmp-111283aWCkwe0PoA1\node_modules\.bin\ng new "workspace" --collection=@nrwl/schematics
    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:640:13)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@nrwl\schematics\bin\create-nx-workspace.js:90:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
```

the workspace is created, then

```js
cd workspace 
npm i
ng g app myapp
```
it run success

Angular CLI: 7.1.2
Node: 10.6.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.11.2
@angular-devkit/core         7.1.2
@angular-devkit/schematics   7.1.2
@schematics/angular          7.1.2
@schematics/update           0.11.2
rxjs                         6.3.3
typescript                   3.1.6

**Comment by FrozenPandaz** [comment]
Hm, I'm having trouble reproducing this. What `npm` version is being used? (`npm -v`)

**Comment by vsavkin** [comment]
Closing this. If the problem persists, could you reopen the issue?
