### ISSUE TITLE
Cannot run connect-to-nx-cloud on existing nx workspace

### ISSUE THREAD

**Issue by wkaskie** [nrwl/nx#9688]
## Current Behavior

When running nx connect-to-nx-cloud on an existing workspace, an error is thrown:
```
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.<anonymous> (/project-dir/node_modules/@nrwl/workspace/src/command-line/connect-to-nx-cloud.js:37:36)
    at Generator.next (<anonymous>)
    at /project-dir/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/project-dir/node_modules/tslib/tslib.js:113:16)
    at Object.connectToNxCloudCommand (/project-dir/node_modules/@nrwl/workspace/src/command-line/connect-to-nx-cloud.js:35:20)
    at /project-dir/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:103:249
    at Generator.next (<anonymous>)
    at fulfilled (/project-dir/node_modules/tslib/tslib.js:114:62)
```

## Expected Behavior

I expect to successfully connect to nx cloud.

## Steps to Reproduce

I am running this on legacy angular app that was converted to an Nx workspace.

Nx tools appear to be working otherwise. For example, dep-graph works and when running other commands, the "Nx messages" are displayed.

### Failure Logs

No logs, but the error above should be traceable in the code.

### Environment

The command was run locally.

**Comment by AgentEnder** [comment]
What does `nx report` output?

**Comment by wkaskie** [comment]
Any thoughts?

**Comment by AgentEnder** [comment]
Hmmm, connect-nx-cloud runs

```
npm i -d @nrwl/nx-cloud
nx g @nrwl/nx-cloud:init
```

Do you get an error running those?

**Comment by wkaskie** [comment]
That worked! Thanks!!!
