### ISSUE TITLE
ENOENT: no such file or directory, open '.../apps/first-app/project.json'

### ISSUE THREAD

**Issue by mklueh** [nrwl/nx#9971]
I'm trying to set up an NX project with two Nuxt 3 applications manually, as the third-party Nuxt support plugin [https://github.com/ZachJW34/nx-plus](https://github.com/ZachJW34/nx-plus) does not work for me (failing during setup and no Nuxt 3 support).

**However, NX complains about missing project.json files.**

In my previous NX project I did not need that, but now it seems mandatory. However, the [documentation ](https://nx.dev/configuration/projectjson) sounds like its optional and the package.json is enough.
 
> Projects can be configured in package.json (if you use npm scripts and not Nx executors) and project.json (if you use Nx executors). Both package.json and project.json files are located in each project's folder. Nx merges the two files to get each project's configuration. This guide covers the project.json case.

This is the error I'm getting:

```
nx run first-app:serve:production
nx run [project][:target][:configuration] [_..]

Run a target for a project
(e.g., nx run myapp:serve:production).

You can also use the infix notation to run a target:
(e.g., nx serve myapp --configuration=production)

You can skip the use of Nx cache by using the --skip-nx-cache option.

Options:
      --version        Show version number                                                                                                                                                                                     [boolean]
      --prod           Use the production configuration                                                                                                                                                       [boolean] [default: false]
  -c, --configuration  Target configuration                                                                                                                                                                                     [string]
      --project        Target project                                                                                                                                                                                           [string]

Error: ENOENT: no such file or directory, open '/home/user/workspace/nuxt3-multi-page/apps/first-app/project.json'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at readJsonFile (/home/user/workspace/nuxt3-multi-page/node_modules/nx/src/utils/fileutils.js:21:43)
    at /home/user/workspace/nuxt3-multi-page/node_modules/nx/src/config/workspaces.js:280:61
    at Array.forEach (<anonymous>)
    at inlineProjectConfigurations (/home/user/workspace/nuxt3-multi-page/node_modules/nx/src/config/workspaces.js:277:38)
    at resolveNewFormatWithInlineProjects (/home/user/workspace/nuxt3-multi-page/node_modules/nx/src/config/workspaces.js:273:24)
    at Workspaces.readFromWorkspaceJson (/home/user/workspace/nuxt3-multi-page/node_modules/nx/src/config/workspaces.js:176:16)
    at Workspaces.readWorkspaceConfiguration (/home/user/workspace/nuxt3-multi-page/node_modules/nx/src/config/workspaces.js:57:20)
    at readWorkspaceConfig (/home/user/workspace/nuxt3-multi-page/node_modules/nx/src/project-graph/file-utils.js:99:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/user/workspace/nuxt3-multi-page/apps/first-app/project.json'
}

```

### These are my config files

**package.json**
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.1"
  },
  "nx": {
    "targets": {
      "build": {
        "outputs": [
          "dist/apps/first-app"
        ],
        "dependsOn": [
          {
            "target": "build",
            "projects": "dependencies"
          }
        ]
      },
      "test": {
        "outputs": [],
        "dependsOn": [
          {
            "target": "build",
            "projects": "self"
          }
        ]
      }
    }
  }
}

```

**nx.json**
```
{
  "extends": "@nrwl/workspace/presets/npm.json",
  "npmScope": "nuxt3-multi-page",
  "cli": {
    "defaultCollection": "@nrwl/workspace"
  },
  "affected": {
    "defaultBase": "main"
  },
  "workspaceLayout": {
    "appsDir": "apps",
    "libsDir": "libs"
  },
  "implicitDependencies": {
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    ".eslintrc.json": "*"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e"
        ]
      }
    }
  },
  "targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  }
}

```

**workspace.json**
```
{
  "version": 2,
  "projects": {
    "first-app": "apps/first-app",
    "second-app": "apps/second-app"
  }
}

```

**What am I doing that makes NX require those files and how can I disable the lookup?**

**Comment by AgentEnder** [comment]
If `workspace.json` is present, `project.json` is currently mandatory. With `workspace.json` absent, project inference kicks in to load projects.

**Comment by mklueh** [comment]
I came across an[ example project](https://github.com/vsavkin/large-monorepo/blob/main/workspace.json) on GitHub and adjusted my workspace.json, and now it works without the project.json files:

```
{
  "version": 2,
  "projects": {
  "first-app": {
      "root": "apps/first-app"
    },
    "second-app": {
      "root": "apps/second-app"
    },
  }
}
```

instead of 

```
{
  "version": 2,
  "projects": {
    "first-app": "apps/first-app",
    "second-app": "apps/second-app"
  }
}

```

**Comment by mklueh** [comment]
I'd like to add something to this issue:

I was using a globally installed Nx the whole time, because I did not manage to use "nx.." commands with the local installed version.

Likely, the global version was outdated, leading to this issues.

Now I'm using the local version only with "yarn nx..." and I've removed the global installation
